### ISSUE TITLE
Release GHC-9.10 aware cabal-install

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#10010]
Otherwise there is no way to use `build-type: Custom` packages, like `entropy` or `postgresql-libpq` using bundled `Cabal/-syntax`.

```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.10.2.1 supports 'ghc' version < 9.10): /github/home/.ghcup/ghc/9.10.1/bin/ghc is version 9.10.1
```

```
Error: cabal-3.10.2.0: Could not resolve dependencies:
[__0] trying: postgresql-libpq-0.10.1.0 (user goal)
[__1] next goal: postgresql-libpq:setup.Cabal (dependency of postgresql-libpq)
[__1] rejecting: postgresql-libpq:setup.Cabal-3.12.0.0/installed-be90 (constraint from maximum version of Cabal used by Setup.hs requires <3.12)
```

**Comment by ulysses4ever** [comment]
This is tracked as https://github.com/haskell/cabal/issues/9885

**Comment by andreasabel** [comment]
(Using the other close button (one given semantics: "duplicate") that does not suggest this issue was fixed yet.)

**Comment by ulysses4ever** [comment]
@andreasabel thanks for the correction! Indeed, I keep forgetting about the various modes of closing issues. I blame GH UI but I should learn the lesson one day!
