### ISSUE TITLE
Cabal (the library) advises use of `extensions:` when that field is deprecated

### ISSUE THREAD

**Issue by mpilgrem** [haskell/cabal#10042]
Motivation: https://github.com/commercialhaskell/stack/issues/6589

If a Cabal file uses `ghc-options:` to set language extensions, Cabal (the library) will advise the use of `extensions:` even when `extensions:` has been deprecated in favour of `default-extensions:`.

EDIT: This appears to be true even if the `cabal-version:` specifies a Cabal package format version that no longer supports `extensions:` at all.

**Comment by ulysses4ever** [comment]
That's an oversight. PR fixing it is welcome!

**Comment by mpilgrem** [comment]
I'll try to give the fix some attention in the coming days.
