### ISSUE TITLE
Are we validating `ghc-options` in `.cabal` files?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#10071]
Are we validating `ghc-options` in `.cabal` files? I ask because when looking at #10070, I made a typo and got an odd message.

```
$ cabal init myapp --non-interactive
$ cd myapp
$ cabal build
Resolving dependencies...
Build profile: -w ghc-9.8.2 -O1
In order, the following will be built (use -v for more details):
 - myapp-0.1.0.0 (exe:myapp) (cannot read state cache)
Configuring executable 'myapp' for myapp-0.1.0.0..
Preprocessing executable 'myapp' for myapp-0.1.0.0..
Building executable 'myapp' for myapp-0.1.0.0..
```

Now I make the typo:

```diff
   common warnings
-       ghc-options: -Wall
+       ghc-options: -Wall 02
```

Notice the message `target ‘02’ is not a module name or a source file`:

```
$ cabal build
Resolving dependencies...
Build profile: -w ghc-9.8.2 -O1
In order, the following will be built (use -v for more details):
 - myapp-0.1.0.0 (exe:myapp) (configuration changed)
Configuring executable 'myapp' for myapp-0.1.0.0..
Preprocessing executable 'myapp' for myapp-0.1.0.0..
Building executable 'myapp' for myapp-0.1.0.0..
target ‘02’ is not a module name or a source file
Error: cabal: Failed to build exe:myapp from myapp-0.1.0.0.
```

**Comment by philderbeast** [comment]
All the options start with `-`:

```
$ ghc --show-options > options.txt

$ grep '^[-].*$' options.txt
-package-db
-clear-package-db
-no-global-package-db

...
--abi-hash
-e
--frontend

$ grep '^[^-].*$' options.txt
```

**Comment by ffaf1** [comment]
Could be done in `cabal check`, but it would be better if it done in each path that actually uses the options.

**Comment by adamgundry** [comment]
> All the options start with `-`

But some options take arguments. So this would somehow need to check we're not in one of those cases, which seems difficult in general.

**Comment by philderbeast** [comment]
There's a lot of options but lot of these would not take arguments, would they? All of the extension options `-X*` for instance. It is hard to say whether the `-Wwarn=` and `-Werror=` options are taking arguments or whether their option name verbatim includes `=`.

```
$ ghc --show-options | wc -l
1662

$ ghc --show-options
...
-Werror=incomplete-export-warnings
-Werror=inconsistent-flags
-Wwarn=duplicate-exports
-Wwarn=duplicate-constraints
...
```

**Comment by sol** [comment]
Is this really the responsibility of `cabal`?

May I suggest close this as "won't fix"?

**Comment by geekosaur** [comment]
Not only is it not our responsibility, but it could make it difficult to impossible to use cabal with a ghc it doesn't know about.

**Comment by sol** [comment]
Yes, exactly, same thought here.

**Comment by Bodigrim** [comment]
Cabal does validate language extensions, which technically is a subset of GHC options. Which is both annoying if you need to deal with brand new extensions from a fresh GHC release, but also somewhat useful because it allows solver to refuse compilation against unsupported Haskell compilers. 

(Not arguing for any particular resolution, just saying)

**Comment by geekosaur** [comment]
Yes, and we've had the discussion about getting them from the compiler (`ghc --show-options`) instead of hardcoding them before; I don't recall why we decided to continue hardcoding them.

**Comment by sol** [comment]
@Bodigrim you could query language extensions from the `ghc` that is actually used, which then I think could work. However, I doubt this is feasible for options in general.

**Comment by geekosaur** [comment]
We know language extensions don't take options. We don't know it for general options, so `--show-options` doesn't help us.

**Comment by sol** [comment]
Yes, exactly, same thought here.

**Comment by andreabedini** [comment]
> Cabal does validate language extensions, which technically is a subset of GHC options.

@Bodigrim FWIW I am all for reducing the coupling between Cabal and GHC. I find the current situation problematic.

**Comment by ulysses4ever** [comment]
If GHC exposed such interface as extensions, flags etc. in a machine-readable way, we could check them dynamically. The current "static" approach looks problematic to me too.

**Comment by sol** [comment]
Giving it more thought, I think even the dynamic approach is problematic.

A cabal file is a package specification that can be built with possibly a range of different compilers (say a range of different GHC versions). At the point you invoke `cabal check` you have commonly only one such compiler (say one specific  version of GHC) available.  So the best thing `cabal check` could do is validate the  package specification against that specific compiler. But it could not validate `ghc-options` in general, e.g. considering conditional sections etc.

> I don't recall why we decided to continue hardcoding them.

@geekosaur I imagine this may also be the reason why you decided to continue to hard code language extensions.

**Comment by ulysses4ever** [comment]
@sol agree. I first thought that we could check it at package build time, but that happens in the package client machines, and the clients won't be interested in that information. So, yes, I think we're checking too much.

**Comment by andreabedini** [comment]
A good UX improvement would be to prefix (and perhaps colorise) the source of the messages. E.g.
```
Building executable 'myapp' for myapp-0.1.0.0..
[GHC] target ‘02’ is not a module name or a source file
Error: cabal: Failed to build exe:myapp from myapp-0.1.0.0.
```
We probably already have an issue about this.
