### ISSUE TITLE
Changelog for Cabal 3.12 is missing mention of error codes

### ISSUE THREAD

**Issue by BinderDavid** [haskell/cabal#10086]
I mentioned this in the matrix channel and was prompted to open an issue:

The prerelease changelogs for cabal 3.12 do not mention that cabal now emits unique error codes in the style `Cabal-xxxxx`. This should be changed in view of #9885

**Comment by geekosaur** [comment]
I'm working on the 3.12.1.0 changelogs.

The `Cabal` library also had error codes added, which are not noted in the 3.12.0.0 changelog. Should I retroactively add it there, or add it to the 3.12.1.0 changelog with a note that they actually appeared in 3.12.0.0?

**Comment by ulysses4ever** [comment]
My proposal would be to do both:

- fix notes for Cabal-3.12.0.0
- put it into notes for cabal-install-3.12.1.0

**Comment by Mikolaj** [comment]
BTW, if the error codes are not in the changelog, it's probably because of this lower case cabal here: https://github.com/haskell/cabal/pull/9018/files#diff-af2626c83a197fa0d9bc54cd3aa108406e5a74dea0418e0f4159c5b3b36bc202

PR welcome that makes the changelog.d tool maintained by @fgaz ignore case (and another PR that makes it actually check for known packages and fail so that we can catch this in CI, as suggested by @geekosaur).

**Comment by ulysses4ever** [comment]
I don't like the idea of making the tool case insensitive to the package names. I'd prefer there was a way to specify known packages in the config file, so that the tool fails when it sees something unknown.

**Comment by geekosaur** [comment]
That's actually my current plan; I intend to look into it after the release.

**Comment by geekosaur** [comment]
Interesting, this didn't get autoclosed. The changelog for 3.12.1.0 mentions the new error codes and the fact that it was actually in 3.12.0.0, and retrofits it into the 3.12.0.0 changelog.

**Comment by geekosaur** [comment]
https://codeberg.org/fgaz/changelog-d/pulls/13 fwiw
Tested locally, works unchanged if I don't add packages to `changelog.d/config`, correctly reports problems with command line-specified packages and packages in `changelog.d` files if I do add them.
