### ISSUE TITLE
cabal install thinks dangling symlink ==  already exists

### ISSUE THREAD

**Issue by kowey** [haskell/cabal#1009]
This sort of situation can come up quite easily if you're using sandbox build environments and working with multiple copies of a particular executable.

Basically if your .cabal/bin/foo points to some non-existing location (from a previous install which was cleaned away), the next time you try to install that package, cabal will fail and complain it already exists. If the symlink points to a live file, cabal-install is much smarter; it tells you that the link already exists and doesn't do anything. Here, I think Cabal could just be happy to clobber the link.

Here's a small script to show what I mean:

```
#!/bin/bash
set -ev
CABAL_HOME=$HOME/Library/Haskell
rm -f $CABAL_HOME/bin/bogus-cabal-thing
ln -s /tmp/this/is/a/totally/bogus/filename $CABAL_HOME/bin/bogus-cabal-thing
rm -rf bogus
mkdir bogus
cd bogus
cat > bogus.cabal <<EOF
name:                bogus
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.8
executable bogus-cabal-thing
  main-is:             main.hs
  build-depends:       base
EOF
echo 'main = return ()' > main.hs

# WANTED [a]: it just clobbers the dead symlink, or
# WANTED [b]: it just complains that the symlink already exists
# BUG?: just says that bogus already exists
cabal install
```

**Comment by mcandre** [comment]
I get a similar error when installing happy.

```console
$ cabal install --force-reinstalls happy
Resolving dependencies...
Configuring happy-1.19.9...
Building happy-1.19.9...
Installed happy-1.19.9
Warning: could not create a symlink in /Users/andrew/.cabal/bin for happy
because the file exists there already but is not managed by cabal. You can
create a symlink for this executable manually if you wish. The executable file
has been installed at /Users/andrew/.cabal/bin/happy

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.1

$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.0 of the Cabal library 
```

**Comment by ulysses4ever** [comment]
My reading of https://github.com/haskell/cabal/issues/1009#issuecomment-24676471 is that the crux of the issue has to do with symlinks to sandboxes. We don't story sandboxes anymore. Should this be closed?
