### ISSUE TITLE
Don't print benchmark results concurrently

### ISSUE THREAD

**Issue by noughtmare** [haskell/cabal#10133]
**Describe the bug**

By default cabal runs benchmarks concurrently including the printing of the results. This can be very confusing. Furthermore, running benchmarks concurrently can influence the measurements.

**To Reproduce**

```
$ git clone https://github.com/awkward-squad/queues.git
$ cd queues
$ cabal bench
Build profile: -w ghc-9.6.5 -O1
In order, the following will be built (use -v for more details):
 - queues-1.0.0 (bench:bench-ephemeral-queue) (first run)
 - queues-1.0.0 (bench:bench-real-time-queue) (first run)
 - queues-1.0.0 (bench:bench-sequence-queue) (first run)
Preprocessing benchmark 'bench-real-time-queue' for queues-1.0.0..
Preprocessing benchmark 'bench-ephemeral-queue' for queues-1.0.0..
Building benchmark 'bench-real-time-queue' for queues-1.0.0..
Building benchmark 'bench-ephemeral-queue' for queues-1.0.0..
Preprocessing benchmark 'bench-sequence-queue' for queues-1.0.0..
Building benchmark 'bench-sequence-queue' for queues-1.0.0..
Running 1 benchmarks...
Benchmark bench-ephemeral-queue: RUNNING...
Running 1 benchmarks...
Benchmark bench-real-time-queue: RUNNING...
All
  EphemeralQueue: Running 1 benchmarks...
Benchmark bench-sequence-queue: RUNNING...
All
  Queue: All
  Seq: OK
    10.9 ms ± 729 μs

All 1 tests passed (0.17s)
Benchmark bench-sequence-queue: FINISH
         OK
    7.44 ms ± 724 μs

All 1 tests passed (0.24s)
Benchmark bench-real-time-queue: FINISH
                  OK
    2.83 ms ± 271 μs

All 1 tests passed (0.38s)
Benchmark bench-ephemeral-queue: FINISH
```

This makes it impossible to figure out which benchmark produced which result.

**Expected behavior**

Benchmarks should always be run sequentially rather than concurrently.

**System information**
 - NixOS 24.05pre627788.4a6b83b05df1 (Uakari)
 - cabal-install version 3.10.3.0
    compiled using version 3.10.3.0 of the Cabal library
- ghc-9.6.5

**Comment by ulysses4ever** [comment]
Hey, thanks for the report. Could you check if it regressed since 3.8? 3.10.1?

**Comment by noughtmare** [comment]
I don't think I can easily try out old versions of cabal on NixOS. I might try to check later on another machine.

**Comment by ulysses4ever** [comment]
Oh, no worries, we can definitely try it on our end.

Just a note: a good-old `cabal install cabal-install-3.8.1.0` should probably work on NixOS.

**Comment by Bodigrim** [comment]
Duplicate of https://github.com/haskell/cabal/issues/7557. It's not a regression, it was always broken.

**Comment by noughtmare** [comment]
I'll close this as duplicate of #7557 then.

**Comment by ulysses4ever** [comment]
Thank you Bodigrim for the pointer and noughtmare for reviving this issue. We should fix it one day.
