### ISSUE TITLE
Bootstrap plans still contain hashable-1.4.6.0 with +arch-native

### ISSUE THREAD

**Issue by TerrorJack** [haskell/cabal#10146]
Before the new release goes out, you might also want to update bootstrap json plans to ensure `hashable-1.4.6.0` is not contained in the bootstrap plans, maybe also bumping the `hashable` lower bound?

Related: #9885 #10142

**Comment by geekosaur** [comment]
Bootstrap plans aren't part of the release.

**Comment by geekosaur** [comment]
More to the point, we've punted on bootstrap plans for 9.10.1 because we want to release before hackage-server is likely to release a compatible version, so bootstrap is going to be hobbled anyway.

**Comment by Mikolaj** [comment]
I think it's fine if bootstraps don't support the newest GHC. The original purpose was to bootstrap to new architectures and using the newest GHC is only asking for trouble (unless it's the only one supporting the architecture). Similarly, Linux distributions never use the newest GHC.

BTW, is `hashable-1.4.6.0` actually a part of any of the existing boostrap plans on branch `master`? It can't be, I guess?

**Comment by TerrorJack** [comment]
> Bootstrap plans aren't part of the release.

Of course, but bootstrap plans infected with a bad revision of `hashable` will still bite their consumers hard (e.g. distro packagers) so it's still good to correct this particular mistake IMHO

> BTW, is hashable-1.4.6.0 actually a part of any of the existing boostrap plans on branch master?

https://github.com/haskell/cabal/blob/master/bootstrap/linux-9.8.2.json#L214
https://github.com/haskell/cabal/blob/master/bootstrap/linux-9.6.4.json#L210
https://github.com/haskell/cabal/blob/master/bootstrap/linux-9.4.8.json#L240
https://github.com/haskell/cabal/blob/master/bootstrap/linux-9.2.8.json#L250
https://github.com/haskell/cabal/blob/master/bootstrap/linux-9.0.2.json#L280
https://github.com/haskell/cabal/blob/master/bootstrap/linux-8.10.7.json#L280

**Comment by geekosaur** [comment]
A bunch of `hashable` refs in the bootstrap jsons on both `3.12` and `master` have `+arch-native`.
```
hilfy «cabal:master» Z$ grep -A2 hashable bootstrap/*.json
bootstrap/linux-8.10.7.json:      "component": "lib:hashable",
bootstrap/linux-8.10.7.json-      "flags": [
bootstrap/linux-8.10.7.json-        "+arch-native",
--
bootstrap/linux-8.10.7.json:      "package": "hashable",
bootstrap/linux-8.10.7.json-      "revision": 0,
bootstrap/linux-8.10.7.json-      "source": "hackage",
--
bootstrap/linux-9.0.2.json:      "component": "lib:hashable",
bootstrap/linux-9.0.2.json-      "flags": [
bootstrap/linux-9.0.2.json-        "+arch-native",
--
bootstrap/linux-9.0.2.json:      "package": "hashable",
bootstrap/linux-9.0.2.json-      "revision": 0,
bootstrap/linux-9.0.2.json-      "source": "hackage",
--
bootstrap/linux-9.2.8.json:      "component": "lib:hashable",
bootstrap/linux-9.2.8.json-      "flags": [
bootstrap/linux-9.2.8.json-        "+arch-native",
--
bootstrap/linux-9.2.8.json:      "package": "hashable",
bootstrap/linux-9.2.8.json-      "revision": 0,
bootstrap/linux-9.2.8.json-      "source": "hackage",
--
bootstrap/linux-9.4.8.json:      "component": "lib:hashable",
bootstrap/linux-9.4.8.json-      "flags": [
bootstrap/linux-9.4.8.json-        "+arch-native",
--
bootstrap/linux-9.4.8.json:      "package": "hashable",
bootstrap/linux-9.4.8.json-      "revision": 0,
bootstrap/linux-9.4.8.json-      "source": "hackage",
--
bootstrap/linux-9.6.4.json:      "component": "lib:hashable",
bootstrap/linux-9.6.4.json-      "flags": [
bootstrap/linux-9.6.4.json-        "+arch-native",
--
bootstrap/linux-9.6.4.json:      "package": "hashable",
bootstrap/linux-9.6.4.json-      "revision": 0,
bootstrap/linux-9.6.4.json-      "source": "hackage",
--
bootstrap/linux-9.8.2.json:      "component": "lib:hashable",
bootstrap/linux-9.8.2.json-      "flags": [
bootstrap/linux-9.8.2.json-        "+arch-native",
--
bootstrap/linux-9.8.2.json:      "package": "hashable",
bootstrap/linux-9.8.2.json-      "revision": 0,
bootstrap/linux-9.8.2.json-      "source": "hackage",
hilfy «cabal:master» Z$ _
```

**Comment by Mikolaj** [comment]
Wow, well spotted. Surprising that it's so many of them.

**Comment by geekosaur** [comment]
Interestingly, GitHub didn't close this issue despite recognizing the above merge that fixed this. Closing.
