### ISSUE TITLE
Bad Checksum in Bloomfilter ebuild from Haskell overlay

### ISSUE THREAD

**Issue by adsicks** [haskell/cabal#1017]
emerge bloomfilter using the haskell overlay added with layman -fa haskell produces the following error:

!!! Fetched file: bloomfilter-1.2.6.10.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      21456
!!! Expected: 21533
Refetching... File renamed to '/usr/portage/distfiles/bloomfilter-1.2.6.10.tar.gz._checksum_failure_.x13Lve'

!!! Couldn't download 'bloomfilter-1.2.6.10.tar.gz'. Aborting.
 * Fetch failed for 'dev-haskell/bloomfilter-1.2.6.10', Log file:
 *  '/var/tmp/portage/dev-haskell/bloomfilter-1.2.6.10/temp/build.log'

>>> Failed to emerge dev-haskell/bloomfilter-1.2.6.10, Log file:

>>>  '/var/tmp/portage/dev-haskell/bloomfilter-1.2.6.10/temp/build.log'

 * Messages for package dev-haskell/bloomfilter-1.2.6.10:

 * Fetch failed for 'dev-haskell/bloomfilter-1.2.6.10', Log file:
 *  '/var/tmp/portage/dev-haskell/bloomfilter-1.2.6.10/temp/build.log'

Checked file size with Opera by just downloading the file, and the file size on server does not match the Manifest...jigging the manifest to the right sizes and signatures and it appears the package is actually a patch and not the right package for an install...

**Comment by jsl** [comment]
Based on comments in this thread it seems like this was a packaging issue that should be reported and fixed elsewhere. Can we close this issue?
