### ISSUE TITLE
`cabal-install/tests/IntegrationTests2.hs` is sensitive to local configuration

### ISSUE THREAD

**Issue by geekosaur** [haskell/cabal#10187]
**Describe the bug**
If my local cabal configuration contains `documentation: True`, running `validate.sh` locally fails with
```
Integration tests (internal)
  Regression tests
    program options scope all:                 FAIL (1.36s)
      tests/IntegrationTests2.hs:1560:
      q
      expected: Just ["-fno-full-laziness"]
       but got: Just ["-haddock"]
      Use -p '/program options scope all/' to rerun this test only.
    program options scope local:               FAIL (1.26s)
      tests/IntegrationTests2.hs:1585:
      q
      expected: Just ["-fno-full-laziness"]
       but got: Just ["-haddock"]
      Use -p '/program options scope local/' to rerun this test only.
    program options scope specific:            FAIL (1.33s)
      tests/IntegrationTests2.hs:1610:
      q
      expected: Nothing
       but got: Just ["-haddock"]
      Use -p '/program options scope specific/' to rerun this test only.
```
Validation succeeds if I comment out the `documentation` directive in my local config.

**To Reproduce**

```
$ vi ~/.config/cabal/config # and set "documentation: True"
$ git clone https://github.com/haskell/cabal
$ cd cabal
$ cabal build all
$ ./validate.sh --with-cabal=$(cabal list-bin cabal)
```

**Expected behavior**
Validation should succeed regardless of the local setting of `documentation`.

**System information**
 - Linux Ubuntu 22.04.3
 - `cabal` `master` `HEAD` as of 2024-07-08, `ghc` 9.6.6

**Comment by geekosaur** [comment]
Should `validate.sh` point to a default config file via `CABAL_CONFIG`, or does it need to use some other mechanism to avoid overriding test-specific config files?

**Comment by ulysses4ever** [comment]
dunno but perhaps if you do something wrong and override the test-specific configs it will fail horribly?..

**Comment by geekosaur** [comment]
It looks like `IntegrationTests2` already _has_ a default cabal config; it's just not using it, as far as I can tell, or at least isn't using it everywhere it needs to be used. I'm thinking that needs to be moved into `validate.sh`.
