### ISSUE TITLE
Figure out why `MAX_PATH` is still a problem in Cabal

### ISSUE THREAD

**Issue by jasagredo** [haskell/cabal#10191]
Base should be fixed once WinIO was merged, but there are still tests which even in newer GHCs still fail with MAX_PATH issues:

```
 C:\Users\runneradmin\AppData\Local\Temp\cabal-testsuite-26120\cabal-external.dist\work\.\dist\build\x86_64-windows\ghc-9.10.1\indef-0.1.0.0\indef-0.1.0.0-inplace+3YxWX6XJM8s5QouYtC2nTB\build\indef-0.1.0.0-inplace+3YxWX6XJM8s5QouYtC2nTB\autogen\Data\: openBinaryTempFileWithDefaultPermissions: invalid argument (CallStack (from HasCallStack):

  withMetadata, called at src\Distribution\Simple\Utils.hs:459:7 in Cabal-3.13.0.0-inplace:Distribution.Simple.Utils
```

Mistuke mentioned that Cabal uses its own logic for temp files, but this one looks like it uses the base one. This is worth investigating in any case, because Backpack results in very long paths always...

**System information**
 - Operating system Windows
 - `cabal`, `ghc` versions: 3.12.1.0 and 9.0.2-9.10.1

**Comment by jasagredo** [comment]
Tests that are currently marked as failing because of this:
- `PackageTests\Backpack\Includes2\cabal-internal.test.hs`
- `PackageTests\Backpack\Includes3\cabal-external.test.hs`
- `PackageTests\Backpack\Includes3\cabal-internal.test.hs`
- `PackageTests\Backpack\T6385\cabal.test.hs`

**Comment by jasagredo** [comment]
Cabal uses temporary files for writing files atomically. It then renames the file to the right name after writing it. However this cannot deal with long paths on Windows.

See how [GetTempFileNameW](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettempfilenamew) specifies:

> The string cannot be longer than MAX_PATH–14 characters or GetTempFileName will fail.

And actually there is a TODO in Win32Utils.c in GHC:

https://gitlab.haskell.org/ghc/ghc/-/blob/3939a8bf93e27d8151aa1d92bf3ce10bbbc96a72/libraries/ghc-internal/cbits/Win32Utils.c#L259

So my suggestion and the PR I'm preparing is to create temp files in the global temp directory instead of in the final destination. This is somewhat of a breaking change, but I don't think it will be too noticeable.

**Comment by GulinSS** [comment]
> This is somewhat of a breaking change, but I don't think it will be too noticeable.

Well, [hello from 2025](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13856#note_619869). 😅 Thanks for good information at commit message what is going on there. Very appreciate!

Dealing with it [here](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13856#note_619869).

**Comment by dcoutts** [comment]
This doesn't work. You can't use a temporary directory in a different place than the build tree since that is not guaranteed to be on the same file system. And the atomic file renaming is only atomic if it's on the same file system.

This change breaks things when the system temp dir in on another file system (which is very common).
