### ISSUE TITLE
`cabal path` writes purely informational output to `stdout` instead of `stderr`

### ISSUE THREAD

**Issue by sol** [haskell/cabal#10200]
**Describe the bug**

I think it's a common misconception that `stderr` is meant for error messages only.  A better way to think about whether to write something to `stdout` or `stderr` may be:

1. When a program produces some output and you redirect `stdout` when running that program then do you in the **common case** want this output to be captured (== redirected)? If yes, write it to `stdout`.  If no, write it to `stderr`.
1. For purely informational output you don't want it to be captured in the **common case**.
2. Note that there are **special cases** where you want to  capture all output, including error message. An example would be a CI system,  like Jenkins or GitHub actions.

**To Reproduce**

```bash
$ rm -f ~/.config/cabal/config
```
```bash
$ cabal path --installdir > result
```
```bash
$ cat result
Config file path source is default config file.
Config file not found: /home/sol/.config/cabal/config
Writing default configuration to /home/sol/.config/cabal/config
/home/sol/.local/bin
```

**Expected behavior**
```bash
$ rm -f ~/.config/cabal/config
```
```bash
$ cabal path --installdir > result
Config file path source is default config file.
Config file not found: /home/sol/.config/cabal/config
Writing default configuration to /home/sol/.config/cabal/config
```
```bash
$ cat result
/home/sol/.local/bin
```

**System information**

```
$ cabal --version
cabal-install version 3.12.1.0
compiled using version 3.12.1.0 of the Cabal library
```

**Workaround**
```bash
$ rm -f ~/.config/cabal/config && cabal -v0 path --installdir
```

**Comment by ulysses4ever** [comment]
This is not about `cabal path` exclusively, so I'd suggest to change back the title of the issue to say "Cabal writes purely...".

This issue has come up several times: https://github.com/haskell/cabal/issues/8870, https://github.com/haskell/cabal/issues/7790, https://github.com/haskell/cabal/issues/4652 #9911

There are two old draft PRs:

- #7838 
- https://github.com/haskell/cabal/pull/4789

There are some design consideration that were not resolved (what should remain on `stdout` exactly), but they're not that bad: I'd say we could err on the side of sending more to stderr first and then play it by the year (get bug reports and revert part of the output back to stdout). 

A bigger technical problem, as funny as it sounds, is adjusting our humongous test suite. I'm still to see a brave soul who would take this on.

I'm tentatively closing this as a duplicate, but feel free to reopen if you disagree.
