### ISSUE TITLE
Dependency License Audit and Automatic In/Exclusion Lists

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/cabal#10201]
# Overview

It would be very useful for cabal to have
- dependency licensing audits that describe the licensing for each of the build targets
- checks that cause the build to fail if dependencies violate: the top package's license, and/or a specified licensing policy described in the cabal file.

# Details

## Audit

`cabal license audit [--verbose] [--json] [TARGET]`

`cabal license audit` Lists each target and the set of dependency licenses.

`cabal license audit [--verbose] Lists each target and a flattened recursive map of the dependencies and their associated license.

`cabal license audit --json` Outputs in formatted json or some other formatted text if json is not desirable.

```txt
$ cabal license audit
library library-name
  BSD-3-Clause
  ...
executable executable-name
  BSD-3-Clause
  ...
test-suite test-suite-name
  BSD-3-Clause
  ...
benchmark benchmark-name
  BSD-3-Clause
  ...
```

## Builds Failing From License Violations

If a licensing policy is specified and a violation is found, the build should fail with a description of which dependencies are violating the policy.

The flag `--ignore-licenses` should be added to `cabal build` so that the license checks are not performed.

## Policy Description

There should be an optional field `licensing` added to the top level and each component that has subfields that allow for inclusion and exclusion patterns.

The below is just an example and there may be a better way to describe the policy

```cabal
licensing
  BSD*

executable executable-name
  licensing
    ! GPL*
```

I am unsure how the global licensing policy should interact with the target licensing policy. Perhaps, the target policy patterns could be prepended to the global policy patterns and the first match is what is selected.

**Comment by mpickering** [comment]
This seems like it would be a good use of external commands. (https://cabal.readthedocs.io/en/stable/external-commands.html)

**Comment by BebeSparkelSparkel** [comment]
@mpickering External Commands sound great! I'll look into an implementation.

**Comment by wraithm** [comment]
Is there some good way to just list all of the licenses from external deps using cabal? Is there a good tool for this? I'm having trouble finding this.

**Comment by geekosaur** [comment]
https://hackage.haskell.org/package/cabal-dependency-licenses perhaps?
