### ISSUE TITLE
Deploying Cabal on RISC-V Architecture

### ISSUE THREAD

**Issue by Boring545** [haskell/cabal#10210]
**What is your question?**
I'm currently trying to deploy Cabal on the RISC-V architecture. Is this possible? I've attempted to use ghcup, stack, but it indicates that it does not support this architecture. Now, I have successfully configured GHC in my RISC-V environment. Could anyone guide me on how to compile a usable Cabal setup?

**System information**
 - linux
 - `ghc` versions：9.4.8

**Comment by Boring545** [comment]
```
wget https://downloads.haskell.org/~cabal/Cabal-3.8.1.0/Cabal-3.8.1.0.tar.gz
tar -xf Cabal-3.8.1.0.tar.gz
cd Cabal-3.8.1.0
/home/zjq/build_factory/GHC/release_temp/bin/ghc --make Setup.hs
./Setup configure --user --enable-library-profiling --with-compiler=/home/zjq/build_factory/GHC/release_temp/bin/ghc --prefix=/home/zjq/build_factory/GHC/cabal/release_cabal-3.8.1.0

```
Is it correct for me to attempt building Cabal in this way?

**Comment by ulysses4ever** [comment]
Hello! I'm not aware of previous attempts at this. 

For your purpose (I think) you should be using bootstrap harness we provide: https://github.com/haskell/cabal/blob/master/bootstrap/README.md

**Comment by fgaz** [comment]
If you already built GHC on RISC-V, you already have Cabal, since it's a [boot package](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries). If you want cabal-install, the [bootstrap script](https://github.com/haskell/cabal/tree/master/bootstrap) should work

**Comment by Boring545** [comment]
Due to the lack of an available GHC for RISC-V architecture, I found a GHC built via cross-compilation at https://github.com/skeuchel/riscv64-ghc-bindist. I installed GHC by navigating to ghc-9.4.8, running ./configure --prefix=/home/zjq/build_factory/GHC/release_temp (without specifying any parameters defaults to installing at /usr/local/bin/ghc), followed by make -j$(nproc) install. This approach may have resulted in me not generating cabal simultaneously.

Currently, my system does not have an executable cabal. I'm attempting to execute the bootstrap.py script, which, as described, should build cabal-install in the absence of an available cabal. I'm not very familiar with some components of the Haskell language. If I successfully generate cabal-install, cabal should be generated simultaneously, correct?

**Comment by ulysses4ever** [comment]
@fgaz it'd seem to me that we should be more gentle in advertizing distinction between the library and the tool, and try to explain it in more detail before moving on. Anecdotally, 3/4 of casual Haskell users I know have not a slightest idea of the distinction.

@Boring545 you're on the right track. Except that the Cabal library have certainly been built when the other person built GHC for RISC-V. That's because GHC itself depends on the Cabal library, so it's not possible to build a GHC without the library.

Now, you're probably into getting `cabal` the command-line tool to build on your architecture. That's a separate business that should fully be covered by the bootstrap process we referenced above. Is it working for you? If not, please provide more detail what's not working. If you succeed with it, you will have a fully-functiounal `cabal` the command-line tool working.

What fgaz may have alluded to above is that for some simple tasks the command-line tool is not necessary and you may get away with using the library, which, most certainly, is available if you have a functioning GHC on that platform. But I'd say, in many cases the library is not enough and bootstrap may just work, so why not try it: it doesn't require much.

**Comment by Boring545** [comment]
I found a file named ghc-cabal in ghc-9.4.8\utils\ghc-cabal\dist-install\build\tmp, which I believe is a precompiled cabal by someone else. However, when I tried to use it, unfortunately, it resulted in an error.
![图片](https://github.com/user-attachments/assets/469cf1c5-8fad-4ff7-8a68-2002d7aba1c7)
`./ghc-cabal: error while loading shared libraries: libHSCabal-3.8.1.0-ghc9.4.8.so: cannot open shared object file: No such file or directory`
After running make -j$(nproc) install, I found the compiled libHSCabal-3.8.1.0-ghc9.4.8.so file. However, the error indicates that it requires libHSprocess-1.6.18.0-ghc9.4.8.so.

**Comment by ulysses4ever** [comment]
@Boring545 thanks for sharing! `utils/ghc-cabal` is something unfamiliar, so we can't help much with that but you seem to be making progress, which is great to hear! 

If you hit a dead end somewhere on this path, I highly recommend trying out our bootstrap script -- it's meant to be used for cases like yours, and is officially maintained by the Cabal team.

**Comment by Bodigrim** [comment]
@supersven is this something you might comment on given your work on GHC on RISC-V?

**Comment by Boring545** [comment]
During the execution of the bootstrap script, it was interrupted due to some issues. I found in hashable.cabal at line 173 the following configuration:

`ghc-options: -optc=-march=native -optc-mtune=native`

I changed it to:

`ghc-options: -optc=-march=rv64gc -optc-mtune=generic`

After making this change and re-running the script, I noticed that it starts from the beginning instead of continuing from where it left off. Is there a way to resume the script from the last successful point?
![图片](https://github.com/user-attachments/assets/935ef742-3c48-460e-b625-970d11804980)

**Comment by supersven** [comment]
> @supersven is this something you might comment on given your work on GHC on RISC-V?

Hey :wave: 

GHC has a LLVM backend for RISCV64, so there's no need to run *unregisterised*. Though, there's no official binary distribution for RISCV64. Some Linux distributions have packages for GHC and `cabal-install`. E.g.

- https://packages.debian.org/sid/cabal-install
- https://build.opensuse.org/project/show/home:Andreas_Schwab:riscv:ghc:9.8

However, it's quite interesting to see these bootstrapping efforts, as I need to build cabal from scratch for testing reasons, too.

**Comment by Boring545** [comment]
Upon reviewing the bootstrap script, I discovered that the resolve_dep function unpacks the source files every time it is called. This results in any modifications I made to the hashable.cabal file being overwritten by the newly unpacked files. Additionally, every execution of the bootstrap script triggers a recompilation of all dependencies.

Previously, I encountered an issue where the hashable.cabal file did not correctly pass parameters to GCC on RISC-V. To temporarily address these issues, I implemented a [quick fix in the bootstrap.py script](https://github.com/Boring545/cabal/blob/master/bootstrap/bootstrap.py). 

First, execute ./bootstrap/bootstrap.py -d ./bootstrap/linux-9.4.8.json -w /home/zjq/build_factory/GHC/release_temp/bin/ghc. After approximately 14 hours, an error will be reported.
![图片](https://github.com/user-attachments/assets/b37ef40d-103c-4a73-a8f7-ffada3559ac5)

I manually modify the file c`abal/_build/unpacked/hashable-1.4.6.0/hashable.cabal`:177 
from
`ghc-options: -optc=-march=native -optc-mtune=native`
to
`ghc-options: -optc=-march=rv64gc. Then, I re-run the script with the command:`

Continuing to execute, (where a new parameter `-p hashable` was added), and then it can continue with the compilation.
`./bootstrap/bootstrap.py -d ./bootstrap/linux-9.4.8.json -w /home/zjq/build_factory/GHC/release_temp/bin/ghc -p hashable`

**Comment by Boring545** [comment]
Thank you all for your help. I successfully ran the bootstrap script, everything has been configured correctly, and cabal is now working properly.
