### ISSUE TITLE
convert cabal-install/changelog to markdown

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#10220]
**What is wrong with the docs?**
The cabal-install changelog file is basically a list of links to the release files.
But it is a plain text file, so one has to copy urls and paste them in order to open them easily.

Converting to a simple markdown file `changelog.md` should be straightforward.
I could probably help with that: is the file just written by hand?

**Comment by ulysses4ever** [comment]
Dup of https://github.com/haskell/cabal/issues/8857? Contributions welcome!
