### ISSUE TITLE
Search does not Reveal Docs for `Paths_{pkgname}`

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/cabal#10233]
I was trying to find information on the auto-generated module `Paths_{pkgname}` but when searching with the term `Paths` or `Paths_` no relevant results were returned.
 
The [github search](https://github.com/search?q=repo%3Ahaskell%2Fcabal+path%3Adoc%2F+Paths_&type=code) reveals that the page [cabal-package-description-file.rst](https://github.com/haskell/cabal/blob/356c2f4cc8d205de4b79c28e287735f457924ab4/doc/cabal-package-description-file.rst#accessing-data-files-from-package-code) has the relevant documentation.

Also, `PackageInfo_{pkgname}` has the same problem.

**Comment by geekosaur** [comment]
This is a shortcoming of RTD's documentation theme; last time I tried it, it worked with `Paths_pkgname`. (Just checked: it still does.)

**Comment by ulysses4ever** [comment]
I struggled to find it in the past too, so I consider it a serious issue.

I wonder if we can trick read-the-docs into indexing Paths and Paths_... Is it as easy as sneaking these as proper words somewhere? Is there a way to force it to index it? Nothing like that in https://cabal.readthedocs.io/en/stable/genindex.html#P ...

**Comment by geekosaur** [comment]
It looks to me like we might be able to make an end run around it with explicit `index::` entries? (This is from Sphinx documentation, but it looks like RTD uses Sphinx.) https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup

**Comment by ulysses4ever** [comment]
great! thank you, Brandon! @BebeSparkelSparkel, do you care to submit a PR along these lines? we have a preview on PRs, so we'll be able to tell if it worked right away!
