### ISSUE TITLE
Regression in HEAD leading to build path leaking into object files (preprocessors)

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#10242]
In Cabal HEAD, when hsc2hs is invoked an absolute path is passed which then leaks into the object files due to this path being used in a LINE pragma.

In older versions of Cabal this is a relative path which doesn't include the build directory. 

I suspect this is due to work performed by @sheaf so I will coordinate investigations with him to investigate a fix.

**Comment by mpickering** [comment]
Seems that `preprocessFile` requires an argument of type `Maybe (SymbolicPath CWD (Dir Pkg))` but then the filepath which arrives is `"/home/matt/mercury-web-backend/zlib-0.7.1.0/"`, notably not a relative path from CWD to (Dir Pkg).

**Comment by mpickering** [comment]
It seems this absolute path originates a long way back in `cabal-install`, so I am a bit wary of changing it. I will talk with Sam.

**Comment by Kleidukos** [comment]
@mpickering If I understand wwell, the `dir` in question has already been resolved to be an absolute path?

**Comment by mpickering** [comment]
@Kleidukos 3.12 doesn't have this regression but it's important to fix before 3.14 I believe.

**Comment by Kleidukos** [comment]
Quite right indeed.

**Comment by Kleidukos** [comment]
@mpickering Have you coordinated with @sheaf for a fix?

**Comment by sheaf** [comment]
Yes, Matthew fixed this in #10256 (now merged).

**Comment by Kleidukos** [comment]
Fantastic, this brightens my day.
