### ISSUE TITLE
Source repository doesn't display properly on hackage 2

### ISSUE THREAD

**Issue by hesselink** [haskell/cabal#1028]
The 'Source repository' property doesn't display correctly on hackage 2. For example, the ['flock' package](http://new-hackage.haskell.org/package/flock-0.3.1.2) shows:

    Source repositoryhead: SourceRepo {repoKind = RepoHead, repoType = Just (OtherRepoType "github"), repoLocation = Just "git://github.com/hesselink/flock.git", repoModule = Nothing, repoBranch = Nothing, repoTag = Nothing, repoSubdir = Nothing}

The old hackage shows:

    Source repository	github git://github.com/hesselink/flock.git

**Comment by ttuegel** [comment]
This isn't a Cabal issue.

**Comment by 23Skidoo** [comment]
Still an issue though. Can we perhaps migrate those tickets that are still valid to the `hackage-server` tracker?

**Comment by ttuegel** [comment]
@23Skidoo Yup, that's what I'm doing next. I just wanted to get all the Hackage-only issues closed at once so I wasn't bouncing back and forth.

**Comment by 23Skidoo** [comment]
@ttuegel Great. Thanks for doing this.
