### ISSUE TITLE
Improve user signup etc

### ISSUE THREAD

**Issue by igfoo** [haskell/cabal#1029]
User signup should ask for username, password, e-mail address, and perhaps optionally other information (e.g. name etc).

It should then send a confirmation mail to the e-mail address, which includes a URL. The URL must be visited to activate the account.

Similarly, there should be an 'I forgot my password' button which also sends a mail containing a URL. That URL will include a 'reset my password' button, which sets the password to a random string and shows and/or e-mails that password to the user.

As well as requiring e-mail confirmation, accounts must also be confirmed by an admin before they can upload. There should be a page listing the outstanding requests, with 'accept' and 'reject' buttons (and perhaps 'drop' too, for silent rejects?). Admins should be mailed either when a new request is made, once a day if there are outstanding requests, or both.

**Comment by ttuegel** [comment]
This is not a Cabal issue.
