### ISSUE TITLE
Rewrite `validate.sh` in Haskell

### ISSUE THREAD

**Issue by 9999years** [haskell/cabal#10317]
[`validate.sh`](https://github.com/haskell/cabal/blob/13041baec5c7e91b785c7c4dcc3d52b74e8319f8/validate.sh) is the entry-point to CI and local testing. `validate.sh` is needed because it's non-trivial to [run tests](https://github.com/haskell/cabal/blob/13041baec5c7e91b785c7c4dcc3d52b74e8319f8/CONTRIBUTING.md#running-tests) otherwise.

However, `validate.sh` is a shell script, which limits its expressive power and maintainability.
I've been working on improving it with PRs like #10293 and #10315, but working with shell scripting idioms makes it much more difficult than it needs to be. Let's rewrite it as a simple Haskell script. I'm willing to do this if the maintainers OK it.

**Comment by 9999years** [comment]
@philderbeast Yes, but I'm not set on it if the maintainers have other preferences.

**Comment by philderbeast** [comment]
When generating a [sha256map for nix](https://github.com/cabalism/updo/blob/main/project-nix/sha256map.hs), turtle came in handy and was easy to use so I'd be happy to see it used here. Another thing I did with Updo was offer the option to install each standalone *.hs script by listing them as executables in the package. That could help speed thing up for scripts called multiple times.

**Comment by ulysses4ever** [comment]
I'm in support. But we should try to think really hard of potential adversarial effects. Portability. Startup times. Downstream users including distributors like ghcup and nixpkgs (who may want to run it). Nothing jumps at me as a show stopper.

At least, probably, `validate.sh` should stay and turn into a one-liner calling validate.hs?
