### ISSUE TITLE
doc builder doesn't handle haddock failure well

### ISSUE THREAD

**Issue by igfoo** [haskell/cabal#1036]
If haddock fails, as it does with her-lexer-0.1:

$ cabal haddock --hyperlink-source
Running Haddock for her-lexer-0.1...
Running hscolour for her-lexer-0.1...
Preprocessing library her-lexer-0.1...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0, mtl-2.1.2, split-0.2.0.0,
transformers-0.3.0.0
Preprocessing library her-lexer-0.1...
Haddock coverage:
   0% (  0 / 14) in 'Language.Haskell.Her.Parsley'
   0% (  0 / 57) in 'Language.Haskell.Her.HaLay'

dist/build/tmp-10691/src/Language/Haskell/Her/FromClutterToLines.hs:5:3:
    parse error on input `-- | When we get the tokss from her-parser's ready, they're a bit cluttered.  I'm not sure what Dr. McBride had in mind when he made that mess.  But this doesn't mater, from this clutter we can create a list of lines which is aware of haskell's brackets.  If a multi-line clause is inside brackets, then we keep the whole section in the same "line".'
$ echo $?
1

then the doc builder will still upload something. Actually, this could be useful, as it includes the highlighted sources (ideally we would make that available no matter what; that would also solve #1024. But currently there are no links to the sources if there's no docs), but it means that the package page thinks that docs are available, so http://new-hackage.haskell.org/package/her-lexer gets broken links to http://new-hackage.haskell.org/package/her-lexer-0.1/doc/Language-Haskell-Her-HaLay.html etc.

**Comment by ttuegel** [comment]
This isn't a Cabal issue.
