### ISSUE TITLE
Some way to apply a constraint on the command line to `build-tool-depends`

### ISSUE THREAD

**Issue by geekosaur** [haskell/cabal#10375]
**Describe the feature request**
`--constraint` only applies to libraries. There's no equivalent mechanism for build tools.

**Additional context**
`happy-2.0` was just released, and breaks `haskell-lib-parser` and probably other things (and possibly is just straight-up broken). Until its constraint can be adjusted or a fixed `happy` is released, there needs to be some way to constrain it to avoid the breakage without making it a local source or editing `cabal.project` (which may be in CI, or you aren't doing an install within a project).

**Comment by grayjay** [comment]
I think that this issue is part of #3502. Is it possible to work around the specific issue with `happy` by using `any.happy`, or do you need to only constrain a specific use of the build tool?

**Comment by geekosaur** [comment]
I'm uncertain. It didn't attempt to build the library, whereas it did when I let it use happy-2.0, so I guess that's a good sign.

**Comment by grayjay** [comment]
@geekosaur Were you able to build the project by adding an `any.happy` constraint, or is there another issue that isn't covered by #3502?

**Comment by geekosaur** [comment]
We (this was originally raised by Tom Smeding on IRC, but someone else originally asked about it there) were able to get it to work with that, yes.
