### ISSUE TITLE
Refactor to avoid incomplete record selection warning

### ISSUE THREAD

**Issue by simonpj** [haskell/cabal#10402]
When I compile cabal with `-Wincomplete-record-selectors` I get this:
```
libraries/Cabal/Cabal/src/Distribution/Simple/GHC/Build/Link.hs:637:115: error: [GHC-17335] [-Wincomplete-record-selectors, Werror=incomplete-record-selectors]
    Selecting the record field ‘componentExposedModules’ may fail for the following constructors:
      FLibComponentLocalBuildInfo, ExeComponentLocalBuildInfo, TestComponentLocalBuildInfo, BenchComponentLocalBuildInfo
    |
637 |               reexported_modules = [mn | LibComponentLocalBuildInfo{} <- [clbi], IPI.ExposedModule mn (Just{}) <- componentExposedModules clbi]
    |                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^
```
Now, it's true the the record selector `componentExposedModules` cannot fail when applied to `clbi`, but the reasoning for that is very indirect: it means understanding that `LibComponentLocalBuildInfo{} <- [clbi]` guarantees that `clbi` is definitely built with `LibComponentLocalBuildInfo`, which itself involves knowlege of how list comprehensions work, and singleton lists.  This far beyond what the incomplete-record-selector warning mechanisms can do.

Suggestion: the code would be more perspicuous and robust if we said
```
         reexported_modules = [mn | LibComponentLocalBuildInfo{ componentExposedModules = exposed_mods } <- [clbi]
                                  , IPI.ExposedModule mn (Just{}) <- exposed_mods]
```
Now no warning!  And it's a fully backward-compatible change.

## How did this arise?

It turns out that [GHC proposal 516 Incomplete record selectors](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0516-incomplete-record-selectors.rst) said that `-Wincomplete-record-selectors` should be in `-Wall`, but due to an error it was omitted.  When I add it to `-Wall`, to make GHC follow the proposal, GHC's build system falls over when compiling Cabal because it uses `-Werror`.

For now, we've agreed that I'll add `-Wno-incomplete-record-selectors` to GHC's build system for Cabal.  But if the Cabal authors adopt the above change, we can stop suppressing those warnnings.  Thank you!

**Comment by geekosaur** [comment]
What version is `libraries/Cabal` pinned to? That's line 738 on `master` and probably `3.14`. (I'm preparing a PR on `master` it should backport readily to `3.14` but I think `libraries/Cabal` is on something older that's missing e.g. the tagged files refactor.)

**Comment by simonpj** [comment]
Thanks!  I don't know about branches... maybe @mpickering can help.

**Comment by mpickering** [comment]
My understanding according to the release timelines on #10193 is that there will be 3.16 cut from the master branch before the 9.12 release so no backports to 3.14 branch will be needed.

**Comment by mpickering** [comment]
It seems that in #10193 the consensus is now there will not be a 3.16 release before ghc-9.12. Sorry for that misunderstanding, I was going by what was written in the ticket.

However, the patch in question which requires this change will not be in 9.12, so there is no need to hurry a backport.
