### ISSUE TITLE
candidate package functionality is incomplete

### ISSUE THREAD

**Issue by igfoo** [haskell/cabal#1041]
If you upload a candidate package, and then click on "maintain", then you get a page that says "Here, you can delete a candidate, publish it, upload a new one, and edit the maintainer group.". However, it isn't actually possible to do any of those things.

Some more information:
http://www.haskell.org/pipermail/cabal-devel/2012-September/009111.html

Before going live, we should either finish the functionality, or disable it completely (i.e. remove the "maintain" link, and perhaps rename "upload candidate" to "check package").

**Comment by ttuegel** [comment]
This is not a Cabal issue.
