### ISSUE TITLE
./setup install broken on `Cabal-3.14` release

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#10416]
Running `./setup install` will give you an error:

```
fromFlag NoFlag. Use fromFlagOrDefault
CallStack (from HasCallStack):
  error, called at src/Distribution/Simple/Flag.hs:110:19 in Cabal-3.15.0.0-inplace:Distribution.Simple.Flag
  fromFlag, called at src/Distribution/Simple/Register.hs:161:16 in Cabal-3.15.0.0-inplace:Distribution.Simple.Register
```

This seems to not be tested anywhere and most people will use `./setup register` in any case, but we should fix this for the next point release in 3.14 series.

There is a one-line fix which I will provide.

**Comment by Kleidukos** [comment]
@mergifyIO backport 3.14
