### ISSUE TITLE
hackage does not find custom preprocessor when building package

### ISSUE THREAD

**Issue by niklasbroberg** [haskell/cabal#1043]
For my hsp-0.7.1 package, I have a build failure for ghc-7.4. The failure is due to hsp requiring the trhsx preprocessor to parse. That preprocessor is installed in one of the dependencies, but apparently to a location that is not in the path.

Here are the relevant parts of the build failure log:

...
Building hsx-0.10.2...
Preprocessing executable 'trhsx' for hsx-0.10.2...
Building executable trhsx...
...
Installing executable dist/build/trhsx/trhsx to
/usr/local/tmp/archive/install/bin/trhsx
...
ghc: could not execute: trhsx

**Comment by ttuegel** [comment]
This is not a Cabal issue.
