### ISSUE TITLE
Custom setup: Can't use Cabal-3.14 released with GHC 9.12

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#10467]
> [__1] rejecting: Agda:setup.Cabal; 3.14.0.0/installed-17a5, 3.14.0.0 (constraint from maximum version of Cabal used by Setup.hs requires <3.14)

I already reported this for Cabal-3.12 in #9917 ...
- #9917 

But maybe a RC for cabal-install-3.14 (for GHC 9.12) will be available soon?

**Comment by ulysses4ever** [comment]
@geekosaur as the #9917 discussion showed, some people want to have it through ghcup's channels only...

**Comment by geekosaur** [comment]
Yes, but this is about checking whether the prerelease to hopefully be made available there soon will work.

**Comment by andreasabel** [comment]
I tried current `master` of cabal and that one works fine.

**Comment by andreasabel** [comment]
cabal-install 3.14 has been released. I am closing this in favor of #9917.
