### ISSUE TITLE
GHC has LANGUAGE extensions that Cabal doesn't know about

### ISSUE THREAD

**Issue by simonpj** [haskell/cabal#1050]
What is the protocol for updating Cabal's list of LANGUAGE extensions?

GHC has a test (driver/T4437) that tests the difference between GHC's LANGUAGE extensions and Cabals.  It has a list expectedGhcOnlyExtensions for ones GHC knows about but Cabal doesn't.  Current state of play is below.

But ultimately these extensions should end up in Cabal. But how?  

Simon

expectedGhcOnlyExtensions :: [String]
expectedGhcOnlyExtensions = ["ParallelArrays",
                             "RelaxedLayout",
                             "DeriveGeneric",
                             "DefaultSignatures",
                             "InterruptibleFFI",
                             "AlternativeLayoutRule",
                             "AlternativeLayoutRuleTransitional",
                             "MonadComprehensions",
                             "TraditionalRecordSyntax",
                             "DataKinds",
                             "PolyKinds",
                             "ExplicitNamespaces",
                             "InstanceSigs",
                             "CApiFFI",
                             "LambdaCase",
                             "MultiWayIf",
                             "TypeHoles"]

**Comment by BardurArantsson** [comment]
Already fixed, I think? (Though I disagree with referring to the documentation unless it's something that cabal users can actually see somewhere. It's not like Google doesn't exist.)

**Comment by 23Skidoo** [comment]
Yes, I think this can be closed. Please open separate issues/PRs for individual extensions that need to be registered with Cabal.
