### ISSUE TITLE
`cabal-head` is busted since October 3

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#10515]
Here's  a recent Validate run: https://github.com/haskell/cabal/actions/runs/11646685603/job/32432228957

It has:
![2024-11-04_09-11-1730732195](https://github.com/user-attachments/assets/4841355b-02a9-4e0c-858f-54b96593fdb6)

The "🤔 Pattern 'binaries/cabal-*' does not match any files." part looks suspicious...

**Comment by geekosaur** [comment]
```
    # When multiple artifacts are matched, this changes the behavior of the destination directories.
    # If true, the downloaded artifacts will be in the same directory specified by path.
    # If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
    # Optional. Default is 'false'
    merge-multiple:
```
Looks like we need this enabled? Am cutting a PR.

**Comment by ulysses4ever** [comment]
The release action seems happier now 
![2024-11-07_10-11-1730994352](https://github.com/user-attachments/assets/fb68514b-7a28-4d0f-9f73-628c5db09865)

Also, [reports from the field](https://github.com/haskell/cabal/pull/10483#issuecomment-2458064979) indicate that the new binaries are in effect. 

One silly thing is that the new action doesn't update the date on the prerelease itself nor the commit it says was used to create the prerelease. It only updates the binaries and that's it... I opened https://github.com/haskell/cabal/issues/10537
