### ISSUE TITLE
Cabal library API breakage in 3.14.0.0

### ISSUE THREAD

**Issue by ulidtko** [haskell/cabal#10559]
Up until version 3.14, the public module `Distribution.Simple` of Cabal-the-library has been exporting these names:

 * `GlobalPackageDB`
 * `UserPackageDB`
 * `SpecificPackageDB`

as constructors of `PackageDB` data type (indirectly, via reexport of [Distribution.Simple.Compiler][]).

The patchset #10256, specifically commit 90fbf086543dc346ccf95bfb7eba46c9019df269, having shuffled the definitions a little bit, is now causing compile errors in either of two forms:

```
src/Distribution/Extra/Doctest.hs:481:8: error: [GHC-76037]
    Not in scope: data constructor ‘GlobalPackageDB’
    Suggested fix:
      Perhaps you want to add ‘GlobalPackageDB’
      to one of these import lists:
        ‘Distribution.Simple’ (src/Distribution/Extra/Doctest.hs:(66,1)-(68,23))
        ‘Distribution.Simple.Compiler’ (src/Distribution/Extra/Doctest.hs:(69,1)-(70,74))
    |
481 |       (GlobalPackageDB:dbs)
    |        ^^^^^^^^^^^^^^^
```
*with* `import Distribution.Simple.Compiler (PackageDB(..))` being already there;

or

```
src/Distribution/Extra/Doctest.hs:70:59: error:
    In module ‘Distribution.Simple.Compiler’:
      ‘GlobalPackageDB’ is a data constructor of ‘PackageDBX’
    To import it use
      import Distribution.Simple.Compiler( PackageDBX( GlobalPackageDB ) )
    or
      import Distribution.Simple.Compiler( PackageDBX(..) )
   |
70 |        (CompilerFlavor (GHC), CompilerId (..), PackageDB, GlobalPackageDB, UserPackageDB, SpecificPackageDB, compilerId)
   |                                                           ^^^^^^^^^^^^^^^
```

[Distribution.Simple.Compiler]: https://hackage.haskell.org/package/Cabal-3.12.0.0/docs/Distribution-Simple-Compiler.html#t:PackageDB

Please at least document this in release notes, as it's a breaking change.

(BTW there's no 3.14.0.0 on https://github.com/haskell/cabal/releases )

**Comment by ulidtko** [comment]
One more with `BuildCommonFlags` (bundled, record) pattern synonym: https://github.com/haskell/cabal/pull/9718#discussion_r1850612302

**Comment by ulidtko** [comment]
... The `BuildCommonFlags` one puzzles me for good :thought_balloon: 

Seems like the post-refactor API is incomplete; the new pattern synonym `BuildCommonFlags` should be bi-directional... Yet, with its ViewPatterns definition, it can't.

Hi @sheaf, can I ask you as the implementor of #9718 — am I missing a way to rewrite snippets that use Cabal-the-library like so

```haskell
miniRepro :: BuildFlags
miniRepro = defaultBuildFlags {buildVerbosity = undefined}
```

against Cabal 3.14?..

That (I think, correctly) yields:

```
src/Minirepro.hs:245:13: error: [GHC-16444]
    • non-bidirectional pattern synonym ‘BuildCommonFlags’ used in an expression
    • In a record update at field ‘buildVerbosity’
      and with pattern synonym ‘BuildCommonFlags’.
      In the expression: defaultBuildFlags {buildVerbosity = undefined}
      In an equation for ‘miniRepro’:
          miniRepro = defaultBuildFlags {buildVerbosity = undefined}
    |
245 | miniRepro = defaultBuildFlags {buildVerbosity = undefined}
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Under spoiler, I've minimized a bare ghci-ready model test, to spare us all of traversing Cabal codebase for smoother discussion:
<details><summary>minified example</summary>

Foo.hs:
```haskell
{-# LANGUAGE PatternSynonyms, ViewPatterns #-}

module Foo
  ( Sauce (BuildPun, buildDolor, buildSitamet)
  , defaultSauce
  ) where

-- exported without constructor
data Sauce = Sauce
  { lorem :: Int
  , ipsum :: Bool
  , buildSauce :: CommonSauce
  }

data CommonSauce = CommonSauce
  { dolor :: String
  , sitamet :: Maybe ()
  }

pattern BuildPun :: String -> Maybe () -> Sauce
pattern BuildPun
  { buildDolor
  , buildSitamet
  } <- ( buildSauce -> CommonSauce { dolor=buildDolor, sitamet=buildSitamet })

defaultSauce = Sauce 42 False defaultCommonSauce
defaultCommonSauce = undefined
```

Bar.hs:
```haskell
module Bar where

import Foo (Sauce (..), defaultSauce)

example :: Sauce
example = defaultSauce { buildDolor = "WAT" }
```

Same error message:
```
Bar.hs:6:11: error: [GHC-16444]
    • non-bidirectional pattern synonym ‘BuildPun’ used in an expression
    • In a record update at field ‘buildDolor’
      and with pattern synonym ‘BuildPun’.
      In the expression: defaultSauce {buildDolor = "WAT"}
      In an equation for ‘example’:
          example = defaultSauce {buildDolor = "WAT"}
  |
6 | example = defaultSauce { buildDolor = "WAT" }
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
</details> 

Not a heavy user of pattern synonyms myself, so apologies for perhaps obvious question, and thanks in advance.

**Comment by ulidtko** [comment]
That's quite awkward :face_with_diagonal_mouth: Also realize it must be wrapped into CPP version checks (which I see you did in cabal tests).

Wasn't the point of refactor to simplify?..

Anyhow, thanks for the reply, I'll try to adapt to this change as well.

**Comment by ulysses4ever** [comment]
hey @ulidtko ! thanks for raising this issue! just wanted to make it explicit here: do you expect Cabal to document all API changes between major versions? does any other package track these? I saw how some packages do highlight some "notable" API changes in the changelog, and we certainly could retroactively fix the notes for 3.14.0.0, and 3.14.1.0 can include these as well. But it's not clear to me that anyone has a reliable and exhaustive reporting of **all**  API changes. I'd be curious to know how people set this up especially in case of big packages like Cabal+Cabal-syntax with ~60K LOC and several dozen modules and active contributors community.

**Comment by ffaf1** [comment]
> But it's not clear to me that anyone has a reliable and exhaustive reporting of *all* API changes.

If migrating is not trivial — this seems to be the case — as a user I would be quite happy to see a migration guide.
Cabal devs/managers resources are finite, so PR authors need to help with foresight on what might throw a spanner in our users’ codebases.

**Comment by ffaf1** [comment]
This is fantastic and I will incorporate this via a PR as soon as the weekend kicks in.
Thanks @ulidtko!
