### ISSUE TITLE
cabal install buries compiler warnings in logs, making them less obvious

### ISSUE THREAD

**Issue by joeyadams** [haskell/cabal#1062]
When you `cabal install` a package or set of packages, it generates per-package build logs and puts them in `~/.cabal/logs`.  It no longer prints these build messages directly.  I guess this is needed for parallel build support.

This is neat, but has a terrible side effect: compiler warnings are no longer obvious, except in one's own individual package built with `cabal build`.  This means:
- Most users won't see compiler warnings in upstream packages, meaning they're less likely to get reported and fixed.
- Building a collection of local packages (e.g. `cabal install ./Cabal ./cabal-install`) buries compiler warnings in log files, making them less obvious.

Another side effect is that it hides progress.  Some modules take inordinately long to build (e.g. `Crypto.CPoly` in [crypto-api](hackage.haskell.org/package/crypto-api)).  It'd be nice to see which ones those are.

I don't know the best way to solve this, but here are some ideas:
- Print the path to the log file.  Instead of:
  
  ```
  Building cereal-0.3.5.2...
  ```
  
  Say:
  
  ```
  Building cereal-0.3.5.2 ( /home/joey/.cabal/logs/cereal-0.3.5.2.log )
  ```
- Summarize build results in output:
  
  ```
  Installed cereal-0.3.5.2 (3 warnings)
  ```
  
  or perhaps:
  
  ```
  Installed cereal-0.3.5.2 (3 warnings; see /home/joey/.cabal/logs/cereal-0.3.5.2.log )
  ```
- Forward any compiler errors and warnings to output, at least by default.
- When `-j1` is used, and when the output medium supports it: print the name of the module currently being built, and modify it in-place (e.g. `"\rBuilding Crypto.CPoly\e[K"`).  This would look pretty slick.

**Comment by BardurArantsson** [comment]
I may be off my rocker here, but couldn't this be solved rather easily by just (atomically) copying the whole log file to stdout post-build (of each package)? Possibly via an option to cabal-install?

It would definitely solve the case that I'm personally interested in, namely seeing warnings for a set of co-dependent packages that I'm developing where I use "cabal install dir1 dir2 dir3 ..." to build all of them together (with a coherent set of dependencies).

**Comment by BardurArantsson** [comment]
Alright, so as far as I can tell just printing the logs post-each-job should be quite a simple modification to printBuildResult in Install.hs in cabal-install. As this is an 80% solution that works for me, I'll try to make that work and submit a PR.

AFAICT there's no parallelism involved here, and so it should be fine without any explicit locking anywhere.

Any comments, questions, doubts, etc.?

Btw, should this be behind an option? (I would prefer not having it behind "verbosity" since that could potentially induce all manner of ther output.)

**Comment by BardurArantsson** [comment]
(Oh, yes. Personally, I wouldn't want this behind an option since it just harmonizes what happens with -j1 vs. -jN, but if that's a requirement for getting it in, I'm happy to add it :))

**Comment by ulysses4ever** [comment]
v1 is deprecated. Should this be closed?

**Comment by Mikolaj** [comment]
Yes, I'm afraid we won't be able to work on that and v2- has even greater problems in this area. :) Closing.
