### ISSUE TITLE
Cabal treats url with trailing whitespace in import `cabal.project` file as a file path

### ISSUE THREAD

**Issue by theGhostJW** [haskell/cabal#10622]
**Describe the bug**

Cabal treats url with trailing whitespace in import `cabal.project` file as a file path

**To Reproduce**

When following along with: [the users guide](https://cabal.readthedocs.io/en/stable/nix-local-build.html#how-can-i-have-a-reproducible-set-of-versions-for-my-dependencies)

1. Add the following to the cabal.project file:

```
packages: .
import: https://www.stackage.org/nightly-2024-12-05/cabal.config 
```

Note: there is a trailing space at the end of the url

2.
```
$ cabal build .
```
=> An error similar to the following is emitted:

```
/home/john-walker/repos/pyrethrum/https:/www.stackage.org/nightly-2024-12-05/cabal.config : withBinaryFile: does not exist (No such file or directory)
```
3. delete the trailing white space.
4. try build again
```
$ cabal build .
```
=> build proceeds as expected

**Expected behavior**

The current behaviour is confusing if you don't notice the white space. A better UX would be to:
1. automatically trim the url OR
2. emit a specific error pertaining to the trailing space

**System information**
 - Operating system: Ubuntu 24.04.1 LTS
 - cabal: cabal 3.12.1.0 
 - ghc:  GHC   9.8.4

**Comment by philderbeast** [comment]
I can reproduce this.

**Comment by philderbeast** [comment]
We're relying on `Network.URI.parseURI`:

```
$ cabal repl cabal-install
...
ghci> import Network.URI
ghci> parseURI "https://www.stackage.org/nightly-2024-12-05/cabal.config"
Just https://www.stackage.org/nightly-2024-12-05/cabal.config
ghci> parseURI "https://www.stackage.org/nightly-2024-12-05/cabal.config "
Nothing
```

**Comment by philderbeast** [comment]
> A string is a valid URL potentially surrounded by spaces if, after stripping leading and trailing whitespace from it, it is a valid URL.
> W3C/HTML5/[URLs](https://www.w3.org/TR/2010/WD-html5-20100624/urls.html)

**Comment by philderbeast** [comment]
I tested this on `cabal-install` versions; `3.8.1.0`, `3.10.1.0`, `3.10.2.0`, `3.10.3.0` and `3.12.1.0`. They all reported an error of "withBinaryFile: does not exist (No such file or directory)", something like this:

```
$ ~/.ghcup/bin/cabal build all --dry-run --project-file=cabal.tabs-and-spaces.project
/home/.../cabal/https://www.stackage.org/nightly-2024-12-05/cabal.config
: withBinaryFile: does not exist (No such file or directory)
```
