### ISSUE TITLE
cabal sdist is missing globbed extra-source-files on cabal HEAD

### ISSUE THREAD

**Issue by TeofilC** [haskell/cabal#10653]
**Describe the bug**
I was trying to build `ghc-events` with cabal-head through haskell-ci. This uses `cabal sdist` to ensure that it contains all necessary code. But it looks like some files are missing.

**To Reproduce**
See: https://github.com/haskell/ghc-events/actions/runs/12411837954/job/34650351445?pr=113

1. Or checkout https://github.com/haskell/ghc-events.
2. use `cabal sdist`, then unpack that and `cd` into it
3. `cabal test all` fails with a missing test data file

Note that we have this in our cabal file:
```
extra-source-files: include/EventLogFormat.h
                    test/*.eventlog
                    test/*.reference
                    test/Utils.hs
                    test/stop.hs
```

**Expected behavior**
cabal should correctly include everything picked up by the glob.

**Comment by geekosaur** [comment]
cc @parsonsmatt

**Comment by TeofilC** [comment]
Actually taking the version of `cabal` from `master`, I'm struggling to reproduce this. Perhaps the version from ghcup might be older?

**Comment by TeofilC** [comment]
I can see that the prerelease ghcup picks up is 2 months old (https://github.com/tweag/ghc-wasm-bindists/releases/download/20241019T164140/cabal.tar.xz).

I downloaded that and I still can't reproduce it locally. I have a feeling this is a bug in haskell-ci rather than cabal.

So I'm tempted to close this one. Sorry for the noise folks!

**Comment by ulysses4ever** [comment]
No worries! Keep us posted if it ends up being a cabal bug after all.
