### ISSUE TITLE
Prereleases not updating GitHub release

### ISSUE THREAD

**Issue by TeofilC** [haskell/cabal#10652]
It looks like the `cabal-head` release hasn't been updated since Oct 3 https://github.com/haskell/cabal/releases/tag/cabal-head

Yet the pipelines on `master` seem to be succeeding and claim to be updating it, eg, https://github.com/haskell/cabal/actions/runs/12399481693/job/34618533301

**Comment by geekosaur** [comment]
Hm. It also says it updated the artifacts as the prerelease job shows, even though the metadata says it's still for an old commit.

**Comment by TeofilC** [comment]
I'm suspicious that it's not actually being updated because I don't see https://github.com/haskell/cabal/issues/10653 using those artifacts but I am seeing it using the ones I'm getting from the HEAD commit manually

**Comment by TeofilC** [comment]
Actually I think I'm mistaken. `diff` tells me they are identical

**Comment by geekosaur** [comment]
I think we're using a buggy release action, since it should be updating the metadata. I'm going to look for alternative actions. (We switched to the current action because the one we were using is unmaintained.)

**Comment by geekosaur** [comment]
Also: @ulysses4ever, I know you disagree with its scope, but I think we really should land #10541; if nothing else, it would make it easier to verify what commit these prereleases are on. The previous behavior of this particular release action had it supposedly making prereleases, but they were all of the same old commit.

**Comment by ulysses4ever** [comment]
This is a dup https://github.com/haskell/cabal/issues/10537

**Comment by geekosaur** [comment]
I had it flagged as draft, for one. It's now marked as ready for review.

**Comment by ulysses4ever** [comment]
@TeofilC do you have energy to resubmit my https://github.com/ulysses4ever/cabal/commit/de17531569b25c4f4b46064e675bb601603930d6 to fix this issue? I accidentally killed the accompanying PR #10540 (which didn't get any attention in weeks) by resetting my fork, and now someone has to start over...

**Comment by TeofilC** [comment]
@ulysses4ever sure I'd be happy to rebase that and make a PR

**Comment by TeofilC** [comment]
Resolved by https://github.com/haskell/cabal/pull/10654
