### ISSUE TITLE
cabal init / cabal check inconsistency in allowed licenses

### ISSUE THREAD

**Issue by dudebout** [haskell/cabal#1074]
`cabal init` allows me to specify a license that it does not recognize, by using option 11. However, `cabal check`, which is used by hackage, rejects an unrecognized field, such as ISC.

**Comment by colinwahl** [comment]
Hi all! Has any consensus been reached on where to go with this issue?  I would like to begin working on this, if a direction has been decided on.

**Comment by 23Skidoo** [comment]
IIRC @dcoutts still thinks that restricting the set of allowed licenses is a good idea.

**Comment by colinwahl** [comment]
So getting rid of support for Unrecognized Licenses?

**Comment by 23Skidoo** [comment]
Not in the .cabal parser (because backwards compat), but changing `cabal init` is OK.

**Comment by ezyang** [comment]
@colinwahl Yeah. It's a bit goofy because you just fixed the code to handle unparseable unrecognized licenses better, and now you are going to delete the code, but if you are up for it, go for it!

**Comment by gbaz** [comment]
This should be obsoleted by the spdx license work, no?

**Comment by 23Skidoo** [comment]
@phadej, do you agree?
