### ISSUE TITLE
Add support for command aliases to `cabal-install`

### ISSUE THREAD

**Issue by sol** [haskell/cabal#1089]
I propose to add support for command aliases to `cabal-install`.  This is inspired by Git's support for aliases; if I have

```
[alias]
    logk=log --graph --oneline --decorate --all
```
in `~/.gitconfig`, then running `git logk` will have the same effect as `git log --graph --oneline --decorate --all`.

Similarly I'd like to have some means to specify that e.g. running `cabal fork` has the same effect as running `cabal get --source-repository`.

Git's bash-completion script takes aliases into account, and so should we!

**Comment by 23Skidoo** [comment]
Closing in favour of #3849, which is more recent.
