### ISSUE TITLE
Automatically install dependencies before building, if needed

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1100]
If you're currently working on a package, the right way to build it is as follows:

```
cabal install --only-dependencies
cabal build
```

However, this is unintuitive and repetitive and many users end up using

```
cabal install
```

instead.

The reasons I've heard for not having build imply installing dependencies is that users might not want packages to be downloaded from the internet, unless they explicitly use cabal install. While that's a fair point, I think it should be an opt-out rather than an opt-in because:
- Users will end up have to install the dependencies anyway and there's typical no other options than installing them from Hackage.
- Many users use cabal install instead of cabal build, for the reasons given above, making it a moot point.

Once we start installing dependencies by default, the very first run of cabal build may take a long time, especially if sandboxing is used, so I think we should output the following message before installing dependencies:

> "Installing dependencies. This may take a long time if this is the first time you build this package."

/cc @dcoutts @23Skidoo

**Comment by ezyang** [comment]
nix-local-build does this.

**Comment by jneira** [comment]
I  gonna close this as made obsolete by the V2 build
