### ISSUE TITLE
Sandboxing should be used by default

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1101]
This follows the "make it correct, then make it fast" principle. Sandboxing helps with a certain class of build problems, namely problems due to two different builds overwriting each others' dependencies in the shared package database. This problem shows up as a dangerously sounding cabal warning message, mentioning the `--force-reinstalls` flag.

Sandboxing is an imperfect solution to this problem, requiring more rebuilding of packages than strictly necessary. A final solution would involve something like a Nix-style, append-only package database. The Nix solution is being worked on, as part of GSoC, but it's a difficult problem and it requires more wide-reaching changes (e.g. to ghc, ghc-pkg, ghci, and cabal). Since sandboxing is working today (with a few minor tweaks yet to be done) and it can be transparently replaced with a better solution once we have one, I think we should enable it by default in 1.18.

Since sandboxing will result in more rebuilding, we should also enabled parallel builds by default, as they typically speed up builds by a factor of 2. Finally I think we need to improve messaging. We could use:

> "Installing dependencies. This may take a long time if this is the first time you build this package."

Adding sandboxing by default also makes it easier to depend on unreleased versions of packages, as it has an `add-source <dir>` sub-command for managing those.

This would be a big change so we should think it over carefully before we do it.

/cc @dcoutts @23Skidoo

**Comment by hvr** [comment]
For the record, the original premise of this ticket has changed, i.e. the  nix-style package db is becoming a reality:

http://blog.ezyang.com/2015/08/help-us-beta-test-no-reinstall-cabal/

**Comment by ezyang** [comment]
Yes, I think this ticket is obsolete now. s/new-build/build/ is what we should be aiming for now.
