### ISSUE TITLE
Solver does not explain why dependencies are being reinstalled

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1111]
A user [reported](https://pay.reddit.com/r/haskell/comments/137156/this_is_unacceptable_cabal/) the following build failure, with a clean platform install:

```
> cabal install cabal-dev --global
Resolving dependencies...
In order, the following would be installed:
tar-0.3.2.0 (new package)
transformers-0.2.2.0 (new version)
mtl-2.0.1.0 (new version)
parsec-3.1.3 (reinstall) changes: mtl-2.1.2 -> 2.0.1.0
network-2.3.2.0 (new version)
HTTP-4000.2.6 (new version)
cabal-dev-0.9.1 (new package)
cabal.exe: The following packages are likely to be broken by the reinstalls:
network-2.3.1.0
haskell-platform-2012.4.0.0
cgi-3001.1.7.4
HTTP-4000.2.5    
```

Ultimately cabal-dev's dependencies are to blame here, but nowhere in the out is it clear why parsec is being reinstalled. It's not clear in the sense that even though cabal is telling us that it's because mtl is being upgraded, it's not clear why a new mtl is being installed. Perhaps we should explain why we're not using an already installed mtl.

This might be caused by a combination of some messages not being output at the default verbosity or not being their in the first place. We should consider what changes are needed so it would be clear from the above error what caused the need to upgrade parsec.

**Comment by ezyang** [comment]
This is obsoleted by nix-local-build, which never attempts to reuse pre-existing dependencies.
