### ISSUE TITLE
"check" warns for missing Setup.hs, but "sdist" adds one anyway

### ISSUE THREAD

**Issue by dag** [haskell/cabal#1125]
The warning therefore seems redundant to me.

**Comment by eightyeight** [comment]
I assume the fix involves removing this check? Or only performing the check if the distribution type is not `Simple`?

**Comment by phadej** [comment]
https://github.com/haskell/cabal/issues/2629 is related

**Comment by 23Skidoo** [comment]
Fixed by #2657.
