### ISSUE TITLE
Support for rebuilding packages broken by a build

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#1144]
Currently, performing a `cabal update` after a substantial number of packages have been installed is a source of frustration for many users as package breakage resulting from subsequent builds is common place. Cabal gaining the ability to detect and report this breakage before the installation is perform helps alleviate a lot of this frustration. 

That being said, sorting out what to do when breakage is detected is left up to the user. A common pattern for resolving breakage is to add the to-be-broken packages to the installation list. Currently, this must be done manually by the user. However, given that cabal knows precisely which packages will be broken, it should be easy to implement a flag (e.g. `--rebuild-broken`) instructing Cabal to attempt adding any packages which will be broken by a build to the build list. In the event that this is not possible, Cabal can still give up before any action is taken, allowing the user to sort the situation out as they are currently required to do.

**Comment by BardurArantsson** [comment]
Isn't this entirely subsumed by sandboxes and @ezyang's recent work on being able to have multiple versions of the same package installed simultaneously?

**Comment by ttuegel** [comment]
Yes, this is subsumed by sandboxes and allowing multiple installed versions. Furthermore, the Nix-like build system will soon subsume both of those features!
