### ISSUE TITLE
Compile Paths module independently

### ISSUE THREAD

**Issue by dag** [haskell/cabal#1170]
Fay is currently experimenting with replacing the `base` package with a `fay-base` package, but this is leading to build failures in `fay-jquery` which exposes its `Paths_fay_jquery` module.  Cabal tries to build that module with the same flags as the other modules, but it's importing lots of modules from the `base` package that `fay-base` isn't exporting.

Besides Fay, this is not the first time a problem has appeared due to Cabal building this generated module with the same flags as the library; these bugs are all a result of this: #907 and #1000, #994, #1137.

The module itself is written with assumptions about how the `.cabal` file is written, assumptions that quickly break down in different setups.

**Comment by tfausak** [comment]
👍 I just ran into this problem by combining `OverloadedStrings` and `RebindableSyntax`. See [this Gist](https://gist.github.com/tfausak/0128f9d3353f8ffe345a78e2c636942c) for a small, complete example.

**Comment by jneira** [comment]
* Closing in favour of #7761 as the root cause is the use of the standard prelude in the autogen modules
* Feel free to reopen or comment in such issue
