### ISSUE TITLE
--reinstall being ignored for --only-dependencies

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#1175]
I get the following with `cabal-install-1.16.0.3`:

```
$ cabal install --only-dependencies --reinstall

Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
```

Appending more `--reinstall`s does not help.

**Comment by eigengrau** [comment]
I would also welcome it it if this combination of options would work (sans boot libraries), at least as a work-around until Cabal can detect missing components in registered packages. Currently, it’s somewhat problematic if one wants to do static builds inside of a sandbox when some dependencies are installed by the OS distribution and are missing static libraries. Currently, the only way to deal with this would be to set-up a package database containing only the boot libraries and using this in place of the global one. If `--reinstall --only-dependencies` could be used to this effect this would certainly be less inconvenient.

**Comment by gbaz** [comment]
closing as obsolete
