### ISSUE TITLE
Support pure test packages

### ISSUE THREAD

**Issue by feuerbach** [haskell/cabal#1186]
Currently if I have a package description file that defines just a test suite (without a library), I get the message

    % cabal configure --enable-tests
    Resolving dependencies...
    Configuring smallcheck-tests-0.7...
    cabal: No executables and no library found. Nothing to do.

I suppose there are no technical issues with building and running such tests?

The reason I want to do this is that the test for smallcheck also depends on test-framework-smallcheck, which in turn depends on smallcheck. If I put the test suite description into `smallcheck.cabal`, the build command will produce the following error:

    '/opt/ghc762rc/bin/ghc' '--make' '-no-link' '-fbuilding-cabal-package' '-O' '-static' '-odir' 'dist/build/test/test-tmp' '-hidir' 'dist/build/test/test-tmp' '-stubdir' 'dist/build/test/test-tmp' '-i' '-idist/build/test/test-tmp' '-itest' '-idist/build/autogen' '-Idist/build/autogen' '-Idist/build/test/test-tmp' '-optP-include' '-optPdist/build/autogen/cabal_macros.h' '-hide-all-packages' '-package-db' 'dist/package.conf.inplace' '-package-id' 'base-4.6.0.1-4957e18cdbf85bf6a8e2f1860a9aa808' '-package-id' 'test-framework-0.8-0ce644c59b770473a8dff65350e80268' '-package-id' 'test-framework-smallcheck-0.2-c3c898b7eb147b3e3fd55e4e402b186d' '-package-id' 'smallcheck-0.7-inplace' '-XHaskell98' 'test/test.hs'
    <command line>: cannot satisfy -package-id smallcheck-0.7-inplace: 
        smallcheck-0.7-inplace is shadowed by package smallcheck-0.7-531c49bb37bfd4fbc8779021d10a9776
        (use -v for more information)

**Comment by ttuegel** [comment]
This would be helpful to resolve #960.

@BardurArantsson This would be a good task for a newcomer. There isn't any technical problem to resolve here, it's just a matter of flipping a switch in the source code.

**Comment by ttuegel** [comment]
Here are a few notes about what must be done before we close this issue.

- [ ] Relax the constraint which requires a library or an executable to be defined in the package description. The package description should be considered valid if a library, an executable, a test, or a benchmark is defined.
- [ ] Trying to install a pure test or pure benchmark package should exit with a "nothing to do" message because there is nothing to install.

**Comment by 23Skidoo** [comment]
Looks like this was fixed by #2699.
