### ISSUE TITLE
Construct a sandbox from another package repository

### ISSUE THREAD

**Issue by mightybyte** [haskell/cabal#1196]
I routinely work on multiple projects that depend on each other but that I don't want to share a sandbox.  It would be a huge time saver if there was a way to do "cabal sandbox-install" but have it get already installed packages from the old cabal --user or --global repositories (or maybe even other sandboxes) without having to rebuild them.  In my use case, I would want the package to be copied to the new repository so that this sandbox still works independent of the other repository.

**Comment by christiaanb** [comment]
It was pointed out to me that I should perhaps leave a comment in this thread. `Cabal 1.22` is shipped with _preliminary_ support for so-called relocatable (or prefix-independent) packages. What his currently enables you to do is to have a completely _relocatable_ `.cabal-sandbox` directory. This means you can move/copy the entire `.cabal-sandbox` directory anywhere you want on your machine.
To get a relocatable `.cabal-sandbox` dir just do:

* `cabal sandbox init`
* `cabal install --dependencies-only --enable-relocatable`

I know this doesn't get you completely what you describe in the issue, but I'm sure this new aspect of sandboxes will help in ultimately achieving it.

**Comment by mietek** [comment]
@mightybyte: [Halcyon](https://halcyon.sh/) supports building sandboxes based on previously-built sandboxes.

See the [Halcyon tutorial](https://halcyon.sh/tutorial/#build-the-sandbox) for an example.

This is made possible by keeping the sandbox at a pre-defined sandbox directory, and swapping the contents of this directory between projects.  The trade-off is, only one build can be performed concurrently.

@christiaanb: Support for relocatable packages is a well-appreciated step forward. Thank you.

**Comment by phadej** [comment]
Sandbox are going to be removed.
