### ISSUE TITLE
Implement `cabal sandbox hc-pkg` / `cabal sandbox buildopts`

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1200]
`cabal-dev` has a command `ghc-pkg` which is handy for manipulating the sandbox package DB using `ghc-pkg`:

```
cabal-dev ghc-pkg unregister foo
```

It'd be nice if `cabal sandbox` also supported this feature (see discussion in #1195). Additionally, there is `cabal-dev buildopts` that extracts the options that would be passed to the compiler when building.

**Comment by phadej** [comment]
sandbox functionality is removed.
