### ISSUE TITLE
cabal-install gets multiarch wrong

### ISSUE THREAD

**Issue by bos** [haskell/cabal#1225]
I received a [bug report against the hashable package](https://github.com/tibbe/hashable/issues/55#issuecomment-14339593) that I tracked down to `cabal-install` not noticing that the `ghc` in its search path is not targeted at the same architecture as it is.

In my test case, I have a 64-bit `cabal` executable, and a 32-bit `ghc` executable. The sections of the `hashable.cabal` file that are i386-dependent are not processed by `cabal-install`, so it builds a partially broken package that fails to link correctly.

Here's the section that is missed:

  if arch(i386)
    C-sources:       cbits/siphash-sse2.c

**Comment by ttuegel** [comment]
Closing this. There has been no response in more than 2 years.
