### ISSUE TITLE
Remove duplication between D.S.Haddock and D.C.Haddock

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1233]
As @kowey observed in #1231, there is some duplication between [`Distribution.Client.Haddock`](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Haddock.hs) and [`Distribution.Simple.Haddock`](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Haddock.hs). It'd be nice to get rid of it.

Quoting @dcoutts:

> The thing in cabal-install is about generating an index of all the packages you have installed. Yes, I guess there's some opportunity for sharing there. If anyone wants to do that, then follow the model we have for D.S.Program.*, e.g. the HcPkg and GHC modules there. They define program invocations and some handy utilities for calling the programs in various ways.

**Comment by Mikolaj** [comment]
I'm taking the liberty of closing this ticket due to its age and inactivity. Please open a new one if/when you are able to reproduce with an up to date cabal (assuming you are still using the v1- cabal API). Thank you for the report!
