### ISSUE TITLE
There's no way to move `setup-exe-cache` to another directory

### ISSUE THREAD

**Issue by nagisa** [haskell/cabal#1234]
According to the https://github.com/haskell/cabal/pull/958#issue-5317676 setup-exe-cache is hardcoded to `~/.cabal/setup-exe-cache` and there's no way to change it. Looking at the code, path building didn't change and it is still hardcoded.

Making setup-exe-cache movable is a prerequisite for #680

**Comment by Mikolaj** [comment]
This is likely to be solved by #680 and related PRs.
