### ISSUE TITLE
cabal-install should rebuild dependants when a package is upgraded

### ISSUE THREAD

**Issue by bos** [haskell/cabal#124]
(Imported from [Trac #131](http://hackage.haskell.org/trac/hackage/ticket/131), reported by bringert on 2007-05-23)

Currently, when cabal-install upgrades a package, other packages that depend on it are not rebuilt.

Scenario: You have package A-1.0 and A-2.0, and B-1.0 which depends on A. B-1.0 is compiled against A-1.0. C then depends on A and B, and GHC picks A-2.0 and B-1.0. This breaks, because C now uses A-2.0 and B-1.0 uses A-1.0.

This could be made less of a problem if cabal-install would be able to reinstall all packages which depend on the new package. This might not always be what you want, so there should be a flag to turn it off.

Logic: When installing a new package Foo-X.Y, then each installed package which depends on Foo with a version range that includes X.Y should be reinstalled.

**Comment by jsl** [comment]
This issue appears to be resolved based on comments. I propose closing, and re-opening a new issue if one is found. 

/cc @tibbe
