### ISSUE TITLE
Package check needs to allow license AllRightsReserved

### ISSUE THREAD

**Issue by dcoutts** [haskell/cabal#1240]
The package checking code checks for license things. It currently assumes that distribution is public distribution and so disallows the AllRightsReserved licence, but of course there's also the case of internal/private distribution and there AllRightsReserved would be fine.

The ideal thing to do would be to only complain about there being no license specified, but that'll need a change to the type because we currently do not distinguish between no license and AllRightsReserved.

This affects the hackage server which uses the Cabal lib's package checks.

**Comment by tfausak** [comment]
:+1: 

> The ideal thing to do would be to only complain about there being no license specified, but that'll need a change to the type because we currently do not distinguish between no license and AllRightsReserved.

I think #2147 resolved this ambiguity.

**Comment by ttuegel** [comment]
Appears to be resolved on the Cabal side.
