### ISSUE TITLE
Add a `cabal-default-dir` setting to `~/.cabal/config`

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1242]
See the discussion in #1126. We need a general "where cabal puts its misc other files" entry in the config for things that don't have a specific entry (like setup exe cache). This will also allow to remove some things like `world-file`.

**Comment by m-renaud** [comment]
Has this been made obsolete by general cabal changes in the last 5 years? If so can we either close this out, or update it given the current architecture? thanks!

**Comment by ulysses4ever** [comment]
As m-renaud, I too doubt that this is still relevant and vote to close.

**Comment by Mikolaj** [comment]
No objections seen. Closing. Thank you all.
