### ISSUE TITLE
cabal upload succeeds but doesn't terminate...

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1260]
Hey All, 

i've been a recent build of cabal-install head  (built from head Mar 21st), and i noticed a funny problem when uploading a package to hackage today. Namely that cabal-install doesn't return / terminate after  successfully uploading.... 

my local code isn't using cabal sandbox for that project, if thats any help

**Comment by ttuegel** [comment]
Was this bug ever reproduced?

**Comment by 23Skidoo** [comment]
I never had time to look into it.

**Comment by ttuegel** [comment]
@cartazio I'm closing this because it is so old and unconfirmed. You know where to find me if it continues to be a problem.
