### ISSUE TITLE
cabal init should read default values from configuration file

### ISSUE THREAD

**Issue by Toxaris** [haskell/cabal#1270]
I would like to use the cabal configuration file to set _default values_ for some of the information `cabal init` collects. For example, I want `cabal init` to know my name, my email adress, my preferred license, etc. Note that I want to set only the defaults, not the actual values, so `cabal init` should still ask me.

**Comment by l8l** [comment]
Is it now possible to provide default values for author, mail, synopsis, category and other values in the .cabal file that is created by cabal init? I have not been able to find this option.

**Comment by Mikolaj** [comment]
No idea. Experimenting, design and, once it's discussed, a PR would be very welcome.

**Comment by ulysses4ever** [comment]
Author and maintainer’s email are being taken from your git config currently (cabal 3.8.1). The rest is still up to the caller of the command. Though, other fields are not really generalizable I think, but maybe I don’t quite understand your use case.

There’s a workaround for this, I think: most (all?) fields can be set via command-line arguments of `cabal init`. So, you can create a shell alias for calling `cabal init` with the desired values. (Let me know if you want an example — I’ll need to get to a computer to cook one).

By the way, I think we could close this issue on the grounds of cabal init reading git config now.

**Comment by l8l** [comment]
The main use case is to get a file with less boiler-plate code. Everytime I use cabal-init, I have to delete some comments in the .cabal file that suggest to add some synposis, for instance. I would prefer a clean file and hoped to be able to remove those comments that are auto-generated by inserting default values. I might want also want author and mail defaults different from the git-config and would like to configure them e.g. in the cabal config. 

But yes, your idea to use a shell alias for cabal init with additional arguments seems good to me. An example would be appreciated.

**Comment by Mikolaj** [comment]
@l8l, how about a little challenge and an occasion to contribute for you? Would you like to sketch that workaround (the alias command in bash is just `alias`), using the output of `cabal init --help` to glean the correct option names, and determine if anything is missing? Optionally, suggest what extra options `cabal init` should take to make the workaround complete?

**Comment by ulysses4ever** [comment]
@l8l one more thing: you probably want to use the `-m` flag with `cabal init` so that you don't get the abundant comments in the resulting file.

Here's an example:

```
cabal/t1270-init-config/A 
❯ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 

cabal/t1270-init-config/A 
❯ cabal init -n -m --lib --author="John Doe" --email="john@doe.com" --synopsis="My great package" --category="Music" --license="MIT"
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.8
[Log] Creating fresh file LICENSE...
[Log] Creating fresh file CHANGELOG.md...
[Log] Creating fresh directory ./src...
[Log] Creating fresh file src/MyLib.hs...
[Log] Creating fresh file A.cabal...
[Info] You may want to edit the .cabal file and add a Description field.


cabal/t1270-init-config/A 
❯ cat A.cabal
cabal-version:   3.8
name:            A
version:         0.1.0.0
synopsis:        My great package
license:         MIT
license-file:    LICENSE
author:          John Doe
maintainer:      john@doe.com
category:        Music
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  MyLib
    build-depends:    base ^>=4.17.0.0
    hs-source-dirs:   src
    default-language: Haskell2010
```

**Comment by l8l** [comment]
Thanks @ulysses4ever this is great and the -m flag is indeed very helpful. Together with the alias, this is a sufficiently good solution for me. @Mikolaj yes, perhaps I should've looked into the --help options earlier and done what you wrote.

**Comment by Mikolaj** [comment]
@l8l, well done, that alias is going to be helpful for whomever searches the issue tracker looking for a solution to any similar problem. It's also helpful to devs, because we now know we don't need any more options to `cabal init` for now. Do you think this ticket can be closed now that this investigation of ours has concluded?

**Comment by l8l** [comment]
From my side yes, though I can not speak for everyone because it was not me who opened the issue originally.

**Comment by Mikolaj** [comment]
No objections, so let me close. Thank you everybody.

**Comment by andreasabel** [comment]
The OP was not implemented so closing this as "not planned" rather than "completed".

**Comment by Toxaris** [comment]
> I can not speak for everyone because it was not me who opened the issue originally.

I suspect the alias solution:

1. does not work on Windows
2. does not implement the "note that I want to set only the defaults, not the actual values, so cabal init should still ask me" aspect

I'm no longer doing any Haskell though, so I don't mind whether this is closed or not.

(Random story: the reason I don't do Haskell anymore is that when I left academia to work as a Scala developer, my boss turned out to be an OCaml person, so I'm actually doing some ReasonML now. If only there would be fancy modules *and* fancy types ...)
