### ISSUE TITLE
Implement `install --reinstall-revdeps`

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1298]
Right now, if the install plan requires us to reinstall some packages and reinstallation is likely to break some of their reverse dependencies, [we fail with an error in `checkPrintPlan`](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Install.hs#L425). However, if one lists those packages as arguments for the `install` command, the solver usually finds a way to reinstall them without introducing breakage.

It'd be nice if instead of having to list them manually the user could just say `install --reinstall-revdeps` and have that happen automatically. Imaginary workflow:

```
$ cabal install foo
In order, the following would be installed:
bar-1.0 (reinstall)
cabal: The following packages are likely to be broken by the reinstalls:
baz-1.0
Use --reinstall-revdeps if you want me to try to reinstall all reverse
dependencies automatically. Use --force-reinstalls if you want to force
reinstallation (likely breaking the packages listed above).

$ cabal install --reinstall-revdeps foo
Installing bar-1.0...
Installing baz-1.0...
Installing foo-1.0...
```

This feature would be also useful for sandboxes since we tend to reinstall a lot and currently have to resort to some hacky workarounds. 

/cc @kosmikus

**Comment by grayjay** [comment]
I don't think this feature is necessary with new-build, which avoids destructive reinstalls.
