### ISSUE TITLE
setup sdist places implementation-dependent preprocessor output in the source bundle

### ISSUE THREAD

**Issue by bos** [haskell/cabal#130]
(Imported from [Trac #137](http://hackage.haskell.org/trac/hackage/ticket/137), reported by ross on 2007-06-02)

e.g. happy -agc output in the haskell-src package.

Suggested new scheme: [http://www.haskell.org/pipermail/cabal-devel/2007-May/000529.html](http://www.haskell.org/pipermail/cabal-devel/2007-May/000529.html).

**Comment by ezyang** [comment]
I milestoned this _|_ because, although this is a clear bug, people mostly seem to deal.

**Comment by typedrat** [comment]
#5389 ended this going forward.
