### ISSUE TITLE
how to define a MIN_VERSION_Cabal(x,y,z) macro?

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1319]
I'm trying to get the LLVM library bindings to build on both new and old Cabal versions... and I'm finding myself unable to do the "obvious" conditional compilation thing here.

Is this a known quirk / problem? 

Whats good workaround?

**Comment by 23Skidoo** [comment]
`setup-depends` [are now implemented](http://www.well-typed.com/blog/2015/07/cabal-setup-deps/).
