### ISSUE TITLE
packages share dependencies across executables

### ISSUE THREAD

**Issue by dmwit** [haskell/cabal#1326]
I'm actually not sure whether this is a bug or not, but it seemed odd, so I thought I'd make a note of it here. I discovered by accident that when a package builds several executables, the dependency lists are shared: I can list, say, the containers package in one executable's build-depends section, then import Data.Map freely in the remaining executables' sources. Small reproducing package is attached.

**Comment by ttuegel** [comment]
I marked this `easy` because the only thing left to do is integrate the provided test suite.

**Comment by eightyeight** [comment]
To clarify, should the test suite test that the packages as given _do not_ build when specifying `cabal-version >= 1.7.1`? Or that it _does_ build when you don't? Or both?

**Comment by BardurArantsson** [comment]
Both, I would think. The latter would guard against regressions.

**Comment by ezyang** [comment]
There's already a test that does this, BuildDeps/SameDepsAllRound so I'm going to close this ticket.
