### ISSUE TITLE
Add (functional) tests for sandboxes

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1342]
It'd be nice to have automated tests for the sandbox feature. [`cabal-dev`'s test suite](https://github.com/creswick/cabal-dev/tree/master/test) can be used as a starting point.

**Comment by BardurArantsson** [comment]
AFAICT there are now tests for sandboxing...? At least there's a UnitTests/Distribution/Client/Sandbox.hs file. 

If the tests are not complete (and having just peeked at the file, they aren't), please file concrete issues for each of the (missing) tests.

Can we close this? (Once subsidiary tests have been filed.)

**Comment by BardurArantsson** [comment]
(Meta-comment: This is the kind of thing that needs to be addressed during review: If a test is missing, ask for an Issue. If an issue is missing, ask for a Test. It's not rocket surgery.)

**Comment by phadej** [comment]
sandbox functionality is removed.
