### ISSUE TITLE
An 'add-source' package in sandbox always added as constraint

### ISSUE THREAD

**Issue by hesselink** [haskell/cabal#1362]
If you 'add-source' (and possible install) a package in a sandbox, it seems to always be added as a 'global constraint'. This can cause weird errors, and make other packages impossible to install.

For example, we have a fork of `heist` which I `add-source`d. I later tried to build another package in the same sandbox, which requires an old `snap`, which needs an older `heist`. This made it impossible to install the package, since the new `heist` was always added as a global constraint.

Might be related to #1299?

**Comment by phadej** [comment]
sandbox functionality is removed.
