### ISSUE TITLE
No package is an island

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1367]
As described in @tibbe's "Cabal of my dreams" [blog post](http://blog.johantibell.com/2012/03/cabal-of-my-dreams.html), we'd like to move from a package-centric model to a source-tree based model.

Quoting @tibbe's post:

> We frequently have to work on multiple dependent packages at once and thus we also need a way to build them together, without registering the by-products in some shared package database. For example, given this directory structure

>```
src
  |-- foo
  |  | -- foo.cabal
  |-- bar
     | -- bar.cabal
```
> where `foo` is a package that depends on `bar`, I should be able to do

>```
cd src
cabal build foo
```

>and that better traverse the directory structure, find, and build dependencies and use them when compiling foo.

>Aside: This could be implemented in a few different, more or less explicit, ways e.g. by specifying the directories used to search for dependencies explicitly, as in

>```
cd src/foo
cabal build --root-dir=~/src
```

**Comment by ezyang** [comment]
This is solved by `cabal.project` files.
