### ISSUE TITLE
cabal haddock does not copy required file

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#1369]
When running `cabal haddock` on my project, which contains:

`Mymodule.hs`:

```haskell
$(doSomeThWith "Somefile.template")
```

I get the error:

```
dist/build/tmp-4986/src/Mymodule.hs:1:1:
    Exception when trying to run compile-time code:
      /home/niklas/.../Somefile.template: openFile: does not exist (No such file or directory)
      Code: doSomeThWith "Mymodule.template"
```

How can I tell `cabal haddock` that this file should be made available in that temporary dir?

I've tried `extra-source-files` and  `data-files` so far, but to no avail.

**Comment by ttuegel** [comment]
You need to specify `extra-source-files: Somefile.template`. Because Template Haskell can perform arbitrary IO, there is no way we could possibly track this.

**Comment by nh2** [comment]
> You need to specify extra-source-files: Somefile.template.

Ah, good point.

It would be great if GHC could add this as a hint if the `building-cabal-package` option is passed.
