### ISSUE TITLE
Installs in sandbox 'forgotten' if final build fails

### ISSUE THREAD

**Issue by hesselink** [haskell/cabal#1375]
If you `add-source` some packages in a sandbox, and they get installed as dependencies of a package whose build ultimately fails, they are reinstalled afresh the next time you issue an install command. For example:
- Have packages `a` and `b`, where `b` depends on `a`.
- `cabal sandbox add-source a/`
- `cabal install b/`

This installs `a` and then `b`. If `b` has e.g. a type error, you fix it and issue another `cabal install b/`, `a` also gets installed again, even though it was already installed and nothing about it changed.

**Comment by acfoltzer** [comment]
Is this now on track for 1.24? I have to do a bunch of workarounds currently to avoid lost time due to this, like scripting smaller install plans together to avoid packages that might be temporarily broken during development.

**Comment by ygale** [comment]
Recording here the simple workaround that a lot of people already know:

Unless you really do expect the external source to change often and require rebuilds, use `add-source --snapshot`. If at some point later you do need it rebuilt, you cad do `delete-source` and then `add-source` without `--snapshot`. If you just need a new version, you can do `add-source --snapshot` also for the newer version, and the solver will then consider both of them.

**Comment by 23Skidoo** [comment]
Fixed in fcabd87406effc0c265312eb38509804682e4623.
