### ISSUE TITLE
"--internal" flag for cabal haddock doesn't do anything

### ISSUE THREAD

**Issue by BruceBerry** [haskell/cabal#1409]
I've read it's supposed to pass "--ignore-exports" to haddock. However, there is no such flag in haddock anymore. There is "--ignore-all-exports" though. Passing "--haddock-options="--ignore-all-exports" to cabal haddock has the desired effect.
Instead, "--internal" does not add any extra flag to haddock (at least when it's used with --executables, which is my case) and is silently ignored. Unknown flags normally throw an error. This should either pass "--ignore-all-exports" or throw an error if you don't want to maintain the feature.

**Comment by ttuegel** [comment]
This is fixed for some time already.
