### ISSUE TITLE
Cabal should be able to produce foreign libs (shared or static)

### ISSUE THREAD

**Issue by bos** [haskell/cabal#141]
(Imported from [Trac #148](http://hackage.haskell.org/trac/hackage/ticket/148), reported by eivuokko on 2007-08-23)

GHC supports linking final executable into a DLL instead of normal executable.  Cabal should support this use, and also support specifying DEF file for exports and building an import library.

**Comment by 23Skidoo** [comment]
See #2540.

**Comment by phadej** [comment]
is this done?

**Comment by 23Skidoo** [comment]
Yep, I think this ticket can be closed given that we now have [`foreign-library`](https://www.haskell.org/cabal/users-guide/developing-packages.html#foreign-libraries).
