### ISSUE TITLE
Cabal does not report it when a package is unknown to it

### ISSUE THREAD

**Issue by jwiegley** [haskell/cabal#1414]
Steps to reproduce:

 1. Upload a brand new package to Hackage.
 2. Create a local project that depends on it.
 3. Run `cabal install --only-dependencies` in your package.

Expected:

The package "foo" is unknown, perhaps you need to run cabal update?

Actual:

```
Reading available packages...
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: myproject-0.0.0
```

Where `myproject` is the project of mine that I'm trying to build which has a dependency on the brand new package.  I get no information at all about what's wrong, or what to do to resolve it.  It's only because I've tracked this problem down before that I had any clue what the real problem was.

**Comment by ttuegel** [comment]
This is fixed.
