### ISSUE TITLE
cabal install failure message "setup: Most RTS options are disabled. Link with -rtsopts to enable them." ... is not helpful enough

### ISSUE THREAD

**Issue by markstos** [haskell/cabal#1421]
Recently, "cabal install" quite working to compile darcs for me. It was failing like this:

>  setup: Most RTS options are disabled. Link with -rtsopts to enable them.

This was message was not particularly helpful because it didn't tell me /what/ to link, or how to link it. Not all users of `cabal install` are Haskell developers. 

The actual cause of the problem would have been particularly difficult for me to guess, as the solution in this case wasn't to link anything with `-rtsopts`.

It turns out that I had this in my `.bashrc` because I need it for darcs:

```
GHCRTS=-K100M
```

Does `cabal` actually ever need this environment variable set? If not, the simplest solution to explicitly ignore it in the future. If you /do/ need to allow the variable to be set, then diagnostic message emitted should be updated to something more like this:

> setup: GHCRTS=-K100M was set in the environment, but most RTS options are disabled. If you don't know what this and didn't explicitly set it, you can try prefixing your `cabal install` command with `GHCRTS=` to explicitly unset RTS options. If did  intent to enable this RTS option for cabal, you should link XXX with -rtsopts by doing YYY to enable them.

**Comment by andreasabel** [comment]
Looks like nothing was escalated upstream, because today I got the same mysterious error today: https://github.com/BNFC/bnfc/actions/runs/3712560779/jobs/6294229897#step:21:27
```
Run $CABAL repl BNFC --with-ghc-pkg=$HCPKG -w doctest
Build profile: -w ghc-9.4.3 -O1
In order, the following will be built (use -v for more details):
 - BNFC-2.9.5 (configuration changed)
setup: '/github/home/.cabal/bin/doctest' exited with an error:
doctest: Most RTS options are disabled. Link with -rtsopts to enable them.
```

It was helpful to find this issue here explaining the cause.

**Comment by bapcyk** [comment]
I have the same error. As a temporary workaround is create a shell script called failed binary but called before it `unset GHCRTS`
