### ISSUE TITLE
unnecessary rebuilding when tests share modules declared in other-modules

### ISSUE THREAD

**Issue by coreyoconnor** [haskell/cabal#1446]
1. clone https://github.com/coreyoconnor/vty
2. cabal configure --enable-tests
3. cabal test
4. cabal test

The expectation is that no compilation is performed for the second "cabal test". On my system using Cabal 1.18 and cabal-install 1.18 this is not the case. The modules in common to each test suite listen in other-modules are all recompiled.

These modules are not part of the vty library because they have dependencies specific to testing. Which should not be part of the vty depdnencies.

This may be a configuration issue in the vty.cabal. I just have had no luck figuring out what the issue is :-)

**Comment by ezyang** [comment]
I'm pretty sure I accidentally fixed this bug in #3015.
