### ISSUE TITLE
sandbox delete-source does not uninstall the source dependency

### ISSUE THREAD

**Issue by gregwebs** [haskell/cabal#1447]
I am using the release candidate:
cabal install http://johantibell.com/files/Cabal-1.18.0.tar.gz http://johantibell.com/files/cabal-install-1.18.0.tar.gz

I had a few minor issues with delete-source:
- cabal sandbox --help does not mention delete-source

Although cabal sandbox list-sources does mention it, which is great.
- After I ran delete-source it kept using the existing sourced version of the package.

I was expecting it to also delete the existing sourced version. I could see how the current behaviour could be thought of as desirable. However, it is essentially creating build properties that are invisible to the user so I don't think it is a good default unless perhaps list-sources mentions theses pre-existing sourced versions. It was also unclear to me how I would remove that package, so I just wiped out my sandbox and re-installed everything. Perhaps I was supposed to use hc-pkg, but that option is not explained and it doesn ot respond to --help

**Comment by gbaz** [comment]
`delete-source` is documented in `help` now, along with a warning:

> delete-source:
>   Remove an add-source dependency; however, this will not delete the
>   package(s) that have been installed in the sandbox from this dependency. You
>   can either unregister the package(s) via `cabal sandbox hc-pkg unregister`
>   or re-create the sandbox (`sandbox delete; sandbox init`).

Given the direction of cabal, should that suffice to close this  ticket?

**Comment by 23Skidoo** [comment]
OK, sure.
