### ISSUE TITLE
cabal repl gets killed by interrupts

### ISSUE THREAD

**Issue by ibotty** [haskell/cabal#1448]
i often use ctrl-c to reset the line i was in in ghci. unfortunately that kills cabal repl.

**Comment by gracjan** [comment]
Note: this strikes again.

**Comment by jsl** [comment]
@gracjan which cabal version, and which interrupt are you seeing that kills cabal repl? I just tried with cabal 1.22.0, and Ctrl-C does *not* kill the repl, so this seems to be working fine for me.

**Comment by gracjan** [comment]
Unexpected: After Ctrl-C whole GHCi is terminated and bash prompt appears.

    gracjan@computer:~/Sources/xxx:master$ cabal repl
    Preprocessing executable 'xxx' for xxx-1.0...
    GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
    Prelude> :m +Control.Monad
    Prelude Control.Monad> forever (return ())
    ^C
    gracjan@computer:~/Sources/xxx:master$ 

Expected: After Ctrl-C prompt for GHCi appears again:

    Prelude> :m +Control.Monad
    Prelude Control.Monad> forever (return ())
    ^C
    Prelude>

Version of cabal:

    $ cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library 

I do not know how to check which version of `process` was this particular cabal compiled.

**Comment by gracjan** [comment]
As a success story:

    Prelude> :m +Control.Monad
    Prelude Control.Monad> :m +Control.Concurrent
    Prelude Control.Monad Control.Concurrent> forever (threadDelay 1000000)
    ^CInterrupted.
    Prelude Control.Monad Control.Concurrent> 

So success!

That was after doing:

    cabal install cabal-install --constraint 'process==1.2.2.0' --constraint 'Cabal<1.22.1.1'

(Note that Cabal==1.22.1.1 did not compile for me).

I do not know why installing 1.22 did not pull latest process 1.2.2 as dependency.

**Comment by qxjit** [comment]
Just tripped over this using cabal 1.22.2.0 with ubuntu trusty's stock ghc-7.6.3-10 package, which contains an older version of process.  Installing cabal with a newer version of process as @gracjan shows above worked, as did using a newer ghc (7.10.1) version from the ppa repository (as described here: https://www.haskell.org/downloads/linux).
