### ISSUE TITLE
Bootstrap.sh has external dependency that is not reliably updated with new releases

### ISSUE THREAD

**Issue by AaronFriel** [haskell/cabal#1457]
Hackage is wonderful, but it's not fast. Right now, `bootstrap.sh` is broken for 100% of users checking out 1.18. For many experienced users that won't be a problem, but for many others it will be a pain point, albeit temporary, that may dissuade them from using Cabal or Haskell.

So, for one thing, why does `./cabal-install/bootstrap.sh` pull Cabal-1.18 from Hackage when the library is in the same git repo? 

Here's what I did in order to install the current head release:

```
~/git/cabal$ cd ./cabal-install/
~/git/cabal/cabal-install$ ./bootstrap.sh
all sorts of errors because Hackage doesn't have the cabal library 1.18 yet
~/git/cabal/cabal-install$ cd ../Cabal/
~/git/cabal/Cabal$ ghc --make Setup
...
~/git/cabal/Cabal$ ./Setup configure --user
...
~/git/cabal/Cabal$ ./Setup build
...
~/git/cabal/Cabal$ ./Setup install
...
~/git/cabal/Cabal$ cd ../cabal-install/
~/git/cabal/cabal-install$ ./bootstrap.sh
...
HUGE SUCCESS!
```

Now, that doesn't seem sensible to me, and I don't know what to edit in the bootstrap.sh to make it just *do this*, but I think it ought to be done. No less aware user should have to get stuck trying to get Cabal from the repo because they heard 1.18 has lots of glorious new fixes and then find it Just Won't Work(tm).

**Comment by BardurArantsson** [comment]
If you want a dev install you can now use `setup-dev.sh` (or the provided `stack` configuration file if you're so inclined). If you want a non-dev install you can use "bootstrap.sh".

@AaronFriel : If you feel that this is insufficient or that it perhaps requires documentation then please re-open, but be prepared to be asked for a patch :).
