### ISSUE TITLE
Always use relative paths in Haddock documentation

### ISSUE THREAD

**Issue by liyang** [haskell/cabal#1465]
Is it not possible to always use relative instead of absolute ```file://``` URLs? (Or at least make a best-effort for Windows.) This was mentioned in #509, #1064, #1406, and committed in 544d737a23ac4d6c030b0c45bbb76f650f15b46f to cater for Windows platforms where ```C:\…``` is mistakenly interpreted as a protocol by some browsers.

As things currently stand, I cannot serve up my main Haddocks index for use when I'm ssh/VPNing into my dev machine from home. (Nor for other people in the office to use, for that matter.)

There's also a seconday issue in that Chrome forbids cookies for ```file://``` URLs, such that ```haddock-util.js``` can't keep track of which sections were collapsed: [untested workaround](https://code.google.com/p/chromium/issues/detail?id=535); [related Chrome issue](https://code.google.com/p/chromium/issues/detail?id=47416). Perhaps HTML5 local storage is the way forward there. So far I've been using a local HTTP server even when browsing on the machine in question.

**Comment by ttuegel** [comment]
See #462.
