### ISSUE TITLE
cabal should walk up folders to find cabal file

### ISSUE THREAD

**Issue by errge** [haskell/cabal#1479]
The new 1.18 cabal repl feature is very cool!  The same thing that has been provided by tools like cabal-ghci, but much better integrated and working.

Although, I miss the feature from cabal-ghci that automatically walked upwards the filesystem tree until it found a .cabal file.

So if there is no .cabal file in the current directory, try in .., then ../.., etc.

Would it be possible to add that to 'cabal repl'?

**Comment by ezyang** [comment]
This bug has nothing to do with repl in particular.

cabal new-repl DOES walk up looking for a cabal.project, so that might fix this for some of you.

**Comment by gbaz** [comment]
closing as obsolete
