### ISSUE TITLE
cabal sandbox paths default to not being relative paths

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1490]
if i do 

```
mkdir test
cd test
cabal sandbox init
cabal install void # or any other package
cd ..
mkdir test2
mv test test2/
cd test2/test
cabal install data-reify
```

i get 

```
carter test2/test » cabal install data-reify
cabal: No sandbox exists at /Users/carter/test/.cabal-sandbox

```

this suggests to me that the default paths in the cabal sandbox config (for the data that is local to the sandbox) should be relative paths, because its very unintuitive that moving a sandbox breaks the config files

**Comment by krauthaufen** [comment]
+1
Would make it easier to commit sandbox files and use them on different machines.

**Comment by siddharthist** [comment]
Another use case: installing a package with cabal inside a Docker container.

**Comment by sinelaw** [comment]
+1

**Comment by sinelaw** [comment]
I've found a workaround: search/replace old path to new path in all .conf files, then run ghc-pkg recache on the package db of the sandbox:

    find /path/to/.cabal-sandbox -iname "*.conf" -type f | xargs sed -i 's, /.*/\.cabal-sandbox, /path/to/.cabal-sandbox,g'
    ls /path/to/.cabal-sandbox/ | grep 'conf\.d' | xargs -t -n1 -i_db_ ghc-pkg --package-db=/path/to/.cabal-sandbox/_db_ recache


Replace `/path/to/.cabal-sandbox` with your own path for the relocated sandbox.

**Comment by phadej** [comment]
sandbox functionality is removed.
