### ISSUE TITLE
Sandbox: "Cannot select only the dependencies" with --disable-tests

### ISSUE THREAD

**Issue by bos** [haskell/cabal#1500]
I'm trying to use cabal 1.18 in a sandbox to build the mwc-random package. The first build succeeds, but the second one fails as follows:

```
+ cabal install --only-dependencies --disable-tests --enable-documentation
Resolving dependencies...
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the package mwc-random-0.13.0.0 is required by a
dependency of one of the other targets.Note: when using a sandbox, all
packages are required to have consistent dependencies. Try
reinstalling/unregistering the offending packages or recreating the sandbox.
```

The problem with this error message is that it tells me that something is wrong, but it gives me no clue **what** is wrong, so I don't have the faintest idea what to do or where to look.
## Reproduction

This takes a few minutes.
### Step 1

```
git clone git://github.com/bos/mwc-random
cd mwc-random
cabal sandbox init
cabal install --only-dependencies -j --disable-tests
cabal install -j test-framework-hunit test-framework-quickcheck2 statistics --disable-tests
cabal configure --enable-tests
cabal build
```

This build should succeed without a problem.
### Step 2

Now I want to do a rebuild in the same sandbox, by following the same recipe. It fails at the very first real step.

```
cabal install --only-dependencies --disable-tests
```

This is the point at which the sandbox gets stuck. I don't know what's wrong, or how to fix it.

**Comment by grayjay** [comment]
#1575 covers the issue with cycles between packages and their test dependencies.  I think that the only other issue here is that the error message is less clear when the build is done with `--only-dependencies` and a sandbox.  The install command tries to reinstall all packages in the sandbox, including the test dependencies, and `--only-dependencies` prevents the main package from being reinstalled.

**Comment by phadej** [comment]
sandbox functionality is removed.
