### ISSUE TITLE
"cabal sandbox" does not take a --with-ghc argument, and yet it seems to need ghc in path

### ISSUE THREAD

**Issue by rrnewton** [haskell/cabal#1511]
If we try to run without `ghc` in path:

```
$ /cygdrive/c/Haskell_Platform/2013.2.0.0/lib/extralibs/bin/cabal sandbox init
cabal.exe: The program ghc version >=6.4 is required but it could not be
```

The context is a testing system which has four or five versions of GHC installed.  One approach we use sometimes is to make sure there is NO ghc in path at all, and use explicitly versioned commands only, to make sure our wires don't get crossed while testing.

I think the simple solution is that any subcommand that expects ghc should take `--with-ghc=`, right?

**Comment by phadej** [comment]
sandbox functionality is removed.
