### ISSUE TITLE
cabal install runs out of stack space on Ubuntu 13.10

### ISSUE THREAD

**Issue by pikajude** [haskell/cabal#1515]
$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu Saucy Salamander (development branch)
    Release:        13.10
    Codename:       saucy

    $ cabal install --only-dependencies --enable-tests -v +RTS -K100m -xc
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
      MAIN.MAIN
    Reading available packages...
    *** Exception (reporting due to +RTS -xc): (THUNK_STATIC), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_STATIC), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_STATIC), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (THUNK_STATIC), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (CONSTR_2_0), stack trace: 
      MAIN.MAIN
    *** Exception (reporting due to +RTS -xc): (CONSTR_2_0), stack trace: 
      MAIN.MAIN
    Stack space overflow: current size 104857600 bytes.
    Use `+RTS -Ksize -RTS' to increase it.

If I can provide any more helpful information please let me know.

**Comment by grayjay** [comment]
I spent some time looking into this bug.  I don't think there is enough information to reproduce it now.  The VM image and project are no longer available, and the heap profile doesn't have cost centers.  I did notice that the log contains `Reading available packages...` but not the choice of solver, so it's possible that there was a problem reading the index.  Should this be closed?

**Comment by 23Skidoo** [comment]
This was probably fixed by #2826.
