### ISSUE TITLE
Document `other-extensions` in user guide

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#1517]
I was surprised to see that the user-guide doesn't mention the `other-extensions` field at all.

**Comment by hvr** [comment]
This has been partly addressed by 3f53ee2e42c180a34fb7dd506d33da56aa8221d1 but as @phadej points out it should provide more guidance about what effect using `other-extensions` has (e.g. for Cabal < 1.24 it results in Cabal aborting if the current compiler doesn't provide the extensions, for Cabal>=1.24 the solver uses that information)

**Comment by 23Skidoo** [comment]
Fixed by #2818.

**Comment by massysett** [comment]
Thank you!

**Comment by Ericson2314** [comment]
https://www.haskell.org/cabal/users-guide/ seems really out of date---this is probably documented elsewhere but I've twice forgotten about this, been confused by the lack of documentation at the URL, and then checked the repo.

**Comment by hvr** [comment]
@Ericson2314 for future reference, http://cabal.readthedocs.io/en/latest/developing-packages.html#build-information
