### ISSUE TITLE
Unclear message when a file is missing (cabal sdist)

### ISSUE THREAD

**Issue by HJvT** [haskell/cabal#1531]
The command 
  cabal sdist
resulted, for a certain package on my hard disk, in the error message
  cabal: does not exist
It is very unclear what caused this error message, a better message would have been:
  cabal: the file README.txt does not exist
The cabal file of this package contained a.o.:
   Extra-Source-Files:
                README.txt
An even better error message would be:
  cabal: the file README.txt (mentioned in section Extra-Source-Files) does not exist

**Comment by ttuegel** [comment]
Closing, as this appears to have been resolved.

**Comment by HJvT** [comment]
The situation is exactly the same as I reported it the first time (I forgot to mention that I use Windows; maybe the Windows version is different):

> cabal --version
cabal-install version 1.22.0.1
using version 1.22.1.1 of the Cabal library

> cabal sdist
Distribution quality warnings:
When distributing packages it is encouraged to specify source control
information in the .cabal file using one or more 'source-repository' sections.
See the Cabal user guide for details.
Warning: Cannot run preprocessors. Run 'configure' command first.
Building source dist for HJvT-0.0.0...
cabal.exe: does not exist
