### ISSUE TITLE
feature: cabal sandbox add-source <git-repo> (darcs too ideally…)

### ISSUE THREAD

**Issue by kowey** [haskell/cabal#1534]
One potentially useful thing for teams working with complex families of packages would be able to add source code repositories (bonus: ability to pick out branches…).  This is quite helpful for synchronisation and avoids time wasted in “oh wait, that's why you're having trouble; you need to pull the lastest git version of the foo dependency from my branch” style discussions in mid-development.  For me, getting somebody up and running with this new feature would consist in handing them a list of URIs for sources, and that'd be it.

Alternatives that I'm aware of so far would be to write people scripts (a bit tricky if you have Windows/Unix mixed teams) or to use something like cabal-meta instead (but preferable not to have to give people a new cmd to learn like cabal-dev)

Otherwise, the new cabal sandbox is making me happy.  Thanks, devs!

**Comment by phadej** [comment]
sandbox functionality is removed.
