### ISSUE TITLE
cabal sandbox doesn't see a source dependency

### ISSUE THREAD

**Issue by feuerbach** [haskell/cabal#1546]
I'm observing a strange behavior of cabal sandboxes. This is cabal-install from the current master.

    # Check that `/home/feuerbach/prog/tasty/core` is a registered source dependency

    % cabal sandbox list-sources
    Source dependencies registered in the current sandbox
    ('/home/feuerbach/prog/tasty/sandbox/.cabal-sandbox'):

    /home/feuerbach/prog/tasty/core
    /home/feuerbach/prog/tasty/smallcheck
    /home/feuerbach/prog/tasty/quickcheck
    /home/feuerbach/prog/tasty/hunit
    /home/feuerbach/prog/tasty-golden

    To unregister source dependencies, use the 'sandbox delete-source' command.

    # Check that it contains a new version (0.3.1) of tasty

    % head /home/feuerbach/prog/tasty/core/tasty.cabal 
    -- Initial tasty.cabal generated by cabal init.  For further documentation,
    --  see http://haskell.org/cabal/users-guide/

    name:                tasty
    version:             0.3.1
    synopsis:            Modern and extensible testing framework
    description:         See <http://documentup.com/feuerbach/tasty>
    license:             MIT
    license-file:        LICENSE
    author:              Roman Cheplyaka

    # Try to install it

    % cabal install tasty                             
    Resolving dependencies...
    All the requested packages are already installed:
    tasty-0.3
    Use --reinstall if you want to reinstall anyway.

**Comment by BardurArantsson** [comment]
Seems this should just be closed? (Seems to have no value just being in the issue tracker without a way to reproduce + it's a 1½ years old report.)
