### ISSUE TITLE
--enable-executable-dynamic not working on packages containing both lib and executables, makes installation problematic

### ISSUE THREAD

**Issue by magthe** [haskell/cabal#1568]
RPATH for executables is set to include the build location for the library and not the install location for the library.  This results in the situation described in detail [in this mail](http://www.haskell.org/pipermail/haskell-cafe/2013-November/111245.html).

This makes it rather impossible to install this type of packages when linking dynamically.

**Comment by jessicah** [comment]
Is there some magic incantation I need to pass to Cabal to make this work?

I've just downloaded pandoc sources from Hackage, and run:

    ~> cd pandoc-1.12.4.2
    ~/pandoc-1.12.4.2> cabal install --force-reinstalls
    ~/pandoc-1.12.4.2> readelf -a /boot/system/non-packaged/bin/pandoc | more
    ...
      0x00000001 (NEEDED) Shared library: [libHSpandoc-1.12.4.2-ghc7.8.3.so]
    ...
     0x0000000f (RPATH)  Library rpath: [/Data/pandoc-1.12.4.2/dist/build:/boot/system/non-packaged/lib:...]

And version of cabal:

    ~> cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library
