### ISSUE TITLE
bad error message when using configuration flags that were not defined

### ISSUE THREAD

**Issue by bos** [haskell/cabal#157]
(Imported from [Trac #164](http://hackage.haskell.org/trac/hackage/ticket/164), reported by @dcoutts on 2007-10-16)

Using a flag in an if condition when that flag has not been previously defined gives an unhelpful error message:

<pre class="wiki">-- flag foo never declared:
if flag(foo)
  blah:
else
  other:
</pre>We get the error message:

<pre class="wiki">cabal-setup: Environment not defined for all free vars
</pre>The error is reported by <tt>Distribution.Configuration.simplifyCondTree</tt> but the error should probably be checked for much earlier.

**Comment by mgsloan** [comment]
I am still getting this error message with Cabal-1.22.7.0, did this regress?
