### ISSUE TITLE
HTTP_PROXY and reserved characters

### ISSUE THREAD

**Issue by pierrevandelaar** [haskell/cabal#1579]
The value of HTTP_PROXY has as format
http://user:pass@host:80/

In the password special characters can occur, like @ and !.
According to wiki (http://en.wikipedia.org/wiki/Percent-escape)
these characters must be percent-encoded, like %40 and %21.

Cabal doesn't accept percent-encoded characters.
And cabal errs on these characters (if password is a@b, Cabal doesn't look to the right site, but probably to "b@host:80" (error message is not clear enough to be certain)

**Comment by ttuegel** [comment]
This issue needs to be solved in HTTP.

**Comment by 23Skidoo** [comment]
@ttuegel
Can you please report it to them?

**Comment by ttuegel** [comment]
[Done](https://github.com/haskell/HTTP/issues/83).
