### ISSUE TITLE
Cabal is not working on Windows when user name uses locale characters

### ISSUE THREAD

**Issue by wdanilo** [haskell/cabal#1583]
Hi!
Cabal is not working on Windows if there are locale characters in your user name.
For example, if I'm testing cabal with user name "userążółć" (some polish locales), I get very strange errors:

```
C:\Users\userazólc>cabal update -v3
Config file path source is default config file.
Config file C:\Users\usercabal: <stdout>: invalid argument
```
etc. 

I've tested it on 1.18.2 and 1.19.1 (current HEAD).

**Comment by ttuegel** [comment]
Duplicate of #650.
