### ISSUE TITLE
local path disclosure

### ISSUE THREAD

**Issue by accursoft** [haskell/cabal#1611]
When compiling cabal-install, the path to my ~/.cabal directory is hard-coded several times in the executable. Is it possible to avoid this?

My use case is a private server that's compiling cabal-install, then deploying it to less privileged servers which shouldn't know anything about the private server's file system.

**Comment by mietek** [comment]
@23Skidoo: By “anywhere”, do you mean the _cabal-install_ source code, or also the GHC run-time? Could other executables be non-relocatable, without a specific reason in their source code?

**Comment by 23Skidoo** [comment]
@mietek The former, but since these symbols come from the Cabal-generated `Paths_` module, the GHC runtime can't know about them either.

> Could other executables be non-relocatable, without a specific reason in their source code?

Only if an executable uses these paths in some way, e.g. if it accesses data files with `getDataDir` instead of `file-embed`.
