### ISSUE TITLE
cabal init failed without git installed

### ISSUE THREAD

**Issue by sniperliu** [haskell/cabal#1613]
Package name? [default: ttt]
Package version? [default: 0.1.0.0]
Please choose a license:
- 1) (none)
  ...
  12) Other (specify)
  Your choice? [default: (none)]
  cabal: git: does not exist

Heuristics.hs
readProcessWithExitCode "git" ["config", "", ""] "" will jump out directly if createProcess fail to find the executable.

**Comment by rbelouin** [comment]
I currently use cabal 1.22.2.0, and I have a similar error (note that git is not installed):

```
Your choice? [default: (none)] 
cabal: git: permission denied
```

**Comment by byorgey** [comment]
Hmm, I note you are getting a "permission denied" error rather than a "does not exist" error.  I'll reopen this for now and try to look into it in more detail soon.

**Comment by 23Skidoo** [comment]
@byorgey Any news on this?

**Comment by byorgey** [comment]
@23Skidoo thanks for the ping, obviously this had fallen completely off my radar.  The problem with this issue is that it seems very platform-dependent and hence difficult to reproduce.  However, my best guess is that the fix is simply to change this line: https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Compat/Process.hs#L46 to `isDoesNotExistError e || isPermissionError e`.  This seems like a sensible thing to do, I'll put together a patch.

**Comment by byorgey** [comment]
This probably isn't the right place for this, but in trying to put together a patch for this, I am having trouble compiling `Cabal` from git: I get
```
cabal: Error: some packages failed to install:
Cabal-1.25.0.0 failed during the configure step. The exception was:
user error ('/home/brent/local/bin/ghc' exited with an error:

Cabal/Distribution/Utils/BinaryWithFingerprint.hs:11:0:
error: missing binary operator before token "("
#if MIN_VERSION_base(4,8,0)
^
)
```
Has anyone seen this before?  Looks like some sort of CPP error...

**Comment by 23Skidoo** [comment]
@byorgey Are you running `Setup.hs build`?

**Comment by byorgey** [comment]
@23Skidoo I basically did
```
git clone haskell/cabal
cd cabal
cabal sandbox init
cabal install Cabal/ cabal-install/
```
The `cabal` I have installed is `1.22.6.0`, built with `Cabal-1.22.5.0`.  If I do `runhaskell Setup.hs build` I get the same error.  Is there something different I am supposed to do?

**Comment by 23Skidoo** [comment]
No, you're doing everything right. I wonder why Travis didn't catch this.

**Comment by 23Skidoo** [comment]
Basically, we need to handle the case when `MIN_VERSION_` macros are not defined. Will try to fix this later today.

**Comment by byorgey** [comment]
OK.  Would you like me to open a new ticket to track this?

**Comment by 23Skidoo** [comment]
Sure, please do.
