### ISSUE TITLE
Cabal sandbox ignores user db, while GHC does not by default

### ISSUE THREAD

**Issue by alevy** [haskell/cabal#1621]
Setting `GHC_PACKAGE_PATH` to, e.g `.cabal-sandbox/x86_64-linux-ghc-7.6.3-packages.conf.d:` when invoking ghc commands (`ghc`, `ghci`, etc'), looks for packages in the given, sandbox, database, then the user database, then the global database, by default. Conversely, running cabal commands within a sandbox (e.g. `cabal build`, `cabal repl`) skips over the user database -- in looks at the sandbox db and the global db only.

This causes problems when the user database and the global database have different versions of the same package. `cabal install` will compile dependencies against the global database version, but ghc will then load the user database versions. Obviously, this can be overcome by explicitly excluding the user database when invoking ghc, but this makes it hard to write tools that are agnostic of whether we're running inside a cabal sandbox.

Two possible solutions:
1. Modify cabal to use the user database in the same way ghc does. I'm not familiar with why the original choice was made, but this seems like the more "correct" solution.
2. Add a `cabal exec` command (kind of like `bundle exec` in Ruby's bundler) that sets up the GHC environment approriately and lets you run arbitrary shell commands. While maybe a bit less clean of a solution, I'd argue there are nice benefits to have such a command anyway, and it doesn't require breaking any expectations about how cabal sandboxes work.

**Comment by leonbaum** [comment]
How does `cabal exec` help one use the user package db in a sandbox?

I have many large packages installed in my user db that I don't want to re-install for every sandbox I create.  Is there no way to share them between sandboxes?  For standard setups, I really don't understand the problem with sharing the user db..

**Comment by alevy** [comment]
It doesn't help you use the user package db, it kind of does the opposite.

`cabal exec` ensures that when you run a command, that command runs in an environment that's the same as the one `cabal install` uses. If you have a cabal sandbox, that environment **exludes** the user database, which in your case is kind of the opposite of what you want, I think.
