### ISSUE TITLE
cabal-install does not quote the path in the --with-gcc parameter

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1634]
According to haskell/network#118 cabal-install does properly quote the path passed to `--with-gcc`, causing failures on Windows when the path contains a space.

**Comment by drbo** [comment]
The only solution I know of is to either fix or ditch Autoconf, which has a bad track record with handling spaces in variables.

**Comment by gbaz** [comment]
For the record, I've found the short names solution to work. What a pain :-/

**Comment by 23Skidoo** [comment]
IIUC, @hvr fixed this in #2946 (we now use `./configure CC=/path/to/gcc` instead of `./configure --with-gcc`). If it still doesn't work, then it's a bug in Autoconf.

**Comment by 23Skidoo** [comment]
> If it still doesn't work, then it's a bug in Autoconf.

It doesn't, see #3185.
