### ISSUE TITLE
Provide pre-built cabal-install binaries for OS X and Linux

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1653]
We're already providing a pre-built cabal-install executable for Windows. Users have requested that we also do the same for Linux and OS X (see [this thread](http://www.haskell.org/pipermail/libraries/2014-January/021940.html)).

For Linux binaries we should probably use [statifier](http://statifier.sourceforge.net/) or [Ermine](http://www.haskell.org/pipermail/libraries/2014-January/021940.html) like the Darcs folks to make the executables more portable.

Perhaps we should also set up an official PPA for Ubuntu.

**Comment by gbaz** [comment]
this is now part of the standard release process.

**Comment by jneira** [comment]
> Long term we might want to set up a bunch of build bots that constantly produce binaries, but that's work I don't have time to do now.

the historician living in me loves this old issues
