### ISSUE TITLE
cabal update should optionally take a server to only update

### ISSUE THREAD

**Issue by mxswd** [haskell/cabal#1656]
A full `cabal update` is very slow. Ideally, if I have both `hackage.org` and a local `hackage.local`, I should be able to update them independently.

A command such as `cabal update hackage.local`, where it looks up the server from the name in the remotes.

**Comment by ulysses4ever** [comment]
you can specify the server these days. Closing... Please, reopen if you think it's not exactly what you expected.

**Comment by philderbeast** [comment]
As of #4809 `cabal update` accepts a package repository argument.

**Comment by ulysses4ever** [comment]
Hey @philderbeast, thanks a lot for the link! Do you think it (#4809) covers what they asked for initially? #4809 talks about cabal.project a lot but the plain config files are also subject to this logic?..
