### ISSUE TITLE
cabal should complain about unlisted modules

### ISSUE THREAD

**Issue by schell** [haskell/cabal#1664]
Not listing `other-modules` results in `ld: illegal text reloc`. It seems like it should instead warn about unlisted modules since an illegal text reloc is rather esoteric, though I'm sure it's just forwarding the error from ghc.

I've created a little test case at https://github.com/schell/illegal-text-reloc.

BTW, this seems to only happen when building a library.

**Comment by ttuegel** [comment]
See #1746.
