### ISSUE TITLE
Apparently spurious error about Cabal-version check

### ISSUE THREAD

**Issue by rrnewton** [haskell/cabal#1666]
To avoid issue #1284, [I recently added](https://github.com/rrnewton/haskell-lockfree/commit/3f82513b62566ce2643e920ee469658c0c83e238) an explicit requirement to my .cabal file that insists upon cabal 1.18 or newer:

```
Cabal-version:       >=1.18
```

But this seems to result in failures, [as in this log here](http://tester-lin.soic.indiana.edu:8080/job/Haskell-LockFree_master/JENKINS_GHC=7.6.3,label=macos/346/console), which complains about >=1.18 not being available:

```
cabal: Error: some packages failed to install:
atomic-primops-0.5.99 failed during the configure step. The exception was:
user error (The package 'atomic-primops' requires Cabal library version -any
&& >=1.18 but no suitable version is installed.)
```

In spite of the fact that earlier in that same log,  `cabal --version` reports:

```
cabal-install version 1.18.0.1
using version 1.18.0 of the Cabal library
```

Well then!

**Comment by ulysses4ever** [comment]
This is a very old bug report with no (apparent) reproducer. Should we close it?

**Comment by ulysses4ever** [comment]
Got +1 from jneira, so closing...
