### ISSUE TITLE
sbt-style continuous build and test

### ISSUE THREAD

**Issue by Zane-XY** [haskell/cabal#1678]
Hi,
`cabal test` will stop after the tests complete.  It would be nice and practical to have the tests automated if the related sources has been changed, like `cabal ~test` will issue a test command every time when a source has been changed.
I think this would be very useful.
Thanks!

**Comment by iphydf** [comment]
Here is why "on top of cabal", if I understand that correctly as being a script calling cabal build on change, is infeasible:
```
cabal build  4.02s user 1.99s system 207% cpu 2.907 total
```
The whole point of the continuous build/test in sbt is that you can very quickly (in milliseconds) build a new version and run a single test while writing the code. In test-driven development, I'd write some test cases (quickcheck properties), and then start implementing the code for them. Continuous testing would help a lot there.

**Comment by ezyang** [comment]
This ticket is basically asking for `./Setup build` to run faster. I agree it would be great if it ran faster. It may be difficult to achieve this without rewriting all of the implementation of `Build`, however, so that we don't, e.g., needlessly repreprocess things that are not necessary. I'd quite like to rewrite Setup build on top of Shake so that this worked.

**Comment by 23Skidoo** [comment]
With the file monitoring infrastructure in new-build now in place, this should be easier to implement.

**Comment by ezyang** [comment]
Not by much. The file monitoring is only used by cabal-install and there is no interface building individual files in Cabal library.

**Comment by 23Skidoo** [comment]
Oh, I meant the original feature request. You're right about rewriting Setup build on top of Shake.

**Comment by ulysses4ever** [comment]
This can be closed in favor of #5252: a more extensive discussion of the future is there.

**Comment by Mikolaj** [comment]
No objections, so let me close in favor of https://github.com/haskell/cabal/issues/5252.
