### ISSUE TITLE
Make documentation generation and upload for Hackage easier

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/cabal#1702]
Sometimes we want to upload our own documentation to Hackage for whatever reasons. At the moment it is possible but difficult to get right: we need to generate the docs so that the pages are linked properly (including index pages &c), we need to pack the documentation up into a tarball with a proper format, we need to figure out proper curl flags etc. etc.

It's not the easiest process to go through and there's no official documentation about it (#1025): only documentation that exists is that which was put together by Haskellers. Few hacky scripts exist to help and they seem to do the job although it's far from perfect.

It'd be great if we could have a command like `cabal haddock --upload` or something along these lines which invokes Haddock with the correct flags and uploads the data with the correct settings if Haddock succeeds. 

Alternatively, a `cabal haddock --check` command could be implemented which checks for badly generated docs. This should be less work but it feels like a dirty workaround for lack of official solution.

**Comment by 23Skidoo** [comment]
This has been fixed in #2890.
