### ISSUE TITLE
usage hint for how to invoke cabal-install misleads

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1706]
currently is has

```
Usage: cabal COMMAND [FLAGS]
   or: cabal [GLOBAL FLAGS]
```

i think it should actually be 

```
Usage: cabal COMMAND [FLAGS]
   or: cabal [GLOBAL FLAGS]
   or: cabal [GLOBAL FLAGS] COMMAND [FLAGS]
```

NOT enough people realize this! I literally only found out this past week

**Comment by gbaz** [comment]
currently `Usage: cabal [GLOBAL FLAGS] [COMMAND [FLAGS]]`
