### ISSUE TITLE
bootstrap.sh misconfigures linker on Mavericks

### ISSUE THREAD

**Issue by jhenahan** [haskell/cabal#1710]
Using GHC 7.8-RC2: [Gist](https://gist.github.com/jhenahan/e46981bd90ef63b6788e)

The issue is in the regex used to extract the name of the linker. In particular, when `$link` is interpolated in

```
echo 'main;' | ${CC} -v -x c - -o /dev/null -\#\#\# 2>&1 | grep ld | sed -e "s|\(.*$link\).*|\1|" -e 's/ //g' -e 's|"||'
```

the path gets cut off in unusual ways because it matches the text preceding the linker path up to `/var/fold`.

I'm not really sure of the best way to get around this. Maybe just trading out the regex for just asking for `which $link`.

**Comment by creswick** [comment]
This fixed a symptom -- but it's still a problem.  See #2542
