### ISSUE TITLE
Drop Haddock 0.x support

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/cabal#1718]
Module comment in `Cabal.Distribution.Simple.Haddock` says that the module supports 0.x and 2.x Haddock versions. Perhaps it'd be a good idea to drop 0.x support to simplify the module.

I doubt that there's a compiler version that compiles today's Cabal and Haddock 0.x and I doubt anyone still uses Haddock 0.x and expects modern tools interacting with it to work.

**Comment by ulysses4ever** [comment]
This has been fixed in 98c537f1 (it appears), I wonder why the issue wasn't auto-closed. Closing?

**Comment by Fuuzetsu** [comment]
You're probably correct, closing.
