### ISSUE TITLE
ExitFailure 127 when installing unix-time, accelerate and more

### ISSUE THREAD

**Issue by trygvea** [haskell/cabal#1723]
Multiple packages fails during install with ExitFailure 127, but no more (sensible) explation. The bug is easily reproducable as follows:
```
touch ~/foo
ln -s ~/foo ~/bar
PATH=~/bar/foobar:$PATH    
cabal install unix-time
```
which returns:
```
...
unix-time-0.2.2 failed during the configure step. The exception was:
ExitFailure 127
```

I'm running OS X 10.9, GCH 7.6.3, cabal-install version 1.18.0.3.

This issue is also reported as an issue on the unix-time package: https://github.com/kazu-yamamoto/unix-time/issues/19#issuecomment-37286413

I'm apparently not the only one having this problem, neither is unix-time the only package: https://www.google.no/search?q=cabal+ExitFailure+127

**Comment by ttuegel** [comment]
I think the only bug here that Cabal can do anything about is the poor error messages, which have been improved recently. Please complain if this needs re-opened!
