### ISSUE TITLE
cabal repl does not honor implicit 'module Main'

### ISSUE THREAD

**Issue by zerobuzz** [haskell/cabal#1732]
When loading a source file that has no 'module Main where' line into cabal repl, the symbol definitions from that file are missing.

Workaround: Always include 'module' declaration in source files.

To reproduce (off the top of my head) -

> git checkout https://github.com/zerobuzz/cabal-repl-issue
> cd cabal-repl-issue
> git checkout -b 7417bb3ba99f3ca33871b0d24b75055d6f54b67b  # broken
> cabal sandbox init
> cabal install
> cabal repl
> :load test.hs
> x

This should yield '3', but instead ghc complains about x being undefined.

> git checkout -b 6d55454060ebca003ff39ec49d2e223a6cc60c58  # working
> cabal install  # (may not even be necessary)
> cabal repl
> :load test.hs
> x

This yields '3' as expected.

Reproduced with cabal 1.18.0.2 and both ghc-7.6.3 and 7.8.1-rc2.

**Comment by Mikolaj** [comment]
@ulysses4ever: after many months of inactivity and no objections for a couple of days, I think you can safely close.
