### ISSUE TITLE
`Does not exists` error when running cabal in windows

### ISSUE THREAD

**Issue by sbergot** [haskell/cabal#1733]
With the newest cabal, I get a lot of does not exist errors when running `cabal install --only-dependencies` or `cabal configure` if I am not in a MSYS console.

error when running `cabal install --only-dependencies`:
setup-Cabal-1.18.1.3-i386-windows-ghc-7.6.3.exe: does not exist

error when running `cabal configure`:
cabal: does not exist

cabal -V:
cabal-install version 1.18.0.3
using version 1.18.1.3 of the Cabal library

ghc -V:
The Glorious Glasgow Haskell Compilation System, version 7.6.3

Everything is working with a MSYS console

**Comment by ShabbyX** [comment]
I was in a virtual machine, running windows 7 with the DHCP service disabled (so I didn't have internet connection) and this error popped out. cabal-install version 1.22.6.0. Starting the DHCP server solved this issue.

Not only cabal update gave this error, but cabal install complained about log files missing. It seems that when cabal fails to connect to where it wants, it fails with random other errors.

**Comment by 23Skidoo** [comment]
@ShabbyX Your problem seems to be different, though the error is the same. Just opened a new ticket for it (#3115).
