### ISSUE TITLE
Incorrect processing of .lhs files 

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1735]
Initially reported by Pierre-Étienne Meunier on cabal-dev@:

> Hi,
> 
> There is a bug in cabal haddock, when lines in an lhs file start with a $, which is quite common when writing a paper with large TeX fragments in the programs.
> 
> For instance, cabal haddock fails on the following lhs file:
> 
> ```
> blabla, blibli
> $a+b$
> \begin{code}
> main=putStrLn "Hello"
> \end{code}
> ```
> 
> I first thought it was a haddock bug, but the haddock maintainers disagree:http://trac.haskell.org/haddock/ticket/293

**Comment by gbaz** [comment]
Can't repro.
