### ISSUE TITLE
cabal: <file descriptor: 8>: does not exist

### ISSUE THREAD

**Issue by mikeizbicki** [haskell/cabal#1750]
I just did a fresh install of GHC 7.6.3, followed by installing the latest platform.  But when I run cabal update, I get:

    bash-4.1$ cabal update
    Downloading the latest package list from hackage.haskell.org
    cabal: <file descriptor: 8>: does not exist

What file descriptor is this referring to?

**Comment by ttuegel** [comment]
This is usually a transient network problem.
