### ISSUE TITLE
Document HookedBuildInfo

### ISSUE THREAD

**Issue by copumpkin** [haskell/cabal#1757]
Many of the hooks in a Cabal build are supposed to return that type, but the type itself has no documentation attached to it, and the type alias resolves to a rather uninformative `(Maybe BuildInfo, [(String, BuildInfo)])`. It looks like the `fst` is applied to the library and the `snd` has entries for executables.

**Comment by nh2** [comment]
Not sure this issue is really done; even with the added Haddocks, there's still nothing that explains what the `(Maybe BuildInfo, [(String, BuildInfo)])` is used for (library vs executables? What happens if I return `Nothing`).
