### ISSUE TITLE
GHC thread escapes when suspending cabal with Ctrl+Z

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#1760]
When I build [xhb](http://hackage.haskell.org/package/xhb) with `cabal build -j4` on GHC 7.8 (`cabal configure -w ghc-7.8.1`), and then suspend the process with `Ctrl+Z`, one ghc process is not suspended and goes nuts on 100% CPU (possibly forever).

(xhb doesn't currently build cleanly on 7.8; you have to `cabal get xhb`, then edit `Graphics/XHB/Shared.hs` and add an `import System.IO.Unsafe (unsafePerformIO)` to make it work.)

I don't know if this is a GHC or cabal related problem.

**Comment by gbaz** [comment]
closing as rotted. (info-needed after 4 years is probably not forthcoming).

**Comment by nh2** [comment]
I didn't see that there's `info-needed` requested from my side, as adding tags doesn't send anybody emails.

I have just tried it again with

```
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
ghc-7.10.3
xhb-0.6.2015.8.1
```

and could not reproduce the problem.
