### ISSUE TITLE
Adding CC0 to the License type

### ISSUE THREAD

**Issue by ianbollinger** [haskell/cabal#1765]
Due to inherent problems with dedicating creative works to the public domain, several licenses were written that contain fallback clauses in case public domain dedication is impermissible--for instance, the [Creative Commons Zero license](https://en.wikipedia.org/wiki/CC0#Zero_.2F_Public_domain), or CC0. ([The Unlicense](http://unlicense.org/) is another.) Currently, a dozen or more packages on Hackage using either license specify `PublicDomain` for their license field; it would be nice if users could see the real license reflected in the package description, rather than the nebulous `PublicDomain` value. It also might be of help for future dependency-license auditing tools.

Currently, the documentation refers to `PublicDomain` as a "license", which should be changed. As for additional documentation, I don't know if it would be wise to warn about the (potential) lack of legal protections public domain dedications give to users. There is already a precedent for being prescriptive regarding 4-clause BSD, at least. On the other hand, the other license descriptions might also use more neutral descriptions or dispense with them and link to relevant web resources instead.

**Comment by L-TChen** [comment]
It looks like this issue has been resolved by the [SPDX license](https://hackage.haskell.org/package/Cabal-syntax-3.10.1.0/docs/Distribution-SPDX-LicenseId.html#t:LicenseId) type, right?
