### ISSUE TITLE
Solver is often stumped by restrictive upper bounds

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#1783]
To define the term: by "restrictive upper bound" I mean an upper bound which excludes some packages available from Hackage. So if foo 1.0, 1.1, and 1.2 are available on Hackage, a bound of `foo < 1.3` would _not_ be restrictive, whereas `foo < 1.2` _would_ be restrictive.

I went to build a project I haven't touched in a few months (haskellers.com), and cabal was unable to produce a build plan. Eventually, I whittled this down to [this cabal file](https://gist.github.com/snoyberg/10955715). In this file, there is only one restrictive upper bound: http-conduit. I then ran the following command with both cabal-install 1.16 + GHC 7.6 and cabal-install 1.18 + GHC 7.8:

```
clear;date;cabal install --dry-run --reorder-goals --max-backjumps=-1;date
```

In both cases, there was no response for approximately 15 minutes, at which point I killed cabal. However, I was able to cause the dry run to succeed almost immediately (< 10 seconds) with either of the following:
1. Adding: --constraint 'http-conduit == 1.9.6'
2. Relaxing the upper bound on http-conduit to allow the newest version.

I'd like to note that these are the kinds of errors Yesod users complained about regularly in the past. The ultimate "solution" I settled on was (1) encourage usage of yesod-platform to help out the constraint solver, and (2) remove most upper bounds in cabal files. Obviously it would be better if cabal was better able to handle these situations.

**Comment by 23Skidoo** [comment]
@snoyberg 
> I'm beginning to think this is caused exclusively by `--reorder-goals`.

`cabal-install` 1.24 will have some performance improvements to `--reorder-goals` (#3208).

**Comment by Blaisorblade** [comment]
There's also a wiki page on constraint-solving through SAT-solving:
https://github.com/haskell/cabal/wiki/Constraint-Solving

I think that could be really cool.

The wiki-page is somehow confused on conditional constraints — implications seem easy to encode as boolean formulas. What might be harder is enabling flags automatically if they add dependencies that are available, if desired (I'm not sure that's the current behavior of flags, but such flags are desirable in a few scenarios, say https://www.reddit.com/r/haskell/comments/4pf86b/cabal_build_variants/d4kv7yp).

**Comment by hvr** [comment]
@Blaisorblade translating the cabal constraint satisfaction problem into SAT or SMT language is mostly straight-forward; several people (including myself) have done this in the past, and it's mostly a matter of sitting down on a calm weekend. And in fact, solvers like Z3 then can easily beat the modular cabal solver finding some arbitrary solution. However, as soon as you want an optimal solution according to some criteria (which you then need to encode in the SMT/SAT language as well), things get ugly quite and demotivating, and the modular cabal solver turns out to be better suited... :-/

**Comment by Blaisorblade** [comment]
Just found #2860, answering there...

**Comment by cartazio** [comment]
Question: has anyone tried using a datalog variant?
In some respects we want the max of viable build plans , and if two build
plans are incomparable in the partial order of versions that's where things
get interesting!

I may have a poke at seeing if the data log tools in z3 and friends are
helpful here.  There's been a lot of interesting work in the past two or
three years at this intersection

**Comment by grayjay** [comment]
I think that cabal is much better at handling restrictive upper bounds now that it can reorder goals with the conflict counting feature added in #3513.  If a package has a restrictive upper bound and it occurs frequently in conflict sets, conflict counting causes the solver to choose the packages affected by the constraint earlier.  Then it can make choices that take the constraint into account.

I tried to reproduce the original problem by specifying `--index-state` and turning off conflict counting, and the results seemed consistent.  I ran `cabal install --dry-run --reorder-goals --max-backjumps=-1  --index-state 2014-04-15T22:20:17Z --no-count-conflicts` on `haskellers.cabal` with GHC 7.6.3.  cabal was still running after 15 minutes.  Adding `--constraint 'http-conduit == 1.9.6'` or lifting the upper bound on `http-conduit` caused it to finish in ~7 seconds.

Turning `--count-conflicts` back on allowed cabal to find a solution in ~20 seconds with the first command.  In fact, `--reorder-goals` wasn't necessary, and `cabal install --dry-run --max-backjumps=-1  --index-state 2014-04-15T22:20:17Z` finished in 4 seconds.  The -v3 log showed that the solver chose `http-conduit` at level 154 on its first descent of the search tree but chose it at level 6 before descending to the solution, so `--count-conflicts` had moved it higher up in the tree.

Please open another issue if there is still a problem.
