### ISSUE TITLE
Lens fails to build on Windows with Cabal install 1.20RC2

### ISSUE THREAD

**Issue by mantkiew** [haskell/cabal#1784]
When building my projects and all dependencies from scratch (removed Roaming/cabal and Roaming/ghc) on (Windows 8, HP 2013.2.0.0, GHC7.6.3, Cabal install 1.20 RC2) I got this :

```
Failed to install lens-4.1.2
Last 10 lines of the build log ( C:\Users\mantkiew\AppData\Roaming\cabal\logs\lens-4.1.2.log ):
[77 of 85] Compiling Data.Vector.Lens ( src\Data\Vector\Lens.hs, dist\build\Data\Vector\Lens.o )
... < cut >
[85 of 85] Compiling Codec.Compression.Zlib.Lens ( src\Codec\Compression\Zlib\Lens.hs, dist\build\Codec\Compression\Zlib
\Lens.o )
c:\dev\HaskellPlatform\2013.2.0.0\mingw\bin\strip.exe: cannot create tempdir for archive copying (error: File exists)
cabal.exe: Error: some packages failed to install:
clafer-0.3.6 depends on lens-4.1.2 which failed to install.
lens-4.1.2 failed during the building phase. The exception was:
ExitFailure 1
```

Tried again from scratch - nothing helped.

Then I tried with Cabal 1.18.\* and everything builds and installs normally.

**Comment by michalfapso** [comment]
I had the same problem on mingw. Here is a simple script overcoming the strip's issue with creating temp files: https://gist.github.com/michalfapso/833d4198244698e4266e
