### ISSUE TITLE
cabal repl should allow specifying modules to load

### ISSUE THREAD

**Issue by chowells79** [haskell/cabal#1793]
A common part of my workflow is making experimental changes to a module, then playing with the result in ghci to see if I like how it works out.  Only if it works well do I update all modules that depend on it to work with the new changes.

It's currently not possible to use cabal repl for this case, because it loads all modules in the project, making it fail on any incomplete change.  There is now a workaround available via cabal exec ghci, but it would be nicer if cabal repl supported this use case.

**Comment by gbaz** [comment]
imho sufficiently resolved by https://github.com/haskell/cabal/pull/7578

**Comment by cheater** [comment]
@gbaz so how do I now specify that I want the repl to also load module Foo.Bar and Quux.Baz?

**Comment by gbaz** [comment]
using `:l` in the repl.
