### ISSUE TITLE
Option to unregister older dependencies on install

### ISSUE THREAD

**Issue by k-bx** [haskell/cabal#1803]
I have repos `proj-models`, `proj-config` and `proj`. In `proj` I have sandbox which has `add-source`'d `../proj-models` and `../proj-config`.

The problem: sometimes, after I update a version of `proj-config` (from `1.2.3` to `1.2.4`), upon running `cabal install` inside `proj`, it would say something about `installation may break these packages: proj-config-1.2.3`. So I have to manually run `cabal sandbox hc-pkg unregister proj-config-1.2.3` and only then do `cabal install` (as you mentioned somewhere, I should do `cabal build` instead, but I guess that wouldn't change things).

The problem is that this breaks sometimes my build-scripts, which is not as smart as I am and cannot read output and decide to unregister that package. How should I deal with this ideally? Thank you!

**Comment by ttuegel** [comment]
As we move toward multiple instances, the message about `installation may break packages` will go away, and then there is no reason to do this.
