### ISSUE TITLE
Handle framework paths (-F) in Cabal

### ISSUE THREAD

**Issue by bos** [haskell/cabal#182]
(Imported from [Trac #189](http://hackage.haskell.org/trac/hackage/ticket/189), reported by guest on 2007-12-10)

There's been some discussion on the GHC trac ([1931](http://hackage.haskell.org/trac/ghc/ticket/1931), [1798](http://hackage.haskell.org/trac/ghc/ticket/1798), [1395](http://hackage.haskell.org/trac/ghc/ticket/1395)) about adding framework search paths (gcc's <tt>-F</tt> flag, and ghc's <tt>-framework-path</tt> flag).  Currently Cabal handles <tt>-framework</tt>, but not <tt>-framework-path</tt>.

I propose the following behavior for Cabal:

<ol><li>Add a <tt>framework-path:</tt> field which will pass <tt>-framework-path</tt> to <tt>ghc</tt> and <tt>-F</tt> to <tt>gcc</tt>, <tt>hsc2hs</tt>, et. al.
</li><li>Always add <tt>-F$HOME/Library/Frameworks</tt> as an argument to the above programs (regardless of any <tt>framework-path</tt> entries).
</li></ol>I believe <tt>#1</tt> to be uncontroversial.  My reasoning for <tt>#2</tt> is the following:

<ul><li><tt>$HOME/Library/Frameworks</tt> is the standard location to put frameworks if you do not have administrative access.
</li><li> Without it, <tt>readline.cabal</tt> (e.g.) would need
<pre class="wiki">framework-path: /Users/judah/Library/Frameworks
</pre>which is not portable between machines.
</li></ul>Finally, note that these flags only affect build behavior, not runtime loading of libraries (which searches <tt>$HOME/Library/Frameworks</tt> by default).  See [OSXFrameworks](http://hackage.haskell.org/trac/ghc/wiki/OSXFrameworks) for more info.

-Judah

**Comment by komadori** [comment]
It used to be possible to pass the -framework-path option in via the ghc-options field, but now that shared library builds are standard, the ghcSharedLinkArgs construction in Distribution.Simple.GHC doesn't permit any mechanism for sending custom options to the final link command. AFAICS, on MacOS 10.11, the only way to use a framework without being able to specify this flag is to place it inside the Xcode bundle. This makes it quite difficult to work with frameworks.

I have created a patch to add a framework-dirs field paralleling the existing include-dirs and extra-lib-dirs  fields.
