### ISSUE TITLE
Add check for unused dependencies

### ISSUE THREAD

**Issue by bergmark** [haskell/cabal#1820]
It's quite easy to change some code and as a consequence no longer use a dependency. Currently the only way to prune dependencies (AFAIK) is to remove them from the cabal file and try to build. It would  be nice if `cabal check` or even `cabal install` would give warnings for this so you don't have to remember to do it manually.

Edit: `cabal init` can already generate dependencies, could this check be implemented in terms of that?

**Comment by gbaz** [comment]
also providing related functionality: https://hackage.haskell.org/package/weeder

**Comment by ulysses4ever** [comment]
Should we close it as out of scope since there are standalone tools achieving this, and we can't grow the code base indefinitely?

**Comment by andreabedini** [comment]
💯 yes

**Comment by ffaf1** [comment]
As per consensus
