### ISSUE TITLE
'cabal upload --check' broken

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#1823]
I noticed that `cabal upload --check` is broken, as it uses the [hardcoded](https://github.com/haskell/cabal/blob/3f061c77fa3/cabal-install/Distribution/Client/Upload.hs#L45) URL:

```haskell
checkURI :: URI
Just checkURI = parseURI "http://hackage.haskell.org/cgi-bin/hackage-scripts/check-pkg"
```

Which doesn't seem to work anymore (it responds with a 404). Is it planned to have this functionality restored?

**Comment by ttuegel** [comment]
If this option has been replaced by package candidates, should it be removed?
