### ISSUE TITLE
Does not create ~/Library/Haskell/bin on OS X

### ISSUE THREAD

**Issue by jarrett** [haskell/cabal#1836]
When installing `cabal-install` on OS X, the installer appears to succeed, but then complains that `~/Library/Haskell/bin on OS X` does not exist. (A fresh install of the Haskell Platform does not create the folder.)

Manually creating the folder before running the installer fixes this problem. Most likely, the installer should automatically create the folder if it does not exist.

**Comment by gbaz** [comment]
This _was_ a mac hp installer bug.
