### ISSUE TITLE
cabal install doesn't read changes to .cabal file

### ISSUE THREAD

**Issue by asr** [haskell/cabal#1844]
Minimal example.

````bash
$ cabal --v
cabal-install version 1.20.0.1
using version 1.20.0.0 of the Cabal library 
````
````bash
$ cat test.cabal
name:          Test
version:       0.1.0.0
build-type:    Simple
cabal-version: >=1.10

executable Test
  main-is:          Main.hs
  build-depends:    base >=4.7 && <4.8
  default-language: Haskell2010
````
````bash
$ cat Setup.hs
import Distribution.Simple
main = defaultMain
````
````bash
$ cat Main.hs
module Main where

main = putStrLn "Hello World"
````
Steps for reproducing the issue:
1. Run `cabal install`.
2. Add `ghc-options : -Wall -Werror` to `test.cabal`.
3. Run `cabal install`again.

What is the expected output:
````bash
$ cabal install
...
Main.hs:3:1: Warning:
    Top-level binding with no type signature: main :: IO ()

<no location info>: 
Failing due to -Werror.
Failed to install Test-0.1.0.0
````
What is the current output:
````bash
$ cabal install
...
Installed Test-0.1.0.0
````
That is, `cabal install` didn't read the changes to `test.cabal`.

**Comment by ttuegel** [comment]
You need to run `cabal clean` first. Because the object files already exist, GHC avoids building them a second time, so the new `ghc-options` have no effect.

**Comment by asr** [comment]
> Because the object files already exist, GHC avoids building them a second time

You are right. Since I couldn't reproduce this behaviour using GCC (the GNU Compiler Collection) I opened the issue https://ghc.haskell.org/trac/ghc/ticket/10360.
