### ISSUE TITLE
cabal install silently skips haddock if hyperlink-source enabled and hscolour not installed

### ISSUE THREAD

**Issue by bmmoore** [haskell/cabal#1845]
When I enabled hyperlink-source in .cabal/config, cabal install stopped producing any haddocks, while apparently succeeding. Looking into logs I see things like this:

Running Haddock for lens-4.1.2...
setup: The program 'hscolour' version >=1.8 is required but it could not be
found.

It seems cabal install silently skips the entire haddock step if hscolour is not installed.

**Comment by ttuegel** [comment]
Duplicate of #1216.
