### ISSUE TITLE
Flag constraints are ignored for installed packages

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#1849]
Consider the following scenario:

```
$ cabal sandbox init
$ cabal install -v transformers-compat --constraint "transformers-compat +transformers3"
[Installs transformers-compat +transformers3]
```

However, a subsequent `cabal install -v transformers-compat --constraint "transformers-compat +transformers2"` does nothing, since `transformers-compat` is already installed. This seems to be caused by the fact that the flag assignment is not stored in `InstalledPackageInfo`.

Shouldn't we be able to detect that the flag assignment has changed and the package needs to be reinstalled? Current behaviour means that putting `constraints: foo +bar` in `cabal.config` doesn't actually guarantee that `foo` is compiled with `+bar`.

Fixing this would also let us allow flag constraints in `build-depends`, although I am not sure whether we want to encourage packages with flag assignment-dependent API. Another related issue is storing installed build variants (profiling/dynamic/...) - solver could take into account whether installing `foo` depends on just `libbar` or `libbar +profiling,dynamic`.

(Motivated by [this SO question](http://stackoverflow.com/questions/23523869/is-there-any-way-to-define-flags-for-cabal-dependencies).)

/cc @kosmikus

**Comment by osa1** [comment]
:+1: for this. Another issue I'm having is that we can't use flag constraints in `build-depends` field. Any ideas about that?

**Comment by 23Skidoo** [comment]
`new-build` fixes this.

**Comment by gbaz** [comment]
closing as obsolete
