### ISSUE TITLE
cabal-install 1.16+ saves tarballs with file mode 0600

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#1850]
I see that cabal-install stores source tarballs of downloaded packages with mode 0600 for some reason:

```
$ umask
0002
$ cabal fetch conduit
:
$ ls -l ~/.cabal/packages/hackage.haskell.org/conduit/1.1.1.1/
-rw-------. 1 moi moi 29057 May  5 11:52 conduit-1.1.1.1.tar.gz
-rw-rw-r--. 1 moi moi jens    34 May  5 11:52 conduit-1.1.1.1.tar.gz.etag
```

As you can see for 1.20+ the etag file is saved with the expect filemode but the tarball is 0600.  From my limited testing this doesn't happen with cabal-install-0.14 but seems to happen for cabal-install >= 1.16.  It is not the end of the world but slightly annoying so I thought I would report it here. I haven't worked out yet why this is happening.

**Comment by ttuegel** [comment]
I cannot reproduce this with `cabal-install-1.23.0.0`, so I expect it was fixed and this issue was simply never closed.

**Comment by 23Skidoo** [comment]
May have been a bug in `base` or some other dependency.
