### ISSUE TITLE
Cabal binaries scattered on Win

### ISSUE THREAD

**Issue by cchantep** [haskell/cabal#1862]
In Windows env, cabal binaries are scattared in different directories:
- `cabal.exe` in `$HOME/.cabal/bin`,
- binaries like `alex.exe`, `happy.exe` in `C:\Users\$USER\AppData\Roaming\cabal\bin`.

A unified/common userdir would be nice (`$HOME/.cabal/bin`).

Env: Win7, msys2, cabal1.18

**Comment by jasagredo** [comment]
As Cabal now uses the XDG spec on Windows, binaries are installed by default on `C:/Users/<User>/AppData/Roaming/cabal/bin`, and `cabal.exe` itself is managed by GHCup.

I'm closing this issue. Please re-open if you disagree.
