### ISSUE TITLE
Bad install plan selected for keter with GHC 7.8.2

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#1877]
With a clean package database, I just ran `cabal install keter --dry-run` using ghc-7.8.2 and cabal-install-1.20.0.1. The full output is available at:

https://gist.github.com/snoyberg/d1b9d1d4e3feae8daad9

The important bits:

```
bytestring-0.10.2.0 (latest: 0.10.4.0) (new version)
unix-2.7.0.1 (reinstall) changes: bytestring-0.10.4.0 -> 0.10.2.0
unix-2.7.0.1 (reinstall) changes: bytestring-0.10.4.0 -> 0.10.2.0
Warning: The following packages are likely to be broken by the reinstalls:
haskell98-2.0.0.3
ghc-7.8.2
Cabal-1.18.1.3
bin-package-db-0.0.0.0
hpc-0.6.0.1
Use --force-reinstalls if you want to install anyway.
```

Instead running with `--reorder-goals` generates a more sensible build plan: https://gist.github.com/snoyberg/1a8362ee40aa5b91675b.

This is likely related to #1855.

**Comment by 23Skidoo** [comment]
> As far as I can test, this one is (will be) fixed by #1879.

Closing then.
