### ISSUE TITLE
1.20 regression from 1.18 -- /tmp/pkgConf-unix-compat-0.4.164303.1: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by parfunc** [haskell/cabal#1883]
Under cabal 1.18.0, and GHC 7.8.2, installing unix-compat works fine.  After `cabal sandbox init`, a `cabal install unix-compat` yields:

```
In-place registering unix-compat-0.4.1.1...
Installing library in
/nfs/nfs4/home/parfunc/temp/unix-compat/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.2/unix-compat-0.4.1.1
Registering unix-compat-0.4.1.1...
Installed unix-compat-0.4.1.1
```

But under cabal 1.20.0 I get this:

```
In-place registering unix-compat-0.4.1.1...
Creating package registration file: /tmp/pkgConf-unix-compat-0.4.164303.1
Failed to install unix-compat-0.4.1.1
cabal: Error: some packages failed to install:
unix-compat-0.4.1.1 failed during the final install step. The exception was:
/tmp/pkgConf-unix-compat-0.4.164303.1: hGetContents: invalid argument (invalid
byte sequence)
```

This is happening on RHEL 6.5.  I don't have the problem on Mac OS.

**Comment by mietek** [comment]
[Halcyon](https://halcyon.sh) includes a workaround for this issue.

**Comment by hoosierEE** [comment]
@wereHamster  - your comment pointed me in the right direction, thanks!

I was having the `invalid argument (invalid byte sequence)` issue with tf-random-0.5 on ARM, specifically:

    $ uname -m
    armv7l

...but after a quick google, the [Arch wiki](https://wiki.archlinux.org/index.php/Locale#Other_uses) came to the rescue, as the following fixed it for me and I was able to install tf-random:

    $ export LANG="C.UTF-8"
