### ISSUE TITLE
C-c fails in "cabal repl", works fine in "ghci"

### ISSUE THREAD

**Issue by osa1** [haskell/cabal#1885]
Hi all,

I remember having this very annoying problem in the past, and it was working for last few months(I don't know what changed) but now I'm having this problem again. I did not update anything Cabal/Haskell related, but I made some updates on my Linux distro and restarted the system -- then had this issue again.

`C-c` fails in `cabal repl`, but works fine in `ghci`. Here's an example:

(I trimmed output a bit, and put `^C` and `^D` markers to show what I typed)

```
➜  ghcjs git:(work) ✗ cabal repl
...
[40 of 40] Compiling GHCJS            ( src/GHCJS.hs, interpreted )
Ok, modules loaded: ...
ghci> ^C
ghci> 
➜  ghcjs git:(work) ✗ 
➜  ghcjs git:(work) ✗ 
➜  ghcjs git:(work) ✗ 
➜  ghcjs git:(work) ✗ 
➜  ghcjs git:(work) ✗ 
➜  ghcjs git:(work) ✗ 
<stdin>: hGetChar: hardware fault (Input/output error)


➜  ghcjs git:(work) ✗ which cabal
/home/omer/.cabal/bin/cabal
➜  ghcjs git:(work) ✗ cabal --version
cabal-install version 1.21.0.0
using version 1.21.0.0 of the Cabal library 
➜  ghcjs git:(work) ✗ ghci
GHCi, version 7.8.2: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
ghci> ^C 
ghci> ^C
ghci> ^D
Leaving GHCi.
```

Can anyone help me with this? I'm using C-c in the REPL all the time and this is just too annoying for me.

EDIT: to clarify, C-c is control-c (sometimes also written as ^C)

**Comment by ezyang** [comment]
This seems to be fixed in HEAD.
