### ISSUE TITLE
cabal sandbox --help does not include short description of what the commands do

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell/cabal#1886]
The --help informaion in cabal isn't informative enough.

$ cabal sandbox --help
Usage: cabal sandbox init
   or: cabal sandbox delete
   or: cabal sandbox add-source  [PATHS]

   or: cabal sandbox hc-pkg      -- [ARGS]
   or: cabal sandbox list-sources

Flags for sandbox:
 -h --help        Show this help text
 -v --verbose[=n] Control verbosity (n is 0--3, default verbosity level is 1)
    --snapshot    Take a snapshot instead of creating a link (only applies to
                  'add-source')
    --sandbox=DIR Sandbox location (default: './.cabal-sandbox').

Compare this to: 

$ go help
Go is a tool for managing Go source code.

Usage:

	go command [arguments]

The commands are:

    build       compile packages and dependencies
    clean       remove object files
    env         print Go environment information
    fix         run go tool fix on packages
    fmt         run gofmt on package sources
    get         download and install packages and dependencies
    install     compile and install packages and dependencies
    list        list packages
    run         compile and run Go program
    test        test packages
    tool        run specified go tool
    version     print Go version
    vet         run go tool vet on packages

What cabal should be printing is something like:

$ cabal sandbox --help
Usage: cabal sandbox init    *Create a new sandbox*
   or: cabal sandbox delete   *Delete a sandbox*
   or: cabal sandbox add-source  [PATHS]

   or: cabal sandbox hc-pkg      -- [ARGS]  *WTF is this doing??*
   or: cabal sandbox list-sources  *List sources*

Flags for sandbox:
 -h --help        Show this help text
 -v --verbose[=n] Control verbosity (n is 0--3, default verbosity level is 1)
    --snapshot    Take a snapshot instead of creating a link (only applies to
                  'add-source')
    --sandbox=DIR Sandbox location (default: './.cabal-sandbox').

**Comment by lspitzner** [comment]
i think this can be closed now that #2259 is merged.
