### ISSUE TITLE
cabal register always registers to the user database

### ISSUE THREAD

**Issue by JohnLato** [haskell/cabal#1887]
Running `cabal register`, regardless of any flags specified (any permutation of `--global`, `--user`, or `--inplace`), always calls `ghc-pkg update --global --user`, and thus always installs to the user database.

This can be observed by calling `cabal register --gen-script` and checking the last line of the script, or calling `cabal register` and checking with `ghc-pkg`.

```
cabal-install version 1.20.0.0 
using version 1.20.0.0 of the Cabal library
```

**Comment by phadej** [comment]
IIRC `cabal register` respects whatever `--package-db` stuff is supplied to `cabal configure`

```
 % cabal configure --package-db=clear --package-db=global
Resolving dependencies...
Configuring acme-operators-0.2.0.0...

% cabal build
Building acme-operators-0.2.0.0...
Preprocessing library acme-operators-0.2.0.0...
[1 of 1] Compiling Acme.Operators.Base ( src/Acme/Operators/Base.hs, dist/build/Acme/Operators/Base.o )
In-place registering acme-operators-0.2.0.0...

% cabal register --gen-script                           
Creating package registration script: register.sh

% tail register.sh 
trusted: False
import-dirs: /Users/ogre/Library/Haskell/ghc-7.8.4-x86_64/lib/acme-operators-0.2.0.0
library-dirs: /Users/ogre/Library/Haskell/ghc-7.8.4-x86_64/lib/acme-operators-0.2.0.0
data-dir: /Users/ogre/Library/Haskell/share/ghc-7.8.4-x86_64/acme-operators-0.2.0.0
hs-libraries: HSacme-operators-0.2.0.0
depends:
    base-4.7.0.2-918c7ac27f65a87103264a9f51652d63
haddock-interfaces: /Users/ogre/Library/Haskell/ghc-7.8.4-x86_64/lib/acme-operators-0.2.0.0/doc/html/acme-operators.haddock
haddock-html: /Users/ogre/Library/Haskell/ghc-7.8.4-x86_64/lib/acme-operators-0.2.0.0/doc/html
' | '/usr/local/bin/ghc-pkg' 'update' '-' '--global' '--no-user-package-db' "$@"
```

---

IMHO we should just drop `--user` and `--global` as `register` command is stateful and respects whatever `configure` was given. Even *worse*, you **have to** build the package before you can register it.

So only `--inplace` flag makes sense for `register`, because you can register either in the last package db anyway or *in place* one, which is one more db at the top of the db stack.

**Comment by ttuegel** [comment]
I'm assigning this to myself as part of my reconfigure branch. With seamless reconfiguration and rebuilding, we can support these flags to register properly.

**Comment by gbaz** [comment]
closing as obsolete
