### ISSUE TITLE
'cabal list' should always work, even if 'require-sandbox: True'

### ISSUE THREAD

**Issue by choener** [haskell/cabal#1889]
'cabal list' should work, even if
~~~
require-sandbox: True
~~~
is set in the cabal config.
(I guess this should hold for all ``query-like'' operations?)

~~~
cabal-install version 1.20.0.1
using version 1.20.0.0 of the Cabal library 
~~~

**Comment by 23Skidoo** [comment]
Fixed by 121c9de9b3219b148ff633ebf242603e2f76917b.
