### ISSUE TITLE
Document "default-language"

### ISSUE THREAD

**Issue by massysett** [haskell/cabal#1894]
The "Developing Cabal Packages" here makes no mention of it:

http://www.haskell.org/cabal/users-guide/developing-packages.html

**Comment by joecrayne** [comment]
Related question:  If I want cabal to use the default language of GHC, can it be done while specifying a default-language?   Specifying Haskell2010 causes my code not to compile without adding more LANGUAGE pragmas.

**Comment by carymrobbins** [comment]
Same with `other-languages`, `default-extensions`, and `other-extensions`.  Also, [BuildInfo](https://hackage.haskell.org/package/Cabal-1.22.8.0/docs/Distribution-PackageDescription.html#t:BuildInfo) seems to have an `oldExtensions` field, not sure if that means that the cabal file may also have an `old-extensions` field.

**Comment by 23Skidoo** [comment]
> `default-extensions`, and `other-extensions`.

They are documented in `master`.

**Comment by jneira** [comment]
closing in favour of #6755, @massysett thanks for pointing out the lack of docs about
Duplicate of #6755
