### ISSUE TITLE
Add -w flag to cabal sandbox hc-pkg?

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#1899]
To select which ghc version to use, I use the `-w` flag, like `cabal install -w ghc-7.8 ...`.

However, when I use `cabal sandbox hc-pkg list`, I will only always get results for `.cabal-sandbox/x86_64-linux-ghc-7.6.3-packages.conf.d`.

Should `cabal sandbox hc-pkg` have a `-w` flag, or is there a different way to select which compiler's package db `hc-pkg` shall look at? If so, it would be great if that could be mentioned in `cabal help sandbox`.

**Comment by adamgundry** [comment]
The problem with `cabal sandbox hc-pkg` not using the configured compiler is fixed by #2859. For the remaining feature request (`-w` flag for `cabal sandbox hc-pkg` and `cabal exec`) see #2177.
