### ISSUE TITLE
add-source --snapshot gets wedged when dependency is missing a file

### ISSUE THREAD

**Issue by acfoltzer** [haskell/cabal#1904]
Suppose I want to add a snapshot of package `foo` to my `bar` sandbox, but `foo` is missing `some-extra-file.txt` listed in its `extra-source-files`. I end up with the following behavior:

```
% cabal sandbox add-source --snapshot ~/src/foo
cabal: some-extra-file.txt: does not exist
```

Then I fix the problem by moving `some-extra-file.txt` to the correct place in `~/src/foo`, and re-add:

```
% cabal sandbox add-source --snapshot ~/src/foo
cabal:
~/src/bar/.cabal-sandbox/snapshots/foo-0.0.1:
does not exist
```

Apparently a tmp version of the snapshot ends up in the directory, and I have to delete it before I can attempt to add the snapshot again.

```
% ls .cabal-sandbox/snapshots/
foo-0.0.1-tmp/
% rm -rf .cabal-sandbox/snapshots/foo-0.0.1-tmp
% cabal sandbox add-source --snapshot ~/src/foo
```

My guess is there's some extra cleanup that needs to happen in case adding the snapshot fails.

**Comment by phadej** [comment]
sandbox functionality is removed.
