### ISSUE TITLE
cabal-install 1.20 generates build reports that Hackage can't parse

### ISSUE THREAD

**Issue by lfairy** [haskell/cabal#1918]
See haskell/hackage-server#226.

Cabal 1.20 tries to save space (I think) by eliding fields with empty values. Unfortunately, the Hackage parser requires that all fields are present, even if empty. This causes the doc builder to fail (400 Bad Request) when it uploads a report.

To reproduce, try:

```
cabal install hello-1.0 --build-summary=alpha
cabal install hello-1.0.0.2 --build-summary=beta
```

You'll notice that `beta` includes a "flags" entry, whereas `alpha` does not.

I'm not quite sure whether we should fix Hackage here, or Cabal. I personally prefer fixing Cabal, because I'm sure other consumers wouldn't expect the field to be missing either.

**Comment by quasicomputational** [comment]
This seems to have been fixed on the Hackage side and there've been no other complains about this, so closing.
