### ISSUE TITLE
Allow more convenient use of ghc profiling options -auto and -auto-all

### ISSUE THREAD

**Issue by bos** [haskell/cabal#193]
(Imported from [Trac #200](http://hackage.haskell.org/trac/hackage/ticket/200), reported by guest on 2007-12-18)

Add Setup.(l)hs options that: 1) tells ghc to make a profiling library; 2) tells ghc to make a profiling executable 3) pass on the (a) -auto or (b) -auto-all option 4) Let you do (1)-(2)-(3a) or (1)-(2)-(3b) with a single option, instead of three.

**Comment by iustin** [comment]
I also happened to get confused by this when migrating a project from Makefile/ghc --make to pure cabal. What's the status? Is the still at the "we need to decide on the command line arguments"?

**Comment by ttuegel** [comment]
As of Cabal-1.22, the command line options to Cabal have changed. Library profiling is enabled through `--enable-library-profiling`. Executable profiling is enabled by `--enable-profiling` and it implies `--enable-library-profiling`. Each of these implies the GHC option `-prof` during the appropriate phase, but no other options. GHC now has a [wider range](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/prof-compiler-options.html) of profiling options. I think it would make the most sense to apply `-fprof-auto`; it doesn't generate too many SCCs like `-fprof-calls`, but it also generates enough SCCs that stack traces are useful. No one is working on this at the moment.

**Comment by ttuegel** [comment]
As documented on [this haskell-cafe thread](http://haskell.1045720.n5.nabble.com/ghc-prof-options-and-libraries-on-Hackage-td5756706.html), `-fprof-auto` can have very high costs, giving misleading profiles. On the other hand, `-fprof-auto-exported` only generates SCCs for exported bindings, which is low cost and more generally useful. I recommend that we make that the default for libraries. For executables, which generally do not have exported bindings, I recommend we use `-fprof-auto-top` by default. It generally has a higher cost that `-fprof-auto-exported`, but one only builds executables with profiling if one really wants the profiling information.

**Comment by iustin** [comment]
Thanks for the information, I was not aware of the recent GHC changes, and neither of the fact that auto-all is that expensive. Looking forward to have this merged in!

**Comment by ttuegel** [comment]
I think this issue is half-solved in its current state. We have reasonable default options. I would like to add an optional argument to `--enable-profiling` to allow the user to select from the available profiling options, e.g. `--enable-profiling=auto` to enable `-fprof-auto`, etc.

**Comment by ttuegel** [comment]
Oh, my mistake, it looks like this was already done.
