### ISSUE TITLE
cabal check accepts any file matching "*.cabal", but must be $packagename.cabal

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#1936]
My project named "foo" contained Foo.cabal. cabal check reported no problems at all. Hackage does not accept the package, because "missing 'foo.cabal'".

Furthermore, I tested if cabal check just ignores the case:

```
> mv Foo.cabal bar.cabal
> cabal check
No errors or warnings [..]
```

As I understand, cabal check should have the same requirements as hackage, so this is a bug.

```
> cabal --version
cabal-install version 1.20.0.2
using version 1.20.0.0 of the Cabal library 
```

**Comment by ffaf1** [comment]
`cabal 3.8.1.0` warns about this portability problem.

     Warning: The filename './Ttt.cabal' does not match package name (expected:
     'ttt.cabal')

Closing this.
