### ISSUE TITLE
Shared BuildInfo between targets

### ISSUE THREAD

**Issue by rudymatela** [haskell/cabal#1949]
A nice feature to add would be to share properties between targets.  A common thing to see (even in cabal's `.cabal` file):

```
library
  exposed-modules: Blah, Bleh
  ghc-options: -Wall -Wsomething
  default-language: Haskell 2010
  if flag(debug)
    cpp-options: -DDEBUG

Test-Suite test
  ...
  ghc-options: -Wall -Wsomething
  default-language: Haskell 2010
  if flag(debug)
    cpp-options: -DDEBUG

Executable blah
  ...
  ghc-options: -Wall -Wsomething
  default-language: Haskell 2010
  if flag(debug)
    cpp-options: -DDEBUG
```

It would be nice to be able to declare the 4 lines as a set of options and just reference them on the different targets.  With the new `.cabal` looking more or less like:

```
Common-Properties commonflags
  ghc-options: -Wall -Wsomething
  default-language: Haskell 2010
  if flag(debug)
    cpp-options: -DDEBUG

library
  exposed-modules: Blah, Bleh
  include-properties: commonflags

Test-Suite test
  ...
  include-properties: commonflags

Executable blah
  ...
  include-properties: commonflags
```

**Comment by rudymatela** [comment]
By the way, I've seen a few posts on stackoverflow related to this issue:

* [Eliminating repetition in cabal files](https://stackoverflow.com/q/15179316/)
* [How to reduce duplication in the build-depends fields of a .cabal file?](https://stackoverflow.com/q/10163604/)

**Comment by ulysses4ever** [comment]
Should this be closed in the light of common stanzas? (#4751, bfb1967c096c, possible dup of #2832)

**Comment by Mikolaj** [comment]
@rudymatela: would you like to comment? Alternatively, we can close this ticket and you are very welcome to open a new one once you have the time to investigate the new cabal feature that plausibly solves this issue.

**Comment by rudymatela** [comment]
@ulysses4ever @Mikolaj I did not test the common stanzas feature, but by reading the relevant tickets (#4751, #2832) they seem to resolve this issue.

Thanks for addressing this!

I will close now.

**Comment by Mikolaj** [comment]
Thank you!
