### ISSUE TITLE
install --only-dependencies & package flags

### ISSUE THREAD

**Issue by cchantep** [haskell/cabal#1951]
Using `cabal install --only-dependencies -f package_flag`, _package_flag_ is ignored, at least with cabal 1.18.1.3/windows (e.g. with gtk3 package, flag `-f -fmode-binary`).

**Comment by jneira** [comment]
@cchantep flags works in general so i am gonna close this optimistically, please feel free to reopen if it reproduces with newer versions of cabal-install
