### ISSUE TITLE
Problem with cabal freeze constraints on 1.20.0.2 vs 1.20.0.1

### ISSUE THREAD

**Issue by freebroccolo** [haskell/cabal#1955]
I'm not exactly sure what's going on but there's a thread describing some issues @jonsterling and I encountered when using `cabal freeze`.

Specifically, `1.20.0.2` records constraints incompatible with `1.20.0.1` and earlier versions of `cabal-install` which are otherwise capable of compiling the package. I'm not sure if this is related to the solver fix in the `.2` bump or something else but there are further details in the issue thread: https://github.com/jonsterling/TT-Reflection/pull/15#issuecomment-46640396

Also some comments at: https://twitter.com/darinmorrison/status/480059427324588032

**Comment by ttuegel** [comment]
@benarmston @freebroccolo Were either of you able to reproduce this?

**Comment by benarmston** [comment]
I didn't look into it further than is stated on the ticket. I think we can
close this and reconsider if a reproducible test case is provided.

**Comment by ttuegel** [comment]
Right then, I'm closing this for now. Please ping me if it needs reopened!
