### ISSUE TITLE
Something like --save in npm?

### ISSUE THREAD

**Issue by kvanbere** [haskell/cabal#1961]
npm (the Node.js package manager) allows you to install packages and automatically add the latest version to the dependency list of your package.

It would be cool if you could add a --save flag, which given any scope (including sandboxes) would look for a .cabal file in the current directory and
- If it's already installed, add the latest version to the depends
- If it isn't installed, download, install and then append the latest version to the depends

Example usage:

```
cabal sandbox init
cabal install pipes --save
```

At least for my node project, it made dependency version management super breezy.

**Comment by hughfdjackson** [comment]
:+1: from me too - I really enjoy this feature for fast prototyping in node; something i really enjoy doing in haskell too.  A little thing, but it makes a developer-happiness difference for me :)

**Comment by baconscript** [comment]
:+1: -- exactly what hughfdjackson said

**Comment by a-x-** [comment]
:+1: for a `--save` feature (and -S alias) like npm!

It's very inconvenient edit .cabal for adding package!
How you live so?

**Comment by folsen** [comment]
I just sat down to see if I could implement this and found a difference between what `cabal` does and what `npm` does that affects this. In `npm` you only have two types of dependencies, package dependencies and development dependencies, represented by the two `--save` and `--save-dev` commands.

In `cabal` however you have 0 or 1 library and 0 or more executables, test-suites and benchmarks. These can all have their own separate dependencies.

So what makes the most semantic sense for a `--save` command in `cabal`? I can see 3 options.

1. It adds the installed package as a dependency to the library (if there is one).
1. It adds the installed package as a dependency to _all_ the components in the project (library, all executables etc)
1. We add an optional argument to the `--save` flag such that without it, it adds the installed package to the library, and you can optionally add component(s) by name just like the `cabal build` command.

**Comment by a-x-** [comment]
Thank you for research!

I'm beginner in Haskell, and think that `--save` might be working with library by default and would be `--save-in-component $component_name` with components if them has some unique IDs.

If save to all use case is common, that team would be add something like this `--save-to-all` too.

_Excuse my beginner's English_

**Comment by Fresheyeball** [comment]
cabal file
```cabal
executable server
  -- stuff
  build-depends:       base >=4.8 && <4.9
```

```bash
cabal install foo --save server build
cabal install foo#1.3.6 --save server build
```

result
```cabal
executable server
  -- stuff
  build-depends:       base >=4.8 && <4.9
                               , foo 1.3.6
```

**Comment by Wizek** [comment]
This is a shell script 'solution' I've put together so we can have this functionality even before it is implemented in cabal: https://github.com/Wizek/cabal-install-save

It looks for the latest version of the specified package, adds it to the *.cabal file then does a `cabal install --only-dependencies`.

Installation:

```bash
$ git clone git@github.com:Wizek/cabal-install-save.git
$ # Export to path:
$ echo 'export $PATH:'`pwd`'/cabal-install-save/bin' >> ~/.*hrc
```

Usage: 

```bash
$ cd /to/a/cabal/project
$ cabal-install-save foobar
``` 

Questions, comments, issues and pull requests are welcome.

**Comment by Fresheyeball** [comment]
Correct me if I'm wrong, but I think this issue has been addressed by **stack**. No? Shouldn't we just use **stack** from now on instead of using cabal directly? At the very least for conveniences like those being discussed here?

**Comment by 23Skidoo** [comment]
How does `stack` solves this problem?

**Comment by phadej** [comment]
AFAIK `stack` never modifies `*.cabal` files.

**Comment by folsen** [comment]
One of the fundamental problems here is that there's not a "proper" parser for `*.cabal` files, the parser that's in place in the cabal library (not `cabal-install` and so `stack` wouldn't solve this problem) throws away a lot of information like structure, comments, etc. The `.cabal` format is actually quite complex, allowing conditionals etc in the package description.
Once a better parser exists it would be trivial to add the `--save` feature, but I personally put the project on the shelf because I didn't have time to write a new parser. I know there's some thought/activity on it though from people like Duncan.

**Comment by zsszatmari** [comment]
:+1:

**Comment by gbaz** [comment]
closing as dup in favor of linked ticket
