### ISSUE TITLE
cabal update with unreachable http_proxy yields unhelpful cabal: does not exist

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#1962]
In order to avoid  #1602 I upgraded HTTP to version 4000.2.17. But I noticed a new (minor) problem: If the proxy mentioned in http_proxy is down, I get
```
(sid)root@kirk:~# unset http_proxy
(sid)root@kirk:~#  cabal update
Downloading the latest package list from hackage.haskell.org
(sid)root@kirk:~# export http_proxy=http://localhost:3128/
(sid)root@kirk:~#  cabal update
Downloading the latest package list from hackage.haskell.org
cabal: does not exist
# now starting the proxy
(sid)root@kirk:~#  cabal update
Downloading the latest package list from hackage.haskell.org
```

Certainly the error message could be more helpful.

**Comment by ttuegel** [comment]
@23Skidoo Did you intend to re-open this?

**Comment by 23Skidoo** [comment]
It looks like [I reverted that commit](https://github.com/haskell/cabal/commits/master/cabal-install/Distribution/Client/HttpUtils.hs). IIRC I didn't like how that patch replaced all possible HTTP error messages (which can be quite useful, as in example above) with `"Cannot connect to uri. Is http_proxy set?"`. Should be easy to fix by just re-raising the exception.

**Comment by 23Skidoo** [comment]
Hmm, looks like it only handles `DoesNotExistError`. Maybe I just wanted to improve the patch a bit and then forgot about it.
