### ISSUE TITLE
`cabal test --test-show-details=streaming` should support colour output

### ISSUE THREAD

**Issue by mietek** [haskell/cabal#1963]
As discussed in https://github.com/haskell/cabal/issues/1601#issuecomment-29897670

Paging @ttuegel, @dag.

**Comment by Rufflewind** [comment]
There is an easier workaround via the `script` utility, which does all the tricky TTY emulation and stuff.  (It doesn't fix all the problems though; color codes will still get recorded to file, but you could argue that's a "feature" too: you can view the colored output using `less -R`.)

To make it work, there needs to be a way to invoke the test executable via a wrapper of some kind.  This would have applications beyond colored output and should be relatively easy to implement.

Therefore, the easiest way to get colored output is if Cabal supported a way to *indirectly* invoke the test executable via a flag or .cabal setting (or both?), e.g.

~~~
cabal test --test-runner=./faketty.sh --test-option=opt1
~~~

which would call the test executable like this:

~~~
./faketty.sh dist/build/test/mytest opt1
~~~

You can then put this in `faketty.sh`:

~~~sh
#!/bin/sh
p="s/'/'\\\\''/g"
cmd=
for arg; do
    cmd="$cmd '"`printf "%s" "$arg" | sed "$p"; printf "'"`
done
exec script -e -q -c "$cmd" /dev/null 2>/dev/null
~~~

**Comment by ttuegel** [comment]
> To make it work, there needs to be a way to invoke the test executable via a wrapper of some kind. This would have applications beyond colored output and should be relatively easy to implement.

Not yet, but your contribution would be welcome!

For this particular case, I think it would be best if this worked out-of-the-box. If we added `script` to the [list of configurable programs](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Program/Builtin.hs), we could build this function into the test runner (while having the ability to fallback to something else if `script` isn't available).

**Comment by erikd** [comment]
> Does this issue affect cabal new-test as well?

Yes it does!

**Comment by erikd** [comment]
Colored test output works with `cabal test --test-show-details=direct`.

See also: https://github.com/haskell/cabal/issues/6129

**Comment by yaitskov** [comment]
Why command line flag is so long?  I would expect something like `-d`

**Comment by gbaz** [comment]
Given that we have `direct` does this ticket really still make sense?

**Comment by Mikolaj** [comment]
@gbaz: no, the ticket seems to be outdated. Let's close.

@yaitskov: you can set `test-show-details: direct` in your cabal.project file and then the length no longer hurts. But feel free to review our commandline options and propose a sensible scheme of one-letter counterparts for all (most?) in a new ticket, especially if you'd like to implement that. That may be ripe for some overhaul.
