### ISSUE TITLE
cabal init should create a src directory by default

### ISSUE THREAD

**Issue by kvanberendonck** [haskell/cabal#1967]
I thought this was only annoying me, but I got quite a few upvotes when I mentioned this in a reddit thread.

http://www.reddit.com/r/haskell/comments/294ihr/what_would_you_want_out_of_a_cabal_enhancement/cihdo3d

Basically, `cabal init` sets up the project to have the `Main.hs` file in the same directory as the cabal file which is not the intention in prettymuch every use case. Most people create a `src` directory and setup `hs-source-dirs` accordingly. It would be great if cabal did this by default (including create the directory).

For bonus points, in executable projects create a `Main.hs` file in the `src/` directory with `Hello, World!` so that `cabal init` projects build out of the box.

**Comment by ttuegel** [comment]
It appears this issue is fixed in master, is that correct?

**Comment by byorgey** [comment]
That's correct, I hadn't noticed this issue was still open.
