### ISSUE TITLE
Disabling library-for-ghci by default broke the plugins package

### ISSUE THREAD

**Issue by dmbarbour** [haskell/cabal#1968]
Cabal's earlier versions have "--enable-library-for-ghci" as the default, and it has been documented as the default, e.g. [here](http://www.haskell.org/ghc/docs/7.0.2/html/Cabal/builders.html). It seems that at least version 1.20.0.0 has the opposite default (I just upgraded from 1.16.0.2 from Ubuntu up to 1.20.0.0 so I'm not sure about the intermediates). This is unfortunately a breaking change for the 'plugins' library, which apparently relies on the '.o' library files.

**Comment by Mikolaj** [comment]
Hi! It seems we now need to disable the flag for good on Windows, see #8062.

Can you try if you this still breaks plugins (or anything) with newest master branch cabal code? Thank you!

**Comment by dmbarbour** [comment]
Sorry, not using Haskell any longer. Left for F# due to better support runtime code loading.

A quick glance through the Plugins package source code (last updated Feb 19, 2021 by Jeremy Shaw @stepcut) seems to show it still relies on `.o` files. He's the maintainer of Plugins, and should be the one to talk to.

**Comment by Mikolaj** [comment]
@dmbarbour: thank you

@stepcut: do you know if disabling "--enable-library-for-ghci" by default would still break Plugins in ghci on Windows? Any ideas how to work around or how to fix it in cabal or GHC? It seems we have to disable this on Windows #8062, so a way to handle the fallout would be great.

**Comment by jneira** [comment]
I can't even build the package in windows in cmd or msys2 shell:

```
D:\ws\haskell\issues\plugins-1.6.2>cabal build --disable-library-for-ghci
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - plugins-1.6.2 (lib:plugins) (first run)
Configuring plugins-1.6.2...
configure: WARNING: unrecognized options: --with-compiler
checking build system type... /D/ws/haskell/issues/plugins-1.6.2/config.guess: unable to guess system type

This script, last modified 2002-07-23, has failed to recognize the operating system you are using. It is advised that you download the most up to date version of the config scripts from

    ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (/D/ws/haskell/issues/plugins-1.6.2/config.guess) is already up to date, please send the following data and any information you think might be pertinent to <config-patches@gnu.org> in order to provide the needed information to handle your system.

config.guess timestamp = 2002-07-23

uname -m = x86_64
uname -r = 3.3.3-341.x86_64
uname -s = MSYS_NT-6.1-7601
uname -v = 2022-01-18 13:00 UTC

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = x86_64
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = x86_64
UNAME_RELEASE = 3.3.3-341.x86_64
UNAME_SYSTEM  = MSYS_NT-6.1-7601
UNAME_VERSION = 2022-01-18 13:00 UTC
configure: error: cannot guess build type; you must specify one
```

and

```
# cabal build --disable-library-for-ghci
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - plugins-1.6.2 (lib:plugins) (first run)
Configuring plugins-1.6.2...
configure: WARNING: unrecognized options: --with-compiler
configure: loading site script D:/msys64/etc/config.site
checking build system type... Invalid configuration `x86_64-pc-msys': system `msys' not recognized
configure: error: /bin/sh /D/ws/haskell/issues/plugins-1.6.2/config.sub x86_64-pc-msys failed
```

**Comment by jneira** [comment]
The package https://github.com/stepcut/plugins claims it is buildable with cygwin, which is not widely used nowadays:

> On cygwin/windows you (a) make sure the cygwin "find" is before the
>  windows "find" on your PATH, and (b) to give the windows-style path
>  (e.g., "c:/cygwin/usr/local") in the ./configure --prefix=foo/bar
>  step

**Comment by jneira** [comment]
ok, it allows build with mingw shell so i've got to pass the configure step and reach a build error, with both `--enable-library-for-ghci` and `--disable-library-for-ghci` and ghc-8.6.5:

```
src\System\Plugins\Consts.hs:39:23: error:
    lexical error in string/character literal at character 'g'
   |
39 | ghcLibraryPath  = GHC_LIB_PATH
   | 
```

**Comment by bgamari** [comment]
My understanding is that this issue is really the result of a bug in the `plugin` package anyways; it depends upon GHCi libraries which in general are not universally available and not a "stable" feature of the Haskell packaging story (especially after this change). The correct fix here would have been to fix the `plugin` package to accept archives, not to revert #977.
