### ISSUE TITLE
Can't prevent cabal-install from touching my home directory

### ISSUE THREAD

**Issue by jsw-fnal** [haskell/cabal#1978]
Even though I use a sandbox, cabal-install still creates a directory in $HOME, and promptly fills it with well over a hundred MB of tarballs.  When users on some systems (including the one I was using) have home directory quotas in the ~1GB range, this is not good.  At minimum, there should be a way to redirect that to a more acceptable location such as a scratch disk.  But it seems to my (admittedly naive) way of thinking that it would be better not to write to the filesystem outside the sandbox directory.

**Comment by jneira** [comment]
Nowadays, afaics if you set `$CABAL_DIR`, cabal will write all the required files in that path, without touching home (just i checked it)
@jsw-fnal feel free to reopen if it does not work for you
