### ISSUE TITLE
cabal doesn't reconfigure after cabal.config changes.

### ISSUE THREAD

**Issue by spl** [haskell/cabal#1992]
Through my experimentation, it seems like `cabal.config` is not considered for `cabal configure`. For example, change a version number in `cabal.config` and `configure` still thinks you're using the previous version (if it's still available in a package database).

First, is this always true?

Second, is it possible to always reconfigure if `cabal.config` changes, much like we do when the `.cabal` file changes?

My use case for the latter is when sharing a `cabal.config` file among multiple people in a repository for the same project. When somebody updates the `cabal.config`, it should cause a reconfigure for everybody else.

I suppose an alternative approach would be to put those constraints directly into the `.cabal` file. But that makes it more difficult to use `cabal freeze`.

**Comment by ulysses4ever** [comment]
I think this is not relevant anymore with v2-configure being completely optional and v2-build doing all the heavy-lighting including consulting with the project file. Should this be closed?

**Comment by Mikolaj** [comment]
I think so. Thank you everybody, closing.
