### ISSUE TITLE
Show dependencies for non-libraries with cabal info

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#1999]
Currently, `cabal info` will only list the dependencies of a package's library component, and not the dependencies of its executables, test suites, etc. It would be useful to be able to view them for the [`cab`](https://github.com/kazu-yamamoto/cab) program. It has a `cab revdeps <package>` feature which lists all packages that depend on a particular package, but it can only list dependent libraries, not executables or test suites.

**Comment by RyanGlScott** [comment]
On further thought, I'm not sure how feasible this is in the grand scheme of things, given that `Cabal` doesn't "register" installed executables in any sense, so I don't know how `Cabal` could even obtain this knowledge.

**Comment by ezyang** [comment]
We would have to start "registering" executables by some alternate mechanism. It's certainly doable; e.g., if you look at the Nix local build store, every install directory contains a `cabal-hash.txt` which records dependencies.

**Comment by mgsloan** [comment]
Not sure if it's relevant, but FYI stack does have a system for registering executables, so that we know when the version has changed and needs to be built / copied.

**Comment by RyanGlScott** [comment]
Closing stale issue.
