### ISSUE TITLE
allow preprocessor chaining

### ISSUE THREAD

**Issue by bos** [haskell/cabal#20]
(Imported from [Trac #13](http://hackage.haskell.org/trac/hackage/ticket/13), reported by @syntaxpolice on 2005-10-31)

Allow preprocessor chaining so that a file can be preprocessed by more than one tool.

**Comment by jsl** [comment]
The comments on this ticket point to other issues that have been closed due to inactivity, or are dead links. No new comments on this ticket in almost three years.

I propose we close this due to lack of activity. Please open a new issue if this is still desired.

/cc @tibbe

**Comment by 23Skidoo** [comment]
Closing.
