### ISSUE TITLE
cabal: Codec.Compression.Zlib: premature end of compressed stream

### ISSUE THREAD

**Issue by Zane-XY** [haskell/cabal#2001]
I am using ghc 7.8.3 with:

```
cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.1 of the Cabal library
```

When I am trying to install `scion-browser` inside a fresh sandbox, I got the following error:

```
cabal install scion-browser
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/username/haskell/scion-browser/.cabal-sandbox
Configuring haskell-src-exts-1.14.0.1...
Configuring persistent-template-1.3.1.4...
cabal: Codec.Compression.Zlib: premature end of compressed stream
```

What does the error mean? How to fix it?

**Comment by tobiasBora** [comment]
Hello,

I also have this very annoying problem, and I also run under a university proxy. I can help you to debug if needed !

**Comment by phadej** [comment]
I'm not sure, there might be different problems:
- multiple users: `//root/.cabal/packages/hackage.haskell.org/00-index.tar.gz` path is suspicious
- something weird happening with `zlib`, `cabal-install-1.24` compiled with `zlib-0.6.*` should be quite robust, can you try it?

**Comment by ambuc** [comment]
I have the same issue:
```
$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library 

$ cabal install permutation
Resolving dependencies...
cabal: Codec.Compression.Zlib: premature end of compressed stream
```
Happy to help debug / provide more info. if needed.

**Comment by jneira** [comment]
It seems newer version of cabal-install dont suffer from this bug. Closing optimistically, if anybody participating here can reproduce it with a newer version of cabal, feel free to reopen
