### ISSUE TITLE
Cabal shows a misleading message

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#2013]
**Steps to reproduce:**

 - Start with a clean sandbox
 - Run `cabal install --dry-run --constraint 'aeson>=0.8.0.0' 'snap==0.13.2.8'`

**Actual message:** Contains the line `trying: lens-4.3 (dependency of snap-0.13.2.8)`. But lens-4.3 is not a dependency of snap-0.13.2.8. In fact, that snap version has an upper bound on lens <4.2.

**Expected result:** Something along the lines that snap-0.13.2.8 has a upper bound on aeson <0.8.

**Comment by kosmikus** [comment]
I'm working on this now.

**Comment by grayjay** [comment]
It looks like this issue was fixed by #2741.  Now cabal prints this message with `-v3`:

    [__9] next goal: lens (dependency of snap-0.13.2.8)
    [__9] rejecting: lens-4.13, lens-4.12.3, lens-4.12.2, lens-4.12.1, lens-4.12, lens-4.11.1, lens-4.11, lens-4.10, lens
    -4.9.1, lens-4.9, lens-4.8, lens-4.7.0.1, lens-4.7, lens-4.6.0.1, lens-4.6, lens-4.5, lens-4.4.0.2, lens-4.4.0.1, len
    s-4.4, lens-4.3.3, lens-4.3.2, lens-4.3.1, lens-4.3, lens-4.2 (conflict: snap => lens>=3.7.6 && <3.8 || >=3.7.6 && <4
    .2)
    [__9] trying: lens-4.1.2.1
    [_10] trying: lens-4.1.2.1:!bench

**Comment by kosmikus** [comment]
@grayjay Thanks.
