### ISSUE TITLE
Incorrect error message about globbing

### ISSUE THREAD

**Issue by bos** [haskell/cabal#2030]
In the criterion package, I tried to have a `data-files` section like this:

```
data-files:
  templates/js/jquery-*.min.js
```

When I try to run `cabal`, I get this error:

```
cabal: invalid file glob 'templates/js/jquery-*.min.js'. Wildcards '*' are
only allowed in place of the file name, not in the directory name or file
extension. If a wildcard is used it must be with an file extension.
```

The actual name of the file I'm trying to include is as follows:

```
templates/js/jquery-1.6.4.min.js
```

It looks like `cabal` is misidentifying where the "`*`" is showing up in the pattern here.

**Comment by quasicomputational** [comment]
The error message has been improved.
