### ISSUE TITLE
Run test suites without building?

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2034]
When running Stackage builds, I need to run `cabal test` on a large number of packages. The way I do this is:

* `cabal unpack` the package.
* `cabal configure --enable-tests`
* `cabal build`
* `cabal test`

However, some of the test suites use doctest, and need to know about the special GHC package database created by the Stackage build, so I set GHC_PACKAGE_PATH to include that directory. Normally, this works fine, However, I'll occasionally get a test failure saying:

```
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
```

Which seems to imply that `cabal test` is trying to build the code, even though it's already been built. I can think of a couple solutions to this:

* Provide a command line option to `cabal test` to say "never try to build the test suite." I could see that as more generally useful.
* Provide a command line option to `cabal test` to allow setting environment variables that the child process only will see. Likewise, this may be more generally useful.

**Comment by ezyang** [comment]
I'm going to close this, because there's a good way to set the env var, and another way to run tests WITHOUT rebuilding is to do `cabal act-as-setup -- test` which will bypass to the Setup script, which never rebuilds.
