### ISSUE TITLE
cabal test sucks

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2058]
How does it suck? Let me count the ways:

1. It always try to compile the test executable; there should be an option to interpret (maybe even by default), since it's really annoying having to wait several seconds for what should be an instantaneous test run.
2. It doesn't stream output, even when `--show-details=always`. It always waits until the test executable is done running before printing the output.
3. It's not obvious from the help text how to build the test suite, without actually running it (`cabal build test-name`)
4. It's really hard to tell what the options for the underlying test executables are: usually you have to build it yourself, and then run the executable manually with `--help`. The help text doesn't give any advice on how to do this.
5. `--test-option` is really nonsense when there are multiple test suites, since you really wanted to feed separate options to each test suite.
6. cabal test passes hidden information to the underlying executables, making it hard to run the tests in isolation.  This is best seen by running the cabal-install test suite itself, where if you run 'cabal test package-tests', the locally built cabal-install executable is picked up, but if you run the package-tests executable manually, it picks up whatever cabal is in your PATH. This is unobvious even with `-v`, which reports that Cabal is just running the relevant command

**Comment by ttuegel** [comment]
We now have separate issues for the problems enumerated in this ticket, so I will close this one.
