### ISSUE TITLE
Cabal.Distribution.PackageDescription.Check should be factored per component

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2065]
Right now `Cabal.Distribution.PackageDescription.Check` operates on a sort of ad hoc basis, calling `allBuildInfo` to implement various checks. This means that there are few cases where we completely forget to validate fields at all, especially build-depends in stanzas. Instead, we should have a function which validates a BuildInfo, and call it on each of the build-infos.

**Comment by ffaf1** [comment]
This will be fixed when #8427 is merged.
