### ISSUE TITLE
PackageDescription.buildDepends should be nuked

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2066]
It is a vestige of backwards-compatibility and all build-depends should be put in components.

**Comment by dylex** [comment]
Just for clarification, in the current documentation there is discussion about removing the `customFieldsPD` field that points to this issue, but mainly seems to be discussing the `buildDepends` field.  Is this comment just misplaced, or will this change affect `customFieldsPD` as well?

**Comment by ezyang** [comment]
That's a doc bug, the Haddock comment is being associated with the wrong field.

**Comment by Ericson2314** [comment]
https://github.com/Ericson2314/cabal/tree/build-depends-cleanup -- maybe breaking changes are good for 2.0? Will elaborate later.
