### ISSUE TITLE
Document `cabal test --show-details=streaming`

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#2069]
Originally reported in #2058, I implemented this feature but didn't document it anywhere! The `--show-details=` documentation should be reworded anyway, it's awkward as is.

**Comment by lspitzner** [comment]
`cabal help test` mentions this (since 9583fdab054038d1d33ad8653c3e7f4e2f6a2e1a), so i guess this is about the user guide?

**Comment by ttuegel** [comment]
Yes, that's right.

**Comment by ezyang** [comment]
It's been fixed in user guide.
