### ISSUE TITLE
Cabal install fails on Freebsd10-amd64

### ISSUE THREAD

**Issue by maxphilippov** [haskell/cabal#2086]
Ok, long story short:
I tried 
http://www.haskell.org/cabal/release/cabal-install-1.20.0.3/cabal-install-1.20.0.3.tar.gz

.bootstrap fails on access to /dev/sa0 like someone forgot to pass -f to tar.
I'm not a UNIX guru that's why I just changed this line

``` shell
${GZIP} -d < "${PKG}-${VER}.tar.gz" | ${TAR} -x
```

to

``` shell
${TAR} -zxf "${PKG}-${VER}.tar.gz"
```

I saw it's fixed in current version, so let's just pass by.

Now it did compile, however after compilation I got stuck with this:

``` shell
Linking Setup ...
Configuring Cabal-1.20.0.0...
Setup: Cannot find the program 'ld'. User-specified path
'/usr/bin/ld""--eh-frame-hdr""-dynamic-linker""/libexec/ld' does not refer to
an executable and the program is not on the system path.

Error during cabal-install bootstrap:
Configuring the Cabal package failed.
```

When I tried current version from github I got 404 trying to download 1.21 from hackage which is not there. After manually changing URL I got stuck with the same error, except I tried version 1.20.0.3.

`````` shell
$ uname -a
FreeBSD samuel 10.0-RELEASE FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64```
``````

**Comment by ulysses4ever** [comment]
This is an 8-years old bug report about FreeBSD support. I’m not qualified to make strong statements, but… There seems to be a (relatively) [well-maintained cabal-install port](https://www.freshports.org/devel/hs-cabal-install/). If we had a volunteer who could investigate the current situation with building from source, that would be nice. But until then, maybe we should close?

**Comment by Mikolaj** [comment]
Indeed. And we have a FreeBSD CI build at https://gitlab.haskell.org/haskell/cabal/-/pipelines, which BTW is failing ATM, so that would be a more up to date problem with which we'd appreciate any help. Closing.
