### ISSUE TITLE
Insufficient explanation about the failure

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#2097]
Usually, `cabal-install` is quite good at telling me why a certain installation fails. But now I get this output:

```
Reading available packages...
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: vty-5.2.1 (user goal)
next goal: yi (user goal)
rejecting: yi-0.8.2, 0.8.1, 0.8.0, 0.7.2 (global constraint requires
(==0.7.1))
trying: yi-0.7.1
Dependency tree exhaustively searched.
```

The issue seems to be related to flag assignment; `yi`’s dependency on `vty` is flag-dependent.

**Comment by ttuegel** [comment]
@nomeata Do the recent improvements to the solver's messages resolve this issue for you?

**Comment by grayjay** [comment]
It looks like this issue was fixed:

    Reading available packages...
    Warning: The package list for 'debian' is 513 days old.
    Run 'cabal update' to get the latest list of available packages.
    Choosing modular solver.
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: vty-5.2.1 (user goal)
    next goal: yi (user goal)
    rejecting: yi-0.8.2, yi-0.8.1, yi-0.8.0, yi-0.7.2 (constraint from command
    line flag requires (==0.7.1))
    trying: yi-0.7.1
    trying: yi-0.7.1:-ghcapi
    rejecting: yi-0.7.1:-pango (constraint from command line flag requires
    opposite flag selection)
    trying: yi-0.7.1:+pango
    trying: yi-0.7.1:-profiling
    trying: yi-0.7.1:-scion
    trying: yi-0.7.1:+testing
    rejecting: yi-0.7.1:+vty (conflict: vty==5.2.1, yi-0.7.1:vty => vty>=4.7.0.0
    && <5)
    rejecting: yi-0.7.1:-vty (constraint from command line flag requires opposite
    flag selection)
    Dependency tree exhaustively searched.
