### ISSUE TITLE
Latest cabal-install bootstrap.sh still fails on OS X building Cabal documentation

### ISSUE THREAD

**Issue by fmaste** [haskell/cabal#2102]
The error msg is:
```
Error during cabal-install bootstrap:
Documenting the Cabal package failed.
```

I know this was fixed in #1740 but when using the latest release found here (Cabal-v1.20.0.2.tar.gz) it still happens

I fix it by changing the Cabal's dependency on bootstrap.sh from 1.20.0.0 to 1.20.0.2

**Comment by 23Skidoo** [comment]
This should be fixed in recent versions. A workaround is to use `--no-doc`.
