### ISSUE TITLE
`cabal build && cabal install` in a sandbox compiles the package twice

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2106]
When in a sandbox, running `cabal install` without arguments will use the `dist/dist-$HASH` directory for storing intermediate files. However, if you previously ran `cabal build`, it used `dist`. This leads to unnecessary recompilation; `dist/dist-$HASH` should be used only for add-source dependencies.

**Comment by phadej** [comment]
sandbox functionality is removed.
