### ISSUE TITLE
getDataDir in Paths_pkgname module ignores data-dir in .cabal

### ISSUE THREAD

**Issue by fujimura** [haskell/cabal#2113]
`Paths_pkgname` seems to be ignoring `data-dir` which is declared in pkgname.cabal file.
Is this intentional?

For example, with a my library which has `data-dir:  templates`, `getDataDir` behave as following:

```
λ import qualified Paths_hi 
λ Paths_hi.getDataDir 
"/Users/fujimura/.ghq/github.com/fujimura/hi/.cabal-sandbox/share/x86_64-osx-ghc-7.8.2/hi-0.0.8.2"
```

but I expected it returns path of `templates` directory like this:

``` 
"/Users/fujimura/.ghq/github.com/fujimura/hi/.cabal-sandbox/share/x86_64-osx-ghc-7.8.2/hi-0.0.8.2/templates"
```

I made a failing test case but not yet able to fix the actual code.
https://github.com/fujimura/cabal/commit/4c61ac845290dca3d8bf70d7dd9382482b546084

**Comment by ttuegel** [comment]
This is working as intended. The `data-dir` field simply tells Cabal where to look for data files when installing a package. The directories listed under `data-dir` become the root of installed data tree.
