### ISSUE TITLE
Cabal install in a sandbox with an added source uses that project's Setup.hs for other builds

### ISSUE THREAD

**Issue by thsutton** [haskell/cabal#2120]
Working in a sandbox I've needed to checkout an upstream dependency to apply a patch. This dependency has a Custom build with a Setup.hs that does unusual things and this `Setup.hs` gets run when installing subsequence packages.

My steps go something like this:

```
cd $MY_PROJECT
cabal sandbox init
git clone git@github.com:upstream/depenency-with-custom-build.git
git clone git@github.com:upstream/project.git
# Build the project with a custom Setup.hs
cabal sandbox add-source depenency-with-custom-build
cabal install depenency-with-custom-build/
# Build the project with a normal Setup.hs
cabal sandbox add-source project
cabal install project/
cabal install --dependencies-only
```

But the second `cabal install` fails, producing an error message that must come from the custom `Setup.hs` in `depenency-with-custom-build/`.

Alas most of the code is private, but I could probably knock up a reproduction if required.

**Comment by phadej** [comment]
sandbox functionality is removed.
