### ISSUE TITLE
Cabal bootstrap doesn't use dependency solver to guarantee consistent set of dependencies

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2124]
The command that the bootstrap uses to build Setup.hs is:

```
/usr/bin/ghc --make -odir /srv/code/cabal/Cabal/dist/dist-sandbox-e9d11fda/setup -hidir /srv/code/cabal/Cabal/dist/dist-sandbox-e9d11fda/setup -i -i/srv/code/cabal/Cabal -package-db /srv/code/cabal/.cabal-sandbox/x86_64-linux-ghc-7.6.3-packages.conf.d /srv/code/cabal/Cabal/dist/dist-sandbox-e9d11fda/setup/setup.hs -o /srv/code/cabal/Cabal/dist/dist-sandbox-e9d11fda/setup/setup -threaded -v
```

Notice this does not hide the global package databases. Thus, if GHC makes an unlucky selection from the user database, the bootstrap will fail, EVEN if a sandbox was being used.

**Comment by 23Skidoo** [comment]
This is a `wontfix` I think? The bootstrap script is only guaranteed to work on a fresh GHC install (and we are now testing that it does).

**Comment by ezyang** [comment]
Yeah, ok.
