### ISSUE TITLE
outdated subcommand like as cab's

### ISSUE THREAD

**Issue by cutsea110** [haskell/cabal#2139]
I think `cab outdated` command is very usefull.
Wouldn't you support this feature?

**Comment by 23Skidoo** [comment]
Scrive is willing to pay me to work on this. Our current plan (UI is still subject to bikeshedding) is to either add a `cabal outdated` command or add a warning about outdated dependencies to `cabal configure`, `build` and possibly `check` plus a setting to `~/.cabal/config` to allow disabling said warning (probably a more general `warning-level` setting).

Additionally, there will be a setting for restricting the outdated deps warning to particular version ranges (e.g. "ignore new releases in the foo-0.7 series, but warn if foo-0.6.2 comes out and our dependency on foo is pinned to 0.6.1").

The most important use case for us is to make it easier to update freeze files once new dependencies come out. It should be also possible to automate this check (meaning it should be easy to make it fail CI). This is probably easiest to implement by adding a flag for treating Cabal warnings as errors to `cabal check` or `cabal build`.

One possible complication is that there may be some dependencies that are mentioned in the freeze file, but not in the `.cabal` file.

**Comment by phadej** [comment]
To clarify, one may want to:
- check that constraints in `.cabal` allow all the newest dependencies (`packdeps` does that)
- check that freeze file has a same plan as solver would give it using current constraints in `.cabal` / `.project`

It's not clear which you'd need in Scrive?

---

About `packdeps`: it has very simple approach: `fold` the `BuildInfo`s and for each dependency, check that newest version is accepted by the version constraint. It's used to work around conditionals:
```
if flag(foo2)
  build-depends: foo >= 2
else
  build-depends: foo < 2
```

Yet, if we are in the `cabal-install`, i.e. have access to the solver, better (or complementory?) approach would be to solve the plan, and check that each version there is the newest. This would highlight that
even the bound is relaxed, there isn't valid install plan which could use the latest versions of libs.

Trivially that can be implemented as generating constraints file with only the newest versions of packages, and running solver. In that case solver will hopefully tell why some dependencies aren't allowed.

**Comment by 23Skidoo** [comment]
We mainly want this for updating the freeze file, but it feels natural to add support for the `build-depends` case at the same time as well.
