### ISSUE TITLE
`cabal repl` shouldn't load anything until instructed to do so

### ISSUE THREAD

**Issue by bitemyapp** [haskell/cabal#2144]
Much of the point of a REPL is to work on broken / partly working / incomplete code. Having `cabal repl` exit with an error because my code doesn't compile misses the point.

defer type error isn't sufficient. Forcing me to use `undefined` so I can work on something in-progress in an interface designed for incremental development is absurd.

**Comment by ttuegel** [comment]
Is this still a problem?

**Comment by bitemyapp** [comment]
@ttuegel I think it's fixed in 1.22, closing.
