### ISSUE TITLE
ExitFailure 1

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#2145]
I just tried

`cabal install scotty AesonBson>=0.2.2 -j8 --disable-library-profiling --disable-documentation`

It runs for `64.93s user 3.81s system 188% cpu 36.401 total` and then dies with:

```
cabal: Error: some packages failed to install:
AesonBson-0.2.1 failed during the building phase. The exception was:
ExitFailure 1
```

Could we have more details?

**Comment by ttuegel** [comment]
Was anyone able to reproduce this?

**Comment by nh2** [comment]
> Maybe it's due to shell interpreting '>' as output redirection?

Good mercy, that's it :/ Sorry for the noise.
