### ISSUE TITLE
Reload packages

### ISSUE THREAD

**Issue by kgadek** [haskell/cabal#2149]
My use-case: I'm working on multi-cabal project. Usually I load packages I need (`:m +foo bar`) and work on particular file (`:l quux.hs`). Yet sometimes I need to change something in a package, let's say `foo`. So in second terminal I do that and `cabal install`.

The pitty: I need to restart my ghci and load all the packages and the file again. In my case that's about 20 packages to load. I use copy-paste extensively to do that, but I believe it could be automated in a nice way.

The proposal is to add `:reloadpkg` that would:
1. revert everything to clean state,
2. load all packages that used loaded previously,
3. load the file(s) that user loaded previously.

**Comment by ttuegel** [comment]
This is a GHCi feature request. Please report it [there](https://ghc.haskell.org/trac/ghc/wiki/ReportABug).

**Comment by kgadek** [comment]
Looking from time perspective, I have no idea why I posted it here…
