### ISSUE TITLE
Build doesn't fail on failure of add-source'd dependency.

### ISSUE THREAD

**Issue by sykora** [haskell/cabal#2153]
When (re)-building a package in a sandbox that has a modified add-source'd dependency, the build doesn't stop if that dependency failed to build; instead continuing to build against the previous version of the dependency already installed in the sandbox.

While this is technically a feasible behaviour, it can have some unintended consequences in terms of how users interpret cabal's output. It's also unclear if this is a feature or a bug.

In either case, there are two immediate implications:
1. While the build log does record the build failure of the dependency, it's slightly misleading since the final message can indicate a build success.
2.  The same is true of cabal's exit code, which also indicates success even if there was a dependency build failure. This doesn't work well with tools which analyze exit codes, such as emacs' compilation-mode.

These reasons suggest to me that a cabal build should fail when an automatically pulled add-source'd dependency fails to build.

At the very least, can we clarify if this behaviour is intended?

**Comment by phadej** [comment]
sandbox functionality is removed.
