### ISSUE TITLE
cabal sandbox delete-source gives no indication of whether it did anything

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#2155]
`Cabal sandbox delete-source` should fail if it is given a non-existant source. At the moment it simply pretends all is well,
```
$ cabal sandbox delete-source this-is-not-a-source
Note: 'sandbox delete-source' only unregisters the source dependency, but does
not remove the package from the sandbox package DB.

Use 'sandbox hc-pkg -- unregister' to do that.
$ echo $?
0
```

**Comment by dredozubov** [comment]
I stumbled upon it a few times. Typo will result in the same message and 0 exit code. I guess i'll give it a look today.

**Comment by martinvlk** [comment]
Hi, I want to take this one for fixing, got a rough fix ready locally - Denis, do you mind?

**Comment by dredozubov** [comment]
@martinvlk Please do, i completely forgot about this issue! Sorry.
