### ISSUE TITLE
Cabal build and cabal test should install their own dependencies

### ISSUE THREAD

**Issue by bitemyapp** [haskell/cabal#2176]
`cabal install --dependencies-only` and `cabal install --dependencies-only --enable-tests`

Users don't know or care about a (stateful) plan maintained via configure or otherwise. They have declarative commands that they want to work the first time.

**Comment by ezyang** [comment]
Closing this as subsumed by nix-local-build, and even *more* subsumed by per-component configure #3662.

There's a ticket for per-component install plan solving #1575, but I don't think that's what's being asked for here.
