### ISSUE TITLE
cabal exec -w --with-compiler (generalization of #1899)

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2177]
It should be possible to have -w flag (see `cabal configure`/`install`) on `cabal exec` command. (and `cabal init`, but that really is not important. `cabal sandbox hc-pkg` is just `cabal exec -- ghc-pkg` (right?), which is my reasoning for calling this "generalization".)

In #1899 the same was discussed for `cabal sandbox hc-pkg`. The suggestion was to use `cabal configure -w ..` followed by other stuff. But:
- `cabal configure` needs an actual package. `cabal exec` should be usable without that.
- The suggested solution does not seem to work on both the currently published `1.20.0.3` and on the repository head.. for both `cabal exec` and `cabal sandbox hc-pkg`. (i have tested multiple times now, but it is easy to make some strange mistake.. but even if i did, i does not affect the other point)
## 

thanks to the contributors for their work

**Comment by adamgundry** [comment]
The suggested solution should be fixed by #2859. Adding a `-w` flag to `cabal exec` and `cabal sandbox hc-pkg` is a good idea, patches welcome.

**Comment by hvr** [comment]
NB: `v2-exec` supports this already

**Comment by gbaz** [comment]
closing on above basis
