### ISSUE TITLE
Sandbox not picking up changes in add-source in custom build

### ISSUE THREAD

**Issue by ersran9** [haskell/cabal#2186]
Sandbox having `build-type: Custom` does not seem to pick up changes in add-source'd directories. This behavior seems to occur only during `cabal build` or `cabal repl`

**Comment by domdere** [comment]
I was experiencing this problem, but it was fine after i upgraded my version of `Cabal` from 1.20.0.0 to 1.20.0.3 (im using 1.22.0.0 now but 1.20.0.3 was the lowest version i have tried, and it didnt exhibit the problem)

**Comment by ersran9** [comment]
You're right - `cabal` 1.20.0.3 version does not seem have this issue. Thanks for the heads up.
