### ISSUE TITLE
prefix errors when configuring add-source'd package

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2191]
i accidentally removed a add-sourced subdirectory. then did

```
> cabal configure
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal
```

which confused me for a moment, as this error is for the subdirectory, not the root (where there is a .cabal file).

reproduction:
1) new dir
2) `cabal sandbox init`
3) `mkdir sub`
4) `touch sub/sub.cabal`
5) `cabal sandbox add-source sub`
6) `rm sub/sub.cabal`
7) `touch main.cabal`
8) `cabal configure`

some indication that the error happened for add-source'd dir would be nice.

**Comment by phadej** [comment]
sandbox functionality is removed.
