### ISSUE TITLE
Identical installed package ID does not ensure interconvertibility of packages

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2199]
Right now, the installed package ID is computed purely from the ABI hash of the `exposed-modules` in the library section of a Cabal file. This means we can assign the same installed package ID to a package, even when details of the package in the installed package database are different in a substantive way. In particular, module reexports are not currently accounted for in the ABI hash.

This could result in variation, even if the package description was not changed at all. In particular, if we reexport a module from a dependency which is otherwise not used by any modules in the package, dependency resolution will set some implementation for this module, and which module is picked will vary depending on dependency resolution.

#1019 is probably another instance of this issue, although I can't tell where the collision in that case came from.

The long term plan for installed package ID is to drop ABI hashes from the equation, and base it off of some large hash of source code, package description, etc. such that the IPID truly uniquely identifies a package (and if the IPID is equal, the ABI is equal too.)

**Comment by ttuegel** [comment]
Do the recent changes to IPIDs resolve this issue?

**Comment by ezyang** [comment]
Sort of. The new Nix hashes SHOULD guarantee a particular package. But we still record an `abi` field that doesn't properly manage reexports (GHC uses this to determine interconvertibility).

**Comment by ezyang** [comment]
Well, the abi issue is a different matter. I'll close this one to keep things simple.
