### ISSUE TITLE
Investigate link failures on Windows caused by using Cygwin instead of MSYS

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2205]
In #2202, a user was trying to build `cabal-install` from the Cygwin shell (using native GHC/`cabal-install`). This caused link failures, which was solved by switching to MSYS2 shell.

Since we now get the `gcc` path from `ghc --info`, this was probably caused by Cygwin somehow tricking the network package's `configure` script into using a wrong version of `gcc`. We should look into whether it's possible to fix this by e.g. invoking `configure` with `CC=/path/to/gcc` or something like it.

**Comment by jasagredo** [comment]
Nowadays, Haskell on Windows relies on the Mingw toolchain and not on Cygwin. I'm closing this ticket as it is about Cygwin, please re-open if you disagree.
