### ISSUE TITLE
CABAL_SANDBOX_CONFIG error handling

### ISSUE THREAD

**Issue by htebalaka** [haskell/cabal#2224]
I was playing around with a script to auto-update the CABAL_SANDBOX_CONFIG to the current sandbox and display the current sandbox in my PS1 variable (if any sandboxes are encountered from the current directory to the root), and encountered what I think is a bug in cabal. If the CABAL_SANDBOX_CONFIG variable is set to an empty string, a lot of commands fail in a very uninformative manner. For instance

$ export CABAL_SANDBOX_CONFIG=''
$ cabal sandbox init
Writing a default package environment file to
cabal: .tmp: does not exist
$ cabal init
cabal: .: interrupted
$ cabal sandbox delete
cabal: The package environment file '' doesn't exist

Mostly my fault since I'm mucking about things, and had assumed the empty string was synonymous with no variable in bash, but I think more informative error messages could be helpful in any case.

**Comment by tonyday567** [comment]
If the CABAL_SANDBOX_CONFIG variable is set to a file that doesn't exist (or an empty string), then a lot of commands fail, and this is independent of sandboxing. eg

$ export CABAL_SANDBOX_CONFIG='./cabal.sandbox.config'
$ cabal update
cabal: The package environment file './cabal.sandbox.config' doesn't exist

**Comment by BardurArantsson** [comment]
I would suggest also adding a check for GHC_PACKAGE_PATH at the same time.

**Comment by BardurArantsson** [comment]
Is this something like what was requested? https://github.com/haskell/cabal/pull/2680

**Comment by edsko** [comment]
Reopening because of https://github.com/haskell/cabal/pull/2680#issuecomment-140360590.

**Comment by phadej** [comment]
sandbox functionality is removed.
