### ISSUE TITLE
Use parallel compilation during ./bootstrap.sh run in parallel, if GHC supports it

### ISSUE THREAD

**Issue by ppetr** [haskell/cabal#2229]
During the bootstrap process a lot of packages are compiled and using parallel compilation would speed up the process considerably.

**Comment by daniel-kun** [comment]
@ppetr I think this can be closed now. When building cabal-install-1.22.6, with ghc-7.10.3, which are both fairly old, it already built packages in parallel.

**Comment by jneira** [comment]
closed as per last comment
