### ISSUE TITLE
Add an include-with-filtering mechanism for config files

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2238]
In #2226 I changed how list fields work in config files to make the behaviour less surprising. This is still not quite satisfactory: ideally we'd want to replace implicit inheritance with an explicit `include` mechanism to make it more obvious what happens. So, for example, instead of implicitly mappending `cabal.config` with `cabal.sandbox.config` and `~/.cabal/config`, we would require the user to write

```
include ~/.cabal/config
include cabal.sandbox.config

[...]
```

in `cabal.config`. There should also be a filtering mechanism to make it possible to override list fields. Example:

```
include ~/.cabal/config hiding (remote-repo)
```

**Comment by gbaz** [comment]
agreed.
