### ISSUE TITLE
"buildable: False" should fail the current configuration

### ISSUE THREAD

**Issue by bos** [haskell/cabal#224]
(Imported from [Trac #231](http://hackage.haskell.org/trac/hackage/ticket/231), reported by @dcoutts on 2008-02-05)

Currently resolving configurations does not take account of the <tt>buildable</tt> field. It should act rather like <tt>build-depends: non-existant</tt>, though with a different error message.

If possible the error message should relate to the guard condition expression (the conjunction if there are several nested guards).

At the moment it is not considered at all and we don't notice that the package cannot be built until the build step, rather than the configure step.

One problem is that it's not clear if <tt>buildable: False</tt> is always fatal. People sometimes do that for test executables that are not supposed to be installed. So what should the behaviour be? The lib or only exe failing to configure must be an error.

**Comment by hvr** [comment]
> Another possibility is to deprecate buildable for this use case and add fail instead which would provide an error message to indicate why a particular configuration is not possible.

I guess `fail` would have a similiar effect to `build-depends: base<0`?

**Comment by Ericson2314** [comment]
Now that #1725 is fixed (with #3039), can we revisit this? I might take a stab at undoing https://github.com/haskell/cabal/commit/04dff517c2905e219274c56eb0f8611ac37ffc0f
