### ISSUE TITLE
Even Cabal Sandbox Idris not installing 

### ISSUE THREAD

**Issue by arey0pushpa** [haskell/cabal#2244]
>
sabbath@sabbath-Studio-XPS-1645:~/idris-install$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
>
sabbath@sabbath-Studio-XPS-1645:~/idris-install$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 

-------------------------------------------------------------------------------------------------------------------

sabbath@sabbath-Studio-XPS-1645:~/idris-install$ cabal sandbox init
Writing a default package environment file to
/home/sabbath/idris-install/cabal.sandbox.config
Using an existing sandbox located at
/home/sabbath/idris-install/.cabal-sandbox

sabbath@sabbath-Studio-XPS-1645:~/idris-install$ cabal install idris
Resolving dependencies...
cabal: Codec.Compression.Zlib: premature end of compressed stream

when This CABAL Hell will stop ?

**Comment by ttuegel** [comment]
We already have several issues about the quality of error messages when encountering file corruption or network unavailability.
