### ISSUE TITLE
Add cabal freeze flag -w --with-compiler

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2245]
Currently freeze neither respects a `configure`d option nor allows setting it.
Actually i found no way to `freeze` with a custom compiler version.

I just noticed this when testing which commands exactly get affected by `configure`; i do not currently need this functionality.

See related issues (asking for -w for other commands): #2177 #2242

**Comment by hvr** [comment]
NB: `v2-freeze` supports this already

**Comment by andreasabel** [comment]
There should be one freeze file per GHC version (like there is a build directory per GHC version in v2-cabal).  Currently there is a single `cabal.project.freeze`.

Otherwise, freeze does not work as expected in a multi-GHC environment, and whether `-w` is supported is then rather irrelevant.

**Comment by fgaz** [comment]
I'll close this since `-w` is implemented in v2-freeze, and allowing one freeze file per GHC version is tracked in #7367
