### ISSUE TITLE
cabal sdist generates invalid package for hackage server

### ISSUE THREAD

**Issue by KasperJanssens** [haskell/cabal#2253]
cabal sdist is normally used to generate a package for hackage server. However when the name of the cabal file and the name of the project aren't the same (e.g. they have a difference in casing) cabal sdist will just create the package but hackage server will never accept it. It would be best for cabal sdist to return a warning or an error for this, makes it a little more clear. Got an open issue at hackage-server for this : haskell/hackage-server#285

**Comment by BardurArantsson** [comment]
AFAICT there isn't really any reasonable way to keep hackage-server in sync with cabal sdist (as it stands). Certainly, a rule could be added for this particular case, but in the end it's hackage-server that determines what it'll accept.

As a parallel example from the Java world: Open Source projects can upload packages to the OSS SonaType repository, but OSS SonaType has a requirement that the packages are signed with OpenPGP signatures and include Javadoc. Other package repositories may have more lax requirements (BinTray, for example). Thus, the build tool doesn't do anything to warn you about any of this unless you use the build tool itself to upload the packages -- in which case the server can tell you exactly what is wrong (if anything).

(Obviously, we only have a single package repository in Haskell-land at the moment, but I think the general point stands.)

Does "cabal upload" do the right thing here? If so, I think this is not-a-bug and should be closed.

**Comment by BardurArantsson** [comment]
In fact, I think a better way to do this is to do what OSS SonaType (OST henceforth) does: When you upload a package to OST it isn't actually released immediately. It gets uploaded to a "staging" area and the server just checks that it satisfies all the prerequisites set by the server (signatures, documentation and whatnot). Once the server is satisfied, then developer can issue another command to the server to move the package from the staging area to the "release". This involves no uploading, just the developer saying to the server "yup, I'm satisfied with how that looks, publish to the world!". Until the move-to-release happens the developer is still free to tweak things and upload new versions as much as they want.

This is very reminiscent of the new "package candidate" stuff in hackage-server, so I'd propose that as an alternate way to go for solving this use case.

**Comment by BardurArantsson** [comment]
(I should add, that if anythings going to be done about this and we care enough, then discussion should probably be summarized and recast into a different issue.)

**Comment by 23Skidoo** [comment]
> In short: Have "cabal upload" (just upload as candidate and perform server-side checks) and "cabal release" (move from 'candidate' to 'released') as separate commands. Validation problem solved forever.

Implemented in #3419.
