### ISSUE TITLE
'freeze' ignores existing constraints

### ISSUE THREAD

**Issue by mietek** [haskell/cabal#2265]
As mentioned in https://github.com/haskell/cabal/pull/1519#issuecomment-25211352:

> I mostly like the idea of refreezing by rerunning `cabal freeze` and having it ignore [`cabal.config`]. But freezing something that is already frozen and having it change seems surprising.

It appears that as currently implemented, `cabal freeze` ignores any constraints set both in the local `cabal.config` file, and in the global `~/.cabal/config` file.  Re-running `cabal freeze` with no packages installed results in a new set of constraints, matching the newest available versions of all dependencies.

`cabal freeze` also does not support the `--constraint=` command-line option, available for `cabal install`.

In order to improve the workflow for upgrading dependencies, I wanted to add two options to [Halcyon](https://halcyon.sh/), `--ignore-constraints` and `--ignore-all-constraints`, corresponding to the `--ignore-frozen` and `--ignore-all-frozen` options proposed in https://github.com/haskell/cabal/pull/1519#issuecomment-25205975. Unfortunately, with no apparent way to specify constraints for `cabal freeze`, I can only support `--ignore-all-constraints`.

Additionally, there is no way to help users who have included partial `cabal.config` files with their applications. If `cabal freeze` did not ignore constraints, this could be detected and the user could be warned.

**Comment by grayjay** [comment]
#2519 describes another use case for running `cabal freeze` with an existing freeze file.

**Comment by grayjay** [comment]
new-build should improve the situation, since new-freeze takes a `--constraint` option and uses the constraints from an existing `cabal.project.freeze` file.  I don't think it supports anything like `--ignore-frozen` or `--ignore-all-frozen`, though.

**Comment by mietek** [comment]
Closing as no longer relevant.
