### ISSUE TITLE
Test all possible version permutations for all dependencies

### ISSUE THREAD

**Issue by alexander-b** [haskell/cabal#2266]
A very powerful and neat feature would be for cabal to try building (and testing) the project with all possible permutations of specified dependencies (respecting bounds) to identify versions that do not work.

An option for testing the possible permutations for a specific set of dependencies would also be useful.

An option for only testing x.y or x (as opposed to x.y.z) would be useful as well.

**Comment by BardurArantsson** [comment]
AFAICT this would require an exponential number of builds and and such would be largely impractical for actual use. As such, I think this is a "wontfix"?
