### ISSUE TITLE
Enhancement: Strip sandboxes thoroughly

### ISSUE THREAD

**Issue by mietek** [haskell/cabal#2274]
As [previously mentioned](https://github.com/haskell/cabal/issues/1622#issuecomment-62076817): Cabal sandboxes could be stripped far more thoroughly than they currently are.

On Linux, [Halcyon](https://halcyon.sh/) runs `strip --strip-unneeded` on every file found in the sandbox.  I have not found any issues with this approach over at least six months of testing.

Limited testing was also performed on OS X, with `strip -u -r` used instead.

The following numbers were obtained on Ubuntu 14.04 LTS, using GHC 7.8.3 and _cabal-install_ 1.20.0.3.

Application | Sandbox size | Stripped size | Savings
------------|--------------|---------------|--------
[_hello-apiary_](https://halcyon.sh/shootout/#hello-apiary)       |  81MB |  70MB | 13%
[_hello-happstack_](https://halcyon.sh/shootout/#hello-happstack) |  65MB |  55MB | 15%
[_hello-mflow_](https://halcyon.sh/shootout/#hello-mflow)         | 151MB | 130MB | 14%
[_hello-miku_](https://halcyon.sh/shootout/#hello-miku)           |  84MB |  73MB | 13%
[_hello-scotty_](https://halcyon.sh/shootout/#hello-scotty)       |  83MB |  71MB | 14%
[_hello-simple_](https://halcyon.sh/shootout/#hello-simple)       | 101MB |  88MB | 13%
[_hello-snap_](https://halcyon.sh/shootout/#hello-snap)           |  75MB |  65MB | 13%
[_hello-spock_](https://halcyon.sh/shootout/#hello-spock)         | 104MB |  88MB | 15%
[_hello-wai_](https://halcyon.sh/shootout/#hello-wai)             |  45MB |  39MB | 13%
[_hello-wheb_](https://halcyon.sh/shootout/#hello-wheb)           | 146MB | 128MB | 12%
[_hello-yesod_](https://halcyon.sh/shootout/#hello-yesod)         | 251MB | 217MB | 13%

**Comment by thomie** [comment]
@mietek I can not reproduce your findings. 

* Maybe it is fixed in recent versions of cabal?
* Did you use any special cabal options?
* Perhaps you are running `strip --strip-unneeded` not only over the cabal sandbox, but also the `dist/` directory, or other files that halycon perhaps generates? Note that Cabal doesn't strip executables at build time, only at install time. This means the `hello-apiary` executable in the `dist/` directory is not stripped, but `.cabal-sandbox/bin/hello-apiary` is. There is 4MB difference on my system.

I installed `hello-apiary` in a cabal sandbox, and compared the size of the sandbox before and after running `strip --strip-unneeded` over it:
```
$ uname -op
x86_64 GNU/Linux

$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2

$ git clone https://github.com/mietek/hello-apiary

$ cd hello-apiary

$ cabal sandbox init

$ cabal install

$ du -hs .cabal-sandbox/
105M	.cabal-sandbox/

$ find .cabal-sandbox/ | xargs strip --strip-unneeded
# Ignore all the 'File not recognized' warnings

$ du -hs .cabal-sandbox/
105M	.cabal-sandbox/

$ cabal sandbox hc-pkg list | xargs echo
/opt/ghc/7.10.2/lib/ghc-7.10.2/package.conf.d: Cabal-1.22.4.0 array-0.5.1.0 base-4.8.1.0 bin-package-db-0.0.0.0 binary-0.7.5.0 rts-1.0 bytestring-0.10.6.0 containers-0.5.6.2 deepseq-1.4.1.1 directory-1.2.2.0 filepath-1.4.0.0 (ghc-7.10.2) ghc-prim-0.4.0.0 haskeline-0.7.2.1 hoopl-3.10.0.2 hpc-0.6.0.2 integer-gmp-1.0.0.0 pretty-1.1.2.0 process-1.2.3.0 template-haskell-2.10.0.0 terminfo-0.4.0.1 time-1.5.0.1 transformers-0.4.2.0 unix-2.7.1.0 xhtml-3000.2.1 /tmp/hello-apiary/.cabal-sandbox/x86_64-linux-ghc-7.10.2-packages.conf.d: aeson-0.8.0.2 aeson-pretty-0.7.2 apiary-1.4.3 appar-0.1.4 attoparsec-0.12.1.6 auto-update-0.1.2.2 blaze-builder-0.4.0.1 blaze-html-0.8.1.0 blaze-markup-0.7.0.2 byteorder-1.0.4 bytestring-builder-0.10.6.0.0 bytestring-read-0.3.1 case-insensitive-1.2.0.4 cmdargs-0.10.13 data-default-class-0.0.1 dlist-0.7.1.1 exceptions-0.8.0.2 hashable-1.2.3.3 hex-0.1.2 http-date-0.0.6.1 http-types-0.8.6 http2-1.0.3 iproute-1.5.0 mime-types-0.1.0.6 monad-control-1.0.0.4 mtl-2.2.1 mwc-random-0.13.3.2 network-2.6.2.1 primitive-0.6 random-1.1 scientific-0.3.3.8 simple-sendfile-0.2.21 stm-2.4.4 streaming-commons-0.1.12.1 stringsearch-0.3.6.6 syb-0.5.1 text-1.2.1.3 transformers-base-0.4.4 transformers-compat-0.4.0.4 types-compat-0.1.1 unix-compat-0.4.1.4 unordered-containers-0.2.5.1 vault-0.3.0.4 vector-0.10.12.3 wai-3.0.3.0 warp-3.1.1 web-routing-0.6.2 word8-0.1.2 zlib-0.5.4.2
```

**Comment by BardurArantsson** [comment]
What is the use case here?

I get that there's a small space savings, but for all situations where you really care about the space taken up (e.g. if you're trying to minimal lxc-containers or the like), you'd probably want a more specialized solution that also strips all the *other* system binaries (and removes package docs, etc. etc.) *anyway*. So what would be gained by adding this feature?

**Comment by mietek** [comment]
@thomie:  If you’d like to reproduce my findings, you could use GHC 7.8.3 or 7.8.4.

```
$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

$ git clone https://github.com/mietek/hello-apiary
$ cd hello-apiary
$ cabal sandbox init
$ cabal install --dependencies-only

$ du -hs .cabal-sandbox
135M	.cabal-sandbox
$ find .cabal-sandbox | xargs strip --strip-unneeded 2>/dev/null
$ du -hs .cabal-sandbox
117M	.cabal-sandbox
```

```
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

$ git clone https://github.com/mietek/hello-apiary
$ cd hello-apiary
$ cabal sandbox init
$ cabal install --dependencies-only

$ du -hs .cabal-sandbox/
135M	.cabal-sandbox/
$ find .cabal-sandbox | xargs strip --strip-unneeded 2>/dev/null
$ du -hs .cabal-sandbox/
117M	.cabal-sandbox/
```

It appears that GHC 7.10.1 and 7.10.2 generate already-stripped files.

```
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1

$ git clone https://github.com/mietek/hello-apiary
$ cd hello-apiary/
$ cabal sandbox init
$ cabal install --dependencies-only

$ du -sh .cabal-sandbox/
114M	.cabal-sandbox/
$ find .cabal-sandbox | xargs strip --strip-unneeded 2>/dev/null
$ du -sh .cabal-sandbox/
114M	.cabal-sandbox/
```

**Comment by thomie** [comment]
So this ticket can be closed.

I looked into the way Cabal does stripping in #2782, and I think all is good now.

**Comment by BardurArantsson** [comment]
Good to hear, closed. :)
