### ISSUE TITLE
Suboptimal parseInstalledPackageInfo performance

### ISSUE THREAD

**Issue by blackgnezdo** [haskell/cabal#2276]
My search for ghc-pkg memory consumption described in https://ghc.haskell.org/trac/ghc/ticket/9885 led me to parseInstalledPackageInfo.  The following simple program will eat up 8G of memory:

> import Distribution.InstalledPackageInfo
> 
> main = print $ length $ show $ parseInstalledPackageInfo x
>    where x = "ld-options: x" ++ concat (take 20000 $ repeat ",\"x\" ")

The memory profile looks something like this:
(953)>>=...(...)
    >>=..\
    >>=.\
    >>=
    many1
    many
    sepBy1
    sepBy
    parseSepList
    parseOptCommaList
    listField
    installedFieldDescrs
    accumFields.setField
    accumFields
    parseFieldsFlat.\
    parseFieldsFlat
    parseInstalledPackageInfo
    parsePackageInfo
    registerPackage
    runit
    main     794023536

**Comment by phadej** [comment]
Fixed in #5017
