### ISSUE TITLE
Windows binary for cabal-1.20.0.4 is not available

### ISSUE THREAD

**Issue by ndmitchell** [haskell/cabal#2279]
I was hoping to find it in https://www.haskell.org/cabal/release/cabal-install-1.20.0.4/, but it's not.

Would be good to have as we rely on it for MinGHC, see https://github.com/snoyberg/minghc/issues/11#issuecomment-67365200

**Comment by 23Skidoo** [comment]
I've uploaded the 1.20.0.6 binary to https://drive.google.com/file/d/0B-gmfQNqT8HtdlRoYVdvQ09MWm8/view?usp=sharing
