### ISSUE TITLE
Language extensions to be registered for Cabal 1.22

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2291]
GHC 7.10 currently has a couple of new language extensions not yet registered in `Cabal`:

The following 4 should go in in any case:

 - `PatternSynonyms`
 - `PartialTypeSignatures`
 - `NamedWildcards`
 - `DeriveAnyClass`

The following one should probably not go in yet:

 - `StaticPointers` (current impl. in GHC 7.10 considered a prototype)

**Comment by tibbe** [comment]
Care to whip up a pull request against master @hvr?
