### ISSUE TITLE
Haddock support broken due to package keys

### ISSUE THREAD

**Issue by luite** [haskell/cabal#2297]
Cabal is still using the old-fashioned `-package-name` flag with haddock, which results in warnings.

Hackage also needs some updates, since it cannot determine the version from packages that are not in a package database (often the one currently being compiled), and panics if package lookup fails.

see https://github.com/haskell/haddock/issues/353

**Comment by bgamari** [comment]
I believe the haddock fix is in. What needs to happen at this point?

**Comment by ezyang** [comment]
We need to pull it into the Haddock submodule in the GHC tree, so we have to put it in `ghc-head`. @Fuuzetsu, can you take a look?

**Comment by Fuuzetsu** [comment]
I'll see if I can't put the changes on ghc-head today.

**Comment by bgamari** [comment]
There is a status update [here](https://github.com/haskell/haddock/issues/361#issuecomment-75822956).

**Comment by bgamari** [comment]
@luite where might one find your partial cabal fix?

**Comment by bgamari** [comment]
@Fuuzetsu am I correct in concluding that any `haddock >= 2.16` should have  `--package-name` and `--package-version`?

**Comment by Fuuzetsu** [comment]
Yes thought that's not officially out. It is the version that will be going with 7.10.

**Comment by bgamari** [comment]
My `haddock-pkgid` [branch](https://github.com/bgamari/cabal/compare/haddock-pkgid) I believe should resolve this. Still waiting on testing.

**Comment by Fuuzetsu** [comment]
Looks nice and simple. 

On related note, I wonder if we could make the `expectJust` error from Cabal into something saner and user-friendly. Perhaps a `Maybe` is in order now that it can fail.

**Comment by ezyang** [comment]
@bgamari I don't think that's right. In particular, the `ghc-head` branch has been marked version 2.16 since Dec 12 (1739375eb23342618a3ac01c46a9e4a48cabf716) but it does not have `--package-name`/`--package-key` support.

**Comment by 23Skidoo** [comment]
Yes, this is causing failures on Travis/GHC 7.10. @bgamari, can you look into it?

**Comment by bgamari** [comment]
@ezyang @23Skidoo I'll have a look tonight.

**Comment by bgamari** [comment]
@Fuuzetsu can you cut a new Haddock release and try to get it in to GHC 7.10 and master?

If so, I can bump the version check which I believe will avoid the trouble that @ezyang describes.

**Comment by Fuuzetsu** [comment]
New release will come out when 7.10 does

**Comment by bgamari** [comment]
@Fuuzetsu so to ensure we are on the same page: we can assume that haddock 2.17 will correctly support package keys and will ship with GHC 7.10? If so I'll update the Cabal check.

**Comment by Fuuzetsu** [comment]
2.16 onwards will, that's what will ship with 7.10

**Comment by ezyang** [comment]
For the version test that's happening here, it would be convenient if you guys did a major version bump for new flags. Otherwise, it will be difficult to test if Haddock supports it.

**Comment by bgamari** [comment]
"Edward Z. Yang" <notifications@github.com> writes:

> For the version test that's happening here, it would be convenient if you guys did a major version bump for new flags. Otherwise, it will be difficult to test if Haddock supports it.
>
I agree; especially for folks working on GHC and related projects it's
not uncommon to install snapshots. These users could face frustrating
errors without a version bump. Given the low cost of a release it seems
appropriate to take the conservative route here and ensure that we can
distinguish between haddock releases with and without these flags.

**Comment by 23Skidoo** [comment]
+1 to what @ezyang and @bgamari said.

**Comment by Fuuzetsu** [comment]
At best I could release 2.16 now with appropriate base constraint and something like 2.16.1 when GHC comes out iff any changes are put in between now and then. Is that satisfactory?

**Comment by bgamari** [comment]
@Fuuzetsu assuming the user is *only* using releases there should be no problem. Unfortunately the world is a messy place and it's not uncommon to find people installing snapshots, especially when trying to bring up a GHC 7.10 environment for testing their packages before the release. On my machine `$HOME/.cabal/bin` occurs before the GHC prefix in `$PATH`. This means that if I install haddock using cabal that binary will be used

**Comment by Fuuzetsu** [comment]
> Unfortunately the world is a messy place and it's not uncommon to find people installing snapshots, especially when trying to bring up a GHC 7.10 environment for testing their packages before the release.

And if you're building 7.10 snapshot then you're getting a Haddock snapshot that works with it, one that presumably has the fix already.

> On my machine $HOME/.cabal/bin occurs before my GHC prefix in $PATH. This means that if I install haddock using cabal the resulting binary will be used whenever haddock is invoked. 

You could merely change your PATH to make the Haddock binary you actually want be picked up earlier. PATH is there for you to change to accomodate for these things…

Point being that if you're going out and installing snapshots of software then you're the special case, not the majority. If I release a version on Hackage now, it may not work for anyone not running the precise 7.10 snapshot (not even the RC!) that me or you happened to be working with at the moment. Understandably I'm reluctant to make a release from against a random GHC commit.

**Comment by 23Skidoo** [comment]
Right now it looks like the 7.10 branch includes the fix, but HEAD for some strange reason doesn't. Compare build logs for 7.10 and HEAD [here](https://travis-ci.org/haskell/cabal).

**Comment by Fuuzetsu** [comment]
HEAD doesn't because the changes need to be cherry-picked onto `ghc-head` Haddock branch and I had issues with getting GHC HEAD to run properly hence could not do it. If you have working HEAD then feel free to cherry-pick the relevant commit onto that branch and to update the Haddock submodule. You should have the commit rights to do so.

**Comment by hvr** [comment]
@bgamari 

> This is why bumping the version number is typically the last thing I do before tagging and making a release. This ensures that at worst a user will get a snapshot with strictly more functionality than he would expect from the version number, never fewer (unless functionality is specifically removed).

OTOH, it makes release management much harder for GHC if the version numbers are bumped at the very last moment before a release, and it makes it very difficult for package maintainers wanting to support GHC snapshots if they can't discriminate non-released versions with new features (or even breaking changes) from officially released versions. 

So for the purpose of GHC's boot libraries it's better to bump early so that even snapshots reflect the PVP contract (relative to released versions), as well as keeping everything in a rightaway-releasable state (and avoiding the upper-bound update waves otherwise occurring last minute which are quite tiresome as you need to wait on upstream maintainers to react, and that sometimes means waiting a few days which blocks your patch-queue).
