### ISSUE TITLE
A way to override cabal.config for sandboxes

### ISSUE THREAD

**Issue by aslatter** [haskell/cabal#2300]
I'd like to turn off haddock-creation for sandboxes (because it's expensive to build and I already have Hackage docs and user-level docs).

My options look like:
1. Turn off documentation in ~/.cabal/config. I don't like this because I want user-level documentation.
2. Turn off documentation in $PROJECT/cabal.config. I don't like this because this will have a side-effect of turning off user-level documentation for this package (I think?). Also I would need to add an entry for /cabal.config to my VCS ignore file, which would preclude using `cabal freeze` and committing the changes to my VCS.
3. Turn off documentation in $PROJECT/cabal.sandbox.config. This file has scary warnings at the top telling me not to edit this file.

None of these options are great.

Options which I would like better could be:
1. A separate config file in ~/.cabal/ which contains defaults on top of ~/.cabal/config, but only when used in a sanbox. This could be take into account when generating $PROJECT/cabal.sandbox.config, or in some other way.
2. A separate config file in $PROJECT/ which only applies to sandboxes but is allowed to be user editable. I'm not sure which should take priority between $PROJECT/cabal.new_thing.config and $PROJECT/cabal.config.

**Comment by phadej** [comment]
sandbox functionality is removed.
