### ISSUE TITLE
Bootstrap failure network-uri <2.6

### ISSUE THREAD

**Issue by k-bx** [haskell/cabal#2305]
Hi!

If you clone this repo https://github.com/k-bx/docker-ghc-7.8 and run `sudo docker build .` you will (probably) see following error upon `./bootstrap.sh` stage:

```
Configuring cabal-install-1.20.0.4...
Setup: At least the following dependencies are missing:
network-uri <2.6

Error during cabal-install bootstrap:
Configuring the cabal-install package failed.
2014/12/26 04:38:40 The command [/bin/sh -c ./bootstrap.sh] returned a non-zero code: 2
```

Please check it out.

**Comment by kaiko** [comment]
1.20.0.6 works.
1.18.0.5 works.
Inital error still arises for 1.18.0.6 and 1.18.0.7 (Setup: At least the following dependencies are missing: network <2.5).

Dockerfile:

    FROM debian:wheezy
    RUN apt-get update && apt-get -y upgrade
    RUN apt-get -y install make curl bzip2 gzip libffi-dev libgmp-dev zlib1g-dev
    
    RUN curl -s http://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.bz2 | tar xj
    RUN curl -s http://hackage.haskell.org/package/cabal-install-1.18.0.7/cabal-install-1.18.0.7.tar.gz | tar xz
    
    RUN cd ghc-* && ./configure && make install
    RUN cd cabal-* && ./bootstrap.sh --global
    RUN cabal update

**Comment by tibbe** [comment]
@kaiko I've release cabal-install-1.18.0.8, hopefully fixing the issue.
