### ISSUE TITLE
Regression: 'update' enforces 'require-sandbox'

### ISSUE THREAD

**Issue by mietek** [haskell/cabal#2309]
Between 1.20.0.3 and 1.20.0.5, `cabal update` started enforcing the `require-sandbox` option, and now can fail with:

```
cabal: 'require-sandbox' is set to True, but no sandbox is present.
```

I think this is too restrictive. Does anyone think otherwise?

**Comment by mhwombat** [comment]
I'm having the same problem with `cabal list` and `cabal info`. I don't think those commands, or `cabal update` should require the sandbox.

**Comment by lspitzner** [comment]
related: #1889

**Comment by mietek** [comment]
[Halcyon](https://halcyon.sh) includes a workaround for this issue.
