### ISSUE TITLE
Improve 'Could not resolve dependencies' message

### ISSUE THREAD

**Issue by gracjan** [haskell/cabal#2316]
So I got this message after trying to bump monad-control:

cabal: Could not resolve dependencies:
trying: conduit-1.2.1/installed-488... (user goal)
trying: conduit-1.2.1/installed-488... (user goal)
next goal: monad-control (user goal)
rejecting: monad-control-0.3.2.2/installed-aae... (global constraint requires
==1.0.0.1)
rejecting: monad-control-1.0.0.1 (conflict: conduit =>
monad-control==0.3.2.2/installed-aae...)
rejecting: monad-control-1.0.0.0, 0.3.3.0, 0.3.2.3, 0.3.2.2, 0.3.2.1, 0.3.2,
0.3.1.4, 0.3.1.3, 0.3.1.2, 0.3.1.1, 0.3.1, 0.3.0.1, 0.3, 0.2.0.3, 0.2.0.2,
0.2.0.1, 0.2, 0.1 (global constraint requires ==1.0.0.1)
Backjump limit reached (change with --max-backjumps).

Note that:
- conduit is an indirect dependency
- conduit is not listed in my .cabal file
- conduit is not listed in my cabal.config file

'Something' is relying on exact version of 'conduit'. How to find out what is that?

**Comment by kosmikus** [comment]
I think we can improve the message, but this isn't a solver issue (or at least only partially so). "conduit" is listed as a "user goal", which means the solver is *called* with "conduit" as a goal. It's *not* an (indirect) dependency. Probably this is due to sandboxing which invokes the solver with additional goals. We should probably change the invocation of the solver when called from a sandbox so that goals that are added via a sandbox are identified as such, because it is wrong and misleading to call them "user goals".

**Comment by gracjan** [comment]
Note:

    cabal sandbox hc-pkg hide conduit

Changes nothing.
Command:

    $ cabal sandbox hc-pkg unregister conduit
    ghc-pkg: unregistering conduit would break the following packages: 
    soap-0.2.2.4 xml-conduit-writer-0.1.1.1 xml-conduit-1.2.3
    conduit-extra-1.1.5 yaml-0.8.9.3 (use --force to override)

And then:

    $ cabal sandbox hc-pkg unregister conduit --force
    cabal: unrecognized 'sandbox' option `--force'

Well, okay:

    $ cabal sandbox hc-pkg unregister conduit -- --force

And that changes a little as then cabal install says:

    rejecting: monad-control-1.0.0.1 (conflict: happstack-server =>
    monad-control==0.3.2.2/installed-aae...)

After a couple of 'unregister this' and 'unregister that' I get:

    cabal: Could not resolve dependencies:
    next goal: conduit-extra (user goal)
    rejecting: conduit-extra-1.1.5/installed-e9e... (package is broken)
    trying: conduit-extra-1.1.6

That probably means that 1.1.5 is not taken into account at all anymore, even if it could be reinstalled. Am I right?

Ok, whatever, lets unregister anything that happens to be broken (as it was depending on old monad-conduit). Lets see:

    cabal sandbox hc-pkg list

This ^ command helpfully marks broken packages in RED. Nice, although I do not know how to grep by RED. Anyway after a couple of mouse-copy-and-paste I have the command:

    cabal sandbox hc-pkg unregister yaml xml-conduit xml-conduit-writer soap -- --force

Sadly ghc-pkg cannot unregister many packages at once. One more try:

    echo yaml xml-conduit xml-conduit-writer soap | xargs -J % -n 1 cabal sandbox hc-pkg unregister % -- --force

And that actually got me somewhere as cabal install --only-dep now tell me that:

    rejecting: happstack-server-7.3.9, 7.3.8, 7.3.7, 7.3.6, 7.3.5, 7.3.4, 7.3.3,
    7.3.2, 7.3.1, 7.3.0, 7.1.7.1, 7.1.7, 7.1.6 (conflict: monad-control==1.0.0.1,
    happstack-server => monad-control>=0.3 && <0.4)
    Dependency tree exhaustively searched.

And that tells me that my set of constraints is really inconsistent.

I'd like to know which packages depend on monad-control. Is there a way to list them? Note that this does not have to be cabal-command-line, it is OK for me to do some Haskell hacking around Cabal (the library).

**Comment by gracjan** [comment]
Note: After all the messing:

    $ cabal install --only-dep --max-backjumps=-1
    Resolving dependencies...

Never ends. Or at least I could not wait longer.

**Comment by mietek** [comment]
I expect you are running into an issue related to https://github.com/snoyberg/conduit/issues/194. You probably want `streaming-commons-0.1.8` and `conduit-extra-1.1.6.2`.

**Comment by gracjan** [comment]
Thanks for the hint. I have a couple of people and a couple of automatic build systems building.Telling then to try out different options depending on what happens to currently be in their sandbox and/or global registry is not an option.

**Comment by bergmark** [comment]
I think this is solved by using `-v2` in cabal-install-1.22.4.0

**Comment by phadej** [comment]
sandbox functionality is removed.

**Comment by gbaz** [comment]
closing as obsolete
