### ISSUE TITLE
Cached sandbox installs

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#2318]
I'd like to suggest and discuss a potential feature:

A `cabal install --cached` that, when run in a sandbox, checks if there's already a package with that version present in `~/.cabal` and just registers it in the `./.cabal-sandbox/*-packages.conf.d/`.

So no downloading and compilation in case the package had already been compiled on this machine.

If a package to be installed with `--cached` is not already installed, it gets compiled and put into `~/.cabal`'s `lib` instead of the sandbox's `lib`.

---

This option would be a tradeoff, giving away some hermeticity for great speed increase if many sandboxes are used (e.g. no more compiling `lens-4.5` 30 times, 5 minutes each).

It would run under the assumption that the environment hasn't changed, which seems reasonable to me as long as it's implemented as an explicitly given flag.

Do you think this is reasonable? What would be potential obstacles?

**Comment by yongqli** [comment]
This sounds like a very good idea. Right now if I make even a small change I risk breaking the sandbox. Since my project has lots of dependencies it takes up to half an hour to rebuild everything.

**Comment by ttuegel** [comment]
This would potentially be addressed by [this GSoC proposal](https://gist.github.com/fugyk/37510958b52589737274).

**Comment by nh2** [comment]
> This would potentially be addressed by this GSoC proposal.

If I understand it right, that proposal is still very different, and mainly concerned with making Cabal Nix-like.

The suggestion in this ticket can achieve higher incrementality of builds, independent of whether we have a Nix-like setup or not (because it works on GHC tracking `.hi` files).

**Comment by ttuegel** [comment]
> The suggestion in this ticket can achieve higher incrementality of builds, independent of whether we have a Nix-like setup or not (because it works on GHC tracking .hi files).

Sorry, I misunderstood this part:

> So no downloading and compilation in case the package had already been compiled on this machine.
> 
> If a package to be installed with --cached is not already installed, it gets compiled and put into ~/.cabal's lib instead of the sandbox's lib.

It sounded to me like you wanted Nix-like caching of built packages, but you're really looking for something ccache-like.

**Comment by phadej** [comment]
sandbox functionality is removed.
