### ISSUE TITLE
Missing changelog entries for some versions of Cabal and cabal-install

### ISSUE THREAD

**Issue by asr** [haskell/cabal#2319]
There are not `changelog` entries for Cabal 1.20.0.2 and 1.20.0.3, and cabal-install 1.20.0.4, 1.20.0.5, 1.20.0.6 and 1.22.0.0.

**Comment by ttuegel** [comment]
We will probably not issue changelogs for past releases, but I am writing a formal issue triage/milestoning procedure based on GHC's to ensure we have an accurate, canonical list of changes in each release.

**Comment by asr** [comment]
Thanks!
