### ISSUE TITLE
Cabal-1.22.0.0 test suite does not compile

### ISSUE THREAD

**Issue by peti** [haskell/cabal#2321]
Preprocessing test suite 'package-tests' for Cabal-1.22.0.0...

    tests/PackageTests.hs:37:8:
        Could not find module ‘PackageTests.ReexportedModules.Check’
        Use -v to see a list of the files searched for.

**Comment by NobbZ** [comment]
So how can we install cabal-install until the next release? I'd like to update but it fails because of this…

**Comment by tibbe** [comment]
Running the cabal test suite isn't necessary to install cabal. Running

```
cabal install Cabal-1.22.0.0
```

should work. If not check if you adding something like `tests: True` or similar to your ~/.cabal/config.
