### ISSUE TITLE
Cabal 1.22.0.0 does not compile with GHC 7.6.3

### ISSUE THREAD

**Issue by peti** [haskell/cabal#2322]
Building `./Setup.hs` fails with the following error:

    Distribution/Simple/Configure.hs:127:22:
        Module `Data.Binary' does not export `decodeOrFail'

A complete build log is at http://hydra.cryp.to/build/301439/nixlog/1/raw.

**Comment by 23Skidoo** [comment]
You need a newer version of `binary`, as specified in `Cabal.cabal`.

**Comment by peti** [comment]
The same issue exists with GHC 7.4.2: http://hydra.cryp.to/build/301520/nixlog/1/raw.
With GHC 7.2.2, the build log is even shorter: http://hydra.cryp.to/build/300831/nixlog/1/raw

**Comment by peti** [comment]
@23Skidoo, the build never gets to interpret the Cabal file if `Setup.hs` doesn't compile.

**Comment by 23Skidoo** [comment]
It should work if you install `Cabal` with `cabal-install`.

**Comment by peti** [comment]
Also, I wonder what the consequences are if I build that library with a newer version of `binary` that doesn't match the core library shipped with the compiler? Won't that get me into trouble when mixing Cabal 1.22.x with other libraries that use the core `binary` library?

**Comment by peti** [comment]
@23Skidoo, yes, I know that I can work around this issue by using an older version of `cabal-install` for bootstrapping. That process is not exactly ideal, no? I'm sure many people still use GHC 7.6.3, and not many of them will not realize what the error message they get means and how they can remedy it. It would be great if `ghc --make Setup && ./Setup configure` would do something useful for a library as fundamental as `Cabal`.

**Comment by 23Skidoo** [comment]
> Also, I wonder what the consequences are if I build that library with a newer version of `binary` that doesn't match the core library shipped with the compiler? Won't that get me into trouble when mixing Cabal 1.22.x with other libraries that use the core `binary` library?

If you use `cabal-install` to manage dependencies it will make sure that the only one version of `binary` is used. Though it shouldn't matter for Cabal.

> yes, I know that I can work around this issue by using an older version of cabal-install for bootstrapping. That process is not exactly ideal, no?

You can also use the `bootstrap.sh` script. I guess we could add a bootstrap script for `Cabal` itself that'd validate the versions of the dependencies.

**Comment by peti** [comment]
@23Skidoo, I'm not sure what you are saying. Do you care about the fact that `ghc --make Setup.hs` won't succeed with pre 7.8.x compilers? Or do you feel that this issue is irrelevant because there are other ways to build the library?

**Comment by tibbe** [comment]
@dcoutts thoughts? Should we try to have Cabal build with the version of binary that shipped with GHC 7.6?

/cc @kolmodin

**Comment by 23Skidoo** [comment]
> Should we try to have Cabal build with the version of binary that shipped with GHC 7.6?

-1 on that. This means adding more `#ifdef` cruft and will likely produce a broken Cabal (due to bugs in old versions of `binary`).

> I'm not sure what you are saying. Do you care about the fact that `ghc --make Setup.hs` won't succeed with pre 7.8.x compilers?

I don't think there's a satisfactory way to make `ghc --make Setup.hs` work, but we could add a bootstrap script similar to `cabal-install/bootstrap.sh` that'd validate that you have the right versions of all dependencies and install them for you if they're missing. You'd use it instead of `ghc --make Setup.hs`.

**Comment by ttuegel** [comment]
The only way we are going to get Cabal to build with `binary < 0.7` is to remove the binary LBI feature. It relies on the "new" generics support. But, the library will be buildable with `GHC >= 7.2`.

**Comment by tibbe** [comment]
@ttuegel I'm guessing that anything that could be derived using Generics could be generated manually (i.e. using boilerplate instances)?

**Comment by ttuegel** [comment]
@tibbe Yes, we could do the instances by hand. There are ~50 instances derived via generics right now. Is that the direction we want to go, given that we're trying to get rid of bootstrap scripts?

**Comment by tibbe** [comment]
@ttuegel Good question. I don't know what to do yet. What's the path we want to give users who want to bootstrap?

**Comment by ttuegel** [comment]
@tibbe What about bringing in the necessary parts of `binary` into the Cabal tree under `Distribution.Compat.Binary` (internal module)? I think we would just need the generic instance from the library. `binary` is a small library anyway, and compatibly licensed. For GHC >= 7.8, it would just re-export the relevant bits of the actual `binary` library.

**Comment by tibbe** [comment]
Should be fixed on 1.22 branch by the commits from #2332 which I cherry-picked onto the 1.22 branch.
