### ISSUE TITLE
Handling / pretty printing of GenericPackageDescription changed in Cabal 1.22

### ISSUE THREAD

**Issue by dan-t** [haskell/cabal#2323]
Now parsing a cabal file with `parsePackageDescription` and pretty
printing it with `showGenericPackageDescription` will result into a cabal
file where every section contains the 'build-depends' field twice.

Previously the dependencies have been resolved into `CondNode.condTreeConstraints`
and the field `BuildInfo.targetBuildDepends` has been emptied.

Now it seems that both - `CondNode.condTreeConstraints` and `BuildInfo.targetBuildDepends` -
contain the dependencies and therefore they're output twice.

The resolving into `CondNode.condTreeConstraints` always seemed a bit like a hack to me,
because there's already the distinction between `GenericPackageDescription` and `PackageDescription`,
and `PackageDescription` already representing the resolved state, so I'm wondering if it wouldn't
be best to let `CondNode.condTreeConstraints` just go, or as a first step, not using it anymore.

**Comment by tibbe** [comment]
Do you know which commit introduced the regression?

**Comment by dan-t** [comment]
On Mon, Jan 05, 2015 at 08:38:16AM -0800, Johan Tibell wrote:
> Do you know which commit introduced the regression?

No, I hoped that someone on the mailing list might have an idea.

**Comment by dan-t** [comment]
It seems to be 31719ae9215024159ad9de4b74ac10c8e7a87d42.

**Comment by ezyang** [comment]
One tentative proposal is to make `ppConTree` stop calling `ppDeps`. But I'm a bit worried: do we ever merge nodes of the CondTree over: that is to say, could the BuildInfo information be out-of-date?

Also, I don't see anywhere in the fingered commit where I start preserving data that previously had been dropped. @dan-t, are you sure that's the commit/

**Comment by dan-t** [comment]
This seems to fix it:

    diff --git a/Cabal/Distribution/PackageDescription/Parse.hs b/Cabal/Distribution/PackageDescription/Parse.hs
    index 0e7b0bf..c5667a5 100644
    --- a/Cabal/Distribution/PackageDescription/Parse.hs
    +++ b/Cabal/Distribution/PackageDescription/Parse.hs
    @@ -1254,6 +1254,5 @@ buildDependsWithRenaming pkg =
     
     setBuildDependsWithRenaming :: [DependencyWithRenaming] -> BuildInfo -> BuildInfo
     setBuildDependsWithRenaming deps pkg = pkg {
    -    targetBuildDepends = map dependency deps,
         targetBuildRenaming = Map.fromList (map (\(DependencyWithRenaming (Dependency n _) rns) -> (n, rns)) deps)
       }

`targetBuildDepends` seems to be empty before calling `setBuildDependsWithRenaming`.

Would this fix break other things?

**Comment by ezyang** [comment]
Ugh, I'm having traumatic flash backs about this piece of code. Your fix will work as long as the CondTree code which fills in BuildInfo later always produces the same list of dependencies in targetBuildDepends. Which, if it does, one must wonder: then why is it nobbling about with this at all? Or if it never gets filled in, why do we have a targetBuildDepends to begin with?

I don't have the patience today to figure this out, but some careful code reading is in order.

**Comment by dan-t** [comment]
On Tue, Jan 06, 2015 at 04:05:50PM -0800, Edward Z. Yang wrote:
> Which, if it does, one must wonder: then why is it nobbling about with
> this at all? Or if it never gets filled in, why do we have a targetBuildDepends to begin with?

I think the major issue here is, that `GenericPackageDescription` is on
one side used as the representation of the parsed cabal file, in which
case `targetBuildDepends` represents the `build-depends` field of a
cabal file section, and on the other side its used as some kind of
intermediate representation during the resolving of dependencies/constraints,
in which case `condTreeConstraints` contains this information.

The - before Cabal 1.22 - emptiness of `targetBuildDepends` was a big
irritation for me when writing my tools operating on the cabal file
and I consider it as the wrong thing, so having valid data inside
of `targetBuildDepends` makes a lot more sense then the previous behaviour.

Most likely it's no option to remove `condTreeConstraints` now, so one
workaround for the current issue might be to just to leave it out for
the pretty printing.

**Comment by tibbe** [comment]
So what do we do about this? I have the bug assigned to the Cabal-1.22.0.1 milestone, but I don't know how to fix it. Any volunteers?

**Comment by dan-t** [comment]
On Mon, Jan 12, 2015 at 11:51:30PM -0800, Johan Tibell wrote:
> So what do we do about this? I have the bug assigned to the Cabal-1.22.0.1
> milestone, but I don't know how to fix it. Any volunteers?

I think that removing 'condTreeConstraints' from the pretty printing
might be the best solution, because it's not part of the cabal file,
so why should it be printed?

But I don't know if any other parts in cabal depend on the pretty printing of
'condTreeConstraints'.

If nobody complains about the removal, then I can do it.

**Comment by dcoutts** [comment]
I'm happy with removing it from the pretty printing.

In the new data structure that I'll eventually commit, I only have the constraints as a field in the body and don't lift them out specially as we do with the current data structure, so this issue would disappear entirely.

**Comment by 23Skidoo** [comment]
Fixed by #2364.

**Comment by dan-t** [comment]
Will the version containing this fix be 1.22.0.1?

That would be a bit unfortunate, because the cabal macros like MIN_VERSION_Cabal are only operating on the first three numbers and I most likely need some CPPing to make my tools backward compatible.

**Comment by 23Skidoo** [comment]
@tibbe, can we call the next release `1.22.1`?

**Comment by tibbe** [comment]
@23Skidoo yes. I've bumped the version number on the branch.
