### ISSUE TITLE
cabal command to remove unused packages

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#2324]
Bundler has a subcommand 'clean' which removes all unused gems. This is useful when one upgrades dependencies and wants to get rid of the packages which are afterwards unused.

Building Haskell projects on travis (https://travis-ci.org/) is time consuming because all the dependencies have to be installed afresh for each build. Cabal sandboxes don't help because nothing is preserved between builds. A while ago the travis team added the ability to cache files (1, 2). Travis has builtin support for caching bundler and cocoapod dependencies. Having an equally easy way to enable haskell cache would be useful. However one precondition (according to the travis developers) is that there needs to be an automatic way to clean the cache.

1: http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/
2: http://docs.travis-ci.com/user/caching/

**Comment by ttuegel** [comment]
This would be addressed by [this GSoC proposal](https://gist.github.com/fugyk/37510958b52589737274).

**Comment by wereHamster** [comment]
Was the GSoC proposal accepted?

**Comment by 23Skidoo** [comment]
Yes, it was.

**Comment by peti** [comment]
The link from https://github.com/haskell/cabal/issues/2324#issuecomment-96195552 points nowhere, unfortunately.

**Comment by hvr** [comment]
fwiw, @lspitzner's https://github.com/lspitzner/pkgdbgc tool is currently exploring the design space

**Comment by grayjay** [comment]
Similar issue for new-build: #3333

**Comment by jneira** [comment]
i would close this in favour of #3333, v1 commands are deprecated and there is lot of work to be done in v2
