### ISSUE TITLE
regression: `local-repo` no longer works in sandboxes

### ISSUE THREAD

**Issue by twittner** [haskell/cabal#2326]
Commit 5fcf3d994e5c5a0f101ac04e092a8beedadcdc8d changed the semantics of `local-repo` and other settings to "override" instead of "append" which makes it impossible to specify additional local repositories when using sandboxes with cabal-install >= 1.20.0.4.
### Steps to reproduce
1. Create a fresh sandbox somewhere.
2. Add a `cabal.config` file to the sandbox and specify as `local-repo` the one from `cabal.sandbox.config`.
3. Add another `local-repo` to `cabal.config` which points to a local repository with some private packages.
4. Install a private package.
### Result

```
cabal: There is no package named 'my-private-package'.
You may need to run 'cabal update' to get the latest list of available
packages.
```
### Workaround

It is possible to put the `local-repo` settings directly into `cabal.sandbox.config` and things work, however:

```
-- THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
-- Please create a 'cabal.config' file in the same directory
```
### Expected behaviour

From my point of view it would be preferable to revert back to the old behaviour for `local-repo` as it was not even necessary to create a `cabal.config` file inside of a sandbox. You could just specify a private local repository in `~/.cabal/config` and every sandbox would be able to pick up packages from there.

If this is not acceptable then I would at least expect the `cabal.config` file to override the settings in `cabal.sandbox.config` and not vice versa.

**Comment by 23Skidoo** [comment]
I'd really prefer to not special-case `remote-repo`. The fact that 

```
local-repo: /path/to/.cabal-sandbox/packages/
local-repo: /path/to/local/repo
```

doesn't work looks like a bug; what if you try

```
local-repo: /path/to/local/repo
local-repo: /path/to/.cabal-sandbox/packages/
```

instead?

Related: #2238.

**Comment by twittner** [comment]
The order of `local-rep` does not matter. The cause of this bug is the fact that `cabal.sandbox.config` settings replace the ones on `cabal.config`. This is true also for other settings (e.g. `build-summary`). I am not too well acquainted with cabal's code base but I was surprised by the usage of `overrideSandboxSettings`, i.e. I would have expected:

```diff
diff --git a/cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs b/cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
index 56cb865..93c0f3c 100644
--- a/cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
+++ b/cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
@@ -349,11 +349,10 @@ tryLoadSandboxPackageEnvironmentFile verbosity pkgEnvFile configFileFlag = do
   -- Layer the package environment settings over settings from ~/.cabal/config.
   cabalConfig <- fmap unsetSymlinkBinDir $
                  loadConfig verbosity configFileFlag NoFlag
-  return (sandboxDir,
-          updateInstallDirs $
-          (base `mappend` (toPkgEnv cabalConfig) `mappend`
-           common `mappend` inherited `mappend` user)
-          `overrideSandboxSettings` pkgEnv)
+
+  let merged = base `mappend` (toPkgEnv cabalConfig) `mappend` common `mappend` inherited
+
+  return (sandboxDir, updateInstallDirs $ merged `overrideSandboxSettings` pkgEnv `mappend` user)
     where
       toPkgEnv config = mempty { pkgEnvSavedConfig = config }
```
But I may be barking up the wrong tree.

All that said I prefer the append semantics for `local-repo` as well as for `remote-repo`, but I understand that others do not. Therefore I look forward to https://github.com/haskell/cabal/issues/2238 being implemented.

**Comment by twittner** [comment]
> All that said I prefer the append semantics for local-repo as well as for remote-repo

To expand on this a bit--imagine a team of developers working on a shared code-base. Every developer clones the repository to a different location on his workstation. They already use a `cabal.config` file to freeze dependencies, i.e. this file is part of revision control. With the new semantics every developer has to make local changes to this file which conflicts with those of his collaborators. What do you do?

**Comment by edsko** [comment]
This actually happens with a single `local-repo` too. If my cabal `config` just records a single `local-repo`

```
local-repo: /path/to/some/repo
```

and then in a fresh directory call `cabal sandbox init ; cabal install some-package` then you get that `some-package` does not exist error (without touching the generated sandbox config at all).

**Comment by phadej** [comment]
sandbox functionality is removed.
