### ISSUE TITLE
Debugging doesn't work anymore

### ISSUE THREAD

**Issue by DekwoKybon** [haskell/cabal#2328]
After updating cabal all kind of errors occurred. I had to follow these instructions (http://stackoverflow.com/questions/23432510/cabal-install-1-20-0-0-fails-to-install-on-os-x) to fix that error. 

I don't know if it is somehow related to the fact that debugging doesn't work anymore. I get the exact same error as reported here:
http://stackoverflow.com/questions/27204678/how-to-make-the-debug-function-of-haskell-idea-plugin-work-properly
Mind the typo in the error message: "occured" instead of "occurred". Maybe that can give a clue somehow...

Currently I'm using the latest build 0.4.23.beta. 
Note: Debugging used to work with 0.4.21.beta but now that's also not working anymore.

Best regards,
Wouter
Ubuntu 14.10
Intellij 14

**Comment by ttuegel** [comment]
Please take this up with https://github.com/Atsky/haskell-idea-plugin.
