### ISSUE TITLE
cabal update APPCRASH Windows Server 2008 R2

### ISSUE THREAD

**Issue by bhillis** [haskell/cabal#2331]
On a fresh installation of Windows Server 2008 R2, when with minghc-7.8.3 or minghc-7.8.4-x86_64 installed and when using cabal-1.22.0.0-i386-unknown-mingw32 directly downloaded from https://www.haskell.org/cabal/release/cabal-install-latest/, running cabal update starts the process but on reaching

    Downloading the latest package list from hackage.haskell.org

the following appears

![image](https://cloud.githubusercontent.com/assets/10448814/5662197/25f06e3c-978a-11e4-9d32-2c83b676a134.png)

Problem signature:
Problem Event Name: APPCRASH
Application Name: cabal.exe
Application Version: 0.0.0.0
Application Timestamp: 53d6efb8
Fault Module Name: KERNELBASE.dll
Fault Module Version: 6.1.7601.17514
Fault Module Timestamp: 4ce7bafa
Exception Code: 40010006
Exception Offset: 0000b727
OS Version: 6.1.7601.2.1.0.272.7
Locale ID: 1033
Additional Information 1: 53cb
Additional Information 2: 53cb7be0fb852ae44dcdf0df9b24117f
Additional Information 3: 993a
Additional Information 4: 993ac5f6525bc97f4b381e31cd2c5591

Tried installing into the default path and a new path. Tried as Administrator or normal user. Tried with custom config from Stackage. All crash in the same way.

Just to confirm that it wasn't a bad download, installing on Windows 7 32-bit & Windows 8 64-bit worked without issue.

**Comment by 23Skidoo** [comment]
Probably an issue with the `network` library.

**Comment by 23Skidoo** [comment]
Can you please compile and run [this test program](https://gist.github.com/23Skidoo/c8d6ab1684ea11195a04) and report us the results?

**Comment by bhillis** [comment]
I will prefix this with saying that I am quite new to haskell, so I might miss some of the intricacies. The fact that I am I am not sure what environment you wanted the test program built in so I downloaded the 64-bit Haskell Platform 2014.2.0.0 and used it to build the application.

I got the following output:

```
Trying to download http://hackage.haskell.org/packages/archive/00-index.tar.gz
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.18.0.5


Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 301 Moved Permanently 
Server: nginx/1.6.2
Content-Type: text/plain; charset=UTF-8
Location: /packages/index.tar.gz
Transfer-Encoding: chunked
Accept-Ranges: bytes
Date: Thu, 08 Jan 2015 20:35:23 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-syd1622-SYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1420749322.665580,VS0,VE389
Content-Length: 0


301 - redirect
Redirecting to http://hackage.haskell.org/packages/index.tar.gz ...
Sending:
GET /packages/index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.18.0.5


Recovering connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK 
Server: nginx/1.6.2
Content-Type: application/x-gzip
Cache-Control: public, no-transform, max-age=300
Content-MD5: 054e77405e642a37e93d052d6f88b8a1
ETag: "054e77405e642a37e93d052d6f88b8a1"
Last-Modified: Thu, 08 Jan 2015 20:28:18 GMT
Content-Length: 8567714
Accept-Ranges: bytes
Date: Thu, 08 Jan 2015 20:35:23 GMT
Via: 1.1 varnish
Age: 186
Connection: keep-alive
X-Served-By: cache-syd1622-SYD
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1420749323.137390,VS0,VE25


Downloaded to E:\Haskell\00-index.tar.gz
```

I then attempted to use cabal that was supplied with the Haskell Platform (cabal-install version 1.18.0.5, using version 1.18.1.3 of the Cabal library) and this was able to do a cabal update successfully.

So it seems it is either something to do with the version of cabal (cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library) or the version of the network library the pre-compiled version of cabal comes with.

**Comment by bhillis** [comment]
OK, so I managed to do a `cabal install cabal-install` which built a version of cabal 1.22.0.0 using the packages supplied by default in the 2014.2.0.0 Haskell Platform. This build version is able to update the package list without issue. I also checked with a cleaned out package cache and confirmed it works correctly.

So it looks like it is something in one of the libraries that the pre-compiled cabal.exe is built against.

**Comment by 23Skidoo** [comment]
> So it looks like it is something in one of the libraries that the pre-compiled cabal.exe is built against.

It was built with the latest 32-bit Haskell Platform (2014.2.0.0).

**Comment by 23Skidoo** [comment]
Can you please build the test program I supplied with 32-bit HP?

**Comment by bhillis** [comment]
Crash when the test program is built with 32-bit HP. Error similar to the original bug report. No issue with 64-bit HP.

Interestingly, 32-bit HP can run the test app with ghci in interpreted mode. Either, way, doesn't seem to be a cabal bug.

**Comment by 23Skidoo** [comment]
OK, please file this at the `network` library bug tracker then. The problem may also have been caused by `HTTP`.
