### ISSUE TITLE
cabal configure should complain when given wrong arguments

### ISSUE THREAD

**Issue by Javran** [haskell/cabal#2337]
I mistyped `cabal configure --bindir=<dir>` as `cabal configure -bindir=<dir>`, not a single warning is given, but `cabal copy` will still copy binaries to their default locations.

**Comment by psibi** [comment]
@ttuegel I think this issue can be closed since it seems to be resolved in master.

    $ cabal configure -bindir=/home/sibi/some_dir
    cabal: unrecognized 'configure' option `-bindir=/home/sibi/some_dir'

**Comment by 23Skidoo** [comment]
Optimistically closing.
