### ISSUE TITLE
cabal-install 1.22.0.0 fails to compile

### ISSUE THREAD

**Issue by bos** [haskell/cabal#2338]
I'm using ghc 7.4.2 and cabal-install 1.20.0.3 to try to upgrade cabal-install, but it fails:

```
$ cabal update
$ cabal install cabal-install
[17 of 77] Compiling Distribution.Client.Types ( Distribution/Client/Types.hs, dist/build/cabal/cabal-tmp/Distribution/Client/Types.o )

Distribution/Client/Types.hs:222:21:
    No instance for (Ord URI)
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      add an instance declaration for (Ord URI)
      or use a standalone 'deriving instance' declaration,
           so you can specify the instance context yourself
    When deriving the instance for (Ord RemoteRepo)
```

**Comment by bos** [comment]
The issue is that the lower bound on the `network` package is bad. The earliest version of `network` that has an `Ord` instance for `Network.URI` is 2.4.0.0.

The problem can be worked around by compiling with `-fnetwork-uri`, but this is not obvious without some sleuthing.

**Comment by tibbe** [comment]
I've fixed the already uploaded version. I will include an updated lower bound in the next patch release.
