### ISSUE TITLE
Linker problem when installing alex on CentOS 5 with newer cabal-install

### ISSUE THREAD

**Issue by acfoltzer** [haskell/cabal#2339]
Okay, yikes, esoteric issue title, I know.

On a 32-bit CentOS 5 machine, I've got three installations of `cabal-install` and `Cabal`:

```
$ /opt/ghc-7.6.3/bin/cabal --version
cabal-install version 1.18.0.3
using version 1.18.1.3 of the Cabal library
$ /opt/ghc-7.8.3/bin/cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.1 of the Cabal library
$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library
```

Keeping GHC versions the same at 7.8.3, just switching `cabal`s, I try installing `alex` into a fresh sandbox. The 1.18.0.3 install goes swimmingly. The 1.20.0.3 and 1.22.0.0 installs however fail to link the `alex` executable at the end of the build:

```
...
Linking dist/dist-sandbox-79015d48/build/alex/alex ...
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0x3bb): undefined reference to `Threefish_256_Process_Block'
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0x543): undefined reference to `Threefish_256_Process_Block'
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0x883): undefined reference to `Threefish_256_Process_Block'
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0xb9f): undefined reference to `Threefish_256_Process_Block'
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0xd5b): undefined reference to `Threefish_256_Process_Block'
/tmp/tmp.ISEzb16554/.cabal-sandbox/lib/i386-linux-ghc-7.8.3/tf-random-0.5/libHStf-random-0.5.a(Gen.o):(.text+0xee3): more undefined references to `Threefish_256_Process_Block' follow
collect2: ld returned 1 exit status
Failed to install alex-3.1.4
Updating world file...
cabal: Error: some packages failed to install:
alex-3.1.4 failed during the building phase. The exception was:
ExitFailure 1
```

I notice that the final invocation of `ghc` to build the executable has more linker flags in the newer versions. Maybe something is causing the linker to miss the symbol from `tf-random`'s cbits?

I've posted full logs here: https://gist.github.com/acfoltzer/c46274098956d03e6f79

It's worth noting that this does not occur on a similarly-configured 64-bit machine, nor any of our newer CentOS machines.

Thanks for any ideas you might have.

**Comment by tibbe** [comment]
There are two changes that could be related:

 1. We now support relocatable packages on some platforms. @christiaanb knows more about that.
 2. There's 685bbaee45e7fb90bd39974fd51f14716d2818c4, which changes how we build C sources for dynamic linking (we didn't do it correct before).

**Comment by mietek** [comment]
Would either of these changes affect 1.20.0.3?

**Comment by christiaanb** [comment]
One thing I notice is that 1.20 and 1.22 do things like:
`/usr/bin/strip dist/dist-sandbox-d8d63bac/build/libHSprimitive-0.5.4.0-ghc7.8.3.so --strip-unneeded`

Where 1.18 does not do that any symbol stripping of the libraries.
I'm quite sure that I did not touch any symbol-stripping related aspects in my relocatable packages patch.

**Comment by mietek** [comment]
@acfoltzer: Does that also happen when linking `alex-3.1.3`, or just the newly-released `alex-3.1.4`?

**Comment by acfoltzer** [comment]
@mietek same problem occurs for alex-3.1.3.

@christiaanb this sounds promising, since the break appears to be going from 1.18 -> 1.20, and lo and behold passing `--disable-library-stripping` causes the installation to succeed.

For the purposes of this ticket then, the question is whether we should run `strip` by default on older platforms? This distro of course uses a positively ancient version:

```
$ /usr/bin/strip --version
GNU strip 2.17.50.0.6-26.el5 20061020
```

I suspect newer versions of `strip` don't break the symbols in `libHStf-random-0.5.a`.

**Comment by acfoltzer** [comment]
It looks like the `--strip-unneeded` option to `strip` 2.17 incorrectly strips the `Threefish_256_Process_Block` symbol from the `threefish_block.o` file in the static archive. I installed binutils 2.18, and it works correctly.

To save others some grief, I think we should put a check in `Distribution.Simple.Program.Strip` like we have for some entire platforms that skips library stripping for 32-bit systems with binutils older than 2.18. I don't mind adding this check, but am wondering if cabal has a pattern for checking tool versions like that (I've never messed with the source before)

**Comment by 23Skidoo** [comment]
>  I don't mind adding this check, but am wondering if cabal has a pattern for checking tool versions like that (I've never messed with the source before)

Yes, look at [`tarProgram`](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Program/Builtin.hs#L323) for an example, where we check whether it supports `--format`.
