### ISSUE TITLE
Cabal-install crashes when downloading a package

### ISSUE THREAD

**Issue by HJvT** [haskell/cabal#2341]
cabal-install crashed each time a package was to be downloaded; adding the line:

```
jobs: $ncpus
```

to the file %appdata%\cabal\config solved the problem.

OS: Windows 8.1
Haskell Platform: 2014.2.0.0
cabal-install: 1.20.0.4 and 1.22.0.0

**Comment by HJvT** [comment]
It seems that the problem no longer exists in cabal-install 3.4.0.0, so the issue can be closed.

**Comment by Mikolaj** [comment]
@HJvT: thank you, closing.
