### ISSUE TITLE
`cabal install --package-db=user` results in an internal error

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2344]
```
> cabal install --package-db=user multistate
```

> Resolving dependencies...
> Configuring multistate-0.1.3.2...
> Building multistate-0.1.3.2...
> Failed to install multistate-0.1.3.2
> Build log ( ~/.cabal/logs/multistate-0.1.3.2.log ):
> Configuring multistate-0.1.3.2...
> Building multistate-0.1.3.2...
> Preprocessing library multistate-0.1.3.2...
> setup-Simple-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4: internal error: unexpected package db stack: [GlobalPackageDB,UserPackageDB,UserPackageDB,SpecificPackageDB "dist/package.conf.inplace"]
> cabal: Error: some packages failed to install:
> multistate-0.1.3.2 failed during the building phase. The exception was:
> ExitFailure 1

tested with both 1.22.0.0 and HEAD at 0daccdec60f97f198bbf04a888bb8f327841d4cf, with no sandbox and require-sandbox=false.

**Comment by dcoutts** [comment]
Yes, it should produce an error formatted for the user, rather than an internal error.

**Comment by jneira** [comment]
it is being reproduced with newer cabal versions?

**Comment by gbaz** [comment]
This still fails with v1-install

```
internal error: unexpected package db stack: [GlobalPackageDB,UserPackageDB,UserPackageDB]
CallStack (from HasCallStack):
  error, called at ./Distribution/Simple/Program/HcPkg.hs:496:20 in Cbl-3.4.0.0-ee8b7702:Distribution.Simple.Program.HcPkg
```

However, it doesn't go wrong with v2-install, which doesn't install into package-dbs directly, anway. So I think we can close on the basis that v2 obsoletes this.

**Comment by fgaz** [comment]
Could it be that the error still happens with Setup.hs?
