### ISSUE TITLE
description of the --package-db flag is lacking

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2345]
the the difference between cabal help text

> Use a given package database (to satisfy dependencies and register in). May be a specific file, 'global', 'user' or 'clear'.

and description froom userguide (https://www.haskell.org/cabal/users-guide/installing-packages.html)

> Allows package dependencies to be satisfied from this additional package database db in addition to the global package database. All packages in the user’s package database will be ignored. The interpretation of db is implementation-specific. Typically it will be a file or directory. Not all implementations support arbitrary package databases.

Also i believe that the latter description is still wrong; when not specifying a package-db packages installed in user db are still found. Given that i ran into #2344 when trying to find out what is going on, i am not sure what the _supposed_ behaviour is.

**Comment by bergey** [comment]
I too would like better docs for `--package-db`, and especially better error messages when it's used in unsupported ways.

When I run `cabal install --package-db=global`, the error is 
`cabal: If the global package db is specified, it must be specified first and
cannot be specified multiple times`

This is a very cryptic way to suggest that I write `cabal install --package-db=clear  --package-db=global`.

Assuming I'm understanding the behavior, as I starting point, I propose:
`    --package-db=DB                 Add the given package database to those used to satisfy
                                    dependencies and register in. May be a
                                    specific file, 'global', 'user' or 'clear'.  The default list is [global, user].  'clear' clears the list, rather than appending to it.`

And errors if `--package-db=user` or `--package-db=global` is called without `--package-db=clear`: `The {user|global} package db is already included, and cannot be included twice.  Maybe you meant to use '--package-db=clear' before adding it?`

**Comment by lspitzner** [comment]
I have included a temporary modification in #2416 that simply explicitly leaves the initial list unspecified, but improves the situation by explaining how clear, user, global, $file work (in my current understanding, which might be wrong completly.)

**Comment by dcoutts** [comment]
Added a comment to #2416 about the behaviour of `--package-db`. I guess we should update the user guide with the same.

**Comment by lspitzner** [comment]
#2416 fixes the command-line-side of this. close, or keep it open as a reminder to update the user guide (i have not looked into that).
