### ISSUE TITLE
Allow cabal to execute user-defined subcommands

### ISSUE THREAD

**Issue by fujimura** [haskell/cabal#2349]
I propose to add a functionality to allow Cabal to execute user-defined subcommands like `git`.
With this, user or library author can add their custom command like `cabal doctest` etc. (see #2327).

I tried to implement this roughly and basic part is working.
https://github.com/fujimura/cabal/compare/user-defined-subcommands?expand=1

If you can agree with this, I'm happy to finish implementation and make an pull request. Please let me know how do you think and concerns about this. Thanks!

**Comment by tibbe** [comment]
How do users create subcommands with your approach?

@dcoutts thoughts?

**Comment by luite** [comment]
If this is added, it should probably use the existing `cabal exec` functionality (and perhaps extend it where needed) to work with the correct package environment. Just having `cabal userCommand` as an alias for `cabal-userCommand` isn't terribly useful by itself in my opinion (which is what I understand it's doing in the WIP, correct me if i'm wrong).

**Comment by tibbe** [comment]
We should also look at other systems, e.g. git, and see how they provide this kind of facility. @dcoutts and I have discussed this in the past. For example, it would be useful to allow a subcommand to run in an environment where the preprocessors have already been run*.

* An example of such a use case is a source code indexer (think hashtags). Here we want to process the source code with our own "compiler" instead of GHC, but we still want the source code to be preprocessed for us.

**Comment by fujimura** [comment]
@tibbe 

> How do users create subcommands with your approach?

By creating an executable prefixed with `cabal-` and put it under PATH. In most case, it will be a Cabal package with executable since it's Haskell.

What I used to test the code above is:

```
$ cat .cabal-sandbox/bin/cabal-foo
#! /bin/sh
echo "FOO"
$ cabal foo
FOO
```
> other systems

Git seems to be just invoking executable starts with `git-` in PATH. RubyGems has interface to register custom command(http://ruby-doc.org/stdlib-2.2.0/libdoc/rubygems/rdoc/Gem/CommandManager.html). Why I chose the way Git is using for my implementation is, it's easier than creating interface for subcommands.

@luite 

>  it should probably use the existing cabal exec functionality

Thanks for pointing it out. This is yet another missing implementation in my code.

**Comment by 23Skidoo** [comment]
Is this the same as aliases? I think there's already a ticket for that.

**Comment by fujimura** [comment]
Not same as aliases. Aliases discussed in https://github.com/haskell/cabal/issues/1089 is to extend existing commands, not to add new command.

Just FYI, Links below are articles about how to add custom command to git. 
http://stackoverflow.com/questions/10978257/extending-git-functionality
http://thediscoblog.com/blog/2014/03/29/custom-git-commands-in-3-steps/

**Comment by BardurArantsson** [comment]
As @tibbe said:

> We should also look at other systems, e.g. git, and see how they provide this kind of facility

This would actually come in very handy for an issue I'm try to implement (#2810) which will probably require setting the current process' CWD during e.g. test or compilation (TH code might rely on relative paths), etc. Unfortunately setting it back properly is very error-prone/fragile without spawning a subprocess to do the setCWD and letting it do all the work of the actual command that was invoked. (See https://github.com/haskell/cabal/issues/2810#issuecomment-137914204 and https://github.com/haskell/cabal/issues/2810#issuecomment-137922614). However, a git-like model would fix both that problem almost as a side effect[1].

This issue would also become trivial.

Would the powers that be be interested in my trying to tackle this and just doing a simple version with split-up-executables? (I'll create an issue if I get positive feedback.)

**Comment by hvr** [comment]
Why do you need to restore the CWD during the `cabal` process lifetime?

**Comment by alok** [comment]
I'd just like to second this idea. Rust has this, and it allows things like https://github.com/killercup/cargo-edit, which are very useful for simple project management
