### ISSUE TITLE
cabal-install doesn't

### ISSUE THREAD

**Issue by RobertHarper** [haskell/cabal#2355]
I am running Mac OS X 10.10 on two platforms (a MacBook Air and an iMac).  I use mac ports to perform an upgrade after the updates; this included upgrading GHC to version ghc @7.8.3_1.  I suspect the problems I'm experiencing are a matter of version skew, but I haven't been able to work them out.

When I tried to install Agda, after the GHC upgrade, cabal asked me to update, which I duly did.  It then asked me to re-install cabal, by using cabal to install cabal-install, but this fails:

~> cabal update
Downloading the latest package list from hackage.haskell.org
Note: there is a new version of cabal-install available.
To upgrade, run: cabal install cabal-install
~> cabal install cabal-install
Resolving dependencies...
Downloading Cabal-1.22.0.0...

I then get hundred of compilation errors, most of which seem to be about a missing delimiter, and it eventually is unable to install cabal because, it claims, the currently installed version is not managed by cabal, which is not true.  Pressing on I try to install Agda, and it fails as well, apparently due to version skew:

cabal install Agda
Resolving dependencies...
Downloading Agda-2.4.2.2...
[1 of 1] Compiling Main             ( /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-91013/Agda-2.4.2.2/dist/setup/setup.hs, /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-91013/Agda-2.4.2.2/dist/setup/Main.o )
Linking /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-91013/Agda-2.4.2.2/dist/setup/setup ...
Configuring Agda-2.4.2.2...
setup: The program 'alex' version >=3.1.0 && <3.2 is required but the version
found at /usr/bin/alex is version 3.0.2
Failed to install Agda-2.4.2.2
cabal: Error: some packages failed to install:
Agda-2.4.2.2 failed during the configure step. The exception was:
ExitFailure 1

Could someone please advise me on how to get back to a sane state?

**Comment by 23Skidoo** [comment]
> I then get hundred of compilation errors, most of which seem to be about a missing delimiter

Likely a Clang CPP issue. Others (@cartazio?) would know more.

> `setup: The program 'alex' version >=3.1.0 && <3.2 is required but the version
found at /usr/bin/alex is version 3.0.2`

Try running `cabal install happy alex` before installing `Agda`.

**Comment by RobertHarper** [comment]
thanks.  i appear to be in some desperately screwed up state, for reasons unknown.  i deinstalled ghc from macports, and re-installed the haskell platform from haskell.org <http://haskell.org/> from scratch.  i deleted .cabal entirely, then did cabal update, then cabal install Agda:

~> cabal install Agda
Resolving dependencies...
Configuring STMonadTrans-0.3.2...
Configuring boxes-0.1.3...
Failed to install STMonadTrans-0.3.2
Build log ( /Users/rh/.cabal/logs/STMonadTrans-0.3.2.log ):
Configuring data-hash-0.2.0.0...
Configuring geniplate-0.6.0.5...
Failed to install boxes-0.1.3
Build log ( /Users/rh/.cabal/logs/boxes-0.1.3.log ):
Failed to install data-hash-0.2.0.0
Build log ( /Users/rh/.cabal/logs/data-hash-0.2.0.0.log ):
Configuring hashtables-1.1.2.1...
Failed to install geniplate-0.6.0.5
Build log ( /Users/rh/.cabal/logs/geniplate-0.6.0.5.log ):
Configuring polyparse-1.11...
Configuring strict-0.3.2...
Failed to install hashtables-1.1.2.1
Build log ( /Users/rh/.cabal/logs/hashtables-1.1.2.1.log ):
Configuring tf-random-0.5...
Failed to install polyparse-1.11
Build log ( /Users/rh/.cabal/logs/polyparse-1.11.log ):
Failed to install strict-0.3.2
Build log ( /Users/rh/.cabal/logs/strict-0.3.2.log ):
Failed to install tf-random-0.5
Build log ( /Users/rh/.cabal/logs/tf-random-0.5.log ):
cabal: Error: some packages failed to install:
Agda-2.4.2.2 depends on tf-random-0.5 which failed to install.
QuickCheck-2.7.6 depends on tf-random-0.5 which failed to install.
STMonadTrans-0.3.2 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
boxes-0.1.3 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
cpphs-1.18.6 depends on polyparse-1.11 which failed to install.
data-hash-0.2.0.0 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
equivalence-0.2.5 depends on STMonadTrans-0.3.2 which failed to install.
geniplate-0.6.0.5 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
hashtables-1.1.2.1 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
haskell-src-exts-1.16.0.1 depends on polyparse-1.11 which failed to install.
polyparse-1.11 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
strict-0.3.2 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)
tf-random-0.5 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e:
Cabal-1.22.0.0-2c22f46d0e9966d313e70754f2d55c4e is unusable due to missing or
recursive dependencies:
base-4.7.0.1-c64d224738ec7af4085e89ca9c12c37b
binary-0.7.1.0-06fe2cfe2c00e6f7d43cdb53345c4945
bytestring-0.10.4.0-18fe2f3ce284617c82da1702e16772cf
containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5
deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77
directory-1.2.1.0-bfdf4eb032907ecaf13c26632da610b8
process-1.2.0.0-4870cdb503fdbb301e26c7b926e216b2
time-1.4.2-bf925e935c287d0b75398fe297453c28
unix-2.7.0.1-f08a326ca9af10483c3b264aeb4b091c
(use -v for more information)
)

i’ve obviously gotten something way wrong, but it’s a little mysterious right now what that might’ve been, or how i might’ve done that.

help, please!  i used to be able to run Agda (and ghc) no problem!

bob

**Comment by 23Skidoo** [comment]
>  i deleted .cabal entirely

You also need to delete `~/.ghc`.

**Comment by RobertHarper** [comment]
did that too, but forgot to mention it in my previous, sorry.

-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by RobertHarper** [comment]
after doing a clean install (afaik), i just tried to build cpphs, which Agda happens to need, but anyway it should build, i guess:

 sudo activate-hs 7.8.3

Haskell now set to:
    GHC      7.8.3
    Arch.    x86_64
    Platform 2014.2.0.0

View documentation with this command:
    open /Library/Haskell/doc/start.html
~> cabal update
Config file path source is default config file.
Config file /Users/rwh/.cabal/config not found.
Writing default configuration to /Users/rwh/.cabal/config
Downloading the latest package list from hackage.haskell.org
~> cabal install cpphs
Resolving dependencies...
Downloading polyparse-1.11...
Configuring polyparse-1.11...
Building polyparse-1.11...
Failed to install polyparse-1.11
Build log ( /Users/rwh/.cabal/logs/polyparse-1.11.log ):
[1 of 1] Compiling Main             ( /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/polyparse-1.11-95129/polyparse-1.11/dist/setup/setup.hs, /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/polyparse-1.11-95129/polyparse-1.11/dist/setup/Main.o )
Linking /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/polyparse-1.11-95129/polyparse-1.11/dist/setup/setup ...
Configuring polyparse-1.11...
Building polyparse-1.11...
Preprocessing library polyparse-1.11...
<command line>: cannot satisfy -package-id text-1.1.0.0-9bd69e9ace700e05fb08e463086bc383
    (use -v for more information)
cabal: Error: some packages failed to install:
cpphs-1.18.6 depends on polyparse-1.11 which failed to install.
polyparse-1.11 failed during the building phase. The exception was:
ExitFailure 1
~> 

as you've seen building Agda leads to lots of such errors, but i'm trying to isolate the problem.  i appear to have a fresh copy of ghc installed, i removed all previous cabal files, i did a cabal update, which built a new configuration, and then simply tried to install a single package (which i don't even know what it is, but i could guess, and that's of course besides the point).

bob


-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by 23Skidoo** [comment]
> `<command line>: cannot satisfy -package-id text-1.1.0.0-9bd69e9ace700e05fb08e463086bc383 (use -v for more information)`

I strongly suspect that there is some old state left over. What's the output of `ghc-pkg check`?

**Comment by RobertHarper** [comment]
ghc-pkg check
WARNING: cache is out of date: /Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/package.conf.d/package.cache
Use 'ghc-pkg recache' to fix.

-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by RobertHarper** [comment]
doing the suggested recache allows me to build cpphs!  building Agda now, but that takes a bit starting from nothing, but is building smoothly at the moment.  thanks for the help so far!

-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by RobertHarper** [comment]
i spoke too soon, now i get a truly strange situation.  i build cpphs-1.18.6 (the current default, it seems), and then while building Agda it complains of exactly not having this version that i installed moments before!  i am rather confused ...

~> cabal install cpphs
Resolving dependencies...
Configuring polyparse-1.11...
Building polyparse-1.11...
Installed polyparse-1.11
Downloading cpphs-1.18.6...
Configuring cpphs-1.18.6...
Building cpphs-1.18.6...
Installed cpphs-1.18.6

~> cabal install Agda
Resolving dependencies...
Downloading STMonadTrans-0.3.2...
Downloading boxes-0.1.3...
Configuring STMonadTrans-0.3.2...
Downloading data-hash-0.2.0.0...
Configuring boxes-0.1.3...
Downloading geniplate-0.6.0.5...
Configuring data-hash-0.2.0.0...
Downloading hashtables-1.1.2.1...
Configuring geniplate-0.6.0.5...
Downloading haskell-src-exts-1.16.0.1...
Downloading strict-0.3.2...
Configuring hashtables-1.1.2.1...
Downloading tf-random-0.5...
Configuring strict-0.3.2...
Configuring tf-random-0.5...
Building STMonadTrans-0.3.2...
Building boxes-0.1.3...
Configuring haskell-src-exts-1.16.0.1...
Building data-hash-0.2.0.0...
Building geniplate-0.6.0.5...
Building hashtables-1.1.2.1...
Building strict-0.3.2...
Building tf-random-0.5...
Building haskell-src-exts-1.16.0.1...
Installed boxes-0.1.3
Installed STMonadTrans-0.3.2
Downloading equivalence-0.2.5...
Configuring equivalence-0.2.5...
Installed data-hash-0.2.0.0
Building equivalence-0.2.5...
Installed strict-0.3.2
Installed tf-random-0.5
Downloading QuickCheck-2.7.6...
Configuring QuickCheck-2.7.6...
Installed geniplate-0.6.0.5
Building QuickCheck-2.7.6...
Installed equivalence-0.2.5
Installed hashtables-1.1.2.1
Installed QuickCheck-2.7.6
Installed haskell-src-exts-1.16.0.1
Downloading Agda-2.4.2.2...
Configuring Agda-2.4.2.2...
Failed to install Agda-2.4.2.2
Build log ( /Users/rwh/.cabal/logs/Agda-2.4.2.2.log ):
[1 of 1] Compiling Main             ( /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-95904/Agda-2.4.2.2/dist/setup/setup.hs, /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-95904/Agda-2.4.2.2/dist/setup/Main.o )
Linking /var/folders/yx/fs78zb6j2tvfj8hdtsg5877r0003zh/T/Agda-2.4.2.2-95904/Agda-2.4.2.2/dist/setup/setup ...
Configuring Agda-2.4.2.2...
setup: The program cpphs version >=1.18.6 && <1.19 is required but the version
found at /Users/rwh/Library/Haskell/bin/cpphs is version 1.16
cabal: Error: some packages failed to install:
Agda-2.4.2.2 failed during the configure step. The exception was:
ExitFailure 1



-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by 23Skidoo** [comment]
Is `cpphs` in PATH? You may need to add `~/.cabal/bin` to `PATH`.

**Comment by RobertHarper** [comment]
yes, it turns out that there is a link to the old cpphs in ~/Library/Haskell/bin, via an old installation of ghc.  i'll check my PATH.  thanks!

bob
-----------------------------
Bob Harper
Carnegie Mellon CSD
rwh@cs.cmu.edu
-----------------------------

**Comment by cartazio** [comment]
1) whats the output of `ghc --settings`
2) you aren't using sudo anywhere aside from `activate-hs` right?

i personally dont recommend haskell platform for precisely these reasons :)

sounds like the problems solved now?

**Comment by RobertHarper** [comment]
hi carter,

i have to sudo to remove .ghc completely, otherwise yes.  earlier this evening i removed everything i could find related to haskell, and i noticed that there were some symbolic links in /usr/local/bin pointing to the GHC framework, which i removed (don’t ask my how they got there, over time i guess).  after that i reinstalled the haskell platform from scratch, then did a cabal install cabal-install, which failed before, and i am now building Agda, so far with no problems, but it is very slow on my macbook air running on battery.  this may work, not sure, but i’m amazed that i got into such a thicket without doing “anything” except having stuff evolve over years.  suddenly, gebam.  wish me luck.

how’re things with you?  where are you?  what are you up to?

bob

**Comment by cartazio** [comment]
hrm, perhaps https://ghcformacosx.github.io/ would be a bit easier to get up and running, or at least worth considering? @etrepum is the author there, and it has a MUCH simpler install and UX than haskell platform.

**Comment by RobertHarper** [comment]
thanks for all the help, i appear to have resolved the problem by (a) removing everything i could find related to haskell and cabal, and (b) removing even more, and (c) reinstalling the haskell platform, then running cabal to update and install cabal-install, and then the build of Agda completed without incident.

mikhail’s tips helped resolve some problems, and gave me hints about where to look for others.  it turns out, for reasons unknown to me, there were quite a few stray symbolic links in /usr/local/bin, not sure how they got there, including a link to cabal inside of the GHC framework in /Library, and that was the one being selected when i ran cabal.  i removed all such symbolic links as i could find, and then the rebuild worked.  (well, i haven’t tried using the rebuilt agda yet, but i think if it built it’ll be ok.)

afaik the whole thing was a matter of bit rot.  it basically had to be, but the problem is how to discover what is going wrong.  trial and error.

thanks for the help.
bob harper

**Comment by RobertHarper** [comment]
never heard of it.  i’ll check it out.

bob

**Comment by 23Skidoo** [comment]
Glad to have helped.

**Comment by zhiyuanshi** [comment]
Searching "Agda" and "cpphs" has led a frustrated Agda newbie here.

Hi @RobertHarper! I second @cartazio's suggestion of using https://ghcformacosx.github.io/. I recently switched from Haskell Platform (by `sudo uninstall-hs only 7.8.3 --remove`) to https://ghcformacosx.github.io/. Thanks, at least `cabal install Agda` no longer hangs forever! (In my opinion, [Haskell Platform](https://github.com/haskell/haskell-platform) does not seem to be well maintained—the last commit was in March and a lot of [issues](https://github.com/haskell/haskell-platform/issues) get unaddressed or are not even answered.)

Having said that, when it comes back to installing Agda, I still got no luck:

```bash
Configuring Agda-2.4.2.2...
setup: The program cpphs version >=1.18.6 && <1.19 is required but the version
found at /Users/george/Library/Haskell/bin/cpphs is version 1.19
Updating documentation index
/Users/george/Library/Haskell/share/doc/x86_64-osx-ghc-7.8.4/index.html
cabal: Error: some packages failed to install:
Agda-2.4.2.2 failed during the configure step. The exception was:
ExitFailure 1
```

I'm not sure if this is an issue of Cabal or Agda?

**Comment by RobertHarper** [comment]
i had a helluva time installing agda because of the haskell cabal being such a mess.  i had to deinstall ghc, manually remove all traces of it, which somehow remained, then reinstall all from scratch, and then it worked.

bob

**Comment by zhiyuanshi** [comment]
Finally, I managed to find my way out by:

1. Reset my packages according to [an article at FPComplete](https://www.fpcomplete.com/user/simonmichael/how-to-cabal-install#the-easy-solution--reset-your-packages):

        rm -rf ~/.ghc ~/.cabal

2. Install the version of cpphs that satisfy the requirement (>=1.18.6 && <1.19) of Agda:

        cabal install cpphs-1.18.9
