### ISSUE TITLE
Disabled test suites cause spurious test failures

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2357]
This seems to be a regression in cabal-install 1.22 (or Cabal, not sure). As an example, unpack mwc-random-0.13.3.0 and run `cabal test`. With cabal-install 1.22, I get the output:

```
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring mwc-random-0.13.3.0...
cabal: Cannot build the test suite 'tests' because the component is marked as
disabled in the .cabal file.
```

With 1.20, I get the far more useful:

```
Saved package config file seems to be corrupt. Configuring with default flags.
If this fails, please run configure manually.
Resolving dependencies...
Configuring mwc-random-0.13.3.0...
Building mwc-random-0.13.3.0...
Preprocessing library mwc-random-0.13.3.0...
[1 of 3] Compiling System.Random.MWC ( System/Random/MWC.hs, dist/build/System/Random/MWC.o )

System/Random/MWC.hs:103:1: Warning:
    The import of ‘Bits’ from module ‘Data.Bits’ is redundant
[2 of 3] Compiling System.Random.MWC.Distributions ( System/Random/MWC/Distributions.hs, dist/build/System/Random/MWC/Distributions.o )
[3 of 3] Compiling System.Random.MWC.CondensedTable ( System/Random/MWC/CondensedTable.hs, dist/build/System/Random/MWC/CondensedTable.o )
In-place registering mwc-random-0.13.3.0...
Package has no test suites.
```

**Comment by tibbe** [comment]
I agree that the 1.20 behavior is better. We should revert to the old behavior and add a unit test to make sure it doesn't regress.

**Comment by snoyberg** [comment]
Cool, thanks for the quick response @tibbe.

**Comment by kazu-yamamoto** [comment]
Is this also relating to this bug? https://github.com/kazu-yamamoto/unix-time/issues/29

**Comment by tibbe** [comment]
@ttuegel this issue and #2313 are the two remaining ones holding up the next minor release. Will you have time to look at them?

**Comment by ttuegel** [comment]
@tibbe I'm looking at them right now.

**Comment by ttuegel** [comment]
The package does have a test suite, and it has been disabled with `buildable: False` in the .cabal file. The error message from 1.20 is actually incorrect.

**Comment by kazu-yamamoto** [comment]
@ttuegel What is the source of this problem? https://github.com/kazu-yamamoto/unix-time/issues/29

**Comment by ttuegel** [comment]
@kazu-yamamoto This looks like a regression in the `Configure` build-type. The `build` command doesn't accept component names. I'll open another issue for it.

**Comment by kazu-yamamoto** [comment]
@ttuegel Thanks.

**Comment by tibbe** [comment]
@ttuegel I think @snoyberg and I are both arguing that the 1.20 behavior is *better*. In particular it lets you script interaction with cabal in a consistent way (e.g. use the same .travis.yml for all packages built by travis) without having to deal with issues like a particular package not having a test suite.

I think we should warn that there are no test suites, but I don't think we should fail.

**Comment by ttuegel** [comment]
@tibbe I agree, but that's not what this is. This package *does* have test suites. This isn't `cabal test` failing because there are no tests, this is `cabal build` failing because the named component (`tests`) isn't buildable. The way I understand the semantics of `buildable: False`, this is the correct result. I doubt it's what the package author intended, so we may have a miscommunication about what the `buildable` field means. Or, the misunderstanding is mine.

In 1.20, we built the entire package with `cabal build` before `cabal test`, but now we name the tests suites in the call to `cabal build` (to avoid building the entire library unnecessarily). That's why this starts failing in 1.22; `cabal build` skips unbuildable components, but `cabal build [name]` fails if the named component is unbuildable.

**Comment by ttuegel** [comment]
So, I think what I'll do is have `cabal test` filter unbuildable test suites from the call to `cabal build`. I think this subverts the author's stated intent, but I also think that's not actually what the package author wants.
