### ISSUE TITLE
Implement Monad for Condition

### ISSUE THREAD

**Issue by eternaleye** [haskell/cabal#2366]
Condition being an instance of Monad would make a number of things much simpler, in particular specializing CondTree's for the current build environment. For example, in writing a tool that converts Cabal format to the Exheres format used on Exherbo, I found that implementing Monad for Condition allowed me to clear out cases like (non) Linux OS ConfVars by converting them to Lit in a much easier manner. I'll paste my definition below, though it's a trivial one.

```haskell
instance Monad Condition where
    return = Var
    -- Terminating cases
    (>>=) (Lit x) _ = Lit x
    (>>=) (Var x) f = f x
    -- Recursing cases
    (>>=) (CNot  x  ) f = CNot (x >>= f)
    (>>=) (COr   x y) f = COr  (x >>= f) (y >>= f)
    (>>=) (CAnd  x y) f = CAnd (x >>= f) (y >>= f)
```

I also implemented Functor, Applicative, MonadPlus, and Alternative - there was really no reason not to.

```haskell
instance Functor Condition where
    fmap = liftM

instance MonadPlus Condition where
    mzero = Lit False
    mplus = COr

instance Applicative Condition where
    pure  = return
    (<*>) = ap

instance Alternative Condition where
    empty = mzero
    (<|>) = mplus
```

Another thing that might be worthwhile is to consider making a contractual guarantee that a Condition will always be in some normalized state, which would allow for Eq to behave more sensibly.

In particular, I implemented a normalization function such that the Condition is always in disjunctive normal form, with COr's descending to the right and CAnd's descending to the left. Non-root Lits can be eliminated via or/and/not identities, and mutually exclusive Var/CNot Var subexpressions can cancel; I also ordered Vars 'before' CNot Vars (nearer to the root).

In the case of Ord a => Condition a, one can also then sort the Vars, to have a truly canonical ordering. In that case, I'd have the ordering of the Var values take precedence over Var/CNot Var ordering, so that disjoint subexpressions are adjacent (making elimination simpler).

**Comment by 23Skidoo** [comment]
Care to write a pull request?
