### ISSUE TITLE
Cabal fails to install listed dependency "text"

### ISSUE THREAD

**Issue by yongqli** [haskell/cabal#2369]
Please see this issue: https://github.com/ndmitchell/cmdargs/issues/19

Our program compiles but doesn't run properly -- any ideas?

**Comment by yongqli** [comment]
Looks like this is cabal's fault. If you run [test.sh in the test case](https://gist.github.com/j-e-k/3a64faf2a4a5fa62e92e), even though it lists `text` as a dependency it is not installed. Installing `text` into the sandbox fixes the issues.

**Comment by yongqli** [comment]
cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library

**Comment by lspitzner** [comment]
i am a bit confused about your testcase. `test.sh` reads

~~~~
cabal run
runhaskell Main.hs 
~~~~

Both commands have the intention of running the program (one in sandbox, one not). What is the output in each case? Or did you mean `cabal build` ?

**Comment by yongqli** [comment]
It runs them one after the other. The cabal sandbox version outputs `cmdargs-test: System.Console.CmdArgs.Implicit, unexpected flag (hello): Text` because it is using the wrong version of `text`. The `runhaskell` version outputs `Sample {hello = ""}` because it is using the latest version of `text`.

**Comment by yongqli** [comment]
This only seems to happen on our Ubuntu machine on which we installed ghc from haskell-platform (the pre-built binaries)

**Comment by ttuegel** [comment]
Could you elaborate on "the wrong version of text"? Your example doesn't specify a version constraint, so I'm not sure what this means.

**Comment by grayjay** [comment]
I was able to reproduce the error with `text-1.1.0.0` (included with Haskell Platform 2014.2.0.0), but not `text-1.2.2.1`.  cabal and runhaskell both gave the same result.

Maybe a newer version of `text` was installed in the user package database.  Then cabal would have ignored the user db and used `text` from HP, and runhaskell would have used the version from the user db.

**Comment by grayjay** [comment]
I think that the only issue with cabal is that it didn't choose the latest version of `text`.  nix-style build should help, by reducing the need for globally installed packages and not preferring packages in the store.
