### ISSUE TITLE
"cabal exec" doesn't handle subdirectories the same way as the root folder. 

### ISSUE THREAD

**Issue by seanparsons** [haskell/cabal#2374]
If I run "cabal exec ghc myfile.hs" from a sub-folder of the sandbox, the sandboxed libraries are completely ignored. I'm not immediately sure if this is a conscious design decision, but it can make things awkward if you have a nested folder to work from the root of the project.

**Comment by lspitzner** [comment]
(duplicate of #2022/#2004, still an open issue)

direct explanation: see `cabal help sandbox`:

> Currently, cabal will not search for a sandbox in folders above the current
one, so cabal will not see the sandbox if you are in a subfolder of a
sandbox.

and `cabal exec` works outside of a sandbox (without any effect on the rest of the command, afaik), producing the noted behaviour.

feel free to add your opinion to #2004 :-)

**Comment by seanparsons** [comment]
Ah, Github search didn't find those!
