### ISSUE TITLE
'cabal build' does not accept component names in 'Configure' build-type

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#2375]
As reported here https://github.com/kazu-yamamoto/unix-time/issues/29, the build command does not accept component names in packages using the 'Configure' build type, as of Cabal 1.22.

**Comment by ttuegel** [comment]
I have confirmed this is a regression from Cabal 1.20.

**Comment by tibbe** [comment]
Anyone have a fix?

**Comment by kazu-yamamoto** [comment]
What is the status of this issue?

**Comment by ttuegel** [comment]
This is caused by `autoconfUserHooks` not allowing extra arguments to the build command. I'm testing a patch now. The regression is because `cabal-install < 1.22` builds the entire package just to build the test suites, whereas `cabal-install-1.22` tries to build only the required components.

This only affects users trying to build individual components--and transitively, trying to build tests and benchmarks. Building and installing packages is not affected. A workaround is to use `./setup test` to run tests.

I'm bumping the milestone to `Cabal-1.24` because `Cabal-1.22.1.0` is already out.

**Comment by tibbe** [comment]
@ttuegel if you merge to the 1.22 branch I will roll a bugfix release.

**Comment by ttuegel** [comment]
@tibbe Already done!

**Comment by tibbe** [comment]
@dcoutts is there a problem in changing the signature of `autoconfUserHooks`?

**Comment by dcoutts** [comment]
@tibbe there's no change of signature here, it's fine.

**Comment by kazu-yamamoto** [comment]
Cabal 1.22.1.1 fixes the problem. Thank you for your efforts, guys!
