### ISSUE TITLE
cabal init: if PublicDomain is selected, License and Copyright fields should not be generated

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2380]
self explanatory

**Comment by byorgey** [comment]
@ezyang Can you clarify a bit?  In particular, by what mechanism should it be conveyed that a package is in the public domain, if not by the License field?  Although I do realize that technically speaking, a work in the public domain is not under any license.

Agree about not generating a copyright field.

**Comment by byorgey** [comment]
Perhaps you meant that a License-file field should not be generated?

**Comment by byorgey** [comment]
@dcoutts does Hackage allow uploads of packages with no License-file field?

**Comment by ezyang** [comment]
Yeah, referring to the license-file field.

**Comment by BardurArantsson** [comment]
Is there any reason this isn't a pull request yet?

**Comment by byorgey** [comment]
@BardurArantsson , good question.  It looks like I started working on it but never quite finished.  There's some formatting I want to clean up first.  I'll try to get to it soon.

**Comment by BardurArantsson** [comment]
(I know this is belated, but I was "out of commission" for while...)

Thank you very much for the pull request :).
