### ISSUE TITLE
cabal update uses a ridiculous amount of memory

### ISSUE THREAD

**Issue by accursoft** [haskell/cabal#2396]
`cabal update` uses 500-600Mb on my system, causing builds to fail completely on small virtual servers.

Memory usage sky-rockets after `Updating the index cache file...`, so I'm guessing that something in `Distribution.Client.IndexUtils.updatePackageIndexCacheFile` is constructing the entire package list in memory.

**Comment by accursoft** [comment]
Found 2 other reports of this:
http://stackoverflow.com/questions/20769183/cabal-update-failed-due-to-out-of-memory
http://stackoverflow.com/questions/26899426/cabal-update-failure-return-code-9

**Comment by mietek** [comment]
Seconded.  `cabal update` can fail on machines with “only” 512MB RAM.

**Comment by aBathologist** [comment]
I'm stuck in the same spot.

**Comment by ttuegel** [comment]
Probably related to #1164.

**Comment by accursoft** [comment]
Probably not related, as this occurs after the package list has been downloaded, and doesn't involve the network at all.

**Comment by sznurek** [comment]
I've implemented somewhat hacky fix for this bug: https://github.com/sznurek/cabal/commit/fbf2298e0397e05e340989903c379491b7d3b74e - the memory usage is now less that 0.5MB.

If somebody could take a look at it to check if this solution is acceptable I will be happy to finish it.

**Comment by sznurek** [comment]
@ttuegel: Just as a reminder, I'm still happy to help with this issue if it's still needed.

**Comment by ttuegel** [comment]
@sznurek Can you make a pull request for that commit? And maybe describe in the commit message what it's doing? It's not clear to me what the fix is, exactly.

**Comment by sznurek** [comment]
@ttuegel Opened PR #2826.

**Comment by gbaz** [comment]
@mcandre this ticket was specifically about an issue in the `update` network operation. Typically when there is a memory issue in building that is either a ghc issue or a linker issue, not a cabal issue. Have you been able to narrow this down to cabal per-se?
