### ISSUE TITLE
Making a flag default based on ghc version

### ISSUE THREAD

**Issue by ethercrow** [haskell/cabal#2397]
yi depends on hint, which is not updated for ghc 7.10 yet, so I've tried the following in yi.cabal:

```
flag hint
  if impl(ghc >= 7.10.1)
    Default: False
  else
    Default: True
  Description: Include hint (haskell interpreter) in yi
```

but got

```
cabal: 'parseField' called on a non-field. This is possibly a bug in Cabal.
Please report it to the developers: https://github.com/haskell/cabal/issues/new
```

Is it a bug in cabal or is it illegal to place Default field under conditional?

**Comment by grayjay** [comment]
See #2429 for another example of how conditionals in flag definitions could be used.

**Comment by grayjay** [comment]
Closing in favor of #5328, which would allow setting the flag default based on GHC version.
