### ISSUE TITLE
Cabal sandbox being able to depend on another sandbox/package list

### ISSUE THREAD

**Issue by taksuyu** [haskell/cabal#2402]
So say I have a cabal sandbox in my home directory. This sandbox can or cannot depend on my global directory to which I have chosen a stable path managed by a package manager. This works well with haskell utilities like the base version of cabal-install.

My home directory sandbox which doesn't have to depend on the global package list can be used as a psuedo package list that I want to build other packages off of, in the case of a more volatile dependancy tree that is more up to date.

While this can result in a bit more headache with managing dependencies, with careful curation, a person could benefit from reducing the relatively standard use libraries from propagating throughout sandboxes.

Possibly it shouldn't be treated as a sandbox since it's more like a package list, but I wanted to know how feasible something like this would be or if there is anyway to achieve it currently.

**Comment by phadej** [comment]
sandbox functionality is removed.
