### ISSUE TITLE
hoogle: True in ~/cabal/config doesn't do anything for me

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#2406]
I'm using cabal 1.22. In https://github.com/haskell/cabal/pull/1707 `hoogle: True` was added. In `~/cabal/config`:

```
haddock
  -- keep-temp-files: False
  hoogle: True
  -- html: False
```

But when I run `cabal haddock -v2`, I see that the `--hoogle` flag is not passed to haddock. It is used only when I explicitly pass it via `cabal haddock --hoogle -v2`.

Could you check if that config setting is really used?

Thanks!

**Comment by jneira** [comment]
Hi, i've tried to reproduce the issue with lastest cabal and setting `hoogle: True` in the global config and with `cabal haddock -v3` i've got

```
["haddock","--verbose=2","--builddir=D:\\dev\\ws\\haskell\\cabal-test\\dist-newstyle\\build\\x86_64-windows\\ghc-8.10.7\\cabal-test-0.1.0.0","--hoogle","lib:cabal-test"]
```

so i am gonna close optimistically the issue, feel free to reopen if you continue experiencing the issue
