### ISSUE TITLE
Cabal passes --enable-profiling to older setup-exe when using jobs > 1

### ISSUE THREAD

**Issue by hesselink** [haskell/cabal#2409]
This might be related to #2394: when using the latest 1.22 HEAD (3c0e6480d5057dd616457a0ac0458e60946c9849) I get an error when compiling with jobs > 1:

```
unrecognized 'configure' option `--disable-profiling'
```

With a build from 6 commits earlier this didn't happen, so it seems likely that #2394 is the culprit. Compiling with `-v` shows this (edited):

```
/Users/erik/.cabal/bin/cabal --config-file=<config-file> install --verbose=2 --force-reinstalls --disable-library-profiling --disable-executable-profiling --disable-documentation --disable-library-coverage --disable-benchmarks
<snip>
/Users/erik/.cabal/setup-exe-cache/setup-Simple-Cabal-1.20.0.3-x86_64-osx-ghc-7.8.3
configure --verbose=2 --ghc
<snip>
--disable-library-profiling --disable-profiling --disable-executable-profiling
```

So somehow the `--disable-profiling` flag got added. The `--disable-coverage` flag isn't in there, btw.

**Comment by hesselink** [comment]
I've just verified that reverting 25f7f9a1389686e3d5083ab36fa90f59ccaa2652 fixes this.

**Comment by hesselink** [comment]
Any update on this @ttuegel (or anyone else)? This worked before, and it would be nice if there was a fix in the final released version with GHC 7.10.

**Comment by 23Skidoo** [comment]
I'm trying to reproduce, but it seems to work fine so far.

**Comment by 23Skidoo** [comment]
Trying with Cabal-1.20.0.3 now...

**Comment by 23Skidoo** [comment]
`cabal-install` 1.23 seems to work fine with both 1.18 and 1.20. Will try with 1.22 now...

**Comment by 23Skidoo** [comment]
Hmm, I think I see what is causing this bug:

```
filterConfigureFlags flags cabalLibVersion
| cabalLibVersion >= Version [1,19,2] [] = flags_latest
...
| cabalLibVersion < Version [1,21,1] [] = flags_1_20_0
```

Here, is the version is 1.20, we always use `flags_latest` instead of `flags_1_20_0`, as @ttuegel intended.

**Comment by 23Skidoo** [comment]
OK, managed to reproduce. You need to pass `--disable-profiling` to `cabal install` to trigger this.

**Comment by ttuegel** [comment]
@23Skidoo If fixing the version bounds in those guards doesn't fix it, I think you might be able to fix it by switching the order of the `profiling` and `executable-profiling` flags in [`Distribution.Simple.Setup`](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Setup.hs#L462). But, you will also need to use `flags_1_20_0` for all versions, and Cabal >= 1.22 users will get a harmless warning.

This is fixed properly in master, I just couldn't fix properly here without breaking PVP.

**Comment by 23Skidoo** [comment]
So there seem to be two bugs: the aforementioned wrong version check and the lack of the `configProf` field on 1.22, which means that when a user passes `--{enable,disable}-executable-profiling`, the setup script is passed `--{enable,disable}-profiling`.

**Comment by 23Skidoo** [comment]
@ttuegel I've now fixed this on master. Re:1.22, what if I bump the Cabal version to, say, 1.22.2.0, make `cabal-install` depend on `> 1.22.2` and add back the `configProf` field?

**Comment by 23Skidoo** [comment]
Wrong version check fixed in fdae633cc97100831d35b3963eedbfc91e94d169.

**Comment by ttuegel** [comment]
Changing type definitions requires a major version bump, to 1.24, because it will break every previous cabal-install release in the 1.22 branch.

**Comment by 23Skidoo** [comment]
Hmm, but surely if I add a `configProf` field and leave `configProfExe` and `configProfLib`, old cabal-install will still compile?

Then I could change the definition in `Setup.hs` to:

```      
,option "" ["profiling"]
         "Executable profiling (requires library profiling)"
         configProf (\v flags -> flags { configProfLib = v, configProfExe = v, configProf = v })
         (boolOpt [] [])
```

and set `configProf` to NoFlag in `flags_1_20_0`.

**Comment by 23Skidoo** [comment]
Changing the order of definitions doesn't seem to help.

**Comment by ttuegel** [comment]
See #2389. Old cabal-install will build, but fail at runtime due to the missing field.

**Comment by 23Skidoo** [comment]
I see, we're using `ConfigFlags {` instead of `mempty {` somewhere.

**Comment by 23Skidoo** [comment]
OK, I came up with a hack that fixes this on 1.22. See #2482.

**Comment by ttuegel** [comment]
@23Skidoo Thanks for fixing! Looking at your solution, I'm suddenly very sorry I didn't just fix it correctly in the first place. At least the hack will not live on in master!

**Comment by hesselink** [comment]
Thanks for fixing this! I've just tested building our entire stack any found no problems anymore.

**Comment by bergmark** [comment]
Thanks a bunch!
