### ISSUE TITLE
Handle Protocol Buffers

### ISSUE THREAD

**Issue by rfn01** [haskell/cabal#2411]
It would be cool to have builtin support for hprotoc, similar to the existing happy or alex support.  Or, perhaps, an easy way to specify such dependancies.

Thanks!

**Comment by BardurArantsson** [comment]
"No. Implement a custom Setup.hs."... I think is the answer to that?

**Comment by jneira** [comment]
@rfn01 not sure if you continue being interested in add hprotoc support after those years 🙂 
otoh the project does not seem very active lately

related issues:
* extended preprocessors support: https://github.com/haskell/cabal/issues/6232
* support bnfc: https://github.com/haskell/cabal/issues/6232

**Comment by jneira** [comment]
Thanks, as we have an issue for generic preprocessor support i guess we can close this one
