### ISSUE TITLE
Unclear prompt in 'cabal init'

### ISSUE THREAD

**Issue by joecrayne** [haskell/cabal#2413]
I needed to ask an IRC channel to figure out what this prompt from cabal init means:

> Include documentation on what each field means (y/n)? [default: n]

I thought it might have something to do with haddock.  It was suggested, and I strongly agree that the following would be a better phrasing:

> Add informative comments to cabal file (y/n)? [default: n]

**Comment by lspitzner** [comment]
what, i am not able to do evil rebases and force pushes without unintentionally spamming referenced issues? meh.. ok, i reluctantly refrain from doing another commit-message-rewording.

**Comment by byorgey** [comment]
This seems like a great idea to me.  @lspitzner, if you create a pull request I will be happy to merge it.

**Comment by lspitzner** [comment]
fixed via #2416 (specifically, c04cc8c6fe3374e95064cb36805f217f07a90fef)
