### ISSUE TITLE
Cabal fails to parse Windows proxy string.

### ISSUE THREAD

**Issue by Prillan** [haskell/cabal#2424]
My proxy settings are set to the following in Windows:
    
    Type   Proxy address to use  Port      
    HTTP   127.0.0.1             3213
    HTTPS  127.0.0.1             3213
    FTP    <empty>               <empty>
    SOCKS  <empty>               <empty>

Which leads to the following error using `cabal`

    Invalid http proxy uri: "http=127.0.0.1:3213;https=127.0.0.1:3213"
    proxy uri must be http with a hostname
    ignoring http proxy, trying a direct connection

The error message comes from `Network.HTTP.Proxy.fetchProxy`.

**Comment by 23Skidoo** [comment]
> The error message comes from `Network.HTTP.Proxy.fetchProxy`.

Then this is a HTTP library issue. Please [file a ticket a their bug tracker](https://github.com/haskell/HTTP/issues/new).

**Comment by Prillan** [comment]
Isn't it up to `cabal` to send the appropriate proxy string to the HTTP library? Otherwise, why would it read the Windows proxy setting if it doesn't care about it? To me this sounds like a `cabal` issue.
