### ISSUE TITLE
misleading hint in error message(s): Use 'sandbox hc-pkg -- unregister'

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#2425]
E.g., 

```
cabal sandbox delete-source foobar
Note: ...
Use 'sandbox hc-pkg -- unregister' to do that.
```

but actually the command to use is `cabal sandbox hc-pkg -- unregister`.

**Comment by lspitzner** [comment]
it is meant as "use the subcommand \`sandbox ..."

devs: afaik, we try to keep the program name (`cabal`) exchangable, but we do not forward it to the function that produces the above output. should we
a) just reword to "use the sub-command \`sandbox.."
b) hard-code "cabal"
c) pass progName around? (or whatever it is called)

**Comment by gbaz** [comment]
obsoleted by removal of sandboxes
