### ISSUE TITLE
"cabal update" is blocked by IWSS of TrendMicro. Is Exceed_File_Count_Limit.

### ISSUE THREAD

**Issue by murat-to** [haskell/cabal#2426]
It might be that such of to say to Trend Micro.
But, Please I wish considered for whether.

---
IWSS Security Event 
InterScan Web Security detected the following in HTTP traffic:

Item: http://hdiff.luite.com/packages/archive/00-index.tar.gz
Action: deleted
Reason: Violation of a compressed file restriction

-- File: 00-index.tar.gz, security warning: Exceed_File_Count_Limit
The uncleanable file is deleted.

**Comment by 23Skidoo** [comment]
> `-- File: 00-index.tar.gz, security warning: Exceed_File_Count_Limit`

Well, I'm not sure how we could work around this in Cabal. Perhaps we should a note to the FAQ.

**Comment by murat-to** [comment]
Thank you for answer.
>I'm not sure how we could work around this in Cabal.
Yes, I'm so think too.
Misplaced issue post, Please pardon.
