### ISSUE TITLE
cabal test doesn't care about changes to dependency bounds

### ISSUE THREAD

**Issue by chreekat** [haskell/cabal#2430]
I apologize in advance for what may a rather nebulous issue. Here are the steps I took:

1. Do a fresh `cabal install --enable-tests --only-dep` in a sandbox.
2. Run `cabal test`. Everything works.
2. Put an upper bound on a dependency that cannot work. (Specifically, "yesod-test < 1.4.3" when 1.4.3.1 was installed.)
3. Run cabal test.

What I expected next was some sort of reconfigure and then complaint about a wrong version of yesod-test. Instead, cabal test runs fine, with no complaints.

Is that to be expected?

**Comment by ttuegel** [comment]
Probably what happens is: cabal tries to reconfigure, but that fails. That failure is not treated as fatal because the package was previously configured, and the previous configuration is just reused.

**Comment by ezyang** [comment]
Given that (1) this bug doesn't actually cause any problems (just minor confusion) and (2) we're going to replace the old configure interface with Nix-local build, I am going to close this. If this is really killing someone please reopen.
