### ISSUE TITLE
`cabal test` fails if the package is of type `Configure`

### ISSUE THREAD

**Issue by Rufflewind** [haskell/cabal#2431]
Minimal example:

```sh
mkdir cabtest
cd cabtest

cat >configure.ac <<EOF
AC_INIT([Foobar], [1.0], [], [foobar])
AC_OUTPUT
EOF

cat >cabtest.cabal <<EOF
name: cabtest
version: 0.0.0
build-type: Configure
cabal-version: >=1.10
library
  default-language: Haskell98
  build-depends: base
test-suite foobar
  default-language: Haskell2010
  main-is: test.hs
  type: exitcode-stdio-1.0
  build-depends: base
EOF

autoreconf
cabal test
```

On the very last line, `cabal test` will cause the following error:

    cabal: Unrecognised flags: foobar

This does not occur if `build-type` is `Simple`.

(GHC 7.8.4, Cabal 1.22.0.0, cabal-install 1.22.0.0, Linux 3.18.6-1-ARCH.)

**Comment by ttuegel** [comment]
It's likely this is just #2427.

**Comment by ttuegel** [comment]
Disregard my last comment, this is *actually* #2375. I'm closing this issue in favor of the original report.
