### ISSUE TITLE
cabal should not repeatedly preprocess executables

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2432]
Steps to reproduce:

1. Make a cabal file with a bunch of executables
2. cabal install
3. Edit source file of one executable
4. cabal install

Expected behavior: just the edited source file re-preprocesses.

Actual behavior: all executables preprocess

The preprocessing step is kind of slow, so it would be really good if we could avoid it.

**Comment by tibbe** [comment]
Does the same happen if you use cabal build?

**Comment by ezyang** [comment]
Yes.

**Comment by kolmodin** [comment]
For me, it's not even required to edit the files. All files that has a preprocessor will be preprocessed at each `cabal build`, even if nothing has changed.

```
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library
```

Also, a related issue, all executables are re-linked, even if nothing changes. If I run `cabal build` twice, all files will be preprocessed twice, and all executables linked twice.

**Comment by ezyang** [comment]
I'm closing this in favor of #3662, with a per-component configure you'll only preprocess the executable if you actually try to build it.
