### ISSUE TITLE
Cabal-1.22 keyed filepaths truncate library name and hide version

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#2437]
With current Cabal-1.22, library paths are now of the form:

    /usr/lib64/ghc-7.10.0.20141222/direc_3m6Ew9I164U5MIkATLCdb8/libHSdirec_3m6Ew9I164U5MIkATLCdb8-ghc7.10.0.20141222.so

Is the 5 character truncation of package names (and no version) necessary?
It makes it pretty hard to see at a glance what package a particular directory or file belongs to and seems there is no easy way to work out the package version without referring to the package.conf file/dir.

If possible I would prefer a filepath format like:

    /usr/lib64/ghc-7.10.0.20141222/directory-1.2.1.1_3m6Ew9I164U5MIkATLCdb8/libHSdirectory-1.2.1.1_3m6Ew9I164U5MIkATLCdb8-ghc7.10.0.20141222.so

**Comment by juhp** [comment]
Edward Zang explained some of the rationale on the mailing-list:

> The motivation for truncating the names and version was to keep symbol name sizes manageable even with the addition of the hash, while giving at least some hint when working with the symbols directly.  It doesn't seem that this rationale applies for library names, so it's possible we could separate these (in any case, only the hash really matters: the package name/version are included in the hash), but we'd have to figure out where in the current codebase makes assumptions about this.

**Comment by juhp** [comment]
Perhaps the key hash which is repeated in the filepath could be somewhat truncated too to shorten it??

**Comment by tibbe** [comment]
I think it's pretty unsatisfying that the library name and version is not there. @ezyang can we do something about it?

**Comment by ezyang** [comment]
Snowed in with ICFP deadline, but afterwards I can take a look and see if I can suss out where these assumptions are made.

**Comment by ezyang** [comment]
Still validating, but looks like it was an easy fix.

**Comment by juhp** [comment]
Thanks a lot for this @ezyang  - looks good - looking forward to test it later. :)

**Comment by juhp** [comment]
With ghc-7.10.1 it now looks like this:

```
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/System/Directory.dyn_hi
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/System/Directory.hi
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/include/HsDirectory.h
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/include/HsDirectoryConfig.h
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/libHSdirectory-1.2.2.0-3TcTyYedch32o1zTH2MR00-ghc7.10.1.so
   /usr/lib/ghc-7.10.1/direc_3TcTyYedch32o1zTH2MR00/libHSdirectory-1.2.2.0-3TcTyYedch32o1zTH2MR00.a
```

**Comment by ezyang** [comment]
Oh, hmm, I guess we missed a spot

**Comment by juhp** [comment]
Maybe truncating the hash in the filepaths (git style) would help also for the Windows file-length limitation?

**Comment by ezyang** [comment]
Figured it out. This is a GHC bug, so I'm going to reclose this issue.

**Comment by ezyang** [comment]
Actually, it touches some Cabal code too.

**Comment by juhp** [comment]
Thanks!

Any chance of this landing in ghc-7.10.2?

**Comment by ezyang** [comment]
We'd have to backport the Cabal and GHC changes. I'll leave this decision to the release managers.

**Comment by 23Skidoo** [comment]
I'd like to see this and a fix for #2502 in GHC 7.10.2.

**Comment by juhp** [comment]
Okay I finally tested building with ghc-7.10.2.
Cabal installs of packages look good, but builds of ghc itself still seem to have truncated package dirnames.
Maybe I am missing a ghc patch or some config?

**Comment by ezyang** [comment]
No, GHC has to be updated to run a version of Cabal which has this fix.

**Comment by juhp** [comment]
Ah, is this expected behaviour:

```
$ rm -rf dist
$ ./Setup configure --user
$ ./Setup build
$ ./Setup install     # (installs to `<packa-hash>`)
$ rm -rf dist
$ ./Setup configure --user --libsubdir='$compiler/$pkgid'
$ ./Setup build
$ ./Setup install     # (installs to `<package-version>`)
$ ./Setup configure --user
$ ./Setup build
$ ./Setup install     # (installs to `<package-version-hash>`)
```

For Fedora builds I configure with `--libsubdir='$compiler/$pkgid'` after which
`(./Setup configure --user ...; ./Setup install)` installs into <package-version-hash>,
which lead me to conclude incorrectly that 1.22.4.0 was working...
