### ISSUE TITLE
Could not update cabal to 1.22.0.1

### ISSUE THREAD

**Issue by m3nthal** [haskell/cabal#2440]
After installing HaskellPlatform-2014.2.0.0-x86_64-setup.exe

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\User>cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library

C:\Users\User>cabal update
Config file path source is default config file.
Config file C:\Users\User\AppData\Roaming\cabal\config not found.
Writing default configuration to C:\Users\User\AppData\Roaming\cabal\config
Downloading the latest package list from hackage.haskell.org
Note: there is a new version of cabal-install available.
To upgrade, run: cabal install cabal-install

C:\Users\User>cabal install cabal-install
Resolving dependencies...
Downloading cabal-install-1.22.0.1...
Configuring cabal-install-1.22.0.1...
Building cabal-install-1.22.0.1...
Failed to install cabal-install-1.22.0.1
Last 10 lines of the build log ( C:\Users\User\AppData\Roaming\cabal\logs\cabal-
install-1.22.0.1.log ):
    Could not find module `Distribution.Verbosity'
    There are files missing in the `Cabal-1.22.1.1' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

Main.hs:142:8:
    Could not find module `Distribution.Version'
    There are files missing in the `Cabal-1.22.1.1' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
cabal-install-1.22.0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by 23Skidoo** [comment]
> ```
Main.hs:142:8:
Could not find module Distribution.Version' There are files missing in theCabal-1.22.1.1' package,
try running 'ghc-pkg check'.
```

Looks like your installation is borked somehow. Uninstall HP, delete `%APPDATA%/{ghc,cabal}`, reinstall HP.
