### ISSUE TITLE
Optimizations specified on the command line with -O should override the .cabal file

### ISSUE THREAD

**Issue by mightybyte** [haskell/cabal#2443]
Currently -O ghc-options specified in the .cabal file override anything specified on the command line.  I believe this is backwards.  The .cabal file should be used when nothing is specified on the command line, but the command line should override it.  This is necessary for a proper solution to #2442.

**Comment by bitemyapp** [comment]
Tend to agree, command-line arguments are a more direct assertion of intent than config files.

(+1)

**Comment by ttuegel** [comment]
This should be true of all the command-line arguments. I suspect that `-O` is being lumped in with all the other Cabal-generated options to GHC, but the proper order should be
1. Cabal generated
2. cabal.config
3. command-line `--ghc-options`
4. command-line `-O`, `-prof`, `-fhpc`, etc.
(assuming GHC takes the *last* `-O` option specified).

**Comment by dcoutts** [comment]
I agree, the command line should override what is specified in the .cabal file. So e.g. people can have -O2 in the .cabal file but `cabal configure -O0` should nevertheless do the right thing. Note that it means we'll need to make sure that not specifying any -O setting to cabal configure passes nothing to ghc, or we'll always override.

**Comment by mkawalec** [comment]
We've looked into it during Zurihac with @kosmikus and it seems that the options are passed to GHC in correct order ie. the command line options comes after the .cabal file one. Furthermore GHC seems to behave according to the last -O option specified.

Has this been fixed in the meantime?

**Comment by ttuegel** [comment]
Have you also checked the behavior with respect to the cabal.config file? It's possible that's what the original poster meant (and we should check it while we're at it).

**Comment by ulysses4ever** [comment]
I checked the problem as stated in the title ("Optimizations specified on the command line with -O should override the .cabal file"), and it no longer exists: command-line `--ghc-options -O2` does override the option given in the `.cabal` file. I think this issue can be closed. 

As for behavior w.r.t. the cabal `config` file, it is weird: the `config` file seems to take priority before both `.cabal` file and command line. At lerast w.r.t. the `-O` option. If anyone concerned about that, they could open another ticket. But I doubt many people specify `-ON` in the `config` file...

**Comment by Mikolaj** [comment]
I agree that we should call success and close. I seem to remember `--disable-optimization` and `--enable optimization` also override .cabal file fine. Closing.
