### ISSUE TITLE
--package-db flag ignored in sandbox mode

### ISSUE THREAD

**Issue by dcoutts** [haskell/cabal#2453]
We were documenting the --package-db flag #2416, and noticed that it doesn't have any effect in sandbox mode. The expected behaviour is that `--package-db` always appends, and in a sandbox case the only difference is that the initial list of package dbs is [global, sandbox]. But `--package-db` on the command line should always append to that list.

See also #2344

**Comment by phadej** [comment]
sandbox functionality is removed.
