### ISSUE TITLE
Issue #2320 needs some extra love for GHCJS

### ISSUE THREAD

**Issue by cstrahan** [haskell/cabal#2454]
It appears that the fix in #2320 has a bug: [this line](https://github.com/haskell/cabal/commit/3c0e6480d5057dd616457a0ac0458e60946c9849#diff-75fc8741c2032b36ae984f51c98f4bcfR882) will always return ~~false~~ true, because GHCJS's version is `0.1.0`.

cc @luite

**Comment by cstrahan** [comment]
cc @ryantrinkle, who's [work](https://github.com/ryantrinkle/nixpkgs/commit/c5417bc792b22346f58b116f1aa007bcfcb02505#diff-af05908910d18fe98daec59bb3bedcadR13) originally brought this to my attention.

**Comment by luite** [comment]
`ghcjs-pkg` follows `ghc-pkg` for the version numbering (to avoid the complexity of the approach for the `ghcjs` executable which has to be queried for both the ghcjs and the ghc version).

can you give an example where this goes wrong for ghcjs?

**Comment by ryantrinkle** [comment]
Specifically see this line: https://github.com/ryantrinkle/nixpkgs/commit/c5417bc792b22346f58b116f1aa007bcfcb02505#diff-af05908910d18fe98daec59bb3bedcadR35

I set the value to constantly false rather than checking the version number, because False is correct for *all* versions of GHCJS (from what I can tell).

**Comment by luite** [comment]
GHCJS supports the package database types that the underlying GHC supports. When built against GHC 7.8, `ghcjs-pkg` is a modified ghc 7.8 `ghc-pkg`, for ghc 7.10 it's based on a 7.10 `ghc-pkg`.

If the single DB is only kept for backwards compatibility, then we can always disable it, otherwise it should be ok to enable it for 7.8 based builds (unless i'm missing something here)

**Comment by cstrahan** [comment]
@luite: I'm rebuilding GHCJS against 7.10.1-rc3, and I'm still getting the

> ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.

error when compiling `integer-gmp`.

I'm currently rebuilding GHC with:

    sed -i 's/HcPkg.useSingleFileDb = .*/HcPkg.useSingleFileDb = False/' libraries/Cabal/Cabal/Distribution/Simple/GHCJS.hs

If GHCJS then compiles successfully, I would presume there's some problem either in GHCJS or in Cabal, but I wouldn't know which.

When the build terminates, I'll let you know if it was successful.

--------

P.S. Work continues in Nixpkgs to get GHCJS ready for GHC 7.10: https://github.com/NixOS/nixpkgs/pull/6786

**Comment by cstrahan** [comment]
@luite: The aforementioned modification in `Cabal/Distribution/Simple/GHCJS.hs` lets the GHCJS build continue (it fails for unrelated reasons, though; I'll mention those through some other channel).

The GHC release is coming up soon, and I'd hate to see a bug make its way into the release. Could I help you diagnose this, perhaps?

**Comment by luite** [comment]
Ah I think I found the problem. I was stupidly assuming that the ghcjsPkgProgram version check was using `--version`, but it's using `--ghcjs-version`:

https://github.com/haskell/cabal/blob/72e908c12341fe34ebcbf84814f08ec25ee4e420/Cabal/Distribution/Simple/Program/Builtin.hs#L144

I think we can make it use the GHC version instead (switching to `--version`), since I don't think anything else is using the version... but it's still a bit hacky. Can you check if changing that line in `Distribution.Simple.Program.Builtin` helps, and find if the ghcjs-pkg version is used anywhere else?

**Comment by cstrahan** [comment]
@luite: I tried your suggestion, but that results in this error when building GHCJS:

    /nix/store/5is7pgfrsar7q7m6sqacwkrqsvj9qyiw-cabal-install-1.22.0.1/bin/cabal --config-file /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/share/ghcjs/x86_64-linux-0.1.0-7.10.0.20150316/ghcjs/cabalBootConfig install ./boot/ghc-prim --solver=topdown --configure-option=--with-gmp-includes=/nix/store/pbzgy470imzf1lyjqz70j744n98f8j47-gmp-5.1.3/include '--configure-option=--with-gmp-libraries=  /nix/store/pbzgy470imzf1lyjqz70j744n98f8j47-gmp-5.1.3/lib' --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs --with-gcc /nix/store/qsl51gm9qcwngdsl6myg9gx8sq51skdm-gcc-wrapper-4.8.4/bin/cc --with-hc-pkg /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs-pkg --prefix /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0 --libdir $prefix/lib/$compiler --libsubdir $pkgid --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/share/ghcjs/x86_64-linux-0.1.0-7.10.0.20150316/ghcjs/run.sh -v2 --dry-run
    cabal: Version mismatch between ghcjs and ghcjs-pkg:
    /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs is version
    0.1.0 /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs-pkg is
    version 7.10.0.20150316
    ghcjs-boot: error running: /nix/store/5is7pgfrsar7q7m6sqacwkrqsvj9qyiw-cabal-install-1.22.0.1/bin/cabal --config-file /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/share/ghcjs/x86_64-linux-0.1.0-7.10.0.20150316/ghcjs/cabalBootConfig install ./boot/ghc-prim --solver=topdown --configure-option=--with-gmp-includes=/nix/store/pbzgy470imzf1lyjqz70j744n98f8j47-gmp-5.1.3/include '--configure-option=--with-gmp-libraries=  /nix/store/pbzgy470imzf1lyjqz70j744n98f8j47-gmp-5.1.3/lib' --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs --with-gcc /nix/store/qsl51gm9qcwngdsl6myg9gx8sq51skdm-gcc-wrapper-4.8.4/bin/cc --with-hc-pkg /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs-pkg --prefix /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0 --libdir $prefix/lib/$compiler --libsubdir $pkgid --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/share/ghcjs/x86_64-linux-0.1.0-7.10.0.20150316/ghcjs/run.sh -v2 --dry-run
    exit status: 1
    stderr: cabal: Version mismatch between ghcjs and ghcjs-pkg:
    /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs is version
    0.1.0 /nix/store/zanziikamkawq7mpcxxbnd0vnv3n1bvh-ghcjs-0.1.0/bin/ghcjs-pkg is
    version 7.10.0.20150316

**Comment by luite** [comment]
Ah makes sense, Cabal does check the version when configuring and it now compares against the wrong one

**Comment by luite** [comment]
pushed a fix to master and cherry picked to 1.22, unfortunately too late for the 1.22.2.0 release...

**Comment by 23Skidoo** [comment]
Fixed by 975fc46e0055a9f9b434d594569a18eaa0ef0320.

**Comment by 23Skidoo** [comment]
@luite Next time you push a fix to some open issue, please add "Fixes #TICKETNO." to the commit message body.
