### ISSUE TITLE
GHC 7.10 HPC test failures

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2457]
Quite a lot of tests are [failing on Travis with GHC HEAD right now](https://travis-ci.org/haskell/cabal/jobs/53405779) with an error message that looks like:

```
PackageTests/TestSuiteExeV10/dist-WithHpc-LibProfExeProfExeDynShared/hpc/prof/mix/my-0.1/my-0.1/Foo.mix should exist
```

@ttuegel, can you please take a look?

**Comment by ttuegel** [comment]
Looks like GHC stopped respecting the `-hpcdir` option. I will double-check locally once I get GHC HEAD installed and file a bug with GHC if needed. This only affects HEAD and not the 7.10 branch, right? With the upcoming release, would it be possible to get a 7.10 branch test?

**Comment by 23Skidoo** [comment]
Updated `travis.yml` to also run tests with GHC 7.10.1 snapshot.

**Comment by 23Skidoo** [comment]
Looks like we'll have to wait until someone uploads a patched version of `ansi-wl-pprint`.

**Comment by ddssff** [comment]
You can add something like this to the travis install: section:

    - travis_retry git clone https://github.com/hvr/ansi-wl-pprint
    - cabal install ./ansi-wl-pprint

**Comment by 23Skidoo** [comment]
@ddssff Thanks, that worked.

**Comment by 23Skidoo** [comment]
@ttuegel Looks like [this also happens with 7.10](https://travis-ci.org/haskell/cabal/jobs/53712734).

**Comment by ddssff** [comment]
@23Skidoo it looks like version 0.6.7.1 of ansi-wl-pprint from hackage is replacing hvr's patched version from github, which is still at 0.6.7.  I created a fork in https://github.com/seereason/ansi-wl-pprint with the newer version number and made a pull request.

Hackage is becoming kind of a mess...

**Comment by ttuegel** [comment]
I cannot work on this currently because Cabal won't build with GHC HEAD. Looks like something to do with the last-minute changes to AMP.

**Comment by 23Skidoo** [comment]
@ttuegel Which error are you getting?

**Comment by ttuegel** [comment]
```
[41 of 79] Compiling Distribution.Simple.Program.Db ( Distribution/Simple/Program/Db.hs, dist/setup/Distribution/Simple/Program/Db.o )

Distribution/Simple/Program/Db.hs:470:28:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Prelude)
```

**Comment by 23Skidoo** [comment]
@ttuegel You are using an old snapshot of GHC HEAD that doesn't have `<$>` in the Prelude.

**Comment by ttuegel** [comment]
Right, thanks. I don't know why I thought NixOS's ghc-HEAD build would be up to date.

**Comment by ttuegel** [comment]
Looks like GHC >= 7.10 puts the module interfaces in `$hpcdir/mix/$name-$version/$key` now. I need to adjust the test according to GHC version.
