### ISSUE TITLE
Add an option to delete all sources from a sandbox

### ISSUE THREAD

**Issue by danclien** [haskell/cabal#2458]
Any one have thoughts on adding a `cabal sandbox delete-all-sources` or `cabal sandbox delete-sources` that removes all sources from the sandbox?

On the random occasion I move or rename one of my source directories, it's easier for me to script  deleting all the sources and adding all of them back in (using `bash`) than manually doing `delete-source`  and `add-source`.

I would rather have the functionality to delete all the sources built into `cabal` since my `bash` script is brittle due to parsing `cabal sandbox list-sources`'s output. I'm willing to attempt a PR.

**Comment by lspitzner** [comment]
makes sense. for now you might get the desired effect by doing some manual

~~~~
rm -r .cabal-sandbox/packages
cabal sandbox init
~~~~

which should delete the add-sources, but leave the installed packages. no guaranties, though :)

**Comment by BardurArantsson** [comment]
AFAICT this would be somewhat at odds with #2631 in that we surely don't want to add even more ways to mutate the state of sandboxes -- thus making for even more edge cases, etc. It seems to me that #2631 is moving towards a less stateful model where Cabal will itself pick up whatever sources you have and "do the right thing"(TM).

**Comment by BardurArantsson** [comment]
... therefore I suggest this be closed as "WONTFIX".

**Comment by phadej** [comment]
sandbox functionality is removed.
