### ISSUE TITLE
cabal sdist doesn't include cabal.config file with freezed versions

### ISSUE THREAD

**Issue by varosi** [haskell/cabal#2463]
cabal 1.20.x

I would like to freeze my versions for more consistent and easier distribution with:
cabal freeze
cabal sdist

but the second line will not keep cabal.config into archive.
Is it possible to add a possibility for that?

**Comment by 23Skidoo** [comment]
`cabal.config` is not supposed to be distributed with the tarball. Even if you did that (e.g. with `extra-source-files`), `cabal install`ing such a package would ignore settings from the bundled `cabal.config`. Adding it to the Git repo makes sense, though.
