### ISSUE TITLE
ignoring sandboxes is not possible

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2464]
(re-issue #2333)

`ignore-sandbox` config value seems to have no effect; also there is no commandline flag for ignoring a sandbox (or it is not documented).

**Comment by lspitzner** [comment]
btw i do not need this feature, and would give it fairly low priority, if any. it is mentioned in the users-manual, though.

labels = S.fromList ["sandbox"]

**Comment by phadej** [comment]
sandbox functionality is removed.
