### ISSUE TITLE
Add cabal-install flag to build project in a sandbox, but install normally

### ISSUE THREAD

**Issue by Hrothen** [haskell/cabal#2473]
Currently there are a whole bunch of workarounds people use to safely build binaries in a sandbox but access them everywhere, the most common being to add the sandbox itself to the PATH, make a symlink to the binary in the sandbox, or move the binary to /usr/bin.

The first two methods generally work, but you end up with a bunch of sandboxes taking up space. Moving the binary lets you delete the sandbox, but won't work if the program installed data files. In all cases we need to do a lot more work than just typing `cabal install foo`. New users who are unaware of these problems end up globally installing programs (which most tutorials still instruct you to do) and end up in cabal hell despite otherwise using sandboxes.

So I propose a flag (something like `--sandboxed-build`) that instructs cabal to create a temporary sandbox and build the package in it, but then actually install the binary and data files wherever it's configured to with a normal `cabal install`, as well as providing those paths via the `Paths_` module. This would probably still not work for packages with a custom Setup.hs, but would be sufficient for the vast majority of programs.

**Comment by lspitzner** [comment]
Note that there is https://github.com/quchen/cabal-install-bin, which is not included in cabal (yet) but does exactly what you describe, i think. (the trick is to use `--prefix`, which implicitly modifies `--bindir` and `--datadir` params for `install`.)

Contrary to what it says in the readme, alex/happy seem to work fine; i recently talked to quchen and our guess is that the problems only existed before using --prefix properly. I will test this again to make sure.

**Comment by Hrothen** [comment]
That's surprising, if `--prefix` will cause a sandboxed install to put data files outside of the sandbox then that should probably be made explicit in the documentation.

**Comment by lspitzner** [comment]
i agree; only recently i found out about the meaning of prefix, and found the documentation (commandline and users-guide) both lacking. but for --bindir and the other --foodir options, the existing documentation looks ok to me; e.g. even if you put libraries outside of the sandbox, they will only be registered inside the sandbox package db.

btw i have tested quchen's script, and did not observe any problems with alex/happy.

**Comment by phadej** [comment]
sandbox functionality is removed.
