### ISSUE TITLE
ETXTBSY in setup exe cache code

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2474]
Recently I started seeing intermittent failures on Travis ([example](https://travis-ci.org/haskell/cabal/jobs/54592649)) with the following error:

```
cabal: Error: some packages failed to install:
HTTP-4000.2.19 depends on network-2.6.0.2 which failed to install.
network-2.6.0.2 failed during the configure step. The exception was:
/home/travis/.cabal/setup-exe-cache/setup-Configure-Cabal-1.18.1.3-x86_64-linux-ghc-7.8.3:
runProcess: runInteractiveProcess: exec: resource busy (Text file busy)
```

It appears that `cabal-install` is trying to replace an already existing setup executable. We should review the setup exe cache code and investigate why this is happening.

**Comment by ulysses4ever** [comment]
This looks like an obsolete bug report. Should it be closed?

**Comment by jneira** [comment]
Totally agree, closing myself :-)
