### ISSUE TITLE
Cabal download page should be behind a CDN

### ISSUE THREAD

**Issue by rthomas** [haskell/cabal#2490]
From email thread with @mietek

> It would be great to have https://www.haskell.org/cabal/release/ CDN-ified as https://downloads.haskell.org/~cabal/, just like https://www.haskell.org/ghc/dist/ is CDN-ified as https://downloads.haskell.org/~ghc/.

**Comment by amigalemming** [comment]
What means "CDN-inified"?

**Comment by rthomas** [comment]
The wiki.haskell.org host hosts the binaries for all of the cabal download versions. "CDN-ified" would mean to put these binaries behind a CDN, meaning we get better, globally distributed download performance and less bandwidth cost on our host, at the cost of the CDN.

**Comment by amigalemming** [comment]
On Wed, 22 Apr 2015, Ryan Thomas wrote:

> The wiki.haskell.org host hosts the binaries for all of the cabal download versions. "CDN-ified" would mean to
> put these binaries behind a CDN, meaning we get better, globally distributed download performance and less
> bandwidth cost on our host, at the cost of the CDN.

What is a CDN?

**Comment by rthomas** [comment]
A CDN is a Content Delivery Network, more info can be found here: http://en.wikipedia.org/wiki/Content_delivery_network

**Comment by gbaz** [comment]
we now use downloads.haskell.org as the official distro channel for cabal binaries.
