### ISSUE TITLE
cabal: Сouldn't find a timestamp record for the given compiler/platform pair.

### ISSUE THREAD

**Issue by yongqli** [haskell/cabal#2491]
cabal: Сouldn't find a timestamp record for the given compiler/platform pair.
    Please report this on the Cabal bug tracker:
    https://github.com/haskell/cabal/issues/new .
    Warning: Couldn't reinstall some add-source dependencies.

**Comment by yongqli** [comment]
% cabal --version
    cabal-install version 1.22.0.1
    using version 1.22.2.0 of the Cabal library

**Comment by 23Skidoo** [comment]
Can you come up with a small reproducible test case? If not, can you please upload `.cabal-sandbox/add-source-timestamps` and `.cabal-sandbox/packages/00-index.tar` somewhere and tell us which command triggered that error?

**Comment by yongqli** [comment]
It seems that this happened because the packages inside the sandbox was compiled with one version of ghc (due to PATH issues) while I tried to run `cabal build` with another.

**Comment by mietek** [comment]
Looks like another instance of https://github.com/haskell/cabal/issues/1869.
