### ISSUE TITLE
Cabal releases with sftp can't update '-latest' symlink

### ISSUE THREAD

**Issue by rthomas** [haskell/cabal#2493]
The new process for uploading to haskell.org using sftp does not allow us to update the '-latest' symlinks in the downloads directory.

As of `1.22.2.0` these are still pointing to `1.22.0.0`.

**Comment by tibbe** [comment]
Probably worth sorting out with admin@haskell.org. If we can't make it work with an sftp account, they should give you ssh access.

**Comment by rthomas** [comment]
Yep I'll chase up with them. Out at FLOSS UK at the moment so my ability to
get things done is limited.

**Comment by 23Skidoo** [comment]
`releases/latest` is currently not a symlink, it's a copy of `releases/cabal-1.22.0.0`. Looks like SFTP actually allows to create symlinks to directories, but nginx refuses to serve them (404). Guess we can either just upload a copy of `release/cabal-$VER` to `release/latest/` on each release or ask @davean to tweak the nginx config file.

**Comment by 23Skidoo** [comment]
This issue resolved itself somehow, I'm able to create symlinks using `lftp` on `www-origin.haskell.org` now.

**Comment by 23Skidoo** [comment]
...and they actually work correctly, see e.g. https://www.haskell.org/cabal/release/cabal-install-latest/.
