### ISSUE TITLE
argument interpretation of `cabal run`

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2507]
depending on whether there is one or more executables in the package, `cabal run foo` will either try to execute component `foo` or run the default component with parameter foo, i.e. `cabal run -- foo`. i vote against this feature, as it is inconsistent and can lead to surprises. (e.g. when adding a second executable, or when the one executable is marked disabled.)

**Comment by 23Skidoo** [comment]
There should be a way to choose the executable you want to run. What do you propose?

**Comment by ttuegel** [comment]
@23Skidoo He is proposing that `cabal run foo` should *only* run `foo`. If there is no executable `foo`, it should not fall back on running executable `bar` with option `foo`, which is what it does now.

**Comment by lspitzner** [comment]
yes, that is what i meant.

**Comment by 23Skidoo** [comment]
But you don't want to make the name parameter obligatory?

**Comment by ttuegel** [comment]
@23Skidoo I would vote for making the name obligatory, but I could see a case for making it optional when there is only one executable. Actually, I don't think we should treat anything before the `--` as an option to be passed to the executable; arguments before `--` go to `cabal`, arguments after go to the executable. What happens now if the user tries to pass an option to `cabal run foo`, but makes a typo? Does the misspelled option just get passed along to the executable? (That's what I suspect does happen.)

**Comment by 23Skidoo** [comment]
The original plan was to make `--` non-obligatory when the parse is unambiguous (#1119). Also, right now we can't detect whether or not `--` has been passed in `cabal run` code (it is handled by `GetOpt`).

**Comment by ttuegel** [comment]
I think I can live with the former, but I'm not sure about the latter. Is there an unambiguous way to pass options to `cabal run` versus the executable it runs?

**Comment by 23Skidoo** [comment]
Options starting with `-`/`--` are always passed to `run` itself unless preceded by `--`. Positional arguments [are interpreted in a context-dependent way](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Run.hs#L43), but I guess we could add support for `exe:exename` syntax.

**Comment by lspitzner** [comment]
In my case,
- i had test-suite foo (previously an executable), disabled executable bar.
- ran `cabal run foo`
- got output "bar is disabled".
- confused for a few minutes

maybe the best path of action is to detect that the first parameter to run is a non-executable component name, and print some warning. this allows #1119 while preventing this particular confusion. i might find time to code this today.

**Comment by 23Skidoo** [comment]
The problem seems to be that `run` doesn't support running test suites. Maybe it should (and if so, it should also support `test:testname` syntax). Also I guess it shouldn't try to run disabled executables.

I'll try to look into this later.

**Comment by lspitzner** [comment]
can be closed, unless you want to use this to track support for testsuites/benchmarks/the `test:testname` syntax etc.
