### ISSUE TITLE
bash completion for 'cabal sandbox' subcommands does not work

### ISSUE THREAD

**Issue by jstolarek** [haskell/cabal#2513]
I load bash completion using `source` command:

```bash
$ source bash-completion/cabal
```
but get an error when trying to complete a sandbox command:
```bash
$ cabal sandbox de<TAB>
-bash: bad substitution: no closing "`" in `).
package
```

**Comment by trskop** [comment]
@jstolarek What version of cabal-install are you using? On system where I'm right now I still have 1.20.0.4, but if I'm not mistaken then output of "cabal help sandbox" changed in later versions. Am I correct?

**Comment by jstolarek** [comment]
I downloaded latest `cabal-install` from Hackage:

```
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library
```
Bash completion file is also from there.

**Comment by 23Skidoo** [comment]
Yes, it looks like the help message format has changed:

```
$ cabal help sandbox | sed -rn '/Flags/q;s/^.* sandbox *([^ ]*).*/\1/;t p;b;: p;p'
.
init
delete
add-source
delete-source
list-sources
hc-pkg
in
in
if
in
;
.
with
from
hc-pkg
init`).
package
.
$ cabal --version
cabal-install version 1.23.0.0
using version 1.23.0.0 of the Cabal library 
```

**Comment by 23Skidoo** [comment]
Should work now, I think. Please reopen if still happens.
