### ISSUE TITLE
cabal freeze should take into account setup done by cabal configure

### ISSUE THREAD

**Issue by gracjan** [haskell/cabal#2521]
`cabal configure` takes a set of options like:
- --constraints
- --solver
- -w ghc
- etc

All of those should be taken in account when `freezing` current configuration.

**Comment by benarmston** [comment]
For what it's worth, freeze already has a solver option.  But many of the
configure flags are not currently supported. I can add them in as and when
they are requested, but it would be even better to get a list of configure
flags which should be supported.

Separate to the issue of flags is that of paying attention to the work
already done by configure. Currently, IIRC, freeze pays attention to some
of that work but not all. There have been requests for freeze to pay
attention to more and also requests for it to pay attention to less.

I'm on my phone at the moment so I don't want to try and dig them out. I'll
see if I can come up with a plan to support both use cases better.

**Comment by ulysses4ever** [comment]
Configure simply creates cabal.project.local these days. If you have a freeze file too, both will be taken into a count afaiu. Should we close this ticket?

**Comment by Mikolaj** [comment]
No objections, so lets close. Please open new tickets if applicable. Thank you!
