### ISSUE TITLE
(NEEDS TRIAGE) Detailed test-suites require v1.22

### ISSUE THREAD

**Issue by d3dave** [haskell/cabal#2524]
As evidenced by 2b50d0a74ac8c460f2fb49711de1fb069d572ee5, `type: detailed-0.9` test-suites as documented in the [User's Guide](https://www.haskell.org/cabal/users-guide/developing-packages.html#test-suites) require Cabal-1.22 to work. This is not documented anywhere.

I'm currently using Haskell Platform 2014.2.0.0 which ships with Cabal-1.18.1.3 and thus `type: detailed-0.9` test-suites fail to build with a cryptic message (details in [this SO question](http://stackoverflow.com/q/29449359)).

**Comment by ttuegel** [comment]
That commit appears to fix a regression in 1.20 from 1.18, i.e. detailed test suites should work it 1.18. @ezyang can you comment on that commit?

@d3dave Without seeing your test suite, I cannot comment further on this issue, except to say that error message can indicate that the file `Tests.hs` contains a module with a name other than `Tests`. Detailed test suites were certainly working prior to 1.20.

**Comment by d3dave** [comment]
@ttuegel Here's the `tests/Tests.hs` file:

    module Tests ( tests ) where

    import Distribution.TestSuite

    tests :: IO [Test]
    tests = return []

Also, when running `cabal build -v3`, and executing the shown `ghc` command manually, the resulting `Tests.o` file is present in `dist/build/`. The issue is with the `Linking...` step, as that seems to somehow either:
  1. delete the resulting object file, or
  2. prevent it from being written to the filesystem.

**Comment by ezyang** [comment]
My commit should not have any thing to do with it, since you are reporting a bug with GHC 7.8 but the package key fix is only applicable with GHC 7.10.

**Comment by d3dave** [comment]
Ok. I am currently using `stdio` tests until a new Platform comes out with support for v1.22.
You can close this if there is no resolution to my problem.

**Comment by ttuegel** [comment]
> The issue is with the Linking... step, as that seems to somehow either:
> 
>  1. delete the resulting object file, or
>  2. prevent it from being written to the filesystem.

We have had issues with file deletion/creation semantics on Windows before; I suspect that is happening here. Cabal-1.22 has a lot of changes to the build system; one of these changes may have coincidentally fixed the problem. I still want to investigate this further, to see if we can test for it and prevent it in the future.
