### ISSUE TITLE
Cannot install any package

### ISSUE THREAD

**Issue by Ippo343** [haskell/cabal#2526]
Hello. I'm encountering an issue trying to install some packages.

I just  made a fresh install of the latest haskell platform and I'm trying to install some packages using cabal install. However, the process never ends and it gets stuck either at the "Configuring" or "Building" step.

This happens for all the packages I tested (`zip-archive`, `digest`, `http-conduit` and `cabal-install` itself). I even tried reinstalling the whole platform from scratch. I tried both the 64 bit and 32 bit version, with the same error.

OS: Windows 8.1 x64
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library

Thanks.

**Comment by Ippo343** [comment]
Also, [here is the log](https://gist.github.com/Ippo343/520a6cf114f8629c5fed): you will see that it suddenly cuts off mid-line at the end. The last line is this (newlines added for clarity):

    [59 of 79] Compiling Distribution.Simple.LHC 
    ( C:\Users\MIPPO_~1\AppData\Local\Temp\Cabal-1.22.2.0-3008\Cabal-1.22.2.0\Distribution\Simple\LHC.hs,
    C:\Users\MIPPO_~1\AppData\Local\Temp\Cabal-1.22.2.0-3008\Cab

**Comment by Ippo343** [comment]
Update: I tried to build the package step by step using this sequence:

    cabal fetch cabal-install
    cabal unpack cabal-install
    cd cabal-install-1.22.2.0
    cabal configure

And this results in the error:

    cabal: At least the following dependencies are missing:
    Cabal >=1.22.2 && <1.23

Full output from the command with `--verbose=3` is in [this gist](https://gist.github.com/Ippo343/e5c2331dcf8af2e24ab5).

**Comment by 23Skidoo** [comment]
> Also, [here is the log](https://gist.github.com/Ippo343/520a6cf114f8629c5fed): you will see that it suddenly cuts off mid-line at the end.

Really weird. Is the `ghc` process still running? What does Task Manager show?

>     cabal: At least the following dependencies are missing:
    Cabal >=1.22.2 && <1.23

Well, yes, `cabal-install` 1.22.2 depends on a recent Cabal. Try `cabal install cabal-install`.

**Comment by Ippo343** [comment]
Really weird. Is the ghc process still running? What does Task Manager show?

I am currently not at home, I will check tonight and post the task list. However, I seem to recall that no, it's not running (the log file is owned by a process called `setup.exe`)

    Try cabal install cabal-install.

That's the output of `cabal install cabal-install`

**Comment by Ippo343** [comment]
Ok so, I'm running `cabal install cabal-install --verbose=3` on an administrator prompt, just to be sure.

On the console output, I can see the line

    Using Cabal library version 1.22.2.0

which makes me think that I already have an updated cabal.
First it rebuilds the setup script:

    Setup executable needs to be updated, compiling...
    (call to ghc with a long list of search folders)

From here, it moves to calling the setup executable like this

    <path>\setup.exe configure --verbose=3 --ghc (and a lot of other options)

After that call, it says that the build log is being redirected on a file, which is the log I posted previously that is cut in half.

The process never moves from this stage. When this happens, the task list shows both `cabal.exe` and a `setup.exe` that must be the one spawned by cabal, but no `ghc.exe`.

**Comment by jasagredo** [comment]
This ticket has been stale for almost 10 years. The versions used are very old.

I'm closing it, please re-open if you disagree.
