### ISSUE TITLE
uploads blocked by conditional use of `-Werror`

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#2527]
`cabal check` says about a package:
~~~~
The following errors will cause portability problems on other environments:
* 'ghc-options: -Wall -Werror' makes the package very easy to break with
future GHC versions because new GHC versions often add new warnings. Use just
'ghc-options: -Wall' instead.

Hackage would reject this package.
~~~~

The warning seems to be reasonable, however the `-Werror` option is activated by a flag.
~~~~
Flag developer
  Description: developer mode - warnings let compilation fail
  Default: False

Library
  If flag(developer)
    GHC-Options: -Werror
~~~~

I think, Cabal should only warn about unconditional uses of -Werror or conditional uses of -Werror where the flags default to `True`.

**Comment by ttuegel** [comment]
Cabal should warn about unconditional use of `-Werror`, and conditional use when the default is `True` or the flag is not manual.

**Comment by ekmett** [comment]
Does it actually reject your package or just say that it would?

**Comment by ekmett** [comment]
(About half of my packages currently have such a flag for use when testing on travis.)

**Comment by amigalemming** [comment]
On Fri, 24 Apr 2015, Edward Kmett wrote:

> Does it actually reject your package or just say that it would?

It only says that it would.

**Comment by MichaelXavier** [comment]
I'm not so sure about it being an idle threat. As of yesterday I tried to upload a package that uses the same flagging technique as lens and others and it was rejected.

**Comment by MichaelXavier** [comment]
So it looks like in the source there's several acknowledgements that `flattenPackageDescription` will cause this by ignoring conditionals. What's the right thing to do here, I wonder? Should the flattener continue to flatten but first take stock of conditionals and omit any that are default False, manual True? This is my first time looking at the cabal codebase so I don't even know if that is a practical thing to do.

**Comment by ttuegel** [comment]
The correct thing to do would be to walk down the tree of conditionals in the `GenericPackageDescription` and ensure:

1. there are no unconditional `-Werror` flags,
2. there are no `-Werror` flags under conditionals protected by automatic flags, and
3. there are no `-Werror` flags exposed by the default settings of any flag.

So, I think what you can do is walk down the tree, checking `-Werror` flags, but discarding branches protected by manual flags that default to `False`.

**Comment by dolio** [comment]
I'd appreciate being able to use -d flags this way, as well. For instance, I want to add a dump-simpl flag that adds -ddump-simpl -ddump-to-file to the ghc-options, and I'd rather not have to patch it out when uploading to hackage.

**Comment by cartazio** [comment]
+1 to @dolio  and @ttuegel's suggestions
i actually have to disable cabal check in my travis CI builds so i can use all the various debugging / linting tools

**Comment by bos** [comment]
Changed the title to reflect the severity of the problem.

**Comment by cartazio** [comment]
Is there anyone actively owning resolving this issue?

**Comment by cartazio** [comment]
Like, this is the kinda issue we should get fixed this week.

**Comment by ttuegel** [comment]
@cartazio AFAIK, nobody is actively working on this.

**Comment by cartazio** [comment]
I'm doing a bunch of family travel the next few days and was hoping to work
on some of my own projects, but maybe I should see if the fix is a quickie.

@erikd & @ttuegel if I get a PR sorted today or tomorrow, will you help
review and push for doing a patch/minor  level release or whatever so we
can get this down streamed to hackage server pronto?

**Comment by ttuegel** [comment]
@cartazio Yes, if you put a PR together I can see that it gets merged. I don't recall what is required to get changes onto Hackage, I will have to check.

**Comment by 23Skidoo** [comment]
I have pushed a workaround to the 1.22 branch. Fixing this properly looks somewhat involved, since the flattened package description is used everywhere instead of `GenericPackageDescription`.

**Comment by dcoutts** [comment]
@23Skidoo thanks for the short term workaround.

It's not quite true that it only works with the flattened description:

    checkPackage :: GenericPackageDescription
                 -> Maybe PackageDescription
                 -> [PackageCheck]
    checkPackage gpkg mpkg =
         checkConfiguredPackage pkg
      ++ checkConditionals gpkg
      ++ checkPackageVersions gpkg
      where
        pkg = fromMaybe (flattenPackageDescription gpkg) mpkg

At the top level it gets the unflattened one, and two of the three classes of checks are on the unflattened one.

**Comment by 23Skidoo** [comment]
@dcoutts Yes, I meant that a proper fix requires changing `checkConfiguredPackage` (which contains most of the checks) to work on a `GenericPackageDescription`.

**Comment by dcoutts** [comment]
@23Skidoo or just using a separate class, like the `checkConditionals`. No need to merge it with or change `checkConfiguredPackage`.

**Comment by dcoutts** [comment]
In fact `checkPackageVersions` is a good example of a check that could not be added to `checkConfiguredPackage` as it needed the full tree. We can just follow that pattern.

**Comment by dcoutts** [comment]
@23Skidoo gimme 20min...

**Comment by 23Skidoo** [comment]
I suspect that there are more checks that should be fixed to walk the tree of conditionals instead of using the flattened package description. If we don't want to change the signature of `checkConfiguredPackage`, we should audit it for such checks and move them out.

**Comment by dcoutts** [comment]
Pull req #2594

@23Skidoo I moved a number of other similar dev flag checks out.

**Comment by dcoutts** [comment]
Merged by @23Skidoo 

We'll try and get this deployed in the hackage server this weekend.

**Comment by suhailshergill** [comment]
@dcoutts cheers for picking this up; much appreciated

**Comment by bos** [comment]
Thanks for the quick turnaround!

**Comment by begriffs** [comment]
:heart:

**Comment by rcook** [comment]
This fix was submitted nearly a year ago and has not made it into an official release. Should this have happened by now? I am not familiar with cabal's release process, so I apologize if this is a stupid question.

**Comment by 23Skidoo** [comment]
There will be a new major Cabal release very soon, probably this week.

**Comment by rcook** [comment]
@23Skidoo : Thanks for the information!
