### ISSUE TITLE
cabal install clobbers symlinked world file

### ISSUE THREAD

**Issue by eigengrau** [haskell/cabal#2533]
When the world file is a symlink (e. g. in order to keep ~/.cabal/world under version control), instead of writing to the symlink target, doing cabal install will cause the link to be deleted and a new world file to be created in ~/.cabal.

**Comment by gbaz** [comment]
We got rid of world files, right?  if sho, we should close this, and also https://github.com/haskell/cabal/issues/687 https://github.com/haskell/cabal/issues/854  https://github.com/haskell/cabal/issues/812 https://github.com/haskell/cabal/issues/687

**Comment by 23Skidoo** [comment]
I think everything world file-related will be obsoleted by `new-build`.

**Comment by gbaz** [comment]
closing as obsolete
