### ISSUE TITLE
Give some little hints to newbies on how to resolve a backjump limit reached error

### ISSUE THREAD

**Issue by mjepronk** [haskell/cabal#2535]
I was trying to install project dependencies for a project with a kind of complicated dependency graph  (Snap, digestive-functors and persistent), which gave me the error: "backjump limit reached".

As a Haskell newbie, it would have helped me if Cabal would tell me the number of backjumps it used at the time (default is 2000, but this is hard to find out), and that I could also try to use --reorder-goals (which solved the problem in this case, as well as increasing the number of backjumps to 5000).

**Comment by kosmikus** [comment]
Fixed by #2536.
