### ISSUE TITLE
cabal test complains that test suites are not enabled after change to cabal file

### ISSUE THREAD

**Issue by taladar** [haskell/cabal#2539]
I am working on a cabal project which has been configured with

    cabal configure --enable-tests

and cabal test complains at some point that I need to add a dependency to the tests (Could not find...it is a member of the hidden package...perhaps you need to add ... to cabal file). I do so and invoke cabal test again. Now it presents the error

    cabal: Cannot build the test suite 'spec' because test suites are not enabled.
    Run configure with the flag --enable-tests

instead of the expected automatic reconfiguration with last set of flags I explicitly used (which included --enable-tests).

The cabal version is

    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library
  
on GHC 7.8.4 on Linux

**Comment by ezyang** [comment]
Options are preserved now, so this is fixed.
