### ISSUE TITLE
cabal install --only ignores --libdir

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2549]
Example run:

```
[tagged-0.8.0.1] cabal --no-require-sandbox install --libdir=/tmp/tagged
```

installs `tagged` in `/tmp/tagged/x86_64-osx-ghc-7.10.1/` as expected, but 

```
cabal --no-require-sandbox configure
cabal --no-require-sandbox build
cabal --no-require-sandbox install --only --libdir=/tmp/tagged
```

installs it in `~/.cabal/lib/x86_64-osx-ghc-7.10.1/tagge_3iHE9vJFhCP9NBKGRL5eSu` instead.

**Comment by dcoutts** [comment]
The `--only` is an undocumented semi-hidden thing. It's the same as copy+register. And copy does not take a libdir flag. You want to use --libdir at configure time.

**Comment by edsko** [comment]
Tsssh :-p
