### ISSUE TITLE
Add a command to just create a config file

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2553]
I've seen people ask questions in the past about how to create a ~/.cabal/config file. The answer is typically "run `cabal update`", but in some circumstances, that's not the optimal action (e.g., when you're going to change immediately to a different remote-repo). What about adding a command (strawman: `cabal init-config`) that only creates the ~/.cabal/config file, and only when missing? (Optional: I suppose it could take a flag to force it to overwrite an existing file, but I have no need of such a feature.)

**Comment by yogsototh** [comment]
In my script I do a "cabal info" which only create a ~/.cabal/config file. I modify it ASAP to use Haskell LTS. On the other hand I would I found nice to have a command to pass some basic init flags, like changing the remote-repo or having profiling activated by default.

**Comment by 23Skidoo** [comment]
This has been fixed by #3095, by the way.
