### ISSUE TITLE
`cabal test` should display test execution environment

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#2554]
As noted in #2058, `cabal test` uses `showCommandForUser`, but what we really want is `showCommandEnvForUser`.

**Comment by psibi** [comment]
@ttuegel Is `showCommandEnvForUser` already implemented ? Also I don't see `cabal test` using `showCommandForUser` using anywhere. The [testAction](https://github.com/haskell/cabal/blob/a2aaf2b929fd211abcf0ec4cbe957f36b72014cf/cabal-install/Main.hs#L722) method doesn't seem to be implemented using it.

**Comment by ttuegel** [comment]
Actually, this is already fixed and I forgot to close it. `cabal test` runs the executable with `rawSystemIOWithEnv` which prints the command and environment.
