### ISSUE TITLE
Please add a fast way to run cabal build and cabal test

### ISSUE THREAD

**Issue by hamishmack** [haskell/cabal#2556]
In particular it should only try to build the library in the package once.  This is an issue because even if there are no changes ghc can take several seconds to figure that out.

Leksah used to run

```
cabal build
cabal test
cabal copy
cabal register
```

Then `cabal test` changed so it would also build the test suites (and the library), so we switched so it to

```
cabal test
cabal copy
cabal register
```

But it turns out it does not build the executables in the package.  For now I am going to change it to do

```
cabal build
cabal test --wih-ghc=true
cabal copy
cabal register
```

This works, but it is a horrible hack.

Could we please update cabal-install so it supported

```
cabal build --run-tests
cabal copy
cabal register
```

or

```
cabal build
cabal test --skip-build
cabal copy
cabal register
```

**Comment by quasicomputational** [comment]
`cabal new-test` only builds the library once, so I think this bug's been solved.
