### ISSUE TITLE
Cabal config corrupted when using Unicode

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2557]
```
$ git clone https://github.com/hvr/-.git 無
...
$ cd 無
$ runghc Setup.hs configure
Configuring 無-0...
$ runghc Setup.hs build
Setup.hs: Saved package config file header is corrupt. Try re-running the 'configure' command.
```

**Comment by ttuegel** [comment]
Looks like we just need to let GHC handle the text encoding for us, rather than going through ByteString.

**Comment by 23Skidoo** [comment]
Once this is fixed, we should also add a regression test.

**Comment by hvr** [comment]
@ttuegel you self-assigned this bug 2 years ago... did you make any progress? Do you mind if I try giving this one a shot myself? ;-)

**Comment by ttuegel** [comment]
@hvr Have at it! I think at the time I had some reason to believe this would be simple to fix, but I never got to it.
