### ISSUE TITLE
How can I publish my own package to cabal, just like I can npm publish in JS/Node?

### ISSUE THREAD

**Issue by bucaran** [haskell/cabal#2559]
Hi! 

Thanks for all the hard work. I am just getting started with Haskell and I would like to know how can I publish my own package to cabal, just like I can `npm publish` in JS/Node?

**Comment by 23Skidoo** [comment]
Use `cabal sdist` and `cabal upload dist/$PKGNAME-$VERSION.tar.gz`. You need to be registered on Hackage for this to work. See also [here](https://hackage.haskell.org/upload).

**Comment by bucaran** [comment]
@23Skidoo Thanks!
