### ISSUE TITLE
cabal upload uses HTTP basic authentication over unencrypted connection

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2561]
I discussed this with @dcoutts last week, but only yesterday discovered how serious the situation is. It turns out that, currently, `cabal upload` is using HTTP basic authentication- which sends username and password in base64-encoded format- over an unencrypted HTTP connection. The relevant bit of code is:

https://github.com/haskell/cabal/blob/2b3a69490a2dbd6dfa3905b8a50ebad8aec7b276/cabal-install/Distribution/Client/Upload.hs#L56

This means that anyone sniffing packets during a `cabal upload` will be able to capture the uploader's username and password. Three mitigations come to mind:

* Switch to digest authentication (not perfect, since a MITM attack would still work for sending a compromised package)
* Add HTTPS support to `cabal upload`
* Remove `cabal upload` completely, and require users to upload by some other means.

I'd argue that this is serious enough that we should consider blocking non-HTTPS uploads to Hackage, or at the very least disabling HTTP basic authentication.

**Comment by erikd** [comment]
The upload feature is one that is *not* used by the vast majority of cabal users. Since it it also insecure it makes a great deal of sense to remove that feature from `cabal` itself (any reduction of complexity is an improvement as far as I am concerned). 

That single feature can then be replaced with a secure `cabal-upload` (@snoyberg already has an implementation called `stackage-upload` that fits the bill and I'm sure he wouldn't mind renaming it). The existing `cabal upload` functionality could then be replaced with a message "please `cabal install xxxxx-upload` and upload using that instead".

**Comment by snoyberg** [comment]
Just to confirm: if the naming is somehow the thing that would prevent @erikd's suggestion, I have no problem renaming.

**Comment by 23Skidoo** [comment]
#2563 fixes this.

**Comment by snoyberg** [comment]
I think this is severe enough to warrant backporting to previous releases. There is of course still vulnerability here, even with digest being used:

* A MITM can replace the request body with something nefarious
* Theoretically: an eavesdropper would be able to sniff the packets with the headers and send a simultaneous response, which would essentially be a security race condition

I'm overall still in favor of disabling the feature completely if there is no SSL support. I also think we need to do something at the Hackage Server level as well (I can open an issue there if it would be easier to track).

**Comment by 23Skidoo** [comment]
> I'm overall still in favor of disabling the feature completely if there is no SSL support.

I'm not opposed in principle.

>  I also think we need to do something at the Hackage Server level as well 

+1.

**Comment by snoyberg** [comment]
I've opened haskell/hackage-server#348 to track the Hackage aspect of this.

**Comment by 23Skidoo** [comment]
Assigning this to @rthomas since we need new releases from 1.22, 1.20, 1.18 and 1.16 branches now that this has been fixed.

**Comment by 23Skidoo** [comment]
@rthomas Can you provide an estimate of when you'll be able to make new releases?

**Comment by rthomas** [comment]
Sure thing, I will do them tonight (UTC).

**Comment by 23Skidoo** [comment]
@rthomas Great, thanks!

**Comment by 23Skidoo** [comment]
I noticed that Debian 7.8 still uses cabal-install 0.14, so I also ported this patch to the `cabal-1.14` branch. @rthomas, we'll also need a new 0.14 point release.

**Comment by rthomas** [comment]
Ack

**Comment by rthomas** [comment]
Mikhail: Could you please confirm whether this is both Cabal and
cabal-install or just cabal-install that needs the releases?

Cheers,

ryan

**Comment by 23Skidoo** [comment]
@rthomas Just cabal-install.

**Comment by rthomas** [comment]
Cheers. On it now.

**Comment by rthomas** [comment]
All but 0.14.1 have been completed, will send the announce when I update
the downloads page.

I am getting a compile error trying to build 0.14.1 (on the cabal-1.14
branch).

Distribution/Client/BuildReports/Upload.hs:54:38:
    Couldn't match expected type `Maybe b0' with actual type `URI'
    In the return type of a call of `relativeTo'
    In a stmt of a 'do' block: relativeTo rel uri
    In the expression:
      do { rel <- parseRelativeReference location;
           relativeTo rel uri }

This is on debian 7.8 with ghc-7.4.1.

**Comment by 23Skidoo** [comment]
Strange, it worked for me on the same version of Debian.

**Comment by 23Skidoo** [comment]
Managed to reproduce.

**Comment by rthomas** [comment]
Ack. Let me know if you have a solution - I will proceed with the rest of
the releases and do this one separately.

**Comment by 23Skidoo** [comment]
Should be fixed now.

**Comment by rthomas** [comment]
Cheers!

**Comment by rthomas** [comment]
Ok all built - I also had to add the Distribution.Client.JobControl module
to the cabal-install.cabal file to get it to pass the bootstrap test.

**Comment by rthomas** [comment]
I have released 1.22.4.0, 1.20.1.0, 1.18.1.0, 1.16.1.0, 0.14.1 of cabal-install.

They are on hackage and haskell.org.

The sha1sums are as follows:

b98eea96d321cdeed83a201c192dac116e786ec2 cabal-install-1.22.4.0.tar.gz
338fc09b0aa56fead06cecfae2bccd573f5dd3da cabal-install-1.20.1.0.tar.gz
ab5c6801c6949a86edf41833c782201e0df1108f cabal-install-1.18.1.0.tar.gz
ffb2cd81d620122982f5c1e4d8672c98d85296a0 cabal-install-1.16.1.0.tar.gz
35cd57eae72e0488a6a37ea503b906248da5230a cabal-install-0.14.1.tar.gz

**Comment by 23Skidoo** [comment]
Awesome!
