### ISSUE TITLE
cabal sdist leaves over empty src directory

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2562]
Easiest to see with the `--builddir` argument. If you run `cabal sdist --builddir=foo`, then- in addition to the desired .tar.gz file in `foo`, you'll also have an empty `src` directory.

**Comment by ttuegel** [comment]
Just checked, this is only reproducible with cabal-install, not with plain Cabal.

**Comment by gbaz** [comment]
Just checked and this does not seem to occur with sdist on current cabal-install.
