### ISSUE TITLE
What does `PACKAGES` in `cabal freeze PACKAGES` do?

### ISSUE THREAD

**Issue by soenkehahn** [haskell/cabal#2565]
`cabal freeze --help` says that you could pass `PACKAGES` as arguments. But it doesn't really seem to be doing anything. Even `cabal freeze does-not-exist` works without complaint. Could we document what `PACKAGES` is used for?

**Comment by benarmston** [comment]
Thanks for the bug report.

It's a documentation bug introduced in
ad895439f13c4d0ded3a7b51e529ce1452d09875. PACKAGES shouldn't be mentioned.

**Comment by lspitzner** [comment]
@benarmston no, it was present before i refactored the code. no matter who introduced it, it is good to have fixed :)

**Comment by benarmston** [comment]
@lspitzner you're quite right it was there prior to your refactoring. I
guess I didn't understand what `usagePackages` was doing. Neither when I
introduced the bug nor this morning when I was trying to understand how it
got there.

**Comment by soenkehahn** [comment]
Thanks for looking into this.

Does this mean that only the `--help`-output changed? Does `cabal freeze` still accept positional arguments? If so, is this wanted behaviour?
