### ISSUE TITLE
unionBuildInfo should not always use nub

### ISSUE THREAD

**Issue by bos** [haskell/cabal#257]
(Imported from [Trac #264](http://hackage.haskell.org/trac/hackage/ticket/264), reported by @igloo on 2008-04-02)

The below report was originally filed as
[http://hackage.haskell.org/trac/ghc/ticket/2190](http://hackage.haskell.org/trac/ghc/ticket/2190)

In libraries/Cabal/Distribution/PackageDescription.hs, the unionBuildInfo function combines, for example, ldOptions from two `BuildInfos?`, using nub to eliminate duplicate arguments.  This is wrong for ldOptions and some other elements.  For example, if ldOptions contains:

<tt>-Xlinker -R -Xlinker /dir1 -Xlinker -R -Xlinker /dir2</tt>

Then the nubbed result is:

<tt>-Xlinker -R /dir1 /dir2</tt>

which doesn't work at all.  There may be some redundancy that could be eliminated, but for arguments passed to external programs, it can only be done safely by understanding the semantics of the arguments.  Similarly for extraLibs, <tt>-lfoo -lbar -lfoo</tt> may be necessary if <tt>libfoo</tt> and <tt>libbar</tt> reference each other's symbols.

Using nub is wrong for at least cppOptions, ccOptions, ldOptions, and extraLibs.  But I think it is necessary for some other `BuildInfo?` components, like hsSourceDirs, so it can't be removed completely; that results in an error while building GHC:

<pre class="wiki">Preprocessing library unix-2.3.0.0...
Generating Makefile unix-2.3.0.0...
Setup: makefile: can't cope with multiple hs-source-dirs yet, sorry
</pre>So <tt>combine</tt> could take an extra arguments, which would be nub in some cases or id in others.

**Comment by facundominguez** [comment]
Was there a regression here?

When using 
```
cc-options: -optc a -optc b
```
`cabal-install` invokes `ghc` with `ghc -optc a b`

```
$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```
