### ISSUE TITLE
Improve documentation for `cabal-version` field

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2571]
There seems to be some confusion regarding the `cabal-version` field, causing some authors to set e.g. `cabal-version: >= 1.14` for no good reason due to lack of understanding what that field actually means.

Also it would be useful to include a condensed `cabal-version` changelog of features added in each `cabal-version` to the manual.

C.f. https://github.com/haskell/cabal/blob/641e854ae663e2b34f34ecc11ba663ac3a9bdc19/Cabal/Distribution/PackageDescription/Check.hs#L911-L1091 )

**Comment by bergmark** [comment]
I've also seen libraries using this with a custom Setup.hs that requires a newer Cabal. Unfortunately this isn't part of dependency resolution so builds often fail when picking an earlier version would work.

**Comment by phadej** [comment]
@hvr, would be it enough to write down specific *breakpoints*, i.e. 1.21, 1.10 and previous?

And maybe mention that `cabal check` will say if it's too low for the features you use?
