### ISSUE TITLE
Handle cabal files beginning with a byte order marker (BOM)

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2573]
Original issue: https://github.com/haskell/hackage-server/issues/351, also related to #2572

The ideal behavior IMO would be:

* Modify `cabal check` to reject any cabal file with a BOM in it (to support older versions of cabal)
* Modify the code (either `Cabal` or `cabal-install`, I'm not sure) to strip off the BOM at the beginning of a cabal file.

**Comment by ttuegel** [comment]
According to comments in #2621, this is implemented already.
