### ISSUE TITLE
customFieldsPD

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2585]
I have a use case where I'd like to use `customFieldsPD`. However, the documentation for that field makes it clear that the field has some deeply magical stuff going on, and shouldn't be trusted. My question is: is there any use case under which it's safe to use that field? For example, is there a guarantee that if I use `parsePackageDescription` and then use `customFieldsPD` on those results that I'll get the fields I'm looking for?

**Comment by jneira** [comment]
We are talking about:

https://github.com/haskell/cabal/blob/0abbe37187f708e0a5daac8d388167f72ca0db7e/Cabal-syntax/src/Distribution/Types/PackageDescription.hs#L125-L127

I've not found nothing in docs about custom fields so i am not sure if the warning is there anymore.
However iirc there are some actual usages and the question were not answered so i guess we can close this, feel free to reopen on toher case
