### ISSUE TITLE
use of multiple --allow-newer options

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#2588]
I tried
~~~~
$ cabal install --allow-newer=base --allow-newer=ghc-prim pkg
~~~~
and it seems that `--allow-newer=ghc-prim` overrides `--allow-newer=base`. I expected that both options are combined. I was not aware that I can use a list of packages as argument to the option. I suggest to either

* combine multiple uses of the allow-newer option, or
* abort with an error if the option is passed twice.

I prefer the first way.

**Comment by 23Skidoo** [comment]
Try `--allow-newer=base,ghc-prim`.

**Comment by hvr** [comment]
...at the very least we should have `cabal-install` emit a warning if multiple uses of `--allow-newer` result in a different behaviour than expected...
