### ISSUE TITLE
Can't upgrade from 1.16 to 1.22

### ISSUE THREAD

**Issue by GAumala** [haskell/cabal#2597]
I'm new to cabal and I read somewhere that I needed to use sandboxes to avoid having problems. Then I read that I need 1.18 for sandbox. Running `cabal update` and `cabal install Cabal cabal-install`
tried to install 1.22.4.0 but my computer (Ubuntu 14.04) still had 1.16.

After reading issue https://github.com/haskell/cabal/issues/1586 I tried to do `sudo cabal install --global cabal-install` but now I have a different problem:

```
[11 of 11] Compiling Network          ( Network.hs, dist/build/Network.o )

Network.hs:292:16: Warning:
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: SockAddrCan _

Network.hs:401:5: Warning:
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: SockAddrCan _
In-place registering network-2.6.1.0...
cabal: /usr/local/share/doc/network-2.6.1.0: does not exist
Failed to install network-2.6.1.0
Configuring network-uri-2.6.0.3...
Warning: Unknown extensions: DeriveGeneric
Building network-uri-2.6.0.3...
Preprocessing library network-uri-2.6.0.3...
[1 of 1] Compiling Network.URI      ( Network/URI.hs, dist/build/Network/URI.o )
In-place registering network-uri-2.6.0.3...
cabal: /usr/local/share/doc/network-uri-2.6.0.3: does not exist
Failed to install network-uri-2.6.0.3
cabal: Error: some packages failed to install:
Cabal-1.22.3.0 depends on binary-0.7.4.0 which failed to install.
HTTP-4000.2.19 depends on network-uri-2.6.0.3 which failed to install.
binary-0.7.4.0 failed during the final install step. The exception was:
ExitFailure 1
cabal-install-1.22.4.0 depends on network-uri-2.6.0.3 which failed to install.
network-2.6.1.0 failed during the final install step. The exception was:
ExitFailure 1
network-uri-2.6.0.3 failed during the final install step. The exception was:
ExitFailure 1
```
Googling `network-uri-2.6.0.3` didn't show me any useful results. Please help. I don't really care about what version I end up using as long as I can start working as soon as possible.

**Comment by 23Skidoo** [comment]
> Running `cabal update` and `cabal install Cabal cabal-install`
tried to install 1.22.4.0 but my computer (Ubuntu 14.04) still had 1.16.

You need to add `~/.cabal/bin` to `PATH`.

**Comment by GAumala** [comment]
added `export PATH=$PATH:$HOME/.cabal/bin` at the end of `$HOME/.profile`. It didn't help

**Comment by 23Skidoo** [comment]
What's the output of `ls ~/.cabal/bin`?

**Comment by GAumala** [comment]
Only one file: `cabal`

**Comment by 23Skidoo** [comment]
And what is `~/.cabal/bin/cabal --version`?

**Comment by GAumala** [comment]
It's 1.22. I should use `$HOME/.cabal/bin/cabal` then?

**Comment by 23Skidoo** [comment]
Yes. Close and reopen your terminal window or run `source ~/.profile` in the shell.
