### ISSUE TITLE
Pretty-printer always omits default values, sometimes building incorrect file

### ISSUE THREAD

**Issue by abbradar** [haskell/cabal#2598]
Test case:
```
import Distribution.PackageDescription.Parse
import Distribution.PackageDescription.PrettyPrint
import Distribution.Verbosity
import System.Environment

main :: IO ()
main = getArgs >>= mapM_ (\cabalFile -> readPackageDescription silent cabalFile >>= writeGenericPackageDescription cabalFile)
```
Source file:
```
name:                test
cabal-version:       -any
license:             UnspecifiedLicense

Flag myflag
  Default:           False

library
  if flag(myflag)
    Buildable:       True
  else
    Buildable:       False
```
Resulting file:
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
    
    if flag(myflag)
    else
        buildable: False
```

**Comment by 23Skidoo** [comment]
Thanks for the bug report and a nice reproducible test case.

**Comment by abbradar** [comment]
The problem is actually different: pretty-printer doesn't print anything with default values, so `if ... buildable: True` and possibly other patterns break. Two more examples:
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
  if flag(myflag)
    extra-libraries:
  else
    extra-libraries: mylib
```
to:
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library

    if flag(myflag)
    else
        extra-libraries:
            mylib

```
and
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
  if flag(myflag)
    buildable: False
    extra-libraries:  
  else
    buildable: True
    extra-libraries: mylib
```
to:
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
    
    if flag(myflag)
        buildable: False
    else
        extra-libraries:
            mylib
```

**Comment by abbradar** [comment]
Possible workaround would be printing `buildable: True` when all fields are defaults in places where something must ; this would lose some semantic information (`buildable` instead of `extra-libraries` in my example above) but at least always render valid Cabal file.

**Comment by phadej** [comment]
I could take a look on this.

**Comment by phadej** [comment]
While experimenting I found a following situation:

```
executable foo
  buildable: False
  buildable: True
```
builds the executable

---

```
executable foo
  buildable: True
  buildable: False
```

Doesn't build

---

```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
  buildable: False
  if flag(myflag)
    buildable: True
```

pretty prints as

```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
    
    if flag(myflag)
    buildable: False
```

and acts accordingly, if written as 
```
name: test
cabal-version: -any
license: UnspecifiedLicense

flag myflag
    default: False

library
    
    if flag(myflag)
        buildable: True
    buildable: False
```
in the first place.

---

Seems that adding `buildable: True` into otherwise empty branches would make a trick; yet I find the behaviour of the last example surprising. Should cabal warn if singular field is defined twice?

**Comment by peti** [comment]
I have reason to believe that this bug was fixed properly. When I run the test program on the Cabal file from  http://hackage.haskell.org/package/pandoc-1.13.2/revision/2.cabal, then the output still looks like this:

~~~~
executable make-pandoc-man-pages
    
    if flag(make-pandoc-man-pages)
    else
        buildable: False
    main-is: make-pandoc-man-pages.hs
~~~~~

**Comment by 23Skidoo** [comment]
@peti 
> I have reason to believe that this bug was fixed properly.

Did you mean to say "wasn't"?

**Comment by peti** [comment]
Yeah, I meant "wasn't fixed properly". Sorry about that.

Curiously enough, the issue seems to be gone in the current `HEAD` from the git repository. Is it possible that e6bff69dfc5f4cc715e32ca60c9fa0c057195e07 is the proper fix, indeed, but that this commit didn't make it into the 1.22.4.0 release that's shipped with GHC 7.10.2?

**Comment by 23Skidoo** [comment]
Yes, e6bff69dfc5f4cc715e32ca60c9fa0c057195e07 wasn't backported to the 1.22 branch.

**Comment by peti** [comment]
Well, that's a shame, because now the only release version of `Cabal` that can do a round-trip with reasonable chances of success is version 1.20.x. :-(
