### ISSUE TITLE
Get LocalBuildInfo in pre-test hook

### ISSUE THREAD

**Issue by pikajude** [haskell/cabal#2599]
I've asked in #haskell and nobody seems to know the answer to this. What's the right way to get the current LocalBuildInfo in the preTest hook?

**Comment by ezyang** [comment]
There doesn't seem to be a state-sponsored way. But you can connive to get it yourself using `getBuildConfig`. You'll need to have your overridden `UserHooks` ready, as well as the dist location from `testDistPref`. If it breaks, you get to keep all the pieces.
