### ISSUE TITLE
Tests fail with missing dependency

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/cabal#2610]
Apologies if this is a duplicate. I know this is probably user error, but consider this a documentation bug report as I'm just following the simple steps in HACKING.md.

    $ cabal sandbox init
    $ cabal install --only-dependencies --enable-tests
    $ ./Setup configure --enable-tests --package-db=/home/mitchell/haskell/cabal/Cabal/.cabal-sandbox/x86_64-linux-ghc-7.10.1-packages.conf.d
    $ ./Setup build
    $ ./Setup test

Results in 9 / 47 failed tests, all of which look like:

    Setup: At least the following dependencies are missing:                                                       
    old-time -any

Hm...

    $ ls .cabal-sandbox/x86_64-linux-ghc-7.10.1-packages.conf.d | grep old-time
    old-time-1.1.0.3-c6c471a5ec61ff049468f265b077486d.conf

:(

Full log: http://lpaste.net/133327

**Comment by 23Skidoo** [comment]
IIRC you need `old-time` to be installed in the user or global package DB for this to work. So try doing `cabal install old-time` outside a sandbox.

**Comment by 23Skidoo** [comment]
Thanks for the bug report, by the way. We probably need to fix tests to work on stock GHC 7.10.

**Comment by ezyang** [comment]
With new-build Travis works, so I think we're good now.
