### ISSUE TITLE
expose more global options in cabal --help ?

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#2612]
Currently for global options, in Setup.hs we have the line "showOrParseArgs of ShowArgs -> take 6"

This means that the options for "remote-repo" "remote-repo-cache" "local-repo" "logs-dir" and "world-file" are all hidden.

It seems to me that as our infrastructure has evolved, these options are not as exotic as they once were, and perhaps should all be exposed by the --help command? This can be fixed by just swapping "take 6" for id there :-)

**Comment by gbaz** [comment]
note that --store-dir also doesn't appear in global help. That should definitely be added too! (and of course world-file is very dead and probably should be ripped out if it hasn't been yet)

**Comment by jneira** [comment]
`--store-dir` definitely must be listed

**Comment by phadej** [comment]
Probably no, as this doesn't sound like a very big task.
