### ISSUE TITLE
Default number of jobs is different using cabal build than using cabal install

### ISSUE THREAD

**Issue by asr** [haskell/cabal#2628]
Using

``` bash
$ cabal --version
cabal-install version 1.22.4.0
using version 1.22.3.0 of the Cabal library
```

the default number of jobs in my machine using `cabal build` is four

``` bash
$ cabal configure -v2
...
creating dist/setup
./dist/setup/setup configure --verbose=2 --ghc --prefix=/home/asr/.cabal

$ cabal build -v2
...
creating dist/setup
./dist/setup/setup build --verbose=2 --builddir=dist --jobs=4
```

but using `cabal install` the default number of jobs isn't set up

``` bash
$ cabal install -v2
...
creating dist/setup
./dist/setup/setup configure --verbose=2 --ghc --prefix=/home/asr/.cabal
...
creating dist/setup
./dist/setup/setup build --verbose=2
```

Is it the expected behaviour?

**Comment by 23Skidoo** [comment]
Yes, `cabal install` builds packages (and now components) in parallel, so if we just build each package with `ghc -j4`, there will be too much parallelism. I have some [old unfinished patches](https://github.com/23Skidoo/cabal/commits/num-linker-jobs) intended to improve the situation.
