### ISSUE TITLE
Improve the user experience around sandboxes with multiple source packages

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#2631]
- [x] Allow the cabal binary itself to be used as a `Setup.hs` file, removing errors related to not having the right version of Cabal installed/available (e.g. when doing parallel builds.) (#2633)
- [x] Track down and fix issue (probably timestamp related) with unnecessary rebuilds in source packages that haven't changed.
- [ ] Allow build targets that include package names/directories, not just components in the current directory.
- [ ] Implicit "add-source" for packages in subdirectories.
- [ ] Allow dist/ to live inside the sandbox directory, rather than in the package directory.
- [ ] Search upwards for sandbox directory.
- [ ] Cabal configure should produce and save an install plan. Cabal build should install the plan (by invoking cabal install --only-dep).
- [ ] Come up with catchy title for issue.

/cc @dcoutts

**Comment by BardurArantsson** [comment]
Is there any of this that a noob such as myself could help with? (And which would have value on as a feature of its own.)

**Comment by dcoutts** [comment]
@BardurArantsson you could have a look at the one "Search upwards for sandbox directory". It shouldn't be hard to implement, and then you'd want to play around with it a bit and see if there's any unexpected issues with that approach.

**Comment by BardurArantsson** [comment]
Thanks, I'll have a look at that tomorrow (or the day after). Hopefully, it's pretty independent of the rest of all the others?

(I think I can already theoretically foresee a few issues wrt. backward compatibility, but we'll see, I guess...)

**Comment by dcoutts** [comment]
@BardurArantsson yeah, should be independent.

**Comment by BardurArantsson** [comment]
Sorry, got sidetracked on this. Would I be right in thinking that the main change here would be in having "getSandboxConfigFilePath" in Sandbox.hs -- namely replacing the call to getCurrentDirectory with a search towards higher-up directories?

(I can see there are other references to getCurrentDirectory that will have to be adjusted, of course. I'm thinking mainly whether getSandboxConfigFilePath is always the entry point for getting the "reference" to the sandbox.)

**Comment by BardurArantsson** [comment]
Ok, so I've added a new issue #2810 for the "Search upwards..." sub-task. Could someone please edit it into the first post on this issue?

I'll do a pull req for #2810 shortly just for initial review.

**Comment by phadej** [comment]
sandbox functionality is removed.
