### ISSUE TITLE
Inconsistent package name case sensitivity

### ISSUE THREAD

**Issue by bmjames** [haskell/cabal#2636]
On the command line, it appears that `cabal install` treats package names case-insensitively. For example, `cabal install spock` and `cabal install Spock` have the same behaviour.

However, packages in the `build-depends` section of a `.cabal` file are case-sensitive.

This leads to a confusing user experience, when a package appears to install successfully on the command line, but fails in a `.cabal` file.

My suggestion: when a package name is not correctly given to `cabal install`, instead of succeeding, it should instead fail with a message indicating that there is a similarly named package available.

**Comment by phadej** [comment]
Would be enough to issue a warning if the case doesn't match, but the match is unambiguous?

**Comment by BardurArantsson** [comment]
Ah, exactly what I was commenting on earlier @phadej. This is not a good idea -- but I'm not sure we can change it at this point.

**Comment by tfausak** [comment]
Fixed by #4778.
