### ISSUE TITLE
custom-setup warning should only be suspicious

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2638]
If people want to support an old version of Cabal, they can't add the new setup build dependencies from https://github.com/haskell/cabal/pull/2515

So it should only be a suspicious warning, not a warning. This matters for GHC, since we hard error on all cabal check warnings.

**Comment by ezyang** [comment]
@hvr points out to me that if people follow this advice, their new package will instantly break all pre-7.10 users. Not great.

Warning in question is https://github.com/edsko/cabal/commit/529912ee4163a1b1905364a97cb5e609119368b

**Comment by hvr** [comment]
there's another problem if people start setting `cabal-version: >= 1.23` to soon w/o also setting a relatively high `base`-lower bound: old `cabal-install` versions don't include the `cabal-version` constraint into the cabal-solving, and hence don't backtrack. This can cause `cabal install foo` to instantly break for all pre cabal-install-1.23 users as soon as `foo` starts publishing a version w/  `cabal-version: >= 1.23`

**Comment by edsko** [comment]
So what's the conclusion here? 

/pinging also @dcoutts

**Comment by dcoutts** [comment]
Right, build warning is too high here. It's at most dist suspicious.

As for the compat issue. Yes technically we don't need to require `cabal-version: >= 1.23` for packages that use the new section. What we could do is make sure this works:

 * if the new setup section exists, use it (in new cabal)
 * old cabal *should* ignore the new section, with a warning. I think that's the behaviour, but have to double check.
 * Have a check that if the package uses a custom setup, suggest (at dist suspicious level) using the new section type, but don't require `cabal-version: >= 1.23`. We can note in the check message that it is not necessary to use `cabal-version: >= 1.23`, however older cabal will not read the section so it may or may not work with old cabal (as it relies on the old behaviour of using what's in the ambient environment).
 * if `cabal-version: >= 1.23` however, and a package still uses a custom setup, make that a build warning (or at minimum dist inexcusable)

**Comment by edsko** [comment]
Ok, @dcoutts has told me he will fix this :)

**Comment by ezyang** [comment]
This is still open because the committed change was only a partial fix.

**Comment by ezyang** [comment]
Punting.
