### ISSUE TITLE
Cabal solver shall consider `*-extensions`

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2644]
I thought I had seen this feature request filed ages ago, but couldn't find it (the closest related side-comment I did find was https://github.com/haskell/cabal/issues/335#issuecomment-5891726). In any case, here it is (again) explicitly:

It's possible (and afaik recommended) to list used language extensions in the `.cabal` file. However, that information is currently used too late, after the cabal solver has already locked into an install-plan.

Instead, the Cabal solver should regard the declared `{default,other}-extensions` as a dependency, and integrate that information with the solving algorithm, thereby allowing to backtrack to other package-versions/install-plans if the current compiler is known not to provide the requested language extensions

/cc @dcoutts

**Comment by 23Skidoo** [comment]
Is the problem that extensions can be conditionally enabled by flags? Otherwise this could be implemented by just not considering such packages in the first place.

**Comment by hvr** [comment]
@23Skidoo yeah, that's exactly why this can't be implemented as a trivial pre-filtering step...

**Comment by kosmikus** [comment]
Yes, interesting suggestion. So this isn't *quite* as easy as it sounds, because the solver uses its own simplified index format right now, and discards the extensions information during an initial conversion step. So the implementation of this would have to extend the solver-specific index format with extension information. Then we'd need a mapping from GHC versions to supported extensions. Is this available somewhere already? Can one query GHC for this easily? Once we have the supported extensions available as an input to the solver, and the extended index info mentioned above, the actual filtering should be very easy.

**Comment by hvr** [comment]
@kosmikus afaik, Cabal knows which language extensions a compiler provides, see API at http://hackage.haskell.org/package/Cabal-1.22.3.0/docs/Distribution-Compiler.html

**Comment by hvr** [comment]
PS: Here's the `cabal configure` check against the required  `*-language:` and `*-extensions` specifications `Cabal` performs currently (after cabal solving):

https://github.com/haskell/cabal/blob/d860aeebad571fec77b89c1312ea668870693ed8/Cabal/Distribution/Simple/Configure.hs#L568-L583

**Comment by kosmikus** [comment]
Ok great. Then this part is easy. So I think this makes this a relatively easy (but not quite trivial), to work on for someone who wanted to gain a little bit of understanding on how the solver works.

**Comment by dcoutts** [comment]
Yes, I think ultimately the solver should be extended to cover several other kinds of dependency in addition to libraries: build tools, language extensions, C libs etc.

For language extensions we need to know which extensions are supported by the current compiler, which we already have infrastructure for. So then once the solver is extended to accept the set of supported extensions then it's easy to plug together.

**Comment by kosmikus** [comment]
Yes, let's not make this ticket more complicated than it is. For language extensions, it's a simple yes/no check, which makes this a rather low hanging fruit.

**Comment by kosmikus** [comment]
I'm working on this now.

**Comment by phadej** [comment]
Should we formulate some guidelines for `default-extensions` and `other-extensions` fields. As they are soon used by solver. E.g. I use `DefaultSignatures` but the usage is often guarded by cpp, should I put it in `other-extensions` or not?

**Comment by hvr** [comment]
@phadej fwiw, `other-extensions` and `default-extensions` are already used right now, it's just that they're checked too late (after the solver ran) by Cabal. However, there's a ticket #1517  about documenting `{other,default}-extensions`. I usually mirror the `CPP`-conditional which guards language pragmas inside the `.cabal` file via Cabal conditionals.

**Comment by 23Skidoo** [comment]
Fixed by #2873.
