### ISSUE TITLE
Make CABAL_SANDBOX_CONFIG visible from cabal repl, cabal test, etc.

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#2654]
I have a program which needs to behave differently depending on whether the user is running within a sandbox. Currently, the only way I know of detecting the presence of a sandbox within Haskell is by using the value of the `CABAL_SANDBOX_CONFIG` environmental variable, e.g.,

``` haskell
module Main (main) where

import Control.Exception (try)
import System.Environment (getEnv)

main :: IO ()
main = do
    mbSandboxCfg <- try $ getEnv "CABAL_SANDBOX_CONFIG"
    putStrLn $ case (mbSandboxCfg :: Either IOError FilePath) of
        Left  e  -> show e
        Right fp -> fp
```

Running this code with `cabal exec runhaskell` (or installing it as an executable and running that with `cabal exec`) produces the sandbox path as I'd expect. However, `CABAL_SANDBOX_CONFIG` can't be used from other `cabal` contexts, including `cabal repl`, `cabal test`, or `cabal bench`:

```
$ cabal repl
Preprocessing library cabal-sandbox-config-0.1...
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( src/Main.hs, interpreted )
Ok, modules loaded: Main.
λ> main
CABAL_SANDBOX_CONFIG: getEnv: does not exist (no environment variable)
```

```
$ cabal test --show-details=always
Preprocessing test suite 'test' for cabal-sandbox-config-0.1...
Running 1 test suites...
Test suite test: RUNNING...
CABAL_SANDBOX_CONFIG: getEnv: does not exist (no environment variable)
Test suite test: PASS
Test suite logged to: dist/test/cabal-sandbox-config-0.1-test.log
1 of 1 test suites (1 of 1 test cases) passed.
```

```
$ cabal bench 
Preprocessing benchmark 'benchmark' for cabal-sandbox-config-0.1...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/benchmark/benchmark-tmp/Main.o )
Linking dist/build/benchmark/benchmark ...
Running 1 benchmarks...
Benchmark benchmark: RUNNING...
CABAL_SANDBOX_CONFIG: getEnv: does not exist (no environment variable)
Benchmark benchmark: FINISH
```

Because of this limitation, I end up having to launch a subprocess to `cabal exec ...` just to determine whether I'm in a sandbox or not, which feels like overkill. Can `CABAL_SANDBOX_CONFIG` always be defined from `cabal` (or perhaps there is a better way of tackling this problem)?

**Comment by Rufflewind** [comment]
I agree this will be very useful.  I ran into the [same problem a while back](https://github.com/haskell/directory/issues/25), but I ended up working around the problem entirely because of this and many other issues.

> Because of this limitation, I end up having to launch a subprocess to `cabal exec ...` just to determine whether I'm in a sandbox or not …

That won't always work, because if the user calls `cabal` with `--sandbox-config-file=…` then you will not get the right behavior.

**Comment by RyanGlScott** [comment]
Yeah, my above suggestion is not a very good way to do it.

I did find [this much cleaner hack](https://github.com/bgamari/hoogle-index/blob/9a5a8fe2ea7ce142fae1abc1f1dc83f13d168539/Main.hs#L343-355) (thanks, Ben Gamari!) for finding out if the current path is sandboxed. I'll post it here in case anyone finds it useful:

```haskell
import Data.Char (isSpace)
import Data.List (isPrefixOf)
import Data.Maybe (listToMaybe)

import System.Directory (doesFileExist, getCurrentDirectory)
import System.FilePath ((</>))

-- | Get the path to the sandbox database if any
getSandboxPath :: IO (Maybe FilePath)
getSandboxPath = do
  dir <- getCurrentDirectory
  let f = dir </> "cabal.sandbox.config"
  ex <- doesFileExist f
  if ex
    then
      (listToMaybe .
       map (dropWhile isSpace . tail . dropWhile (/= ':')) .
       filter (isPrefixOf "package-db") .
       lines) <$> readFile f
    else return Nothing
```

**Comment by RyanGlScott** [comment]
This has been obsoleted by nix-local-build.
