### ISSUE TITLE
Pretty-printer loses necessary quotes in ghc-options

### ISSUE THREAD

**Issue by peti** [haskell/cabal#2661]
The Cabal file http://hackage.haskell.org/package/serversession-backend-persistent-1.0/serversession-backend-persistent.cabal defines the following `ghc-options` flags:

```
ghc-options:     -Wall -threaded "-with-rtsopts=-N -s -M1G -c" -rtsopts
```

When round-tripped through the Cabal library, however, the outcome will be:

```
ghc-options: -Wall -threaded -with-rtsopts=-N -s -M1G -c -rtsopts
```

The quotation marks -- which are essential for the build to succeed -- are lost.

To reproduce this error, process the Cabal file given above with the following code:

``` haskell
import Distribution.PackageDescription.Parse
import Distribution.PackageDescription.PrettyPrint
import Distribution.Verbosity
import System.Environment

main :: IO ()
main = getArgs >>= mapM_ (\cabalFile -> readPackageDescription silent cabalFile >>= writeGenericPackageDescription cabalFile)
```

This error occurs with Cabal-1.22.2.0, but older versions (like Cabal 1.20.x) seem to have the same issue.

**Comment by peti** [comment]
This bug is still present in current Git versions of Cabal 1.25.0.0. 😞

**Comment by sopvop** [comment]
I think [this](https://github.com/haskell/cabal/blob/2a8e8535571ca246b760a0ddaa75f0eeb39a401e/Cabal/Distribution/Parsec/Types/FieldDescr.hs#L133) is a the relevant line for Parsec based parser.
And [this one](https://github.com/haskell/cabal/blob/2a8e8535571ca246b760a0ddaa75f0eeb39a401e/Cabal/Distribution/ParseUtils.hs#L249) is for current parser.
I think conditionally adding quotes on `any isSpace` predicate should fix this problem.
