### ISSUE TITLE
Doesn't notice changes in .cabal/config until reconfigure

### ISSUE THREAD

**Issue by gitfoxi** [haskell/cabal#2662]
`cabal build` fails because it can't find a library so I update ~/.cabal/config with

```
extra-lib-dirs: /usr/local/lib
```

`cabal build` continues to fail. Eventually I figure out I need to run `cabal configure` which is something I never knew about because `cabal build` always ran it for me. Desirable behavior would be for `cabal build` to detect that `~/.cabal/config` has changed and rerun `cabal configure` in that case.

**Comment by andreasabel** [comment]
> Desirable behavior would be for `cabal build` to detect that `~/.cabal/config` has changed and rerun `cabal configure` in that case.

Anecdotally, this seems to be the case now.
I added `extra-lib-dirs` and `extra-include-dirs` and even _all dependencies_ were rebuild (this seems to be going to far, but better than not retrying anything).

Closing, but feel free to add a test case...
