### ISSUE TITLE
Add a 'build from sdist tarball' feature (aka distcheck)

### ISSUE THREAD

**Issue by bos** [haskell/cabal#267]
(Imported from [Trac #274](http://hackage.haskell.org/trac/hackage/ticket/274), reported by guest on 2008-05-07)

I've often seen Darcs repos where the sdist tarball was incomplete, or where a person had a tarball which was incomplete.

I think this is because most people just never use the tarball; if they do ever use it, it's because it's what was downloaded from Hackage. The reason is that doing so is much more complex than 'configure; build; install': you need to configure, create an sdist tarball, cd into dist/; do a tar -xvf or whatever of the correct tarball; cd into _that_ - and then you can configure/build/install. Assuming it is a working tarball.

Now, of course you can automate it. After the first dozen times, I wrote myself a shellscript to do all that for me:

function build_sdist { clean_configure &amp;&amp; sdist &amp;&amp;

<blockquote>
cd dist/ &amp;&amp; untar *.tar.gz &amp;&amp; cd <tt>ls -t ./ | grep "/" | head -n 1</tt> &amp;&amp;
clean_configure &amp;&amp; build &amp;&amp; hinstall; haddock &amp;&amp; hinstall; }

</blockquote>

(This is pretty long and imperfect, but it would be even longer if all the other aliases and function definitions were included; I think they're pretty straightforwardly named though, so I haven't included them.)

It seems to me that this would be, at the very least, a useful adjunct to cabal check - if it makes sense to see whether various fields are filled out sanely, surely it makes sense to see whether needed files are included/listed?

It might be even better to make the normal 'runhaskell Setup build' do it from sdist, but this is harder to code (besides the forgoing, you'd need to copy in the configuration from the top-level, from when the user ran 'runhaskell Setup configure' and added whatever options) and possibly more confusing ("But Foo.hs _is_ there, right there in src/! Why can't Cabal find it?"). So I'd be satisfied to do something like 'cabal checkdist'.
## 

gwern

**Comment by Rufflewind** [comment]
FWIW I often test this by running `sdist` followed by `v1-install` in my CI scripts.

However, it seems v2-install has broken the capability to install from local tarballs:

~~~
$ cabal --version

cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library

$ cabal v2-install --lib /home/someone/blas-hs/dist-newstyle/sdist/foo-0.1.0.0.tar.gz

cabal: Invalid package ID:
/home/someone/blas-hs/dist-newstyle/sdist/foo-0.1.0.0.tar.gz
"<eitherParsec>" (line 1, column 1):
unexpected "/"
~~~

https://github.com/haskell/cabal/issues/6393 is related, but it seems scoped to URLs rather than local paths.

**Comment by Mikolaj** [comment]
Given that #6393 is fixed, perhaps this is a low hanging fruit? Definitely worth a check.

**Comment by fgaz** [comment]
In the meantime, v2-install works too: it currently does a sdist then installs from that (this actually caught errors in cabal files for a lot of people)

**Comment by jneira** [comment]
yeah, cabal install can install tarballs directly too, so i think we can close this as the feature has been implmented (although not under a `distcheck`)
