### ISSUE TITLE
Remember hackage credentials

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#2672]
Every time I upload a package to hackage I have to enter my credentials.

Modern operating systems have a secure credential store (eg. Keychain on OS X) which is used by many desktop applications. Even commandline applications tap into it (git for example via the external credentials helpers).

**Comment by 23Skidoo** [comment]
You can set username and password in `~/.cabal/config`, but it's plain text.

**Comment by 23Skidoo** [comment]
Also see #2506, which added an option for `cabal upload` to read password from arbitrary command output.

**Comment by expipiplus1** [comment]
The settings in `~/.cabal/config` are called `username` and `password`
