### ISSUE TITLE
Cabal Fails to find ar when it is not named 'ar'

### ISSUE THREAD

**Issue by Boxfire** [haskell/cabal#2673]
On a system where the gcc is explicitly prefixed, i.e. x86_64-pc-linux-gnu-ar or i686-pc-linux-gnu-ar etc Cabal fails to find 'ar', and setting ~/.cabal/config to have ar-location point directly to the explicitly named ar program fails to find it. Cabal simply expects it to be named 'ar' in all cases.

In https://github.com/haskell/cabal/blob/49dba823de44584babc4d5bfcdd7673582b08436/Cabal/Distribution/Simple/Program/Builtin.hs#L269

we can see the program must be named "ar". This needs to be configurable to support prefixed systems.

**Comment by phadej** [comment]
it is.
setting 
```
program-locations
  -- alex-location:
  ar-location: /usr/local/bin/my-very-own-ar
```

in `cabal.config`

results into
```

```
% /Users/ogre/Coding/other-haskell/cabal/.stack-work/install/x86_64-osx/ghc-7.10/7.10.2/bin/cabal configure -v2
...
Using ar given by user at: /usr/local/bin/my-very-own-ar
...
```

**Comment by Boxfire** [comment]
I believe you are correct. For whatever reason I did not have success setting ar-location before, but it must have been specific to my systems. Sorry about that.

**Comment by phadej** [comment]
:+1:, Please report if problem reoccurs.
