### ISSUE TITLE
Need `extra-include-dirs` in cabal file

### ISSUE THREAD

**Issue by lukehoersten** [haskell/cabal#2674]
There's no way to specify `extra-include-dirs` in a cabal file like there is `extra-lib-dirs`. The `--extra-include-dirs` flag is available on the cabal command line so it seems incomplete to not make it available in the cabal file.

**Comment by bitemyapp** [comment]
Good catch :+1: 

This seems a good one unless there were good reasons for not doing it to begin with.

**Comment by hawkish** [comment]
I would also very much like the extra flag available. OpenSSL dependencies on OSX with cabal needs it.

**Comment by bitemyapp** [comment]
@ttuegel is this perhaps not a good idea because different build environments could be different? Is it possible for lib/include dirs passed via the command-line to take precedence somehow? Seems potentially tricky unless you let the Cabal file demand a particular build env.

**Comment by 23Skidoo** [comment]
Related: #2641.

**Comment by jneira** [comment]
With v2 commands you can set `extra-include-dirs` in the cabal.project file, from [docs](https://cabal.readthedocs.io/en/stable/cabal-project.html#cfg-field-extra-include-dirs):

> Using this option has the same affect as appending the directory dir to the [include-dirs](https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-include-dirs) field in each library and executable in the package’s .cabal file. The advantage of course is that you do not have to modify the package at all. These extra directories will be used while building the package and for libraries it is also saved in the package registration information and used when compiling modules that use the library.

It would ne not available when building from hackage but i am not sure if include dirs is amenable to be shared viahackage, as noted above

@lukehoersten would be the cabal.project alternative good enough for your use case?

**Comment by jneira** [comment]
* We have #2641, which imo summarizes the problems with relative paths and the interaction with ghc-pkg and list the possible actions to fix or improve the situation
* So i am gonna close this one, feel free to reopen (or ask to do it) if you think there is some value in keeping it opened
