### ISSUE TITLE
cabal user-config behaves inconsistently when a non-default config file is specified

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#2679]
`cabal --config-file=my-config user-config update` merges my-config with a newly generated config file and then writes it to ~/.cabal/config .  It seems like user-config should write to the same file that it merges, whether it is my-config or ~/.cabal/config.

Modifying user-config so that it writes to the config file specified by CABAL_CONFIG or --config-file has the added benefit of allowing the feature's tests to write to a config file that is not in the home directory.  Then the tests can set CABAL_CONFIG instead of HOME in order to run on Windows (Issue #2678).

Would you like a pull request allowing user-config to write to a non-default config file?

**Comment by 23Skidoo** [comment]
> Would you like a pull request allowing user-config to write to a non-default config file?

Sure!

**Comment by grayjay** [comment]
Fixed by #2684.
