### ISSUE TITLE
Cabal install on Windows fails

### ISSUE THREAD

**Issue by travelbasys** [haskell/cabal#2682]
Cabal fails to install certain packages on Windows.
I have <b>HaskellPlatform-2014.2.0.0-i386-setup.exe</b> installed under an admin account.

See what happens: (after some slight editing)

    C:\>ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

    C:\>cabal --version
    cabal-install version 1.22.6.0
    using version 1.22.4.0 of the Cabal library

    C:\>cabal install cantor
    Resolving dependencies...
    Configuring hxt-charproperties-9.2.0.1...
    Building hxt-charproperties-9.2.0.1...
    Failed to install hxt-charproperties-9.2.0.1
    Build log ( %Userprofile%\Anwendungsdaten\cabal\logs\hxt-charproperties-9.2.0.1.log ):
    setup-Simple-Cabal-1.22.4.0-i386-windows-ghc-7.8.3.exe: 
    Run the 'configure' command first.
    cabal: Error: some packages failed to install:
    cantor-0.4 depends on hxt-charproperties-9.2.0.1 which failed to install.
    hxt-9.3.1.15 depends on hxt-charproperties-9.2.0.1 which failed to install.
    hxt-charproperties-9.2.0.1 failed during the building phase. The exception was:
    ExitFailure 1
    hxt-regex-xmlschema-9.2.0.2 depends on hxt-charproperties-9.2.0.1 which failed to install.
    hxt-unicode-9.0.2.4 depends on hxt-charproperties-9.2.0.1 which failed to install.
    hxt-xpath-9.1.2.2 depends on hxt-charproperties-9.2.0.1 which failed to install.

    C:\>path
    PATH=%ProgramFiles%\Haskell\bin;
    %ProgramFiles%\Haskell Platform\2014.2.0.0\lib\extralibs\bin;
    %ProgramFiles%\Haskell Platform\2014.2.0.0\bin;
    C:\WINDOWS\system32;
    C:\WINDOWS;
    %ProgramFiles%\Haskell Platform\2014.2.0.0\mingw\bin;
    %AppData%\cabal\bin;
    %AllUsersProfile%\Programs\wscite-1.79
I found similar issues like this one in this forum and on Stackoverflow.
Each one containing: <b>Run the 'configure' command first.</b>.
But I was not able to understand what I can do.
Thanks for any help.

**Comment by kolmodin** [comment]
Can you post the contents of the build log? The log you posted says it should be located here `%Userprofile%\Anwendungsdaten\cabal\logs\hxt-charproperties-9.2.0.1.log`.

In the case of the bug reported on [Stackoverflow](http://stackoverflow.com/questions/27627010/linker-cant-find-parsec-library), it's about the linker not finding the `parsec` library even though `ghc-pkg` says `parsec` is installed.

**Comment by travelbasys** [comment]
Sorry for the delay.
Can't reproduce.
But I am pretty sure the log contained a single line only:

    Run the 'configure' command first.

But the Cantor package was changed and has issues now: missing modules.
So i am closing this item now.

Thanks.
