### ISSUE TITLE
Config jobs: $ncpus doesn't work on DragonflyBSD

### ISSUE THREAD

**Issue by cgag** [haskell/cabal#2688]
Probably a problem on FreeBSD as well.  The number of jobs seems to be getting set to 1 despite having 4 cpus, everything works fine if I manually set it to 4.

**Comment by 23Skidoo** [comment]
The code that is used to find the number of cores is in [`cbits/getnumcores.c`](https://github.com/haskell/cabal/blob/master/cabal-install/cbits/getnumcores.c). On GHC > 6.12 we use the `getNumberOfProcessors` function from GHC RTS.

Which version of GHC was your `cabal-install` exe compiled with?

**Comment by cgag** [comment]
Ah, 7.8.3, maybe it's fixed in later versions.

**Comment by 23Skidoo** [comment]
In GHC HEAD the POSIX version of this function looks [like this](https://github.com/ghc/ghc/blob/c5911479f295242e16e396eb5d1369f2e4ce8de0/rts/posix/OSThreads.c#L236) (there's a separate Win32 implementation). Looks like it works on FreeBSD at least. If it doesn't work on your OS, please [file a ticket on the GHC bug tracker](https://ghc.haskell.org/trac/ghc/wiki/ReportABug).
