### ISSUE TITLE
Include headers directory of Mac framework

### ISSUE THREAD

**Issue by mtolly** [haskell/cabal#2689]
In https://github.com/phaazon/al/pull/6 I noticed that including a framework on OS X like

```
frameworks: OpenAL
```

does not include the framework's headers (so that either `c2hs` or a C file listed in `c-sources` can see them). I also needed to add

```
include-dirs: "/System/Library/Frameworks/OpenAL.framework/Headers/"
```

Seems like this could be done automatically.

**Comment by 23Skidoo** [comment]
Reopening, see https://github.com/haskell/cabal/pull/2739#issuecomment-125795165.

**Comment by christiaanb** [comment]
I don't think this should be done automatically. For example, CMake doesn't do it automatically: http://www.cmake.org/Wiki/CMake:HowToUseExistingOSXFrameworks

As you can see on the above link, the OpenAL includes on:
- Linux : `#include <AL/al.h>`
- OS X: `#include <OpenAL/al.hs>`
- Windows: `#include <al.h>`

Indeed, if I replace all `#include <al.h>` by `#include <OpenAL/al.h>` in the sources, the `al` Haskell package compiles just fine on OS X _without_ the extra `include-dirs`.

**Comment by rwbarton** [comment]
For a quick introduction to frameworks see https://ghc.haskell.org/trac/ghc/wiki/OSXFrameworks, which explains how `<OpenAL/al.h>` gets mapped to a file in the OpenAL framework.

**Comment by mtolly** [comment]
That does make a lot more sense, sorry for the confusion! I'll reedit `al` to CPP-select the headers in that fashion then.

**Comment by lukexi** [comment]
Howdy! Can we cherry-pick https://github.com/haskell/cabal/commit/f0d5cdde14a85e33e0d0af4260b41bbc014c61a2 into 1.22 to make it into the 7.10.3 release? Thanks!

**Comment by 23Skidoo** [comment]
@lukexi Care to make a pull request?

**Comment by 23Skidoo** [comment]
@lukexi Care to make a pull request?
