### ISSUE TITLE
cabal test compile times absurdly slow

### ISSUE THREAD

**Issue by mikeizbicki** [haskell/cabal#2690]
On [this project](http://github.com/mikeizbicki/subhask), running `cabal test` causes GHC to take more than 10 minutes to compile and use more than 3G of ram.  If I run GHC manually, compile time is less than 10 seconds and only 300M of ram is used.

**Comment by kolmodin** [comment]
Possibly different flags are used when invoking GHC.
`cabal test -v` will output which flags it uses to compile the tests.
Can you say which flags you use when you compile manually?

When you invoke GHC manually, do you build against a preinstalled `subhask` library, or do you compile the whole project?

**Comment by mikeizbicki** [comment]
Thanks.  Adding the `-v` flag I see that `cabal test` invokes ghc with `-O` when I specifically don't want it to.  Is there a way to modify the cabal file to prevent cabal from adding this flag?

**Comment by kolmodin** [comment]
In your [`.cabal` file](https://github.com/mikeizbicki/subhask/blob/master/subhask.cabal) you've set
```
    ghc-options:
        -O
```
for your test suite `TestSuite`. IIRC `-O` is already the default for cabal, so there's no need to add this explicitly.
If you want to override the optimisation flag, you can put your new value into the `.cabal` file instead. `-O0` most often makes the compilation faster.

**Comment by mikeizbicki** [comment]
In a different branch I had removed the `-O` hoping to remove optimizations, but it was still passing it.  Adding `-O0` disabled the optimizations though, speeding up the build.

Thanks a ton for the help!

**Comment by kolmodin** [comment]
You're welcome :)
