### ISSUE TITLE
Unable to install packages added via 'cabal sandbox add-source' located inside cabal repo folder

### ISSUE THREAD

**Issue by aemixdp** [haskell/cabal#2701]
I've fetched a package, unarchieved it in the same folder, made a minor modification to fix it, added as source, and tried to install into sandbox of my project:

```
$ cabal sandbox init
$ cabal sandbox add-source ../tagsoup-parsec
$ cabal install tagsoup-parsec
```

And here is what I got:

```
Resolving dependencies...
Notice: installing into a sandbox located at C:\hs\...\.cabal-sandbox
Configuring tagsoup-parsec-0.0.8...
Building tagsoup-parsec-0.0.8...
Failed to install tagsoup-parsec-0.0.8
Build log ( C:\hs\...\.cabal-sandbox\logs\tagsoup-parsec-0.0.8.log ):
Building tagsoup-parsec-0.0.8...
Preprocessing library tagsoup-parsec-0.0.8...
[1 of 1] Compiling Text.HTML.TagSoup.Parsec ( Text\HTML\TagSoup\Parsec.hs, dist\dist-sandbox-372bbaea\build\Text\HTML\Ta
gSoup\Parsec.o )
C:\Users\...\AppData\Local\Programs\minghc-7.10.1-x86_64\ghc-7.10.1\mingw\bin\ar.exe: dist/dist-sandbox-372bbaea\build\
libHStagsoup-parsec-0.0.8-JQq2ZmGXYwD0r1wqsxPw15.a-256\libHStagsoup-parsec-0.0.8-JQq2ZmGXYwD0r1wqsxPw15.a: No such file
or directory
cabal.exe: Error: some packages failed to install:
tagsoup-parsec-0.0.8 failed during the building phase. The exception was:
ExitFailure 1
```

However, if I move the extracted folder to other location before adding as source, everything works fine.
System info:

```
$ gwmi win32_operatingsystem | select caption
Microsoft Windows 7 Ultimate

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1

$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
```

**Comment by aemxdp** [comment]
This tagsoup-parsec package wasn't compiling for me as-is, so I thought this may be related to the fact I unpacked the package to done some changes before trying to install, but today I've noticed this happens not only in such cases, but sometimes even with simple cabal install: I've tried installing ghc-mod and packages data-default-instances-containers-0.0.1 and data-default-instances-old-locale-0.0.1 failed with same error. After unpacking them outside they install just fine without any modifications.

**Comment by phadej** [comment]
sandbox functionality is removed.
