### ISSUE TITLE
Add support for `-g` option

### ISSUE THREAD

**Issue by bitonic** [haskell/cabal#2702]
`-g` builds libraries with DWARF symbols, but it's quite awkward to use it:

```
cabal install --disable-library-stripping --ghc-options="-g -rtsopts"
```

I think we should have a flag that automatically does the above.

Moreover, I'd also like a flag that stores the downloaded source, so that the debug symbols will refer to sources which still exist.

**Comment by cartazio** [comment]
i think you can add that to your ~/.cabal/config file as a default ghc options flag

**Comment by 23Skidoo** [comment]
This seems to be already implemented (fbf84997fdb7881e90210bb13bb129f067beac47). Try `cabal install --disable-library-stripping --enable-debug-info`.

/cc @tibbe

**Comment by bitonic** [comment]
OK, I'd still like the second part to happen:

> Moreover, I'd also like a flag that stores the downloaded source, so that the debug symbols will refer to sources which still exist.

It's extremely nice to get `perf` output side-by-side to the Haskell source.

**Comment by bitonic** [comment]
Also, I'd say that `--enable-debug-info` should automatically disable library stripping, if that's not the case already.

**Comment by 23Skidoo** [comment]
Yes, makes sense.

**Comment by mpickering** [comment]
Just to point out that `debug-info` doesn't imply `--disable-library-stripping` still, which makes `debug-info` on its own rather useless. If someone points me to the right file then I will prepare a patch.

**Comment by bubba** [comment]
@mpickering see also this TODO left here https://www.haskell.org/cabal/users-guide/nix-local-build.html#cfg-field-executable-stripping

**Comment by 23Skidoo** [comment]
@mpickering Good place to start is running `rg stripLib` and `rg stripExe`. We should also add a warning to `cabal-install` that fires when the user **explicitly** enables both `[library,executable]-stripping: True` and `debug-info: True` in the config file.

I think that normally one will want to either enable `debug-info` on per-project basis, or enable it system-wide just for libraries and use the default (strip exes) for exes `cabal install`ed system-wide. So perhaps we need a separate `library-debug-info` option?

**Comment by mpickering** [comment]
@23Skidoo It seems the natural place to implement this is `Cabal.Distribution.Simple.Configure.configure` but by that point we have lost the knowledge about how the option came to be set. Where is the right place to implement warnings about things found in `cabal.project` files?

**Comment by mpickering** [comment]
`defaultConfigFlags` also seems to set the default to `Flag True` rather than `NoFlag`. 

Unless there is a similar warning I can look at to see where to implement this check it seems like a lot of untangling to implement the logic where a warning happens if the user has explicitly set the option.

**Comment by mpickering** [comment]
Is this patch actually a good idea? It was only on `v2-install` that the executables were stripped. Now with this patch there's no way to strip executables when they are installed. Executables built with `v2-build` didn't get stripped.

**Comment by 23Skidoo** [comment]
> Now with this patch there's no way to strip executables when they are installed. 

You mean, if you have `debug-info: True` in `.cabal/config`?

**Comment by mpickering** [comment]
Yes if you set `debug-info: 3` in a global setting.
