### ISSUE TITLE
GZipUtils unit test failure

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#2704]
When I run the cabal-install unit tests I get one failure.  I am using zlib-0.5.4.2 and version 1.2.8 of the zlib C library.  The failure started in commit fd64fce1887a4632ad7f5b483234902b26f8e894, which is when the test was added.

    Test suite unit-tests: RUNNING...
    Unit Tests
      UnitTests.Distribution.Client.UserConfig
        nullDiffOnCreate:          OK (0.01s)
        canDetectDifference:       OK
        canUpdateConfig:           OK
        doubleUpdateConfig:        OK
      Distribution.Client.Sandbox
        sandboxBinDirOnSearchPath: OK
        oldSearchPathRestored:     OK
      Distribution.Client.Targets
        readUserConstraint:        OK
        parseUserConstraint:       OK
        readUserConstraints:       OK
      Distribution.Client.GZipUtils
        maybeDecompress:           OK
        decompress plain:          FAIL
          *** Failed! Exception: 'Codec.Compression.Zlib: premature end of compressed stream' (after 1 test): 
          []
          Use --quickcheck-replay '0 TFGenR 0000000E8566AA1300000000000F4240000000000000DF7700000009502F9000 0 1 1 0' to reproduce.
        decompress zlib:           OK
          +++ OK, passed 100 tests.
        decompress gzip:           OK
          +++ OK, passed 100 tests.
      UnitTests.Distribution.Client.Dependency.Modular.PSQ
        splitsAltImplementation:   OK
          +++ OK, passed 100 tests.
    ...

**Comment by phadej** [comment]
I actually checked with some 0.5.x version, it worked. i'll recheck check on Monday
