### ISSUE TITLE
package-tests do not work with stack

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2711]
Steps to reproduce: run `stack test` in Cabal.

Actual result:

```
Cabal-1.23.0.0: test (suite: package-tests)
package-tests: dist: canonicalizePath: does not exist (No such file or directory)
```

OK, so let's set `CABAL_BUILDDIR` explicitly, like ` env CABAL_BUILDDIR=.stack-work/dist/x86_64-linux/Cabal-1.22.2.0/ stack test`. Then we get:

```
    expected: 'setup install' should succeed
      output: "/home/hs01/ezyang/cabal-edge/Cabal/tests/Setup configure --user -w /bin/ghc" in 
PackageTests/BuildDeps/InternalLibrary2/to-install
    Configuring InternalLibrary2-0.1...
    Setup: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
    Cabal. Use the flag --package-db to specify a package database (it can be used
    multiple times).
```

**Comment by 23Skidoo** [comment]
Patches welcome.

**Comment by ezyang** [comment]
An adequate workaround is to call the test executable directly with `CABAL_BUILDDIR`, e.g. `env CABAL_BUILDDIR=.stack-work/dist/x86_64-linux/Cabal-1.22.2.0/ .stack-work/dist/x86_64-linux/Cabal-1.22.2.0/build/package-tests/package-tests`

**Comment by ezyang** [comment]
I have a better idea, which is to use the executable name of the package tests to infer the build directory.

**Comment by ttuegel** [comment]
@ezyang You can work around this by running `stack exec --no-ghc-package-path stack test`.
