### ISSUE TITLE
Cannot find new Cabal version after update

### ISSUE THREAD

**Issue by travelbasys** [haskell/cabal#2713]
I use <b>HaskellPlatform-2014.2.0.0-x86_64-setup</b> for Haskell on Windows 7.
After that I update Cabal running <tt>cabal update</tt> followed by <tt>cabal install cabal-install</tt>.
But the newly installed Cabal version is not found.

I did not make any manual changes to the path variable as the Platform installer left it.
Here is the log:

    C:\tmp>ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3
    
    C:\tmp>cabal --version
    cabal-install version 1.18.0.5
    using version 1.18.1.3 of the Cabal library
    
    C:\tmp>cabal update
    Config file path source is default config file.
    Config file %userprofile%\AppData\Roaming\cabal\config not found.
    Writing default configuration to %userprofile%\AppData\Roaming\cabal\config
    Downloading the latest package list from hackage.haskell.org
    Note: there is a new version of cabal-install available.
    To upgrade, run: cabal install cabal-install
    
    C:\tmp>cabal install cabal-install
    Resolving dependencies...
    Downloading Cabal-1.22.4.0...
    Configuring Cabal-1.22.4.0...
    Building Cabal-1.22.4.0...
    Installed Cabal-1.22.4.0
    Downloading cabal-install-1.22.6.0...
    Configuring cabal-install-1.22.6.0...
    Building cabal-install-1.22.6.0...
    Installed cabal-install-1.22.6.0
    
    C:\tmp>cabal --version
    cabal-install version 1.18.0.5
    using version 1.18.1.3 of the Cabal library
    
    C:\tmp>where cabal
    %userprofile%\Bin\HaskellPlatform\2014.2.0.0\lib\extralibs\bin\cabal.exe
    %userprofile%\AppData\Roaming\cabal\bin\cabal.exe
    
Installing the new version did *not* update the old location of cabal.exe in <tt>extralibs</tt>.
Instead, the new version is placed into <tt>AppData</tt>. This location, unfortunately, is hidden behind
<tt>extralibs</tt>, as the Platform installer decided.

Either one has to manually reorganize one's path or to delete or rename one's old cabal version.
It would be helpful and avoid irritation if that could be fixed in the Platform distribution and/or in Cabal's install.
Thanks.

**Comment by 23Skidoo** [comment]
Not a Cabal bug. This has been a known issue with the Windows HP installer for quite some time, don't know whether it's fixed or not.
