### ISSUE TITLE
Remove Cabal's support for non-GHC compilers

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2714]
Does anyone actually use/test Cabal on non-GHC? Axing the other compilers would simplify the code a bit.

**Comment by 23Skidoo** [comment]
GHCJS probably doesn't count as non-GHC. Other than that, we support only JHC, LHC, UHC and HaskellSuite. They all seem to be more or less active, so I guess we should ask on their mailing lists first.

**Comment by 23Skidoo** [comment]
LHC seems to use HaskellSuite now, so the LHC-specific code in Cabal is probably safe to remove.

**Comment by ezyang** [comment]
Conversely, can we get the Travis suites running with the other compilers we actually support, so that we are less likely to break the other compilers.

**Comment by Blaisorblade** [comment]
FWIW: last commit on https://github.com/jimcrayne/jhc was in 2015, https://mail.haskell.org/pipermail/jhc/ is pretty dead and https://github.com/ajhc/ajhc (which funded development of a JHC fork, later merged) shut down. Yet JHC support is still in.

(I googled the topic because of https://www.reddit.com/r/haskell/comments/8ll3sh/dear_haskell_its_not_you_its_your_tooling/dzhs9ms/).

**Comment by 23Skidoo** [comment]
LHC-specific code has been recently removed in favour of HaskellSuite.

**Comment by BardurArantsson** [comment]
I think I'd be up for doing the work this weekend, so:

Would removing the rest of the non-GHC/GHCJS compilers have a chance of being merged?

**Comment by 23Skidoo** [comment]
HaskellSuite code is used by LHC, which is active. UHC looks moribund, JHC looks dead -- let's remove these two and see if anyone complains.

**Comment by phadej** [comment]
UHC has small activity, see https://github.com/UU-ComputerScience/uhc

**Comment by BardurArantsson** [comment]
How maby packages are likely to work with UHC?

--
  Bardur Arantsson
  bardur@scientician.net



On Fri, May 25, 2018, at 16:05, Oleg Grenrus wrote:
> UHC has small activity, see https://github.com/UU-ComputerScience/uhc> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/haskell/cabal/issues/2714#issuecomment-392068759

**Comment by 23Skidoo** [comment]
Yep, that's what I meant by "moribund".

**Comment by BardurArantsson** [comment]
Oh, right, sorry @23Skidoo hadn't noticed your reply. I was on mobile up until just now :)

I'll try to prepare a PR this weekend.

**Comment by phadej** [comment]
I tried to compile QuickCheck with UHC, and succeed a year ago.

**Comment by BardurArantsson** [comment]
So that's... one, I suppose? :)

**Comment by 23Skidoo** [comment]
@BardurArantsson BTW, if you do this, please make two separate commits, one for UHC, and one for JHC, so that we could revert them separately if someone complains.

**Comment by BardurArantsson** [comment]
Yes, of course, though it's going to be a bit annoying to revert the "wrong" (earlier in the commit history). I'm doing JHC first -- hopefully that's pretty uncontroversial.

**Comment by quasicomputational** [comment]
Is it worth sending a message to haskell-cafe asking for any users to come in and pipe up on this issue?

**Comment by BardurArantsson** [comment]
I'll just close this as it seems it's not really going to happen -- see the discussion on #5347 .

**Comment by tom-bop** [comment]
Fwiw I don't know that the github repo linked above is the right place for JHC -- it seems http://repetae.net/repos/jhc/ (whose last update was 2017) is the main repo (linked from http://repetae.net/computer/jhc/development.shtml)
