### ISSUE TITLE
Missing warning when constraint is not used

### ISSUE THREAD

**Issue by asr** [haskell/cabal#2719]
I lost some time using the command

```bash
$ cabal install foo --constraint=trasformers==0.4.3.0
```
after I realised that there was a typo in `trasformers`. I warning like

```bash
the constraint trasformers==0.4.3.0 was not used
```
would have been very useful.

**Comment by kosmikus** [comment]
Yes, I guess this would be useful to have. This makes more sense to be outside of the solver, really, as it needs nothing of the solver machinery, and would work exactly the same for all solvers. It should also be rather easy to do, so it would be a good ticket for new contributors.

**Comment by 23Skidoo** [comment]
> This makes more sense to be outside of the solver

Hmm, yes, one could either check that all constraints refer to valid package names, or check that the install plan contains all packages named in constraints.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
A new command-line option for making warnings into errors (for example, `-Werror` in GHC) is not a good idea since the warning

```bash
Warning: Note that reinstalls are always dangerous. Continuing anyway...
```

is very common. For this reason, I think the new warning added after fixing this issue should be rather an error.
