### ISSUE TITLE
cabal upload should automatically find tarball to upload

### ISSUE THREAD

**Issue by bos** [haskell/cabal#272]
(Imported from [Trac #279](http://hackage.haskell.org/trac/hackage/ticket/279), reported by guest on 2008-05-14)

Cabal-upload is a nice enough tool, but it doesn't have a good default: it just errors out if not specifically told exactly where to find a tarball.

I think this could be smarter. cabal-upload will almost always be run in the top level of a cabal package. A much better default would be: if no arguments are given, cabal-upload looks in dist/ and if there is an appropriate tarball in it, uploads it.

Smarter possibilities:
* if there are multiple tarballs, instead of bailing out, cabal-upload just picks the highest numbered one.
* before looking in dist/, do a runhaskell Setup sdist.

--
gwern

**Comment by feuerbach** [comment]
Note: this is already addressed in stackage-upload https://www.reddit.com/r/haskell/comments/344dig/announcing_stackageupload/cqr6mvv

**Comment by 23Skidoo** [comment]
@hvr [writes on Reddit](https://www.reddit.com/r/haskell/comments/344dig/announcing_stackageupload/cqrcm7o):

> With my Trustee hat on, I'm a bit worried about promoting the workflow of uploading packages straight from the current source-repo w/o any --non-candidate flag failsafe to make it a conscious choice.

> This means more work for Trustees to manually edit .cabal files for packages accidentally uploaded broken that didn't pass basic QA...

**Comment by BardurArantsson** [comment]
Please see my comments on https://github.com/haskell/cabal/issues/2253

I think they completely supercede this issue. If you agree, please close this one.

**Comment by ezyang** [comment]
OK I agree, closing this one.
