### ISSUE TITLE
Instructions in HACKING.md do not work

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#2720]
If I follow the exact instructions, the process fails during the build of cabal-install due to missing test dependencies.

I don't know if it's the right fix, but adding `--enable-tests` to the "cabal install --only-dependencies" line in step 2 (for `cabal-install`) seems to fix it.

**Comment by lspitzner** [comment]
right; that should be the correct fix. i'll write a pr later to also add -Werror.

**Comment by BardurArantsson** [comment]
OK, I'll submit a quick PR for --enable-tests, should be trivial via the GitHub interface
