### ISSUE TITLE
Error encountered when I run 'cabal install cabal-install'

### ISSUE THREAD

**Issue by kshitijmeets** [haskell/cabal#2726]
Here are the first few lines of the error:

```
Preprocessing executable 'cabal' for cabal-install-1.22.6.0...
[ 1 of 77] Compiling Distribution.Client.Dependency.Modular.Version ( Distribution\Client\Dependency\Modular\Version.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Dependency\Modular\Version.o )
[ 2 of 77] Compiling Distribution.Client.Dependency.Modular.PSQ ( Distribution\Client\Dependency\Modular\PSQ.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Dependency\Modular\PSQ.o )
[ 3 of 77] Compiling Distribution.Client.Dependency.Modular.Package ( Distribution\Client\Dependency\Modular\Package.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Dependency\Modular\Package.o )
[ 4 of 77] Compiling Distribution.Client.Compat.ExecutablePath ( Distribution\Client\Compat\ExecutablePath.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Compat\ExecutablePath.o )
[ 5 of 77] Compiling Distribution.Client.Haddock ( Distribution\Client\Haddock.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Haddock.o )
[ 6 of 77] Compiling Distribution.Client.Compat.Environment ( Distribution\Client\Compat\Environment.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Compat\Environment.o )
[ 7 of 77] Compiling Distribution.Client.PackageUtils ( Distribution\Client\PackageUtils.hs, dist\build\cabal\cabal-tmp\Distribution\Client\PackageUtils.o )
```

**Comment by kshitijmeets** [comment]
Sorry guys...pasted wrong part of the log.....here is the actual error:

[77 of 77] Compiling Main             ( Main.hs, dist\build\cabal\cabal-tmp\Main.o )
Linking dist\build\cabal\cabal.exe ...
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x26a6): undefined reference to `shutdownWinSock'
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x2fae): undefined reference to `shutdownWinSock'
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x300b): undefined reference to `initWinSock'
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x3156): undefined reference to `shutdownWinSock'
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x393e): undefined reference to `shutdownWinSock'
C:\Users\kshitij\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\HTTP-4000.2.19/libHSHTTP-4000.2.19.a(TCP.o):fake:(.text+0x399b): undefined reference to `initWinSock'

**Comment by 23Skidoo** [comment]
Something to do with the `network` library. @tibbe, does this look familiar?

**Comment by tibbe** [comment]
@23Skidoo doesn't sound familiar. @ndmitchell did make some changes recently (e.g. https://github.com/haskell/network/commit/69739c176483602bc1ec8432b5a1cadb1516e574). Does the HTTP lib explicitly mention any of these functions and e.g. rely on network having them internally?

**Comment by ndmitchell** [comment]
@23Skidoo - which version of network are you on? Curious to see if it includes my changes or not.

**Comment by ndmitchell** [comment]
I deleted shutdown, but left init present, so would have expected only the shutdown error if it was related to my changes.

**Comment by 23Skidoo** [comment]
@ndmitchell 
> @23Skidoo - which version of network are you on?

I think you wanted to address @kshitijmeets.

@tibbe
> Does the HTTP lib explicitly mention any of these functions and e.g. rely on network having them internally?

Doesn't look like it.

**Comment by 23Skidoo** [comment]
Optimistically closing, please reopen if this still occurs.
