### ISSUE TITLE
GHC Panic: Loading temp shared object failed with `--enable-coverage` option

### ISSUE THREAD

**Issue by mrkkrp** [haskell/cabal#2757]
Please see this [StackOverflow question and answer](http://stackoverflow.com/questions/31937302/ghc-panic-loading-temp-shared-object-failed) for comprehensive description.

In short, when test coverage (via HPC) is enabled and cabal repl is started for non-test build target you get a ghc panic.

**Comment by 23Skidoo** [comment]
"GHC panic" usually means that this is a GHC bug. Try the GHC bug tracker.

/cc @ttuegel

**Comment by mrkkrp** [comment]
@23Skidoo, OK, feel free to close this issue if you think it doesn't belong here.

**Comment by 23Skidoo** [comment]
Corresponding GHC ticket: http://ghc.haskell.org/trac/ghc/ticket/10765

**Comment by mrkkrp** [comment]
@23Skidoo, according to the [last comment in the ticket](https://ghc.haskell.org/trac/ghc/ticket/10765#comment:2), this is a Cabal issue.
