### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by eamsden** [haskell/cabal#2760]
For those running private repositories HTTPS would help ensure security. Cabal should be able to update and download packages over HTTPS, especially to protect HTTP authentication information (#2761)

**Comment by 23Skidoo** [comment]
HEAD supports HTTPS, implemented using curl/wget and PowerShell.

**Comment by eamsden** [comment]
@23Skidoo commits b780cc77ddf77ec8cdadb511f4e0adfb0962d9c7, 36e9e6222916f30a6336b6902e977392b3496b41, and 4a4964a69f0a815ef1a4f8c5fc4cabe2e52e5067 right?

**Comment by 23Skidoo** [comment]
Yes.

**Comment by 23Skidoo** [comment]
Closing as a duplicate of #936.
