### ISSUE TITLE
http-transport: wget with password in repo URL sends "..." as password

### ISSUE THREAD

**Issue by eamsden** [haskell/cabal#2763]
When authentication information is included in the repo url, i.e.
`https://<user>:<pw>@<hostname>/`
and cabal is configured with `http-transport: wget` the URL passed to wget has the password component replaced by `...`

**Comment by 23Skidoo** [comment]
This was fixed by #2890, though other transports still use `show uri`. We should support this directly by adding per-repo `username` and `password` fields instead (#2761).
