### ISSUE TITLE
Add http support to `cabal sandbox add-source`

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2769]
This would be particularly convenient in combination with Hackage's candidate feature, as then you could e.g.

```
cabal sandbox add-source http://hackage.haskell.org/package/lzma-0.0.0.0/candidate/lzma-0.0.0.0.tar.gz
```

and then  `cabal` could keep track of the `etag` to detect if the package needs to be redownloaded and rebuilt...

**Comment by 23Skidoo** [comment]
So you suggest that it should do a HTTP request for each remote add-source package on each `cabal build`?

**Comment by hvr** [comment]
Yes. This may sound weird at first, but otoh if one doesn't want that behaviour, there's the `add-source --snapshot` flag already available to decouple from filesystem based "upstream" locations. So it'd be only consistent with the existing UI to have http-based tested source-deps tested for freshness as well, IMO.

**Comment by 23Skidoo** [comment]
OK, understood. I considered implementing this for `git://` URLs, but then decided that standard `add-source` and submodules/manual `git pull` work better.

**Comment by hvr** [comment]
In fact, this reminds me about adding some kind of syntax-sugar to `cabal` for Hackage candidates. Specifically something like a `candidate:`-prefix that would expand to a http URL, then one could conveniently say:

```
cabal install candidate:lzma-0.0.0.0

cabal sandbox add-source candidate:lzma-0.0.0.0
```

etc... I think this would increase the value of the Package candidate feature. As right I don't think many users are aware of the package candidate feature, nor that it can be used as a staging area for packages quite easily.

/cc @dcoutts

**Comment by phadej** [comment]
sandbox functionality is removed.
