### ISSUE TITLE
Remove global DB restriction when converting PackageDbStack into ghc/ghc-pkg flags

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2772]
In #2593, we removed the global DB restriction from `getInstalledPackages` for compilers that don't require this restriction. We should also change the function that converts the db stack into ghc/ghc-pkg flags (`D.S.Program.GHC.packageDBArgs`) accordingly. See this comment by @dcoutts: https://github.com/haskell/cabal/pull/2617#issuecomment-107149392.

**Comment by phadej** [comment]
I can check this during this week (no hard promise though).

**Comment by snoyberg** [comment]
Hope you don't mind @phadej, I took a crack at this in #2776.
