### ISSUE TITLE
 Сouldn't find a timestamp record for the given compiler/platform pair.

### ISSUE THREAD

**Issue by remysucre** [haskell/cabal#2784]
When running `cabal build` from `stack exec ...` I got 

```
cabal: Сouldn't find a timestamp record for the given compiler/platform pair.
Please report this on the Cabal bug tracker:
https://github.com/haskell/cabal/issues/new .
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
...
<command line>: cannot satisfy -package-id base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834
```

No idea what's happening.

**Comment by 23Skidoo** [comment]
Can you paste the output of `cabal build -v3`?

**Comment by remysucre** [comment]
It is very long, I hope it doesn't contain sensitive data:

------------------

Using a sandbox located at /home/remy/Genesis/thunk/.cabal-sandbox
Reading available packages...
Reading installed packages...
("/home/remy/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc-pkg",["dump","--package-db=/home/remy/Genesis/thunk/.cabal-sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d","-v0"])
("/home/remy/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc",["--print-libdir"])
Found no modified add-source deps.
Using internal setup method with build-type Simple and args:
["build","--verbose=3","--builddir=dist","--jobs=4"]
Component build order: executable 'thunk'
creating dist/build
creating dist/build/autogen
Building thunk-0.1.0.0...
Preprocessing executable 'thunk' for thunk-0.1.0.0...
Building executable thunk...
creating dist/build/thunk
creating dist/build/thunk/thunk-tmp
Environment:
[("CLUTTER_IM_MODULE","xim"),("COLORTERM","gnome-terminal"),("COMPIZ_CONFIG_PROFILE","ubuntu"),("DBUS_SESSION_BUS_ADDRESS","unix:abstract=/tmp/dbus-H7jfK7AG1h"),("DEFAULTS_PATH","/usr/share/gconf/ubuntu.default.path"),("DESKTOP_SESSION","ubuntu"),("DISPLAY",":0"),("GDMSESSION","ubuntu"),("GDM_LANG","en_US"),("GHC_PACKAGE_PATH","/home/remy/Genesis/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/pkgdb:/home/remy/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/pkgdb:/home/remy/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d"),("GNOME_DESKTOP_SESSION_ID","this-is-deprecated"),("GNOME_KEYRING_CONTROL","/run/user/1000/keyring-SPaGEv"),("GNOME_KEYRING_PID","1958"),("GPG_AGENT_INFO","/run/user/1000/keyring-SPaGEv/gpg:0:1"),("GTK_IM_MODULE","ibus"),("GTK_MODULES","overlay-scrollbar:unity-gtk-module"),("HASKELL_DIST_DIR",".stack-work/dist/x86_64-linux/Cabal-1.18.1.5"),("HASKELL_PACKAGE_SANDBOX","/home/remy/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/pkgdb"),("HASKELL_PACKAGE_SANDBOXES","/home/remy/Genesis/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/pkgdb:/home/remy/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/pkgdb:"),("HOME","/home/remy"),("IM_CONFIG_PHASE","1"),("INSTANCE","Unity"),("JOB","gnome-session"),("LANG","en_US.UTF-8"),("LANGUAGE","en"),("LESSCLOSE","/usr/bin/lesspipe
%s %s"),("LESSOPEN","| /usr/bin/lesspipe
%s"),("LOGNAME","remy"),("LS_COLORS","rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:"),("MANDATORY_PATH","/usr/share/gconf/ubuntu.mandatory.path"),("OLDPWD","/home/remy/Genesis"),("PATH","/home/remy/Genesis/thunk/.cabal-sandbox/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/remy/.cabal/bin"),("PWD","/home/remy/Genesis/thunk"),("QT4_IM_MODULE","xim"),("QT_IM_MODULE","ibus"),("QT_QPA_PLATFORMTHEME","appmenu-qt5"),("SELINUX_INIT","YES"),("SESSIONTYPE","gnome-session"),("SHELL","/bin/bash"),("SHLVL","1"),("SSH_AUTH_SOCK","/run/user/1000/keyring-SPaGEv/ssh"),("STACK_EXE","/usr/bin/stack"),("TERM","xterm"),("TEXTDOMAIN","im-config"),("TEXTDOMAINDIR","/usr/share/locale/"),("UPSTART_EVENTS","started
starting"),("UPSTART_INSTANCE",""),("UPSTART_JOB","unity-settings-daemon"),("UPSTART_SESSION","unix:abstract=/com/ubuntu/upstart-session/1000/1962"),("USER","remy"),("VTE_VERSION","3409"),("WINDOWID","69206028"),("XAUTHORITY","/home/remy/.Xauthority"),("XDG_CONFIG_DIRS","/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg"),("XDG_CURRENT_DESKTOP","Unity"),("XDG_DATA_DIRS","/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/"),("XDG_GREETER_DATA_DIR","/var/lib/lightdm-data/remy"),("XDG_RUNTIME_DIR","/run/user/1000"),("XDG_SEAT","seat0"),("XDG_SEAT_PATH","/org/freedesktop/DisplayManager/Seat0"),("XDG_SESSION_ID","c2"),("XDG_SESSION_PATH","/org/freedesktop/DisplayManager/Session0"),("XDG_VTNR","7"),("XMODIFIERS","@im=ibus"),("_","/usr/bin/stack")]
("/usr/local/bin/ghc",["--make","-no-link","-v","-fbuilding-cabal-package","-O","-j4","-static","-outputdir","dist/build/thunk/thunk-tmp","-odir","dist/build/thunk/thunk-tmp","-hidir","dist/build/thunk/thunk-tmp","-stubdir","dist/build/thunk/thunk-tmp","-i","-idist/build/thunk/thunk-tmp","-i.","-idist/build/autogen","-Idist/build/autogen","-Idist/build/thunk/thunk-tmp","-optP-include","-optPdist/build/autogen/cabal_macros.h","-hide-all-packages","-no-user-package-db","-package-db","/home/remy/Genesis/thunk/.cabal-sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d","-package-db","dist/package.conf.inplace","-package-id","base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834","-XHaskell2010","./Main.hs","-O0","-rtsopts"])
Glasgow Haskell Compiler, Version 7.8.3, stage 2 booted by GHC version 7.4.1
Using binary package database:
/home/remy/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/package.cache
Using binary package database:
/home/remy/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/pkgdb/package.cache
Using binary package database:
/home/remy/Genesis/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/pkgdb/package.cache
Using binary package database:
/home/remy/Genesis/thunk/.cabal-sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d/package.cache
Using package config file: dist/package.conf.inplace
*** Deleting temp files:
Deleting:
*** Deleting temp dirs:
Deleting:
<command line>: cannot satisfy -package-id
base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834
    (use -v for more information)
/usr/local/bin/ghc returned ExitFailure 1

**Comment by 23Skidoo** [comment]
Probably some weird `cabal-install`/`stack` interaction issue. E.g. you may have created a sandbox using one compiler version, then used `stack` to switch to a different one, and `cabal-install` now thinks that your timestamp file is borked.

**Comment by remysucre** [comment]
I guess few people will run cabal inside stack so this might not be too
serious. I was able to get around by running the executable directly
instead of doing `stack exec`. But I'm not sure if other actions may
trigger this error.

**Comment by 23Skidoo** [comment]
Do you have a reproducible test case that triggers this error? Something like `cabal get foo; cd foo; stack exec cabal build`.

**Comment by gbaz** [comment]
closing as obselete
