### ISSUE TITLE
'Distribution.Client.GZipUtils' test sometimes fails

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#2794]
See e.g. [here](https://travis-ci.org/haskell/cabal/jobs/77229990). This is with GHC 7.10.

```
  Distribution.Client.GZipUtils
    maybeDecompress:           OK
    decompress plain:          FAIL
      *** Failed! Falsifiable (after 55 tests and 6 shrinks): 

      [56,79,170,0]

      Use --quickcheck-replay '54 TFGenR 00000000BC6D5FC30000000000009C40000000000000DFAB0000000772FDB280 0 36028797018963967 55 0' to reproduce.
```

/cc @phadej, @edsko

**Comment by phadej** [comment]
```hs
 > maybeDecompress $ BSL.pack  [56,79,170,0]
"x*** Exception: Codec.Compression.Zlib: premature end of compressed stream
```

QuickCheck generates something which looks like valid stream start. I could change the prop to generate  only ANSI-strings for `prop_maybeDecompress_plain`, that should reduce false positives.

**Comment by 23Skidoo** [comment]
@phadej Unfortunately, this still happens even with your fix:

```
  Distribution.Client.GZipUtils

    maybeDecompress:           OK

    decompress plain:          FAIL

      *** Failed! Falsifiable (after 86 tests): 

      [40,83,98,86,108,50,99,65,40,86,90,72,38,69,41,41,49,37,80,84,49,82,105,106,60,44,76,49,56,80,37,120,76,87,119,33,108,54,45,59,125,56,125,121,76,75,42,49,49,74,124,58,61,114,116,117,51,119,88,124,118,70,108,107,43]

      Exception thrown while printing test case: 'Codec.Compression.Zlib: compressed data stream format error (invalid distance too far back)'

      Use --quickcheck-replay '85 TFGenR 7F908FAAD4C5853D28907A975E48C57F351877177030922AE633CA879067CF16 0 4194303 22 0' to reproduce.

    decompress zlib:           OK (0.01s)
```

**Comment by phadej** [comment]
QuickCheck is just to good :) Should we drop a test case? Seems it isn't that simple to generate a bytestring, which doesn't seems as valid compressed data. In real use that never happens.

**Comment by 23Skidoo** [comment]
Can't we change it to something like `isInvalidCompressedStream bs ==> prop_maybeDecompress_plain bs`?

If that's too hard, then sure.

**Comment by phadej** [comment]
@23Skidoo simple way to check whether stream is compressed, is to try to decompress it. But `zlib` doesn't offer non-exception-throwing decompression, so it seems to be too hard.

**Comment by phadej** [comment]
Too hard, as we have
```hs
-- Once we have received any output though we regard errors as actual errors
-- and we throw them (as pure exceptions).
```

That property is too hard to verify, valid compressed stream header comes too often in random data.

**Comment by phadej** [comment]
https://github.com/haskell/cabal/pull/2798
