### ISSUE TITLE
Drop IPI642 and IPI641 compatibility support

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2819]
We're not running continuous integration tests on these ancient version of GHC, there's no reason to expect this code to actually work. We should get rid of it.

**Comment by 23Skidoo** [comment]
Is this code required to make `cabal-install` support these old versions or is it just there so that Cabal could be compiled with them? It'd be nice if `cabal install -w ghc-6.4 foo` continued to work even with new versions of `cabal-install`.

**Comment by ezyang** [comment]
It's to actually support ghc-6.4.

**Comment by 23Skidoo** [comment]
IPI641 support has been dropped (#3034).

**Comment by ezyang** [comment]
Dropping IPI642 will drop support for GHC 6.8 and earlier. So whenever we decide to stop caring about that version we can finish this bug.
