### ISSUE TITLE
Cabal test shouldn't reconfigure if there aren't any tests to begin with

### ISSUE THREAD

**Issue by Rufflewind** [haskell/cabal#2824]
Scenario: I'm writing a script to automate installation of Haskell packages via a PKGBUILD script, so I naturally try to write in the most general way possible.  The script does something like this (simplified for clarity):

```
cabal configure --enable-tests
cabal build
cabal test
cabal copy …
```

Now the problem is that not all packages have tests (but I leave it there anyway hoping that it's just a no-op).  When that happens, cabal test will attempt to reconfigure the package, and then discover that there are no tests.  The whole point of `--enable-tests` was to avoid this reconfiguration, but `cabal test` does it again anyway.

IMO `cabal test` shouldn't reconfigure if there are no tests to begin with.  Or at the very least it should not reconfigure if `--enable-tests` was already specified earlier.

**Comment by ttuegel** [comment]
> cabal test shouldn't reconfigure if there are no tests to begin with.

This is a little tricky; we can't know for sure if there are tests until we configure the package with `--enable-tests`. Even if the package description has tests, they may not be buildable in some configurations. However, we can and should avoid reconfiguring on packages that don't define any tests at all.

> Or at the very least it should not reconfigure if --enable-tests was already specified earlier.

There are checks in place to make sure this does not happen. Could you give an example of a package that does this?

**Comment by Rufflewind** [comment]
> There are checks in place to make sure this does not happen. Could you give an example of a package that does this?

Idris:

```sh
cabal get idris
cd idris-*
cabal sandbox init
cabal install --only-dependencies --enable-tests
cabal configure --enable-tests
cabal test # running this will cause a configure every time!
```

It's particularly annoying for Idris because reconfiguring will trigger a `make clean` every time.

**Comment by ttuegel** [comment]
The problem here is that Idris is using the `Custom` build type. Packages using `Simple` should not reconfigure, but using the `Custom` type, a package's `Setup.hs` can edit the package description during configuration.

**Comment by jneira** [comment]
It seems this was not diagnosed as a bug and v1 commands are deprecated so i think we could close this. Feel free to reopen.
