### ISSUE TITLE
Cabal from Haskell Platform 7.10.2 for 'El Capitan': /usr/bin/ar: permission denied

### ISSUE THREAD

**Issue by danfran** [haskell/cabal#2851]
I have installed GHC 7.10.2 for El Capitan and I am having this issue:

cabal: /usr/bin/ar: permission denied

and I noticed that all the symlinks (after I have reinstalled Haskell-Platform) in /usr/bin are gone.

**Comment by gbaz** [comment]
@danfran which install method are you using? the /ar issue appears to be one related to ghcformacosx -- the missing symlinks issue is due to new rootless security, but should mainly affect the platform install method.

This ticket on the platform tracker describes the script to fix _those_ up: https://github.com/haskell/haskell-platform/issues/221

**Comment by danfran** [comment]
This script https://github.com/mzero/haskell-platform/blob/osx-elcap-fix/hptool/os-extras/osx/bin/activate-hs looks not working. I still cannot see the symlinks.

**Comment by gbaz** [comment]
The symlinks will now be placed in /usr/local/bin with that script. Did you
look there? Or were any errors printed?

**Comment by danfran** [comment]
yes they are in /usr/loca/bin now.

**Comment by danfran** [comment]
Using that script before to fix the permissions as apparently work but when I try to run the same script in:

sudo /Library/Haskell/ghc-7.10.2-x86_64/bin/activate-hs

I got:

/Library/Haskell$ sudo ghc-7.10.2-x86_64/bin/activate-hs 
ln: /usr/bin/ghc: Operation not permitted
ln: /usr/bin/ghc-7.10.2: Operation not permitted
ln: /usr/bin/ghc-pkg: Operation not permitted
ln: /usr/bin/ghc-pkg-7.10.2: Operation not permitted
ln: /usr/bin/ghci: Operation not permitted
ln: /usr/bin/ghci-7.10.2: Operation not permitted
ln: /usr/bin/haddock: Operation not permitted
ln: /usr/bin/haddock-ghc-7.10.2: Operation not permitted
ln: /usr/bin/hp2ps: Operation not permitted
ln: /usr/bin/hpc: Operation not permitted
ln: /usr/bin/hsc2hs: Operation not permitted
ln: /usr/bin/runghc: Operation not permitted
ln: /usr/bin/runghc-7.10.2: Operation not permitted
ln: /usr/bin/runhaskell: Operation not permitted
ln: /usr/share/doc/ghc: Operation not permitted
ln: /usr/bin/HsColour: Operation not permitted
ln: /usr/bin/activate-hs: Operation not permitted
ln: /usr/bin/alex: Operation not permitted
ln: /usr/bin/cabal: Operation not permitted
ln: /usr/bin/cabal.real: Operation not permitted
ln: /usr/bin/cabal.wrap: Operation not permitted
ln: /usr/bin/ghc-clang-wrapper: Operation not permitted
ln: /usr/bin/happy: Operation not permitted
ln: /usr/bin/uninstall-hs: Operation not permitted

Haskell now set to:
    GHC      7.10.2
    Arch.    x86_64
    Platform 7.10.2-a

View documentation with this command:
    open /Library/Haskell/doc/start.html

I image this is the current script in the package.

**Comment by gbaz** [comment]
Yes, the script I linked is a new version that is patched to work with El Capitan. The old script that remains in Library/Haskell/ghc-7.10.2-x86_64/bin/activate-hs is not the patched version, and will not work.

**Comment by ezyang** [comment]
OK, I'm going to mark this as fixed.

**Comment by Irio** [comment]
Was having this problem (OS X El Capitan 10.11.2 and GHC 7.10.2) and solved after reinstalling GHC through https://ghcformacosx.github.io/.

**Comment by TazeTSchnitzel** [comment]
I'm still having this issue even with 7.10.

**Comment by Hokutosei** [comment]
same here, got the same error. following instructions from [here](https://www.spock.li/tutorial/)

```
-> % cabal install --only-dependencies && cabal configure
cabal: /usr/bin/ar: permission denied
```

**Comment by gbaz** [comment]
how did you install cabal?

**Comment by Hokutosei** [comment]
@gbaz I installed it from here https://ghcformacosx.github.io/

I'm starting to learn haskell as my next programming language coming from c/c++, go, ios, etc... it's my first true functional language. 

I hope to get this working, hoping to use for microservices....

**Comment by gbaz** [comment]
@Hokutosei You probably need a newer cabal binary -- the one ghcformacosx provides hasn't been updated in a long time, unfortunately. Here's a link to what should be a working binary to replace it with... https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-x86_64-apple-darwin-mavericks.tar.gz

**Comment by gbaz** [comment]
for the record, ghcformacosx has now been updated and should provide an up-to-date cabal binary. :smile:

**Comment by sphvn** [comment]
I tried the following on my MBP today.

```
wget http://hackage.haskell.org/package/cabal-install-1.22.4.0/cabal-install-1.22.4.0.tar.gz
tar xf cabal-install-1.22.4.0.tar.gz
cd cabal-install-1.22.4.0
EXTRA_CONFIGURE_OPTS="" ./bootstrap.sh --sandbox --no-doc

...

[79 of 79] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Configuring Cabal-1.22.7.0...
Setup: /usr/bin/ar: permission denied
```

**Comment by gbaz** [comment]
@sphvn yes, the issue that prevents cabal from working is _also_ the issue that prevents you from bootstrapping a new cabal-install from the setup script :-/.

As I noted, there's a new ghcformacosx and you should just be able to download that and it should work?

**Comment by sphvn** [comment]
Would downloading just the cabal-install executable resolve this issue bar being able to install a new version?  Rather than having to download the full Haskell for Mac zip, as I've already installed 7.10.2 and 7.8.4.

**Comment by gbaz** [comment]
The dropbox link above is one potential source for a cabal-install executable. I don't at the moment know of any other great sources for one outside of the ghc-for-os-x distribution or the haskell platform distribution.

**Comment by sphvn** [comment]
Roger that.  I'll give the https://ghcformacosx.github.io/ package a go, seems to be working so far.

The only other source I can think of is cabal-1.22.0.0 from https://www.haskell.org/cabal/download.html.

**Comment by gbaz** [comment]
Unfortunately that cabal is too old -- they haven't been producing binary builds for the last few releases, just source tarballs....

**Comment by sphvn** [comment]
Using the ghcformacosx package,
```
cabal install --only-dependencies
cabal: /usr/bin/ar: permission denied
```
Still no luck.

**Comment by gbaz** [comment]
Can you check which cabal is on your path (`which cabal`) and which version it is (`cabal --v`).

**Comment by sphvn** [comment]
```
~/src  which cabal
  /Applications/ghc-7.10.3.app/Contents/bin/cabal
~/src  cabal --v
  cabal-install version 1.22.6.0
  using version 1.22.4.0 of the Cabal library 
```

**Comment by gbaz** [comment]
Yipe. Sorry for the runaround. The new version was supposed to fix this issue. I just uploaded the cabal extracted from the platform build. So either the dropbox link or this link may provide a working binary.

http://code.haskell.org/~sclv/cabal

**Comment by 23Skidoo** [comment]
@gbaz I can upload that binary to http://haskell.org/cabal. Which architecture it's for?

**Comment by sphvn** [comment]
Using the provided binary above (http://code.haskell.org/~sclv/cabal):

```
cd ~/Downloads
cp cabal $HOME/bin/cabal
which cabal
  /Users/sphvn/bin/cabal
cd ~/src/play
cabal install HUnit-1.3.1.1
  Resolving dependencies...
  ...
  setup-Simple-Cabal-1.18.1.5-x86_64-osx-ghc-7.8.4: /usr/bin/ar: permission denied
  cabal: Error: some packages failed to install:
  HUnit-1.3.1.1 failed during the configure step. The exception was:
  ExitFailure 1
```

Still getting `permission denied` on `/usr/bin/ar`.

**Comment by gbaz** [comment]
Whew! Sorry you were the test case for such a mess :-/

**Comment by gbaz** [comment]
@23Skidoo by the naming conventions I guess its x86_64-apple-darwin-yosemite, but it also works with el-capitan (as we now have another test case verifying).

    $ ./cabal --version
    cabal-install version 1.22.6.0
    using version 1.22.5.0 of the Cabal library

**Comment by 23Skidoo** [comment]
Uploaded the binary to https://www.haskell.org/cabal/release/cabal-install-1.22.6.0/, also updated the download page.

**Comment by sphvn** [comment]
Yeah I'm running on OSX El Capitan 10.11.3 and this is working for me.
