### ISSUE TITLE
Update the online user's guide

### ISSUE THREAD

**Issue by chreekat** [haskell/cabal#2855]
https://www.haskell.org/cabal/users-guide/developing-packages.html

default-extensions and other-extensions were apparently added five years ago, and they were added to Cabal/doc/developing-packages.markdown five months ago. Is somebody here able to update the website?

**Comment by phadej** [comment]
Hmm, and good starting point would be to have `cabal-install` and `Cabal` versions mentioned in the documentation.

**Comment by ezyang** [comment]
The sources for the user guide are here https://github.com/haskell/cabal/tree/master/Cabal/doc

Patches very happily accepted!

**Comment by 23Skidoo** [comment]
The problem here is that I don't have write access to haskell.org/cabal. Tried emailing admin@haskell.org, but to no avail. @rthomas also mentioned that he had problems with SFTP access.

BTW, once this is sorted out, we can configure Travis to build and deploy documentation for us.

**Comment by gbaz** [comment]
@johnw can you hook @23Skidoo up with write access? (btw  I checked my mail archives and it looks like I can't find the email to admin@ requesting this, but that could be an error on my end...)

**Comment by gbaz** [comment]
@jwiegley can you hook @23Skidoo up with write access? (btw I checked my mail archives and it looks like I can't find the email to admin@ requesting this, but that could be an error on my end...)

**Comment by 23Skidoo** [comment]
Well, it was quite some time ago.

**Comment by rthomas** [comment]
I've been able to push to www.haskell.org with sftp for the last releases I did - it seems at some point their infrastructure was rejigged and is no longer accepting connections at wiki.haskell.org.

Should I push the docs up from master, or from the 1.22 branch?

**Comment by 23Skidoo** [comment]
@rthomas 1.22 for now, I think.

**Comment by 23Skidoo** [comment]
@jwiegley Ping.

**Comment by jwiegley** [comment]
@23Skidoo Hi, can you e-mail me your SSH public key, and your preferred username?

**Comment by 23Skidoo** [comment]
@jwiegley Just sent an e-mail to johnw@newartisans.com.

**Comment by 23Skidoo** [comment]
This has been fixed.
