### ISSUE TITLE
Rebuilding results in "cannot satisfy package-id"

### ISSUE THREAD

**Issue by crockeea** [haskell/cabal#2856]
Here's the scenario: my cabal file contains a library and an executable. I've built the library and executable before, then I make changes to the executable files (which are independent of the library files) and try to rebuild with `cabal build myexec`. I get:

```
Preprocessing library mylib-0.1.0.0...
In-place registering mylib-0.1.0.0...
Preprocessing executable 'myexec' for mylib-0.1.0.0...
<command line>: cannot satisfy -package-id mylib-0.1.0.0-inplace
    (use -v for more information)
```

If I re-run the command, the build succeeds. This does not happen every time I make a change, so there seems to be some non-determinism involved.

Here's a cleaned up version of my cabal file:

```
name:                mylib
version:             0.1.0.0
stability:           experimental
build-type:          Simple
extra-source-files:  src/cSrc/header.h,
                     test-suite/TestHelper.hs
cabal-version:       >=1.10

library
  hs-source-dirs:     src
  Include-dirs: src/Crypto/Lol/Cyclotomic/Tensor/CTensor
  C-sources: src/cSrc/main.c
  Includes: src/cSrc/header.h
  default-language:   Haskell2010

  ghc-options: -pgml gcc -fPIC
  cc-options: -std=gnu99 -fPIC -Wall

  ghc-options: -optc-O3 -optlo-O3
  ghc-options: -O3 -Odph -funbox-strict-fields -fllvm -fwarn-dodgy-imports -fno-liberate-case -funfolding-use-threshold1000 -funfolding-keeness-factor1000 -threaded -rtsopts

  exposed-modules: 
    ...
  other-modules:
    ...
  build-depends:
    ...
  other-extensions: TemplateHaskell

executable myexec
  default-language:   Haskell2010
  hs-source-dirs: test-suite
  main-is: Main.hs
  ghc-options: -threaded -rtsopts

  build-depends:
    mylib,
    ...
```

**Comment by ezyang** [comment]
Is this with the latest Cabal HEAD?

**Comment by crockeea** [comment]
$ cabal --version
cabal-install version 1.22.4.0
using version 1.22.2.0 of the Cabal library

**Comment by ezyang** [comment]
@crockeea I can't reproduce. Could you please run the following:

```
git clone https://github.com/haskell/cabal.git
cd cabal/Cabal
cabal install
cd ../cabal-install
cabal install
```

and then let us know if the problem shows up again?

If it does show up again, we will need a FULL package that we can actually compile.

**Comment by gbaz** [comment]
if we have a can't repro and its been blocked on info-needed for two years, i suggest to close.
