### ISSUE TITLE
Parameter to make solver pick the minimal set of version depencencies

### ISSUE THREAD

**Issue by jdnavarro** [haskell/cabal#2876]
This would be useful to detect wrong minimum dependency version bounds.

@kosmikus, would this be too difficult?

**Comment by phadej** [comment]
AFAICS this is a opposite of [`preferLatestOrdering`](https://github.com/haskell/cabal/blob/97ccac0b1a38878f7653c5ea81b8a9c98728cfff/cabal-install/Distribution/Client/Dependency/Modular/Preference.hs#L92)
I'd suggest:
- make `preferFirstOrdering`
- make a solver flag (`--prefer-oldest`)
- wire the two things together
- write tests
- profit

**Comment by jdnavarro** [comment]
That should be easy enough for me :)

**Comment by kosmikus** [comment]
This has been suggested and even been worked on in the past, and I recall it not having been quite as easy as it sounds. I'll have to try to remember the details though. One issue I seem to remember is that it rarely works if applied recursively. You can control your own lower bounds, but not the lower bounds of all packages you depend on.

**Comment by kosmikus** [comment]
See #1309 and #2228. So there's actually an old pull request to start from if you like. I'm still in general in support of this. I think #1309 was just abandoned by the original author, and I didn't have the energy to push resolve the remaining questions and push it through on my own.

**Comment by phadej** [comment]
I would still try to make it work recursivelyi It would result into some work to correct lower bounds, but IMHO it's worth that.

There are packages with no lower bounds, and even people don't agree on how to specify upper bounds, lower bounds should be much more straight forward.

**Comment by kosmikus** [comment]
@phadej The situation has certainly changed because we now have Hackage trustees and the option of fixing bounds of old packages. But please consider that this is the only option: uploading a *new* version with fixed lower bounds wouldn't help, because the recursive `--prefer-oldest` would still pick the older one.

Consider the following scenario:

Package A-1 depends on B >=1 and B < 3.
Package B-1 depends on C, but fails to build with C-1.
Package B-2 depends on C >= 2.
Package C-1 and C-2 depend on nothing.

Package author of A is morally correct to say that B >= 1 is the lower bound. There's nothing wrong if A-1 is built against B-1 and C-2. However, B-1 is broken. The only way to "fix" this is to update B-1's bounds. Creating B-1.1 or B-3 wouldn't help for the `--prefer-oldest` strategy. We also don't want to encourage A to change the lower bound to B >= 2.

**Comment by phadej** [comment]
@kosmikus yes. But package authors could do revisions of their own packages too. So in very perfect world, trustees won't be overloaded with work.

It might make sense to centrally fix lower bounds for the core subset of Hackage (i.e. something everything depends on), but I'd don't expect there to be a lot of broken packages.

**Comment by phadej** [comment]
And we can "automate" that by kindly asking `matrix.hackage.haskell.org` to build with `--prefer-oldest` ;)

**Comment by kosmikus** [comment]
I'm not opposed here. I was just trying to explain why in the past, we considered this to be a more significant problem than it may be now.

**Comment by bmillwood** [comment]
What's wrong with simply making it non-recursive? After all, it's probably the package you're building whose lower bounds you want to check. You're not interested in finding out if some other package is doing things wrong.

**Comment by kosmikus** [comment]
@bmillwood One problem I can think of is that we currently have no priority between different soft preferences. So if user goal A has "prefer oldest", but all dependencies of A have "prefer newest", and A depends on B and C, and B also depends on C, then now it depends on the goal order the solver chooses whether we get the oldest or the newest version of C.

More generally speaking, unless we also add some heuristic that the immediate dependencies of user goals have to be solved in a preferred way, the "prefer oldest" default may easily turn out to be ineffective in practice. If "prefer oldest" was recursively applied, then this particular problem would not occur.

**Comment by ndmitchell** [comment]
FWIW, I gave this a go by hacking it in directly. I wrote the results up at http://neilmitchell.blogspot.co.uk/2018/03/adding-package-lower-bounds.html.

**Comment by Bodigrim** [comment]
I came up with the same idea in #8229 independently. I implemented it in a personal fork and I'm very satisfied with the result. Indeed at the beginning it involves a fair amount of recursive revisions, but now I'm done with them and can enjoy a reliable way to set lower bounds. Cannot recommend enough, it would be great to upstream this feature.

**Comment by jneira** [comment]
sounds great, maybe opening the pr could help to make it be included
is there any caveat you can think of?
