### ISSUE TITLE
Precompiled "cabal" on download page is only good for 32-bit OS

### ISSUE THREAD

**Issue by dtonhofer** [haskell/cabal#2885]
_Problem description:_

Go to: https://www.haskell.org/cabal/download.html

Grab the "cabal-1.22.0.0-i386-unknown-linux.tar.gz"

...because I want to just compile Haskell on Fedora 22 and I am running into _"ghc: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format."_ while building with the haskell-platform. This is apparently due to Fedora 22 coming with a cabal that is a bit long in the tooth: ghc-Cabal-1.18.1.5-45.fc22.x86_64

Untar the above, which yields a "cabal" executable. Put "cabal" on PATH. Run platform build. Error message appears:

./platform.sh: /home/builder/bin/cabal: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory

Indeed, this is a 64-bit OS. Why isn't there a 64-bit version only a 32-bit version? Please add a 64-bit version.

I just want to compile Haskell. I have been going through a deepening problem stack for 6 hours or so and keep getting insulted by the platform build script with cryptic errors. I shall yet succeed but ... FFS!!

**Comment by 23Skidoo** [comment]
We need to automate deployment of release binaries, because doing this manually clearly doesn't scale. We can use Travis for x86-64 and possibly i386 Linux (maybe also OS X), and maybe AppVeyor for Linux.

@dcoutts I remember there was talk about using some of your machines for this?

**Comment by gbaz** [comment]
If anyone wants to hop on the #haskell-infrastructure channel on freenode and is willing to set up the builder apparatus, we'd be happy to slice off some of our vm space for this. In general we'd like to have a cross-platform builder story that would handle windows, linux, and os x alike for use by all the various core projects.

**Comment by 23Skidoo** [comment]
@gbaz I'm interested.

**Comment by 23Skidoo** [comment]
We now have both 32-bit and 64-bit Linux binaries on the download page. Building of release binaries haven't been automated yet.
