### ISSUE TITLE
Docu says: "Adding -j <n> to the build invocation will enable building on multiple cores at once." Not true.

### ISSUE THREAD

**Issue by dtonhofer** [haskell/cabal#2886]
At https://github.com/haskell/haskell-platform the README says:

_"Adding -j <n> to the build invocation will enable building on multiple cores at once."_

This seems to not be reliably the case.

Both 

./platform.sh ../ghc-7.10.2-x86_64-unknown-linux-centos66.tar.bz2 -j 4

and

./platform.sh -j 4 ../ghc-7.10.2-x86_64-unknown-linux-centos66.tar.bz2 

fail with errors that seem to indicate that "-j 4" is interpreted as input to something else ("Error, file does not exist and no rule available:  4"

Although -j 4 in front indeed seems to allocate the cores more than leaving it out, at least at until the build error occurs.

**Comment by 23Skidoo** [comment]
`platform.sh` is something specific to HP, so [please use their bug tracker](https://github.com/haskell/haskell-platform/issues/new).
