### ISSUE TITLE
happy-1.18 problem - buildVerbose vs buildVerbosity in Setup.lhs

### ISSUE THREAD

**Issue by doswellf** [haskell/cabal#2888]
Trying to build happy-1.17 from source on ubuntu 14

After changing 
import System.IO.Error ( try ) 
to
import Control.Exception (try)
 which fixed on error, I then get a problem with this line:

Line 33 let runProgram p = rawSystemProgramConf (buildVerbose flags) p (withPrograms lbi)

This output resutls:

Setup.lhs:29:46:
    Not in scope: `buildVerbose'
    Perhaps you meant `buildVerbosity' (imported from Distribution.Simple.Setup)

Tried buildVerbosity from that package which of course failed because the type is wrong.

Which package is buildVerbose from? 
If someone knows this is I can get on to actually installing happy and then install haskell-src-exts
then get the eclipsefp2 support framework running in eclipse again.

Fraser

**Comment by 23Skidoo** [comment]
`happy-1.17` is quite old, can't you try a newer version? Looks like `happy-1.17`'s setup script requires an old version of Cabal.
