### ISSUE TITLE
No --enable-optimization --disable-optimization flags for build option.

### ISSUE THREAD

**Issue by MKloczko** [haskell/cabal#2901]
Cabal-install 1.22.6
Cabal version 1.22.4

Hello.

I would like to build a executable with different optimization flags.
In the cabal file, I've been changing the -On option multilpe times. 
 `ghc-options: -O2` to `ghc-options: -O0` but it didn't force recompilation. 

The flags --enable-optimization, -On, and --disable-optimization are not recognised for build option.

**Comment by dcoutts** [comment]
People are welcome to have a go at improving this in the current code, but I should note that it's fixed in the nix-local-build branch (but as a consequence of doing everything completely differently, so it's not a thing we can cherry-pick.)

**Comment by MKloczko** [comment]
Oh, sorry. It seems that for both *nix-local-build* branch and the 1.22.6 cabal-install from hackage you can set the optimization flags at `configure` and `install level`, but not on `build`.

It is probably not an issue, but why one cannot set that for build option ?

Another question if I might ask here - why changing the optimization option does not result in recompilation of the executable ?

**Comment by dcoutts** [comment]
Sorry, in the nix-local-build branch the new code path there is currently called via "cabal new-build".

> Another question if I might ask here - why changing the optimization option does not result in recompilation of the executable ?

Oh, doesn't it? We delegate this decision to `ghc --make`.

**Comment by MKloczko** [comment]
Ok, it seems it's ghc related bug:
http://ghc.haskell.org/trac/ghc/ticket/10923

Current workaround - use -fforce-recomp

**Comment by 23Skidoo** [comment]
Closing (because it is not a Cabal bug), but feel free to reopen if you disagree.
