### ISSUE TITLE
Cabal fails on Unicode characters in source file name

### ISSUE THREAD

**Issue by strake** [haskell/cabal#2908]
[This example package](https://cloud.githubusercontent.com/assets/976729/10901605/5c057074-81a6-11e5-87e6-0738d5df528d.png) (actually a gzipped tarball; ignore the file extension) makes cabal fail.

$ cabal build
Building test-0.1.0.0...
Preprocessing executable 'test' for test-0.1.0.0...
[1 of 2] Compiling Példa            ( Példa.hs, dist/build/test/test-tmp/Példa.o )
/usr/bin/ld: cannot find /home/strake/test/dist/build/test/test-tmp/P
/usr/bin/ld: cannot find lda_o_split/P
/usr/bin/ld: cannot find lda__1.o
/usr/bin/ld: cannot find /home/strake/test/dist/build/test/test-tmp/P
/usr/bin/ld: cannot find lda_o_split/P
/usr/bin/ld: cannot find lda__2.o
/usr/bin/ld: cannot find /home/strake/test/dist/build/test/test-tmp/P
/usr/bin/ld: cannot find lda_o_split/P
/usr/bin/ld: cannot find lda__3.o
collect2: error: ld returned 1 exit status
éééééé

\<no location info\>: ghc: phase `Linker' failed (exitcode = 1)
$

**Comment by 23Skidoo** [comment]
Does it work with `ghc --make`?

**Comment by 23Skidoo** [comment]
Looks like it does.

**Comment by 23Skidoo** [comment]
Closing as works for me:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
$ cabal --version
cabal-install version 1.23.0.0
using version 1.23.0.0 of the Cabal library

$ cabal build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring pelda-0.1.0.0...
Building pelda-0.1.0.0...
Preprocessing executable 'példa' for pelda-0.1.0.0...
[1 of 2] Compiling Példa            ( Példa.hs, dist/build/példa/példa-tmp/Példa.o )
[2 of 2] Compiling Main             ( Main.hs, dist/build/példa/példa-tmp/Main.o )
Linking dist/build/példa/példa ...

$ ./dist/build/példa/példa
példa
```

Test project sources: https://github.com/haskell/cabal/issues/2908

**Comment by 23Skidoo** [comment]
Your test package also works fine:

```
$ cabal build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring test-0.1.0.0...
Warning: The 'license-file' field refers to the file 'LICENSE' which does not
exist.
Building test-0.1.0.0...
Preprocessing executable 'test' for test-0.1.0.0...
[1 of 2] Compiling Példa            ( Példa.hs, dist/build/test/test-tmp/Példa.o )
[2 of 2] Compiling Main             ( Main.hs, dist/build/test/test-tmp/Main.o )
Linking dist/build/test/test ...
```

So probably an issue with `ld` or GHC. Try updating binutils.
