### ISSUE TITLE
Add a way for test suites to print colors

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#2911]
Hi,

with the current code, the stdout of a test suite is always attached to a pipe (and previously to a file), never to the terminal directly. This is unfortunate, as many test frameworks provide nice and useful coloring if attached to a terminal.

I suggest to add yet a nother mode to `--show-detail` that is `direct`: Like `streaming`, but it connects the test output directly to a terminal. It would not save a log file in this case, but that is ok.

In this case, no worrying thread spawning and lazy IO is requires, so this would also be a work-around for #2398.

CC’ing @ttuegel.

Thanks,
Joachim

**Comment by nomeata** [comment]
This is implemented in PR #2913.

**Comment by BardurArantsson** [comment]
#2913 was merged. Closing.
