### ISSUE TITLE
Minor release with for binary

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#2919]
`binary` will provide `Binary Version` instance, we should make a minor release

https://github.com/kolmodin/binary/pull/87

**Comment by phadej** [comment]
Why this is closed, I cannot see release yet? actually, One would need to backport fix to 1.22 branch...

**Comment by ezyang** [comment]
Oops, I saw merged and closed it, but we haven't released yet.

**Comment by phadej** [comment]
@23Skidoo what you think, should I backport binary-0.8 patch to 1.22 branch as well?

**Comment by 23Skidoo** [comment]
@phadej Sure, that would not be bad. 

Re: next 1.22 point release, I've e-mailed Ryan, but he hasn't responded yet.

**Comment by quasicomputational** [comment]
I can pretty safely say that there won't be a 1.22 point release now.
