### ISSUE TITLE
cabal configure --builddir doesn't use custom Setup.hs

### ISSUE THREAD

**Issue by noteed** [haskell/cabal#2935]
Running `cabal configure --builddir /path/to/dist` or `cabal configure` produce different results.

The first one outputs

```
Resolving dependencies...
Configuring package-name-x.y.z...
```

The second one outputs

```
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Configuring package-name-x.y.z...
XXX
```

where "XXX" is because I have `putStrLn "XXX"` in a `postConf` hook in the `Setup.hs` file.

It seems a workaround is to manually copy the custome `Setup.hs` file to `setup/setup.hs` in the builddir location.

**Comment by ezyang** [comment]
I can't repro on Cabal HEAD.

{{{
ezyang@sabre:~/Dev/cabalbugs/cabal-2935$ cabal configure
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Configuring cabal2935-0.1.0.0...
dist/build
ezyang@sabre:~/Dev/cabalbugs/cabal-2935$ cabal configure --buildir=dist2
cabal: unrecognized 'configure' option `--buildir=dist2'
ezyang@sabre:~/Dev/cabalbugs/cabal-2935$ cabal configure --builddir=dist2
Resolving dependencies...
[1 of 1] Compiling Main             ( dist2/setup/setup.hs, dist2/setup/Main.o )
Linking ./dist2/setup/setup ...
Configuring cabal2935-0.1.0.0...
dist2/build
ezyang@sabre:~/Dev/cabalbugs/cabal-2935$ cabal configure --builddir=dist2/build
Resolving dependencies...
[1 of 1] Compiling Main             ( dist2/build/setup/setup.hs, dist2/build/setup/Main.o )
Linking ./dist2/build/setup/setup ...
Configuring cabal2935-0.1.0.0...
dist2/build/build
}}}

Here's my test program: 
[cabal-2935.zip](https://github.com/haskell/cabal/files/71008/cabal-2935.zip)
