### ISSUE TITLE
install of BuildWrapper failed

### ISSUE THREAD

**Issue by houseofwealth** [haskell/cabal#2944]
Hello, I get the following compile error when I try to install BuildWrapper (necessary for the EclipseFP plugin). Prior to this I ran `cabal update`. I am running on Windows 7 and have the Haskell Package 7.10.2-a installed. Can anyone help?

------------------------------
$ cabal install BuildWrapper
Resolving dependencies...
[1 of 1] Compiling Main             ( C:\Users\Owner\AppData\Local\Temp\cabal-tmp-39884\buildwrapper-0.9.1\dist\setup\setup.hs, C:\Users\Owner\AppData\Local\Temp\cab
al-tmp-39884\buildwrapper-0.9.1\dist\setup\Main.o )
Linking C:\Users\Owner\AppData\Local\Temp\cabal-tmp-39884\buildwrapper-0.9.1\dist\setup\setup.exe ...
Configuring buildwrapper-0.9.1...
Building buildwrapper-0.9.1...
Preprocessing library buildwrapper-0.9.1...
[1 of 6] Compiling Language.Haskell.BuildWrapper.Base ( src\Language\Haskell\BuildWrapper\Base.hs, dist\build\Language\Haskell\BuildWrapper\Base.o )

src\Language\Haskell\BuildWrapper\Base.hs:13:1: Warning:
    The import of `Control.Applicative' is redundant
      except perhaps to import instances from `Control.Applicative'
    To import instances alone, use: import Control.Applicative()
[2 of 6] Compiling Language.Haskell.BuildWrapper.Cabal ( src\Language\Haskell\BuildWrapper\Cabal.hs, dist\build\Language\Haskell\BuildWrapper\Cabal.o )

src\Language\Haskell\BuildWrapper\Cabal.hs:271:17:
    Non type-variable argument
      in the constraint: RegexContext
                           Regex source1 (String, String, String, [String])
    (Use FlexibleContexts to permit this)
    When checking that `extractLine' has the inferred type
      extractLine :: forall source1.
                     RegexContext Regex source1 (String, String, String, [String]) =>
                     source1 -> Int
    In an equation for `parseCabalMessages':
        parseCabalMessages cf cabalExe s
          = let (m, ls) = foldl parseCabalLine ... $ lines s
            in
              nub
              $ case m of {
                  Nothing -> ls
                  Just (bwn, msgs) -> ls ++ [...] }
          where
              parseCabalLine ::
                (Maybe (BWNote, [String]), [BWNote])
                -> String -> (Maybe (BWNote, [String]), [BWNote])
              parseCabalLine (currentNote, ls) l
                | "Error:" `isPrefixOf` l
                = (Just (BWNote BWError "" (mkEmptySpan cf 1 1), [...]),
                   addCurrent currentNote ls)
                | "Warning:" `isPrefixOf` l
                = let ... in (Just ..., addCurrent currentNote ls)
                | Just (bw, n) <- cabalErrorLine
                                    cf cabalExe l (not (any isBWNoteError ls))
                = (Just (bw, n), addCurrent currentNote ls)
                | Just (jcn, msgs) <- currentNote
                = if not $ null l then (Just ..., ls) else (Nothing, ls ++ ...)
                | otherwise = (Nothing, ls)
              extractLine el
                = let ... in if null ls then 1 else readInt (head ls) 1

src\Language\Haskell\BuildWrapper\Cabal.hs:768:47:
    Couldn't match type `ModuleName' with `ExposedModule'
    Expected type: [ExposedModule]
      Actual type: [ModuleName]
    In the second argument of `(++)', namely `hms'
    In the second argument of `map', namely `(ems ++ hms)'
Failed to install buildwrapper-0.9.1
cabal.exe: Error: some packages failed to install:
buildwrapper-0.9.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by grayjay** [comment]
According to this issue, BuildWrapper is no longer maintained and doesn't build with GHC >= 7.10.1: https://github.com/JPMoresmau/BuildWrapper/issues/58

**Comment by BardurArantsson** [comment]
Yeah, this is a BuildWrapper issue (and BW is unmaintained). Closing.
