### ISSUE TITLE
Issue with locales on ArchLinux

### ISSUE THREAD

**Issue by lukasepple** [haskell/cabal#2945]
Upon invoking cabal I get:

```
cabal: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_COLLATE) / sizeof (_nl_value_type_LC_COLLATE[0]))' failed.
```

If I set an invalid `LANG` it works fine:

```
$ LANG=nope cabal --help
Command line interface to the Haskell Cabal infrastructure.

See http://www.haskell.org/cabal/ for more information.
```

My locale looks like this:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_US.UTF-8
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
But I also had trouble with a german locale and without `LC_COLLATE`.

My cabal version is:

```
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```

I could also get it to work by generating no locale at all. Seems to be a common issue on ArchLinux though that has affected pandoc, steam and other applications in the past. I could not manage to find a general solution yet.

Related:

* <https://www.reddit.com/r/archlinux/comments/3g9dzf/>
* <https://github.com/junegunn/fzf/issues/356>
* <https://github.com/rstudio/rmarkdown/issues/498>

**Comment by 23Skidoo** [comment]
> Seems to be a common issue on ArchLinux though that has affected pandoc, steam and other applications in the past.

Looks like it should be fixed on the Arch side then. Thanks for the bug report, maybe it'll help people googling for the error message.
