### ISSUE TITLE
[nix-local-build] mtl bounds insufficient for Control.Monad.Except

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2953]
It was added in 2.2.1, but cabal-install's mtl bound is >= 2.0. But I'm not sure bumping it up is the right answer.

CC @dcoutts

**Comment by dcoutts** [comment]
What are we supposed to do? The .Error one is deprecated.

**Comment by 23Skidoo** [comment]
@ezyang 
> But I'm not sure bumping it up is the right answer.

Why?

**Comment by ezyang** [comment]
I guess if the newest version of mtl builds on all versions of GHC in our support window, no problem.
