### ISSUE TITLE
Regression in cache construction

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2956]
PR #2826 (addressing #2396) introduced a bug in the cache construction, although we could define it away as "not a bug" if we were so inclined. 

Here's the issue. In principle the index can contain multiple versions of a `preferred-versions` file at the same path (i.e., we might have multiple entries for `/example-package/preferred-versions`). If this is the case, then later entries should override earlier ones. This is why in the cache construction `parsePackageIndex` was using a `Map` as the accumulator for `preferred-versions`, with paths as map keys. Whenever a `preferred-versions` file was encountered, it got added to the map, thereby automatically overriding earlier versions of the same file if they existed. 

In the attempt to make the cache construction lazy (stream from the tarfile to the cache file, without building the whole thing in memory) this `Map` got removed. In principle this is a bug. In practice, however, this is probably okay: Hackage guarantees that the legacy `00-index.tar.gz` index remains to exist, and has at most one `preferred-versions` file per package (see `writeLegacy` in `Distribution.Server.Packages.Index`); it does this precisely because this bug has existed in `cabal` before. Indeed, we might revert to having the server serve a _single_ `preferred-versions` file (https://github.com/haskell/hackage-server/issues/414). 

This is _not_ true for the new `01-index.tar.gz` format introduced by the Hackage Security work. However, this will receive a special case anyway in the cache construction, because the `hackage-security` library constructs its own cache (piggybacking on @dcoutts 's work on the `TarIndex`) which does deal correctly with this situation (and must, because the `01-index` is strictly incremental). We can take advantage of this cache when constructing `cabal-install`'s own cache; initially I was working on this just to improve the performance of a check for updates, but unless we fix this issue this will actually be essential for correctness (and I will mark it as such).

So we can probably close this as wont-fix, but I wanted to at least have documented this in detail as it's somewhat subtle. 

Pinging @23Skidoo , @accursoft , @dcoutts .

**Comment by dcoutts** [comment]
I think we can define this as not a problem, since we're not planning to change the 00-index format, partly because old versions had this bug, but also because adding the new stuff increased the size significantly.

**Comment by 23Skidoo** [comment]
Does this only affect `preferred-versions` or also `.cabal` files?

**Comment by edsko** [comment]
@23Skidoo The `00-index.tar.gz` will not contain multiple versions of `.cabal` files (though the `01-index.tar.gz` will).

**Comment by 23Skidoo** [comment]
Yes, but in principle it can, right?

**Comment by edsko** [comment]
Yes, just like for `preferred-versions`.

**Comment by edsko** [comment]
(Though for `.cabal` files this may matter less because in the construction of the package index from the cache we already allow for this possibility; see `packageIndexFromCache` ; see the base case of `accum`.

**Comment by edsko** [comment]
Closing as wont-fix so. Added a comment to my (forthcoming) patch that integrates the security library that special case in `withIndexEntries` (introduced in #2962) for secure repos is required for correctness.
