### ISSUE TITLE
[nix-local-build] Need new-style clean

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2957]
A few bugs:
1. "cabal clean" doesn't clean dist-newtyle. Maybe need a "cabal new-clean"?
2. cabal clean obviously isn't going to respect projects

CC @dcoutts

**Comment by dcoutts** [comment]
What should it clean do you think? All the local packages and cached info? Or just one package, or ?

**Comment by ezyang** [comment]
Current cabal clean just cleans one project (e.g. that happens if you use it in a sandbox?) so that's my inclination. Though I'm not sure.

**Comment by hvr** [comment]
Fwiw, I'd expect `cabal new-clean` to remove the `dist-newstyle/` which may contain all sorts of executables and local artifacts

**Comment by lspitzner** [comment]
note that custom Setup.hs gets compiled into `$PACKAGE/dist/..` even with new-build. so new-build clean might need to
~~~~
packages `forM_` \path -> rm -rf (path</>dist)
~~~~

as well. (sorry for the haskell/bash mixture, it is horrible.)

**Comment by ezyang** [comment]
Putting this low priority because the workaround is really simple (just delete dist-newstyle yourself.)

**Comment by gbaz** [comment]
Its irritating to discover the workaround -- this just hit me and I ended up here :-)
