### ISSUE TITLE
[nix-local-build] Build of Cabal forces download of old version of Cabal

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2963]
Steps to reproduce:

1. Look in `~/.cabal/packages/hackage.haskell.org/Cabal` and delete the most recent cached version of Cabal.
2. Run `cabal new-build` in `Cabal`'s source directory.

Expected result: no downloads

Actual result: We download Cabal-1.22.5.0

(This might be expected behavior but it's not obvious why that would be the case.)

CC @dcoutts

**Comment by 23Skidoo** [comment]
Just a guess: maybe it needs it to build the setup script?

**Comment by hvr** [comment]
iirc, @dcoutts told me this is expected behavior (but I forgot the rationale he gave me)

**Comment by dcoutts** [comment]
Right, this is actually correct.

In the nix-local-build branch we treat dependencies of Setup.hs scripts rather strictly. Either they are new style that specify their deps explicitly in the .cabal file or they are legacy style in which case we pick a fixed set of package names for them. In particular we pick Cabal, but for compatibility we pick Cabal < 1.23, on the theory that we want to start breaking the Cabal API at some point without breaking all old Setup.hs scripts.
