### ISSUE TITLE
cabal-install-1.22 with zlib-0.6 

### ISSUE THREAD

**Issue by itteam** [haskell/cabal#2966]
@23Skidoo would it be ok to do minor release with bumped dependencies. I can make a PR against `1.22` branch, if it's otherwise ok.

This is needed for https://github.com/fpco/stackage/issues/537 at least

**Comment by itteam** [comment]
And I used wrong account...

**Comment by phadej** [comment]
And I used wrong account to create an issue... :S

**Comment by 23Skidoo** [comment]
Yes, sure, in fact there was another request for a minor release: https://github.com/haskell/cabal/pull/2767#issuecomment-164431690.
