### ISSUE TITLE
Bring the cabal-install runner to Cabal library

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2970]
Annoyingly all the code is in `IntegrationTests.hs` and I don't really know if we want to make another library to house the common test code, or just copy paste it (ick).

Cabal test runner needs to operate a little differently because we need to build a 'Setup' executable (linked against the library) to then run the tests with.

**Comment by ezyang** [comment]
CC @BardurArantsson

**Comment by ezyang** [comment]
Well, for now I'm going to refactor the Cabal test suite to make it easier to write tests with.

**Comment by BardurArantsson** [comment]
FWIW, I think your refactoring is basically The Right Way To Do It, so as far as I'm concerned at least, I think you can just close this when #2998 is merged (as it will hopefully be soonish).

**Comment by ezyang** [comment]
OK close it for now.
