### ISSUE TITLE
[nix-local-build] Globbing in 'packages' field silently fails

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2973]
Suppose you write in your cabal.config

```
packages: foo/foo.cabal bar/bar.cabal
```

This won't work. It will silently fail and claim that there are no projects. (You need to use a comma.)

It seems that if a user writes a pattern, and it matches ZERO files, Cabal should warn.

CC @dcoutts

**Comment by dcoutts** [comment]
Now does fail, and there's a different field for optional package globs, ie ones where it's ok for the glob to match nothing.
