### ISSUE TITLE
[nix-local-build] Glob fails to parse nested directories inside curlies

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2974]
Suppose you write

```
packages: ../{Cabal/Cabal,bar}/*.cabal
```

This will fail to parse. (I don't know if this is not strictly POSIX glob, but I don't care and users probably don't either.)

CC @dcoutts

**Comment by dcoutts** [comment]
Ben and I decided not to support this as it's actually rather tricky to implement. Adding globbing features on names within dirs is easy, doing it with dirs too affects the rest of the algorithm for checking if files have changed. So perhaps we should parse them like this and then say explicitly they're not supported.

**Comment by ezyang** [comment]
If #2973 was fixed that would go a long way towards making this less troublesome.

In the Shake model, this would not be difficult to implement: the directory glob would be an oracle (i.e., we just run every invocation of Cabal) and then you would look at the result and see if it changed from last time (if it did, reparse!)

**Comment by dcoutts** [comment]
Our glob monitoring is more efficient than just re-running the glob search and comparing the output. We also have a oracle-like mechanism, it's the value part of the monitors.

In this case, is it really that important to support globs that span '/'s? I'd be surprised. More important in this area is probably recursive / all-subdirs globs.

**Comment by ezyang** [comment]
It is now possible to omit the *.cabal from packages, so my motivation for writing this glob is done. I'll close this.
