### ISSUE TITLE
cabal repl and cabal exec ghci equivalent for new-build?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2977]
Even if just manually? I tried passing some package DBs to ghci but no luck.

**Comment by ezyang** [comment]
Yeah, it's not implemented yet. You should be able to divine the manual flags by looking at the output of `cabal new-build -v`. What flags did you try?

**Comment by edsko** [comment]
Ah, indeed. Running with -v suggests

```
ghci -package-db /Users/e/.cabal/store/ghc-7.10.3/package.db 
     -package-db /Users/e/my/project/dist-newstyle/packagedb/ghc-7.10.3 
     -package-db /Users/e/my/project/dist-newstyle/build/project-0.1.0.0/package.conf.inplace
```

and that seems to work.

**Comment by ezyang** [comment]
Right. GHCi really needs to step up its "multiple local packages" game. SPJ and I have chatted about it, we have some ideas about how to do it, but it's not been implemented.

**Comment by ezyang** [comment]
There's `cabal new-repl` now. Not documented though.
