### ISSUE TITLE
In a post build hook how to get the right build path in a sandbox

### ISSUE THREAD

**Issue by danfran** [haskell/cabal#2978]
I am creating a simple post-build-hook but the problem comes when I try to build the project that is meant to use this hook, inside a sandbox. 

I am using `Distribution.Simple.LocalBuildInfo` to pass the parameter to the hook, and specifically the function `buildDir` that always returns `dist/build`.

The problem is that in a sandbox the project will be built inside a `dist/dist-sandbox-xxxxxxxx/build`.

Am I using the right function or I should use something else?

**Comment by ezyang** [comment]
Hello danfran, you are using the right parameter. On Cabal HEAD, I verified that the contents of buildDir are printing out the Sandbox directory. Here is my test: 
[cabal-2978.zip](https://github.com/haskell/cabal/files/70986/cabal-2978.zip)

Initialize a sandbox in this directory and then call 'cabal install'. The hook will print the right path.

Note that if you say 'cabal build', buildDir will point to `dist/build`, and this is INTENTIONAL, since sandboxes don't apply for those commands.

**Comment by danfran** [comment]
Hi ezyang, thanks for the answer.

I run it but I cannot see the hook working.

After `cabal install` nothing has returned. Only `cabal build` return as usual `dist/build`.

I am wondering how this could work if the hooks belong to an external package (sorry, I was not totally clear in my question).

I mean given a package A (the hook) and a package B that uses the package A.

If the package B is built inside a sandbox and uses the hook in the package A, you will see that cabal will create:

`B/dist/A-stuff` relative to the hook A
`B/dist/dist-xxxxxxxx/B-stuff`

So the hook A cannot find the B-stuff.

I found this issue as I am trying to fix some problems with cabal-macosx hook too.

**Comment by ezyang** [comment]
What is the output of `cabal --version`? Can you try running with a newer version?

Your second problem seems like a different problem. Could you make a zip file like the test I uploaded showing this problem (with a list of commands to run to trigger it?)

**Comment by danfran** [comment]
`
$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
`

and ghc is 7.10.3

**Comment by ezyang** [comment]
Could you please run

```
git clone https://github.com/haskell/cabal.git
cd cabal/Cabal
cabal install
cd ../cabal-install
cabal install
```

and then try again?

**Comment by danfran** [comment]
Hi ezyang,

it looks good now thanks! I can see both hook and package working under the same `dist/dist-xxxxx`.

**Comment by ezyang** [comment]
OK. If the second problem is still an issue please reopen this ticket!
