### ISSUE TITLE
Parser problem for cabal.project

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2980]
If I leave out a comma, as in

```
packages: Cabal/Cabal.cabal cabal-install/cabal-install.cabal
```

then `new-build` simply doesn't build anything at all.

**Comment by ezyang** [comment]
Duplicate of #2973 haha.

**Comment by edsko** [comment]
Whoops, sorry @dcoutts :)

**Comment by edsko** [comment]
(Though I consider this as evidence that syntax without commas is more natural :)
