### ISSUE TITLE
[nix-local-build] Gets confused when vendored package has same version as Hackage

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2986]
If your vendored package (listed in project.cabal) has the same version as the one on Hackage, the planner will refine it to the installed plan, but then wonder why there's no inplace copy of the package available. We should either (1) error earlier, or (2) not refine it into the install plan.

**Comment by dcoutts** [comment]
Sorry, I don't follow. Can you elaborate?

**Comment by ezyang** [comment]
I can't reproduce anymore,
