### ISSUE TITLE
"Freeze" the state of the package DB?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2996]
It's somewhat annoying when using cabal-nix that whenever I call `cabal update`, a subsequent `cabal-nix` might start installing a bunch of new packages. (Somewhat related to @hvr 's way-back feature.)

**Comment by hvr** [comment]
Btw I actually love that `cabal new-build` rebuilds stuff against the latest versions by default, some stuff I'm working on relies on this very property. Freezing the package db should be something the user explicitly requests (e.g. by writing something like `index-snapshot: 2015-12-24T14:43` into the `cabal.project` file).

**Comment by edsko** [comment]
Ah, yes, I'm not suggesting freezing should happen by default.

**Comment by hvr** [comment]
I hope I'll get to forward-porting the index-wayback branch very soon so we can glue it all together and see how it interoperates with nix-local-build & hackage-security

**Comment by edsko** [comment]
Note that always defaulting the latest and greatest of all packages also means we end up with tons of different permutations of packages with their dependencies in the store. Still not convinced that this is the most sensible default.

**Comment by ezyang** [comment]
There is now `cabal new-freeze` which should have the desired effect.
