### ISSUE TITLE
Add guidelines around FIXME/TODO/XXX

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#3001]
(Placeholder comment, I'll update the issue shortly with a proper description.)

**Comment by BardurArantsson** [comment]
Note to self: #2800 is relevant

**Comment by BardurArantsson** [comment]
Note to self: Import style is wildly inconsistent

**Comment by BardurArantsson** [comment]
Maybe: We should also add detection of trailing whitespace to our Travis build? (Seems a shame to use so many resources for such a simple thing, but GitHub doesn't allow shell hooks, I'm guessing?)

**Comment by 23Skidoo** [comment]
> Maybe: We should also add detection of trailing whitespace to our Travis build?

+1.

**Comment by BardurArantsson** [comment]
More note to self: Travis supports failing the build but continuing on; that should alleviate *some* of the aggravation factor of having whitespace checks in Travis.

**Comment by ezyang** [comment]
I recently changed it to fail more quickly (and people liked it.) I for one would like to get a failure status from Travis more quickly than less quickly. Makes the logs easier to parse too.

**Comment by BardurArantsson** [comment]
Once people get their editor configured and set up it properly it should really be a non-issue (i.e. should never happen), at least if we think about only whitespace. (We *could* start enforcing no-FIXMEs-on-merge, but that cannot be automatically handled by editors, so...)

My thinking here was that it would be pretty obnoxious for first-time contributors to have to wait 10-15 minutes for a PR to *start* building only to have it rejected early (without even compiling any of their Haskell code!) because of whitespace. Make sense?
