### ISSUE TITLE
Don't overwrite build artefacts when switching ghc version

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3011]
We talked about this already, recording so we don't forget. Perhaps we ought to have some kind of "named profiles", so that build artefacts are stored in `dist-newstyle/:profile/...`. Currently it's very annoying that when i switch `ghc` version everything (local) gets overwritten.

**Comment by ezyang** [comment]
As a workaround, you can manually get a named profile by changing the name of the dist directory (from `dist-newstyle`). I'm not sure if `-builddir` does the trick, but creating a new directory where its contents are symlinks to the other projects certainly does.

**Comment by ezyang** [comment]
This is fixed in HEAD.
