### ISSUE TITLE
cabal install should recognize if package was already configured

### ISSUE THREAD

**Issue by bos** [haskell/cabal#302]
(Imported from [Trac #309](http://hackage.haskell.org/trac/hackage/ticket/309), reported by bfr on 2008-07-05)

If I first configure an unpacked package inside its source directory

<blockquote>
cabal configure --prefix=/my/path --flags=whatever

</blockquote>
and then afterwards do

<blockquote>
cabal install

</blockquote>
then the configure options I gave before are not recognized by the 'cabal install'.

Instead, 'cabal install' without a package name argument should inspect whether the package is already configured and use whatever options have been set.

**Comment by ezyang** [comment]
Yeah, we're not going to do this.
