### ISSUE TITLE
Parser problem

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3032]
This works:

```
packages: foo.cabal,
          -- comment
          bar.cabal
```

but this does not

```
packages: -- first comment
          foo.cabal,
          -- another comment
          bar.cabal
```

**Comment by dcoutts** [comment]
This is not specific to the new nix style stuff. The same property of the syntax is true of .cabal files and others.

The rule is that comments have to be on a line on their own. The reason for this rule is that -- is a legitimate occurrence in program flags.

**Comment by edsko** [comment]
Fair enough. I guess what made that there would be no feedback at all, just no packages being built, leaving the user wondering what's going on. But I suspect with the new interpretation of blobs that will be a lot clearer.

**Comment by 23Skidoo** [comment]
Looks like a `wontfix`.
