### ISSUE TITLE
Drop 6.4.1 InstalledPackageInfo support

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3034]
@dcoutts has stated that he'd be happy to drop it, so let's do it.

**Comment by 23Skidoo** [comment]
+1.

**Comment by dcoutts** [comment]
This would leave 6.4.2 as the earliest ghc version we support.

**Comment by BardurArantsson** [comment]
This was merged as https://github.com/haskell/cabal/commit/94e59da83627b8db9294f48952c6e8b82ef16122 (part of https://github.com/haskell/cabal/pull/3047 ) wasn't it? Shouldn't this be closed?

**Comment by ezyang** [comment]
Yep, closed!
