### ISSUE TITLE
Cabal should ifndef CURRENT_PACKAGE_KEY macro definitions

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3041]
@mgsloan reports that Stack has to manually undef CURRENT_PACKAGE_KEY in order to avoid a slew of redefinition errors. We should ifndef these macro definitinos.

**Comment by mgsloan** [comment]
Note that this is in the case where we're loading up ghci with multiple packages, and so multiple cabal_macros.h

**Comment by 23Skidoo** [comment]
Won't this break packages that actually use `CURRENT_PACKAGE_KEY`?

**Comment by ezyang** [comment]
Yes, but as long as GHCi doesn't know how to manage multiple sets of preprocessor flags when loading in files, there is nothing you can do.
