### ISSUE TITLE
Dependency graph information in 'master'

### ISSUE THREAD

**Issue by jystic** [haskell/cabal#3048]
I make heavy use of the dependency graph information added in c0b3c7f1b6ae7bb7663a2c18578ede95d6a40919 and I would hate to lose it, but this commit doesn't seem to be available in master.

Is there a plan to cherry-pick or merge this across before the new cabal is released?

/cc @hvr

**Comment by ezyang** [comment]
Looks easy enough to cherry-pick.

**Comment by hvr** [comment]
@jystic yes, I certainly hope so. You may also be interested that I want to add an option to dump that information nicely structured as JSON document for further processing by tooling (there's code for that already in the `cabal new-build` codepaths which the old codepaths may be able to build upon)

**Comment by jystic** [comment]
@hvr that sounds great, look forward to it!
