### ISSUE TITLE
[nix-local-build] Recompiling packages with many components is still pretty slow

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3049]
nix-local-build has to attempt to recompile EVERY component, even if files from only one component has changed. There seems to be some non-zero latency associated with thinking about a file, so when nix-local-build ends up hitting every component, this combined with GHC's recompilation avoidance latency makes the latency pretty bad.

**Comment by dcoutts** [comment]
To really do this we would need to be able to `Setup build` (or equiv) a component without it doing its own checks for dependent components. Probably the best approach to that is to go directly to the Cabal lib, bypassing the `Setup build` CLI API. Alternatively it needs some flag to `Setup build` to build exactly the given components without also rebuilding their deps.

**Comment by ezyang** [comment]
Will be fixed by #3662
