### ISSUE TITLE
Cabal library implicitly depends upon global current working directory

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#3051]
The Cabal library (in particular `configure`) appears to depend implicitly upon the process's current working directory, making it rather tricky to use in a larger application. See, for instance, https://github.com/snowleopard/shaking-up-ghc/issues/170.

**Comment by BardurArantsson** [comment]
If I recall correctly during my work on trying to search for the .cabal file in parent directories, this is actually surprisingly non-trivial to do.

(Not that I wouldn't like to see it, but I'm just leaving this note in case anyone wants to attempt it.)

**Comment by quasicomputational** [comment]
AIUI, @angerman has solved this with #4874, and, while there are probably still lurking bugs and definitely some spots of CWD dependence, this is done well enough that Hadrian's happy with it.
