### ISSUE TITLE
'sandbox delete-source' test failure on Windows

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3059]
sandbox-sources
      should_run
        report_success_removing_source.sh (ignoring stderr):                OK (0.45s)
      should_fail
        fail_on_nonexistent_source.sh (ignoring stdout):                    FAIL (0.44s)
          Unexpected exit status.
  
          Exit status: ExitSuccess
          Working directory: C:\Users\kristen\AppData\Local\Temp\cabal-install-test-11967\should_fail
  
          <stdout> was:
          Success deleting sources: "p"
  
          Note: 'sandbox delete-source' only unregisters the source dependency, but does
          not remove the package from the sandbox package DB.
  
          Use 'sandbox hc-pkg -- unregister' to do that.
  
  
          <stderr> was:
        fail_removing_source_thats_not_registered.sh (ignoring stdout):     FAIL (0.33s)
          <stderr> did not match file 'C:\cabal\cabal-install\tests\IntegrationTests\sandbox-sources\should_fail\fail_removing_source_thats_not_registered.err'.
          Exit status: ExitFailure 1
          Working directory: C:\Users\kristen\AppData\Local\Temp\cabal-install-test-11968\should_fail
  
          <stdout> was:
  
  
          <stderr> was:
          Warning: Sources not registered: "q" "r" "s"
  
          cabal.exe: The sources with the above errors were skipped. ("q" "r" "s")

It looks like cabal can remove the non-existent sources on Windows because `canonicalizePath "p"` succeeds even when `p` doesn't exist.  There is an error on Linux: `canonicalizePath: does not exist (No such file or directory)`  https://github.com/haskell/cabal/blob/083e73daa3dd5149b86ab48518703af880df9b2b/cabal-install/Distribution/Client/Sandbox/Index.hs#L182

I also noticed that the .err files for both tests contain the executable name, which differs on Windows.

**Comment by BardurArantsson** [comment]
Re: Executable name: The "simple regex version" described in #2872 might be relevant to implement as part of solving this. It shouldn't be that much more effort compared to butchering the test case to use various forms of "grep" and status code checking, etc.

**Comment by grayjay** [comment]
The same two failures occur on Linux with `directory >= 1.2.3.0`.

**Comment by grayjay** [comment]
Here is my idea for fixing the tests.  Does this sound reasonable?
* `fail_on_nonexistent_source` - This test should allow the command to either fail with the correct error message, or succeed.
* `fail_removing_source_thats_not_registered` - This should only test removing an existing source that is not registered.  It currently also tries to remove a non-existent source.

**Comment by 23Skidoo** [comment]
@grayjay 
> Does this sound reasonable?

Yes, it does.
