### ISSUE TITLE
installedPackageId vanished

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#3068]
`Distribution.Package.installedPackageId` and `Distribution.InstalledPackageInfo.installedPackageId` no longer exist. It turns out that these are used by a number of packages. I seem to recall there were more, but all I can find at the moment is `packunused` (see https://github.com/hvr/packunused/blob/master/packunused.hs#L12)

**Comment by phadej** [comment]
at least recent commit https://github.com/haskell/cabal/commit/ecdf65a3c1e01b798e9d073258a6d1c8ff63a6d8 shows it will be soon back.

cc @ezyang

**Comment by ezyang** [comment]
We can offer more compatibility wrappers but the constructor has changed so packunused is not going to work without more changes (I think if you just use "display" rather than unpack it manually that should help.)
