### ISSUE TITLE
`cabal bench` ignores RTS options

### ISSUE THREAD

**Issue by crockeea** [haskell/cabal#3079]
I have a multi-threaded program that I'd like to benchmark. If I run `cabal bench +RTS -N4`, I get no speedup relative to `-N1`. However, if I directly run the executable with these options (i.e. `./dist/build/bench/bench +RTS -N4`), I see the speedup I expect. It seems cabal is ignoring the RTS options.

**Comment by 23Skidoo** [comment]
Try `cabal bench --benchmark-options="+RTS -N4"`.

**Comment by crockeea** [comment]
Are the RTS options black-holed without the --benchmark-options, or are they used for some other purpose? Can cabal warn me if I'm giving it arguments it doesn't know how to handle?

**Comment by 23Skidoo** [comment]
When you run `cabal bench +RTS -N4`, you're passing RTS options to the `cabal` executable itself.

**Comment by crockeea** [comment]
Okay, thanks for your help. `--benchmark-options` it is.
