### ISSUE TITLE
custom-setup should respect hs-source-dirs

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3085]
Otherwise, we can't support Cabal self-bootstrapping now that the source files have gone into `src`.

**Comment by ezyang** [comment]
Chatting with @dcoutts, it seems that we want to keep `custom-setup` stanzas as simple as possible, because any tools which want to use them need to know how to build them and we want to keep this simple. (I'm a little skeptical; maybe this just means that there should be a way for a Cabal project to refer to an external Cabal project to supply the setup script...) Which means that we don't want to do this.

But then how do we bootstrap Cabal now? A thorny issue.

**Comment by 23Skidoo** [comment]
Now that Cabal uses `build-type: Simple`, maybe bootstrapping should be something that is only done manually? This will mean that `Cabal.cabal` will only be able to use Cabal features that are available in supported GHC versions. Not sure how bad of a limitation this is.

**Comment by ezyang** [comment]
The obvious way to manually bootstrap (`cabal install Cabal; cabal install cabal-install`) is fairly annoying when you are refactoring data structures like `LocalBuildInfo`. (You may not want to "just" build a `Setup` executable because you want cabal-install to take care of things for you, e.g. `cabal new-build`.) It's possible that `cabal-install` could be adjusted to make this case easier ("Yes, I know it's a Simple build type, but please use this setup executable anyway").

**Comment by hvr** [comment]
@ezyang are you considering `cabal.project`-based development of Cabal+cabal-install, or is this still about the pre-nix workflows?

**Comment by ezyang** [comment]
This is in both worlds, but I'm thinking about Nix workflow.

**Comment by ezyang** [comment]
Cabal got moved out of `src` back to the base directory so this problem is no longer a blocker for Cabal. So I guess close for now. See also https://github.com/haskell/cabal/issues/3003
