### ISSUE TITLE
cabal-install test suite: are we intended to create a fresh category for each new test?

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3086]
Hey @BardurArantsson, I want to add some tests for `build-type: Custom` to the cabal-install test suite, but I couldn't figure out what the intended directory layout for this is. I need a separate Cabal package for each test. Am I supposed to make a subdir in `custom/should_run/pkg` and then cd into that directory before running the test? But IIRC you copy the entirety of `custom` to the work directory, so if I add a lot of different, unrelated packages here, we'll do a lot of unnecessary copying. So am I supposed to make a new category for each one?

Advice appreciated!

**Comment by BardurArantsson** [comment]
Don't have time to look at the code right now, but IIRC...

- Each "group" (or category) is copied for every test
- If you add files add the "group" level, you can reference them using relative (e.g. `../custom.sh`) paths from each individual test. You could probably also use (relative) symlinks for this. I don't think I've tested explicitly, but I *think* adding non-test directories at the "group" level should also work. AFAIR it just blindly copies everything (including other tests)
- I wouldn't worry about excessive copying unless we're really talking huge files or huge numbers of files (several hundreds or thousands).

So: If your individual tests need to share a lot of (e.g.) package directories, then I'd definitely add them at the "group" level, perhaps using an _-prefix convention[1] to distinguish from the actual test directories. Then either just use relative paths (if possible, e.g. add-source supports that, IIRC) or use symlinks. Each instance of a test (when run) will get its own copy, so you don't have to worry about any "state" contamination across tests in these directories.

I guess I should really write some of this up in a README in the test directory. Feel free to create an issue for that and assign it to me! (Can't promise I'll get to it soon, though. Very busy at work at the moment.)

[1] Maybe we should do the opposite and force test directories to be prefixed with `test-`. Haven't thought about this too much.

**Comment by ezyang** [comment]
Thanks, so perhaps this test looks OK? https://github.com/ezyang/cabal/commit/fef3ecda0f6ac0fef48b37ecd37d0077bab0d95d (I was going to add some more files like `plain.sh` using different packages.)

BTW, are we really supposed to copy `common.sh` for every category? Seems a bit silly.

**Comment by BardurArantsson** [comment]
Yeah, it was that or copy *all* the tests for every test case. I decided just copying `common.sh` was the lesser of two evils. (It could be argued that there could plausibly be differences in `common.sh` between tests of different 'areas' of cabal-install, but I'm not sure that's actually the case in any of the existing tests, so...)

**Comment by BardurArantsson** [comment]
... soooo, as I mentioned: Please create an issue for documentation (and please reference all the issue numbers you can think of!) to adress this.

I'll just close, but feel free to reopen if you don't feel a new issue would adress the problems! :)
