### ISSUE TITLE
Some issues profiling an executable

### ISSUE THREAD

**Issue by vladfi1** [haskell/cabal#3107]
I'm building a package (in a sandbox) that has both a library and an executable that depends on the library. I'd like to profile the library by running the executable, so in the sandbox I have a cabal.config file that says:
```
library-profiling: True
executable-profiling: True
```
However, cabal tells me that
```
Warning: The flag --enable-executable-profiling is deprecated. Please use
--enable-profiling instead.
```
If I change ```executable-profiling``` to ```enable-profiling``` I instead get that:
```
Unrecognized field enable-profiling on line 6
```

Worse, my executable fails to compile because of missing dependencies. In particular, when cabal tries to build the executable, it for some reason decides to rebuild the library as well (maybe because of the extra profiling flags I have enabled for the executable?), and since the executable does not explicitly say that it depends on anything other than the library itself, I get lots of "Could not find module... It is a member of hidden package...".

What is the right way to do this?

**Comment by vladfi1** [comment]
I've worked around the compilation problem by following the advice here: http://stackoverflow.com/questions/6711151/how-to-avoid-recompiling-in-this-cabal-file

**Comment by 23Skidoo** [comment]
Use `profiling: True` instead of `executable-profiling: True`.

**Comment by 23Skidoo** [comment]
The `--enable-profiling` message is about the `cabal configure` command. Configuration files don't need the `--enable` bit.

**Comment by vladfi1** [comment]
So profiling: True covers both executables and libraries?

**Comment by 23Skidoo** [comment]
Yes, `profiling` now implies `library-profiling`.
