### ISSUE TITLE
Bad error message on Windows when there's no network connection

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3115]
[Quoting @ShabbyX](https://github.com/haskell/cabal/issues/1733#issuecomment-180928144):

> I was in a virtual machine, running windows 7 with the DHCP service disabled (so I didn't have internet connection) and this error popped out. cabal-install version 1.22.6.0. Starting the DHCP server solved this issue.
> 
> Not only cabal update gave this error, but cabal install complained about log files missing. It seems that when cabal fails to connect to where it wants, it fails with random other errors.

**Comment by 23Skidoo** [comment]
For googlability: error message is the infamous "does not exist".

**Comment by ulysses4ever** [comment]
This looks like history. I propose we close it.

**Comment by Mikolaj** [comment]
Let's enshrine this history in a closed ticket.
