### ISSUE TITLE
Push a release candidate tarballs some somewhere publicly accessible

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#3127]
The GHC 8.0.1 release candidates require an unreleased Cabal (see, e.g. [Trac #11558](https://ghc.haskell.org/trac/ghc/ticket/11558)). At the moment I manage this by requesting that users install Cabal and cabal-install from git. It would be more convenient, however, if we could place source tarballs somewhere so users could `cabal install http://.../cabal-1.23-rc1.tar.bz2 http://.../cabal-install-1.23-rc1.tar.bz2`.

**Comment by hvr** [comment]
What about uploading as package candidates to Hackage? then we also get URLs suitable for `cabal-install`, as well as a place hosting candidate haddocks for Cabal...

**Comment by 23Skidoo** [comment]
@hvr I can do that. Can you please add me to the Cabal maintainers group on Hackage?

**Comment by hvr** [comment]
@23Skidoo ...I can't myself, but I've just summoned the powers that can!

**Comment by 23Skidoo** [comment]
@hvr Thanks!

**Comment by hvr** [comment]
@23Skidoo btw, you can use `hackage-cli push-candidate ...tar.gz` to automate pushing candidates until `cabal upload` learns how to do that... :-)

https://github.com/hvr/hackage-cli

**Comment by 23Skidoo** [comment]
Thanks! Yes, we should teach `cabal upload` to do that as well.

**Comment by 23Skidoo** [comment]
Just uploaded Cabal/cabal-install 1.23 candidates to Hackage:

* http://hackage.haskell.org/package/Cabal-1.23.1.0/candidate/Cabal-1.23.1.0.tar.gz
* http://hackage.haskell.org/package/cabal-install-1.23.0.0/candidate/cabal-install-1.23.0.0.tar.gz

**Comment by 23Skidoo** [comment]
@bgamari BTW, what is the currently planned release date for GHC 8 RC3?

**Comment by phadej** [comment]
shouldn't those be Cabal-1.24 - **24** ?

**Comment by 23Skidoo** [comment]
I considered bumping the version, but decided that it will be useful to be able to distinguish these snapshots from the official 1.24 release when dealing with bug reports.

**Comment by bgamari** [comment]
Ahh, sorry; somehow notification of this slipped through my inbox. Thanks for posting those candidates!

@23Skidoo It's not perfectly clear at the moment; it largely depends upon how quickly we can get the runtime representation rework in, which is at this point blocked on either me or Richard working through some performance regressions. The next rc may come as early as next week although at this point the week after may be more likely.

**Comment by 23Skidoo** [comment]
@bgamari Thanks, I'll try to merge the remaining patches planned for 1.24 during this week.
