### ISSUE TITLE
Investigate whether 'D.C.Compat.Time' actually works as advertised

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3132]
@dcoutts noticed that this module actually doesn't provide us with sub-second resolution. This should be investigated and fixed.

**Comment by BardurArantsson** [comment]
Just a little caveat: I believe there are file systems and possibly OS'es which don't actually provide sub-second precision on things like file modification times. (I wish I could be more specific, but it's been a while...)

**Comment by 23Skidoo** [comment]
> [For example, the resolution of create time on FAT is 10 milliseconds, while write time has a resolution of 2 seconds and access time has a resolution of 1 day, so it is really the access date.](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290%28v=vs.85%29.aspx)

But this about the code being buggy on all file systems.

**Comment by BardurArantsson** [comment]
Fair enough! As you were -- sorry about the noise :)

**Comment by 23Skidoo** [comment]
/cc @dcoutts 

Perhaps this can be now used in the `FileMonitor` implementation.
