### ISSUE TITLE
Make bootstrap.sh usable with GHC 8.0

### ISSUE THREAD

**Issue by bjpe** [haskell/cabal#3133]
Hi, I tried to install `cabal-install` via the `bootstrap.sh` script for GHC 8.0 and discovered the following issues I'd like to report:

* GHC 8.0 no longer provides the package `old-time`, and it is also not installable for GHC 8.0. Furthermore, it is also not required for GHC 8.0, so that the script should not try to install it.
* The script also tries to install `old-locale`, which is neither provided by GHC 8.0 nor does it occur in the configuration of `cabal-install`. Thus, it seems as it could be removed from the script.
* The script tries to install `HTTP-4000.3.2`, which does not work with GHC 8.0. Since `HTTP-4000.3.3` does, the script should be adjusted.
* The package `ed25519` can also not be installed because of thoughtpolice/hs-ed25519#10.

Thanks, Björn

**Comment by hvr** [comment]
@bjpe

 -  why is `old-time` not installable for GHC 8.0? Looks fine to me on http://matrix.hackage.haskell.org/package/old-time
 - and older version of `ed25519` is installable with GHC 8: http://matrix.hackage.haskell.org/package/ed25519

**Comment by bjpe** [comment]
@hvr I tried again and figured out that the downloaded tarballs for `old-locale` and `old-time` contain the constraints `base >= 4.2 && < 4.9` and  `base >= 4.7 && < 4.9` respectively. However, in the linked package description the constraints have been relaxed.

Maybe this is caused by some updated revision (for further information, see https://mail.haskell.org/pipermail/haskell-cafe/2016-February/123095.html for the same problem for the `mtl` package).

**Comment by bjpe** [comment]
Regarding the package `ed25519` I only tried the version `0.5.0.0` since this version is automatically selected by the `bootstrap.sh` package and I only wanted to report problems with the current script.

**Comment by 23Skidoo** [comment]
I guess we can build `ed25519` with `--allow-newer`.

**Comment by 23Skidoo** [comment]
Fixed. I had to downgrade ed25519 to 0.2.0.0 temporarily.

**Comment by hvr** [comment]
@23Skidoo fyi, http://hackage.haskell.org/package/ed25519-0.0.5.0/revisions/ -- but that doesn't help with the `bootstrap.sh` script unless it learns how to fetch revised `.cabal` files
