### ISSUE TITLE
add-source deps are not reinstalled when LBI can't be loaded

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3136]
Reinstallation of add-source deps is done in `reconfigure`, and that function silently ignores bad version errors and returns when loading LBI fails. This can happen when a package is using `build-type: Custom` and the setup script is built against a different version of Cabal than `cabal-install`. So changes in add-source deps are ignored in this case.

**Comment by phadej** [comment]
sandbox functionality is removed.
