### ISSUE TITLE
configureToolchain tests the wrong ld for -x support

### ISSUE THREAD

**Issue by rwbarton** [haskell/cabal#3140]
Steps to reproduce: Set `ld command` to `false` in the ghc settings file. Then try to build any package.

Output with `-v` includes
```
/home/rwbarton/bin/ghc -c /tmp/16816927771714636915.c -o /tmp/1957747793424238335.o
/usr/bin/ld -x -r /tmp/1957747793424238335.o -o /tmp/7198853861649760492.o
...
```
Expected output was `false -x -r /tmp/1957747793424238335.o -o /tmp/7198853861649760492.o`.

This is bad for two reasons:

* We're presumably going to use the `ld` from `ghc --info` later, rather than the system linker, so that's the one for which we need to know whether it supports `-x`. (Though I don't know when Cabal actually uses `ld`, if ever.)

* Using the system linker here can fail in some scenarios, such as when running a 32-bit ghc on a 64-bit host system.

As a workaround I have to use the `--with-ld` flag manually. Then this works as expected.

**Comment by rwbarton** [comment]
Also, after running `ld`, Cabal just exits with an error like
```
cabal: /tmp/7198853861649760492.o: does not exist
```

I think that this is an exception from the last `withTempFile` failing to delete the temporary file, which I guess was removed by `ld` (because the input file was for the wrong architecture). Probably the `catchIO` was intended to have a wider scope than just the innermost do block.

**Comment by 23Skidoo** [comment]
I think this happens because it's looking for an executable called just `ld`. If you copy `/bin/false` to `/foo/bar/ld` and then set `ld program` to `/foo/bar/ld`, it should work.

**Comment by rwbarton** [comment]
Oh, weird. Indeed, it did. But that seems wrong also, since e.g. `/usr/bin/ld.gold` is a common value for ld command (e.g. on ARM where this is important), and Cabal doesn't seem to recognize that as being `ld`. Shouldn't Cabal just use whatever GHC says to? When does Cabal run `ld` anyways?

In my real situation, the `ghc --info` output line is
```
 ,("ld command","/home/rwbarton/bin/i386-unknown-linux-ld")
```

**Comment by 23Skidoo** [comment]
> Shouldn't Cabal just use whatever GHC says to?

Yes, I think it should. I'll write a patch.

**Comment by 23Skidoo** [comment]
@rwbarton See #3141. Would be nice if you could confirm that it fixes your problem.
