### ISSUE TITLE
Incorrect cabal_macros.h on Windows

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3145]
Building Cabal with `-Werror`:
    
    $ ./Setup.exe build
    Building Cabal-1.23.2.0...
    Preprocessing library Cabal-1.23.2.0...
    
    In file included from <command-line>:8:0:
    
    dist\build\autogen\cabal_macros.h:102:0:
         error: "TOOL_VERSION_gcc" redefined [-Werror]
    
    dist\build\autogen\cabal_macros.h:95:0:
         note: this is the location of the previous definition
    
    dist\build\autogen\cabal_macros.h:103:0:
         error: "MIN_TOOL_VERSION_gcc" redefined [-Werror]
    
    dist\build\autogen\cabal_macros.h:96:0:
         note: this is the location of the previous definition
    cc1.exe: all warnings being treated as errors

`cabal_macros.h` contains these lines:

```c
/* tool gcc-4.6.3 */
#define TOOL_VERSION_gcc "4.6.3"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  6 || \
  (major1) == 4 && (major2) == 6 && (minor) <= 3)

/* tool gcc.exe-4.6.3 */
#define TOOL_VERSION_gcc.exe "4.6.3"
#define MIN_TOOL_VERSION_gcc.exe(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  6 || \
  (major1) == 4 && (major2) == 6 && (minor) <= 3)
```

The error was introduced in 6ba18a6f252b13e0e80c690b5ea709a5c1de13af.  I also noticed that AppVeyor stopped running: https://ci.appveyor.com/project/23Skidoo/cabal/history

**Comment by ezyang** [comment]
CC @23Skidoo

**Comment by 23Skidoo** [comment]
That's interesting.

**Comment by 23Skidoo** [comment]
Should be fixed now. Also fixed AppVeyor configuration - looks like it didn't enable the webhook automatically for some reason.
