### ISSUE TITLE
cabal on RaspberryPi 2

### ISSUE THREAD

**Issue by neuwirthe** [haskell/cabal#3149]
I am trying to build the latest cabal on an RPi 2.
I found a working binary installer of ghc 7.10.3.
Then I tried to install cabal from source from here:
https://www.haskell.org/cabal/release/cabal-install-1.22.8.0/cabal-install-1.22.8.0.tar.gz
When running ./bootstrap.sh I get

```
  Using local tarball for mtl-2.2.1.
  [1 of 1] Compiling Main             ( Setup.hs, Setup.o )
  Linking Setup ...
  Setup: schedule: re-entered unsafely.
     Perhaps a 'foreign import unsafe' should be 'safe'?

```
How can I get a working version?

**Comment by bgamari** [comment]
You are almost certainly using a buggy LLVM release. GHC requires LLVM 3.5.2 or later. See [GHC #11574](https://ghc.haskell.org/trac/ghc/ticket/11574#comment:3) for details.

**Comment by neuwirthe** [comment]
I was using 3.5.0. So I installed 3.7.1 from 
[http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-armv7a-linux-gnueabihf.tar.xz](http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-armv7a-linux-gnueabihf.tar.xz)
Then I unarchived cabal-install from
[http://hackage.haskell.org/package/cabal-install-1.22.8.0/cabal-install-1.22.8.0.tar.gz](http://hackage.haskell.org/package/cabal-install-1.22.8.0/cabal-install-1.22.8.0.tar.gz)
but I still get

```
tm-2.4.4.1 will be downloaded and installed.

Downloading mtl-2.2.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15391  100 15391    0     0   2665      0  0:00:05  0:00:05 --:--:--  3615
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Setup: schedule: re-entered unsafely.
   Perhaps a 'foreign import unsafe' should be 'safe'?

Error during cabal-install bootstrap:
Configuring the mtl package failed.

```

**Comment by 23Skidoo** [comment]
So it fails while trying to run `mtl`'s setup script. Probably a GHC bug. The only unsafe foreign import in the Cabal library itself is `setenv` in `Distribution.Compat.Environment`. You can try changing it to `safe`, recompiling Cabal and then recompiling the setup script against the patched version of Cabal. I can't guarantee that it will work, though.

**Comment by 23Skidoo** [comment]
Closing in favour of [GHC #11574](https://ghc.haskell.org/trac/ghc/ticket/11574).
