### ISSUE TITLE
`bootstrap.sh` fails with a 404 error

### ISSUE THREAD

**Issue by drbo** [haskell/cabal#3151]
`bootstrap.sh` fails with a 404 error from `curl` on my system (Fedora 23 Linux).

**Comment by 23Skidoo** [comment]
Which file is it trying to download?

**Comment by drbo** [comment]
The command that failed is `curl -L --fail -O https://hackage.haskell.org/package/Cabal-1.23.2.0/Cabal-1.23.2.0.tar.gz`

**Comment by drbo** [comment]
I worked around this by building Cabal from this repository and then running `./bootstrap.sh`, but then I got the `https not supported error` -- I thought that `cabal-install` supported HTTPS now.

**Comment by 23Skidoo** [comment]
This is expected, 1.23.2.0 is not on Hackage. The script could be fixed to support bootstrapping from a Git working copy, though.

**Comment by 23Skidoo** [comment]
> then I got the `https not supported error` -- I thought that `cabal-install` supported HTTPS now.

Try running `cabal --http-transport=curl`.
