### ISSUE TITLE
The "You need to re-run the 'configure' command" message is a bit ugly

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#3157]
Today I stumbled upon Cabal's "you need to reconfigure" message and noticed that not only is it >100 columns wide, but it doesn't have a terminating newline,
```
[0949 ben@ben-laptop network-analysis(distributed)] $ cabal build
You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.23.1.0, now Cabal-1.23.2.0). Additionally the compiler is different (was ghc-7.10, now ghc-8.0) which is probably the cause of the problem.[0949 ben@ben-laptop network-analysis(distributed)] $ 
```
As far as bugs go this is pretty minor, but it seems like it shouldn't be difficult to fix. It seems that ideally `ConfigStateFileError` would have a `Text` instance and whoever is catching this exception would use it one way or another.

**Comment by 23Skidoo** [comment]
We do call `wrapText` in `topHandler`, it looks like something else is going on here. Is this a package with `build-type: Custom`?

**Comment by bgamari** [comment]
Mikhail Glushenkov <notifications@github.com> writes:

> We do call `wrapText` in `topHandler`, it looks like something else is
> going on here. Is this a package with `build-type: Custom`?
>
Afraid not, `build-type: Simple`

**Comment by 23Skidoo** [comment]
I have actually encountered this once or twice, but right now am having problems reproducing.

**Comment by ttuegel** [comment]
> It seems that ideally ConfigStateFileError would have a Text instance and whoever is catching this exception would use it one way or another.

I don't believe it does. I'll take a look.

**Comment by 23Skidoo** [comment]
It doesn't, but one approach to this is to replace its `Show` instance with `Text` and fix the compile errors.

**Comment by ttuegel** [comment]
I'm not sure about this now; should I write a `Text` instance, complete with `parse`? I don't expect anyone will need to parse an error message. Would a one-off function, e.g. `dispConfigStateFileError :: ConfigStateFileError -> Doc` be more appropriate?

**Comment by 23Skidoo** [comment]
You're right, it doesn't need a `parse`.

**Comment by ttuegel** [comment]
The root cause turned out to be that we only used `wrapText` on `IOException`s. I just needed to move the call up in `topHandler` so it applies to all exceptions. My PR will be on its way soon; I am taking this opportunity to improve the messages `ConfigStateFileError` throws.

**Comment by 23Skidoo** [comment]
Great, thanks for working on this.
