### ISSUE TITLE
Bump Cabal library version number every time the LBI binary format changes

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3181]
Quoting @ezyang in https://github.com/haskell/cabal/issues/2114#issuecomment-173001567:

> [...] I'd prefer it if we could figure out how to get Travis to bleat if you change any of the binary formats. Here's a proposal:
> 1. For every data structure which has a binary format which is shared across the Cabal/cabal-install boundary, we keep checked in a binary serialized version of it based on some sentinel value (it could be `mempty`, or it could be a custom value we write for each of them.)
> 2. We add a script to re-generate these binary serialized versions and admonishes you to bump the version.
> 3. Travis checks if this binary serialized version has changed (similar to the current `misc` script for checking if `other-files` is correct.)
> 
> FWIW, we should NOT bump the patch level, this is a BC-incompatible change so we should bump the appropriate number.

**NB:** this is about the version numbers of development snapshots, released versions are guaranteed to be binary compatible. As a palliative we can bump the version number manually every time a GHC RC is released for now.

Also we should bump the Cabal version number every time an option gets added to `Setup configure/build/...` that `cabal-install` might want to use. See `filterConfigureOptions` & `filterBuildOptions`.

**Comment by Mikolaj** [comment]
I'm about to make a new release. Is this still relevant? I bet we lost the CI check for that long ago (when Travis died). When exactly should we bump what?

**Comment by Mikolaj** [comment]
I'm again about to make a cabal new release (3.10). Is this still relevant? If not, I'm going to close.
