### ISSUE TITLE
Pass short path names to configure scripts on Windows

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3185]
In #2946 we changed Cabal to use the standard mechanism when passing the gcc path to `configure` scripts. Unfortunately, it looks like this feature is still broken (at least on Windows) when the path contains spaces (a bug in Autoconf). A workaround that is confirmed to work is to use [short path names](https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx). We should change Cabal to do that automatically.

**Comment by gbaz** [comment]
Of the mechanisms to get short path names in windows, this looks fairly reliable for programmatic use: http://stackoverflow.com/a/21786312/371753

**Comment by 23Skidoo** [comment]
Is `GetShortPathName` unreliable?

**Comment by gbaz** [comment]
Calling the function directly should work fine too. I just tend to prefer to shell out rather than deal with more bindings...

**Comment by Mistuke** [comment]
8.3 short names can be disabled for performance reasons https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#short_vs._long_names 
So I don't particularly like this as the default. Isn't there another possible fix?

**Comment by 23Skidoo** [comment]
@Mistuke 
> 8.3 short names can be disabled for performance reasons

The documentation for `GetShortPathName` says:

> If you call GetShortPathName on a path that doesn't have any short names on-disk, the call will succeed, but will return the long-name path instead. This outcome is also possible with NTFS volumes because there's no guarantee that a short name will exist for a given long name.

So it looks like using `GetShortPathName` will be no worse than status quo when 8.3 names are disabled.
