### ISSUE TITLE
can't install cabal-install : Dependency tree exhaustively searched.

### ISSUE THREAD

**Issue by Heather** [haskell/cabal#3187]
F:\P\thridparty\M\cabal\Cabal>cabal install
Resolving dependencies...
In order, the following will be installed:
Cabal-1.25.0.0 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring Cabal-1.25.0.0...
Building Cabal-1.25.0.0...
Installed Cabal-1.25.0.0

F:\P\thridparty\M\cabal\Cabal>cd ..

F:\P\thridparty\M\cabal>cd cabal-install

F:\P\thridparty\M\cabal\cabal-install>cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cabal-install-1.25.0.0 (user goal)
next goal: hackage-security (dependency of cabal-install-1.25.0.0)
rejecting: hackage-security-0.5.0.2/installed-c53... (conflict:
hackage-security => Cabal==1.23.1.0/installed-LRF..., cabal-install =>
Cabal>=1.25 && <1.26)
trying: hackage-security-0.5.0.2
next goal: Cabal (dependency of cabal-install-1.25.0.0)
rejecting: Cabal-1.25.0.0/installed-8P8... (conflict: hackage-security =>
Cabal>=1.14 && <1.25)
rejecting: Cabal-1.23.1.0/installed-LRF..., Cabal-1.22.5.0/installed-00f...,
Cabal-1.22.7.0, Cabal-1.22.6.0, Cabal-1.22.5.0, Cabal-1.22.4.0,
Cabal-1.22.3.0, Cabal-1.22.2.0, Cabal-1.22.1.1, Cabal-1.22.1.0,
Cabal-1.22.0.0, Cabal-1.20.0.4, Cabal-1.20.0.3, Cabal-1.20.0.2,
Cabal-1.20.0.1, Cabal-1.20.0.0, Cabal-1.18.1.7, Cabal-1.18.1.6,
Cabal-1.18.1.5, Cabal-1.18.1.4, Cabal-1.18.1.3, Cabal-1.18.1.2,
Cabal-1.18.1.1, Cabal-1.18.1, Cabal-1.18.0, Cabal-1.16.0.3, Cabal-1.16.0.2,
Cabal-1.16.0.1, Cabal-1.16.0, Cabal-1.14.0, Cabal-1.12.0, Cabal-1.10.2.0,
Cabal-1.10.1.0, Cabal-1.10.0.0, Cabal-1.8.0.6, Cabal-1.8.0.4, Cabal-1.8.0.2,
Cabal-1.6.0.3, Cabal-1.6.0.2, Cabal-1.6.0.1, Cabal-1.4.0.2, Cabal-1.4.0.1,
Cabal-1.4.0.0, Cabal-1.2.4.0, Cabal-1.2.3.0, Cabal-1.2.2.0, Cabal-1.2.1,
Cabal-1.1.6 (conflict: cabal-install => Cabal>=1.25 && <1.26)
Dependency tree exhaustively searched.

**Comment by phadej** [comment]
See https://github.com/haskell/cabal/pull/3182 and https://github.com/well-typed/hackage-security/pull/151

**Comment by Heather** [comment]
@phadej thanks, helps
