### ISSUE TITLE
Cabal should support Cabal-version-dependent Setup.hs

### ISSUE THREAD

**Issue by bos** [haskell/cabal#319]
(Imported from [Trac #326](http://hackage.haskell.org/trac/hackage/ticket/326), reported by claus on 2008-08-16)

The manual says about non-standard <tt>Setup.hs</tt>: "good luck". But there are  packages that need non-standard <tt>Setup.hs</tt>, often just very small ones. And all of them risk breakage when Cabal changes.

The first issue is to specify the dependency on a particular Cabal version (#284).

The next issue is that package authors often know how to write their <tt>Setup.hs</tt> for different versions of Cabal, but have to pick one or the other. It would be better to have <tt>Setup.hs</tt> code adapt to as many Cabal versions as possible. Since version mismatch leads to compile errors, that seems to imply either

<ul><li>separate sources (<tt>Setup-v1.4.hs</tt>, <tt>Setup-v1.5.hs</tt>, etc.)
</li></ul><ul><li>one source, with CPP (#if Cabal==1.4 ..)
</li></ul>If I read [Add auto-generated CPP macros for package version testing](http://www.haskell.org/pipermail/cabal-devel/2008-August/003576.html) correctly, that almost provides package version info via CPP. It would only need to provide precise versions instead of lower bounds, and for the Cabal package.

**Comment by 23Skidoo** [comment]
IIUC, this is now fixed with `setup-depends`.
