### ISSUE TITLE
Symlinks for Cabal package tests are not included in the sdist

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3190]
These symlinks aren't listed in `Cabal.cabal`.  When I list them, `./Setup sdist` copies their targets, but we need the symlinks in this case.

```
tests/PackageTests/GhcPkgGuess/Symlink/ghc
tests/PackageTests/GhcPkgGuess/SymlinkGhcVersion/ghc
tests/PackageTests/GhcPkgGuess/SymlinkVersion/ghc
```

**Comment by ezyang** [comment]
...hmm. But we really don't want to distribute an sdist with symlinks in it, makes life harder for Windows people. Not sure what to do here.

**Comment by 23Skidoo** [comment]
Can't the test suite check whether it's running on non-Windows and create them on the fly?

**Comment by ezyang** [comment]
SGTM.
