### ISSUE TITLE
Remove cap on number of jobs?

### ISSUE THREAD

**Issue by mistydemeo** [haskell/cabal#3191]
cabal hardcodes the maximum number of build jobs to 64: https://github.com/haskell/cabal/blob/b402dc87136700be1c231954366c42b67133eaa4/Cabal/Distribution/Simple/Setup.hs#L2240

When reviewing #1142, I didn't see a specific rationale given; maybe this was just trying to restrict it to a sane set of values, or avoid typos? We ran into this in Homebrew - Homebrew/homebrew#49509. Homebrew sets the number of build jobs to the number of threads, usually 2x the number of CPUs. The user in question has a server with two 18-core CPUs, or 72 logical threads, so Homebrew automatically sets 72 build jobs for most software; since this is above the magic number of 64, cabal-install errors out.

**Comment by 23Skidoo** [comment]
Sure, it can be bumped or removed entirely.

**Comment by mistydemeo** [comment]
How about removing it entirely?

**Comment by 23Skidoo** [comment]
Fine with me.

**Comment by mistydemeo** [comment]
Does #3192 look suitable?
