### ISSUE TITLE
ghc-options cannot be used to compile multiple rts opts into a binary

### ISSUE THREAD

**Issue by axman6** [haskell/cabal#3198]
We've been trying to compile in some RTS flags to a binary, and cannot find a way to possibly have all flags compiled in. Some options we've tries include:

```
  ghc-options:  -threaded -with-rtsopts=-TI1 -- This results in -T being compiled in but not -I1
  ghc-options:  -threaded -with-rtsopts='-T -I1' -- This results in the RTS being passed the flag <'-T> (notice the ')
  ghc-options:  -threaded '-with-rtsopts=-T -I1' -- Similar to above, GHC does not understand the flag <'-with-rtsopts=-T>
```

We've tried several more alternatives but we've had to finally resort to just compiling with `-rtsopts` when we'd like to avoid that. As far as we can tell it is currently impossible to pass more than a single option to be compiled into the RTS using a Cabal file. The cause of this seems to be because cabal is doing a dump application of `words` on the string passed via the `ghc-options` directive and then passing each of those "words" as individual arguments, while ghc does not understand multiple flags passed as a group[, like some other command line apps do, a la `tar` etc.

**Comment by 23Skidoo** [comment]
Does `-with-rtsopts=-T -with-rtsopts=-I1` work?

**Comment by axman6** [comment]
From memory no, only the last call to --with-rtsopts is used by GHC

**Comment by 23Skidoo** [comment]
Looking at the code, I see that the parser uses `parseTokenQ'`. So try using `ghc-options: -threaded "-with-rtsopts=-T -I1"`.

**Comment by axman6** [comment]
I'm not sure how to tell if that's actually working, since the issue we're trying to resolve doesn't manifest on my machine. (Excessive CPU usage because the GC runs way too often)

**Comment by axman6** [comment]
That doesn't appear to work either, using:
```
ghc-options:         -threaded "-with-rtsopts=-B -T -I1"
```

I don't get a bell sounding each time a major GC happens, which I do get it I use
```
ghc-options:         -threaded -rtsopts
```
and pass `+RTS -B` to the program.

**Comment by 23Skidoo** [comment]
When I look at `-v2/-v3` output, it does look like the option is passed to `ghc` correctly:

```
$ cabal build -v2
[...]
ghc --make [..] -fwarn-tabs '-with-rtsopts=-B -T -I1' -threaded
```

**Comment by 23Skidoo** [comment]
So I added `"-with-rtsopts=-B -sstderr"` to `ghc-options` in `cabal-install.cabal`, recompiled it and now when I run `./dist/build/cabal/cabal` I get:

```
$ ./dist/build/cabal/cabal
cabal: no command given (try --help)
          78,360 bytes allocated in the heap
           9,936 bytes copied during GC
          42,580 bytes maximum residency (1 sample(s))
          18,860 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.000s   0.001s     0.0006s    0.0006s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.000s  (  0.001s elapsed)
  MUT     time    0.004s  (  0.005s elapsed)
  GC      time    0.000s  (  0.001s elapsed)
  EXIT    time    0.000s  (  0.002s elapsed)
  Total   time    0.004s  (  0.009s elapsed)

  Alloc rate    19,589,999 bytes per MUT second

  Productivity 100.0% of total user, 45.8% of total elapsed

gc_alloc_block_sync: 0
whitehole_spin: 0
gen[0].sync: 0
gen[1].sync: 0
```

So it appears to work, at least with GHC 7.10 and a recent `cabal-install`.

**Comment by 23Skidoo** [comment]
@axman6 Can you please check whether upgrading to a newer `Cabal`/`cabal-install` fixes the issue for you?

**Comment by axman6** [comment]
So it seems that the use of `"-with-rtsopts=-T -I1"` has solved the issue, it would be good if the syntax was documented in the documentation, because clearly with a lot of trial and error we never found the appropriate syntax. Specifically this exact example should probably be used because I imagine it's quite common for people to want to compile in specific its flags without wanting to enable everything available through `-rtsopts`. Happy for this to be closed, but would love to see the docs improved.

**Comment by 23Skidoo** [comment]
@axman6 I added this example to the documentation.

**Comment by axman6** [comment]
Fantastic, thanks so much @23Skidoo!
