### ISSUE TITLE
test-suite does not understand hierarchical structure of source

### ISSUE THREAD

**Issue by andrewufrank** [haskell/cabal#3200]
i have a test main together with the related instance code in ~/app/Store/. 
the instance code is called Store.XX and is as such in the cabal library section.
the test-suite section seems only to work when coded as here 

````
Test-Suite test6fs
    type:       exitcode-stdio-1.0
    main-is:    Datas6FStest.hs
    build-depends:
       base -any
    default-language: Haskell2010
    hs-source-dirs: ., src, Store
    ghc-options: -threaded
````

putting the filename as Store.Datas6FStest.hs gives a "source not found error".

i use:
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library

**Comment by ezyang** [comment]
Does `main-is: Store/Datas6FStest.hs` work?

**Comment by andrewufrank** [comment]
yes, it does - thanks for the hint, but it would be nice, if this could be corrected to work like other parts of cabal.

**Comment by ezyang** [comment]
Well, it's not as simple as that. `main-is` takes a filename, not a module name (see the trailing `.hs` extension.) By design, when you ask GHC to compile an executable, conventionally you pass the filename and not the module name, because by default files which compile to executables have the module name `Main`. So unless I'm missing something, it is quite reasonable for `Store.Datas6FStest.hs` to not work. One might be able to argue that `Store.Datas6FStest` should work, but this is deeply dodgy if the module stored at `Store/Dats6Ftest.hs` actually is just defining `Main`; there's no relationship between the module name and the actual file.

**Comment by andrewufrank** [comment]
i see - thank you for the explanation. i realized that the test-suite does not allow module names which are not Main (despite that the filename has a different name). 
again - thank you for the hint (perhaps you can include it in the cabal manual).
andrew

**Comment by andrewufrank** [comment]
another - perhaps related observatinon 
i get the error message 

````
Warning: The directory /home/xx/.cabal/bin is not in the system search
path.
````
my path is correctly set to include .cabal/bin 
any explanation?

**Comment by ezyang** [comment]
Do you have any symlinks along the way? It's a known bug that Cabal is not clever enough to figure out what's going on in that situation.

**Comment by andrewufrank** [comment]
probably along the same lines:
i get error reports from cabal (inside leksah) that requested packages are not available.
when i install the same package outside of leksah (i.e. in a terminal with working dir the same where the cabal file is and type cabal install it runs - no complaints. 

````
Resolving dependencies...
In order, the following will be installed:
functionalStorage-0.0.2 (reinstall) (changes: appFoundation-0.0.5 added, appcode-0.0.6 added, basics-0.4.0 added)
````

**Comment by andrewufrank** [comment]
no simlinks (.bin and .cabal/bin are ordinary directories), the files are all executables

**Comment by andrewufrank** [comment]
another observation:
i started leksah from the executable 
if i start leksah from a terminal with "`leksah`" the tests are run ok.
if i start it with from an item in a panel (which runs it in a terminal, perhaps with some difference in the
environment) i get 

````
leksah: Can't start leksah-serverleksah-server: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
````
what environmental vars does leksah require?
