### ISSUE TITLE
can't link cabal-install: undefined reference to `_DistributionziText_display1_closure

### ISSUE THREAD

**Issue by Heather** [haskell/cabal#3228]
```
Linking dist\build\cabal\cabal.exe ...
C:\Users\Rainbow\AppData\Roaming\cabal\x86_64-windows-ghc-7.10.3\hackage-security-0.5.0.2-KvpPdaPKCQNF1XIswUzRpz/libHShackage-security-0.5.0.2-KvpPdaPKCQNF1XIswUzRpz.a(Client.o):fake:(.text+0x46d0): undefined reference to `z38UP8K4dohSFOGjUHsQm8yyx_DistributionziText_display1_closure'
...
```

os: win 10 x64

**Comment by 23Skidoo** [comment]
BTW, our AppVeyor build bot uses Windows x64 and GHC 7.10.3 as well, and doesn't seem to bump into this issue. Most likely not a Cabal bug.

**Comment by Heather** [comment]
Removing from AppData and then rebuilding `hackage-security` with `--force-reinstalls` resolved this issue.

not sure if such experience should be documented or if it very specific
