### ISSUE TITLE
changing cabal_macros.h resulting in rebuilds

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3241]
Since 14f055cdcd1559c85b6aacfc3b336b1c74ee6592  `cabal_macros.h` seems to change more often, I've noticed this in the nix-local-branch which forces annoying rebuilds when I first build the `lib:` target and then go on to build a `test:` goal because the library being built  gets added into the global `cabal_macros.h` file now out of a sudden...

So basically 14f055cdcd1559c85b6aacfc3b336b1c74ee6592  is a  regression for me as I can't workaround the effects of #1893  in cabal-1.24 anymore by making sure all non-lib goals have dependencies already mentioned in the main library because I can't have the library depend on itself... :-(

/cc @erikd @dcoutts

**Comment by ezyang** [comment]
This should be fixed by https://github.com/haskell/cabal/pull/3022/commits/ea46482f5193d640d638c16ec7a455240fbb28f5 which is still in CR as part of https://github.com/haskell/cabal/pull/3022

**Comment by hvr** [comment]
@ezyang ...is that scheduled for 1.24?

**Comment by 23Skidoo** [comment]
> ...is that scheduled for 1.24?

No. Maybe we can cherry-pick the relevant changes?

**Comment by hvr** [comment]
actually I may have confused the cabal versions I was testing as I can't seem to be able to reproduce the issue with a cleanly built `cabal`... I need to investigate; I'll close this issue for now again, sorry for the noise

**Comment by ezyang** [comment]
Separating macros per component is a BC breaking change (I know, for example, GHC's build system needs to be adjusted for it). Don't really see an easy way around the BC breakage either, unless we *also* generate a legacy style macro file but don't tell GHC to use it.
