### ISSUE TITLE
cabal check empty exposed module list

### ISSUE THREAD

**Issue by headprogrammingczar** [haskell/cabal#3255]
When a package builds as a library with an empty list of exposed modules, that should be caught by `cabal check`. It's an easy mistake to make.

**Comment by ezyang** [comment]
Related #2982.

**Comment by rightfold** [comment]
I'm going to work on this.

**Comment by rightfold** [comment]
This checks seems to be already in place? https://github.com/haskell/cabal/blob/master/Cabal/Distribution/PackageDescription/Check.hs#L237-L242

**Comment by 23Skidoo** [comment]
Yeah, seems like this has been already fixed in #3441.
