### ISSUE TITLE
Planned improvements to cabal-install integration-tests

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3269]
I was using `integration-tests` and was annoyed by a few things, so I'm planning to fix them. Here is my work plan:

- [x] I'm going to follow @phadej's suggestion to just use `!` to invert the exit code of command which are expected to fail. Then I'll eliminate `should_run`/`should_fail` directories, so we just have a single level of hierarchy. This makes tests which want to work with the same packages but want to test both successful and failing variants more convenient.
- [x] It's annoying to copy paste the same `common.sh` for each category. So I'm going to have a single global common script in `IntegrationTests` which gets copied into all scripts. It will just get pasted into the category directory.
- [ ] Something a little annoying is that I can't run the test script in the temporary directory directly to rerun the test, since the envvars aren't set.  So, instead of passing through the environment variables implicitly, I'll write them to a file. So the expectation is you also write `. ./env.sh` at the top of your scripts.
- [ ] I don't really like `RE:`. It's annoying to write, and it means we can't implement `accept` later. Furthermore, we're only using it to munge cabal.exe to cabal. So I'm going to replace it with a direct munge.
- [ ] The idiom `>/dev/null` is really irritating for debugging, since it means we suppress the output. Cabal's package tests does a lot better here: we turn on verbose by default (for good test logs) and we don't dev null any output. I think perhaps the right thing to do here is to `tee` the output we want to compare against to a log file, and then employ a naming convention for checking these log files (similar to how in package tests we only test the stdout/stderr of a few, important command)
- [ ] The de-interleaving of stderr and stdout is a pain. For display, put them together, and also say which command was run before each.

For now I'm just planning to do the first two, since they seem like obviously good improvements.

CC @BardurArantsson

**Comment by BardurArantsson** [comment]
Not sure what you mean about the "RE:"/munging, but FWIW everything else sounds sensible.

**Comment by ezyang** [comment]
@BardurArantsson I looked at all use sites of `RE:` and it seems to be purely for ensuring we are indifferent to `cabal` versus `cabal.exe` in output. If that's the only case it's used, we can just add a special case to the comparator to substitute occurrences of `cabal.exe` with `cabal` and then drop the regex.

I added one more work item, which is the fact that `>/dev/null` is bad for good test log output.

**Comment by 23Skidoo** [comment]
@ezyang 
>  it means we can't implement `accept` later.

What is `accept`?

**Comment by ezyang** [comment]
It's an idiom in GHC's system, where if your expected stdout/stderr doesn't match the actual, you can "accept" the new output and replace the saved expected stdout/stderr output automatically.

**Comment by BardurArantsson** [comment]
> I looked at all use sites of RE: and it seems to be purely for ensuring we are indifferent to cabal versus cabal.exe in output. If that's the only case it's used, we can just add a special case to the comparator to substitute occurrences of cabal.exe with cabal and then drop the regex.

I'm pretty agnostic on this; needs and practicality should dictate what happens to this. One other case I can think of that *might* turn out to be important would be path names in the output.

Perhaps it would be more sensible to allow placeholders? E.g. something like "%CABAL_EXE% which would match either "cabal" or "cabal.exe"? That could probably sensibly be expanded to matching paths in a cross-platform way.

> I added one more work item, which is the fact that >/dev/null is bad for good test log output.

I agree that it's a bit of a pain.

I wonder if your suggestion could be adequately addressed by setting up an appropriate file descriptor, reading "expected output from that" and using `>& $FD` or similar to make sure stuff you care about reaches that file descriptor. When running outside of the test harness, `common.sh` could set `FD=1` if FD isn't set already.

**Comment by 23Skidoo** [comment]
> It's an idiom in GHC's system, where if your expected stdout/stderr doesn't match the actual, you can "accept" the new output and replace the saved expected stdout/stderr output automatically.

Sounds like an easy way to get false positives :-)
If you think we really need `accept`, maybe it could just error out on files containing `RE:`?
I'm okay with adding special-casing for `cabal.exe`, but `RE:` is a nice general mechanism that could be useful for other things.

**Comment by ezyang** [comment]
> One other case I can think of that might turn out to be important would be path names in the output.

GHC certainly endeavours to not put absolute paths in output; everything is relative to the current working directory. There's definitely some backpressure on how error messages are designed here :)

> I wonder if your suggestion could be adequately addressed by setting up an appropriate file descriptor, reading "expected output from that" and using >& $FD or similar to make sure output you actually care about gets compared with "expected". When running outside of the test harness, common.sh could set FD=1 if FD isn't set already.

I don't think you want this; or, at least, you want to tee instead—the reason is that if you are piping some of the output, it won't show up in the "main" log, so you'll be missing information from the debugging output.

> Sounds like an easy way to get false positives :-)

Works pretty well for GHC, and definitely is why we have such comprehensive error message checking in the test suite. Sometimes tests wobble but then we fix the outputter or the add a filter to make it stop.

**Comment by BardurArantsson** [comment]
> GHC certainly endeavours to not put absolute paths in output; everything is relative to the current working directory. There's definitely some backpressure on how error messages are designed here :)

I was actually just thinking mostly of "/" vs. "\".

> I don't think you want this; or, at least, you want to tee instead—the reason is that if you are piping some of the output, it won't show up in the "main" log, so you'll be missing information from the debugging output.

If `common.sh` were to set FD=1 (if not already set to something else) as described, you'd get output on stdout just like normal.

Anyway, probably not a big deal how it's implemented exactly, but it'd be nice to avoid having to tee to a "magic" file...

Perhaps add a shell function "capture" to `common.sh` which every 'interesting' command could be prefixed with? Then the implementation could change as needed without having to rejig test cases. So you'd have something like

`shell
    cabal init      # don't care about output here
    capture cabal install A      # capture output for comparison
`

Seems like it should be pretty straightforward to implement?

**Comment by ezyang** [comment]
> I was actually just thinking mostly of "/" vs. "\".

Yeah, GHC's test suite just normalises backslashes to normal slashes, as necessary.

> If common.sh were to set FD=1 (if not already set to something else) as described, you'd get output on stdout just like normal.

Sure, but that implies you're going to run the test again. But imagine in Travis, you want to report a test failure: you want the complete log from the original test run.

> Perhaps add a shell function "capture" to common.sh which every 'interesting' command could be prefixed with?

That should be OK, but if there are multiple captures it seems better if they are each explicitly named, so that we can match on them individually (otherwise we have to insert extra markers to distinguish the output of one command from the next.)

**Comment by ezyang** [comment]
Punting this ticket.
