### ISSUE TITLE
~/.cabal/config file includes end of line -- comments in flag args

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#3275]
I'm not sure if this is by design or not
but in my cabal file i had 

```
  docdir: $datadir/doc/$arch-$os-$compiler/$pkgid -- pre 1.24, $abi is equal to this triple?

```

and it included the post `--` part of the line in the doc dir folder name ....

This probably is part of larger family of "line that starts with a comment is ignored" but "lines that end with a line comment go wrong" bugs I think cabal file formats sometime have :(

**Comment by cartazio** [comment]
If you need help reproducing or pinning it down let me know.  I'm pretty sure there's an analogous issue at least historically with project.cabal files. 

The .cabal/config was using the local nix builds branch as of this last week. I can pull up the commit if needed

**Comment by jneira** [comment]
My cabal file with cabal-install-3.2.0.0 does no contain that comment anymore, maybe we could close this one
//cc @phadej

**Comment by cartazio** [comment]
@jneira  the issue was not  THAT CABAL included a comment. BUt rather that cabal used the full line, *including the comment* as the value to pass to in the flag

**Comment by cartazio** [comment]
people should be able to comment their config notes!

**Comment by phadej** [comment]
comments have to be on separate line. We won't change that.

One reason: it is convenient to be able to write `myprog-options: --flag1`.
Another is that selectively adding `--` comment parsing inside individual fields would increase maintenance burden for grammar.

**Comment by cartazio** [comment]
is it documented anywhere that the format only supports comments on their own lines?

**Comment by phadej** [comment]
> is it documented anywhere that the format only supports comments on their own lines?

No. The `.cabal`-like format is formally undocumented. There are some comments in the implementation.

**Comment by jneira** [comment]
Sorry i misunderstood the issue
