### ISSUE TITLE
GHC 7.6 and earlier have buggy relinking avoidance

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3294]
You can see the problem in the Travis failure https://travis-ci.org/haskell/cabal/builds/121240033 for #3289 which has a simple recompilation test.

The proximal patch which introduced this bug is the fix for #842, which separated the build and linking steps (if you don't separate these steps, GHC will correctly relink.)

One obvious fix is this: if GHC is too old, pass `-fforce-recomp` to the linking command. Unfortunately, this does not work: the linking command will subsequently attempt to rebuild all of the modules again. Something like https://ghc.haskell.org/trac/ghc/ticket/11807#ticket would work but obviously the old version of GHC will not have it.

Another fix: we can remove the result of linking before we link it. This does appear to work, assuming we can figure out what it is we are linking.

In the case that there are no C source files that depend on FFI exports, I think there is one more way that this can be fixed: we should revert to pre-#842 and do compilation and linking in one go. This will obviously make the GHC code more complicated, but I suspect it will pay its way: we'll also get faster compilation for new versions of GHC since we don't have to call GHC twice. Duncan previously claimed that the performance hit from calling GHC a second time should not be large, but actually there is a substantial performance hit when module graphs are large, as GHC recomputes the module graph on every computation (one of the reasons why Shake is so much faster.)

**Comment by dcoutts** [comment]
Sigh. Ideally we should link by just calling GHC to link the .o files etc, and not have it look at .hs and .hi files. Removing the link target seems an ok workaround for now.
