### ISSUE TITLE
Can't install ansi-wl-pprint on Windows

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3307]
```
$ ../dist/build/cabal/cabal install ansi-wl-pprint
Resolving dependencies...
Notice: installing into a sandbox located at
C:\cabal\ansi-wl-pprint\.cabal-sandbox
Configuring ansi-terminal-0.6.2.3...
Building ansi-terminal-0.6.2.3...
Installed ansi-terminal-0.6.2.3
Configuring ansi-wl-pprint-0.6.7.3...
Failed to install ansi-wl-pprint-0.6.7.3
Build log ( C:\cabal\ansi-wl-pprint\.cabal-sandbox\logs\ansi-wl-pprint-0.6.7.3.log ):
Configuring ansi-wl-pprint-0.6.7.3...
cabal.exe: The following package dependencies were requested
--dependency='ansi-terminal=.fake.ansi-terminal-0.6.2.3'
however the given installed package instance does not exist.
cabal: Leaving directory 'C:\Users\kristen\AppData\Local\Temp\cabal-tmp-119476\ansi-wl-pprint-0.6.7.3'
cabal.exe: Error: some packages failed to install:
ansi-wl-pprint-0.6.7.3 failed during the configure step. The exception was:
ExitFailure 1
```
I also reproduced it on Appveyor: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.116#L11443

I ran `git bisect`, and the first failing commit was 137075dcfc76a9b4bab7c0cf44d30c55b636df2f.

**Comment by ezyang** [comment]
This should have been fixed in https://github.com/haskell/cabal/commit/09528c2d075c236947830abb3d0b19582ba2922f Do you have a later failing commit?

In any case, shouldn't be a Windows only problem; I also saw this issue on Linux too.

**Comment by ezyang** [comment]
(@grayjay Would you like me to bisect? I definitely agree it's related to code I wrote.)

**Comment by grayjay** [comment]
@ezyang I must have been on an old commit, because I can't reproduce it on master now.  Thanks!

**Comment by ezyang** [comment]
Great, thanks. Sorry about the broken commit in history.
