### ISSUE TITLE
[nix-local-build] Edit to Cabal file does not cause new inplace package dependency to be built, resulting in "Encountered missing dependencies"

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3324]
Steps to reproduce:

1. Create two packages p-0.1 and q-0.1, with modules P and Q, and Q importing P. Do NOT put p in the build-depends of q.
2. Create a cabal.project with `packages: p q`
3. `cabal new-build q`, observe that the build fails
4. Edit `q` so that it now build depends on `p`
5. `cabal new-build q`

Expected result: Build succeeds

Actual result:

```
[ezyang@hs01 tmp-depchange]$ cabal new-build q -v
In order, the following will be built:
q-0.1.0.0 (lib:q) (files changed)
creating /home/hs01/ezyang/tmp-depchange/dist-newstyle/build
creating /home/hs01/ezyang/tmp-depchange/dist-newstyle/tmp
creating /home/hs01/ezyang/tmp-depchange/dist-newstyle/build/q-0.1.0.0
creating /home/hs01/ezyang/tmp-depchange/dist-newstyle/build/q-0.1.0.0/cache
./q.cabal has been changed. Re-configuring with most recently used options. If
this fails, please run configure manually.
Configuring q-0.1.0.0...
cabal: Encountered missing dependencies:
p -any
```

CC @dcoutts

**Comment by ezyang** [comment]
I bet this has the same root cause as #3323. In fact, I bet we're failing to track a solver dependency on the local inplace Cabal files!

**Comment by dcoutts** [comment]
Was fixed a while ago.
