### ISSUE TITLE
Cabal 1.24 breaks ghcjs

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3330]
There's currently a serious bug in Cabal/cabal-install 1.24 which makes it unusable with `ghcjs`, specifically `/usr/bin/strip` seems to be applied to .js files, which fails terribly...

@luite told me yesterday:

```
hvr> luite: did you take care of that Cabal 1.24 <-> ghcjs bug?
luite> hvr: not yet, i have a patch now that works here, but unfortunately i missed the rc3
```

So I'm creating this issue mostly so this issue is not forgotten, and possibly makes it into 8.0 final's Cabal (tbh, I don't know if the mentioned patch touches `Cabal` or only `cabal-install`)

/cc @23Skidoo

**Comment by ezyang** [comment]
So this is something like, when using GHCJS, `stripExes` and `stripLibs` should always be false?

**Comment by 23Skidoo** [comment]
@luite, can we take a look at the patch?

Also, it would be nice if we had a Travis configuration for testing with GHCJS set up.

**Comment by 23Skidoo** [comment]
@luite 

This is basically the last bug blocking the 1.24 release. If I won't hear from you for the next few days, I'll postpone this until 1.24.0.1.
