### ISSUE TITLE
`new-build` must not pass component-goals to `Setup.hs build` for Cabal 1.16 and older

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3335]
This shows up for packages with custom `Setup.hs` files when trying to build with GHC 7.6, e.g. seen when trying to  `cabal new-build` `lens`

@dcoutts suggests we may want to rethink whether to require `Cabal >= 1.18` when using `new-build` for custom `Setup.hs`

/cc @dcoutts

**Comment by dcoutts** [comment]
With the older Cabal lib versions, `setup build lib:blah` syntax is not supported. So we can only build all the default components. We'll have to adjust for that. But yes, may also want to try having it pick a later Cabal lib by default. In this example we could have the solver pick a later version and it'd work.

**Comment by hvr** [comment]
as a workaround, I tried now:

```bash
cd /tmp/
cabal get lens-4.13.2.1
cd lens-4.13.2.1/
PATH=/opt/ghc/7.6.3/bin:$PATH cabal-1.24 new-build --constraint 'Cabal >= 1.18'
```

which worked, but at the end I got some warnings (which *seem* harmless):

```
[81 of 81] Compiling System.Exit.Lens ( src/System/Exit/Lens.hs, /tmp/lens-4.13.2.1/dist-newstyle/build/lens-4.13.2.1/build/System/Exit/Lens.o )
In-place registering lens-4.13.2.1...
Warning: Could not list sources of the package 'lens'.
Warning: Exception was: user error (The package 'lens' requires Cabal library
version >=1.18.0 && >=1.8 but no suitable version is installed.)
Creating package registration file:
/tmp/lens-4.13.2.1/dist-newstyle/tmp/package-registration-1255179497524872353
```
