### ISSUE TITLE
cabal install assumes Custom packages will be installed with configured IPID, not true for old Cabal

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#3345]
With 1223a39, this is how far installing yi gets:

```
$ cabal -j4 install yi yi-fuzzy-open
...
Installed dynamic-state-0.2.2.0
Configuring executable-path-0.0.3...
Building executable-path-0.0.3...
Configuring ghc-paths-0.1.0.9...
Installed blaze-builder-0.4.0.1
Configuring oo-prototypes-0.1.0.0...
Installed executable-path-0.0.3
Building oo-prototypes-0.1.0.0...
Configuring io-storage-0.3...
Installed oo-prototypes-0.1.0.0
Building io-storage-0.3...
Configuring parallel-3.2.1.0...
Installed io-storage-0.3
Building ghc-paths-0.1.0.9...
Configuring parsec-3.1.9...
Installed charsetdetect-ae-1.1.0.1
Building parallel-3.2.1.0...
Configuring pointedlist-0.6.1...
Installed ghc-paths-0.1.0.9
InstallPlan: internal error: configured package depends on a non-library
package
```

**Comment by ezyang** [comment]
Hmm, does this occur on master?

**Comment by tuncer** [comment]
Yes, 1223a39 is master on github.

**Comment by tuncer** [comment]
The only non-default setting I have in ~/.cabal/config is `split-objs: True`.

**Comment by tuncer** [comment]
I haven't bisected when this started to happen, but I've been using cabal from master all the time.

**Comment by tuncer** [comment]
The previous cabal executable was built on April 4th.

**Comment by 23Skidoo** [comment]
@tuncer Does this happen with 1.24? My guess is that this is related to internal libraries.

**Comment by ezyang** [comment]
Well, I've seen this error before but it was in the case of `new-build` and fixed by https://github.com/haskell/cabal/commit/61fb6fadbefa2bd341fa8165bf77dea56624ff39 I feel that the install logic in this case should be correct. In any case I'll try to repro.

**Comment by ezyang** [comment]
OK, repro'd.

**Comment by ezyang** [comment]
OK, I've diagnosed the problem: `ghc-paths` is a Custom script built against an old version of Cabal. Consequently, we don't actually pass `--ipid` when configuring, and then the resulting IPID of the package is not what we expect. We can fix this by adopting some code from `new-build`. I have a small working test case too.

**Comment by ezyang** [comment]
PR'd.

**Comment by tuncer** [comment]
Thanks, @ezyang, #3356 fixed it for me.
