### ISSUE TITLE
[nix-local-build] Should print out reason why rerun occurs at default verbosity

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3352]
When I invoke `ghc --make` with default settings, it tells me (one) reason why any given file is recompiled. This is pretty nice to know, and is very useful for debugging when things are recompiling when they shouldn't be.

I think new-build should act similarly. At the very least, for every message we give (e.g. "Resolving dependencies...") we should say WHY we are rebuilding, and not just a vague reason like "project settings changed) but a specific file. For example, it would have made me notice #3351 much earlier.

**Comment by dcoutts** [comment]
Yeah, so long as it's not too intrusive. And we do have most of the info available.

**Comment by ezyang** [comment]
Issue subsumed by PR #3785.
