### ISSUE TITLE
Drop root-cmd support

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3353]
Current recommended Cabal usage is users should ~never install into the global package database. It's just not done. So can we drop `--root-cmd` support?

If people do think `root-cmd` is really useful, we'll have to plumb out nix-local-build's registration logic (which involves overwriting the IPID in some cases) so that when we reexecute ourselves that logic is picked up as well.

**Comment by erikd** [comment]
My only concern is that when building Linux distribution packages (eg Debian, Fedora etc) of Haskell libraries, the distro packaging too chains may use `cabal` as part of their tooling. Is suspect @nomeata knows if this will be an issue.

**Comment by ezyang** [comment]
Glancing at the packaging for GLUT in Debian, Fedora and Arch Linux, none of these use `root-cmd`.

**Comment by 23Skidoo** [comment]
Fine with me. In fact, why did we need `--root-cmd` instead of just asking the user to run `sudo cabal`?

**Comment by nomeata** [comment]
Hi,

Debian packaging never uses `cabal`, only the Setup.hs that comes with `Cabal`.

Am 17. April 2016 05:30:47 MESZ, schrieb Erik de Castro Lopo <notifications@github.com>:

**Comment by hvr** [comment]
Just for reference, 3bde7b3df9ae570cb828bcb42450f5047066de3d implemented `--root-cmd` in order to address #195

**Comment by 23Skidoo** [comment]
@hvr
Thanks, makes sense. Then I guess we should remove `--global` as well while we're at it.
