### ISSUE TITLE
Unvendoring of 'tar' breaks unpacking

### ISSUE THREAD

**Issue by davean** [haskell/cabal#3390]
[Commit 0db3b21](https://github.com/haskell/cabal/commit/0db3b216ce04634b14506e387f2504af8db76e05) introduces a dependancy on a tarbomb check that can't handle many hackage packages.

For example:
```
$ cabal get binary-0.6.4.0
Downloading binary-0.6.4.0...
Unpacking to binary-0.6.4.0/
File in tar archive is not in the expected directory "binary-0.6.4.0"
```

The old code handled POSIX.1-2001/pax tarballs specificly, of which there are many on hackage. The code in the tar package does not understand the pax records, and errors on them thinkng they're "normal files" in the wrong location.

These packages did install properly in the last cabal-install version.

**Comment by 23Skidoo** [comment]
@dcoutts, can you please look into this?

**Comment by 23Skidoo** [comment]
Same issue on the `tar` bug tracker: https://github.com/haskell/tar/issues/1.

**Comment by dcoutts** [comment]
Ok.

**Comment by dcoutts** [comment]
@23Skidoo @hvr @davean please try with the new release 0.5.0.3 and if it's ok then lets just tweak the cabal-install constraints (no need to re-release).

**Comment by dcoutts** [comment]
Note that haskell/tar#1 is a different issue really. That's about wholesale support for PAX, this issue was just about ignoring PAX headers for the purposes of the tarbomb check. This check had been added to the tar code in cabal-install but never ported over to the main tar package.

**Comment by 23Skidoo** [comment]
Confirmed that tar-0.5.0.3 fixes the issue. Updated the version bound in the repo and on Hackage.
