### ISSUE TITLE
Add support for `--hadock-options` to `cabal upload --doc`

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3414]
The `cabal upload --doc` feature implemented by @bennofs  is super useful. However, currently I can't seem to be able to pass `--haddock-options` to tweak the generated documentation (e.g. to set `--use-unicode` or `--hyperlinked-source`).

So right now I have to fallback to `cabal haddock --for-hackage` + uploading the generated doc-tarball. However, if `cabal upload` supported the `--haddock-options` flag it'd be more convenient.

/cc @thoughtpolice

**Comment by 23Skidoo** [comment]
Using `--for-hackage` is probably the best way to do it because it lets you specify options to the `cabal haddock` command itself (which may do some further preprocessing).
