### ISSUE TITLE
Cabal upload should have a --candidate flag.

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#3418]
As is, I think there's no way to upload a candidate directly with cabal?

This means people need to figure out the curl commands or the like to do it themselves, or to do it via the web.

e.g. https://github.com/haskell/hackage-server/issues/175

**Comment by phadej** [comment]
I remember a discussion to even make `upload` to upload a candidate by default. Cannot find it though. cc @hvr

**Comment by hvr** [comment]
Definitely +1 for uploading a candidate by default. I'm not sure where the discussion was either


@gbaz  fwiw, I currently use `hackage-cli push-candidate <srctarball>` (see https://github.com/hvr/hackage-cli)

**Comment by 23Skidoo** [comment]
IIRC there was a ticket about folding all/most of `hackage-cli`'s functionality into `cabal-install`.

**Comment by 23Skidoo** [comment]
See #3419.
