### ISSUE TITLE
HTTP transports should uniformly follow redirects / not follow redirects

### ISSUE THREAD

**Issue by bennofs** [haskell/cabal#3426]
Currently, when you use `--http-transport=curl` cabal won't follow redirects in responses, while it will with `--http-transport=plain-http`. See https://github.com/haskell/cabal/pull/3419#issuecomment-219005008. 

This should be uniformly handled by all transport. I have not investigated how the wget and the powershell transports handle this yet.

**Comment by hvr** [comment]
Slightly related, the timeout/retry behaviour varies as well: #3386

**Comment by bennofs** [comment]
Ok, it looks like at least the wget transport currently does follow redirects.

**Comment by 23Skidoo** [comment]
+1 on following redirects in all cases. Looks like it can be fixed [by simply invoking `curl` with `-L`](https://curl.haxx.se/docs/faq.html#How_do_I_tell_curl_to_follow_HTT).

**Comment by bennofs** [comment]
Only the curl transport needs to be changed, WebClient does follow redirects by default according to https://msdn.microsoft.com/de-de/library/system.net.webclient%28v=vs.110%29.aspx#Anchor_6 (AllowAutoRedirect is set to true).
