### ISSUE TITLE
Please test bootstrap.sh (in travis)

### ISSUE THREAD

**Issue by zeha** [haskell/cabal#3427]
Given the recent issue #3389, I'd suggest testing bootstrap.sh regularly (before making releases), possible as part of the existing Travis test runs.

Please consider this suggestion.

**Comment by bennofs** [comment]
#3349 looks related

**Comment by 23Skidoo** [comment]
Yes, this is being worked on.

**Comment by 23Skidoo** [comment]
Fixed by 2645970ae942f13a942b369ad938db20ff641f75.
