### ISSUE TITLE
Missing CHANGELOG entries in cabal-install 1.24.0.0

### ISSUE THREAD

**Issue by asr** [haskell/cabal#3435]
The [changelog](http://hackage.haskell.org/package/cabal-install-1.22.9.0/changelog) for cabal-install 1.22.9.0 includes entries for 1.22.2.0, 1.22.3.0, 1.22.4.0, 1.22.5.0, 1.22.6.0, 1.22.7.0, 1.22.8.0 and 1.22.9.0 which are missing in the [changelog](http://hackage.haskell.org/package/cabal-install-1.24.0.0/changelog) for cabal-install 1.24.0.0.

**Comment by 23Skidoo** [comment]
Those are entries for bugfixes backported to 1.22 from `master`. IMO it's better not to clutter the changelog with them.

**Comment by asr** [comment]
There are other entries for bugfixes in the CHANGELOG of 1.24.0.0, so doesn't include entries for bugfixes doesn't seem a valid reason. IMO the CHANGELOG should be as complete as possible.

**Comment by 23Skidoo** [comment]
I may be open to updating the section for 1.24.0.0, just don't want the 1.24 changelog to have separate sections on 1.22 point releases.

**Comment by 23Skidoo** [comment]
I changed my mind :-)
1d3814ab854989c9db8c0de7aa577c14ea49357d
