### ISSUE TITLE
--enable-profiling not recognized by new-build?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3442]
How do I make new-build build a profiling-enabled version of my executable? Can it be done?

/cc @dcoutts

**Comment by hvr** [comment]
`cabal new-configure --enable-executable-profiling` results in `cabal.project.local` containing

    executable-profiling: True

...doesn't that work?

**Comment by edsko** [comment]
Doesn't appear to, no.

**Comment by ezyang** [comment]
It's possible you're seeing some more subtle bug, e.g. #3485. Hard to say without a reproducing case, but maybe wait till we fix that one and see if that fixes your case.

**Comment by ezyang** [comment]
Please add `constraints: Cabal >= 1.24` and tell us if you still see this problem.

**Comment by edsko** [comment]
With `cabal-install-head` from @hvr (1.25+git20160918.1.c9e046e~xenial), this config works:

```
packages: ingest.cabal

profiling: True
executable-profiling: True
constraints: Cabal >= 1.24

program-options
  ghc-options: -fprof-auto 
```

**Comment by hvr** [comment]
@edsko minor nitpick: `ghc-prof-options` should be used to override the default prof detail level, and even better yet, there's

 - `profiling-detail: all-functions` and
 - `library-profiling-detail: all-functions`

which are supposed to work in cabal.project files (in pkg.cabal files we can only use `ghc-prof-options`), where the levels: default, none, exported-functions, toplevel-functions, all-functions map to the corresponding `-fprof-auto*` flags...

**Comment by ezyang** [comment]
OK @edsko, I think that confirms that this is a dupe of #3485.

@hvr, this clearly seems like a documentation failing. `ghc-prof-options` is not documented. Can we fix the docs.

**Comment by 23Skidoo** [comment]
Closing in favour of #3790, which has now been fixed. Please reopen if disagree.

**Comment by ezyang** [comment]
Also note that `executable-profiling: True` is unnecessary; `profiling` will automatically enable it.

**Comment by ezyang** [comment]
Also, to be clear, `ghc-prof-options` is NOT supported in `cabal.project` format. So you can only put the flags in `ghc-options` or use Cabal's built-ins.
