### ISSUE TITLE
travis-script.sh bash dependency

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#3450]
It would be great to eventually remove the bash dependency in `travis-script.sh`.

**Comment by 23Skidoo** [comment]
Do you want to remove it In favour of Haskell or in favour of `sh`?

**Comment by tuncer** [comment]
`sh` would be the logical choice, unless somebody wants to rewrite it in Haskell and avoid the fragility of shell scripting.

**Comment by 23Skidoo** [comment]
IMO rewriting it in Haskell makes more sense, but patches for improving compatibility with `sh` would likely also be accepted.

**Comment by hvr** [comment]
Rewriting in Haskell poses its own challange, as you'd have to write code that works across multiple GHC versions without access to any `MIN_VERSION_...` macros (those are only available starting with GHC 8.0)

**Comment by tuncer** [comment]
Sorry, I meant `travis-script.sh`, not `bootstrap.sh`.

**Comment by 23Skidoo** [comment]
Fixed by #3454.
