### ISSUE TITLE
cabal does not automatically reconfigure when the state of dependencies changed

### ISSUE THREAD

**Issue by Peaker** [haskell/cabal#3458]
If you re-install dependencies of a configured cabal package, trying to `cabal build` may fail until you manually `cabal configure`. However, `cabal configure` requires manually re-specifying all the flags.

Either a `cabal reconfigure` command should be provided, or cabal should automatically reconfigure when the state of dependencies changed.

**Comment by 23Skidoo** [comment]
As a workaround, you can do `touch foo.cabal && cabal build`.

**Comment by 23Skidoo** [comment]
> If you re-install dependencies of a configured cabal package, trying to `cabal build` may fail until you manually `cabal configure`.

Isn't this fixed by `new-build`, by the way?

**Comment by gbaz** [comment]
closing as obsolete
