### ISSUE TITLE
bootstrap: TMPDIR redefinition

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#3464]
When creating https://github.com/haskell/cabal/commit/ce58148ff6849c5adb56bcf5cfcb92c2263e3092, I was surprised to see that `TMPDIR` is reused for something else than the convention of pointing to a custom `/tmp`.
1. Where is the re-exported `TMPDIR` used? Maybe by cabal-install?
2. It goes against convention to name it TMPDIR because you set TMPDIR to deviate from /tmp, so referencing a directory inside /tmp by the name `$TMPDIR` isn't right.

/cc @23Skidoo.

**Comment by ezyang** [comment]
Hi @tuncer.

This is a textbook case of (1) someone before you not documenting something tricky they did, and (2) if you see something tricky, you better investigate.

I blame'd the Git code, and this line was introduced in #1710 to fix some sort of awful problem on Mavericks. But the fix here wasn't complete and so @23Skidoo wrote another patch to solve @creswick's report at #2542.

As the grep now doesn't pick up ld's, it is possible the patch from #1710 can be deleted. But I would not feel confident about it without checking to see if #2542 is still fixed.

**Comment by tuncer** [comment]
@ezyang, the referenced tickets seem resolved. Does that mean the OS X issues are fixed and, if so, can we get rid of this now? One side effect is that this seems to produce a leftover cabal-XXXXXXX in /tmp.

**Comment by ezyang** [comment]
Erm, do you mean, get rid of the `TMPDIR` setting? I think it's possible but I certainly want to test. Maybe here is a reasonable workplan:

1. Adjust the Mac OS X bootstrap script to take place in a folder named `arnold` (or anything with `ld`) so we keep testing #2542
2. The existing bootstrap script should test #1710. So now just drop the TMPDIR setting and make sure Travis is green, then push.

Does that sound good?

**Comment by tuncer** [comment]
> Erm, do you mean, get rid of the TMPDIR setting? 

Yes, overriding TMPDIR is one thing, but what's going on here is confusing.

> Does that sound good?

Sounds like a workable plan.

**Comment by tuncer** [comment]
@ezyang, should we close this?

**Comment by ezyang** [comment]
Sure.
