### ISSUE TITLE
Improve CI times

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#3465]
Travis-CI takes quite some time (20 to 30 minutes per GHC version) right now. As a remedy it's worthwhile to investigate CircleCI or haskell.org's Harbormaster.

/cc @23Skidoo, @gbaz

**Comment by hvr** [comment]
What `-j` level do we use? iirc there was some issue that too high `-j` values caused slowdowns on Travis (and `-j` w/o a number may over-estimate the amount of available parallelism on Travis VMs)

Is there something we can reasonably cache from previous buildjobs w/o sacrificing the intent of the buildjob?

**Comment by tuncer** [comment]
@23Skidoo had suggested to use arg-less `-j` in order to automatically pick up resources if travis upgrades the host. With the current limits, it might be wise to limit it to `-j2`. It's enough to change the line in `.travis.yml`.

In 7872bcc2cfd35d01f70a569f2029eb562dce1ed2 I tried reusing ~/.ghc and ~/.cabal as left by bootstrap.sh, but that would require more changes, so it's postponed for now. Here's the error:

```
In order, the following would be installed:
Cabal-1.25.0.0 (reinstall)
cabal: The following packages are likely to be broken by the reinstalls:
hackage-security-0.5.1.0
Use --force-reinstalls if you want to install anyway.
```

**Comment by tuncer** [comment]
Is it possible to make use of Harbormaster for this?

**Comment by phadej** [comment]
from the references PR on GHC-7.8:
```
bootstrap.sh script took 415 seconds.
Installing parsec took 85 seconds.
Generated files check took 0 seconds.
Cabal took 474 seconds.
cabal-install took 537 seconds.
```

As I expected, there is three not-independent-enough subparts in the job, which all just take long.

**Comment by phadej** [comment]
One quick suggestion: we could separate testing `bootstrap.sh` into separate matrix items, and build `Cabal` + `cabal-install` with `cabal` from apt repository. It will parallelise the whole build a bit more, though won't reduce total wall clock time

**Comment by 23Skidoo** [comment]
> One quick suggestion: we could separate testing `bootstrap.sh` into separate matrix items, and build `Cabal` + `cabal-install` with `cabal` from apt repository.

If there's a restriction on how many matrix items can be started simultaneously, this can actually be slower.

**Comment by phadej** [comment]
@23Skidoo there is, I guess it's five jobs

**Comment by phadej** [comment]
And with amended timings:
```
bootstrap.sh script took 420 seconds.
Installing parsec took 85 seconds.
Generated files check took 0 seconds.
Cabal dependencies took 173 seconds.
Cabal build took 298 seconds.
cabal-install dependencies took 101 seconds.
cabal-install build took 433 seconds.
```

Looks like that even building dependencies takes some time, it's not the major part :(

**Comment by 23Skidoo** [comment]
@ezyang did a lot of work in this area recently (thanks!), so I guess we can consider this fixed.
