### ISSUE TITLE
Unrecognized stanza

### ISSUE THREAD

**Issue by tsoernes** [haskell/cabal#3467]
Hi,

I installed the full platform package with GHC 7.10.3. When i run cabal update this happens:
```
Warning: C:\Users\x\AppData\Roaming\cabal\config: Unrecognized stanza
on line 14
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
```
The cabal config on line 14 and onwards reads:
```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: False
  -- root-keys:
  -- key-threshold:
```

**Comment by 23Skidoo** [comment]
Looks like you have a new style config from a previous installation left over which you're trying to use with an old version of `cabal-install`. Simply delete the config file and run `cabal update`.

**Comment by tsoernes** [comment]
Thank you that solves the problem.

**Comment by b-mehta** [comment]
Hi, I'm having this exact issue, but deleting the config file and running `cabal update` doesn't fix it for me.
