### ISSUE TITLE
Cabal CLI support for building Setup.hs?

### ISSUE THREAD

**Issue by mgsloan** [haskell/cabal#3471]
With the advent of explicit-setup-deps, it would be convenient for `stack` if the default `Setup.hs` provided a way to compile a custom `Setup.hs`.

Not sure what this would look like, perhaps `runhaskell TheDefaultSetup.hs build-setup-hs`

Otherwise, we're going to need to do our own implementation of invoking `ghc` with the explicit setup deps. See https://github.com/commercialhaskell/stack/issues/2094#issuecomment-222125146

**Comment by hvr** [comment]
fwiw, afaik `setup-depends` has been designed (@dcoutts knows better though) to be so limited in its expressiveness as to make it trivial to implement for distro  packagers (like e.g. afaik no cabal conditionals are supported or other features not suitable for an external bootstrap-phase of Setup.hs)

**Comment by mgsloan** [comment]
Cool!  Perhaps it's unneeded then, thanks!
