### ISSUE TITLE
broken markup in users guide documentation

### ISSUE THREAD

**Issue by mauke** [haskell/cabal#3481]
https://www.haskell.org/cabal/users-guide/developing-packages.html#configuration-flags

> Note that this value may be \[overridden in several ways\](installing-packages.html#controlling-flag-assignments“).

https://www.haskell.org/cabal/users-guide/developing-packages.html#conditional-blocks

>     `if `_condition_
>          _property-descriptions-or-conditionals*_

> or

>     `if `_condition_
>          _property-descriptions-or-conditionals*_
>     `else`
>          _property-descriptions-or-conditionals*_

**Comment by ezyang** [comment]
Thanks for the report.

**Comment by mauke** [comment]
Are you sure `installing-packages.html#controlling-flag-assignments"` (including the trailing `"`) is the right link?

**Comment by ezyang** [comment]
Oh! I misunderstood the report; I thought it was a rendering problem.

**Comment by mauke** [comment]
It's both. :-)
