### ISSUE TITLE
cabal init picks up source files without adding directories to hs-source-dirs

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3484]
Steps to reproduce:

1. Create a subfolder `foo` and put `A.hs` in it
2. Run `cabal init` (in the parent folder)

Expected behavior:

EITHER:
1. No modules are added to `exposed-modules` and `hs-source-dirs` is commented out
2. `A` is added to `exposed-modules` and `hs-source-dirs` contains `foo`

Actual behavior: `A` is added to `exposed-modules` but `hs-source-dirs` is not updated.

A fairly minor bug but a bug nonetheless.

**Comment by byorgey** [comment]
@ezyang which behavior do you think makes more sense?  I am personally leaning towards (1).

**Comment by ezyang** [comment]
I think (1) is fine, doesn't require any fancy footwork.

**Comment by byorgey** [comment]
Actually on reflection this is trickier than I thought --- the only way to know that `Foo/A.hs` should not be added to `exposed-modules` is to look at the module name defined in `A.hs` to see whether it is `A` or `Foo.A`.  I suppose a simple hack would be to just ignore directories whose names start with anything other than a capital letter.

**Comment by byorgey** [comment]
Oh hey, what do you know, the existing code already figures out the module name for each source file it finds. =)

**Comment by byorgey** [comment]
@ezyang Check out the above pull request and see if it looks sensible to you.  I will be travelling for the next week and a half with limited internet access but should be able to respond to any concerns after that.
