### ISSUE TITLE
cannot `delete-source` (re)moved directory by absolute path

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#3486]
When using `cabal sandbox delete-source`, the user is advised to specify the full, absolute path in case that the destination does no longer exist. Doing so does not work any better, i.e. it does not.

Reproducable with default-initialized setup, after deleting the destination (folder) of an add-source dependency.

cabal-install 1.24.0.0

**Comment by phadej** [comment]
sandbox functionality is removed.
