### ISSUE TITLE
Add a goal order parameter to the dependency solver

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3489]
This parameter would allow unit tests to specify the exact order of goals in the solver's tree.  Without it, changes in goal order heuristics could break the backjumping tests that rely on a specific order.  It would also allow us to simplify those tests by specifying the goal order more directly.  This issue came up in https://github.com/haskell/cabal/pull/3422#issuecomment-219205230.

**Comment by kosmikus** [comment]
Yes, I very much support this.

**Comment by grayjay** [comment]
Implemented in #3510.
