### ISSUE TITLE
new-repl with other ghci

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3497]
I'd like to use `cabal new-repl --with-ghc=intero`, this used to work with `cabal repl`. But now I get the following error:

```
jacco@xw4600:~/projects/leksah/leksah$ cabal new-repl --with-ghc intero
cabal: '/home/jacco/.local/bin/intero' exited with an error:
intero: UnhelpfulSpan "on the commandline": cannot use `--interactive' with
`--supported-languages'
Usage: For basic information, try the `--help' option.
```

This also happens with any other ghci (e.g. `cabal new-repl --with-ghc=ghci`)

**Comment by dcoutts** [comment]
Hmm. The thing is you're specifying a ghc program, and so cabal expects it to behave like ghc. In particular it has to be able to configure it, so it needs to know the `--info` output, and what languages it supports etc etc. There isn't a separate ghci vs ghc program as far as cabal is concerned.

This problem must also happen with the normal repl right?

What are you really trying to do here?

**Comment by jaccokrijnen** [comment]
I'd like to use [intero](https://github.com/commercialhaskell/intero) (a ghci fork) with my cabal project. It actually does work with normal `cabal-repl`, but not with `new-repl`. But what you say makes sense, it's `with-ghc` not `with-ghci`. Is there another way how I can achieve using it in stead of the usual ghci?

**Comment by dcoutts** [comment]
You could patch intero I guess. Even if we add a --with-ghci style thing we'd still need to be able to configure it, which would also mean calling things like --supported-languages. The fact that it works with the classic repl is a bit of a fluke, it's relying on intero being exactly the same version as your configured ghc, which is not being checked. It's a fairly unsafe thing for us to encourage. So I'd look to see if you can get intero to behave in such a way that it'd be possible to auto-discover info about it, like making --spported-languages work.

**Comment by ezyang** [comment]
For GHC 8.0 and beyond, consider having intero as a frontend plugin: https://downloads.haskell.org/~ghc/master/users-guide/extending_ghc.html#frontend-plugins

It will handle GHC-compatible command line parsing for you.

**Comment by ezyang** [comment]
Closing as WONTFIX.
