### ISSUE TITLE
nix-style - incomplete instructions - editing .package file does not show effect

### ISSUE THREAD

**Issue by andrewufrank** [haskell/cabal#3498]
nix-style build  is a great idea and I hope it works. 
at the moment i am not clear where the .project files belong. the blog entry says “root” and probably you mean somewhere on the path. could you be more specific?
i tried a project with several packages each in a directory (not in the $PATH)
i tried naively a package file with */*.cabal (per example in the blog) in the directory where the different subdirectories contain the packages (each with its cabal file) and gets a BadLocGlobEmptyMatch error.
changing the project file does not help, because the config file is not updated automatically. deleting the config file in this directory does not help – it is reconstructed every time (and i cannot find where it comes from).
what did i do wrong?
thank you!

**Comment by lspitzner** [comment]
afaik "root" refers to "project root", something like

~~~~
root (e.g. /home/user/haskell/project14)
- package1
  - package1.cabal
  [..]
- package2
  - package2.cabal
  [..]
- cabal.project
~~~~

i don't think `$PATH` is relevant at all in this respect.

perhaps you misnamed the `cabal.project` file? what are the exact contents of the directory you run `cabal new-build` in? what is the exact error message you get? what is this "config file" you mention?

**Comment by andrewufrank** [comment]
thank you for the help. there were several misunderstandings on my part. i have a directory setup with one level more, i.e. the root, folders with multiple packages, folders with one package. 
my cabal 
my `cabal.projec`t file (with exactly this name in the "root" of this tree) looks like this now (i put it here as an example - perhaps you can indicate how it could be improved)

```
packages:
    basic/stringConversion/stringConversion.cabal
    basic/basics/basics.cabal 
    basic/fileio/fileio.cabal
    basic/bindingGeneralized/bindingGeneralized.cabal

    gui/appCode/appCode.cabal
    gui/appFoundation/appFoundation.cabal
    gui/eule/eule.cabal
    gui/genkeyval/genkeyval.cabal
    gui/geometry/geometry.cabal
    gui/guibind/guibind.cabal
    gui/guimodules/guimodules.cabal
    gui/guimodulesStorage/guimodulesStorage.cabal
    gui/layout/layout.cabal 
```
how would i cabal install this project when not in this directory? 
thank you for a tool which seems VERY helpful and simple to use (once overcome the first hurdle)

**Comment by lspitzner** [comment]
ah, i see, one more level. have you tried the wildcard `*/*/*.cabal`?

> how would i cabal install this project when not in this directory?

i think `new-build` always only looks in the current directory.

(support for the equivalent of `cabal install --bindir=..` (i.e. locally "deploying" an executable) is probably coming in the future; i am not sure if there are any plans to support referencing one (local) `cabal.project` from another `cabal.project`.)

**Comment by andrewufrank** [comment]
i did a new-build and then go to another package which uses one of the packages listed above (e.g. basics) and i have a cabal.project with wildcard */*.cabal. the error is then
```
cabal: Could not resolve dependencies:
trying: installDeb-0.0.1 (user goal)
next goal: basics (dependency of installDeb-0.0.1)
Dependency tree exhaustively searched.
```
the package basics is listed with ghc-pkg list and a regular `cabal install`(in the subdirectory) does work. how do i refer to other packages in the nix-style build?

**Comment by lspitzner** [comment]
unlike (non-sandboxed) `cabal install`, `new-build` does not install packages anywhere such that they can later be accessed from other directories. i assume that is what your non-understanding boils down to (?)

instead of going to the other package, you can `cabal new-build path/to/package.cabal` from the top-level (i.e. where a central `cabal.project` is located). alternatively create a `cabal.project` for each package and add all local dependencies as appropriate to each one.

**Comment by dcoutts** [comment]
@andrewufrank so your `cabal.project` file is ok, or as @lspitzner said you could use wildcards like `*/*/*.cabal`. If you have other dependencies for your project that are not on hackage then you need to list them in your `cabal.project` file, i.e. give the directory to the source dir for those packages. In future you'll also be able to list local (or remote) tarballs (or git/darcs/etc repos), but for now it's just directories.

**Comment by andrewufrank** [comment]
thank you - this was helpful and i will try it out. it appears very flexible and i look forward to some concise documentation/instructions!
