### ISSUE TITLE
Switchting ghc version does not rerun pre-processors

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3499]
When switching from ghc-8.0.1 to ghc-7.10.3, I tried rebuilding a package with `new-build`. But when cabal was building a local dependency it gave me this

```
src/Data/GI/Base/Signals.hsc:42:8:
    Could not find module ‘GHC.OverloadedLabels’
    Use -v to see a list of the files searched for.
```
Which is only [imported with base >= 4.9](https://github.com/haskell-gi/haskell-gi-base/blob/master/src/Data/GI/Base/Signals.hsc#L41).

(complete log: https://gist.github.com/jaccokrijnen/9230612b6730e42592a11e5eab00c7ca)

I think cabal has configured the local dependency with my ghc 8 and its dependencies but does not configure it now. Or perhaps this has to do something with caching? Only solution I could find was to complete delete dist-newstyle/

**Comment by hvr** [comment]
@jaccokrijnen it probably isn't important, but which method did you use to switch between GHC versions? (i.e. changing PATH, use `cabal new-build -w ghc-7.10.3` or `cabal new-configure -w ghc-7.10.3`, or something else?)

**Comment by jaccokrijnen** [comment]
@hvr By changing PATH

**Comment by dcoutts** [comment]
Ah, I'll bet that it's due to it being a `.hsc` file and not re-pre-processing the .hsc file when the ghc version changed. Currently we don't bother blowing away the .hi files etc because `ghc --make` is smart enough to do that for us, but with pre-processing we may need to do that ourselves.

@jaccokrijnen can you point us to the .hsc file in question? I'll bet it uses cpp to do ghc/base-version specific includes.

**Comment by jaccokrijnen** [comment]
It's this file, indeed a `.hsc` file that uses cpp for versions: https://github.com/haskell-gi/haskell-gi-base/blob/master/src/Data/GI/Base/Signals.hsc#L41

**Comment by ezyang** [comment]
In cabal-install HEAD this is no longer a problem because each version of GHC now gets its own build directory. I suppose we could still try to fix this underlying problem in Cabal, but definitely not a priority now.
