### ISSUE TITLE
[Feature Request] Support for VCS as project's build-depends

### ISSUE THREAD

**Issue by winterland1989** [haskell/cabal#3508]
I'm aware of #3226 , actually this issue followed [this discussion](https://www.reddit.com/r/haskell/comments/4pi8ll/chicago_haskell_getting_started_with_ghcjs_dev/d4lyvqa), simply put, i want to be able express my build-depends like this:

```
  build-depends:        base >=4.8 && <4.9
                    ,   git@XXX.git  bc4c354 /subfolder
```

The VCS line format can be `vcs-uri [optional commit-hash] [optional subfolder]`, or anyother things that support these instructions. Is this feature under working now?

**Comment by 23Skidoo** [comment]
Seems to be a duplicate of #2189. I don't think anyone is working on this currently.
