### ISSUE TITLE
adds dynamic haskell libraries to linker search path, making executable start unnecessarily slow

### ISSUE THREAD

**Issue by joeyh** [haskell/cabal#3524]
#Building git-annex with cabal on linux produces an executable that is statically linked to all haskell libs. However, strace shows the linker looking in a bunch of haskell lib directories for the C libs that the binary is dynamically linked against.

open("/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-7.10.3/data-default-class-0.0.1-K91y8NcZUJI9yaBI61rgdD/x86_64/libsqlite3.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-7.10.3/data-default-class-0.0.1-K91y8NcZUJI9yaBI61rgdD/x86_64", 0x7ffd89984970) = -1 ENOENT (No such file or directory)
open("/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-7.10.3/data-default-class-0.0.1-K91y8NcZUJI9yaBI61rgdD/libsqlite3.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-7.10.3/data-default-class-0.0.1-K91y8NcZUJI9yaBI61rgdD", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-7.10.3/data-default-instances-base-0.0.1-Bh5w1rt638k3gekgUnZ9Qe/tls/x86_64/libsqlite3.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

After 900 such unncessary opens and stats, it finally finds it:

open("/usr/lib/x86_64-linux-gnu/libsqlite3.so.0", O_RDONLY|O_CLOEXEC) = 3

When repeated for the 34 C libraries that git-annex is linked against, this adds something like 30 thousand unncessary syscalls to the program startup, which delays it by 0.02 seconds on my laptop. This is not an insignificant delay for a command-line program.

It's caused by the gcc link command being passed optl-Wl,-rpath with the path for each of of the haskell library dependencies, and each of their dependencies. Since those are being statically linked, that's unncessary. I think that this could be fixed by omitting the -lHSfoo when statically linking haskell libs.

(git-repair also has the problem and is a bit more minimal than git-annex. I have not found a more minimal test case yet.)

Workaround: chrpath -d on the binary produced by cabal

cabal 1.22.9.0 using version 1.22.8.0 of the Cabal library
ghc 7.10.3

**Comment by thomie** [comment]
https://ghc.haskell.org/trac/ghc/ticket/11587 is relevant

**Comment by ezyang** [comment]
Yes, it's a duplicate. But it is a major problem and we should fix it!
