### ISSUE TITLE
Proposal: -v3 should not turn up GHC verbosity

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3540]
In general, if I'm debugging a GHC problem, I get Cabal to spit out the command line I need, and then call GHC myself. If I'm debugging a Cabal problem, I don't really care about what GHC is doing except at broad strokes (black box.) So let's stop passing `-v` to GHC when Cabal's verbosity is sufficiently high.

**Comment by 23Skidoo** [comment]
+1 from me. It'll still be possible to enable old behaviour via `--ghc-options=-v`.
