### ISSUE TITLE
Put generated Haddock documentation for HEAD and PRs somewhere

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3543]
Our CI setup builds Haddock documentation as part of the testing process. It would be REALLY great if these could get uploaded somewhere where we can see them. https://twitter.com/ezyang/status/753011340743208960

**Comment by 23Skidoo** [comment]
We can use GitHub Pages and the `cabal-website` repo for this (I'm a bit nervous about allowing Travis to push to the primary repo).

https://developer.github.com/guides/managing-deploy-keys/ 
https://docs.travis-ci.com/user/encrypting-files/

tl;dr: `travis encrypt-file` the deploy key, commit it to the repo, then in the CI script you can decrypt the deploy key and push to the GH pages repo.

**Comment by 23Skidoo** [comment]
I'll try to implement this today, it's not that hard.

**Comment by 23Skidoo** [comment]
@hvr, can I get Admin rights to the haskell/cabal-website repo?

**Comment by gbaz** [comment]
done :-)

**Comment by 23Skidoo** [comment]
@gbaz Thanks!

**Comment by 23Skidoo** [comment]
Lo and behold: http://haskell.github.io/cabal-website/doc/html/Cabal/

**Comment by ezyang** [comment]
This is great! All we need is a link from the README.

I wonder there wouldn't also be a way to collect the docs from PRs; then we could write a little mention bot saying, "You edited these files/functions, please look at the corresponding Haddocks and make sure they rendered correctly." Well, I won't ask for too much :o)

**Comment by 23Skidoo** [comment]
Added a README link.

> I wonder there wouldn't also be a way to collect the docs from PRs;

Yeah, it should be possible to enable this for PRs and branches other than master. See https://github.com/haskell/cabal/blob/master/.travis.yml#L53.

**Comment by phadej** [comment]
> I wonder there wouldn't also be a way to collect the docs from PRs;

it's possible, but PRs are unsafe. Travis secrets aren't even usable from PRs

> Please note that encrypted environment variables are not available for pull requests from forks.

https://docs.travis-ci.com/user/encryption-keys/

**Comment by phadej** [comment]
(btw. where from `$encrypted_edaf6551664d_key` variable comes?)

**Comment by ezyang** [comment]
Yes. You'd probably need a bit more heavyweight mechanism to do PRs. Maybe some other day, when we try to do a doc sprint.

**Comment by 23Skidoo** [comment]
> (btw. where from $encrypted_edaf6551664d_key variable comes?)

Set up automatically by travis encrypt-file.  To change, go to travis-ci.org > haskell/cabal > Settings.
