### ISSUE TITLE
Consider switching the user's guide to GitHub compatible Markdown

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3546]
Right now we use pandoc-flavored Markdown, which means we can't take advantage of GitHub's affordances for handling Markdown documents. For example see https://github.com/haskell/cabal/commit/84b2975c97c6e85e3edf38cda5818d8f41391f21?short_path=591aeff#diff-591aeff2322d42edf0dd28075b83920b where the rich text diff just doesn't really work.

We'll probably need some style guide saying how to make both Pandoc and GitHub compatible Markdown.

**Comment by 23Skidoo** [comment]
Our documentation is now reST.
