### ISSUE TITLE
transformers dependency for Cabal?

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3548]
Does anyone know if it would be OK for us to take a dependency on transformers in Cabal?

**Comment by 23Skidoo** [comment]
Quoting [HACKING.md](https://github.com/haskell/cabal/blob/master/HACKING.md#dependencies-policy):

> The Cabal library must be buildable out-of-the-box, i.e., the dependency versions required by Cabal must have shipped with GHC for at least 3 years. Cabal may use newer libraries if they are available, as long as there is a suitable fallback when only older versions exist.

GHC [ships with `transformers` since version 7.8](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory). Since GHC 7.6.3 was released in April 2013, we are allowed to drop support for it.

**Comment by ezyang** [comment]
I added it to my branch, tried to build GHC with it, regretted it, reverted it. Let's not.

**Comment by phadej** [comment]
- What was the issue with GHC? (so we know we next time want depend on `transformers`)
- What you wanted `transformers` for? (pure curiosity)

**Comment by ezyang** [comment]
GHC's build scripts needed to somehow be adjusted so that Cabal is built against transformers. Maybe it is easy but it does not work out of the box.

I wanted to use `StateT` to implement `mapAccumM` haha.

**Comment by ttuegel** [comment]
Are you sure this isn't worth it? There are *many* places where `StateT` would be an improvement. `Distribution.Simple.Configure.configure` comes to mind...

**Comment by ezyang** [comment]
Well, it probably is possible to fix the build system; I just didn't feel like dealing with it at the moment.

I actually don't think `configure` would benefit much from a monad, at least in the sense that you seem to be alluding to. There is not actually any state which is evolving consistently over the entire function. (Now, if you said we need an warning collecting monad, yes, absolutely!)

**Comment by BardurArantsson** [comment]
Would it be prohibite (maintenance-wise) to just (ahem) import[1] the StateT code into Cabal/cabal-install? (I have no idea how 'well-factored' the code for `transformers` is, so I don't know if StateT relies on 5 other modules, which rely on 3 other modules, etc.)

[1] As in: Ctrl+C Ctrl+V

**Comment by ezyang** [comment]
I mean, no. Indeed, for performance, it is suggested you reimplement all your monad transformer stacks as monolithic monads. GHC does this repeatedly for many different monads.

**Comment by phadej** [comment]
FWIW, thru `parsec` we'll soon depend on `mtl` and `transformers` and `text`. So rather not copy, but start to depend directly
