### ISSUE TITLE
Mac OS X continuous integration

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3550]
According to https://docs.travis-ci.com/user/multi-os/ Travis supports OS X. We should add it to the build matrix.

**Comment by 23Skidoo** [comment]
IIRC, Stack's Travis script supports OS X, so we can start by looking there.

**Comment by phadej** [comment]
@23Skidoo they only use `stack` on osx

**Comment by ezyang** [comment]
Once I finish #3525 we will have on-time Mac OS X builds.

**Comment by ezyang** [comment]
Fixed!
