### ISSUE TITLE
How to run single package tests.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3558]
Whole suite takes ages, which is frustrating.

**Comment by ezyang** [comment]
If you are running test binary directly use `-p` which applies a regex filter to the test names. I personally hate this interface but it's what tasty gives us and I've been too lazy to complain about it to upstream.

Also, if it's package-tests, `test.sh` in the same directory as `test.log` is intended to let you rerun the test without running the actual test driver.

**Comment by 23Skidoo** [comment]
You can use `cabal test --test-option="-p PATTERN"`.
