### ISSUE TITLE
Flags to `cabal test` not to build, neither to reconfigure

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3561]
Sometimes I want `cabal test` just to run all tests for me,
- not try to reconfigure (IIRC there was some issues when `cabal` either used `Setup.hs` or interpreted `.cabal` file directly, and when I did `cabal test` it tried to reconfigure)
- re-building hadn't been an issue, but could be good to make it possible to disable as well.

I'm ok if this is implemented only for `new-test`, when it's done.

**Comment by ezyang** [comment]
If `cabal test` reconfigures unnecessarily that's a straight up bug and should be fixed.

**Comment by 23Skidoo** [comment]
Does `cabal test --only` work for you?

**Comment by phadej** [comment]
I don't remember what this was about.
