### ISSUE TITLE
Unnecessary recompilation when using the CPP language extension

### ISSUE THREAD

**Issue by asr** [haskell/cabal#3562]
Using the files below I got the following behaviour:

```
$ cabal install --enable-tests
...

$ cabal install
...
Preprocessing library Foo-0.1.0.0...
[1 of 1] Compiling Foo              ( Foo.hs, dist/build/Foo.o ) [dist/build/autogen/cabal_macros.h changed]
```

Cabal correctly changes `cabal.macros.h` because the dependencies of the library and the test-suite are different.
 
Why  the module `Foo.hs` is recompiled?

If I comment-out  `{-# LANGUAGE CPP #-}` in `Foo.hs`, this module isn't recompiled.

Files: [Foo.cabal.txt](https://github.com/haskell/cabal/files/366309/Foo.cabal.txt), [Foo.hs.txt](https://github.com/haskell/cabal/files/366310/Foo.hs.txt) and [Test.hs.txt](https://github.com/haskell/cabal/files/366311/Test.hs.txt).

Cabal and GHC versions:
```
$ caball --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library

$ ghc --numeric-version
8.0.1
```

**Comment by phadej** [comment]
The is no way to check whether symbols from `cabal_macros.h` aren't used in `Foo.hs`, most likely if you have `{-# LANGUAGE CPP #-}`, then you use it.

solution to https://github.com/haskell/cabal/issues/3545 will probably fix this as well, as libraries and test-suite `cabal_macros.h` will be actually different.

**Comment by asr** [comment]
Thanks for the reference to #3545.

**Comment by ezyang** [comment]
Yes, this is fixed in master.

BTW, there is always an implicit include of `cabal_macros.h`. Without `CPP` this can never affect the module, but with it we have to recompile. Arguably GHC should be smarter about not recompiling when preprocessor output is the same, but that is a GHC bug.

**Comment by ezyang** [comment]
PS the real ticket is #1893 and the fixing commit is 90e908b80b327c4636c21627b0e2a54a6a8d4e4f

**Comment by asr** [comment]
I *couldn't* reproduce the problem using the current master (commit 0260415). Thanks!
