### ISSUE TITLE
Wrong warning when using `--enable-tests`

### ISSUE THREAD

**Issue by asr** [haskell/cabal#3563]
Using the files below I got the following behaviour:

```
$ cabal install --enable-tests
...
$ cabal install --enable-tests
...
Foo-0.1.0.0 *test (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
```

Why I got the above warning (and the `Foo-0.1.0.0 *test (reinstall)` message) if I'm not reinstalling anything?

Files: [Foo.cabal.txt](https://github.com/haskell/cabal/files/366411/Foo.cabal.txt), [Foo.hs.txt](https://github.com/haskell/cabal/files/366412/Foo.hs.txt) and [Test.hs.txt](https://github.com/haskell/cabal/files/366413/Test.hs.txt).

Cabal and GHC versions:
```
$ caball --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library

$ ghc --numeric-version
8.0.1
```

**Comment by phadej** [comment]
Why you think you aren't reinstalling?

**Comment by asr** [comment]
Because I'm running `cabal install --enable-tests` twice in row. What I'm reinstalling?

**Comment by phadej** [comment]
the package `foo` (is it a library?) into your user database

**Comment by asr** [comment]
Ah, I see. Thanks.
