### ISSUE TITLE
You're awesome! We're giving you commit bits.

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3567]
Hello @thumphries, @sjakobi, @accraze, @headprogrammingczar, @randen, @aisamanra, @kolmodin, @mightybyte, @gbaz, @garetxe, @komadori, @mgsloan, @lukexi, @mpkh, @pra85, @tvestelind, @corngood, @gelisam,

You're receiving this message because you recently contributed to Cabal. We value your contribution to Cabal, and so in the style of [The Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html), we are giving you commit bits.  There are a few common sense rules about pushing to master (e.g., https://github.com/haskell/cabal#conventions — especially, keep the CI green and PR big changes before pushing), but mostly, be bold!

This is a new experiment for all of us and if there are things that are confusing and unclear please ask, we will try to clarify as much as possible.

P.S. If you know anyone I missed, please let me know.

**Comment by 23Skidoo** [comment]
Also added @Blaisorblade since he's one who originally proposed this idea and has contributed some patches in the past.

**Comment by kolmodin** [comment]
Wohoo! First of all, thanks! :)

This also gives access to edit in the issue tracker. I've missed this in the past when I've seen {mis,un}labeled issues. Great!

So you do most development against `master` but bigger features in feature branches?
New releases are always made from `master`?

**Comment by 23Skidoo** [comment]
@kolmodin 
> So you do most development against `master` but bigger features in feature branches?

Basically yes, big features are expected to go through code review before merging.

> New releases are always made from `master`?

From release branches. For example, all 1.24 releases are made from the [1.24 branch](https://github.com/haskell/cabal/tree/1.24).

**Comment by kolmodin** [comment]
> From release branches. For example, all 1.24 releases are made from the 1.24 branch.

Ah, ok. And the release manager is responsible for merging fixes and updates from master to the release branch for minor releases?

**Comment by ezyang** [comment]
Yeah, at the moment only the release manager is supposed to touch the stable branches. But if that is not working for people we can reconsider.

FWIW, I know some people work on big features by running feature branches but my personal style is maintaining patchsets which I continually rebase on HEAD, the idea being that self-contained patches are easier to CR. I'm not sure we should enforce this on everyone though.

**Comment by phadej** [comment]
CR?

**Comment by ezyang** [comment]
Code review!

**Comment by ezyang** [comment]
@acfoltzer added!

**Comment by gelisam** [comment]
Wow, this is a very active project! My inbox is already overflowing with
GitHub notifications from the project, mostly about features I've never
heard of. I guess I'll keep lurking until I get a better idea of what's
going on, or until I see a bug go by which I think I'd be able to fix.

Thanks for adding me!

**Comment by ezyang** [comment]
@gelisam Sorry about the spam! If you (or anyone else) don't want to get notifications for ALL tickets, I think the "unwatch" button should work. But also feel free to lurk / ask questions!

**Comment by 23Skidoo** [comment]
Also added @snoyberg since he has contributed patches and bug reports in the past.

**Comment by snoyberg** [comment]
Thanks :)

**Comment by ezyang** [comment]
Added @NovaDenizen for https://github.com/haskell/cabal/pull/3657

**Comment by ezyang** [comment]
Added @0xmohit for https://github.com/haskell/cabal/pull/3660

**Comment by 23Skidoo** [comment]
Added @mmakowski for [his past contributions](https://github.com/haskell/cabal/commits/master?author=mmakowski).

**Comment by ezyang** [comment]
Added @fmaste for https://github.com/haskell/cabal/pull/3670

**Comment by fmaste** [comment]
Thanks!!

**Comment by Blaisorblade** [comment]
Just found meta:easy for those looking for for ideas to get started:
https://github.com/haskell/cabal/issues?q=is%3Aopen+is%3Aissue+label%3A%22meta%3A+easy%22

**Comment by 23Skidoo** [comment]
Added @RyanGlScott for #3697 and #3704.

**Comment by ezyang** [comment]
Added @alanz for https://github.com/haskell/cabal/pull/3734

**Comment by ezyang** [comment]
Added @jaccokrijnen for #3757

**Comment by ezyang** [comment]
Added @erantapaa  for #3765

**Comment by ezyang** [comment]
Added @arybczak for #3769

**Comment by ezyang** [comment]
Added @omefire so he can assign himself #3795

**Comment by 23Skidoo** [comment]
Added @sopvop for #3830.

**Comment by ezyang** [comment]
Added @brendanhay  for #3844.

**Comment by ezyang** [comment]
Added @arianvp for #3900

**Comment by 23Skidoo** [comment]
Added @quchen for #3949 and #3952.

**Comment by 23Skidoo** [comment]
Added @christiaanb [for his past contributions](https://github.com/haskell/cabal/commits/master?author=christiaanb).

**Comment by 23Skidoo** [comment]
Added @holzensp for #3959.

**Comment by ezyang** [comment]
Added @fmthoma for #3960 and #3961

**Comment by 23Skidoo** [comment]
Added @niteria for #3974.

**Comment by 23Skidoo** [comment]
Added @christiantakle, who is going to be working on the website together with @arianvp (#4013).

**Comment by ezyang** [comment]
Added @dagit for https://github.com/haskell/cabal/pull/4037

**Comment by ezyang** [comment]
Added @sheyll for https://github.com/haskell/cabal/issues/1493

**Comment by ezyang** [comment]
Added @abooij who is going to work on #4049.

**Comment by ezyang** [comment]
Added @Ericson2314 for #4055

**Comment by 23Skidoo** [comment]
Added @juhp for #4099 and his [past contributions](https://github.com/haskell/cabal/commits/master?author=juhp).

**Comment by ezyang** [comment]
Added @chpatrick for #4105.

**Comment by 23Skidoo** [comment]
Added @DanielG for #4114.

**Comment by 23Skidoo** [comment]
Added @ilovezfs for #4117.

**Comment by 23Skidoo** [comment]
Added @robjhen for #4211.

**Comment by ezyang** [comment]
Added @dmwit for #4264

**Comment by ezyang** [comment]
Added @alexbiehl for https://github.com/haskell/cabal/pull/4289

**Comment by ezyang** [comment]
Added @sergv for https://github.com/haskell/cabal/pull/4302

**Comment by ezyang** [comment]
Added @slpopejoy for #4320

**Comment by 23Skidoo** [comment]
Added @bugthunk for #4426.

**Comment by ezyang** [comment]
Added @praunitbauva1997 for working on #3943.

**Comment by 23Skidoo** [comment]
Added @fgaz for #4491.

**Comment by ezyang** [comment]
Added @bitrauser  for #4490.

**Comment by ezyang** [comment]
Added @colinwahl  for https://github.com/haskell/cabal/pull/4504

**Comment by 23Skidoo** [comment]
Added @p-alik for #4584.

**Comment by 23Skidoo** [comment]
Added @ivan-m for #4591.

**Comment by 23Skidoo** [comment]
Added @amir for #4605.

**Comment by 23Skidoo** [comment]
Added @suzumiyasmith for #4612.

**Comment by ezyang** [comment]
Added @alang for https://github.com/haskell/cabal/pull/4638

**Comment by ezyang** [comment]
Added @themoritz for #4664

**Comment by 23Skidoo** [comment]
Added @tfausak for #4692 & #4693

**Comment by 23Skidoo** [comment]
Added @cocreature for #4176.

**Comment by 23Skidoo** [comment]
Added @vedksah for #4717.

**Comment by 23Skidoo** [comment]
Added @peti for #4725.

**Comment by 23Skidoo** [comment]
Added @bucklereed for #4732.

**Comment by 23Skidoo** [comment]
Added @vaibhavsagar for #4804.

**Comment by 23Skidoo** [comment]
Added @recursion-ninja for #4810.

**Comment by 23Skidoo** [comment]
Added @Mistuke for #4835.

**Comment by 23Skidoo** [comment]
Added @cj285 for #4916.

**Comment by 23Skidoo** [comment]
Added @gwils for #4945.

**Comment by 23Skidoo** [comment]
Added @NathanConroy for #4947.

**Comment by 23Skidoo** [comment]
Added @psiska for #4950.

**Comment by 23Skidoo** [comment]
Added @dalaing for #4948, #4946, and #4940.

**Comment by 23Skidoo** [comment]
Added @kmicklas for #5066.

**Comment by 23Skidoo** [comment]
Added @harpocrates for #5140 and #5141.

**Comment by 23Skidoo** [comment]
Added @takenobu-hs for #5130 and #5101.

**Comment by 23Skidoo** [comment]
Added @takano-akio for #5101.

**Comment by 23Skidoo** [comment]
Added @TravisWhitaker for #5118.

**Comment by 23Skidoo** [comment]
Added @merijn for #5237.

**Comment by 23Skidoo** [comment]
Added @quasicomputational for #5284.

**Comment by 23Skidoo** [comment]
Added @felixonmars for #5364.

**Comment by 23Skidoo** [comment]
Added @qnikst for #5302.

**Comment by 23Skidoo** [comment]
Added @trommler for #5384.

**Comment by 23Skidoo** [comment]
Added @danidiaz for #5385.

**Comment by 23Skidoo** [comment]
Added @ChShersh for #5456 and @vrom911 for #5478.

**Comment by 23Skidoo** [comment]
Added @domenkozar for #5561.

**Comment by 23Skidoo** [comment]
Added @m-renaud for #5657.

**Comment by 23Skidoo** [comment]
Added @watashi for #5670.

**Comment by 23Skidoo** [comment]
Added @DavidEichmann for #5673.

**Comment by 23Skidoo** [comment]
Added @int-index for #5679.

**Comment by 23Skidoo** [comment]
Added @emilypi for #5755.

**Comment by 23Skidoo** [comment]
Added @hrhino for #5810.

**Comment by emilypi** [comment]
I can't believe i missed my own commit bits! Thanks! also, great job @hrhino!

**Comment by 23Skidoo** [comment]
Added @earldouglas for #5879 and #5878.

**Comment by 23Skidoo** [comment]
Added @tseenshe for #5906.

**Comment by 23Skidoo** [comment]
Added @piyush-kurur for #5514.

**Comment by 23Skidoo** [comment]
Added @sboosali for #5928.

**Comment by 23Skidoo** [comment]
Added @JoshMeredith for his contributions to #5995.

**Comment by 23Skidoo** [comment]
Added @basvandijk for past contributions.

**Comment by DanielG** [comment]
@23Skidoo can we add @fendor for #6078 and #5954, part of which got merged as #6108?

**Comment by 23Skidoo** [comment]
Added @fendor.

**Comment by jneira** [comment]
this issue is not active and the commit bit is being given more informally, should be close this? @Mikolaj

**Comment by Mikolaj** [comment]
Yes, we've followed the spirit of this issue, but made no notes. I think most of the contributors from last year were offered commit bits, though not all accepted. There was a talk about automating this and spicing up so that it's obvious that's a sign a gratitude, not of forcing a responsibility on somebody. However, this requires a new ticket and a volunteer. Let's close.

And once more thank you to all people mentioned here. You are awesome indeed. :)

**Comment by Mikolaj** [comment]
Actually, quite a few people refused the invitation and I'm told others might have felt overwhelmed by notifications from the repo, so it's no longer obvious an unannounced invitation to a repo is token of appreciation and not, e.g,. of assuming the new person is now suddenly responsible for stuff. I guess our traffic has grown too high and also being one of a hundred is not such a distinction any more.

I propose we drop the habit and instead try to honour contributors by being uncharacteristically civil and expressing gratitude orally. Thoughts?

**Comment by jneira** [comment]
or ask the contributor before giving them perms in the pr?
also you can be a member and silence or reduce repo notifications

**Comment by ulysses4ever** [comment]
It's a good, net-win practice: it cause no harm but may attract new contributors. As noted, notifications are ready to turn off (or ignore the invite altogether).

Sending some standard text that you have this practice and or bears no responsibility, only an opportunity to donate some more of your time, would be welcome. Initially, I was confused when I got the invite, and thought maybe it's a mistake.

**Comment by Bodigrim** [comment]
> It's a good, net-win practice: it causes no harm but may attract new contributors. As noted, notifications are easy to turn off (or ignore the invite altogether).

As an outside observer, I fail to discover any tangible benefit of this practice: while it was followed since 2016, by mid 2020 the number of active contributors decreased roughly to one and remained in that precarious state until recently. I do believe that "being uncharacteristically civil" is a key to create a welcoming environment (huge thanks to the current team for this!), and granting commit bits to strangers out of nowhere is irrelevant.

There is a clear downside of this practice in terms of security. If I have a write access, I can forge a commit from any author with any message and push it into any branch. There are currently 75 people with write access, which is a huge liability.

**Comment by gbaz** [comment]
I believe we should spread the ability to "garden" (set tags and soforth) to anyone with an accepted PR. Having a smaller pool of people with permission to actually commit merges seems fine at this point.

**Comment by Bodigrim** [comment]
Yeah, assigning 'triage' rights is pretty harmless.

**Comment by jneira** [comment]
Well, master and main version branches are protected and nobody, including admins (by default, they can skip it of course) can push directly to them, You need a pr with two approvals. Otoh you (any admin) can always revert any change (even with force pushes if you take care quickly) and revoke permissions.

There are no similar protections for triaging so i would say triaging perm can destroy more valuable info: the issue tracker and the metadata associated. You cant revert remove a label for all issues for example. And the time spent by users and maintainers in the issue tracker is as valuable as the time spent in the codebase imho. 

Otoh give membership helps to build such welcoming environment and helps to avoid an elitist and inaccesible image. Also it encourages the continuation of the contributions. That alone will not make it, as it was demonstrated but sure helps.

But well i think it is better to simply ask contributors if they want to be and only doing it if they responds affirmatively.

**Comment by Mikolaj** [comment]
Unfortunately, I haven't found a way to send an invitation text automatically or even via copy-paste. The Setting/Add People menu doesn't have the functionality, I think. There were talks about some plugins that enable this, but it didn't materialize. I haven't found a way to filter contributors based on PR authorship and on commit bits, either, so guessing whom to send to was manual labor as well.

Would a snippet in README, similar to what @jneira linked, mentioning triage, "commit bit if really needed" and general gratitude regardless, be a better solution than blanket invite-spam? OTOH, reaching out individually to people is invaluable, but that is happening in discussions in the bug tracker and in the #hackage room.
