### ISSUE TITLE
Print final conflict set when dependency solver fails after an exhaustive search

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3570]
@kosmikus suggested showing this message at default verbosity because it is often more relevant than the summarized log.

EDIT:
The new message could go here: https://github.com/haskell/cabal/blob/c116df4742264641f281e9480731cdd8313b309a/cabal-install/Distribution/Solver/Modular/Log.hs#L86  This is where the solver prints a message after an exhaustive search.  It already has access to the final conflict set, `cs`.

I would add a unit test to Solver.hs. Here is an example of a test that checks for a specific error message:
https://github.com/haskell/cabal/blob/c116df4742264641f281e9480731cdd8313b309a/cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs#L45

**Comment by ezyang** [comment]
@grayjay, if PR is welcome, could you edit your message to say where the code is that you would update to make this change, and how you would test it? Thanks!

**Comment by grayjay** [comment]
I realized that the hardest part of this issue is coming up with helpful wording.  The task isn't as well-defined as I thought, so I removed the label.

**Comment by grayjay** [comment]
Added in #3960.
