### ISSUE TITLE
Package sections in cabal.project are insufficient, need local section

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3579]
I'm working on a project and I want to turn on `-Werror`. OK, I'll add `ghc-options: -Werror` to my `cabal.project`. BUT WAIT, this turns on `-Werror` for all my dependencies too. Well, the package I'm building is called `Cabal`, so I'll put it in a package section `package Cabal`.

BUT WAIT: setup dependencies caused an older version of Cabal to be built, which also got `-Werror` applied. Disaster!

All I want is a section that lets me finger the packages that are going to be built inplace.

**Comment by dcoutts** [comment]
Hmm, I thought options at the top level were for local packages, and the problem was we didn't have any way to have options for all packages. So there may be some mistake here.

**Comment by ezyang** [comment]
I checked, and at least for cabal-install-1.24 a top-level `ghc-options` is not understood.

**Comment by ezyang** [comment]
The reason is that there are a set of options which are only added in the package stanza:

```
      sectionFields      = legacyPackageConfigFieldDescrs
                        ++ programOptionsFieldDescrs
                             (configProgramArgs . legacyConfigureFlags)
                             (\args pkgconf -> pkgconf {
                                 legacyConfigureFlags = (legacyConfigureFlags pkgconf) {
                                   configProgramArgs  = args
                                 }
                               }
                             )
                        ++ liftFields
                             legacyConfigureFlags
                             (\flags pkgconf -> pkgconf {
                                 legacyConfigureFlags = flags
                               }
                             )
                             programLocationsFieldDescrs,
```

Was there a reason you specifically did it this way?

**Comment by dcoutts** [comment]
@ezyang there's a `program-locations` section which has the top-level program locations. But perhaps we should abandon that and just allow $PROG-location and $PROG-options at the top level of the file rather that bundling them into a named sub-section. I guess I was thinking it was tidier this way, but it's not essential.

**Comment by ezyang** [comment]
Is there a functional difference? Doesn't look like it. Would there be any reason not to support both syntaxes?

**Comment by phadej** [comment]
Bump. Should this be given higher prioritity? Writing

```
package local-foo
  ghc-options: -Werror

package local-bar
  ghc-options: -Werror
```

is tiresome.

**Comment by coot** [comment]
> Bump. Should this be given higher prioritity? 

That would be appreciated; in `iohk` we a `cabal.package`s with a dozen of [local packages](https://github.com/input-output-hk/ouroboros-network/blob/master/cabal.project). Setting common options for them all would be a relief.  This would be also appreciated from the point of a `ghc-plugin` user (adding `--ghc-options=-fplugin=....` just in one place). Currently my `cabal.project.local` file for that repository  contains `17` repetitions (each contains ~5 lines, this adds up to 85 lines, instead of 5 or 6).

**Comment by philderbeast** [comment]
Putting `ghc-options` in one shared `ghc-options.dhall` imported by a `package.dhall` that [hpack-dhall](https://hackage.haskell.org/package/hpack-dhall) reads to generate a `*.cabal` could be used to workaround this cabal.project limitation @coot.

**Comment by coot** [comment]
Thanks @philderbeast that's indeed helpful for some projects, for others (large ones) introducing another layer of tooling is problematic.

**Comment by goldfirere** [comment]
Bump: just hit this missing feature, too.

**Comment by gbaz** [comment]
I believe the above linked pr (https://github.com/haskell/cabal/pull/7973) resolves this?

**Comment by goldfirere** [comment]
It looks like it does -- thank you! Then should this ticket be closed?

**Comment by jneira** [comment]
It should be closed, yeah. After #7973, `ghc-options` is only applied to all local packages. IT is possible recover the old behaviour, see the workaround here: https://github.com/haskell/cabal/pull/7973#issuecomment-1038837581
Thanks!
