### ISSUE TITLE
RFC remove allow-older and allow-newer support from Setup.hs

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3581]
_Shortly:_ revert changes made in  https://github.com/haskell/cabal/issues/3163 & https://github.com/haskell/cabal/pull/3165, as well as followed `--allow-older` changes. 

_Motivation:_ Such functionality isn't necessary (not used by anyone) to be provided by `Cabal`/`Setup.hs`<sup>&dagger;</sup>, and results into duplicate code (starting from argument parsing etc). `--exact-configuration` should be enough for everyone to force "I know what I'm doing". For the situations were "I almost know what I do, help me with rest", one could/should use external tools (e.g. `cabal-install` could have `cabal solver` command to produce configuration file).

_Optional:_
- Add `--exact-configuration` to `cabal-install`
- Add `cabal solver` (we now use `cabal configure -v2 --dry-run`, but it feels semantically wrong).

_Alternative:_ leave `--allow-newer` in `Cabal`, only remove followed `--allow-older` changes. IMHO this would lead to confusion. `--allow-older` hasn't hit Hackage AFAIK.

_Note:_ this is proposal to remove them only from `Cabal`-the-library, `cabal-install` will continue to have them.

<sup>&dagger;</sup> AFAICS stack opted to use `--exact-configuration` https://github.com/commercialhaskell/stack/issues/1579#issuecomment-168098272

ping @hvr, @ezyang, @23Skidoo, @dcoutts

**Comment by ezyang** [comment]
OK, fine. But we need a test which demonstrates that `--exact-configuration` is sufficient to override the package's `build-depends`.

**Comment by kosmikus** [comment]
Seems I'm missing a whole lot. In particular, I have not the slightest idea what `--exact-configuration` is or does. Where can I read up on this?

**Comment by ezyang** [comment]
@kosmikus The situation is that Cabal the library has a miniature dependency solver, which picks dependencies when a user runs `./Setup configure`. This solver is run even when you say `--dependency="foo=foo-0.5-blahblah"` because you may not have specified a complete set of dependencies and flags. Of course, if you're running `cabal-install`, by the time you get to the setup script you know exactly what dependencies you want. So you can then say `./Setup configure --exact-configuration --dependency="foo=foo-0.5-blahblah"` and then no solver is run; we just take the command line arguments on faith.

`exact-configuration` is completely undocumented and I know about it from reading the `configure` source code.

**Comment by 23Skidoo** [comment]
> *Motivation:* Such functionality isn't necessary (not used by anyone)

Well, the reason it was added was because a user requested it. If @snoyberg no longer needs it, we can reconsider, but I don't think removing it buys us that much. #3165 added 100 lines total, and more than half of those were comments and tests.

**Comment by snoyberg** [comment]
CCing @mgsloan, who will know more about this than I do.

**Comment by mgsloan** [comment]
We don't need such a flag.  I recall a discussion that likely caused this to be implemented.

`stack build --allow-newer` is more permissive than cabal-install's allow-newer.  It causes all version constraints to instead be warnings.  As far as I know, cabal-install does not have this capability.  I guess it would mean installing all the latest versions, maybe?

**Comment by fread2281** [comment]
Nix currently runs `Setup.hs`, and not `cabal configure` (or any cabal command), so this is needed to avoid modifying cabal files afaik (which on nix is fairly involved). I was using this.
