### ISSUE TITLE
Continuous deploy for Cabal website

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3605]
We have: http://haskell.github.io/cabal-website/doc/html/Cabal/

That's great. But there are some more improvements to be made;

1. The canonical location for docs is https://www.haskell.org/cabal/ . We should set up continuous deploy for documentation to this location. This means contributors can suggest fixes to the manual, and then ACTUALLY see their docs make it out to people before the next release.
2. There needs to be a reference to the URL the docs are deployed at in the README of the gh-pages https://github.com/haskell/cabal-website/tree/gh-pages
3. https://github.com/haskell/cabal-website/tree/master Is this really the Cabal website? I don't see any other pages here!

CC @23Skidoo

**Comment by 23Skidoo** [comment]
1. I'm a bit nervous about giving Travis write access to haskell.org/cabal. I think it'd be OK if we had a docs: [stable | nightly] link on the official website, with "nightly" linking to haskell.github.io.
2. Added.
3. I can put the HTML files currently deployed on haskell.org/cabal there. Originally the plan was to redesign the website first, but I haven't got around to doing that yet.

**Comment by ezyang** [comment]
Re (1), how is the deploy carried out at the moment? If everything is versioned and the deploy script only has access to the website itself, I don't see there actually being much harm in the failure mode (someone hacks Travis, defaces website; someone pushes something bad to Cabal, defaces website; someone pushes something bad and the website is glitched?)

Re (3), if the HTML is easy, please do!

**Comment by 23Skidoo** [comment]
1. We need to set up a deploy key for haskell.org/cabal if we're going to enable Travis pushing there. Currently only me, @rthomas, @tibbe and @dcoutts have access. Though I'd prefer if haskell.github.io was used as a staging area, and haskell.org/cabal was updated manually.
3. Done.

> someone hacks Travis, defaces website

This also gives access to haskell.org/cabal/relase, so the attacker can modify release tarballs.

/cc @davean

**Comment by ezyang** [comment]
OK, well, that's a showstopper. I wonder if there is a way to just make the docs updateable.

**Comment by 23Skidoo** [comment]
Maybe we can set up a special account with write access only to https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/.

**Comment by 23Skidoo** [comment]
haskell.org/cabal also seems to be CDN-cached, so using haskell.github.io as a staging area will provide more immediate feedback.

**Comment by ezyang** [comment]
This is fixed with readthedocs.
