### ISSUE TITLE
Cabal/PackageTests/Configure fails on osx, but travis don't.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3623]
See https://travis-ci.org/haskell/cabal/jobs/146958847

reproduced locally, I have `autoreconf` installed

**Comment by phadej** [comment]
Uh. requiring `X` is a bit overkill.

**Comment by ezyang** [comment]
The test uses X because that was the example in documentation https://www.haskell.org/cabal/users-guide/developing-packages.html#system-dependent-parameters

But there isn't any reason it can't be changed to something more portable. Suggestions?

**Comment by phadej** [comment]
`zlib` comes to mind

**Comment by 23Skidoo** [comment]
`zilb-dev` is usually not installed by default.

**Comment by phadej** [comment]
Well, it's needed to build Haskell `zlib`, so it shouldn't be far away.

**Comment by 23Skidoo** [comment]
Yeah, you're right, `zlib-dev` is probably installed by default on Travis given that we don't install it ourselves and `cabal-install` depends on `zlib`.

**Comment by ezyang** [comment]
Fixed.
