### ISSUE TITLE
Way to pass custom options to hook script

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3625]
On IRC, `akegalj` asked if there was a way to pass arguments to a hook specifically. I don't think there is any way to do this. It seems like a good thing to offer, but I don't know how to integrate it smoothly into existing hooks. See also #3600

**Comment by akegalj** [comment]
Looks like there is a way to do this. 

We can declare some flag in cabal with 
```
Flag FlagName
  Description: Compile Block Explorer frontend bundle
  Default:     False
```

and then from `UserHooks` (for example `postReg` http://hackage.haskell.org/package/Cabal-1.24.0.0/docs/Distribution-Simple-UserHooks.html#v:postReg) we can use `LocalBuildInfo.configFlags.configConfigurationsFlags` http://hackage.haskell.org/package/Cabal-1.24.0.0/docs/Distribution-PackageDescription.html#t:FlagAssignment . `FlagName` should appear in this list.

We should close this issue.

**Comment by ezyang** [comment]
Note: you probably want to declare the flag as manual.

What if you want to pass a string?

**Comment by akegalj** [comment]
> What if you want to pass a string?
I guess it is a valid use case but we don't have it. Using `LocalBuildInfo.configFlags.configConfigurationsFlags` solves our problems.

You might still want to keep this issue if you find that feature like that should be implemented.

**Comment by ezyang** [comment]
OK I'm closing this. If someone else wants it they can shout.
