### ISSUE TITLE
ghc-paths-0.1.0.9 setup is broken

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3626]
```
cabal: Entering directory '/tmp/cabal-tmp-3198/ghc-paths-0.1.0.9'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-3198/ghc-paths-0.1.0.9/dist/setup/setup.hs, /tmp/cabal-tmp-3198/ghc-paths-0.1.0.9/dist/setup/Main.o )
/tmp/cabal-tmp-3198/ghc-paths-0.1.0.9/dist/setup/setup.hs:65:7: error:
    • Couldn't match type ‘(Maybe a0, [a1])’
                     with ‘[(ComponentName, BuildInfo)]’
      Expected type: IO HookedBuildInfo
        Actual type: IO (Maybe a0, [a1])
    • In a stmt of a 'do' block: return (Just (read str), [])
      In the expression:
        do { str <- readFile file;
             return (Just (read str), []) }
      In an equation for ‘readHook’:
          readHook _ _
            = do { str <- readFile file;
                   return (Just (read str), []) }
```

Job: https://travis-ci.org/ekmett/bytes/jobs/147342137

**Comment by phadej** [comment]
Regarding this and other recent `setup-depends` & breaking change issues. We should setup a test-bench which tests various different packages with `setup: Custom` across different ghc and cabal-versions (three dimensional matrix).

It should be as "easy" as having a repository with travis-setup which installs all ghc/cabal-install versions (ghc-7.0 &mdash; ghc-head, cabal-install-1.10 &mdash; cabal-install-head) and has a job per package. We should figure out how to deal with common custom `Setup.lhs`

**Comment by ezyang** [comment]
Ah yes, this one. I think I'm going to revert the new feature I wrote to generalize this to work for all components. Seems emphatically not worth it.

**Comment by phadej** [comment]
I setup https://travis-ci.org/phadej/cabal-compatibility/builds/147350764

Seeps that only `new-build` on `1.24` honours `setup-depends`. It's this still the case?

**Comment by phadej** [comment]
ping @ezyang @dcoutts @hvr

**Comment by ezyang** [comment]
This is reverted on HEAD.
