### ISSUE TITLE
cabal install network fails on windows

### ISSUE THREAD

**Issue by PierreVDL** [haskell/cabal#3634]
After installing the newest version of Haskell: HaskellPlatform-8.0.1-minimal-x86_64-setup-a
 cabal install network fails.

See for more info the question on stackoverflow:
http://stackoverflow.com/questions/38570323/failing-cabal-install-missingh-and-network-on-windows

I don't know whether it is a cabal bug or network bug: so submitted to both.

**Comment by 23Skidoo** [comment]
You should use MSYS instead of Cygwin and make sure that `$GHC_DIR/mingw/bin` is in PATH (using a different `gcc` can lead to problems). See [here](https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Windows) for additional info.
