### ISSUE TITLE
new-build produces bad error message on missing cabal.project

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#3636]
If the cabal.project file is missing `cabal new-build` produces the rather opaque error message

```
BadPackageLocations [BadLocGlobEmptyMatch "./*.cabal"]
```

It should probably print something more informative. :)

**Comment by BardurArantsson** [comment]
Oh, and the exact cabal-install version I'm running is commit b7b666efd295c091bea4b2b7e8789d1da35086be

**Comment by dcoutts** [comment]
Just need to add `displayException` method to the `instance Exception BadPackageLocations`.

**Comment by BardurArantsson** [comment]
Sigh... I suppose the labels mean that I really should do this...? I'm just (semi-)joking, I'd be happy to, given the hint.

Aside: Why are we relying on overriding defaults in this manner? Shouldn't we just have a (huge) sum type for every single error that Cabal/cabal-install can show and then be *forced* to implement a human-readable error message? (I'm sure I'm doing a "couldn't we just..." type thing here, but...)

(Assigning to self in the hope of finally starting to contribute to Cabal again.)

**Comment by ezyang** [comment]
@BardurArantsson, if you want to rip out and rewrite all of the error reporting code in cabal-install, I will support the endeavor. But I'd want to see some sort of style guideline come out of it, saying, "This is how we deal with error reporting in cabal-install" (and ideally also, "here's why"). So that if I'm a not-paying-very-much-attention developer and I need to add an error, I know what to do, it is not hard to do "the right thing".

**Comment by alanz** [comment]
Ping @BardurArantsson: Are you still working on this? I'm looking for a trivial getting started issue.

**Comment by BardurArantsson** [comment]
No, it fell through the cracks. Feel free to take a swing at it.

**Comment by dcoutts** [comment]
Could someone check what this does now, and suggest changes to the error message that would make it more appropriate for the situation where there is no explicit cabal.project file. The current message is written assuming there is one and the user groks this.

**Comment by ezyang** [comment]
Same old:

```
ezyang@sabre:~/Dev/labs$ cabal-shake new-build
BadPackageLocations [BadLocGlobEmptyMatch "./*.cabal"]
```

**Comment by dcoutts** [comment]
@ezyang what is `cabal-shake` doing? Does its top level exception handler use `show` or `displayException` ?

**Comment by ezyang** [comment]
Oh, the alias was pointing at an old binary. OK this is fixed in HEAD.
