### ISSUE TITLE
`cabal sandbox init --sandbox<tab>` creates sandbox named `--list-options`

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#3648]
There must be a more reliable approach to this whole bash-completion. seems way too easy to break at every corner.

**Comment by lspitzner** [comment]
my bash-completion is that of master branch (minus the new-build addition, which is irrelevant).

**Comment by 0xmohit** [comment]
The culprit appears to be `eval "${cmd[@]}"` [here](https://github.com/haskell/cabal/blob/master/cabal-install/bash-completion/cabal#L91).

Wondering if `--dry-run` should also be passed along.

**Comment by 23Skidoo** [comment]
The problem is that `sandbox init` and other subcommands don't support `--list-options`. I believe that if #1257 was implemented, bash completion would work as is.

**Comment by gbaz** [comment]
closing as obsolete
