### ISSUE TITLE
getShortPathName returns invalid response in Cygwin

### ISSUE THREAD

**Issue by NovaDenizen** [haskell/cabal#3649]
I installed Haskell Platform 8.0.1 into `C:\HPlat`, so gcc is at "c:\\HPlat\\8.0.1\\mingw\\bin\\gcc.exe"
```
$ uname -a
CYGWIN_NT-6.0 myhostnameI 2.5.2(0.297/5/3) 2016-06-23 14:29 x86_64 Cygwin

$ cygpath -d "c:\\HPlat\\8.0.1\\mingw\\bin\\gcc.exe"
C:\HPlat\80227D~1.1\mingw\bin\gcc.exe

$ cygpath -l -w 'C:\HPlat\80227D~1.1\mingw\bin\gcc.exe'
C:\HPlat\8.0.1\mingw\bin\gcc.exe

$ cd ~/dl/Cabal-1.24.0.0/
$ stack repl
...much deleted...
...stribution.Version Language.Haskell.Extension> getShortPathName "c:\\HPlat\\8.0.1\\mingw\\bin\\gcc.exe"
"c:\\HPlat\\80227D~1.1"
...stribution.Version Language.Haskell.Extension>:q

$ cmd /version
Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

```

**Comment by ezyang** [comment]
CC @23Skidoo who wrote this code.

Since cygpath computes short path correctly, we can look at its source code to see how to do it properly http://cygwin-ports.sourceforge.net/scan-build/utils/report-MWMmDX.html

From GetShortPath docs:

> The path that the lpszLongPath parameter specifies does not have to be a full or long path. The short form can be longer than the specified path.

So that makes the current implementation incorrect in some cases. But after reading the code I don't see anything else obviously wrong.

**Comment by NovaDenizen** [comment]
Found the way to fix it from [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364989.aspx) 

> Passing NULL for this parameter and zero for cchBuffer will always return the required buffer size for a specified lpszLongPath.

**Comment by NovaDenizen** [comment]
#3487 seems related too.

**Comment by ezyang** [comment]
Thanks, I think it is indeed this bug!

**Comment by ezyang** [comment]
I would close this but if we do a point release for 1.24.0.1 we should put this patch in.

**Comment by 23Skidoo** [comment]
Already cherry-picked this into 1.24, so closing.
