### ISSUE TITLE
doubled field

### ISSUE THREAD

**Issue by bos** [haskell/cabal#366]
(Imported from [Trac #373](http://hackage.haskell.org/trac/hackage/ticket/373), reported by guest on 2008-10-16)

I have just uploaded a Cabal package to Hackage which has by accident two
Homepage fields. But Hackage does only show the second of the two fields.
I think either Hackage should support multiple Homepage fields or 'cabal
check' should warn about doubled fields.

**Comment by ttuegel** [comment]
This will be resolved by #2879.

**Comment by phadej** [comment]
not yet, but very soon.
