### ISSUE TITLE
cabal clean requires sandbox (with require-sandbox: True)

### ISSUE THREAD

**Issue by creswick** [haskell/cabal#3666]
## Reproduction:

 - Compile a project (call it PROJECT) with cabal, without a sandbox.
 - Set `require-sandbox: True` in ~/.cabal/config
 - run `cabal clean` in PROJECT

Cabal reports:
```bash
 $ cabal clean
cabal: 'require-sandbox' is set to True, but no sandbox is present. Use
'--no-require-sandbox' if you want to override 'require-sandbox' temporarily.
```

I think cabal clean should clean regardless of the presence of a sandbox.

**Comment by ttuegel** [comment]
Which version of `cabal-install` are you using? I believe this is a duplicate of #3494; if so it is fixed in master.

**Comment by creswick** [comment]
I'm sorry - I meant to include that!

```bash
 $ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library
```

I'll try master.

**Comment by creswick** [comment]
You're right! This is fixed in master.
