### ISSUE TITLE
new-build can't "undo" a build flag and build without the flag

### ISSUE THREAD

**Issue by mightybyte** [haskell/cabal#3681]
Steps to reproduce:

    git clone https://github.com/snapframework/snap-server.git
    cd snap-server
    cabal new-build -fopenssl
    ...some time goes by
    ...you come back to working on this package, but haven't changed any code
    rm -fr dist-newstyle
    cabal new-build

Expected behavior: cabal builds the package without the -fopenssl flag
Actual behavior: cabal tells me that the package is already built, or if it does build the package, it also builds HsOpenSSL which I didn't want to bother with.

At this point I straight-up could not figure out how to get new-build to build the package without the flag.  I guess I could have hunted it down in the cache and deleted it, but that's clearly not an acceptable solution.

I think you should be able to reproduce this with any package and flag.  It was just particularly obvious to me in this particular case because building HsOpenSSL is finicky on Mac.

This is with cabal-install-1.25.0.0.  I think built from commit a92bfc8dfa806e998d49bc661a65020bfb335694

**Comment by dcoutts** [comment]
Worth noting that it's a manual flag:

    Flag openssl
      Description: Enable https support using the HsOpenSSL library.
      Default: False
      Manual: True

**Comment by mightybyte** [comment]
Note that this seems like mostly a command-line UI question to me.  How do you tell cabal when you want to use an already-built set of flags vs when you want to explicitly tell it to build a new set of flags?  But I definitely consider it a bug because it was preventing me from doing something that I needed to do.

**Comment by dcoutts** [comment]
The intention is that this is a stateless UI, so there isn't a notion of a new set vs an existing set, it's just "build this with these flags as if from scratch" (but it caches a fair bit to avoid redoing unnecessary work).

**Comment by mightybyte** [comment]
@dcoutts Yeah, I get that.  But this seems to be a situation where that model breaks down.

**Comment by ezyang** [comment]
Does this workaround work? Add this to your `cabal.project.local`:

```
package snap-server
  flags: -openssl
```

This just sounds like an outright bug. Just to confirm, if you build `snap-server` completely from scratch, e.g., a fresh checkout and fresh HOME directory with no flags, it does NOT build HsOpenSSL?

**Comment by ezyang** [comment]
I did exactly the instructions in the ticket and couldn't repro. My commit is 3e3f3aa3923d3b1437626a6ac6c31c12c0ddab9f. @mightybyte do you have any other ideas about how to repro?

**Comment by mightybyte** [comment]
I haven't had much time to look at it either, but when I did look at it I also was having trouble with the repro.  It seems I may have encountered another bug.  Installing HsOpenSSL on Mac requires specifying --extra-include-dirs.  That works fine with cabal install, but it doesn't seem to be working with new-build.

**Comment by ezyang** [comment]
I think your new problem is another variant of #3719.

**Comment by mightybyte** [comment]
Ok, I agree with your assessment of #3719 for my --extra-include-dirs problem.  I'll close this for now since I'm not sure what is up with my repro.
