### ISSUE TITLE
Allow constraint on using installed package versions

### ISSUE THREAD

**Issue by bos** [haskell/cabal#369]
(Imported from [Trac #376](http://hackage.haskell.org/trac/hackage/ticket/376), reported by @dcoutts on 2008-10-20)

We allow command line args for adding version constraints. Internally the dependency resolver can use constraints on the installed status. We should allow such constraints to be given on the command line, and possibly in the cabal config file.

We should probably also allow preferences to be given on the command line too.

**Comment by andreasabel** [comment]
It would be nice if `--constraint='all installed'` would work to pin the packages shipped with GHC.
