### ISSUE TITLE
cabal fetch should support --with-ghc option

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#3692]
Although `cabal fetch` does not compile anything, it uses `ghc-pkg` for finding installed packages. E.g. I have default GHC version 7.4.2 and want to fetch a package that can be compiled only with GHC-7.6.3 and `base-4.6` and later. Currently I get:

```
$ cabal fetch kaleidoscope
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: kaleidoscope-0.1.0.0 (user goal)
next goal: base (dependency of kaleidoscope-0.1.0.0)
rejecting: base-4.5.1.0/installed-66f... (conflict: kaleidoscope => base>=4.6
&& <4.10)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Dependency tree exhaustively searched.
```

I do not see a way to (only) download that package and its dependencies.
I propose to add a `--with-ghc` option to `fetch`.

**Comment by ezyang** [comment]
I think you are right. Doesn't sound too difficult, would be happy to advise. There are some TODO comments in `cabal-install/Distribution/Client/Fetch.hs` to this effect.

A few further notes:

1. If you use `cabal unpack` instead, we don't query `ghc-pkg`, so you can download anything you want
2. If you use `new-build`, `new-configure` will go ahead and download all of the packages you need to build, and that setting supports `-w`, so this is a non-problem there.

**Comment by dcoutts** [comment]
Right, it should be easy to make new-fetch support this. Indeed it'd be hard to avoid supporting this when new-fetch is implemented.

**Comment by Mikolaj** [comment]
I'm taking the liberty of closing this ticket due to its age and inactivity. Please open a new one if/when you are able to reproduce with an up to date cabal (assuming you are still using the v1- cabal API). Thank you for the report!
