### ISSUE TITLE
new-build always creates an empty dist directory in addition to dist-newstyle

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3699]
Steps to reproduce:
- `cabal get shake-0.15.10`
- `cd shake-0.15.10`
- `cabal new-build`
- `ls -la dist/`
- `ls -la dist-newstyle/`

**Comment by ezyang** [comment]
These instructions are incomplete as shake does not have a cabal.project.

**Comment by 23Skidoo** [comment]
> These instructions are incomplete as shake does not have a cabal.project.

They worked for me without one, I don't think a `cabal.project` is required when there's a top-level `.cabal` file in the directory.

**Comment by dcoutts** [comment]
Yeah, I see this all the time too, have not yet dug into it.

**Comment by RyanGlScott** [comment]
`new-install` also does this. This is somewhat more annoying that in the `new-build` case, since I often invoke `new-install` in places that _aren't_ directories that solely contain Haskell projects, which causes my filesystem to become littered with empty `dist` folders.
