### ISSUE TITLE
Regression: Version bounds ignored with constraints.

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#3701]
Ghc 7.10.3 with `cabal-install` version `1.24.0.0` seems to have a regression with respect to version `1.22.6.0`.

Found this building `haskell-tor`. Reproduciton:
```
git clone https://github.com/erikd/haskell-tor.git
cd haskell-tor
cabal install 
cabal install --dependencies-only --enable-tests --constraint="tls +hans"
```
results in cabal installing `hans` version `3.0.0.1` despite the cabal file having:
```
  if flag(hans)
    build-depends:    hans                       >= 2.6   && < 2.8
    exposed-modules:  Tor.NetworkStack.Hans
```

However, if I do the above with `cabal-install` version `1.22.6.0` it installs a version of `hans` that obeys the above constraints.

**Comment by erikd** [comment]
Currently working on debugging this myself.

**Comment by hvr** [comment]
for the record, it was pointed out on IRC, that `haskell-tor` has its own `hans` flag as well; and `--constraint="tls +hans"` only sets `tls`'s flag to true (and `tls-1.3.4` has no version bounds on `hans`), but still allows `haskell-tor`'s `hans` flag to be false (which is what happens when I try to reproduce this locally)

**Comment by erikd** [comment]
@hvr also suggested:
```
cabal install --dependencies-only --enable-tests --constraint="tls +hans" \
    --constraint="haskell-tor +hans"
```
which did actually work. However, I find it interesting that something that worked with cabal 1.22 doesn't work with cabal 1.24.

**Comment by erikd** [comment]
From IRC:
```
<hvr> iow, say --constraint="tls +hans" --constraint="haskell-tor +hans"
<erikd> hvr: there is still the issue of something that worked with cabal 1.22 and doesn't
               work with cabal 1.24.
<hvr> erikd: well, if it worked, it was due to undefined behaviour
<hvr> tls is doing something that's not guaranteed to work: use an automatic flag to toggle
              an optional dependency + API feature
<hvr> it's just luck that cabal-1.22 picked an install plan and set flags in such a way that
             this worked
<hvr> but it was certainly not supported by the flag semantics
```
Closing this.
