### ISSUE TITLE
Include hackage-security public keys

### ISSUE THREAD

**Issue by DemiMarie** [haskell/cabal#3710]
The public keys needed for hackage-security to work are not included, so signatures cannot be being verified.

**Comment by hvr** [comment]
@DemiMarie this is indeed planned, thanks for reminding us!

For the record (and because this information is difficult to find): here's how to configure `cabal-install 1.24.0.0`'s `~/.cabal/config` (as usual, trust the keys below at your own discretion...)

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- de-comment line below if hackage.haskell.org is down while bootstrapping
  -- url: http://objects.dreamhost.com/hackage-mirror/
  secure: True
  -- NB: these are still the beta keys -- proper keys will be made available soon
  root-keys: 89e692e45b53b575f79a02f82fe47359b0b577dec23b45d846d6e734ffcc887a
             dc4b6619e8ea2a0b72cad89a3803382f6acc8beda758be51660b5ce7c15e535b
             1035a452fd3ada87956f9e77595cfd5e41446781d7ba9ff9e58b94488ac0bad7
  key-threshold: 2
```

**Comment by dcoutts** [comment]
I've got a patch locally, will make a PR.

**Comment by dcoutts** [comment]
See #3714
