### ISSUE TITLE
Confusing or wrong warning about profiling option -auto-all for executables

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#3718]
I have a package containing executables with the field:

```
  GHC-Prof-Options: -auto-all
```

`cabal check` warns me:

```
* 'ghc-options: -fprof*' profiling flags are typically not appropriate for a
distributed library package. These flags are useful to profile this package,
but when profiling other packages that use this one these flags clutter the
profile output with excessive detail. If you think other packages really want
to see cost centres from this package then use '-fprof-auto-exported' which
puts cost centres only on exported functions. Alternatively, if you want to
use this, make it conditional based on a Cabal configuration flag (with
'manual: True' and 'default: False') and enable that flag during development.
```

I was confused because it talks about GHC-Options, although the problem occurs in a GHC-Prof-Options and it does not mention a line number. It complains about `-fprof*` type flags although I have no flag of this form. I guess that `-auto-all` is an alias for an `-fprof` flag. Then the message talks about other packages that are bothered by my flags. However, I added the flag only to executables. So no other package is affected.
Maybe the warning is still valid, but at least it confuses me.

**Comment by ezyang** [comment]
Sounds like a bug to me. Easy fix would be to mention that it could be ghc-options/ghc-prof-options. Line numbers are harder (would block on refactor @phadej is working on)
