### ISSUE TITLE
cabal install shake reports Downloading/Configuring/Building messages multiple times

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#3721]
When installing, say, Shake, cabal-install will print something like this:

    Downloading shake-0.15.10...
    Downloading shake-0.15.10...
    Configuring shake-0.15.10...
    Configuring shake-0.15.10...
    Building shake-0.15.10...
    Building shake-0.15.10...
    Installed shake-0.15.10
    Installed shake-0.15.10

Here, it would be nice to see that one is the lib, while the other is the executable. Or am I wrong in how I interpret the output?

**Comment by hvr** [comment]
@tuncer just for clarification, is this `cabal install` or `cabal new-build` (or both)?

**Comment by ezyang** [comment]
It's just new-build, since that's the only codepath that understands per-component builds atm.

**Comment by tuncer** [comment]
@hvr `cabal install`.

**Comment by ezyang** [comment]
@tuncer is right, you indeed can see this behavior when you do Shake. But this seems more indicative of some sort of bug rather than an output problem.

**Comment by ezyang** [comment]
And I verified that cabal new-build does output the necessary output:

```
Configuring component test:package-tests from Cabal-1.25.0.0
Configuring component test:unit-tests from Cabal-1.25.0.0
Preprocessing test suite 'unit-tests' for Cabal-1.25.0.0...
Preprocessing test suite 'package-tests' for Cabal-1.25.0.0...
```

**Comment by ezyang** [comment]
Reflecting on this more, I think I know what the problem is (nodeNeighbors is returning duplicates). Let me try to cook something up.

**Comment by ezyang** [comment]
Issue obsoleted by PR #3802
