### ISSUE TITLE
new-build enable haddock

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3724]
Hi, I'm trying to build my (local) dependencies with haddock documentation. I've nuked dist-newstyle and tried

```
cabal new-build --enable-documentation
Resolving dependencies...
In order, the following will be built (use -v for more details):
ltk-0.16.0.0
leksah-server-0.16.1.0
vcsgui-0.2.0.0
leksah-0.16.1.0
ghc-pkg: cannConfiguring ltk-0.16.0.0...
ot create: /home/jacco/projects/leksah/leksah/dist-newstyle/packagedb/ghc-7.10.3 already exists
```

Without the `--enable-documentation` it works fine. What's wrong?

**Comment by 23Skidoo** [comment]
There is a workaround in #3535 that seems to work: https://github.com/haskell/cabal/issues/3535#issuecomment-234411057.

**Comment by ezyang** [comment]
The bug here seems to be more about a parallelism bug for initializing the database that other people have reported. It's fixed in HEAD.
