### ISSUE TITLE
Documentation for release process and website

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3733]
@23Skidoo , when you get a chance, could you add some docs on how our release process works to the README? Especially how the docs at https://www.haskell.org/cabal/users-guide/installing-packages.html get updated, and how to get in contact with people who do have bits.

**Comment by ezyang** [comment]
Some of the info is in #3605

**Comment by 23Skidoo** [comment]
There's https://github.com/haskell/cabal/wiki/Making-a-release.

>  Especially how the docs at https://www.haskell.org/cabal/users-guide/installing-packages.html get updated, and how to get in contact with people who do have bits.

It reflects the state of the docs in the latest released stable version (currently 1.24.0.0). 

If you want write access to haskell.org/cabal, I think we can ask @gbaz or @davean or whoever is responsible to give it to you.

**Comment by davean** [comment]
I can provide sftp access if so desired. I'd need an SSH pub key to do so.

**Comment by ezyang** [comment]
Thanks, I added a pointer to the README. (@davean, thanks for the offer, but I'm not asking for bits, just looking for knowledge :)
