### ISSUE TITLE
Quiet failure on new-build

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3745]
Cabal new-build stopped installing without any error message. After turning on `-v`, I found `Redirecting build log to ...`. After opening the build log I found that `cabal: The program 'alex' version >= 3.0.1 is required but it could not be found`.

Shouldn't this error message be shown directly?

**Comment by ezyang** [comment]
This is fixed in HEAD, give it a try!

**Comment by jaccokrijnen** [comment]
Thanks!
