### ISSUE TITLE
Get rid of world files

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3749]
They were added in 9efcc5b2fa05bf1e3a1b3e3835ce855f30ac154a

They are undocumented.

There are no tests.

Nix-local build will probably simulate worlds using a different mechanism.

Let's get rid of it.

CC @dcoutts

**Comment by 23Skidoo** [comment]
I never use this feature, but the basic idea is that it lets you upgrade to a new GHC version and then run `cabal install world` to reinstall all packages that you previously installed manually. So the question is what is the proposed new mechanism that nix-local-build will use to achieve the same goal.

**Comment by ezyang** [comment]
Well, assuming you have some list of `extra-packages` as your world, if you just change the compiler it will autorebuild everything. See #3737

**Comment by dcoutts** [comment]
Yes I think we can abandon the world stuff in new-build at least, and replace it with some other mechanism to conveniently manage the global environment. I wouldn't bother to get rid of it from the legacy code though.

**Comment by ezyang** [comment]
Issue subsumed by PR #3749.
