### ISSUE TITLE
Adopt a regular bugfix release schedule

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#3755]
We have a regular schedule for major releases, but bugfix releases are made irregularly. This is bad for our users, who may need to wait up to 6 months for their bugfix to make the next major release. I think it also discourages our developers from trying to push bugfixes to release branches because they don't know when, or if, the next bugfix release will be. I propose we adopt a regular schedule for bugfix releases.

The particular schedule I would like to propose is the so-called "Fibonacci" release schedule, which looks like this:
- initial release `x.y.0` (week 0)
- bugfix `x.y.0.1` at + 1 week (week 1)
- bugfix `x.y.0.2` at + 1 week (week 2)
- bugfix `x.y.0.3` at + 2 weeks (week 4)

and so on. If there are no queued patches at a particular checkpoint, just defer that release until the next one. The schedule is intended to reflect that many issues which appear after a new release need only a quick fix, while others take longer to discover. The Fibonacci schedule has been adopted by major projects like the KDE Foundation.

This schedule gives developers short but realistic target dates for getting their patches in and gives users faster feedback on their bug reports.

/cc @rthomas and @23Skidoo, who would bear most of the additional load of this proposal.

**Comment by 23Skidoo** [comment]
If we can use Travis/AppVeyor to automate building of executables, then it should be no problem, though I'd go with two weeks instead of one for x.y.0.1 and x.y.0.2 (unless there's a critical bug).

**Comment by ttuegel** [comment]
> If we can use Travis/AppVeyor to automate building of executables, then it should be no problem, though I'd go with two weeks instead of one for x.y.0.1 and x.y.0.2 (unless there's a critical bug).

Sure. We could even double all the intervals (2, 2, 4, 6, ...) because Cabal moves slowly compared to such a large project as KDE.

**Comment by ezyang** [comment]
Sure! But I'm not a release manager so it isn't extra burden on me :P

To be clear, this is just for cabal-install?

**Comment by ttuegel** [comment]
> To be clear, this is just for cabal-install?

I had intended for both Cabal and cabal-install, as necessary, i.e. I'm assuming we would skip checkpoints if there are no changes to release. I'm sure that our release schedule will be slower than other projects, but I still think it would be good to have well-defined checkpoints where a release occurs if there are any changes.

**Comment by phadej** [comment]
Could have releases for `Cabal` the library as soon as patch lands to stable branch
and the new `cabal-install` binary depending on that version later when its scheduled release is?

@23Skidoo what machines are used to build windows/linux (especially x86) and aix binaries?

**Comment by ezyang** [comment]
Since cabal-install and Cabal are still in an incestuous relationship, it may still make sense to synchronize their release cycles, then.

**Comment by phadej** [comment]
Well, maybe automating the process so we can have releases every 2 weeks is already a win. 

Hopefully after Cabal-2.0 there will be less "major changes", so we could concentrate on polishing the features, not adding them (i.e. so `cabal-install` could move fast in terms of user experience)

**Comment by phadej** [comment]
(FWIW: I don't think every `cabal-install` release needs binaries, as far as you could do `cabal-install install cabal`, and I can get new `cabal` to CI/build machines)

**Comment by ezyang** [comment]
Anyway, I'm happy to give whoever decides to make this happen wide latitude in deciding how the details should work out.

**Comment by 23Skidoo** [comment]
> @23Skidoo what machines are used to build windows/linux (especially x86) and AIX binaries?
EDIT: I guess travis/appveyor won't help with 32bit and AIX builds...

Right now I compile windows/linux (both i386 and x86-64) binaries myself. OS X binary was sent to me by @gbaz, and I got the AIX binary from @hvr.

**Comment by 23Skidoo** [comment]
> FWIW: I don't think every `cabal-install` release needs binaries, as far as you could do `cabal-install install cabal`, and I can get new `cabal` to CI/build machines, I guess getting around x86 and AIX isn't all that easy for many of us (anymore?).

I think it makes sense to adapt a tier-1/tier-2 scheme a-la GCC/GHC: every `cabal-install` release must be accompanied with binaries for Windows/Linux i386/x86-64 and OS X x86-64, while binaries for other platforms are not guaranteed to be up to date.

**Comment by ezyang** [comment]
We still don't have a lead on this, so I'm bumping the milestone to triaged.

**Comment by 23Skidoo** [comment]
As I said above, the main issue blocking this is that the process of producing binaries is not fully automated.

**Comment by ulysses4ever** [comment]
Although interesting, this discussion looks dated. If there’s no plan to organize regular release schedule at the moment, maybe we should close it?

**Comment by Mikolaj** [comment]
Closing. Thank you for the ideas, though.
