### ISSUE TITLE
Package name and user guide documentation

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3756]
The [user guide](https://www.haskell.org/cabal/users-guide/developing-packages.html#kinds-of-package-cabal-vs-ghc-vs-system) says

> Cabal package names can use letters, numbers and hyphens, but not spaces. 

But I cannot create a new package named `reproduce-1234`

**Comment by ezyang** [comment]
Thanks. The specific restriction is that any hyphen separated bit must NOT be all numbers, because then it's ambiguous with version numbers. Want to submit a doc patch?

**Comment by jaccokrijnen** [comment]
Sure, can you point me to the right repo/directory?

**Comment by jaccokrijnen** [comment]
Found it
