### ISSUE TITLE
cabal new-freeze should also capture the package flags of local dependencies

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3760]
In my cabal project file I have some local dependencies (git submodules) which might have different flags set. I'd suppose for the sake of reproducibility it would be good to have the flags taken into account when new freezing.

**Comment by ezyang** [comment]
Sounds reasonable, and not even that difficult, hopefully. (Surprising that this is not what happens already!)

**Comment by jaccokrijnen** [comment]
I think Duncan mentioned he almost fixed this :)

**Comment by jaccokrijnen** [comment]
Duncan fixed it :D

**Comment by 23Skidoo** [comment]
Fixed in #3772.
