### ISSUE TITLE
ghc-pkg fails sometimes after removing dist-newstyle folder

### ISSUE THREAD

**Issue by jaccokrijnen** [haskell/cabal#3764]
After removing `dist-newstyle` I *sometimes* get

    ghc-pkg: cannot create: /home/jacco/projects/leksah/dist-newstyle/packagedb/ghc-8.0.1 already exists

In the verbose output, I see ghc-pkg being called twice as

    /opt/ghc/8.0.1/bin/ghc-pkg init /home/jacco/projects/leksah/dist-newstyle/packagedb/ghc-8.0.1

by two packages being installed interleaved.

I suppose this is a concurrency issue? (I've tried a few times, sometimes this happens, sometimes it builds fine). It only seems to happen if the `dist-newstyle` does not yet exist.

**Comment by ezyang** [comment]
Related #3741. You're using `-j` right? Seems very much like a concurrency issue.

**Comment by ezyang** [comment]
Should have been fixed by https://github.com/haskell/cabal/pull/3509

**Comment by jaccokrijnen** [comment]
By the way, I wasn't running with -j.

**Comment by ezyang** [comment]
Thanks for the note. Could you copy paste the contents of `dist-newstyle/cache/config` into this ticket?

**Comment by jaccokrijnen** [comment]
http://lpaste.net/183531

**Comment by ezyang** [comment]
`jobs: $ncpus`: I rest my case! (Probably coming from `~/.cabal/config`. Or maybe it's the default?!)

**Comment by jaccokrijnen** [comment]
I think it's the default yes, I've never edited ~/.cabal/config manually ([here](http://lpaste.net/183612))
