### ISSUE TITLE
We should sanity check GenericPackageDescriptions created by the solver DSL before we ship it to the solver

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3784]
While adding executable support to the solver DSL in #3783, I forgot to add executables to the condExecutables subtree of the generic package description. This lead to considerable head-scratching when I was unable to reproduce the error.

There were two ways this could have been easier to debug:
1. If there was some way to print out the GPD output by the DSL, I could have just printed them out and understood the problem immediately (no executable sections.)
2. If there was some sort of sanity check on the GPD, it would have realized that the ComponentDeps recorded dependencies for an executable which wasn't anywhere in the tree.

This doesn't seem like a pants on fire problem but it would be good to fix eventually. Maybe if it bites me again! (CC @grayjay)

**Comment by grayjay** [comment]
Was the GPD invalid, or was it just inconsistent with the `DSL.ExampleAvailable`?

**Comment by ezyang** [comment]
I am not sure (because I didn't know how to print it); but I think it was invalid because the condition tree should have contained some dependencies were not in the actual BuildInfo.

**Comment by grayjay** [comment]
6dc05349888fc234e4fb3771271cfc050d04883a runs package checks on the GenericPackageDescription produced by the solver DSL.
