### ISSUE TITLE
Don't build setup/executable dependencies with profiling, if profiling library needed

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3789]
It's pointless and a waste of time.

Steps to reproduce: `--enable-profiling` on a package with a dependency which has a Custom setup that requires an old version of Cabal.

**Comment by dcoutts** [comment]
Yep, should be a matter of adjusting the logic in ProjectPlanning so it only looks at lib deps not all deps when working out which packages are affected when a local package has profiling enabled.
