### ISSUE TITLE
cabal sdist seems to ignore the --builddir option when Build-Type for a package is Custom

### ISSUE THREAD

**Issue by stepcut** [haskell/cabal#3794]
I am trying to run `cabal sdist` in a directory for which I do not have write permissions.

If the `Build-Type` in the `.cabal` file is `Simple` then it is sufficient to use `--output-directory` to create the output somewhere I do have write permissions.

If the `Build-Type` is `Custom`, then `cabal sdist` will attempt to build the `Setup.hs`. However, it will fail because it can not write to the `dist` directory. I would imagine that the `--builddir` option would fix that issue -- but it still fails.

```
 $ cabal sdist --builddir=/private/var/folders/_b/wj7ns2190gd3hbz9w0f3m17c0000gn/T/nix-build-cabalsdist.drv-0 --output-directory /nix/store/8li5jw9wbkndvdlpbhi5wzw2x5wynjr8-cabalsdist 
creating /nix/store/8li5jw9wbkndvdlpbhi5wzw2x5wynjr8-cabalsdist
creating dist/setup
creating dist
cabal: dist: permission denied
```

**Comment by ezyang** [comment]
It appears that the way this code path works is we always override the passed in `--builddir` with the build directory we try to infer from the saved config. But if you run `cabal sdist` without having configured, there won't be any valid setting and so it will go to the default.

```
sdistAction :: (SDistFlags, SDistExFlags) -> [String] -> Action
sdistAction (sdistFlags, sdistExFlags) extraArgs globalFlags = do
  unless (null extraArgs) $
    die $ "'sdist' doesn't take any extra arguments: " ++ unwords extraArgs
  let verbosity = fromFlag (sDistVerbosity sdistFlags)
  load <- try (loadConfigOrSandboxConfig verbosity globalFlags)
  let config = either (\(SomeException _) -> mempty) snd load
  distPref <- findSavedDistPref config (sDistDistPref sdistFlags)
  let sdistFlags' = sdistFlags { sDistDistPref = toFlag distPref }
  sdist sdistFlags' sdistExFlags
```

I don't have the foggiest what the intended semantics are. @ttuegel who has been working on how configure works may be able to work. IMO, the way all this works is incredibly dodgy, and maybe the best approach is to way for `new-sdist` which will use the new cabal new-build codepath.

**Comment by stepcut** [comment]
I can wait for new-sdist.

**Comment by 23Skidoo** [comment]
`findSavedDistPref` was introduced by @ttuegel in 2b3282fceed02685bd0b63fb3538fa4ada4ea347. The idea was to allow specifying `builddir` via command-line, `CABAL_BUILDDIR` or the config file, in this order of preference.

Now I don't see what this has to do with having configured or not, since `findSavedDistPref` doesn't look at LBI at all (and it can't, since you must know the dist pref to load it).

**Comment by ezyang** [comment]
OK, maybe I misdiagnosed, then.

**Comment by 23Skidoo** [comment]
> ```
creating dist/setup
creating dist
cabal: dist: permission denied
```
From this I infer that the actual problem is that we're not passing `--builddir` correctly to the setup wrapper code via `SetupScriptOptions.useDistPref`.

**Comment by 23Skidoo** [comment]
And indeed:

```
    setupOpts       = defaultSetupScriptOptions {
      -- The '--output-directory' sdist flag was introduced in Cabal 1.12, and
      -- '--list-sources' in 1.17.
      useCabalVersion = if isListSources
                        then orLaterVersion $ Version [1,17,0] []
                        else orLaterVersion $ Version [1,12,0] []
      }
```

**Comment by ezyang** [comment]
Subsumed by PR #3794.
