### ISSUE TITLE
cabal sandbox add-source directory-name not working

### ISSUE THREAD

**Issue by p75213** [haskell/cabal#3800]
The command `cabal sandbox add-source ..\folder` is not working. When I issue the command `cabal sandbox hc-pkg list` it shows (no packages) for the local sandbox. If I issue the command: `cabal install --only-dependencies` it shows the following message: 

> All the requested packages are already installed:
> Use --reinstall if you want to reinstall anyway.

I am using cabal version 1.24.0.0 on windows 7.

**Comment by 23Skidoo** [comment]
Does your `.cabal` file include a dependency on the package in `..\folder`?

**Comment by ezyang** [comment]
Just a friendly note: try out http://cabal.readthedocs.io/en/latest/nix-local-build-overview.html instead of sandboxes! You'll be pleasantly surprised.

**Comment by p75213** [comment]
Well I tried it again this morning and it worked. I haven't changed anything so I am at a loss to what was going on. Anyway all good now.
@ezyang  Thanks for that. I will read it as soon as I get time.

**Comment by ezyang** [comment]
OK, I'll close this for now. Reopen if you see it again!
