### ISSUE TITLE
Use full $libname in default build-log filename template

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3807]
filename templates are used in flags like

```
    --build-log=TEMPLATE             Log all builds to file (name template can
                                     use $pkgid, $compiler, $os, $arch)
    --remote-build-reporting=LEVEL   Generate build reports to send to a remote
                                     server (none, anonymous or detailed).
```

Currently, `$pkgid` expands to the source pkg id, rather than the installed package id (which contains a hash), E.g. for a package that gets registered as

    text-1.2.2.1-17eefdbf4d895ce3e9c215902aa9044702b477e7a262f7ceca1a1ee04bcd34ec

the flag `--build-log='log/$pkgid.log'` expands to `"log/text-1.2.2.1.log"`, which results in build logs overwriting each (which happens quite frequently with nix-local-build).

One way to address this is to 

 - introduce a new interpolation variable `$unitid` (or `$ipkgid`) to hold the full package-id, and
 - change the default templates prone to name-clashes to use this new variable
   ( e.g. `~/.cabal/logs/$unitid.log` )

/cc @ezyang @dcoutts 

PS: For consistency with `~/.cabal/store/$compiler/...` I'd suggest we switch the default log location to  `~/.cabal/logs/$compiler/$unitid.log` as that would also avoid name-clashing for cases where the hash was left off for ghc boot packages, as well as allow to delete old logs for a specific compiler version more conveniently.

**Comment by ezyang** [comment]
We already have the poorly named `$libname` which outputs the unit id. So it's more a matter of changing the default log locations.
