### ISSUE TITLE
cabal new-build not producing cabal-install bits

### ISSUE THREAD

**Issue by omefire** [haskell/cabal#3821]
After runing ```cabal new-build cabal-install```, I don't get the bits for cabal-install, I only get those for Cabal.
Is there something I'm missing ?

```
omefire@omefire-ubuntu:~/Projects/cabal$ ls dist-newstyle/build/
Cabal-1.25.0.0  hackage-security-0.5.2.2
```

**Comment by ezyang** [comment]
Is this cabal-install-1.24? In HEAD, when I run `cabal new-build cabal-install -v` the executable for cabal-install shows up in the build plan. On 1.24, it's possible that the parallel build errored building cabal-install but swallowed the message. This bug is fixed on HEAD.

**Comment by omefire** [comment]
That was with cabal-install-1.25 (from master).
I just pulled again and am currently running another build, I'll report the results here.

**Comment by omefire** [comment]
Doing a fresh pull solved this issue. don't know why it wasn't working before, maybe a recent commit fixed things? 
Closing this bug as a result.
