### ISSUE TITLE
Revise forward/backward compatiblity window for Cabal versions >= 2

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3838]
Our policy regarding `Cabal` appears to be

> Our GHC support window is three years: that is, the Cabal library must be buildable out-of-the-box with the dependencies that shipped with GHC for at least three years.

However, given that `Cabal` is a special case to `cabal` for custom build-type packages, this compatibility window is too short and results in artificial constraints for install solving. So we should strive to support wide compatibility windows as long as possible in a best effort way, specifically we shouldn't drop support for older GHCs just for mere convenience if there's no well motivated technical reason for doing so.

Quoting @dcoutts from #3833:

> There may be a good argument now for us reconsidering and expanding our support window. With the advent of setup-deps we can have a packages that need older versions of Cabal, and conversely using a new cabal-install with an older ghc may sill involve using packages that require a more recent Cabal. 
>
> So we may have to expand our support window in both directions: point releases of older Cabal to work with newer ghc, and keeping latest Cabal building with older ghc.

**Comment by ezyang** [comment]
I'm OK with expanding the window, sticking to GHC 7.4 hasn't caused problems for me.

**Comment by ttuegel** [comment]
I have no opinion on the compatibility policy for Cabal. For cabal-install, I favor keeping the current policy; the proposed policy is very restrictive. If we expand the policy for Cabal while keeping the policy the same for cabal-install, that would complicate our CI setup. I think we would need to consider separating the repositories again.

**Comment by ttuegel** [comment]
One more thing: I strongly object to any policy that includes soft limits ("best effort") for backwards compatibility. Users need to know exactly what they can expect. Our policy should be absolutely rigid.

**Comment by dcoutts** [comment]
@ttuegel I agree about the best effort thing, though I'm guilty of taking that approach in the past.

As for cabal-install's compat vs Cabal, it's quite true that we don't need such wide compatibility for building cabal-install with lots of GHC versions as we might for Cabal. So indeed we would have to look at the CI. I'd prefer not to split the repos however. Wouldn't it "just" be a case of omitting the cabal-install part of the build for certain ghc versions? @hvr how tricky would it be?

**Comment by ezyang** [comment]
That would be easy.

**Comment by 23Skidoo** [comment]
I'm on this.

**Comment by BardurArantsson** [comment]
If ya'll'lll pardon a dumb question... Why is the policy here time-based rather than on number of major releases?

**Comment by ezyang** [comment]
No good reason. Atm it's a major release a year, so I arbitrarily picked years as the postage.

**Comment by 23Skidoo** [comment]
If a major release is still getting updates after 1-2 years its support window gets automatically extended when the policy is time-based.
