### ISSUE TITLE
RFC: Add a --sign-pgp to `cabal upload`

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3845]
It would be great to be able to attach key-info and a signature of a tarball.

I guess this can be done in steps, even `hackage-server` doesn't do anything yet with this information.

**Comment by phadej** [comment]
ping @hvr, @dcoutts

**Comment by hvr** [comment]
@phadej  well, later phases of hackage-security would provide package signing... we should figure out how this integrates with TUF. Ending up with two orthogonal signing schemes/codepaths would be undesirable.

**Comment by phadej** [comment]
Alternatively `cabal` could integrate with https://www.fpcomplete.com/blog/2016/05/stack-security-gnupg-keys ?

**Comment by hvr** [comment]
@phadej no, because afaics, the Stack approach doesn't care about the details I pointed out

**Comment by phadej** [comment]
which details?

**Comment by hvr** [comment]
@phadej proper integration with hackage-security/TUF & ed25519

**Comment by phadej** [comment]
I don't see why it *should* integrate with hackage-security/TUF. It's an orthogonal approach, and IMHO having one doesn't harm. Also personally I'd depend on `gpg` to generate key anyway, so the dependency isn't a problem to package uploader.

I'm not proposing that `cabal-install` should do anything with this signatures at this point, I'm actually not sure whether `stack` does either. But it would be beneficial to upload signatures, so the authors using `cabal` doesn't need to use `sig-tool` if/when `stack` starts to verify them.

**Comment by hvr** [comment]
why should we implement two redundant signature schemes?

**Comment by phadej** [comment]
Well, maybe we don't need, but is there an outline for hackage-security author signing so an outsider (like me) could contribute to it? There is no visible plan or progress, thus this redundant proposal.

GPG signing, and uploading signatures to the predefined place is quite straightforward to implement. I see in [1] that author signing was actually implemented once already by Nikita, but the link is dead, so cannot see when.

- [1] http://www.well-typed.com/blog/2015/04/improving-hackage-security/

**Comment by hvr** [comment]
Based on the previous IRC `#hackage` conversation, here's relevant additional material:

 - [HIW 2015 Video: Securing Our Package Infrastructure](https://www.youtube.com/watch?v=D9juHHlnayI)
 - https://wiki.haskell.org/wikiupload/a/af/HackageSecurity.pdf  
 - https://github.com/well-typed/hackage-security#readme

**Comment by phadej** [comment]
Doesn't look like this will happen.
