### ISSUE TITLE
Code review process discussion

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3848]
Sometimes I do things in code review, and I wonder if people understand my intentions. The goal of this post is to clarify what I mean when I do certain things in code review, and put us towards a set of guidelines/boilerplate text we can direct contributors to so that they know what they should "do next".

When someone submits a PR, I look at it and I make a judgment:
1. Does the patch have major correctness problems or design problems? If so, I'll **comment and request changes.** This doesn't mean the patch can't get merged, but I would only want to merge a patch with correctness/design problems in exceptional situations: e.g., it (partially) fixes a major bug that has no workaround. I'm less sympathetic to problem patches for bugs for which there exist effective workarounds, or added features which have not been prioritized for the next feature release.
2. Is the patch basically OK, and solves a useful problem, but there are some little niggles which need to be fixed? In that case, I will **comment but approve changes.** In this situation, I am telling the patch author to make a judgment call: are the minor changes major enough to warrant fixing and doing another cycle in the CR process? If they don't think so, it is OK for them to push. The comments I make here, I try to ensure that they are real, substantive comments which would help out other developers: e.g., requests for documentation, clarifying remarks, introduction of code which could be hazardous in the future, if some other disconnected pieces change.
3. Is the patch so good? Then I'll approve, wait a few days, and then merge it.

How does this sound? How do you CR? Do you do certain things differently?

**Comment by ulysses4ever** [comment]
Good points. Remind me of: http://neilmitchell.blogspot.com/2019/04/code-review-approve-with-suggestions.html

That said, maybe it’s time to close this?

**Comment by Mikolaj** [comment]
Yes, I think we follow in @ezyang's footsteps and review in that spirit (with extra features re changelogs and tests, etc.). Closing as completed. :)
