### ISSUE TITLE
Travis does not actually check GHC compatibility out-of-the-box

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#3885]
Our CI script is not testing Cabal's GHC compatibility correctly. The stated policy is that Cabal must build "out-of-the-box" with GHC versions in our support window. The build script tests building Cabal with cabal-install, which is not available out-of-the-box. I discovered this today because our current use of `default-extensions` in `Cabal.cabal` makes it impossible(!!!) to `runghc Setup.hs ...` for Cabal.

Attn. @23Skidoo @ezyang

**Comment by 23Skidoo** [comment]
I think @hvr has just fixed this.

**Comment by ttuegel** [comment]
I see that now, thanks!

**Comment by ttuegel** [comment]
@ezyang Are there checks on Travis to stop this happening again?

**Comment by ezyang** [comment]
@ttuegel The https://github.com/haskell/cabal/blob/master/travis-bootstrap.sh script is supposed to test that `./bootstrap.sh` works. But it would seem that this script uses Setup (from a system Cabal) to build Cabal, thus sidestepping the issue. I guess we should add another bootstrap test.
