### ISSUE TITLE
Provide a way to force a reconfigure for new-build

### ISSUE THREAD

**Issue by glguy** [haskell/cabal#3886]
Currently there is no way to force a "configure" phase to be redone.

cc @ezyang 

```
#haskell - Sept 22, 2016
10:02 glguy           : Can I tell cabal new-build it needs to reconfigure? 
10:02 ezyang          : glguy: delete the cache dir :(                      
10:02 glguy           : OK, thanks                                          
10:03 ezyang          : file a bug too please                               
```

**Comment by dcoutts** [comment]
@glguy can you file a report with the original bug? We'd rather make reconfiguring automatic than have users need to know to blow everything away from time to time. What had changed that required a reconfigure (but wasn't triggering one)?

**Comment by glguy** [comment]
I'm developing a package to be used as a dependency of my Setup.hs which is listed in my custom-setup component. I changed the package (it's listed in my cabal.project) and I wanted to force my Setup.hs configure phase to run again. Should configuration have automatically happened there?

**Comment by ezyang** [comment]
See also https://github.com/haskell/cabal/issues/3020

**Comment by ezyang** [comment]
For what it's worth, I think sometimes cabal new-build *will* make a mistake (for whatever reason; maybe a user didn't write enough files into the Cabal file, or maybe there's a bug in new-build) in which case a way of forcing a rebuild is useful, in much the same way `-fforce-recomp` is a useful flag for GHC. So it does seem to me that this is an important feature to offer in some way. Don't know the correct UI though.

**Comment by phadej** [comment]
I'm closing this issue as wontfix. in `v2-build` paradigm configuring packages is something one doesn't even know about. The underlying bug #3020 is valid, and need to be fixed, but having some kind of `force-reconfigure` should be motivated better. I don't see how it can save considerable work, compared to removing `dist-newstyle`.

**Comment by andreasabel** [comment]
I would think that a flag to force recompilation would be nice to have, just like there is `-B` for `make` and the above-mentioned flag for GHC.  It would be useful to get a list of all the warnings again.  Of course, there is a design issue here; one would likely not want to rebuild all the dependencies; only the current package.

**Comment by ParetoOptimalDev** [comment]
Here's a concrete real-world use-case:

While looking into [compile time quadratic in number of routes, with -O2 #986](https://github.com/haskell-servant/servant/issues/986) I wanted to run a git bisect script on the Servant codebase to find the commit that changed the compile time.

I added `cookbook-many-routes` and added it to cabal.project. Then tried running cabal build twice and expected it to recompile each time and give me an accurate answer to "how long did this take to compile":

```
$ cabal new-build --ghc-option="-fforce-recomp" -O2 cookbook-many-routes
--- snip compilation output --
$ cabal new-build --ghc-option="-fforce-recomp" -O2 cookbook-many-routes
Up to date
```

Then if I had that "how long did this commit hash take to compile" I could have put in my bisect script "fail if it took more than 25s" to find the commit where compile times changed.

**Comment by Mikolaj** [comment]
Why is `cabal clean` not good enough in this case?

**Comment by ParetoOptimalDev** [comment]
> Why is `cabal clean` not good enough in this case?

Because then the rest of servant needs to be recompiled and not just the component `many-routes` I'm interested in the compile time of.

I do still get a coarser number that's still somewhat useful, but I'm testing across ghc versions and the extra noise of recompiling modules I'm not timing undermines my confidence quite a bit.

**Comment by Mikolaj** [comment]
I see. Perhaps `cabal clean` should take component as argument?

**Comment by jneira** [comment]
> I see. Perhaps `cabal clean` should take component as argument?

like requested in https://github.com/haskell/cabal/issues/7506
