### ISSUE TITLE
cabal new-repl does not handle SIGINT correctly

### ISSUE THREAD

**Issue by arianvp** [haskell/cabal#3899]
In the old cabal repl you could cancel your input with SIGINT like this:

```
Prelude> 5 <CTRL+C>  
Prelude> 
```

and it would cancel the input and give you a new prelude line

in `cabal new-repl`  It immediatelly crashes the repl and then produces the following error:

```
*Generics.SOP.Record
λ> 5 
*Generics.SOP.Record
λ> 
╭─arian@laptop  ~/Projects/records-sop  ‹master*› 
╰─$                                                                               130 ↵

<stdin>: hGetChar: hardware fault (Input/output error) 
```

```
╰─$ cabal --version                                                                 1 ↵
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
```

**Comment by arianvp** [comment]
Reproducible on Ubuntu and Arch Linux

**Comment by arianvp** [comment]
Also reproducible in Cabal HEAD

**Comment by ezyang** [comment]
I milestoned this for 2.0, and not 1.24 bugfix, but it's possible we could backport the patch. Update the milestones on this and the PR accordingly if so.
