### ISSUE TITLE
make cabal --cabal-lib-version="" take a dependency or a specific number

### ISSUE THREAD

**Issue by bos** [haskell/cabal#390]
(Imported from [Trac #397](http://hackage.haskell.org/trac/hackage/ticket/397), reported by @dcoutts on 2008-11-08)

The <tt>--cabal-lib-version=</tt> flag currently takes a specific version number. It could easily be like <tt>--constraint=</tt> or like <tt>cabal install "foo &lt; 2"</tt> and take a dependency or a specific version number.

**Comment by BardurArantsson** [comment]
Obsolete (last comment 2008.). Please close.
