### ISSUE TITLE
better support for static linking

### ISSUE THREAD

**Issue by bos** [haskell/cabal#391]
(Imported from [Trac #398](http://hackage.haskell.org/trac/hackage/ticket/398), reported by @dcoutts on 2008-11-08)

Generating statically linked binaries on different platforms requires a bit of knowledge about what flags to pass to ghc. It would be nice to just be able to <tt>cabal configure --enable-static-executable</tt> or something and have that pass the extra <tt>-optl-static</tt> and whatever ghc options are required.

If it's not possible to generate static binaries it should make some attempt at explaining why.

**Comment by filib** [comment]
+1

**Comment by nh2** [comment]
I'm giving a shot at this now.

**Comment by nh2** [comment]
> I'm giving a shot at this now.

OK done.
