### ISSUE TITLE
Asserts enabled with new-build cause performance regression

### ISSUE THREAD

**Issue by alanz** [haskell/cabal#3911]
Testing new-configure times against https://github.com/alanz/haskell-ide-engine master (165b98d6be0d248b735033219b7e67b84539e062)

With a standard ~/cabal/config, generated by cabal 1.24.0.0. from hackage, and with the following security setup, with `secure: False`

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  secure: False
  -- secure: True
  -- root-keys:
  root-keys: 
     fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0,
     1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42,
     2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3,
     0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d,
     51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
    
  -- key-threshold:
  key-threshold: 3
```

 I have

Repeat

    rm -fr dist-newstlye
    cabal new-configure

Until there are no downloads

Then

    rm -fr dist-newstyle
    time cabal new-configure

This gives a plan, and says

    real	0m5.924s
    user	0m5.684s
    sys	0m0.248s

Then, using current master (bb2026c4dd6238338cfbcc4a34e3fa1f6868dc13), and flipping
`secure: True`,

    cabal-1.25 update
    rm -fr dist-newstyle
    cabal-1.25 new-configure

Once things stabilise

    rm -fr dist-newstyle
    time cabal-1.25 new-configure

Gives

    real	0m21.058s
    user	0m20.852s
    sys	0m0.188s

**Comment by alanz** [comment]
I just set `secure: False`, and did

    cabal-1.25 update
    rm -fr dist-newstyle
    cabal-1.25 new-configure
    # Downloads a bunch of stuff
    rm -fr dist-newstyle
    time cabal-1.25 new-configure

And I get

    real	0m20.788s
    user	0m20.596s
    sys	0m0.180s

So the security stuff does not seem to make an appreciable difference

**Comment by hvr** [comment]
Especially this one here in `cabal.project` is evil:

```
program-options
  -- So us hackers get all the assertion failures early:
  ghc-options: -fno-ignore-asserts
```

as it applies to *all* of cabal's deps

**Comment by ezyang** [comment]
@alanz With @hvr's commit did the performance go back to something reasonable?

**Comment by alanz** [comment]
Yes

**Comment by ezyang** [comment]
OK, I'll go ahead and close this.
