### ISSUE TITLE
new-repl sometimes fails in mysterious ways

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3916]
So I did this:

```
$ cabal get bloodhound
$ cd bloodhound-0.11.1.0 
$ cabal new-repl
```

And I got this result:

```
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - bloodhound-0.11.1.0 (first run)
[1 of 1] Compiling Main             ( /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/setup.hs, /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/Main.o )
Linking /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/setup ...
Configuring bloodhound-0.11.1.0...
setup: '/opt/ghc/8.0.2/bin/ghc' exited with an error:
<command line>: Failed to load interface for ‘Database.Bloodhound’
It is a member of the hidden package ‘bloodhound-0.11.1.0’.
Perhaps you need to add ‘bloodhound’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘bloodhound-0.11.0.0’.
Perhaps you need to add ‘bloodhound’ to the build-depends in your .cabal file.
Use -v to see a list of the files searched for.
cabal: Failed to build bloodhound-0.11.1.0. The failure occurred during the
final install step.
```
I tried changing the `build-type` to `Simple` in `bloodhound.cabal`, but that didn't help either:
```
$ cabal new-repl        
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - bloodhound-0.11.1.0 (lib) (first run)
Configuring component lib from bloodhound-0.11.1.0
cabal: '/opt/ghc/8.0.2/bin/ghc' exited with an error:
<command line>: Failed to load interface for ‘Database.Bloodhound’
Use -v to see a list of the files searched for.
cabal: Failed to build bloodhound-0.11.1.0. The failure occurred during the
final install step.
```
`new-build` seems to work, however, as well as `new-repl` on packages that depend on `bloodhound` (e.g. `log`).

**edit:**  I'm not sure what I did, but the issue has now disappeared. Maybe the package DB was in an inconsistent state and running `new-repl` and/or `new-build` on `log` fixed it. Leaving this open for now as a FYI for @dcoutts.

**Comment by ezyang** [comment]
In the future, a `-v` log when it fails like this would be very helpful. In particular, I would have quite liked to see what the command line invocation of ghc was. I suppose the contents of the package databases passed to GHC would have also been helpful. I remilestoned this as _|_ since it will be pretty difficult to debug without a reproducing test case. Maybe we put this down as general robustness improvements to unexpected file system states.

**Comment by ezyang** [comment]
Actually, I was able to reproduce following the instructions.

**Comment by ezyang** [comment]
According to the logs, this is because the Setup script is attempting to compute the ABI hash for bloodhound, but we never built it so obviously this will fail.

**Comment by ezyang** [comment]
OK, so the bug is in ProjectBuilding: the logic for when we register a package (before repl'ing) is by looking at the build status. If we have never successfully built the package, it will unconditionally register, even if a build did not take place. I *guess* we can fix this by not registering unless a build took place? @dcoutts any opinion?

**Comment by ezyang** [comment]
Confirmed that #3919 fixes this particular problem. But whether or not it's the "right" thing to do is a different matter.

**Comment by dcoutts** [comment]
I've seen this bug too and I agree with the cause. As for the fix, I'm not so sure. I had assumed I would fix this by just checking if we were going to repl the thing or not, and not registering if that's the case, but I now see it's more complicated. Will comment in #3919.

**Comment by 23Skidoo** [comment]
> In the future, a `-v` log when it fails like this would be very helpful.

Sorry for not including it. As I said, the issue mysteriously disappeared after some poking around.
