### ISSUE TITLE
RFC: reconsider build-type:custom for cabal-install

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3922]
Currently, `build-type:custom` forces building executable & test components in `cabal-install` to be serialised.

On an Intel Core i7-3770/3.4GHz a full build (i.e. after `rm -rf dist-newstyle`) via `cabal new-build --enable-tests` takes

```
real    8m43.765s
user    8m55.672s
sys 0m8.896s
```

Whereas, when manually changing `build-type:custom` into `build-type:simple`, such a full build takes notably less time to complete:

```
real    4m57.386s
user    9m53.852s
sys 0m10.000s
```

From my POV, there's at least 3 options:
1. do nothing, leave things as is
2. figure out a way to retain component-build parallelism even with `build-type:custom`
3. modify `cabal-install.cabal` to use simple build-type (we use `Setup.hs` only for the purpose of generating a man-page)

**Comment by ezyang** [comment]
I support cabal-install not being a Custom build type. But I'll note that the intention was always to get component-build parallelism with Custom; I just didn't implement it because I didn't feel like fiddling with ProjectBuilding to teach it how to build "a custom setup", and SetupWrapper to teach it how to invoke a specific, pre-built executable.

**Comment by hvr** [comment]
Also note that the only reason we have a `Setup.hs` file for `cabal-install` is to generate and install the `cabal.1` man-page; are there any `cabal` users who benefit from this?

**Comment by ezyang** [comment]
Yeah, I'd say distro packagers, but I also agree with what you say.

**Comment by 23Skidoo** [comment]
I'm +1 on this, but I think that distro packagers won't know about `cabal manpage`, so I suggest that we put a pre-generated manpage into `data-files` and add a CI check that it is up to date.

**Comment by hvr** [comment]
@23Skidoo I think that `extra-source-files` might be better, as packages typically pay attention to what's in the top-level source-tree, and that's where you often find pre-rendered man-pages

**Comment by phadej** [comment]
cabal-install is now build-type: Simple
