### ISSUE TITLE
Unicode filepaths on Window cause linking to fail

### ISSUE THREAD

**Issue by leshabirukov** [haskell/cabal#3926]
[cabal_log.txt](https://github.com/haskell/cabal/files/504861/cabal_log.txt)
Windows 10 (and 7, if memory serves)
I cannot install nor Agda neither Idris, because of similar issues with distinct packages, getting like:
`...`
`  C:/Program Files/Haskell Platform/8.0.1/mingw/bin/ld.exe: `
` cannot find -lHSpolyparse-1.12-FkXEOA8o2Io9i7TJcmDT44`
`  ...`
`  collect2.exe: error: ld returned 1 exit status`
`  ...`
`  cabal: Error: some packages failed to install:`
`  cpphs-1.20.2 failed during the building phase. The exception was:`
`  ExitFailure 1` 
"cabal install cpphs -v3 " attached (cpphs required for agda, idris wants cheapskate)
I have tried to exclude all unrelevant directories from PATH. (I have another mingw/cygwin on disk)
I think this [link1](http://stackoverflow.com/questions/38134118/ld-exe-cant-find-libraries-during-cabal-install-haskell-platform) and this [link2](https://vk.com/wall-96836518_93?reply=96) reference the same problem, may be the cause is Russian letters in the "C:\Users\Алексей\AppData\Roaming\cabal"

**Comment by ezyang** [comment]
If you make a new user without any Russian letters and do an install there, does that successfully link?

**Comment by leshabirukov** [comment]
Yes, with user "dummy" agda installed succesfuly. Idris still have problems, but it may be another issue, log 
[idris_fail.txt](https://github.com/haskell/cabal/files/504942/idris_fail.txt)
[idris_fail_v3.txt](https://github.com/haskell/cabal/files/504943/idris_fail_v3.txt)

attached anyway. 
I will try to make same steps with new Russian -named user.

**Comment by leshabirukov** [comment]
Confirmed, same actions but with Russian user name lead to cpphs package installation fail.

**Comment by 23Skidoo** [comment]
IIRC we already have an issue for unicode username problems.

**Comment by ezyang** [comment]
Re Idris failure, the Setup script is calling "make -C rts clean" which is failing because there is no  program named make. I guess maybe `pacman -S make` should fix it?

**Comment by leshabirukov** [comment]
Installing "make" helps, though i did it using GNU installer, not sure that "pacman" suitable for windows.
Thank's a lot!
But is there a way to use Agda and Idris without switching user? May be a way to move "cabal\roaming" folder?

**Comment by 23Skidoo** [comment]
`pacman` comes with `msys2`.

**Comment by leshabirukov** [comment]
Haskell platform brings `msys`, that one whithout `pacman`

**Comment by 23Skidoo** [comment]
Maybe it's simply not in PATH or maybe HP uses a stripped-down version of MSYS.

**Comment by leshabirukov** [comment]
Well, I had this `make` issue on fresh HP, and new user account, so I suppose this problem is universal. Is it worth to create an issue, and should it be here?

**Comment by 23Skidoo** [comment]
@leshabirukov For the `make` issue I suggest filing a ticket on the HP bug tracker: https://github.com/haskell/haskell-platform/issues/new

**Comment by 23Skidoo** [comment]
Closing as a duplicate of https://github.com/haskell/haskell-platform/issues/258 and https://github.com/haskell/cabal/issues/650.
