### ISSUE TITLE
fail and warnings for build configurations

### ISSUE THREAD

**Issue by bos** [haskell/cabal#393]
(Imported from [Trac #400](http://hackage.haskell.org/trac/hackage/ticket/400), reported by @dcoutts on 2008-11-08)

People expect <tt>buildable: False</tt> to fail the current configuration (rather than letting it configure and then not working at build time). But perhaps we should make that more explicit and allow a message, eg instead of:

<pre class="wiki">if os(windows)
  buildable: False
</pre>allow

<pre class="wiki">if os(windows)
  fail: it doesn't work on windows because, blah blah blah
</pre>And similarly we might want to warn users about selecting particular configurations eg:

<pre class="wiki">if flag(http)
  ...
else
  warn: no http implementation selected, only local
        operations will be possible. You probably really
        want some http implementation.
</pre>The semantics roughly is that it's a workable but sub-optimal configuration.

The solver should try to avoid warnings, by selecting another alternative.

**Comment by grayjay** [comment]
Closing in favor of #3072, which has more comments.
