### ISSUE TITLE
Strange OS X failures on Travis with GHC 7.8.4

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3938]
Our CI recently started failing on OS X with GHC 7.8.4. There's a large number of permissions failures, all of them looking like this:

```
    Command /Users/travis/build/haskell/cabal/Cabal/tests/Setup configure -v --distdir dist-test/./dist --global --with-ghc /Users/travis/.ghc-install/7.8.4/bin/ghc --disable-optimization '--prefix=/Users/travis/build/haskell/cabal/Cabal/tests/PackageTests/BenchmarkStanza/dist-test/usr' '--package-db=clear' '--package-db=global' '--package-db=user' '--package-db=/Users/travis/build/haskell/cabal/dist-newstyle/build/Cabal-1.25.0.0/package.conf.inplace' failed.
    Output:
    Warning: my.cabal: A package using section syntax must specify at least
    'cabal-version: >= 1.2'.
    Configuring BenchmarkStanza-0.1...
    Dependency base -any: using base-4.7.0.2
    Setup: /usr/bin/ar: permission denied
```

The problem is probably not on our side, but this is still annoying, since it keeps happening.

/cc @phadej

**Comment by 23Skidoo** [comment]
The first failing commit was https://github.com/haskell/cabal/commit/c6929fc334d1aad1fbb9867f1828060b3cf760f2, which passed when it was a PR: https://github.com/haskell/cabal/pull/3929.

**Comment by ezyang** [comment]
I think that commit is pretty unlikely to be causing the failure? What is more likely the culprit is Travis's update to the OS X image: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

**Comment by ezyang** [comment]
See also #2653.

**Comment by ezyang** [comment]
Which suggests that if we add `constraint: unix>=2.7.1.0` that should solve the problem... except that we need our bootstrapping cabal to be updated :(

**Comment by 23Skidoo** [comment]
>  except that we need our bootstrapping cabal to be updated :(

Hmm, I thought [the one we were using](https://www.haskell.org/cabal/release/cabal-install-1.24.0.0/cabal-install-1.24.0.0-x86_64-apple-darwin-yosemite.tar.gz) had this bug fixed.
