### ISSUE TITLE
new-build copy/register race condition

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3946]
Presently, copying and registering a package is done in two steps. However, once the store directory has been created, subsequent invocations of new-build will assume the package has been installed, even if it isn't registered in the package database. Thus, there is a potential race condition where the directory is created, but the package is not registered.

Unsure about severity.

**Comment by dcoutts** [comment]
See the issue about locking in the store #3741. This issue is covered there I think.

**Comment by ezyang** [comment]
Not directly in the original description, I think, but we can consolidate there.
