### ISSUE TITLE
Add Stack-based CI

### ISSUE THREAD

**Issue by quchen** [haskell/cabal#3951]
I think Cabal and Stack should be buildable with each other, but since #3949 was not detected by CI, there seems to be no CI test for building Cabal with Stack.

**Comment by 23Skidoo** [comment]
Patches welcome! If you do this, please use a separate matrix entry for Stack.

**Comment by hvr** [comment]
Generally a good idea! But it ought to be marked as `allow_failures`

**Comment by quchen** [comment]
I can’t assign myself, but I’ll try working on it later.

**Comment by phadej** [comment]
Seems I cannot add you as a contributor, but @23Skidoo or @hvr probably can.

**Comment by 23Skidoo** [comment]
> Seems I cannot add you as a contributor, but @23Skidoo or @hvr probably can.
Already done!

**Comment by quchen** [comment]
Status: `stack build` works, `stack test` still fails.

**Comment by phadej** [comment]
@quchen on stack test is problematic because on env vars, try `--no-run-tests` and run them manually...

**Comment by quchen** [comment]
@phadej Yes, `stack test` does not work so well yet. The PR is for `stack build` only for now.
