### ISSUE TITLE
ghcjs needs topdown solver?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3987]
Right now, [building the ghcjs libraries](https://github.com/ghcjs/ghcjs)

```
$ ghcjs-boot --dev
```

fails with

```
/home/edsko/bin/cabal --config-file /home/edsko/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /opt/ghc/7.10.3-ghcjs-0.2.0/bin/ghcjs --with-hc-pkg /opt/ghc/7.10.3-ghcjs-0.2.0/bin/ghcjs-pkg --prefix /home/edsko/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling --root-cmd /home/edsko/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/run.sh -v2 --dry-run
solver must be one of: modular
```

I take it we finally decided to remove the topdown solver from the code; this ticket is not to suggest that it must be put back, but it would be good to understand why it seems that the modular solver can't handle this situation.

Pinging @dcoutts , @kosmikus , @luite .

**Comment by BardurArantsson** [comment]
Are you absolutely sure there isn't some configuration in there that explicitly requests the "topdown" solver?

(Oh, and yes, topdown was removed. IIRC it didn't actually work anyway.)

**Comment by edsko** [comment]
Sure, it explicitly requests it. That's kind of my point:

``` haskell
  let args = globalFlags ++ ("install" : pkgs) ++
             [ "--solver=topdown" -- the modular solver refuses to install stage1 packages
             ] ++ map ("--configure-option="<>) configureOpts ++ flags
```

If @luite found that the topdown solver was _required_ here, it would be good to understand why and why the modular solver can't do the job.

**Comment by BardurArantsson** [comment]
Then the question becomes: Have you *tried* it with the modular solver? :)

**Comment by edsko** [comment]
No, I haven't, but from the comment it is clear that @luite has and found that it doesn't work. My priority right now is to have a stable ghcjs installation so I'm a bit hesitant to try it, lest I end up with subtle problems later on. Figured I'd flag it here so that this problem is documented at least, as it is the first use case of the top-down solver I am aware of (and Luite is a smart guy :-)

**Comment by BardurArantsson** [comment]
Right, but Cabal/cabal-install has obviously been updated quite a bit since that comment was added :).

Anyway, did a quick test and for me ghcjs compilation fails (after removing the "topdown" argument) even before the "boot" stage. Seems there are dependency issues. Anyway this is also being tracked here: https://github.com/ghcjs/ghcjs/issues/535

(I think it should probably be considered a ghcjs "bug" for the moment.)

**Comment by ezyang** [comment]
@BardurArantsson Could you paste the logs here?

**Comment by 23Skidoo** [comment]
I remember that @luite mentioned somewhere that the reason he needs the top-down solver is because the modular one doesn't allow `base` to be reinstalled. Should be easy to fix by adding a `--no-blacklist` option.

**Comment by BardurArantsson** [comment]
Sure. Removing the "topdown" flag yields

```
cabal install ./ghcjs                                                                                                                                            2016-10-16 10:28:05 ba pts/17
Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghcjs-0.2.0 (user goal)
next goal: ghc-boot (dependency of haddock-api-2.17.3)
rejecting: ghc-boot-8.0.1/installed-8.0... (conflict: ghc-boot =>
binary==0.8.3.0/installed-0.8..., ghcjs => binary>=0.7 && <0.8)
trying: ghc-boot-8.0.1
next goal: binary (dependency of ghcjs-0.2.0)
rejecting: binary-0.8.3.0/installed-0.8..., binary-0.8.4.1, binary-0.8.4.0,
binary-0.8.3.0, binary-0.8.2.1, binary-0.8.2.0, binary-0.8.1.0,
binary-0.8.0.1, binary-0.8.0.0 (conflict: ghcjs => binary>=0.7 && <0.8)
rejecting: binary-0.7.6.1, binary-0.7.6.0, binary-0.7.5.0, binary-0.7.4.0,
binary-0.7.3.0, binary-0.7.2.3, binary-0.7.2.2, binary-0.7.2.1,
binary-0.7.2.0, binary-0.7.1.0, binary-0.7.0.1, binary-0.7.0.0 (conflict:
ghc-boot => binary==0.8.*)
rejecting: binary-0.6.4.0, binary-0.6.3.0, binary-0.6.2.0, binary-0.6.1.0,
binary-0.6.0.0, binary-0.5.1.1, binary-0.5.1.0, binary-0.5.0.2,
binary-0.5.0.1, binary-0.5, binary-0.4.5, binary-0.4.4, binary-0.4.3.1,
binary-0.4.3, binary-0.4.2, binary-0.4.1, binary-0.4, binary-0.3, binary-0.2
(conflict: ghcjs => binary>=0.7 && <0.8)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

Relaxing the "binary" dependency to include 0.8.x yields

```
cabal install ./ghcjs                                                                                                                                            2016-10-16 10:30:07 ba pts/17
Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghcjs-0.2.0 (user goal)
unknown package: bin-package-db (dependency of ghcjs-0.2.0)
fail (backjumping, conflict set: bin-package-db, ghcjs)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by BardurArantsson** [comment]
(The `cabal install ./ghcjs` command is the first one mentioned in "Install GHCJS (for compiler development)" in the README)

**Comment by luite** [comment]
@BardurArantsson I think you're probably seeing a different problem. If you install from the `master` branch you need GHC 7.10, use the `ghc-8.0` branch if you use GHC 8.

And @23Skidoo  is right. The only actual reason that `ghcjs-boot` uses the topdown solver is that this circumvents some protection against installing certain packages.

Since installing these packages (`ghc-prim`, `base`, `template-haskell` for example) is exactly what `ghcjs-boot` wants, and there's only one version of each package available, I'd be happy with any solver, as long as I can tell it to skip these checks.

**Comment by BardurArantsson** [comment]
@luite Oh, right, thanks.

If anyone wants to take a stab at implementing a `no-blacklist` option: AFAICT the relevant blacklisting code is in `dontUpgradeNonUpgradeablePackages` in `Distribution.Client.Dependency`.

**Comment by BardurArantsson** [comment]
So, I just wanted to try a quick hack to avoid the special handling of `ghc-prim` (etc.) to see if that would work for compiling ghcjs. Unfortunately it doesn't seem to be the case. My changes here:

https://github.com/haskell/cabal/compare/master...BardurArantsson:ghcjs-hack

Unfortunately the cabal compilation log is gone, but it complains about not being able to find "ghc-prim". (Incidentally cabal also complains that no remote repository is configured.)

Not sure what I'm missing.

(Just FWIW: I'm not likely to look more at this, at least today.)

**Comment by ezyang** [comment]
This will probably cause problems for ghcjs on GHC 8.2 if cabal-install doesn't ship with this fix, so let's milestone this for 2.0.

**Comment by grayjay** [comment]
I made a change similar to @BardurArantsson's commit that allows the solver finish, but there is an error while building `ghc-prim`.  I'm not sure if it's a bug or if I didn't run the command correctly.

```
ghcjs-boot: error running: /home/kristen/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-8.0.1/cabal-install-1.25.0.0/build/cabal/cabal --config-file /home/kristen/.ghcjs/x86_64-linux-0.2.1-8.0.1/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --install-base --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/kristen/.cabal/bin/ghcjs --with-hc-pkg /home/kristen/.cabal/bin/ghcjs-pkg --prefix /home/kristen/.ghcjs/x86_64-linux-0.2.1-8.0.1/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling
exit status: 1
stderr: Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.

boot/ghc-prim/dist/setup/setup.hs:19:1: warning: [-Wdeprecations]
    Module ‘System.Cmd’ is deprecated: Use "System.Process" instead

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead

GHC/IntWord64.hs:1:1: error:
    attempting to use module ‘GHC.Types’ (./GHC/Types.hs) which is not loaded
cabal: Error: some packages failed to install:
ghc-prim-0.4.0.0-6F9pAJdD0bv3B7ceBDY4mt failed during the building phase. The
exception was:
ExitFailure 1
```

The full log is here: https://gist.github.com/grayjay/0cc89ef1eb876d5372f55fd3cca305bf

My branch: https://github.com/grayjay/cabal/tree/install-base

**Comment by ezyang** [comment]
CC @luite who may be able to give more guidance on what is supposed to happen.

**Comment by robinp** [comment]
As indicated on haskell-cafe by @grayjay , this bug might be related: https://github.com/haskell/cabal/issues/4209

**Comment by grayjay** [comment]
I rebased my branch and made a PR: #4227

**Comment by 23Skidoo** [comment]
This has been fixed by #4227, I assume?

**Comment by grayjay** [comment]
@23Skidoo I wasn't able to build the base libraries with #4227, and I don't know if anyone else has tried.

**Comment by 23Skidoo** [comment]
@luite Can you please confirm that #4227 fixed this issue?

**Comment by 23Skidoo** [comment]
@luite Ping.

**Comment by 23Skidoo** [comment]
OK, judging from https://github.com/NixOS/nixpkgs/pull/28098 it looks like @grayjay's patch did fix this issue, so closing.
