### ISSUE TITLE
Mac OS X GHC 7.8 CI failure: Cannot cabal install happy

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3991]
All of our Mac OS X GHC 7.8 CI builds are failing because the cache was recently cleared out, and we are now tickling a latent bug: "cabal install happy" no longer works because happy is built with a Custom setup which is built with the system Cabal which is built against the old version of unix which has the "ar: permission denied" error.

I'm not sure what the easiest/most robust way of fixing this. There isn't an easily accessible non-buggy copy of the Cabal library on our OS X image which the Custom setup could link against. There isn't an obvious pre-built happy binary we can use. I suppose we could patch and install a custom copy of happy with the problem fixed?

Maybe we should just drop Mac OS X 7.8 support?

**Comment by phadej** [comment]
We can try to use oluet image https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by 23Skidoo** [comment]
I suppose that a patchlevel release of GHC 7.8 is not going to happen at this point?

**Comment by phadej** [comment]
I don't think so

**Comment by 23Skidoo** [comment]
@ezyang BTW, would be nice to put a notice on the 7.8.4 download page that it doesn't work with El Captain (or whatever it's called).
