### ISSUE TITLE
Mac OS X GHC 7.8 CI failure: takes too long

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3994]
I guess the need to rebuild everything with a different unix is pushing it over the limit. If we manage to hit the cache then that would bring it down but we have to do a build successfully first. I'm not so happy about doing this manual intervention every time the cache is cleared, and it's not good "hoping" it runs fast enough to avoid the timeout, so let's try to fix this.

**Comment by ezyang** [comment]
Related https://github.com/travis-ci/travis-ci/issues/6410

**Comment by ezyang** [comment]
https://travis-ci.org/haskell/cabal/builds/168390465

```
ld: not enough disk space for writing '/Users/travis/build/haskell/cabal/dist-newstyle/build/cabal-install-1.25.0.0/build/integration-tests2/integration-tests2' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

...you've gotta be kidding me.

**Comment by 23Skidoo** [comment]
#3998 is supposed to fix this.

**Comment by ezyang** [comment]
OK it's fixed.
