### ISSUE TITLE
new-freeze sometimes generates weird-looking constraints

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4002]
Generally of form `foo == $VER || == $VER`. For example, `HaXml ==1.25.3 || ==1.25.3 || ==1.25.3 || ==1.25.3` or `aeson-pretty ==0.8.1 || ==0.8.1`. Will try to find a minimal repro.

Probably easy to fix by just adding a normalisation step somewhere.

**Comment by dcoutts** [comment]
Yeah, I saw this too. Should be easy. Use
```
Distribution.Version.simplifyVersionRange :: VersionRange -> VersionRange
```
