### ISSUE TITLE
`cabal new-build`  & {alex,happy}

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#4009]
**UPDATE**: Partially (specifically for the case when `alex`/`happy` are to be installed into the nix store because they were requested via `build-tools`), this turns out to be a regression introduced by 8dc39db73dc40e3ca84116f6915ff8d1cc78f584

`new-build` currently isn't able to self-bootstrap `happy` and `alex` (which are two special cases in Haskell's ecosystem and for it's imho legitimate to add special logic to `new-build`), and this is causing problems for the `new-build` based Travis scripts which don't install `alex`/`happy` via binary packages anymore:

```
$ cabal get happy-1.19.5
Unpacking to happy-1.19.5/
$ cd happy-1.19.5/
$ cabal new-build
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - happy-1.19.5 (exe:happy) (first run)
[1 of 1] Compiling Main             ( /tmp/happy-1.19.5/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/happy-1.19.5/setup/setup.hs, /tmp/happy-1.19.5/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/happy-1.19.5/setup/Main.o )

/tmp/happy-1.19.5/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/happy-1.19.5/setup/setup.hs:21:1-8: warning: [-Wtabs]
    Tab character found here, and in 39 further locations.
    Please use spaces instead.
Linking /tmp/happy-1.19.5/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/happy-1.19.5/setup/setup ...
Configuring happy-1.19.5...
Preprocessing executable 'happy' for happy-1.19.5...
setup: The program 'happy' is required but it could not be found
```

and similiarly for `alex`:

```
$ cabal get alex-3.2.1
Unpacking to alex-3.2.1/
$ cd alex-3.2.1/
$ cabal new-build
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - alex-3.2.1 (exe:alex) (first run)
[1 of 1] Compiling Main             ( /tmp/alex-3.2.1/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/alex-3.2.1/setup/setup.hs, /tmp/alex-3.2.1/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/alex-3.2.1/setup/Main.o )
Linking /tmp/alex-3.2.1/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20161014/alex-3.2.1/setup/setup ...
Configuring alex-3.2.1...
Preprocessing executable 'alex' for alex-3.2.1...
setup: The program 'happy' is required but it could not be found
```

after adding a line `build-tools: happy == 1.19.*` to `alex.cabal`, we get now:

```
$ cabal new-build
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - alex-3.2.1 (exe:alex) (configuration changed)
Configuring alex-3.2.1...
Preprocessing executable 'alex' for alex-3.2.1...
setup: The program 'alex' is required but it could not be found
```

IMO, it ought to be possible to install `happy` without having a prior version of `happy` installed, and likewise possible to install `alex` without having a prior `alex` installed.

And in fact, `alex` includes pre-generated `.hs` code in its `.tar.gz` for that:

```
./src/Parser.y
./src/Scan.x
...
./dist/build/alex/alex-tmp/Scan.hs
./dist/build/alex/alex-tmp/Parser.hs
```

and similarly `happy` includes:

```
./src/AttrGrammarParser.ly
./src/Parser.ly
...
./dist/build/happy/happy-tmp/Parser.hs
./dist/build/happy/happy-tmp/AttrGrammarParser.hs
```

I think it makes sense for `alex` to _not_ specify `build-tools: alex`, and take that as a hint that there's a pre-generated `.x` source bundled in the source-tarball (however, the legacy pathname `./dist/build/alex/alex-tmp/Parser.hs` is imho a bad choice, but we will have to support that for the sake of existing `alex`/`happy` releases). Otoh, if a package specifies `build-tools: alex`, I'd expect the `.x` files to be regenerated by `cabal` (and build `alex` if needed).

Maybe for the future, something interacting with the new  `autogen-modules` field would make sense here for a more principled solution.

/cc @ezyang

**Comment by hvr** [comment]
Turns out, there's a very similiar problem when using legacy sandboxes: https://github.com/simonmar/alex/issues/54

**Comment by hvr** [comment]
After talking to @dcoutts I was informed that this is an unintenteded regression as a side-effect of 8dc39db73dc40e3ca84116f6915ff8d1cc78f584

**Comment by hvr** [comment]
The following partial revert of 8dc39db was suggested by @dcoutts:

```diff

diff --git a/cabal-install/Distribution/Client/ProjectBuilding.hs b/cabal-install/Distribution/Client/ProjectBuilding.hs
index 0f3ae1b..0a69c43 100644
--- a/cabal-install/Distribution/Client/ProjectBuilding.hs
+++ b/cabal-install/Distribution/Client/ProjectBuilding.hs
@@ -749,11 +749,11 @@ withTarballLocalDirectory verbosity distDirLayout@DistDirLayout{..}
         -- builddir under the tarball src dir to keep path name lengths down.
         BuildAndInstall ->
           let tmpdir = distTempDirectory in
-          withTempDirectory verbosity tmpdir "src"   $ \unpackdir ->
-          withTempDirectory verbosity tmpdir "build" $ \builddir -> do
+          withTempDirectory verbosity tmpdir "src"   $ \unpackdir -> do
             unpackPackageTarball verbosity tarball unpackdir
                                  pkgid pkgTextOverride
             let srcdir   = unpackdir </> display pkgid
+                builddir = srcdir </> "dist"
             buildPkg srcdir builddir
```

**Comment by ezyang** [comment]
OK fixed now.

**Comment by hvr** [comment]
@ezyang the `build-tools:`-regression is fixed, but we still can't build a `cabal unpack`'ed alex/happy this way

**Comment by ezyang** [comment]
I can't easily test this but I'll take your word for it. Why doesn't it work for `cabal unpack`?

**Comment by gbaz** [comment]
Just tested and this appears very much resolved at this point.
