### ISSUE TITLE
Redesign the haskell.org/cabal website

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4013]
Our [website](http://haskell.org/cabal) hasn't really been substantially updated since ~2008 and is in a dire need of a facelift. We don't need anything super advanced, just a simple static page (I'd use [Hakyll](https://jaspervdj.be/hakyll/)) with a clean design and a news/RSS feed.

A wishlist of items we'd like to see on the new web site:
- Intro page with a brief overview of what Cabal is focusing on the `cabal-install` tool.
- News/feed blog with an RSS feed where we can post updates. Updates should also be visible on the front page.
- User manual link (both stable and the nightly version at http://cabal.readthedocs.io/en/latest/).
- Developer/new contributor section (how to contribute/communicate, coding standards, etc. - most of that info is in the top-level README, so you can just point there).
- Download area plus a button on the front page. Would be nice (but not necessary) if it checked the user's OS and suggested the appropriate binary or source download.
- Updated versions of existing material (FAQ/tutorials on Haskell.org wiki).

@christiantakle, if you're still interested in working on this, I'll assign this ticket to you. If anyone else is willing to help, leave a comment here and I'll give you access to the [haskell/cabal-website](https://github.com/haskell/cabal-website) repo.

**Comment by arianvp** [comment]
I'd be happy to invest some of my time into this.

**Comment by 23Skidoo** [comment]
@arianvp Great! I'm assigning this ticket to you and @christiantakle, who also expressed an interest.

**Comment by arianvp** [comment]
@christiantakle are you on #hackage  in freenode? Then we can discuss this some time soon. My nick is the same on IRC

**Comment by christiantakle** [comment]
@arianvp yes Im on #hackage as `takle`

**Comment by christiantakle** [comment]
@23Skidoo Yes I'm still interested in working on this. I just had a busy week.

**Comment by gbaz** [comment]
As an interim measure, it would be good to _just_ link the new docs at least. I just showed the new docs (and new-build) to folks at hac-phi and it would have been nice to have had the link to those docs from the homepage...

**Comment by 23Skidoo** [comment]
@gbaz I can't access haskell.org/cabal right now (the key is on a machine in storage in another country, and I forgot to copy it when moving). If we can sort this out (revoke old permissions, grant access to a new key), then sure. Also probably makes sense to give access to @arianvp and @christiantakle while we're at it.

**Comment by 23Skidoo** [comment]
@arianvp You now have write access to the [haskell/cabal-website](https://github.com/haskell/cabal-website/) repo.

**Comment by gbaz** [comment]
@arianvp @christiaanb @23Skidoo are your github keys current (e.g. from https://github.com/23Skidoo.keys) ? I can add them all right now...

**Comment by 23Skidoo** [comment]
@gbaz Just updated mine, so now it's current.

**Comment by gbaz** [comment]
Ok, added you.

**Comment by christiantakle** [comment]
@gbaz My key is current

**Comment by gbaz** [comment]
ok, you have access to `sftp cabal-site@www-origin.haskell.org` as well

**Comment by arianvp** [comment]
https://github.com/arianvp.me.keys  are current

**Comment by 23Skidoo** [comment]
@gbaz Thanks! Just confirming that it works.

**Comment by 23Skidoo** [comment]
@gbaz 
> As an interim measure, it would be good to _just_ link the new docs at least. I just showed the new docs (and new-build) to folks at hac-phi and it would have been nice to have had the link to those docs from the homepage...

Done.

**Comment by gbaz** [comment]
Did anything come of the redesign?

Also I note the users guide at https://www.haskell.org/cabal/users-guide/ is still 1.24. Do we want to put a copy of the 2.0 guide there? Or should we just always link to the readthedocs.io site? I see there can be different versions hosted there. Could we host a stable 2.0 version there?

**Comment by 23Skidoo** [comment]
@gbaz Thanks for the heads-up, I'll update that link once I'm back.

https://www.haskell.org/cabal/release/cabal-2.0.0.2/doc/users-guide/ has current docs.

**Comment by 23Skidoo** [comment]
@gbaz
> Did anything come of the redesign?

I am not aware of any progress. Which means that I'll probably have to do it myself.

**Comment by christiantakle** [comment]
@23Skidoo Hey sorry for the radio silence. It kinda died for me when I was trying to coordinate with @arianvp 

I can pick this up again.

**Comment by 23Skidoo** [comment]
@christiantakle @arianvp Feel free to work on this, no one else has expressed interest.

**Comment by Blaisorblade** [comment]
> Also I note the users guide at https://www.haskell.org/cabal/users-guide/ is still 1.24. Do we want to put a copy of the 2.0 guide there? Or should we just always link to the readthedocs.io site? I see there can be different versions hosted there. Could we host a stable 2.0 version there?

> @gbaz Thanks for the heads-up, I'll update that link once I'm back from vacation on Monday.
> 
> https://www.haskell.org/cabal/release/cabal-2.0.0.2/doc/users-guide/ has current docs.

Right now the only link is to "User's Guide (HEAD)" — I'd avoid clicking on that. Would a PR to change that link help (just found https://github.com/haskell/cabal-website/)?

I realize doing a complete redesign is a big and challenging task, but linking or copy-pasting @23Skidoo's http://coldwa.st/e/blog/2017-09-09-Cabal-2-0.html would be faster. #4807 is about linking to it in GitHub's release notes.

Similar ad-interim changes might improve the situation, as long as someone can't commit to a full redesign (which I'd guess takes no less than 1 week full-time, if not more?).

**Comment by gbaz** [comment]
I'm not sure I follow -- there's a link to both the users guide, and also the HEAD of the user's guide. Are you asking about links to the users guides at all, or just to release notes?

**Comment by Blaisorblade** [comment]
> I'm not sure I follow -- there's a link to both the users guide, and also the HEAD of the user's guide. Are you asking about links to the users guides at all, or just to release notes?

1. Linking to release notes would be good. I'm aware of the Hackage changelogs, but @23Skidoo's blog post is better.

2. The user guide appears fixed — I think earlier today https://www.haskell.org/cabal/users-guide/ was still out of date (or maybe I got a cached version?). Either way, now that seems to have docs for the latest Cabal release as desired!

**Comment by ciez** [comment]
would [this version](https://ciezbit.bitbucket.io/cabal) be ok?

**Comment by christiantakle** [comment]
@ciez I pushed something long ago https://github.com/haskell/cabal-website/tree/feature/next
I don't thing anyone have seen it though so it might be stale. Maybe the two can be combined.

**Comment by ciez** [comment]
@christiantakle
Did you make your version with Hakyll? Is it available online?

I did mine with React (more familiar with React than Hakyll). 

It would be easier to make changes to one version or the other if it were clearer what is missing.

Or we could wait for more versions to choose from.

**Comment by christiantakle** [comment]
@ciez If you clone  https://github.com/haskell/cabal-website/tree/feature/next and do the following steps:

```
git checkout feature/next
stack build
stack exec site rebuild

<some-local-webserver> _site
```
some-local-webserver = live-server (you could do `npx live-server` or install it)

I never requested feedback on my work so it died. Regarding React / Hakyll I don't have a preference (Currently write react + typescript @ work)

I will just refresh the branch. Reduce the font-scaling and see if I can bump lts.

**Comment by fgaz** [comment]
@ciez

When visiting your website I only get this message:

> You need to enable JavaScript to run this app.

I don't think we should require visitors to enable js for such a simple and static site

**Comment by ciez** [comment]
@christiantakle

Could you publish the output to github pages, please? So the interested may see it with clicking a link, rather than building the website themselves.

**Comment by ciez** [comment]
@fgaz

It is easier to write another version of the website for those users.

**Comment by christiantakle** [comment]
@ciez pushed to https://christiantakle.github.io/

**Comment by fgaz** [comment]
@ciez

Well, why don't we _only_ write the non-js version then

**Comment by ciez** [comment]
@fgaz

Fair enough. Let's wait for the html-only version.

**Comment by christiantakle** [comment]
@ciez @23Skidoo @fgaz I just need some feedback on https://christiantakle.github.io/ 

Its pretty simple and we can take it in any direction.

**Comment by fgaz** [comment]
@christiaanb 

I like simple.

Just 3 things:
1. I think the color scheme should be the same that https://haskell.org and https://hackage.haskell.org use
2. Maybe add the cabal logo to the home page
3. Maybe add those "¶" links to each header like readthedocs, hackage, the python docs and many others do

**Comment by fgaz** [comment]
@christiaanb 

As for the content:

4. I think the docs link should point to a page with at least:
    * FAQ
    * User's Guide
    * User's Guide (HEAD)
    * API
0. In the blog page:
    >  Here you can find all my previous posts

    "my" should be "our", "the" or something similar
0. Maybe add a link to the issue tracker
0. Maybe add a link to the source
0. Maybe to the ML too?

**Comment by christiantakle** [comment]
@fgaz 
> I think the color scheme should be the same that https://haskell.org and https://hackage.haskell.org use

I agree I allready toke elements from them. Maybe It should just be almost equal to https://www.haskell.org/downloads

> Maybe add the cabal logo to the home page.

I choose not to originally since I think it could use a touch op but I can add it in there and we can see if it should be updated in a second pass.

> Maybe add those "¶" links to each header like readthedocs, hackage, the python docs and many others do

Not sure I follow can you give me a link to an example? I'm sure its easy to add.


As for the content:

> I think the docs link should point to a page with at least: FAQ, User's Guide, User's Guide (HEAD), API

So change `Documentation` to a subpage with the above links?

> In the blog page. Here you can find all my previous posts. "my" should be "our", "the" or something similar
I will change it to "our".


> Maybe add a link to the
> * issue tracker
> * the source
> * ML too?
> * hackage

I will add a new top-level heading "community" with those links.

**Comment by fgaz** [comment]
@christiantakle 
> Not sure I follow can you give me a link to an example? I'm sure its easy to add.

https://cabal.readthedocs.io/en/latest/intro.html#a-tool-for-working-with-packages
![screenshot-2018-6-18 1 introduction cabal release user s guide](https://user-images.githubusercontent.com/8182846/41523491-77ec380e-72da-11e8-9c5e-8ae76fa5f1fb.png)

https://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Monad.html#g:2 (the whole header here)
![screenshot-2018-6-18 control monad](https://user-images.githubusercontent.com/8182846/41523493-78714170-72da-11e8-89fd-e0c9ff446467.png)


https://docs.python.org/3/library/enum.html#using-automatic-values
![screenshot-2018-6-18 8 13 enum support for enumerations python 3 6 6rc1 documentation](https://user-images.githubusercontent.com/8182846/41523492-782da596-72da-11e8-9049-1bba59148099.png)

> So change Documentation to a subpage with the above links?
yup

Btw, these are only my personal opinions as I am _not_ an @Haskell member. You should ask @23Skidoo or others too

**Comment by 23Skidoo** [comment]
@christiantakle I think that @fgaz's suggestions make sense. Some additional comments:

* I'd make the "Download" button more prominent, like in @ciez's version.
* "Cabal" in the top left corner should be replaced with the logo, like in @ciez's version. Though I'd use [the one with the light background](https://wiki.haskell.org/Haskell_logos#Cabal).
* I'd add a top-level ["fork me on GitHub" ribbon](https://blog.github.com/2008-12-19-github-ribbons/), or maybe a GitHub logo button like on https://www.scala-sbt.org/.
* It doesn't look like there's an RSS feed, we need it to connect the news feed to Planet Haskell.
* Each news post should have Disqus comments attached, like I have [here](http://coldwa.st/e/blog/2017-09-09-Cabal-2-0.html), for example.
* I'd make the "proudly generated by Hakyll" string smaller, it's too eye-catching right now. Maybe put it under a thin `<hr>`, like Contact/API/About/... section in the bottom of this GitHub page.
* "Posts" and "Blog" should be "News". "Archives" should be "News Archives".
* "Quick Links" shouldn't be the main thing on the front page, we have the top menu for this. Instead in this place there should be a short intro text with a simple example of usage and links to the quick start page and further documentation instructions. See https://gulpjs.com/ and https://gruntjs.com/ for inspiration. News section can stay where it is.

@christiantakle @ciez @arianvp I gave you all write access to the `cabal-website` repo, maybe if @christiantakle pushed his code to an orphan branch there, you could use that repo to collaborate?

**Comment by 23Skidoo** [comment]
@fgaz
> Btw, these are only my personal opinions as I am not an @haskell member.

I don't think that membership of the @haskell org confers any special status on a Cabal contributor. I think @hvr can make you a member, though.

**Comment by ciez** [comment]
Any thoughts re: running 2 versions of the website: with Js enabled and static html without Js altogether?
There seem to be at 2+ contributors ready to look after 1 version.

BTW my version has RSS feed reader & formatter. The Haskell Cabal RSS feed section on the main page is gen'ed in browser.

We could store / update content as RSS XML file. Each version (html, js) would then transform the content (html: server side, js: client side) and display it without the need to dig with each update, into the source code.

?

**Comment by quasicomputational** [comment]
-1. Which would be the canonical homepage? Why duplicate the effort and build a more complicated system? We want a no-JS version anyway for grumps like me who'd complain about having to enable JS just to find a link to the docs, so let's go with that.

**Comment by ciez** [comment]
Are the no-Js grumps - the primary target audience for the website? Or shall we try to improve UI to try to impress visitors who are only curious about Haskell? It may be worth to collect stats about visitors with/out Js enabled.

Between
a) A is keen to do x1, B is keen to do x2
b) we need Y who will do y1. Anyone?

a) seem to make more sense even if x1+x2 > y1

**Comment by 23Skidoo** [comment]
Having two versions of the website sounds like overkill, however I think JS could be appropriate in a couple of places (provided that the functionality degrades gracefully in a no-JS setting):

* On mobile, making the top menu pop up when the user presses the menu icon (instead of having the menu always on top) would look nicer and more compact. 
* The download page could auto-detect the user's arch and OS and automatically recommend the most appropriate binary for download.

@ciez BTW, if you're not familiar with how Hakyll works, you basically write all content in Markdown, then it generates a website for you using the HTML templates you write separately. 

What's important for me here is that all content should come from a single source, i.e. if there are two versions of the website, I as an author should only be required to edit a single Markdown file to publish a new blog post.

**Comment by ciez** [comment]
Must the single source be in markdown format?

What about RSS files? Can all editable content come from RSS feed? If yes, then both versions could display the same content.

**Comment by christiantakle** [comment]
It should be simple enough to add rss/atom to a Hakyll produced site. In the case of being more fancy I would properly investigate one of the many static site generators that uses react as the template language.

https://www.staticgen.com/ e.g. next.js

That should reduce duplication in theory but not sure if its needed. I think even a basic update would be a win currently.

**Comment by 23Skidoo** [comment]
> Must the single source be in markdown format?

Hakyll also seems to support `.rst` and other input formats; ReST is probably better actually, since that's what the Cabal manual is written in (it uses Sphinx). Re: RSS, it can be generated from the same Markdown/ReST source.

**Comment by ciez** [comment]
> even a basic update would be a win currently.

Yes, it is so.

Well, everyone has their preferences. 

With React, significant changes are easier, if I worked on them.

The React version is ready. Don't quite follow what the duplication refers to. Deploying 2 versions?

Even if one version is not maintained, it can be dropped later. Html site does not need to be modified because of the js version.

**Comment by ciez** [comment]
> Re: RSS, it can be generated from the same Markdown/ReST source.

Are such RSS files already available somewhere?

Their format may be changed later. It is easy enough to adapt the code to display the content.

**Comment by tom-bop** [comment]
Mainly for bus factor reasons, I'd also favor a simple Hakyll-based site. Gracefully handling non-JS is good to have also.

**Comment by christiantakle** [comment]
> @christiantakle @ciez @arianvp I gave you all write access to the haskell/cabal-website repo, maybe if @christiantakle pushed his code to an orphan branch there, you could use that repo to collaborate?

Its been there for a while.
https://github.com/haskell/cabal-website/commits/feature/next

I will look at adding the changes proposed during the weekend. Others are welcome to play with the branch as well.

**Comment by m-renaud** [comment]
Any update on this? I've thrown together a simple restyle and content re-organization that you can browse at https://www.m-renaud.com/sites/haskell-org/cabal/ (not all the relative links work, I only updated the pages that are in the same directory/styled using the same css).

I like the idea of completely re-doing the site but this is a simple stop-gap until all the issued discussed above can be worked out. What are everyone's thoughts?

**Comment by simonmichael** [comment]
Just found this issue - I think https://haskell.org/cabal has been using @m-renaud's redesign for some time, correct ?

It seems this initiative didn't reach completion, and Hakyll adds a bunch of complexity. I propose this issue should be closed.

**Comment by gbaz** [comment]
following above advice i think we should close this
