### ISSUE TITLE
package-tests on old GHC spazzes out trying to build Setup.hs

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4018]
The problem is that we don't pass `-hide-all-packages`, so everything from the store database just gets slammed into GHC, a pile of shadowing takes place and when the dust settles, more often than not, 1.25.0.0 will have gotten hidden.

Passing `-hide-all-packages` should solve the problem.

**Comment by jneira** [comment]
closing optimistically, as we don't observe the error in last GH ci
