### ISSUE TITLE
Support for creating a static package repo

### ISSUE THREAD

**Issue by bos** [haskell/cabal#402]
(Imported from [Trac #409](http://hackage.haskell.org/trac/hackage/ticket/409), reported by mnislaih on 2008-11-19)

Usual scenario:

Bob has a bunch of packages for personal use he does not want or cannot upload to hackage. All he needs is a public_html folder, his packages in tar.gz files, and a bit of help to set up a private static hackage repo.

[RubyGems](http://hackage.haskell.org/trac/hackage/wiki/RubyGems) allows this with the <i>generate_index</i> command, see [here](http://rambleon.org/2008/08/01/creating-your-own-gem-server-redux/).

Since cabal-install supports multiple package sources already, the only thing missing is a command to generate the index and directory structure.

**Comment by phadej** [comment]
The `file+noindex` repositories are morally this.
