### ISSUE TITLE
Drop support for depending on non-internal version of package with build-depends constraint

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4020]
Currently in Cabal, you can do this (tested in `BuildDeps/InternalLibrary4`):

```
name: p
version: 1.0

library
  ...

executable pexe
  build-depends: p < 1.0
```

The version constraint on the internal dependency p forces us to use an external copy of p, rather than the internal copy.

This seems like a pretty useless feature. The modular dependency solver is unable to take advantage of this fact. It interacts poorly with `--allow-older` and `--allow-newer`. Can we get rid of it?

**Comment by 23Skidoo** [comment]
+1 from me.

**Comment by dcoutts** [comment]
Yes. Seems like a feature that must be very rarely used, since it cannot work with any automation (cabal-install or stack).
