### ISSUE TITLE
Setup travis-dedup

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4024]
See: https://github.com/grosser/travis_dedup

I actually tried to set this up myself (see https://github.com/grosser/travis_dedup/issues/6 ) but apparently my user doesn't have enough permissions. @23Skidoo or maybe a haskell org owner, maybe the authorization has to come from your account?

**Comment by 23Skidoo** [comment]
I'll look into this tomorrow.

**Comment by 23Skidoo** [comment]
I've updated the webhook's token.

**Comment by 23Skidoo** [comment]
Still seems to fail. @hvr, since you're one of the haskell org owners, can you try updating the token? See https://github.com/grosser/travis_dedup#a-using-travis-dedupherokuappcom-via-github-push-notification for the instructions.

**Comment by hvr** [comment]
@23Skidoo I have, but I'm confused; following the instructions, I don't seem to be able to restrict the token's permission scope to only cover the haskell org (or even better yet, only the cabal project repo).

**Comment by 23Skidoo** [comment]
@hvr I think that's the downside with this method.

**Comment by 23Skidoo** [comment]
`travis_dedup` is now deprecated. From their webpage:

> Travis will ship this as a feature in Q12017, currently in beta if you ask them.

So I suggest we just wait until then. Leaving this ticket open for now.

**Comment by hvr** [comment]
@23Skidoo it's this here, right? https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by 23Skidoo** [comment]
Yes, and I've actually already enabled it.
