### ISSUE TITLE
ProjectConfig Arbitrary instance is too brittle

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4044]
Inside `cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs` there are a number of QuickCheck Arbitrary instances which are implemented using positional arguments.

```
    shrink (PackageConfig
              x00 x01 x02 x03 x04
              x05 x06 x07 x08 x09
              x10 x11 x12 x13 x14
              x15 x16 x17 x18 x19
              x20 x21 x22 x23 x24
              x25 x26 x27 x28 x29
              x30 x31 x32 x33 x33_1 x34
              x35 x36 x37 x38 x39
              x40) =

```

These are very brittle, as when you add a new field you need to carefully make sure that all of the positions get updated correctly. A better strategy would be to use record syntax and meaningful names to make this code more robust.

**How to test.** Once you've made your change, run `cabal new-test cabal-install:unit-tests` to build and run the cabal-install test suite. Note that you will need a sufficiently new version of cabal (HEAD) for `new-test` to work.

**What you will learn if you fix this.**

1. How to build and install a HEAD version of cabal-install
2. How to use Haskell record syntax in place of positional syntax
3. How to build and run the cabal-install unit test suite

**Comment by dcoutts** [comment]
Agreed. Named fields FTW!

**Comment by bitrauser** [comment]
I'd like to look into this.

**Comment by ezyang** [comment]
Thanks @bitrauser!

**Comment by BardurArantsson** [comment]
Close, since #4536 was merged.
