### ISSUE TITLE
build-reports: option is invalid in a config file

### ISSUE THREAD

**Issue by bos** [haskell/cabal#405]
(Imported from [Trac #412](http://hackage.haskell.org/trac/hackage/ticket/412), reported by guest on 2008-11-22)

With darcs (tonight) cabal and cabal-install, I see the generated .cabal/config includes the line '-- build-reports:', suggesting that this is a valid configuration option.

However, it is not. If one uncomments it to 'build-reports: True', then Cabal warns and apparently ignores one's configuration as corrupt:

gwern@craft:29302~&gt;cabal update
Warning: Error parsing config file /home/gwern/.cabal/config:9: "True"
Warning: Using default configuration.
Downloading package list from server
'[http://hackage.haskell.org/packages/archive](http://hackage.haskell.org/packages/archive)'

The syntax is valid, the True is correct, it's not listed as being part of a section. further, --build-reports is a valid CLI option:

gwern@craft:29304~&gt;rm .cabal/config &amp;&amp; mv config .cabal &amp;&amp; cabal install --build-reports ztail                       [ 9:21PM]
Resolving dependencies...
Downloading hinotify-0.2...
[1 of 1] Compiling Main             ( /tmp/TMPhinotify-0.2/hinotify-0.2/Setup.lhs, /tmp/TMPhinotify-0.2/hinotify-0.2/dist/setup/Main.o )
Linking /tmp/TMPhinotify-0.2/hinotify-0.2/dist/setup/setup ...
Downloading ztail-1.0...
........

Either the default config is lying/wrong, or the build-reports: option is busted.

**Comment by BardurArantsson** [comment]
This is obsolete. Please close.
