### ISSUE TITLE
Not helpful / useful error messages on parse failure in fields in .cabal files

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#4050]
not sure if this is a bug or a feature request/task (or just that .cabal files have atrocious parse error messages), but in build-depends:  a comment at the end of line in a build dep field

eg  
`base >= 4.9 -- && < 4.10`
will get a parse error

but 

```
base >= 4.9
 -- && < 4.10

```

works fine

also currently

**Comment by ezyang** [comment]
Here is the error with Parsec:

```
ezyang@sabre:~/Dev/labs/T4050$ /home/ezyang/Dev/cabal-shake/dist-newstyle/build/x86_64-linux/ghc-7.10.3/cabal-install-1.25.0.0/noopt/build/cabal/cabal act-as-setup -- configure -v3
Using Parsec parser
Warning: T4050.cabal:22:35:
unexpected '-'
expecting space, "&&", white space, "||", "," or end of input: "base >=4.8 --
&& <4.9"
```

Should we allow comments here? @phadej, how hard would this be?

**Comment by dcoutts** [comment]
No, we cannot allow -- as comments on the same line, because -- is valid in many options lists e.g. `foo-options: --frobnicate`.

It's always been the case that -- is a comment only on a line on its own in .cabal files. The best we can do I think is produce better error messages (e.g. by taking `--` as a whole token so we the parser can say `unexpected '--'`).

**Comment by cartazio** [comment]
Either way the current error message is terrible.  And that needs be fixed

**Comment by ezyang** [comment]
@cartazio Do you think the new Parsec error is still bad?

**Comment by cartazio** [comment]
The bare parsec error is definitely way better. Knowing what are valid / possible tokens is definitely an improvement. 

Should this sort of change be applied to other parts of the cabal file format? File format errors have always been a pain in cabal files

**Comment by ezyang** [comment]
Well, @phadej's glorious Parsec patch applies to ALL things we parse, so, yes.

**Comment by ezyang** [comment]
OK, I'm going to close this, as it will get "fixed" when we switch to parsec. That's the point.
