### ISSUE TITLE
`cabal configure` hangs forever often.

### ISSUE THREAD

**Issue by crocket** [haskell/cabal#4061]
Softwares
- ArchLinux
- Linux 4.8.4
- cabal-install 1.24

It seems kernel version is irrelevant because this issue doesn't go after I downgrade linux.

``` shell
% cabal configure
Resolving dependencies...
Configuring stack-demo-0.1.0.0...
^Ccabal: fd:13: hGetContents: illegal operation (delayed read on closed handle)
```

Basically, `cabal configure` hangs forever often. If I pressed `Ctrl+C`, the shell might print `fd:13: hGetContents: illegal operation (delayed read on closed handle)`.

If I executed `strace cabal configure`, it would hang on `FUTEX_WAIT_PRIVATE`.

**Comment by crocket** [comment]
I just created a new unix user, and the new unix user executes `cabal configure` very quickly.

I think there is something wrong with my user settings, but I don't know what is wrong, yet.

**Comment by crocket** [comment]
After deleting dot files and dot folders randomly, `cabal configure` became fast again.
But, I don't know which exact dot files or folders were responsible for the issue.
I can't reproduce this heisenbug. Thus, I'm closing this issue.

When I encounter the bug again, I'll carefully test this issue after deleting each of dot files and dot folders.

**Comment by ezyang** [comment]
Thanks, your efforts are highly appreciated.

In the future, if you manage to reproduce, uploading a `-v3` log and a full `strace` log (or perhaps `strace -e file`) may also help us diagnose.
