### ISSUE TITLE
CPP error when building Cabal

### ISSUE THREAD

**Issue by byorgey** [haskell/cabal#4092]
I have `cabal-1.22.6.0` built with `Cabal-1.22.5.0`.  If I do
```
git clone haskell/cabal
cd cabal
cabal sandbox init
cabal install Cabal/ cabal-install/
```
then compilation of `Cabal` fails with
```
cabal: Error: some packages failed to install:
Cabal-1.25.0.0 failed during the configure step. The exception was:
user error ('/home/brent/local/bin/ghc' exited with an error:

Cabal/Distribution/Utils/BinaryWithFingerprint.hs:11:0:
error: missing binary operator before token "("
#if MIN_VERSION_base(4,8,0)
^
)
```
See the discussion at #1613.

**Comment by 23Skidoo** [comment]
And I assume that you're using GHC < 8, which has built-in `MIN_VERSION_` macros.

**Comment by byorgey** [comment]
Yes, I should have mentioned that, I happened to be using GHC 7.10.2.

**Comment by ezyang** [comment]
The error is pretty obvious; Binary.WithFingerprint is in the bootstrap set but it doesn't use alternate macros in that case.

**Comment by ezyang** [comment]
So, I don't really know why the macro is not defined, or how to repro, but #4101 should solve the error.
