### ISSUE TITLE
specify a way to add .o files to a library

### ISSUE THREAD

**Issue by bos** [haskell/cabal#41]
(Imported from [Trac #34](http://hackage.haskell.org/trac/hackage/ticket/34), reported by @igfoo on 2005-12-11)

.o files may be generated by means outside of cabal, and there should be a way to list them in the .cabal file as being linked with the library.

**Comment by jsl** [comment]
It seems like this issue didn't even make sense 8 years ago, let alone now. :)

I suggest closing and re-opening another ticket if there is something we're missing. /cc @tibbe
