### ISSUE TITLE
cabal new-build --dep with yesod-core stopped working

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4100]
```
ezyang@sabre:~/Dev/labs/yesod-core-1.4.25$ cabal new-build --dry --dep 
Warning: The package list for 'hackage.haskell.org' is 21 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Distribution/Client/ProjectPlanning.hs:2250:5-10: Assertion failed
```

Working on a smaller repro.

**Comment by ezyang** [comment]
OK, actually, this is super easy to repro, just have a package that looks like this:

```
name: p
version: 1.0
cabal-version: >= 1.8
build-type: Simple

test-suite q
    type: exitcode-stdio-1.0
    main-is: Foo.hs
```

CC @hvr

**Comment by ulysses4ever** [comment]
I just tried the little example above, and instead of an assertion failure cabal finished with a warning that test suite won't be build and there are no other components, which is exactly correct.

Should we close this?

**Comment by ulysses4ever** [comment]
This is both, with latest cabal release and with `HEAD`.

**Comment by Mikolaj** [comment]
That's great news. Thank you everybody. Closing.
