### ISSUE TITLE
nslookup and snapshot.json

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#4102]
On a machine without `nslookup` (but `drill` from `ldns` instead) git master sometimes fails as follows:

```
Warning: 'nslookup' tool missing - can't locate mirrors
Downloading the latest package list from hackage.haskell.org
Verification loop. Errors in order:
Invalid hash for <repo>/snapshot.json
Invalid hash for <repo>/snapshot.json
Invalid hash for <repo>/snapshot.json
Invalid hash for <repo>/snapshot.json
Invalid hash for <repo>/snapshot.json
```

Maybe the fallback code isn't correct and/or `drill` should be used if found.

**Comment by ezyang** [comment]
CC @hvr, who implemented the DNS-based mirror resolution protocol in ae24c5c6e68e4cbb4d0b49b546eac88a64a0517f.

**Comment by hvr** [comment]
tbh, I don't think the nslookup-code is to blame here. The message about `nslookup` just states that the optional(!) best-effort attempt to locate mirrors via DNS lookup failed (which is only done when bootstraping hackage-security; once we have a validated `mirrors.json` file we don't do any DNS mirror lookups), and that we now proceed to bootstrap with only `hackage.haskell.org` as the only known mirror.

IOW, I'm quite certain you'd get the same failure even withouth ae24c5c

**Comment by accursoft** [comment]
`ldns` uses 10% the space of `nslookup` (from `dnsutils`) on Debian. It would be nice to have this as an alternative.
```
# apt install --no-install-recommends dnsutils
After this operation, 46.4 MB of additional disk space will be used.
```
```
# apt install --no-install-recommends ldnsutils
After this operation, 4958 kB of additional disk space will be used.
```

**Comment by 23Skidoo** [comment]
> have you noticed that dnsutils must be installed for cabal-install to work?

As @hvr wrote above, this shouldn't be the case, that step is optional. Patches adding support for `ldnsutils` are welcome, of course.

**Comment by hvr** [comment]
Coincidentally, for targetting POSIX platforms, I've been already working a couple of weeks on a light-dependency library which uses the ubiquitous `req_query(3)` library to provide DNS look up services.

**Comment by 23Skidoo** [comment]
So, there are two issues here: 

1) Adding support for `ldns` to the nslookup code.
2) Verification loop error that is unrelated to nslookup stuff.

Would be nice to get a repro case for the latter.

**Comment by hvr** [comment]
@23Skidoo I've finally managed to get that `res_query(3)` polished and released; see #4839; I'm looking next at a native solution for Win32's `<windns.h>` API.

**Comment by tuncer** [comment]
@hvr, this looks resolved and can be closed. Correct?

**Comment by tuncer** [comment]
Closing as resolved.
