### ISSUE TITLE
does not work with ghc-7.6 because of -fno-omit-yields 

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#4106]
I have some old code that needs to be compiled with ghc-7.6.3. I don't seem to be able to do this with cabal-install 1.24.0.1:

```
PATH=/opt/ghc/ghc-7.6.3/bin:$PATH cabal install -v
...
/opt/ghc/ghc-7.6.3/bin/ghc -hide-all-packages -c /tmp/1804289383846930886.c -o /tmp/16816927771714636915.o -fno-omit-yields
ghc: unrecognised flags: -fno-omit-yields
```
(I can work around this by hacking the ghc driver bash script to ignore this option. I don't know the implications. And I have not the slightest idea why cabal-install wants to compile a C file.)

**Comment by ezyang** [comment]
Hello @jwaldmann.

Cabal will never add `-fno-omit-yields` of its own volition, which means one of your packages has it as one of its `--ghc-options`. Unfortunately, you've truncated your log output, so I can't actually tell you which of the packages it is. Once you determine the offending package, you can force an older version of the package which doesn't have the problem using the `--constraint` flag.

Hope that helps.
