### ISSUE TITLE
CI does not work with cabal-install-1.24.0.1

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4108]
@hvr updated the cabal-install PPA to 1.24.0.1, but this broke our CI. A representative failure is https://travis-ci.org/haskell/cabal/jobs/175033797

I haven't investigated further.

**Comment by 23Skidoo** [comment]
@ezyang 
IIRC something like this happened before and was fixed by you, but I can't find the ticket right now.

**Comment by ezyang** [comment]
Reproduced locally; I think this is a redux of #3932. I actually have been working on a rewrite of the test suite which would fix this problem, but it is going to be some more time before I finish it.
