### ISSUE TITLE
Develop a "validate" script which runs the CI locally

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4112]
In GHC, we have a './validate' script which serves as the basis of truth for whether or not a commit passes tests or not. It would be useful to have something similar for Cabal as well; the truth of the matter is that there are a lot of test suites to remember to run, and a lot of versions of GHC to build Cabal with. So most people don't locally test at all, except for the bits they are sure they should be running specific tests for. But, while it may be hard to run tests on multiple OSes, it's relatively easy to build and test Cabal on multiple versions of GHC.

**Comment by phadej** [comment]
... relatively easy on linux (or do I have to say Ubuntu/Debian). OTOH it's still better than nothing.

If someone picks to implement this, than the CI have to actually use the same `./validate`, otherwise it will cause confusion (CI passes, local no, or vice versa).

**Comment by andreabedini** [comment]
I believe @phadej developed a such script in 6a9a101ca5e1731b9f099a94579a84d2e19667f8, about four years ago :)

**Comment by jneira** [comment]
yeah, indeed, thanks for noting it
