### ISSUE TITLE
cabal-install should handle packages that need a later Cabal version better

### ISSUE THREAD

**Issue by bos** [haskell/cabal#412]
(Imported from [Trac #419](http://hackage.haskell.org/trac/hackage/ticket/419), reported by jimburton on 2008-12-01)

I am using cabal-install 0.5.2. I have previously installed cgi (and other packages) locally. Now when I try to upgrade them all:

Resolving dependencies...
cabal: Couldn't read cabal file "./cgi/3001.1.7.1/cgi.cabal"

I presumed that the starting point in that path was ~/.cabal/packages/hackage.haskell.org. In cgi/3001.1.7.1 there is just the tarball for the package but opening it and putting the .cabal file in the right place didn't help.

**Comment by gbaz** [comment]
is this resolved by the `cabal-version` field?
