### ISSUE TITLE
new-build ignores --builddir option

### ISSUE THREAD

**Issue by DanielG** [haskell/cabal#4127]
`cabal new-build` doesn't seem to respect `--builddir`, regardless of what I pass it still creates the `dist-newstyle` directory.

This is with HEAD (2146ea148fc52ee97549b89c1e9bb18c90610670).

As far as I can tell this is because `DestDirLayout` is constructed without considering any of the `*DistPref` fields from `CliConfigFlags`.

See https://github.com/haskell/cabal/blob/2502ea1baea35f6d28128b76603efb741b5d2f40/cabal-install/Distribution/Client/ProjectOrchestration.hs#L176

I wouldn't mind submitting a PR for this if anyone can point out a good way to do this since I'm still new to the new-build code.

**Comment by ezyang** [comment]
See also #4124
