### ISSUE TITLE
Unrecognized stanza on the new "repository" syntax in package-local config

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/cabal#4129]
When something like

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  secure: True
  root-keys: <root-key-IDs>
  key-threshold: <key-threshold>
```

is specified in the "cabal.config" file next to the project's "*.cabal" file, Cabal reacts with

```
Warning: /Users/mojojojo/Dropbox/Dev/refined/cabal.config: Unrecognized stanza
on line 1
```

My Cabal version is 1.24.0.0.

**Comment by ezyang** [comment]
Hi @nikita-volkov, what command are you using to interact with Cabal?

**Comment by ezyang** [comment]
CC @ttuegel who contributed the "reconfigure" feature, which I believe is responsible for reading in `cabal.config` so that it knows how to reconfigure a build when it sees that things are out of date.

**Comment by hvr** [comment]
Is the new-style repository even legal for `cabal.config` files? I was under the impression that `cabal.config` only supports the legacy-style repo syntax, while `cabal.project` files only support the new-style syntax

**Comment by ttuegel** [comment]
> Is the new-style repository even legal for cabal.config files? I was under the impression that cabal.config only supports the legacy-style repo syntax, while cabal.project files only support the new-style syntax. I.e. I considered this deliberate behaviour rather than a bug.

This was also my understanding.

**Comment by stla** [comment]
Same problem. For future readers: this works without warning with `remote-repo: hackage.haskell.org` instaed of `repository hackage.haskell.org.

**Comment by gbaz** [comment]
closing as obsolete
