### ISSUE TITLE
Empty package: cabal-hash.txt: Does not exist

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4130]
Got this while trying to build `ircbrowse` with a recent snapshot of `cabal-install` HEAD:

```
$ cabal new-build
[...]
cabal: Failed to build snap-app-0.7.0 (which is required by exe:ircbrowse from
ircbrowse-0.1.0.0). The failure occurred during the final install step. The
exception was:
/home/refold/.cabal/store/ghc-8.0.1/snap-app-0.7.0-e7ebb350f8c439e859941200457b8734ec0e234e736ed19e834da281aa9c8440/cabal-hash.txt:
openBinaryFile: does not exist (No such file or directory)
```

The `/home/refold/.cabal/store/ghc-8.0.1/snap-app-0.7.0-e7ebb350f8c439e859941200457b8734ec0e234e736ed19e834da281aa9c8440/` directory doesn't seem to exist.

**Comment by 23Skidoo** [comment]
`snap-app` [is an empty package](https://hackage.haskell.org/package/snap-app-0.7.0/snap-app.cabal), and we don't seem to handle that case correctly either:

```
$ cabal new-build
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - snap-app-0.7.0 (lib) (first run)
Configuring component lib from snap-app-0.7.0
Preprocessing library snap-app-0.7.0...
```

**Comment by 23Skidoo** [comment]
@hvr showed me an example where an empty library is actually useful: http://hackage.haskell.org/package/nats-1.1.1/nats.cabal

**Comment by ezyang** [comment]
Since hashing is only done for packages from a repository, it will be difficult to construct a test case (all our test cases rely on inplace builds); so from a tooling perspective, this is blocking on #4016.

**Comment by hvr** [comment]
@23Skidoo here's another canonical one btw: http://hackage.haskell.org/package/fail-4.9.0.0/fail.cabal

**Comment by ezyang** [comment]
#4016 is solved so we should be able to make a test case for this.

**Comment by hvr** [comment]
Just in case there was any doubt, this is a regression relative to old-build (which handles the weirdo-case `snap-app-0.7.0` just fine)

**Comment by phadej** [comment]
@hasufell, installing `test-suite`s is something which shouldn't work anyway, should it? (I agree that error should be about that, and not about something internal).

**Comment by phadej** [comment]
With `cabal-install-3.0` it's better, as it doesn't make store broken:

```
% cabal build --dep
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - snap-app-0.7.0 (lib:snap-app) (requires download & build)
Downloading  snap-app-0.7.0
Downloaded   snap-app-0.7.0
Starting     snap-app-0.7.0 (all, legacy fallback)
Building     snap-app-0.7.0 (all, legacy fallback)
Installing   snap-app-0.7.0 (all, legacy fallback)
cabal: Failed to build snap-app-0.7.0. The failure occurred during the final
install step. The exception was:
/cabal/store/ghc-8.6.5/incoming/new-99767/cabal/store/ghc-8.6.5/snap-app-0.7.0-69381acbcfc33e2f42e1fee72b15c9d7d1d268b1e258f52f29e71a36232fc0bb/cabal-hash.txt:
openBinaryFile: does not exist (No such file or directory)
```

**Comment by phadej** [comment]
Note, this doesn't happen for `nats-1.1.1`, so it's probably related to `legacy fallback`.
