### ISSUE TITLE
cabal exec PATH regression on Windows

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4133]
Steps to reproduce:

1. Build latest cabal HEAD
2. Create a sandbox
3. Install an executable named `myprog` in the sandbox. Simple way is to create a little package with an executable and install that.
4. Run `cabal exec sh -- -c myprog`.

Expected result: it works, because PATH was adjusted to contain bin.

Actual result: it doesn't work. When you inspect the environment, you see that only the *lib* directory of the sandbox has been added; the PATH has been clobbered. Actually, you can see that in Exec.hs we are setting the PATH twice on Windows: once for the library path, and once (see the bottom of the file) to actually update the PATH to include bin. These two updates are clobbering each other.

One thing I don't understand is why integration-tests didn't catch the failure. I only noticed the problem because I had ported the integration test to a new framework, which then started failing. Here is a failing Appveyor build using the new test suite: https://ci.appveyor.com/project/23Skidoo/cabal/build/%232709%20(master)

CC @abooij who contributed what I think is the breaking patch 4347d0d75f216890e267edbaa46b733257ca19fe.

**Comment by 23Skidoo** [comment]
I think we should fix it for 2.0.

**Comment by grayjay** [comment]
> One thing I don't understand is why integration-tests didn't catch the failure.

I didn't enable the `exec` tests in appveyor.yml because they were flaky:  #3123
