### ISSUE TITLE
Consider dropping old-time from legacy custom setup packages when GHC >= 8.0

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4140]
GHC 8.0 no longer ships old-time as a boot package, so there isn't any situation where a "bare ghc --make" would be able to pick it up.

On the other hand, one could make a reasonable argument that the point of legacy custom setup is to make old packages keep working, even as GHC is upgraded, in which case we should bring old-time in.

**Comment by hvr** [comment]
I think we need to keep it in, as starting with Cabal 1.24 (which is the one needed by GHC 8), cabal 1.24 will nag about declaring `setup-depends` anyway. So the real target audience for the implicit `setup-depends` is really Cabal <= 1.22 & GHC <= 7.10, more or less as you concede yourself in the 2nd half of your comment

**Comment by ezyang** [comment]
OK.
