### ISSUE TITLE
add option to fetch a single package without dependencies

### ISSUE THREAD

**Issue by bos** [haskell/cabal#416]
(Imported from [Trac #423](http://hackage.haskell.org/trac/hackage/ticket/423), reported by guest on 2008-12-01)

Right now, <tt>cabal fetch</tt> fetches all missing dependencies of a package along with its source.

In some cases, in particular when studying code, those dependencies are not useful. It would be nice to have an option, say <tt>--no-deps</tt> to fetch just the specified packages.

(This is related to <tt>cabal unpack</tt> -- see #390.)

**Comment by jsl** [comment]
Since as @dcoutts commented in 2009, we now have `--no-deps` option in `cabal fetch` the original purpose of this ticket has been fulfilled. I propose closing. 

While I do agree that `cabal fetch` documentation can be made more clear, I'll follow up on that in other tickets.
