### ISSUE TITLE
bootstrap.sh fails for cabal-install-1.24.0.1 with ghc-8.0.1

### ISSUE THREAD

**Issue by rampion** [haskell/cabal#4165]
`cabal-install-1.24.0.1`'s ./bootstrap.sh contains a dependency on `mtl-2.2.1` which in turn has a dependency on `transformers ==0.4.*`, but `ghc-8.0.1` only comes with `transformers-0.5.0.0`, so the install fails.

**Comment by 23Skidoo** [comment]
I'll look into it, but the bootstrap script does download the latest version of the `.cabal` file from Hackage. C-f `URL_PKGDESC`.

**Comment by rampion** [comment]
nevermind, put this one down as user error.
