### ISSUE TITLE
build-depends in global section in new-style .cabal files are ignored

### ISSUE THREAD

**Issue by bos** [haskell/cabal#417]
(Imported from [Trac #424](http://hackage.haskell.org/trac/hackage/ticket/424), reported by @dcoutts on 2008-12-03)

[http://hpaste.org/12669](http://hpaste.org/12669)

In a .cabal file like:

<pre class="wiki">name:          music
version:       0.0
cabal-version: &gt;= 1.2
build-type:    Simple
build-depends: base == 4
library
  exposed-modules:
    Music
</pre>which uses new-style syntax but puts the build-depends in the global section, the build-depends get ignored.

It should either warn or reject this, or it should automatically propagate such global options into each buildable component.

**Comment by jsl** [comment]
The original issue reported here (in 2008) is that Cabal didn't warn when build-depends appeared in the global section of a new cabal file. I just tested with a new cabal, and it does warn when I put this clause in the global section (output: "Warning: atomic-write.cabal: Unknown fields: build-depends (line 57)").

Can we close this ticket, and re-open or create a new ticket if there are other problems with build-depends?

/cc @tibbe
