### ISSUE TITLE
$ cabal install cabal cabal-install     errors

### ISSUE THREAD

**Issue by boboyada** [haskell/cabal#4178]
1.My os:ubuntu 16.04 lts
2.sudo apt install haskell-platform

$ ghci --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3

$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library 

I follows :https://www.haskell.org/cabal/download.html

3. cabal install cabal cabal-install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cabal-0.0.0.0 (user goal)
next goal: youProbablyWantCapitalCabal (dependency of cabal-0.0.0.0)
fail (unknown package: youProbablyWantCapitalCabal)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

4.why ?

I want update to latest for cabal,but ....

**Comment by 23Skidoo** [comment]
> `cabal install cabal cabal-install`

Try just `cabal install cabal-install`. `cabal` (spelled in lowercase) is a dummy package that points you to `Cabal`. `Cabal` will be installed automatically as `cabal-install` depends on it.
