### ISSUE TITLE
Missing support for directory 1.3.0.0.

### ISSUE THREAD

**Issue by asr** [haskell/cabal#4180]
Cabal and cabal-install don't support directory 1.3.0.0. This version of directory is shipped with GHC 8.0.2 RC2.

**Comment by ezyang** [comment]
Version bound bump was made in 034b44191740214c9e691439b604a8ac95ee9946; fix needs to be backported and do a new release.

Also, gosh, I didn't realize 8.0.2 did a major version bump of directory.

**Comment by asr** [comment]
> Also, gosh, I didn't realize 8.0.2 did a major version bump of directory.

After the above comment, I wrote [this](https://mail.haskell.org/pipermail/ghc-devs/2016-December/013428.html) email.

**Comment by 23Skidoo** [comment]
/cc @bgamari 

Do we need a new Cabal release from the 1.24 branch or can I just bump the bounds on Hackage?

**Comment by 23Skidoo** [comment]
Actually, Cabal-1.24.2.0 supports `directory  >= 1.1 && < 1.4`, so I think the issue should be considered as already fixed.

**Comment by 23Skidoo** [comment]
Please reopen if you disagree.
