### ISSUE TITLE
Cannot build threads-0.5.1.4

### ISSUE THREAD

**Issue by hsyl20** [haskell/cabal#4181]
Latest Cabal in GHC's master repository cannot configure threads-0.5.1.4:
```
> cabal configure --allow-newer=base -v
[..]
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
./dist/setup/setup configure --verbose=2 --ghc --prefix=/home/hsyl20/.cabal
--user --extra-prog-path=/home/hsyl20/.cabal/bin
--dependency=base=base-4.10.0.0 --dependency=stm=stm-2.4.4.1 --disable-tests
--exact-configuration --disable-benchmarks
Configuring threads-0.5.1.4...
Dependency base >=4.4 && <4.10 && ==4.10.0.0: using base-4.10.0.0
Dependency stm ==2.4.4.1: using stm-2.4.4.1
Source component graph: component lib
toConfiguredComponent: base
CallStack (from HasCallStack):
error, called at
libraries/Cabal/Cabal/Distribution/Backpack/ConfiguredComponent.hs:131:20 in
Cabal-1.25.0.0:Distribution.Backpack.ConfiguredComponent
```

However If I remove the upper-bound (< 4.10) on base in threads.cabal, it works.

**Comment by ezyang** [comment]
Couldn't repro with 98678926d97774faf3da22ffbf79846b4355da1f

**Comment by ezyang** [comment]
Couldn't repro with 09865f60caa55a7b02880f2a779c9dd8e1be5ac0 (current latest HEAD).

@hsyl20 what is the specific commit of cabal-install that you are running, and which GHC are you running with?

**Comment by hsyl20** [comment]
I think I was using GHC f1dfce1cb2a823696d6d3a9ea41c2bc73d949f12 with libraries/Cabal 034b44191740214c9e691439b604a8ac95ee9946
But now it works with the latest GHC master, I'll close then.
