### ISSUE TITLE
Fingerprint of Generic representation causes GHC to fail to validate

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4184]
Commit ebcae71d97b24f7052c916d3f7c075a042950099 causes GHC to fail to build, when I update GHC to the latest version, complaining that the saved config file is corrupted when running ghc-cabal-bin. I am not sure what the problem is but it might have to do with the fingerprint varying when built with stage0 versus stage1 compilers, or somewhere in the GHC source code calling the wrong encode/decode function.

**Comment by ezyang** [comment]
OK, so the problem is actually pretty clear: GHC's build system relies on the binary configuration format output by Cabal built with one version of GHC to coincide with the binary format built from the same Cabal but built with a different version of GHC. The fingerprints we use are GHC generated and are of course going to differ between different versions of GHC.

I can't think of a good way out of this quandary, so I think for now I'll revert the commit ebcae71d97b24f7052c916d3f7c075a042950099 and reopen #4059.

**Comment by hvr** [comment]
@ezyang well, while not as as elegant, one can resort to manual versioning... :-)

**Comment by 23Skidoo** [comment]
Fixed in 09865f60caa55a7b02880f2a779c9dd8e1be5ac0.
