### ISSUE TITLE
missing add-source error message

### ISSUE THREAD

**Issue by ciez** [haskell/cabal#4188]
**a-s**  : add-sourced

when multiple local packages should be a-s, 
if a package which should be a-s, is not a-s

actual behaviour _confusing_: 
error message lists a mix of a-s (with valid path) and not a-s (or invalid path) packages.

suggested behaviour: _user friendly_:
error message lists only the missing (which should be, but are not) a-s packages

**Comment by ezyang** [comment]
Hello @ciez, thanks for the report. It would be really helpful for us if you could give us some steps for reproducing the error. For example, do the steps involving creating a sandbox with two subdirectories containing packages, add-sourcing one of them, and then... doing something? I'm not sure what the last step is.

**Comment by ciez** [comment]
Hello @ezyang. Thank you for replying promptly.

I am not able to reproduce this as a simple clean (from 0) 3-project (1 lib + 2 deps) scenario.

closing this until I see this behaviour again so I can reproduce it reliably.
