### ISSUE TITLE
cabal repl does not respect <package>.buildinfo

### ISSUE THREAD

**Issue by spl** [haskell/cabal#4195]
As I discovered in https://github.com/haskell/network/issues/231 for `network`, it seems like `cabal repl` does not respect the `network.buildinfo` configuration in the same way that `cabal build` does. Is this by design or by accident? Should it do so?

**Comment by spl** [comment]
See also https://github.com/commercialhaskell/stack/issues/1239 and https://github.com/commercialhaskell/stack/pull/2242.

**Comment by 23Skidoo** [comment]
>  Is this by design or by accident?

Probably by accident.

**Comment by andreasabel** [comment]
Issue lacks reproducer in its current form.  Please reopen with reproducer (remember to use permalinks, commit hashes etc. to make reproducer time-independent).

**Comment by alt-romes** [comment]
Fixed by #9440
