### ISSUE TITLE
how to fix the error: "cabal exec runghc gave exit code 1"?

### ISSUE THREAD

**Issue by luckypoem** [haskell/cabal#4199]
hi.
```
root@AR:/usr/local/aherrmann.github.io# .cabal-sandbox/bin/blog build
it shows:
...
[ERROR] Hakyll.Core.UnixFilter.unixFilterWith: cabal exec runghc gave exit code 1
root@AR:/usr/local/aherrmann.github.io#
```
how to fix it?
thank u very much!

**Comment by 23Skidoo** [comment]
> `[ERROR] Hakyll.Core.UnixFilter.unixFilterWith: cabal exec runghc gave exit code 1`

Looks like this error originates somewhere in Hakyll library code, please ask on the [Hakyll bug tracker](https://github.com/jaspervdj/hakyll/issues/new).
