### ISSUE TITLE
how to access temporary build-files/logs?

### ISSUE THREAD

**Issue by bos** [haskell/cabal#420]
(Imported from [Trac #427](http://hackage.haskell.org/trac/hackage/ticket/427), reported by claus on 2008-12-05)

when trying to debug an installation failure, it would be most useful to be able to keep the temporary build files (similar to ghc's -keep\* options). Apart from being able to look at things like <tt>config.log</tt>, it would also allow to experiment with patched commands from the verbose build log (which needs the temporary files still
present).

**Comment by andrejpodzimek** [comment]
13 years later, `--keep-build-dir` doesn’t exist any more and there is still no proper way to obtain build logs from failed package builds. For example, you get a `./configure` output fragment saying that your compiler cannot create executables. Oh sure, that same compiler builds the entire Linux kernel and thousands of distro packages, no problem, but then a misconfigured Haskell package claims the compiler doesn’t work. It would be helpful to see what exactly the compiler’s error message was, what exactly the input was, etc. Unfortunately this is nowhere to be found.

**Comment by PACHAKUTlQ** [comment]
it's been 14 years
