### ISSUE TITLE
cabal new-build does not rebuild package if dep changed on separate run

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4202]
Steps to reproduce:
1. Create a project with two packages `p` and `q`, `q` depends on `p`
2. `cabal new-build p q`
3. Modify the first package
4. `cabal new-build p`
5. `cabal new-build q`

Expected behavior: q rebuilds on step 5
Actual behavior: cabal reports "Up to date"

The problem seems to be the logic in `checkPackageFileMonitorChanged`:

```
      MonitorUnchanged () _
          -- The configChanged here includes the identity of the dependencies,
          -- so depsBuildStatus is just needed for the changes in the content
          -- of dependencies.
        | any buildStatusRequiresBuild depsBuildStatus -> do
            regChanged <- checkFileMonitorChanged pkgFileMonitorReg srcdir ()
            let mreg = changedToMaybe regChanged
            return (Left (BuildStatusBuild mreg BuildReasonDepsRebuilt))
```

This tests if any dependencies changed. But this information is populated on a per-run basis. If the dependency finished building successfully in a previous run, it will not have reported as requiring build, and then we'll decide nothing needs building.

Correct fix would be to somehow monitor the dep's outputs (now entirely sure what the correct file to monitor is) so that the change persists across runs.

CC @dcoutts

**Comment by edsko** [comment]
This also happens (probably "obviously") if you run `cabal new-build` inside say, `p`, and then say `cabal new-build` inside `q`. I run into this problem all the time, especially also since we don't have a `cabal new-build all` yet.

**Comment by ezyang** [comment]
Saying a little more: one obvious file to monitor is the monitor file for builds (pkgFileMonitorBuild). But this relies on the monitor file not getting updated when no change was made; I haven't checked if this is the case.

**Comment by edsko** [comment]
Awesome! @ezyang you're a star :)

**Comment by ezyang** [comment]
I have to admit, though, I'm not the biggest fan of this patch :P
