### ISSUE TITLE
Setup doesn't print GHC command line in copy-pasteable form

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4213]
This should be fixed.

**Comment by 23Skidoo** [comment]
Even with `-v3`?

**Comment by ezyang** [comment]
According to @bgamari, then we get a (String, [String]) print.

**Comment by 23Skidoo** [comment]
IIRC the relevant code is somewhere in `Distribution.Simple.Program.*`.

**Comment by 23Skidoo** [comment]
This is fixed now.
