### ISSUE TITLE
Add IsString UnqualComponentName instance (and other no-more-strings)

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4224]
What it says on the tin.

**Comment by bgamari** [comment]
Indeed, I ran into this while trying to build `distributive` with GHC `master`.

**Comment by bgamari** [comment]
To be clear, `distributive`'s `Setup.hs` has the following,
```haskell
rewriteFile (dir </> "Build_" ++ testName suite ++ ".hs") $ unlines ...
```

**Comment by bgamari** [comment]
Ignore my comment about `distributive`; this was due to indiscriminate use of `--allow-newer`. Without `--allow-newer` Cabal links `Setup` against `Cabal-1.24` as expected.

**Comment by phadej** [comment]
@bgamari see: https://github.com/ekmett/bytes/pull/32 I hope I'll get working Setup.hs / doctests.hsc soon (across GHC & Cabal versions, build|new-build)
