### ISSUE TITLE
Make parsec parser compilation unconditional.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4245]
This is blocked on GHC setting up dependencies.

**Comment by phadej** [comment]
@ezyang @hvr @23Skidoo also, can we actually do this if we want to keep `Cabal` compilable with "old" GHC. I.e. We probably have to keep flag, but invert the default to "enabled".

**Comment by 23Skidoo** [comment]
Yeah, it won't build out of the box. Maybe we should update our policy and add a bootstrap script for Cabal as well. IIRC we had a similar issue with `binary`.
