### ISSUE TITLE
Ambiguous interface errors in GHCi, even with -XPackageImports

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#4253]
I'm not sure if this is a `Cabal` or GHC bug, so I'll file here first to see if anyone has any idea. To reproduce, you'll need to install the `GLFW` and `GLFW-b` libraries (two packages that export the same module name), and then try to import it (and run something from it) in GHCi:

```
$ cabal install GLFW-0.5.2.5 GLFW-b-1.4.8.1
$ ghci -XPackageImports
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
λ> import "GLFW" Graphics.UI.GLFW
λ> Window

<interactive>:1:1: error:
    Ambiguous interface for ‘Graphics.UI.GLFW’:
      it was found in multiple packages: GLFW-0.5.2.5 GLFW-b-1.4.8.1
```

GHCi mysteriously complains about `Graphics.UI.GLFW` being ambiguous, even though I explicitly imported it from `GLFW` using `-XPackageImports`.

**Comment by RyanGlScott** [comment]
I've been able to reproduce this on GHC HEAD with `Cabal-1.25.0.0` as well, FWIW.

**Comment by phadej** [comment]
Isn't this a GHC bug. IIRC, ghci parses import statements itself, so might not support PackageImports

**Comment by RyanGlScott** [comment]
I believe that GHCi _does_ support `PackageImports`, as evidenced by this (closed) [GHC Trac issue](https://ghc.haskell.org/trac/ghc/ticket/5979). There's also [this regression test](http://git.haskell.org/ghc.git/commit/02fb36f5a28f2a1e38df7beacc65c0af82562e9a).

**Comment by RyanGlScott** [comment]
Since `GLFW` and `GLFW-b` are rather hefty packages, I prepared a minimal example located at https://github.com/RyanGlScott/cabal-gh4253. To reproduce the issue, clone that repo and do the following:

```
$ cabal install package1/ package2/
$ ghci -XPackageImports
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
λ> import "package1" DuplicateModuleName
λ> Window

<interactive>:1:1: error:
    Ambiguous interface for ‘DuplicateModuleName’:
      it was found in multiple packages:
      package1-0.1.0.0 package2-0.1.0.0
```

**Comment by 23Skidoo** [comment]
If this doesn't happen with `ghc --make`, it's definitely a GHCi bug.

**Comment by RyanGlScott** [comment]
Despite my best efforts, I cannot find a way to make this happen with `ghc --make`. So I'll close this issue in favor of https://ghc.haskell.org/trac/ghc/ticket/13168.

**Comment by saurabhnanda** [comment]
I'm facing something similar at http://stackoverflow.com/questions/41896211/how-to-use-packageimports-extension-to-shadow-a-module

@RyanGlScott based on your research, is this a GHCi only bug, or does this happened in GHC compiled code as well? My initial research seems to show that it happens in GHC-compiled code as well (although I didn't try to isolate the case like you did).
