### ISSUE TITLE
cabal fetch does not obey constraints in config file

### ISSUE THREAD

**Issue by kenta2** [haskell/cabal#4256]
If there are "constraint:" lines in the user's ~/.cabal/config file, then "cabal install" will obey them, but "cabal fetch" will not to fetch given package.  I think the problem is in the difference in planPackages (and resolverParams) in cabal-install/Distribution/Client/Install.hs and cabal-install/Distribution/Client/Fetch.hs

**Comment by ezyang** [comment]
Thanks for the report @kenta2. I think we are unlikely to fix this without a little extra help; would you be interested in helping contribute a fix? Happy to advise.

**Comment by 23Skidoo** [comment]
Should be more or less easy to fix, you just need to pass `configExConstraints` to the solver in `fetch` code. Feels kinda ad hoc though, maybe we should add `SolverFlags` and a `solver` section to the config.

**Comment by jraygauthier** [comment]
it does not either support the `--constraints=""` cli argument as does the install command.

**Comment by arrowd** [comment]
The command also doesn't support `--default-user-config` flag. I was hoping to feed Stackage-generated `cabal.config` file to `cabal fetch`, but failed.

**Comment by Mikolaj** [comment]
I'm taking the liberty of closing this ticket due to its age and inactivity. Please open a new one if/when you are able to reproduce with an up to date cabal (assuming you are still using the v1- cabal API). Thank you for the report!
