### ISSUE TITLE
Expensive assertion in Distribution.Solver.Modular.Linking

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#4258]
The assertion at https://github.com/haskell/cabal/blob/6d993e21bb39f6a2b6f22dc5043b4a4db65b4c35/cabal-install/Distribution/Solver/Modular/Linking.hs#L138 makes the solver run slowly when there are many setup dependencies, especially with --reorder-goals.  Solving for jsaddle-warp with new-build is a good example (See https://github.com/haskell/cabal/issues/4192#issuecomment-269940713).  When I ran `cabal new-build jsaddle-warp --dry-run` with GHC 8.0.1, it took almost nine minutes with the assertion and about eight seconds without.

I didn't see any obvious ways to improve the performance.  However, even if we minimized the effect of assertions on runtime, assertions could still affect performance measurements during development.  It's easy to accidentally compare a cabal executable with assertions enabled to one without assertions.

I'm not sure of the best solution.  Here are some ideas:

- Remove `ghc-options: -fno-ignore-asserts` from cabal.project and then enable assertions for unit tests in CI.
- Add another build flag to control just the expensive assertions, and turn them on in CI.  Other assertions would be enabled in cabal.project.
- Print a warning when assertions are enabled.

**Comment by ezyang** [comment]
The way that GHC's RTS handles expensive asserts is like (2): by default they are not turned on, but if you turn on a "sanity" mode it will start running with them. The RTS asserts are toggleable at runtime but that will probably be inconvenient to do in the solver unless we're threading around some solver environment (maybe we are?)

**Comment by 23Skidoo** [comment]
> Print a warning when assertions are enabled.

We should definitely do that at least.

**Comment by grayjay** [comment]
Thanks for the feedback.  I added a build flag in #4346 so that it would be easy to call the conditional assert from anywhere in cabal-install.

I think it would also be useful to warn when assertions are enabled.  I'm not sure where we should put the warning, though.

**Comment by grayjay** [comment]
> > Print a warning when assertions are enabled.
> 
> We should definitely do that at least.

I opened a new issue: #4377
