### ISSUE TITLE
Mac OS X RPATH-related issue when using `cabal new-repl`

### ISSUE THREAD

**Issue by bugthunk** [haskell/cabal#4263]
`cabal-install` HEAD used, started from scratch after purging `~/.ghc` and `~/.cabal`. `cabal new-build` builds the binary as expected, but `new-repl` fails, saying:

```
$ cabal new-repl app-server
In order, the following will be built (use -v for more details):
 - app-0.0.1 (exe:app-server) (ephemeral targets)
Preprocessing executable 'app-server' for app-0.0.1...
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: /Users/fcar/.cabal/store/ghc-8.0.2/servant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62/lib/libHSservant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62-ghc8.0.2.dylib (dlopen(/Users/fcar/.cabal/store/ghc-8.0.2/servant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62/lib/libHSservant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62-ghc8.0.2.dylib, 5): no suitable image found.  Did find:
	/Users/fcar/.cabal/store/ghc-8.0.2/servant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62/lib/libHSservant-auth-server-0.2.1.0-efe758625dac2edc974329c8463fa768f38aba7638472ecdb2325ccd5b848f62-ghc8.0.2.dylib: malformed mach-o: load commands size (35832) > 32768)
cabal: repl failed for exe:app-server from app-0.0.1.
```

**Comment by bugthunk** [comment]
Furthermore, maybe it's related to GHC ticket https://ghc.haskell.org/trac/ghc/ticket/12479, but `cabal repl` with a cabal sandbox works as expected.

**Comment by christiaanb** [comment]
No surprise there... sadly.... the whole range of `cabal new-<command>` will run into this bug. The problem is that, for "old-style" builds, we now put `.dylib` files all into one directory, so that only one `RPATH` per package datebase is needed (so two in most cases: `global` and `user`).

With "new-style" builds, all the `.dylib` files still each go into their own directory. I have no idea how the hashing works for new-style, but I guess it should be possible to put the `dylib`s can go into the shared build-store lib directory without conflicts. @dcoutts  probably knows.

**Comment by 23Skidoo** [comment]
@christiaanb Thanks! That's what I suspected.

This shouldn't be very hard to fix, so I think we should try to get the fix into 2.0.

**Comment by christiaanb** [comment]
So the line that needs "fixing" is: 
https://github.com/haskell/cabal/blob/8d2229ab4751622b20910dfc9d5307fc1bfd89d9/cabal-install/Distribution/Client/ProjectPlanning.hs#L2594

That `dynlibdir` shouldn't be equal to `libdir`, which in turn is equal to `prefix/lib`, where `prefix` is the `$STORE/package-hash`. It should be equal to `$STORE` or `$STORE/dynlib`. Whethe the `dylib`s already get the correctly hashed names I have no idea.

**Comment by ezyang** [comment]
I think it should be OK to dump all of the dynamic libraries for `.cabal/store` in a single directory. @christiaanb do you want to submit a patch? `dylib`s are hashed correctly; they will look like `libHSp-0.1.0.0-hash-ghcx.y.z.dylib`

**Comment by ulysses4ever** [comment]
Appears to have been fixed in 

- #4656 

Please, reopen if not.
