### ISSUE TITLE
error, called at ./Distribution/Client/ProjectPlanning.hs:1381:21

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4266]
Happens with current master: eda30d314dba478d2830744f9f3ef9adeb28b938

Doesn't happen with 
```
ii  cabal-install-head                                   1.25+git20170113.0.cd90a31-3~16.04
```

cc @Ericson2314 

---

I tried to build `servant-js` repository, where I added (`cabal get servant-0.9`)

```diff
       Servant.JSSpec.CustomHeaders
+  build-tool-depends: hspec-discover:hspec-discover >=2.4.0 && <2.5
   build-depends:     base
```

---

Let's avoid partial functions at all costs, or at least print reasonable diagnostics. Please.

**Comment by Ericson2314** [comment]
I'm sorry! I thought those were pre-existing invariants. Any idea which pattern isn't getting matched? I'll be at work soon and look at this then.

**Comment by phadej** [comment]
It might be not your fault, but I guess you know best what `build-tool-depends` adds to the planning.

https://github.com/haskell/cabal/blob/eda30d314dba478d2830744f9f3ef9adeb28b938/cabal-install/Distribution/Client/ProjectPlanning.hs#L1381
is the check
