### ISSUE TITLE
Changes in `D.S.Build` break stacks setup-hs--shim

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4273]
Especially the change of `initialBuildSteps` signature.

cc @ezyang

```
    /home/ogre/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:28:69: error:
        • Couldn't match expected type ‘Distribution.Types.ComponentLocalBuildInfo.ComponentLocalBuildInfo’
                      with actual type ‘Distribution.Verbosity.Verbosity’
```

For the reference: https://github.com/commercialhaskell/stack/blob/master/src/setup-shim/StackSetupShim.hs

---

I guess we cannot make migration story better, but at least `initialBuildSteps` needs a haddock.

**Comment by phadej** [comment]
It seems that sometimes in stack internals changed as it tries to compile shim with `Cabal` in the repository (I have `stack-head` as it uses hackage-security). So with next `stack` the development of `cabal-install` will be impossible, due this "bug". I guess @ezyang is best one to say how to make stack's shim compatible

**Comment by ezyang** [comment]
Probably the easiest way to keep BC is to rename the new initialBuildSteps to componentInitialBuildSteps, and then add back initialBuildSteps whose semantics is "run initial build steps for all components"
