### ISSUE TITLE
Shorter Travis build times

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4277]
Travis takes too long to run; esp Mac OS X on GHC 8.0.1 which is running up against the limit.  What can we do?  I see two main ways we can win a lot:

1. cabal-install library.  Currently building cabal-install takes 740s (12min), but this far bigger than it should be: we actually have to build many modules FOUR times (134+70+72+119) because the test suites can't share a library between themselves. Primary objection to this is that we don't really want external clients to start depending on this API. I don't know a good way around this.

2. Saving build products.  Currently building takes 1143s (19min) while tests take 740s (12min).  The tests are embarassingly parallel, so they could all be run in parallel (matrix style), IF ONLY we had a way of efficiently sharing the build products.

(1) is easy to do.  (2) is a bit more difficult, for a few reasons:

- Travis doesn't have any way of blocking builds, waiting for others
  to happen.  This has been requested at https://github.com/travis-ci/travis-ci/issues/249
  but Travis is not planning to implement it.  So we need to manually
  implement this (more on this below).

- We need to store the build products somewhere, so that we can grab
  them when we do the second build.  Preferably somewhere free.  There
  are a number of candidates so we'd have to pick one.

So, here is a straw proposal:

1. We configure Travis on the main Cabal repo to ONLY build executables.
   When the build finishes, the Travis script pushes the binaries to a different,
   Cabal binaries repository.

2. This Cabal binaries repository has, itself, a Travis script, which
   takes the binaries and runs the CI tests on them.  It also has an
   EXTRA Travis webhook to report the result of these runs to the
   ORIGINATING issue.

The biggest technical issue is probably whether or not GitHub can deal
with a repository that is repeatedly having binaries pushed to it.
One possiblity: make a branch per binary, and then regularly clear out the
branches.

Timings were based on https://travis-ci.org/haskell/cabal/jobs/195667947

**Comment by 23Skidoo** [comment]
> we actually have to build many modules FOUR times (134+70+72+119) because the test suites can't share a library between themselves.

One thing we can do here is add a special `cabal-install.cabal` file for CI only that has those modules exposed as a library. We'll have to be careful to keep both `.cabal` files in sync, though.

> One possiblity: make a branch per binary, and then regularly clear out the
branches.

Or just use `commit --amend` and `push -f`. This is how haddocks deployment to `cabal-website/gh-pages` works already.

**Comment by phadej** [comment]
I could develop `cabal-refact` to be able to do `.cabal` file editing on travis, if would help? I plan to make a "refactoring" generating `exposed-modules` anyway...

**Comment by ezyang** [comment]
@phadej That probably would be the most robust way of doing it, assuming cabal-refact doesn't take too long to build.

**Comment by ezyang** [comment]
OK, prototype is here: https://github.com/ezyang/sake-bot
I tested the strategy with a small repo.

Look at that link for full info, but the proposal is this:

1. Change cabal's travis.yml to ONLY build Cabal/cabal-install. After it's done, it Travis will push the built commit to a new Git repo that accumulates Cabal build products.
2. That repo will be setup on Travis, and will start running the tests.
3. Using the sake-bot, the SECOND Travis instance will report test results back to the ORIGINATING commit in Cabal.

This has all been setup on https://github.com/ezyang/sozu/commits/master ; look at the build results for the first few commits to see how it will look.

If people like the plan, I'll start carving up Cabal's Travis to do this.

**Comment by kolmodin** [comment]
I find Mikhail's solution in https://github.com/haskell/cabal/issues/4277#issuecomment-275808894 is far simpler than the alternatives.

Another solution would be to add the each unit test separately to theTravis  test matrix instead of all together.

**Comment by grayjay** [comment]
We could also run the solver-quickcheck test suite in fewer builds, since it shouldn't be platform dependent.

**Comment by 23Skidoo** [comment]
One potential problem with using GH repos for storing binary artifacts is that GH doesn't allow storing large files (>100 MiB IIRC). However, I think that we can use GitHub releases (which use S3 under the hood) to store large files, as they are allowed to be quite large.

**Comment by ezyang** [comment]
> Another solution would be to add the each unit test separately to the Travis test matrix instead of all together.

While this would get us down the build limit, we'd end up wasting a lot of time rebuilding the build products each test. We're already doing this now (Cabal versus cabal-install tests) but I'd rather not.

> We could also run the solver-quickcheck test suite in fewer builds, since it shouldn't be platform dependent.

Yes, although the solver-quickcheck tests are pretty speedy (10s), so we wouldn't get that much benefit.

> One potential problem with using GH repos for storing binary artifacts is that GH doesn't allow storing large files (>100 MiB IIRC). However, I think that we can use GitHub releases (which use S3 under the hood) to store large files, as they are allowed to be quite large.

In my local checkout, the largest individual file is 40MB (the cabal executable.) So... we should be OK.

**Comment by bennofs** [comment]
Travis appears to run at most 4 builds from the same matrix in parallel (not sure if that's a temporary limitation or always the case), so splitting it up won't improve total build time. 

Another possibility for improving travis build time would be using the travis build cache to get incremental rebuilds (and cache library dependencies).

IMO, the solution using two repos is quite a hack (it makes understanding where to find the results much harder for contributors). Also, that probably won't work well with the github status API, right? It'll then show "All checks passed" even when the tests failed, won't it?

**Comment by ezyang** [comment]
@bennofs 

> Also, that probably won't work well with the github status API, right? It'll then show "All checks passed" even when the tests failed, won't it?

Nope, that's what sake-bot is for: it takes the build status from the second repo and posts it to the first repo. So you'll see if tests succeeded or not, and you'll be able to look at the usual place to find a link to the actual build result. So yes, it's kind of a hack, but I don't think it's that terrible.

> Another possibility for improving travis build time would be using the travis build cache to get incremental rebuilds (and cache library dependencies).

We already cache library dependencies. At least with the current new-build implementation, an incremental rebuild would not be wise because there are a few known new-build recompilation bugs (e.g., failing to reconfigure when LBI format changes, known GHC recompilation bugs related to flags, etc.) so we could end up in a situation where Travis thinks the build is OK, but actually it's not.

**Comment by ezyang** [comment]
One thing to wonder about in the two repo setup: what exactly should get pushed to the second repo? At a first glance you might think just the binaries we want to test should be enough, but some tests involve compiling against the Cabal library, so all of that data also needs to be propagated. Should we copy all of `.cabal` into the Git repository, or should we be more surgical, or should we try to use Travis-side caching on the other end to handle this?

**Comment by ezyang** [comment]
Here is the WIP branch for two-repository Travis builds. https://github.com/ezyang/cabal/pull/9

It looks like the tax for spinning up a totally new instance is something like 5min (in particular PPA downloads are *really slow*). The build time numbers are bogus because I turned on heavy caching for dev; I'm going to do a full rebuild now and see what the end to end numbers end up looking like.

**Comment by 23Skidoo** [comment]
This scheme has been implemented, though we're still often bumping into the limit on OS X. Feel free to open new tickets for further improvements.
