### ISSUE TITLE
cabal exec uses default ghc version instead of one appropriate to sandbox

### ISSUE THREAD

**Issue by claudeha** [haskell/cabal#4287]
`cabal exec` uses `ghc` instead of the version used to install packages to the sandbox.  Moreover `-w` is not recognized by `cabal exec`, so I can't force which version it uses.

    $ cabal sandbox init
    Writing a default package environment file to
    /home/claude/code/local/haskell/sandbox-bug/cabal.sandbox.config
    Creating a new sandbox at
    /home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox
    $ cabal install -w ghc-8.0.1 containers --ghc-options=-optl-no-pie
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox
    Downloading containers-0.5.9.1...
    Configuring containers-0.5.9.1...
    Building containers-0.5.9.1...
    Installed containers-0.5.9.1
    Updating documentation index
    /home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox/share/ghc-8.0.1/doc/index.html
    $ cabal exec -v -- ghci-8.0.1
    Using a sandbox located at
    /home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox
    /home/claude/opt/bin/ghc --print-global-package-db
    /home/claude/opt/bin/ghci-8.0.1
    GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
    /home/claude/opt/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
    $ ghc -V
    The Glorious Glasgow Haskell Compilation System, version 8.0.2
    $ cabal exec -w ghc-8.0.1 -- ghci-8.0.1
    cabal: unrecognized 'exec' option `-w'

I guess a simple fix might be to add `cabal exec -w` option?  (Possibly other commands could benefit from a `-w` option too.)

**Comment by dcoutts** [comment]
So it looks like exec is setting up the GHC_PACKAGE_PATH based on the default ghc, rather than the one used in the construction of the sandbox (since the sandbox doesn't have any notion of a selected compiler).

We should confirm when we implement cabal new-exec that we use the ghc path for the selected compiler.

**Comment by 23Skidoo** [comment]
```
$ cabal exec -v -- ghci-8.0.1
Using a sandbox located at
/home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox
/home/claude/opt/bin/ghc --print-global-package-db
/home/claude/opt/bin/ghci-8.0.1
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
/home/claude/opt/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
```

Here, the correct `ghci` version (8.0.1) is invoked, but

**Comment by claudeha** [comment]
As requested in IRC:

    $ cabal exec bash
    $ echo $GHC_PACKAGE_PATH
    /home/claude/code/local/haskell/sandbox-bug/.cabal-sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d:/home/claude/opt/lib/ghc-8.0.2/package.conf.d

**Comment by dcoutts** [comment]
So I think this is hard to fix in the current sandbox implementation because the sandbox lacks any notion of a selected compiler. The same sandbox can be used with any number of ghc versions at once, and none is privileged. A `cabal exec -w ghc-8.0.1` flag would be possible but it's not practical to expect users to use it.

On the other hand this should work fine with the new project based implementation since that does have a notion of the currently selected/default compiler.

**Comment by 23Skidoo** [comment]
> The same sandbox can be used with any number of ghc versions at once, and none is privileged.

This is not quite correct, the compiler that the user specified via `cabal configure -w` is considered to be the currently selected one, though there still may be some places where we forget to take it into account (like `cabal exec`).

**Comment by ezyang** [comment]
Given that this will eventually be a legacy codepath, I'm OK with adding `-w` or, if what @23Skidoo says is true, just fixing the code to take that into account. @claudeha, fixing this bug probably will not be a priority, FYI, but if you submit a patch I'll try to merge it.

**Comment by claudeha** [comment]
In my particular instance, I was using sandboxes without a `.cabal` file, so I'd prefer `-w` for `cabal exec` rather than the `cabal configure -w` mechanism.  But it's not such a high priority for me either (so I won't be submitting a patch), it was not too much work to recreate my sandbox with the latest `ghc`.

**Comment by phadej** [comment]
sandbox functionality is removed.
