### ISSUE TITLE
sdist fails with non-installed custom-depends:

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4293]
```
$ cabal sdist
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
dist/setup/setup.hs:1:1: error:
    Failed to load interface for ‘Distribution.Extra.Doctest’
    Use -v to see a list of the files searched for.
```

Do we need `cabal new-sdist`?

**Comment by phadej** [comment]
Or is there some workaround (the dependency is in store)?

**Comment by 23Skidoo** [comment]
> Do we need `cabal new-sdist`?

Probably yes.

**Comment by 23Skidoo** [comment]
>  or how to say to `sdist` "Don't configure" / "Pretend `build-type: Simple`".

I don't think there is a way to do this now, but it should be possible to add by tinkering with `D.S.SetupWrapper`.

**Comment by ezyang** [comment]
Workaround should be to set `builddir` to new-build's created dist directory.

**Comment by RyanGlScott** [comment]
It should be noted that this issue [prevents the `gl` package](https://github.com/ekmett/gl/issues/17) from using `new-build` entirely.
