### ISSUE TITLE
Allow per file gcc flags while compiling c code for ffi

### ISSUE THREAD

**Issue by piyush-kurur** [haskell/cabal#4294]
At the onset let me say that this is a feature request that not many people would need. However if one wants to do platform dependent compilation this is valuable.

The problem is the following: Let us say you have two implementation for the stream cipher chacha20 one tuned to use some processor extension like avx2. and another which does not have it. For gcc to be effictive we need to compile with mavx2 flag. However we do not want the other implementation to be compiled with mavx2 (this could lead to bad performance or worse errors). 

Currently we can do a flag based setting of appropriate options but this means we cannot use some cpu probing instructions to select implementation at runtime (there by making generic executables say for distribution through os package system). This means that for example while cross compiling for package distributions, one needs to be conservative and use only the portable implementation.

For more details see the discussion raaz-crypto/raaz#300

**Comment by ezyang** [comment]
I agree that the use-case is reasonable but I am having trouble thinking of what a reasonable format in the Cabal file would look like, we don't really have any precedent for this kind of option. There's a more general problem where Cabal scales poorly if you have a very complicated C project that needs building, since it really doesn't have any of the hooks or smarts you might need for a real world C project.

This is unlikely to get fixed unless someone steps up with a format proposal and some code.

**Comment by piyush-kurur** [comment]
Let me see what can be done @TomMD @vincenthz can we work on this together. It seems we are the
ones most effected by this.

**Comment by TomMD** [comment]
@piyush-kurur Thank you for starting this issue.  I don't have the bandwidth at present to contribute technically but I'm happy to participate in discussions.

@ezyang The need for concrete contributions is noted.  For what it's worth the uses have always been very small bits of C code for point-solutions in larger Haskell programs.  For example, ShareMonad needed an easy way to fold a mask-then-xor across very large tables (16MB+) as many times a second as siliconly possible.  Similarly piyush needs AVX for stream ciphers, everyone wants aes-ni for aes, some of us use rdrand for randoms, etc etc.  None of these involved very much C code, but lots of build system fiddling.

**Comment by piyush-kurur** [comment]
@TomMD @ezyang  I just forked cabal and will be tracking changes in this branch

 https://github.com/piyush-kurur/cabal/tree/per-file-cflags

If I understand correctly, the first step is to get a consensus on how this is to be represented in the cabal file. As a starting point let us have the field cc-options-for which takes a filename and the cc-flags to be used for that particular file. 

```
cc-options-for: foo/bar/biz.c -mvectorise -mnative
```

The sematics of this would be as follows.

(1) While building, the builder program should compile the foo/bar/biz with the options given. For example the above field should result in cabal-install compiling the above code as follows.

```
gcc -c foo/bar/biz.c -mvectorise -mnative

```

(2) The filename given in cc-options-for should be considered as being entered in the c-sources and in particular a cc-options-for with empty compiler option should be equivalent to just c-sources

(3) We can also consider file patterns that are allowed in c-sources in cc-options. This allows things like

````
cc-options-for: x86-avx2/*.c   -mavx2
```

**Comment by piyush-kurur** [comment]
The other option is to have a separate cc-flags matcher file where the file (file-pattern) vs cc options are listed. It can then be activated by some kind of user hooks.  Older cabals just ingore this.

**Comment by piyush-kurur** [comment]
Just some more clarification. Often the code is compiled on a machine (let me call it the builder) that is different from the machine on which it is run (let me call it the target). To be specific let us consider an avx2 optimised function bar  inside the  foo.c. It might be the case that builder does not support avx2 but the target might. I see one solution to it

1. Compile of foo.c with the flag -avx2 using whatever proposal we come up with 
2. Decide to call bar via ffi only if the target supports avx2. This can be achieved by a runtime test (cpuid kind of instruction) or through other means (user on the target machine first tunes his application to see what are supported functions and it is her responsibility to call the right function)
3. We can also modularise it if we have something like backpack

**Comment by piyush-kurur** [comment]
Pointed out by @ongy 

 http://stackoverflow.com/questions/12925989/gcc-enable-compiler-flags-only-on-specific-functions

This should solve a lot of problems

**Comment by piyush-kurur** [comment]
Here is more details.

https://gcc.gnu.org/wiki/FunctionSpecificOpt

While I have not tried it out, it looks like this should do the trick and I am okey with closing this issue at least for time being.

**Comment by ezyang** [comment]
OK, let's close this for now.
