### ISSUE TITLE
regex-compat/regex-posix inexplicably buggy on Windows, DO NOT USE

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4336]
See: http://stackoverflow.com/questions/39047317/simple-regular-expression-substitution-crashes-on-windows-using-regex-compat/39101634#39101634 I discovered this while using regex-compat in the spirit of using an existing dependency that we had in our test suite.

On one of my Windows computers, using the regular expressions was sufficient to cause my program to hang indefinitely; on AppVeyor, regex-compat seems to misinterpret the regular expression in some situations (for example, if I have a regex with a lot of escaped backslashes, it will stop matching too early) and also causes the program to run *really slowly*.

So... yeah. Don't use regex-compat/regex-posix on Windows.

**Comment by 23Skidoo** [comment]
I remember bumping into this, but then it mysteriously went away after recompilation, so I never bothered to investigate.

**Comment by 23Skidoo** [comment]
The workaround is to use `regex-tdfa`, I guess?

**Comment by ezyang** [comment]
Yeah; in fact, it's a complete drop-in replacement. Patch coming.

**Comment by RyanGlScott** [comment]
AFAICT, this was implemented in 2ea28cab3ce569b388b5226f0f10605f3d5ca2c1, so closing.
