### ISSUE TITLE
Add option to generate *nix register/unregister scripts on Windows

### ISSUE THREAD

**Issue by alethea** [haskell/cabal#4356]
I'm working on packaging some Haskell libraries for MSYS2, and it would be great if I could pass a flag to generate *nix shell style registration scripts instead of batch files.

**Comment by jneira** [comment]
From `cabal help v1-register`:

> The v1-register command is a part of the legacy v1 style of cabal usage.

> It is a legacy feature and will be removed in a future release of
> cabal-install. Please file a bug if you cannot replicate a working v1- use
> case with the nix-style commands.

So i am afraid it is very unlikely new features will be added. I am gonna close this one if you dont mind, feel free to reopen or ask any question about how to replace v1-register functionality

**Comment by fgaz** [comment]
@jneira this ticket is about Cabal's register command, not cabal-install's

**Comment by jneira** [comment]
> @jneira this ticket is about Cabal's register command, not cabal-install's

oh, sorry for the noise here, reopening
