### ISSUE TITLE
[Meta] Rebase only merges?

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#4359]
I just noticed that we're (apparently) not doing merges any more, but only allowing rebase + FF... I think this may be a mistake unless we're willing to enforce stricter standards on individual commits including that they compile individually + have reasonable commit messages (or that they're squashed into one commit if they don't). WDYT? Am I being overly paranoid?

**Comment by BardurArantsson** [comment]
I should add that I'm actually a fan of the rebase-only approach, but my reason for it is that it makes the logs a lot cleaner. However, if we're not enforcing good commit messages and a "no spurious/bad commits" policy that reasoning doesn't apply.

I should also emphasize that realize that *many* (if not most) contributors actually do adhere to this pretty closely, but it can be quite a high hurdle for people who are new to git or to projects with such high standards.

**Comment by ezyang** [comment]
I was in the habit of rebase merging PRs (because I like clean history), so I flipped it to be rebase only. Is the main motivation for CI'ing every commit if you rebase only to keep bisect working? If so clean history is not worth it. I flipped it back to merge only.

**Comment by BardurArantsson** [comment]
Yeah, it's primarily about bisect. (It's not that it makes bisect *impossible* per se, but it can make it *really* **really** annoying if e.g. 4 out of 6 commits don't actually build.

Anyway, as you've changed back to merge only, I'm closing this. :)
