### ISSUE TITLE
Improve error message about stanzas

### ISSUE THREAD

**Issue by chrissound** [haskell/cabal#4361]
I've just added the following lines in my **.cabal** file:
```
source-repository    head
  type:              git
  location:          https://github.com/exampleabc
```

And get an error message of:
```
FromString "Plain fields are not allowed in between stanzas: F 15 \"data-files\" \"templates/*\\n, templates/heist/*\\n, templates/cache/.keepme\"" (Just 15)
````

"Stanza" is mentioned only briefly within the cabal user guide (https://www.haskell.org/cabal/users-guide/installing-packages.html). Could we add documentation for this or improve the error message?

It works correctly if I move those lines to the end of the **.cabal** file.

**Comment by ezyang** [comment]
@chrissound It's hard to tell because you haven't posted the whole Cabal file, but I'm guessing you did something like:

```
source-repository    head
  type:              git
  location:          https://github.com/exampleabc
data-files: blah blah blah
...
```

Which, apparently, the parser doesn't know how to handle.

**Comment by chris-martin** [comment]
I just got this error, and I'm still confused about what I did wrong.

**Comment by chris-martin** [comment]
It is trying to say that plain fields aren't allowed *after* stanzas?

**Comment by hvr** [comment]
@chris-martin exactly that, yes

**Comment by phadej** [comment]
I close this, as error message is improved
