### ISSUE TITLE
bootstrap.sh sometimes picks up wrong Cabal library when building Setup

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4365]
@ongy on `#haskell` IRC tried to bootstrap cabal-install using the bootstrap.sh script, but ran into the error:

```
Error during cabal-install bootstrap:
Building the hackage-security package failed.
cleaning...
Linking Setup ...
Configuring cabal-install-2.1.0.0...
Setup: Encountered missing dependencies:
Cabal ==2.1.*,
HTTP >=4000.1.5 && <4000.4,
bytestring >=0.9 && <0.10.2,
directory ==1.1.*,
hackage-security >=0.5.2.2 && <0.6,
network >=2.4 && <2.6,
process >=1.0.1.1 && <1.1.0.2

Error during cabal-install bootstrap:
Configuring the cabal-install package failed.
./bootstrap.sh  61.28s user 3.28s system 97% cpu 1:06.55 total
2 ongy@ongy-lap /tmp/cabal/cabal-install (git)-[master] %
```

When we checked the version of the Setup script for cabal-install, we found `./Setup --version: Cabal library version 1.24.0.0`

So, for some reason, GHC is picking the wrong version of the library when building Setup. This is not too surprising, seeing as bootstrap.sh doesn't try especially hard to pick the correct package. Maybe GHC shadowed the new Cabal library for some reason. bootstrap.sh should try harder to select the correct package.

**Comment by befedo** [comment]
Got the same issue. Is there any WIP on this?

**Comment by jneira** [comment]
bootstrap.sh does not exist anymore, so i am gonna close it optimistically, betting the newbootstrap.py does not suffer the issue 😄
