### ISSUE TITLE
Segfault with process-1.2.3.0

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4367]
I've managed to tickle segfaults in our test suite when built against process-1.2.3.0, in TestSuiteTests/ExeV10/setup-no-tix.test.hs Freeze/legacy-disable-benchmarks.test.hs CustomPreProcess/setup.test.hs CustomPreProcess/setup.test.hs. I'm not sure why it doesn't repro on CI.

**Comment by jneira** [comment]
I think we can close this as it is not reproducible anymore
