### ISSUE TITLE
openBinaryTempFileWithDefaultPermissions: does not exist

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4368]
I got this failure:

```
C:\projects\cabal\cabal-testsuite\PackageTests\BuildToolsPathInternal\cabal.dist\work\.\dist\build\x86_64-windows\ghc-8.0.1\build-tools-path-internal-0.1.0.0\c\my-custom-preprocessor\build\my-custom-preprocessor\autogen\:
openBinaryTempFileWithDefaultPermissions: does not exist (No such file or
directory)
```

in this Windows build https://ci.appveyor.com/project/23Skidoo/cabal/build/%233257%20(master)

I guess autogen was not created? Maybe we should just have `writeAtomic` always ensure the temporary directory exists.

**Comment by jneira** [comment]
closing optimistically as we don't observe this error in last GH ci
