### ISSUE TITLE
cabal new-build on GHC 8.0.2 can't bootstrap itself

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4372]
Here is a representative failure: https://travis-ci.org/haskell/cabal/jobs/207561490

Unfortunately, I don't seem to be (easily) able to reproduce locally.

**Comment by ezyang** [comment]
OK, the problem seems to be that hackage-repo-tool requires `directory < 1.3`

**Comment by 23Skidoo** [comment]
Looks like `hackage-repo-tool` was fixed, closing.
