### ISSUE TITLE
dynamic-library-dirs on GHC 8.0.2 Mac OS X is not properly feature gated

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4374]
When I build unbounded-delays with a HEAD Cabal in the build plan on GHC 8.0.2 on Mac OS X, it appears that we use dynamic-library-dirs when installing the library, even though ghc-pkg with GHC 8.0.2 doesn't understand it.

```
Configuring unbounded-delays-0.1.0.9...
Building unbounded-delays-0.1.0.9...
Preprocessing library unbounded-delays-0.1.0.9...
[1 of 2] Compiling Control.Concurrent.Thread.Delay ( Control/Concurrent/Thread/Delay.hs, dist/build/Control/Concurrent/Thread/Delay.o )
[2 of 2] Compiling Control.Concurrent.Timeout ( Control/Concurrent/Timeout.hs, dist/build/Control/Concurrent/Timeout.o )
Installing library in
/Users/travis/.cabal/store/ghc-8.0.2/unbounded-delays-0.1.0.9-72a613275973bec80e87943ec6d825052a7beb0cfdb0b6726e01b577bfdf31c7/lib
Creating package registration file:
/Users/travis/build/haskell/cabal/dist-newstyle/tmp/package-registration-726031364407052494
Warning:
/Users/travis/build/haskell/cabal/dist-newstyle/tmp/package-registration-726031364407052494:
Unrecognized field dynamic-library-dirs on line 26
```

Travis log https://travis-ci.org/haskell/cabal/jobs/207615132

CC @christiaanb

**Comment by christiaanb** [comment]
https://github.com/ghc/ghc/blob/ghc-8.0/compiler/main/PackageConfig.hs#L130 says that ghc-8.0.2 does know `dynamic-library-dirs`. How are you so sure that it's ghc-pkg that's creating that warning?

**Comment by ezyang** [comment]
You're right! It's not ghc-pkg, it's cabal, because this CI build is using an old version of cabal-install?

This is a bit unfortunate (cabal-install-1.24.0.0 fails in a hard to understand way with GHC 8.0.2) but I am not sure what we can do...

**Comment by 23Skidoo** [comment]
> I am not sure what we can do...

Use `cabal-install-head` from @hvr's repo instead of 1.24?

**Comment by ezyang** [comment]
Nah, 1.24.0.2 works OK; I had forgotten to update the Mac OS X installation procedure ;)

**Comment by ntc2** [comment]
Related: https://github.com/TomMD/crypto-api/issues/26
