### ISSUE TITLE
Dependency cycle when building cabal master using cabal master

### ISSUE THREAD

**Issue by cocreature** [haskell/cabal#4388]
I built cabal from the master branch (40318a77f2bacfc8b82b466ff72d344d954b9602) using cabal 1.24. Now, I am trying to rebuild cabal at the same commit using the previously built cabal. However, I’m seeing the following error:

```
internal error in InstallPlan.fromSolverInstallPlanWithProgress: 
The following packages are involved in a dependency cycle cabal-testsuite-2.1.0.0-inplace
The following packages are involved in a dependency cycle cabal-install-2.1.0.0-inplace

CallStack (from HasCallStack):
  error, called at ./Distribution/Client/InstallPlan.hs:261:25 in cabal-install-2.1.0.0-inplace:Distribution.Client.InstallPlan
```

**Comment by 23Skidoo** [comment]
Which command do you use to build the project?

**Comment by cocreature** [comment]
Oh sorry, I completely forgot about that. I ran `cabal new-build all` and `cabal new-build cabal-install`. Both commands produce the same error.

**Comment by grayjay** [comment]
I ran `git bisect` and found that it was introduced two days ago, in 9752f2878a6318dc0e48068ed32cc6fb66defd86.

**Comment by ezyang** [comment]
Thanks @grayjay, I'll look into it.

**Comment by ezyang** [comment]
Problem is pretty simple: I forgot to filter out internal deps from the dependency calculation, and those are being reported as dependency loops.
