### ISSUE TITLE
Can't set path to tools in ~/.cabal/config

### ISSUE THREAD

**Issue by bos** [haskell/cabal#439]
(Imported from [Trac #446](http://hackage.haskell.org/trac/hackage/ticket/446), reported by awick on 2009-01-07)

The config file for cabal-install lets me set all sorts of useful paths, except for the non-compiler tools. In other words, there's no config file mapping for the --with-PROG or --PROG-options flags, which would be really convenient.

(At least, when I tried the obvious versions, it didn't work. Maybe missing docs somewhere?)

**Comment by BardurArantsson** [comment]
Seems long-obsolete. Close?

**Comment by gbaz** [comment]
As best as I can parse, this is asking for what we have now in the program-locations and the program-default-options stanzas of the cabal config file. I'm closing. If I missed something, please comment and reopen.
