### ISSUE TITLE
showVersion was gratuitously removed

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4406]
No reason we can't have it as an alias to display. DEPRECATE it even, if you like.

**Comment by 23Skidoo** [comment]
Cherry-picked the relevant patch from #4410 into 2.0.

**Comment by 23Skidoo** [comment]
Leaving this ticket open for now, will be fixed in master once #4410 is merged.

**Comment by hvr** [comment]
Oh dear... this will break a couple of early adopters that already adapted...
