### ISSUE TITLE
Q: Installing dependencies makes `validateSolverResult` function return errors

### ISSUE THREAD

**Issue by zilinc** [haskell/cabal#4415]
I got error
```
CallStack (from HasCallStack):
error, called at ./Distribution/Client/Dependency.hs:658:33 in
main:Distribution.Client.Dependency
```
when installing dependencies for my project. (https://travis-ci.org/NICTA/cogent/jobs/213613398#L749)
I'm using cabal-install-1.24 and ghc-8.0.

Why could this have happened? Is it a bug in the installing packages or cabal-install, or my settings?

**Comment by ezyang** [comment]
An error here is usually a cabal-install bug, although it could also mean you build cache is borked. What happens if you (a) reset the Travis cache to scratch and try again, and (b) if you try build with cabal-install-head (you can conveniently get an executable using hvr's PPA.)

**Comment by zilinc** [comment]
I tried both. a) didn't work; b) fixed it.

**Comment by ezyang** [comment]
OK, let's call this "fixed in HEAD".
