### ISSUE TITLE
WARNING in hptSomeThingsBelowUs...out-of-date interface files

### ISSUE THREAD

**Issue by bfrk** [haskell/cabal#4417]
I pull a few patches into the darcs source tree and when I say cabal new-build, I get lots of 

```
WARNING in hptSomeThingsBelowUs
  missing module Darcs.Util.Environment
  Probable cause: out-of-date interface files
WARNING in hptSomeThingsBelowUs
  missing module Darcs.Util.Environment
  Probable cause: out-of-date interface files
```

Cleaning dist and dist-newstyle (rm -rf) and re-building fixes the problem (everything compiles cleanly). I am using cabal-head from the http://ppa.launchpad.net/hvr/ghc/ubuntu

**Comment by 23Skidoo** [comment]
> hpt

Looks like a GHC issue.

**Comment by bfrk** [comment]
Does cabal use ghc --make? In that case I agree. If cabal calls ghc separately for each file then it's cabal's fault.

**Comment by 23Skidoo** [comment]
It does.

**Comment by bfrk** [comment]
Ok, I'll take a look at the ghc bugs. Thanks.

**Comment by bfrk** [comment]
I may have been to fast closing this. Yes the error was issued by ghc. But what triggered the problem was that in one patch I renamed a file and updated the cabal file accordingly. Wouldn't that qualify this to be a problem /between/ ghc and cabal?

**Comment by 23Skidoo** [comment]
Do you have a reproducible test case?

**Comment by ezyang** [comment]
No, it's still probably a GHC bug only. All Cabal does is pass the list of modules to be compiled to GHC. If that list is "correct" (and it would be, if your cabal file is written correctly), then GHC should be able to deal.

**Comment by bfrk** [comment]
Okay. Will see what the ghc devs say. Feel free to close.

**Comment by avh4** [comment]
The related ghc issue is here: https://gitlab.haskell.org/ghc/ghc/-/issues/15234
