### ISSUE TITLE
Use gold linker in travis

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4438]
We do link a lot, so it might save us build-time. https://www.reddit.com/r/haskell/comments/63shj7/link_with_the_gold_linker_for_faster_build_times/

@ezyang is the flag easy to add to use in the test-suite?

**Comment by ezyang** [comment]
Yes, we should just add it to the flags we pass Cabal by default; I guess `--ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ld=ld.gold` or something similar would be sufficient. Another possibility is to use update-alternatives to have ld point to ld.gold; then you'll get it automatically.

FWIW, I temporarily switch to ld.gold as my default ld, but I think this breaks some stuff so I didn't do it.

**Comment by 23Skidoo** [comment]
`update-alternatives` is probably the easiest option.

**Comment by ezyang** [comment]
This was tried in #4441 but it didn't really help.

**Comment by 23Skidoo** [comment]
#4441 has been merged.
