### ISSUE TITLE
Appveyor is broken: Cannot select only the dependencies

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4456]
```
echo "" | ..\appveyor-retry ..\cabal install --only-dependencies --enable-tests
Resolving dependencies...
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the packages are required by a dependency of one
of the other targets.
```

Failing log: https://ci.appveyor.com/project/23Skidoo/cabal/build/%233393%20(master)

**Comment by ezyang** [comment]
This is fairly easy to reproduce, just run ` cabal install --only-dependencies --enable-tests -v3 --dry-run` on the Cabal directory. Here is what is happening.

On April 15, @hvr performed a revision to unbounded-delays to add a custom-setup section to unbounded-delays. This was the immediate cause for Appveyor to start failing.

What happened was that when the custom-setup was added, unbounded-delays began to have its setup dependency solved for in the dependency solver. The good news is, invariably, we select the pre-installed copy of Cabal for the setup dependency (NOT the local that would be built; that's impossible to do!) The bad news is, the consistency check that the solver applies after the fact treats this setup dependency on a preinstalled copy as a dependency on one of the targets, and decides to bail out, even though it really should go ahead and install everything!

While we can fix this bug in the consistency check, this is not much solace for making our Appveyor build start working in the near future. Another hotfix is to force an older version (or possibly an older revision?! We don't have syntax for that) of unbounded-delays, which will prevent the solver from trying to solve for Cabal. That is a fragile fix, however, because if any of the other deps in our tree grow a setup-depends, it will cause the same problem.

This error occurred in #1500 but I haven't read the ticket enough to see if it's the same.

**Comment by grayjay** [comment]
Should this be reopened, since we don't have a complete fix?

**Comment by ezyang** [comment]
unbounded-delays no longer has a Custom setup, so this is "fixed". (But we could break in the future if any of our deps grow Custom setup.)
