### ISSUE TITLE
"thread blocked indefinitely in an STM transaction"

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#4461]
I've noticed that from time to time cabal seems to fail with

```
...
Building hspec-core-2.4.3 (lib)...
Configuring hspec-2.4.3 (lib)...
Building hspec-2.4.3 (lib)...
thread blocked indefinitely in an STM transaction
```

which is quite annoying with CI jobs.

Just now, @alexbiehl ran into the very same issue on Travis: https://travis-ci.org/haskell/haddock/jobs/225512194#L377

and I was able to reproduce this locally as well (and quite reliably). In order to be able to reproduce it, `~/.cabal/store` should be empty, as well as the source-tarball cache in `~/.cabal/packages/hackage.haskell.org/*/*/*`, as this seems to occur only when cabal needs to download source-tarballs during `new-build`.

(Moreover, a less important observation: this occurs with both `--http-transport=curl` and `--http-transport=http-plain`)

**Comment by alexbiehl** [comment]
The travis log with cabal verbose output: https://travis-ci.org/haskell/haddock/jobs/225517509#L4676 Unfortunately nothing too suspicous.

**Comment by phadej** [comment]
@hvr I guess that we don't recover from http transpost errors gracefully enough. I *guess* the test case can be made 100% reliable if you use wrapper around `curl` which fails often enough, could you try?

**Comment by hvr** [comment]
@phadej I'm not sure I understand what you're saying though. In the case where I saw the STM exceptions, the http transports appear to have succeeded w/o any errors. I.e. all source tarballs were downloaded successfully.

**Comment by phadej** [comment]
Uh. That interesting, what's then causing the stm exceptions (some unfortunate timing of events is causing deadlock-like situation?)

**Comment by dcoutts** [comment]
hvr has identified the problem (though he didn't say what it was in the PR!) and has a fix.

**Comment by hvr** [comment]
@phadej while #4463 fixes the problem that triggered the issue here in #4461 (which was originally a `BlockedIndefinitelyInMVar` exception that got promoted to an STM-exception), I think you bring up a good point that we should check whether there's other situations where an `BlockedIndefinitelyOnSTM` could result from.
