### ISSUE TITLE
Removal of Dependency type not mentioned in changelog

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#4467]
It seems that version 2.0 of the Cabal library has removed the `Dependency` type which used to be in `Distribution.Package`, but this change is not noted in the [changelog](https://github.com/haskell/cabal/blob/master/Cabal/changelog).

Would be really nice if this was mentioned in the changelog along with suggestions for working around its removal.

**Comment by 23Skidoo** [comment]
Seems to live in `Distribution.Types.Dependency` now. This change was done in #4364.

**Comment by erikd** [comment]
I assume closing this is appropriate.
