### ISSUE TITLE
file permissions of installed files on windows

### ISSUE THREAD

**Issue by bos** [haskell/cabal#447]
(Imported from [Trac #454](http://hackage.haskell.org/trac/hackage/ticket/454), reported by @toxaris on 2009-01-13)

When installing a binary on Windows Vista using ghc 6.10.1 and Cabal 1.6.0.1, it is not accessible for ordinary users. Old binaries installed with ghc 6.8.2 and Cabal 1.4 had "read" and "execute" permissions set for "all users", while new binaries have only permissions set for "administrators".

Cabal should set "read" and "execute" permissions for "all users" for binaries.

A workaround is to manually set these permissions using the executable's properties dialog.

**Comment by bawa-v** [comment]
Hi, 

I run 
 `stack build --allow-different-user :duckling-regen-exe && stack exec duckling-regen-exe && stack test` for building a service from https://github.com/facebook/duckling 
 
 and get the following error from Cabal : 

`/mnt/c/Users/<user>/<working directory>/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/.stack-cabal-mod26078-0.tmp: withBinaryFile: permission denied (Operation not permitted)`

I changed the permissions of the above folder using 
`sudo chmod -R 1777 /mnt/c/Users/<user>/<working directory>/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/`

But that does not change the error. Any ideas?
