### ISSUE TITLE
Cabal new-build projects should allow setup-depends from the project

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4471]
Otherwise it's impossible to develop (and test) packages meant to be used in setup-depends, e.g. `cabal-doctest`. Currently I have to use sandboxes (or `stack`).

I remember discussion about this, but cannot find in which issue it was.

Also the solution where one have to **explicitly** mark a package eligible for use in `setup-depends` is OK;
It's probably good to separate between "setup pkg" and "real pkg" (so there is no mess like with TemplateHaskell dependencies).

ping @ezyang @dcoutts @hvr @RyanGlScott

**Comment by hvr** [comment]
just to clarify, you're talking about allowing local packages (declared via `(optional-)packages:` to become eligible for qualified goals such as `setup-depends`?

**Comment by phadej** [comment]
@hvr yes. (or via separate list of packages, `setup-packages` mod name bikesheding)

**Comment by hvr** [comment]
@phadej this sounds a bit like https://github.com/haskell/cabal/issues/4432#issuecomment-291391948 doesn't it?

**Comment by grayjay** [comment]
Is this related to #4295?  I thought cabal could use any package from the project as a setup dependency.

**Comment by phadej** [comment]
@grayjay paged out that issue completely; will verify if `--independent-goals` works for me

**Comment by grayjay** [comment]
The --independent-goals flag was commented out, but I tried to enable it in https://github.com/grayjay/cabal/tree/enable-independent-goals.  The branch probably needs more work, though.

**Comment by ezyang** [comment]
I am confused about this issue because #4432 implies the opposite: that an inplace package will get used for setup depends, whether you want it to or not.

@phadej, it would help if you tried to repro this from scratch (e.g., make a test case for our test suite), or gave us more detailed repro instructions with cabal-doctest.

**Comment by grayjay** [comment]
@ezyang I think that the issue with #4432 is that the solver can pick any version to satisfy the dependencies, and there isn't a constraint to force it to use the local or non-local version.

**Comment by phadej** [comment]
I think this works, as I was successfully able to test `cabal-doctest` locally.
