### ISSUE TITLE
cabal configure should fail if cannot satisfy setup-depends

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4474]
Related: https://github.com/phadej/cabal-doctest/issues/11

```
$ /opt/cabal/2.0/bin/cabal configure -w /opt/ghc/8.2.1/bin/ghc
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: distributive-0.5.2:+tagged
unknown package: tagged (dependency of distributive-0.5.2:+tagged)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: distributive, distributive-0.5.2:flag,
taggedTrying configure anyway.
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )

... compiler error
```

That's very frustrating, and doesn't make sense.

I hope this can be fixed quickly, I'm more than happy to make a PR, if no-one objects (for a very good reason).

**Comment by 23Skidoo** [comment]
I actually fixed this before, but it broke the containers test suite and was reverted. See #1575.

**Comment by phadej** [comment]
I'd say that default behavior should be: fail; if you don't it to fail, you have to say that explicitly.

**Comment by 23Skidoo** [comment]
OK, this probably can be implemented, though people relying on that feature will be angry :-).

**Comment by angerman** [comment]
Not sure if this is related, but running `cabal configure` or `cabal new-configure`, with or without `--allow-newer`, where cabal is built with new-build, never returns but runs at 100% cpu.

`-v` gives:

```
[...]
Reading available packages of hackage.haskell.org...
Using most recent state specified from most recent cabal update
```
and then nothing.

**Comment by grayjay** [comment]
There is also #2614.

**Comment by phadej** [comment]
So many duplicate issues; should we close them (newers) with `duplicate` label?

**Comment by 23Skidoo** [comment]
I guess we can close this in favour of #2614.
