### ISSUE TITLE
Migration guide for 2.0

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4483]
I started a wiki page: https://github.com/haskell/cabal/wiki/2.0-migration-guide please add known BC-breaking changes and how to solve them.

**Comment by angerman** [comment]
Should this be in the cabal user guide as well?

**Comment by hvr** [comment]
@angerman I think the designated place for describing Cabal's API (and by extension migration/changes) should be the Haddocks and the associated ChangeLog file

**Comment by ezyang** [comment]
I think it is best to put it in wiki, that way it is easier to make changes post release when people complain.

**Comment by angerman** [comment]
Under the "these are non-user facing" changes aspect. I agree that the **user** guide would be the wrong place.

**Comment by hvr** [comment]
@ezyang Fair enough, but then we should link to that wiki-page from the ChangeLog, as that's the first place ppl look when wondering why on earth the API would break.... :-)

**Comment by 23Skidoo** [comment]
I've expanded that wiki page a bit, I think this ticket can be closed now.
