### ISSUE TITLE
cabal list: filter by pattern

### ISSUE THREAD

**Issue by bos** [haskell/cabal#450]
(Imported from [Trac #457](http://hackage.haskell.org/trac/hackage/ticket/457), reported by guest on 2009-01-16)

dcoutts: cabal feature request: a way to filter the output of "cabal list" by field (e.g. "cabal list Section=Games".

**Comment by jsl** [comment]
Given that there are no comments since 2009, I propose we close this issue. Please re-open or create a new ticket if this is still desired.

/cc @tibbe
