### ISSUE TITLE
bootstrap.sh for cabal-install 1.24.0.2 fails to run on Scientific Linux (CentOS)

### ISSUE THREAD

**Issue by merijn** [haskell/cabal#4512]
I ran into an issue where the bootstrap.sh script fails to find the linker correctly on CentOS, see #4187. This renders the current source tarball on https://www.haskell.org/cabal/download.html unbuildable.

The tar ball should be updated with a bootstrap.sh that includes the fix from #4187 so that it can at least be installed.

**Comment by ezyang** [comment]
@23Skidoo How hard would it be to hotpatch this?

**Comment by gbaz** [comment]
obsolete afaik
