### ISSUE TITLE
Tests with GHC HEAD are failing

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4516]
They simultaneously started failing on 2.0 and master on different commits so I think it is probably an environment change. https://travis-ci.org/haskell/cabal/branches

These tests started failing on the 9th, which corresponds to when a new version of ghc-head showed up on @hvr's PPA, which is probably the proximal cause of failure (but the root cause is probably a change in ghc-head).

It took a week for me to notice the problem, which is far too long. I wonder if we can change Travis notification settings to be noisier when master fails.

**Comment by ezyang** [comment]
Upstream fix is at https://phabricator.haskell.org/D3590

I'm torn between flatout disabling ghc-head tests, versus trying to do something more surgical, while we wait for ghc-head to start working again.

**Comment by hvr** [comment]
@ezyang a new PPA build including the merged D3590 fix is on its way... give or take ~2 hours :-)

**Comment by hvr** [comment]
@ezyang fwiw, 967a64e35721e330dbb980aa062cec1047aae151 is green now... but I'm not sure if it'll stay that way if I restarted the build now... :-)

**Comment by jneira** [comment]
Afaik we are not testing ghc head anymore, hvr/ppa is no being updated anymore. Maybe it would be good to do it but at least Cabal the library is being tested in https://gitlab.haskell.org/ghc/head.hackage.
