### ISSUE TITLE
-Wmissing-home-modules check doesn't work for executable components

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4528]
We'd like to make the `-Wmissing-home-modules` check work for executables.

@hvr identified the following issues that need to be solved for it to work:

  * `-Wmissing-home-modules` gets confused when the main module is specified on the command line using a relative path. This needs to be fixed in GHC, upstream issue: https://ghc.haskell.org/trac/ghc/ticket/13727
  * Cabal doesn't pass the list of `other-modules` to `ghc --make` when building executables. This should be solved on the Cabal side.

See also discussion in https://github.com/haskell/cabal/pull/4526.

**Comment by 23Skidoo** [comment]
Fixed by #4534, but still needs a test case, and that is blocked by #4529. So leaving open for now.

**Comment by hvr** [comment]
Points in the test-space might want to test/verify:

 - `main-is: main.c`
 - foreign libs
 - internal/convenience libraries
 - tests/executable/benchmark stanzas
 - autogenerated modules
 - combination of intra-package lib-dependency + overlapping hs-source-dirs (picking up modules directly already part of the library)
 - ...

**Comment by hvr** [comment]
@23Skidoo I (or rather @alanz) just found a minor problem:

We need to cope with questionable cabal files such as http://hackage.haskell.org/package/happy-1.19.5/happy.cabal  which mention the main module twice;  via `main-is: Main.lhs`  *and* `other-modules: Main`.

So one simple hack would be to filter out modules named `Main` from other-modules for executables (and assuming that `ghc-options: -main-is ...` is used to infrequently that we don't need to bother);

...and also we should emit a warning when Main is both via main-is and via other-modules.

**Comment by 23Skidoo** [comment]
What happens now with such .cabal files?

**Comment by hvr** [comment]
@23Skidoo GHC complains about multiple modules providing `main`; I'm already on it to implement a workaround (and I'll try to take into account `ghc-options`) ... PR coming later today!

**Comment by hvr** [comment]
@23Skidoo See PR #4539

**Comment by hvr** [comment]
From what I can see, this was already resolved in the released Cabal-2.0.0.2 (since #4539, #4533, #4534 were all backported and were part of the 2.0.0.2 release)
