### ISSUE TITLE
Add detailed error for extra-libraries missing

### ISSUE THREAD

**Issue by suzumiyasmith** [haskell/cabal#4541]
It's really confusing and mis-leading that cabal says a library already installed is missing.
```
/usr/bin/gcc returned ExitFailure 1 with error message:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../lib/libchipmunk.so:
undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../lib/libchipmunk.so:
undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```
those are errors shown in verbose mode. But cabal only says that:

```
cabal: Missing dependency on a foreign library:
* Missing C library: chipmunk
```

It could be more helpful to show that something wrong while trying to use extra-libraries rather than simply saying it is missing.

Actually, last time I stuck in the same question(https://stackoverflow.com/questions/41943494/haskell-stack-missing-c-library-xft-when-using-stack-building-x11-xft). 

I would be appreciated if detailed error info could be displayed. Thanks.

**Comment by ezyang** [comment]
Yes, in general, the `./configure` style testing that `cabal configure` does to determine what libraries are available is not very robust, and arguably should be replaced with something simpler that doesn't try to paper over errors like this. Maybe I can newcomer'ify this ticket.

**Comment by ezyang** [comment]
Out of curiosity, were you passing `-Wl,-no-as-needed`?

**Comment by suzumiyasmith** [comment]
No, I haven't attached any option to linker. I was just trying `inline-c` ffi to some system lib(custom building from `aur`), so I simply added some `cc-option`s such as `O2`, `fastmath` and `Wall`.

I think it is like a newbie trap(if he has some broken sys lib). For me, I am now using `stack build` with `cabal-verbose` command.

**Comment by ezyang** [comment]
To be fair, I had to work pretty hard to repro the problem ;) If a sys lib is present but requires symbols from something else, most people have lazy linkers by default so this won't cause your problem above.

**Comment by suzumiyasmith** [comment]
I simply copy&paste some error info from header missing. It only changes the error text.
