### ISSUE TITLE
haskell.org docs are silently out-of-date

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#4546]
/cc @ezyang I think you wrote the code?

All I'm really after is *how* exactly you specify an internal/convenience library.

**Comment by BardurArantsson** [comment]
Actually, I think I found out how (just add a "name" to the header of the library section), but then realized that we cannot use it because cabal-install itself uses the Custom build type.

**Sigh**.

**Comment by 23Skidoo** [comment]
With regard to the original question - yes, go to http://cabal.readthedocs.io/en/latest/developing-packages.html#library and scroll down a bit.

**Comment by BardurArantsson** [comment]
Oh, I see. Google led me to obsolete documentation -- I wonder if there's anything we can do about that.

**Comment by ezyang** [comment]
cabal-install can't use it anyway because it needs to be buildable with old versions of cabal-install that don't understand.

I see Google search "Cabal internal libraries" points to haskell.org docs. We should do something about this.

**Comment by 23Skidoo** [comment]
I'll update haskell.org/cabal once 2.0 is out.

**Comment by BardurArantsson** [comment]
@ezyang I was under the impression that once 2.0 is out, we could switch? (Only theoretically, because "Custom", obviously).

**Comment by 23Skidoo** [comment]
Well, you want `cabal install cabal-install` to work with the majority of previous `cabal-install` versions still in use.

**Comment by BardurArantsson** [comment]
Sure. Regardless, the point is moot.

**Comment by 23Skidoo** [comment]
This is fixed now, I believe.

**Comment by cocreature** [comment]
I’m not sure if that’s still the purpose of this issue (the title seems to be more general than the discussions), but the docs still seem to be out of date, https://www.haskell.org/cabal/users-guide/ points to the user guide for 1.24.

**Comment by 23Skidoo** [comment]
@cocreature Thanks, fixed.
