### ISSUE TITLE
Sandbox dependency checking causes rebuild of Custom setup with wrong version of Cabal

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4561]
Originally reported by  Henk-Jan van Tuyl https://mail.haskell.org/pipermail/haskell-cafe/2017-June/127281.html

Let us start our sordid little story with the TODO comment that is causing this bug:

```
-- | Has this dependency been modified since we have last looked at it?
isDepModified :: Verbosity -> ModTime -> AddSourceTimestamp -> IO Bool
isDepModified verbosity now (packageDir, timestamp) = do
  debug verbosity ("Checking whether the dependency is modified: " ++ packageDir)
  -- TODO: we should properly plumb the correct options through
  -- instead of using defaultSetupScriptOptions
  depSources <- allPackageSourceFiles verbosity defaultSetupScriptOptions packageDir
  go depSources
```

OK, how bad could it be? Here's the problem:

Steps to reproduce:
1. Use GHC 8.2
2. Create a sandbox
3. Add a source package to the sandbox. This package should have a custom setup with a version constraint `Cabal < 2.0` in custom-setup. Furthermore, the custom setup should have some code which builds with Cabal-1.24, but NOT with Cabal-2.0.
4. cabal install the package
5. cabal install the package again

Expected result: It all works

Actual result: It fails because it was linked with Cabal-2.0

So what's going on? Basically, before we've dependency solved and know what version of Cabal we should use with a setup script, sandbox checking for dependency changes runs sdist. But sdist should run with Custom setup... disaster.

I'm not sure how to properly fix the problem; I suspect a "correct" fix pushes dependency testing later until after we have dependency info, as it is in new-build. One quicker fix possibility is to always bypass the Custom setup when running sdist purely for dependency purposes. You can do this with a direct call to `listPackageSources` from `Distribution.Simple.SrcDist`.  But it's still a little terrible because you need a PackageDescription, not a GenericPackageDescription which is what you have at this point. I'm not terribly keen on doing a massive refactor of this code, which is obsoleted by new-build anyway.

**Comment by ezyang** [comment]
So, it turns out the situation is a little more complicated; in particular, the repro instructions above don't work exactly.

First, it is essential that GHC 8.2 be added to the PATH, and not just be selected with `-w`. This is because the build of setup for sdist will use whatever GHC is in your PATH (not what was specified with `-w`.)

Second, by default, we save a `setupVersionFile` whenever we make a custom setup, which is intended to make the choice of Cabal version sticky, even if we try to invoke setup without having appropriate settings. For example, cabal build won't run the dep solver, so we must rely on a previous version file to trust the setup script is done correctly. Now, if the Custom package in question is in the ROOT of the sandbox, it will have written out a version file in `dist/setup/setup.version` which sdist will pick up and subsequently use the right thing. So to repro the bug, you must NOT have a package in the root of the sandbox.

So, there appears to be another bug, in that in sandbox mode, we're creating `dist/setup` inside of each package directory, but sandbox should go into a special sandbox. This probably also is caused by the incorrect use of default setup options, since the dist dir is never setup correctly in this case.

What I still don't understand, is empirically, the setup.version written here is for Cabal 2.0. But I cannot see in the logs where this could possibly have occurred. This is troubling.

**Comment by phadej** [comment]
sandbox functionality is removed.
