### ISSUE TITLE
Can the description field be optional?

### ISSUE THREAD

**Issue by ivan-m** [haskell/cabal#4571]
I've just received a warning from trying to run `cabal check` using GHC/cabal HEAD that my description isn't longer than my synopsis.

The problem is that a lot of libraries tend to be ones along the form of "Make `foo` and `bar` talk to each other."; as such, unless I wanted to talk about what `foo` and `bar` are, there is not much I can really talk about there (except possibly repeat all the functions that are found in the Haddock docs).

As such, would it be possible for Cabal to _not_ require the description field?  I've found in practice that it's either not much more than a re-worded version of the synopsis or that it's so long that it means I have to scroll the Hackage page before I can view what I actually want (typically the Haddock pages).

**Comment by hvr** [comment]
Being the one who created the warning you now see, I claim that such cases are the minority, and that the overall benefit for Hackage outweighs the inconvenience for those few cases where you really can't come up with a full paragraph of things to say your package. It would help if you could point me to concrete examples on Hackage.

See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more on the relationship on synopsis/description/README.

**Comment by ivan-m** [comment]
[This](https://hackage.haskell.org/package/streaming-conduit) is a library I uploaded recently.

If you know what streaming and conduit are, then just the package name/synopsis suffices.  If you don't, then whilst I could put more details into the description, that's the task of those packages themselves.

The description could cover the functions available... but that's the job of the Hackage docs.

**Comment by 23Skidoo** [comment]
@ivan-m I think a good start would be to repeat what you said in the "Motivation" section of the README.

**Comment by ivan-m** [comment]
@23Skidoo see, I put that in there just to bulk out the README a bit so it didn't look so plain on GitHub and also link to some other libraries.

Again, I think it's primarily a case that the synopsis of "Bidirectional support between the streaming and conduit libraries" covers completely what it does, and the Hackage docs cover the specifics of how to do it; anything else I put either in the description or the README is just filler faff rather than actually adding any value.

**Comment by phadej** [comment]
I tend to disagree, description really adds the value.

Compare:

![screen shot 2017-06-21 at 10 04 34](https://user-images.githubusercontent.com/51087/27371375-35824fdc-5669-11e7-83e7-2524a07ba233.png)

![screen shot 2017-06-21 at 10 04 56](https://user-images.githubusercontent.com/51087/27371386-3adc6544-5669-11e7-9081-19b486db4706.png)

---

If nothing else, convert the `streaming` and `conduit` into links in the description (description fields is rendered using haddock syntax - than it will be longer and more useful!

**Comment by 23Skidoo** [comment]
@ivan-m I disagree :) I found the README your wrote useful, even though I know what the `streaming` and `conduit` packages do (and for someone who doesn't, it saves a few clicks). Phrases like "Interoperability" and "bidirectional support" are somewhat general/broad, so it's nice when the package author explains in English what they mean in current context. If you're completely out of ideas what to put in the description, I'd suggest a small code example with an explanation.

**Comment by 23Skidoo** [comment]
Closing as `wontfix`.
