### ISSUE TITLE
DoRec vs. RecursiveDo

### ISSUE THREAD

**Issue by rhymoid** [haskell/cabal#4573]
`DoRec` is deprecated, according to [its documentation of the `DoRec` constructor](https://github.com/haskell/cabal/blob/master/Cabal/Language/Haskell/Extension.hs#L135). However, it also provides a syntax that is preferred over that of `RecursiveDo`, according to [the documentation of the `RecursiveDo` constructor](https://github.com/haskell/cabal/blob/master/Cabal/Language/Haskell/Extension.hs#L139).

Which one is it?

**Comment by 23Skidoo** [comment]
IIUC, the person that marked `DoRec` deprecated forgot to update the comment for `RecursiveDo`, which nowadays also enables the `do rec` syntax in addition to `mdo`.

**Comment by 23Skidoo** [comment]
Fixed in 6f901564c1981812dfad156182d6ce4b4c0f19cb.
