### ISSUE TITLE
cabal-install: `--reinstall` ignored with `--dependencies-only`

### ISSUE THREAD

**Issue by eigengrau** [haskell/cabal#4576]
When issuing `cabal install --dependencies-only --reinstall` (run inside a Cabal sandbox), the `--reinstall` option appears to be ignored, yielding the message:

```
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
```

Would it make sense to go ahead and reinstall all dependencies in this case?

Background usecase (and request for advice): Arch Linux recently abandoned shipping static libraries with their Haskell packages. This has repercussions when trying to do sandboxed static builds using Cabal. Since distro packages will be registered within the global package DB, `cabal install --dependencies-only` will consider some dependencies satisfied, but the static build will later error out during linking (since the static libraries are missing). So I’m currently looking for a good way to further isolate the sandbox from what’s installed globally.

**Comment by 23Skidoo** [comment]
Looks like a duplicate of #1175. Basically, what we want here is a better error message.

**Comment by eigengrau** [comment]
Thanks for the pointer!
