### ISSUE TITLE
Documentation not generated with config: Documentation: True

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#4581]
For ages I have this in my config:
~~~~
$ fgrep documentation ~/.cabal/config
documentation: True
~~~~
So far this made Cabal generate and install package documentation.
It seems to have gone with Cabal-2.0.
Now, documentation is only generated if I add the documentation flag to every install invocation:
~~~~
$ cabal install --enable-documentation pkg-name
~~~~

**Comment by ezyang** [comment]
Repro'd with fc3ef2a75dc6ff285129ad87f3ecd0ce8795c5e8

**Comment by 23Skidoo** [comment]
I'll try to look into this.

**Comment by cartazio** [comment]
I hit this bug too, is there a current work around or fix?

**Comment by hvr** [comment]
@ezyang's 1e90ae4380cdcef5662d933e3a34dcfef6080ec1 caused this...

**Comment by 23Skidoo** [comment]
Thanks @alexbiehl!

**Comment by hvr** [comment]
@23Skidoo btw @alexbiehl is already working on a quickfix... if we get this resolved, this would have been the last blocker for releasing cabal-install-2.0, no? :-)

**Comment by 23Skidoo** [comment]
Yes, looks like it. There's also #4622, but it should be easy to fix.
