### ISSUE TITLE
Windows failure (hClose: resource vanished (Broken pipe)) when running cabal-tests

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4618]
We've been seeing intermittent failures on AppVeyor ([example](https://ci.appveyor.com/project/23Skidoo/cabal/build/%233751%20(ghc-8.2.1-blockers))) with the following error message:

```
dist\build\cabal-tests\cabal-tests.exe -j3
threads: 3
tests to run: 170
Shutting down GHCi sessions (please be patient)...
Unexpected failure on GHCi exit: fd:4: hClose: resource vanished (Broken pipe)
cabal-tests.exe: fd:4: hClose: resource vanished (Broken pipe)
```

These usually go away after restarting the build. Would be nice to fix this problem at the root.

**Comment by jneira** [comment]
I did not see that error in the new GitHub CI so closing
