### ISSUE TITLE
Solver.Prelude missing from other-modules

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4625]
These modules are needed for compilation but not listed in your .cabal file's other-modules: Distribution.Solver.Compat.Prelude

**Comment by 23Skidoo** [comment]
Why didn't Travis catch that?

**Comment by hvr** [comment]
@23Skidoo maybe this doesn't occur in the cabal flag-configurations covered by Travis?

**Comment by 23Skidoo** [comment]
So which is the one that we should add?

**Comment by hvr** [comment]
@23Skidoo it appears to be missing for the `flag(lib)=False` configuration; we have the `other-modules` basically listed redundantly twice in the cabal-install.cabal, once for the `library` and once for the `executable cabal`.

**Comment by 23Skidoo** [comment]
@hvr Thanks!

**Comment by 23Skidoo** [comment]
So basically, `other-modules` under `library` and `executable cabal` must be identical. It should be easy to add a check for that to the Travis `meta` step.
