### ISSUE TITLE
new-build wants to install Cabal on old GHCs, but old-build doesn't

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#4628]
This appears to happen with GHC 7.8.4 and older (but not more recent versions). Using `cabal-install-2.0`, if I try to install the dependencies needed for `distributive` and its test suite using the old style, I get this:

```
distributive-0.5.2$ cabal install --enable-tests -w /opt/ghc/7.8.4/bin/ghc --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
ansi-terminal-0.6.3.1
base-compat-0.9.3
base-orphans-0.6
cabal-doctest-1.0.2
call-stack-0.1.0
code-page-0.1.3
generic-deriving-1.11.2
ghc-paths-0.1.0.9
hspec-discover-2.4.4
mtl-2.1.3.1 (latest: 2.2.1)
primitive-0.6.2.0
random-1.1
setenv-0.1.1.3
stm-2.4.4.1
syb-0.7
text-1.2.2.2
HUnit-1.6.0.0
transformers-compat-0.5.1.3 (latest: 0.5.1.4)
tf-random-0.5
async-2.1.1.1
doctest-0.11.4 (latest: 0.12.0)
hashable-1.2.6.1
hspec-expectations-0.8.2
tagged-0.8.5
QuickCheck-2.10.0.1
unordered-containers-0.2.8.0
nats-1.1.1
quickcheck-io-0.2.0
semigroups-0.18.3
hspec-core-2.4.4
hspec-2.4.4
distributive-0.5.2
```

But with `new-build`, it brings in another, bulkier dependency: `Cabal` itself!

```
distributive-0.5.2$ cabal new-build --enable-tests --enable-benchmarks -w /opt/ghc/7.8.4/bin/ghc --dry-run
In order, the following would be built (use -v for more details):
 - Cabal-2.0.0.2 (lib) (requires download & build)
 - ansi-terminal-0.6.3.1 (lib:ansi-terminal) (requires build)
 - base-compat-0.9.3 (lib) (requires build)
 - base-orphans-0.6 (lib) (requires build)
 - call-stack-0.1.0 (lib) (requires build)
 - generic-deriving-1.11.2 (lib) -base-4-9 (requires build)
 - hsc2hs-0.68.2 (exe:hsc2hs) (requires build)
 - hspec-discover-2.4.4 (lib) (requires build)
 - mtl-2.1.3.1 (lib:mtl) (requires build)
 - primitive-0.6.2.0 (lib) (requires build)
 - random-1.1 (lib) (requires build)
 - setenv-0.1.1.3 (lib) (requires build)
 - stm-2.4.4.1 (lib) (requires build)
 - syb-0.7 (lib) (requires build)
 - text-1.2.2.2 (lib) (requires build)
 - ghc-paths-0.1.0.9 (lib:ghc-paths) (requires build)
 - cabal-doctest-1.0.2 (lib) (requires build)
 - HUnit-1.6.0.0 (lib) (requires build)
 - code-page-0.1.3 (lib) (requires build)
 - transformers-compat-0.5.1.3 (lib) (requires build)
 - tf-random-0.5 (lib) (requires build)
 - async-2.1.1.1 (lib) (requires build)
 - hashable-1.2.6.1 (lib) (requires build)
 - hspec-expectations-0.8.2 (lib) (requires build)
 - doctest-0.11.4 (lib) (requires build)
 - tagged-0.8.5 (lib) (requires build)
 - QuickCheck-2.10.0.1 (lib) (requires build)
 - unordered-containers-0.2.8.0 (lib) (requires build)
 - nats-1.1.1 (lib) (requires build)
 - quickcheck-io-0.2.0 (lib) (requires build)
 - semigroups-0.18.3 (lib) (requires build)
 - hspec-core-2.4.4 (lib) (requires build)
 - hspec-2.4.4 (lib) (requires build)
 - distributive-0.5.2 (lib:distributive, test:doctests, test:spec) (first run)
```

(`hsc2hs` also snuck in there, although that doesn't take quite as long to install.)

Is there a reason why `new-build` doesn't just use the `hsc2hs` and `Cabal` bundled with GHC 7.8.4? A consequence of this is that Travis builds for older GHCs take quite a bit longer.

**Comment by 23Skidoo** [comment]
> A consequence of this is that Travis builds for older GHCs take quite a bit longer.

If you enable cache on Travis, it will be only a problem once.

**Comment by RyanGlScott** [comment]
Well, sure... but that's not really a satisfying answer to the original question. Why does `new-build` need to reinstall boot libraries/tools in the first place?

**Comment by hvr** [comment]
@RyanGlScott as for `hsc2hs`, new-build is still lacking the ability to improve its install-plan to reuse "preinstalled" instances of build-tools (something it supports for libraries). as for lib:Cabal, `new-build` imposes a lower bound on the lib:Cabal version as otherwise it can't communicate with custom-setups. And GHC 7.8.4 comes with lib:Cabal-1.18.15 preinstalled, which is below that threshold. So it *needs* to install a newer lib:Cabal which satisfies the respective `custom-setup`'s constraints as a qualified goal. Note that this can end up installing *multiple* versions or instances of lib:Cabal.

**Comment by RyanGlScott** [comment]
Ah, OK. That answers my questions quite nicely, so I'll close this. Thanks!
