### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4632]
First failure is here: https://travis-ci.org/haskell/cabal/builds/257383949

Not sure what the proximal cause of failure is, but this may have coincided with the Cabal-2.0.0.2 official release https://hackage.haskell.org/package/Cabal

**Comment by ezyang** [comment]
What appears to be happening:
* cabal-install-1.24.0.2 new-build has a bug where it incorrectly tries to register packages that contain non-buildable libraries. This bug was fixed in dd2731f691c5505591a9edb92fc96ad57eadb1db but cabal-install-1.24 doesn't have the fix
* Unfortunately, for ease in testing, cabal-install.cabal now has a library stanza, which means the buggy cabal-install-1.24 code always assumes that registration is needed.

What I don't understand is why we didn't catch this problem before.

**Comment by 23Skidoo** [comment]
Can we fix this by switching to `cabal-install-2.0` package from hvr's PPA?

**Comment by ezyang** [comment]
See https://github.com/haskell/cabal/pull/4634

**Comment by ezyang** [comment]
No, it doesn't fix this entirely, because there is no OS X build of cabal-install 2.0 yet.

**Comment by 23Skidoo** [comment]
I think we can use @phadej's nightly in the meanwhile: https://haskell.futurice.com/.

**Comment by ezyang** [comment]
That helped! Just one failing test to fix...
