### ISSUE TITLE
Environment files interfere with legacy Custom setup builds in sandbox

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4642]
I was investigating why the test in this CI build was failing https://travis-ci.org/haskell/cabal/jobs/258389289 As it turns out, it's an environment file induced problem. Two things went wrong:

1. A parent directory had a new-build take place, which caused an environment file to be written. In this case, the environment file corresponds to the new-build of Cabal/cabal-install itself.
2. A legacy Custom setup build was carried out inside a sandbox.

Historically, Cabal built custom setup scripts without `-hide-all-packages`, using the default user environment. But, environment files are enabled when this flag is not set. So if Cabal builds a setup script in this legacy mode, the environment file will be applied, as was the case for building a setup script in a sandbox:

```
/Users/travis/.ghc-install/8.0.2/bin/ghc --make -odir /Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-2ea43d80/setup -hidir /Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-2ea43d80/setup -i -i/Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom -package-db /Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/sandbox.dist/sandbox/x86_64-osx-ghc-8.0.2-packages.conf.d -package-id Cabal-1.24.2.0 /Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-2ea43d80/setup/setup.hs -o /Users/travis/build/haskell/cabal/cabal-testsuite/PackageTests/CustomDep/custom/dist/dist-sandbox-2ea43d80/setup/setup -threaded
```

Not clear what the correct resolution is. I think we have some default set of exposed packages for the legacy case in new-build, which we could port to sandbox, but I'm not that keen on adding a bugfix for this edge-case.

CC @hvr

**Comment by 23Skidoo** [comment]
I'm slowly coming to think that enabling environment files before GHC added an option to ignore them was a mistake.

**Comment by phadej** [comment]
sandbox functionality is removed.
