### ISSUE TITLE
Passing arguments to test suites run via new-test is unsupported

### ISSUE THREAD

**Issue by cocreature** [haskell/cabal#4643]
Currently it is impossible to pass any arguments to a test suite that is run via `new-test` since they are interpreted as targets (regardless of how many `--` you add in between).

There is the question of what should happen if multiple test suites are run. Personally, I would prefer if the arguments are just passed to all of them in that case but I’m also fine with an error or whatever else as long as I have the possibility to specify the test suite explicitly.

**Comment by fgaz** [comment]
This probably also affects `new-bench`

**Comment by 23Skidoo** [comment]
Just bumped into this the other day. I think that none of the flags specific to old-test (`TestFlags`) are supported by new-test right now.

**Comment by fgaz** [comment]
Apparently some are set to `mempty`.
See `setupHsTestFlags` and `setupHsTestArgs` in `Distribution/Client/ProjectPlanning.hs`

**Comment by lspitzner** [comment]
in the meantime..

~~~~
cabal new-build TESTNAME && `find dist-newstyle/build -type f -name TESTNAME` --color --my --other --args
~~~~

which probably is brittle and breaks if you build tests with and without optimizations at some point..

**Comment by hvr** [comment]
@lspitzner less brittle: use `cabal-plan list-bin` :-)

**Comment by fgaz** [comment]
Continuing on https://github.com/haskell/cabal/issues/3638#issuecomment-318907673,

That's because @hvr's example uses (currently) incorrect syntax.

As with `new-run`, the full syntax is:

```
cabal new-test --cabal-flags -- test-name -- --test-flags and test args
```

The first `--` separates cabal flags and targets, and the second one separates targets and targets' args.

This correctly parses as
```haskell
["test-name","--","--test-flags","and","test","args"]
```

**Comment by ezyang** [comment]
Let me offer one more unsolicited suggestion: maybe `cabal new-test` should NOT support running multiple tests. If you want multiple tests, make a new command or something.

**Comment by hvr** [comment]
I somewhat sympathize with @ezyang's suggestion; it would probably make things simpler and less surprising.

**Comment by phadej** [comment]
Yes, there should be a way to run *all tests* (in project/package) without knowing the test-suite names.

**Comment by fgaz** [comment]
Partially fixed with #4861 (new-run can now run tests/benchs and it can pass arguments).

new-test still cannot pass arguments.

**Comment by sjakobi** [comment]
I'd love to see a fix for this! I think the `new-run` workaround doesn't work for me because it doesn't support `--allow-newer`.

**Comment by l29ah** [comment]
`new-test` and `new-bench` still don't accept args via `--`, as seen with cabal-3.6.2.0

**Comment by ulysses4ever** [comment]
@l29ah unfortunately, this is correct. The corresponding issue is #6198. There's a draft PR attached to it (#7454) with a simple and straightforward design, but it's abandoned, as far as I can see. Do you want to try to pull it out? We're happy to advise.
