### ISSUE TITLE
new field for version policy

### ISSUE THREAD

**Issue by bos** [haskell/cabal#465]
(Imported from [Trac #472](http://hackage.haskell.org/trac/hackage/ticket/472), reported by @dcoutts on 2009-01-21)

We would like packages to be able to describe what version policy they use.

One common policy that we have been discussing is called the [Package versioning policy](http://haskell.org/haskellwiki/Package_versioning_policy) or PVP for short. In particular we would like packages to be able to opt-in to following this policy. It would enable hackage to enforce the policy (with a suitable API-checking tool) which should provide a strong guarantee for client packages. In addition it would allow hackage and cabal to make suggestions for packages about dependencies on packages that follow the polciy. For example it could suggest not using upwardly open version ranges.

So we would like a reasonably extensible syntax for packages to specify what version policy they follow. One suggestion is:

<pre class="wiki">version-policy: PVP-1
</pre>That is named (and versioned) policies. The names would have to be well known and defined elsewhere. Only known policies could only be enforced. As with other similar meta-data, the value should be parsed but allow unknown policies. Hackage could reject unknown policies, but it would enable people to make in-house modifications to add new policies.

**Comment by BardurArantsson** [comment]
Last change on this was 2009(!) pre-import. I'll add a reference to #1703 just in case, but I think this can be closed.
