### ISSUE TITLE
new-build busted on macOS Sierra

### ISSUE THREAD

**Issue by angerman** [haskell/cabal#4653]
As mentioned in #4651, new-build's dynamic library paths end up being quite long,
this then easily exhausts the load command size of the shared library with messages
like:

```
malformed mach-o: load commands size (33576) > 32768
```

I don't really know how to fix this properly. We'd need to drastically reduce the length
of library names :-/

**Comment by 23Skidoo** [comment]
This is duplicate of #4263.
