### ISSUE TITLE
cabal-install needlessly reinstalls an existing package

### ISSUE THREAD

**Issue by bos** [haskell/cabal#467]
(Imported from [Trac #474](http://hackage.haskell.org/trac/hackage/ticket/474), reported by judah on 2009-01-23)

With ghc-6.10.1, Cabal-1.6.0.1 and cabal-install-0.6 (or HEAD):

<pre class="wiki">$ cabal install cabal-install --dry-run -v
[..]
Reading available packages...
Resolving dependencies...
[..]
selecting Cabal-1.6.0.1 (installed or hackage)
[..]
selecting process-1.0.1.1 (installed or hackage) and discarding filepath-1.0,
process-1.0.0.0 and 1.0.1.0
[..]
In order, the following would be installed:
Cabal-1.6.0.1 (reinstall) changes: process-1.0.1.0 -&gt; 1.0.1.1
cabal-install-0.6.0 (new package)
</pre>The <tt>ghc</tt> package depends on <tt>Cabal-1.6.0.1</tt> and <tt>process-1.0.1.0</tt>, so rebuilding <tt>Cabal</tt> to depend on <tt>process-1.0.1.1</tt> causes <tt>ghc</tt> to have inconsistent dependencies.  In particular:

<pre class="wiki">$ cabal install cabal-install
[succeeds, but reinstalls Cabal-1.6.0.1]
$ cabal install ghci-haskeline
Resolving dependencies...
cabal: dependencies conflict: ghc-6.10.1 requires process ==1.0.1.0 however
process-1.0.1.0 was excluded because ghc-6.10.1 requires process ==1.0.1.1
</pre>It seems like the right thing to do would be to use <tt>process-1.0.1.0</tt> when building <tt>cabal-install</tt>.

**Comment by BardurArantsson** [comment]
Last report was in 2012. Maybe just... close? If there's a larger-scale problem here (and with other old reports), perhaps we should try to gather a "Task Force" to figure out what's wrong?

(I'll volunteer.)

**Comment by 23Skidoo** [comment]
OK, closing as obsolete. If anyone objects, feel free to reopen. Or maybe just open an enhancement request.
