### ISSUE TITLE
'cabal check' should warn when there are no upper bounds in setup-depends

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4683]
`wxc` [has the following `custom-setup` section](http://hackage.haskell.org/package/wxc-0.92.3.0/wxc.cabal):

```
custom-setup
  setup-depends: 
    base, 
    Cabal,
    bytestring,
    split,
    process,
    directory,
    filepath
```

That is, it says that its setup.hs works with any version of Cabal. However, it is lying - it actually fails to build against Cabal 2. We should warn about such obviously incorrect `setup-depends` and maybe even auto-rewrite the constraint on Cabal to < 2.

**Comment by 23Skidoo** [comment]
Related: https://sourceforge.net/p/wxhaskell/bugs/112/

**Comment by hvr** [comment]
As discussed on IRC, it'd also make sense to validate that the lower bound on lib:Cabal is consistent with the spec-version specified in the .cabal file.

**Comment by grayjay** [comment]
> As discussed on IRC, it'd also make sense to validate that the lower bound on lib:Cabal is consistent with the spec-version specified in the .cabal file.

#3751 is related to this.

**Comment by phadej** [comment]
If you review&accept my #4701, then I'd like to tackle this as a follow-up ;)

**Comment by phadej** [comment]
Note: 

```
      +++ custom-setup
      +++     setup-depends: base -any
      +++                    Cabal -any
      +++                    cabal-doctest >=1.0.2 && <1.1
```

here I know that omitting upper bounds on Cabal is safe. Cabal dependency is needed because of https://github.com/haskell/cabal/issues/4288

**Comment by qnikst** [comment]
I'm going to work on this

**Comment by ulysses4ever** [comment]
Since #7409 has been megen, this probably can be closed. Cc @Mikolaj

**Comment by Mikolaj** [comment]
Right. High time. :)

Thank you again, @ulysses4ever, @qnikst and everybody who took part in the struggle.

**Comment by ulysses4ever** [comment]
Thanks a lot @Mikolaj for helping out with it!
