### ISSUE TITLE
Allow new-run test-suites and benchmarks

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4684]
E.g.

```
cabal new-run benchmarks -o bench.html
cabal new-run specs SpecificSpec
```

IMHO way simpler then working with `--test-options` or `--bench-options` (which `new-test` doesn't accept. does it)

**Comment by hvr** [comment]
Related discussion in https://github.com/haskell/cabal/issues/3638#issuecomment-318907673 and https://github.com/haskell/cabal/issues/4643#issuecomment-321526868
