### ISSUE TITLE
Cabal-install binaries on haskell.org

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#4688]
Hi All,

I've noticed that since Cabal 2.0 the binaries are no longer hosted on Haskell.org and instead it points you to use Halcyon. This however is a problem as it means I have no "trusted" source to download the binaries for when packaging https://chocolatey.org/packages/cabal since GHC's binaries aren't reproducible. I won't be able to convince the package reviewer that the binaries are unmodified if I build them myself.

It would be really helpful if the binaries for Windows could still be produced, if it's a resource issue, I can build binaries for any tagged release and upload them if it makes it easier.

Thanks,
Tamar

**Comment by 23Skidoo** [comment]
I'll post them today/tomorrow.

**Comment by Mistuke** [comment]
Thanks!

**Comment by 23Skidoo** [comment]
This has been fixed.
