### ISSUE TITLE
Building with Stack is broken

### ISSUE THREAD

**Issue by tfausak** [haskell/cabal#4691]
After a fresh clone (at f3a5767f95e575d8c1a59a18a351b89472432451), I am unable to build this project with Stack:

```
cabal> stack test
Invalid flag specification:
- Package 'Cabal' does not define the following flags (specified in stack.yaml):
  parsec
- Flags defined by package 'Cabal':
  Cabal:bundled-binary-generic
  Cabal:old-directory
  Cabal:parsec-struct-diff
- Package 'cabal-install' does not define the following flags (specified in stack.yaml):
  parsec
- Flags defined by package 'cabal-install':
  cabal-install:debug-conflict-sets
  cabal-install:debug-expensive-assertions
  cabal-install:debug-tracetree
  cabal-install:lib
  cabal-install:monolithic
  cabal-install:network-uri
  cabal-install:old-bytestring
  cabal-install:old-directory
```

I think #4654 caused this.

**Comment by 23Skidoo** [comment]
Yep, it has been broken for a while because most active contributors don't use Stack.

**Comment by tfausak** [comment]
Sure, but Travis CI is supposed to be testing with Stack: https://github.com/haskell/cabal/blob/f3a5767f95e575d8c1a59a18a351b89472432451/.travis.yml#L84

Two problems with that though:

- It manually sets a resolver, which is weird because the `stack.yaml` already does that.
- It is allowed to fail, and has indeed been failing: https://travis-ci.org/haskell/cabal/jobs/264667352#L548

**Comment by 23Skidoo** [comment]
> It manually sets a resolver,

If you think that this is wrong, feel free to fix!

> It is allowed to fail,

This is by design, we want to be aware whether it works or not (plus it's useful for validating PRs such as this one), but we don't want to impose the burden of keeping it working on all our contributors. See e.g. [here](https://github.com/haskell/cabal/pull/4667#issuecomment-321036564).

**Comment by tfausak** [comment]
> This is by design, we want to be aware whether it works or not (plus it's useful for validating PRs such as this one), but we don't want to impose the burden of keeping it working on all our contributors.

Why even bother having it? It's been broken for at least 5 months: https://travis-ci.org/haskell/cabal/jobs/208471402

**Comment by 23Skidoo** [comment]
> Why even bother having it?

Um, I think I explained it? Because we find it occasionally useful when someone who uses Stack for working on Cabal decides to fix it.

**Comment by tfausak** [comment]
My point was that it's been broken for a long time, so it seems like you aren't really aware of whether it works or not.

**Comment by 23Skidoo** [comment]
I was aware, I just don't use Stack for working on Cabal so I never bothered with fixing it.
