### ISSUE TITLE
new-run doesn't seem to run anything

### ISSUE THREAD

**Issue by chris-martin** [haskell/cabal#4699]
I'm trying to run an executable from [this Backpack demo](https://github.com/chris-martin/backpack-regex-example/tree/cb8e651092c0cd855d8fd664e711c2bef4c11645) using `new-run`. It seems to only *build* the executable, but it does not *run* it.

```
> nix-shell --pure --run 'cabal new-run regex-example:regex-example'
Up to date
```

If I search for the artifact ...

```
> find -name regex-example -type f
./dist-newstyle/build/x86_64-linux/ghc-8.2.1/regex-example-0.1.0.0/c/regex-example/build/regex-example/regex-example
```

... then it seems I can run it myself:

```
> ./dist-newstyle/build/x86_64-linux/ghc-8.2.1/regex-example-0.1.0.0/c/regex-example/build/regex-example/regex-example
True
True
```

Cabal version:

```
> nix-shell --pure --run 'cabal --version'
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library
```

Am I using it wrong, or is this feature not complete?

**Comment by 23Skidoo** [comment]
This is fixed in `master`.
