### ISSUE TITLE
Seemingly incorrect Haddock generation for BuildInfo

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#4703]
While viewing the Haddocks, I see the following:
<img width="1002" alt="screen shot 2017-08-17 at 9 52 55 am" src="https://user-images.githubusercontent.com/49415/29399428-e04d3cf2-8331-11e7-9b70-19f7cd936494.png">

Looks like Haddock is having trouble parsing the markup here, and has put the docs for `buildTools` into the `buildable` docs. Happy to send a PR to fix this up, just confirming I'm not missing something first.

**Comment by snoyberg** [comment]
Just noticed as well: It looks like the `BuildToolDepends` link is supposed to be a module link, I can update that at the same time.

**Comment by 23Skidoo** [comment]
Yes, these two look like bugs. A fix would be appreciated.
