### ISSUE TITLE
[cabal-install only] ci flag

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#4721]
Building and testing Cabal takes about half (~2 hours of 4 on travis) of ci time,  What if we added a flag to disable Cabal recompilation and instead used a cached binary for commits that only touch cabal-install?

A [Cabal only] flag is less useful, as changes in Cabal can have consequences in cabal-install.

EDIT:
I'm talking about a flag in the commit message (like [ci skip]).
When activated we should skip all the Cabal building and remove the inplace Cabal from the cabal.project before building cabal-install (so travis can cache it).

Or instead we could conditionally add/retrieve part of dist-newstyle to/from the travis cache.

**Comment by 23Skidoo** [comment]
> I'm talking about a flag in the commit message (like [ci skip]).

If there's a way to make the overall scheme work, I think it could be automated further by making the script look at the diff and automatically skip commits that only touch the `Cabal/` subdirectory.

**Comment by fgaz** [comment]
Yes, but then we'll need some more advanced caching and/or diffing.
For example what if the previous commit _did_ modify Cabal _but_ it was [ci skip]ped? We need to check the diff against the Cabal in cache. One solution could be to save in the cache a Cabal-git-hash file containing the sha of the last built commit.
Or we could make a diff with the source directly if it's saved in the cache too.
Or again we could change Cabal's version to something like 2.0.0.0.[git hash] (this has problems with ordering).

**Comment by fgaz** [comment]
Wait, is this related? https://github.com/haskell/cabal/blob/d18c05629eb60cb7195310f4a9850078616d16c0/travis-script.sh#L95

**Comment by fgaz** [comment]
@phadej like the [ci skip] one, I guess this can be closed?

**Comment by phadej** [comment]
Yes. This is not relevant anymore.
