### ISSUE TITLE
cabal fetch should support the --enable-tests option

### ISSUE THREAD

**Issue by asr** [haskell/cabal#4723]
Is there some reason why `cabal fetch` is not supporting the `--enable-tests` option?

**Comment by 23Skidoo** [comment]
No deep reason, patches welcome.

**Comment by dalaing** [comment]
Is this closed by the merged PR, or do we want to keep it around as a reminder for when cabal new-fetch lands?

**Comment by 23Skidoo** [comment]
Fixed by #4948.
