### ISSUE TITLE
Local bootstrap.sh fails but CI bootstrap looks successful

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#4744]
Despite bootstrap.sh on travis-ci being successful, I failed to bootstrap locally for a few weeks. The last successful build is from August 11th.

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

Error:
```
Registering hackage-security-0.5.2.2...
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Configuring cabal-install-2.1.0.0...
Setup: Encountered missing dependencies:
Cabal ==2.1.*,
bytestring >=0.9 && <0.10.2,
bytestring-builder >=0.10 && <1,
directory ==1.1.*,
network >=2.4 && <2.6,
process >=1.0.1.1 && <1.1.0.2

Error during cabal-install bootstrap:
Configuring the cabal-install package failed.
```

**Comment by phadej** [comment]
hmm. looks like revisions aren't applied. Does @hvr have any insight on this?

**Comment by 23Skidoo** [comment]
Weird, the bootstrap script does download updated `.cabal` files from Hackage.

**Comment by BardurArantsson** [comment]
Not that this is a solution, but if you want a workaround (and already have a semi-recent Cabal), I've had good success with just building cabal-install locally (in its own directory) by simply doing a git clone and then using `cabal new-build cabal-install`. The executable will be in `dist-newstyle/build/cabal-install-2.1.0.0/build/cabal/cabal`.

(You might also need a `cabal update` before the `new-build`.)

**Comment by tuncer** [comment]
@BardurArantsson, part of why I use bootstrap.sh is to incorporate Cabal with the same git revision. Would `new-build` use `../Cabal/`?

**Comment by BardurArantsson** [comment]
@tuncer You should run the `cabal new-build ...` command in the top-level directory. And yes, it will use the 'local' Cabal, etc. (See `cabal.project` file for what it includes.)

You do (apparently) get some extra assertion code which may be time-consuming (at runtime), so you may want to edit that out of the `cabal.project` file. (I haven't noticed any problems with this, but YMMV.)

**Comment by tuncer** [comment]
@BardurArantsson, I tried that and ran into linker errors. I also remembered the other reason why I use bootstrap.sh: Getting a Haskell environment ready after building/installing GHC.

**Comment by tuncer** [comment]
@23Skidoo, do we know what the bug is?

**Comment by BardurArantsson** [comment]
@tuncer Hm, odd. Are you using Arch Linux by any chance?

**Comment by tuncer** [comment]
@BardurArantsson, it was Arch Linux in that case, yes. FWIW, new-build works for other packages like brittany or darcs, so I don't think it's a general problem.

**Comment by 23Skidoo** [comment]
@tuncer I'll look into this once I'm back from ICFP.

**Comment by BardurArantsson** [comment]
@tuncer If you're using the 'community' repository GHC then it's very likely an Arch problem since they switched to dynamic linking. The package maintainer(s) screwed the pooch soooo badly on that one. (See https://wiki.archlinux.org/index.php/Haskell for details.) 

I ended up just using the 'ghc' from the "haskell-core" repository mentioned here: https://wiki.archlinux.org/index.php/ArchHaskell

**Comment by tuncer** [comment]
@BardurArantsson, I've been using a locally bootstrapped GHC for years, but I've seen the various GHC packages they now carry. I actually thought you meant there might be a problem with LD.

**Comment by BardurArantsson** [comment]
Ah, right, nvm then. If you're sure you aren't/weren't using the Arch GHC then it's definitely not related to that. :/

**Comment by tuncer** [comment]
Today's master (e63c0f3a9) bootstrapped successfully. Therefore, closing as resolved.
