### ISSUE TITLE
cabal-install 2.0.0.0 fails with ././dist/setup/setup.version: openFile: resource busy (file is locked) when confronted with cabal install 1.24 dist directory

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#4753]
Summary: cabal-install 2.0.0.0 fails with ././dist/setup/setup.version: openFile: resource busy (file is locked) when confronted with cabal install 1.24 structure

More details:
When trying to compile haskell projects compiled with `cabal-1.24` before, and not removing the `dist` directory, `cabal-2.0.0.0` just crashes with above error.

Deleting the setup.version file makes this error go away.

**Comment by andreasabel** [comment]
If there is a commit / PR / subsuming issue documenting the fix / resolution of this issue, grateful to link it here.  (But no need to go to great lengths...)

**Comment by gbaz** [comment]
I should have commented when closing -- I consider this superseded by new-build -- i.e. this only affects v1-build and requires users starting from a particularly old version of cabal to get into this situation.
