### ISSUE TITLE
Backpack doesn't work with profiling

### ISSUE THREAD

**Issue by int-index** [haskell/cabal#4754]
The error:

```
[1 of 2] Compiling Slay.Number[sig] ( src/Slay/Number.hsig, /home/gumo/Projects/slay/dist-newstyle/build/x86_64-linux/ghc-8.2.1/slay-core-0/slay-core-0-inplace+JACzl5parSWAjZnfXRg086/build/slay-core-0-inplace+JACzl5parSWAjZnfXRg086/Slay/Number.p_o )

src/Slay/Number.hsig:1:1: error:
    • Could not find hi interface for signature ‘slay-core-0:Slay.Number’:
          Failed to load interface for ‘Slay.Number’
          Perhaps you haven't installed the profiling libraries for package ‘slay-core-0’?
          Use -v to see a list of the files searched for.
    • while checking that slay-number-double-0:Slay.Number.Double implements signature Slay.Number in slay-core-0[Slay.Number=slay-number-double-0:Slay.Number.Double]
  |
1 | signature Slay.Number where
  | ^
```

System configuration: Xubuntu, `ghc-8.2.1` and `cabal-head` installed from `ppa:hvr/ghc` (including `ghc-8.2.1-prof`).

The contents of `cabal.project.local`:

```
with-compiler: /opt/ghc/8.2.1/bin/ghc
profiling: True
```

Steps to reproduce:

1. clone https://github.com/int-index/slay
2. checkout `3fe9e38`
3. `cabal new-build all`

Without `profiling: True` the project builds fine.

**Comment by ezyang** [comment]
I can repro this on a pretty small example, this is almost definitely a GHC bug (also my responsibility ;)

**Comment by int-index** [comment]
> I can repro this on a pretty small example

That's great, thank you for looking into this.

>  this is almost definitely a GHC bug

Is there a GHC Trac ticket that I can subscribe to in order to be notified of the progress?

**Comment by ezyang** [comment]
Not yet!

**Comment by ezyang** [comment]
Actually, it's a Cabal bug. PR incoming.
