### ISSUE TITLE
Backpack is undocumented

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4761]
A user on Reddit [brought to my attention](https://www.reddit.com/r/haskell/comments/6z2gja/whats_new_in_cabalcabalinstall_20_improved/dmw6qzq/) that searching for "Backpack" in the user's guide [returns zero results](http://cabal.readthedocs.io/en/latest/search.html?q=backpack&check_keywords=yes&area=default#). It'd be nice if there was a Backpack section in the user's guide like we have for Nix integration, right now I have to refer people to posts on @ezyang's blog.

**Comment by ocharles** [comment]
I'm quite surprised Backpack officially made it into 2.0 (to the point of receiving the blessing of being in the Changelog), yet made it there without any documentation. I do not mean this in a snarky way, but is there a release process behind releasing `cabal-install`, and if so - should this process not require that all new user facing features be documented? Also, I see this isn't scheduled for a milestone yet - should it be?

**Comment by ezyang** [comment]
Hi @ocharles, the lack of documentation in the Cabal user manual was an oversight, due in part to the fact that the documentation is "elsewhere" (https://ghc.haskell.org/trac/ghc/wiki/Backpack ; the thesis contains a complete and accurate description of what Cabal supports). We definitely should add a Backpack section to the Cabal manual and it is one of my priorities.

**Comment by ocharles** [comment]
Awesome, thanks @ezyang. I hope I didn't come across too negative, though my question about whether documentation is part of the release manager's checklist does still stand.

**Comment by phadej** [comment]
@ezyang bump.

**Comment by 23Skidoo** [comment]
@ezyang, if you want to get this in before the next release, the branch-off date will be sometime around 15 Jan.

**Comment by sjakobi** [comment]
Bump! :)

**Comment by cartazio** [comment]
@hvr @ezyang has there been more action on this?

**Comment by cartazio** [comment]
bumpity bump bump :)

**Comment by ezyang** [comment]
btw, Backpack *is* explicitly mentioned in the user guide now, but there is not a Backpack section which puts it together
