### ISSUE TITLE
allBuildInfo does not include foreign library dependencies

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#4763]
This may be a misunderstanding on my part, I'm not familiar with foreign libraries outside of the type `ForeignLib` itself. But it appears that:

* A `ForeignLib` can introduce dependencies on packages
* The `allBuildInfo` function will not return the `BuildInfo` values within `ForeignLib`s

It seems like this means we will not necessarily track dependencies from `ForeignLib`s. Is this intentional?

**Comment by snoyberg** [comment]
I've introduced a modified version of `allBuildInfo` in Stack to work around this:

https://github.com/commercialhaskell/stack/commit/8f61b8cb5782dd25ea5cca77eef73485f4681925

If you look in that commit, you'll see a modification to an integration test (adding a foreign library dependency on the mtl package). Without the `allBuildInfo'` change, this causes an error when building. Note that I also tested `cabal-install-2.0.0.0` with both the `install` and `new-build` commands. Both of them installed `mtl`. So it appears to me at least that `cabal-install` has a different dependency tracking mechanism than `allBuildInfo`.

**Comment by ezyang** [comment]
This is a straight up bug in allBuildInfo and we should fix it.

**Comment by snoyberg** [comment]
Cool, I'll PR it then, since it's actually within my skill set :)

**Comment by 23Skidoo** [comment]
Also backported into the 2.0 branch.
