### ISSUE TITLE
Can't install without global package DB (internal error: unexpected package db stack)

### ISSUE THREAD

**Issue by Rufflewind** [haskell/cabal#4765]
Suppose `/tmp/package.conf.d` is a valid package DB that contains all the boot packages.  Now let's try installing any package, e.g. zlib:

```
$ cabal install --package-db=clear --package-db=/tmp/package.conf.d zlib

…

internal error: unexpected package db stack: [SpecificPackageDB
"/tmp/package.conf.d",SpecificPackageDB "dist/package.conf.inplace"]
CallStack (from HasCallStack):
error, called at
libraries/Cabal/Cabal/Distribution/Simple/Program/HcPkg.hs:460:18 in
Cabal-1.24.2.0:Distribution.Simple.Program.HcPkg
```

It seems that the module just isn't designed to handle cases like this at all: https://github.com/haskell/cabal/blob/4780c0af1ddaef8ddda14c2a14375fbfab52b899/Cabal/Distribution/Simple/Program/HcPkg.hs#L465-L478

Tested on cabal-install-1.24.0.2/Cabal-1.24.2.0

**Comment by gbaz** [comment]
closing as obsolete
