### ISSUE TITLE
macOS Sierra will not run the prebuilt macOS cabal-2.0 binary

### ISSUE THREAD

**Issue by cj285** [haskell/cabal#4767]
On macOS, the prebuilt cabal-install-2.0.0.0-x86_64-apple-darwin-sierra.xz cannot be marked executable.
I did `chmod -x cabal-2.0`, but I cannot run it.

**Comment by cj285** [comment]
whoops.... I was using chmod incorrectly, the syntax is +x
(that said, I imagine most users will have to chmod +x the Mac cabal binary locally so maybe we should add a hint / mention of the invocation in the docs?)

**Comment by 23Skidoo** [comment]
Looks like it needs to be a `.tar.xz` if we want to preserve permissions.

**Comment by cj285** [comment]
It was a .tar.xz file that I downloaded. I was just using chmod incorrectly, but it was lacking the executable in the local environment.

**Comment by 23Skidoo** [comment]
The prebuilt file on https://www.haskell.org/cabal/download.html is just an `.xz`, not a tarball.

From `man xz`:

>       After successfully compressing or decompressing the file, `xz` copies the
>       owner, group, permissions, access time, and modification time from  the
>      source  file  to the target file.

So we can sort of fix it by running `chmod +x cabal-install-2.0.0.0-x86_64-apple-darwin-sierra.xz` on the server, but I'm not sure that marking the `.xz` archive executable is a good idea.

**Comment by 23Skidoo** [comment]
I've replaced the file on server with a `.tar.xz`.
