### ISSUE TITLE
Release for GHC 8.2.2

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4772]
GHC 8.2.2 is quickly approaching and @hvr had mentioned that there are some Cabal fixes which should go in. Can we get a release with these fixes by the end of this week?

**Comment by hvr** [comment]
Ironically, I still need to look into that particular issue I was worried about... will look into this today

**Comment by 23Skidoo** [comment]
The 2.0 branch has already accumulated some fixes, the only issue blocking the 2.0 point release is #4624, a fix for which we really want to include in 2.0.1.0.

**Comment by 23Skidoo** [comment]
I bumped the versions of Cabal and `cabal-install` on the 2.0 branch.

**Comment by 23Skidoo** [comment]
Update on #4624: @hvr has a `cabal-install`-only fix in the pipeline, so #4624 is not blocking the lib:Cabal release.

**Comment by bgamari** [comment]
#4808 is a blocker.

**Comment by bgamari** [comment]
Unless instructed otherwise I will release 8.2.2 with adae1e7326f70fcc08794b42fa3ab207a69999c1.

**Comment by 23Skidoo** [comment]
@bgamari Can you please use 0d34d92cf3c414a3ca0e06708b9d15586014d15b instead?

**Comment by bgamari** [comment]
Sure.

**Comment by gbaz** [comment]
So now that GHC is released, should we cut a cabal lib and install release to match?

**Comment by hvr** [comment]
@gbaz `lib:Cabal` yes; `cabal-install` needs a little bit more work

**Comment by 23Skidoo** [comment]
New `lib:Cabal` release is out.
