### ISSUE TITLE
Unable to build `tensorflow-proto` with `new-build`

### ISSUE THREAD

**Issue by elliottt** [haskell/cabal#4774]
The `tensorflow-proto` package depends on an executable built by `proto-lens-protoc`, which isn't ending up in the store when building with e63c0f3a9db3172536d2f2fff15638fba98364a8. Is there a reason that the executable isn't making it into the store, or is there a change that needs to be made to the package to depend on it correctly?

If I build that dependency with a sandbox, and manually copy the executable into my path, the build makes it further, but then fails in part of the custom setup code from `proto-lens-protoc` (specifically, the `sDistHook` is called with `Nothing` for the `Maybe LocalBuildInfo` argument). I think that problem is best reported to the `proto-lens-protoc` author, but I figured that it would be worth mentioning here just in case there is an obvious solution.

**Comment by hvr** [comment]
Is this by any chance the same problem described in #4648?

**Comment by elliottt** [comment]
I think that this is in fact the same issue. I'll close this one, and favorite the other. Thanks!
