### ISSUE TITLE
build-tool-depends silently ignored for non-existent executable

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#4781]
Consider the following specification,

```
name:                dummypkg
version:             0
build-type:          Simple
cabal-version:       >=2.0

library
  default-language: Haskell2010
  build-tool-depends: mtl:imaginary-exe
```

when invoking `new-build`, this silently succeeds. And also, `plan.json` doesn't record any `exe-depends` from `dummypkg-0-inplace`  on `mtl`  as it would if `build-tool-depends` referred to an actually existing executable:

```json
    {
      "type": "configured",
      "id": "dummypkg-0-inplace",
      "pkg-name": "dummypkg",
      "pkg-version": "0",
      "flags": {},
      "style": "local",
      "dist-dir": ".../dist-newstyle/build/x86_64-linux/ghc-8.2.1/dummypkg-0",
      "depends": [],
      "exe-depends": [],
      "component-name": "lib"
    },

```

For a `build-tool-depends` declaration, I'd expect the solver to require the existence  of that executable in the respective package as a constraint to solve for. The reason being is that packages may start out as a library, and in later releases start adding an executable. Or sometimes executables may get renamed or removed.

/cc @grayjay @Ericson2314

**Comment by grayjay** [comment]
It looks like cabal doesn't solve for specific executables yet: https://github.com/haskell/cabal/blob/d53b6e0d908dfedfdf4337b2935519fb1d689e76/cabal-install/Distribution/Solver/Modular/IndexConversion.hs#L374-L376

That will probably require #4087.

**Comment by Ericson2314** [comment]
@grayjay yeah that was a stop-gap in lieu of per-component solving. Is a better solution possible now?

**Comment by phadej** [comment]
Can we make specific constraints, including only versions of package with an executable requested. That should work even we don't have per-component solving

**Comment by Ericson2314** [comment]
That would be nice. To be clear, this still fails on the Cabal library side of things, right? I added a bunch of tests and stuff for those failure cases.

**Comment by grayjay** [comment]
@Ericson2314 I don't know of a better solution now.

@phadej Where would the constraints be specified?  It seems like that would be easier to implement than complete per-component dependency solving.

**Comment by phadej** [comment]
@grayjay when the build-tool-depends executable is requested, we could elaborate that into more precise constraints than just package (+ bounds). I don't know how it happens now though :(

**Comment by grayjay** [comment]
I think that would need to happen in the solver, after it chooses to build a package that has a build-tool-depends dependency.  That corresponds to the first tree transformation that I described under "Component dependency validation steps" in https://github.com/haskell/cabal/issues/4087#issuecomment-287665861.  I don't think we need to add the other tree transformations as long as we continue to require the dependencies for all executables for each package.
