### ISSUE TITLE
add support for generating BOTH library and app stanzas in cabal init 

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#4784]
currently the choices are 

```
What does the package build:
   1) Library
   2) Executable
```
there should be an option 3: BOTH! 

this is something i've been wanting for a while :) 

@cj285 might be interested in trying this out as a newcommer task if cabal folks would support adding this change in maybe even 2.2/2.4? :)

**Comment by 23Skidoo** [comment]
> adding this change in maybe even 2.2/2.4? :)

Sure, why not?

**Comment by cartazio** [comment]
@cj285 do you still wanna  do this ?

**Comment by hvr** [comment]
this has been accomplished via #4916
