### ISSUE TITLE
Use of MIN_VERSION macros breaks Cabal's Setup.hs with GHC<8.0

### ISSUE THREAD

**Issue by DanielG** [haskell/cabal#4785]
When trying to compile Cabal's Setup.hs directly using `ghc --make Setup.hs` with GHC<8.0 or when using `-fno-version-macros` with GHC>=8.0 the compilation errors out because a couple of spots in the code now assume `MIN_VERSION` macros are always defined.

I wonder why the CI isn't catching this?

To reproduce:
```
$ ghc --make -fno-version-macros Setup.hs
```

Summary of problem spots:
```
Distribution/Utils/IOData.hs:36:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_bytestring(0,10,0)

Distribution/Parsec/ParseResult.hs:21:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,10,0)

Distribution/Parsec/ParseResult.hs:76:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,10,0)

Distribution/Compat/Map/Strict.hs:15:7: error:
    Ambiguous occurrence ‘fromSet’
    It could refer to either ‘Data.Map.fromSet’,
                             imported from ‘Data.Map’ at Distribution/Compat/Map/Strict.hs:22:1-53
                             (and originally defined in ‘containers-0.5.7.1:Data.Map.Base’)
                          or ‘Distribution.Compat.Map.Strict.fromSet’,
                             defined at Distribution/Compat/Map/Strict.hs:30:1
```

**Comment by 23Skidoo** [comment]
There's a comment in `Setup.hs` that bootstrapping does not work. See #3003 for the gory details. `Cabal.cabal` has `build-type: Simple`, so you should be able to install it with the version of Cabal that came with your GHC:

```
$ ghc-7.10.3 --make -i Setup.hs -outputdir tmp -o setup
[1 of 1] Compiling Main             ( Setup.hs, tmp/Main.o )
Linking setup ...
```

**Comment by 23Skidoo** [comment]
I'd accept your patch, though.

**Comment by DanielG** [comment]
Wow that's one hell of a tricky issue. That explains why the CI doesn't try to bootstrap and hence why these errors where introduced in the first place. Is there a good reason not to just fix them like I did in the commit above though?

I discovered this as part of work on cabal-helper, trying to get older Cabals (< 1.22.6) to install with cabal-install >1.24 without patching the source, by using Setup.hs directly. I guess I'll just have to bite that bullet and find some patches that work for each version instead.

**Comment by hvr** [comment]
> Is there a good reason not to just fix them like I did in the commit above though?

To be fair, your patch doesn't appear to fix this properly either, it just adds some heuristics which may provide an improvement of the situation in common cases (but I haven't looked too closely).

**Comment by 23Skidoo** [comment]
> To be fair, your patch doesn't appear to fix this properly either, it just adds some heuristics which may provide an improvement of the situation in common cases (but I haven't looked too closely).

Yep, but I think it's the best we can do.
