### ISSUE TITLE
Command to print `GHC_PACKAGE_PATH`

### ISSUE THREAD

**Issue by sgraf812** [haskell/cabal#4806]
There should really be a command to just print `GHC_PACKAGE_PATH` as set by `cabal exec`, like `stack path --ghc-package-path`. Or is there already a way to do this right now?

**Comment by phadej** [comment]
Doens't something like
```sh
cabal exec -- sh -c 'echo $GHC_PACKAGE_PATH'
```
work?

**Comment by sgraf812** [comment]
This doesn't work on Windows. Well, it works when going through `stack exec --no-ghc-package-path cabal -- exec -- sh -c 'echo $GHC_PACKAGE_PATH'`, but not when just doing `cabal exec -- sh -c 'echo $GHC_PACKAGE_PATH'` through a vanilla HP installation.

**Comment by phadej** [comment]
@sgraf812 note that (If i read code right) `cabal exec` doesn't always set GHC_PACKAGE_PATH, one scenario is when there is sandboxes involved (maybe stack triggers something like that in cabal, dunno).

What are you trying to do, maybe there is some other way to solve your X problem, without solving Y (= getting GHC_PACKAGE_PATH)?

**Comment by sgraf812** [comment]
I'm basically trying to solve https://stackoverflow.com/questions/46505007/access-ghc-package-database-in-test-and-benchmark-suite in a relatively portable way.

**Comment by phadej** [comment]
@sgraf812 one solution is to use `build-type: Custom`, in a way http://hackage.haskell.org/package/cabal-doctest does, so you get all needed flags.

With `doctest`, we have to feed `doctest` package-ids and package-db flags, for it to work properly. `cabal-doctest` "solves" that. The core problem seems similar. I'm not aware of easier, non-hacky solution. (Except adding custom code into `Cabal`)

**Comment by sgraf812** [comment]
OK, thanks. I'll look into it when I prepare a release for my prototype.

**Comment by 23Skidoo** [comment]
#3643 is possibly related.

**Comment by gbaz** [comment]
possibly could be solved by https://github.com/haskell/cabal/pull/7500 ?

**Comment by jneira** [comment]
> This doesn't work on Windows. Well, it works when going through `stack exec --no-ghc-package-path -- cabal exec -- sh -c 'echo $GHC_PACKAGE_PATH'`, but not when just doing `cabal exec -- sh -c 'echo $GHC_PACKAGE_PATH'` through a vanilla HP installation.

Hi, i usually use this trick to print the environment vars set by cabal:

```
PS D:\dev\ws\haskell\cabal> cabal exec -- cmd
Microsoft Windows [Versión 10.0.19044.1645]
(c) Microsoft Corporation. Todos los derechos reservados.

D:\dev\ws\haskell\cabal>echo %GHC_ENVIRONMENT%
D:\dev\ws\haskell\cabal\dist-newstyle\tmp\environment.-10396\.ghc.environment.x86_64-mingw32-8.10.7
```

Note i am not using `%GHC_PACKAGE_PATH%` as nowadays `cabal exec` is `cabal v2-exec` and it seems the v2 use ghc environment files tointeract with ghc instead the GHC_PACKAGE_PATH. But if it was set, it would be also printed
In fact v1-commands are deprecated and v1-exec does not exist anymore in cabal-3.6.2.0 

So as there was a suggestion to fix your original issue, motivation to print GHC_PACKAGE_PATH i would close this.
Feel free to reopen if you have any question or you think it should be keep alive.
