### ISSUE TITLE
Building dynamic profiled libraries?

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4816]
Currently it seems that there is no way to convince Cabal to build libraries in the `dyn_p` way. This renders it impossible to build projects which have plugin build dependencies with profiling enabled. The reason for this is that a profiled `ghc` will attempt to load the *plugin* built in the profiled way, which does not exist.

**Comment by ezyang** [comment]
To be clear, loading a profiled plugin is only useful when *GHC* is profiled, because a profiled plugin needs a profiled runtime. So this capability would be a lot less useful than you would think (although, certainly, we should support it...)

**Comment by bgamari** [comment]
Yes, that is true; this was the case that I encountered although my ticket description confused things. I've fixed the text.

**Comment by m0ar** [comment]
In our thesis we ran into an additional use case. We wanted to run profiling on a file containing the `ANN` pragma; this requires `.dyn_o` files for the payload data type to be available. 

Suspect it is then impossible to use Cabal with profiling for _anything_ using the `ANN` pragma.
