### ISSUE TITLE
Split sections is not supported

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4819]
Cabal has a `--enable-split-objs` flag yet no `--enable-split-sections`. Note that GHC recommends using section splitting in favor of object splitting wherever possible.

**Comment by 23Skidoo** [comment]
Isn't `-split-objs` just a synonym for `-split-sections` when the former is supported? Makes sense to use the correct name, though.

**Comment by bgamari** [comment]
Nope, `-split-objs` still enables object splitting, even if `-split-sections` is enabled. Hopefully in 8.6 we will be able to remove split objects entirely, at which point it will merely throw a warning.
