### ISSUE TITLE
Cabal 2.0 operations fail without an internet connection with default settings.

### ISSUE THREAD

**Issue by dalaing** [haskell/cabal#4821]
I updated my NixOS VM last night, which bumped my cabal versions to:
```
> cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library
```
and then tried to do some development on my train trip into work:
```
> cabal build
Warning: Caught exception during _mirrors lookup:dieVerbatim: user error
(cabal: '/run/current-system/sw/bin/nslookup' exited with an error:
)
Warning: No mirrors found for http://hackage.haskell.org/
dieVerbatim: user error (cabal: '/run/current-system/sw/bin/curl' exited with an error:
curl: (6) Could not resolve host: hackage.haskell.org
```

I can comment out the repository information in ~/.cabal/config as a temporary workaround, but it seems like a bad user experience that could be fixed.

**Comment by schmittlauch** [comment]
I, another Nix user, am affected by this as well. Particularly I have set up an isolated nixos container with an environment of all required Haskell dependencies already fetched at container-build time. At runtime the container has no internet access and thus cannot reach the hackage indexing servers.

Emptying the cabal config is a workaround, but please keep this use case in mind.

**Comment by phadej** [comment]
Use `active-repositories: :none` in `cabal.project` (with `cabal-install: 3.4`).
