### ISSUE TITLE
cabal-install cannot download gnuidn-0.2.2

### ISSUE THREAD

**Issue by peti** [haskell/cabal#4828]
Using `cabal-install` revision 63f14905badda69077c28d0f094e41f479ff8f64 from the current `master` branch, I get the following error trying to fetch http://hackage.haskell.org/package/gnuidn-0.2.2:

~~~
$ rm -rf ~/.cabal/packages/hackage.haskell.org/gnuidn && cabal get gnuidn-0.2.2
Downloading gnuidn-0.2.2...
Invalid package gnuidn-0.2.2
~~~

That doesn't seem right?

**Comment by 23Skidoo** [comment]
I can reproduce this. Looks like the failure comes from `hackage-security`.

/cc @edsko

**Comment by hvr** [comment]
@23Skidoo it's hackage-server#488 ; we mostly need a better error message explaining why the package is considered invalid (i.e. because it doesn't pass authenticity validation).

**Comment by peti** [comment]
Fixed by https://github.com/haskell/hackage-server/pull/644.
