### ISSUE TITLE
new-freeze does not freeze dependencies of executables

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#4832]
And even though some dependency is frozen, it will be rebuilt because an executable it depends on is updated. In the worst case, all your frozen dependencies will be re-built after a `cabal update` because somethink like "happy" has a new version.

`cabal-install-2.0.0.0`. The observed behaviour is consistent independent of using freeze file or project file `constraints` field.

Reproduction: Init empty cabal lib project, add dependency `gkt3`, try to restrict version of `happy` (an executable dependency) to something non-latest.

**Comment by hvr** [comment]
@lspitzner  That's a long-standing issue; we've had long conversations about this; most recent comment about this I can recall is https://github.com/haskell/cabal/issues/3502#issuecomment-282597043

**Comment by grayjay** [comment]
It looks like new-freeze currently doesn't add any qualifiers to the constraints in the freeze file ([CmdFreeze.hs](https://github.com/haskell/cabal/blob/4e85e44bebf6c3dae4cf924238dc95689bda311c/cabal-install/Distribution/Client/CmdFreeze.hs#L176)), so it only constrains the top-level dependencies.  It should probably at least use the `any` qualifier on every constraint until we finish implementing #3502.

**Comment by hvr** [comment]
@grayjay but if you simply add `any.` to all constraints, doesn't this risk the freeze file being inconsistent with the "unconstrained" install-plan computed  (and in the worst case, the freeze file being unsatisfiable)?

**Comment by grayjay** [comment]
I think that new-freeze already took the union of all of the versions in the install plan when calculating the constraints, to work around the lack of qualified constraints before they were added.  So this issue is probably a regression from when we made constraints like `happy == 1.19.8` only apply to top-level dependencies.  If cabal took the union of happy versions in the install plan and output an `any.happy` constraint, it would at least be able to prevent a project from picking up a newer version after an update.  I'll try to work on a fix.

**Comment by 23Skidoo** [comment]
> I think that new-freeze already took the union of all of the versions in the install plan when calculating the constraints

I think I saw `new-freeze` generate constraints of form `foo == x.y.z || == a.b.c`, is that a consequence of that behaviour?

**Comment by grayjay** [comment]
> I think I saw new-freeze generate constraints of form foo == x.y.z || == a.b.c, is that a consequence of that behaviour?

Yes

**Comment by 23Skidoo** [comment]
@grayjay Can it lead to situations where we read in a freeze file, but the solver chooses a different install plan than the one that was frozen? Do we have a ticket for fixing that?

**Comment by 23Skidoo** [comment]
@grayjay Thanks!
