### ISSUE TITLE
cabal-install will not read repository from custom config file

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#4845]
I copied the repository information from the default config file into my own config file, like so:
```
repository hackage.haskell.org
  url: http://hackage.haskell.org/

extra-lib-dirs: /nix/store/v2pvzmmkar9dsfx4s7gskf2q0zp9wlsn-openblas-0.2.20/lib /nix/store/zcrrq61k354gnjg80v840p232m6xdh3y-zlib-1.2.11-dev/lib /nix/store/1gymfh2rkiii6c5flk8w93xlqbp58g8h-zlib-1.2.11/lib
extra-include-dirs: /nix/store/v2pvzmmkar9dsfx4s7gskf2q0zp9wlsn-openblas-0.2.20/include /nix/store/zcrrq61k354gnjg80v840p232m6xdh3y-zlib-1.2.11-dev/include

program-locations
  ar-location: /nix/store/9i5bj3c48vrdb4m4khbhaipvhy3m0bh0-binutils-2.28.1/bin/ar
  gcc-location: /nix/store/qh1ikg5lsnhiglsrfjz9k69fhzq17v8h-gcc-wrapper-6.4.0/bin/gcc
  ld-location: /nix/store/qh1ikg5lsnhiglsrfjz9k69fhzq17v8h-gcc-wrapper-6.4.0/bin/ld
  strip-location: /nix/store/9i5bj3c48vrdb4m4khbhaipvhy3m0bh0-binutils-2.28.1/bin/strip
  tar-location: /nix/store/q6nivamar2h6havsq73iyhcdnfd5jw7h-gnutar-1.29/bin/tar
```
According to the default configuration file created by cabal-install, this is all the repository information that is required. Now cabal-install thinks there is no remote repository. `cabal update` gives
```
fromFlag NoFlag. Use fromFlagOrDefault
CallStack (from HasCallStack):
  error, called at ./Distribution/Simple/Setup.hs:169:21 in Cabal-2.1.0.0-7Zzlk2k1PajDtaVal7GI34:Distribution.Simple.Setup
  fromFlag, called at ./Distribution/Client/GlobalFlags.hs:142:8 in main:Distribution.Client.Global
```
which points to a missing default remote repository.

**Comment by ttuegel** [comment]
The answer is that one must add the line,
```
remote-repo-cache: /path/to/some/directory
```
This path should be `$HOME/.cabal/packages`, which is the default, but unfortunately only cabal-install can generate that value because `defaultCabalDir` is not configurable or accessible. I think the reasonable thing to do here would be to provide a default `remote-repo-cache`.

**Comment by hvr** [comment]
I ran into this as well with `head.hackage` at https://github.com/hvr/head.hackage/blob/aa5708a2b96e7a8d268d28efefd522866ccdd2de/scripts/head.hackage.sh#L33-L44
