### ISSUE TITLE
When invoking strip on Windows, make sure the output doesn't exist

### ISSUE THREAD

**Issue by ndmitchell** [haskell/cabal#4854]
See the report at https://github.com/commercialhaskell/stack/issues/3528, where I got:

```
mmWhpHwQRVjkjSBA
    Installing executable(s) in C:\sr\snapshots\3c4ad812\bin
    C:\Users\ndmit_000\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\mingw\bin\strip.exe: unable to rename 'C:\sr\snapshots\3c4ad812\bin\HsColour.exe'; reason: File exists

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
```

Seems that I probably hit Ctrl-C at an inopportune point previously, and the output of strip already existed, and thus strip failed (my hypothesis).

**Comment by hvr** [comment]
@ndmitchell afaik, you invoke `strip` by pointing it to an existing executable, and then `strip` performs its operation in-place. It's an internal implementation detail of `strip` which temporary filenames it uses, so there's little we can do here, as we obviously cannot (or rather should not attempt to) predict what temporary filenames some particular `strip` implementation will end up using (which in general may not even be deterministic).

**Comment by ndmitchell** [comment]
OK, suggest we ignore it for now, and if I reproduce it ever I'll reopen.

**Comment by simonmichael** [comment]
This happened to me today, here is the log: https://ci.appveyor.com/project/simonmichael/hledger/builds/19772103
A guess: the job might have been killed for exceeding a time limit.

**Comment by simonmichael** [comment]
And today, on a github windows runner:
```
2020-03-17T07:12:30.9674438Z 'cabal copy' failed.  Error message:
2020-03-17T07:12:30.9674861Z 
2020-03-17T07:12:30.9675128Z --  While building package happy-1.19.12 using:
2020-03-17T07:12:30.9675377Z       C:\Users\runneradmin\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.2.exe --builddir=.stack-work\dist\29cc6475 copy
2020-03-17T07:12:30.9675628Z     Process exited with code: ExitFailure 1
```
It went away on next push.
