### ISSUE TITLE
LibV09 requires makeAbsolute from directory>=1.2.2

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#4856]
When compiling with `directory-1.1` I get:
~~~~
Distribution/Simple/Test/LibV09.hs:40:28:
    Module `System.Directory' does not export `makeAbsolute'
~~~~

**Comment by phadej** [comment]
Is this `master`?

**Comment by amigalemming** [comment]
https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Test/LibV09.hs#L40

**Comment by hvr** [comment]
Ok, so this was introduced in https://github.com/haskell/cabal/commit/e76c4820cfbefafabb377a887f8771d097e58587 but it doesn't appear to have made it into the `Cabal-2.0.0.2` release... strange...

**Comment by 23Skidoo** [comment]
Fixed in af81cfb7237436bd52fdfdc2a5eb670fdfaf11b6. @hvr, thanks for investigating.

**Comment by amigalemming** [comment]
On Fri, 3 Nov 2017, Mikhail Glushenkov wrote:

> Fixed in af81cfb. @hvr, thanks for investigating.

There is still a makeAbsolute in 
cabal-install/Distribution/Client/CmdInstall.hs

**Comment by 23Skidoo** [comment]
@amigalemming 
Hmm, not sure we want to fix that, actually. It's `cabal-install` code (unlike the previous case, which was `lib:Cabal), and `makeAbsolute` is supported since GHC 7.10. I think I'll just update bounds and `bootstrap.sh`.

**Comment by hvr** [comment]
@23Skidoo that works too... :-)
