### ISSUE TITLE
cabal build and cabal install should emit warnings

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#4862]
If we are intending to transition to `cabal new-...` stuff then `cabal build` and `cabal install` should probably emit warnings saying that they are no longer the recommended way to do things.

[This ticket filed as discussed with `angerman` [on Haskell Reddit](https://www.reddit.com/r/haskell/comments/7a9d8b/why_is_cabal_so_bad_at_managing_modules/dpag3j0/)]

**Comment by angerman** [comment]
Thanks!

@23Skidoo, @hvr any objections to adding warnings when using the "old" commands?

**Comment by 23Skidoo** [comment]
Yep, it makes sense to add a warning in 2.2, but there should be an option to turn it off. I suggest something along the following lines:

```
Warning: The behaviour of this command will change in the upcoming 3.0 release. 
To read more about the upcoming changes, see <https://URL>. If you want to try 
the new behaviour right now, use the new-{build,install,test} set of commands 
instead of this one.
To turn this warning off permanently, add 'disable-new-build-warning: True' to your 
'~/.cabal/config' file.
```

**Comment by angerman** [comment]
I was thinking more of an encouraging warning: you likely want to use new-* unless you rely on the old behavior.

**Comment by tomjaguarpaw** [comment]
I don't know what you generally do for your deprecation process or what you planned for this functionality, but have you considered adding `old-build` and `old-install` and mentioning in the warning for `build` and `install` that they should use `old-build` and `old-install` if they want to preserve the behaviour in the next version?

**Comment by tomjaguarpaw** [comment]
That might make the transition easier.

**Comment by hvr** [comment]
@tomjaguarpaw tbh, it'd be great (at least that's the thing I can't wait to do) if we could get rid of the old codepaths asap in order to allow us to radically refactor and make the code-base less confusing; which would mean to get rid of the `old-*` commands with cabal 3.0  ideally

**Comment by tomjaguarpaw** [comment]
@hvr That's fair enough.  I'll slightly refine my suggestion then: whilst the old behaviour still exists add `old-..` aliases for it (that don't warn).

**Comment by hvr** [comment]
@23Skidoo please don't forget about this one!

**Comment by fgaz** [comment]
@typedrat isn't this done?

**Comment by typedrat** [comment]
I forgot to close it.

**Comment by typedrat** [comment]
See #5358, #5378.
