### ISSUE TITLE
The Parser for ModuleRenaming fails to skip some spaces

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#4864]
`(Foo as Bar)` parses, `( Foo as Bar)` does not. 

This leads to particularly awkward multi-line `mixins`.

It just looks like a couple of calls to `Parse.skipSpaces` were missed.

**Comment by fgaz** [comment]
Was this fixed in https://github.com/haskell/cabal/pull/5293 ?

**Comment by phadej** [comment]
I think so. (ditto other issue)
