### ISSUE TITLE
Per Module / Per Source file flags?

### ISSUE THREAD

**Issue by angerman** [haskell/cabal#4871]
Say I have a set of modules. On a given subset I want to apply say `-O0`. Or a set of c-sources, for which I want to apply say, `-fobjc-arc`. How can I model this in cabal right now?

Would we need support for new source file/module syntax?
```
MyModule(-fmy-flags)
```
or is there some alternative approach?

**Comment by 23Skidoo** [comment]
In the case of .hs files, can't you do that with the `OPTIONS_GHC` pragma?

**Comment by hvr** [comment]
Btw, you can also use SubLibs for that, if you need a group of modules to have a different BuildInfo (different build-depends, different ghc-options, different default-extensions etc), and using `{-# OPTIONS_GHC / LANGUAGE #-}` doesn't cut it

**Comment by angerman** [comment]
Ahh. SubLibs, where can I find more about that?

**Comment by 23Skidoo** [comment]
@angerman http://cabal.readthedocs.io/en/latest/developing-packages.html#library, C-f "internal libraries".

**Comment by ezyang** [comment]
Note that this would be fairly difficult to implement on top of `--make` builds, because GHC simply does not have the ability to specify flags for a specific module via this interface. You can work around this with one-shot compile mode (`-c`) but that has its own problems (compile-time perf is worse than with `--make`)

**Comment by angerman** [comment]
I believe internal libraries might be the correct solution. I'll still have to check if the final library will be linked properly. This came up while looking at building a cabal file for the `rts`. Which has custom flags for certain sources. I'll put this on the back of my queue for now, as ghc's rts is not, and can not yet be built with cabal.

**Comment by angerman** [comment]
I guess we can close this for now.
