### ISSUE TITLE
Backpack: Unsupported mutually recursive unit identifiers

### ISSUE THREAD

**Issue by alexbiehl** [haskell/cabal#4876]
In a project of mine I stumbled over this one:

```
$ cabal new-build
Error:
    Unsupported mutually recursive unit identifier
    In the stanza 'executable bug-example'
    In the inplace package 'bug-0.1.0.0'
```

But there is no actual mutual dependency!

See the following files for a reproducer:

## Bug.cabal
```
name:                bug
version:             0.1.0.0
-- synopsis:
-- description:
license:             BSD3
license-file:        LICENSE
author:              alexbiehl
maintainer:          alexbieh@...
-- copyright:
-- category:
build-type:          Simple
cabal-version:       >=2.0

library bug-sublib
  build-depends:      base, bug
  exposed-modules:   BugImpl
  reexported-modules: BugImpl as Bug
  default-language:   Haskell2010

library
  build-depends:       base >=4.10 && <4.11
  exposed-modules:     UsesBug
  signatures:          Bug
  default-language:    Haskell2010

executable bug-example
  build-depends:       base, bug-sublib
  default-language:    Haskell2010
```

## Bug.hsig

```
signature Bug where

bug :: String
```

## UsesBug.hs

```
module UsesBug where

import Bug

test = bug
```

I want to build an executable `bug-example`: The depenencies are basically: `bug-example -> bug-sublib -> bug`

You can also download the files archive from here: https://gist.github.com/alexbiehl/eb8e3a7381a5f5ef2eaf45dfa08d1aab

**Comment by ezyang** [comment]
The error message could be better but it hits the nail on the head: you're trying to recursively link bug-sublib and bug together, and this is not supported.  bug-sublib brings a signature named Bug into scope; and by reexporting BugImpl as Bug it also declares that this signature should be filled using BugImpl... which came from the same module as the Bug signature.

Put differently, the Cabal file above has a package that produces BugImpl and requires Bug, and you have said that you want Bug to be implemented via BugImpl. Circularity. This *can* work, but it is not implemented in GHC today.

**Comment by alexbiehl** [comment]
Sorry @ezyang. Your answer and http://blog.ezyang.com/2017/01/try-backpack-cabal-packages/ helped to get it right!

**Comment by mitchellwrosen** [comment]
Just to clarify, is it that a single package, regardless of how it is organized (private or public sub-libraries), cannot both require a signature and expose modules that satisfy that signature, for other packages to write e.g. this?

```
mixins:
  the-package requires (The.Package.Signature as The.Package.Implementation)
```

**Comment by mitchellwrosen** [comment]
My above comment is incorrect, I've spent an hour or so messing around with my cabal file organization - I have a sub-library that both requires a signature and provides an implementation for it (a signature "transformer" of sorts), and getting it imported into a test suite without the "unsupported mutually recursive unit identifier" was tricky.

**Comment by roconnor-blockstream** [comment]
@mitchellwrosen How did you solve it?  How did you get it imported into a test suite without the "unsupported mutually recursive unit identifier" error?

**Comment by roconnor-blockstream** [comment]
@ezyang Maybe you can help me here, because it seems that if you make an indefinite package whose signatures contains types that are defined in the indefinite package itself, it is most natural that whenever you implement that signature you will need to depend on the indefinite package that provides the types used in that signature.

**Comment by ezyang** [comment]
@roconnor-blockstream Yes, it's "natural", but it's not supported at the moment. So the usual fix for this situation is to make another small helper internal library to contain the types in question, and then have both the signature and the signature implementation depend on it.
