### ISSUE TITLE
Backpack breaks `cabal repl`

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#4881]
I can `cabal build` and `cabal install` a package built with backpack, but using `cabal repl` breaks:

Using the code from #4880:

```
mac:coda/ref/ski> cabal repl ski
Preprocessing library 'fun' for ski-0.0.1..
Building library 'fun' instantiated with Term = <Term>
for ski-0.0.1..
Preprocessing library 'direct' for ski-0.0.1..
Building library 'direct' for ski-0.0.1..
Preprocessing library 'fun' for ski-0.0.1..
Building library 'fun' instantiated with
  Term = ski-0.0.1-I5z4se7uXl9IVcfVdLnek8-direct:Direct
for ski-0.0.1..
generalInstalledPackageInfo: missing IPI for ski-0.0.1-I5z4se7uXl9IVcfVdLnek8-direct
CallStack (from HasCallStack):
  error, called at ./Distribution/Simple/Register.hs:458:28 in Cabal-2.0.0.2-inplace:Distribution.Simple.Register 
```

`cabal new-repl` works fine, but if the package is being built so that it can be installed or users need to build using the "legacy" style, this is a mess.

**Comment by ezyang** [comment]
Yes, this should work. I'll look into it.

**Comment by jneira** [comment]
As v1 commands are deprecated and `cabal v2-repl` works i would say make `cabal v1-repl` work with backpack is not a priority.

**Comment by Mikolaj** [comment]
I agree. However, we'd support any volunteers motivated to work on this. Closing.
