### ISSUE TITLE
allow Win32 2.6

### ISSUE THREAD

**Issue by joeyh** [haskell/cabal#4882]
My package depends on Win32-2.6, and stack fails to build it because Cabal depends on < 2.6. Please update the dependency.

**Comment by fgaz** [comment]
HEAD is already at < 2.7

**Comment by joeyh** [comment]
Cabal-1.24.2.0 builds with Win32-2.6 once dep is relaxed.

-- 
see shy jo

**Comment by 23Skidoo** [comment]
Relaxed the Win32 dependency on the 2.0 branch and on Hackage (for both 2.0.* and 1.24.* releases).
