### ISSUE TITLE
Allow cabal to build a cabal package that only has a main c file.

### ISSUE THREAD

**Issue by angerman** [haskell/cabal#4890]
Cabal currently expects there to be at least one Haskell module, which prevents the following cabal file to build:

```
cabal-version: >=2.1
Name: unlit
Version: 0.1
Copyright: XXX
License: BSD3
Author: XXX
Maintainer: XXX
Synopsis: Literate program filter
Description: XXX
Category: Development
build-type: Simple

Executable unlit
    Default-Language: Haskell2010
    Main-Is: unlit.c
    C-Sources: unlit.c
```

**Comment by hvr** [comment]
Here's btw an old related issue: #497

**Comment by 23Skidoo** [comment]
This should already work actually, see #1080 and [`PackageTests/CMain`](https://github.com/haskell/cabal/tree/2ea28cab3ce569b388b5226f0f10605f3d5ca2c1/cabal-testsuite/PackageTests/CMain).

**Comment by angerman** [comment]
@23Skidoo no. That test, has a crucial ingredient: the `Bar.hs` module.

**Comment by 23Skidoo** [comment]
Ah, OK. Shouldn't be that hard to fix, I think.

**Comment by 23Skidoo** [comment]
@hvr
> I'm specifically thinking about the GHC RTS; shall it be available to a `main-is: main.c` w/o any haskell modules?

I'd say that it shouldn't, unless you have requested it explicitly with something like `build-depends: rts`. Though I'm not sure that that's how `ghc -c foo.c` works right now.
