### ISSUE TITLE
Add '--with-msys-location=/path/to/msys' to 'cabal user-config init'

### ISSUE THREAD

**Issue by pold500** [haskell/cabal#4901]
Cmd: cabal install hindent

Cabal output:
$ cabal install hindent
Resolving dependencies...
Downloading distributive-0.5.3...
Downloading hashable-1.2.6.1...
Configuring old-time-1.1.0.3...
Downloading lifted-base-0.2.3.11...
Downloading temporary-1.2.1.1...
Configuring distributive-0.5.3...
Configuring hashable-1.2.6.1...
Configuring temporary-1.2.1.1...
Configuring lifted-base-0.2.3.11...
Building hashable-1.2.6.1...
Building temporary-1.2.1.1...
Building lifted-base-0.2.3.11...
Failed to install old-time-1.1.0.3
Build log ( C:\Users\dmytriie\AppData\Roaming\cabal\logs\ghc-8.2.1\old-time-1.1.0.3-B8XpIJbhq9uLX1PMmzKlcp.log ):
Configuring old-time-1.1.0.3...
configure: WARNING: unrecognized options: --with-compiler
checking for gcc... C:\PROGRA~1\HASKEL~1\826561~1.1\mingw\bin\gcc.exe
checking whether the C compiler works... no
configure: error: in `/cygdrive/c/Users/dmytriie/AppData/Local/Temp/cabal-tmp-21116/old-time-1.1.0.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
cabal: Leaving directory 'C:\Users\dmytriie\AppData\Local\Temp\cabal-tmp-21116\old-time-1.1.0.3'
Installed temporary-1.2.1.1
Installed hashable-1.2.6.1
Installed lifted-base-0.2.3.11
Building distributive-0.5.3...
Installed distributive-0.5.3
cabal: Error: some packages failed to install:
cpphs-1.20.8-5cEQ4JG4zEO48rflCalI7n depends on cpphs-1.20.8 which failed to
install.
haskell-src-exts-1.19.1-GkIKqZuv8CjDj4xYyAfokK depends on
haskell-src-exts-1.19.1 which failed to install.
hindent-5.2.4.1-6Jn2HtqpNbYCTNcSVqr91c depends on hindent-5.2.4.1 which failed
to install.
old-time-1.1.0.3-B8XpIJbhq9uLX1PMmzKlcp failed during the configure step. The
exception was:
ExitFailure 77

OS type: Windows 10 Professional
Cabal version: 
$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library

**Comment by hvr** [comment]
Please look through the `old-time` issue tracker; this is a common issue: https://github.com/haskell/old-time/issues?utf8=%E2%9C%93&q=is%3Aissue

/cc @Mistuke @gbaz

**Comment by gbaz** [comment]
i have a wip branch right now, just going to add a generic "append" flag that can take a range of arguments. more long-term flexibility and generalizability this way -- it gives a generic hook to update cabal config files with configurable flags per distro.
