### ISSUE TITLE
Backpack: unknown package: hole

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#4908]
When building [this package](https://github.com/ekmett/coda/tree/3d994c3405515e8c2712ae4953790a2d970bd0e7/lib/coda-set) I get this error:

```
mac:coda/lib/coda-set> cabal new-build
In order, the following will be built (use -v for more details):
 - coda-set-0.0.1 (lib) (first run)
Preprocessing library for coda-set-0.0.1..
Building library instantiated with Elem = <Elem>
for coda-set-0.0.1..
<command line>: unknown package: hole
```

If I replace the stupidly small `Elem` signature with a `.hs` stub the package compiles.

All my other backpack projects build just fine.

**Comment by phadej** [comment]
```
20:58  edwardk what bugs me is i don't see at all how this package is at all different than say, coda-dyck which works just fine
20:59  edwardk its literally the same cabal file with a couple of tweaks
```

With released 8.2.1 it works, with 8.2.1.20171030 or 8.2.2 it doesn't.

**Comment by ekmett** [comment]
I was able to reduce the issue to the (unused) `{-# language CPP #-}` pragma in `Set.Internal`. 

There appears to be an issue with backpack and `CPP` in the release candidate.

**Comment by int-index** [comment]
The same error triggered by an unused `TemplateHaskell` pragma, as I reported here https://github.com/haskell/cabal/issues/4905#issuecomment-346595064

**Comment by ezyang** [comment]
https://phabricator.haskell.org/D4234 is a patch which should fix this.

**Comment by ezyang** [comment]
Fix is in GHC HEAD.
