### ISSUE TITLE
Backpack: Too long paths for Windows

### ISSUE THREAD

**Issue by alexbiehl** [haskell/cabal#4914]
A project of mine which uses Backpack fails to compile on Windows: 

```
CreateDirectory "C:\\Users\\abiehl\\git\\ignite\\dist-newstyle\\build\\x86_64-windows\\ghc-8.2.1\\ignite-0.1.0.0\\l\\ignite-prelude-indef\\ignite-0.1.0.0-inplace-ignite-prelude-indef+8Vkgfyobi1D5mXxZcObkdr\\build\\ignite-0.1.0.0-inplace-ignite-prelude-indef+8Vkgfyobi1D5mXxZcObkdr": does not exist (Der Dateiname oder die Erweiterung ist zu lang.)
```
_"Der Dateiname oder die Erweiterung ist zu lang"_ is a complaint about a too long path. 

Would it be possible to compress the path a bit?

**Comment by hvr** [comment]
Windows' `MAX_PATH` is the truly the gift that keeps on giving... ;-)

**Comment by ezyang** [comment]
Blegh. The filepath shenanigans are not that easy to fix, but I'll try to resolve it again.

**Comment by Mistuke** [comment]
If the linked PR does not fix this, can I have a small repro for this? I don't know how to make a backpack example :)

**Comment by ezyang** [comment]
I don't see any reason why Backpack wouldn't have been fixed by your patch too :) I'm going to close this unless it pops up again.

**Comment by hvr** [comment]
@Mistuke fwiw, see https://github.com/alexbiehl/ignite
