### ISSUE TITLE
UTF-8 encoding/decoding is broken

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#4927]
The UTF-8 encoding/decoding functions in `Distribution.Utils.String` are broken:

```
ghci> (decodeStringUtf8 . encodeStringUtf8) "\65534"
"\65533"
```

I believe this means that `encodeStringUtf8` is producing invalid UTF-8.

CC: @hvr 
See also: #4902

**Comment by hvr** [comment]
@ttuegel I know... :-) see https://github.com/haskell/cabal/issues/4644#issuecomment-318897407

**Comment by 23Skidoo** [comment]
@hvr Is this a duplicate? Feel free to close then.

**Comment by hvr** [comment]
@23Skidoo yeah; it's imho the same issue
