### ISSUE TITLE
"cabal init" should support support --with-ghc

### ISSUE THREAD

**Issue by bitc** [haskell/cabal#4936]
"cabal init" should be consistent with the other cabal commands and allow "--with-ghc":

```
$ cabal init
cabal: The program 'ghc' version >=6.11 is required but it could not be found.
$ cabal init --with-ghc=/opt/ghc-8.2.2/bin/ghc
cabal: unrecognized 'init' option `--with-ghc=/opt/ghc-8.2.2/bin/ghc'
```

**Comment by NathanConroy** [comment]
For the record, this option flag appears can appear as "-w" and "--with-compiler=PATH" and possibly others ...

**Comment by 23Skidoo** [comment]
Why does it need to run `ghc`? To get the available packages?

**Comment by fgaz** [comment]
@23Skidoo when running `cabal init` it tries to guess the dependencies (only from the global packagedb or sandbox I think), extensions and some other things

**Comment by 23Skidoo** [comment]
OK. Makes sense for it to support `-w` then.
