### ISSUE TITLE
Build failures with GHC 7.6.3 and cabal-install 2.0

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#4938]
I include build matrices on Travis that sometimes include GHC 7.6.3. Usually I use the version of cabal-install shipped with that GHC version for testing, but on some projects I've moved over to the latest cabal-install instead to work around various issues. For example, on conduit I wrote https://github.com/snoyberg/conduit/commit/6f927d6d447ee06849d6826e986980fbf93a0fc6#diff-354f30a63fb0907d4ad57269548329e3, which was to work around #4298.

In any event: I've been mashing the "rebuild" button on Travis for about an hour now to no avail, so  thought this may be more than the average transient issue. If you look at this build log:

https://travis-ci.org/snoyberg/conduit/jobs/312229576

Also captured at:

https://gist.github.com/snoyberg/a4a42ff57ff41d6936b40394612615cb

You can see this message:

```
[22 of 22] Compiling Test.Hspec.Core.QuickCheck ( src/Test/Hspec/Core/QuickCheck.hs, dist/build/Test/Hspec/Core/QuickCheck.o )
ghc-pkg: /home/travis/.ghc/x86_64-linux-7.6.3/package.conf.d/vector-algorithms-0.7.0.1-7zMncRCjKkbBZ9Ytp6Vr7N.conf: openFile: does not exist (No such file or directory)
cabal: Leaving directory '/tmp/cabal-tmp-4299/hspec-core-2.4.4'
...
cabal: Error: some packages failed to install:
hspec-2.4.4-4lYAiXTfQoECkvTLFxQttA depends on hspec-2.4.4 which failed to
install.
hspec-core-2.4.4-BLSH50pLGoAAf4aExUu4ut failed during the building phase. The
exception was:
ExitFailure 1
```

It appears that, for some reason, cabal-install-2.0 is having trouble building packages with GHC 7.6.3. My guess is that this has to do with parallel builds, and lack of filesystem locking in ghc-pkg. I know that in Stack, we've implemented a lock to ensure that only one process triggers a ghc-pkg register at any given time.

I can try moving back to the older cabal-install versions for this build, but that may result in the build failing due to the overlong dependency solver. It seems my only other option would be to mark cabal-install builds on Travis as allowed failures.

**Comment by 23Skidoo** [comment]
> My guess is that this has to do with parallel builds, and lack of filesystem locking in ghc-pkg. I know that in Stack, we've implemented a lock to ensure that only one process triggers a ghc-pkg register at any given time.

`cabal-install` also has that since 2.0, but only in the `new-build` code. Can you try converting your Travis job to `new-build`? You can use [`make_travis_yml_2.hs`](https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs) for that.

It should be fairly easy to add file locking to old-install too, but you'll have to wait for a new `cabal-install` release.

**Comment by snoyberg** [comment]
Unfortunately that script isn't an option: it lacks OS X and Stack testing. I'll see if I can put together a tweak to use new-build, but I'm nervous about doing my testing using a new feature that users may not be using yet (especially those who are still using GHC 7.6.3). I raised this concern once before: https://github.com/haskell/bytestring/pull/73.

**Comment by hvr** [comment]
> Unfortunately that script isn't an option: it lacks OS X

I've got good news: @phadej has been working on OSX support (see https://haskell.futurice.com/ for more details)

**Comment by snoyberg** [comment]
Glad to hear that. Are you planning on also adding support for Stack-based builds?

**Comment by snoyberg** [comment]
Also @hvr: I tried to open up a PR or an issue, but I was unable to do so. I'm assuming you've blocked me on Github (which is why I'm also not receiving notifications on your comments on issues). So I'll just comment here instead.

You should probably modify that script to use `language: generic` instead of `language: c`.

**Comment by gbaz** [comment]
closing as obsolete
