### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by TomMD** [haskell/cabal#4963]
I've been really happily using `new-run` so thank you all for making that work and work well.  As a matter of fact, I entirely forgot I installed from the repo and was surprised when a new team member's entirely new cabal (i.e. from Hackage) did not permit the same workflow.  Could we get a release? The current state of the repository is quite decent and the functionality improvements over 2.0.x are notable.

**Comment by 23Skidoo** [comment]
2.2 will be out at the end of January.

**Comment by 23Skidoo** [comment]
See https://mail.haskell.org/pipermail/cabal-devel/2017-December/010410.html.
