### ISSUE TITLE
Make it possible for everyone in the haskell/cabal team to restart haskell-pushbot builds

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#4964]
As discussed in #4902, it'd be nice if everyone in the `haskell/cabal` team could manually restart `haskell-pushbot` builds. As summarised in https://github.com/haskell/cabal/pull/4902#issuecomment-348669633, the way forward is to move the [`haskell-pushbot/cabal-binaries`](https://github.com/haskell-pushbot/cabal-binaries) repo to a separate org and manually add everyone from the `haskell/cabal` team to collaborators. I am willing to manage the latter, not sure if I need any special access to @haskell-pushbot to do the former.

/cc @ezyang

**Comment by jneira** [comment]
Afaiu this talks about some ci infra we are not using anymore. And i think all the cabal dev team can restart github workflows
