### ISSUE TITLE
cabal-2.0: Distribution/Client/TargetSelector.hs:(355,7)-(356,55): Irrefutable pattern failed for pattern t' : _

### ISSUE THREAD

**Issue by code5hot** [haskell/cabal#4966]
When running cabal tests with cabal new-test I got this error message:

https://travis-ci.org/code5hot/plugins/jobs/319992952#L898

If there are changes required for the new-* prefixed commands then cabal new- should report the errors with reference to the specific files and configuration items inside them that are not appropriate.

**Comment by 23Skidoo** [comment]
Does this happen with HEAD as well?

**Comment by code5hot** [comment]
Can you outline how I might to adjust the .travis.yml file in the plugins repo so that cabal head is used?

I can spend some time trying a few things but I'm a bit new with the travis/github ecosystem

**Comment by 23Skidoo** [comment]
Just use the `cabal-install-head` package instead of `cabal-install-2.0`.

**Comment by code5hot** [comment]
Apart from an interface change such that no-test-suites = test failure it's fine in head: https://travis-ci.org/code5hot/plugins/jobs/320031531

**Comment by 23Skidoo** [comment]
Closing as fixed in HEAD.

**Comment by hvr** [comment]
@code5hot are you aware of https://github.com/haskell-hvr/multi-ghc-travis ?

**Comment by code5hot** [comment]
No, I wasn't at all aware. Thanks for the heads up.

Is head going rapidly into hvr's PPA and other places so the fix becomes
naturally available in place of cabal-2.0 soonish?
