### ISSUE TITLE
executables with a C main function

### ISSUE THREAD

**Issue by bos** [haskell/cabal#497]
(Imported from [Trac #504](http://hackage.haskell.org/trac/hackage/ticket/504), reported by @dcoutts on 2009-02-22)

We would like to be able to do:

<pre class="wiki">executable blah
  main-is: main.c
</pre>Either for pure C programs or mixed C/Haskell programs with main in the C code rather than Haskell code.

<h2 id="Workaround">Workaround</h2>
Until this is implemented one can use a main in Haskell that calls out to the C main function. For example:

<tt>main.c</tt>

<pre class="wiki">int real_main () {
  return 42;
}
</pre><tt>Main.hs</tt>

<pre class="wiki">import System.Exit
import Foreign.C
main = real_main &gt;&gt;= exitWith . ExitFailure . fromIntegral
foreign import ccall "real_main" real_main :: IO CInt
</pre><tt>c-main.cabal</tt>

<pre class="wiki">name: c-main
version: 0.0
build-type: Simple
cabal-version: &gt;= 1.2
extra-source-files: main.h
executable c-main
  main-is: Main.hs
  c-sources: main.c
  includes: main.h
  extensions: ForeignFunctionInterface
  build-depends: base
</pre><h2 id="Implementationnotes">Implementation notes</h2>
At the moment Cabal's "Simple" build system requires <tt>main-is</tt> to specify a <tt>.hs</tt> or <tt>.lhs</tt> file (though it does allow that to be generated by a pre-processor). If we lift that restriction the first thing to go wrong will be that <tt>ghc --make</tt> does not work with <tt>-no-hs-main</tt>. We will have to do the build and link steps separately (which is probably a good thing anyway). We would use <tt>ghc --make</tt> to compile all Haskell modules to <tt>.o</tt> files and then invoke <tt>ghc</tt> in batch mode passing it all the <tt>.o</tt> files (from Haskell and C modules) and <tt>-package</tt> flags. If we're using a C main then we'd do the link step with <tt>-no-hs-main</tt>.

**Comment by ttuegel** [comment]
Appears to be resolved.
