### ISSUE TITLE
"cabal init" shouldn't complain about GHC_PACKAGE_PATH being set

### ISSUE THREAD

**Issue by jsynacek** [haskell/cabal#4989]
I don't think that there is a reason to complain. Simple reproducer:

1. `mkdir /tmp/test`
2. `cd /tmp/test`
3. `stack exec -- cabal init`
> cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
> Cabal. Use the flag --package-db to specify a package database (it can be used
> multiple times).

Whereas this works well:

3. `stack exec -- bash`
4. In the new shell: `unset GHC_PACKAGE_PATH ; cabal init`
> ... cabal init works ...

#### Expected behavior
`cabal init` runs without complaining about the environment variable.

**Comment by fgaz** [comment]
But `cabal init` _does_ use the packagedb, eg. to automatically fill `build-depends` fields

**Comment by 23Skidoo** [comment]
Closing as invalid, feel free to reopen if you disagree.

**Comment by jsynacek** [comment]
Running `cabal init` in an empty directory just to create an initial cabal file doesn't care about any `build-depends`, does it? It's a minor issue, though, but having to generate the initial cabal file the roundabout way (when using `stack`) feels kind of user unfriendly.

**Comment by fgaz** [comment]
I think it does in that case too. For example it automatically puts bounds on base
