### ISSUE TITLE
new-haddock after new-build does not work

### ISSUE THREAD

**Issue by yav** [haskell/cabal#4992]
Hello,
this is what I did:

1. `cabal new-build my-package`: builds the package successfully.
2. Now I want the docs:  `cabal new-haddock my-package`.   Cabal says `Up to date`, but there is no documentation generated anywhere (or at least, `find --name '*.html'` does not return anything :-)

It looks like there is a confusion between the package being built, and the documentation for the package being built.

**Comment by dalaing** [comment]
This looks like a duplicate of #4506.

**Comment by 23Skidoo** [comment]
Closing in favour of #4506.
