### ISSUE TITLE
new-install symlink location

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#5000]
Currently new-install errors out without additional flags because it uses `symlink-bindir` as symlink location, which is unset by default. I actually am not sure what that flag was supposed to do originally (can someone clarify? Is the current behavior the intended one?).

After some digging I found that `bindir` is the only flag that is automatically set to `~/.cabal/bin` in the config file.

Now there are two courses of action:
1. set `symlink-bindir` to `~/.cabal/bin` and equivalents on config creation
2. use `bindir` instead

The downside of (1) is that existing configurations will not have that flag set and will give an error. edit: well, I just discovered `cabal user-config update`
The downside of (2) is that the `bindir` flag serves an obvious purpose for packagers, and using it for the symlink and not the executable violates that.

I think (1) is the correct one, maybe with a default to address the empty flag problem, but I'd like to hear some opinions first.

We should also document `symlink-bindir` [here](https://cabal.readthedocs.io/en/latest/installing-packages.html#installation-paths)

**Comment by 23Skidoo** [comment]
Congrats on the 5000 get, by the way.

**Comment by ezyang** [comment]
(1) seems OK to me, esp if the error message when it is unset explains how to unwedge your config.

**Comment by fgaz** [comment]
@dcoutts you seem to be the author of symlink-bindir https://github.com/haskell/cabal/commit/2eddc49b70c964bb7616996df34b1f009789f6b0

Is the first option here correct?

**Comment by angerman** [comment]
I'm in favor of (1) as well.

---
Wow, 2eddc49 is almost 10 years old!
