### ISSUE TITLE
Cabal `init project` command?

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#5005]
Should we generate a skeleton project file like we do a skeleton config file?  `cabal init project`? `cabal project-init`?

**Comment by hvr** [comment]
Here's a couple of questions OTTOMH which may or may not help figure out a design:

 - How would that skeleton look like? What arguments/flags should `cabal init --project` have?
 -  Which heuristics would it implement?
 -  Would it, like `cabal init`, ask the user a series of questions?
 -  Would it make sense to include this functionality simply as part of `cabal init` ("Do you want to create a `cabal.project` file?")?
 - Would this overlap with `cabal new-configure` which can generate a `cabal.project.local` file which has the same syntax as a `cabal.project` file?

**Comment by 23Skidoo** [comment]
Making this part of `cabal init` is IMO the right way.

**Comment by gbaz** [comment]
Considering this now, and based on more recent discussions.. I think that `cabal configure` is really the approach here.
