### ISSUE TITLE
--enable-split-sections doesn't do anything

### ISSUE THREAD

**Issue by mgsloan** [haskell/cabal#5011]
I was reading this commit https://github.com/bgamari/cabal/commit/450d6bc4d8dda8e4c56390833cec34f4b34149df , because someone contacted me to see if I was favorable about adding more direct support for split-sections in stack.

I noticed that [this line](https://github.com/bgamari/cabal/commit/450d6bc4d8dda8e4c56390833cec34f4b34149df#diff-6c1f0428958c136d788ac9fa6a9452b1R356) looks like it contains a copy paste error.  In that change, and still on master, it is

```haskell
  , [ "-split-sections" | flagBool ghcOptSplitObjs ]
  , [ "-split-objs" | flagBool ghcOptSplitObjs ]
```

and not

```haskell
  , [ "-split-sections" | flagBool ghcOptSplitSections ]
  , [ "-split-objs" | flagBool ghcOptSplitObjs ]
```

It looks like that change also intends to make split sections a default, but that also will not happen with the current code.

Also, if I'm reading the change correctly, it seems like with >= ghc 8 and no `--disable-split-sections`, specifying split-objs will cause it to always warn about mixing split-sections with split-objs even though the user did not specify split-sections.

**Comment by 23Skidoo** [comment]
Good catch, thank you! @bgamari, would you mind fixing this?

**Comment by 23Skidoo** [comment]
@bgamari Ping.

**Comment by nh2** [comment]
Another short ping about this; it would be very nice to have split-sections work as intended with whatever gets released along GHC 8.4.

**Comment by bgamari** [comment]
Oh dear, somehow I overlooked this. Sorry for the latency!

**Comment by bgamari** [comment]
> It looks like that change also intends to make split sections a default, but that also will not happen with the current code.

I didn't intend to make split-sections a default; I'm not sure it's desirable for Cabal to be in the business of defining such defaults.

> Also, if I'm reading the change correctly, it seems like with >= ghc 8 and no --disable-split-sections, specifying split-objs will cause it to always warn about mixing split-sections with split-objs even though the user did not specify split-sections.

Hmm, I'm not sure I follow. Are you just looking at `Cabal.Distribution.Simple.Configure.configure`?

**Comment by mgsloan** [comment]
@bgamari Yes, I am looking at this part of the change https://github.com/bgamari/cabal/commit/450d6bc4d8dda8e4c56390833cec34f4b34149df#diff-a6de9cdd16372d3e6c4ec16d4d1703a1R609 .  This isn't from observation, just reading the code.  If GHC >= 8.0, then `split_sections = True`.  Later on, if `split_objs` is specified and `split_sections == True`, then it warns.  That doesn't seem good.

**Comment by 23Skidoo** [comment]
> If GHC >= 8.0, then `split_sections = True`.

I don't think so. `configSplitSections cfg` [is `False` by default](https://github.com/bgamari/cabal/commit/450d6bc4d8dda8e4c56390833cec34f4b34149df#diff-0346182e8a2987e6b6d529fb7ab340c9R461), unless the user passes `--enable-split-sections`. So the compiler version check is executed only when the user has requested split sections.
