### ISSUE TITLE
Cabal should warn when unused .hs files are present in hs-source-dirs

### ISSUE THREAD

**Issue by ryantrinkle** [haskell/cabal#5030]
A problem I've often run into, both personally and when teaching new users, is forgetting to add a module to exposed-modules and/or other-modules, which results in errors in later package builds.  Generally, these errors don't provide much indication that the user needs to change their cabal file.

I believe it is generally rare for users to have Haskell files that are completely unused by their cabal file.  If this is correct, then providing a warning when .hs files present in hs-source-dirs but not mentioned in exposed-modules, etc., would help catch issues earlier.

Personally, I would also like a way to treat this warning as an error.

**Comment by gbaz** [comment]
relevant: https://github.com/haskell/cabal/issues/1746

Note that the missing home modules warning (on by default) will give a message if you `cabal build` something that uses a module not explicitly listed in the cabal file (but present in the source dir):

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Bar

Do you think this suffices for this use case?

**Comment by 23Skidoo** [comment]
Yep, with `-Wmissing-home-modules` this should be less of a problem. Also there may be legitimate reasons to have unused `.hs` files, like platform-specific code, so the check should collect `*-modules` from all `CondTree` branches.

**Comment by phadej** [comment]
@23Skidoo should we have&use `Cabal: check` label?

**Comment by ulysses4ever** [comment]
The discussion above suggests that this is essentially a dup of #1746, which was closed thanks to `-Wmissing-home-modules`. I propose we close this too.
