### ISSUE TITLE
getIPID fails when there are multiple packages

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5039]
When running `PackageTests/Backpack/Includes3/setup-external-ok.test.hs`, it fails because I have non-global `containers` in `.store`.

but that's often the case as `new-build` gets used more and more!

```
id: containers-0.5.10.2
id: containers-0.5.7.0-9028308afe4ede14e53eba8de7c4a08422b3cef30ab40c590d8611f3715008a4

stderr:
*** Exception: could not determine id of containers
```

cc @ezyang

**Comment by phadej** [comment]
Seems this is an instance of https://github.com/haskell/cabal/issues/4642
I can fix `validation.sh` by removing `.ghc.environment` files.

@ezyang Please close #5041 if it's invalid resolution.

**Comment by ezyang** [comment]
I'm OK with merging #5041, with a note saying what problem it works around, to patch over the problem. The correct way to solve the problem is to work out how to prevent environment files from infecting the test suite but I literally have no idea how to do this without doing all tests out-of-place.
