### ISSUE TITLE
Able to filter out particular tests from cabal-testsuite

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5040]
`tasty-1.0` seems to export the pattern stuff: http://hackage.haskell.org/package/tasty

**Comment by ezyang** [comment]
Yeah, OK with any sort of regex thing. Note that you can execute a specific task by running `cabal-tests path/to/test.php` and if you pass a directory it will only run the files in that directory.

**Comment by jneira** [comment]
I think test suites already can be filtered using `-p`
