### ISSUE TITLE
Bootstrap unreliable?

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#5049]
Is bootstrap unreliable? It seems to [succeed with 8.2.2 on Travis-CI](https://travis-ci.org/haskell/cabal/jobs/326237025), but for me it fails (also with 8.2.2) as follows:

```
Downloading hackage-security-0.5.2.2...
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Configuring hackage-security-0.5.2.2...
Setup: Encountered missing dependencies:
zlib >=0.5 && <0.7

Error during cabal-install bootstrap:
Configuring the hackage-security package failed.
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Configuring cabal-install-2.1.0.0...
Setup: Encountered missing dependencies:
HTTP >=4000.1.5 && <4000.4,
hackage-security >=0.5.2.2 && <0.6,
network >=2.4 && <2.7,
network-uri ==2.6.*,
resolv >=0.1.1 && <0.2,
zlib >=0.5.3 && <0.7

Error during cabal-install bootstrap:
Configuring the cabal-install package failed.
```

**Comment by mitchellwrosen** [comment]
You need `libz` installed

**Comment by tuncer** [comment]
Which `libz` do you mean? If you mean `libz` as in `-lz` and `zlib`, then I doubt those are missing because it's hard to find a Unix-like system without. I also verified that I can `cabal get` and `cabal new-build` zlib from Hackage. Also, zlib 0.6.1.2 fits into the constraint.

Have to look for more clues the next time I try to bootstrap.

**Comment by 23Skidoo** [comment]
On Ubuntu I had to install `zlib1g-dev`, because the -dev package is not installed by default.

**Comment by tuncer** [comment]
Like I said, I have the required dev files and was able to build zlib-0.6.1.2 separately:

```
$ find zlib-0.6.1.2 -name '*.so' -print -exec ldd {} \;|egrep '(HSzlib|libz)'
zlib-0.6.1.2/dist-newstyle/build/x86_64-linux/ghc-8.2.2/zlib-0.6.1.2/build/libHSzlib-0.6.1.2-inplace-ghc8.2.2.so
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f097543d000)
```

Hence, I don't think it's related to zlib. I'll try to find more info on the next bootstrap try.

**Comment by tuncer** [comment]
The source of the problem was that while my GHC installation worked in principle, it broke down at the first package during bootstrap which had to compile C code. This is because I had installed with `./configure --prefix... CC=clang CPP=clang-cpp LD=ld.lld`. Of those only `ld.lld` doesn't trigger any issue. And after editing the settings file to have the following two lines, bootstrap completed:

```
...
("C compiler command", "gcc"),
...
("Haskell CPP command","cpp"),
...
```

Would be interesting to bootstrap on macOS and FreeBSD where default `cc` is `clang`.

@23Skidoo, is this issue resolved by me going back to gcc for CC and CPP, or do you think it's a bug to be tracked? I mean, the fact that the old settings file didn't cause a failure when using cabal to `get` and `new-build` zlib would suggest there's something problematic with bootstrap and the previous GHC settings are fine.

**Comment by 23Skidoo** [comment]
If it's caused by a GHC/Clang combo, it's probably not specific to bootstrap, but rather a GHC bug. Try to come up with a small reproducible test case and then file a ticket at the GHC issue tracker.

**Comment by tuncer** [comment]
Don't know yet what bootstrap does that's different from calling cabal or ghc as usual. Something with CC/CPP must be special.

**Comment by tuncer** [comment]
Closing since it's not a cabal bug.
