### ISSUE TITLE
Cannot `cabal new-build` a project with a `generics-eot` dependency

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/cabal#5058]
[`generics-eot`](https://hackage.haskell.org/package/generics-eot) depends on [`markdown-unlit`](https://hackage.haskell.org/package/markdown-unlit), which provides a `markdown-unlit` executable.

`generics-eot` uses the `markdown-unlit` executable as the literate pre-processor with lines like

```
ghc-options: -Wall -fno-warn-name-shadowing -pgmL markdown-unlit
```

in its cabal file. When I try to `cabal new-build` a project with a `generics-eot` dependency, it fails:

```
$ cabal new-build
...
Configuring library for generics-eot-0.2.1.1..
Preprocessing library for generics-eot-0.2.1.1..
Building library for generics-eot-0.2.1.1..
ghc: could not execute: markdown-unlit
...
```

However, the old way (at least I think this is the old way) works fine:

```
$ cabal sandbox init
$ cabal install generics-eot
$ cabal build
```

Is this possibly a bug in `cabal new-build`, or am I misusing it? Thanks!

**Comment by hvr** [comment]
@mitchellwrosen it doesn't look like `generics-eot` does not declare the dependency on the executable `markdown-unlit`; please consult http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-build-tool-depends, and if something's not clear there, I'm happy to clarify!

**Comment by erikd** [comment]
Does `generics -eot` have a `build-tools` or `build-tools-depends` stanza?

**Comment by erikd** [comment]
@hvr I was chasing this myself and found that https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-build-tools has a link "see below ...." which is broken.  It links to https://www.haskell.org/cabal/users-guide/buildtoolsbc which is 404.

**Comment by hvr** [comment]
@erikd interesting, the link does seem to work on http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-build-tool-depends, doesn't it?

**Comment by erikd** [comment]
@hvr Yes it does!

**Comment by mitchellwrosen** [comment]
@hvr Thanks, that did it. Unfortunately `generics-eot` is built with `hpack` which does not yet recognize `build-tool-depends`...!

**Comment by hvr** [comment]
@mitchellwrosen btw, https://matrix.hackage.haskell.org/package/generics-eot ;-)

**Comment by angerman** [comment]
@mitchellwrosen, have you checked if this is an open issue with `hpack`? Not that this goes unnoticed.

**Comment by mitchellwrosen** [comment]
@angerman it's already an open issue on `hpack`, yeah. (On mobile, can't find the link)
