### ISSUE TITLE
`cabal new-run` doesn't work

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/cabal#5074]
I feel very silly for filing this ticket, because I looked through some open issues and found other people using `cabal new-run` just fine. But anyway, `cabal new-run` isn't working in [this sample repo](https://github.com/mitchellwrosen/cabal-new-run-doesnt-work). It builds the executable, but doesn't run it. What might I be doing wrong?

**Comment by hvr** [comment]
I suspect you're using a non-bleeding edge `cabal` version? Afaik, `cabal new-run` wasn't fully functional yet in cabal 2.0 exhibiting the very behaviour you're seeing; and most people dogfooding `new-build` tend to use cabal 2.1 (i.e. cabal HEAD) -- where I can confirm that `cabal new-run` works as expected on your repro case.

PS: It's fine to file issues here, but I'd also like to point out that you can come to the `#hackage` IRC channel if you like to discuss things in a more interactive medium

**Comment by mitchellwrosen** [comment]
Makes sense, thanks! I was using the latest `cabal-install` from Hackage but I'll use HEAD from now on.
