### ISSUE TITLE
Cabal release for GHC 8.4

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#5075]
GHC 8.4 is quickly approaching. What is the status here?

**Comment by phadej** [comment]
I need to fix a bug in https://github.com/haskell/cabal/issues/5055, will do that tomorrow.

**Comment by 23Skidoo** [comment]
I'll create a branch once that is merged.

**Comment by angerman** [comment]
We need #4874 for hadrian (reloc).

**Comment by angerman** [comment]
There should be no release before #5053 is merged.

**Comment by phadej** [comment]
- #5053 is `cabal-install` change, so it's not a blocker for `Cabal` branch.
- #4874 has `Cabal` changes, so we have to get that in too.

**Comment by phadej** [comment]
@bgamari is https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory correct, `time` will stay at `1.8.0.2`. @hvr when `parsec-3.1.12` will be released? (Do we want to have >=3.1.12 lower bound?)

**Comment by Ericson2314** [comment]
Hoping to land https://github.com/haskell/cabal/pull/4383, so we will only have 2.0 allowing ambiguous libraries

**Comment by phadej** [comment]
AFAICS everything is in, can we cut the 2.2 branch?

**Comment by angerman** [comment]
#4874

**Comment by phadej** [comment]
@angerman hopefully it will be merged by the time @23Skidoo notices my message! :)

**Comment by angerman** [comment]
Yea, I'm running some final hadrian tests, and will fix #5111 for inclusion (which unbreaks #4892, which broken when trying to get the flags to hide... for some reason my cross validation ran against some stale code :( -- it's now only blocked by the use of LambdaCase, I believe; will fix.)

**Comment by Ericson2314** [comment]
Ooo I hope I make it. https://github.com/haskell/cabal/pull/5100 also should be finished as we've got spurious warnings right now without it.

**Comment by phadej** [comment]
No please, no #5100. Or any other non-trivial patches.

- Fixing bugs :+1:
- Writing docs :+1:
- Improving error messages: :+1:
- Breaking API :-1:

The branch had to be cut for stabilization already 20 days ago (Jan 15th). The feature creep was enormous, let's not make it any worse.



ping @23Skidoo

**Comment by 23Skidoo** [comment]
+1 on not including #5100 at this stage. I'll cut the branch later today or tomorrow, the remaining fixes will be cherry-picked.

**Comment by Ericson2314** [comment]
> The branch had to be cut for stabilization already 20 days ago

A cabal branch or GHC branch?

**Comment by 23Skidoo** [comment]
Cabal branch.

**Comment by Ericson2314** [comment]
Understood now, talking to @phadej on IRC. The plan was for Jan 15, but it has already slipped. Never mind me then.

**Comment by 23Skidoo** [comment]
Yep, there was an announcement on `cabal-devel`: https://mail.haskell.org/pipermail/cabal-devel/2017-December/010410.html.

**Comment by angerman** [comment]
#4874 is now green as well (after we gave travis a chance to turn green again ;-))

**Comment by 23Skidoo** [comment]
Created the 2.2 branch.

**Comment by bgamari** [comment]
As documented in [#14862](https://ghc.haskell.org/trac/ghc/ticket/14862), the HEAD of Cabal 2.2 breaks the `ghc-8.4`. @angerman has put quite a bit of time into trying to identify the culprit but there is currently no solution. As the release is supposed to go out tomorrow, I think we need to start looking for alternatives.

The last known working commit is d2cf3f13da. I recommend that this commit be designated 2.2.0.0 so we can release GHC in the same state that the release candidate was cut in. It's hard to tell precisely what fixes we will miss out on by doing this, but a quick glance suggests that it's nothing particularly awful.

**Comment by 23Skidoo** [comment]
If we're sure that the `basedir` patch is the source of the problems, I can just revert it.

**Comment by hvr** [comment]
I'd like to look into the windows issue; this must be something simple... it's really just about a backslash getting eaten somewhere

**Comment by quasicomputational** [comment]
Cabal 2.2 has been released, the linked bugs have been resolved, and there aren't howls of pain about brokenness, so I guess this issue's served its purpose.
