### ISSUE TITLE
fix pretty-printing of `executable.scope`

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5083]
It always printed as `scope: unknown`.

This is not biggie but easy to fix.

There is no label for pretty-printer, so I tag it as parser issue :P

**Comment by 23Skidoo** [comment]
Feel free to add a label, it'll be handy to track `cabal format` progress.

**Comment by phadej** [comment]
There's now `Cabal: pretty` label (not to clash with `Cabal: file format`)
