### ISSUE TITLE
Maintain central haddock module index.

### ISSUE THREAD

**Issue by bos** [haskell/cabal#509]
(Imported from [Trac #516](http://hackage.haskell.org/trac/hackage/ticket/516), reported by @dcoutts on 2009-03-03)

The ghc api documentation includes a central index of [all the modules in the core libraries](http://haskell.org/ghc/docs/latest/html/libraries/). Some people would like the same for all the modules provided by all the packages they have installed.

See #206 for some of the previous discussion on this topic.

The questions to resolve are where the index should be kept by default and how it should be configured (eg switched off).

For example for a per-user install an index could live in <tt>$HOME/.cabal/share/doc/index.html</tt> but the equivalent is not appropriate for other prefixes like <tt>/usr/local</tt>.

For global packages shipped by a distro the problem is much worse. We do not really want to have to have distro packages re-generating an html index every time they add and remove a package. Perhaps we should be looking at alternative solutions like using [devhelp](http://live.gnome.org/devhelp) which can give easy access to installed documentation without maintaining a central index/catalog.

Similar issues apply to a hoogle index.

**Comment by Arkemyr** [comment]
Hi,

I would like to have a master index with new style Cabal packages.
Is that possible?

I am quite new to Cabal and I did not find any mention about this in the documentation.
There is however the `where_is_my_stuff.txt` that says master index should be in `~/Library/Haskell/doc/` after first `cabal install`.
However I do not want to use the old style commands _ever again_.

Thanks for any hints :)

**Comment by gbaz** [comment]
closing as this is obsoleted imho by v2-build features/issues
