### ISSUE TITLE
Add check so cabal-version should be even

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5094]
And tweak `Cabal` lib to "round up" (current) version for development.

```
setup: This package description follows version 2.2 of the Cabal specification. This tool only supports up to version 2.1.0.0.
```

is annoying.

*EDIT* I'm not even sure that have to be based on `Paths_Cabal`. If we keep changing cabal spec, we will remember to bump hard coded value.

**Comment by hvr** [comment]
I've been wanting something like this!

**Comment by phadej** [comment]
And the follow-up: verify that `cabalVersion` is something known e.g.
```
(>=1 && <1.25) || ==2.0 || ==2.2
```

(Hackage is probably full of weird values).

**Comment by phadej** [comment]
The parser is stricter now.
