### ISSUE TITLE
new-update requires .cabal or cabal.project

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5096]
```
% cabal new-update            
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.
```

is this by design, or does `new-update` tries to read project info and fails (using the same codepath as `new-build`?)

**Comment by fgaz** [comment]
We can quickly fix this by using CmdInstall:establishDummyProjectBaseContext instead of establishProjectBaseContext (which requires a cabal project)

**Comment by phadej** [comment]
@fgaz will `new-update` read `cabal.project` if it exists then? That's a requirement (otherwise `head.hackage` overlay won't work)

**Comment by fgaz** [comment]
Hmm it probably won't work.

Maybe (even more dirty):
try to do establishProjectBaseConfig and if it fails fall back to establishDummyProjectBaseContext

**Comment by fgaz** [comment]
_or_ we could make establishProjectBaseContext _not_ fail and instead return a partial ProjectContext if there isn't a project

**Comment by fgaz** [comment]
(by partial i mean a new datatype, not undefined-partial)

**Comment by angerman** [comment]
Im fine with either approach. I do prefer the second (don’t fail, assume empty project(?), and print warning(!)) approach...

...as long as overlays keep working ;-)
