### ISSUE TITLE
new-repl on test-suite does not bring Main module into scope

### ISSUE THREAD

**Issue by sol** [haskell/cabal#5103]
Steps to  reproduce:

```
$ git clone -b cabal-new-build https://github.com/hspec/hspec-example
$ cd hspec-example/
$ cabal new-repl spec
*Data.String.StripSpec> 
```

This will result in `Data.String.StripSpec` being in scope.

My naive assumption was that `Main` should be in scope.  Is there a rational for the current behavior?

**Comment by hvr** [comment]
I *think* it's mostly an oversight. In order to to this, one would have merely to include the cabal property `main-is:` value (which unlike `other-modules` is not a module name but rather a filepath) onto the ghci command line... (and hoping there aren't any complications)

**Comment by sol** [comment]
@hvr As far as I can tell, the `Main` module is loaded.  I can bring it into scope with `:module *Main`.  Even accessing it qualified is possible.

**Comment by hvr** [comment]
oh indeed, sorry; I was looking at the wrong `new-repl` invocation which brought a different component into scope for me; So yes, in this case it may be just a matter of changing the order of how the arguments are passed to GHCi... making sure the `test/Spec.hs` argument isn't last, but rather the first one.

**Comment by dwijnand** [comment]
It's a simple solution, but you can work around this by making the main module a thin shim over the real main module:

```cabal 
  hs-source-dirs:      test
  main-is:             Main.hs
  other-modules:
      Spec
      FooSpec
```

```haskell
-- test/Main.hs
module Main (main) where

import qualified Spec

main :: IO ()
main = Spec.main
```

```haskell
-- test/Spec.hs
module Spec (main) where

import FooSpec

main :: IO ()
main = ...
```

**Comment by dwijnand** [comment]
I've submitted the 1-line change in #6311, if anyone would like to review it.
