### ISSUE TITLE
Treating a local dependency as "external" with new-build

### ISSUE THREAD

**Issue by sol** [haskell/cabal#5110]
Hey, first things first, thank you guys for working on `cabal new-build`!  I think this has serious potential and I would be excited to eventually ditch [`sol/tinc`](https://github.com/sol/tinc) in favor of it!

One of my major roadblocks is, that I want to depend on local dependencies and get them cached.

Example: We have packages `foo` (under `~/projects/foo`) and `bar` (under `~/projects/bar`), where `foo` depends on `bar`.

Is it right now somehow possible to use `~/projects/bar` when hacking on `foo` so that

- `bar` gets cached under `~/.cabal/store` (essentially treating it as "external dependency")
- ensures that `~/projects/bar` is used (that is: rather fail, then use `bar` form Hackage, similar to what `cabal sandbox add-source` gives you)

?

Any solution would work for me even if it's ugly (editing config files, passing command line flags, or a combination of it).

Any pointers are very much appreciated!

**Comment by gbaz** [comment]
So a naive question from me here -- what's wrong with just having a `cabal.project` in `~/projects` proper? This doesn't give you exactly your requirements, but it seems like it covers what I understand the use-case to be...

**Comment by sol** [comment]
I don't think it does, specifically, it will not allow me to decide what version of `bar` to use on a per project basis.  As I understand it this will give something like "one big sandbox".

**Comment by gbaz** [comment]
That's correct. For the moment a potential solution would be to use a local-repo for an overlay as per https://github.com/haskell/cabal/issues/5060

But I think that wouldn't pass requirement 2.

**Comment by hvr** [comment]
it can pass requirement 2, if you combine it with `constraints` to pin the particular version from your local repo.

**Comment by sol** [comment]
@hvr thanks a lot! I'll give this a try!

**Comment by sol** [comment]
@gbaz thanks for the pointer!
