### ISSUE TITLE
Add support for `SPDX-License-Identifer` alias

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#5112]
The SPDX 2.1 specification promotes the use of a common syntax for declaring SPDX short identifiers, see [SPDX 2.1 - Appendix V](https://spdx.org/spdx-specification-21-web-version#h.twlc0ztnng3b) which tooling agnostic to language-specific syntaxes/grammars can easily scan for:

> The SPDX License Identifier syntax may consist of  a single license (represented by a short identifier from the SPDX license list) or a compound set of licenses (represented by joining together multiple licenses using the license expression syntax).
>
> The tag should appear on its own line in the source file, generally as part of a comment.
>
> ```
> SPDX-License-Identifier: <SPDX License Expression>
> ```

Right now, we'd have to duplicate the license field as a comment to achieve this:

```
license: (GPL-2.0+ WITH Bison-exception-2.2)
-- SPDX-License-Identifier: (GPL-2.0+ WITH Bison-exception-2.2)
```

What I'm suggesting is that from `cabal-version:2.2` on, we allow

```
SPDX-License-Identifier: (GPL-2.0+ WITH Bison-exception-2.2)
```

as a synonym for the `license:` field.

/cc @phadej

**Comment by phadej** [comment]
It's not simple technical change. I'm :-1: for 2.2. Parser framework doesn't support alternatives (it's literally not `Alternative`).

The `license-file` + `license-files` is a hack at the moment

**Comment by hvr** [comment]
Alright, punting to 3.0 then ;-)

**Comment by gbaz** [comment]
I believe we moved fully to spdx licences and this can be closed?
