### ISSUE TITLE
Parse error on "mixins" field

### ISSUE THREAD

**Issue by pikajude** [haskell/cabal#5150]
The `mixins` field doesn't parse if the provided renaming clause has whitespace after the opening parenthesis.

```
mixins: example-mixin ( Mixin1 as Foo.Mixin1
                      , Mixin2 as Foo.Mixin2
                      )
```

```
$ readGenericPackageDescription normal "test.txt"
Warning: test.txt:6:26:
unexpected " "
expecting ")"

example-mixin ( Mixin1 as Foo.Mixin1
, Mixin2 as Foo.Mixin2
)
*** Exception: dieVerbatim: user error (<interactive>: Failed parsing "test.txt".
```

If I delete the space in `( Mixin1` it parses fine. I feel like the given example should parse correctly since it would make vertically formatted long renaming clauses nicer-looking.

If this isn't intended behavior, I can PR the patch I've made locally.

**Comment by phadej** [comment]
Can you test what cabal-install-2.0 does, (e.g. `cabal check`).

**Comment by pikajude** [comment]
```
$ cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library
cabal: ./test.cabal:6: Parse of field 'mixins' failed.
```

**Comment by phadej** [comment]
As old cabal-install fails too, new lenient parser have to be guarded with `cabal-version` check. We have to be bug compatible :/

**Comment by pikajude** [comment]
Which version of Cabal is supposed to be able to parse my example? If I specify `cabal-version: 2.2` at the top of the file, the parse error still happens, and `2.3` isn't a supported version.

**Comment by ezyang** [comment]
Sorry, what @phadej was saying that it's not enough to just fix the parser, we also have to make sure the fix only applies when you have a sufficiently new `cabal-version` (probably 2.4 since we've missed this merge Window.)

@phadej, is this really necessary? It's certainly not a BC-breaking change, which is what I thought `cabal-version` was for.

**Comment by phadej** [comment]
@ezyang It's breaking change. If there will be a `.cabal` file requiring relaxed parser and `cabal-version: 2.0`, it will fail as example above shows.

Similar "small" thing is e.g #4611  are #5092 #5093 #5138

**Comment by fgaz** [comment]
Was this fixed in https://github.com/haskell/cabal/pull/5293 ?
