### ISSUE TITLE
Implement upgrade feature

### ISSUE THREAD

**Issue by XVilka** [haskell/cabal#5151]
Many years passed and people still struggle how to update all packages, like e.g. `opam upgrade` can.
There is even a workaround like:
```bash
cabal list --simple-output --installed | awk '{print $1}' | uniq | xargs -I {} cabal install {} --reinstall
```
(taken from https://stackoverflow.com/questions/6905163/whats-the-best-workaround-for-not-having-cabal-upgrade/6905267#6905267 )

Would be nice to finally have it. (Yes, I know about Stack, but it's still far from being widely used).

**Comment by hvr** [comment]
This may have made sense in the old-build paradigm, but it doesn't apply anymore in the nix-style local builds paradigm, where the package db is merely a binary cache. It's not a stateful pkd db you can "upgrade". Unless I misunderstand your suggestion.

**Comment by 23Skidoo** [comment]
Check out [`cabal outdated`](http://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=outdated#listing-outdated-dependency-version-bounds) and #4831.

**Comment by gbaz** [comment]
closing as obsolete
