### ISSUE TITLE
Cabal logging and reporting should be able to display revision information

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#5156]
As suggested somewhere around: https://github.com/haskell/ecosystem-proposals/pull/6#issuecomment-367040922

**Comment by hvr** [comment]
I briefly looked at the codepaths involved, and this should be doable with a little bit of refactoring to collect the extra information bit and funnel it through to places where it can be displayed.

**Comment by 23Skidoo** [comment]
See also #1929.

**Comment by hvr** [comment]
Duplicate of #1929

**Comment by hvr** [comment]
(I always wanted to try out that feature... C:-) )

**Comment by gbaz** [comment]
closing this in favor of dup ticket
