### ISSUE TITLE
cabal sdist with directory listed in extra-source-files silently fails

### ISSUE THREAD

**Issue by alunduil** [haskell/cabal#5195]
When a directory gets added to `extra-source-files`, `cabal sdist` silently fails.  Using strace revealed the error was due to a directory in the `extra-source-files` directive, but cabal itself didn't indicate any issue other than an exit code of 1.

It would be nice if mistakes like this could have an error message indicating roughly where and what to look for to get things working again.

Let me know if any other information is useful and I'll be sure to add it.

```
% cabal --version                                                                                                                                                             (git)-[develop] 
cabal-install version 2.0.0.0                                                                                                                                                                                                    
compiled using version 2.0.0.2 of the Cabal library
```

If anyone is willing to point me in the right direction, I'm more than happy to put forth an effort to work this issue myself as well.

**Comment by 23Skidoo** [comment]
> If anyone is willing to point me in the right direction, I'm more than happy to put forth an effort to work this issue myself as well.

Awesome! The relevant part of Cabal is https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/SrcDist.hs#L145. If you need further pointers, just ask.

**Comment by alunduil** [comment]
@23Skidoo , sorry for the delay on this.  I've finally got a little freedom to work on this.  Looks like the line you linked has moved but that file seems mostly straight-forward.

Is it a known discrepancy that in the cabal file there is an `extra-source-files` but an `extraDocFiles` in the code?  Let me know if I'm just reading this incorrectly as well.  Thanks!

**Comment by 23Skidoo** [comment]
`extra-doc-files` are something different: http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-extra-doc-files

**Comment by alunduil** [comment]
Alright, I'll have to dive into it one more time.  Thanks for the sanity check!
