### ISSUE TITLE
`cabal new-haddock --haddock-for-hackage` claims to have created non-existent files

### ISSUE THREAD

**Issue by sjakobi** [haskell/cabal#5210]
```
$ cabal get bytestring
$ cd bytestring-0.10.8.2
$ cabal new-configure -w ghc-8.4.1
$ cabal new-haddock --haddock-for-hackage
…
Documentation created:
/home/simon/src/bytestring/dist-newstyle/build/x86_64-linux/ghc-8.4.1/bytestring-0.10.9.0/doc/html/bytestring-0.10.9.0-docs/index.html,
/home/simon/src/bytestring/dist-newstyle/build/x86_64-linux/ghc-8.4.1/bytestring-0.10.9.0/doc/html/bytestring-0.10.9.0-docs/bytestring.txt
Documentation tarball created:
/home/simon/src/bytestring/dist-newstyle/bytestring-0.10.9.0-docs.tar.gz
```

But neither the `index.html` and `bytestring.txt` files nor the tarball exist.

**Comment by hvr** [comment]
see also https://github.com/haskell/cabal/issues/4412#issuecomment-301762546

**Comment by 23Skidoo** [comment]
This is probably easy to fix, IIUC those files are not supposed to be created in `--for-hackage` mode in the first place.

**Comment by andreasabel** [comment]
Me too.
`cabal haddock --haddock-for-hackage` prints it generated `long/path/index.html`, but this file does not exist.
How can this happen?  (Meaning: the code printing the report on what is being created should not make up filenames, but get a result vector which it prints out (selectively).)
