### ISSUE TITLE
question: using "cabal copy" and "cabal sdist" with "cabal new-build"

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/cabal#5217]
I am using `cabal new-build` in my CI script. I build from the sdist using `cabal sdist` and also test installs using `cabal copy`.  This all works fine with the old cabal builds. However, when using new-build, cabal-sdist throws some warnings like this:

```
cabal sdist
Warning: Cannot run preprocessors. Run 'configure' command first.
Building source dist for packcheck-0.2.0...
Source tarball created: dist/packcheck-0.2.0.tar.gz
```

The `cabal copy` command just fails:

```
cabal copy
Run the 'configure' command first
```

Am I supposed to run the `cabal configure` command as well even when using `new-build`? I tried `cabal new-configure` but that does not help.

**Comment by fgaz** [comment]
Neither `new-sdist` nor `new-copy` exist yet. You'll have to rebuild everything with old build or skip the sdist/copy tests for now

**Comment by harendra-kumar** [comment]
Thanks for the clarification!
