### ISSUE TITLE
`cabal new-build` treats haddock failures fatally

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#5232]
originally reported at https://github.com/haskell-infra/hackage-trustees/issues/146

`cabal new-build` currently fails when `haddock` fails (e.g. due to `documentation: True` set globally; note that Haddock currently fails for packages w/o any local modules);
instead, `cabal new-build` ought to merely record/log/warn about them, but otherwise carry on

**Comment by cartazio** [comment]
this seems like a high priority bug :) 

where in the cabal code base is this issue? i can poke around but if theres some know how, i'd like to help get this into a point fix post haste!

**Comment by alexbiehl** [comment]
Carter, look here https://github.com/haskell/cabal/blob/457ebb8aff13e86e8928f301132f14ccaa23c28f/cabal-install/Distribution/Client/ProjectBuilding.hs#L941-L945

`annotateFailureNoLog` catches the error from cabal and rethrows it. You probably don't want that behaviour in case of haddock.

**Comment by cartazio** [comment]
@alexbiehl ok, that helps!
better question, should we fix just that, or also not generate haddocks when theres no modules? (later seems more complicated perhaps but more correct?)

**Comment by alexbiehl** [comment]
We should do both I think:

1) Cabal shouldn't treat haddock errors as fatal errors and 2) Cabal should avoid invoking haddock if there are no inputs.

**Comment by cartazio** [comment]
@alexbiehl is your haddock work on master a fix to for master, or unrealted clean up?

should i do this patch for 2.2 or master?

**Comment by cartazio** [comment]
i'm trying to test build cabal and i'm getting this fun error 

Resolving dependencies...
Configuring cabal-install-2.2.0.0...
Building cabal-install-2.2.0.0...
Installed cabal-install-2.2.0.0
Updating documentation index
/Users/carter/.cabal/share/doc/x86_64-osx-ghc-8.2.2/index.html
<command line>: cannot satisfy -package-id cabal-testsuite-2.2.0.0-inplace
    (use -v for more information)

**Comment by cartazio** [comment]
this hacky first cut of a patch seems to work now that i got the build working :)

**Comment by cartazio** [comment]
the current patch just demotes haddock failures unconditionally to an adhoc warning, the right approach might be to add support for "warnings" along with full build failures.  

additionally: it'd probably be good to have / retain the option to treat haddock failures as errors either per package build or globally?

additionally additionally: cabaly shouldn't even invoke haddock when theres no docs to build probably?!

**Comment by alexbiehl** [comment]
Yeah, the behaviour is yet to be specified. 

For the other issue take a look here: 
https://github.com/haskell/cabal/blob/335fa8d82520bad1a6980fd55230e65889c99860/Cabal/Distribution/Simple/Haddock.hs#L111

You might want to not invoke haddock if argTargets is empty.

**Comment by cartazio** [comment]
If you look I wrote a new function that soesnst rethrow

**Comment by cartazio** [comment]
@alexbiehl thx! i'll have a look at that after i catchup with a few other things this week (my janky patch for now has me unstuck on a huge backlog at the moment :) )

Is there a  mechanism in cabal at the moment for easy logging / posting of non-fatal warnings/errors to logs/user stdout/stderr? what are the current cabal-install standards for these?

**Comment by cartazio** [comment]
ok, i pushed some partially done changes, 
I added to the haddock exports a "compute input files " function,
though i'm not sure how i get the arguments i need for it in the `ProjectBuilding.hs` file

```
haddockInputFilesFromLibrary :: Verbosity
            -> LocalBuildInfo
            -> ComponentLocalBuildInfo
            -> Library
            -> IO [FilePath]
haddockInputFilesFromLibrary  verbosity lbi clbi lib =
  map snd `fmap` getLibSourceFiles verbosity lbi lib clbi


```

**Comment by cartazio** [comment]
I'm a little lost about where i can get the right LocalBuildInfo / Library / ComponentLocalBuildInfo args from  :(

**Comment by cartazio** [comment]
Thanks!
Also your patch makes it look way cleaner than what I was trying to do.
Many thanks.
