### ISSUE TITLE
cabal new-run silliness

### ISSUE THREAD

**Issue by yav** [haskell/cabal#5243]
I have a cabal package that defines a library and executable.  Not surprisingly, they have the same name.  Here is what happens when I try to use `cabal new-run` with it:

    $ cabal new-run cryptol
    cabal: Ambiguous target 'cryptol'. It could be:
    exe:cryptol (component)
    lib:cryptol (component)

It doesn't really make sense to run a library (and Cabal knows that, as it reports an error if you try to do so), so `new-run` should only consider the executable targets and filter out the rest.

**Comment by fgaz** [comment]
Duplicate of #4676
