### ISSUE TITLE
I have this problem when I try to install tidal cycles. How to solve this problem in manjaro linux? 

### ISSUE THREAD

**Issue by MoiRouhs** [haskell/cabal#5248]
Resolving dependencies...
Notice: installing into a sandbox located at /home/carlos/.cabal-sandbox
Configuring mersenne-random-pure64-0.2.2.0...
Configuring blaze-builder-0.4.1.0...
Building blaze-builder-0.4.1.0...
Building mersenne-random-pure64-0.2.2.0...
Failed to install mersenne-random-pure64-0.2.2.0
Build log ( /home/carlos/.cabal-sandbox/logs/ghc-8.2.2/mersenne-random-pure64-0.2.2.0-60uKuwEkCr4HbgBy9XHGZP.log ):
cabal: Entering directory '/tmp/cabal-tmp-6483/mersenne-random-pure64-0.2.2.0'
Configuring mersenne-random-pure64-0.2.2.0...
Preprocessing library for mersenne-random-pure64-0.2.2.0..
Building library for mersenne-random-pure64-0.2.2.0..
[1 of 4] Compiling System.Random.Mersenne.Pure64.Base ( dist/dist-sandbox-94bb7a0e/build/System/Random/Mersenne/Pure64/Base.hs, dist/dist-sandbox-94bb7a0e/build/System/Random/Mersenne/Pure64/Base.o )
[2 of 4] Compiling System.Random.Mersenne.Pure64.Internal ( System/Random/Mersenne/Pure64/Internal.hs, dist/dist-sandbox-94bb7a0e/build/System/Random/Mersenne/Pure64/Internal.o )
[3 of 4] Compiling System.Random.Mersenne.Pure64.MTBlock ( System/Random/Mersenne/Pure64/MTBlock.hs, dist/dist-sandbox-94bb7a0e/build/System/Random/Mersenne/Pure64/MTBlock.o )
[4 of 4] Compiling System.Random.Mersenne.Pure64 ( System/Random/Mersenne/Pure64.hs, dist/dist-sandbox-94bb7a0e/build/System/Random/Mersenne/Pure64.o )

System/Random/Mersenne/Pure64.hs:48:1: error:
    Could not find module ‘System.Random’
    There are files missing in the ‘random-1.1’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
48 | import System.Random
   | ^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-6483/mersenne-random-pure64-0.2.2.0'
Configuring streaming-commons-0.2.0.0...
Building streaming-commons-0.2.0.0...
Failed to install blaze-builder-0.4.1.0
Build log ( /home/carlos/.cabal-sandbox/logs/ghc-8.2.2/blaze-builder-0.4.1.0-76A6rNBvwvR8MTgrMARis4.log ):
cabal: Entering directory '/tmp/cabal-tmp-6482/blaze-builder-0.4.1.0'
Configuring blaze-builder-0.4.1.0...
Preprocessing library for blaze-builder-0.4.1.0..
Building library for blaze-builder-0.4.1.0..
[ 1 of 11] Compiling Blaze.ByteString.Builder.Internal.Write ( Blaze/ByteString/Builder/Internal/Write.hs, dist/dist-sandbox-94bb7a0e/build/Blaze/ByteString/Builder/Internal/Write.o )
[ 2 of 11] Compiling Blaze.ByteString.Builder.Compat.Write ( Blaze/ByteString/Builder/Compat/Write.hs, dist/dist-sandbox-94bb7a0e/build/Blaze/ByteString/Builder/Compat/Write.o )
[ 3 of 11] Compiling Blaze.ByteString.Builder.Int ( Blaze/ByteString/Builder/Int.hs, dist/dist-sandbox-94bb7a0e/build/Blaze/ByteString/Builder/Int.o )
[ 4 of 11] Compiling Blaze.ByteString.Builder.Html.Word ( Blaze/ByteString/Builder/Html/Word.hs, dist/dist-sandbox-94bb7a0e/build/Blaze/ByteString/Builder/Html/Word.o )
[ 5 of 11] Compiling Blaze.ByteString.Builder.Char8 ( Blaze/ByteString/Builder/Char8.hs, dist/dist-sandbox-94bb7a0e/build/Blaze/ByteString/Builder/Char8.o )

Blaze/ByteString/Builder/Char8.hs:37:1: error:
    Could not find module ‘Data.Text’
    There are files missing in the ‘text-1.2.3.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
37 | import qualified Data.Text      as TS
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Blaze/ByteString/Builder/Char8.hs:38:1: error:
    Could not find module ‘Data.Text.Lazy’
    There are files missing in the ‘text-1.2.3.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
38 | import qualified Data.Text.Lazy as TL
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-6482/blaze-builder-0.4.1.0'
Failed to install streaming-commons-0.2.0.0
Build log ( /home/carlos/.cabal-sandbox/logs/ghc-8.2.2/streaming-commons-0.2.0.0-8aHSty4okIT2XDZrEAxkjm.log ):
cabal: Entering directory '/tmp/cabal-tmp-6483/streaming-commons-0.2.0.0'
Configuring streaming-commons-0.2.0.0...
Preprocessing library for streaming-commons-0.2.0.0..
Building library for streaming-commons-0.2.0.0..
[ 1 of 16] Compiling Data.Streaming.ByteString.Builder.Buffer ( Data/Streaming/ByteString/Builder/Buffer.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/ByteString/Builder/Buffer.o )
[ 2 of 16] Compiling Data.Streaming.ByteString.Builder ( Data/Streaming/ByteString/Builder.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/ByteString/Builder.o )
[ 3 of 16] Compiling Data.Streaming.FileRead ( Data/Streaming/FileRead.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/FileRead.o )
[ 4 of 16] Compiling Data.Streaming.Filesystem ( Data/Streaming/Filesystem.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/Filesystem.o )
[ 5 of 16] Compiling Data.Streaming.Network.Internal ( Data/Streaming/Network/Internal.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/Network/Internal.o )
[ 6 of 16] Compiling Data.Streaming.Network ( Data/Streaming/Network.hs, dist/dist-sandbox-94bb7a0e/build/Data/Streaming/Network.o )

Data/Streaming/Network.hs:112:1: error:
    Could not find module ‘System.Random’
    There are files missing in the ‘random-1.1’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
    |
112 | import System.Random (randomRIO)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-6483/streaming-commons-0.2.0.0'
cabal: Error: some packages failed to install:
blaze-builder-0.4.1.0-76A6rNBvwvR8MTgrMARis4 failed during the building phase.
The exception was:
ExitFailure 1
hosc-0.16-GysdlLQGnw31KcgtiCitD3 depends on hosc-0.16 which failed to install.
mersenne-random-pure64-0.2.2.0-60uKuwEkCr4HbgBy9XHGZP failed during the
building phase. The exception was:
ExitFailure 1
streaming-commons-0.2.0.0-8aHSty4okIT2XDZrEAxkjm failed during the building
phase. The exception was:
ExitFailure 1
tidal-0.9.6-3dsxGB82j4b1Su3eYktnIw depends on tidal-0.9.6 which failed to
install.
websockets-0.12.4.0-5QdjjHkNyHC6TutsheZEsb depends on websockets-0.12.4.0
which failed to install.

**Comment by hvr** [comment]
@MoiRouhs ...do you happen to use Arch Linux?

**Comment by MoiRouhs** [comment]
Yes

**Comment by gbaz** [comment]
Arch packages haskell in a very weird way, and needs special setup for developing. c.f. https://wiki.archlinux.org/index.php/haskell

**Comment by MoiRouhs** [comment]
I install tidal cycle but no linking whit the librery thacks you
