### ISSUE TITLE
Linker error on Windows with chocolate

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#5254]
Here is the log exhibiting the linker failure with cabal 2.2.0.0: https://ci.appveyor.com/project/Mikolaj/allure/build/1.0.148

```
Linking dist\build\Allure\Allure.exe ...
Warning: resolving _GetModuleFileNameW by linking to _GetModuleFileNameW@12
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
    `_GetModuleFileNameW' referenced in section `.text' of dist\build\Allure\Allure-tmp\Paths_Allure.o: defined in discarded section `.text' of C:/ProgramData/chocolatey/lib/ghc/tools/ghc-8.2.2/mingw/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/lib/../lib/libkernel32.a(dghgds00535.o)
collect2.exe: error: ld returned 1 exit status
```

And the same project succeeds after downgrading cabal to 2.0.0.1: https://ci.appveyor.com/project/Mikolaj/allure/build/1.0.149

I both cases, initial 64bit build succeed fine, only the subsequent 32bit build fails (with the new cabal version).

I tried `--enable-stdcall-fixup`, which made the warnings disappear, but the error remain. Then I tried `--disable-stdcall-fixup` and I got a different error (as before, only in 32bit build, https://ci.appveyor.com/project/Mikolaj/allure/build/1.0.150):

```
Linking dist\build\Allure\Allure.exe ...
dist\build\Allure\Allure-tmp\Paths_Allure.o:fake:(.text+0xe65): undefined reference to `GetModuleFileNameW'
collect2.exe: error: ld returned 1 exit status
```

When comparing the logs, nothing strikes me, except that only the 64bit compilation (the one that doesn't fail) shows the warning (but only with the old cabal):

```
dist\build\Allure\autogen\Paths_Allure.hs:73:1: warning: [-Wunsupported-calling-conventions]
    * the 'stdcall' calling convention is unsupported on this platform,
      treating as ccall
    * When checking declaration:
        foreign import stdcall unsafe "windows.h GetModuleFileNameW" c_GetModuleFileName
          :: Ptr () -> CWString -> Int32 -> IO Int32
   |
73 | foreign import stdcall unsafe "windows.h GetModuleFileNameW"
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

(So it seems as if old cabal had the stdcall problem only on 64bit, but the fixes changed also how 32bit builds work and broke them.)

Also, the log shows some new chocolatey Windows shims are present in the new chocolatey cabal package. But they probably only add the exes to path, so should be benign. 

The error does not appear if the exe is in the same cabal package as the lib: https://ci.appveyor.com/project/Mikolaj/lambdahack/build/1.0.428

Some vaguely related links:

https://mcuoneclipse.com/2017/11/12/solving-problem-with-gnu-linker-and-referenced-in-section-defined-in-discarded-section-error-message
https://stackoverflow.com/questions/31085538/function-referenced-in-section-text-of-defined-in-discarded-section-te
https://ghc.haskell.org/trac/ghc/ticket/9524
https://ghc.haskell.org/trac/ghc/ticket/14300

**Comment by Mistuke** [comment]
That's... peculiar.. can you attach `dist\build\Allure\Allure-tmp\Paths_Allure.o` and `dist\build\Allure\autogen\Paths_Allure.hs`?

> Also, the log shows some new chocolatey Windows shims are present in the new chocolatey cabal package. But they probably only add the exes to path, so should be benign.

Chocolatey always created shims, the only difference is that now the package contains both 32 and 64bit  cabals and it uses the 64 bit one by default on 64 bit hosts.

Previously the cabals in chocolatey were only 32 bit. My guess is something is trying to link a 32 bit ABI into a 64 bit build and that it has less to do with cabal `2.0` vs `2.2`. This probably works if you do a `choco install cabal -x86` before the ghc install. I'll investigate later when I get home.

**Comment by Mistuke** [comment]
The suspicious part is this

>    `_GetModuleFileNameW' referenced in section `.text' of dist\build\Allure\Allure-tmp\Paths_Allure.o: 
>    defined in discarded section `.text' of C:/ProgramData/chocolatey/lib/ghc/tools/ghc-
>    8.2.2/mingw/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-
>    mingw32/lib/../lib/libkernel32.a(dghgds00535.o)

Notice `i686`. and not a `64 bit` gcc path. This is starting to look like an issue with the `gcc` bindists.

**Comment by Mikolaj** [comment]
You are totally right. I removed forcing the 2.0 version and it still works. So it seems forcing reinstall of cabal before reinstall of ghc is enough for the build to succeed. I verified in the logs that reinstalling only ghc (from 64bit to 32bit) doesn't induce reinstall of cabal for 32bit. Previously it resulted in 32bit cabal used for both 32bit and 64bit builds and it worked fine. But after the change in chocolatey packaging, the 64bit cabal was used for both and it broke the 32bit build for some reason.

Re Chocolatey shims, I just noticed there is a message about them in the new build log and no mention in the old, but you may very well be right they are applied in both.

Re `libkernel32.a` path, I'd say it's right, because we are building for 32bits at this place (this is the end of the log and there we build for 32bit, while be build fo 64bit at the beginning).

**Comment by Mistuke** [comment]
> Re Chocolatey shims, I just noticed there is a message about them in the new build log and no mention in the old, but you may very well be right they are applied in both.

The message is a debug message that I explicitly print out now to tell the user which one was ignored and which one was shimmed. The shim creations are usually transparent and have no user output unless you put chocolatey in verbose mode.

The GHC package doesn't use shims at all but uses the PATH to control things. This is so I can better support having multiple versions of GHC installed at once. For cabal that wasn't a needed feature.

**Comment by Mistuke** [comment]
> You are totally right. I removed forcing the 2.0 version and it still works. So it seems forcing reinstall of cabal before reinstall of ghc is enough for the build to succeed. I verified in the logs that reinstalling only ghc (from 64bit to 32bit) doesn't induce reinstall of cabal for 32bit.

Ahhhh I did not scroll down, so I hadn't notice you were building both versions in one build. This starts to make some sense to me now.

So you can build a `64 bit` executable using a `32 bit` cabal because `ld` will do `stdcall fixup`, and rewrite the `stdcall to ccall`. It can do this by adding stubs to clean up the argument passing since the caller doesn't need changing.

But it seems like you cannot build a `32 bit` application using a `64 bit cabal`. Because you can't fixup `ccall to stdcall` during linking because that would require changes at the caller site.

Now what has me confused is to why the architecture of `cabal-install` matters. It should be linking against the `Cabal` library registered in `GHC`. So it should work. but somehow the architecture of the tool generating the `Path_` module seems to be mattering..

**Comment by Mikolaj** [comment]
Let me know if I can make any experiments for you, though that's not very easy for me, because I don't have Windows, so I have to hack the appveyor scripts and debug via the logs or export extra info via the build artifacts. Thank you again.

**Comment by Mistuke** [comment]
No worries I'll try to reproduce it this weekend. Should be easy enough I
think.

**Comment by Mistuke** [comment]
Ok, this is a bug in cabal. When generating the `Paths_` module the `cconv` is baked into the binary instead of being determined by the compiler being used to compile the library.

If you look at https://github.com/haskell/cabal/blob/602dfdcda54476ef182a8acdc4673c7e840da92f/Cabal/Distribution/Simple/Build/PathsModule.hs#L298 the `cconv` check is done in that module. So a 64 bit cabal will always use `ccall`. Which explains the error.

This check should instead be done in the generated `Paths_` module.

**Comment by Mikolaj** [comment]
Indeed, it takes the arch from `System.Info` at compile time of cabal exe: https://github.com/haskell/cabal/blob/76bafc11e53390b9adfd1b3a8ea907d0adaa45a6/Cabal/Distribution/System.hs#L218

**Comment by Mikolaj** [comment]
Thank you!
