### ISSUE TITLE
why does cabal-install  depend on cabal-testsuite?

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#5262]
maybe i'm overlooking something, but seems to be a dep in the tip of the cabal 2.2 branch ... which took me a little while to realize thats an actual top of the repo package!

**Comment by hvr** [comment]
What makes you think that the `cabal-install` package depends on the `cabal-testsuite` package?

**Comment by cartazio** [comment]
When I run cabal install on the cabal-install Sub dir I seem to get that
error on the 2.2 branch.

I’ll clean stuff up and try again. I had some issues trying to use new
build / new install to work too

**Comment by hvr** [comment]
Without further information I'd prefer to close this. If this problems still persists please reopen with actual log output from cabal.
