### ISSUE TITLE
cabal-install 2.2 environment file build issues

### ISSUE THREAD

**Issue by boj** [haskell/cabal#5274]
We were rebuilding our CI build images with cabal 2.2 instead of 2.0 today and noticed some weird behavior.

Given some library A, and project B which explicitly depends on A, if we build A first (in our case to test for warnings) and then build B after the fact, the `.ghc.environment.x86_64-linux-8.2.2` file that got generated in A prevents B from building.

The fix is to remove that file between the two build steps, but it seems odd that B would break here.

**Comment by hvr** [comment]
@boj how exactly did you invoke the builds?

**Comment by boj** [comment]
The two build steps look like:

```
cabal new-configure --builddir=dist/x/common && cabal new-build -v --builddir=dist/x/common --ghc-options='-Werror'

cabal new-build -v --builddir=dist/x/backend --ghc-options='-Werror'
```

**Comment by 23Skidoo** [comment]
This is a known issue, see https://mail.haskell.org/pipermail/haskell-cafe/2018-May/129076.html and the discussion that followed. Closing in favour of #4542.
