### ISSUE TITLE
SPDX License List 3.2 available

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5282]
https://www.mail-archive.com/spdx-legal@lists.spdx.org/msg01771.html

**Comment by 23Skidoo** [comment]
Would be nice to use this opportunity to document the process of upgrading to a new license list version.

**Comment by phadej** [comment]
Seems that procrastinating pays off sometimes: `Version: 3.2 2018-07-10`

When `2.4` has to be cut off, I'll make an upgrade before that (but would like to push the upgrade as late as possible)

**Comment by hvr** [comment]
@phadej have you figured out how to handle the `cabal-version:` spec-version <-> SPDX list spec version correlation?

**Comment by phadej** [comment]
I think I'll just make Parsec LicenseId case on version (use different auxiliary lookup map), so we can have only non-deprecated LicenseId's in use

The challenge is to engineer the codegen so it doesn't torture GHC too much. I think
- single large LicenseId enum, but
- separate mkLicenseId's per Cabal-spec/SPDX license list version
