### ISSUE TITLE
cabal new-haddock is inconsistent about telling you where the docs are

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#5285]
On the first run of `cabal new-haddock` it tells me where it buried the documentation.

After I successfully build `new-haddock` if I later want to open them and re-run

```
$ cabal new-haddock
Up to date
```

it unhelpfully tells me nothing about the directory in which it was buried previously. This means that you have to go rummage around in `dist-newstyle` by hand. It'd be useful to have it be consistent with the initial haddock run and tell you where they are.

**Comment by alexbiehl** [comment]
@ekmett this has been addressed in some of recent work. This should work on master.
