### ISSUE TITLE
Possible incorrect handling of whitespace in .cabal file parser

### ISSUE THREAD

**Issue by piyush-kurur** [haskell/cabal#5292]
In cabal file's `mixin` stanza the `requires` clause has a problem with white spaces.
In particular the code

```
mixin: foo requires ( A as B) -- This fails (note the space after the parenthesis)
mixin: foo requires (A as B) -- This works.
```

Here is an example of a package that fails <https://github.com/piyush-kurur/trying-backpack/blob/master/whitespace/whitespace.cabal#L40>

**Comment by phadej** [comment]
That's known bug. Try with `cabal-version: 2.2`

**Comment by hvr** [comment]
We still haven't documented the `mixin` field in the user's guide, have we?

**Comment by piyush-kurur** [comment]
I think I managed to fix this particular bug. Shall I send a pull request?

**Comment by phadej** [comment]
Ah, seems I haven't fixed that because backward compatibility:

https://github.com/haskell/cabal/issues/5150

**Comment by phadej** [comment]
I.e. the fix isn't *simply* adding `spaces` in right place, if we don't want to break `cabal-install-2.0` and `cabal-install-2.2` users.

**Comment by phadej** [comment]
@piyush-kurur you can check how `VersionRange` is cased by cabal version. It's not tricky, just something to be aware of. (And if one changes the parser, it's good idea to write a lot of test for *should be accepted and rejected* cases, so we don't end up with layers of versions :))

**Comment by piyush-kurur** [comment]
@phadej I guess what you mean is that the parser skipping spaces should depend on the version declared  in the cabal file ? I just pushed the parser changes to my repository https://github.com/piyush-kurur/cabal/commit/cb0d813277b5fd1b509425beef21169fd470f217. As far as I see these are instace declarations of  certain types. I do not think I have access to the version ranges here.

**Comment by phadej** [comment]
Resolved by https://github.com/haskell/cabal/pull/5514
