### ISSUE TITLE
Flag normalisation for GHC 7.0-7.10

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5298]
This is reminder, only support for GHC >= 8.0 is implemented.

**Comment by merijn** [comment]
Should be pretty easy (albeit somewhat time consuming, depending on code churn), just a matter of checking out source for relevant GHC versions, diffing DynFlags.hs with 8.0 and adjusting relevant bounds.

**Comment by phadej** [comment]
I think we don't care about these GHCs anymore that much.
