### ISSUE TITLE
cabal-install bootstrap.sh fails at compiling FetchUtils

### ISSUE THREAD

**Issue by ZeroBomb** [haskell/cabal#5307]
Installing cabal-install on WSL-Ubuntu using the bootstrap script, with ghc 4.8.2 yields the following error:

> 

[ 98 of 146] Compiling Distribution.Client.FetchUtils ( Distribution/Client/FetchUtils.hs, dist/build/cabal/cabal-tmp/Distribution/Client/FetchUtils.o )

Distribution/Client/FetchUtils.hs:182:36: error:
    • Couldn't match type ‘Distribution.Types.PackageId.PackageIdentifier’
                     with ‘Cabal-2.2.0.1:Distribution.Types.PackageId.PackageIdentifier’
      NB: ‘Cabal-2.2.0.1:Distribution.Types.PackageId.PackageIdentifier’
            is defined in ‘Distribution.Types.PackageId’
                in package ‘Cabal-2.2.0.1’
          ‘Distribution.Types.PackageId.PackageIdentifier’
            is defined in ‘Distribution.Types.PackageId’
                in package ‘Cabal-2.2.0.1’
      Expected type: Cabal-2.2.0.1:Distribution.Types.PackageId.PackageIdentifier
        Actual type: PackageId
    • In the second argument of ‘Sec.downloadPackage'’, namely ‘pkgid’
      In a stmt of a 'do' block: Sec.downloadPackage' rep pkgid path
      In the second argument of ‘($)’, namely
        ‘do info verbosity ("Writing " ++ path)
            Sec.downloadPackage' rep pkgid path’
       |
182 |           Sec.downloadPackage' rep pkgid path
       |                                                     ^^^^^

Error during cabal-install bootstrap:
Building the cabal-install package failed.

**Comment by jneira** [comment]
bootstrap.sh does not exist anymore, so i am gonna close it optimistically, betting the newbootstrap.py does not suffer the issue 😄
feel free to reopen the issue ifthat is not the case
