### ISSUE TITLE
add way to query package dependency graph

### ISSUE THREAD

**Issue by bos** [haskell/cabal#532]
(Imported from [Trac #539](http://hackage.haskell.org/trac/hackage/ticket/539), reported by ganesh on 2009-04-17)

I'd like to be able to list all the forward or reverse dependencies of a package, optionally recursively.

The attached patch makes a 'cabal depends' command that does this, but Duncan (quite reasonably) doesn't want a proliferation of top-level commands. Instead it should be integrated into cabal info in some appropriate way, but this probably requires some refactoring of that command first.

The attached patch could also be improved in (at least) two ways:

<ul><li>Deal with package version numbers as well as names. This involves matching the constraints on version numbers against specific version numbers.
</li><li>Use a less naive transitive closure calculation.
</li></ul>

**Comment by ulysses4ever** [comment]
The current way to access dependency graph is https://hackage.haskell.org/package/cabal-plan It’s debatable whether it should be ported into Cabal.

**Comment by Mikolaj** [comment]
Please kindly join the debate in other tickets or open a new one if the standalone cabal-plan is not enough for you use case. Closing.
