### ISSUE TITLE
document CABAL_CONFIG env variable.

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#5322]
`nix-shell` works by setting a bunch of env variables. It would be nice if among those variables it could set would be one that directed `cabal` to use a config file other than in ~/.cabal/config. That way, we could tweak all of cabal's other settings at once to make it play nicely in the nix environment. This is potentially useful in other settings as well when some other tool wants to put cabal into a specific environment.

**Comment by grayjay** [comment]
`CABAL_CONFIG` overrides the config file location, though it looks like it's not documented:

https://github.com/haskell/cabal/blob/3c339d2ea9e204c551acab62e18284deb0ea9b23/cabal-install/Distribution/Client/Config.hs#L658-L660

**Comment by hvr** [comment]
r elatedly, it may be useful to have such an env-var for setting the `--project-file` value via env as well
