### ISSUE TITLE
pushbot's ssh key got revoked

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#5330]
This means that downstream CI jobs are no longer running. A short term fix is to issue a new ssh key, but another thing we can do is hide it from the repo so that GH doesn't detect it again.

**Comment by quasicomputational** [comment]
When you say 'hide it from the repo', do you mean something like rot-128ing all the bytes in the repo and then reversing it before pushing in the Travis script? Or something more elaborate than that?

**Comment by ivan-m** [comment]
Store them as secrets in the actual CI tools?

(e.g. Travis-CI allows you to store encrypted values/files in the YAML configuration, which are encrypted using a repo-specific key using the `travis` command line tool.)

**Comment by 23Skidoo** [comment]
There's some reason we can't do that, though I don't what it is rn.

**Comment by ezyang** [comment]
The reason we can't store it in YAML is that we need PRs to have rights to push to the binaries repo, and Travis doesn't permit pull requests to get at Travis secrets (for good reason; they'd be trivially exfiltratable that way!) Rot32 would be good enough, I think; we could also host it on another webserver (and maybe firewall it so only Travis servers can ping it.)
