### ISSUE TITLE
New cabal continues to be overridden by old cabal

### ISSUE THREAD

**Issue by mcandre** [haskell/cabal#5338]
When `cabal install cabal-install` finishes, it appends the new cabal to `PATH`, which unfortunately means that users invoking `cabal` will trigger the old, system cabal instead of the desired, new cabal:

```console
$ cat /etc/profile.d/cabal-install.sh
CABALBIN=${HOME}/.cabal/bin

if ! echo ${PATH} | /bin/grep -q ${CABALBIN} ; then
    if [ -d ${CABALBIN} ]; then
	PATH=${PATH}:${CABALBIN}
    fi
fi
unset CABALBIN
```

I'm patching my `/etc/profile.d/cabal-install.sh` to prepend the new CABALBIN to PATH, so that the right one gets invoked when users type `cabal`.

**Comment by gbaz** [comment]
`cabal` doesn't modify the path afaik. It just inserts into `/.cabal/bin` unconditionally. The issue is however the path is setup already has the wrong precedence order between the directories. So I'd explore how that happens (because it isn't cabal!).

**Comment by hvr** [comment]
@mcandre `/etc/profile.d/cabal-install.sh` is something typically installed by Fedora linux distributions when you install `cabal-install` via RPM. Are you experiencing this on Fedora?

**Comment by 23Skidoo** [comment]
Sounds like a system configuration issue, i.e. not a `cabal-install` bug.
