### ISSUE TITLE
cabal check mentions ghc-options when it could be ghc-shared-options

### ISSUE THREAD

**Issue by quasicomputational** [haskell/cabal#5342]
Title is self-explanatory. All the various `ghc-(shared-|prof-|)options` get smashed together in one list and if there's something warnable in there it's reported as `ghc-options`, which could send someone astray. Better would be keeping track of which field an option comes from and then reporting that.

**Comment by 23Skidoo** [comment]
Adding provenance information to that check should be relatively easy. See `Distribution.PackageDescription.Check`.
