### ISSUE TITLE
writeGenericPackageDescription erroneously omits "buildable: True"

### ISSUE THREAD

**Issue by peti** [haskell/cabal#5352]
If you run the program

~~~
module Main ( main ) where

import Distribution.PackageDescription.Parsec
import Distribution.PackageDescription.PrettyPrint
import Distribution.Verbosity

main :: IO ()
main = readGenericPackageDescription silent "fgl.cabal"
   >>= writeGenericPackageDescription "fgl.cabal-new"
~~~

on the [`fgl-5.6.0.0`](http://hackage.haskell.org/package/fgl-5.6.0.0/fgl.cabal) Cabal file, then the generated output ends with the following stanza:

~~~
benchmark fgl-benchmark
    type: exitcode-stdio-1.0
    main-is: benchmark.hs
    hs-source-dirs: test
    other-modules:
        Data.Graph.Inductive.Proxy
    default-language: Haskell98
    ghc-options: -Wall
    build-depends:
        fgl -any,
        base -any,
        microbench -any,
        deepseq -any

    if flag(containers042)
    else
        buildable: False
~~~

That last is-else clause is a syntax error, obviously, and it's caused by Cabal omitting the `buildable: True` attribute that was originally specified there. This issue exists in Cabal's current `master` @ 5c9cadef6c9f17f827aa91f8f1f0f53ce2a9a9d1, but it's been introduced much earlier.

**Comment by phadej** [comment]
It's parse error with older Cabal's, but not with current.

```
% tail -n 20 fgl.cabal 

    ghc-options:      -Wall

}

benchmark fgl-benchmark
    default-language: Haskell98
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          benchmark.hs
    other-modules:    Data.Graph.Inductive.Proxy
    build-depends:    fgl
                    , base
                    , microbench
                    , deepseq

    ghc-options:      -Wall
    if flag(containers042)
    else
        buildable:    False

% cabal check 
The following warnings are likely to affect your build negatively:
* The 'license-file' field refers to the file 'LICENSE' which does not exist.

* 'hs-source-dirs: test' directory does not exist.

* 'hs-source-dirs: fgl-arbitrary' directory does not exist.

* 'hs-source-dirs: test' directory does not exist.

Hackage would reject this package.

% cabal-1.18 check
cabal-1.18: fgl.cabal:123: 'then' branch of 'if' is empty

```

I have this problem at hand when making `writeGenericPackageDescription`. Either I make old Cabal read it, or make the file roundtrip. I picked latter.

For me it's not a syntax error to begin with. Sections in cabal-like files can be empty.

I'm tempted to close this as *wontfix*

**Comment by phadej** [comment]
Addition: this is not a problem for Hackage, as Hackage checks files with old `Cabal` parsers. So you won't be able to upload such `cabal-version: 1.12` file for old `cabal-install` to consume.

For other tooling, which cares about support for older `cabal-install`s, I'd recommend to do a transformation like was done on the `CondTree`s in `GenericPackageDescription` https://github.com/haskell/cabal/blob/c048b479d4c2a6eeaad8bd29a0cceb8c86cba41b/Cabal/Distribution/PackageDescription/PrettyPrint.hs#L251, as you see it was a hack, and it's good it's gone from Cabal codebase.

**Comment by peti** [comment]
> For me it's not a syntax error to begin with. 

Okay, I see your point. I have to say, though, that 

~~~
    if flag(containers042)
    else
        buildable: False
~~~

looks far less nice than

~~~
    if !flag(containers042)
        buildable: False
~~~

..., which does the same thing and should work with older Cabal versions, too. Anyhow, if you don't want to deal with this issue in Cabal, then I suppose I can add a workaround to my tool instead. Thank you for the pointers to prior art.

**Comment by phadej** [comment]
"less nice" is not an error. Ugly: yes, error: no.

As said, I value the roundtrip-property: you get exactly the same GPD when you read it back, and it works for whole Hackage. My argument is that it makes testing of `writeGenericPackageDescription`  simple: can use `==` vs. some more complicated GPD-equivalence.
