### ISSUE TITLE
symlink-bindir should really be a user/global option rather than in the main section

### ISSUE THREAD

**Issue by bos** [haskell/cabal#537]
(Imported from [Trac #544](http://hackage.haskell.org/trac/hackage/ticket/544), reported by Jedai on 2009-04-19)

Well, not much to add. symlink-bindir is currently an option from the main section, it would make more sense to make it an option for the installdirs sections since this is really a choice of where to install things.

**Comment by gbaz** [comment]
now that we're moving more generally way from the "user"/"global" view of installs of things (the v1 way) I think this ticket is outdated and will close.
