### ISSUE TITLE
Cabal new-build generating insanely long and redundant build PATHS on Windows.

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#5376]
I'm trying to https://github.com/input-output-hk/cardano-sl on Windows in AppVeyor. Unfortunately Cardano SL is a large project and using Stack we have been continuously bumping up against the Windows path length limitations. 

Trying `cabal new-build` as an alternative to stack we run into the Windows path length issue in a different place. From the AppVeyor output, it seems `cabal new-build` is installing stuff in:
```
C:\Users\appveyor\AppData\Roaming\cabal\store\ghc-8.0.2\incoming\new-1824\
  Users\appveyor\AppData\Roaming\cabal\store\ghc-8.0.2\
```
a path with one hell of a lot of redundancy. That path should at least be shortened to something like:
```
C:\Users\appveyor\AppData\Roaming\cabal\store\incoming\new-1824\ghc-8.0.2\
```

**Comment by harpocrates** [comment]
Does `--store-dir` not fix this for you? You should be able to set that to something super short... I was running into this sort of problem on AppVeyor and passing `--store-dir=c:\cabal-store` ended up being my workaround.

**Comment by gbaz** [comment]
But even if there's a workaround, it still seems like a genuine bug that the path is duplicated, no?

**Comment by Mistuke** [comment]
Yeah, I have a PR for that but couldn't figure out why it caused a test to fail on linux and I forgot about it... https://github.com/haskell/cabal/pull/4978

Also long paths for Haskell programs are fixed in GHC 8.6, so a cabal-install compiled with 8.6 should work without any workarounds.

**Comment by angerman** [comment]
Long paths may be fixed. The response file fix for library search paths, which what @erikd s underlying issue is, won’t be solved in time for 8.6, I believe?

**Comment by Mistuke** [comment]
It depends on when @bgamari wants patches by. I'm trying figured out the
build issues.

**Comment by Mistuke** [comment]
Also how is the response files think Erik'd underlying issue? This ticket is purely about backpack making a path too long for it to write to with the current platform APIs it's using. It has nothing to do with the underlying compiler and linker because it doesn't get that far.

**Comment by angerman** [comment]
You are right that it’s not explicitly mentioned. I believe this came up when we tried to swap cabal in for stack, which kept failing on windows. The exceptionally long paths just made the issue worse.

**Comment by AndreasPK** [comment]
> Also long paths for Haskell programs are fixed in GHC 8.6, so a cabal-install compiled with 8.6 should work without any workarounds.

I still get long path related errors with cabal new-build using GHC head so I'm not sure if this is completely fixed.

**Comment by Mistuke** [comment]
Such as?

**Comment by Mistuke** [comment]
Right, that's not cabal failing but gccc, we have a ticket for that. The
patch explicitly mentioned ghc is not excluded from MAX_PATH because of the
use of gnu utilities. That's going to take some time to patch

**Comment by Mistuke** [comment]
Ultimately there's nothing `cabal` itself can do to fully fix this, for every workaround we do there will always be a corner case. I need to find some time to finish https://github.com/haskell/cabal/pull/4978 which should mitigate it for a bit but we need to fix the surrounding tools.

**Comment by jasagredo** [comment]
I think this has been fixed already, there are no directories in `store/ghc-xxx/incoming`:

```
➜ ls -lah AppData/Local/cabal/store/ghc-9.8.2/incoming/ | grep "^d"
drwxr-xr-x 1 Javier Javier 0 Jul 18 23:30 .
drwxr-xr-x 1 Javier Javier 0 Jul 18 23:30 ..
```

I will preemptively close this issue. Feel free to re-open if you disagree.
