### ISSUE TITLE
cabal new-build --help says default build-dir is dist/

### ISSUE THREAD

**Issue by quasicomputational** [haskell/cabal#5380]
That's a lie: it should be `dist-newstyle/`. I started chasing this up but I got lost in the twisty maze of option parsing.

**Comment by hvr** [comment]
fwiw, `dist-newstyle` is supposed to be renamed to `dist` when `new-build` becomes `build`; so I'm not sure this is of much priority.

**Comment by typedrat** [comment]
I'm gonna say that makes this a WONTFIX.
