### ISSUE TITLE
Uses of 'extra-prog-path' from cabal config need to format it for the specific platform

### ISSUE THREAD

**Issue by randen** [haskell/cabal#5420]
The cabal config uses "," (comma) and the platform-specific newline (at least on Windows, it is CR/LF) to format multi-line entries.  For example, if cabal-install is used to --augment the user's config file with extra-prog-path entries, this is the result (note: the "\n" below would be the actual newline 0x0D):

````
extra-prog-path: F:\Program Files\Haskell Platform\8.4.3\msys\usr\bin,\n
                 F:\Users\name\AppData\Roaming\cabal\bin
````
Uses of this entry by the Cabal code (specifically, during a 'cabal build') is taken without sufficient conversion.  When used in command line arguments or environment variables (e.g., %PATH%), a conversion to remove any linefeeds (0x0A) and change newline (0x0D) into the two characters "\n" seems to be done, and the comma(s) remains.

However, for use in a Windows PATH variable, the commas need to be converted to semi-colons, and the newlines should be stripped completely rather than being converted to the two characters '\\' and 'n'.

This issue results in the extra programs not being found on these extra paths due to these syntactic errors, failing the use case of being able to build configure-style projects which require a unix-like system such as MSys.

**Comment by yaxu** [comment]
Thanks for clarifying this @randen. As the maintainer of the tidalcycles library I probably help someone with this issue every day.

**Comment by yaxu** [comment]
Oh, I thought that this was recent, but the probem was identified 8th July 2018. I'd love to see this fixed.
