### ISSUE TITLE
cabal new-repl without a project

### ISSUE THREAD

**Issue by int-index** [haskell/cabal#5425]
Sometimes I just need to check a couple of things in GHCi, not specific to any project. I could run `ghci`, but then I don't get access to any packages except the ones that are installed globally.

With `stack` I can run `stack ghci --package lens`, for instance.

With `cabal` I have to create something like this:

```
cabal-version: 2.2
name: global
version: 0

library
  build-depends: base, lens
  default-language: Haskell2010
```

and then run `cabal new-repl` in a directory with this `.cabal`-file.

I'd prefer to write `cabal new-repl --package lens`:

* it would find a suitable build plan for the specified packages and launch GHCi in this environment
* it would not create `dist-newstyle` in the current directory, instead it could use `~./cabal/dist-global` or similar

**Comment by int-index** [comment]
another possible syntax:

```
cabal global repl --build-depends "lens, aeson"
```

**Comment by hvr** [comment]
@int-index you can try https://github.com/hvr/cabal-env for now, which is supposed to be a UI prototyping sandbox for what a possible UI for cabal could be.

Your use-case is handled by

    cabal-env -i lens aeson

**Comment by int-index** [comment]
@hvr thank you, `cabal-env` indeed works well for my needs. Looking forward to having this functionality in `cabal`.

**Comment by hvr** [comment]
@int-index btw, please feel free to suggest enhancements to `cabal-env`; it's really supposed to be a playground for UI experimentation.
