### ISSUE TITLE
Behavior when settings options via new-configure and new-build.

### ISSUE THREAD

**Issue by AndreasPK** [haskell/cabal#5457]
> The options of all of these flags apply only to local packages in a project; this behavior is different than that of cabal install.

http://cabal.readthedocs.io/en/latest/nix-local-build.html#cabal-new-configure

> '--with-PROG' and '--PROG-options' are applied to all packages
	and not local packages only (#5019).

https://github.com/haskell/cabal/blob/41eab33eb2ef16b73660e5675929b03c27fc546b/cabal-install/changelog#L26

This should be updated I assume if this behavior is here to stay.

There is also a bug where new-builds doesn't pick up options set via new-configure

* `new-configure --disable-tests --ghc-options="-fimpossible-flag"` lists as far as I can tell all dependencies as being rebuilt. (So working like the changelog describes)
* `cabal new-build all --disable-tests --ghc-options="-fimpossible-flag" --dry-run` does as well.
* `cabal new-configure <brokenFlag>; cabal new-build all --dry-run` does ignore the broken flag change and thinks everything is up to date.

I guess configure is either writing a wrong project.local file or new-build is ignoring it.

```
$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library
```

**Comment by AndreasPK** [comment]
This seems to be fixed in the master branch for what it's worth.

**Comment by gbaz** [comment]
closing on the basis this is reported fixed
