### ISSUE TITLE
Subdir field of `source-repository-package` should accept multiple arguments.

### ISSUE THREAD

**Issue by merijn** [haskell/cabal#5472]
I'm playing around with the freshly merged `source-repository-package` (#2189, #5351), after searching the `cabal-install` source to figure out all the field names, I noticed an annoyance. The implementation of remote dependencies was prescient enough to allow me to specify a subdirectory to look for a cabal file in, but sadly only allows me to list a single subdirectory to look in.

I have several related packages in a single repository, these depend on each other, but some haven't been released yet, so I need to depend on multiple package from the same repo. Unfortunately, I can only specify one subdir to look in for cabal files. I've worked around this by listing the same repo multiple times, but this super ugly:

```
source-repository-package
  type: git
  location: https://github.com/merijn/broadcast-chan.git
  tag: 996aecdacc2eb8501a1a27c8559153d93ed3d6d2
  subdir: broadcast-chan

source-repository-package
  type: git
  location: https://github.com/merijn/broadcast-chan.git
  tag: 996aecdacc2eb8501a1a27c8559153d93ed3d6d2
  subdir: broadcast-chan-conduit

source-repository-package
  type: git
  location: https://github.com/merijn/broadcast-chan.git
  tag: 996aecdacc2eb8501a1a27c8559153d93ed3d6d2
  subdir: broadcast-chan-tests
```

Ideally subdir should just take a list of subdirectories so I can instead simply write:

```
source-repository-package
  type: git
  location: https://github.com/merijn/broadcast-chan.git
  tag: 996aecdacc2eb8501a1a27c8559153d93ed3d6d2
  subdir: broadcast-chan broadcast-chan-conduit broadcast-chan-tests
```

**Comment by hvr** [comment]
I have to cringe at a singular `subdir` taking multiple args ;-)

other than that, I think that's a reasonable request (and indeed it's been suggested to @dcoutts already iirc)

**Comment by merijn** [comment]
@hvr Well, we could just change it to `subdirs` instead of `subdir`, since it's not in any officially released version of `cabal-install`. Alternatively, change it to `subdirs` and keep `subdir` as backwards compat alternative.

**Comment by hvr** [comment]
@merijn I like the idea to introduce a `subdirs` fieldname; but isn't the parser for `source-repository-package` shared with the one for source-repos in the `.cabal` pkg description? If so, we'd need to make sure that `subdirs` is only allowed for `source-repository-package` but not for `source-repository`s

**Comment by hvr** [comment]
**IMPORTANT**: Due to #5487 there's a minor added complexity: we'd need to resolve the multiple `subdirs` to a unique a `subdir` in the `plan.json` output for the respective package

**Comment by mpickering** [comment]
This would be a good feature.

**Comment by erikd** [comment]
Just hit this myself. Is there a workaround?

**Comment by dcoutts** [comment]
@hvr I really think this is just a case of expanding it out at the syntax layer. The underlying mechanisms already have support for subdir and doing only a single download even when there are multiple uses of the same repo (including for git when different uses use different commits/branches).

For @erikd and others: yes the workaround is just list the repo multiple times, once for each subdir. It only gets downloaded once.

**Comment by patrickt** [comment]
Would love this!

**Comment by phadej** [comment]
Implementation comment: the `SourceRepository` in `Cabal` the lib **should not** be changed,
as that would change `.cabal` file format. That type need to be forked into `cabal-install`.

**Comment by michaelpj** [comment]
This would be nice!

**Comment by int-index** [comment]
The lack of this feature has definitely been annoying for me. I have the following lines in my `cabal.project`:

```
source-repository-package
  type: git
  location: https://github.com/int-index/slay
  tag: 69b533004637319c2f210dfb17f44acfce3f59d2
  subdir: core

source-repository-package
  type: git
  location: https://github.com/int-index/slay
  tag: 69b533004637319c2f210dfb17f44acfce3f59d2
  subdir: combinators

source-repository-package
  type: git
  location: https://github.com/int-index/slay
  tag: 69b533004637319c2f210dfb17f44acfce3f59d2
  subdir: cairo
```

And each time the `tag:` field changes, I have to update it in three places instead of one place.
