### ISSUE TITLE
Expose cabal-install as a library

### ISSUE THREAD

**Issue by quasicomputational** [haskell/cabal#5473]
There's currently no good way to parse or render `cabal.project` files: there's code in `cabal-install`, but getting at it requires setting a flag with a description telling you not to do that very thing. The alternative for some use-cases is grubbing around with the `plan.json`, which ties you even more to `cabal-install`'s implementation details.

#3781 is an issue from two years ago about exposing the solver somehow, which would be useful for Stack along with other things: again, these are using ugly hacks today like inspecting `plan.json` or trying to parse output that's only meant for human consumption. If I'm looking at things correctly, most of the separation work has been done since that issue was opened; the only thing holding people back is that `cabal-install` isn't sanctioned for use as a library.

What are the concerns that led to not exposing the library? If it's API ossification, I'm not so worried: `cabal-install` isn't a boot package, so users can lag behind on upgrading if necessary. It follows the PVP and I think we should continue to be bold in refactoring the API whenever it's a good idea; the only new thing we would have to do would be to make sure API changes go into the changelog, which we're not currently in the habit of doing.

**Comment by hvr** [comment]
Duplicate of #1597

**Comment by quasicomputational** [comment]
Thanks for the cross-reference - "cabal-install" and "library" are not very precise search terms in the bugs here... I'll close this one and repost a precis of the new information there.
