### ISSUE TITLE
Bacpack doesn't work when one signature imports another and when only imported signature is used

### ISSUE THREAD

**Issue by ChShersh** [haskell/cabal#5490]
My `.cabal` file looks like this:

```haskell
name:                foo
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.25

library foo-sigs
  build-depends:       base
  signatures:          Foo, Bar
  hs-source-dirs:      foo-sigs

library foo-indef
  build-depends:       base, foo-sigs
  exposed-modules:     X
  hs-source-dirs:      foo-indef

library foo-impls
  build-depends:       base
  exposed-modules:     Baz
  hs-source-dirs:      foo-impls


library
  hs-source-dirs:      foo-example
  exposed-modules:     Y

  build-depends:       base, foo-sigs, foo-impls, foo-indef
  mixins:              foo-indef (X as X.Baz)
                          requires (Foo as Baz)
```

I have simple signature with data type and simple function:

```haskell
signature Foo where
data Foo
foo :: Foo -> Foo
```

Now I want to extend this signature  by adding new functions and reusing existing type. So it makes sense to me to have signature like this one:

```haskell
signature Bar where
import Foo
bar :: Foo -> Foo
```

The idea is that sometimes I need only `Foo` signature. Like in this example:

```haskell
module X where

import Foo

foo2 :: Foo -> Foo
foo2 = foo . foo
```

And then I can implement only `Foo` signature:

```haskell
module Baz where

data Foo = Foo

foo :: Foo -> Foo
foo Foo = Foo
```

But when trying to combine like this:

```haskell
library
  hs-source-dirs:      foo-example
  exposed-modules:     Y

  build-depends:       base, foo-sigs, foo-impls, foo-indef
  mixins:              foo-indef (X as X.Baz)
                          requires (Foo as Baz)
```

I see the following error:

```
<no location info>: error:
    • Identifier ‘bar’ has conflicting definitions in the module
      and its hsig file
      Main module: bar :: Baz.Foo -> Baz.Foo
      Hsig file:  bar :: {Foo.Foo} -> {Foo.Foo}
      The two types are different
    • while merging the signatures from:
        • foo-0.1.0.0:foo-indef[Bar=<Bar>,Foo=Baz]:Bar
        • foo-0.1.0.0:foo-sigs[Bar=<Bar>,Foo=<Foo>]:Bar
        • ...and the local signature for Bar
```

Maybe I'm using Backpack in a wrong way? Could you please explain what does this error mean and how can I resolve it?

Cabal version: 2.3.0.0
GHC version: 8.4.3

**Comment by ezyang** [comment]
Your problem is this:

> Now I want to extend this signature by adding new functions and reusing existing type. So it makes sense to me to have signature like this one:

```
signature Bar where
import Foo
bar :: Foo -> Foo
```

To extend a signature, just write a signature *at the same name* and add the extra functions you need. Signature merging will merge the signatures together into a single one.

**Comment by ChShersh** [comment]
@ezyang Thanks a lot :pray: This works like a charm! :blush:

**Comment by ChShersh** [comment]
@ezyang Does this mean that these two signatures should be in different packages? Because I can't have modules with the same name inside single package... Also, I would like to be able to specify on user side what exact module I want to use: initial or extended. How is this possible?

**Comment by ezyang** [comment]
Yes, it (unfortunately) means you'll need separate packages. So you'd have foo-sig and foo-extended-sig, and user side they would either declare a dependency on 'foo-sig' or 'foo-extended-sig'. There's no need to have a dependency relationship between foo-sig and foo-extended-sig, but if you like, foo-extended-sig can depend on foo-sig (and will  "inherit" all the signatures from foo-sig).

Also, to elaborate on the UX some more, if you have packages "p uses foo-sig" and "q uses foo-extended-sig", and you want to use them both together in r, r will have a signature that is the merge of foo-sig and foo-extended-sig.
