### ISSUE TITLE
Better errors for reject-unconstrained-dependencies

### ISSUE THREAD

**Issue by quasicomputational** [haskell/cabal#5501]
In #5475, @grayjay pointed out that the current error reporting from the solver assumes that it is individual versions of a package being rejected. However, `reject-unconstrained-dependencies` will reject packages wholesale rather than individual versions. There may be a way to get better error messages if we can talk about packages rather than versions.

**Comment by grayjay** [comment]
We decided against fitting the error message on one line in #5510, because it was hard to fit all of the information.  The error message needs to show the package name, the reason that the package was required, and the reason for the failure.
