### ISSUE TITLE
Cabal scripting support produces bulk garbage on screen

### ISSUE THREAD

**Issue by typedrat** [haskell/cabal#5508]
I think that cabal-as-a-shebang-interpreter should default to a reduced verbosity because on one hand it is useful information but on the other hand having every script execution start with this is a bit disruptive:

```
❯ ./mk-truth.hs
Resolving dependencies...
Build profile: -w ghc-8.4.2 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (first run)
Configuring executable 'script' for fake-package-0..clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..
[1 of 1] Compiling Main             ( Main.hs, /var/folders/86/3w7nwq551nb3phw0kvflsgcr0000gn/T/cabal-repl.-96612/dist-news
tyle/build/x86_64-osx/ghc-8.4.2/fake-package-0/x/script/build/script/script-tmp/Main.o )
Linking /var/folders/86/3w7nwq551nb3phw0kvflsgcr0000gn/T/cabal-repl.-96612/dist-newstyle/build/x86_64-osx/ghc-8.4.2/fake-pa
ckage-0/x/script/build/script/script ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
```

**Comment by hvr** [comment]
an obvious way would be to be able to set the `verbose: normal` property in the `{- cabal`-meta-data block... unfortunately we still have that bug which prevents cabal from picking up the verbosity setting from config files....

**Comment by bacchanalia** [comment]
a workaround is to use `#!/usr/bin/env -S cabal run -v0`

**Comment by bacchanalia** [comment]
@gbaz Do you have plans to work on this ticket? If not I might take a look at it. What do you think the solution looks like?

**Comment by gbaz** [comment]
I don't have immediate plans to work on it, but I definitely think somebody should, and would be happy to try to give advice.

I think that the first thing would be to just set a lower default verbosity for running cabal scripts. It shouldn't be hard to track down where this is set on that path.

Then overriding the default low verbosity could be documented in the user guide as possible using the trick you just posted, and perhaps you could even find and try to fix the bug that prevents verbosity being set in config files (if indeed it still is a bug) to allow controlling verbosity within the `cabal` block itself.

**Comment by gbaz** [comment]
Thanks for the link! I commented there. Imho the workaround you posted means that we don't need to be blocked on solving that ticket, but that is certainly a good ticket to work on as well.
