### ISSUE TITLE
Cabal treats /c/foo and c:\foo to be the same on Windows.

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#5509]
when used with a `--store-dir` cabal seems to treat the relative path `/c/foo` to be the same as the absolute path `c:\foo`. On Windows, a leading `/` means relative to the active drive. so if your `cwd` was `C:\...` `/c/foo` should refer to `c:\c\foo`.

This is a followup from #5504

**Comment by hvr** [comment]
@ndmitchell are we maybe using `filepath`  wrong in cabal?

**Comment by ndmitchell** [comment]
@hvr perhaps - any idea what code is doing anything? In most cases these things should "just work", but it's always possible to get it wrong.

**Comment by Mistuke** [comment]
hmm I can't seem to find any reason for this in the `cabal` source.  On a clean directory `--store-dir=/c/foo` correctly passes `/c/foo` on to `ghc-pkg` which does the right thing.

So I think this is probably the same caching issue that fixed #5504 as `cabal-head` compiled at ` b07e39fa414b89b18861b060b159625d40ebbf27` works correctly.
