### ISSUE TITLE
Allow `type` in common stanzas or default to `exitcode-stdio-1.0`

### ISSUE THREAD

**Issue by daig** [haskell/cabal#5531]
Currently, cabal complains:

    Unknown field: "type"
    Test suite "my-test" is missing required field "type" ....

I don't see any reason that `type` should be excluded from common stantzas - does it make sense to add?

A minor annoyance, but in practice the boilerplate encourages monolithic test files

**Comment by hvr** [comment]
@daig there *is* a simple reason: common stanzas currently only allow fields which are applicable to all stanza kinds, iow, the common denominator; this was a deliberate design decision to simplify the semantics & implementation for the first iteration of `common`-stanzas.

**Comment by daig** [comment]
Thanks, I had missed that discussion. It does make sense for a first iteration and I'm much glad to have existing `common` stanzas as an 80% solution. What is the best place to track discussion on the next iteration for `common` stanzas?

**Comment by hvr** [comment]
@daig keep watching this ticket and the original #2832; if any progress is made those tickets are very likely to get updated as well

**Comment by gbaz** [comment]
I think this is subsumed by https://github.com/haskell/cabal/issues/7459
