### ISSUE TITLE
check doesn't warn on build-tool-depends with pre-2.0 spec versions

### ISSUE THREAD

**Issue by quasicomputational** [haskell/cabal#5532]
`build-tool-depends` was new in 2.0, but `cabal check` doesn't warn if you use it with an earlier spec version. It ought to, since it likely won't be doing what the user wants if it's used with an old version of Cabal.

This should be easy for a newcomer: the relevant module is `Distribution.PackageDescription.Check`, and there are several examples of warning about constructs if the spec version is too low in there already.

**Comment by Mikolaj** [comment]
I don't hear any objections, so let's close this until somebody with an up to date use case and enough motivation decides it's worth the trouble to start the discussion anew.
