### ISSUE TITLE
Incorrect haddock link

### ISSUE THREAD

**Issue by qrilka** [haskell/cabal#5537]
At http://hackage.haskell.org/package/Cabal-2.2.0.1/docs/Distribution-Version.html#v:mkVersion-39-
in the text

> Variant of Version which converts a Data.Version Version into Cabal's Version type.

2 URL for "Version" point to the same http://hackage.haskell.org/package/Cabal-2.2.0.1/docs/Distribution-Version.html#t:Version while the 1st of them should point to the one in `Data.Version` from `base`

**Comment by 23Skidoo** [comment]
Fixed, thanks!
