### ISSUE TITLE
build-tool-depends in setup-depends

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#5540]
While trying to use `cabal` to build a project that the author has setup with `stack`, I found myself wanting to add `build-tool-depends` to `setup-depends`:

```
custom-setup
  setup-depends:
      base
    , Cabal
    , containers
    , directory
    , filepath
    , genapply
    , process
  build-tool-depends:
    genapply:genapply
```

but Cabal seems to not know how to handle `build-tool-depends` in `custom-setup`. Is that intentional, or an oversight?

**Comment by hvr** [comment]
Duplicate of #4648

**Comment by 23Skidoo** [comment]
Closing in favour of #4648.
