### ISSUE TITLE
Too many open files with cabal new-sdist and many data-files

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#5541]
A project that I was trying to build contains one package (`ghc-toolkit`) that has 1054 files in `data-files` defined 
(https://github.com/tweag/asterius/tree/caf15690c54aef3ae4eecbc7224c6163de040f7a/ghc-toolkit).

It also contains another package `genapply` that does not even depend on `ghc-toolkit`.

I can run `cabal new-build genapply` just fine. But if I run `cabal new-install genapply`, I get

```
$ cabal new-install genapply -w ~/build/haskell/ghc/inplace/bin/ghc-stage2 --allow-newer=base
Wrote tarball sdist to
/home/jojo/build/haskell/asterius/dist-newstyle/sdist/asterius-0.0.1.tar.gz
boot-libs/template-haskell/Language/Haskell/TH/LanguageExtensions.hs: openBinaryFile: resource exhausted (Too many open files)
```
Interestingly, 
```
$ cabal new-sdist genapply 
Downloading
https://github.com/haskell/primitive/archive/ea9f0426646ecf8a5a0a1659b29a8dc014ceda05.tar.gz
Wrote tarball sdist to
/home/jojo/build/haskell/asterius/dist-newstyle/sdist/genapply-0.1.tar.gz
```
works, but
```
$ cabal new-sdist all
Downloading
https://github.com/haskell/primitive/archive/ea9f0426646ecf8a5a0a1659b29a8dc014ceda05.tar.gz
Wrote tarball sdist to
/home/jojo/build/haskell/asterius/dist-newstyle/sdist/asterius-0.0.1.tar.gz
boot-libs/template-haskell/Language/Haskell/TH/Ppr.hs: openBinaryFile: resource exhausted (Too many open files)
```
does not.

So maybe there are two issues here:

 * `cabal new-install` creates more `sdists` than it has to.
 * `cabal new-sdist` does not work well with large number of `data-files`.

**Comment by hvr** [comment]
It's quite possible `new-sdist` might have uncovered a long-standing bug in the sdist code...

**Comment by typedrat** [comment]
This means files aren't getting closed correctly, because if `new-sdist` works for one it should work for all.

**Comment by typedrat** [comment]
I've been looking at the code and thinking about this for the last bit, and I just do not see how this bug is possible.

**Comment by 23Skidoo** [comment]
Lazy I/O? A missing `bracket` leading to a resource leak?

**Comment by typedrat** [comment]
I don't see any obvious resource acquisitions, so I'm pretty close to saying (through the process of elimination) it's (curses!) lazy IO.

**Comment by typedrat** [comment]
>Read an entire file lazily into a ByteString. The Handle will be held open until EOF is encountered.

**Comment by hvr** [comment]
NB: this was already cherry-picked to 2.4

**Comment by nomeata** [comment]
Thanks!
