### ISSUE TITLE
cabal: failed to parse output of 'ghc-pkg dump'

### ISSUE THREAD

**Issue by m13m** [haskell/cabal#5548]
Hello,
```
$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.3
```

ghc-pkg dump : https://gist.github.com/m13m/99ce52d0620703f5dd6ab534266d5d10

I tried to update with `cabal install Cabal cabal-install` got the error "cabal: failed to parse output of 'ghc-pkg dump' "

**Comment by phadej** [comment]
2.0 is not the latest, and it doesn't work with GHC-8.4. You should use cabal-install-2.2

I'm surprised cabal-install doesn't error out sooner, as you try to use it with "unknown" GHC-version

**Comment by m13m** [comment]
@phadejI have updated the issue description.

**Comment by hvr** [comment]
@phadej well, Cabal-2.0.1.1 didn't have the warning for unknown GHC versions yet... and well, it'd just be a warning for now; at some point we might want to turn it into an error

**Comment by hvr** [comment]
@m13m were you able to resolve the issue by upgrading to at least cabal 2.2 ?

**Comment by m13m** [comment]
@hvr I did the fresh Install and everything working fine now.

**Comment by doaitse** [comment]
I am getting this message too, with a fresh install of the Haskell platform:
Last login: Wed Jan  9 10:41:45 on ttys001
Doaitse-2:~ doaitse$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library 
Doaitse-2:~ doaitse$ cabal update           
Downloading the latest package list from hackage.haskell.org
Skipping download: local and remote files match.
Doaitse-2:~ doaitse$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.3
Doaitse-2:~ doaitse$ cabal --verbose install uu-parsinglib
/Users/doaitse/Library/Haskell/bin/alex --version
/Users/doaitse/Library/Haskell/bin/cpphs --version
/usr/bin/gcc -dumpversion
looking for tool haddock near compiler in /usr/local/bin
found haddock in /usr/local/bin/haddock
/usr/local/bin/haddock --version
/Users/doaitse/Library/Haskell/bin/happy --version
/usr/local/bin/hpc version
looking for tool hsc2hs near compiler in /usr/local/bin
found hsc2hs in /usr/local/bin/hsc2hs
/usr/local/bin/hsc2hs --version
/usr/local/bin/HsColour -version
/usr/local/bin/ghc -hide-all-packages -c /var/folders/9m/xpbyx5fs19xcf68s9wjjy12c0000gn/T/16807282475249.c -o /var/folders/9m/xpbyx5fs19xcf68s9wjjy12c0000gn/T/1622650073984943658.o
/usr/bin/ld -x -r /var/folders/9m/xpbyx5fs19xcf68s9wjjy12c0000gn/T/1622650073984943658.o -o /var/folders/9m/xpbyx5fs19xcf68s9wjjy12c0000gn/T/1144108930470211272.o
/usr/local/bin/pkg-config --version
Warning: cannot determine version of /usr/bin/strip :
""
/usr/bin/tar --help
cabal: failed to parse output of 'ghc-pkg dump'
Doaitse-2:~ doaitse$

**Comment by code5hot** [comment]
cabal repl
Resolving dependencies...
Configuring gtk3-0.15.1...
setup: failed to parse output of 'ghc-pkg dump'
tristan@unobtanium:~/photon/gtk3-0.15.1$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library 
tristan@unobtanium:~/photon/gtk3-0.15.1$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.4
