### ISSUE TITLE
option `--builddir' is ambiguous

### ISSUE THREAD

**Issue by martijnbastiaan** [haskell/cabal#5550]
I want cabal to put its build files in a custom directory. However using `builddir` results in an error:

```
$ /opt/cabal/bin/cabal-head new-install --builddir=/tmp/dist
cabal-head: option `--builddir' is ambiguous; could be one of:
--builddir=DIR The directory where Cabal puts generated build files (default
dist)
--builddir=DIR The directory where Cabal puts generated build files (default
dist)
```

I'm unsure if `--builddir` is even a valid option for new-build, but it seems to be according to the docs.

**Comment by hvr** [comment]
It is definitely valid for `cabal new-build`!

But it appears it doesn't work properly w/ `new-install`

cc @typedrat

**Comment by typedrat** [comment]
Huh.

**Comment by typedrat** [comment]
It handles things the same way as new-build, so I can't see why it wouldn't work.

**Comment by martijnbastiaan** [comment]
Are you able to reproduce it?

**Comment by typedrat** [comment]
I can, I just don't see how it's possible.

**Comment by typedrat** [comment]
There's no difference in how the input filtering works other than the addition of a few more options that don't include a `--builddir`, and that's about the limit of my understanding of the way Cabal does option flags.

**Comment by fgaz** [comment]
Oops, linked the wrong pr
