### ISSUE TITLE
download user guide as PDF or epub

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5557]
I would like to read the user guide as a PDF or epub, but there is no download link for this. Apparently https://docs.readthedocs.io/en/latest/features.html#pdf-generation provide this service, and it is an addon to sphinx, could you please link me to where the PDF is?

**Comment by hvr** [comment]
For epub, try  https://readthedocs.org/projects/cabal/downloads/epub/latest/

**Comment by fommil** [comment]
fantastic! Would you like me to leave this ticket open or should I close it now that I have the epub (and from there, a PDF).

**Comment by hvr** [comment]
I'd like to keep this open for a bit, as I'd like to investigate a bit more if we could also provide PDFs (I probably disabled their generation due to some issues)

**Comment by fommil** [comment]
@hvr any joy? I suggest we just close this unless the answer was obvious, I had reasonable success converting the epub to PDF :smile: (some newlines didn't convert properly, but that's my convertor's fault)

**Comment by hvr** [comment]
I tried to enable it, but it fails w/ errors I don't have enough willpower to fix right now: https://readthedocs.org/projects/cabal/builds/7822097/

**Comment by fommil** [comment]
Let's close as "not important enough"...
