### ISSUE TITLE
Cabal build-tool-depends doesn't work

### ISSUE THREAD

**Issue by domenkozar** [haskell/cabal#5560]
See the following diff: https://github.com/sol/markdown-unlit/pull/13/files

Which results into:

```
$ cd example && cabal install --only-dependencies --enable-tests && cabal configure --enable-tests && cabal build && cabal test
Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
Resolving dependencies...
Configuring nifty-library-0.0.0...
Preprocessing test suite 'readme' for nifty-library-0.0.0..
Building test suite 'readme' for nifty-library-0.0.0..
ghc: could not execute: markdown-unlit
```

I thought maybe there was a bug in Cabal 2.0, but it also fails with 2.2: https://travis-ci.org/nikita-volkov/hasql/jobs/423628586

**Comment by hvr** [comment]
Due to technical limitations of old-build, `build-tool-depends` only works w/ the nix-style `new-*` commands

**Comment by domenkozar** [comment]
Thanks @hvr :)

>  It is fine for the package to be the current one, in which case this is termed an internal, rather than external executable dependency.

I don't understand this sentence, what does it mean to be "current one"?

**Comment by domenkozar** [comment]
Ah, does it mean any target defined in current cabal file?

**Comment by domenkozar** [comment]
https://github.com/haskell/cabal/pull/5561
