### ISSUE TITLE
`import` in `if`

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#5563]
It'd be useful to be able to place an `import` statement inside of an `if` to factor out repetitive logic.

e.g. in the common idiom of

```
if !flag(test-whatever)
  buildable: False
else
  ...
```

**Comment by phadej** [comment]
You should be able to put conditional into common stanza. And also import common stanzas into other ones.

**Comment by ekmett** [comment]
Putting the conditional into a common stanza doesn't work for this idiom where the test is particular to the test suite in question.

**Comment by hvr** [comment]
Fwiw, this is strongly correlated with #5564 regarding the  underlying technical limitation

**Comment by ekmett** [comment]
I've started using common blocks and imports rather than build-depends so I only have to state my version ranges once in some otherwise massive cabal configurations.

e.g.

```
common bifunctors
  build-depends: bifunctors >= 5 && < 6

common bytestring
  build-depends: bytestring ^>= 0.10.8
...
library lsp
  import: aeson, base, bytestring, data-default, filepath, hashable, lens,
          lens-aeson, template-haskell, text, unordered-containers, uri-encode
  hs-source-dirs: src/lsp
```

but this breaks with the idiom of doing

```
test-suite test-tasty
  ...
  if !flag(test-tasty)
    buildable: False
  else
    build-depends: ...
```

I currently bury my dependencies down under the `if` to avoid incurring them unnecessarily when that particular test target isn't being built. (Is this still needed these days?) So, I currently repeat my version bounds, messily, in my test suites.

**Comment by phadej** [comment]
@ekmett I see.

Would https://github.com/haskell/cabal/pull/5566 work for you? There we still have a limitation that `import: common` should be on top, but it can be on top of conditional section (see added test-file in the PR).

**Comment by ekmett** [comment]
That'd probably work for me.

**Comment by phadej** [comment]
This is possible with `cabal-version: 3.0`
