### ISSUE TITLE
import statements have to be the first thing in a stanza

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#5564]
This doesn't appear to be documented anywhere, and you don't get particularly helpful error messages when you violate this invariant.

**Comment by hvr** [comment]
@phadej re docs; can we consider `import` morally a `buildinfo` field? if so we should document it as a field there in the cabal docs (and reference that from the `common` stanza description); and document this limitation there

**Comment by ulysses4ever** [comment]
3752c3e5edc fixed this (I think)
https://github.com/haskell/cabal/blame/3752c3e5edc3c19b7262cdb0b70f4e0539b46362/Cabal/doc/cabal-package.rst#L2610
Close?

**Comment by Mikolaj** [comment]
I think so. Please let us know if anything of that is, in fact, not fixed.
