### ISSUE TITLE
Add ability to suppress `extra-src-files` relative path warning

### ISSUE THREAD

**Issue by chshersh** [haskell/cabal#5581]
Currently structure of my project looks very similar to the following one:

```
haskell/
frontend/
mobile/
proto/
```

The directory `proto` contains Protocol Buffers description of messages. To keep track of those files in my project I put those files under `extra-source-files` field in the `haskell/my-project.cabal` file. But because of that I see a lot of warnings like this one:

```haskell
Warning: 'extra-src-files: ../proto/common.proto' is a relative path
outside of the source tree. This will not work when generating a tarball with
'sdist'.
```

Since I'm not going to publish project to Hackage, I would like to suppress this warning and reduce noise in the output. Thanks!

**Comment by hvr** [comment]
Relatedly, I've got a spec draft bitrotting in my INBOX describing "cabal profiles" (name loosely inspired by the concept of MPEG profiles) which you can use to declare the level of strictness your package description needs to meet (depending on whether you intend to distribute the package to Hackage which has fairly strict portability & policy requirements, or whether this is an inhouse package which only needs to be portable across Unix environments etc), and which would affect the warnings emitted by cabal & `cabal check`, as well as serve as a safe-guard against accidentally publishing a package to Hackage.

**Comment by ffaf1** [comment]
With #9442 you can now do it.
