### ISSUE TITLE
Implement a 'v2-reconfigure' command

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#5591]
For old-build we have a useful `reconfigure` command (originally implemented by @ttuegel), which is like `configure`, but instead of fully overwriting the old settings file, it `mappend`s the new flags on top of the old ones and records that. I think it'd be useful to have this for `v2-build` as well.

/cc @bugthunk

**Comment by emilypi** [comment]
I would like to take this on if possible.
