### ISSUE TITLE
new-run doesn't suppress its own stdout when being invoked as part of a pipe

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#5595]
Invoking `cabal new-run target -- something > data` is kinda broken, because I get cabal information messages at the front.

**Comment by phadej** [comment]
@hasufell, have you tried

`cabal new-run -v0 target -- something > data`

**Comment by hasufell** [comment]
Yes, didn't change anything

**Comment by typedrat** [comment]
Honestly, I think that some of that information should be going to stderr instead.

**Comment by ulysses4ever** [comment]
Should this be closed as superseded by #7790?
