### ISSUE TITLE
cabal new-install attempts to dump non-existent package db

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#5597]
@AndreasPK has noticed that `cabal new-install cabal-install` attempts to run `ghc-pkg dump` on a non-existent `~/.cabal/store/ghc-8.4.3/package.db`.

Running `cabal new-build` on a random package and then trying again creates the missing package database, allowing `new-install` to proceed.

**Comment by phadej** [comment]
Duplicate of https://github.com/haskell/cabal/issues/5516

**Comment by typedrat** [comment]
Yup, @phadej. Closing.
