### ISSUE TITLE
new-configure confused with contents of aeson package

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#5599]
```
$ cabal get aeson-1.4.1.0
$ cd aeson-1.4.1.0
$ cabal new-configure
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: aeson-1.4.1.0 (user goal)
[__1] trying: base-4.11.1.0/installed-4.1... (dependency of aeson)
[__2] trying: aeson-benchmarks-0 (user goal)
[__3] next goal: json-builder (dependency of aeson-benchmarks)
[__3] rejecting: json-builder-0.3, json-builder-0.2.5, json-builder-0.2.4,
json-builder-0.2.3, json-builder-0.2.2, json-builder-0.2.1,
json-builder-0.2.0, json-builder-0.1.1, json-builder-0.1.0,
json-builder-0.0.1, json-builder-0.0 (conflict:
base==4.11.1.0/installed-4.1..., json-builder => base>=4 && <4.11)
[__3] fail (backjumping, conflict set: aeson-benchmarks, base, json-builder)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: aeson, base, json-builder,
aeson-benchmarks
```

The last command fails because the current directory contains multiple .cabal files, and one of them is incompatible with my current compiler (GHC 8.4). One workaround I found is to create a cabal.project file that references aeson.cabal explicitly and ignores the other cabal files. I also didn't see an option to specify a single package to be built on the commandline (something like `cabal new-configure --only-this=aeson.cabal`

**Comment by typedrat** [comment]
Just to clarify, there is not another Cabal file _in the same directory_, it's deeper into the structure. I'm not sure if a `--only-this` flag is really the right way to go, but there should be a solution for this issue.

**Comment by wereHamster** [comment]
Yes, sorry. There are two subdirectories (examples, benchmarks) that have a .cabal file each.

**Comment by jneira** [comment]
A workaround could be create a `cabal.project` file in the project root to override the default `packages` option:
```
packages: *.cabal
```

**Comment by wereHamster** [comment]
Why does the default include a single level of subdirectories? What's the idea behind it?

**Comment by jneira** [comment]
Mmm, well, i guess that is the desired behaviour in *most* cases (when all subpackages work with the same versions of cabal/ghc/deps bounds; that *should* be the normal case, right?)

**Comment by jneira** [comment]
You can specify the goal when executing `new-build` (f.e. `cabal new-build aeson`) but `new-configure` is about all subpackages, it accepts the goal (f.e. `cabal new-configure aeson` does not throw an error) but it tries to configure the entire project anyway (cause the goal is to create a `cabal.project.local`!).

**Comment by wereHamster** [comment]
Can I run `new-build` without configuring first?

**Comment by jneira** [comment]
Yeah, in fact `cabal help new-configure` states:
```
It is never necessary to use the 'new-configure' command. It is merely a
convenience in cases where you do not want to specify flags to 'new-build'
(and other commands) every time and yet do not want to alter the
'cabal.project' persistently.
```
But `cabal new-build` will fail cause it tries to build all subpackages by default. so, to sum up:
* Maybe aeson should fix that asymmetry between its subpackages
* As a workaround you could do:
  * `cabal new-build aeson` to build only the lib
  * create the `cabal.project` file as above
  * create a project file with another name (f.e. `cabal-ghc8.4.project`) and use it with `cabal new-build --project-file=cabal-ghc8.4.project`

**Comment by hvr** [comment]
@wereHamster the problem with that approach is that cabal will still need to solve for all .cabal files which match the implicit

```
packages: ./*.cabal
optional-packages: ./*/*.cabal
```

default.

So you'd rather need the sequence:

```
cabal get <pkg>
cd <pkg>-*
echo "packages: ." > cabal.project
cabal new-build
```

**Comment by jneira** [comment]
> I know the name of the package, so I can invoke `new-build` with the package name as argument.
> 
> ```
> cabal get <pkg>
> cd <pkg>-*
> cabal new-build <pkg>
> ```

well, it works for aeson (and for most packages) but not always the main cabal file matches the name of the package (f.e. `dhall-haskell` has a `dhall.cabal` in the root dir)

**Comment by jneira** [comment]
@hvr mmm, yeah, you are right, that option does not work: i've tested it deleting `cabal.project` but no `new-dist` and it worked for me, sorry for the confusion  :worried:

**Comment by wereHamster** [comment]
When cabal builds dependencies, it follows similar steps, right? Does it then implicitly generate a "packages: ." project file?

**Comment by hvr** [comment]
No, building library or build-tool dependencies is significantly different from the `cabal get` + `cabal new-build` codepaths; there's no implicit `cabal.project` involved.

**Comment by wereHamster** [comment]
Is there a way to emulate the codepath that cabal uses during installation of a dependency?

**Comment by jneira** [comment]
You can examine the internal calls to build dependencies with `cabal new-build -v3`. They are self calls to `cabal configure` and `cabal build` (the old ones!) with a lot of custom options computed on-the-fly to make it works within the `new-build` store. So there is not a easy way to reproduce it (if even it is possible!).

Doesn't [the steps involving creating a `cabal.project`](https://github.com/haskell/cabal/issues/5599#issuecomment-426191554) fit your needs?
