### ISSUE TITLE
we still have poor error messages for mismatched case for package names (in october 2018 / cabal 2.4)

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#5601]
as far as I know, on the hackage side we dont allow new package names to use uppercase ascii, but that aside, cabal-install could stand much better error messages for this class of typoes

an example from today: 
```
$ cabal v2-install earley megaparsec
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] unknown package: earley (user goal)
[__0] fail (backjumping, conflict set: earley)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: earley

```

i had to google to notice that the hackage package name has its first letter capitalized `Earley`.

I think our error messages when we can't find any package could be better... 
This does get tricky for off hackage packages, but at least in the context of hackage we can assume ASCII only .. 

the error message could be an analogue of the "`hatt` is an unbound/wrongly typed variable, perhaps you meant `hott`?" style error diagnostic many language implementations provide

cc @hvr thoughts?

**Comment by hvr** [comment]
> on the hackage side we dont allow new package names to use uppercase ascii

that's not fully accurate; we merely disallow non-maintainers to case-squat popular packages they don't own for security reasons (like e.g. occurred with `Cassava` vs `cassava`), but we intentionally allow maintainers to change the case of their own packages, which we consider a legitimate use-case.

**Comment by hvr** [comment]
PR #5635 should improve things (again)
