### ISSUE TITLE
new-sdist fails with vcs packages

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#5612]
```
$ cabal new-sdist some-vcs-package
cabal: The impossible happened: a local package isn't local
```
edit: here's the callstack:
```
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/CmdSdist.hs:222:14 in main:Distribution.Client.CmdSdist
```

**Comment by typedrat** [comment]
You shouldn't be able to sdist VCS packages at all, this is really just a dup of #5586 since that's what makes it possible for this to even be stated.

**Comment by 23Skidoo** [comment]
Closing in favour of #5586, please reopen if disagree.
