### ISSUE TITLE
Static new-build fails as Template Haskell seems to force -dynamic-too with GHC v8.4.3 on Arch Linux

### ISSUE THREAD

**Issue by moll** [haskell/cabal#5615]
Hey,

I'm having trouble compiling a simple exe that uses Docopt (https://github.com/docopt/docopt.hs), which in turn depends on Template Haskell. Long log short (pasted below), `new-build --enable-profiling` seems to invoke `ghc` with `-dynamic-too`, and I'm guessing it's failing to find any profile-enabled dynamic libraries. I'm using GHC on Arch Linux and that only provides profiling libraries for base et alii in static versions. Removing Docopt.hs (and thereby TH), `new-build --enable-profiling` seems to compile fine. I've attemped to jam in every static-related option (`--disable-executable-dynamic --disable-shared --disable-library-vanilla --enable-static`) in hopes it might disable `-dynamic-too`, but no luck. I assume this part includes it: https://github.com/haskell/cabal/blob/a6415a8f303ea9c2713ccc6a07a3c8d3397f6e1b/Cabal/Distribution/Simple/GHC.hs#L604-L607

Any magical incantation I could do to get profiling working here?

Thanks!

```
Building library for th-lift-0.7.11..
creating dist/build
/usr/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -idist/build/global-autogen -Idist/build/autogen -Idist/build/global-autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-unit-id th-lift-0.7.11-c7768014bc8d0ec126010c8e28f2108b3d36ae3bb19649dcbf7a7bcfed62cbdd -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db /home/user/.cabal/store/ghc-8.4.3/package.db -package-db dist/package.conf.inplace -package-id base-4.11.1.0 -package-id ghc-prim-0.5.2.0 -package-id th-abstraction-0.2.6.0-8bhBYrrqrAJFCd9hjMrFb4 -package-id template-haskell-2.13.0.0 -XHaskell98 -XCPP -XTemplateHaskell -XMagicHash -XTypeSynonymInstances -XFlexibleInstances Language.Haskell.TH.Lift -Wall -hide-all-packages
[1 of 1] Compiling Language.Haskell.TH.Lift ( src/Language/Haskell/TH/Lift.hs, dist/build/Language/Haskell/TH/Lift.o )

src/Language/Haskell/TH/Lift.hs:42:1: error:
    Could not find module ‘Language.Haskell.TH.Datatype’
    There are files missing in the ‘th-abstraction-0.2.6.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
42 | import Language.Haskell.TH.Datatype
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/ProjectOrchestration.hs:917:8 in main:Distribution.Client.ProjectOrchestration
```

**Comment by 23Skidoo** [comment]
Looks like the store got borked somehow, nuking it may help.
