### ISSUE TITLE
cabal new-test should show the test output as it comes

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/cabal#5617]
`cabal new-build` is great but there is a major issue with `cabal new-test` because of which its almost unusable for me. I have non-trivial, decent amount of tests in my packages. When I run cabal new-test it holds up all the output of tests and shows it only after it finishes. This takes too long, and is very annoying interactively, because of which I always use `stack test` instead. Even bigger issue is the CI tests, I cannot use cabal in my CI tests because the CI fails when it does not see any output in 10 minutes. Therefore, I had to disable the cabal tests and keep only the stack tests.

I am not sure if there is an issue already on this, I could not find one on a quick search. I think this should be a high priority issue to make new-test usable for non-trivial testing.

**Comment by harpocrates** [comment]
@harendra-kumar  Does `--test-show-details=streaming` (implemented when #4766 was closed) work for you? I think it has the behaviour you expect.

**Comment by harendra-kumar** [comment]
Yes it works as I expected, thanks @harpocrates! Unfortunately, I have not been able to adopt the new version of cabal which has this feature because of frequent occurrence of #5518.
