### ISSUE TITLE
Relax cabal-install constraint, allow network-2.8.*

### ISSUE THREAD

**Issue by DanBurton** [haskell/cabal#5639]
https://github.com/haskell/cabal/blob/738a51148217885f797ea56af773b945469286b9/cabal-install/cabal-install.cabal.pp#L37

Can `cabal-install-2.4.0.0` be revised to allow building against `network-2.8.*`?

See also the `network` changelog: http://hackage.haskell.org/package/network-2.8.0.0/changelog

**Comment by 23Skidoo** [comment]
It probably can, I'll look into it.

**Comment by juhp** [comment]
I checked and cabal-2.4.0.0 builds fine with network-2.8.0.0.

(`stack --resolver nightly build cryptohash-sha256 ed25519 hackage-security resolv network-2.8.0.0 cabal-install`; requires "allow: newer")

**Comment by juhp** [comment]
https://github.com/commercialhaskell/stackage/commit/7b8d7287179cd4934c2daa7a6f030112ab97b669
