### ISSUE TITLE
Should 'cabal install' do 'cabal update' when the index doesn't exist?

### ISSUE THREAD

**Issue by neongreen** [haskell/cabal#5640]
After a fresh installation of `cabal-install`:

```
$ cabal new-install dhall dhall-json
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies: [...]
```

It seems that there should be no harm in automatically doing `cabal new-update` for the user in this case. Am I missing something?

**Comment by hvr** [comment]
Well, the harm is that it's huge download of ~80MiB when you have to fetch the complete index from scratch. If you're on a metered inet connection you might not want your build-tool to start download such an amount without a heads-up.

**Comment by neongreen** [comment]
Alright, that's a sensible tradeoff.
