### ISSUE TITLE
source-repository-package breaks 'cabal new-install all'

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#5643]
Example minimal project: https://github.com/hasufell/example-cabal-project

```sh
$ cabal new-install all
Wrote tarball sdist to
/home/maerwald/git/example-cabal-project/dist-newstyle/sdist/example-cabal-project-0.1.0.0.tar.gz
cabal: The impossible happened: a local package isn't local
```

And `cabal new-install` on the contrary does **nothing**.

**Comment by fgaz** [comment]
Another dup of #5586?

**Comment by hasufell** [comment]
I don't think it's a dup, `new-install` is *completely* broken, it doesn't install those dependencies either.

**Comment by hvr** [comment]
@hasufell but do you expect new-install to treat the source-repo deps as if they were local packages and thus their executables to be installed by `new-install`? or should they rather be treated as dependencies (and thus their executables not be installed)?

**Comment by hasufell** [comment]
Imo, those are dependencies.

**Comment by hvr** [comment]
Another way to trigger the same exception:

1. `cabal.project` file with only

```
packages: http://hackage.haskell.org/package/uhttpc-0.1.1.0/uhttpc-0.1.1.0.tar.gz
allow-newer: uhttpc:*
```

2. 

```
$ cabal new-install uhttpc -v
Downloading
http://hackage.haskell.org/package/uhttpc-0.1.1.0/uhttpc-0.1.1.0.tar.gz
Reading available packages of hackage.haskell.org...
Using most recent state specified from most recent cabal update
index-state(hackage.haskell.org) = 2018-11-20T16:17:34Z
Resolving dependencies...
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/CmdSdist.hs:222:14 in main:Distribution.Client.CmdSdist
cabal: The impossible happened: a local package isn't local
```
