### ISSUE TITLE
``cabal init`` doesn't allow specifying an alternative location for GHC executable

### ISSUE THREAD

**Issue by kozross** [haskell/cabal#5654]
For many invocations of ``cabal``, I can pass a ``-w`` argument to specify where GHC can be found, which is very useful if you have local GHCs set up in your home directory. However, ``cabal init`` doesn't allow this, instead opting to fail and complain about a missing GHC. Would it be possible to have ``cabal init`` accept a ``-w`` flag too?

**Comment by m-renaud** [comment]
+1. I just ran into this issue as well when taking a look at the end to end process to create a new project using `cabal-install` and a specific GHC version, you can see the steps I took [here](https://www.reddit.com/r/haskell/comments/9tpfo2/my_experience_upgrading_ghc_build_tools_and_dev/).

At the bottom of the post I have a list of some changes that would really improve the experience, having `cabal init` accept `-w` is one of them. From what I can tell this could be as simple as having `init` create (or update) the `cabal.project.local` file to contain a `with-compiler` directive that the rest of the init process could use.

**Comment by hvr** [comment]
I've implemented this the simplest way I could think of in the PR at #5658

**Comment by 23Skidoo** [comment]
Related: #4936, #4956.
