### ISSUE TITLE
cabal init doesn't generate a template compatible with newer cabal version (>= 2.2/2.4)

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#5655]
also where is the current documentation / or reference templates for different cabal versions?

the best i could find is https://www.haskell.org/cabal/users-guide/cabal-projectindex.html#cap-package.cabal%20fields

**Comment by hvr** [comment]
1. Have you seen https://github.com/haskell/cabal/pull/5567  ? It'll be in the next point release of 2.4

2. Have you seen the `master`-branch of the docs at  https://cabal.readthedocs.io/en/latest/file-format-changelog.html ?

**Comment by cartazio** [comment]
these look great! that basically resolves it for me I think
