### ISSUE TITLE
Unhelpful error message if `import` is not first stanza

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal#5664]
# Summary

If the `import` directive is not the first stanza in a section (library, executable, etc.) the error message you get is: `Unknown field: "import"` and dependencies fail to resolve.

# Broken Example

```
cabal-version:       2.4
name:                broken
version:             0.1.0.0

common deps
  build-depends: base >=4.9 && < 4.12

executable broken
  main-is: Main.hs
  import: deps
  default-language: Haskell2010
```

Error:

```
$ cabal v2-build
Resolving dependencies...
Build profile: -w ghc-8.0.2 -O1
In order, the following will be built (use -v for more details):
 - broken-0.1.0.0 (exe:broken) (first run)
Warning: broken.cabal:10:3: Unknown field: "import"
Configuring executable 'broken' for broken-0.1.0.0..
Preprocessing executable 'broken' for broken-0.1.0.0..
Building executable 'broken' for broken-0.1.0.0..
[1 of 1] Compiling Main   ( Main.hs, /home/mrenaud/exp/broken/dist-newstyle/build/x86_64-linux/ghc-8.0.2/broken-0.1.0.0/x/broken/build/broken/broken-tmp/Main.o )

Main.hs:1:8: error:
    Failed to load interface for ‘Prelude’
    It is a member of the hidden package ‘base-4.9.1.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    it is a hidden module in the package ‘hackage-security-0.5.3.0’
    Use -v to see a list of the files searched for.
```

Moving the `import` to the first line under `executable broken` causes it to build successfully.

**Comment by phadej** [comment]
Will be fixed by https://github.com/haskell/cabal/pull/5566

The error will be `Unknown field: import. Common stanza imports should be at the top of the enclosing section`

**Comment by cartazio** [comment]
@phadej  did you also update the documentation? https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=common#pkg-section-common-common doesn't mention it hence i filed a duplicate https://github.com/haskell/cabal/issues/5912

**Comment by phadej** [comment]
#5566 was merged
