### ISSUE TITLE
cabal new-update fails to download the package list

### ISSUE THREAD

**Issue by adithyaov** [haskell/cabal#5669]
This is not a network problem. I've thoroughly checked it. I am able to ping `hackage.haskell.org` and download `http://hackage.haskell.org/01-index.tar.gz` via `wget`. Please help me with this. Thank you.

![cabalupdateerror](https://user-images.githubusercontent.com/17845944/48090394-c668de80-e22c-11e8-9c67-c5588b7df0e8.PNG)
![capture2](https://user-images.githubusercontent.com/17845944/48090397-c7017500-e22c-11e8-9a6a-5ec53b97ba8f.PNG)
![capture](https://user-images.githubusercontent.com/17845944/48090396-c668de80-e22c-11e8-9f8b-0536164e67f6.PNG)

**Comment by 23Skidoo** [comment]
Apparently it tries to download `http://hackage.haskell.org/01-index.tar.gz` with `curl` and that fails. What happens if you try to do that manually?

**Comment by gbaz** [comment]
Also note that if wget works and curl doesn't, you can always use the `--http-transport` flag to switch to using wget.

**Comment by adithyaov** [comment]
Thank you for the reply. It seems like @hvr 's solution works fine for me. Is there a reason why curl fails in this case? curl works fine (checked it) so its not a problem with curl.

I'm closing the issue, thank you for the help!

**Comment by 23Skidoo** [comment]
You can see the exact command line cabal-install uses to invoke `curl` if you run `cabal new-update` with `-v3`. If it works when you run it the same way from console, then either something is wrong with your version of `curl`, or with the `cabal-install` code.
