### ISSUE TITLE
'cabal new-clean' should also delete the environment file

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#5689]
How to reproduce:

```
# In some project's directory
$ cabal new-build
$ cabal new-clean
$ ls .ghc.environment.*
.ghc.environment.x86_64-linux-8.4.4 # Expected: zero hits
```

I'd prefer `cabal new-clean` to imply `rm -rf .ghc.environment.*` in the project's root directory, though it might be argued that it only should delete the environment file for the currently configured compiler.

/cc @hvr @typedrat

**Comment by fommil** [comment]
dupe of ##5587 ?

**Comment by 23Skidoo** [comment]
Closing in favour of #5587.
