### ISSUE TITLE
options for source-repository-package cause rebuilds

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5691]
If I add a source package AND some custom options, e.g.

```
source-repository-package
    type: git
    location: https://github.com/symbiont-io/text-format.git
    tag: 142dc88bcd94bf2780f7c3f11095f4b529e80449

package text-format
  ghc-options: -Wno-dodgy-imports -Wno-unused-imports

```

then swapping between `cabal new-build all`  and `cabal new-build all -O0` will trigger a full rebuild even when it's already been built and cached.

Arguably, we shouldn't be doing this as developers... we are in control of the source code, so we should change the `ghc-options` in that fork, right? I agree with that.

BUT... what if we want to apply global options, such as

```
package *
  optimization: 2
```

this also causes the same problems and any change to the configuration causes a recompile.

**Comment by fommil** [comment]
this issue is bogus. I'm seeing it without any special flags for source dependencies.

**Comment by fommil** [comment]
I am unsure if this is the minimisation... I noticed something like this when I ran, from clean, and without any package options like in the ticket description:

```
cabal new-build all -O0
cabal new-build all
cabal new-build all -O0
```

but once I did those three builds, it stabilised. Perhaps if the first build has `-O0` then that confuses things... I'll try to minimise.

**Comment by phadej** [comment]
Changing optimisation level **should** cause recompile. Why you think it shouldn't?

**Comment by fommil** [comment]
@phadej yes, I mean after they've already been compiled.

**Comment by fommil** [comment]
Dumping notes as I experiment:

I can confirm what **doesn't** trigger it... on a simple project like https://github.com/symbiont-io/jaeger-flamegraph that doesn't have any source dependencies, if I add a `package *` glob then caching seems to work fine and there are no unexpected rebuilds.

**Comment by fommil** [comment]
ok, this ticket is completely bogus and the rebuilds I'm seeing must be caused by something else. I added the source repo from the report to a small project, and some project specific overrides to it build, and then did the build cycles, and the third one was `Up to date`... I'll close for now and come back when I know what I'm talking about :blush:
