### ISSUE TITLE
new-clean should not delete dist-newstyle/src

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5699]
I also tried with `-s`

Unfortunately deleting the `src` dir means that source dependencies (i.e. git repos) are also deleted. Which is unfortunate.

It would be highly desirable not to delete these repos. Perhaps if the repos were stored in a global location this would not be a problem?

**Comment by typedrat** [comment]
`new-clean` was written before `src` existed. It'd be a trivial patch to fix it.
