### ISSUE TITLE
create compiler frameworks for new compilers

### ISSUE THREAD

**Issue by bos** [haskell/cabal#57]
(Imported from [Trac #50](http://hackage.haskell.org/trac/hackage/ticket/50), reported by @syntaxpolice on 2006-01-20)

Email from John Meacham below.  Another possibility is to make it rather like a hook.

I'd rather work on making a general compiler framework for it so that
jhc can just drop a file describing its interface in
/usr/share/lib/cabal/compilers/jhc.cabal-compiler  or something and
cabal will automatically be able to use it. Ideally, one would not have
to upgrade their cabal just because they install (or write) a new
haskell compiler. I think all compilers conform to one of

hmake-like: ghc --make, jhc, nhc + hmake
interpreter-like: hugs
gcc-like: ghc, nhc98

so a compiler declaration file would not have to be much more
complicated than a string telling it how to invoke the compiler and a
mapping of various extensions/cabal options -&gt; compiler flags.

I'd also like to do something like this for preprocessors, which would
be a much simpler project so will probably do first.

**Comment by jsl** [comment]
Doesn't seem like there is activity on this since 2006. I propose closing, please re-open a new issue if this is still desired.
