### ISSUE TITLE
Allow installation of distro packages

### ISSUE THREAD

**Issue by bos** [haskell/cabal#571]
(Imported from [Trac #578](http://hackage.haskell.org/trac/hackage/ticket/578), reported by @bos on 2009-08-28)

It would be very nice indeed if <tt>cabal-install</tt> could be taught how to install a distro's version of a package. This could amount to simply asking a shell script if the package is available and can be installed, before proceeding with the usual Cabal installation machinery.

**Comment by mietek** [comment]
[Halcyon](https://halcyon.sh) supports declaring native OS packages to be installed for use at build-time with the [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages) option.

Similarly, you can use [`HALCYON_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_extra_os_packages) to declare native OS packages for use at run-time.

See [Haskell Language](https://halcyon.sh/examples/#haskell-language) for an example of declaring _libicu_ as a dependency.
