### ISSUE TITLE
Support leading and trailing commas in `exposed-modules` (and similar)

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal#5713]
## Overview

So, the cabal file format is kinda inconsistent regarding when commas are required and where they're optional, and the places where they are optional don't always allow leading or trailing commas (like `build-depends` supports).

## Example

For example, the following fails to parse, giving an error about the trailing comma after `B`.

```
library
  exposed-modules:
    A,
    B,
  build-depends:
    ...
```

This also fails for `other-modules`, `default-extensions`, and `other-extensions`.

## Solution

The grammar and parser should support leading and trailing commas for all repeated fields which support optional commas.

## (Potentially) Controversial Opinion

The grammar **should require commas for all module fields** (and probably most repeated fields, except for maybe GHC options?). This makes the grammar much more consistent, although would be a backwards incompatible change (but VERY easy to automate updating).

It's really strange that some repeated fields are comma separated and others are whitespace separated, I can't think of any other file format that has this inconsistency.

**Comment by hvr** [comment]
If you `cabal init`, you might notice something:

```
$ cabal init
Please choose version of the Cabal specification to use:
 * 1) 1.10   (legacy)
   2) 2.0    (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2    (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4    (+ support for '**' globbing)
```

Notice the mention of  "`redundant commas`"? ;-)

**Comment by m-renaud** [comment]
@hvr I should have mentioned in the original post that this is for Cabal spec 2.4, here's the .cabal file:

```
cabal-version:       2.4
name:                myapp
version:             0.1.0.0

library
  exposed-modules:
    A,
  build-depends:       base >=4.12 && <4.13
  default-language:    Haskell2010
```

Which results in:

```
$ cabal v2-build
CabalFileParseError "./myapp.cabal" [PError (Position 7 7) "\nunexpected end of input\nexpecting white space or \"\\\"\"\n\nA,\n"] (Just (mkVersion [2,4])) []
```

Or with the new fancy error messages:

```
Errors encountered when parsing cabal file ./myapp.cabal:

myapp.cabal:7:7: 
unexpected end of input
expecting white space or "\""

    6 |   exposed-modules:
    7 |     A,
    8 |   build-depends:       base >=4.12 && <4.13
```

**Comment by phadej** [comment]
:-1:. The `exposed-modules` unfortunately is **optional** commas field now. I.e. writing

```
  exposed-modules:
    Data.TreeDiff,
    Data.TreeDiff.List
    Data.TreeDiff.Tree,
    Data.TreeDiff.Expr
    Data.TreeDiff.Class,
    Data.TreeDiff.Pretty
    Data.TreeDiff.Parser,
    Data.TreeDiff.Golden
    Data.TreeDiff.QuickCheck
```

is valid now. Allowing comma at front (xor end) will make parser to bizarre. 

Most people **omit** all commas.

When I introduced *redundant commas* I didn't touch optional comma fields. Two options:
- these fields should be simply commaless
- or commas could still be optional; but if commas are present, they should be between every element (and then redundant leading xor trailing) is fine.

**Comment by phadej** [comment]
Edit: `tested-with` fields is also optional commas. That's crazy. i.e. writing:

```
tested-with: GHC==7.8.4 GHC==7.10.3 GHC==8.0.2 GHC==8.2.2 GHC==8.4.3 GHC==8.6.1
```

is ok.

Or 

```
tested-with: GHC==7.8.4 GHC==7.10.3, GHC==8.0.2 GHC==8.2.2 GHC==8.4.3 GHC==8.6.1
```

(`cabal-1.24` accepts these too)

**Comment by phadej** [comment]
https://github.com/haskell/cabal/blob/b8b3b4142762686b0eec58bd2bf9645c9ebca559/Cabal/Distribution/PackageDescription/FieldGrammar.hs#L381-L400

- `ld-options` cannot have commas
- `pkgconfig-depends` needs commas
- `frameworks` etc are like `tested-with` or `exposed-modules` above.

**Comment by phadej** [comment]
One more comment, `reexported-modules` requires commas (its list-element syntax contains spaces, `Foo as Bar` IIRC)

**Comment by m-renaud** [comment]
That's for all the info @phadej! What's the rationale for even having "optional" commas and not just making them required for all "list like fields"? The only type of firld that makes sense to **not** have commas are flag field (like ld-options and ghc-options, etc). This becomes even more confusing when some "module fields" require them (like you mention above about `reexported-modules`) but others don't.

My vote would very strongly be: make commas required everywhere, unless there's a very good argument against for a goddess field.

**Comment by phadej** [comment]
for some lists like e.g. `default-extensions` commas would be simply noise;
also some fields **disallow** commas, e.g. `ld-options` (linkers like commas etc), so commas for all list-like fields is not feasible.

About `exposed-modules` in particular; I don't remember seeing anyone using commas in that field. So starting to require commas will make people very angry, and not willing to update to newer cabal spec versions.

If anything, I'd reduce the fields with required commas to bare minimum (i.e. no commas everywhere), not the other way around.

**Comment by m-renaud** [comment]
@phadej so I've thought about this some more, and I think I agree with you. I guess what I really want is consistency, and I compared some cabal files using different styles and think that the "no commas anywhere" is the cleanest.

Would it be possible to support "newline separated entries" for fields that are currently "commas required" such as `build-depends` and others? I find I often have these each on their own line anyways. Then you could have something like:

```
cabal-version: 2.6
name: myapp
version: 0.1.0.0

library
  default-language: Haskell2010
  exposed-modules:
    A
    B
  reexported-modules:
    Foo as F
    Quux as Q
  build-depends:
    base ^>=4.12
    containers ^>= 0.6
```

WDYT?

**Comment by phadej** [comment]
People still write `build-depends: base, containers` for small stuff.

I think this big changes are too big to discuss properly in time for 3.0; My PR OTOH is hopefully not controversial.

**Comment by phadej** [comment]
Amendum: for now pretty printer implementation is cabal spec version independent, @m-renaud last proposal (no commas anywhere) would need change there too. That's not impossible (and probably have to be done at some point), but that's some coding to do too.

**Comment by m-renaud** [comment]
> People still write build-depends: base, containers for small stuff.

Couldn't we do something similar to what we have (after your change) for optional commas? Namely, "commas required" changes too "all entries comma separated" **or** "all entries newline separated". In other words, don't prohibit the current comma separated list, but if one desires they can use newline separation and skip the commas.

> too big to discuss properly in time for 3.0

You're probably right, just thought I'd start the discussion :)

> My PR OTOH is hopefully not controversial.

Agreed!

**Comment by phadej** [comment]
Leading/trailing commas are implemented.

For the controversial part please open new issue. This issue is fixed, the new one might be "wontfix".
