### ISSUE TITLE
RFC: Remove `build-tools`

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5726]
The field is deprecated, it doesn't work.

User can specify
```
build-tools: unzip
```

And that field **does nothing**. I somehow assume that `cabal-install` would check that the tool exists in `$PATH`; but it doesn't even do that.

Therefore, let's remove the field.

---

Note: this would affect only `cabal-version: 3.0` and higher, so nothing existing would break

**Comment by phadej** [comment]
- https://github.com/haskell/cabal/issues/5464 an issue with `build-tools`
- https://github.com/haskell/cabal/issues/4238 confusing issue by me (almost two years old)
- https://github.com/haskell/cabal/issues/5412 (migration to `build-tool-depends`) will be naturally forced as people move to `cabal-version: 3.0` (sooner or later)

**Comment by phadej** [comment]
ping @hvr @Ericson2314

**Comment by hvr** [comment]
I'm sympathetic to making `build-tools` illegal with `cabal-version: 3.0`; at this point I consider `build-tools` merely redundant syntax sugar for `build-tool-depends` anyway.

**Comment by Ericson2314** [comment]
Oh I just saw this. Awesome!!
