### ISSUE TITLE
Remove support for `.zip` format source distributions

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#5735]
`cabal sdist` has had support for generating `.zip`ped source distributions ever since it was added in ae0dee3e99464331bdf3f126a710248d01a60235

```
    --targz                Produce a '.tar.gz' format archive (default and required for uploading to hackage)
    --zip                  Produce a '.zip' format archive
```

The original implementation relied on invoking an external `zip` executable, whereas in the course of the `new-sdist` implementation this the Haskell library `zip-archive` was used (see 8fe7607f5037d78aebf3f30c21472e611659e2c2) thereby gaining an additional dependency.

However, it's not clear to me if this feature is even relevant to anyone anymore; This feature is also rather asymmetric as there's only write support but not read support for `.zip` sdists. I'd argue it'd be more in line w/ the KISS principle to handle this by a simple  `tgz2zip` utility than to bloat `cabal` with trivial convenience concerns which lead to feature creep.

If nobody needs/uses this feature it'd be effectively dead-code and we should eliminate it in the interest of reducing current and future maintenance costs of additional code-paths as well as an additional library dependency.

Concretely, I suggest to 

1. remove the `--zip` feature (and associated codepaths)  from `sdist` & `v2-sdist`,
2. drop the `zip-archive` dependency, and
3. (optionally) if there's actually demand, implement a native Haskell `tar2zip` or `tgz2zip` tool and host its package on Hackage to satisfy the needs of what I believe to be a very small minority target audience :-)

**Comment by 23Skidoo** [comment]
+1. I can see how .zip makes sense for binaries, but for source packages it makes more sense to have a single standard format.

**Comment by phadej** [comment]
:+1:

**Comment by dcoutts** [comment]
Agreed.

**Comment by emilypi** [comment]
Finished as of #5755
