### ISSUE TITLE
Cannot build Cabal from source

### ISSUE THREAD

**Issue by accursoft** [haskell/cabal#5742]
Building Cabal from source fails on #5391.

~~`bootstrap.sh` fails on #5391~~

**Comment by accursoft** [comment]
same for `--user`

**Comment by hvr** [comment]
I couldn't reproduce this; can you provide us with more details? Such which OS or Linux Distro you were on, which GHC version you used for bootstrapping and which version of cabal-install were you trying to bootstrap? Can you provide us with the full build output as a gist.github.com?

**Comment by accursoft** [comment]
Installed ghc 8.2.1 from source on Debian, then attempted to bootstrap latest cabal-install.

https://bitbucket.org/accursoft/haskell-cloud/src.

Output of `bootstrap.sh` is the same as in #5391.

**Comment by hvr** [comment]
@accursoft I strongly suspect that this has nothing to do with `bootstrap.sh`!

I noticed in https://bitbucket.org/accursoft/haskell-cloud/raw/e0d0a677e466ab8cba9086319af61ed04358b581/image/cabal.sh 

```sh
#!/bin/sh -eu

export EXTRA_CONFIGURE_OPTS="--disable-library-for-ghci"
export EXTRA_BUILD_OPTS="-j"

#download latest Cabal from hackage
curl https://hackage.haskell.org`curl https://hackage.haskell.org/package/Cabal | grep -o '/package/Cabal-[0-9.]*/Cabal-[0-9.]*.tar.gz'` | tar xz
cd Cabal-*
#build
ghc Setup -o Setup $EXTRA_BUILD_OPTS
./Setup configure $EXTRA_CONFIGURE_OPTS
./Setup build $EXTRA_BUILD_OPTS
./Setup install
cd ..

#download cabal-install
curl https://hackage.haskell.org`curl https://hackage.haskell.org/package/cabal-install | grep -o '/package/cabal-install-[0-9.]*/cabal-install-[0-9.]*.tar.gz'` | tar xz
cd cabal-install-*

#build
./bootstrap.sh --no-doc --sandbox
#we could use --bindir in EXTRA_CONFIGURE_OPTS, but bootstrap.sh would warn after successful installation
#The 'cabal' executable was not successfully installed into .cabal-sandbox/bin/
mv .cabal-sandbox/bin/cabal /usr/local/bin

#clean up
rm -r /Cabal-* \
      /cabal-install-* \
      ~/.cabal
```


that you compile `Setup.hs` manually via `ghc Setup -o Setup`, instead try to build it with

```
ghc -i Setup.hs -o Setup
```

**Comment by accursoft** [comment]
```
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )

Setup.hs:1:1: error:
    Could not find module `Distribution.Simple'
    It is not a module in the current program, or in any known package.
  |
1 | import Distribution.Simple
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by accursoft** [comment]
`ghc --make Setup` gives the same result as `ghc Setup -o Setup`.

**Comment by hvr** [comment]
@accursoft what does your `ghc-pkg list` output look like?

**Comment by accursoft** [comment]
```
    array-0.5.2.0
    base-4.10.0.0
    binary-0.8.5.1
    bytestring-0.10.8.2
    containers-0.5.10.2
    deepseq-1.4.3.0
    directory-1.3.0.2
    filepath-1.4.1.2
    (ghc-8.2.1)
    ghc-boot-8.2.1
    ghc-boot-th-8.2.1
    ghc-compact-0.1.0.0
    ghc-prim-0.5.1.0
    ghci-8.2.1
    haskeline-0.7.4.0
    hoopl-3.10.2.2
    hpc-0.6.0.3
    integer-gmp-1.0.1.0
    pretty-1.1.3.3
    process-1.6.1.0
    rts-1.0
    template-haskell-2.12.0.0
    terminfo-0.4.1.0
    time-1.8.0.2
    transformers-0.5.2.0
    unix-2.7.2.2
```

**Comment by hvr** [comment]
@accursoft well, you've got a very exotic setup there: 

The original CABAL spec requires compliant compiler implementations to provide a way to compile or run a `Setup.hs` script such as the following

```hs
import Distribution.Simple( defaultMain )
main = defaultMain
```

in other words, it is assumed that the compiler has a version of the `Cabal` library bundled. In your case however, you have a compiler which has no `Cabal` library at all. This is not a standard configuration of GHC, as GHC includes Cabal in its distribution!

In order to build Cabal you need to provide all its dependencies. In your case you're missing a few. But in order to install those you *need* to have `Cabal` already installed! Do you see the problem?

Also note, that GHC 8.2.1 bundles Cabal 2.2, not Cabal 2.4. You might have a better chance with bootstrapping Cabal-2.2

**Comment by accursoft** [comment]
🤔 The intention was to build a minimal docker image. After installing GHC, I'm removing the packaged Cabal, then installing the latest Cabal from Hackage.

Doing all this in the same layer might enable old Cabal to be removed only after new Cabal has been built, but at the cost of re-building GHC every time Cabal is updated.
