### ISSUE TITLE
No clear way to install executables on Windows

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#5748]
It seems that `cabal new-install` is quite insistent on installing executables with symlinks. However, this facility is not available on Windows. Consequently any attempt to use `new-install` on Windows ends with either cabal-install complaining that `symlink-bindir` is not defined or that symlinks aren't supported on Windows.

**Comment by jneira** [comment]
It seems there is a pr about it: https://github.com/haskell/cabal/pull/5684

**Comment by AndreasPK** [comment]
There are now new flogs to allow this however they are off by default.

#5684 seems to have stalled.

Is there a reason against simply making `--install-method=copy` and `--overwrite-policy=always` the default on windows?

**Comment by fgaz** [comment]
@andersk The flags introduced in #5870 can be configured in ~/.cabal/config, but the configuration will not be effective until #5942 is fixed. The windows default is still symlink though; PRs welcome.

There's more discussion about this and a possible `auto` method in #5837 and #5843

**Comment by AndreasPK** [comment]
`--install-method=copy` works now, however cabals default method still fails on windows.

Is there a reason why we can't just default to copy on windows?

**Comment by fgaz** [comment]
@AndreasPK #5837 has dome discussion about that

**Comment by fgaz** [comment]
Fixed in #6519
