### ISSUE TITLE
`new-install --lib` also builds exes

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#5754]
Consider a recent `new-install` session of mine:

```
$ cabal new-install shake --lib
Resolving dependencies...
Build profile: -w ghc-8.6.2 -O1
In order, the following will be built (use -v for more details):
 - shake-0.17.2 (exe:shake) (requires download & build)
 - shake-0.17.2 (lib) (requires download & build)
Downloading  shake-0.17.2
Downloaded   shake-0.17.2
Starting     shake-0.17.2 (lib)
Starting     shake-0.17.2 (exe:shake)
Building     shake-0.17.2 (exe:shake)
Building     shake-0.17.2 (lib)
Installing   shake-0.17.2 (exe:shake)
Completed    shake-0.17.2 (exe:shake)
Installing   shake-0.17.2 (lib)
Completed    shake-0.17.2 (lib)
```

Despite the fact that I explicitly specified `--lib`, `cabal-install` went ahead and built the `shake` executable anyway. It does appear that passing `--lib` had _some_ effect, since the `shake` executable wasn't symlinked. At least, that's as far as I can tell, since checking `~/.cabal/bin` revealed that the `shake-0.17` (older version) executable was still symlinked:

```
~/.cabal/bin
$ ls -alh
total 314M
drwxr-xr-x 3 ryanglscott ryanglscott 4.0K Nov 29 10:01 .
drwxrwxr-x 9 ryanglscott ryanglscott 4.0K Oct 24 19:01 ..
...
lrwxrwxrwx 1 ryanglscott ryanglscott  104 Nov  8 09:30 shake -> ../store/ghc-8.6.2/shake-0.17-4b9036746e783e9f0e4115f44f9db023c08fe7fb0da4e4c9b14259f7d6a403b5/bin/shake
```

Still, I consider the fact that the `shake-0.17.2` executable was _built_ (but not installed) to be rather surprising in the presence of `--lib`, and I would consider that to be wasted CPU cycles (and disk space).

**Comment by phadej** [comment]
Is this related to the fact that we don't have per-component builds? (I.e. we always build the lib and exes of dependencies now?)

**Comment by hvr** [comment]
@phadej that would be the case for the legacy-fallback cases which require to install all default components as a single unit into the store; but that isn't the case for `shake`, as e.g. 

```
$ cabal new-repl --build-d shake --dry
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following would be built (use -v for more details):
 - heaps-0.3.6 (lib:heaps) (requires build)
 - shake-0.17.2 (lib) (requires download & build)
 - fake-package-0 (lib) (first run)
``

shows which only builds & installs the `lib:shake` component, w/o the `exe:shake` component.

**Comment by typedrat** [comment]
That's because `new-install` acts like shake is a local package and thus builds all of it even with `--lib`. It'd be easy enough to fix, though.
