### ISSUE TITLE
Cabal should pass -x to hsc2hs when cross-compiling

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#5764]
Currently, one has to write

```
package lzma
    hsc2hs-options: -x

package memory
    hsc2hs-options: -x
```

and so on, which can be quite tedious. Ideally, cabal should pass `-x` to `hsc2hs` when it detects we are cross-compiling. 

I'd be willing to implement this feature, but I want to make sure it's done "properly" - i.e. we may wish to make a patch which is general enough to work for other preprocessors which may or may not need special options when cross-compiling.

**Comment by 23Skidoo** [comment]
Does

```
package *
    hsc2hs-options: -x
```

work?
