### ISSUE TITLE
cabal new-install doesn't create package.db for current ghc version

### ISSUE THREAD

**Issue by claudeha** [haskell/cabal#5777]
preparation: cabal-install compiled wtih ghc-8.4.4, then installed ghc-8.6.2

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 8.6.2
    $ cabal --version
    cabal-install version 2.4.0.0
    compiled using version 2.4.0.1 of the Cabal library 
    $ cabal new-update
    ...
    $ cabal get wedged
    ...
    $ cd wedged-2

the bug

    $ cabal new-install wedged.cabal 
    Wrote tarball sdist to
    /home/claude/code/local/wedged-2/dist-newstyle/sdist/wedged-2.tar.gz
    cabal: ghc-pkg dump failed: dieVerbatim: user error (cabal:
    '/home/claude/opt/bin/ghc-pkg' exited with an error:
    ghc-pkg: /home/claude/.cabal/store/ghc-8.6.2/package.db:
    getDirectoryContents:openDirStream: does not exist (No such file or directory)
    )

workaround:

    $ mkdir /home/claude/.cabal/store/ghc-8.6.2
    $ ghc-pkg init /home/claude/.cabal/store/ghc-8.6.2/package.db
    $ cabal new-install wedged.cabal 
    ...
    (succeeds)

cabal new-install should probably check that the package db for the current ghc version exists, and if not then it should create the directory and call ghc-pkg init

**Comment by 23Skidoo** [comment]
Does this still happen with `cabal-install-2.4.1.0`?

**Comment by claudeha** [comment]
seems fixed with `cabal-install-2.4.1.0` (after installing a fresh `ghc-8.6.3` to test)
