### ISSUE TITLE
cabal new-install doesn't update symlink to point to new ghc version

### ISSUE THREAD

**Issue by claudeha** [haskell/cabal#5778]
I have:

    $ cabal --version
    cabal-install version 2.4.0.0
    compiled using version 2.4.0.1 of the Cabal library 
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 8.6.2

with

    $ grep symlink ~/.cabal/config 
    symlink-bindir: /home/claude/opt/bin

I just installed my package this morning (Dec 7 2018) and the symlink wasn't updated:

    $ cabal get wedged
    $ cd wedged-2
    $ cabal new-install wedged.cabal
    ...
    Starting     wedged-2 (exe:wedged)
    Building     wedged-2 (exe:wedged)
    Installing   wedged-2 (exe:wedged)
    Completed    wedged-2 (exe:wedged)
    Symlinking wedged
    $ ls -l `which wedged`
    lrwxrwxrwx 1 claude claude 113 Nov  6 04:58 /home/claude/opt/bin/wedged -> ../../.cabal/store/ghc-8.6.1/wedged-2-8a3e474537e490fb91319fd405a357f426a3b7ccba481510b25b7d8442a3a85f/bin/wedged

note the old version (compiled with ghc-8.6.1 a month ago)

the correct location (newly installed) is at

    -rwxr-xr-x 1 claude claude 89342792 Dec  7 05:58 /home/claude/.cabal/store/ghc-8.6.2/wedged-2-704b79238c282cf84753cf924b1a8b19ab44b8f93363017455e95ba3e27b8f59/bin/wedged

shouldn't the link in ~/opt/bin have been updated to point to this location?

**Comment by 23Skidoo** [comment]
Does this still happen with `cabal-install-2.4.1.0`?

**Comment by claudeha** [comment]
no, it emits an error message:

    $ cabal new-install wedged
    ...
    Symlinking 'wedged'
    cabal: Path '/home/claude/opt/bin/wedged' already exists. Use
    --overwrite-policy=always to overwrite.

following the suggestion works nicely:

    $ cabal new-install wedged --overwrite-policy=always
    Resolving dependencies...
    Up to date
    Symlinking 'wedged'
    $ ls -l `which wedged`
    lrwxrwxrwx 1 claude claude 113 Dec 14 14:57 /home/claude/opt/bin/wedged -> ../../.cabal/store/ghc-8.6.3/wedged-2-2dacd5429cbb24b04591b1f835c586211bbaddc21f3abb9f0fcb7b6eb3d33adf/bin/wedged
