### ISSUE TITLE
"unknown package" on cabal build

### ISSUE THREAD

**Issue by razvan-panda** [haskell/cabal#5780]
I am using the 8.2.2 Haskell Distribution for Windows.

> cabal-install version 2.0.0.1
> compiled using version 2.0.1.1 of the Cabal library

When building https://github.com/razvan-panda/Haskell-CodeWars I am getting following error:

> K:\Dropbox\Coding Challenges\Codewars\Haskell>cabal build
> Resolving dependencies...
> Warning: solver failed to find a solution:
> Could not resolve dependencies:
> trying: CodeWars-0.1.0.0 (user goal)
> unknown package: lens (dependency of CodeWars-0.1.0.0)
> fail (backjumping, conflict set: CodeWars, lens)
> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: CodeWars, lens
> Trying configure anyway.
> Configuring CodeWars-0.1.0.0...
> cabal: Encountered missing dependencies:
> lens -any, split -any, text -any

If I build the same project under Linux / NixOS, it builds just fine:

> [nix-shell:~/Projects/CodeWars]$ cabal build
> Resolving dependencies...
> Configuring CodeWars-0.1.0.0...
> Preprocessing library for CodeWars-0.1.0.0..
> Building library for CodeWars-0.1.0.0..
> ignoring (possibly broken) abi-depends field for packages

The cabal-install version is newer though:

> [nix-shell:~/Projects/CodeWars]$ cabal --version
> cabal-install version 2.2.0.0
> compiled using version 2.2.0.1 of the Cabal library

**Comment by razvan-panda** [comment]
The project builds fine with stack on Windows:

> K:\Dropbox\Coding Challenges\Codewars\Haskell>stack init --resolver lts-11.22
> 
> K:\Dropbox\Coding Challenges\Codewars\Haskell>stack build
> CodeWars-0.1.0.0: configure (lib)
> Configuring CodeWars-0.1.0.0...
> CodeWars-0.1.0.0: build (lib)
> Preprocessing library for CodeWars-0.1.0.0..
> Building library for CodeWars-0.1.0.0..
> [1 of 7] Compiling Code0            ( src\Code0.hs, .stack-work\dist\5c8418a7\build\Code0.o )
> [2 of 7] Compiling Code1            ( src\Code1.hs, .stack-work\dist\5c8418a7\build\Code1.o )
> [3 of 7] Compiling Code2            ( src\Code2.hs, .stack-work\dist\5c8418a7\build\Code2.o )
> [4 of 7] Compiling Code3            ( src\Code3.hs, .stack-work\dist\5c8418a7\build\Code3.o )
> [5 of 7] Compiling Code4            ( src\Code4.hs, .stack-work\dist\5c8418a7\build\Code4.o )
> [6 of 7] Compiling Code5            ( src\Code5.hs, .stack-work\dist\5c8418a7\build\Code5.o )
> [7 of 7] Compiling Code6            ( src\Code6.hs, .stack-work\dist\5c8418a7\build\Code6.o )
> 
> CodeWars-0.1.0.0: copy/register
> Installing library in K:\Dropbox\Coding Challenges\Codewars\Haskell\.stack-work\install\b7328101\lib\x86_64-windows-ghc-8.2.2\CodeWars-0.1.0.0-C4kELYcqVRe6s1FqME0K
> Registering library for CodeWars-0.1.0.0..

**Comment by Mistuke** [comment]
did you forget to do a `cabal update`?

**Comment by Mistuke** [comment]
have you tried `cabal new-build` instead, it's solver is a bit more flexible, though not sure why old build isn't seeing `text`.

**Comment by razvan-panda** [comment]
@Mistuke Yes, I tried cabal new-build, see: https://github.com/haskell/cabal/issues/5781

**Comment by razvan-panda** [comment]
I am getting a similar error on NixOS:

> [neo@nixos:~/Projects/Haskell]$ cabal build
> Resolving dependencies...
> Warning: solver failed to find a solution:
> Could not resolve dependencies:
> [__0] trying: CodeWars-0.1.0.0 (user goal)
> [__1] unknown package: text (dependency of CodeWars)
> [__1] fail (backjumping, conflict set: CodeWars, text)
> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: CodeWars, text
> Trying configure anyway.
> Configuring CodeWars-0.1.0.0...
> cabal: Encountered missing dependencies:
> lens -any, split -any, text -any

**Comment by razvan-panda** [comment]
Above NixOS error was fixed using "cabal install --only-dependencies" followed by "cabal build".
I can't currently test on Windows, will get back to this ticket later.

**Comment by gbaz** [comment]
Right. So you need to install the deps before the package. This isn't a cabal error. It is intended cabal behavior.

If you're building this as a nix package, using nix derivations then you need to study how to use cabal with nix. E.g. I noticed you don't have the cabal deps declared in your nix derivation: https://github.com/razvan-panda/Haskell-CodeWars/blob/master/default.nix

You can use a tool like https://github.com/NixOS/cabal2nix to generate that. 

You do seem to have the packages in shell.nix, so they should be available in the nix shell. Either way, the issue is with your usage of nix, not a problem in cabal as far as I can see.

**Comment by razvan-panda** [comment]
@gbaz As far as I can tell what I was missing was running `cabal install --only-dependencies` before running `cabal build`. I'd prefer if you kept this issue opened until I had the chance to test this works on  Windows also.

On nix the configuration is as intended since I am using nix-shell. So no, this is definitely not a Nix issue. The issue was me not knowing how to use cabal.
