### ISSUE TITLE
Specifying remote Git repositories without .cabal file?

### ISSUE THREAD

**Issue by pythonissam** [haskell/cabal#5785]
Suppose we want use a remote git repository and write so:

```plain
source-repository-package
  type: git
  location: https://github.com/wataru86/han2zen
  tag: 7b13cb39506453b07eb38d5ad24799926f641bde
```

However, when that repository doesn't contain a cabal file, cabal complains with `NoCabalFileFound`. Of course we can generate cabal files and include it into git, but if there're alternatives, we'd like to know. Thanks.

**Comment by fgaz** [comment]
stack/hpack developers now recommend to include the .cabal file in the repository: https://github.com/commercialhaskell/stack/issues/5210

**Comment by phadej** [comment]
There is now a https://cabal.readthedocs.io/en/latest/cabal-project.html?highlight=%22source-repository-package%22#cfg-field-post-checkout-command
