### ISSUE TITLE
cabal new-build applies flags to non-local packages

### ISSUE THREAD

**Issue by maximpichler** [haskell/cabal#5794]
When running "cabal new-build --ghc-options=-eventlog" after a successful "cabal new-build", a host of dependencies gets recompiled into the global store. Looking into the store's new cabal-hash.txt files reveals that the only difference with version from the previous run is  "--ghc-options=-eventlog".

**Comment by quasicomputational** [comment]
This is tracked in #3883, which even has a plan for solving it.
