### ISSUE TITLE
-haddock flag blocks building cabal-install  (ghc 8.6.3 cabal-install 2.4 upgrading to 2.4.1)

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#5827]
main/Main.hs:596:5: error:
    parse error on input ‘-- $ cabal sandbox init && cabal configure -w /path/to/ghc
    --   && cabal build && cabal install
    --
    -- performs the compilation twice unless you also pass -w to 'install'.
    -- However, this is the same behaviour that 'cabal install' has in the normal
    -- mode of operation, so we stick to it for consistency.’
    |
596 |     -- $ cabal sandbox init && cabal configure -w /path/to/ghc
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Leaving directory '/var/folders/td/m25lmrxj68sdkwfjpnnqm6640000gn/T/cabal-tmp-37980/cabal-install-2.4.1.0'
Updating documentation index
/Users/carter/.cabal/share/doc/x86_64-osx-ghc-8.6.3/index.html
cabal: Error: some packages failed to install:
cabal-install-2.4.1.0-Hxe8KokzbCy4KNRkdNXXwX failed during the building phase.
The exception was:

**Comment by cartazio** [comment]
@sjakobi i think you care about this sort of thing? 

seems like a problem! (i disabled -haddock so i could unblock this build, but not a user friendly situation, docs or successful building! ;) )

**Comment by sjakobi** [comment]
Thanks for the report @cartazio!

Once https://ghc.haskell.org/trac/ghc/ticket/8944 is eventually fixed, GHC will emit a warning instead of erroring out on cases like this one.

**Comment by harpocrates** [comment]
> @sjakobi that patch in question hasn't been tickled since november, any idea whats holding it back?

My lack of free time. 😄 

More seriously, the main blockers are:

  * correctness in the presence of the multitude of GHC lexer/parser hacks and extensions (without introducing too many more hacks)
  * preserving performance

Last I checked, speed was impacted enough to make `haddock` performance tests fail. That's unacceptable since the whole point of this patch is to make `ghc -haddock` a good default.

**Comment by jwaldmann** [comment]
This also breaks the build for `c2hs`.

I have `ghc-options: -haddock` under `program-default-options` in my `$HOME/.cabal/config`. Is there a way to disable this? The naming `-default-` suggests to me that values will only be used when they are not overridden (by `cabal install --ghc-options=""` ) but apparently they are appended. What _is_ the way to override (in this case, remove) the defaults?

**Comment by sjakobi** [comment]
> What _is_ the way to override (in this case, remove) the defaults?

Seems like we'd want a `-no-haddock` flag in GHC.

**Comment by cartazio** [comment]
do we? that seems problematic ... I want to have docs :) !

1) current ghc errors instead of keepingon trucking

2) ....

**Comment by jwaldmann** [comment]
I think `ghc -no-haddock` would be a work-around only - for the real bug (in cabal-install)  that `default`options are always present, while they should be used only if there is no `--ghc-options`?

**Comment by cartazio** [comment]
To be clear : I have the haddock flag set in my cabal config.  I just want
to have my cake and eat it.

**Comment by gbaz** [comment]
this is resolved upstream afaik.
