### ISSUE TITLE
cabal v2-compile task

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5834]
It would be very useful to have a `v2-compile` task that uses the correct version of `with-compiler` for the project. This would be complementary to `v2-repl`.

For example, this could be used by downstream tools (such as `flycheck`) as an alternative to invoking a mystery meat `ghc` directly.

The `.ghc.*` dir mechanism will kick in naturally thereafter.

It would be even better if there was a way to invoke said compiler, for a given package, with all the flags enabled, e.g. language extensions and warnings / errors.

**Comment by hvr** [comment]
doesn't `cabal v2-exec ghc -- <flags>` kinda implement this magic?

**Comment by fommil** [comment]
umm, ok, that seems to do exactly what I want. I don't know how I didn't see this before :confounded:
