### ISSUE TITLE
v2 cache corruption when switching between --enable-profiling and not

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5835]
While testing @cocreature's implementation of isolated build caches for profiling in https://github.com/haskell/cabal/pull/5314, both myself and @edsko experienced cache corruption. Corruption was reproduced in the v2.4 branch by toggling `--enable-profiling` between builds (instructions included for an example project).

The only fix is to nuke the caches between builds.

**Comment by 23Skidoo** [comment]
Thanks for the report, this is very serious.

**Comment by dwijnand** [comment]
Does anyone have a reproducer for this, even a non-minimised one I can work at trying to minimise, or even a sketch of how to reproduce this?

**Comment by edsko** [comment]
FWIW, I have not seen this happen in quite a long time now.

**Comment by fommil** [comment]
I'm happy to close this if @edsko thinks it has gone away.

FWIW this was the repro https://github.com/haskell/cabal/pull/5314#issuecomment-399940799

**Comment by edsko** [comment]
I never tried to extract a reliable reproducible case so I can't be sure. But I've also not seen it again for quite a long time. Could close it until there is evidence that it is indeed still a problem?
