### ISSUE TITLE
Hooks in Setup.hs did not get called when building something deps on this lib.

### ISSUE THREAD

**Issue by Magicloud** [haskell/cabal#5842]
I have some code generating logic in Magicloud/cairo-core Setup.hs. It works  well when I build the lib. But when I build another project that depends on this lib, changes on Render.hs does not happen. The liftIO change seems working. I verified those via the .hi files.

I think the cause is that in both cases, the target Render.hs are in different place? But could not figure out.

**Comment by hvr** [comment]
For the benefit of others, here's the `Setup.hs` file: https://github.com/Magicloud/cairo-core/blob/3d24f3557b94774b3016ea7c2520d8621c02b96d/Setup.hs

**Comment by Magicloud** [comment]
@hvr Thanks.

Also, not sure if this is for the same reason, haddock generated in cairo-core does not trigger the change in Render.hs as well.

**Comment by Magicloud** [comment]
Closing for now since I could not reproduce this when using cabal.project. Maybe my previous building way was wrong somewhere.

**Comment by Magicloud** [comment]
@hvr, not exactly. At first the issue occured with stack. When I was trying to figure out where is the problem, I used wrong source from local repo. Now I corrected things with cabal.project and no problem was seen. So this should be stack's issue.

**Comment by Magicloud** [comment]
OK. I need to reopen this.

After two days working with cabal.project. I think there still is something wrong here.

Say I have a Cairo.hs depends on gi-gtk/gi-gdk/cairo-core. And gi-gtk/gi-dk depends on gi-cairo. gi-cairo depends on cairo-core. If I build Cairo.hs from the beginning. All fine.

But after I made some changes in gi-cairo/cairo-core, although `cabal v2-build all` prompted that those packages to be rebuilt, sometimes, not always, the generated methods in Render.hs were gone. No obvious message was seen.

The working example is the test/ folder of Magicloud/gi-cairo repo.

**Comment by Magicloud** [comment]
I found it. The logic bug in my code and how Cabal handles unchanged source.
