### ISSUE TITLE
Cannot find Prelude

### ISSUE THREAD

**Issue by adithyaov** [haskell/cabal#5851]
I'm unable to build 1 package but able to build the other. Am I doing something wrong here?

![prelude](https://user-images.githubusercontent.com/17845944/51422831-f7c23b00-1bdb-11e9-850a-15191eb18d73.PNG)

There are 2 packages multihash and multibase, I can build the former but not the later. The build fails with Prelude missing.

I've tried `-dynamic` as some forms suggested but still, it does not seem to work. It's not a problem with the packages. I've tried building another package test with no dependencies but even that fails with the same error.

**Comment by hvr** [comment]
> There are 2 packages multihash and multibase

judging from the output, those are rather two (sub)libraries inside the `multiformats` package

a screenshot is not enough to diagnose the problem; is your project publicly available somewhere? if not, can you show us your `.cabal` file at least?

**Comment by hvr** [comment]
@adithyaov Ok, I found https://github.com/ipfs-haskell/multiformats

so the problem is simply that you omitted the `base` dependency; try this:

```
library multibase
  exposed-modules: Multibase
                 , Standard
  build-depends: word8 ^>= 0.1.2
               , bytestring >=0.9 && <0.11
               , base >=4.6 && < 4.11
  hs-source-dirs: multibase/src
  default-language: Haskell2010


library multihash
  exposed-modules: Multihash
                 , RaazMultihash
  build-depends: base >=4.6 && <4.11
               , bytestring >=0.9 && <0.11
               , raaz ^>= 0.2.0
  hs-source-dirs: multihash/src
  default-language: Haskell2010
```

**Comment by adithyaov** [comment]
I can't believe I missed that. Thank you for the help. Next time I'll make sure to be more clear and provide necessary information related to the issue. I am using seperate `hs-source-dirs` directories for the different components `multihash/src` and `multibase/src`.
