### ISSUE TITLE
Internal libraries break (?) package.conf.inplace

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#5857]
Observed using Cabal 2.4.1.

Reproduction case here: https://github.com/michaelpj/cabal-bug-package-db

If I add even an empty internal library to my package, the package db in `dist/package.conf.inplace` seems to no longer work. `ghc-pkg list` shows the packages as there and exposed, but trying to use them with `ghc -package-db` does not work.

**Comment by hvr** [comment]
@michaelpj you seem to have tried with the legacy v1 commands; I tried with v2-build instead:

```
$ cabal build -w ghc-8.4.4
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following will be built (use -v for more details):
 - test-0.1.0.0 (lib) (first run)
 - test-0.1.0.0 (lib:irritant) (first run)
Configuring library for test-0.1.0.0..
Configuring library 'irritant' for test-0.1.0.0..
Warning: Packages using 'cabal-version: >= 1.10' must specify the
'default-language' field for each component (e.g. Haskell98 or Haskell2010).
If a component uses different languages in different modules then list the
other ones in the 'other-languages' field.
Warning: Packages using 'cabal-version: >= 1.10' must specify the
'default-language' field for each component (e.g. Haskell98 or Haskell2010).
If a component uses different languages in different modules then list the
other ones in the 'other-languages' field.
Preprocessing library 'irritant' for test-0.1.0.0..
Building library 'irritant' for test-0.1.0.0..
Preprocessing library for test-0.1.0.0..
Building library for test-0.1.0.0..
[1 of 1] Compiling Test             ( src/Test.hs, /tmp/cabal-bug-package-db/dist-newstyle/build/x86_64-linux/ghc-8.4.4/test-0.1.0.0/build/Test.o )

$ ghc-8.4.4 Use.hs
Loaded package environment from /tmp/cabal-bug-package-db/.ghc.environment.x86_64-linux-8.4.4

$ echo $?
0
```

**Comment by michaelpj** [comment]
Unfortunately `cabal new-build` is still unusable for me.

I did manage to solve my original problem by using a `cabal` command that set up the paths correctly for me (in this case `cabal doctest`), but I thought it was surprising that when I tried to do it manually with the package db it didn't work.

Feel free to close if you're not interested in fixing this.

**Comment by hvr** [comment]
@michaelpj it's not that we aren't interested, it's rather that the highest priority currently has getting v2-build ready to replace old-build. You say

> Unfortunately cabal new-build is still unusable for me.

and since we're going to make it default real-soon it would be great if you can elaborate what is missing so we can try to address that... :-)

**Comment by michaelpj** [comment]
Ah sorry, I interpreted that as "we're probably not interested in fixing v1 stuff" which would be reasonable :)

I don't think it's anything you don't have tickets for. For my organization at least the following are blockers:
- https://github.com/haskell/cabal/issues/4542 (fixed but not in a Cabal version we have yet)
- https://github.com/haskell/cabal/issues/5783

**Comment by michaelpj** [comment]
Hm, I'm observing this also in the package databases produced by Nix. I don't have a minimal reproduction yet, but it's something like:
- Cabal 2.2.0.0
- ghc 8.4.4+ (*not* observable with ghc 8.4.3)

In this case the combined package db for my dependencies has the package listed as present when I do `ghc-pkg`, but not when I actually try to compile something.

However, I think I have found a clue:
- When I run `cabal repl` or similar I see it passing `-package-id <package name>-<long hash` for all the dependencies.
- If I run `ghc -package-id <package-name>-<long-hash>` (which I pulled from out of the `.conf` file in the package db) then it *does* work.

Now, the docs for [-package-id](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/flags.html#ghc-flag--package-id%20%E2%9F%A8unit-id%E2%9F%A9) say that it exposes the package with the given id. But the `.conf` file in the package says it's exposed already, and `ghc-pkg expose` does nothing.

The only thing I can think of that's consistent with all this is that GHC disagrees with `ghc-pkg` and `cabal` about whether a package is exposed or not, and it requires to be told again that it should be exposed.

**Comment by michaelpj** [comment]
Further evidence that it's just looking for the wrong package id: the error message I get in both cases is *not* the one you get when you try to import from a hidden package, so it's not the exposure status that's wrong.

**Comment by michaelpj** [comment]
I opened a [trac ticket](https://ghc.haskell.org/trac/ghc/ticket/16228) for this since it seems like `ghc-pkg` and `ghc` are disagreeing.

**Comment by michaelpj** [comment]
Returning to this, I have a note about `new-build`: this works with `new-build` because the environment file specifies all the package-ids manually, regardless of whether they're exposed in the package db. I think this masks the bug, since it means we don't notice that a package that should be exposed is in fact hidden.

**Comment by michaelpj** [comment]
I fixed this in GHC.
