### ISSUE TITLE
Module in 'other-modules' is not build/linked

### ISSUE THREAD

**Issue by Treborius** [haskell/cabal#5865]
I want to write a C++ library that exposes some functions to haskell by using FFI and _extern "C"_.
That library should also be able to call some pure functions from haskell.

- so I wrote a haskell module that imports the c-functions (works)
- then I wrote haskell module **_ExportLib_**  with the functions I want to export to C
- then I wrote an _expose_ module **_HsExport_** that calls the haskell functions and exports the functions by FFI

i.e. the well known fibonacci example :
```
{-# LANGUAGE ForeignFunctionInterface #-}
module HsExport where
import Foreign.C.Types
import ExportLib

fibonacci_hs :: CInt -> CInt
fibonacci_hs = fromIntegral . fibonacci . fromIntegral
foreign export ccall fibonacci_hs :: CInt -> CInt
```
because of the c++-part, i used g++ to compile a shared lib,
beforehand I called ghc on the `"HsExport "` module to get the `HsExport_stub.h` header file generated

so at this point, the dynamic library is missing the _fibonacci_hs_ implementation

my cabal file has the following contents:

```
executable server
  Build-tools: c2hs
  hs-source-dirs: . src 
  main-is:             Main.hs
  Include-dirs: ../cxx/include
  extra-lib-dirs: ../cxx/build
  extra-libraries: stdc++ cxxLib
  other-modules: HsExport
```
but how hard I even try, cabal won't compile and link the HsExport into the main-program, 
so I end up with `undefined reference to fibonacci_hs`

is the desribed procedure appropriate? 
are there better solutions to get bi-directional FFI between c++ and haskell going?
what I need to configure in cabal, to make it compile and link HsExport into main?

**Comment by phadej** [comment]
Small  reproducible example (a repository one could clone) would help finding the problem.

To clarify, you don't get `* Missing (or bad) C library: cxxLib` errors, but an actual linker error when cabal tries to link final executable? If I try to reproduce small example myself, it fails early when cabal tries to find external dynamic libraries (as it cannot link a dummy executable, as it doesn't contain missing `fibonacci`).

**Comment by phadej** [comment]
Ok, two points:

- `ghc-options: -lCxx` is semantically wrong, but indeed you bypass the library check. Which is might ok for your use-case
- only adding to `other-modules: ` isn't enough. GHC is smart not to link it, as it seems unused. You can import it as `import HsExport ()`, which isn't that bad.
