### ISSUE TITLE
happy-1.19.9/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by agander** [haskell/cabal#5867]
I am building ghc using nix with:
`nix-shell ./ghc.nix/ --run 'hadrian/build.sh -c -j --flavour=devel2 --build-root=_build test'`
and have the following error:
| Run Happy: compiler/cmm/CmmParse.y => _build/stage0/compiler/build/CmmParse.hs
happy: /home/gander/.cabal/share/x86_64-linux-ghc-8.4.3/happy-1.19.9/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
shakeArgsWith   0.000s    0%                           
Function shake  0.008s    0%                           
Database read   0.029s    0%                           
With database   0.002s    0%                           
Running rules  10.197s   99%  =========================
Total          10.236s  100%                           
Error when running Shake build system:
  at src/Main.hs:58:30-42:
* Depends on: test
  at src/Hadrian/Builder.hs:70:5-23:
* Depends on: _build/stage1/bin/ghc
  at src/Development/Shake/Internal/Rules/Oracle.hs:157:43-68:
* Depends on: OracleQ (ContextDataKey (Context {stage = Stage1, package = Package {pkgType = Library, pkgName = "array", pkgPath = "libraries/array"}, way = v}))
  at src/Hadrian/Haskell/Cabal/Parse.hs:202:5-36:
* Depends on: _build/stage1/libraries/array/setup-config
  at src/Hadrian/Haskell/Cabal/Parse.hs:120:5-14:
* Depends on: _build/stage1/lib/package.conf.d/base-4.12.0.0.conf
  at src/Development/Shake/Internal/Rules/Oracle.hs:157:43-68:
* Depends on: OracleQ (ContextDataKey (Context {stage = Stage1, package = Package {pkgType = Library, pkgName = "base", pkgPath = "libraries/base"}, way = v}))
  at src/Hadrian/Haskell/Cabal/Parse.hs:202:5-36:
* Depends on: _build/stage1/libraries/base/setup-config
  at src/Hadrian/Haskell/Cabal/Parse.hs:120:5-14:
* Depends on: _build/stage1/lib/package.conf.d/rts-1.0.conf
  at src/Development/Shake/Internal/Rules/Oracle.hs:157:43-68:
* Depends on: OracleQ (ContextDataKey (Context {stage = Stage1, package = Package {pkgType = Library, pkgName = "rts", pkgPath = "rts"}, way = v}))
  at src/Hadrian/Haskell/Cabal/Parse.hs:202:5-36:
* Depends on: _build/stage1/rts/setup-config
  at src/Hadrian/Builder.hs:70:5-23:
* Depends on: _build/stage0/bin/ghc
  at src/Utilities.hs:71:18-22:
* Depends on: _build/stage0/compiler/build/libHSghc-8.7.a
  at src/Rules/Library.hs:118:5-30:
* Depends on: _build/stage0/compiler/build/RtClosureInspect.o
  at src/Development/Shake/Internal/Rules/Oracle.hs:157:43-68:
* Depends on: OracleQ (KeyValues ("_build/stage0/compiler/.dependencies","_build/stage0/compiler/build/RtClosureInspect.o"))
  at src/Hadrian/Oracles/TextFile.hs:96:9-20:
* Depends on: _build/stage0/compiler/.dependencies
  at src/Development/Shake/Internal/Derived.hs:118:15-23:
* Depends on: _build/stage0/compiler/.dependencies.mk
  at src/Rules/Dependencies.hs:25:9-18:
* Depends on: _build/stage0/compiler/build/CmmParse.hs
* Raised the exception:
user error (Development.Shake.cmd, system command failed
Command: /home/gander/PROJ/haskell/ghc/hadrian/dist-newstyle/build/x86_64-linux/ghc-8.4.3/happy-1.19.9/build/happy/happy -agc --strict compiler/cmm/CmmParse.y -o _build/stage0/compiler/build/CmmParse.hs
Exit code: 1
Stderr:
happy: /home/gander/.cabal/share/x86_64-linux-ghc-8.4.3/happy-1.19.9/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
)

I am logging this here because I found mention of the same error here:
[https://github.com/haskell/cabal/pull/5132#issuecomment-364333256](url)

`nix-shell ./ghc.nix/ --run 'which happy; happy --version'`
Entering a GHC development shell with CFLAGS, CPPFLAGS, LDFLAGS and
LD_LIBRARY_PATH correctly set, to be picked up by ./configure.

    CC              = /nix/store/lzh9rcw3rjvbaj7n3z4nzsvcz85k2p2m-gcc-wrapper-7.3.0/bin/cc
    CC_STAGE0       = /nix/store/lzh9rcw3rjvbaj7n3z4nzsvcz85k2p2m-gcc-wrapper-7.3.0/bin/cc
    CFLAGS          = -I/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/include
    CPPFLAGS        = -I/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/include
    LDFLAGS         = -L/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/lib
    LD_LIBRARY_PATH = /nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/lib
    LLVM            = NO
    libdw           = YES
    numa            = YES
    configure flags = --enable-dwarf-unwind

Please report bugs, problems or contributions to
https://github.com/alpmestan/ghc.nix
/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/bin/happy
Happy Version 1.19.9 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Marlow

Happy is a Yacc for Haskell, and comes with ABSOLUTELY NO WARRANTY.
This program is free software; you can redistribute it and/or modify
it under the terms given in the file 'LICENSE' distributed with
the Happy sources.

**Comment by agander** [comment]
Solution was to run ./configure manually.
I thought I had with: `hadrian/build.sh -c`

**Comment by hvr** [comment]
For the record, the path `/home/gander/.cabal/share/x86_64-linux-ghc-8.4.3/happy-1.19.9/HappyTemplate-arrays-coerce` is a hint that the wrong `happy` instance was picked, or that `happy` was demoted to an inplace package and invoked without going through `cabal v2-{exec,run}`.

**Comment by jmatsushita** [comment]
For the potential googlers, I ran into this same issue, in my case I need to `stack install happy` globally.

**Comment by simonmichael** [comment]
Thanks @jmatsushita. Also for the searchers: I too had to cd out of the current project to home directory and run `stack install happy` there. Then happy could build normally in the project. The error messages were not helpful:
```
.../project$ stack install happy
happy> configure
happy> Configuring happy-1.21.0...
happy> build
happy> Preprocessing executable 'happy' for happy-1.21.0..
happy> happy: /Users/simon/.stack/snapshots/x86_64-osx/nightly-2018-04-25/8.4.2/share/x86_64-osx-ghc-8.4.2/happy-1.19.9/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
```
8.4.2 ? Wat ?
Or after removing the `happy` executable per internet:
```
.../project$ stack install happy
happy> configure
happy> Configuring happy-1.21.0...
happy> build
happy> Preprocessing executable 'happy' for happy-1.21.0..
happy> Cabal-simple_mPHDZzAJ_3.4.0.0_ghc-9.0.1: The program 'happy' is required but
happy> it could not be found
```
Wat ?

**Comment by simonmichael** [comment]
I'm told "that's [installing from outside the project] only necessary if the .cabal file is missing a build-tools section", which mine is.
