### ISSUE TITLE
cabal new-clean doesn't remove `dist`

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#5871]
I just did a `cabal new-build` and then a `cabal new-clean`. But I'm left with a `dist` directory. Obviously I can delete that myself, but I would expect `cabal new-build; cabal new-clean` always to be a (local) no-op. ("Local" because the building might augment the package store.)

**Comment by hvr** [comment]
`new-clean` is only supposed to delete what it created, and unless its builddir is actually set to `dist/` it has no business removing it. That being said, we had a bug which caused spurious `dist/` folders to be created even though the build-dir was e.g. `dist-newstyle`; But this was already addressed via #5839 and so there shouldn't be any spurious `dist/` folder be created anymore.

**Comment by 23Skidoo** [comment]
Is #5839 included in any released version?

**Comment by 23Skidoo** [comment]
Looks like no, but should be in the next 2.4 point release.

**Comment by goldfirere** [comment]
That makes sense. I was also wondering about the two `dist`ish directories, but didn't pursue that angle. Sounds like this should be considered fixed, then.
