### ISSUE TITLE
cabal error - could not read index. Did you 'checkForUpdates'?

### ISSUE THREAD

**Issue by abarrasso** [haskell/cabal#5884]
Hi,

I am having a problem running cabal commands on terminal (mac), e.g. "cabal new-repl" or "cabal repl" and Im just getting the following error:

cabal: Could not read index. Did you call 'checkForUpdates'?

Does anyone know what could be the problem? It is the most updated version I'm wondering if it is a problem with my mac or some packages. Thanks!

**Comment by dewey92** [comment]
https://github.com/haskell/cabal/issues/5574 ?

**Comment by 23Skidoo** [comment]
Yep, looks like a duplicate.

**Comment by jneira** [comment]
Closing optimistically as duplicated, @abarrasso I see you commented in the original issue where you can track istveventual resolution.
Feel free to reopen if you think this is different
