### ISSUE TITLE
cabal with empty config has no default repository

### ISSUE THREAD

**Issue by tych0** [haskell/cabal#5891]
Hi,

With the old-style projects, I used to be able to do,

`cabal --config-file=/dev/null build`

and things would work. However, when I do it with `new-build`, I get,

```
cabal --config-file=/dev/null new-build
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: xcffib-0.6.0 (user goal)
[__1] unknown package: semigroups (dependency of xcffib)
[__1] fail (backjumping, conflict set: semigroups, xcffib)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: xcffib, semigroups

make: *** [Makefile:35: dist/build/xcffibgen/xcffibgen] Error 1
```

**Comment by phadej** [comment]
Without a repository `cabal v2-build` cannot work, as the error tells:

    unknown package: semigroups (dependency of xcffib)

`v1-build` "worked", because the dependencies were installed locally. One can mimic that behavior by vendoring in all dependencies into a big `cabal.project`, but I guess it's not the goal?

I'm also not seeing `new-build` in a referenced commit, so it further confuses me.

**Comment by tych0** [comment]
Ah, I didn't realize it would look at locally installed stuff. I suppose then it depends on how distros will package v2 projects for this to work; is there no way to do a local install similar to v1? (mostly just for my own edification, the solution above works fine for me)

**Comment by phadej** [comment]
`v2-build` is orthogonal to how distributions package cabal projects. I'd recommend distributions to not use `cabal-install` at all, but execute raw `./Setup.hs` (or `cabal act-as-setup` if it's more convenient). (`cabal v2-build` can be used to find install-plans, but using `cabal` to execute them will only cause conflicts as `cabal v2-build` wants to manage the dependencies itself).
