### ISSUE TITLE
Don't snip version conflicts

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/cabal#5892]
It would be convenient for debugging a build failure if I could see all of the version information cabal knows about. Unfortunately it tends to do this:

```
(conflict: Cabal => containers==0.5.7.1/installed-0.5...)
```

What's after that `0.5...`?? :)

**Comment by hvr** [comment]
The code in question is at https://github.com/haskell/cabal/blob/28d7da00ee7ccb6cc86dbc0312b4a262925bdf29/cabal-install/Distribution/Solver/Modular/Package.hs#L57-L67

**Comment by grayjay** [comment]
See #6465 for another example of a truncated version.
