### ISSUE TITLE
Thoughts on factoring out `Distribution.System` into its own library?

### ISSUE THREAD

**Issue by LightAndLight** [haskell/cabal#5897]
`Distribution.System` seems to have the most robust treatment of operating systems and architectures I can find in the Haskell ecosystem. I'd like to re-use this functionality in my own code, but I really don't need to depend on `Cabal`.

What do people think about splitting this out into a separate library?

Alternatively, I've found this ticket: https://ghc.haskell.org/trac/ghc/ticket/2614 which suggests there's some desire to have at least some of the functionality merged into `System.Info`. Maybe that's a better avenue to pursue.

**Comment by 23Skidoo** [comment]
I think it'd make sense to add this functionality to `base`, however, this is a matter for the core libraries committee and not Cabal developers. I recommend writing a patch / [proposal](https://wiki.haskell.org/Library_submissions#Guide_to_proposers) for `base`.
