### ISSUE TITLE
cabal new-install lacks `--with-PROG=` and `--PROG-option=` flags

### ISSUE THREAD

**Issue by TerrorJack** [haskell/cabal#5898]
The `--with-PROG=` and `--PROG-option=` flags are present in `new-configure` and `new-build`, but surprisingly absent in `new-install`. Are they excluded on purpose or is this just a bug?

**Comment by 23Skidoo** [comment]
Probably an oversight. /cc @typedrat

**Comment by typedrat** [comment]
I'll have to look at where those come from, because it has the same flag set as any other `new-` command.

**Comment by harpocrates** [comment]
I can't build `cabal` on my work laptop, but I think this was also fixed by #5931, right?

**Comment by 23Skidoo** [comment]
Yes, looks like it, though the help message currently doesn't mention this.
