### ISSUE TITLE
How can I specify specific source files for building a component?

### ISSUE THREAD

**Issue by Martinsos** [haskell/cabal#5905]
Hi,
instead of having tests in separate tests/ folder as it is most commonly done, I would like to mix them together with the source files, meaning that in my case both tests and source files would be in the src/ directory.

However, the problem is, the only way I have found to specify the source files is to specify `hs-source-dirs` where I don't have the needed granularity. I would like to specify that only files which match `src/**/*Test.hs` glob are to be used as source files for my test-suite, while all the others are to be used as src files for my library.

Is there any way to do this in Cabal right now?

Thanks a lot!

**Comment by jneira** [comment]
Hi @Martinsos, that is a good question, sorry for the late response :slightly_smiling_face: 

Have you tried to set `hs-source-dirs` to `src` in both lib and test component and list in each one the correlated modules (in `exposed-modules` and/or `other-modules)? Not sure if it would have caveats.

**Comment by phadej** [comment]
> Not sure if it would have caveats.

it does. GHC will recompile the modules in test-suites  instead of using (already) compiled library. 

There is a note in the docs: https://cabal.readthedocs.io/en/3.4/cabal-package.html#pkg-field-hs-source-dirs

**Comment by Martinsos** [comment]
Thank you for responding! I have to admit I got used to keeping the tests in a separate directory, and while I still think being able to mix tests with source code might be a nicer option, I am ok with it for the time being. I will close the issue!
