### ISSUE TITLE
/opt/ghc/bin/cabal v2-sdist -w $HC cabal: unrecognized 'v2-sdist' option `-w'

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5908]
v2-sdist doesn't recognise --with-compiler

**Comment by typedrat** [comment]
Why would it? It doesn't need it.

**Comment by phadej** [comment]
I see

> Deprecated: SDist hooks violate the invariants of new-sdist. Use 'autogen-modules' and 'build-tool-depends' instead.

Why that hook isn't simply removed?

**Comment by typedrat** [comment]
@hvr, (I think) @23Skidoo, and I talked about it, and we decided leaving it there to not entirely break old-style use cases and old custom setups would be the proper approach.

**Comment by phadej** [comment]
Old `Custom` setups should define an upper bound on `Cabal`, that's why we have `custom-setup`.

**Comment by 23Skidoo** [comment]
IIRC the aim was to give a more user-friendly warning. I think we can remove it in 3.0 or 3.2.

**Comment by jneira** [comment]
So afaiu this issue is not about add support `-w` to `cabal v2-sdist`, but for remove SDist hooks?
I dont remember see the warning: `Deprecated: SDist hooks violate the invariants of new-sdist. Use 'autogen-modules' and 'build-tool-depends' instead.`, is it done?

**Comment by Mikolaj** [comment]
I don't understand the issues invovled, but #6124 shows a use case (somewhat) contrary to the analysis. Also

```
git grep "violate the invariants"
```

turns out no hits. I have no idea where we are.

**Comment by phadej** [comment]
sdist hooks are removed, this issues is outdated.
