### ISSUE TITLE
Cabal says package hashable has missing files even though it doesn't.

### ISSUE THREAD

**Issue by skynet1** [haskell/cabal#5913]
Whenever I run `cabal install accelerate` it tells me that it can't build the package unique because there are missing files in hashable-1.2.7.0 .
I've gone through the files in the ~/.cabal directory and found that the hashable package seems to have the missing files.

Here's the output:

`Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Resolving dependencies...
Downloading  cryptonite-0.25
Starting     unique-0
Building     unique-0
Failed to install unique-0
Build log ( /home/noah/.cabal/logs/ghc-8.6.3/unique-0-HX83fuJBpWlJf3rf68Fdf5.log ):
cabal: Entering directory '/tmp/cabal-tmp-22237/unique-0'
Configuring unique-0...
Preprocessing library for unique-0..
Building library for unique-0..
[1 of 1] Compiling Control.Concurrent.Unique ( src/Control/Concurrent/Unique.hs, dist/build/Control/Concurrent/Unique.o )

src/Control/Concurrent/Unique.hs:12:1: error:
    Could not find module ‘Data.Hashable’
    There are files missing in the ‘hashable-1.2.7.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
12 | import Data.Hashable
   | ^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-22237/unique-0'
Downloaded   cryptonite-0.25
Starting     cryptonite-0.25
Building     cryptonite-0.25
Completed    cryptonite-0.25
cabal: Error: some packages failed to install:
accelerate-1.2.0.1-HcANriTkHRSJtRxmM4f2bV depends on accelerate-1.2.0.1 which
failed to install.
unique-0-HX83fuJBpWlJf3rf68Fdf5 failed during the building phase. The
exception was:
ExitFailure 1`

OS: Arch Linux
Cabal version: 2.4.1.0
Ghc version: 8.6.3

**Comment by gbaz** [comment]
This is the famous issue with arch packaging of haskell. The packages you have only have the dynamic builds, but cabal is trying to link against (nonextant) static builds. See https://wiki.archlinux.org/index.php/haskell for discussion on a range of solutions, and perhaps hop on to #haskell on freenode irc to get some interactive help if you continue to have problems or questions about this.
