### ISSUE TITLE
Stop passing -Wmissing-home-modules to GHCi

### ISSUE THREAD

**Issue by edmundnoble** [haskell/cabal#5917]
Doesn't seem useful for GHCi, and it doesn't work properly anyway; every time I subsequently use `:l` in the REPL session, every module loaded shows as "not listed in other-modules" even if it is. Going to try to tackle this in a PR.

**Comment by hvr** [comment]
@edmundnoble can you post a concrete example? Also you used `:l`, would this also happen with `:m`?

**Comment by hvr** [comment]
we figured out after a brief conversation on #hackage  that `:m` does in fact not trigger the warning; so let's close this again

**Comment by edmundnoble** [comment]
Doesn't happen with `:m`. I'd post a project or something but this always happens when you use `:l` with `cabal new-repl`; it's happened with every project I've had.

As you pointed out on IRC though I don't really need to use `:l Module` because I can use `:m* Module` for the same effect, and that doesn't have this issue.
