### ISSUE TITLE
cabal new-install -z

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5919]

**Comment by typedrat** [comment]
Huh?

**Comment by gbaz** [comment]
you know, for when your  new-install needs more `z`.

**Comment by typedrat** [comment]
OH! It's `cabal v2-repl --ignore-project` for `v2-install`.

**Comment by emilypi** [comment]
Sure it doesn't install sleep for the user? That'd be a killer feature.

**Comment by phadej** [comment]
@typedrat. @emilypi any progress on this?

**Comment by emilypi** [comment]
Hey @phadej sorry for the late response - I'm only just now answering emails. I've taken a break from OSS until work becomes less strenuous, so it's probably best to assign this to someone else until i'm back.

**Comment by phadej** [comment]
@emilypi no worries. Sorry for taking away the joy of completing something (it's done in #6428). Yet, there're plenty of open issues to tackle, for whenever you feel like solving one.

**Comment by emilypi** [comment]
Hahaha no worries. Yeah, i'll pick something else up.
