### ISSUE TITLE
On Windows cabal seems to search for unsuffixed binaries only

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#5936]
I have noticed that cabal has trouble finding e.g. `pkg-config` because it's looking for `pkg-config` instead of `pkg-config.exe`. 

The search for binary functionality on Windows needs to search for both, giving preference to `.exe` as that's likely to be found.

I do remember this used to work before.

**Comment by hvr** [comment]
Did you experience this with a version of `cabal` that had #5753 in it (and note that no released version of cabal currently has this)?

**Comment by Mistuke** [comment]
yeah, it's one of the latest head builds. AppVeyor should show it by putting it in verbose mode. One sec let me  check the latest head.

**Comment by hvr** [comment]
@Mistuke is there any way you could help debug this? I.e. is it `findProgramOnSearchPath` that fails to find `pkg-config` or is it some other codepath being at fault here?

**Comment by Mistuke** [comment]
Sure, I've started a build to check. (not on my usual machine so don't have one handy).

**Comment by Mistuke** [comment]
hmm that's interesting, it seems to work on the latest head..


```
Using pkg-config version 0.29.2 found on system at:
C:\dev\msys64\mingw64\bin\pkg-config.exe
```

I will have to wait till I'm home to find the other build I was trying. But this seems to not be an issue anymore... Sorry for the noise.
