### ISSUE TITLE
Support nested lists in the `description` field of `.cabal` files

### ISSUE THREAD

**Issue by ChShersh** [haskell/cabal#5938]
Consider the following minimal `.cabal` file that illustrates desired usage:

```cabal
cabal-version: 2.4
name: haddock-description-example
version: 0.0.0.0
description:
    * Top-level
    .
        1. First item
        .
        2. Second item

library
  exposed-modules:     Foo
  build-depends:       base ^>= 4.12
```

When I build the documentation for this small package, I see the following rendering of the `description` field:

<img width="395" alt="Screenshot 2019-03-14 at 9 25 06 AM" src="https://user-images.githubusercontent.com/4276606/54325009-13c1e600-463b-11e9-913e-979718e3e3f4.png">

However, I'm expecting to see nested lists. I tried different combinations of placing dots to achieve this, but nothing works. At the same time, It's not clear from the Haddock and cabal documentation, what should be added to fix the problem.

* https://haskell-haddock.readthedocs.io/en/latest/markup.html#itemized-and-enumerated-lists
* https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-description

**Comment by sboosali** [comment]
did you try putting the "blank-line-separing" dot farther left (I don't
know if that even parses, as I'm the way from a computer).

Haddock needs four spaces per indentation. It Cabal parses a blank line as
starting from that line's dot (rather the `description`-field-wide
indentation), that might explain it.

**Comment by ChShersh** [comment]
@sboosali I've tried the following combinations, but nothing works:

```cabal
    * Top-level
        .
        1. First item
        .
        2. Second item
```

```cabal
    * Top-level
    .
        1. First item
    .
        2. Second item
```

```cabal
    * Top-level
    .
    .    1. First item
    .
    .    2. Second item
```

```cabal
    * Top-level
    .
        1. First item

        2. Second item
```

**Comment by hvr** [comment]
I remember having briefly discussed this some time ago already... the problem is that the parser doesn't consider leading whitespace significant. We'd need to tweak the handling of the `description` field to have it preserve leading whitespace; and while at it, we should also get rid of the anachronistic `.`-paragraph-separator hack (and we'd probably want to version guard this)

**Comment by sboosali** [comment]
i like the `|` hack
