### ISSUE TITLE
hs-source-dirs does not accept a leading comma

### ISSUE THREAD

**Issue by andrewthad** [haskell/cabal#5959]
We can do this:

    build-depends:
      , HUnit 
      , QuickCheck                                                       
      , automata

But not this:

    hs-source-dirs:
      , test
      , common         

This feels inconsistent.

**Comment by phadej** [comment]
Duplicate of https://github.com/haskell/cabal/issues/5713 which is resolved in https://github.com/haskell/cabal/pull/5714
