### ISSUE TITLE
index-state with multiple repositories is suboptimal

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5965]
Not sure how it works at all :)

**Comment by hvr** [comment]
Well, in the original design I anticipated the ability to prefix index-states by the repo-id; I just never got to implement it... :-)

`cabal v2-update` already supports repo-qualified index-states

**Comment by phadej** [comment]
@hvr I'm confused what `index-state` in cabal.project does when there are multiple repositories; does it applies to all repositories?

**Comment by 23Skidoo** [comment]
Yeah, the setting should be made per-repo. And username and password too.

**Comment by phadej** [comment]
Now (In 3.4) it is possible to set `index-state` per repo.
