### ISSUE TITLE
Support "if" in cabal.project

### ISSUE THREAD

**Issue by maoe** [haskell/cabal#5975]
Currently neither of these are accepted in cabal.project:

```
package gtk
  if os(osx)
    flags: +have-quartz-gtk
```
or
```
if os(osx)
  constraints: gtk +have-quartz-gtk
```

It would be handy if something like these were supported.

**Comment by maoe** [comment]
According to the release notes and the [official doc](https://cabal.readthedocs.io/en/stable/cabal-project.html?highlight=cabal.project#conditionals-and-imports), v3.8 seems to support this.

**Comment by maoe** [comment]
> i.e. there is no support for a notion of custom flags in project files

Apparently it's not really supported yet.

**Comment by gbaz** [comment]
Right. No custom flags. But os, arch, and compiler are there, which seems to be what this issue was about. So I think we can mark this resolved?

**Comment by maoe** [comment]
The following snippet worked in the threadscope project:

```
if os(darwin)
  package gtk
    flags: +have-quartz-gtk
```

> So I think we can mark this resolved?

Yes, we can.
