### ISSUE TITLE
cabal v2-haddock exits with 0 even when it fails to build the docs

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5977]
With `3.0+git20190317.1.b3d6d0b-6~18.04`

```
% cabal v2-haddock && echo $?
...
Warning: Failed to build documentation for github-0.21.
0
```

**Comment by phadej** [comment]
Even it says a *warning* that failed to build a documentation. I need a way to make it fail, even the default is lenient. That is needed for automated scripts, like CI.

**Comment by phadej** [comment]
ping @RyanGlScott, atm `haskell-ci`s haddock building doesn't fail the builds.

**Comment by phadej** [comment]
I assigned this to @hvr, as he did tweak something related. Again, this is high priority issue, as there are no way to check in CI that haddocks build.

**Comment by isovector** [comment]
@phadej suggests https://github.com/haskell/cabal/pull/5459 might be to blame. I'm going to investigate.

**Comment by isovector** [comment]
For a quick CI workaround:

```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,7 +20,7 @@ script:
- - cabal new-haddock
+ - "! cabal new-haddock 2>&1 >/dev/null | grep 'Failed to build documentation'"
```

**Comment by phadej** [comment]
Fixed with https://github.com/haskell/cabal/pull/6137, thanks @isovector!
