### ISSUE TITLE
bootstrap.sh link is broken on hackage

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#5980]
From http://hackage.haskell.org/package/cabal-install, in the readme the [bootstrap.sh](http://hackage.haskell.org/package/cabal-install-2.4.1.0/cabal-install-2.4.1.0/srcbootstrap.sh) link is broken. The response is:

    Page not found: Sorry, it's just not here.

The link is good within this repo when using github's user interface, it doesn't work when the same content is viewed from hackage's page for the latest cabal-install.

**Comment by 23Skidoo** [comment]
Hmm, shouldn't be this fixed on the Hackage server side instead? The `[bootstrap.sh]` Markdown link in README gets rewritten by Hackage to http://hackage.haskell.org/package/cabal-install-2.4.1.0/cabal-install-2.4.1.0/srcbootstrap.sh, but it should be http://hackage.haskell.org/package/cabal-install-2.4.1.0/src/bootstrap.sh.

**Comment by 23Skidoo** [comment]
Closing in favour of https://github.com/haskell/hackage-server/issues/823.
