### ISSUE TITLE
Inscrutable error message if cabal.project has no packages field

### ISSUE THREAD

**Issue by Boarders** [haskell/cabal#6013]
If I create a project with a `cabal.project` file that does not list the packages field then I get the error:

```
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.
```

I think this is not a very helpful message for the problem at hand.

**Comment by mitchellwrosen** [comment]
I believe it also does this if you write

```
packages:
  my-package
```

**Comment by Boarders** [comment]
To be clear, this behavior occurs if I *do* have a  `<pkgname>.cabal` file and a `cabal.project` but fail to list the packages field in the `cabal.project` file.

**Comment by 23Skidoo** [comment]
Yep, bumped into this too.

**Comment by phadej** [comment]
Related: https://github.com/haskell/cabal/issues/6144
