### ISSUE TITLE
change the default of cabal v2-configure

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6016]
It says:

```
The 'cabal.project.local' file persists across 'clean' but is overwritten
on the next use of the 'configure' command. The intention is that the
'cabal.project' file should be kept in source control but the
'cabal.project.local' should not.
```

but I often have non-trivial configuration there, e.g.

```
package Cabal
  ghc-options: -Werror
```

and if I **accidentally** `cabal v2-configure`, that setup is gone. As `cabal.project.local` files **aren't checked into VCS**, overwriting them is destructive, and irreversible operation.

I suggest `v2-configure` to abort if `cabal.project.local` exists. And possibly have a `--force` flag.

**Comment by 23Skidoo** [comment]
```
package Cabal
  ghc-options: -Werror
```

Why not put this stuff in `cabal.project`?

**Comment by phadej** [comment]
Because cabal.project **is** checked to VCS, and I try to avoid cabal.project changes  as I could accidentally commit them.

**Comment by 23Skidoo** [comment]
OK. May be easier to introduce a new local config file (`cabal.project.user` or `cabal.project.extra`) file for such customisations.

**Comment by hvr** [comment]
btw, in order to address this very issue we already implemented a failsafe when this came up some time ago already: when you `v2-configure` a backup of the old file is created at `cabal.project.local~`; see #3943

**Comment by fgaz** [comment]
Is the `disable-overwrite` option added in #7402 enough to close this? @phadej do you think it should be enabled by default? Right now, the default is both backup and overwrite enabled

**Comment by ulysses4ever** [comment]
Not much activity here: I take it people have been satisfied with the current behavior of configure, where it backs up an existing cabal.project.local, if any. Maybe this could be closed?

**Comment by Mikolaj** [comment]
Also, there's been some major activity about it in #7402 (and minor in #6877), so this is probably quite obsolete. Closing. Thank you, everybody.

**Comment by fgaz** [comment]
There's also the `--enable-append` option that can be set globally in `~/.cabal/config`

**Comment by andreasabel** [comment]
> I take it people have been satisfied with the current behavior of configure, where it backs up an existing cabal.project.local,

I am not, see #8408.
