### ISSUE TITLE
Newlines in bullet point within description of package

### ISSUE THREAD

**Issue by sheaf** [haskell/cabal#6026]
I am trying to include a bullet point list with newlines in my package description, like so:

- Text for bullet point 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  More text on a new line. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
- Text for bullet point 2. Ut enim ad minim veniam.
  More text for bullet point 2 on a new line.
  Yet another line of text for bullet point 2.
- Bullet point 3.

As per [Haddock issue #1013](https://github.com/haskell/haddock/issues/1013), the way to do that seems to be to use indentation, in the following manner:

```
{-|
*   Text for bullet point 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.


    More text on a new line. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

*   Text for bullet point 2. Ut enim ad minim veniam.


    More text for bullet point 2 on a new line.


    Yet another line of text for bullet point 2.

*   Bullet point 3.
-}
```

However when I attempt this within the description field of a package, using Cabal 3.0 as per #5938 #5971, it doesn't work, and the subsequent lines are typeset as part of the main text instead of within the bullet point. Specifically, the description field

```
description:
  *   Text for bullet point 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  
  
      More text on a new line. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  
  *   Text for bullet point 2. Ut enim ad minim veniam.
  
  
      More text for bullet point 2 on a new line.
  
  
      Yet another line of text for bullet point 2.
  
  *   Bullet point 3.
```
results in the following layout:

![cabal_wrong_indentation](https://user-images.githubusercontent.com/1297748/57091982-ae20da80-6d0a-11e9-876d-31959c9f49f7.png)

Does anyone know how to insert newlines within a bullet point item in a package description?

**Comment by sheaf** [comment]
OK actually I included too many newlines, it works with 

```
description:
  *   Text for bullet point 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  
      More text on a new line. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  
  *   Text for bullet point 2. Ut enim ad minim veniam.
  
      More text for bullet point 2 on a new line.
  
      Yet another line of text for bullet point 2.
  
  *   Bullet point 3.
```

**Comment by hvr** [comment]
@sheaf btw, I suspect this only works as intended starting with cabal 3.0 (see #5971 & #5981)

**Comment by sheaf** [comment]
Yes, I mentioned those two issues in the OP. Do you have a suggestion for a cross-compatible solution? Thanks.

**Comment by hvr** [comment]
@sheaf sorry, missed the mention; and no, if you need multiple paragraphs per bullet-point I can't think of a good solution that works pre cabal-version:3.0 ... but then again, what's the problem using cabal-version:3.0 ? `cabal 3.0` still supports all GHCs back till GHC 7.0

**Comment by sheaf** [comment]
That's fine, no problem with using `cabal 3.0`, and I appreciate the improvements. I was only wondering if there was a workaround for users who haven't yet moved to cabal 3.0, given that it seems it won't be bundled with GHC 8.8 either. No worries though, thanks.

**Comment by phadej** [comment]
- Cabal-the-library 3.0 will ne bundled with GHC, why you think it wouldn’t
- cabal-the-tool (cabal-install-3.0) can still be used; it’s not ties to particular GHC and (will be) distributed separately

**Comment by sheaf** [comment]
Oh, I thought that because the release notes for GHC 8.8.1-alpha1 mentioned Cabal 2.5.0.0, as seen [here](https://downloads.haskell.org/ghc/8.8.1-alpha1/docs/html/users_guide/8.8.1-notes.html#included-libraries). But of course cabal-install can still be used regardless, so I agree it's not much of an issue.
