### ISSUE TITLE
Cabal should print contents of response-files with high enough verbosity

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6027]
```
/cabal/bin/haddock '@/code/mess/example/dist-newstyle/build/x86_64-linux/ghc-8.6.5/example-0/doc/html/example/haddock-response81850-1.txt' 
```

and no way to see what arguments are passed there,

*EDIT* as response-file is removed after the command.

*EDIT* alternative is a flag to keep response-files

*EDIT* current workadound is `--disable-response-files`

**Comment by harpocrates** [comment]
@phadej Doesn't `-v3` cause Cabal to print out the response file contents to console? I think that's what I've used in the past.

**Comment by phadej** [comment]
Oh, we had it in `-v3`. Silly me. Thanks!
