### ISSUE TITLE
cabal configure (v2.4.1.0) hangs

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#6031]
Trying to find an Agda bug via bisection, I find `cabal configure` in version 2.4 is hanging.
Downgrading to 1.24 fixes this, thus, it must be a regression.
The last output gotten with -v3 is
```
...
Searching for jhc in path.
Cannot find jhc on the path
Searching for ld in path.
Found ld at /usr/bin/ld
Environment: [...,("LC_CTYPE","UTF-8"),...,("_","/Users/abel/.cabal/bin/cabal")]
("/usr/local/bin/ghc",["-c","/var/folders/lg/qcd3v89j59l3m6520kr42bdm0000gn/T/8235644401115438165.c","-o","/var/folders/lg/qcd3v89j59l3m6520kr42bdm0000gn/T/178448449274243042.o"])
```
I am running ghc-7.10.3 (in order to compile old Agda versions).

I have a snapshot of the directory including the cabal sandbox, but it is >2GB, please contact me if you want to look at this for debugging.

**Comment by 23Skidoo** [comment]
What happens if you try with current `master`?

**Comment by hvr** [comment]
@andreasabel I couldn't reproduce this; does this happen with the Git master branch of Agda? What steps did you perform? Does cabal hang or is it rather an external process (e.g. `ghc`) that's hanging?

**Comment by gbaz** [comment]
going to optimistically close this. please reopen if it appears to be an issue with current cabal.
