### ISSUE TITLE
Unknown extensions: GeneralisedNewtypeDeriving

### ISSUE THREAD

**Issue by jforberg** [haskell/cabal#6032]
I get an "unknown extension" warning when building my project with Cabal 2.4.0.1. This surprises me since, as far as I understand, the GeneralisedNewtypeDeriving extension has been around for a while.

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-GeneralisedNewtypeDeriving

This is not a big problem as the project still builds, but I feel you should be aware of it.

**Comment by gbaz** [comment]
It'll work with a "z" instead of an "s". Note that the release notes for ghc say "British spelling since 8.6.1." So I guess cabal should update to support the British (i.e. obviously wrong 😛) spelling too?

**Comment by 23Skidoo** [comment]
Is this just a matter of adding another `Extension` constructor? Should the `Eq` instance be modified to make `GeneralizedNewtypeDeriving == GeneralisedNewtypeDeriving = True`?

**Comment by phadej** [comment]
They are not the same.

> Since: 6.8.1. British spelling since 8.6.1.

**Comment by 23Skidoo** [comment]
Right, `ghc --supported-languages` now reports both `GeneralisedNewtypeDeriving` and `GeneralizedNewtypeDeriving`, and for GHC < 8.6 it only has the latter. So just a new constructor then.
