### ISSUE TITLE
Directory wildcards for data files do not work

### ISSUE THREAD

**Issue by mrkkrp** [haskell/cabal#6043]
I've read carefully [this page](https://www.haskell.org/cabal/users-guide/developing-packages.html?highlight=data%20files#pkg-field-data-files) and afaiu this pattern is OK:

> data/**/*.hs

However, it doesn't work in practice:

```
     Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4: invalid file glob 'data/**/*.hs'.
    Wildcards '*' are only allowed in place of the file name, not in the directory
    name or file extension. If a wildcard is used it must be with an file
    extension.
```

It appears that there is a disagreement between actual logic in the code and the documentation?

**Comment by quasicomputational** [comment]
They were added in version 2.4.

That output looks very much like it's from 2.2.0.1, possibly as bundled with GHC 8.4.4.

Can you paste the whole `.cabal` file? Either you've got an inappropriately low `cabal-version` (it should be at least 2.4), or there's something funny going on.

**Comment by mrkkrp** [comment]
OK, I think I just have Cabal 2.2:

```$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library```

**Comment by mrkkrp** [comment]
Anyway, I cannot use the feature because I cannot guarantee that consumers of my package will have recent-enough Cabal.
