### ISSUE TITLE
Regression: `cabal run prog -- foo @ bar` interprets `@`

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#6050]
After updating to the most recent HEAD snapshot I noticed a regression (and it basically breaks me to the point where I can't use `cabal run` anymore for two tools of mine):

specifically,

```
cabal run prog -- foo @ bar
```

is supposed to pass everyting after `--` unmodified to the invoked program as argv, i.e. `prog` is supposed to have `getArgs` return `["foo","@","bar"]`

However, sometime in the last 2 weeks this broke, and now instead `cabal` intercepts the arguments and throws an error

```
Error while expanding response file: : openFile: does not exist (No such file or directory)
```

**Comment by 23Skidoo** [comment]
I'm pretty sure the response files patch is at fault (#5996).

/cc @angerman @JoshMeredith

**Comment by angerman** [comment]
Thanks @23Skidoo
