### ISSUE TITLE
Update .cabal/config along with cabal-install

### ISSUE THREAD

**Issue by bos** [haskell/cabal#606]
(Imported from [Trac #613](http://hackage.haskell.org/trac/hackage/ticket/613), reported by guest on 2009-11-28)

When cabal-install is upgraded, it sometimes gains new features with corresponding lines in the default .cabal/config; however, the existing .cabal/config is not updated.

One way of updating it would be to make it, at every invocation of cabal-install, rewrite the file using a merger of the current configuration and the default one.

There are some issues with this - most particularily, user-written comments in the file should be preserved, without this stopping cabal-install from inserting its own comments for (disabled) new features, or causing duplication of comments.

None of this is particularily hard to imagine a solution for, but in the interests of avoiding priming, I won't write down my own suggested solutions here. If whoever eventually decides to try fixing this explains his proposed solution here, I'll chime in then.

**Comment by jsl** [comment]
Given that this ticket hasn't had any activity since 2009, I propose closing. Please open a new issue, or re-open if this is still desired.

/cc @tibbe
