### ISSUE TITLE
cabal --index-state broken

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#6061]
Another `@`-related regression in HEAD I stumbled over:

```
cabal build --index-state @1474732068
```

used to work for various v2 commands... but now it fails with

```
Error while expanding response file: 1474732068: openFile: does not exist (No such file or directory)
```

/cc @angerman @JoshMeredith

**Comment by 23Skidoo** [comment]
Hmm, not sure how to fix this in a good way apart from changing `--index-state` syntax.

**Comment by 23Skidoo** [comment]
We can of course pass through the `@`-argument when the response file doesn't exist, but this can lead to surprising behaviour in some cases.

**Comment by angerman** [comment]
I think checking for the existence of the response file prior to expansion is the best option we have. It will certainly lead to unexpected behavior if someone happens to have a file named like that, but can be rectified by the user.

The @<timestamp> syntac should probably go though. 

We could potentially also add some conditional expansion? If the previous token matched X, don’t expand? But I find adding even more complexity to the commandline Argument Logic to not be very desirable.

**Comment by DanielG** [comment]
Would it be possible to just require response file paths to start with `/` or `./`? Wouldn't that disambiguate this sufficiently?

**Comment by angerman** [comment]
Requiring `@./` or `@/` would probably work, but we'd deviate from the syntax other tools are using, and I'd prefer, we would not to be the special snowflake here that just had to do something different than all the others.

**Comment by JoshMeredith** [comment]
Maybe requiring an `--index-state=...` syntax would be a decent solution?

**Comment by JoshMeredith** [comment]
After installing `master`, it seems that the `=` syntax is already valid. A documentation update and maybe a note in the error message when the option is used with space could be the way to go?

**Comment by hvr** [comment]
> I think checking for the existence of the response file prior to expansion is the best option we have.

That'd at least make `cabal` follow the convention of the other prominent tooling supporting the `@`-expansion hack...

**Comment by 23Skidoo** [comment]
We should make a patch for `base` as well then.

**Comment by angerman** [comment]
@JoshMeredith please look into this :-)

**Comment by JoshMeredith** [comment]
I'm ready to merge a fix into cabal, but I wanted to get opinions on if I should make any changes before submitting it to base.

**Comment by hvr** [comment]
Fwiw, this `@`-feature has caused enough knock-off effects that somebody should write a blogpost about it :-)

**Comment by 23Skidoo** [comment]
@JoshMeredith Re: further changes to #6063, you may want to add recursive expansion of response files for full compatibility with `gcc`/`clang` (with a recursion depth limit to prevent infinite looping). I do not consider it a blocker, though.
