### ISSUE TITLE
`cabal new-haddock` does not include any documentation on `reexported-modules`

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#6066]
In theory the top-level haddocks should at least link reexported-modules off to the docs for the (sub-)library they came from.

**Comment by 23Skidoo** [comment]
IIRC there's a ticket for this already.

/cc @ezyang

**Comment by ezyang** [comment]
Even if we fix this in Haddock, Hackage needs to be fixed separately because it reimplements rendering logic.

**Comment by harpocrates** [comment]
The Cabal side of this was fixed by @phadej in #6028. I've opened a separate issue for Hackage: https://github.com/haskell/hackage-server/issues/833.
