### ISSUE TITLE
Allow the show-details test flag to be configured

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#6069]
We have a [show-delails](https://cabal.readthedocs.io/en/latest/installing-packages.html?highlight=%20test-show-details#cmdoption-setup-test-show-details) option to the `cabal test` command.

I would be nice to have that as an option in the `~/.cabal/config` as well as having it in the `cabal.project` file. If the option is present in the former, it should override the latter.

**Comment by erikd** [comment]
I have now find its possible to do `cabal configure --test-show-details=direct` which adds that option to the `cabal.project.local` file.

**Comment by ulysses4ever** [comment]
@erikd does your second comment mean that this is basically handled and the issue should be closed?

**Comment by Mikolaj** [comment]
From the silence I presume this must be so. If not, please kindly re-open or open a new ticket. Closing.
