### ISSUE TITLE
Prelude.foldr1: empty list on pkgconfig-depends in sub-library using cabal 3

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#6082]
If I uncomment the `pkgconfig-depends` line at [fontconfig.cabal](https://github.com/ekmett/codex/blob/178b48960bdf67d59a37beea227905aeb352dcb0/fontconfig/fontconfig.cabal#L67) then I get the following rather helpful error message from cabal:

```
$ cabal new-build
Prelude.foldr1: empty list
```

I don't believe I have done anything wrong here. The sub-library worked just fine as a standalone package. At worst, I think the dependency list may be redundant with the upstream packages, which both incur the same constraints, and therefore hopefully would ensure I get linked against the appropriate libs, but this isn't the right way to say that if that is what is being indicated. =)

**Comment by hvr** [comment]
@phadej does this ring any bells related to your commit at 01df85eda2a1e986b47c9ca83cdc511b49fb62f2 ?

**Comment by phadej** [comment]
Argh, yes. I should used foldr or sepBy1

Can we have NonEmpty in Cabal?

**Comment by hvr** [comment]
@phadej we could bite the bullet at some point (maybe Cabal 3.2 ?), and add a conditional dependency such as

```
if !impl(ghc >= 8.0)
   build-depends: semigroups >= 0.16.1 && < 0.19
```

to Cabal -- assuming there's no `build-type:custom` in semigroups' trans-deps... :-)

and also get rid of our fake `Distribution.Compat.Semigroup` in the process... :-)
