### ISSUE TITLE
cabal v2-repl permission denied on unrelated directory

### ISSUE THREAD

**Issue by chrissound** [haskell/cabal#6089]
cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 

```
[nix-shell:~/Haskell/JohnProjv2]$ cabal v2-repl app
/home/chris/fromLaptopt/usbflash/Haskell/JohnProjv2/././_data: getDirectoryContents:openDirStream: permission denied (Permission denied)
```
The `_data` directory is completed unrelated to the Haskell / cabal project, and I don't expect cabal to fail because of not having permission to that directory.

**Comment by gbaz** [comment]
i doubt this is reproducible with a current cabal. closing optimistically.
