### ISSUE TITLE
Install the offline version

### ISSUE THREAD

**Issue by PengFeiDuan1995** [haskell/cabal#6093]
HI，My server is CentOS and cannot connect to the Internet. How can I get a full offline version and install it?thank you。

**Comment by 23Skidoo** [comment]
You can download a Linux `cabal-install` binary from https://www.haskell.org/cabal/download.html. Is this what you want?

**Comment by PengFeiDuan1995** [comment]
> You can download a Linux `cabal-install` binary from https://www.haskell.org/cabal/download.html. Is this what you want?

Thank you, I downloaded after installation, this will still download other things, my environment is simulated completely Intranet.

**Comment by 23Skidoo** [comment]
There's also the offline mode (`cabal install --offline`) and the `cabal fetch` command.
