### ISSUE TITLE
--overwrite-policy in CLI blows out

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#6098]
```
$ cabal new-install -f --overwrite-policy=always happy
Invalid flag assignment: --overwrite-policy=always
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:49:24 in Cabal-2.4.1.0-2mL6d3JeEJ7DKvehaV04FE:Distribution.ReadE
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 
```
Is it expected?

**Comment by mitchellwrosen** [comment]
`-f` sets a flag for all packages - is that there on purpose?

**Comment by ulysses4ever** [comment]
@mitchellwrosen good point! In fact, I meant force-reinstall. I solved my problem in the end. But anyway, it's probably bad to crash like this, isn't it?

**Comment by mitchellwrosen** [comment]
It depends what you mean - bad to crash with such an ugly message? - well that's cabal for you ;) - but bad to crash given an invalid flag assignment? The other option I can think of is to ignore it (which cabal does sometimes, e.g. unknown fields in `cabal.project`), which may be even worse.

**Comment by ulysses4ever** [comment]
Fair enough. Thanks for your reply!
