### ISSUE TITLE
As `Cabal` now depends on `semigroups` remove partial functions

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6107]
e.g. `groupBy` + `head` can be made safe with `NonEmpty` stuff, and so one.

As most modules use `Distribution.Compat.Prelude`, hiding partial `Prelude` stuff should be quite straight forward.

Bonus: clean up `(a, [a])` stuff in `Distribution.Compat.Parsing`.

**Comment by dwijnand** [comment]
@phadej Anything left?  I could have a look if there is.

**Comment by phadej** [comment]
Thanks for helping, I think we are good now
