### ISSUE TITLE
Improve error message for undefined flags

### ISSUE THREAD

**Issue by coot** [haskell/cabal#6113]
**Describe the bug**
I got the following error message:
```
cabal v2-build ...
Resolving dependencies...
Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:610:17 in containers-0.5.11.0:Data
.Map.Internal
```
The error is caused by a call to `flag(someFlag)` where `someFlag` was not defined.  Either adding the flag or removing the call to `flag(someFlag)` fixed the error.    It would be nice to get an informative error message which would mention that a given flag was used but not defined.

**Expected behavior**
An informative error message. 

**System informataion**
 - Operating system: `GNU/Linux`
 - `cabal`, `ghc` versions: `cabal-2.4.1.0`, `ghc-8.6.5`

**Additional context**

**Comment by phadej** [comment]
This is fixed by https://github.com/haskell/cabal/pull/5876, try `3.0` branch.

**Comment by coot** [comment]
Nice, thanks @phadej!
