### ISSUE TITLE
`v2-build` passes but `v2-install` fails on a multi-projects setting

### ISSUE THREAD

**Issue by YoEight** [haskell/cabal#6118]
**Describe the bug**
```
$ cabal v2-build foo # works
$ cabal v2-install foo # fails
```

**To Reproduce**
I have a contrived project that showcases that issue:

https://github.com/YoEight/cabal-weird-bug

`dep-lib` uses `TemplateHaskell` to embed a file into the binary (using `file-embed` package). `dep-exe` is an executable that uses `dep-lib`. While `v2-build` passes, `v2-install` fails with that
error message:

```
~/c/cabal-weird-bug ❯❯❯ cabal v2-install dep-exe                             
Wrote tarball sdist to
/home/ylaupa/code/cabal-weird-bug/dist-newstyle/sdist/dep-lib-0.1.0.0.tar.gz
Wrote tarball sdist to
/home/ylaupa/code/cabal-weird-bug/dist-newstyle/sdist/dep-exe-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - dep-lib-0.1.0.0 (lib) (requires build)
 - dep-exe-0.1.0.0 (exe:dep-exe) (requires build)
Starting     dep-lib-0.1.0.0 (lib)
Building     dep-lib-0.1.0.0 (lib)
Warning: Some package(s) failed to build. Try rerunning with -j1 if you can't
see the error.

Failed to build dep-lib-0.1.0.0.
Build log (
/home/ylaupa/.cabal/logs/ghc-8.6.5/dep-lib-0.1.0.0-f2a39409273d0c34f2209f9a3417e86fbf060a4e
0cf92a0d50f4ca326811f9b2.log
):
Configuring library for dep-lib-0.1.0.0..
Preprocessing library for dep-lib-0.1.0.0..
Building library for dep-lib-0.1.0.0..
[1 of 1] Compiling Lib              ( Lib.hs, dist/build/Lib.o )

Lib.hs:8:11: error:
    • Exception when trying to run compile-time code:
        etc/foo.txt: openBinaryFile: does not exist (No such file or directory)
      Code: embedFile "etc/foo.txt"
    • In the untyped splice: $(embedFile "etc/foo.txt")
  |
8 | fooFile = $(embedFile "etc/foo.txt")
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build dep-lib-0.1.0.0 (which is required by exe:dep-exe from
dep-exe-0.1.0.0). See the build log above for details.


```

**Expected behavior**
`v2-install` should succeed if `v2-build` does.

**System informataion**
 - OS: Ubuntu 18.04 LTS
 - Cabal: 2.4.1.0
 - GHC: 8.6.5 

**Additional context**

Thanks for your time.

**Comment by naglalakk** [comment]
Lib.hs:8:11: error:
    • Exception when trying to run compile-time code:
        etc/foo.txt: openBinaryFile: does not exist (No such file or directory)
      Code: embedFile "etc/foo.txt"
    • In the untyped splice: $(embedFile "etc/foo.txt")

are you sure this is not an issue with your file? the error seems to be indicating that it cannot find your file and therefor it cannot install. It tries to run it on install I guess and that's where it differs.

**Comment by phadej** [comment]
add `etc/foo.txt` to `extra-source-files`.

**Comment by YoEight** [comment]
Hello @phadej. Thanks, it did solve the issue, but I still think a bug remains here. Why `new-build` even builds? `new-build` produces a binary too. I know it's not `stack` repo, but `stack` doesn't fail on `stack install` on this instance, while still using `Cabal` internally. 

Consider the following situation, imagine `dep-lib` from my contrived project was actually on Hackage, I could have built and uploaded it on Hackage but would have broken a user of `dep-lib` build with it.

This situation defers from forgetting a module in `exposed-modules` or `other-modules` sections because `dep-lib` build would have failed. On this issue situation, I can't track I forgot to add `etc/foo.txt` in `extra-source-files` because the CI would have passed anyway.

**Comment by phadej** [comment]
If you use something like [`haskell-ci`](https://github.com/haskell-CI/haskell-ci) which does `sdist` before building, CI would failed.

**Comment by YoEight** [comment]
Thank you for pointing me to `haskell-ci`
