### ISSUE TITLE
jobs-Argument not parsed correctly

### ISSUE THREAD

**Issue by power-fungus** [haskell/cabal#6120]
**Describe the bug**
Argument for the number of jobs is not correctly parsed in `cabal-install` when using different styles

**To Reproduce**

```
$ cabal v2-build -j 1
cabal: Unknown target '1'.
There is no component '1'.
The project has no package '1'.

$ cabal v2-build --jobs 1
cabal: Unknown target '1'.
There is no component '1'.
The project has no package '1'.

$ cabal v2-build --jobs=1
[Works fine]
```

**Expected behavior**
Build with 1 job in all 3 cases.

**System informataion**
 - archlinux, also tested on fedora
 - `cabal-install version 2.4.1.0`

**Additional context**

**Comment by phadej** [comment]
Because value-less `-j` is also accepted, i.e.

```
cabal v2-build -j
```

a value have to be "attached" to the command line option. Otherwise parsing would be ambiguous.

---

Also

```
% ghc -j 1
target ‘1’ is not a module name or a source file
```

---

I'm personally not a fan of optional values for arguments, and for `-j` it's not so useful, maybe. I don't remember if we have other cli options which take optional value.

**Comment by power-fungus** [comment]
So this is expected behaviour? What default-value is used for `-j`? Where is this documented?

**Comment by phadej** [comment]
E.g. in the `--help` message.

```
% cabal v2-build --help|grep -A 2 -- -j
 -j --jobs[=NUM]                                         Run NUM jobs simultaneously
                                                         (or '$ncpus' if no NUM is
                                                         given).
```

**Comment by power-fungus** [comment]
My mistake. I only looked at `cabal --help`.

Is it possible to give an argument to `-j`?

**Comment by phadej** [comment]
@power-fungus of course, sorry for not understanding your problem right away. Simply attach number to `-j`: 

```
cabal v2-build -j4
```

**Comment by power-fungus** [comment]
Fine. This is certainly not as expected but not an issue.
