### ISSUE TITLE
Cabal 3: Incorrect handling of constraints

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#6121]
**Describe the bug**
Currently using cabal version 3 from git (commit `ed3ae133`) and working on https://github.com/input-output-hk/cardano-sl-x509 (commit `e8bfc129`) . The cabal file has:
```
                  , ip < 1.5,
```
but building it I get:
```
src/Data/X509/Extra.hs:52:1: error:
    Could not load module ‘Net.IPv6’
    It is a member of the hidden package ‘ip-1.4.2.1’.
    Perhaps you need to add ‘ip’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘ip-1.4.2.1’.
    Perhaps you need to add ‘ip’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘ip-1.4.2.1’.
    Perhaps you need to add ‘ip’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘ip-1.4.2.1’.
    Perhaps you need to add ‘ip’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```
Changing that constraint to:
```
               , ip == 1.4.*
```
and it builds correctly.

**To Reproduce**
```
$ git clone https://github.com/input-output-hk/cardano-sl-x509
$ cd cardano-sl-x509
$ git checkout -b test e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4
$ cabal v2-build
```
Same problem as above with cabal version 2.4 and `v2-build`.

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
A constraint like `ip < 1.5` should work correctly.

**System informataion**
 - Linux
 - cabal install from git, revision `ed3ae133`
 - ghc-8.6.5

**Comment by phadej** [comment]
There's nothing wrong, on my machine:

```
 ├─ cardano-sl-x509-3.0.0
 │  ├─ base64-bytestring-1.0.0.2
 │  │  └─ bytestring-0.10.8.2
 │  │     └─ deepseq-1.4.4.0 ┄┄
 │  ├─ ip-0.6.0
 │  │  └─ aeson-1.4.4.0
 │  │     ├─ attoparsec-0.13.2.2
```

And this is valid as it's in specified (`ip <1.5`) range. Often enough install-plans aren't comprable. Due traversal order in solver, it picks `hashable-1.3` and `primitive-0.7` forcing to pick quite old `ip`; yet if `ip` bound has lower-bound then older `hashable-1.2.7.0` and `primitive-0.6.4.0` are selected.

```diff
--- upper.txt	2019-07-01 12:02:16.612727200 +0300
+++ wild.txt	2019-07-01 12:01:56.420972237 +0300
@@ -32,14 +32,14 @@
 ghc-boot-th-8.6.5
 ghc-prim-0.5.3
 happy-1.19.11 exe:happy setup
-hashable-1.3.0.0
+hashable-1.2.7.0
 haskell-lexer-1.0.2
 hedgehog-1.0
 hourglass-0.2.12
 hsc2hs-0.68.4 exe:hsc2hs
 integer-gmp-1.0.2.0
 integer-logarithms-1.0.3
-ip-0.6.0
+ip-1.4.2.1
 libyaml-0.1.1.0
 lifted-async-0.10.0.4
 lifted-base-0.2.3.12
@@ -55,7 +55,7 @@
 pretty-1.1.3.6
 pretty-show-1.9.5
 pretty-show-1.9.5 exe:ppsh
-primitive-0.7.0.0
+primitive-0.6.4.0
 process-1.6.5.0
 QuickCheck-2.13.2
 random-1.1
```

A solution is to specify (lower) bounds.

**Comment by erikd** [comment]
Ok, thanks @phadej !

Closing this.
