### ISSUE TITLE
cabal (new-)install produces "~/.cabal/bin: createDirectory: does not exist (No such file or directory)" on mac

### ISSUE THREAD

**Issue by josefs** [haskell/cabal#6145]
**Describe the bug**
Whenever I do cabal (new-)install of a package, the package seems to build fine but when it comes to actually installing it, I get:

    ~/.cabal/bin: createDirectory: does not exist (No such file or directory)

**To Reproduce**
Do `cabal new-install <some package>`. 

I'm on mac.

**Expected behavior**

The package/binary should just be installed.

**System informataion**
 - macOs 10.14.5
 - cabal-install version 2.4.1.0
 - compiled using version 2.4.1.0 of the Cabal library

**Comment by juev** [comment]
I have the same issue:

```bash
cabal install --installdir=~/.local/bin --overwrite-policy=always --install-method=copy stylish-haskell
```

produced issue:

```bash
Resolving dependencies...
Up to date
~/.local/bin: createDirectory: does not exist (No such file or directory)
```

Tried absolute url, like `/home/username/.local/bin`, result the same.

**Comment by phadej** [comment]
Cannot reproduce with `cabal-insall-3.4-rc3`:

```
% cabal install --installdir=/tmp/freshdirectory --overwrite-policy=always --install-method=copy alex      
...
Copying 'cabal-fmt' to '/tmp/freshdirectory/alex'
```

**Comment by phadej** [comment]
Note: `--installdir=~/.local/bin` is not expanded by shell. Use `--installdir=$HOME/.local/bin`

**Comment by juev** [comment]
@phadej my fail, with $HOME its worked! Thank you!
