### ISSUE TITLE
Cannot expose posixSecondsToUTCTime from time package to cabal new-build

### ISSUE THREAD

**Issue by julian1** [haskell/cabal#6154]
Version
-----------------
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library

Steps to reproduce
-----------------

I want to use posixSecondsToUTCTime from https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-Clock-POSIX.html

```
$ cabal new-build test03

src/test/Test03.hs:28:1: error:
    Failed to load interface for ‘Data.Time.Clock.UTC’
    it is a hidden module in the package ‘time-1.6.0.1’
```

But my cabal has a reference to time which should expose it to the build?

```
-- common stanzas
common deps
  build-depends:      base >=4.9 && <4.10,
                      http-client >= 0.6.4,
                      http-types,
                      bytestring,
                      aeson >= 1.4.3.0,
                      keccak >= 0.2.0,
                      base16-bytestring,
                      text,
                      mtl >= 2.2.2,
                      http-client-tls >= 0.3.5.3,
                      case-insensitive,
                      time,                       <-- here
                      cryptohash-sha256 

executable test03
  import:             deps
  main-is:            Test03.hs
  hs-source-dirs:     src/test
  build-depends:      helpers
```

Weirdly, there's no local time package installed,

```
$ ghc-pkg list --package-db=$HOME/.cabal/store/ghc-8.0.1/package.db/ time
/home/me/.cabal/store/ghc-8.0.1/package.db/
    (no packages)

```
 

However a global version of the lib is installed. And the version 1.6.0.1, matches the version the compiler complains is hidden. This suggests cabal is looking outside the local packages?

```
$ ghc-pkg list time
/usr/lib/ghc/package.conf.d
    time-1.6.0.1

$ ls -ld /usr/lib/ghc/time-1.6.0.1
drwxr-xr-x 4 root root 4096 Apr  9  2018 /usr/lib/ghc/time-1.6.0.1
```

If I try to uninstall the global version - in the hope it might force a local instance to be installed - I get a message that it will would break my installed compiler, which is apt-get installed when i installed xmonad. I would prefer not to break my desktop environment.

```
$ ghc-pkg unregister time-1.6.0.1
ghc-pkg: unregistering would break the following packages: ghc-8.0.1 ...
```

Trying a different approach to forcefully install all cabal libraries locally gets a different complaint,

```
$ cabal new-install --lib
Resolving dependencies...
Up to date
Warning: The current compiler doesn't support safely installing libraries, so
only executables will be available. (Library installation is supported on GHC
8.0+ only)
```

So how can I hide the global version, so that cabal installs the local version which can be included. Or alternatively, how can I unhide the global version?

Adding the following package include option directly for the compiler doesn't change the behavior

```
ghc-options:        -O2 -package time-1.6.0.1
```

Also trying the following to expose the global version, also does not change behavior

```
sudo ghc-pkg expose time-1.6.0.1
```

**Comment by phadej** [comment]
What are the contents (or imports) of  `Test03.hs`

Are you sure you do

```haskell
import Data.Time.Clock.POSIX
```

and not

```haskell
Import Data.Time.Clock.UTC
```

**Comment by julian1** [comment]
@phadej  Thank you. 

Yes I was importing Data.Time.Clock.UTC. Code was this
```
import Data.Time.Clock.POSIX
import Data.Time.Clock.UTC

millisToUTC :: Integer -> UTCTime
millisToUTC t = posixSecondsToUTCTime $ (fromInteger t) / 1000
```

which works following your suggestion, when changed to,
```
import Data.Time.Clock.POSIX
import Data.Time.Clock

millisToUTC :: Integer -> UTCTime
millisToUTC t = posixSecondsToUTCTime $ (fromInteger t) / 1000
```

I confess I still can't interpret the error message, or why the time library was not being pulled in correctly. With the good imports, the code still looks like it has a dependency on the library.

```
*Main> :t  posixSecondsToUTCTime
posixSecondsToUTCTime :: POSIXTime -> UTCTime
*Main> :t  UTCTime
UTCTime
  :: time-1.6.0.1:Data.Time.Calendar.Days.Day -> DiffTime -> UTCTime
*Main> :t  POSIXTime
```

**Comment by phadej** [comment]
@julian1 the `time` library is pulled correctly.

In its definition there are 

```
exposed-modules: Data.Time.Clock Data.Time.Clock.POSIX, ...
other-modules: Data.Time.Clock.UTC, ...
```

from the outside, you **cannot** import non-exposed, `other-modules`. The module is **hidden**, in the same way you may write a module

```haskell
module Foo (Bar, mkBar) where

data Bar = ...

mkBar :: Int -> Bar
mkBar = ...
```

not exposing the implementation details.

**Comment by julian1** [comment]
@phadej Thank you for explaining.
