### ISSUE TITLE
SPDX license list 3.6 2019-07-10

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6170]
@bgamari would it be acceptable to make the change for 3.0 still?

It will be technically a breaking change to currently tagged `3.0-rc3` (`LicenseId` etc type would change), but I doubt it would really break anyone. (EDIT: I assume it's "monotonic" update, so only new identifiers added, nothing removed).

**Comment by bgamari** [comment]
I agree that it's unlikely that the additions will break anyone. Feel free to merge.
