### ISSUE TITLE
v2-test with GHCJS doesn't work

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6175]
**Describe the bug**

`cabal-install` (or `Cabal`?) doesn't know how to run tests.

**To Reproduce**

Take e.g. `splitmix` package

```
$ cabal v2-test
...
cabal: Error: Could not find test program
"/code/public-haskell/splitmix/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/splitmix-0.0.3/t/examples/build/examples/examples".
Did you build the package first?
```

That's close, but one needs to do something like:

```
% node /code/public-haskell/splitmix/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/splitmix-0.0.3/t/examples/build/examples/examples.jsexe/all.js
SMGen 142593372 1604540297
```

I'm not sure how GHCJS finds `node` executable, does it just looks in the PATH?

**Expected behavior**

Tests should run.

**System informataion**
 - Operating system: Ubuntu-18.04
 - `cabal-install-3.0`, `ghcjs-8.4` from HVR's ppa:ghc and ppa:ghcjs

**Comment by dfordivam** [comment]
This is a regression in the functionality as the `-build-runner` option was removed in this commit https://github.com/haskell/cabal/pull/6025/commits/c4701546b55158b77177ce3e69d8a1f6873e45dc

I confirmed this issue with ghcjs 8.10.5 as well. And passing this option manually (`--ghcjs-options=-build-runner`) the `cabal test` works.

It is not clear from the commit why the option was removed (perhaps there is an alternate way to use ghcjs?) 

Though this option is still being used here https://github.com/haskell/cabal/blob/2bd058885bbf411dd7c93bbb12595a4667ce344d/cabal-install/src/Distribution/Client/SetupWrapper.hs#L854

@luite might be able to clarify
