### ISSUE TITLE
Cabal should calculate the package key the same way cabal-install does

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#6192]
**Describe the bug**
Building libraries using Cabal, with or without tests enabled gives different pkg id/key hashes.
This has been happening for a long time - during most (all?) of Cabal-2.*?

**To Reproduce**

```
$ cabal unpack zlib-0.6.2
$ cd zlib-0.6.2
$ runghc Setup configure
$ runghc Setup build
$ runghc Setup install
$ ghc-pkg field zlib id

$ cd ..
$ rm -r zlib-0.6.2
$ cabal unpack zlib-0.6.2
$ cd zlib-0.6.2
$ runghc Setup configure --enable-tests
$ runghc Setup build
$ runghc Setup install
$ ghc-pkg field zlib id
```

**Expected behavior**
Same package id/key whether tests enabled or not.

**Actual behaviour**
Package id/key depends on whether tests enabled or not.

**System informataion**
 - Operating system: Fedora Linux
 - ghc-8 and Cabal-2 (and 3.0)

**Comment by phadej** [comment]
@juhp are you 100% sure something obvious doesn't change, i.e. which packages `zlib` depends upon then?

---

That said, we need a debug output (at high verbosity level) of what things go into package hash, I was wondering about that.

**Comment by juhp** [comment]
Yep there are testsuite deps on tasty*.

**Comment by juhp** [comment]
Just to explain/motivate - this is very annoying because it means when enabling or disabled tests in say a distro like Fedora - the hashes will change...

**Comment by phadej** [comment]
I'm sorry, I misread the description initially; you use `./Setup` i.e. not `cabal v2-build`. In this case I advice just to tell `Setup` which IPID you want, and not rely on it computing something deterministically. (`cabal v2-build` computes them, and tells `./Setup` scripts explicitly as well).

```
% runghc -package-env=- Setup.hs configure -v --ipid=zlib-0.6.2.1
Using Parsec parser
Configuring zlib-0.6.2.1...
Flags chosen: non-blocking-ffi=False, pkg-config=False
Dependency base >=4 && <4.14: using base-4.12.0.0
Dependency bytestring >=0.9 && <0.11: using bytestring-0.10.8.2
Source component graph: component lib
Configured component graph:
    component zlib-0.6.2.1
...
```

**Comment by juhp** [comment]
Okay I need to read how cabal-install calculates ipid then...
I don't think zlib-0.6.2.1 is not good enough to prevent ghc-pkg dependency breakage, right?
But I think if Setup just excluded testsuites and benchmarks from ipid that would be good enough.

> Yet, that way you won't rebuild nor reinstall the library components; which works accidentally - i.e. is not really a good design.

Sorry, I didn't understand this sentence. So it is better or not?

**Comment by juhp** [comment]
Very slow, I know, but I finally tested this and got:

`Setup: --cid is only supported for per-component configure`

**Comment by phadej** [comment]
`Cabal` doesn't *calculate* hashes. It uses the one its told.

We will not add the logic of `cabal-install` to `Cabal`. `Cabal` is stupid interface which is does what a higher level program tells it. If you want to replicate the very same ids `cabal-install` would produce in nix-style store or otherwise, you have to replicate that logic yourself.

I mght not be understanding what's the problem, yet `--cid`, `--exact-configuration` and specifying components is how you tell `Cabal` what to do.
