### ISSUE TITLE
cabal-install `new-build` configure is broken

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#6208]
**Describe the bug**
When building a large number of packages the following error occurs

```
Linking ...\ghc-paths-0.1.0.12\dist\setup\setup.exe ...
unrecognized 'configure' option `--disable-executable-static'
```

Seems to happen when there's a custom setup and caused by #5446 and makes `new-build` unusable.

```
Failed to build ghc-paths-0.1.0.12. The failure occurred during the configure
step.
Build log (
C:\Users\Tamar\AppData\Roaming\cabal\logs\ghc-8.7.20181216\ghc-paths-0.1.0.12-6da92f8e6da78aead5f62a2faad6a24c5827a743.log
):
[1 of 1] Compiling Main             ( ...\ghc-paths-0.1.0.12\dist\setup\setup.hs, ...\ghc-paths-0.1.0.12\dist\setup\Main.o )
Linking ...\ghc-paths-0.1.0.12\dist\setup\setup.exe ...
unrecognized 'configure' option `--disable-executable-static'

Failed to build happy-1.19.11. The failure occurred during the configure step.
Build log (
C:\Users\Tamar\AppData\Roaming\cabal\logs\ghc-8.7.20181216\happy-1.19.11-76230f8fd2444683ee1e6c3d155bd6fa464d702d.log
):
[1 of 1] Compiling Main             ( ...\happy-1.19.11\dist\setup\setup.hs, E:\ghc-dev\msys64\home\Tamar\HaskellDevChoco\tools\haskell-ide-engine\dist-newstyle\tmp\src-22205\happy-1.19.11\dist\setup\Main.o )
Linking ...\happy-1.19.11\dist\setup\setup.exe ...
unrecognized 'configure' option `--disable-executable-static'
```

and am unable to build a large number of packages now using `cabal 3.0` and `new-build`.

Latest nightly head is still broken. `cabal-head v3.1.0.0-B20190823`

**To Reproduce**
I can reliably hit it when trying to build `hie`, a large number of packages fail. I suspect trying to build any of them in isolation would probably trigger it to but didn't check.

```
$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System informataion**
 - Windows 10
 - The Glorious Glasgow Haskell Compilation System, version 8.7.20181216
 - cabal-install version 3.1.0.0
    compiled using version 3.1.0.0 of the Cabal library

**Comment by hvr** [comment]
@Mistuke I couldn't reproduce this with a very recent GHC 8.8.1 snapshot; I'm wondering if you're running into this because of the quite old GHC 8.7 snapshot from 2018 which bundled a fairly old lib:Cabal which probably interacts badly with the setup-wrapper flag filtering logic...

**Comment by Mistuke** [comment]
@hvr Ah, indeed, it seems that 8.6.5 and 8.9.0-B020190824 work, so must have been a mismatch. Sorry for the noise!
