### ISSUE TITLE
Add --benchmark-options option

### ISSUE THREAD

**Issue by sjakobi** [haskell/cabal#6209]
…in analogy to `--test-options`.

For now, I can use `cabal run` to run benchmarks with arguments, but that doesn't work for benchmarks that try to open files by relative paths.

**Comment by symbiont-sam-halliday** [comment]
Note https://github.com/haskell/cabal/issues/6114#issuecomment-526218750 which is somewhat relevant.

**Comment by RyanGlScott** [comment]
I took a shot at this in #6224. It mostly works, although there are some unresolved issues to work out, such as the one observed in https://github.com/haskell/cabal/pull/6224#issuecomment-528666158.

**Comment by Boarders** [comment]
Just to quickly say I ran into this and would appreciate this feature, is it still on the agenda somewhere?

**Comment by sjakobi** [comment]
@Boarders It was released in `cabal-install-3.2.0.0`.
