### ISSUE TITLE
cabal user-config update silently enables remote-build-reporting

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#6210]
As suggested in #5973  I am doing `cabal user-config update`. 
This silently adds  a  line `remote-build-reporting: anonymous` to the config file (while 
the default setting is `none`).

This is with 
```
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
```

**Comment by hvr** [comment]
I tried with cabal 1.16 (the oldest version I had locally) to see what the default generated `~/.cabal/config` would look like (by invoking it for an empty new user account), and as I suspect it contained 

```
-- build-log:
remote-build-reporting: anonymous
-- one-shot: False
```

Consequently, the default setting for the ~/.cabal/config file has been this way at least since cabal-install 1.16

**Comment by phadej** [comment]
I think in Europe something like that should require explicit consent nowadays. So better to have `remote-building-reporting` off by default. Espcially, as I'm quite sure that the data isn't used for anything.

**Comment by phadej** [comment]
To clarify: It's irrelevant how long the `anonymous` default. Time have gone past it, we care about our privacy.

**Comment by jwaldmann** [comment]
Yes. If `user-config update` asked me to enable reporting (and explains what data is used by whom) I might allow it.

remote-build-reporting is not mentioned in the docs? (try https://www.haskell.org/cabal/users-guide/search.html?q=reporting&check_keywords=yes&area=default )

Also, I am a bit confused: `anonymous` is defined as the default value here? https://github.com/haskell/cabal/blob/7650ce94c4d2b0918f1efa9e7de322a55c57811e/cabal-install/Distribution/Client/Config.hs#L572  But in the auto-generated config file, the line is `remote-build-reporting: anonymous`, not `-- remote-build-reporting: anonymous`, so I thought that the value shown is not the default.

**Comment by phadej** [comment]
I think 6625 fixed this.
