### ISSUE TITLE
Regression from 2.4.1.0 to 3.0 on i686 Windows when building sdl2

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#6215]
**Describe the bug**

With cabal 3.0, building of

https://hackage.haskell.org/package/sdl2

hangs (tested many times, always happens)

https://ci.appveyor.com/project/Mikolaj/lambdahack/builds/27081315/job/6x2alfd71v0swrr2

while after downgrading to cabal 2.4.1.0 it builds fine

https://ci.appveyor.com/project/Mikolaj/lambdahack/builds/27091414/job/k3gvw3lq3r6op0md

**To Reproduce**

use commands as in the appveyor script

https://github.com/LambdaHack/LambdaHack/blob/master/appveyor.yml

with and without the forcing of cabal version.

I can't reproduce locally, because I don't have Windows.

**Comment by Mistuke** [comment]
Is it possible for you to try ghc 8.6.5? Just to rule out an issue with older ghc on 32-bits.

**Comment by Mikolaj** [comment]
Here you go, but apparently I'm doing something wrong: https://ci.appveyor.com/project/Mikolaj/lambdahack/build/job/59b3mkj9ljo046re

**Comment by Mistuke** [comment]
You need to call refreshenv after installing ghc. GHC installs use `PATH` instead of shims like `cabal` installs so they can co-exist. I'm actually surprised you didn't get this error before.

**Comment by Mikolaj** [comment]
refreshenv always failed for me, which was why I needed to remove it. However, this time it goes through fine, but fails elsewhere: https://ci.appveyor.com/project/Mikolaj/lambdahack

**Comment by Mistuke** [comment]
Hmm `refreshenv` should never fail. Alright I'll just clone your repo to take a look.

Also I believe that your appveyor file is much more complicated than it needs to be. Would you be interested in me submitting a cleaner approach?

**Comment by Mikolaj** [comment]
I'd be extatic, but I'm afraid, it's too messed up to unravel. However, do
your worst. :)
21 wrz 2019 11:00 "Tamar Christina" <notifications@github.com> napisał(a):

**Comment by Mikolaj** [comment]
The CI script in question is overcomplicated and will be abandoned once I no longer want to suport 32bit Windows and so can move to a new toolchain. Therefore, let's let it rest. Thank you, again! Closing.
