### ISSUE TITLE
Feature request: upload a new package version from the CLI

### ISSUE THREAD

**Issue by patrickt** [haskell/cabal#6230]
The GitHub Semantic Code team has a large number of packages of which we need to keep track (`tree-sitter`, `tree-sitter-python`, `tree-sitter-ruby`, etc.)

The `cabal sdist && cabal haddock --haddock-for-hackage && cabal-upload` workflow works well for us. However, many of our package updates consist simply of loosened version bounds, and as such we use the Hackage metadata editor in the web interface. We’d like to keep track of revision info in our Git repository, and we’d also like to be able to [automate the process](https://github.com/tree-sitter/haskell-tree-sitter/pull/188) of uploading new revisions of a package rather than editing them by hand in a web browser. 

A look through the documentation didn’t seem to reveal the ability to upload new revisions from the CLI, and manually adding an `x-revision` field and calling `cabal-upload` was rejected by Hackage. Any way to automate the process of loosening version bounds would be much appreciate.

**Comment by hvr** [comment]
@patrickt Are you aware of https://github.com/hackage-trustees/hackage-cli ?

Specifically the commands

```
  pull-cabal               download .cabal files for a package
  push-cabal               upload revised .cabal files
  sync-cabal               upadate/sync local .cabal file with latest revision on Hackage
```

**Comment by patrickt** [comment]
Wasn’t aware of hackage-cli—this looks like exactly what I need! Thank you, @hvr!
