### ISSUE TITLE
`cabal init -i` Cabal version does not list 3.0

### ISSUE THREAD

**Issue by emilypi** [haskell/cabal#6239]
I have the most up to date stable `Cabal` and `cabal-install` (3.0), but the interactive script does not list this as a valid option:

```
λ П(a: A) ~ → cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
```

```
Please choose version of the Cabal specification to use:
 * 1) 1.10   (legacy)
   2) 2.0    (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2    (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4    (+ support for '**' globbing)
Your choice? [default: 1.10   (legacy)]
```

**Comment by Mikolaj** [comment]
This was fixed in the mentioned PR and missed and discarded, done in another commit, improved/updated later on in #7344 and I see both 3.0 and 3.4 as options right now and 3.0 is the default. Closing.
