### ISSUE TITLE
Updated manual

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#6245]
**Describe the bug**
An updated manual for cabal 3.0 is hard to find (if it exists).

**To Reproduce**
Look at https://www.haskell.org/cabal/users-guide/ and see that it is out of date.

Look at https://www.haskell.org/cabal/ and follow link to https://wiki.haskell.org/Cabal/How_to_install_a_Cabal_package and see that it is *very* out of date.

Look at http://hackage.haskell.org/package/cabal-install and find only links to the above resources.

**Expected behavior**
I expected to learn how, precisely, `cabal install` works these days: where it installs libraries, specifically.

**Comment by 23Skidoo** [comment]
Thanks for the bug report. I've updated haskell.org/cabal/users-guide.

@hvr We should set up redirects so that haskell.org/cabal/release points at d.h.o and delete the haskell.org/cabal/release directory because updating multiple places is annoying. Also haskell.org/cabal/users-guide should point at d.h.o as well.

**Comment by 23Skidoo** [comment]
@hvr I can probably do this myself if I get access.

**Comment by goldfirere** [comment]
Thanks for the quick turnaround, @23Skidoo ! The manual still talks about `v2-install`, say, vs `install`. Is that out of date now?

**Comment by fgaz** [comment]
No, install and v2-install are aliases now. I think it's probably better to explicitly keep the v2 prefix in the manual until the majority of people has cabal >=3

**Comment by gbaz** [comment]
i think pointing at readthedocs and the ongoing work updating the guide there suffices to close this.
