### ISSUE TITLE
Using GHC plugins causes non-deterministic segmentation faults

### ISSUE THREAD

**Issue by sheaf** [haskell/cabal#6251]
I've attached a simple cabal project making use of a type-checking plugin (in this case `ghc-typelits-knownnat`). [PluginCrash.zip](https://github.com/haskell/cabal/files/3645134/PluginCrash.zip)
Using GHC 8.8.1 in conjunction with cabal-install 3.0.0.0, on Windows 10 x64, running `cabal repl` on the project causes a variety of segmentation faults and hangs.

<p>
<details>
<summary> Show/hide error messages.</summary>
<pre><code>Access violation in generated code when reading 0x6d9f4

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x45fdab0    0x14369014 C:\Haskell\GHC\ghc-8.8.1\lib\ghc-8.8.1\libHSghc-8.8.1.a(PrimOp.o)+0xe94
                 (ghc_PrimOp_primOpTag_info+0xbd9c)

Access violation in generated code when reading 0x0

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x45fdab0    0x10e9d993 C:\Haskell\GHC\ghc-8.8.1\lib\ghc-8.8.1\libHSghc-8.8.1.a(NameCache.o)+0x4c3
                 (ghc_NameCache_lookupOrigNameCache_info+0x9c5)

Access violation in generated code when reading 0x7c58

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x45fdab0    0x14c57b8f C:\Haskell\GHC\ghc-8.8.1\lib\ghc-8.8.1\libHSghc-8.8.1.a(TysWiredIn.o)+0x1a52f
                 (ghc_TysWiredIn_isBuiltInOcczumaybe_info+0x1651)

ghc.exe: internal error: evacuate(static): strange closure type 0
    (GHC version 8.8.1 for x86_64_unknown_mingw32)

ghc.exe: internal error: evacuate(static): strange closure type 51339
    (GHC version 8.8.1 for x86_64_unknown_mingw32)

ghc.exe: internal error: evacuate(static): strange closure type 2949221
    (GHC version 8.8.1 for x86_64_unknown_mingw32)

Access violation in generated code when executing data at 0xa00

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x45fdab0    0xa00

Access violation in generated code when executing data at 0x1b98

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x45fdab0    0x1b98
</code></pre>

</details>
</p>

I originally believed this regression was introduced with GHC 8.8.1 (see [trac ticket](https://gitlab.haskell.org/ghc/ghc/issues/17236)), however `ghci` works just fine whereas `cabal repl` does not.    
I can confirm that the combination GHC 8.6.5 + Cabal 2.4.1.0 does not suffer from this bug. I also recall using alpha versions of GHC 8.8 with a version of cabal-install that I built from source before the 3.0.0.0 release, and not running into this issue either (I'm afraid I'm unable to provide a more precise timeline than that). I tried building the latest version of cabal-install from this repository, but the issue remained the same.

**Comment by 23Skidoo** [comment]
If you run `cabal repl` with `-v3` it'll show you the command-line invocation that Cabal uses.

**Comment by sheaf** [comment]
OK thank you, it seems that removing command line arguments to ghci causes the error to happen much less frequently but not go away completely, so I assume this is not a cabal issue. Thanks.
