### ISSUE TITLE
cabal user-config update on windows

### ISSUE THREAD

**Issue by coot** [haskell/cabal#6253]
**Describe the bug**
`cabal user-config update` from `cabal-2.4.0.0` to `cabal-3.1.0.0` (current master), replaced:
```
extra-include-dirs: C:\Program Files\Haskell Platform\8.6.5\mingw\include
```
with
```
extra-include-dirs: C:\Program,
                    Files\Haskell,
                    Platform\8.6.5\mingw\include
```
while it should replace it with:
```
extra-include-dirs: "C:\\Program Files\\Haskell Platform\\8.6.5\\mingw\\include"
```

**To Reproduce**

```
$ cabal user-config update
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System informataion**
 - Operating system: Windows 10
 - `cabal`, `ghc` versions: `cabal-3.1.0.0`, `ghc-8.6.5`

**Additional context**

**Comment by 2mol** [comment]
Hi everybody! I can here to open the same issue. Thanks to coot I now know how to properly quote the path, so thanks!

It currently results in an unfortunate caveat/warning for a beginner install guide that I'm working on: https://github.com/zfoh/haskell-simple-install#some-remarks-about-cabal-on-windows

I'm not familiar with the cabal codebase, could somebody point me towards where this path string is created? I reckon it shouldn't be too hard to fix.

**Comment by phadej** [comment]
I'm not sure how `C:\Program Files\Haskell Platform\8.6.5\mingw\include` without quotes worked in the first place, that's invalid syntax.

**Comment by phadej** [comment]
@2mol ask people to install `Cabal` using chocolatey, https://hub.zhox.com/posts/introducing-haskell-dev/

@Mistuke worked out most of the culprits one could have while installing GHC and Cabal.
I'd **recommend not** to use Haskell Platform.

**Comment by 2mol** [comment]
Thanks for the insights @phadej, will evaluate chocolatey.

Do you know if it's being discussed to remove Haskell Platform as the recommended (and only) way to install Haskell on Windows on haskell.org?

**Comment by phadej** [comment]
There have been enough drama about haskell.org downloads page, so I think no one is brave enough to propose any changes.

**Comment by 2mol** [comment]
Ha, ok, I'll stay away from it :) Thanks for the help!

**Comment by Mistuke** [comment]
> Ha, ok, I'll stay away from it :) Thanks for the help!

Every so often you have a bikeshedding attempt again. Latest is https://github.com/haskell-infra/www.haskell.org/issues/12 but no response from anyone at haskell.org. At this point it's not a fight worth fighting :)
