### ISSUE TITLE
Can't build `happy`

### ISSUE THREAD

**Issue by harpocrates** [haskell/cabal#6260]
**Describe the bug**
I expect to be able to build [`happy`](https://github.com/simonmar/happy) but I can't.

**To Reproduce**

```
$ git clone https://github.com/simonmar/happy.git
$ cd happy && git checkout 3ea1aa76d9a2e87f23fde830b1e42d62e20c3f4c
$ cabal v2-build
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - happy-1.19.12 (exe:happy) (first run)
Configuring executable 'happy' for happy-1.19.12..
Preprocessing executable 'happy' for happy-1.19.12..
happy: /Users/atheriault/Documents/code/happy/./data//HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
```

**Expected behavior**
I should be able to build `happy`. 😄 

**System informataion**
 - Operating system: macOS
 - `cabal` (from `ghcup install-cabal`): 3.0.0.0
 - `ghc` (also all from `ghcup`):  tried all of 8.8.1, 8.6.5, and 8.4.4

**Additional context**
I can build other projects that use `happy`, just not `happy` itself. Having `happy` on (or not on `$PATH`) made no difference.

**Comment by phadej** [comment]
This is not a cabal issue. Look at Makefile in happy repository. Maybe `make sdist` or `cabal new-run gen-happy-sdist` will create needed local files, and maybe there should be a note in Readme.

**Comment by harpocrates** [comment]
Oh I see (and build) now. The happy README is indeed missing some important information. Thanks!
