### ISSUE TITLE
Cabal cannot find installed library

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#6265]
**Describe the bug**
I have installed a library, but cabal cannot find it.

**To Reproduce**

Create two packages, `wiz` and `woz`. Both contain only libraries. Have `woz` depend on `wiz`.

```
$ cd wiz
$ cabal v2-install --lib wiz
$ cd ../woz
$ cabal v2-install --lib woz
```

Witness the error that `wiz` is unknown.

**Expected behavior**
I expected `woz` to install, using the `wiz` that was already installed. (I do see `wiz` in my global env file.) `--alow-depending-on-private-libs` doesn't help (though I'm not sure if that's relevant -- just a guess in the dark). 

**System informataion**
 - Mac
 - `cabal 3.0.0.0`
 - `ghc HEAD` (ish)

**Additional context**
Perhaps I'm going about things the wrong way, so I'll describe my actual use case.

I wish to experiment with the linear types extension to GHC. So I build locally the linear-types branch. But actually, I need to see how some libraries are interacting. (Specifically, `inline-java`.) I try `cabal install --lib --with-ghc=xyz` in `inline-java`. This runs into trouble when installing `th-desugar`, a dependency, because of a bug in the GHC branch that can't deal with some code in `th-desugar`. So I make a local clone of `th-desugar`, and rewrite the bit of `th-desugar` that causes trouble. I then install with `cabal install --lib --with-ghc=xyz`. Now I return to my main task: installing `inline-java`. But `inline-java` says it doesn't know where to find `th-desugar`. :(

At this point, I'm really stuck -- I don't have a workaround, and now I can't complete the task I wanted to. Help?

**Comment by phadej** [comment]
This use-case won't work. `cabal v2-install --lib` is to make libraries available for dummy tools (like GHCi), `cabal` itself ignores that global state.

---

What you should do is create a *project*: https://cabal.readthedocs.io/en/latest/nix-local-build.html#configuring-builds-with-cabal-project then, you could install stuff. E.g. with `cabal.project`

```
packages: dec
packages: fin
packages: vec
```

I can `cabal install --lib vec` (which depends on `dec` and `fin`).

To add, you can specify `with-compiler: /path/to/linear-ghc` in `cabal.project` too. But I'd rather use `cabal repl`

---

I.e. in your case

`cabal.project`

```
with-compiler: /path/to/linear-ghc
packages: th-desugar/
packages: inline-java-experiments/
```

`inline-java-experiments/inline-java-experiment.cabal`

```cabal
cabal-version: 2.4
name: inline-java-experiment
version: 0

library
  default-language: Haskell2010
  build-depends: base, inline-java
  exposed-modules: Scratch
```

were `inline-java` and `th-desugar`. Most likely, you'd write some test-code using `inline-java`, so it doesn't need to be local package.

**Comment by goldfirere** [comment]
I have a slightly different use-case in this space, and I'd love to understand how to adapt your approach to my other use-case:

`th-desugar` and `singletons` are independent packages, but they are co-developed. That is, often a need in `singletons` directly inspires changes in `th-desguar`. (`singletons` depends on `th-desguar`.) My usual workflow is to make the changes in `th-desugar`, then install it into my global env, then try to test things in `singletons`. If `cabal` won't see the `th-desugar` in my env, then I can't use e.g. `cabal test` when working on `singletons`, can I?

My guess is that I need to then put the two in some larger `cabal.project` file. Is that right? Does that mean that I need to make a separate directory hosting the combined project? Ideally, I won't have to edit any (persisted) file in either project, as I wouldn't want to expose my internal workflow in e.g. the git histories of the projects.

Thanks!

**Comment by phadej** [comment]
> My guess is that I need to then put the two in some larger cabal.project file. Is that right?

Yes.

> Does that mean that I need to make a separate directory hosting the combined project?

Not necessarily. Let's assume that you have packages in the same top directory

```
haskellprojects/singletons
haskellprojects/th-desugar
```

Then you can in `singletons` directory add a `cabal.project.local` (which you should have in global or project specific `.gitignore`, as it's local):

```
packages: ../th-desugar
```

as there's really no hard technical reason to have project sources "below" cabal.project.

I also sometimes `ln -s ../th-desugar .`, so I can more easily navigate to the dependency, but you get an idea.
