### ISSUE TITLE
Cabal user-config updates breaks password-command

### ISSUE THREAD

**Issue by merijn** [haskell/cabal#6268]
`cabal user-config update` linebreaks a `password-command` containing spaces into multiple lines separated by commas (resulting in a command that obviously can't work).

**To Reproduce**
Have a `~/.cabal/config` where `password-command` contains spaces and run `cabal user-config update`.

**Comment by gbaz** [comment]
does it/could it work btw if the command was enclosed in quotes?

**Comment by liskin** [comment]
No, enclosing the command in quotes doesn't work:

* it results in `"firstword: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`
* spaces are still replaced with commas

This also affects the `--augment` option of `cabal user-config`:

```
$ cabal user-config init -f -a 'password-command: hello world'
Writing default configuration to /home/tomi/.cabal/config

$ grep password-command: ~/.cabal/config
password-command: hello,world
```

```
$ cabal user-config init -f -a 'password-command: "hello world"'
Writing default configuration to /home/tomi/.cabal/config

$ grep password-command: ~/.cabal/config
password-command: "hello,world"
```

**Comment by liskin** [comment]
And for some added fun, it replaces not just spaces, but also nonbreakable spaces (U+00A0) and tabs (U+0009).

**Comment by frasertweedale** [comment]
I'm investigating this issue (because it is impacting me).

**Comment by frasertweedale** [comment]
Pull request incoming (tomorrow)
