### ISSUE TITLE
Parse error when trying to use multiple public libraries within mixins

### ISSUE THREAD

**Issue by chshersh** [haskell/cabal#6281]
**Describe the bug**

I have the following lines in my `.cabal` file:

```cabal
  build-depends:       containers-backpack:{ int-strict, ordered-strict, unordered-strict, contrib }

  mixins:              containers-backpack:contrib (Map.Contrib.Group as Map.Contrib.Group.Int)
                                          requires (Map as Map.Int)
```

Here `containes-backpack` is a package with the public library `contrib` inside it. However, when trying to build this package with `cabal-install` I see the following error:

```
Errors encountered when parsing cabal file ./containers-backpack.cabal:

containers-backpack.cabal:142:43: error:
unexpected ':'
expecting "-", white space, "(", "hiding", "requires", comma or end of input

  140 |   build-depends:       containers-backpack:{ int-strict, ordered-strict, unordered-strict, contrib }
  141 | 
  142 |   mixins:              containers-backpack:contrib (Map.Contrib.Group as Map.Contrib.Group.Int)
      |                                           ^
```

**To Reproduce**

You can find full code here:
* https://github.com/kowainik/containers-backpack/pull/46

1. Clone the repo.
2. Checkout to branch from linked PR.
3. Do `cabal v2-build`

**Expected behavior**

No parse error.

**System informataion**
 - Ubuntu-18.04
 - `cabal-3.0.0.0`
- `ghc-8.6.5` or `ghc-8.8.1`

**Comment by fgaz** [comment]
Might be an instance of #5846.

**Comment by chshersh** [comment]
@fgaz Thanks for pointing to this issue! #5846 is another problem I have. For some reason the following doesn't parse:

```cabal
build-depends: containers-backpack:sig
             , QuickCheck
```

But when I write dependencies in a single line, it parses:

```cabal
build-depends: containers-backpack:sig, QuickCheck
```

> Adding `-any` also parses

Which is for now only a minor UI inconvenience.

**Comment by fgaz** [comment]
Weird… I wonder what's wrong with the parsing code. I wasn't able to find the issue last time I tried to debug this. If you want to take a look at it yourself it's in Cabal/Distribution/Types/Dependency.hs

**Comment by phadej** [comment]
@fgaz this is missing functionality. `Mixin` (**not** `Dependency`) is atm defined as 

```haskell
data Mixin = Mixin { mixinPackageName :: PackageName
                   , mixinIncludeRenaming :: IncludeRenaming }
```

There are no sublibs.
