### ISSUE TITLE
`cabal outdated` needs ghc but has no `--with-compiler` option

### ISSUE THREAD

**Issue by mpilgrem** [haskell/cabal#6283]
The `cabal outdated` command yields this error message (when `ghc` is not on the path):
```
cabal: The program 'ghc' version >=7.0.1 is required but it could not be
found.
```
However, `--with-compiler` is an `unrecognized 'outdated' option`.

That can be contrasted with the `cabal build` command. It also asks for `ghc`, but provides a `--with-compiler` option so that where `ghc` can be found can be specified.

This is on Windows 10 with:
```
cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library
```
(I don't have `ghc` on the path because I tend to use `stack`, which does not need `ghc` on the path.)

**Comment by hvr** [comment]
Duplicate of #4956

**Comment by 23Skidoo** [comment]
Closing in favour of #4956.
