### ISSUE TITLE
Failed to unpack `cabal-doctest-1.0.8`

### ISSUE THREAD

**Issue by mpilgrem** [haskell/cabal#6285]
I have a Travis CI script for a package under GHC 8.8.1 that fails (in a repeatable way) with `cabal-install-3.0.0.0` but works with `stack`. I do not know for sure, but I think it may be a cabal-install-related issue. For example, `stack unpack cabal-doctest-1.0.8` locally (on my Windows 10 machine) works fine but, on the other hand, lots of other packages are downloaded and installed by the cabal command in the script before the failure.

The log is here: https://travis-ci.org/mpilgrem/google-static-maps/jobs/594026369

Extracts from the log include:
```
334  In order, the following will be built (use -v for more details):
342   - cabal-doctest-1.0.8 (lib) (requires download & build)
518  Downloading  cabal-doctest-1.0.8
520  Downloaded   cabal-doctest-1.0.8
800  cabal: Failed to unpack cabal-doctest-1.0.8 (which is required by
801  servant-client-0.16.0.1 and servant-JuicyPixels-0.3.0.5). The exception was:
802  $HOME/.cabal/packages/hackage.haskell.org/cabal-doctest/1.0.8/cabal-doctest-1.0.8.tar.gz:
803  openBinaryFile: does not exist (No such file or directory)
```

**Comment by gbaz** [comment]
Is this a live issue or can we close?

**Comment by mpilgrem** [comment]
In the interim, I've moved away from Travis CI and can't reproduce the set up that I once had. All I can say is my current set up is not troubled in this way.

**Comment by gbaz** [comment]
ok, so let's close for now. thanks!
