### ISSUE TITLE
Make a default-language optional in cabal-version: 3.2

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6288]
It's essentially always `Haskell2010` nowadays.

We can introduce the same `Default` thing as we did with `build-type`

:+1: / :-1: ?

**Comment by hvr** [comment]
I've been wanting to do this as well; the only thing we need however is  to make sure that there's a way to don't send any `-XHaskell2010` at all to GHC (e.g. via  an empty `default-language: ` ?)

**Comment by phadej** [comment]
Is there a way to not-send any -XHaskell* nowadays? Omitting default-language field generates an error, is that wrong?

**Comment by 23Skidoo** [comment]
SGTM.

**Comment by emilypi** [comment]
+1
