### ISSUE TITLE
cabal-install: premature end of compressed stream

### ISSUE THREAD

**Issue by bos** [haskell/cabal#629]
(Imported from [Trac #636](http://hackage.haskell.org/trac/hackage/ticket/636), reported by migmit on 2010-02-18)

$ cabal -v3 update
Downloading the latest package list from hackage.haskell.org
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/0.8.0
Creating new connection to hackage.haskell.org
Received:
HTTP/1.1 200 OK
Date: Thu, 18 Feb 2010 11:07:11 GMT
Server: Apache/2.2.9 (Debian) mod_python/3.3.1 Python/2.5.2
Last-Modified: Thu, 18 Feb 2010 04:35:56 GMT
ETag: "1bda0bd-167306-47fd880b74300"
Accept-Ranges: bytes
Content-Length: 1471238
Content-Type: application/x-tar
Content-Encoding: x-gzip
Downloaded to C:\Documents and Settings\mmitrofanov\Application
Data\cabal\packages\hackage.haskell.org\00-index.tar.gz
cabal.exe: Codec.Compression.Zlib: premature end of compressed stream

Windows, `CygWin?`, GHC 6.10.4

ghc-pkg:

$ ghc-pkg list
D:/ghc/ghc-6.10.4\package.conf:

<blockquote>
Cabal-1.6.0.3, Cabal-1.8.0.2, HTTP-4000.0.9, HUnit-1.2.0.3,
`QuickCheck?`-1.2.0.0, Win32-2.2.0.0, array-0.2.0.0, base-3.0.3.1,
base-4.1.0.0, bytestring-0.9.1.4, containers-0.2.0.1,
directory-1.0.0.3, (dph-base-0.3), (dph-par-0.3),
(dph-prim-interface-0.3), (dph-prim-par-0.3), (dph-prim-seq-0.3),
(dph-seq-0.3), extensible-exceptions-0.1.1.0, filepath-1.1.0.2,
(ghc-6.10.4), ghc-prim-0.1.0.0, haskell-src-1.0.1.3,
haskell98-1.0.1.0, hpc-0.5.0.3, html-1.0.1.2, integer-0.1.0.1,
mtl-1.1.0.2, network-2.2.1.2, old-locale-1.0.0.1, old-time-1.0.0.2,
packedstring-0.1.0.1, parallel-1.1.0.1, parsec-2.1.0.1,
pretty-1.0.1.0, process-1.0.1.1, random-1.0.0.1,
regex-base-0.72.0.2, regex-compat-0.71.0.1, regex-posix-0.72.0.3,
rts-1.0, stm-2.1.1.2, syb-0.1.0.1, template-haskell-2.3.0.1,
time-1.1.4, xhtml-3000.2.0.1, zlib-0.5.2.0

</blockquote>

$ cabal --version
cabal-install version 0.8.0
using version 1.8.0.2 of the Cabal library

**Comment by benclifford** [comment]
For future readers: I've encountered this problem with a misbehaving (non)transparent corporate HTTP firewall/proxy. The proxy was incorrectly terminating the underlying HTTP connection, and this was not being detected by the HTTP library, leading to a confusing error message.
