### ISSUE TITLE
Allow overriding defaultPackageDesc

### ISSUE THREAD

**Issue by bos** [haskell/cabal#630]
(Imported from [Trac #637](http://hackage.haskell.org/trac/hackage/ticket/637), reported by guest on 2010-02-19)

I'm trying to keep the source of multiple packages in a single source repository. Unfortunately, I cannot maintain a .cabal file per package, because some commands invoke function defaultPackageDesc unconditionally.

I tried using <tt>defaultMainNoRead</tt> instead of <tt>defaultMain</tt>
and passing the desired package name through the environment. This solution doesn't work at all in 1.6.0.3. It works only partially in HEAD: <tt>Setup configure</tt> and <tt>Setup build</tt> work but <tt>Setup sdist</tt> does not because it ignores the <tt>readDesc</tt> field and invokes <tt>defaultPackageDesc</tt> unconditionally.

Would it be possible to add a field to <tt>UserHooks</tt> which would specify the .cabal filename to use? Then <tt>defaultPackageDesc</tt> should be always called through this field, never directly, and could thus be consistently overridden.

**Comment by thumphries** [comment]
This also bit me recently. I was also programmatically populating `extra-source-files`.

Any command ignoring the `readDesc` hook is out of line. Note that `sdist` now does the expected thing ( #3491 ) , though there are other issues such as #3552 to be ironed out.

Long run I would expect our use case to disappear in favour of globstar #3178 , so this issue will be doubly dealt with. I am unsure of the original author's use case, however, so I am hesitant to close this issue.

**Comment by jneira** [comment]
It seems to me that `I'm trying to keep the source of multiple packages in a single source repository.` is just what v2 build and cabal.project gives us. Otoh we are trying to reduce the use of custom setups .
The `extra-source-files`use case is also covered as noted above so i am gonna close this.
Feel free to reopen if this is still needed for an use case not took in account
