### ISSUE TITLE
CI: Could not resolve host: haskell-cabal.s3.amazonaws.com

### ISSUE THREAD

**Issue by dwijnand** [haskell/cabal#6324]
@phadej mentioned in #6315 that master has been broken for a number of days.  I'm looking at the latest build https://travis-ci.org/haskell/cabal/builds/601490658 and 8/16 jobs are due to failing to upload to S3 the binaries to test, due to:

    curl: (6) Could not resolve host: haskell-cabal.s3.amazonaws.com

There's also a 9th failure of "Could not resolve host: hackage.haskell.org", which I've also seen in the past in other CI jobs.

Does anyone know what might've happened?

I noticed the `travis_retry` usage just lower down in `travis/upload.sh` so I'm tempted to PR adding that to the curl.  Would that be appreciated?

**Comment by phadej** [comment]
ping @ezyang

**Comment by ezyang** [comment]
Yeah, let's try a retry?

**Comment by dwijnand** [comment]
#6325
