### ISSUE TITLE
cabal-install 3.0.1.0 release planning

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#6328]
Given #6327 it becomes more urgent to finalize a first point-release of cabal-install with the main goals of being a

- GHC 8.8.1 compatible (that is, being compilable by GHC 8.8.1; not only supporting driving GHC 8.8.1) release (requires new backward-incompat `hackage-security` release) and
- include/backport important fixes (such as e.g. #6317 and ideally #6218)

After a brief conversation with @23Skidoo a realistic time-schedule is to aim for releasing sometime next week (before end of Sunday Nov 17th)

As deliverables, this ought to include

- A source-release to Hackage
- Making sure the bootstrap script works w/ at least GHC 8.8.1 (relevant to e.g. #6317)
- Binary releases for Linux (@hvr), macOS (@phadej), Windows (@Mistuke) on http://downloads.haskell.org
   - inclusion in `ghcup` (cc @hasufell)
   - inclusion in Chocolatey (cc @Mistuke)

**Comment by jneira** [comment]
Hi!, #6298 fixed a minor bug but i think it could be backported to 3.0 without taking many risks.

**Comment by phadej** [comment]
https://github.com/haskell/cabal/milestone/51 milestone has 35 open issues. Those have to be resolved (or reclassified) before this can go forward.

**Comment by phadej** [comment]
I backported bunch of stuff and made https://github.com/haskell/cabal/releases/tag/Cabal-v3.0.1.0-rc1 tag. I'll make a MR to GHC advancing Cabal submodule to it.

**Comment by jneira** [comment]
@phadej sorry for ping but do you think #6298 could be backported to 3.0.1.0? it is a minor bug but it blocks the use of `cabal-helper` (and `haskell-ide-engine`) with a custom `store-dir` (pretty common for windows users)
I could try to do a pr if you think it could be included in the release.
Thanks in advance!

**Comment by phadej** [comment]
@jneira sorry, but I just created another rc. I hope `cabal-install-3.2` will be released in 1-2 months. I'd like not to spend any more time on 3.0.

**Comment by phadej** [comment]
@hvr, @23Skidoo from my side, `Cabal-v3.0.1.0-rc2` is ready to be released: both `Cabal` and `cabal-install`.

**Comment by DanielG** [comment]
Might be too late, but I would have liked #6300 to be included in the point release also. It's another Windos fix.

**Comment by phadej** [comment]
6300 is included. I’ll probably backport store dir also today, if the patch applies cleanly

**Comment by phadej** [comment]
New tags updated in https://github.com/haskell/cabal/issues/6328#issuecomment-565311423

I think they can be released

**Comment by DanielG** [comment]
Awesome, thanks!

**Comment by phadej** [comment]
I backported `cabal install --ignore-project` to `3.0` branch too.

- https://github.com/haskell/cabal/releases/tag/Cabal-v3.0.1.0-rc2
- https://github.com/haskell/cabal/releases/tag/cabal-install-v3.0.1.0-rc2

**Comment by phadej** [comment]
Another tag for `cabal-install`: https://github.com/haskell/cabal/releases/tag/cabal-install-v3.0.1.0-rc4

**Comment by phadej** [comment]
GHC-8.8.2 released with Cabal at Cabal-v3.0.1.0-rc2 tag.

**Comment by arrowd** [comment]
Any ETA for cabal-install 3.0.1.0? I unable bootstrap 3.0.0.0 with GHC 8.8.

**Comment by domenkozar** [comment]
Any chance of getting Cabal 3.0.1.0 on hackage?

**Comment by bezirg** [comment]
> Any chance of getting Cabal 3.0.1.0 on hackage?

Also this page has to be updated: https://www.haskell.org/cabal/download.html

**Comment by symbiont-sam-halliday** [comment]
:crossed_fingers:  for https://github.com/haskell/cabal/issues/6222 in 3.0.1.0

**Comment by fishtreesugar** [comment]
It seems [3.0.1.0](https://github.com/haskell/cabal/blob/bd07f0a095869b91a590d8a564f716a6a136818a/cabal-install/changelog#L3) not correctly [release]((https://github.com/haskell/cabal/releases) with tag and [hackage uploading](https://hackage.haskell.org/package/cabal-install)
