### ISSUE TITLE
CI: Use GHC 8.6 instead of 8.4 for more jobs?

### ISSUE THREAD

**Issue by dwijnand** [haskell/cabal#6331]
I noticed that in CI GHC 8.4 is being favoured over 8.6 (let alone 8.8).  Is there a reason for that?  Specifically:
* the docs are being published using ghc 8.4
* the solver benchmarks, bizarrely, are using ghc 8.0
* bootstrapping is being tested for ghc 8.4 and ghc 8.0
* `-fdebug-expensive-assertions` is also running on (only) ghc 8.4
* on osx the latest version tested is ghc 8.0

What do you think if we replace those 8.4 usages with 8.6?  And perhaps add (or replace) 8.6 for osx too?

**Comment by phadej** [comment]
as far as things work (e.g. docs **are** published), let's not touch them. Debugging CI issues is slow and demotivating.

It's also good idea to test bootstrapping with old(est supported) compilers.

If you want to improve CI, talk to @hvr about GitHub actions.

**Comment by dwijnand** [comment]
Fair enough.  I assume the GitHub actions replacement will make the same or better decisions without needing this issue.
