### ISSUE TITLE
Add nix hashes for source-repositories

### ISSUE THREAD

**Issue by hamishmack** [haskell/cabal#6344]
For source code to be downloaded by nix it is important to have a nix hash of the code you expect to get (especially when building in restricted mode).  It would be very useful if cabal could provide and/or verify nix hashes for `source-repositories` specified in the `cabal.project` file.  Currently we adding them as comments to our `cabal.project` files or bundling them up in separate files (neither ideal).  Both these methods do not work well for users who are not using nix (as they cannot update or check the hashes).

The hashes can be calculated with a tool called `nix-prefetch-git`, but it would be nice if this functionality was available in `cabal` (since it already downloads and stores the source data needed to calculate the hashes).

How `nix-prefetch-git` calculates the hash:

* [removes the the `.git` dir](https://github.com/NixOS/nixpkgs/blob/c3af84d50aafa9818084880c59fe0a4f1dd23f25/pkgs/build-support/fetchgit/nix-prefetch-git#L303-L304)

* [calls `nix-hash`](https://github.com/NixOS/nixpkgs/blob/c3af84d50aafa9818084880c59fe0a4f1dd23f25/pkgs/build-support/fetchgit/nix-prefetch-git#L422) passing it the location a a temporary directory containing the remaining files.

* [`nix-tools` uses `CmdHash` with `mPath`](https://github.com/NixOS/nix/blob/804910fb0eeb6a14ec8d6f98c7fd219da8d04581/src/nix/hash.cc#L155-L160)

* [`CmdHash` calls `dumpPath`](https://github.com/NixOS/nix/blob/804910fb0eeb6a14ec8d6f98c7fd219da8d04581/src/nix/hash.cc#L64)

* [`dumpPath`](https://github.com/NixOS/nix/blob/f7ce80f90ab364058e28989af68ba993fd8180a9/src/libutil/archive.cc#L123) calls [`dump`](https://github.com/NixOS/nix/blob/f7ce80f90ab364058e28989af68ba993fd8180a9/src/libutil/archive.cc#L65-L117)

We will need to include an implementation of `dump` or perhaps require the `nix-hash` tool in the `PATH`. [hnix-store](https://github.com/haskell-nix/hnix-store) may have an implementation.

**Comment by hamishmack** [comment]
@cleverca22 pointed out: 
https://github.com/taktoa/narfuse/blob/86757825a970d483898bb4728f6f05789e3f44b4/Main.hs#L201-L202

> Many years ago, I wrote a parser for nar files, using `Data.Binary.Get`. Currently, it lacks the put functions, but if the blanks get filled in, then all thats left is to generate a NARFile record from a directory, and ensure all directory contents are sorted correctly.

**Comment by phadej** [comment]
I don’t understand this feature request, can you give an example? Doesn’t git commit hash uniquely determine the sources already?

**Comment by hamishmack** [comment]
> I don’t understand this feature request, can you give an example?

[Here](https://github.com/leksah/leksah/blob/master/cabal.project#L38-L56) are some `source-repository-package` sections where including a nix sha256 allows us to download the source on a hydra server that is using restricted evaluation mode.

This is clunky, but should work for nix users who are familiar with the tool nix provides for calculating the hashes `nix-prefetch-git` (or just setting an invalid hash and having nix tell you what it should be).

The difficulty is that users without nix cannot easily update those hash values.  Also if they put them in wrong nothing will tell them they are wrong.

Worse still if we forget to update a nix hash, nix might not give us an error if we already have output that matches the old hash in the store.  Instead it will quietly use the wrong files!

> Doesn’t git commit hash uniquely determine the sources already?

It does, however nix likes to use a different hash, one that it knows how to verify (as far as I know it does not know how to verify a git commit hash).  In order to do any network IO in restricted mode you must provide nix with this nix hash of the output you are going to put in the store (that way nix can verify that the derivation does what is expected).

It would be nice if the nix hash could just be the hash of a `.tar` of the files you wished to put in the store, but `.tar` contains a lot of information that will be stripped when the files are put in the store (this information should not be in the hash).  Instead nix has its own `.nar` format that it uses instead of `.tar`.  It does not include:

* timestamps (nix resets all timestamps to the unix epoch)
* the read/write permission bits
* uid/gids

It only supports:

* files, directories, symlinks
* files can either be executable or not

One advantage of the nix hash is that the same hash can be used to verify both a `git clone` of a rev and a downloaded `.tar.gz` file of that rev.  In some cases downloading a `.tar.gz` file can be much faster.  If nix relied on just the git commit hash then it would not be possible to tell if a `.tar.gz` contained code that matched that commit (my understanding is that files in the .git dir would also be needed).

**Comment by phadej** [comment]
So this would benefit only users of some particular Nix setup and no-one else?

I have hard time justifying this belongs to `cabal-install` proper, and not that particular nix setup.

Extending via "pragmas" in comments is IMO the way to go here. I also work on a small package https://github.com/haskell-CI/haskell-ci/tree/master/cabal-parsers which shows how to parse `cabal.project` files, and can be extended to attach comments to particular (`source-repository-package`) section (Yet, I won't do that, as I don't need it, feel free to fork).

**Comment by phadej** [comment]
FYI: And to make this even more complicated, you can (and sometimes I do) write

```
packages: https://hackage.haskell.org/package/base-compat-0.11.0/base-compat-0.11.0.tar.gz
```

That (I think) actually works with GitHub source `.tar.gz` if the repository is single-package repository. E.g.

```
packages: https://github.com/phadej/tree-diff/archive/2288c7c37d9b8fc2243723e983f56ccee8caac9b.tar.gz
```

**Comment by hamishmack** [comment]
> So this would benefit only users of some particular Nix setup and no-one else?

Them and users without nix collaborating with them.

> I have hard time justifying this belongs to cabal-install proper, and not that particular nix setup.

Maybe an external tool would be better. I have no strong feelings about that.

I've not got time to spend on this right now, but I will ponder it when I can over the next few days.

I did wonder if cabal-install could feed the hash through to the plan.json file to avoid parsing the cabal.project file, but we really want a way to update the hashes as well.

I like the nix hashes in the cabal.project file next to the rev to simplify the way they behave in source control (you can merge them or not together etc.).   If we had a wrapper script for `cabal build` and `cabal repl` that checks or updates the hashes maybe they could be in their own file.

**Comment by phadej** [comment]
This starts to sound like "make `cabal.project` extensible with extra fields". That would work, if there's clean design. Making `cabal-install` actually check the additional information is IMO wontfix, as we cannot cater for any possible downstream user.

I'm closing this issue now. Please think about, and open new one when your idea is clearer.

**Comment by hamishmack** [comment]
Will do.  Thanks.

**Comment by cleverca22** [comment]
`packages: https://hackage.haskell.org/package/base-compat-0.11.0/base-compat-0.11.0.tar.gz`
actually makes things easier for cabal to support nix

when using such a url, nix only needs the plain old sha256, which cabal can trivially calculate (just download and hash)

**Comment by hamishmack** [comment]
Something I forgot is that we already have to parse cabal.project file a bit in the haskell.nix code. So we can run `cabal new-configure` without it needing to download anything we parse and strip out the `source-repository-packages` and replace them with `packages:`.  Currently we use a very [basic parser in written in nix](https://github.com/input-output-hk/haskell.nix/blob/ef4b453f8d4589cefbab750bcf551e338e8cba91/lib/call-cabal-project-to-nix.nix#L84-L113).  There is no way to do this based on the `plan.json` because we are doing it in order to create the `plan.json`.  This seems like another reason not to add the `nix-sha256` to `plan.json` (as it would not help in this use case).  Something built into `cabal-install` or a separate tool using [cabal-parsers](https://github.com/haskell-CI/haskell-ci/tree/master/cabal-parsers) could do the parsing job better than the nix we have now as well as helping users check and update the hashes.

**Comment by angerman** [comment]
> `packages: https://hackage.haskell.org/package/base-compat-0.11.0/base-compat-0.11.0.tar.gz`
> actually makes things easier for cabal to support nix
> 
> when using such a url, nix only needs the plain old sha256, which cabal can trivially calculate (just download and hash)

This one we essentially have with [hackage.nix](https://github.com/input-output-hk/hackage.nix). It's just the source repos that are unpredictable :-/
