### ISSUE TITLE
Write a policy how issues are milestoned.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6346]
Moving unsolved release issues a week before release feels like haux. I don't like that about GHC process, and we don't need to copy bad practices.

I propose: don't milestone any issues to particular release except if **you** will work on them for that, and if so, assign it to yourself. In other words, each release-milestoned issue should have assignees whom one can ask about the process. And in kanban style, one shouldn't have more then 5 assigned milestoned issues or so.

IMHO it's better to underestimate what will be in the next release, than make hoax promises "it will be fixed in the next release" for unknown amount of releases.

Let's write this policy down in some file in this repository (next to `release-checklist.md`).

**Comment by 23Skidoo** [comment]
Makes sense.

**Comment by gbaz** [comment]
i think we should close this as we're feeling out a new dev approach that as i understand it will use milestones less and projects more, for whatever that's worth.
