### ISSUE TITLE
Please ensure cabal does not warn for incomplete-uni-patterns 

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#6355]
As per [this accepted GHC proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0071-Wall-uni-patterns.rst), GHC will add `incomplete-uni-patterns` and `incomplete-record-updates` to `-Wall`.  Could you please ensure that the following files do not give any warnings for `incomplete-uni-patterns`, perhaps by setting the pragma below?  (A clean compile of cabal is needed to build GHC.)

`{-# OPTIONS_GHC -Wno-incomplete-uni-patterns #-}`

* [ ] `Cabal/Distribution/Backpack/Configure.hs`
* [ ] `Cabal/Distribution/Parsec.hs`
* [ ] `Cabal/Distribution/Simple/Build/Macros.hs`
* [ ] `Cabal/Distribution/Simple/GHC.hs`
* [ ] `Cabal/Distribution/Simple/GHCJS.hs`
* [ ] `Cabal/Distribution/Simple/UHC.hs`
* [ ] `Cabal/Distribution/Simple/Test/LibV09.hs`
* [ ] `Cabal/Distribution/Simple/BuildTarget.hs`
* [ ] `Cabal/Distribution/Simple/ShowBuildInfo.hs`
* [ ] `Cabal/Cabal/Distribution/Simple/Haddock.hs`

**Comment by dwijnand** [comment]
When you say "Could you please ensure that the following files do not give any warnings" and then give a list specifying 1 particular file, I assume you found that file to have warnings.  But I'm having a hard time reproducing that, after adding that pragma and running `cabal build Cabal`.  Is there some step I'm missing?

**Comment by tomjaguarpaw** [comment]
I am currently implementing the above-mentioned proposal in GHC, i.e. that  `-Wincomplete-uni-patterns` is added to `-Wall`.  However, that file emits warnings under `-Wincomplete-uni-patterns`, breaking the build of GHC.  I'm asking that `-Wno-incomplete-uni-patterns` is added on that file so that it will not break the build of GHC. Does that make sense?

**Comment by dwijnand** [comment]
If you have a look at https://travis-ci.com/dwijnand/cabal/builds/136806769 and the commit it builds from (which builds on current HEAD), and ignore the failures on older GHCs, you'll see that compilation didn't fail (and I believe warnings are set to fatal), so I do still need some information as to what Parsec.hs needs or how to get it to fail...

**Comment by tomjaguarpaw** [comment]
I'm saying that it *will* fail under `-Wincomplete-uni-patterns` and that warning will be included under `-Wall` under future GHCs, therefore `Parsec.hs` needs `-Wno-incomplete-uni-patterns` applied. In other words, what I'm asking you to do is exactly to merge https://github.com/dwijnand/cabal/commit/4e6b2c5ec354a0204b2b1e74a6b361021d442230!

**Comment by dwijnand** [comment]
Ok, thank you for helping me understand.  Why that file in particular?  Why not all of them?

**Comment by dwijnand** [comment]
> so I do still need some information

Thanks to @phadej I found out that the information I was missing is that the "no" in `-Wno-incomplete-uni-patterns` suppresses the warning.  (I expanded on this in https://twitter.com/dwijnand/status/1195908792686391296.)

**Comment by tomjaguarpaw** [comment]
[Edited the list to include many more cases I found!]

**Comment by phadej** [comment]
Just out of curiosity, is there work on hadrian / shake to make them `-Wincomplete-uni-patterns` clean?
I opened to track that https://gitlab.haskell.org/ghc/ghc/issues/17577
