### ISSUE TITLE
Cabal-3.0.0.0.tar.gz is 9.8MB large

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6360]
...and 50MB unpacked with 

```
28K	Cabal.cabal
48K	ChangeLog.md
2,8M	Distribution
44M	doc
44K	Language
4,0K	LICENSE
8,0K	README.md
4,0K	Setup.hs
2,2M	tests
```

I suggest not to bundle `doc` directory. Nobody looks at it anyway?

**Comment by hvr** [comment]
```
29M	doc/API/Cabal
29M	doc/API
5.4M	doc/users-guide/_static/fonts/Lato
808K	doc/users-guide/_static/fonts/RobotoSlab
8.9M	doc/users-guide/_static/fonts
24K	doc/users-guide/_static/js
120K	doc/users-guide/_static/css
9.6M	doc/users-guide/_static
328K	doc/users-guide/_sources
3.6M	doc/users-guide/.doctrees
15M	doc/users-guide
8.0K	doc/images
44M	doc/
```

I don't like this either; it's a *source* distribution; it's not supposed to contain such huge generated artifacts IMO; it should at most contain the source for the user guide, but not the generated artifacts

**Comment by hvr** [comment]
This is weird; if you unpack Cabal-3.0.0.0; and then re `cabal sdist`, you end up with a 782KiB large .tar.gz; i.e. the `extra-source-files-*` aren't to blame here either;

@23Skidoo how did you prepare the sdist to Hackage?

**Comment by 23Skidoo** [comment]
Using the instructions on the [Making a release](https://github.com/haskell/cabal/wiki/Making-a-release) page.

**Comment by phadej** [comment]
Looks like the cuprit is `make dist`: https://github.com/haskell/cabal/blob/7d7113654213460797513c08cbdf8b913db781e6/Cabal/Makefile#L95-L110

dist tarball is accumulated manually. @hvr, should we move to use `cabal sdist`.

**Comment by ulysses4ever** [comment]
`make dist` doesn't appear to be in the checklist for making a release. So, the generated doc artifacts won't go into future releases. Should we close it?

**Comment by Mikolaj** [comment]
Oh, I had no idea `make dist` even exists. Yes, let's keep things as simple as possible, unless there's something important we are missing by doing ordinary `cabal sdist` four times. If so, please somebody reopen the ticket and explain. Thank you in advance. Closing.
