### ISSUE TITLE
Cabal does not understand the peculiarities of ghcjs executables

### ISSUE THREAD

**Issue by ddssff** [haskell/cabal#6361]
A `ghcjs` "executable" is a collection of files in a subdirectory.  The subdirectory is where the normal executable would be, but it has the extension `.jsexe` and contains `all.js` among other files.  To run the program the `node` or `nodejs` interpreter is passed the path to the `all.js` file.  So suppose I try to run the cabal executable `program-version` as follows
```
$ cabal --ghcjs new-run --project client.project program-version
Resolving dependencies...
Up to date
/home/dsf/git/happstack-ghcjs/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/appraisalscribe-data-2.50/x/program-version/build/program-version/program-version: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
That is, the path `...build/foo/foo` should actually be `...build/foo/foo.jsexe/all.js`, and that path needs to be an argument to `node`.  So the actual command to run it is this:
```
$ node /home/dsf/git/happstack-ghcjs/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/appraisalscribe-data-2.50/x/program-version/build/program-version/program-version.jsexe/all.js
```
Similarly, the new-install command needs a similar change:
```
$ cabal --ghcjs new-install --project client.project program-version
$ ls -l /home/dsf/.cabal/bin/program-version
lrwxrwxrwx 1 dsf dsf 133 Nov 17 16:02 /home/dsf/.cabal/bin/program-version -> ../store/ghcjs-8.6.0.1/appraisalscribe-data-2.50-767e264c71ed2a76eace42907fa2cad47204ca13760ab010754526422c1cd733/bin/program-version
$ ls -lL /home/dsf/.cabal/bin/program-version
ls: cannot access '/home/dsf/.cabal/bin/program-version': No such file or directory
```
The actual location:
```
$ ls -lL /home/dsf/.cabal/store/ghcjs-8.6.0.1/appraisalscribe-data-2.50-767e264c71ed2a76eace42907fa2cad47204ca13760ab010754526422c1cd733/bin/
total 4
drwxr-xr-x 2 dsf dsf 4096 Nov 17 16:02 program-version.jsexe
```

**Comment by angerman** [comment]
I believe the tweagio/asterius project does something similar with results being bundles. There is also the [cabal-macosx](https://hackage.haskell.org/package/cabal-macosx) which does the `bundles` stuff, where your end result is an `.app` folder.

**Comment by hvr** [comment]
> $ node /home/dsf/git/happstack-ghcjs/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/appraisalscribe-data-2.50/x/program-version/build/program-version/program-version.jsexe/all.js

actually, cabal doesn't need to know anything about `node` at all; ghcjs already contains the knowledge and in fact is able to create a script to invoke the tool; this is how e.g. cabal is able to run an `happy` or `alex` compiled by ghcjs (which currently happens as a happy accident when you `build-tool-depends: alex` in `--ghcjs` mode even though `cabal` knows nothing at all about which JS interpreter to use (which is a good thing IMO -- but then again, see also discussion linked below).

See also https://github.com/haskell/cabal/issues/5831#issuecomment-453016654

**Comment by phadej** [comment]
@hvr are you completely sure? I'm quite sure that at least with ghcjs-8.4 `cabal` **does** build `happy`, but actually runs the one in `$PATH` (and fails if there aren't).

I'm quite sure it's that way because i have to install `happy` for haskell-ci ghcjs jobs work properly (there aren't some accidental `happy` in `$PATH`).

FWIW, we should have `ghcjs` tests, otherwise the stuff will only regress again and again
