### ISSUE TITLE
Visibility field not listed under cabal spec changes.

### ISSUE THREAD

**Issue by merijn** [haskell/cabal#6362]
The cabal docs list the [`visibility`](https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-library-visibility) field as existing as of Cabal 3.0, however the list of format changes doesn't list it as an addition in [3.0](https://cabal.readthedocs.io/en/latest/file-format-changelog.html#cabal-version-3-0)

**Comment by jneira** [comment]
visibility is not included anymore in the linked page above: https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-library-visibility
I guess it still was added in 3.0 and should be included in cabal format changes
