### ISSUE TITLE
Leftovers from cmm-options fix

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6377]
https://github.com/haskell/cabal/pull/6033
cc @angerman

---

Things that work now (i.e. that I (@hvr) tested manually; these should be turned into testsuite tests long-term):

- cmm-sources and asm-sources are compiled (in a separate phase like c-sources are) and the resulting object files are linked into the respective component (i.e. like c-sources)
- cabal sdist properly includes cmm-sources and asm-sources in the src-dist
- cmm-options are passed (directly) to GHC when compiling cmm-sources
- asm-options are passed (via -opta) to GHC when compiling asm-sources files
- ghc-options are NOT passed to compilation of cmm-sources/asm-sources

---

@23Skidoo:

If I have both preprocessor-generated asm-sources and cmm-sources, won't this add the union of these to the LBI's asmSources?

Actually, this probably will break if I have any preprocessor-generated C files at all.

---

TODO: forward port b7cd00bd75e379abee79a8ae5ac049b9a10ac0e8 to 3.0+

**Comment by 23Skidoo** [comment]
I left some comments in #6033, were they addressed in the version that got merged to `master`?

**Comment by phadej** [comment]
Edited the description to include preprocessor-generated issue
