### ISSUE TITLE
confusing interface: cabal "install" subcommand has two clashing meanings

### ISSUE THREAD

**Issue by bos** [haskell/cabal#638]
(Imported from [Trac #645](http://hackage.haskell.org/trac/hackage/ticket/645), reported by StefanK on 2010-03-19)

This is not a duplicate of #601. Installing a package with

<pre class="wiki">rm -rf ~/.ghc ~/.cabal
cabal clean
cabal configure --user --prefix="${HOME}/opt"
cabal build
cabal install
</pre>will install the binaries in '/home/sk/.cabal/bin' instead of '/home/sk/opt/bin'.

I'll attach a toy project demonstrating this.

System:

<pre class="wiki">sk@watarrka:~&gt; ghc --version
The Glorious Glasgow Haskell Compilation System, version 6.12.1
sk@watarrka:~&gt; cabal --version
cabal-install version 0.8.0
using version 1.8.0.2 of the Cabal library
</pre>

**Comment by gbaz** [comment]
at this point i think we should close this as designed.
