### ISSUE TITLE
What's the purpose of +markoutput

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6383]
Looking at the git history, it looks like it's only for `cabal-testsuite` needs, to get the cabal output, and **shouldn't** be used by external tools, is it correct?

@ezyang

**Comment by ezyang** [comment]
Yes, it's sole purpose is to demarcate lines of output which we match against explicitly in the test suite. Otherwise there'd be a lot of wobbly lines and we couldn't use expect tests for Cabal output.

**Comment by phadej** [comment]
@ezyang so it's right to say that `+markoutput` is `Cabal` internal thing, and no external things should rely on its behavior?

**Comment by ezyang** [comment]
Yep!
