### ISSUE TITLE
Document verbose flag properlty

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6384]
https://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-verbose only says about numeric properties, no textual `-vnormal`, nor explanation of flags?

- What `+nowrap` does, @hvr
- What `+markoutput` does, @ezyang?

**Comment by ezyang** [comment]
Answered in https://github.com/haskell/cabal/issues/6383

**Comment by bacchanalia** [comment]
duplicate of #4519

**Comment by jneira** [comment]
closed as duplicate of #4519
