### ISSUE TITLE
OnlyConfigure test fails in master

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6408]
https://ci.appveyor.com/project/23Skidoo/cabal/builds/29404216

---

@Mistuke have you seen

```
C:\Users\appveyor\AppData\Local\Temp\ghcE17A.c:2:6: error: expected '=', ',', ';', 'asm' or '__attribute__' before ')' token
  argv) { return 0; }
      ^
```

error. Can it be related to upgraded GCC or something like that?

**Comment by phadej** [comment]
`master` OTOH, fails with

```
Dependency base ==4.12.0.0: using base-4.12.0.0
<command line>: does not exist: C:\Users\appveyor\AppData\Local\Temp\ghc85F1.c
stderr:
```

Looks like something wrong with writing to `Temp` on appveyor?

**Comment by Mistuke** [comment]
Hmm no never seen that one before. Could it be running out of disk space?

**Comment by Mistuke** [comment]
And is it consistently failing?

**Comment by phadej** [comment]
No, it seems to be quite random.

**Comment by phadej** [comment]
This seems to be transient.
