### ISSUE TITLE
GHC-8.10 has -optcxx, should Cabal do something with that?

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6421]

**Comment by phadej** [comment]
ping @cblp

**Comment by cblp** [comment]
I'm not sure this belongs to Cabal or cabal-install, but I will write it down anyway for somebody competent:

1. `cxx-options` should be passed to `-optcxx`
2. `cc-options` should be passed to `-optc`
3. `c-sources` should use `cc-options` but not `cxx-options`
4. `cxx-sources` should use `cxx-options` but not `cc-options`

**Comment by hvr** [comment]
We also need to come up with well-defined `cabal-version`-guards to make sure the semantics well-defined for a given `.cabal` file and don't fluctuate based on which version of `cabal` you're building it with...

**Comment by phadej** [comment]
`cxx-sources` and `cxx-options` are since `cabal-version: 2.2`.

My feeling is that we should make this too complicated, if there's a package which really needs
the separation as in https://github.com/haskell/cabal/issues/6421#issuecomment-564968409,
that it ought to require newer `cabal-version: ...`, but I don't think we need to simulate older behaviour in newer `Cabal`s.

In other words: What would break if above separation is changed. My gut feeling is that nothing. (at least on Hackage). Or more bluntly, whatever is on Hackage and using `cxx-sources` now is broken anyways.

**Comment by bgamari** [comment]
This came up in [GHC #18687](https://gitlab.haskell.org/ghc/ghc/-/issues/18687).

**Comment by ejconlon** [comment]
Hi folks, I reported the linked GHC ticket and included a simple [repro](https://github.com/ejconlon/ffi-repro). I agree with @phadej above that we probably don't have to overcomplicate the fix with advanced `cabal-version` checking. As far as I can tell it's impossible now to pass options to C++ builds through ANY means (`cc-options`, `cxx-options`, `ghc-options`) on 8.10. I believe that if we change this behavior nothing would break that isn't already broken now.

**Comment by ejconlon** [comment]
AFAICT, this line should be `-optcxx` for 8.10 and above: https://github.com/haskell/cabal/blob/90c4695667ccf9281ab570b76a1c9241216c9e9a/Cabal/src/Distribution/Simple/Program/GHC.hs#L689 .
