### ISSUE TITLE
Update changelog for 3.2

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6423]
I'll do that after `3.0.1.0` release is cut, so we can copy the final entries to the `3.2` branch.

**Comment by phadej** [comment]
This is basically done, but I'll still keep this open to remember to do final check before pushing the releases.

**Comment by blackgnezdo** [comment]
Should this release get a higher priority now that ghc 8.10.1 is out and references cabal 3.2 which is not on hackage yet?

**Comment by hvr** [comment]
@blackgnezdo it does already have highest priority... ;-)

**Comment by hvr** [comment]
since all pending lib:Cabal-3.[02].* releases have been published to Hackage I consider this resolved
