### ISSUE TITLE
There are fixed size of known VCS, implement Representable container.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6432]
I.e. container such `lookup :: RepoType -> VCS a -> a` would be total.

One would need to split `OtherRepoType String` out of `RepoType`, into separate type.

There're handful of `error`s to be removed by this refactor.

I think this is newcomer friendly refactoring.

---

One example of this "issue", is e.g. miss-typing `type` in `source-repository-package`:

```
% cabal build      
cabal: (SourceRepo {repoKind = RepoThis, repoType = Just (OtherRepoType
"gitt"), repoLocation = Just "https://github.com/phadej/tree-diff.git",
repoModule = Nothing, repoBranch = Nothing, repoTag = Just "123", repoSubdir =
Nothing},SourceRepoRepoTypeUnsupported (OtherRepoType "gitt"))
```

Technically, we don't need to accept unknown `RepoType`s to begin with in the `cabal.project` parser. Thus there's small argument from splitting `RepoType` into `Enum` part, and `Either String` like wrapper.

**Comment by v0d1ch** [comment]
@phadej how would you like this _Either String like wrapper_ to look? 
I am asking just to make sure I am able to do exactly the thing you wanted

**Comment by phadej** [comment]
Currently we have

```haskell
data RepoType = Darcs | Git | SVN | CVS
              | Mercurial | GnuArch | Bazaar | Monotone
              | OtherRepoType String
```

After we could have

```haskell
data KnownRepoType = Darcs | Git | SVN | CVS
                   | Mercurial | GnuArch | Bazaar | Monotone

data RepoType = KnownRepoType KnownRepoType
              | OtherRepoType String
```

**Comment by v0d1ch** [comment]
Hey @phadej I made the changes and blindly fixed the compiler errors in code and tests. 
Here is the diff https://github.com/haskell/cabal/compare/master...v0d1ch:6432-implement-Representable-container

There is one test that keeps failing and I need some help fixing it:
```
  Distribution.Utils.Structured
    VersionRange:                                                                         OK
    SPDX.License:                                                                         OK
    LocalBuildInfo:                                                                       FAIL
      tests/UnitTests/Distribution/Utils/Structured.hs:26:
      expected: 2b983b5312a676b13edb7b476c2fd11e
       but got: e2909c4dccc1d2dea065d96aa3d0d915

```

**Comment by phadej** [comment]
The `Structured` tests fails for a reason. We indeed change type definitions. The solution is simply copy the new hash into the test (you need to split it in half and add `0x` for hex numbers).

**Comment by phadej** [comment]
The patch looks fine. I'll comment more when you make a PR. Thanks for picking this issue!
