### ISSUE TITLE
Missing `--cabal-config-file` flag

### ISSUE THREAD

**Issue by asr** [haskell/cabal#6451]
Some  commands (e.g. `cabal install` or `cabal-configure`) have the following flag:

```
 --cabal-file=PATH    use this Cabal file
```

What I miss for simultaneously running different versions of `cabal-install` is a flag like 

```
 --cabal-config-file=PATH    use this Cabal config file instead of .cabal/config
```

**Comment by phadej** [comment]
A work around is to use `CABAL_CONFIG` environment variable.

**Comment by phadej** [comment]
Or wait, actually

```
% cabal --help|grep -A 2 config-file
    --config-file=FILE             Set an alternate location for the config
                                   file
```

I.e. `cabal --config-file=yourfile v2-build`, it have to come between `cabal` and `command`.
