### ISSUE TITLE
cabal-install randomly misses part of its man page

### ISSUE THREAD

**Issue by bmwiedemann** [haskell/cabal#6475]
**Describe the bug**
While working on reproducible builds for openSUSE, I found that
our `cabal-install-3.0.0.0` binary package varies in every build
from the included cabal.1 man page
created by `./Setup build -v`

The `cabal-install-2.4.0.0` package was still building reproducibly in 2019-08-16

**To Reproduce**

```
# on openSUSE or Debian:
$ osc checkout openSUSE:Factory/cabal-install && cd $_
for i in 1 2 3 ; do
  osc build --keep-pkg=RPMS --noservice
  rpm -qpvl RPMS/cabal-install-3.0.0.0-*.x86_64.rpm | grep cabal.1.gz | tee -a output-log.txt
done
cat output-log.txt

# actual results:
-rw-r--r--    1 root    root                    21803 Jan  4 21:21 /usr/share/man/man1/cabal.1.gz
-rw-r--r--    1 root    root                    29319 Jan  4 21:27 /usr/share/man/man1/cabal.1.gz
-rw-r--r--    1 root    root                    33865 Jan  4 21:32 /usr/share/man/man1/cabal.1.gz


# or try manually:
for i in $(seq 1 3) ; do
  ghc --make -no-user-package-db Setup
  ./Setup configure
  ./Setup build
  md5sum dist/build/cabal/cabal.1 | tee -a output-log.txt
# 0c2c1f943e5c65348838e78a2e1645ca
# d41d8cd98f00b204e9800998ecf8427e
  wc dist/build/cabal/cabal.1
# 51656 121199 829384 dist/build/cabal/cabal.1
  ./Setup clean
  rm -f Setup
done
```

**Expected behavior**
Build output should be deterministic (aka reproducible).

**System information**
 - Operating system: openSUSE Tumbleweed 2020-01-01
 - `ghc` 8.8.1

**Additional context**

https://reproducible-builds.org/

**Comment by phadej** [comment]
I think we should drop generation of `man` page using `Setup.hs`...

**Comment by phadej** [comment]
man page is not generated due build process. Use `cabal man --raw` to get raw troff source, if you need it in distro packaging.

The generation should be deterministic, yet if it isn't please open a new issue with attached differing man page sources.

Done in #6548
