### ISSUE TITLE
cabal v2-exec fails to create environment.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6479]
```
[polinukli] /code/public-haskell/tree-diff master % cabal v2-exec env                       
Resolving dependencies...
/code/public-haskell/tree-diff/dist-newstyle/tmp/environment.-7050: createDirectory: does not exist (No such file or directory)
```
```
[polinukli] /code/public-haskell/tree-diff master % cabal --version
cabal-install version 3.0.1.0
compiled using version 3.0.1.0 of the Cabal library 
```
```
[polinukli] /code/public-haskell/tree-diff master % /opt/cabal/3.2/bin/cabal v2-exec env 
Resolving dependencies...
/code/public-haskell/tree-diff/dist-newstyle/tmp/environment.-7174: createDirectory: does not exist (No such file or directory)
```

**Comment by fgaz** [comment]
[here](https://github.com/haskell/cabal/blob/0d4ee7ba30f671fbaa1162c2373abb27c460478a/cabal-install/Distribution/Client/CmdExec.hs#L231) the parent may not exist.
Solution: either we create it before calling withTempDirectory, or we modify withTempDirectory to do the equivalent of mkdir -p.
The first option is probably better. Look for other places where distTempDirectory is used to see how it's done

**Comment by phadej** [comment]
In other places the `distTempDirectory` is explicitly created before calling to `withTempDirectory`, I'll go with that.
