### ISSUE TITLE
multiple libraries in cabal breaks module loading

### ISSUE THREAD

**Issue by kuribas** [haskell/cabal#6487]
**Describe the bug**
The typerep-map package has multiple library stanzas.  This breaks loading the Data.TypeRepMap module in ghc and ghci.

**To Reproduce**
```
$ cabal v1-install typerep-map
$ ghci
Prelude> import Data.TypeRepMap
```
**Expected behavior**
loading modules installed in global packages should work

**System information**
 - Linux mint
 - cabal-install version 2.4.1.0
 -  compiled using version 2.4.1.0 of the Cabal library 
 - ghc: The Glorious Glasgow Haskell Compilation System, version 8.4.4

**Comment by phadej** [comment]
Can you try with `cabal-install-3.0.0.0`?

**Comment by phadej** [comment]
Also with `cabal-env` it works, so if it doesn't work with `cabal-install-3.0.0.0`, there's that

```
[polinukli] ~ % cabal-env typerep-map
[   0.00041] debug: runProcess cwd=/home/phadej/.ghc ghc --info
[   0.04699] debug: GHC environment directory: /home/phadej/.ghc/x86_64-linux-8.6.5/environments
[   0.04972] debug: runProcessOutput cwd=/tmp/peura-XXXX-75693c78fcc6ea78 cabal v2-build all --builddir=dist-newstyle
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - typerep-map-0.3.2 (lib) (requires download & build)
 - fake-package-0 (lib) (first run)
Downloading  typerep-map-0.3.2
Downloaded   typerep-map-0.3.2
Starting     typerep-map-0.3.2 (lib)
Building     typerep-map-0.3.2 (lib)
Installing   typerep-map-0.3.2 (lib)
Completed    typerep-map-0.3.2 (lib)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Building library for fake-package-0..
[  14.43300] debug: Process run for 14.383 seconds
[  14.43638] debug: writing environment file
[  14.44338] debug: runPeu completed successfully
[polinukli] ~ % ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Loaded package environment from /home/phadej/.ghc/x86_64-linux-8.6.5/environments/default
Prelude> import Data.TypeRepMap
Prelude Data.TypeRepMap> 
```

**Comment by Mikolaj** [comment]
@kuribas: thank you for the report. I assuming the issue is fixed. I you could kindly verify (with newest cabal) and reopen, if not fixed, that would help us a lot.

@dmjio, if you have any extra clues or if you'd like to double-check the problem is gone, please do.
