### ISSUE TITLE
cabal-install doesn't work with username using locale characters.

### ISSUE THREAD

**Issue by bos** [haskell/cabal#650]
(Imported from [Trac #658](http://hackage.haskell.org/trac/hackage/ticket/658), reported by @shelarcy on 2010-04-09)

If Windows user uses national account name, cabal update is fail.

See: [http://www.sampou.org/cgi-bin/w3ml.cgi/haskell-jp/msg/545](http://www.sampou.org/cgi-bin/w3ml.cgi/haskell-jp/msg/545) (in Japanese)

I thought this problem is GHC 6.10.x and older's bug. So, I tested on Haskell Platform 2010.1.0.0 Windows installer RC3's cabal-install (version 0.8.1), and more recently version cabal-install 0.8.2. But this problem occur newer version (with my National account), too.

<pre class="wiki">C:\Documents and Settings\崇裕&gt;cabal update
Downloading the latest package list from hackage.haskell.org
cabal: invalid argument
</pre>And I tried to use cabal install command in package's directory. But cabal install is also fail.

<pre class="wiki">C:\home\working\parsec-3.1.0&gt;cabal install
cabal: C:\Documents and Settings\ﾕ\Application
Data\cabal\packages\hackage.haskell.org\00-index.tar: invalid argument
</pre>Above error message shows wrong path, but GHC 6.12.1's getTemporaryDirectory, getAppUserDataDirectory and getHomeDirectory show correct path.

<pre class="wiki">Prelude System.Directory&gt; getTemporaryDirectory
"C:\DOCUME~1\\23815\35029\LOCALS~1\Temp\"
Prelude System.Directory&gt; getAppUserDataDirectory "cabal"
"C:\Documents and Settings\\23815\35029\Application Data\cabal"
Prelude System.Directory&gt; getHomeDirectory
"C:\Documents and Settings\\23815\35029"
</pre>So, I think cabal's function passes ascii version's API (_A) instead of wide charactor version's API (_W) internally.

I don't know where this problem come from, cabal-install or Cabal or GHC's library. So, I report this bug on Hackage's Bug Tracker.

**Comment by BardurArantsson** [comment]
Was this fixed with the referenced merge? Can it be closed?

**Comment by ezyang** [comment]
Is #700 related?

**Comment by 23Skidoo** [comment]
Not sure.

**Comment by gbaz** [comment]
This seems to come up with some frequency and is a bad failure case. @Mistuke you've had helpful input on related issues. Do you see a path forward here?

**Comment by Mistuke** [comment]
This is just a CodePage issue. GHC correctly calls the appropriate Unicode APIs, however it encodes characters using the console's CodePage. The default CodePage for consoles on Windows is an ANSI one.

Example, on a fresh cmd session:

```
崇裕@Rage C:\Users\崇裕
> cabal update
Config file path source is default config file.
Config file C:\Users\??\AppData\Roaming\cabal\config not found.
Writing default configuration to C:\Users\??\AppData\Roaming\cabal\config
C:\Users\??\AppData\Roaming\cabal\config.tmp: commitBuffer: invalid argument (invalid character)
```

This because the output functions don't know how to encode the characters and so they send invalid ones. Changing the CodePage to `UTF-8`:

```
崇裕@Rage C:\Users\崇裕
> chcp 65001
Active code page: 65001

崇裕@Rage C:\Users\崇裕
> cabal update
Config file path source is default config file.
Config file C:\Users\崇裕\AppData\Roaming\cabal\config not found.
Writing default configuration to C:\Users\崇裕\AppData\Roaming\cabal\config
Downloading the latest package list from hackage.haskell.org
```

`Win32` exposes functions to programmatically change the CodePage for the process. So one solution for `cabal` may be to change the CodePage to UTF-8 on startup if supported https://github.com/haskell/win32/blob/609843b254bc47b9b20f2fe7a9a51b159bfb8de2/System/Win32/Console.hsc#L56

However do note that GCC does not call the Unicode APIs, so compilation will still fail. Some patches upstream will be required to fix this.

**Comment by Mistuke** [comment]
I'll have a patch for this for the next release hopefully. The reason I'm delaying it is that even if I did fix it it would fail when you try to use the package as gcc can't understand the path. So I rather have it fail early until the entire pipeline is fixed

**Comment by epogrebnyak** [comment]
I seem to bump over this issue too, my Windows home path is, unfortunately, `C:\Users\Евгений`

```
entropy-0.4.1.5-15TY7PVlUsH21GYWWy2zmK failed during the configure step. The
exception was:
dieVerbatim: user error (cabal: 'C:\Program Files\Haskell
Platform\8.4.3\bin\ghc.exe' exited with an
error:
C:\Users\B7E3~1\AppData\Local\Temp\ghc5676_0\ghc_11.rsp: commitBuffer: invalid
argument (invalid character)
)
```

I get this in `cabal install -j --disable-tests wreq`

**Comment by gbaz** [comment]
@Mistuke whatever happened with this?

**Comment by Mistuke** [comment]
@gbaz I fixed it in GHC proper. A cabal compiled with winio enabled should work fine.

**Comment by gbaz** [comment]
Great! Closing this ticket as resolved.
