### ISSUE TITLE
Drop Travis

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6500]
I have set up the GitHub actions:
- They worked well for the past month
- (Recently I added also windows jobs, but let's have appveyor still for time being)
- Let's also run Travis on 3.2 branch

So now Travis is not needed anymore, but I don't want to pull the trigger without larger acknowledgment. Please comment @23Skidoo, @hvr, @ezyang

**Comment by ezyang** [comment]
Go for it. We can get rid of the crazy sake-bot nonsense too once we do this, right?

**Comment by phadej** [comment]
@ezyang, I'd keep travis setup in 3.2 branch for at least until Summer 2020, just in case.
