### ISSUE TITLE
different dependency resolution between v2-build and v2-install

### ISSUE THREAD

**Issue by demokritos** [haskell/cabal#6509]
**Describe the bug**
v2-build and v2-install resolve dependencies differently. So they install different set of packages and identical packages with different hash.

**To Reproduce**
1. With lrucache, time-locale-compat, hakyll installed in the store, hakyll-init <some directory>
2. cabal v2-build --dry-run
3. cabal v2-install --dry-run
4. compare two result
```
$ cabal v2-build --disable-documentation --ghc-option=-dynamic --allow-newer --dry-run
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following would be built (use -v for more details):
 - lrucache-1.2.0.1 (lib:lrucache) (requires build)
 - time-locale-compat-0.1.1.5 (lib) (requires build)
 - hakyll-4.13.0.1 (lib) (requires build)
 - test-blog-0.1.0.0 (exe:site) (first run)

$ cabal v2-install --disable-documentation --ghc-option=-dynamic --allow-newer --dry-run
Wrote tarball sdist to
/home/esrevinu/tmp/test-blog/dist-newstyle/sdist/test-blog-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following would be built (use -v for more details):
 - hakyll-4.13.0.1 (lib) (requires build)
 - test-blog-0.1.0.0 (exe:site) (requires build)
cabal v2-install --disable-documentation --ghc-option=-dynamic --allow-newer   8.01s user 0.74s system 99% cpu 8.795 total
```

**Expected behavior**
At least, v2-build and v2-install install the same dependency packages.

**System information**
 - Operating system : Arch Linux
 - `cabal`, `ghc` versions : cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library; ghc 8.8.1

**Additional context**
```
$ ghc-pkg list --package-db=/home/esrevinu/.cabal/store/ghc-8.8.1/package.db
/home/esrevinu/.cabal/store/ghc-8.8.1/package.db
    hakyll-4.13.0.1
    lrucache-1.2.0.1
    time-locale-compat-0.1.1.5
```
hakyll is also installed. So v2-build and v2-install don't need to install hakyll. The desired dependency resolution can be achieved by giving a flag `--ghc-pkg-option=--package-db='/home/esrevinu/.cabal/store/ghc-8.8.1/package.db'`. It seems that cabal does dependency resolution inconsistently.
```
$ cabal v2-build --disable-documentation --ghc-option=-dynamic --allow-newer --ghc-pkg-option=--package-db='/home/esrevinu/.cabal/store/ghc-8.8.1/package.db' --dry-run
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following would be built (use -v for more details):
 - test-blog-0.1.0.0 (exe:site) (first run)

$ cabal v2-install --disable-documentation --ghc-option=-dynamic --allow-newer --ghc-pkg-option=--package-db='/home/esrevinu/.cabal/store/ghc-8.8.1/package.db' --dry-run
Wrote tarball sdist to
/home/esrevinu/tmp/test-blog/dist-newstyle/sdist/test-blog-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following would be built (use -v for more details):
 - test-blog-0.1.0.0 (exe:site) (requires build)
cabal v2-install --disable-documentation --ghc-option=-dynamic --allow-newer   9.02s user 0.99s system 99% cpu 10.066 total
```

**Comment by demokritos** [comment]
I had `ghc-pkg-options: --package-db=/home/esrevinu/.cabal/store/ghc-8.8.1/package.db` in `~/.cabal/config`. Maybe, for the same reason as #6505, ghc-pkg-options is not passed to the ghc-pkg for some packages, and then cabal generates different hashes for dependency packages. 

Without the flag in the config file, I re-installed hakyll and its depencies. But v2-build and v2-install still try to install hakyll. `--ghc-pkg-option=...` command-line option fixes it again.

**Comment by jneira** [comment]
I think it should work without the workaround of passing explicitly `.cabal/store/ghc-8.8.1/package.db`

**Comment by demokritos** [comment]
@jneira It seems that cabal requires hashes from hackage, not cabal local store if not specifying package-db. I have installed hakyll with github head and my build fix. So I think that package hash is different from the hash from hackage, and cabal tries to install hakyll.
