### ISSUE TITLE
cabal macros header file doesn't generate paths that match file system case

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#6510]
found this in the course of building some stuff with ghc master  with clang based `cc`,

a representative error is 

```
<built-in>:16:10: error:
     error: non-portable path to file '"_build/stage1/utils/haddock/build/Haddock/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#include "_build/stage1/utils/haddock/build/haddock/autogen/cabal_macros.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "_build/stage1/utils/haddock/build/Haddock/autogen/cabal_macros.h"
1 error generated.
```

**Describe the bug**

**To Reproduce**

```
$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by cartazio** [comment]
cc @bgamari

**Comment by cartazio** [comment]
this is on apfs on mac

**Comment by cartazio** [comment]
to be clear: this problem only gets tickled with ghc validate builds on OSX afaict, but seems like a sane thing to cleanup

**Comment by cartazio** [comment]
(i think its a cabal problem rather than a hadrian build system problem, though i could be wrong)

**Comment by cartazio** [comment]
and seems to be OSX specific ...

**Comment by phadej** [comment]
Is this `Cabal` or ghc build system?

**Comment by phadej** [comment]
This is `hadrian` bug, not `Cabal`s.
