### ISSUE TITLE
Advice: shared, read-only package store?

### ISSUE THREAD

**Issue by endgame** [haskell/cabal#6515]
## Background

I'm doing some work for a university that teaches Haskell to its first-year students, and I am helping them keep their Haskell tooling up-to-date.

The student environment consists of GNU/Linux machines deployed and updated over the network, and student home directories access via a network share. The course will teach 400-500 students at a time, and if we use `v2-style` commands I am concerned that if each student downloads and builds all their packages in `$HOME/.cabal/...`, they will either run out their quota or fill the network drive.

This has not been a problem to date, as the university can build and deploy GHC+Libraries by installing everything they need with `v1-style` commands. When those commands go away, I'm not sure what to do.

## Objectives

I want to be able to set things up so that the following are all true:

1. There is a shared, read-only store of packages that the `v2-commands` can see.
2. For future-proofing reasons, the build scripts for this store should be written only using `v2-commands`.
3. Students can see the common store, but if they need additional packages `cabal v2-install` will install to `$HOME/.cabal/...` (This is a stretch goal - we could run the class by preinstalling everything we need into a shared, read-only store at `/usr/local/lib/cabal` or something, but it would be a shame to cap the exploration of inquisitive students.)

## What I think I want

I see that there is a global `[store-dir](https://cabal.readthedocs.io/en/latest/nix-local-build.html#cmdoption-store-dir)` option; while we could populate a store under `/usr/local/lib` or similar, doing so would prevent students from using cabal-install to install their own packages on top of the ones we provide.

I think my ideal solution would be to have some way of telling cabal-install that there are multiple stores it can try and read from, and also which of the several stores it should try to write to if it needs to build new packages. Does something like this exist, or is there a better way to achieve what I'm trying to do?

**Comment by phadej** [comment]
You can have a store in shared location, then your students would need to use `--store-dir` or `cabal user-config update -a "store-dir: /usr/local/lib/cabal/store"` e.g. you'd probably also want to have `remote-repo-cache` configured similarly, so the `01-index.tar` (~600MB) is shared. As a bonus, as students won't be able to update index, they will less likely to run into install plans out of what's in the cache.

The third point, having additional store directories is not supported. It's not impossible to implement, but I'm afraid you'd need to implement that yourself
- starting from adding `read-only-store-dirs` configuration option
- and following up the code where `--store-dir` is used to add `read-only-store-dirs` package databases to the proper places.
- I'm not 100% sure how the `RebuildMonad` would support things which could exist in multiple places, (but written to one), but it's reasonable functionality to have.

---

Completely different approach is to populate global ghc package-db with the packages you'd like to share, then each students' own store will have only additional stuff. The global package db shouldn't even restrict the install plans too much, as store packages may shadow global ones. However packages in global package db are preferred.

**Comment by endgame** [comment]
Thanks for your advice. That second option sounds a lot like how the haskell environments in nixpkgs work, but is there an easy way to set up that package-db once the deprecated v1-commands are removed?

**Comment by endgame** [comment]
I cannot seem to make this work. The packages preinstalled into `/usr/local/cabal/store` do not show up in `ghc-pkg list` (fair enough; they're not installed into the global package db).

But then I cannot seem to make `cabal v2-build` see them, either:
```
$ grep store-dir ~/.cabal/config
store-dir: /usr/local/cabal/store
$ ls /usr/local/cabal/store
ghc-8.6.5 # and lots of subdirectories for expected packages
$ cabal v2-build
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: comp1100-assignment2-0.1.0.0 (user goal)
[__1] unknown package: codeworld-api (dependency of comp1100-assignment2)
[__1] fail (backjumping, conflict set: codeworld-api, comp1100-assignment2)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: comp1100-assignment2, codeworld-api

$ cabal v2-build --package-db=/usr/local/cabal/store/ghc-8.6.5/package.db/
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: comp1100-assignment2-0.1.0.0 (user goal)
[__1] unknown package: codeworld-api (dependency of comp1100-assignment2)
[__1] fail (backjumping, conflict set: codeworld-api, comp1100-assignment2)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: comp1100-assignment2, codeworld-api
```
This seems to be a supported feature; what am I doing that's wrong?

**Comment by phadej** [comment]
The store is just a *cache*, `cabal` would still need to solve using index (that's the `Warning: The package list for 'hackage.haskell.org' does not exist.`) part.

And if the solving output matches, see

> e.g. you'd probably also want to have `remote-repo-cache` configured similarly, so the `01-index.tar` (~600MB) is shared.

in my previous commit, then it should work better.

**Comment by endgame** [comment]
Ah, I misunderstood what that message was trying to say. I'd hoped that by not having the cache I could restrict cabal to only trying to solve deps in its local store. Semester start is closing in, so we'll not have time to sort this out for the current semester, but I hope to get a sustainable long-term solution after that.

**Comment by phadej** [comment]
I thought about this a bit more. We'd need two features for such shared user systems:

- Ability to specify additional package-db's in `v2-build`
    - store would be still per user, but you won't need to pollute global db either.
    - slight problem is that in `~/.cabal/config` is compiler version independent, but package-dbs aren't.
        - one simple way is to make these additional read-only package databases have the store filesystem layout.
             - this way it's also easy to update them, just use them as the writable store
             - This is like `read-only-store-dirs` I mentioned.
        - another option would be to add `if impl(...)` support to configuration files.
          This is difficult task (but will be done eventually).
          One would still would need to add support for addtional package dbs.
          (I suspect Nix users may have use to this variant).
 - Allow "variables" in `~/.cabal/config`, e.g. specifying `store-dir: $home/...`.
   This is not strictly a requirement, but then you could have shared config file as well, which will improve end user experience.

The first, variables in `~/.cabal/config` is something I have on my TODO list (but no promises).
The second feature is something I cannot promise to be implemented by "Cabal Team" (essentially me),
but we would be happy to review the patch.
