### ISSUE TITLE
Document all environment variables "owned" by cabal

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#6516]
Maybe they are documented somewhere and i was not able to find them
Looking for `lookupEnv` in the codebase i've found:
* [ ] `CABAL_DIR` (i was looking for it!): change the default global cabal dir (by default `~/cabal` or `%APPDATA%\cabal`)
* [ ] `CABAL_SANDBOX_PACKAGE_PATH`
* [ ] `CABAL_SANDBOX_CONFIG`
* [X] `CABAL_CONFIG`: already documented
* [ ] `CABAL_BUILDDIR`

**Comment by phadej** [comment]
defined or used?

**Comment by jneira** [comment]
Well i want to mean that they are "owned" by cabal although it doesnt set them only looks for, changing title

**Comment by phadej** [comment]
See https://cabal.readthedocs.io/en/latest/installing-packages.html#environment-variables

**Comment by jneira** [comment]
Looks great! Thanks for take care of that
