### ISSUE TITLE
cabal sdist does not perform all checks.

### ISSUE THREAD

**Issue by bos** [haskell/cabal#652]
(Imported from [Trac #660](http://hackage.haskell.org/trac/hackage/ticket/660), reported by @kmcallister on 2010-04-11)

Some checks in <tt>Distribution.PackageDescription.Check</tt> are defined on <tt>GenericPackageDescription</tt> and are called via <tt>checkPackage</tt>.  <tt>checkPackage</tt> is called by <tt>configure</tt>, which ignores dist-related checks, but not by <tt>sdist</tt>, which only calls <tt>checkConfiguredPackage</tt>.

So any dist-related checks on <tt>GenericPackageDescription</tt>, e.g. warning of <tt>base</tt> version not bounded above, will have no effect.

**Comment by gbaz** [comment]
Since `cabal check` _does_ run all checks, these checks aren't really "inert". However, it is still irritating that `sdist` only does a partial check. It would be nice to fix this.

**Comment by ffaf1** [comment]
Closed via #8427
