### ISSUE TITLE
Fix password issue for curl transport

### ISSUE THREAD

**Issue by newhoggy** [haskell/cabal#6520]
**Describe the bug**
Currently when using `cabal` with `curl` transport with private hackage, `curl` will submit `...` as the password and fail authentication.  To work around this issue, we've had to use `wget` which has the downside of slow `cabal` updates because `wget` doesn't support range requests.

**To Reproduce**
Upload a package to password protected private hackage then try to get `cabal` to download it.

When using `wget` transport:

```
 cabal v2-update
Downloading the latest package lists from:
- hackage.haskell.org
- phackage
Warning: the 'wget' transport currently doesn't support range requests, which
wastes network bandwidth. To fix this, set 'http-transport' to 'curl' or
'plain-http' in '~/.cabal/config'. Note that the 'plain-http' transport
doesn't support HTTPS.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2020-01-31T06:17:33Z'
```

Steps to reproduce the behavior when using `curl` transport:

```
$ cabal get customer-data
Downloading  customer-data-1.0.7
Unexpected response 401 for https://mayhem:...@hackage.mayhem.arbor.net/package/customer-data-1.0.7.tar.gz
```

This works when using `wget` transport:

```
$ cabal get customer-data
Downloading  customer-data-1.0.7
Downloaded   customer-data-1.0.7
Unpacking to customer-data-1.0.7/
```

**Expected behavior**

**System information**
 - Operating system: MacOS (probably any system)
 - `cabal-3.0.0.0`, any `ghc` version

**Additional context**
None

**Comment by newhoggy** [comment]
Possible fix here #6184

**Comment by dsturnbull** [comment]
Related: https://github.com/haskell/cabal/issues/4743

**Comment by gbaz** [comment]
resolved by above
