### ISSUE TITLE
Cabal copy regression exposed via ghc-cabal?

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#6533]
**Describe the bug**
Bumping GHC's `Cabal` submodule from b9253565cc to e4db2dcc3b appears to regress `Cabal` copy. Specifically, `test_bindist` fails with:
```
utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install ":" '' '/home/ben/ghc/ghc/bindisttest/install   dir' '/home/ben/ghc/ghc/bindisttest/install   dir/lib/ghc-8.11.0.20200207' '/home/ben/ghc/ghc/bindisttest/install   dir/share/doc/ghc-8.11.0.20200207/html/libraries' 'v  '  
Saved package config file is outdated:
• the Cabal version changed from Cabal-3.3.0.0 to Cabal-3.0
• the compiler changed from ghc-8.6 to ghc-8.11
Re-run the 'configure' command.
```

**To Reproduce**

Build the `wip/windows-ci` GHC branch; run `make binary-dist; make test_bindist`

**Expected behavior**

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by bgamari** [comment]
I have confirmed that reverting 429f5c3f43589b4f55eaef989695c5f80512aecc fixes the issue.

However,
```patch
diff --git a/boot/cabal_macros.template.h b/boot/cabal_macros.template.h
index 4cd5956bc..e14da10cd 100644
--- a/boot/cabal_macros.template.h
+++ b/boot/cabal_macros.template.h
@@ -27,9 +27,9 @@
 {% endfor %}
 
 {% if notNull packageKey %}
-#ifndef CURRENT_packageKey
-#define CURRENT_packageKey "{{ packageKey }}"
-#endif /* CURRENT_packageKey */
+#ifndef CURRENT_PACKAGE_KEY
+#define CURRENT_PACKAGE_KEY "{{ packageKey }}"
+#endif /* CURRENT_PACKAGE_KEY */
 {% endif %}
 {% if notNull componentId %}
 #ifndef CURRENT_COMPONENT_ID

```
does not resolve the issue.

**Comment by phadej** [comment]
@bgamari is it before or after I told you about `make templates`?

**Comment by bgamari** [comment]
I have confirmed that the above patch *does* fix the issue after running `make templates`.

**Comment by phadej** [comment]
@bgamari good, I'll turn it into proper patch ASAP (today).
