### ISSUE TITLE
Add OpenSearch description to cabal documentation

### ISSUE THREAD

**Issue by coot** [haskell/cabal#6537]
[OpenSearch MDN docs](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

Other haskell systems: GHC User Guide or hackage have it.

This allows to add a search engine to a webrowser (in firefox they appear in 'about:preference#search' in the `One-Click Search Engines` section).

**Comment by phadej** [comment]
Do you mean on https://cabal.readthedocs.io/en/latest/ or somewhere else?

Do you know how to add it?

**Comment by coot** [comment]
Yes, the readthedocs.

GHC docs include:
```
<link rel="search" type="application/opensearchdescription+xml" title="Search within Glasgow Haskell Compiler 8.8.1 User's Guide" href="_static/opensearch.xml">
```
and the linked [xml](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/_static/opensearch.xml)

It seems that `sphinx` has a configuration option for that:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_use_opensearch

**Comment by coot** [comment]
GHC links to the latest documentation, which is not ideal. Maybe there's a way for cabal to link to a specific version in `html_use_opensearch`.

**Comment by phadej** [comment]
Do you mind to make a PR, this sounds as a good improvement.

**Comment by coot** [comment]
Yes, but you'd need to point me where sphinx is configured.

**Comment by phadej** [comment]
The documentation is in `Cabal/doc`
