### ISSUE TITLE
Cabal gives contradictory reason for failing to build dependency tree

### ISSUE THREAD

**Issue by mouse07410** [haskell/cabal#6544]
**Description**
Produces contradictory report about failure to build a dependency tree: "cannot use A because user target requires B, cannot use B because user target requires A". ?!?

**To Reproduce**

```
$ cabal -v install hlint --overwrite-policy=always 2>&1 | tee hlint-build-log.txt
Reading available packages of hackage.haskell.org...
Using most recent state specified from most recent cabal update
index-state(hackage.haskell.org) = 2020-02-16T20:08:49Z
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: haskell-ide-engine (user goal)
[__0] rejecting: haskell-ide-engine-1.1 (constraint from user target requires
==0.12.0.0)
[__0] rejecting: haskell-ide-engine-0.12.0.0 (constraint from user target
requires ==1.1)
[__0] fail (backjumping, conflict set: haskell-ide-engine)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-ide-engine

$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
$ 
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
Successful build of the latest stable `hlint`.

**System information**
 - MacOS Catalina 10.15.3
 - `cabal`, `ghc` versions:
```
$ ghcup debug-info
Script version: 0.0.8

Script variables:
  GHC install location:     /Users/uri/.ghcup/ghc
  Binary install location:  /Users/uri/.ghcup/bin
  Tarball cache location:   /Users/uri/.ghcup/cache
  Downloader:               curl -L --fail -O <url>
  Script update url:        https://gitlab.haskell.org/haskell/ghcup/raw/master//ghcup
  GHC download baseurl:     https://downloads.haskell.org/~ghc
  Meta download url         https://gitlab.haskell.org/haskell/ghcup/raw/master//.download-urls
  Meta download format      1
  Meta version url          https://gitlab.haskell.org/haskell/ghcup/raw/master//.available-versions
  Meta version format       1

Detected system information:
  Architecture:   x86_64
  Distribution:   Darwin
  Distro alias:   darwin
  Distro version: 19.3.0
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
$ hie --version
Version 1.1, Git revision 66163e0f69ce4f9239c1723cb27a67e56156ec5d (3782 commits) x86_64 ghc-8.6.5
$ 
```

**Comment by grayjay** [comment]
That error message means that cabal is trying to install haskell-ide-engine, and there are two contradictory constraints, haskell-ide-engine==0.12.0.0 and haskell-ide-engine==1.1.  Did you run the command in a project directory that contains haskell-ide-engine?

**Comment by mouse07410** [comment]
> Did you run the command in a project directory that contains `haskell-ide-engine`?

Of course. How else would Cabal even find the relevant files?

The computer had an older installation of `haskell-ide-engine` from early last year. I'm trying to (a) install the current version, and (b) build a version compatible with GHC-8.8.2.

**Comment by grayjay** [comment]
> Of course. How else would Cabal even find the relevant files?

I was wondering how haskell-ide-engine was added as a "user target" since the install command only mentioned hlint.  User targets could come from the install command, environment file, or project directory.

> The computer had an older installation of haskell-ide-engine from early last year.

Did you install the older version with "cabal v2-install --lib"?  If so, the older version of the package in the global environment file (for example, ~/.ghc/x86_64-linux-8.6.5/environments/default) could be conflicting with the version in the project directory.

**Comment by phadej** [comment]
FWIW, #6410 is not fixed in any released version of `cabal-install`. With `master` or tips of `3.2` and `3.0` branches, global environment file should not affect project local `cabal install` plans.

**Comment by mouse07410** [comment]
> Did you install the older version with `cabal v2-install --lib`?

I honestly do not recall. It is possible.

> If so, the older version of the package in the global environment file ... could be conflicting with the version in the project directory.

How do I detect that, and if it turns out to be the case - how do I remedy it?

> FWIW, #6410 is not fixed in any released version of `cabal-install`

Understood. :-(

Any idea when those fixes would end up in the released versions?

**Comment by gbaz** [comment]
I think we can close this as resolved now due to the env changes.
