### ISSUE TITLE
cabal keeps overwriting config in cabal.project.local in the background

### ISSUE THREAD

**Issue by ahkole** [haskell/cabal#6555]
**Describe the bug**
Cabal keeps overwriting my config in `cabal.project.local` with the following content:

```
package *
  ghc-location: ghc

program-locations
  ghc-location: ghc

```
This seems to happen whenever you create a project using `cabal init -i` and choose to include a test suite. No matter how often I redo my configuration in `cabal.project.local`, cabal just keeps overwriting it with the same content. The overwriting usually happens within a few minutes after redoing the configuration. I didn't notice anything particular that triggers it.

**To Reproduce**

```
$ cabal init -i
```
In the interactive init, choose all defaults, except for:
* Whether to use sensible defaults, choose `n` here
* Type of project, choose `library` here
* Version of cabal specification, choose `2.4` here
* Source directory, choose `src` here
* Whether to add informative comments, choose `y` here

Some of these might not be important, but these are the settings I used. In the defaults, it should choose to generate a test suite, which causes the problems in my experience. After the init is complete, cabal should start automatically writing to `cabal.project.local` within a few minutes.

**Expected behavior**
I expect cabal to just leave my configuration in `cabal.project.local` alone.

**System information**
 - Operating system: Arch Linux
 - `cabal` version 3.0.0.0, `ghc` version 8.8.1

**Comment by coot** [comment]
Are you aware that `cabal configure` overwrites the `cabal.project.local` file?

**Comment by ahkole** [comment]
> Are you aware that `cabal configure` overwrites the `cabal.project.local` file?

Yes, I am. The problem is that the file gets overwritten without me running any command. Cabal seems to somehow run in the background and overwrites it periodically. I checked using an auditd watch on the file that cabal is indeed the process that keeps writing to the file. This happens without me running any cabal command myself.

**Comment by gbaz** [comment]
Clearly you must be running cabal in the background somehow (through `ghcide` or another helper tool?). It should not just run on its own. It runs a command, completes it, then exits.
