### ISSUE TITLE
cabal - generate tags 

### ISSUE THREAD

**Issue by coot** [haskell/cabal#6561]
I started working on an [experiment](https://github.com/coot/ghctags) to generate tags (e.g. for `vim` or `emacs`) by parsing Haskell source files.  To make it run over files with `CPP` pragmas one needs access to flags introduced in `cabal` files and the generated `cabal_macros.h` header files.  For that reason it makes more sense to add a command `cabal tags`.

I would like to know what criteria would need to met to merge into cabal, or is there any interest in doing the work - I would really like to have such a tool to make navigation easier (and I am willing to do the work :) ). Other solutions are not perfect, though work most of the time, e.g. `hasktags` generates tags not by parsing but by pattern matching, and occasionally it misses some identifiers.

At first I want something simple, without caching - just plain vim / emacs tags files.

Things that can be added after initial implementation:
*  caching of generated tags per module (so one does not re-generate everything), could be added later.
* other preprocessors (hsc files, literate haskell) - though maybe this just works, I just haven't tried. I am using `DriverPipeline.preprocess` directly from `ghc` package.

The interface would be the same as for `cabal build`, e.g. `cabal tags pkg:somepkg` to generate tags for all components of `somepkg`.

**Comment by coot** [comment]
This will impose a dependency on `ghc` (for parsing).  I wonder how big problem is this? One could write a ghc plugin to do the parsing and let the user specify a specific version of it.

**Comment by phadej** [comment]
I don't think this belongs to `cabal`. There's `hasktags` which does good approximation. It could read `plan.json` using `cabal-plan` to learn about configuration (incl. compiler and flags), if it would like to do better job. Also `ghcide` and other ide efforts are on their way.

Dependency on `ghc` is a problem. Even in `cabal-install`.

**Comment by coot** [comment]
`hastags` is not  100% reliable - especially if type some type level features are present in a codebase. If we have a good support for `ghc` plugins (I left a comment here: #6169), that would also do.

A way to go around `ghc` dependency is to use a compiler plugin (I published an initial version of such a plugin [ghc-tags-plugins](https://hackage.haskell.org/package/ghc-tags-plugin-0.1.0.1)).  Either #6169 or a specialized version of `build` command which adds a dependency on `ghc-tags` would do.  The former is a better solution, the latter easier to do (at least to my limited knowledge of `cabal-intall` & `Cabal`).

**Comment by coot** [comment]
Closing, I found a way to run the plugin without need for help from `cabal`.  Modifying `cabal.project.local` file is enough.
