### ISSUE TITLE
"cabal v2-install --lib" uses the wrong directory for the global package environment on Windows

### ISSUE THREAD

**Issue by aboichis** [haskell/cabal#6565]
**Describe the bug**
cabal writes the package environment file in the directory returned by `getHomeDirectory`.
GHC uses `getAppUserDataDirectory`.
These are the same on Linux, but different on Windows (%HOMEPATH% and %APPDATA% respectively)

**To Reproduce**

```
cabal v2-install --lib vector
ghci
```

**Expected behavior**
The package environment file should be created in the correct directory and ghci should load it on startup.

**System information**
 - Windows 10
 - cabal 3.0.0.0, ghc 8.6.5

**Comment by vituscze** [comment]
I can't test the change right now, but something like this should make it match the GHC defaults: https://github.com/vituscze/cabal/commit/84a97d9bce6b725c70e6a4de3fb808c60986a2ff
