### ISSUE TITLE
'cabal new-configure' fails to print the list of dependency packages

### ISSUE THREAD

**Issue by yurivict** [haskell/cabal#6584]
On FreeBSD I am trying to compile the project https://github.com/lettier/gifcurry

Its latest version 6.0.0.0 isn't on Hackage, which shouldn't be a problem.

The recommended command from the FreeBSD ports framework ```make cabal-extract-deps``` runs this command:

> HOME=/usr/ports/multimedia/hs-gifcurry/work/cabal-home cabal new-configure --flags=""

It fails:
```
'cabal.project.local' file already exists. Now overwriting it.
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Gifcurry-6.0.0.0 (user goal)
[__1] next goal: base (dependency of Gifcurry)
[__1] rejecting: base-4.12.0.0/installed-4.1... (conflict: Gifcurry =>
base==4.11.*)
[__1] fail (backjumping, conflict set: Gifcurry, base)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Gifcurry, base
```

It seems to still look for the version ```6.0.0.0``` on Hackage, even though Hackage only has some older version.

What is wrong here? What is the correct command to get all dependency packages of a Haskell project in the current directory?

**Comment by phadej** [comment]
https://github.com/lettier/gifcurry/blob/6dbdf345ead770dd5b67e00ace1767c479ca2db0/Gifcurry.cabal#L129
