### ISSUE TITLE
Update simple distribution for LHC

### ISSUE THREAD

**Issue by bos** [haskell/cabal#660]
(Imported from [Trac #668](http://hackage.haskell.org/trac/hackage/ticket/668), reported by dmp on 2010-04-29)

Cabal needs some updates for its LHC support. Two changes are needed (and implemented in the attached patch):

<blockquote>
1) Change the hackRtsPackage to not fail with an error.
The hackRtsPackage function was previously throwing an error when
it found zero or more than one rts packages. The rts package is not
needed in lhc, so the error is now ignored. This change now matches the
behavior in the GHC distribution (Distribution/Simple/GHC.hs)

</blockquote>

<blockquote>
2) Change the value passed to the odir for compiling C files.
The current code was doing a version check to catch a bug with GHC &lt;
6.4. Since lhc is only version 0.9, it was also failing on the version
check and passing an incorrect value to odir. Changed to use the
correct value as with GHC &gt; 6.4.

</blockquote>
I have attached a patch against the 1.8 branch that implements these changes.

**Comment by ttuegel** [comment]
Sadly, we've lost the original patch. I think it's safe to say this won't be fixed.
