### ISSUE TITLE
Cabal ReadTheDocs not configured for previous versions

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal#6601]
Cabal's [documentation](https://cabal.readthedocs.io/en/latest) (hosted by ReadTheDocs) does is not configured to host previous versions of the documentation.

Docs can be made available for previous versions from this page: https://readthedocs.org/projects/cabal/versions/ by anyone who's an admin.

Why? I'd like to remove the [Developing with sandboxes](https://www.haskell.org/cabal/users-guide/installing-packages.html#developing-with-sandboxes) section from the docs since this is unnecessary since Nix-style/`new-`/`v2-` became the default. In order to do this docs for previous versions which still contain this need to be available.

**Comment by phadej** [comment]
FWIW, we have `stable`, which is currently `3.0` but indeed we should have few past versions too.

**Comment by m-renaud** [comment]
If you'd like I can get that set up going back a few versions, I'd just need admin access on ReadTheDocs.

**Comment by m-renaud** [comment]
Documentation at cabal.readthedocs.io is now available for 2.4.1.0 and 3.0.0.0.

**Comment by phadej** [comment]
I guess it should have explicit tag for 3.2.0.0 too...

**Comment by m-renaud** [comment]
Done (see https://cabal.readthedocs.io/en/cabal-v3.2.0.0/). Currently configured to use tags to select the build commit, another alternative is to use the branch as the source of the docs, it just depends if when you backport doc changes if you also update the tag to point to the new commit (I'm not sure exactly what the semantics are of the tags for this repo, do they ever change once set?)

**Comment by phadej** [comment]
We never change tags (you shouldn't either). Good point about tags vs. branches, I'd rather setup to build branches.

(I cannot, I'm not admin on readthedocs).

**Comment by m-renaud** [comment]
Updated all versions to use the branches: 2.0, 2.4, 3.0, and 3.2. Versions before 2.0 don't have docs (at least in ReStructured Text form). I've removed the tag versions.

**Comment by phadej** [comment]
Thank you!
