### ISSUE TITLE
Add pijul to known repository type

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6610]
Makes sense to do after https://github.com/haskell/cabal/issues/6432

**Comment by v0d1ch** [comment]
I think I can tackle this.

**Comment by phadej** [comment]
@v0d1ch if you find (official) docs or tutorials on `pijul` illustrating the use of commands `cabal` would execute, please put them in the comments in the code.

**Comment by v0d1ch** [comment]
https://pijul.org/manual/reference.html
