### ISSUE TITLE
Cabal ignores "no_proxy" env var

### ISSUE THREAD

**Issue by mouse07410** [haskell/cabal#6630]
**Describe the bug**
Cabal ignores `no_proxy` environment variable, and if `http_proxy` is set - sends traffic there regardless.

In a deployment behind a firewall, web proxy must be specified to reach outside the corporate network, **but** communications with internal hosts must **not** go to the proxy.

**To Reproduce**

1. Define a local Hackage mirror, e.g., in `<project>/cabal.project file`:
```
packages: ./

repository ll-skete
  url: http://local-hackage:12345/packages/archive/
  -- secure: True
  -- root-keys:
  -- key-threshold: 3
```
Make sure Skete server is running on the above-specified host and port.

Then go to the project directory and do `cabal update`. Observe HTTP 502 error code, because proxy does not serve access to internal hosts.

**Expected behavior**
Successful communications with the local (inside the corporate perimeter) hosts, as well as with the remote ones (outside the firewall).

**System information**
 - MacOS Catalina 10.15.4
 - `cabal-3.0.0.0`, `ghc-8.8.3` 

**Additional context**
Living behind a firewall, so have the following env vars set:
- `HTTP_PROXY`
- `HTTPS_PROXY`
- `http_proxy`
- `https_proxy`
- `no_proxy`

**Comment by gbaz** [comment]
You need to pick an appropriate transport. Different transports interact with the proxy differently. If you're defaulting to curl, then set whatever flags curl should respect. If you're not using curl, then you may be using plan http, which is a rather limited library, and _instead_ pick curl or wget, etc.

**Comment by mouse07410** [comment]
> You need to pick an appropriate transport

How? On my machines I have running curl and wget. Both seem to respect the env vars my shell sets, including those for HTTP and HTTPS proxies, and `no_proxy`.

Would you mind giving an example...?

**Comment by phadej** [comment]
https://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-http-transport

**Comment by mouse07410** [comment]
Thank you! 

Do **all** of the Cabal commands accept this parameter? I'm asking because I tried it with `cabal update`, and it rejected it.

**Comment by phadej** [comment]
`cabal --http-transport=curl update` works here. Note that some arguments have to be before command. Compare `cabal --help` and `cabal build --help`.

**Comment by mouse07410** [comment]
> `cabal --http-transport=curl update` works here

Thank you! Yes, it works here as well (in addition, I had to muck around with `curl` until it learned to use my `no_proxy`).
