### ISSUE TITLE
Add cabal init --non-interactive PackageTest

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6649]
If (and as) more changes will be made, we should have tests.

`PackageTests` is a good option, as then one could also try to build the package etc.

**Comment by m-renaud** [comment]
Taking a look at this now, I'm not familiar with the PackageTest setup here so may have a few questions after I'm done digging around.

**Comment by jneira** [comment]
maybe test were added by @ptkato ?

**Comment by ptkato** [comment]
Aye, the tests are already there, in a stale PR, it just needs approval by one of the reviewers. I also have another PR aligned to add more tests, I just need to have the first PR I mentioned approved.

**Comment by jneira** [comment]
That is unfortunate, we should merge prs with tests asap as they are one of the more valuables additions
//cc @Mikolaj

**Comment by Mikolaj** [comment]
Agreed. @ptkato: which PRs are those?

**Comment by jneira** [comment]
The pr adding a test for non interactive is https://github.com/haskell/cabal/pull/7951
The test is https://github.com/haskell/cabal/pull/7951/files#diff-8fcdf9d2a190cf09492d83bf897470659923d6568c2bbacaf157afad4762308f

**Comment by jneira** [comment]
I make the pr close this issue
