### ISSUE TITLE
cabal-install binaries do not work when built with -lukko

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#6657]
**Describe the bug**

cabal-install fails when built with `-flukko`

**To Reproduce**

First, build cabal-install with `--constraint='cabal-install -lukko' --constraint='hackage-security -lukko'`

Then:

```
cabal update
Downloading the latest package list from hackage.haskell.org
flock: invalid argument (Bad file descriptor)
```

All other subcommands fail too, viz.

```
cabal install sak -w ghc-8.8.3
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - sak-0.1.2.0 (exe:sak) (requires download & build)
Downloading  sak-0.1.2.0
cabal: Failed to download exe:sak from sak-0.1.2.0. The exception was:
flock: invalid argument (Bad file descriptor)
``` 

**Expected behavior**

Should do the same thing as `cabal update` which does use `lukko`. 

**System information**
 - Linux
 - cabal-install 3.2, x86_64 and aarch64

**Additional context**

Since lukko fails to cross-compile (see https://github.com/phadej/lukko/issues/18), this means that cross-compiled `cabal` binaries do not work as of 3.2

**Comment by phadej** [comment]
Will be fixed once https://github.com/haskell/hackage-security/pull/242 is merged and released.
