### ISSUE TITLE
Findable extra documentation

### ISSUE THREAD

**Issue by bos** [haskell/cabal#666]
(Imported from [Trac #674](http://hackage.haskell.org/trac/hackage/ticket/674), reported by jbapple on 2010-05-01)

I have a cabal package that should include extra documentation in the distribution. This documentation should not be written in Haddock.
1. There should be a field for this analogous to data-files or extra-source-files. The former is too much: the files do not need to be accessed by any Haskell runtime. The latter is not enough: it does not store the extracted files on the system on which the package is installed.
2. There should be a way for humans to find these files without loading up a GHC runtime or using Unix's "find". I suggest "cabal list" also shows, for installed packages with extra data or documentation files installed, where these files can be found.

**Comment by quasicomputational** [comment]
`extra-doc-files` is now a thing, which ought to satisfy this issue.
