### ISSUE TITLE
please release cabal-install with bootstrap.sh that works for ghc-8.8.3

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#6673]
with ghc-8.8.3, bootstrapping cabal-install does not work since the version for `HTTP` is incompatible with the version of `base` for that compiler.

I see that you already addressed and solved this in https://github.com/haskell/cabal/pull/6636/commits/b6f7ec5f3598f69288bddbdba352e246e337fb90 

This issue here is about releasing the resulting source tarball on hackage.

If that's not possible -- is there some other work-around (short of patching the file manually)? E.g., can we put `--allow-newer` somewhere during bootstrapping, and would that help?

NB: My use case is is first-time users (students - who do this at home because of the lockdown). They want to build  everything on the same ghc version,  similar to #6327 (packagers). I know there are alternatives, e.g.,
* bootstrap cabal-install with previous ghc
* use Haskell platform binary (does it exist for 8.8.3?)
* use other binary distribution mechanism (stack)
* use some online service instead of local installation.

none of which I really like, e.g., I don't want to teach "wget .. | sudo sh". Well, I guess that's my problem then.

**Comment by phadej** [comment]
Please don't use `bootstrap.sh` script if you have older `cabal`.

The primary way of installation of `cabal-install` from source is `cabal install cabal-install`.

**Comment by phadej** [comment]
I'm tempted to remove `bootstrap.sh` from source distribution. It's not meant for large public.

**Comment by phadej** [comment]
Thanks to @m-renaud we now have [*Getting started*](https://cabal.readthedocs.io/en/latest/getting-started.html) page in the users guide. It says

> To install the Haskell toolchain follow the [ghcup instructions](https://www.haskell.org/ghcup/) if you’re using Linux or Mac, or follow [this guide](https://hub.zhox.com/posts/introducing-haskell-dev/) if you’re using Windows.

**Comment by hvr** [comment]
@jwaldmann I'd like to understand your problem a bit better; by which means do you procure the GHC binaries? And why doesn't the same mechanism suffice for cabal as well?

**Comment by jwaldmann** [comment]
Thanks. I didn't know about ghcup. It solves the cabal-install bootstrapping problem by picking a binary from https://downloads.haskell.org/cabal/cabal-install-3.2.0.0/ 
I didn't know such a resource exists.

**Comment by jwaldmann** [comment]
@hvr didn't notice your question at first.

* ghc: install binary package from haskell.org/ghc 
* cabal-install: I didn't know there are "offical" binary packages.

I wanted to avoid third-party binaries.

**Comment by hvr** [comment]
@jwaldmann I'm glad your concern was actually addressed then! :-)

Btw, is there anything we can do to improve the discoverability in a way that would have saved you from not being aware of this?

**Comment by ciez** [comment]
any suggestions for package builders?

does `cabal install cabal-install` work for rooted builds?

how is it possible to specify install prefix?
