### ISSUE TITLE
Should SPDX.NONE be the default option in 'cabal init --interactive'?

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal#6675]
When using `cabal init --interactive` at HEAD there is no longer a default licence in the prompt list (as of https://github.com/haskell/cabal/commit/2fa83023606e89f933bfe0d8779ea805f44b08eb). This means that you can't just press `<ENTER>` when going through the interactive prompt.

Before (with default, can just press `<ENTER>`):
```
Please choose a license:
   1) GPL-2
   ...
 * 7) BSD3
   ...
  14) Other (specify)
Your choice? [default: BSD3] 
Author name? [default: Matt Renaud] 
```

HEAD:
```
Please choose a license:
   1) NONE
   ...
  18) Other (specify)
Your choice? 
 is not a valid choice.
Your choice? 1
```
Should we default this to `Flag SPDX.NONE` @phadej?

**Comment by phadej** [comment]
Yes. Sorry for overlooking this.

**Comment by m-renaud** [comment]
No worries, if you don't have time to put together a PR I can do that tonight or tomorrow, just lmk!

**Comment by phadej** [comment]
Please do. I don't work on `Cabal` full-time, so any help especially with "trivial" issues is welcome.
