### ISSUE TITLE
cabal (v2-)haddock results in "unexpected status"

### ISSUE THREAD

**Issue by pmiddend** [haskell/cabal#6679]
**Describe the bug**
I'm writing some haddock documentation for my program (meaning, just an executable). When running `cabal v2-haddock`, I get:

```
cabal v2-haddock
cabal: renderBuildTargetProblem: unexpected status (TargetDisabledByUser,Nothing)
CallStack (from HasCallStack):
  error, called at ./Distribution/Client/CmdErrorMessages.hs:329:14 in main:Distribution.Client.CmdErrorMessages
```

**To Reproduce**

```
git clone https://github.com/pmiddend/nixos-manager
# either
nix-shell --run "cabal v2-haddock"
# or possibly just:
cabal v2-haddock
```

**Expected behavior**

Well, `cabal haddock --haddock-executables` works. I guess that is supposed to happen then :)

**System information**
 - NixOS
 - cabal 3.0.0.0, ghc 8.8.3

**Comment by phadej** [comment]
Could you minimize the reproducer

```
root@09667402f9bd:~/nixos-manager# cabal v2-haddock
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: nixos-manager-1.0 (user goal)
[__1] trying: haskell-gi-base-0.23.0 (dependency of nixos-manager)
[__2] trying: gi-gtk-declarative-app-simple-0.6.3 (dependency of
nixos-manager)
[__3] next goal: haskell-gi (dependency of gi-gtk-declarative-app-simple)
```
fails for other reasons...

I guess one needs a package with an executable and not library, or is there something else in the mix?

**Comment by pmiddend** [comment]
Oh, sorry phadej. You're right, my example isn't exactly minimal. I tried removing all the dependencies from `build-depends` and then doing `cabal v2-haddock`. The same thing happens. Does that help?

**Comment by phadej** [comment]
Yes. I guess we should instead of

```
% cabal haddock
cabal: renderBuildTargetProblem: unexpected status (TargetDisabledByUser,Nothing)
CallStack (from HasCallStack):
  error, called at ./Distribution/Client/CmdErrorMessages.hs:331:14 in main:Distribution.Client.CmdErrorMessages
```

fail like `test` does

```
% cabal test
Resolving dependencies...
No tests to run for the package nixos-manager-1.0
```

I suspect that we have some check somewhere missing, shouldn't be too difficult to find by comparing `CmdHaddock.hs` and `CmdTest.hs`

**Comment by noughtmare** [comment]
For a minimal example, I'm also getting this error when running `cabal haddock` on a fresh `cabal init` project. I'm using cabal-install and Cabal library version `3.2.0.0`. Running `cabal haddock` in a project created with `cabal init --lib` does work correctly.

**Comment by anacrolix** [comment]
I'm seeing this with Cabal 3.4.0.0:
```
$ cabal haddock
cabal: renderBuildTargetProblem: unexpected status (TargetDisabledByUser,Nothing)
CallStack (from HasCallStack):
  error, called at ./Distribution/Client/CmdErrorMessages.hs:356:14 in main:Distribution.Client.CmdErrorMessages
```
