### ISSUE TITLE
`cabal upgrade` leads to odd diagnostic

### ISSUE THREAD

**Issue by jrp2014** [haskell/cabal#6691]
**Describe the bug**
I inadvertently tyoed `cabal upgrade` instead of `cabal update` and got a strange diagnostic

**To Reproduce**

```
$ cabal upgrade
fromFlag NoFlag. Use fromFlagOrDefault
CallStack (from HasCallStack):
  error, called at ./Distribution/Simple/Flag.hs:98:21 in Cabal-3.2.0.0 w73VV9T25vCb2mhueKgfz:Distribution.Simple.Flag
  fromFlag, called at main/Main.hs:909:15 in main:Main

$ cabal v2-upgrade
cabal: unrecognised command: v2-upgrade (try --help)
```

**Expected behavior**
So far as I aware, `upgrade` is not a valid `cabal` command so I should get an `unrecognised command` diagnostic.

**System information**
 - Operating system: MacOS Catalina
 - `cabal`, `ghc` versions: cabal 3.2.0.0, ghc 8.8.3

**Additional context**
This is obviously not a deal breaker, but it may point to a deeper bug in `cabal` command line parsing.

**Comment by phadej** [comment]
There is in fact `cabal upgrade` command, which would print you a 

```haskell
    "Use the 'cabal install' command instead of 'cabal upgrade'.\n"
 ++ "You can install the latest version of a package using 'cabal install'. "
 ++ "The 'cabal upgrade' command has been removed because people found it "
 ++ "confusing and it often led to broken packages.\n"
 ++ "If you want the old upgrade behaviour then use the install command "
 ++ "with the --upgrade-dependencies flag (but check first with --dry-run "
 ++ "to see what would happen). This will try to pick the latest versions "
 ++ "of all dependencies, rather than the usual behaviour of trying to pick "
 ++ "installed versions of all dependencies. If you do use "
 ++ "--upgrade-dependencies, it is recommended that you do not upgrade core "
 ++ "packages (e.g. by using appropriate --constraint= flags)."
 where
```

if it wasn't buggy.

**Comment by phadej** [comment]
The question is, should we fix `upgrade` command or just remove it?

**Comment by hvr** [comment]
@phadej `cabal upgrade` sounds like a relict from the v1-* UI idiom... I'm not sure it makes any sense in the v2-* UI paradigm anymore.

**Comment by phadej** [comment]
I take that as we can just remove `cabal upgrade` command?

There is also `win32selfupgrade` command which I have no idea about (it's for sure not tested). Does @Mistuke know about it?

And also `uninstall` which is not implemented, so can be removed as well?

(Other `hiddenCmd` make sense to exist, like `act-as-setup`, I guess they don't even need to be hidden...)

**Comment by Mistuke** [comment]
I can't say I've ever heard of `win32selfupgrade`..  no clue that that does.

**Comment by phadej** [comment]
@Mistuke thanks for that insight. I'll make a PR removing `upgrade`, `win32selfupgrade` and `uninstall`.

**Comment by jrp2014** [comment]
Great work.. Thanks.
