### ISSUE TITLE
cabal-install-3.2.0.0 cannot build with ghc 8.10.1 on macOS

### ISSUE THREAD

**Issue by essandess** [haskell/cabal#6698]
I'm trying to update the MacPorts `cabal` port with `ghc` version 8.10.1, and running in to this build problem while running `bootstrap.sh`:

```
:info:build [1 of 1] Compiling Main             ( Setup.lhs, Setup.o )
:info:build Linking Setup ...
:info:build Configuring HTTP-4000.3.12...
:info:build Setup: Encountered missing or private dependencies:
:info:build base >=4.3.0.0 && <4.13
:info:build Error during cabal-install bootstrap:
:info:build Configuring the HTTP package failed.
```

I see the same issue https://github.com/haskell/cabal/issues/6327 open for `ghc` version 8.8.1.

**Comment by phadej** [comment]
`master` and tip of `3.2` branch are buildable with GHC-8.10

**Comment by essandess** [comment]
I'm still trying to build with ghc 8.10.2 and see this very same error.

I'm following these [instructions](https://github.com/haskell/cabal#installing-cabal-without-cabal) to the letter:
```
cabal-install $ ./bootstrap.sh # running ./bootstrap.sh from within in cabal-install folder.
```

Error:
```
:info:build [1 of 1] Compiling Main             ( Setup.lhs, Setup.o )
:info:build Linking Setup ...
:info:build Configuring HTTP-4000.3.12...
:info:build Setup: Encountered missing or private dependencies:
:info:build base >=4.3.0.0 && <4.13
:info:build Error during cabal-install bootstrap:
:info:build Configuring the HTTP package failed.
:info:build Command failed: /opt/local/var/macports/build/_opt_local_ports_lang_cabal/cabal/work/cabal-install-3.2.0.0/bootstrap.sh
```

**Comment by essandess** [comment]
> master and tip of 3.2 branch are buildable with GHC-8.10

Oh whoops, this is still using https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0-x86_64-apple-darwin17.7.0.tar.xz

I'll wait until 3.4.0.0 is released to try again.
