### ISSUE TITLE
Rewrite bootstrap.sh

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6700]
It should have:
- hardcoded lists of dependencies per GHC (and platform)
- bail out for unsupported combinations

These lists should be autogenerated, with help of `cabal-plan` (I have done something close in spirit in https://github.com/phadej/cabal-extras/tree/master/cabal-bundler so I know it's possible).

It should also check the hashes of `.tar.gz` and revision `.cabal` files downloaded (`cabal-bundler` does that).

Why so? Because `bootstrap.sh` is largely not maintained. We test it with single ghc-compiler version. Much better would be if it was "correct by construction".

---

The script should always work with self-created `ghc-pkg init` package database (which is called sandbox in current script). 

---

It should not generate documentation, when there's working `cabal-install`, one could iterate to get it. Same applies for anything extra. `bootstrap.sh` purpose is to get first working version on platform where there are no (older) `cabal-install`. All other use-cases are out-of-scope.

**Comment by bgamari** [comment]
I would imagine it would also be helpful to write it in a real language. This is the sort of thing I usually fall back onto Python for.

**Comment by bgamari** [comment]
I gave this a quick shot in #6719.

**Comment by phadej** [comment]
Continued in #6979
