### ISSUE TITLE
Unknown origin of Issue cabal-installing "regex-pcre-builtin"

### ISSUE THREAD

**Issue by dtheras** [haskell/cabal#6713]
My system: ghc-8.10.1 cabal-3.2.0.0

Attempting to install the library regex-pcre-builtin. My recent PR with regex-pcre-builtin bumped the library to support base-4.14.0.0. Cabal-list returned the following:

```
$ cabal list regex-pcre-builtin
* regex-pcre-builtin
    Synopsis: PCRE Backend for "Text.Regex" (regex-base)
    Default available version: 0.95.1.2.8.43
    Installed versions: [ Not installed ]
    License:  BSD3
```

When I want to install the library however:

```
$ cabal new-install --lib regex-pcre-builtin
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: base-4.14.0.0/installed-4.14.0.0 (user goal)
[__1] next goal: regex-pcre-builtin (user goal)
[__1] rejecting: regex-pcre-builtin-0.95.1.2.8.43 (constraint from user target
requires ==0.95.1.1.8.43)
[__1] rejecting: regex-pcre-builtin-0.95.1.1.8.43 (conflict:
base==4.14.0.0/installed-4.14.0.0, regex-pcre-builtin => base>=4.3 && <4.14)
.......
```

This literally makes no sense to me. Where is "constraint from user target
requires ==0.95.1.1.8.43" coming from? That seems to fly in the face of the cabal-list result. 

I have exhausted my know-how of cabal to resolve this issue. Please let me know if you need any more information. Thanks.

**Comment by phadej** [comment]
If you run 

```
% ghci-8.10.1
GHCi, version 8.10.1: https://www.haskell.org/ghc/  :? for help
Loaded package environment from /home/phadej/.ghc/x86_64-linux-8.10.1/environments/default
...
```

You'll probably get such environment file printed out, won't you? Does it contain the older `0.95.1.1.8.43)` version?

I suspect you run into https://github.com/haskell/cabal/issues/5888 (or some of its duplicates).

**Comment by dtheras** [comment]
Accurate and it solved the problem. I'll bare this in mind in the future too. Thanks. 

Sorry I didn't recognize my issue among the other issues. So it's appreciated.

**Comment by dtheras** [comment]
Got overjoyed too quick - your solution did help temporarily. 

Now experiencing everything as in #6512.
