### ISSUE TITLE
Getting Started instructions for Windows should link to official Haskell.org documentation

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal#6714]
Currently the Getting Started guide links to [this blog](https://hub.zhox.com/posts/introducing-haskell-dev/) for how to set up the Haskell toolchain on Windows. I suspect that led to [this question](https://www.reddit.com/r/haskell/comments/g2kc1w/is_setexecutionpolicy_bypass_safe_to_use_and_what/) on the r/haskell subreddit. I don't have a Windows machine so am not familiar with the best ways to set up an environment there, but the docs should really point to something official and up to date. Open to any suggestions here.

**Comment by jneira** [comment]
Agree, i think the main ways was pointed in the reddit comments, but i guess that it is not something official. 😄 
However `chocolatey` is a nice and beginner friendly way to install the tool chain,  cause it set sensible defaults to avoid common pitfalls. Unfortunately it is not integrated in windows by default and it is not widely known and used (and the permission thing could be a little bit scary to beginners). So i would not remove a reference to use it.

So ideally the [official haskell.org cabal page](https://www.haskell.org/cabal/#install-upgrade) should have a more detailed windows specific section, mentioning chocolatey. Moreover, the getting started link could be changed to the new section

In the meanwhile (forever? 😁) we could point to both sources (in this order): 
* the official one (https://www.haskell.org/cabal/#install-upgrade)
* the actual one to the blog post about chocolatey

**Comment by phadej** [comment]
> So ideally the official haskell.org cabal page should have a more detailed windows specific section, mentioning chocolatey. Moreover, the getting started link could be changed to the new section

:+1:

IMHO first installing e.g. Minimal Haskell Installer and then using it to upgrade `cabal-install` is just not the way for the beginners. haskell.org page "essentially" says *use `stack`*. I'm not re-starting drama about changing it though.

**Comment by gbaz** [comment]
The cabal page links to the platform. The platform now says "use chocolatey". So this is all the same at various levels of indirection.

**Comment by jneira** [comment]
Well, imo indirection is not good for beginners oriented docs but it could be ok.
Still i think we could do my previous proposal:

> In the meanwhile (forever? 😁) we could point to both sources (in this order):
> * the official one (https://www.haskell.org/cabal/#install-upgrade)
> * the actual one to the blog post about chocolatey

**Comment by m-renaud** [comment]
@jneira do you think you could update haskell.org/cabal with the Windows instructions? The source lives at https://github.com/haskell/cabal-website/blob/master/index.html. @23Skidoo has been the one maintaining that site so we should be able to get that change published pretty quickly. After that I can update the Cabal docs to point to it.

**Comment by jneira** [comment]
Yeah, it could be more cabal specific and include a note about the permission thing :wink:
Otoh it should point itself to the new get starting no?
