### ISSUE TITLE
Bindist for ARM

### ISSUE THREAD

**Issue by samuela** [haskell/cabal#6715]
There are no bindists for ARM. This is currently blocking ghcup support for the raspberry pi and other ARM devices: https://gitlab.haskell.org/haskell/ghcup-hs/issues/12#note_266006.

See https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/.

What needs to be done to get bindists for ARM?

**Comment by hvr** [comment]
I'd need to figure out on which machine those arm7 bindists of GHC were built on (ping @bgamari?) and whether I can get access there to build `cabal` binaries accordingly.

Same for aarch64 btw

**Comment by phadej** [comment]
I'd prefer that this is resolved via https://github.com/haskell/cabal/issues/6616 and not so various people provide bindists (in pretty opaque way). The assembly of bindists should be scripted with scripts perfectly living in this repository.

**Comment by phadej** [comment]
Note my comment on #6616. Based on my this week experiences, if ARM is not a platform which "just works", we (= regular Cabal contributors) won't have resources to maintain it.

**Comment by hasufell** [comment]
I feel this is a little awkward zic-zac. We made @samuela do extensive work on the cabal CI, although he was merely interested in ARM bindists. Now we're telling him ARM won't be supported? There surely is a better way to handle this:

1. include it in the CI
2. make sure users understand it is experimental
3. ask people for help on ARM, if bindists don't work. Apparently, there's at least a couple who care.

**Comment by samuela** [comment]
Ok, it's [official](https://www.theverge.com/2020/6/22/21295475/apple-mac-processors-arm-silicon-chips-wwdc-2020)... Apple is switching to ARM! So getting ARM builds working one way or another will be necessary.

**Comment by hasufell** [comment]
@samuela if you manage to make such bindists manually, then they can be used by ghcup as well. We're not constrained to upstream bindists.

**Comment by jneira** [comment]
Afaik we already have cabal bindists for arm thanks to gitlab ci config added by @hasufell so we could close this
@samuela feel free to reopen if anything is missing
