### ISSUE TITLE
Ability to specify extra-include-dirs and extra-lib-dirs via env variables

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/cabal#6716]
Having env variables corresponding to `extra-include-dirs` and `extra-lib-dirs` could be beneficial for muli-platform (at least MacOS vs Linux) builds where dependencies are installed in different paths.

**Comment by gbaz** [comment]
can't one just set LIBRARY_PATH and C_INCLUDE_PATH?

**Comment by AlexeyRaga** [comment]
@gbaz thanks!

**Comment by chansey97** [comment]
@AlexeyRaga Hi, I tried the LIBRARY_PATH and C_INCLUDE_PATH approach, it doesn't work. Have you ever succeeded with the approach? Setting extra-include-dirs and extra-lib-dirs in cabal/config is OK, but not very convenient.
