### ISSUE TITLE
ar issue on OmniOS

### ISSUE THREAD

**Issue by yobson** [haskell/cabal#6717]
I've been trying to build cabal on [OmniOS](https://omniosce.org) using bootstrap. I get the following error:
```
...
[234 of 235] Compiling Distribution.Simple.Doctest ( Distribution/Simple/Doctest.hs, dist/build/Distribution/Simple/Doctest.p_o )
[235 of 235] Compiling Distribution.Simple ( Distribution/Simple.hs, dist/build/Distribution/Simple.p_o )
ar: cannot open @dist/build/objs-20369/ar20369-2.rsp: No such file or directory
ar: @dist/build/objs-20369/ar20369-2.rsp not found

Error during cabal-install bootstrap:
Building the 3.0.2.0 package failed.
```
**To Reproduce**
```
$ ./bootstrap.sh --no-doc
```

**Expected behavior**
I expected the script to finish and cabal appear on my system in all it's glory!

**System information**
 - OmniOS Bloody
 - `cabal 3.0.2.0 & Head`, `ghc-8.8.1 & 8.4.4` versions (I tried a few combinations)
 - Nothing else installed on the system (just trying it out in a VM)

**Additional context**
I installed GHC by first installing `pkgin` from [Joyent](https://pkgsrc.joyent.com) and then grabbing the GHC packages from [here](https://pkgsrc.joyent.com/packages/SmartOS/2020Q1/x86_64/All/) (download them and run `pkgadd foo.tgz`)

I should note that the script failed earlier with linking errors, fixed by adding `-optl -fstack-protector` to the GHC call in `bootstrap.sh`. The linking errors were to gcc library to do with the stack protector (can't remember which) so I assumed stack protection is enabled by default in OmniOS and patched it. I don't think it's related but it could be!

I'd also like to thank the contributors to Cabal. It's a wonderful tool that has saved me hours and hours of dependency pain!

**Comment by PatrickMerisescu** [comment]
Experiencing the same issue on OpenIndiana. Adding to this, I ran a --verbose while installing.

```
/usr/bin/ar -r dist/build/objs-*/*.a '@dist/build/objs-*/ar*-*.rsp'
ar: cannot open @dist/build/objs-*/ar*-*.rsp: No such file or directory
```

For instance

```
/usr/bin/ar -r dist/build/objs-4748/libHSappar-0.1.8-6f5360c26589050437524e914681f3004c02932eafa6bc2eec812b88ec8286c9.a '@dist/build/objs-4748/ar4748-15.rsp'
ar: cannot open @dist/build/objs-4748/ar4748-15.rsp: No such file or directory
```

When trying to install xmobar

It seems to me as if ar is not creating the archive file.

Might be a year late but maybe we can get some info on this issue.

**Comment by gbaz** [comment]
The @ syntax indicates a response file. Such a file is not taken as an argument to the program itself, but rather is supposed to contain a further set of command line arguments. This is used to work around limitations on long cmd-line lengths which some OSes or programs explicitly disallow. What it looks like is happening here is the OSes in question do not have an `ar` executable that understands response file syntax, and so are treating the `@` argument as a regular argument, and not finding a file with the `@` appended. 

(cf https://gcc.gnu.org/wiki/Response_Files)

Note that cabal itself only uses response files if the ghc info (based on the configure/install of ghc) says this is ok. (https://github.com/haskell/cabal/pull/4596). So perhaps the ghc --info on these systems is incorrect, which should be fixed in the ghc toolchain for them.

**Comment by PatrickMerisescu** [comment]
> The @ syntax indicates a response file. Such a file is not taken as an argument to the program itself, but rather is supposed to contain a further set of command line arguments. This is used to work around limitations on long cmd-line lengths which some OSes or programs explicitly disallow. What it looks like is happening here is the OSes in question do not have an `ar` executable that understands response file syntax, and so are treating the `@` argument as a regular argument, and not finding a file with the `@` appended.

There is a --disable-response-files flag for cabal install. Using it strangely does not affect the process at all and it still attempts to create a response file, fails, and causes a fatal error.

**Comment by gbaz** [comment]
I'd encourage you to inspect the equivalent of your `~/.ghcup/ghc/9.0.1/lib/ghc-9.0.1/settings ` file (depending on where your ghc install dir is) and see if it contains a line like `("ar supports at file", "YES")`, and if so change that to `NO`.
