### ISSUE TITLE
'cabal init' should try to set 'main-is' for executables

### ISSUE THREAD

**Issue by bos** [haskell/cabal#674]
(Imported from [Trac #682](http://hackage.haskell.org/trac/hackage/ticket/682), reported by @dcoutts on 2010-05-05)

Currently, <tt>cabal init</tt> will find modules and add them to the <tt>exposed-modules</tt> of a library. It should try to do something similar for executables. The <tt>main-is</tt> field is required for executables and any <tt>other-modules</tt> also need to be listed.

**Comment by BardurArantsson** [comment]
No. Close. Clearly nobody is *that* bothered :).

**Comment by 23Skidoo** [comment]
IIRC something in this vein was implemented recently.

**Comment by byorgey** [comment]
Probably you are thinking of https://github.com/haskell/cabal/issues/2304, which is ever so slightly different, I don't think it tries to set `main-is` if one already exists.

**Comment by BardurArantsson** [comment]
"Patches welcome" since 2013. Should this just be closed? Clearly nobody with any interest in this cares *enough* to actually address this.
