### ISSUE TITLE
cabal init --non-interactive should create a license file

### ISSUE THREAD

**Issue by ibispi** [haskell/cabal#6744]
**Bug Description**
init --non-interactive should create a license file

**To Reproduce**
- init a cabal project with `cabal init -n`.
- in the output you can find:

    Generating LICENSE...
    Warning: unknown license type, you must put a copy in LICENSE yourself.

No license file is created (while it is listed in `.cabal` `licence-file:`).
This will cause problems, e.g. if you run `cabal sdist`.

**Expected behavior**                                                         
- a licence file is created.                                                  

**System information**
- OS: debian busted
- cabal-install 3.0.0.0, ghc 8.8.3

**Comment by phadej** [comment]
I'm quite sure this is fixed in `master` already. There is no default license anymore. Also there was some mixup with old license identifiers and SPDX ones, but that should be fixed.
