### ISSUE TITLE
Can't install library of local package

### ISSUE THREAD

**Issue by jdkr** [haskell/cabal#6765]
Hello,

I'm trying to install the library component of a local package (for example named "MyPackage") into the global package environment. At my system this is located in `~/.cabal/store/ghc-8.8.1/`. With the command `cabal v2-install --lib MyPackage`, executed from the local package directory, there is the following error:
```
cabal: filepath wildcard 'cabal' does not match any files.
```
I've also noticed that the behavior on Windows and Linux is different. The same command works on Windows and on Linux not. My version of cabal-install for both systems is 3.2.0.0.

**Comment by m-renaud** [comment]
Hi @jdkr, thanks for the report. Do you have a minimal repro example? I tried this locally by creating a simple library package with `cabal init` and installing it and it succeeded. Have you made any other modifications to your cabal configuration file?

**Comment by jdkr** [comment]
Sorry for the confusion. I've found my mistake. After the section `extra-source-files:` I had some comment lines. In between them was one uncommented line that started with some whitespace and afterwards with the word "cabal". This affected `cabal v2-install` but not `cabal v2-build`
