### ISSUE TITLE
Document v2-install all:exes.

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#6769]
In the docs could we please include some mention of allowable target syntax for the `v2-install` command, along the lines of the discussion of `v2-build` targets?

https://github.com/haskell/cabal/blame/master/Cabal/doc/cabal-commands.rst#L66-L87

> cabal v2-build takes a set of targets and builds them (a package target, all, all:ctypes etc)
> cabal v2-install [FLAGS] PACKAGES

With a project that has executables in only some packages, I tried `cabal v2-install all`. This failed to install any of the executables but when I tried `cabal v2-install all:exes` it installed them all as did `cabal v2-install all:excutables`.

```
> cabal v2-install all --overwrite-policy=always
...
Resolving dependencies...
cabal: Cannot build the executables in the package detour-via-sci because it
does not contain any executables. Check the .cabal file for the package and
make sure that it properly declares the components that you expect.

> cabal v2-install all:exes --overwrite-policy=always
...
Up to date
Symlinking 'tag-zone' to '/Users/pdejoux/.cabal/bin/tag-zone'
...
Symlinking 'task-length' to '/Users/pdejoux/.cabal/bin/task-length'
```

**Comment by complyue** [comment]
> With a project that has executables in only some packages, I tried cabal v2-install all. This failed to install any of the executables but when I tried cabal v2-install all:exes it installed them all as did cabal v2-install all:excutables

This is exactly for what I came to search the issues list here, thanks!

**Comment by Mikolaj** [comment]
@philderbeast: are you satisfied with the fix? If so, could you close?

**Comment by Mikolaj** [comment]
Tada!
