### ISSUE TITLE
cabal install does not work when /tmp/ is mounted "noexec"

### ISSUE THREAD

**Issue by bos** [haskell/cabal#677]
(Imported from [Trac #685](http://hackage.haskell.org/trac/hackage/ticket/685), reported by guest on 2010-05-09)

Wanting to to build darcs 2.4.3, I downloaded the tarball (
[http://wiki.darcs.net/Releases/2.4](http://wiki.darcs.net/Releases/2.4) ) and uncompressed it in /tmp/ to
run cabal install.
I got the following error :

cabal: Error: some packages failed to install:
darcs-2.4.3 failed during the configure step. The exception was:
`ExitFailure?` 127

See [http://hpaste.org/fastcgi/hpaste.fcgi/view?id=25412#a25412](http://hpaste.org/fastcgi/hpaste.fcgi/view?id=25412#a25412) for a
full verbose log, but i think there is nothing informative to it.

However, if I do "rm -fr dist" and try cabal install again, darcs
build fine. Also, if I try in $HOME, cabal install works directly.

Here are the versions of the software I'm using:

cabal-install version 0.8.2
using version 1.8.0.4 of the Cabal library

ghc 6.12.1

Linux distribution: Ubuntu 10.04 (Lucid Lynx).

I hope this will help you!

**Comment by BardurArantsson** [comment]
No update since 2010... and I believe Ubuntu have moved away from this practice anyway?

**Comment by 23Skidoo** [comment]
I vaguely remember that there was a newer issue with the same problem.

**Comment by BardurArantsson** [comment]
Yeah, so, if that issue still exists... perhaps close this one? I'm pretty confident stating that this is not a very severe issue :)

(Sorry about the delay... was... distracted.)

**Comment by 23Skidoo** [comment]
Closing in favour of #2422.
