### ISSUE TITLE
Can't build cabal-install

### ISSUE THREAD

**Issue by BarneyStratford** [haskell/cabal#6770]
I attempted to build cabal-install 3.2.0.0 from source under ghc 8.10.1 and base 4.14.0.0 under macOS 10.13.6, but the build failed. The first failure was that cabal-install requires base < 14.4. When I bumped the version number to (try to) allow it to build under the latest base, I got the following error:

[154 of 158] Compiling Distribution.Client.Sandbox ( Distribution/Client/Sandbox.hs, dist/build/cabal/cabal-tmp/Distribution/Client/Sandbox.o )

Distribution/Client/Sandbox.hs:713:7: error:
    • Illegal qualified type:
        GHC.Stack.Types.HasCallStack => IO WereDepsReinstalled
      Perhaps you intended to use RankNTypes
    • In the expansion of type synonym ‘Distribution.Compat.Stack.WithCallStack’
      In the expansion of type synonym ‘Cabal-3.2.0.0:Distribution.Compat.Prelude.IO’
      When checking the inferred type
        topHandler' :: Cabal-3.2.0.0:Distribution.Compat.Prelude.IO
                         WereDepsReinstalled
                       -> IO WereDepsReinstalled
    |
713 |       topHandler' = topHandlerWith $ \_ -> do
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cabal-install-3.2.0.0. See the build log above for
details.

**Comment by gbaz** [comment]
this was an unsupported ghc/cabal combination.
