### ISSUE TITLE
v2-install doesn't produce environment file even when requested

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#6775]
**Describe the bug**
I would like to use `cabal v2-install --lib` to create a package environment with a set of  packages available that can be used to build and measure `nofib` tests. However, `cabal v2-install --lib` does not create a package environment file, even when passed `--package-env=package-env --write-ghc-environment-files=always`.

**To Reproduce**

```
$ cabal v2-install --lib --package-env=package-env --write-ghc-environment-files=always parallel
$ ls package-env
ls: cannot access 'package-env': No such file or directory
```
Moreover, `strace -f -eopen` suggests that no attempt was made to write the environment file anywhere.

**Expected behavior**
A package environment file is created.

**System information**
 - NixOS 20.03
 - GHC 8.8.1, `cabal-install` 3.2.0.0

**Comment by phadej** [comment]
The package-env file is created in `~/.ghc/x86_64-linux-8.10.1/environments/package-env` (or whatever GHC version you are using), not locally.

TO create local file:

```
% cabal install QuickCheck --package-env=./foo --lib
```
