### ISSUE TITLE
Unknown architecture name 'wasm32'

### ISSUE THREAD

**Issue by 3noch** [haskell/cabal#6796]
The time has come. wasm32 for Haskell is actually a thing. But `cabal upload` won't have it.

I have this in my cabal file:

```
if arch(wasm32)
  build-depends:
    jsaddle >= 0.9.6 && < 0.10,
    jsaddle-wasm >= 0.1 && < 0.2
```

Why does `cabal upload` refuse to let me upload this package?

**Comment by phadej** [comment]
```
% cabal check
Warning: The following errors will cause portability problems on other
environments:
Warning: Unknown architecture name 'wasm32'
Warning: Hackage would reject this package.
```

**Comment by 3noch** [comment]
Thanks. I didn't know about `cabal check`. But the problem still remains.

**Comment by phadej** [comment]
That's in general up to Hackage admins, what they accept there. `cabal check` is just a hint, which may or may not be overriden. Report issue to `hackage-server` repository.

**Comment by gbaz** [comment]
Well we don't accept unknown arches on hackage, and I think that's fine.

Perhaps we should add wasm32 as a known arch to cabal in https://github.com/haskell/cabal/blob/dbb2d0e047e143e5c153bae95814ed7be67a9bcb/Cabal/Distribution/System.hs#L177 ?
