### ISSUE TITLE
Remove "colon specifier is experimental feature (issue #5660)" for 3.8

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6801]
Blocked on https://github.com/haskell/cabal/issues/5660

**Comment by phadej** [comment]
Re-milestoning this for 3.6, as it's blocked on #5660.

**Comment by gbaz** [comment]
What even is this about? :-)

**Comment by jneira** [comment]
https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/Cabal/src/Distribution/Types/Mixin.hs#L66
https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/Cabal/src/Distribution/Types/Dependency.hs#L144

???

**Comment by fgaz** [comment]
It's the `build-depends: pkg:lib` syntax, which is still marked as experimental due to #7270
