### ISSUE TITLE
cabal.project documentation field doesn't override global one for dependencies

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#6824]
**Describe the bug**
* If you have enabled documentation in cabal global config and you disable it in the `cabal.project`, cabal still builds docs for dependencies.
* The predecence works for local packages, it only fails for dependencies

**To Reproduce**

```
PS D:\dev\ws\haskell\haskell-ide-engine> cat C:\Users\atrey\AppData\Roaming\cabal\config | grep "documentation"
documentation: True
PS D:\dev\ws\haskell\haskell-ide-engine> cat cabal.project-8.6.5 | grep "documentation"
documentation: False
PS D:\dev\ws\haskell\haskell-ide-engine> cabal v2-install -w ghc-8.6.5 --project-file .\cabal.project-8.6.5
Wrote tarball sdist to
D:\dev\ws\haskell\haskell-ide-engine\dist-newstyle\sdist\haskell-ide-engine-1.4.tar.gz
Wrote tarball sdist to
D:\dev\ws\haskell\haskell-ide-engine\dist-newstyle\sdist\hie-plugin-api-1.4.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - haddock-api-2.22.0 (lib) (requires build)
 - haskell-ide-engine-1.4 (lib) (requires build)
 - haskell-ide-engine-1.4 (exe:hie-wrapper) (requires build)
 - haskell-ide-engine-1.4 (exe:hie) (requires build)
Starting     haddock-api-2.22.0 (lib)
Building     haddock-api-2.22.0 (lib)
Haddock      haddock-api-2.22.0 (lib)
Warning: Failed to build documentation for haddock-api-2.22.0 (which is
required by exe:hie-wrapper from haskell-ide-engine-1.4 and exe:hie from
haskell-ide-engine-1.4).
Copying 'hie.exe'
C:\sd\ghc-8.6.5\haskell-ide-e_-1.4-27a9161f04eb682e2fe38758622f89eca8c95b7e\bin\hie.exe: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:openBinaryFile: does not exist (No such file or directory)
```

Same for `v2-build` but without the linking error

**Expected behavior**

cabal should honour cabal.project `documentation: False` and not build dependencies with docs

**System information**
 - Windows 10
 - Official `cabal-3.2.0.0` , several `ghc` versions

**Additional context**

I need the override to [workaround what seems to be another cabal bug](https://github.com/haskell/haskell-ide-engine/issues/1741) in haskell-ide-engine: `cabal install` fails to symlink/copy the executable if haddock fails for any dependency

**Comment by phadej** [comment]
https://cabal.readthedocs.io/en/latest/cabal-project.html#package-configuration-options

> They can be specified inside an package * stanza, in which case they apply to all packages, local ones from the project and also external dependencies.

---

% cabal build -w ghc-8.10.1
Resolving dependencies...
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - boring-0.1.3 (lib) (first run)
Configuring library for boring-0.1.3..
Preprocessing library for boring-0.1.3..
Building library for boring-0.1.3..
[1 of 1] Compiling Data.Boring      ( src/Data/Boring.hs, /code/public-haskell/boring/dist-newstyle/build/x86_64-linux/ghc-8.10.1/boring-0.1.3/build/Data/Boring.o, /code/public-haskell/boring/dist-newstyle/build/x86_64-linux/ghc-8.10.1/boring-0.1.3/build/Data/Boring.dyn_o )


% $EDITOR cabal.project
% git diff
diff --git a/cabal.project b/cabal.project
index cf3422c..1fde7a0 100644
--- a/cabal.project
+++ b/cabal.project
@@ -2,3 +2,6 @@ packages: .
 
 package boring
   ghc-options: -Wall

package *
  documentation: True

% cabal build -w ghc-8.10.1
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - StateVar-1.2 (lib) (requires build)
 - base-compat-0.11.1 (lib) (requires build)
 - base-orphans-0.8.2 (lib) (requires build)
 - cabal-doctest-1.0.8 (lib) (requires build)
 - dec-0.0.3 (lib) (requires build)
...

seems to turn the documentation on for dependencies.
I expect it similarly turn it off, if set to `False`.

**Comment by jneira** [comment]
Yeah, in the meanwhile @DanielG suggested me in irc  the same tip and i've tried it:
```
package haddock-api
  documentation: False
```
does what i wanted, so this one could be closed taking in account top fields works only for local packages by design

Thanks!
