### ISSUE TITLE
Cabal 3.2 on OS X 10.11

### ISSUE THREAD

**Issue by rachel-barrett** [haskell/cabal#6833]
**Describe the bug**

I tried installing ghcup using the command here https://www.haskell.org/ghcup/.
This installed cabal 3.2. When I ran `cabal update && cabal install record-dot-preprocessor` there was an error 

```
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/rachelbarrett/.ghcup/bin/cabal (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/rachelbarrett/.ghcup/bin/cabal (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
```

**To Reproduce**

1. Install cabal 3.2 by installing ghcup
2. Use cabal to install a package e.g. `cabal install record-dot-preprocessor`

**Expected behavior**

I expected cabal update to succeed and install record-dot-preprocessor, but instead it returned the above error message.

**System information**
 - OS X El Capitan 10.11.6
 - `cabal` version 3.2
- `ghc` version 8.8.3

**Additional context**

**Comment by phadej** [comment]
El Capitan (10.11) is 5 years old OS, which is out of our support window.
(The info is slightly hidden in https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions)

> Our GHC support window is five years for the Cabal library and three years for cabal-install.

I'm sorry to tell, but El Capitan is just too old. And given how hard (i.e. impossible) to get virtualized environments with old macOS, I don't think we can really do better here.

**Comment by gbaz** [comment]
the following suggests a possible fix: https://github.com/rbenv/ruby-build/issues/1133

in particular does `$ xcode-select --install` help?

**Comment by rachel-barrett** [comment]
Thanks both for your responses. That possible fix doesn't work for me: when I run `$ xcode-select --install`, I get `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`
