### ISSUE TITLE
Hackage should not permit hs files encoded as Latin1

### ISSUE THREAD

**Issue by bos** [haskell/cabal#684]
(Imported from [Trac #692](http://hackage.haskell.org/trac/hackage/ticket/692), reported by @ezyang on 2010-05-24)

They seem innocuous (usually hiding in source code comments, lest they fail to compile) but they make uniformly loading *.hs files into memory a pain, since you have to heuristically determine what encoding a file that is not Unicode-enabled is. We should ban them: it's UTF-8 or nothin'.

**Comment by ttuegel** [comment]
This is not a Cabal issue.
