### ISSUE TITLE
GHC 8.12 does not like whitespace around `@` in `var@pattern`

### ISSUE THREAD

**Issue by vdukhovni** [haskell/cabal#6840]
Cabal-install does not build with GHC 8.12, because of bare `@` in https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Dependency.hs#L724
The trivial fix is to remove the surrounding whitespace.

**Comment by phadej** [comment]
Please make a PR.

**Comment by jneira** [comment]
The linked pr was finally merged so this one might be closed. I dont checked it but i am gonna close it optimistically.
@vdukhovni feel free to reopen if that is not the case.
