### ISSUE TITLE
BuildReports don't seem to work with v2-build

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#6851]
A more focused follow-up to #6811

After some digging, it appears that the --build-summary (and --build-log?) flags when passed to new-build are no-ops. I looked through the code, and it seems to me the issue is that this info goes into the `installSummaryFile` config field, but the only place that (or the `BuildReports`) module is used is in `Distribution.Client.Install` such as here:

https://github.com/haskell/cabal/blob/06c3eff242154cdf6b3d1bbaffcfc1a5cbea9da8/cabal-install/Distribution/Client/Install.hs#L824

So v1-build didn't do this, only v1-install. Furthermore, v2-build, if I understand the system (and by implication v2-install) won't hit that path either.

It looks like we'd need to implement similar logic in `ProjectOrchestration.hs` if we want to make use of this? (https://github.com/haskell/cabal/blob/10f33badad67a471d8635e288d24fa495db7d504/cabal-install/Distribution/Client/ProjectOrchestration.hs)

Note that this is actually pretty important for GSoC work, because we can't move the docbuilder to v2-build if we don't have build reports as part of it.

Can someone confirm that this analysis makes sense?

**Comment by gbaz** [comment]
Btw, @hvr do the matrix builders just not make use of build-reports, or am I missing something here?

**Comment by phadej** [comment]
> Can someone confirm that this analysis makes sense?

Yes.

FWIW, for docbuilder the #6876 will need to be tacked too (and I don't have good ideas how to do that, rebuilding everything is lame).

**Comment by gbaz** [comment]
i was also just pointed to the fact that we may have multiple per-component build-reports, so we need to handle that case too. Perhaps extending the build-report syntax to cover multiple packages?
