### ISSUE TITLE
mention --constraint flag in error essage when dep planning fails

### ISSUE THREAD

**Issue by bos** [haskell/cabal#686]
(Imported from [Trac #694](http://hackage.haskell.org/trac/hackage/ticket/694), reported by @dcoutts on 2010-05-31)

Dependency planning problems can often be solved by running with --dry-run -v, seeing what the planner is selecting and forcing it to make different choices using the --constraint flag.

When dependency planning fails with particular kinds of constraint problem, it may be useful to users to mention this. We should check if this advice applies to all cases where the dep planner fails, or if its only appropriate for certain classes of failure.

**Comment by grayjay** [comment]
Does this issue apply to the modular solver?  As far as I know, adding a constraint can only remove solutions, though it could help the solver run faster or pick a better solution.

**Comment by 23Skidoo** [comment]
Yes, let's close.
