### ISSUE TITLE
Need a better error message when cabal-version parse fails

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/cabal#6862]
**Describe the bug**

If I write `cabal-version: 3` as the first line in cabal file, I have no clue at all what's wrong from the error message:

```
$ cabal v2-build
Errors encountered when parsing cabal file ./xls.cabal:

xls.cabal:1:1: error:
cabal-version should be at the beginning of the file starting with spec version 2.2. See https://github.com/haskell/cabal/issues/4899

    1 | cabal-version: 3
      | ^
```

**To Reproduce**
See above.

**Expected behavior**
Version without a "." should be accepted, otherwise at least say that we expect a "." in the version.

**System information**
* Mac OS X
* cabal 3.2

**Comment by phadej** [comment]
It won't be accepted. The version is `3.0`. There is no spec version 3.

**Comment by harendra-kumar** [comment]
Its perfectly ok to not accept it but the error message should say what is wrong. When the version number is wrong cabal is saying that `cabal-version` should be the first line. It makes this very hard to guess what is wrong:

```
cabal-version should be at the beginning of the file starting with spec version 2.2. See https://github.com/haskell/cabal/issues/4899
```

I think it should not be difficult to say that the problem is in the version field and not in the whole line itself. The parser would actually have that information, it should be just a matter of caring to print it.

**Comment by harendra-kumar** [comment]
BTW, how is the user supposed to know what is a valid cabal version? When the version is invalid shouldn't it tell you what makes a valid version or print a list of valid versions or point the user to some resource where he/she can find valid versions?

**Comment by phadej** [comment]
> how is the user supposed to know what is a valid cabal version

https://cabal.readthedocs.io/en/latest/file-format-changelog.html

**Comment by harendra-kumar** [comment]
I think it is a terrible user experience to say that "cabal-version should be at the beginning of the file" when you mean that cabal-version is invalid. The first thing that the user needs to know is that there is something wrong with the version number, only then he/she can even try to go looking into the user guide. Otherwise he is lost at that point itself.

Ideally I would like cabal to tell what a valid version is in the error message itself rather than expecting the user to read the guide till the end first or go searching into the documentation. But I would be happy if the error message itself can be fixed.

**Comment by phadej** [comment]
Please make a PR if you want situation to be improved, I won't however keep an issue open for it.

**Comment by epogrebnyak** [comment]
@phadej, would you be receptive to a PR that just adds to the error message:

https://github.com/haskell/cabal/blob/a6915feafdf6049e67d7dc3b371bfb4bcc6aca04/Cabal/Distribution/PackageDescription/Parsec.hs#L184-L185

The message can say:

```
"cabal-version should be at the beginning of the file starting with spec version 2.2 "
++ "(see https://github.com/haskell/cabal/issues/4899)\n"
++ "You may also need to check version number format, as described at "
++ "https://cabal.readthedocs.io/en/latest/file-format-changelog.html"

The error message is it is now is very confising for beginners. I was putting `3.2.0.0` as a version number and getting the error message about the first line error, very confusing.
