### ISSUE TITLE
cabal init produces `extra-source-files: CHANGELOG.md`

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#6864]
**Describe the bug**
`CHANGELOG.md`(sic `ChangeLog.md`) (and `README.md`) should be listed as `extra-doc-files` not `extra-source-files` (see also #5813).

**To Reproduce**

```
$ cabal init --non-interactive
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
`extra-doc-files:  CHANGELOG.md`

**System information**
 - Operating system: Fedora
 - `cabal-3.2.0.0`, `ghc-8.6.5` versions

**Additional context**
`extra-source-files:  CHANGELOG.md` is put in .cabal file.

**Comment by phadej** [comment]
Note that `extra-doc-files` is `cabal-version: 1.18` (IIRC. please check) feature.

**Comment by juhp** [comment]
> Note that `extra-doc-files` is `cabal-version: 1.18` (IIRC. please check) feature.

Okay but `cabal init` now produces `cabal-version: 2.4` anyway, right?

**Comment by phadej** [comment]
> Okay but cabal init now produces cabal-version: 2.4 anyway, right?

Interactive variant still could be selected to produce `1.10`.

**Comment by juhp** [comment]
Gotya, good point!

I think you are right: #3825.

**Comment by juhp** [comment]
Haven't tested yet, but thanks a lot for addressing this!
