### ISSUE TITLE
cabal install world always reinstalls programs

### ISSUE THREAD

**Issue by bos** [haskell/cabal#687]
(Imported from [Trac #695](http://hackage.haskell.org/trac/hackage/ticket/695), reported by @dcoutts on 2010-05-31)

cabal-install does not currently track the installed state of programs. It does now list them in the world file however. This leads to it always wanting to reinstall programs.

Probably we do want to keep the programs in the world file, since we hopefully will track programs better in future. The temporary hack would be to filter out packages that have no lib when retrieving packages from the world file.

**Comment by gbaz** [comment]
closing as obsolete
