### ISSUE TITLE
Ambiguous TargetSelector crash

### ISSUE THREAD

**Issue by bubba** [haskell/cabal#6874]
**Describe the bug**
In the project [haskell-language-server](https://github.com/haskell/haskell-language-server), calling `cabal repl exe/Arguments.hs` from the root directory will give this error:
```
$ cabal repl exe/Arguments.hs 
TargetSelector: internal error: NoMatch
CallStack (from HasCallStack):
  error, called at ./Distribution/Client/TargetSelector.hs:669:3 in main:Distribution.Client.TargetSelector
```

This is because a subproject `ghcide` which is included in the packages field of `cabal.project` also has a module in a folder `ghcide/exe/Arguments.hs`.
This doesn't happen when calling `cabal repl exe/Arguments.hs` from inside `ghcide`.

**Steps to reproduce**
Working on getting a minimal test case

**Expected behavior**
Presumably in this scenario, `cabal repl src/Arguments.hs` should resolve to the `src/Arguments.hs` in the root project.

**System information**
 - cabal HEAD

**Comment by bubba** [comment]
Turns out this is actually caused because there are two executables that build the same module, which in this case is indeed actually ambiguous. However it looks like the error is getting mangled and an internal one is thrown instead whenever the modules are located within a `hs-source-dirs`.

```
$ tree
.
├── cabal-ambig-sel.cabal
└── src
    └── F.hs

1 directory, 2 files
$ cat cabal-ambig-sel.cabal 
cabal-version:       >=1.10
-- Initial package description 'cabal-ambig-sel.cabal' generated by 'cabal
-- init'.  For further documentation, see
name:                cabal-ambig-sel
version:             0.1.0.0

executable A
  main-is: Main.hs
  hs-source-dirs: src
  other-modules: F

executable B
  main-is: Main.hs
  hs-source-dirs: src
  other-modules: F
```


In this test case, removing the hs-source-dirs and placing `F.hs` in the root produces the proper error
```
$ cabal repl F.hs
cabal: Ambiguous target 'F.hs'. It could be:
:pkg:cabal-ambig-sel:exe:A:file:F (file)
:pkg:cabal-ambig-sel:exe:B:file:F (file)
```

[cabal-ambig-sel.tar.gz](https://github.com/haskell/cabal/files/4731148/cabal-ambig-sel.tar.gz)

**Comment by phadej** [comment]
Have you tried with current `master`. There were patches improving how target selection for files behave.

**Comment by bubba** [comment]
Yeah this is happening with 07c1a43c1e7841135617954c5202942a59e0f71d
I've been poking through `TargetSelector.hs` and I'm still trying to wrap my head around what is making this an internal error, rather than a genuine ambiguous selector error

**Comment by bubba** [comment]
PR created for fix. The reason why this was working with the case where there was no hs-source-dir was by coincidence --- since files `Foo.hs` are rendered as `Foo`, this just happened to match the module syntax.
