### ISSUE TITLE
cabal file not found despite --cabal-file

### ISSUE THREAD

**Issue by hyperfekt** [haskell/cabal#6880]
**Describe the bug**
I expect to be able to use cabal files at an abnormal path by pointing Cabal at it with the `--cabal-file` argument.

**To Reproduce**
1. Set up a package that builds normally with Cabal.
2. Move `[package name].cabal` outside of the directory or change the extension.
3. Run `cabal v2-build --cabal-file [new path]`.

**Expected behavior**
Cabal builds the package as if the Cabal file was at its original path.

**Actual behavior**
Cabal reports the following:
```
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.
```

**System information**
 - Operating system: NixOS 20.03
 - `cabal` version: 3.2.0.0

**Comment by phadej** [comment]
`--cabal-file` is used for testing.

We should remove that flag from public interface.

**Comment by ezyang** [comment]
IIRC, `--cabal-file` does the right thing if you're using the Setup.hs interface. But it doesn't make any sense on the high level v2 interface. Agree it should be removed from there.

**Comment by jneira** [comment]
@hyperfekt as the decision was remove the flag and no "fix" it, I would close this one and open a new one tracking the flag deletion itself
will do if you don't disagree

**Comment by ulysses4ever** [comment]
Agree with @jneira's comment above. Let's act on it?

**Comment by ulysses4ever** [comment]
Same for #7225 (a dup).

**Comment by Mikolaj** [comment]
> Agree with @jneira's comment above. Let's act on it?

Let's do it. :)

**Comment by ulysses4ever** [comment]
Done! #8395
