### ISSUE TITLE
QuickCheck not working even though it is installed and up to date

### ISSUE THREAD

**Issue by coffeecoding** [haskell/cabal#6911]
Trying to use Haskell and QuickCheck on windows. The command

cabal install QuickCheck

returns

Up to date
Warning: You asked to install executables, but there are no executables in
target: QuickCheck. Perhaps you want to use --lib to install libraries
instead. 

So apparently it did get installed however when I run a script that imports Test.QuickCheck I get the following error message:

Could not find module `Test.QuickCheck'

Note: I tried all the proposed solutions I could find on stackoverflow including Could not find module ‘Test.QuickCheck’ on Windows but none of them helped me solve my problem. So please only post a solution if you are sure that it works.

Also if it helps I installed everything according to the instructions i found on the haskell platform

The way I installed QuickCheck was by typing the command

cabal install QuickCheck

Everywhere I look I see only solutions that use the "stack" command which I do not know what it is nor does it work for me.

**Comment by gbaz** [comment]
You are using a new cabal, which uses nix-style sandboxing. Some oof the tutorials you found may have been older. The warning explains the issue -- to install the library so everythiing can use it, you now run `cabal install --lib QuickCheck.`. However, I do _not_ recommend this! Instead, create a project  `cabal init --interactive` that includes QuickCheck as a dependency, and add QuickCheck as a dependency there, then you can use QuickCheck as a lib from within that project, using the usual `cabal build`, `cabal run`, `cabal test` commands, etc.

See the docs at http://cabal.readthedocs.io/
