### ISSUE TITLE
seemingly too liberal behaviour on overlapping dependency constraints across packages

### ISSUE THREAD

**Issue by bos** [haskell/cabal#692]
(Imported from [Trac #700](http://hackage.haskell.org/trac/hackage/ticket/700), reported by @kowey on 2010-06-13)

There's a high chance this is not actually a bug, but I'm filing one anyway.

In [http://bugs.darcs.net/isuse1763](http://bugs.darcs.net/isuse1763) we have darcs-2.4 which depends on mmap &gt;= 0.2 and on hashed-storage &gt;= 0.4.7 &amp;&amp; &lt; 0.5

The hashed-storage 0.4.x line depends on mmap == 0.4.*

The bug in darcs happened when darcs was linked against mmap-0.5 while hashed-storage against mmap-0.4.

Is it reasonable to expect that if I depend on a package, that the package can indirectly impose at least soft constraints (on the cabal-install level) on our shared dependencies?  Should cabal-install have been smart enough to work out that darcs should actually only pick up mmap 0.4?  I think I could be quite happy with "no"

**Comment by BardurArantsson** [comment]
(Last comment in 2010.)

AFAICT, this is not an open issue. As @dcoutts basically said in friendlier words: "No, not going to happen.".
