### ISSUE TITLE
How to revert changes made by bootstrap.sh?

### ISSUE THREAD

**Issue by Kabouik** [haskell/cabal#6937]
Not a bug, just a question: 

I ran `cabal-install`'s `./bootstrap.sh` before noticing there was a sandbox option. Now I would like to revert the changes because it turns out my device does not have enough free space anyway. Is there anything I can do? The device has been compiling for hours and I no longer have the history in my terminal, and since I didn't use the sandbox option, cleaning changes manually seems unrealistic to me.

**Comment by phadej** [comment]
bootstrap.sh is gone.
