### ISSUE TITLE
Reject relative paths for extra-lib/include-dirs

### ISSUE THREAD

**Issue by bos** [haskell/cabal#694]
(Imported from [Trac #702](http://hackage.haskell.org/trac/hackage/ticket/702), reported by @dcoutts on 2010-06-14)

It makes no sense and causes problems later.

See ghc ticket [http://hackage.haskell.org/trac/ghc/ticket/4134](http://hackage.haskell.org/trac/ghc/ticket/4134)

This applies to the paths in the .cabal file. For ones specified on the command line perhaps just making them absolute would be ok. Ones specified in the global config must be absolute. Ones in local config could possibly be relative.

**Comment by jakzale** [comment]
I'd like to tackle this bug during ZuriHac 2015.

I've looked into this bug with @kosmikus, and it appears that ghc-pkg checks if `import-dirs`, `library-dirs`, `include-dirs`, and `framework-dirs` is relative and if any of them is relative stops and reports an error.

Still, cabal seems to translate `include-dirs` to an absolute path, which then does not trigger a ghc-pkg error.

**Comment by ezyang** [comment]
Yes, this bug is not as simple as just rejecting all relative directories, because if you `install-includes` then the include will in fact be present at the absolute path Cabal translates it to.

**Comment by jneira** [comment]
Closing in favour of #2641, which summarizes the problems with relative paths and the interaction with ghc-pkg
