### ISSUE TITLE
"cabal new-update" failed! while installing haskell

### ISSUE THREAD

**Issue by iamshreeram** [haskell/cabal#6941]
**Describe the bug**
Haskell installation failing with below error - 

```
[ Warn  ] New GHC version available: 8.10.1. To upgrade, run 'ghcup install 8.10.1'
[ Info  ] verifying digest of: cabal-install-3.2.0.0-x86_64-apple-darwin17.7.0.tar.xz
[ Info  ] Unpacking: cabal-install-3.2.0.0-x86_64-apple-darwin17.7.0.tar.xz to /var/folders/sn/pw7xq23n2vj_wnq16lkgdrxh0000gn/T/ghcup-UJUMTx
[ Info  ] Installing cabal
[ Info  ] Cabal installation successful
Downloading the latest package list from hackage.haskell.org
Unexpected response 403 for http://hackage.haskell.org/01-index.tar.gz
"cabal new-update" failed!
```

**To Reproduce**
Run installation on Mac Catalina

```
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
```

**Expected behavior**
Installation to be complete

**System information**
 - macos Catalina
 - `cabal`, `ghc` - Both Cabal and GHC are not in the system PATH

**Additional context**
Since `cabal` is not in my system path, I couldnt `﻿﻿cabal --http-transport=plain-http update`

**Comment by gbaz** [comment]
you may want to try navigating to the hackage website with the browser to see if it works at all. additionally, you can still run cabal -- its going to be in ~/.ghcup/bin

**Comment by iamshreeram** [comment]
@gbaz , Thank you! I'm still seeing same issue - 

```
ram:bin [501] ❯ cabal --http-transport=plain-http update
Downloading the latest package list from hackage.haskell.org
Unexpected response 403 for http://hackage.haskell.org/01-index.tar.gz
```
Any other suggestion?

**Comment by gbaz** [comment]
can you access  http://hackage.haskell.org/01-index.tar.gz from wget, curl, or a browser, and are you behind some sort of proxy? also, what ip does hackage resolve to when you nslookup it?

**Comment by gbaz** [comment]
also by any chance are you accessing from in or around mumbai  https://status.fastly.com/incidents/f57f7zz7bhtj

**Comment by iamshreeram** [comment]
@gbaz , Nope. I'm located in US. Btw, If i can download it manually, is there a way i can update manually?

**Comment by iamshreeram** [comment]
My VPN was blocking this download. I had to download manually and update which fixed this issue. Thanks for the support!
