### ISSUE TITLE
--ignore-project creates "Invalid package ID" error

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#6942]
```
git clone https://github.com/tidalcycles/Tidal
cd Tidal
git checkout 1.6.1
cabal install --lib --ignore-project
```
will result in
```
cabal: Invalid package ID: .
```

The repo contains a file `cabal.project` with contents
```
packages: ./ tidal-parse
```
Just running 
```
cabal install --lib
```
will produce some error triggered by constraints in `tidal-parse/tidal-parse.cabal` - that I want to avoid by not building it.

I thought that `--ignore-project` tells `cabal` to ignore `cabal.project`. (although `-?` says "Ignore local project  configuration" and does not mention the file name).

**System information**
 - Fedora GNU/Linux 5.7.6-201.fc32.x86_64
```
cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.1
```

**Comment by jneira** [comment]
* This behaviour changed for 3.4, as described in #8094
* `--ignore-project` is still not fully supported for v2 commands as described in https://github.com/haskell/cabal/issues/7057

So i am gonna close this one in favour of #8094, more recent and including the < 3.4 behaviour
