### ISSUE TITLE
at cabal.readthedocs.io, show doc versions instead of redirecting to latest

### ISSUE THREAD

**Issue by simonmichael** [haskell/cabal#6966]
https://cabal.readthedocs.io currently redirects to https://cabal.readthedocs.io/en/latest/ , which doesn't always correspond to the released cabal that people are using. Worse, when you land there it's really not obvious that this is so. Some ideas to make cabal docs easier for most users:

- if it must redirect, redirect to https://cabal.readthedocs.io/en/stable/ instead
- instead of redirecting, have a front page that links to whatever doc versions are available (clearly labelled with the cabal-install version number users are familiar with - 3.2.0.0 etc.)
- show that version number clearly at the top of all doc pages.

Related: https://github.com/haskell/cabal-website/issues/8, https://github.com/haskell/cabal/issues/6965

**Comment by phadej** [comment]
https://cabal.readthedocs.org/ now redirects to stable version (which is now 3.4, though it's not yet released).

---

As for other versions, it seems the 

![Screenshot from 2020-07-15 15-40-28](https://user-images.githubusercontent.com/51087/87546026-8c163c80-c6b1-11ea-9136-496434db5ce6.png)

is kindly generated by readthedocs.

**Comment by simonmichael** [comment]
@phadej, thanks, things are definitely improving!

Cabal users are still seeing docs for a version they don't have. (This might be "temporary", but it'll happen again.) May I suggest some more tweaks for optimising user experience:

- the default docs shown to users should be for the current release
- when "stable" is used, it should refer to the current release
- but consider removing "stable" from the sphinx version selector; it's redundant with the version number and adds an unnecessary new label for users to understand. (Keep the https://cabal.readthedocs.io/en/stable/ url of course.)
- consider renaming "latest" to "dev" or similar, it can easily be misunderstood as latest release

**Comment by simonmichael** [comment]
PS I realise this is a readthedocs.io-hosted sphinx instance so perhaps some of those are impractical. The first is the most important.

**Comment by phadej** [comment]
Sadly, the 3.4 (i.e. `stable`) describes 3.2 version better than documentation in 3.2 branch, as sad as it is.

**Comment by simonmichael** [comment]
Fair enough.. hopefully something that will resolve itself permanently before too long then. Should this be noted on the the 3.2 and 3.4 docs' front pages ?

**Comment by phadej** [comment]
I hided `stable` version, and made the default to redirect to 3.4 which looks like now

![Screenshot from 2020-07-15 19-17-53](https://user-images.githubusercontent.com/51087/87569567-fccc5180-c6cf-11ea-8365-1768c6f466c2.png)

For the content, more walk, less talk.

**Comment by simonmichael** [comment]
Great! Things are getting much clearer. But, you did disable the https://cabal.readthedocs.io/en/stable/ url - that's needed for permalinks, eg https://www.haskell.org/cabal/ links to it.

**Comment by phadej** [comment]
https://www.haskell.org/cabal/  should link to `https://cabal.readthedocs.io`
