### ISSUE TITLE
sdist tries to sdist source-repository-packages

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6990]

**Comment by typedrat** [comment]
Which `sdist` are you talking about here? :)

**Comment by phadej** [comment]
@typedrat there's only one `sdist` now, `v2-sdist`.

**Comment by typedrat** [comment]
I just wanted to make sure this wasn't `Setup.hs` related.

**Comment by phadej** [comment]
Good point. I'm open to removing `sdist` functionality from `Distribution.Simple` command line interface, leaving (and possibly moving around) library functionality for tools to implement it as they see fit (i.e. something which list files based on GPD).

**Comment by typedrat** [comment]
The solution to the issue itself is simple.

https://github.com/haskell/cabal/blob/a2a6bd47614a301b121da0699a09127d4da2056e/cabal-install/src/Distribution/Client/CmdSdist.hs#L142

Just need to filter them out here.

**Comment by phadej** [comment]
Why `source-repository-package` is in `localPackages`. I did changed them to not be "local" packages for 3.4 (e.g. as far as `v2-build` operates), so I should remember, but I don't :( Was it related to `localPackages` meaning "the ones you which don't come from remote repositories?"

We should find out, and maybe do some renaming to avoid this confusion again.

**Comment by typedrat** [comment]
IIRC, that is exactly right. `localPackages` isn't really local packages, it's all packages that aren't from Hackage.

**Comment by phadej** [comment]
I'm tempted to rename `localPackages` to `nonRemoteRepoPackages`. it's longer, but more correct name.

**Comment by phadej** [comment]
With #7007 fixed, this is not big issue as the tarballs are just copied to the sdist directory. Maybe it's not that bad after all.
