### ISSUE TITLE
A discrepancy between v2-freeze and v2-build

### ISSUE THREAD

**Issue by mrkkrp** [haskell/cabal#6991]
**Describe the bug**

Here is an example of a problematic log:

https://github.com/mrkkrp/megaparsec/runs/908017337?check_suite_focus=true#step:11:1269

First I do `v2-freeze` which creates a `cabal.project.freeze` file with these lines:

```
             any.these ==1.1.1.1,
             these +assoc,
```

This means that `v2-freeze` knows that there is `these-1.1.1.1` available and it choses it. Next, `v2-build all` is called and it sees that 1.1.1.1 should be chosen yet for some reason it doesn't even consider it. It then proceeds to claim that because of the freeze file the version 1.1.1.1 is expected but cannot be found!

**To Reproduce**

Only happens on CI, I cannot reproduce it locally, sorry.

**Expected behavior**

The build should succeed.

**System information**

GitHub actions thing, `ubuntu-latest`.

**Comment by mrkkrp** [comment]
In the meantime, is there a way to make it succeed somehow?

**Comment by phadej** [comment]
Your ` Run actions/cache@v2` restores `~/.cabal/packages` with older index file for Hackage.

**Comment by mrkkrp** [comment]
I see, that means that the restored cache cache overwrites the package database created by `cabal v2-update`. Closing.
