### ISSUE TITLE
Source repository package rebuild

### ISSUE THREAD

**Issue by Kaptch** [haskell/cabal#6996]
**Describe the bug**
Cabal doesn't check if a source repository package was updated and doesn't rebuild it if it was updated.

**To Reproduce**
cabal.project:
```
...
source-repository-package
  type: git
  location: git://github.com/<user>/<repo>
...
```
<package>.cabal:
```
...
  build-depends: <repo>
...
```

```
$ cabal v2-build
```

*The source repository package is updated*

```
$ cabal v2-build
```

**Expected behavior**
Cabal rebuilds the source repository package.

**System information**
 - Arch Linux
 - cabal-3.2.0.0, ghc-8.8.3

**Comment by phadej** [comment]
Specify a `tag`, changing it will force `cabal` to (re)fetch repository. Pulling repositories on every command will make `cabal` quite non-interactive.

**Comment by Kaptch** [comment]
Thanks!
