### ISSUE TITLE
Should ghc-bignum be marked as non upgradeable package?

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6998]
I.e. added to the list in

https://github.com/haskell/cabal/blob/0d0f9e9f5e5ea677a102c6622f412ce314991e3e/cabal-install/src/Distribution/Client/Dependency.hs#L386-L405

ping @bgamari @hsyl20

**Comment by hsyl20** [comment]
There is some wired-in stuff from `ghc-bignum` into `ghc` so I would say yes.

But at the same time I have trouble seeing what would go wrong if we build the same `ghc-bignum` version but with a different backend, except that we couldn't depend both on this and on `ghc`/`template-haskell`/`base`/... compiled libraries provided by GHC. If we could rebuild a `base` that depends on `ghc-bignum` built with another backend, it would make `ghc-bignum` backend switching way easier (for people that don't use TH/GHCi, until we fix cross-compilation related issues).

**Comment by phadej** [comment]
Yes, so as far as `base` is non-upgradable, so is `ghc-bignum`.

I'll mark it explicitly so, then users will get slightly better error messages / solver behavior.
