### ISSUE TITLE
cabal doesn't handle error conditions from getAppUserDataDirectory

### ISSUE THREAD

**Issue by bos** [haskell/cabal#700]
(Imported from [Trac #709](http://hackage.haskell.org/trac/hackage/ticket/709), reported by @creswick on 2010-07-12)

`Distribution.Simple.InstallDirs.defaultInstallDirs` fails if `getAppUserDataDirectory` fails, and it does so with a very uninformative error:
```
# On Cabal 1.8.0.2:
cabal.exe: illegal operation
```

This is a slight regression from the HP 2009 version:

```
# On Cabal 1.6.0.3:
cabal.exe: System.Directory.getAppUserDataDirectory: unsupported operation (unsupported operation)
```

This happens on Windows Vista, in cygwin, when the user doesn't have a windows user directory (eg: `c:\users\username`).

**Comment by neongreen** [comment]
In case anyone has the same problem and stumbles upon this comment: if your Windows user name contains non-latin letters (to be more precise: if the name of your home directory contains non-latin errors), and you're using MSYS, you'll get this error.

**Comment by ttuegel** [comment]
@neongreen Is this a problem if you aren't using MSYS?

**Comment by jasagredo** [comment]
This ticket talks about Cygwin. Haskell nowadays is based on Mingw. I am preemptively closing this, please reopen otherwise.
