### ISSUE TITLE
new-install command fails to install hoauth2 package while old install works

### ISSUE THREAD

**Issue by matthewdyck29** [haskell/cabal#7008]
**Describe the bug**
The command "cabal new-install hoauth2" fails to install the package and complains about unresolved dependencies (see screenshot)
![cabal-error](https://user-images.githubusercontent.com/23403000/89584369-95eb1580-d801-11ea-9774-c045ad7f028a.png)
. 
However, the old version: "cabal install hoauth2" works as expected. 

**To Reproduce**

1. On a machine that doesn't have the hoauth2 package yet, run the command "cabal new-install hoauth2". 

**Expected behavior**
Any dependencies should be resolved automatically and the package should be built successfully. 

**System information**
 - Operating system: Windows 7
 - `cabal`, `ghc` versions: cabal: 2.4.1.0 ghc: 8.6.5

**Comment by ulysses4ever** [comment]
There wasn't any movement here for 2 years. Perhaps, the question is not relevant anymore. Should we close it? Either way, a reproducer with a modern Cabal would be necessary to move forward. Needless to say, `hoauth2` builds fine for me with `new-install --lib --package-env .`.

**Comment by Mikolaj** [comment]
@matthewdyck29: please let us know if the problem re-appears (with new cabal versions). Closing.

**Comment by Mikolaj** [comment]
@matthewdyck29: thank you for the comment. All the best!
