### ISSUE TITLE
Stale link to Cabal library API documentation

### ISSUE THREAD

**Issue by hgolden** [haskell/cabal#7011]
At present, the following API documentation link on the Cabal homepage is dead:
https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/

A possible (older - currently for Cabal 2.4.0.1) link that works is:
https://www.haskell.org/cabal/release/latest/doc/API/Cabal/

Please update the homepage support to refer to the most current version of the API documentation. Thanks.

**Comment by gbaz** [comment]
I think this is resolved?
