### ISSUE TITLE
cabal-install 3.2.0.0 doesn't build with ghc-8.8.3

### ISSUE THREAD

**Issue by josefs** [haskell/cabal#7013]
**Describe the bug**

When I tried to compile cabal-install using ghc-8.8.3 I got a couple of errors due to version constraints. I had to update the bootstrap script to use:
HTTP_VER="4000.3.14"
ZLIB_VER="0.6.2.2"
HASHABLE_VER="1.3.0.0"

**To Reproduce**

Run bootstrap using ghc 8.8.3 and then build

**Expected behavior**

I expect the build to succeed

**System information**
centos linux
ghc 8.8.3
cabal 3.2.0.0, source

**Additional context**

**Comment by phadej** [comment]
bootstrap.sh script was removed, this issue is obsolete.

Note: `bootstrap.sh` is not designed to be used as primary way of installing `cabal-install`. I consider it a "expert way" for the people who cannot do otherwise.
