### ISSUE TITLE
On building, ghcversion.h is not found, but it is there.

### ISSUE THREAD

**Issue by step21** [haskell/cabal#7031]
**Describe the bug**
ghcversion.h is not found. Is there a flag to specify where to look, or where does cabal look, or tell ghc to look? From docs so far I found no info on that, it seems that it is always assumed that this info is present.

**To Reproduce**
Use conda-forge environment to build pandoc, f.e. using docker.

```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=204662&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642
```
As there is no way to specify it, would be great if it could just find the file... or what am I missing? Is this a ghc or pandoc issue instead? (and no, I cannot just use stack, as that is not available everywhere and has only very specific packages (f.e. no aarch64))

**Comment by phadej** [comment]
```
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.
```

The `v1` commands are not supported anymore.
