### ISSUE TITLE
Path forward for forking pieces of cabal-bootstrap-gen

### ISSUE THREAD

**Issue by blackgnezdo** [haskell/cabal#7036]
This is not a bug report but rather a request for comment.

I've been working on [OpenBSD ports infra for building Haskell programs with cabal](https://github.com/blackgnezdo/ports/issues/3).
As part of that work I found cabal-bootstrap-gen very handy and hacked it up like this:
https://github.com/haskell/cabal/compare/3.4...blackgnezdo:openbsd-port-manifest

The idea is to produce a subset of what cabal-bootstrap-gen creates but do this for a larger population of hackage programs.  While I can imagine some generalization opportunities and code sharing, I don't feel it's important enough to invest into this work. The two places have sufficient different goals and constraints.

Should I simply copy cabal/LICENSE file over into a newly forked project and move on? Is the code I took simple enough that you'd consider allowing me to relicense it under BSD 2-clause and donating the result to the OpenBSD project?

**Comment by phadej** [comment]
@blackgnezdo see `cabal-bundler` in https://github.com/phadej/cabal-extras

**Comment by blackgnezdo** [comment]
Yes, I made a small addition to cabal-bundler which now supports my use case.
