### ISSUE TITLE
Cabal install flag --prefix does not work as intended

### ISSUE THREAD

**Issue by JonasRSV** [haskell/cabal#7070]
**Describe the bug**
When using --prefix flag for cabal the documentation says that it will use that directory as installation directory: https://cabal.readthedocs.io/en/3.4/setup-commands.html?highlight=libdir#cmdoption-runhaskell-Setup.hs-configure-prefix

**To Reproduce**

Download precompiled cabal 3.2.0.0 binary from https://www.haskell.org/cabal/download.html for x86-64
Installed ghc from https://www.haskell.org/ghc/download_ghc_8_6_5.html

Then run cabal install xmonad --prefix=/tmp

Files should show up in tmp, instead my files always show up in $HOME/.cabal/

**Expected behavior**
I expect cabal to install the things at the provided path.

**System information**

- Ubuntu 18.0.4.3
- ghc version 8.6.5
- cabal verison 3.2.0.0

**Comment by fgaz** [comment]
Note that the one you linked is the chapter on `Setup.hs` flags. `Setup.hs` is a lower-level interface on which tools like `cabal-install` build upon.

Im not sure if this is your use case, but if you need every artifact to be in a specific place you could use the `--store-dir` flag instead

**Comment by JonasRSV** [comment]
Thanks
