### ISSUE TITLE
Ability to build a cabal script into executable

### ISSUE THREAD

**Issue by ethercrow** [haskell/cabal#7073]
When I have a haskell program in a form of a single file script like

```
#!/usr/bin/env cabal
{- cabal:
build-depends: base, lens, shake, ...
-}
main = putStrLn "All done."
```

I'd like to be able to build it into a standalone executable.

Currently it seems like you can only build something with `cabal v2-build` if there is a cabal file and/or a project file, but building single file scripts is not supported:

```
> cabal v2-build Main.hs
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file ...
```

Creating a package description file is exactly what I'd like to avoid for small programs, since all the necessary information is already contained in the source file.

**Comment by jneira** [comment]
In fact cabal generates an executable when you does a `cabal v2-run script.hs`, it is under dist-newstyle\build\x86_64-windows\ghc-8x.x.x\fake-package-0\x\script\build\script\script.exe in my windows system (the precise path can be different in other os). Maybe it would not be a final solution but maybe a working workaround.

**Comment by phadej** [comment]
@jneira as if I remembered that `cabal script` should just use `runghc`. Whether it should first compiler and run executable, or just interpret is better left to the choice of user. (I think that interpreting is more reasonable default for scripts).

**Comment by bacchanalia** [comment]
I think #7851 resolved this issue.

**Comment by Mikolaj** [comment]
It seems so. @ethercrow (and other interested parties), could you kindly confirm if it solves your use case? Ideally by compiling the master branch and trying it out.

**Comment by georgefst** [comment]
#7851 certainly improves the situation. But there's no easy way to find the resulting binary. It would be great if `list-bin` worked for scripts (and/or `install`, but I've always had issues with that one).

**Comment by bacchanalia** [comment]
There are so many cabal sub commands I didn't even realize `list-bin` was a thing. Adding `list-bin` support for scripts seems reasonable. I think installing a script going against the spirit of a script, though.

**Comment by georgefst** [comment]
> There are so many cabal sub commands I didn't even realize `list-bin` was a thing.

Not unreasonably: #7774.

> Adding `list-bin` support for scripts seems reasonable. I think installing a script going against the spirit of a script, though.

Well, if you have `list-bin` then I was thinking `cabal install Script.hs` is just a shortcut for (roughly) `cabal build Script.hs && cabal list-bin Script.hs | cp ~/.local/bin`. But I seem to remember that `install` isn't defined like that, and I've never understood why.
