### ISSUE TITLE
New feature required to work around platform-specific source-repository-package issue

### ISSUE THREAD

**Issue by newhoggy** [haskell/cabal#7083]
**Describe the bug**
Sometimes we have the situation where a package we depend only builds on a specific platform.  For example `libsystemd-journal` only builds on Linux.  We can `if os(linux)` in the cabal file, so that much is fine, but let's say the package has a bug in it and we want to fork it and used the fork until the bug is upstreamed.  This does not work because `source-repository-package` adds the project to the list of local packages to always build, so `cabal all` no longer works, which breaks CI.

**To Reproduce**
Described above.

**Expected behavior**
This could be fixed in a number of ways.  Add support for `if` in `cabal.project` would allow us to conditionally add `source-repository-package`.  Or we could make `source-repository-package` not add to the list of local projects to build.

**System information**
Affects all versions of cabal currently.

**Additional context**
Work arounds include using `allow-newer`, for example `allow-newer: libsystemd-journal:base` if the problem is just a version bound adjustment.

But this does not solve the problem if the problem preventing the build from succeeding is not a bounds issue.

**Comment by georgefst** [comment]
I've just hit this, as you can see above. I guess ideally it would be closed via #5444?

**Comment by gbaz** [comment]
Yeah, looks like the same exact issue in fact. Can we close this one as a dup?

**Comment by georgefst** [comment]
I wouldn't call it the exact same issue. But #5444 is a solution to this one, and probably the best one. I guess if maintainers agree that this should be fixed by implementing #5444, then there's an argument for closing it.

**Comment by gbaz** [comment]
ok lets just note this will be resolved by #7783

**Comment by jneira** [comment]
...and as #7783 adding conditionals to cabal
project has been merged, we can close this
thanks all!
