### ISSUE TITLE
doctest installation error

### ISSUE THREAD

**Issue by curiositymap** [haskell/cabal#7095]
Hi, I'm trying to install doctest using cabal, but I came across this error when entering `cabal install doctest`:

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _awaitEvent in libHSrts.a(Select.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build exe:hsc2hs from hsc2hs-0.68.7 (which is required by
exe:doctest from doctest-0.17). See the build log above for details.

Could you please take a look and let me know how to resolve this? Thanks!

**Comment by phadej** [comment]
This is most likely a GHC bug, or just you are using GHC bindists on macOS version which it doesn't support or built for.

Please open an issue on GHC issue tracker, https://gitlab.haskell.org/ghc/ghc, and tell the GHC version you use and macOS version you are using, and all other possibly relevant details.

**Comment by curiositymap** [comment]
Thanks for the answer. I consulted with my professor and it turned out this problem can be easily solved by updating Xcode to version 12.
