### ISSUE TITLE
tool support for checking if a package works with a range of versions

### ISSUE THREAD

**Issue by bos** [haskell/cabal#710]
(Imported from [Trac #719](http://hackage.haskell.org/trac/hackage/ticket/719), reported by @dcoutts on 2010-07-28)

[Doaitse reports](http://www.haskell.org/pipermail/libraries/2010-July/013970.html) that he would like:

<pre class="wiki">since I do not have a wide variety of Haskell installations and
package versions on my machine, it would be very nice if the
hackage server could test a package against the extremes of the
indicated dependency ranges before installing. This would have
prevented the mistake I made (and which undoubtedly others will
make too)
</pre>Others responded that they would also like to do the same thing locally, even though the range of versions they have locally may be limited.

So one simple approach would be a flag to indicate a preference that the earliest version of a package (or all packages?) be used rather than the latest version. This might be integrated into a "cabal disttest" feature that makes a tarball and builds from the tarball.

The same approach could be taken for hackage build bots.

**Comment by grayjay** [comment]
See #2876.

**Comment by grayjay** [comment]
I'm closing this issue because it is similar to #2876, but it has fewer comments.
