### ISSUE TITLE
"Page does not exist" on cabal.readthedocs.io

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7102]
https://cabal.readthedocs.io lists the following versions of the documentation, and some of them lead to unicorn wonderland:
-    latest
-    3.4
-    3.2: page does not exist
-    3.0: page does not exist
-    2.4: page does not exist
-    2.0: page does not exist

Conjectured solution: a maintainer log into readthedocs.org and _build_ these versions there.  (Does not happen automatically, in my experience, one has to push the "Build" button.)

**Comment by gbaz** [comment]
It appears this now works.
