### ISSUE TITLE
cabal-install doesn't report which package it failed at

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#7124]
**Describe the bug**

When a source-repository dependency has an incorrect `extra-source-files` field, cabal will bail out with:

```
cabal: filepath wildcard 'ChangeLog.md' does not match any files.
```
not giving any indication where the error exactly happened. At first glance, it seems it's the current package, but it isn't necessarily.

Also see https://github.com/input-output-hk/smash/issues/91

**To Reproduce**

1. `git clone https://github.com/input-output-hk/smash.git`
2. `cd smash`
3. `git checkout b7fa2fecad8dded717352579507a3d04a140f05f`
4. `cabal install`

**Comment by phadej** [comment]
https://github.com/haskell/cabal/pull/7146 will resolve this

```
HEAD is now at 13f44ad Compile with GHC8.10.2 (#157)
HEAD is now at 2547ad1 Merge pull request #65 from dcoutts/dcoutts/drop-vrf-p256-openssl
HEAD is now at 9f95fb8 Update dependencies
HEAD is now at 74188f62 Merge pull request #1814 from input-output-hk/nc/relation
HEAD is now at 4814003f Merge #1721
HEAD is now at 0c5b0a6 Merge #120
HEAD is now at b3231f7 Merge #370
HEAD is now at cde90a2 Re-enable support for GHC 8.6.5
HEAD is now at 8f2086a Merge #575
HEAD is now at f0eb6e439 Merge #2546
cabal: sdist of cardano-client-0.1.0.0: filepath wildcard 'ChangeLog.md' does
not match any files.
````
