### ISSUE TITLE
Data-Files cabal directive should support directories

### ISSUE THREAD

**Issue by bos** [haskell/cabal#713]
(Imported from [Trac #722](http://hackage.haskell.org/trac/hackage/ticket/722), reported by cygnus on 2010-08-02)

It should be possible to use the <tt>Data-Files</tt> directive to include whole directories (recursively) in source distributions.  In many cases it's impossible or cumbersome to list all of the files one would like to install, and it seems to me that nobody should have to do that if what they really mean is, "install everything in that-data-dir/."

In implementation terms, this doesn't strike me as too tricky; after the wildcard parsing that already happens, detect whether the files to be copied are in fact directories and copy them recursively as such.

I'm more than willing to hack on this.

**Comment by BardurArantsson** [comment]
Tihs is either superceded  by (or supercedes) https://github.com/haskell/cabal/issues/784 . Can we please close one of them?

**Comment by ezyang** [comment]
OK, closing this one.
