### ISSUE TITLE
subdir of source-repository-package behaves odd with '.'

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#7131]
**Describe the bug**

```
source-repository-package
    type: git
    location: https://github.com/input-output-hk/cardano-prelude
    tag: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdir:
        .
        test
```

Doesn't work (it can't find the package `.` points to).

Same for

```
source-repository-package
    type: git
    location: https://github.com/input-output-hk/cardano-prelude
    tag: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdir: test
        .
```

But this works

```
source-repository-package
    type: git
    location: https://github.com/input-output-hk/cardano-prelude
    tag: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdir: .
        test
```

For subdirs without `.` it doesn't seem to matter.

**To Reproduce**

1. clone https://github.com/input-output-hk/cardano-wallet
2. set the cardano-prelude thing to what describe above
3. try to resolve

**Additional context**

Found during stack2cabal: https://github.com/hasufell/stack2cabal/pull/32

cabal-3.4.0.0-rc4

**Comment by phadej** [comment]
This is due `cabal.project` parser using old parser, where the line with bare dot `.` is used to inser newline (c.f. `description`).

I could leave this open until someone rewrites `cabal.project` parser to use `Distributions.Fields` etc. framework, but I don't know when this will happen. So closing this now: workaround: don't put single dot on own newline, as you won't write

```
hs-source-dirs:
  .
```

for old formats.

**Comment by hasufell** [comment]
Why did you close the bug report then? Is it valid or not? Whether someone is going to work on it or not is irrelevant. If that's our metrics, then we could close probably half of the bug reports in this issue tracker.

**Comment by phadej** [comment]
I consider this user error.

**Comment by phadej** [comment]
I was looking at this. Seems that https://github.com/haskell/cabal/commit/fe82a920598367debc7553da016e85574f8a3fe8 fixes this. That commit is in `master` but isn't in `3.4`.

Can you check it fixes an issue for you, @hasufell?

**Comment by hasufell** [comment]
Yes, can confirm!
