### ISSUE TITLE
streaming output with v2-test

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#7147]
This is probably duplicate, but I'm annoyed by this enough to open another one.

In CI not seeing the test output is problematic, accessing log files is impossible as well.

One problem with streaming output is that we need to delimit the output, something like https://hackage.haskell.org/package/concurrent-output. We'll need this in `Cabal` itself too.

**Comment by DanielG** [comment]
Don't we have `--test-show-details=direct` for v2-test already? Wouldn't that work? IIRC the only downside over `=streaming` is that it doesn't write log files that way.

**Comment by phadej** [comment]
Let me try `--test-show-details=direct` with `haskell-ci`.

**Comment by phadej** [comment]
It worked. For (`haskell-ci`) CI use it's perfect, as the log files are quite useless. Some other CI systems (which store log files) might want both though, so I leave this issue open, even my immediate problem is sresolved.

Thanks @DanielG !

**Comment by phadej** [comment]
`--test-show-details=direct` doesn't work with `build-type: Custom` and `Cabal` bundled with GHC-7.10

**Comment by gbaz** [comment]
Closing this based on the `direct` thing seeming like a proper solution, despite it not working with sufficiently old `Cabal`s.
