### ISSUE TITLE
cabal.project package flags requires +/- contradicting documentation

### ISSUE THREAD

**Issue by blackgnezdo** [haskell/cabal#7155]
**Describe the bug**

`cabal-project.rst` claims:
[If there is no leading punctuation, it is assumed that the flag should be enabled](https://github.com/haskell/cabal/blob/6118fd90c1c3b5181aa1079d618e048783afffbe/doc/cabal-project.rst)

This doesn't seem to be the case when using [xmonad/cabal.project](https://github.com/xmonad/xmonad/commit/11814bfec35e135b0d99b0a97888da8930c8e39e) with cabal 3.4.0.0-rc5

**To Reproduce**
```
% cat cabal.project
-- cabal.project

packages:
  xmonad.cabal

package xmonad
  flags: generatemanpage

% cabal v2-freeze
cabal: Error parsing project file xmonad/cabal.project:7:
"<eitherParsec>" (line 1, column 1):
unexpected 'g'
expecting "+", "-", white space or end of input
```

**Expected behavior**

Once I insert `+` before `generatemanpage` it goes through:
```
Resolving dependencies...
Wrote freeze file: /home/greg/s/xmonad/cabal.project.freeze
```

**System information**
 - Operating system: OpenBSD
 - `cabal` 3.4, `ghc` 8.10.2

@peti FYI re https://github.com/xmonad/xmonad/commit/11814bfec35e135b0d99b0a97888da8930c8e39e

**Comment by phadej** [comment]
Documentation is out of date.
