### ISSUE TITLE
Distinguish speculative and required build-depends upper bound

### ISSUE THREAD

**Issue by bos** [haskell/cabal#716]
(Imported from [Trac #725](http://hackage.haskell.org/trac/hackage/ticket/725), reported by @ezyang on 2010-08-14)

When a package adds a build-dependency on another package, it's good form to follow the Package Versioning Policy and add a speculative upper bound that is x.(y+1), if the current version is x.y. This is great, but in many cases the next version will /not/ break compatibility with your package. In that case, once you have tested that the dependency is fine, you can bump the upper bound.

As the list of dependencies for any respectable Cabal package can be quite long, it may be useful to have some sort of 'cabal whatsnew' command which checks the upper bounds of your build dependencies and notifies you when there are newer versions than your upper bounds availble. Furthermore, there should be a mechanism for telling Cabal that the upper bound is required, and that the package will break if you try to bump it.

**Comment by BardurArantsson** [comment]
I think "git bisect" + build script largely replaces this. (Without having read through this in too much detail.)

Close?
