### ISSUE TITLE
Failure to build cabal-install-3.2.0.0 with ghc-8.10.1

### ISSUE THREAD

**Issue by fxcoudert** [haskell/cabal#7160]
**Describe the bug**
We're trying to build cabal-install-3.2.0.0 on macOS with ghc-8.10.1
We are applying this commit on top of 3.2.0.0: https://github.com/haskell/cabal/commit/b6f7ec5f3598f69288bddbdba352e246e337fb90

**To Reproduce**
Running `sh bootstrap.sh --sandbox` with ghc 8.10.1 on macOS leads to:

```
Setup: Encountered missing or private dependencies:
base >=4.5 && <4.14
```

**System information**
- macOS 11.0.1 Big Sur
- ghc 8.10.1
- cabal-install-3.2.0.0 with this commit on top https://github.com/haskell/cabal/commit/b6f7ec5f3598f69288bddbdba352e246e337fb90

**Comment by phadej** [comment]
There is no `cabal-install-3.2.x.y` buildable with GHC-8.10.

`cabal-install-3.4.0.0` will be released as soon as GHC-9.0 is released (which will be buildable with GHC-8.10, but **not** GHC-9.0 - there is bootstrap ordering problem). The `cabal-install-3.4.1.0` will hopefully appear soon after, once the dependencies catch up with GHC-9.0

This issue is not actionable, closing.

**Comment by fxcoudert** [comment]
I'm a Homebrew developer, so from the point of view of a distro: what version of `cabal-install` are we supposed to ship alongside ghc 8.10.1 ?

**Comment by fxcoudert** [comment]
Also, I don't understand: we updated to ghc 8.10.1 on 2020-03-25, and updated to cabal-install 3.2.0.0 on 2020-04-04. At that second date, cabal-install 3.2.0.0 was definitely building with ghc 8.10.1, as our CI passed and produced binaries.

**Comment by phadej** [comment]
With GHC-8.10? `cabal-install-3.2`. Unfortunately we hadn't resources to make a release of `cabal-install-3.2` which itself isbuildable with GHC-8.10. As you need an older GHC to bootstrap/compile newer GHC, you can use it to compiler newer cabal-install as well.

- If `homebrew` compiles GHCs, use same (older) GHC to compiler `cabal-install`
- If you use official bindists for GHC, use official bindists for `cabal-install`.
