### ISSUE TITLE
Mention in documentation executable-to-library self dependency feature in 1.8.0.4

### ISSUE THREAD

**Issue by bos** [haskell/cabal#717]
(Imported from [Trac #726](http://hackage.haskell.org/trac/hackage/ticket/726), reported by @ezyang on 2010-08-14)

<pre class="wiki">Thu Jun 10 19:27:49 PDT 2010  ezyang@mit.edu
  * Mention self-referential dependency feature in Cabal &gt;= 1.8.0.4.
    hunk ./doc/Cabal.markdown 135
    -that library.
    +that library.  Fortunately, starting with Cabal 1.8.0.4, executables can
    +also declare the package that they are in as a dependency, and Cabal
    +will treat them as if they were in another package that dependended on
    +the library.
</pre>

**Comment by ezyang** [comment]
Fixed when I introduced internal libraries.
