### ISSUE TITLE
cable configure failure

### ISSUE THREAD

**Issue by livid1664** [haskell/cabal#7177]
Hello

I tried to run "cabal build" and the response "cabal: Run the 'configure' command first."

So i tried "cabal configure". Response was 
  
[j00533938@lhrplinux00001 roc3]$ cabal configure
Resolving dependencies...
Configuring roc3-0.1...
cabal: At least the following dependencies are missing:
split -any

Note: I had previously run "cabal update" and this completed successfully:
[j00533938@lhrplinux00001 roc3]$ cabal update
Downloading the latest package list from hackage.haskell.org

The version of cabal i am using is:
[j00533938@lhrplinux00001 roc3]$ cabal --version
cabal-install version 1.16.1.0
using version 1.16.0 of the Cabal library

QS: How to resolve the missing dependencies as indicated by "cabal configure"?

Thanks in Advance
JO

**Comment by fgaz** [comment]
That's a really old cabal-install. Can you upgrade or do you need to use that version?

**Comment by fgaz** [comment]
Please reopen the issue if the problem persists with a newer cabal-install
