### ISSUE TITLE
Rewrite user guide, document cabal-install

### ISSUE THREAD

**Issue by bos** [haskell/cabal#718]
(Imported from [Trac #728](http://hackage.haskell.org/trac/hackage/ticket/728), reported by @dcoutts on 2010-08-18)

The Cabal user guide is rather out of date. There is no documentation for the cabal-install tool (which should cover the config file format too).

We should also have a man page for cabal-install and perhaps the Cabal file format too.

**Comment by jsl** [comment]
This issue is pretty unspecific and hasn't had any activity since 2010. It seems that much documentation has been added since that point. I propose closing. Please open a new issue for specific issues related to documentation.

/cc @tibbe
