### ISSUE TITLE
Caching of MacOS builds much worse than that of Linux

### ISSUE THREAD

**Issue by newhoggy** [haskell/cabal#7199]
**Describe the bug**
Caching of build on MacOS seems to be less effective than Linux.

**To Reproduce**
I have a situation where in CI, Linux builds cache very well, but MacOS much less so.  For example:

https://github.com/input-output-hk/cardano-db-sync/runs/1568423177?check_suite_focus=true

The `build (8.6.5, ubuntu-latest)` job runs the `Build` step in `15s`, but the same step on `build (8.6.5, macos-latest)` runs in `12m 7s`.

If you expand the build step, you can see that the MacOS build is re-building a lot of packages, whereas the Linux one isn't.

All of the packages that were unnecessarily built are `git` references in the `cabal.project`.

The problem can be reproduced by forking the repository and creating a PR.

**Expected behavior**
The MacOS build should cache just as much as the Linux build.

**System information**
 - MacOS
 - `cabal-3.4.0.0-rc4`, `ghc-8.6.5` and `ghc-8.10.2`

**Additional context**
N/A

**Comment by phadej** [comment]
I don't see a problem.

The dependencies are cached. *Build dependencies* step takes 17s

![Screenshot from 2020-12-17 13-53-32](https://user-images.githubusercontent.com/51087/102484715-536afc80-406f-11eb-9a38-5db12bd415c6.png)


However `dist` cache step is not executed at all for some reason?

![Screenshot from 2020-12-17 13-54-24](https://user-images.githubusercontent.com/51087/102484774-67aef980-406f-11eb-9576-90a7a9f445d2.png)

So it seems right that the build part is redone.
