### ISSUE TITLE
Is it possible to copy a folder into data directory recursively ?

### ISSUE THREAD

**Issue by poscat0x04** [haskell/cabal#7207]
I'm trying to write a project templating tool similar to cookiecutter and need to bundle a list of templates with the program. After some research, the only way I found to do so is to add files to the list `data-files`, which does not preserve the directory structure.
Are there any ways of copying a whole directory into the data dir?

**Comment by poscat0x04** [comment]
I think currently this is impossible

**Comment by fgaz** [comment]
You can do some globbing though

**Comment by poscat0x04** [comment]
I sure can, but It would not preserve the directory structure; everything will be flattened.
