### ISSUE TITLE
Install instructions for cabal-3.4.x are out of date

### ISSUE THREAD

**Issue by tdiesler** [haskell/cabal#7215]
The main README and the README in cabal-install talk about bootstrap.sh, which doesn't exist any more. How would I install Cabal (on aarch64) when I only have GHC?

**Comment by phadej** [comment]
first option should be downloading the bindist. If you are on macOS aarch64, then it's not currently supported.

**Comment by phadej** [comment]
There are bindists for rc4: https://mail.haskell.org/pipermail/cabal-devel/2020-October/010490.html

**Comment by tdiesler** [comment]
Thanks Oleg, I'm already using that distro [here](https://github.com/tdiesler/nessus-cardano/blob/master/node/docker/Dockerfile#L59)

**Comment by jwaldmann** [comment]
> How would I install Cabal ... when I only have GHC?

for me, this works (running from the repo root)
```
./bootstrap/bootstrap.py -d bootstrap/linux-8.8.4.json
```
(I did copy linux-8.8.3.json and replaced the versions of bytestring, process, ghc-boot-th)

https://github.com/haskell/cabal/blob/master/bootstrap/README.md

**Comment by ciez** [comment]
`./bootstrap/bootstrap.py -d bootstrap/linux-8.10.4.json` results in:

> Bootstrapping finished!
> 
> The resulting cabal-install executable can be found at
> 
>     ~/cabal/_build/bin/cabal
> 
> It have been archived for distribution in
> 
>     ~/cabal/_build/artifacts/cabal-install-3.4.0.0-x86_64-bootstrapped.tar.xz
> 
> You now should use this to build a full cabal-install distribution
> using v2-build.

what are the next steps?

**Comment by ciez** [comment]
> first option should be downloading the bindist.

Surely, there should always be a way to build cabal-install from source?

Why was bootstrap.sh removed? It worked just fine with previous versions of cabal-install.

**Comment by gbaz** [comment]
I think this is resolved in the current github readme?
