### ISSUE TITLE
Cabal should give haddock per-package source entity paths

### ISSUE THREAD

**Issue by bos** [haskell/cabal#723]
(Imported from [Trac #733](http://hackage.haskell.org/trac/hackage/ticket/733), reported by @igfoo on 2010-09-04)

Cabal should give haddock per-package source entity paths, so that haddock can make cross-package source links when necessary.

See [http://hackage.haskell.org/trac/ghc/ticket/3810](http://hackage.haskell.org/trac/ghc/ticket/3810) for more details.

**Comment by ttuegel** [comment]
This seems to be fixed.
