### ISSUE TITLE
cabal v2-install does not modify the environment file when using --write-ghc-environment=always

### ISSUE THREAD

**Issue by eed551** [haskell/cabal#7230]
cabal v2-install does not modify the environment variable.

$cabal v2-install name_of_package --write-ghc-environment=always --package-env=def.env --overwrite-policy=always
> Up to date 

However, the file def.env is not modified. I can check that if I introduce a syntactical error in the def.env file I get the following message:
> Warning: The environment file current_path/def.env is unparsable.
Libraries cannot be installed.

By the way I do not know why it is said "Up to date" since the package does not appear in the default environment variable and, if I try to use it to install another Cabal package, it is said that is is "unknown".

I was expecting that the def.env file would be modified.

 - Operating system: Ubuntu 20
 - `Cabal version 3.4.0.0
 - ghc version 8.10.3

The motivation for my question is that my packages that are "installed" with Cabal do not appear in the default environment (and not in the ghc-pkg list either) and are "unknown" when I try to install other packages that depend on them. I wanted to enforce Cabal to register them.

**Comment by fgaz** [comment]
I think you may want `--lib` instead of `-write-ghc-environment=always`

**Comment by gbaz** [comment]
At this point I think the question was resolved and I'm going to close this ticket.
