### ISSUE TITLE
support multiple .cabal files

### ISSUE THREAD

**Issue by bos** [haskell/cabal#724]
(Imported from [Trac #734](http://hackage.haskell.org/trac/hackage/ticket/734), reported by guest on 2010-09-06)

if there are several *.cabal files in the working
directory, then "cabal configure" complains,
and does nothing. That's OK, but it should then
have an option for picking  one of these files
(cf. "make -f FILE").

**Comment by BardurArantsson** [comment]
I think this is entirely superceded by https://github.com/haskell/cabal/issues/2631 and should be closed.

**Comment by deepfire** [comment]
A related thread: https://mail.haskell.org/pipermail/libraries/2011-January/015608.html
