### ISSUE TITLE
Error while updating world-file when v1-installing cabal-install

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7244]
cabal-3.5.0.0 (master) crashes with garbled error message after v1-installing cabal-install:
```
$ cabal-3.5.0.0 v1-install cabal-install
Resolving dependencies...
Downloading  Cabal-3.2.1.0
...
Installing executable cabal in /Users/abel/.cabal/bin
Completed    cabal-install-3.2.0.0
Error while Error while updating world-file. : dieVerbatim: user error (cabal-3.5.0.0: Could not parse world file.
)
```

**System information**
 - Operating system: macOS Mojave
 - `cabal` 3.5.0.0
 - `ghc` 8.8.4

**Additional context**
I invoked above command to downgrade from cabal-master to cabal-released (3.2.x).

**Comment by fgaz** [comment]
[v1- is unsupported in currently maintained cabal-install versions](https://mail.haskell.org/pipermail/cabal-devel/2020-September/010488.html). Doesn't v2-install work?

**Comment by fgaz** [comment]
I'll close this, but please open another issue if v2-install isn't working too.
