### ISSUE TITLE
Cabal 3.4-rc4 cabal.project parser regression

### ISSUE THREAD

**Issue by emilypi** [haskell/cabal#7268]
**Describe the bug**
 
Cabal 3.2 parses both newline and comma-delineated lists in `allow-newer` and `allow-older`, but Cabal 3.4 is only aware of comma-delineated lists when parsing a `cabal.project` file. 

**To Reproduce**

```
λ P temp → cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
λ P ~ → mkdir temp
λ P ~ → cd temp 
λ P temp → cabal init 
...      
λ P temp → echo "packages .\nallow-newer:\n\ttext\n\tvector" > cabal.project 
λ P temp → cabal build
cabal: Error parsing project file
/Users/emilypi/haskell/davean/temp/cabal.project:3:
"<eitherParsec>" (line 2, column 1):
unexpected 'v'
expecting space, comma, white space or end of input
λ P temp → cat cabal.project 
packages .
allow-newer:
	text
	vector
```

In a non-toy project, if I add comma-delineated lists to `allow-newer` in the `cabal-project`, then it works just fine. In either case, 3.2 works fine for both non and comma-delineated lists. 3.4 only seems to work with comma lists. Is this intended behavior? 

**System information**
 - MacOS Big Sur
 - GHC 8.10.3

**Comment by phadej** [comment]
Yes. `allow-newer` syntax is rich (constraints), and allowing to omit commas there was a mistake.
