### ISSUE TITLE
Cabal check warns about ill-specified dependencies

### ISSUE THREAD

**Issue by bos** [haskell/cabal#727]
(Imported from [Trac #737](http://hackage.haskell.org/trac/hackage/ticket/737), reported by guest on 2010-09-09)

Packages that get listed here:
[http://hackage.haskell.org/packages/archive/preferred-versions](http://hackage.haskell.org/packages/archive/preferred-versions)

Get special treatment from cabal-install.  It would help package authors if 'cabal check' could warn about version ranges, especially for packages listed in the preferred-version file.

For example, if the .cabal file just mentions package FOO and preferred-versions asks for FOO &lt; X, then the author might not be aware that some people might expect to use FOO &gt;= X.  It would be nice to let the author know that they need to say, FOO == Y.* or FOO &gt; A &amp;&amp; FOO &lt; B.

This is particularly important for base, where lacking an upper bound leads to bad build behavior.

This should probably be implemented in the Cabal library.

**Comment by jsl** [comment]
Cabal currently does check for an upper-bound on `base`, so it seems the most critical part of this ticket has been addressed:

```
justin ~/Code/atomic-write $ cabal check
The following errors will cause portability problems on other environments:
* The dependency 'build-depends: base' does not specify an upper bound on the
version number. Each major release of the 'base' package changes the API in
various ways and most packages will need some changes to compile with it. The
recommended practise is to specify an upper bound on the version of the 'base'
package. This ensures your package will continue to build when a new major
version of the 'base' package is released. If you are not sure what upper
bound to use then use the next major version. For example if you have tested
your package with 'base' version 2 and 3 then use 'build-depends: base >= 2 &&
< 4'.

Hackage would reject this package.
```

Given that there is no other activity on this ticket since 2010, I propose closing. Please open another ticket if there are other issues related to specifying other bounds which should be addressed.

/cc @tibbe
