### ISSUE TITLE
Cabal init fails with 'no package name provided' if name is already taken on hackage

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#7273]
**Describe the bug**
When I do `cabal init` this doesn't prompt me for anything and just dies.

```
Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating Main.hs...
Error: no package name provided.
```

explicitly specifying interactive mode gets:

```
Should I generate a simple project with sensible defaults? [default: y] y

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Warning: Setup.hs already exists, backing up old version in Setup.hs.save0
Generating CHANGELOG.md...
Warning: CHANGELOG.md already exists, backing up old version in CHANGELOG.md.save0
Error: no package name provided.
```

and the cabal file is never created. Only

```
CHANGELOG.md  Main.hs  Setup.hs
```

**To Reproduce**

```
$ cabal init
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system: Windows 10 (bash or powershell)
 - `cabal`, `ghc` versions: `3.2.0.0` and `8.8.4`

**Additional context**

**Comment by fgaz** [comment]
Does this happen in any directory or just in ones with specific names?

**Comment by Mistuke** [comment]
@fgaz wow.. it's... very interesting... I've tried in a number of directories and they work, but if I create a directory named `monarch` anywhere... `cabal init` fails with the error above..

**Comment by jhrcek** [comment]
It's probably because there already is package with the name like that on hackage: http://hackage.haskell.org/package/monarch
I saw issue like that in the past: https://github.com/haskell/cabal/issues/6236

**Comment by Mistuke** [comment]
Oh wow, that does sound like the issue indeed

**Comment by Mistuke** [comment]
The fix seems relatively recent. I'll try cabal 3.4 rc5

**Comment by emilypi** [comment]
Yeah, this is the dumb "if the package exists, it'll crap out with no reasonable error" workflow. I can add this to my work on #7265

**Comment by andreasabel** [comment]
Please update the title of this issue to something less generic, e.g. "Cabal init fails with non-descriptive error if name is already taken on hackage".

**Comment by KristianBalaj** [comment]
This issue is still appearing with cabal `3.4.1.0`

I named the directory `streaming` and the `cabal init` failed with the error.

**Comment by Mikolaj** [comment]
Hi @KristianBalaj,

Hi! It works fine on master branch (to be released as 3.8; I haven't tried with 3.6.2). It asks you whether you want to name the package so anyway and then proceeds fine. Please confirm.

**Comment by KristianBalaj** [comment]
@Mikolaj 
The following is the behaviour with cabal `3.4.1.0`, it does not ask for anything:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/20045353/150345202-68b183cf-065d-41e5-9785-72190cf88d55.png">

**Comment by Mikolaj** [comment]
@KristianBalaj: thank you for checking. I guess you need to upgrade?

**Comment by KristianBalaj** [comment]
Yeah sure, I was just reporting that in that version of cabal it is still an issue.

**Comment by Mikolaj** [comment]
Thank you again. I guess you may need (regardless of upgrading) run `cabal init` in interactive mode to enable the choice. No needed on the master branch, which is interactive by default now.
