### ISSUE TITLE
overwrite-policy is not documented

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#7275]
While I did find a mention of `install-method` in the docs, I did not find a mention of `overwrite-policy`, unless the search at 
https://cabal.readthedocs.io/en/3.4/search.html?q=%22overwrite-policy%22&check_keywords=yes&area=default
is failing me.

Given that every user who wants to re-install an executable with `cabal install` will have to think about this policy, this is probably worth documenting.

**Comment by fgaz** [comment]
Technically my fault since I added that flag :sweat_smile:

I don't have too much time right now but prs are welcome!
