### ISSUE TITLE
Cabal freeze should freeze either the hackage index or the pacakge revisions

### ISSUE THREAD

**Issue by TomMD** [haskell/cabal#7277]
**Describe the bug**
I just experienced a revision cause no small havoc with my CI/CD and general flow for all the team.  This revisions is here https://github.com/nick8325/quickcheck/issues/326.

The fact that revisions have consequences is fine.  The bug is that this project has a freeze file which should have ensured the project built the same now as it did six months ago.  Clearly freeze is not yet sufficient.

I'm using cabal 3.2 right now.

**Additional context**

I propose two competing solutions:

*Freeze the revisions*

Treating revisions as first class makes the most sense to me.  If it impacts the build and resulting code then its part of freeze.  At the same time this can be verbose and counter productive - users can't just say "unfreeze up to the newest revision".

*Freeze the hackage index*

If we freeze the hackage index then users can benefit from a fixed set of packages, including revision, but have a single line to change and obtain new revisions but not change the package versions.

**Comment by phadej** [comment]
`cabal-install-3.4` writes `index-state` to freeze files.
