### ISSUE TITLE
cabal.project file doesn't parse with cabal-install 3.4.0.0-rc4

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#7279]
**Describe the bug**

`cabal.project` file that parsed with cabal-install 3.2.x no longer parses with the latest release candidate (and I can't see any guidelines in the release notes)

**To Reproduce**

Given:

```
packages: hstar
        , archive-sig
        , archive-libarchive
        , archive-tar
        , snappy-lazy
        -- , archive-tar-bytestring

max-backjumps: 40000

constraints: archive-sig +development
           , archive-libarchive +development
           , archive-tar +development
           , archive-tar-bytestring +development
           , hstar +development +with-snappy +with-brotli

package zlib
  flags: -pkg-config +bundled-c-zlib
```

I get the following error with cabal-install 3.4.x

```
cabal: Error parsing project file
/home/vanessa/programming/haskell/done/archive-backpack/cabal.project:10:
"<eitherParsec>" (line 2, column 1):
unexpected ","
expecting space, "+" or "-"
```

when it worked with cabal-install 3.2.x

**Expected behavior**

It would still work, or there would be some change in the release notes telling how to change things.

**System information**
 - Linux
 - GHC 8.10.4, cabal-install-3.2.x and 3.4.x

**Comment by phadej** [comment]
you can probably do

```
constraints: archive-sig +development
constraints: archive-libarchive +development
...
```

as a workaround

**Comment by sheaf** [comment]
I've noticed this too... @vmchale does it work if you put the commas at the end of the lines instead? I think that's what I had to do on my end.

**Comment by unflawed** [comment]
Any movement on this?

**Comment by Mikolaj** [comment]
I guess we have an agreement this is a regression bug. If so, PRs are welcome. Given two workarounds, this not a blocker for future releases, but being a regression, this is relatively urgent.

**Comment by Mikolaj** [comment]
@ptkato: answering your question from IRC: I don't know where cabal.project is parsed, but fendor recently was adding to these parts of code, so he'd know (I think it's, sadly, some legacy code).

**Comment by jneira** [comment]
this needs a regression test which #8006 did not have
