### ISSUE TITLE
Correct way to parse a PackageDescription?

### ISSUE THREAD

**Issue by singpolyma** [haskell/cabal#7280]
`Distribution.PackageDescription.Parsec.readGenericPackageDescription` gets me a `GenericPackageDescription` which contains a `PackageDescription` with all empty sections (having the section data stored separately) but this means that useful functions like `allBuildDepends` cannot be used -- is there a better way to parse a cabal file into a `PackageDescription` that I'm missing?

**Comment by singpolyma** [comment]
Ah, nevermind. I just finally found `Distribution.PackageDescription.Configuration.flattenPackageDescription`

**Comment by fgaz** [comment]
@singpolyma note that, as the comment above the function notes, you may get an inconsistent result by just using flattenPackageDescription. See `finalizePD` instead for a complete conversion
