### ISSUE TITLE
Download link from haskell.org is outdated

### ISSUE THREAD

**Issue by iyefrat** [haskell/cabal#7282]
Hi,
The cabal download page [on haskell.org](https://www.haskell.org/cabal/download.html) still points to cabal 3.2.

**Comment by merijn** [comment]
That's because there hasn't been an official 3.4 release as of yet.

**Comment by iyefrat** [comment]
@merijn oh my bad, I assumed it had due to ghc 9.0.1 and the cabal 3.4 git tag/hackage upload. I'll close the issue.

**Comment by merijn** [comment]
The problem is that the maintainer who previously built the binaries: 1) does not have access to update the haskell.org page, and 2) stepped down. So the process of getting a new binary on haskell.org is taking longer than ideal.
