### ISSUE TITLE
Ill-formatted description of --test-options

### ISSUE THREAD

**Issue by kkurkiewicz** [haskell/cabal#7284]
In the user guide, the description of the flag --test-options is formatted as if the description was a flag itself (applies to all the versions of the guide available through the "v:" switch):

![image](https://user-images.githubusercontent.com/25784247/108425056-3fdc3d80-723a-11eb-9481-13ae2f54d8c4.png)

**Comment by acairncross** [comment]
When I build the docs locally this is formatted correctly

**Comment by kkurkiewicz** [comment]
@acairncross As far as only version 2.4 is concerned, I was able to resolve the problem just by adding a blank line after the line ".. option:: --test-options=options" in Cabal/doc/installing-packages.rst. When I build the original source*, however, I can still see the error.

*Branch: "2.4", build command: "make clean users-guide" (as specified in Cabal/doc/README.md)

**Comment by kkurkiewicz** [comment]
Also, the link to the page shown in the screenshot is https://cabal.readthedocs.io/en/2.4/installing-packages.html#cmdoption-setup-test-test-options. I tried two web browsers (Chrome and Edge); both render the flag in the same way.

**Comment by acairncross** [comment]
Ah right, so it's been fixed in master by #6971 but it hasn't been backported to older versions

**Comment by kkurkiewicz** [comment]
Well, okay. I'll wait for a merge, then.

**Comment by andreasabel** [comment]
Fixed by #6971.
