### ISSUE TITLE
Regression: cabal-install-3.4 hangs when running v2-update with `allow-newer` set in ~/.cabal/config

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#7291]
**Describe the bug**
I first noticed this bug when attempting to use [`haskell-ci`](https://github.com/haskell-CI/haskell-ci) in combination with `cabal-install-3.4` and [`head.hackage`](https://gitlab.haskell.org/ghc/head.hackage) (by way of `haskell-ci`'s `--head-hackage` flag). I noticed that any `haskell-ci` configurations where `head.hackage` enabled would hang forever whenever `cabal v2-update` was ran ([example](https://github.com/goldfirere/singletons/runs/1943724593?check_suite_focus=true#step:8:18)). However, `cabal v2-update` _would_ not hang on non–`head.hackage` configurations ([example from the same workflow](https://github.com/goldfirere/singletons/runs/1943724595?check_suite_focus=true#step:8:18)). Even stranger, if I downgraded from `cabal-install-3.4` to `cabal-install-3.2`, then the bug would disappear ([example](https://github.com/goldfirere/singletons/runs/1944201456?check_suite_focus=true#step:8:18)).

After some investigation, I discovered that this has nothing to do with `head.hackage` at all, but rather the way that `haskell-ci` sets up its `~/.cabal/config` file. In particular, it creates a `~/.cabal/config` file with [this line](https://github.com/goldfirere/singletons/runs/1943724593?check_suite_focus=true#step:6:61):

```cabal
allow-newer: *:Cabal *:array *:base *:binary *:bytestring *:containers *:deepseq *:directory *:exceptions *:filepath *:ghc *:ghc-bignum *:ghc-boot *:ghc-boot-th *:ghc-compact *:ghc-heap *:ghc-prim *:ghci *:haskeline *:hpc *:integer-gmp *:libiserv *:mtl *:parsec *:pretty *:process *:rts *:stm *:template-haskell *:terminfo *:text *:time *:transformers *:unix *:xhtml
```

**To Reproduce**
You can reproduce the issue locally by copying this line to your `~/.cabal/config` file and running `cabal v2-update`. This will hang with `cabal-install-3.4`:

```bash
$ /opt/cabal/3.4/bin/cabal v2-update -v # Hangs forever
```

But not with `cabal-install-3.2`:

```
$ /opt/cabal/3.2/bin/cabal v2-update -v
Project settings changed, reconfiguring...
Downloading the latest package list from hackage.haskell.org
Selected mirror http://hackage.haskell.org/
Downloading timestamp
/usr/bin/curl 'http://hackage.haskell.org/timestamp.json' --output /tmp/transportAdapterGet189075-1 --location --write-out '%{http_code}' --user-agent 'cabal-install/3.2.0.0 (linux; x86_64)' --silent --show-error --dump-header /tmp/curl-headers189075-2.txt
Waiting to acquire cache lock on
/home/ryanglscott/.cabal/packages/hackage.haskell.org/hackage-security-lock
Acquired cache lock on
/home/ryanglscott/.cabal/packages/hackage.haskell.org/hackage-security-lock
Released cache lock on
/home/ryanglscott/.cabal/packages/hackage.haskell.org/hackage-security-lock
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2021-02-21T01:03:49Z'
```

**Expected behavior**
I'm unclear if this is still intended to parse on `cabal-install-3.4`. Either I would expect it to parse or to fail immediately with a parse error, not hang.

**System information**
 - Ubuntu 20.04 (64-bit)
 - ```
   $ /opt/cabal/3.4/bin/cabal --version
   cabal-install version 3.4.0.0
   compiled using version 3.4.0.0 of the Cabal library
   ```

**Additional context**
Some further observations:

* This bug doesn't seem to trigger if you put the `allow-newer: ...` line in a `cabal.project` file instead of a `~/.cabal/config` file. If you put the line in a `cabal.project` file, it simply fails with a parse error:

  ```
  $ /opt/cabal/3.4/bin/cabal v2-update -v
  Project settings changed, reconfiguring...
  
  cabal: Error parsing project file
  /home/ryanglscott/Documents/Hacking/Haskell/staging/cabal.project:1:
  "<eitherParsec>" (line 1, column 9):
  unexpected '*'
  expecting space, comma, white space or end of input
  ```
* The size of the `allow-newer: ...` line appears to be important to triggering the bug. For example, if you put this line in your `~/.cabal/config` file:

  ```
  allow-newer: *:Cabal *:array *:base *:binary
  ```
  
  Then running `cabal v2-update` with `cabal-install-3.4` will simply fail with a parse error:
  
  ```
  $ /opt/cabal/3.4/bin/cabal v2-update -v
  
  cabal: Error parsing config file /home/ryanglscott/.cabal/config:22:
  Ambiguous parse in field 'allow-newer'.
  ```
  
  On the other hand, if you one more package to that line, like so:
  
  ```
  allow-newer: *:Cabal *:array *:base *:binary *:bytestring
  ```
  
  Then running `cabal v2-update` with `cabal-install-3.4` will hang instead.

**Comment by RyanGlScott** [comment]
A workaround is to avoid specifying this information in `~/.cabal/config` and instead specify it in a `cabal.project` file, but with commas separating each package:

```cabal
allow-newer: *:Cabal, *:array, *:base, *:binary, *:bytestring, *:containers, *:deepseq, *:directory, *:exceptions, *:filepath, *:ghc, *:ghc-bignum, *:ghc-boot, *:ghc-boot-th, *:ghc-compact, *:ghc-heap, *:ghc-prim, *:ghci, *:haskeline, *:hpc, *:integer-gmp, *:libiserv, *:mtl, *:parsec, *:pretty, *:process, *:rts, *:stm, *:template-haskell, *:terminfo, *:text, *:time, *:transformers, *:unix, *:xhtml
```

With this, I am able to run `cabal v2-update` successfully with both `cabal-install-3.4` and `cabal-install-3.2`. Note that the use of a `cabal.project` file is important, because if you put the line above into a `~/.cabal/config` file instead, it will hang with `cabal-install-3.4` (but not with `cabal-install-3.2`).

**Comment by Mikolaj** [comment]
I can't reproduce this with master branch from Apr 6 (reported version 3.5.0.0). Ubuntu 16.04, The cabal binary compiled with GHC 8,8.3, but newest versions of compatible packages. Auto-generated ~/.cabal/config except for that extra line. 

No recent commit description mentions this issue number nor 'allow-newer'.

**Comment by RyanGlScott** [comment]
Ah, good catch! I am unable to reproduce this with `cabal-install` `master` either (at commit 5771a24149a3027144ef18f62a42b9a1a5c29c4c). I also wonder what commit fixed this, but perhaps it's not worth the time effort to bisect this.

At this point, can this issue be closed? Or should a regression test be added first?

**Comment by gbaz** [comment]
let's close?
