### ISSUE TITLE
Bootstrap Instructions on macOS

### ISSUE THREAD

**Issue by essandess** [haskell/cabal#7292]
How does one bootstrap `cabal` 3.4.0.0 on macOS? I am trying to update the MacPorts [cabal](https://github.com/macports/macports-ports/blob/master/lang/cabal/Portfile) port.

Cabal's `README.md` file says:
> ```
> As a convenience for users on Unix-like systems, there is a
> [bootstrap.sh] script that will download and install each of
> `cabal-install`'s dependencies in turn.
> 
>     $ ./bootstrap.sh
> ```

This used to work on previous versions. But this `bootstrap.sh` script is missing in v3.4.0.0.

**Comment by fgaz** [comment]
There is a bootstrap directory in this repository

**Comment by essandess** [comment]
> There is a bootstrap directory in this repository 

I do not see any macOS-specific instructions or `.json`’s in the bootstrap directory; [bootstrap/README.md](https://github.com/haskell/cabal/blob/master/bootstrap/README.md):

> On a (linux) system you are boostrapping, run
>
> >   `bootstrap.py -d linux-ghcver.json -w /path/to-ghc`

How does one bootstrap on macOS?

**Comment by fgaz** [comment]
The next line says:

> To generate the platform-ghcver files for other platforms, do: [...]

**Comment by essandess** [comment]
Thanks! Got it working: https://github.com/macports/macports-ports/pull/10082

**Comment by essandess** [comment]
Also, note that `bootstrap.py` must be run from the top directory.

I'd suggest changing the first command in [bootstrap/README.md](https://github.com/haskell/cabal/blob/master/bootstrap/README.md) to:
 

```
bootstrap/bootstrap.py -d bootstrap/platform-ghcver.json -w /path/to-ghc
```
