### ISSUE TITLE
Allow specifying private C libs to avoid overlinking (but allow static linking)

### ISSUE THREAD

**Issue by bos** [haskell/cabal#730]
(Imported from [Trac #740](http://hackage.haskell.org/trac/hackage/ticket/740), reported by @dcoutts on 2010-09-20)

See [http://wiki.mandriva.com/en/Overlinking](http://wiki.mandriva.com/en/Overlinking) for a discussion of under and overlinking.

In different circumstances, we want both to be able to link to C libs statically and dynamically. For the dynamic case we only want to specify direct C lib dependencies or we end up overlinking. For the static case we must specify all direct and indirect C libs or we will miss libs and get missing symbols.

A sensible solution is to follow [pkg-config](http://people.freedesktop.org/~dbn/pkg-config-guide.html) and specify "private" C libs separately from normal public ones. This would require extensions both to .cabal files and package registration files.

**Comment by BardurArantsson** [comment]
@dcoutts Do you happen to know if this is still a pressing issue? Is it affecting any "real users"? Should it be closed or kept open?

**Comment by jneira** [comment]
as there is no confirmation after 7 years i think we could close this one
