### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by squirlbrain** [haskell/cabal#7307]
I am currently trying to set up a cardano node. But run into this issue trying to install cabal 3.2.0.0x86_64
The issue is exactly as the title suggests. I have tried clean iterations of both ubuntu desktop 20.10 and ubuntu 20.04.02 server LTS "both 64 bit". How ever I always run into the same error after the following string of commands.

Error - cannot execute binary file: Exec format error
```
cd
wget https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0-x86_64-unknown-linux.tar.xz
tar -xf cabal-install-3.2.0.0-x86_64-unknown-linux.tar.xz
rm cabal-install-3.2.0.0-x86_64-unknown-linux.tar.xz cabal.sig
mkdir -p $HOME/.local/bin
mv cabal $HOME/.local/bin/
cabal update
cabal -V
```
```
pretty sure im using cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

I expected so be able to update cabal and check its version to ensure it was installed correctly

**System information**
 - ubuntu desktop 20.10/ubuntu 20.04.02 server LTS "64 bit"
 - raspberry pi 4 
      -- 4 core
      -- 4 gb ram
      --  36 gb sd card
 - `cabal 3.2.0.0
 - ghc 8.10.2

Additionally, i have tried the following commands to meet the same issue
```
cabal install cabal-install
sudo apt cabal install
"and various other commands to try and install the binary."
```
I cant seem to find any forums or information on FAQ sites about this. With the exception that the executable may be for an operating system bit size not native to the one im using. "i have already verified that it should be compatible".

 So any insight would be greatly appreciated. Thank you in advance.

**Comment by fgaz** [comment]
While the raspberry pi does have a 64 bit architecture, it's an ARM one, not a x86 one. I see there are no ARM binary distributions for cabal in the Haskell web site, so you'll have to build your own. If your distribution provides an older cabal in its repositories you can upgrade it by running `cabal update`, `cabal install cabal-install`, and `cabal user-config update`

**Comment by phadej** [comment]
There is aarch64 build (for ubuntu-18.06, it could work on 20.06 too) at https://downloads.haskell.org/cabal/cabal-install-3.4.0.0/

Download page is outdated, as it still speaks about 3.2...

**Comment by squirlbrain** [comment]
Thank you guys. What fgaz said would explain why I'm getting format errors. So ill just go with what phadej suggested and use the aarch 64 build for this project. So far, that build is installed correctly and is responding in a positive way. hopefully its not an issue that this iteration is a little new than the one suggested by the guide.

**Comment by 34r7h** [comment]
Same on ubuntu 20 fwiw "-bash: /home/i_34r7h/.local/bin/cabal: cannot execute binary file: Exec format error"

**Comment by Lazydayz137** [comment]
After trying multiple options, including adding a repository with the 20.04 build, fgaz has the best solution imo.  Thank you!

**Comment by ulysses4ever** [comment]
We supply arm64 binaries with every release lately, so I'm closing this. Feel free to open a new ticket if anything looks amiss.
