### ISSUE TITLE
Release planning for GHC 9.2 cycle (cabal 3.6)

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7312]
It is typical for Cabal major releases to coincide with GHC major releases. This ticket is intended to facilitate coordination on the scoping and eventually cutting of a `Cabal-3.6` branch.

What major patches should be merged before this happens?

**Comment by emilypi** [comment]
Just looking at the changelog, it looks like we'll need to support new extensions and flags/warnings:

- Support DuplicateRecordFields with PatternSynonyms (!4467, @adamgundry)

- -Wambiguous-fields (!4770, @adamgundry)

- NoFieldSelectors extension (!4743, @adamgundry)

- RecordDotSyntax (!4532, @shayne-fletcher-da)

- GHC2021 (!4853, @nomeata)

- -finfo-table-map and -fdistinct-constructor-tables (!3469, @mpickering)

- UnliftedDataTypes (!2218, @sgraf812)
