### ISSUE TITLE
fdLock: invalid argument on i386 linux cabal 3.4.0.0 via ghcup

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#7313]
I'm seeing the dreaded `fdLock: invalid argument`.

**To Reproduce**

```
$ ~/.ghcup/bin/cabal-3.4.0.0 v2-update
Downloading the latest package list from hackage.haskell.org
fdLock: invalid argument (Invalid argument)
```

(I got my `cabal-3.4.0.0` via `./i386-linux-ghcup install cabal 3.4.0.0`.)

Anyone else seeing this?

**Comment by tomjaguarpaw** [comment]
I can confirm that this problem also occurs on `cabal-3.4.0.0` built from source.

**Comment by phadej** [comment]
What's your
- kernel version
- glibc version

**Comment by tomjaguarpaw** [comment]
```
% uname -a
Linux henry 4.19.0-13-686 #1 SMP Debian 4.19.160-2 (2020-11-28) i686 GNU/Linux
% dpkg -l libc6
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libc6:i386     2.29-3       i386         GNU C Library: Shared libraries
```

**Comment by tomjaguarpaw** [comment]
I believe it is a duplicate! Should we close this issue then?

**Comment by phadej** [comment]
Yes, I'd say this is `lukko` issue (15). I have no plans to work on it though (I have no machines to test).

**Comment by tomjaguarpaw** [comment]
I can confirm that it works if I compile with

```
cabal-3.2.0.0 v2-install cabal-install-3.4.0.0 --constraint 'lukko -ofd-locking' ...
```

Perhaps the bindist should be updated to fix this.

**Comment by hasufell** [comment]
ghcup now uses an updated bindist: https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/7e0f839ff8f91cb7cfc78eaa57782bc1af30dc4b

https://downloads.haskell.org/~ghcup/unofficial-bindists/cabal/3.4.0.0/cabal-install-3.4.0.0-i386-unknown-linux.tar.xz
