### ISSUE TITLE
GHC 9.0 CI jobs

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#7315]
I'm a bit confused about how this is done. I guess by modifying ~~the files in `templates`~~ `cabal-dev-scripts/src/GenValidate.hs` and running `make github-actions`... ~~but those files say that they are generated too. Maybe it's like in `cabal-install.cabal.zinza`: the warning is there, but only because it has to go in the generated files somehow.~~

We probably want to document all this

/cc @emilypi

**Comment by Mikolaj** [comment]
While we are at it, we can also remove the hack at

https://github.com/haskell/cabal/blob/3c4023f52cd582199c220eae7a0fd55d50ea7a73/cabal.project#L23-L24

to avoid publishing something depending on allow-newer.

l will bump base bounds of hackage-security as needed.

**Comment by andreabedini** [comment]
@fgaz @Mikolaj is this still relevant?

**Comment by Mikolaj** [comment]
Good find. Not having any `allow-newer` in CI is relevant, but that's it. Closing.
