### ISSUE TITLE
cabal-install needs a populated $HOME/.cabal dir to do nix-style builds

### ISSUE THREAD

**Issue by arrowd** [haskell/cabal#7321]
I'm using `cabal-install` as a build tool to produce FreeBSD packages from Haskell ones. The process boils down to pretty simple steps:

1. Given a `foo-1.2.3` Haskell program I fetch its source tarball from the Hackage. I do the same for all its dependencies and take into account package revisions. I'm actually using `fetch` utility for this, not `cabal get`.
2. I extract `foo-1.2.3.tar.gz` into `workdir/` and all its dependencies into `workdir/foo-1.2.3`.
3. I run `mkdir $HOME/.cabal && touch $HOME/.cabal/config` to create an empty config file. There are no other files in `$HOME/.cabal/`.
4. I run `cd workdir/foo-1.2.3 && cabal v2-build` and it works.

The problem is that these steps don't work anymore with `cabal-install-3.4`:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghc-events-0.15.1 (user goal)
[__1] unknown package: vector (dependency of ghc-events)
[__1] fail (backjumping, conflict set: ghc-events, vector)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghc-events, vector
```

After playing with it a bit it turned out that it does work if `$HOME/.cabal` is populated properly - that is, it contains various cache files for Hackage repository. Removing them causes configuration to fail.

The need to obtain 600Mb cache each time we build some Haskell package is unacceptable by FreeBSD package cluster, so I need to get this feature back. It should be possible to build a package without cache, if user have organized sources in the proper way.

I'm ready to commit my time to this, but I'll need guidance in this case. I tried looking up Cabal sources, but got overwhelmed by unexpectedly large code base. Otherwise, some sensible workaround would also be welcome.

**Comment by fgaz** [comment]
in `workdir/foo-1.2.3` create a `cabal.project` file with the following contents (adjusting them to your dependencies):

```
packages:
  .
  dependency1-0.1.0.0
  dependency2-0.1.0.0
```

**Comment by fgaz** [comment]
Alternatively you could also create a file+noindex repo with all your tarballs and point cabal to that.

Also be aware that `cabal fetch` does not save revision data in `~/.cabal/packages/<repo>/<pkg>/<version>/<pkg>-<version>.tar.gz/<pkg>.cabal`. Those tarballs are pristine. The revision data is saved in the `01-index.tar` instead, and it is extracted at configuration/build time. If you want to have a package with up-to-date metadata you _have_ to use `cabal get`.

**Comment by arrowd** [comment]
> did cabal-install-3.2 work without that file?

Yes. Moreover, for some packages (like `pandoc`) I actually had to delete it, as it was getting in the way.

> Alternatively you could also create a file+noindex repo with all your tarballs and point cabal to that.

Can you please elaborate on that? What files exactly should I create and where do I put tarballs?

**Comment by fgaz** [comment]
> > Alternatively you could also create a file+noindex repo with all your tarballs and point cabal to that.
> 
> Can you please elaborate on that? What files exactly should I create and where do I put tarballs?


https://cabal.readthedocs.io/en/3.4/installing-packages.html#local-no-index-repositories

**Comment by arrowd** [comment]
> in workdir/foo-1.2.3 create a cabal.project file with the following contents (adjusting them to your dependencies):

This seems to be a good workaround. I'll try to apply it to all the packages we currently have in FreeBSD ports tree and then report back.

**Comment by arrowd** [comment]
Okay, the `cabal.project` trick turned out to be an easy workaround. Thanks for pointing this out!

**Comment by fgaz** [comment]
By the way, could you share a link to your work? I'm doing something similar for nix, and I'd like to see other implementations

**Comment by arrowd** [comment]
These are the changes I had to apply: https://github.com/freebsd/freebsd-ports/commit/662d97fa641b16d4a4e48698f565c06bc7e7505f

Here is the simple Haskell port: https://github.com/freebsd/freebsd-ports/blob/master/devel/hs-ghc-events/Makefile
And the machinery it uses behind scenes: https://github.com/freebsd/freebsd-ports/blob/master/Mk/Uses/cabal.mk See `cabal-post-extract`, `cabal-post-patch`, `do-build` and `do-install` targets.

The official documentation on creating Haskell ports: https://docs.freebsd.org/en/books/porters-handbook/index.html#using-cabal
