### ISSUE TITLE
bootstrap 3.4.0.0 - how to build dependency description files (platform-ghcver.json)

### ISSUE THREAD

**Issue by ciez** [haskell/cabal#7333]
#### Problem 
The intention is for cabal-install 3.4.0.0 to be bootstrapped with bootstrap/bootstrap.py, using GHC-8.10.4

I am trying to follow the steps to Build a dependency description file as described in [cabal/bootstrap/README.md](https://github.com/haskell/cabal/blob/master/bootstrap/README.md)

There are 2 versions of GHC installed: 8.6.5 and 8.10.4
1 version of cabal-install: 2.4.1.0 is installed, too

Attempts to run the script from [cabal/bootstrap/README.md](https://github.com/haskell/cabal/blob/master/bootstrap/README.md)
 in cloned cabal-install-3.4.0.0 git repo root fail

#### Questions
a) Can the dependency description files for cabal-install-3.4.0.0 and GHC 8.10.4 be built with this setup? 
or 
b) can the dependency description files for cabal-install-3.4.0.0 and GHC 8.10.4 be built only with cabal-install-3.4.0.0 (and GHC-8.10.4) already installed on the pc?

**Comment by fgaz** [comment]
a) should work too

**Comment by ciez** [comment]
Cheers @fgaz 

is _ghc_ in  `--with-compiler=/path/to/ghc `
-- 8.6.5 (which cabal-install-2.4.1.0 is compatible with)
or
-- 8.10.4 (the _ghcver_ for which the dependency description file is generated)?

**Comment by ciez** [comment]
to build the dependency description files for the cabal-install 3.4.0.0 compatible with GHC-8.10.4, needed to build cabal-install-3.4.0.0 with cabal-install-2.4.1.0

passed the `--with-compiler=/path/to/ghc-8.10.4` flag
