### ISSUE TITLE
cabal sdist ignores extra-source-files after source-repository ?

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#7334]
when `my.cabal` contains an `extra-source-files` section that comes after `source-repository`, it gets silently ignored (the files are not in the tarball).

My test case is  https://github.com/jwaldmann/haskell-tpdb/commit/380076e62f2a3a0ea754b4eef27e1d6f34462a18

and it can be reproduced in an empty project:
* `mkdir extra-source && pushd extra-source && cabal init`
* add `source-repository` section before or after `extra-source-files: CHANGELOG.md`
* `cabal sdist`
* `tar tfa dist-newstyle/sdist/extra-source-0.1.0.0.tar.gz | grep CHANGELOG`

```
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
```

**Comment by fgaz** [comment]
https://cabal.readthedocs.io/en/latest/cabal-package.html#package-properties

> These fields may occur in the first top-level properties section

```
> cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: tmp-e6dWONThmP.cabal:35:1: Ignoring trailing fields after sections:
"extra-source-files"
```
