### ISSUE TITLE
Default .cabal/config Configuration File Uses Insecure HTTP

### ISSUE THREAD

**Issue by essandess** [haskell/cabal#7345]
The default `cabal` configuration file `.cabal/config` created when this file does not exist apparently configures `cabal` To download and compile hackage code through insecure HTTP:

>  `.cabal/config`
```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: True
```

If so, this is a security issue that should be address by changing the default configuration settings to:
```
repository hackage.haskell.org
  url: https://hackage.haskell.org/
  secure: True
```

**Comment by phadej** [comment]
- `secure: True` is hardcoded for `hackage.haskell.org`
- HTTP doesn't really add security not provided by `hackage-security` already, but requires `cabal-install` to use external methods to fetch packages, which availability is not guaranteed.

You would need to teach `cabal-install` to do TLS by itself. I think all currently available Haskell options aren't good enough.
