### ISSUE TITLE
cabal-install sometimes gives empty build-log and no build-summary

### ISSUE THREAD

**Issue by bos** [haskell/cabal#735]
(Imported from [Trac #745](http://hackage.haskell.org/trac/hackage/ticket/745), reported by @igloo on 2010-10-04)

Building <tt>NaturalSort-0.2.1</tt> with GHC 7.0.1 RC 1:

<pre class="wiki">$ cabal install --build-summary=log.bs --build-log=log.bl
Resolving dependencies...
Warning: NaturalSort.cabal: This package requires Cabal version: &gt;=1.6 &amp;&amp; &lt;1.9
cabal: Error: some packages failed to install:
NaturalSort-0.2.1 failed during the configure step. The exception was:
user error (The package requires Cabal library version -any &amp;&amp; &gt;=1.6 &amp;&amp; &lt;1.9
but no suitable version is installed.)
$ cat log.bs
cat: log.bs: No such file or directory
$ cat log.bl
$
</pre>I would like the build log to contain the error.

I have

<pre class="wiki">$ cabal --version
cabal-install version 0.9.2
using version 1.9.2 of the Cabal library
</pre>but this is not a released version; if nothing else, I have the #697 patch applied.

**Comment by BardurArantsson** [comment]
Thanks @manzyuk for trying to reproduce!

Conclusion: (Not reproducible) && (Reported 2010) => Close!
