### ISSUE TITLE
symlinks in sdists

### ISSUE THREAD

**Issue by bos** [haskell/cabal#737]
(Imported from [Trac #747](http://hackage.haskell.org/trac/hackage/ticket/747), reported by @igfoo on 2010-10-12)

Should hackage reject tarballs that contain symlinks? Or broken symlinks?

I just ran across a broken symlink in ipprint 0.4:

<pre class="wiki">ipprint-0.4/.#ipprint.cabal -&gt; gleb@gleb.kiev.zoral.com.ua.3270:1271836339
</pre>

**Comment by ttuegel** [comment]
This is a Hackage issue.
