### ISSUE TITLE
cabal.project compiler field seems to be ineffective

### ISSUE THREAD

**Issue by yobson** [haskell/cabal#7370]
**Describe the bug**
I am trying to build a project with a few packages compiled by GHCJS (v8.6) and a set with GHC (8.10)
and some libraries used by both.

I set the `compiler` field to `ghc` and `ghcjs` respectively in my `cabal.project` file in individual package sections and yet it uses `ghc` for all of them!

**To Reproduce**
[cabal-bug-report.zip](https://github.com/haskell/cabal/files/6372273/cabal-bug-report.zip)

I have attached a zip of a minimal example. `project1` is set to compile with `ghc` and `project2` with `ghcjs`
Simply run

```
$ cabal v2-build all
```
or
```
$ cabal v2-build project1
$ cabal v2-build project2
```

**Expected behavior**
To build `project1` with `ghc` and to build `project2` with `ghcjs`

**System information**
 - Operating system: Mac os Big Sur
 - `cabal 3.4`, `ghc 8.10.4`, `ghcjs 8.6.1`

**Comment by fgaz** [comment]
It looks like the field does work when set at the top level. It probably was never intended to be used in individual packages, like with the similar `with-compiler` option:

> At the moment, it’s not possible to set with-compiler on a per-package basis, but eventually we plan on relaxing this restriction. If this is something you need, give us a shout.

So I'd say this is not a bug. Pull requests to fix the documentation and/or make compiler/with-compiler work for individual packages are welcome though!

**Comment by yobson** [comment]
Thanks for the response!
I may take you up on that pull request! Docs probably. Cabal is massive and I feel my haskell abilities are still young!

My workaround was just adding
```
if impl(ghcjs)
    buildable: False/True
```
tastefully to various cabal files and then running
```
$ cabal build all
$ cabal build all --ghcjs
```
Is your two separate project files solution more elegant?

**Comment by fgaz** [comment]
> Is your two separate project files solution more elegant?

Nah, both are fine :)
