### ISSUE TITLE
MacOS 10.15, fink, cabal install cabal-install fails

### ISSUE THREAD

**Issue by ouboub** [haskell/cabal#7376]
Hi

after installing fink, I installed cabal
cabal-install    1.22.6.0-1
hgc   7.10.3-2 

I run 
cabal install cabal-install 
but obtain
cabal: Error: some packages failed to install:
Cabal-3.0.2.0 failed during the configure step. The exception was:
user error ('/opt/sw/bin/ghc' exited with an error:

/var/folders/j1/7bbsk0jj6nxd5yxndqwvb1t00000gn/T/cabal-tmp-29800/Cabal-3.0.2.0/Distribution/Parsec.hs:134:7:
error: function-like macro 'MIN_VERSION_base' is not defined
#if !(MIN_VERSION_base(4,13,0))
^
1 error generated.
)
cabal-install-3.0.0.0 depends on Cabal-3.0.2.0 which failed to install.
hackage-security-0.5.3.0 depends on Cabal-3.0.2.0 which failed to install.

I tried to set 
allow-newer: True
but it did not make any difference.
Any idea how to proceed?
thanks
Uwe Brauer

**Comment by Mikolaj** [comment]
Hi! The GHC 7.10 compiler is quite outdated. In particular, I guess the new cabal version you tried to install requires a much newer GHC compiler (and you can't install a new compiler with cabal, so there is no way to bootstrap using intermediated versions). I'd recommend to install a newer GHC.

**Comment by ouboub** [comment]
ok, thanks 
this I cannot do using fink, can you give me a pointer how to install that in Mac Os.

**Comment by Mikolaj** [comment]
I have no idea about fink and about Mac OS. Don't any methods from https://www.haskell.org/downloads work? If not, perhas ask on various haskell-beginners forums?
