### ISSUE TITLE
Some commands ignore --dry-run and --only-download

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#7379]
Follow-up to #7351, in which v1-install failed outright.

Apparently some commands completely ignore --dry-run (and now --only-download), and just perform the task. Ideally they should tell what would happen (eg. `the executable "xyz" would be run`), but just not doing the thing would be ok too.

Commands that behave incorrectly:

* v2-configure (creates the project file)
* v2-freeze (creates the freeze file)
* v2-run (runs the executable)
* v2-exec (runs the command)

Commands that behave correctly:

* v2-repl
* v2-build
* v2-install
* v2-haddock
* v2-test
* v2-bench (probably. I didn't check)

**Comment by aaronallen8455** [comment]
I can work on this issue.

**Comment by fgaz** [comment]
That's great!

Those commands are all implemented in `cabal-install/src/Distribution/Client/Cmd*.hs` and they have similar structure. Feel free to ask here or on IRC if you get stuck or need pointers.

**Comment by aaronallen8455** [comment]
Thanks, will do! I have opened https://github.com/haskell/cabal/pull/7407 for this issue.
