### ISSUE TITLE
Don't use sdist in cabal v2-install

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7383]
**Describe the bug**
Currently `cabal v2-install` relies on `sdist` to create a hashable artifact. Not only is this slow but it can fail (e.g. if `cabal check` fails). We should find a better way to generate hashes.

**Comment by athas** [comment]
I very much agree with this.  Is there a workaround that replicates the behaviour of `stack install` (i.e. do an incremental build and then copy the binary somewhere sensible)?

**Comment by phadej** [comment]
cabal build yourprogram && cp $(cabal list-bin yourprogram) /somewhere/sensible
    
That however doesn't work if your program uses data-files, as `Paths_*` are pointing somewhere and aren't copied.

**Comment by athas** [comment]
Fine by me!

**Comment by sergv** [comment]
This issue seems to be a duplicate of https://github.com/haskell/cabal/issues/6919. The thread includes some motivation on why the `sdist` step might be useful at https://github.com/haskell/cabal/issues/6919#issuecomment-646207715.

**Comment by Mikolaj** [comment]
Well spotted. Let's move the discussion there. Closing.
