### ISSUE TITLE
`cabal outdated --v2-freeze-file` forgets all dependencies if no freeze file has been created 

### ISSUE THREAD

**Issue by fendor** [haskell/cabal#7406]
**Describe the bug**
If no `cabal.project.freeze` exists but `cabal outdated --v2-freeze-file` is executed, cabal claims everything is in perfect shape!

**To Reproduce**

```
$ cabal init --lib
```

with .cabal file:
```
cabal-version:      2.4
name:               cabal-outdated-major
version:            0.1.0.0
author:             Fendor
maintainer:         power.walross@gmail.com

library
    exposed-modules:  MyLib
    build-depends:    base ^>=4.14.1.0, binary < 0.6
    hs-source-dirs:   src
    default-language: Haskell2010
```

`binary` is clearly outdated but the output is:
```
$ cabal outdated --v2-freeze-file
All dependencies are up to date.
```

**Expected behavior**
Cabal should complain about binary version:
```
$ cabal outdated --v2-freeze-file
Outdated dependencies:
base >=4.14.1.0 && <4.15 (latest: 4.15.0.0)
binary <0.6 (latest: 0.10.0.0)
```

or abort the execution as it can't do what it is being asked for.

**System information**
 - `cabal 3.4`, `ghc 8.10.2` versions installed via ghcup

**Comment by fgaz** [comment]
I'd go with

> or abort the execution as it can't do what it is being asked for.
