### ISSUE TITLE
Support out-of-source build

### ISSUE THREAD

**Issue by phma** [haskell/cabal#7415]
I've been building C++ projects with CMake for many years and am now learning Haskell and starting my first Haskell project that reads a data file. CMake supports out-of-source builds, which keep data files, output files, and build artifacts from cluttering the repository. I'd like to use the same directory structure in Haskell.

I suggest adding a file `.sourcedir` in the build directory. When Cabal finds this file in `~/build/foo` which says that the source is in `~/src/foo`, and you run e.g. `cabal new-build`, it reads the source files from `~/src/foo`, compiles them, and puts the binary in `~/build/foo`. You can then run `./foo` in the build directory.

It would also be good if GHCi supported such a file. (C++ doesn't have a REPL, so it's irrelevant there.) If you run `:load foo` in a directory which has a `.sourcedir` file, it would look for `foo.hs` in the source directory.

**Comment by phadej** [comment]
I don't understand what you mean by the out of source builds. `cabal-install` keeps build artifacts in `dist-newstyle`, and `cabal.project` can reference outside the root directory too.

**Comment by phma** [comment]
`dist-newstyle` is inside the source directory. I'm asking for the build directory to be outside the source directory.

The location of a developer's data files (for PerfectTIN, these are point clouds I run the program on) cannot be put in a file in the repository, because each developer may have them in a different location, and may have different data files.

My workflow is like this for C++ projects:
```
~/src/foo$ kate -n *.cpp *.h *.txt &
...type some code
```
```
~/build/foo/cdbg$ ninja
[1]Building foo.cpp ...
~/build/foo/cdbg$ foo bar.dat
```
The file `~/build/foo/cdbg/CMakeCache.txt` has a line telling where the source code is. (`cdbg` is one of the build types, a debuggable binary built with Clang. It's the build I use most of the time.)

Is `cabal.project` in the source directory or the build directory? How does it reference outside the root directory?

**Comment by Mikolaj** [comment]
hi! `cabal.project` is in the build directory. It uses paths, including relative paths, to specify source directory locations.

**Comment by phma** [comment]
I'm looking at https://cabal.readthedocs.io/en/3.4/cabal-project.html, and I don't see it. The closest thing I see is `source-repository-package`, but the locations in both examples are https URLs, not directories. What would I put to tell it that the source is in a local directory?

**Comment by Mikolaj** [comment]
`packages: ../foo ../faraway/bar /root/secret/baz`

**Comment by Mikolaj** [comment]
To be precise, you are telling it that *packages* are in local directories. Each package needs a `packageName.cabal` file, etc., as usual. You can have many package per repo, many packages per `cabal.project`, but one directory with `packageName.cabal` per package. I hope I didn't mix it up.

**Comment by phma** [comment]
I wrote a file `~/build/adjblockmovie/cabal.project` with the contents
```
packages: ~/src/adjblockmovie
```
and tried to build it. I got this result:
```
phma@puma:~/build/adjblockmovie$ cabal new-build
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```

**Comment by Mikolaj** [comment]
Well, what happens when you type 'cabal build all'? Sometimes I also use `cabal build .`, but I forgot when.

**Comment by phadej** [comment]
`cabal-install` doesn't expand `~` in paths. (it could, but it doesn't). I.e. don't try `--builddir=~/foo` either, as shell won't expand it in the middle either.
