### ISSUE TITLE
Ability to install dependencies for a for `project.cabal` without source files modules (v2-install --only-dependencies)

### ISSUE THREAD

**Issue by aringeri** [haskell/cabal#7416]
**Describe the bug**
I am looking for a way to use cabal to install all the dependencies of a project without having the source files present. My use case is specific to building haskell projects in docker. By being able to install dependencies without the source files, I can take advantage of docker layer caching. This will allow me to avoid re-install dependencies on every build, and only re-install the dependencies when the `project.cabal` file changes.  

The issue I'm running in to is that `cabal v2-install --only-dependencies` fails when the source files for `exposed-modules` or `other-modules` are not present in the working directory. 

It gives me an error:
```
cabal: Error: Could not find module: My.Public.Module with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

Is there way to ignore this error/validation? It doesn't seem to matter whether the module is valid haskell (v2-install works with an empty file `touch src/My/Public/Module.hs`).

**To Reproduce**

I've created a new project with the directory structure:
```
docker-haskell-example/
├─ src/
│  ├─ My/
│  │  ├─ Public/
│  │  │  ├─ Module.hs
│  │  ├─ Private/
│  │  │  ├─ Module.hs
├─ Dockerfile
├─ docker-haskell-example.cabal

```

docker-haskell-example.cabal:
```
cabal-version: 2.4
name:          docker-haskell-example
version:       0

library lib
  exposed-modules:     My.Public.Module
  other-modules:       My.Private.Module
  ghc-options:        -Wall
                      -ddump-splices
  build-depends:       base ^>=4.14.1
                     , time
                     , bytestring
  hs-source-dirs:      src
  default-language:    Haskell2010
```

Dockerfile:
```
FROM haskell:8.10.4

COPY docker-haskell-example.cabal ./

RUN cabal v2-install --only-dependencies --lib

COPY src ./src

RUN cabal v2-build
```

Run the following command from the `docker-haskell-example` directory.
```docker build .```

**Expected behavior**
I would expect the `cabal v2-install --only-dependencies --lib` step to not fail and install the dependent libraries.

**System information**
 - Operating system: mac, debian in docker
 - `cabal` versions 3.0.0.0 and 3.2.0.0, `ghc` versions 8.6.5 and 8.10.4

**Comment by phadej** [comment]
In https://oleg.fi/gists/posts/2019-07-04-docker-haskell-example.html I use `v2-build --only-dependencies`. Does it work for you. `v2-install` cannot as it sdists the packages etc. 

`v2-install` probably could fall back to `v2-build` mode when `--only-dependencies` is specified though.

**Comment by aringeri** [comment]
Ah yes, I was referring to that blog but seem to have mixed up `v2-install` with `v2-build`. `v2-build --only-dependencies` works for me as expected.

**Comment by aringeri** [comment]
Thanks for your help @phadej
