### ISSUE TITLE
`cabal check` warns about `-O2` even if it is just a flag

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7423]
I have a `.cabal`-file that passes `ghc-options: -O2` under a specific flag:
https://raw.githubusercontent.com/haskell-hvr/regex-tdfa/master/regex-tdfa.cabal

`cabal check` issues a warning.
```
$ cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: 'ghc-options: -O2' is rarely needed. Check that it is giving a real
benefit and not just imposing longer compile times on your users.
```

I think the warning should not be issued if `-O2` is only passed to ghc under a flag.

**Comment by Mikolaj** [comment]
Agreed. No idea if that's a trivial omission for `-O2` or if the checks don't understand flags and conditions in general.

**Comment by andreasabel** [comment]
The check for `-O2` is implemented here:
https://github.com/haskell/cabal/blob/8063cd8dbbd42e20d8a7eecda8ac153226ef4547/Cabal/src/Distribution/PackageDescription/Check.hs#L824-L828
https://github.com/haskell/cabal/blob/8063cd8dbbd42e20d8a7eecda8ac153226ef4547/Cabal/src/Distribution/PackageDescription/Check.hs#L918-L919
https://github.com/haskell/cabal/blob/8063cd8dbbd42e20d8a7eecda8ac153226ef4547/Cabal/src/Distribution/PackageDescription/Check.hs#L904
So this test is rather naive, just checking whether `-O2` appears in any `ghc-options` field anywhere in the package description.
It has not been refined in a long time (at least for 14 years), see: https://github.com/haskell/cabal/blame/f1a833b16e3fddcd2998e3351efe8565158239a2/Distribution/PackageDescription/Check.hs#L246
Maybe at the time of designing this check, the structure of the package description was much simpler?! (No conditionals?)

The current architecture does not seem to allow restricting checks to certain contexts.  The entrypoint for the check is here:
https://github.com/haskell/cabal/blob/8063cd8dbbd42e20d8a7eecda8ac153226ef4547/Cabal/src/Distribution/PackageDescription/Check.hs#L141-L160
`flattenPackageDescription` just pulls field values out of all conditionals, so we are left with a unstructured soup. No context is retained where a `ghc-options` field occurred, thus no refined treatment is possible. 

As someone with strong background in type checking and compilation, I couldn't disagree more with the architecture of this checker.  A checker is a traversal over the abstract syntax.  Full stop.  No previous mangling, no short cuts.  Just a plain traversal, keeping track of the relevant parts of the context.  Everything else asks for pain.

Concretely, that would mean a traversal of the `GenericPackageDescription`.  Any conditionals we step into would then be recorded in the context.  Other stuff might be needed in the context, e.g., which section we are in, relevant info about the package etc.
