### ISSUE TITLE
isGoodRelativeFilePath rejects single-character top-level directories

### ISSUE THREAD

**Issue by ag-eitilt** [haskell/cabal#7426]
I had previously been storing my C source files in a directory called `c` alongside my `.cabal` file.  When I tried to upload the package to Hackage, I got a weird error about a "same directory segment: .." in the path `c/cdio/compat/cdtext.c`; I believe I have narrowed it down to [this line](https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/Cabal/src/Distribution/PackageDescription/Check.hs#L2197), which I think should be switching to `state5` instead of `state3` (note also that the message `state3` is giving on line 2216 has an extra dot); as it is, a directory consisting of a single letter fails if and only if it's at the very beginning of a relative path.  Was this deliberate, whether for OS/tooling compatibility or for reserving names (e.g. the dist-newstyle `x/` prefix for executable targets)?  If so, the error message should probably be edited, which might involve creating a new `state6`; if not, then it should be pointed to the right place.

**Comment by Mikolaj** [comment]
I think you are right. Would you like to create a PR so that we can ask for a review to get another pairs of eyes?
