### ISSUE TITLE
--allow-newer/older is documented as a Cabal option, but it's a cabal-install one

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#7444]
The docs say `--allow-newer` is a `Cabal` flag

https://cabal.readthedocs.io/en/3.4/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-allow-newer

but the flag is in `ConfigExFlags`, which is in `cabal-install`, so that part of the docs needs moving

Relatedly, we may want to move that option to Cabal, as it'd be useful for distributions. EDIT: #7445

**Comment by maralorn** [comment]
Having this in Setup.hs would be great!

**Comment by fgaz** [comment]
I opened #7445 to keep track of the feature, so we can use this ticket only for the docs change

**Comment by ulysses4ever** [comment]
This has been fixed in #7861. 

As for getting it back to `Setup`, there's a long history, which I recap in #7445.
