### ISSUE TITLE
Manjaro linux - ghcup haskell toolchain - Pandoc installation fails with ghc 9.0.1, with ghc 8.5.10 works OK

### ISSUE THREAD

**Issue by Delanii** [haskell/cabal#7446]
**Describe the bug**

Pandoc installation with ghc 9.0.1 with these commands:

```
cabal install pandoc pandoc-crossref
```

Fails with this error output:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.14.0.2 (user goal)
[__1] trying: unicode-collation-0.1.3 (dependency of pandoc)
[__2] trying: template-haskell-2.17.0.0/installed-2.17.0.0 (dependency of
unicode-collation)
[__3] trying: skylighting-core-0.10.5.1 (dependency of pandoc)
[__4] trying: transformers-0.5.6.2/installed-0.5.6.2 (dependency of
skylighting-core)
[__5] trying: containers-0.6.4.1/installed-0.6.4.1 (dependency of pandoc)
[__6] trying: base-4.15.0.0/installed-4.15.0.0 (dependency of pandoc)
[__7] trying: pandoc-crossref-0.3.11.0 (user goal)
[__8] next goal: data-accessor-template (dependency of pandoc-crossref)
[__8] rejecting: data-accessor-template-0.2.1.16 (conflict:
template-haskell==2.17.0.0/installed-2.17.0.0, data-accessor-template =>
template-haskell>=2.11 && <2.17)
[__8] skipping: data-accessor-template-0.2.1.15,
data-accessor-template-0.2.1.14, data-accessor-template-0.2.1.13,
data-accessor-template-0.2.1.12, data-accessor-template-0.2.1.11,
data-accessor-template-0.2.1.10, data-accessor-template-0.2.1.9,
data-accessor-template-0.2.1.8, data-accessor-template-0.2.1.7,
data-accessor-template-0.2.1.6, data-accessor-template-0.2.1.5,
data-accessor-template-0.2.1.4, data-accessor-template-0.2.1.3,
data-accessor-template-0.2.1.2, data-accessor-template-0.2.1.1,
data-accessor-template-0.2.1, data-accessor-template-0.2,
data-accessor-template-0.1.4, data-accessor-template-0.1.3,
data-accessor-template-0.1.2, data-accessor-template-0.1.1 (has the same
characteristics that caused the previous version to fail: excludes
'template-haskell' version 2.17.0.0)
[__8] fail (backjumping, conflict set: data-accessor-template,
pandoc-crossref, template-haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, yaml, pandoc-crossref, base,
template-haskell, data-accessor-template, transformers, skylighting-core,
containers, unicode-collation
Try running with --minimize-conflict-set to improve the error message.
```

The same command but with ghc 8.10.5 install fully working pandoc executable and library.

**To Reproduce**

There are actually a lot. I am learning Haskell and working with cabal on Manjaro Linux (Arch derivative) after using pandoc as system package. Because system-installed Haskell libraries and cabal reportedly dont work well together I have moved to using `ghcup` for anything Haskell related. This lists all steps I have taken (some might be valid)

1. I removed pandoc, pandoc-crossref, ghc, ghc-static and cabal-install from system packages
2. I removed orphaned packages, mostly haskell libraries installed by Manjaro. I not sure whether I have still some installed. If that might be the cause, please let me know. As system package, I was having installed ghc 8.10.5, but searching packages with pacman gives me no haskell-* packages, as they are named in Manjaro/Arch
3. I installed ghcup from here: https://www.haskell.org/ghcup/
4. I installed cabal (and stack) with ghcup
5. I installed pandoc and pandoc-crossref with:

```
cabal install pandoc pandoc-crossref
```

all went OK, because ghcup seems to use ghc 8.10.5 as default for new installation

6. I noticed warning message from ghcup, that there is newer ghc version. I installed it with ghcup and set it as my new default
7. I deleteted `$HOME/.ghc` and `$HOME/.cabal` folders, since reportedly they cause issues after upgrading ghc or cabal
8. I ran `cabal update`
9. I repeated:

```
cabal install pandoc pandoc-crossref
```

(with active ghc v. 9.0.1) but it throws error I posted in the beginning. Please, let me know if this is incorrect cabal usage and if I should use the `v2-` prefixed commands. I am posting here explicitly what I wrote, contrary to the request in the bug report template: "Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity."

**Expected behavior**

Pandoc and Pandoc-crossref should install with cabal with both ghc versions used. Reportedly pandoc is tested to build succesfully with ghc 9.0.1.

**System information**
 - Manjaro Linux stable branch
 - recent ghcup (installed yesterday). `cabal v. 3.4.0.0`, `ghc 8.5.10` and `ghc 9.0.1`

**Comment by Mikolaj** [comment]
Hi @Delanii, 

You are doing great. It's just that pandoc is not yet updated to work with GHC 9.0.1 and the libraries it bundles. Actually GHC 9.0.1 is not yet as stable as GHC 8.10.5, so I think ghcup is to blame for suggesting it, if anybody. Also, the version dependency failures are not readable at all. Did you try the `--minimize-conflict-set`, as suggested? Perhaps the first line "cabal: Could not resolve dependencies" should read something like "cabal: Could not resolve dependencies (possibly a package has not been updated to work with a new version of another or with a new GHC compiler)"? Would that help?

**Comment by Delanii** [comment]
Oh, I should have done that sooner. With output of `--minimize-conflict-set` it appears that actually `pandoc-crossref` is the one incompatible wtih ghc 9.0.1 ; not pandoc itself.
Thank you very much for your guidance and advice about ghc 8.5.10 being probably better solution as of now. I look around pandoc-crossref whether this is known state of things.
I close this issue with this comment, because with finding the problem I take it as resolved on cabal side.

**Comment by Mikolaj** [comment]
You are welcome. Good luck!
