### ISSUE TITLE
Cardano Node : Error Message - no cabal.project file

### ISSUE THREAD

**Issue by kevlim3** [haskell/cabal#7447]
Hi, 

I am new to Linux and Cardano. 

I am trying to build and install the node and have been following step by step base on https://cardano-foundation.gitbook.io/stake-pool-course/stake-pool-guide/getting-started/install-node

But i hit the Error message below . How can i proceed ?

No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.

**Comment by Mikolaj** [comment]
Hi,

Didn't you miss the step `cd cardano-node`? What does `pwd` say?

**Comment by kevlim3** [comment]
Hi, you are right. i missed cd cardano-node. 

Now i am having issue with this command below. do i need to cd anywhere else? 

cp -p dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-node-<NEW VERSION>/x/cardano-node/build/cardano-node/cardano-node ~/.local/bin/

cp -p dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-cli-<NEW VERSION>/x/cardano-cli/build/cardano-cli/cardano-cli ~/.local/bin/

**Comment by Mikolaj** [comment]
Glad to hear that. No, inside cardano-node/ should be the right place. Check whether `ghc --version` matches the string in the path and generally troubleshoot a little and post here messages you are getting if the problems persist.
