### ISSUE TITLE
Make pkgconfig-depends usable

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7448]
**Describe the bug**
Cabal has for a long time supported discovering native library dependencies through `pkgconfig-depends`. This is extremely useful as:

 * it can be used by some distributions to transparently provide native dependencies to `cabal-install` (e.g. see [nix-pkgconfig](https://github.com/bgamari/nix-pkgconfig/blob/master/cabal.project.local))
 * it makes Cabal packages more robust against non-traditional packaging decisions
 * it eliminates the need for Cabal to guess whether the target platform has a particular library

However, due to the fact that `pkg-config` is not available by default on some platforms, libraries tend to either not use `pkgconfig-depends` (e.g. see [`regex-posix`](https://hackage.haskell.org/package/regex-posix)) or guard it behind a default-off flag (e.g. see [`zlib`](https://hackage.haskell.org/package/zlib)). This severely cripples the usefulness of the mechanism.

Even worse, the tendency for packages to assume library non-availability on Windows can blow up catastrophically in some cases. This was the case in [GHC #19945](https://gitlab.haskell.org/ghc/ghc/-/issues/19945) where an ABI mismatch triggered by the assumption that Windows environments do not offer a POSIX regex implementation caused an innocuous-looking program to segfault, requiring many hours of debugging.

**Proposed design**

Users avoid using `pkgconfig-depends` by default because it can cause builds to fail when `pkg-config` is not available. I suggest one of the following (roughly in order of decreasing desirability):

 * `cabal-install` learn to backtrack if a `pkg-config` probe fails due to the executable not being available
 * `cabal-install` implement support for setting/clearing the `pkgconfig` flag on its own depending upon whether the `pkg-config` executable is available, sanctioning the current flag-based convention
 * `cabal-install` assume that the `pkgconfig-depends` are available in the event that `pkg-config` is not available

**Comment by phadej** [comment]
There are related issues:
- https://github.com/haskell/cabal/issues/6771 (Allowing pkg-config to fail), mentions `has(pkg-config)` conditional|
- https://github.com/haskell/cabal/issues/5328 Extend the grammar/semantics of default: to support boolean expressions - with `has(pkg-config` would allow setting flags based on existence of pkg-config.

If these are implemented, then both first and second @bgamari suggestions will be possible.

**Comment by gbaz** [comment]
I think I can have a go at option 1. Would appreciate someone pointing me to the simplest possible package that uses pkgconfig-depends they can think of so I can use it as a test case :-)

(And ideally this would have a cabal file example of how to build it in the no pkg-config case too!)

**Comment by phadej** [comment]
About any, e.g. https://hackage.haskell.org/package/zlib-0.6.2.3/zlib.cabal has manual flag to select `pkg-config`, while on my system: 

```
% pkg-config --list-all|grep zlib
zlib                                zlib - zlib compression library
```

(I forgot to install `zlib1g-dev` in CI environments so many times, I remember that by heart). [`lzma`](https://hackage.haskell.org/package/lzmahttps://hackage.haskell.org/package/lzma) is another.

https://hackage.haskell.org/package/HsOpenSSL is more complicated, where you start to wish `pkg-config` told things to avoid:

```
    if os(darwin) && flag(homebrew-openssl)
        Include-Dirs: /usr/local/opt/openssl/include
        Extra-Lib-Dirs: /usr/local/opt/openssl/lib

    if os(darwin) && flag(macports-openssl)
        Include-Dirs: /opt/local/include
        Extra-Lib-Dirs: /opt/local/lib
```
