### ISSUE TITLE
high verbosity should make configure verbose as well ?

### ISSUE THREAD

**Issue by bos** [haskell/cabal#745]
(Imported from [Trac #755](http://hackage.haskell.org/trac/hackage/ticket/755), reported by simonmic on 2010-10-27)

Even with -v 3, configure scripts run at normal verbosity which is often not enough to debug the problem. AFAIK you have to unpack the package, install/configure again and inspect config.log. If possible it would be convenient to have -v2 or -v3 tell configure to print the full log on stdout.

**Comment by ttuegel** [comment]
Closing due to more than 5 years of inactivity.
