### ISSUE TITLE
Unclear and possibly incorrect documentation for "active-repositories:"

### ISSUE THREAD

**Issue by danidiaz** [haskell/cabal#7450]
I was trying to use [active-repositories:](https://cabal.readthedocs.io/en/3.4/cabal-project.html#cfg-field-active-repositories) in combination with a [local no-index repository](https://cabal.readthedocs.io/en/3.4/installing-packages.html?highlight=local%20no-index%20package%20repositories#local-no-index-repositories). I put a package called "aeson" in my local repository to check how the repositories are merged.

The documentation says:

    you can specify the order and the way active repositories are merged.

but it doesn't say _which_ is the order. First win, or first lose?

Furthermore, this bit isn't working for me:

    -- Force head.hackage to be the primary repository considered
    active-repositories: :rest, head.hackage

The comment says that head.hackage should have priority, but in my experiments that isn't the case, normal Hackage still wins.

Furthermore, I don't understand why `:override` exists. Shouldn't repository order be sufficient? Or perhaps repository order doesn't have any effect, and only `:override` counts?

**Comment by Mikolaj** [comment]
Does anybody have any idea how this is supposed to work? @fgaz? Authors of recent commits that touch the code in question?

If nobody offers help, solving this would require experiments, code-diving and then fixing the documentation, but only if the behaviour seems sane --- otherwise opening tickets with proposed fixes.

**Comment by fgaz** [comment]
Looks like first loses:

https://github.com/haskell/cabal/blob/f085beb184dbdeada53ef3817bfa62ecc9b88d1b/cabal-install-solver/src/Distribution/Solver/Types/PackageIndex.hs#L174-L177

Not sure about the difference between none/override/rest.

Better to ask @phadej who wrote that feature

**Comment by phadej** [comment]
different repositories can have different versions of package, e.g. repository A has `pkg-1 and pkg-2` and repository B has `pkg-2 and pkg-3`. Assume `active-repositories: A, B`.
- `merge` will make all three available, where `pkg-2` will be picked from repository `B`
- `override` will make only version available in the later ones, i.e. `2` and `3` in this example.
