### ISSUE TITLE
Unable to change Simpleview to Liveview

### ISSUE THREAD

**Issue by kevlim3** [haskell/cabal#7457]
Hi, 

I am running on Ubuntu Linux and on testnet. 

I am learning based on the video below
https://cardano-foundation.gitbook.io/stake-pool-course/lessons/lesson-1/config-files-run-node

However, i am unable to change Simpleview to Liveview after running nano shelley_testnet-confiq.jason

Kindly assist.

**Comment by Mikolaj** [comment]
Hi @kevlim3,

I sympathize. How can I help you in your plight?

**Comment by kevlim3** [comment]
Hi Mikolaj, 

Thank you so much. 

Is there a way to be able to get Liveview?

**Comment by Mikolaj** [comment]
I'm sure there is and if you help me reproduce a cabal defect that prevents Liveview from happening, I will try to help. A small cabal invocation example with all the details listed one by one, in textual form, in steps, would me much appreciated. Actually, please edit your main ticket description to contain one. I think there was a template that helped with that you must have ignored it.

**Comment by noughtmare** [comment]
@kevlim3 I think this is just the wrong place to report your problem. That cardano gitbook has a page [Questions, feedback & help](https://cardano-foundation.gitbook.io/stake-pool-course/about-the-stake-pool-initiative/questions-feedback-and-help) that lists [this forum](https://forum.cardano.org/c/staking-delegation/operators-talk/119) as a place where you can ask for help. In fact, it seems your question might be answered here: https://forum.cardano.org/t/liveview-not-working/55142.

**Comment by kevlim3** [comment]
Hi, Yes you are right. Thank you.
