### ISSUE TITLE
Feature request: assume `type: exitcode-stdio-1.0` by default

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#7459]
Test and benchmark components have a required field `type`. 

For tests there are two possible values: either `type: exitcode-stdio-1.0` or `type: detailed-0.9`. We are fortunate enough to have nice testing frameworks, so developers rarely resort to `detailed-0.9` (there are only 50 Hackage packages, mostly old ones).

For benchmarks there is actually only one possible value: `type: exitcode-stdio-1.0` - but the field is nevertheless required! This is just a nonsensical friction, which means that I cannot change `benchmark` to `executable` or vice versa without touching other lines. 

I suggest we assume `type: exitcode-stdio-1.0` by default, so that this field is no longer required.

**Comment by Mikolaj** [comment]
I agree. Unless anybody objects, let's do it (in both places).

**Comment by robx** [comment]
Could `detailed-0.9` even be deprecated in some form? Not necessarily with the plan to remove backwards-compatibility, but e.g. not documenting it as an equal alternative.

**Comment by Mikolaj** [comment]
> Could `detailed-0.9` even be deprecated in some form? Not necessarily with the plan to remove backwards-compatibility, but e.g. not documenting it as an equal alternative.

Yes, that's very much needed.
