### ISSUE TITLE
Unrecognised target ':myfirstapp' when following getting started guide

### ISSUE THREAD

**Issue by noughtmare** [haskell/cabal#7460]
**Describe the bug**

While following the [getting started guide](https://cabal.readthedocs.io/en/3.4/getting-started.html#getting-started-with-haskell-and-cabal) I am running into an error message in the section [running the application](https://cabal.readthedocs.io/en/3.4/getting-started.html#running-the-application).

**To Reproduce**

```
$ mkdir myfirstapp
$ cd myfirstapp
$ cabal init --cabal-version=2.4 --license=NONE -p myfirstapp
...
$ cabal v2-run :myfirstapp
cabal: Unrecognised target ':myfirstapp'.
Expected a meta-target 'all', rather than 'myfirstapp'.
```

**Expected behavior**

Building and running the 'myfirstapp' application without errors.

**System information**
 - Operating system: NixOS 21.05
 - `cabal` 3.4.0.0, `ghc` 8.10.4

**Comment by Mikolaj** [comment]
To clarify: is the new syntax `exe:myfirstapp` or is the problem elsewhere?

**Comment by noughtmare** [comment]
The command `cabal v2-run exe:myfirstapp` works. I have also usually just used `cabal v2-run myfirstapp`. So, I think this is just a documentation issue then.

**Comment by Mikolaj** [comment]
OK, thanks, In that case, PRs welcome.

**Comment by noughtmare** [comment]
Which command should be used in the documentation? Maybe just `myfirstapp` is fine for the getting started guide? I think the most verbose version is `:pkg:myfirstapp:exe:myfirstapp`, any suffix of that seems to work.

**Comment by Mikolaj** [comment]
Indeed, for getting started, the shortest one sounds good.
