### ISSUE TITLE
The package-properties URL provided by `cabal check` leads nowhere

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#7461]
**Describe the bug**
When running `cabal check`, the following URL is given by the program:

> Please refer to <https://www.haskell.org/cabal/users-guide/developing-packages.html#package-properties> for more details.

Which leads to a 404 on readthedocs.io

**To Reproduce**

See the offending code here: https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/PackageDescription/Check.hs#L528-L529

**Expected behavior**
A valid URL

**System information**
 - `cabal` HEAD

**Comment by Mikolaj** [comment]
Huh. It seems somebody improved the name of the page without noticing the old one is hardwired. @emilypi: could we add a redirection for the time being?

**Comment by Mikolaj** [comment]
@emilypi: still there in 3.6.1.0

**Comment by gbaz** [comment]
I fixed the redirect so it hits the main docs page. We should update the url properly going forward.

**Comment by Mikolaj** [comment]
OK, so the task seems to be to add an externally visible anchor somewhere here

```
doc/cabal-package.rst-Package properties
doc/cabal-package.rst-^^^^^^^^^^^^^^^^^^
doc/cabal-package.rst-
doc/cabal-package.rst:These fields may occur in the first top-level properties section and
doc/cabal-package.rst-describe the package as a whole:
```

(section names don't seem to generate such anchors automatically), ideally the one that is mentioned here:

https://github.com/haskell/cabal/blob/ed01de6ec33fcc98f924c51b15337f65ff51b28c/Cabal/src/Distribution/PackageDescription/Check.hs#L500

according to how such anchors have done so far, or according to documentation of the system used for https://cabal.readthedocs.io/en/3.6

Volunteers welcome.
