### ISSUE TITLE
Cabal init: Init should add warning flags such as `-Wall`

### ISSUE THREAD

**Issue by fendor** [haskell/cabal#7465]
This might be controversial, but I think people benefit from most warnings in `-Wall`, but a lot of beginners actually don't have this flag enabled, as it is not trivial to discover.

I propose that `cabal init` adds a set of default warnings to each stanza, and if cabal version > 3.0 maybe even with common stanzas, showing off another nice feature of cabal.

While I can see that some warnings are debatable, I think it is better for newcomers to have these warnings added automatically.

Such additions might be controversial as we impose our (maybe only mine?) opinions on other developers, but I argue that this benefits beginners while not impeding more advanced users.

**Comment by phadej** [comment]
Just implement that but so it's configurable,. i.e. can be switched on or off in config or/and wizard.

No need to wait before the defaults bikeshedding is over.

**Comment by Mikolaj** [comment]
IMHO great idea, including the common stanzas. I'd start with default on and if people complain, we may change the default to off (before a release or in a point release).

**Comment by ptkato** [comment]
I'm in favour of adding this feature to the wizard (interactive); however, I'm not sure about the configurability of it, would a newcomer even know what a stanza is, let alone a common stanza? It might be better to simply assume all projects that don't pick the simple workflow, get a common stanza by default.

**Comment by phadej** [comment]
@ptkato don't force choices on users. You should know that `cabal` users are very diverse group of people. You'll save everyone time and nerves if things are configurable from the beginning. Wizard doesn't necessarily need to ask about them, but I'd definitely want it be configurable for experts.

Another approach is to declare `cabal init` beginner-only utility. I wouldn't mind.

**Comment by Mikolaj** [comment]
I don't think there is a drawback to using common stanzas and if a user has a problem with them, the user can easily inline them. The added complexity is tiny compared to complexity of GHC and cabal flags and parameters and the stanzas quickly pay back by reducing boilerplate or even just by naming sets of related settings.

**Comment by Mikolaj** [comment]
And I think it's fine to think about `cabal init` as a newbie and intermediate user tool. Power users can start with it and then tinker manually, which in their case should be quicker than running `cabal init` repeatedly with various arguments and various answers until the result looks just right.

**Comment by phadej** [comment]
That is  the problem. I would use `cabal init` if I could configure it and use **non-interactively**. If I need to tweak afterwards, it's useless.

**Comment by phadej** [comment]
BTW, the fact, IIRC whether `cabal init` is interactive or not is also non-configurable. And that fact split people into equally loud crowds.

**Comment by Mikolaj** [comment]
I don't see why we can't have the best of all worlds at once. But even then, I think power users would find it easier to tweak the cabal files directly instead of indirectly through `cabal init`. If so, it makes sense to have newbie-friendly defaults, including refraining from asking many questions unless explicitly requested via `--ask-about-foo`.

**Comment by ptkato** [comment]
I always saw `cabal init` as a tool to quickly generate .cabal files, if I need to pass to it every option I want, I might as well just manually write the .cabal file, no? We needn't turn `cabal init` into a weirdly specific text editor. I'm with @Mikolaj on this one, we should try and keep it... not complicated.

**Comment by phadej** [comment]
```
% cabal init --help|grep inter
as possible. The interactive mode can be invoked by the -i/--interactive flag,
can change init to always be interactive by setting the interactive flag in
 -i --interactive                    Enable interactive mode.
 -n --non-interactive                Disable interactive mode.
```

If non-interactive mode is not configurable in config file, i.e. neither with command line options, nor with config options in `cabal.config` (so I could **quickly** generate cabal files to my liking), then you may as well remove non-interactive mode.
