### ISSUE TITLE
cabal-install-solver: improving error messages for misspelled language extensions

### ISSUE THREAD

**Issue by skykanin** [haskell/cabal#7468]
After helping someone debug a cabal build issue which was caused by a misspelled language extension in their `project.cabal` file I thought of an idea for improving the error message for misspelled language extensions.

Currently the error is `rejecting: test-cabal-0.1.0.0 (conflict: requires FlexibleConstraints)` where `FlexibleConstraints` is the misspelled language extension. I was thinking if we calculated the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) of the misspelled language extension and compared it to all known extensions https://github.com/haskell/cabal/blob/f09b8556e08bbaa3aa5acfb4d68e01c49e13d79a/Cabal/src/Language/Haskell/Extension.hs#L123 we could give more useful feedback. For example the error message could instead be something like
`rejecting: test-cabal-0.1.0.0 (conflict: requires FlexibleConstraints did you mean FlexibleContexts?)`From peeking a little at the code: https://github.com/haskell/cabal/blob/6896c6aa0e4804913aaba0bbbe00649e18f17bb8/cabal-install-solver/src/Distribution/Solver/Modular/Message.hs#L218 this seems trivial to implement, but maybe someone more experienced with the cabal codebase could comment on my idea before I submit a PR for this.

**Comment by jneira** [comment]
Imo improving error messages is an area we have to work on, generally in the haskell worls and in cabal, of course.
So a pull request like that may be very welcomed, do you agree @Mikolaj?

**Comment by fgaz** [comment]
+1, we even have edit-distance in the cabal deps

**Comment by Mikolaj** [comment]
Deal. Unblocking and welcoming. :)
