### ISSUE TITLE
Dead link in "data-files:" documentation.

### ISSUE THREAD

**Issue by danidiaz** [haskell/cabal#7469]
The [Accessing data files from package code](https://cabal.readthedocs.io/en/latest/cabal-package.html#accessing-data-files-from-package-code) section of the user guide has a dead link to a non-existent section about "prefix independence":

>  (see prefix independence)

Googling for it, it seems that section [formerly belonged](https://downloads.haskell.org/~ghc/7.0.4/docs/html/Cabal/builders.html#prefix-independence) to the GHC User Guide—but it isn't present in the current GHC User Guide.

**Comment by andreasabel** [comment]
No, the section "prefix independence" is still present in the Cabal docs: https://github.com/haskell/cabal/blob/7d4ce4787cb3d4fe30d08953ad64d19456a77690/doc/setup-commands.rst#prefix-independence

Only the link broke, maybe by 3752c3e5edc3c19b7262cdb0b70f4e0539b46362 which moved the text from `installing-packages.rst` to `setup-commands.rst`
bb16112746724ccef9686d407ec94c7ccf7f928a fixed some links, but must have missed this one.

**Comment by andreasabel** [comment]
Fix in PR #7586.

**Comment by andreasabel** [comment]
I took away the "wierd bug award", as broken references are easy to creep in.  
Broken refs can maybe be avoided by passing `-n` ("nitpick") to `sphinx-build`, see https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-n.  E.g., when I run with `-n`, this sleeping bug surfaces:
```
doc/cabal-project.rst:644: WARNING: 'envvar' reference target not found: PATH
```
I'll prepare a new PR that fixes this.

**Comment by andreasabel** [comment]
> I'll prepare a new PR that fixes this.

PR #7603.

**Comment by Mikolaj** [comment]
Good call, thank you. Broken links are indeed not that weird, as opposed to linking away to an imaginary section.
