### ISSUE TITLE
Strange space when highlighting the documentation

### ISSUE THREAD

**Issue by coot** [haskell/cabal#7475]
Check out the link: https://cabal.readthedocs.io/en/latest/setup-commands.html?highlight=flag#cmdoption-runhaskell-Setup.hs-configure-f
It shows `-f flag name or -f -flagname` where `flag` is highlighted, without highlighting it shows `-f flagname or -f -flagname`.

**Comment by Mikolaj** [comment]
Indeed, looks wrong.

**Comment by andreasabel** [comment]
This has nothing to do with the cabal docs, the same effect can be observed everywhere on readthedocs, e.g. here: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html?highlight=opt

So this issue should be closed.  

If you care about this @coot, you should report it upstream to readthedocs.org or sphinx or whereever suitable.

**Comment by Mikolaj** [comment]
If anybody would like to escalate to upstream and post a link here, that would be great. Otherwise, let's close this after a month or so of inactivity.

**Comment by coot** [comment]
I opened an upstream ticket.

**Comment by fgaz** [comment]
Link for reference: https://github.com/readthedocs/readthedocs.org/issues/8450

**Comment by coot** [comment]
This has been fixed in an incoming version: https://github.com/readthedocs/sphinx_rtd_theme/issues/1223#issuecomment-908502249

**Comment by Mikolaj** [comment]
@coot: thank you so much! success!
