### ISSUE TITLE
could use more options for framework linking on mac

### ISSUE THREAD

**Issue by bos** [haskell/cabal#751]
(Imported from [Trac #761](http://hackage.haskell.org/trac/hackage/ticket/761), reported by simonmic on 2010-11-10)

It seems you can list apple frameworks in a .cabal file like other libs, but I'm not sure how to influence where cabal looks for those frameworks. When trying to link with some in a non-standard place, I wished for an --extra-framework-dirs option. There is a rumoured -framework option, I haven't found much info in --help or online about all this.

**Comment by gbaz** [comment]
We do have --extra-framework-dirs now, so I'm going to close this.
