### ISSUE TITLE
Cabal 3.6 has been announced but cabal install fails to find it on my machine

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/cabal#7514]
Cabal 3.6 has been announced but cabal install fails to find it on my machine

 cabal install --lib Cabal 
Resolving dependencies...
Up to date
bash-3.2$ ghc-pkg list|fgrep Cabal
    Cabal-3.4.0.0
bash-3.2$ ghc-pkg list -f $HOME/.cabal/store/ghc-9*/package.db|fgrep Cabal
bash-3.2$

**Comment by Mikolaj** [comment]
@GeorgeCo: Hi! Thank you for the report. You are right, it's not on Hackage yet, but should probably be there in a day or two.

**Comment by GeorgeCo** [comment]
Thanks

**Comment by emilypi** [comment]
It's on Hackage!
