### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by dj110919871** [haskell/cabal#7515]
**Describe the bug**

**To Reproduce**

```
$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by emilypi** [comment]
Hi @dj110919871 is this issue about something in particular?

**Comment by jneira** [comment]
@dj110919871 closing as we even are not sure if it is a mistake, feel free to reopen with additional info
