### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dj110919871** [haskell/cabal#7540]
**Describe the bug**

**To Reproduce**

```
$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by gbaz** [comment]
feature.

**Comment by fgaz** [comment]
What even is this user? It looks machine-generated and it's spamming dozens of repos with nonsensical issues. I reported it to GitHub.
