### ISSUE TITLE
cabal init declares incorrect cabal-version

### ISSUE THREAD

**Issue by naglalakk** [haskell/cabal#7547]
**Describe the bug**
cabal init with cabal version 3.4.0.0 adds cabal-version in the .cabal file as version: 2.4.
Is this expected? shouldn't it be cabal 3.4.0.0?

**To Reproduce**
Run ```cabal init``` with cabal version = 3.4.0.0

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
Cabal init should mark cabal-version as 3.4.0.0

**System information**
 - arch linux
 - cabal version: 3.4.0.0, ghc version: 8.8.4

**Additional context**

**Comment by Mikolaj** [comment]
I think that means cabal version as old as 2.4 is allowed and capable of processing this file. I agree `cabal-version: 2.4` sounds misleading, but it's probably too late to change it to (a condensed variants of) `minimal-cabal-version-required-to-understand-this-file: 2.4`.

**Comment by Mikolaj** [comment]
Having said that, thank you for the report and perhaps you have a proposal how to help users. E.g., a suggestion to modify documentation in a way that would help?

**Comment by fgaz** [comment]
I'll paste an answer I previously gave to the same question:

> Here `cabal-version` refers to the version of the `.cabal` specification, and can be different from the cabal-install (the tool) version and the Cabal (the library) version you are using.

> A more recent version gives you more features (for example common stanzas, Backpack, SPDX, multiple public libraries...), but will be incompatible with older `Cabal`s which can't understand newer specs. `cabal-version` 2.4 is a good compromise which gives you a lot of features but is still compatible with the ~3-year-old `Cabal` 2.4.

> On the spec changelog you can find the features that get enabled on each version: https://cabal.readthedocs.io/en/3.4/file-format-changelog.html

**Comment by fgaz** [comment]
I recently added a note about it in the docs here: https://cabal.readthedocs.io/en/latest/getting-started.html#initializing-the-application

Maybe we should copy it here too: https://cabal.readthedocs.io/en/latest/developing-packages.html#using-cabal-init

@naglalakk is there any other place where this is not clear?

**Comment by naglalakk** [comment]
Thanks for a quick response and clearing this up. It makes sense that this is the minimum version required. The note you are pointing to @fgaz is pretty clear and personally enough for me. I should have googled a bit better. But if this question keeps popping up it might be a strong move to add it as a comment.

**Comment by Mikolaj** [comment]
Adding "this is minimal cabal format version with which this file is known to work with" as a comment in the .cabal file generated by `cabal init`? That's not a bad idea. Pinging @ptkato as the `cabal init` owner IIRC.

**Comment by fgaz** [comment]
> "this is minimal cabal format version with which this file is known to work with"

it isn't the _minimal_ format version, it's _the_ format version. it's Cabal that needs to have a version equal or greater than that format's to support it

**Comment by Mikolaj** [comment]
Haha, I'd argue it's *minimal* version *known*, because the tool (nor its creators) didn't make any effort to know if an earlier version would suffice, and of those that are known, the lowest is chosen. And that's what we recommend to users: don't make too much effort experimenting, but of the versions that obviously work, enter the minimal, to help with compatibility.

And if we are nitpicking, the comment in the form I've given does not promise that any cabal with version greater or equal would accept the file. It just suggests that is a future cabal supports this format version, the file will work fine.

**Comment by fgaz** [comment]
Heh, true :)

I just think it's important to avoid further ambiguity if we add that comment, sorry for the nitpicking

**Comment by ptkato** [comment]
> it isn't the _minimal_ format version, it's _the_ format version. it's Cabal that needs to have a version equal or greater than that format's to support it

That really is confusing! Now, I'm fine with adding a comment to the cabal file. Gathering the info here, I suggest something like

```
The cabal-version field refers to the version of the .cabal specification, 
and can be different from the cabal-install (the tool) version and the 
Cabal (the library) version you are using. As such, the Cabal (the library)
version used must be equal or greater than the version stated in this field.
```
