### ISSUE TITLE
withShorterPathForNewBuildStore needs the windows tempDir hack

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#7549]
In particular

https://github.com/haskell/cabal/blob/78fbe09298d9259696b939e25dd9a1e943670908/cabal-testsuite/src/Test/Cabal/Prelude.hs#L1000

should make use of `withTestDir`

https://github.com/haskell/cabal/blob/00a2351789a460700a2567eb5ecc42cca0af913f/cabal-install/tests/UnitTests/TempTestDir.hs#L26

so that we don't get sporadic windows failures with `removeDirectoryRecursive` throwing on permissions errors.

**Comment by Mikolaj** [comment]
Possible example of such a failure: https://ci.appveyor.com/project/23Skidoo/cabal/builds/40384463
