### ISSUE TITLE
Where did Distribution.ParseUtils go?

### ISSUE THREAD

**Issue by noughtmare** [haskell/cabal#7555]
I'm trying to update a package called [`shuffle`](https://hackage.haskell.org/package/shuffle). It depends on the following functions from `Distribution.ParseUtils`.

```
import Distribution.ParseUtils (runP, parseOptCommaList, parseFilePathQ, ParseResult (..))
```

And it is only in this function:

```haskell
parseFileList :: String -> String -> Verbosity -> IO [FilePath]
parseFileList fieldName field verbosity =
  case runP 0 fieldName (parseOptCommaList parseFilePathQ) field of
    ParseFailed err    -> dieNoVerbosity $ show err
    ParseOk warnings r -> mapM_ (warn verbosity . show) warnings >> return r
```

I have found out that the `Distribution.ParseUtils` module has been removed in `Cabal` version 3.0.0.0, because of a move towards parsec parsers. Unfortunately, the [3.0 migration guide](https://github.com/haskell/cabal/wiki/3.0-migration-guide) does not contain any information about this change.

I did also find the new `Distribution.Parsec` module which does seem to contain alternatives, but I'm not certain how to use these to match the old behavior.

I will keep on trying to figure this out on my own and I think I will get there, but I think this issue might also be useful for other people. And maybe the results can be added to the 3.0 migration guide.

**Comment by noughtmare** [comment]
I think I have been able to rewrite the function as follows:

```haskell
parseFileList :: String -> String -> Verbosity -> IO [FilePath]
parseFileList fieldName field verbosity =
  case runParser (unPP cabalSpecLatest ((,) <$> parsecOptCommaList parsecFilePath <*> Parsec.getState <* Parsec.eof)) [] fieldName (fieldLineStreamFromString field) of
    Left err    -> dieNoVerbosity $ show err
    Right (r, warnings) -> mapM_ (warn verbosity . show) warnings >> return r
```

**Comment by phadej** [comment]
`ParseUtils` got removed. `Distribution.Parsec` and related stuff is the thing to use now. The [`explicitEitherParsec`](https://hackage.haskell.org/package/Cabal-3.6.0.0/docs/Distribution-Parsec.html#v:explicitEitherParsec) is simpler if you don't need warnings.  If you need warnings then it's that ugly (Cabal itself doesn't need them in that way so there are no helpers).

**Comment by noughtmare** [comment]
Thanks, I'll use this implementation then.
