### ISSUE TITLE
please link "built on" entries in package descriptions to hackage build logs

### ISSUE THREAD

**Issue by bos** [haskell/cabal#756]
(Imported from [Trac #766](http://hackage.haskell.org/trac/hackage/ticket/766), reported by claus on 2010-11-17)

It seems that build logs are no longer linked from package pages (used to be linked from the <tt>built on</tt> entries, iirc), such as:

[http://hackage.haskell.org/package/haddock](http://hackage.haskell.org/package/haddock)

Also, the <tt>latest/</tt> directory has <tt>doc/</tt>, but not <tt>logs/</tt>, while the archived versioned directory has both:

[http://hackage.haskell.org/packages/archive/haddock/latest/](http://hackage.haskell.org/packages/archive/haddock/latest/)

[http://hackage.haskell.org/packages/archive/haddock/2.8.1/](http://hackage.haskell.org/packages/archive/haddock/2.8.1/)

And, since I've more than once confused myself with that directory structure (<tt>package</tt> singular, but <tt>packages/archive</tt> plural? why the different prefix, where a version number postfix should be enough? why both <tt>http://hackage.haskell.org/package/haddock-2.8.0</tt> and <tt>http://hackage.haskell.org/packages/archive/haddock/2.8.0/</tt>?), could that be simplified (or, at least, a link be provided from the <tt>package</tt>-entry to the shadow-hierarchy <tt>packages/archive</tt>)?

**Comment by ttuegel** [comment]
This isn't a Cabal issue.
