### ISSUE TITLE
Cabal does not respect the setgid bit when creating directories

### ISSUE THREAD

**Issue by joewkr** [haskell/cabal#7560]
When using `cabal install` to install packages on a Linux machine it creates quite a number of directories while building and installing components. It works pretty well until you want to use `CABAL_DIR` (or `dist-newstyle` directory) with a set `setgid` bit. In this case some of the directories created by cabal do not inherit the `setgid` bit of the parent directory (as in the following example):

```
$ export CABAL_DIR=/scratch/cabal
$ cabal update
Config file path source is default config file.
Config file /scratch/cabal/config not found.
Writing default configuration to
/scratch/cabal/config
Downloading the latest package list from hackage.haskell.org
$ cabal install zlib
# ... Output omitted ...
$
```
which gives the following under `/scratch/cabal`:
```
$ ll /scratch/cabal
total 28
drwxrwsr-x 5 user grp 4096 Aug 20 14:57 ./
drwxrwsr-x 7 user grp 4096 Aug 20 14:54 ../
-rw-rw-r-- 1 user grp 5508 Aug 20 14:55 config
drwxrwsr-x 3 user grp 4096 Aug 20 14:57 logs/
drwxrwsr-x 3 user grp 4096 Aug 20 14:55 packages/
drwxr-xr-x 3 user grp 4096 Aug 20 14:57 store/ # <== No setgid bit
$ ll /scratch/cabal/store
drwxr-xr-x 3 user grp  4096 Aug 20 14:57 ./
drwxrwsr-x 5 user grp  4096 Aug 20 14:57 ../
drwxr-xr-x 4 user user 4096 Aug 20 14:58 ghc-8.10.6/
$
```
where the `store` directory is created without the `setgid` bit. Thus, the files and directories under `store` have a different group, which could be rather bothersome when user's primary group has a strict disk quota enforced.

It seems that this behavior is related to the definition of the `createDirectoryVerbose` function which calls `setDirOrdinary` after a directory is created. In turn, the `setDirOrdinary` function calls `c_chmod` to set the permissions of the directory in question to `0o755` apparently clearing the `setgid` bit.

It would be really nice to have cabal to be able to recognize this kind of situation and set (or keep) the `setgid` bit accordingly. Or maybe it's already possible?

**Comment by DanielG** [comment]
Thanks for the helpful analysis @joewkr. I agree this behaviour is broken.

I was wondering why we are setting the file/directory permissions like this to begin with when the defaults are ususally just fine. It seems it's related to `umask` messing with permissions when installing packages as root. See 237cfe101bccb6929fea2c53c4d2300b4f53c598 commit message quoted below:

> Reimplement createDirectoryIfMissingVerbose to use sensible file permissions
> 
> Hopefully should fix ghc ticket #4982.
> The problem was permissions on directories: previously we used ordinary
> createDirectory and on unix this creates dirs using the current user's
> umask. If the root user has a silly umask then someone doing sudo
> install will end up with dirs that are not readable by non-root users.
> 
> So the solution is to do the same as we do with files: override the
> umask and explicitly set the file permissions based on the kind of
> file: ordinary file, executable file and now also directory.
> 
> Sadly we also had to re-implement createDirectoryIfMissing to use our
> new createDirectory wrapper function.

So it seems my first attempt at fixing this in #7572 by masking away the unwanted bits is actually wrong since we explicitly want to add the mode bits the `umask` is removing. So instead we'll have to add the bits by or'ing there.

I'm also not quite sure what the difference between FilePerms.hs and CopyFile.hs is since the latter also has a (copied?) `setFileMode` function that I've missed initially.

**Comment by DanielG** [comment]
That should be better. @joewkr can you test if #7572 fixes your issue?

**Comment by joewkr** [comment]
Yes, applying #7572 (well, after correcting a typo in `cabal-install/src/Distribution/Client/Compat/FilePerms.hs` imports) fixes the issue for me. Thanks, @DanielG
