### ISSUE TITLE
Highlighted source code on hackage.haskell.org mangles Unicode

### ISSUE THREAD

**Issue by bos** [haskell/cabal#757]
(Imported from [Trac #767](http://hackage.haskell.org/trac/hackage/ticket/767), reported by andersk on 2010-11-19)

On hackage.haskell.org, when you browse the source of a module that contains Unicode (e.g. [Data.Eq.Unicode](http://hackage.haskell.org/packages/archive/base-unicode-symbols/latest/doc/html/src/Data-Eq-Unicode.html)), it is sent with a <tt>Content-Type: text/html</tt> header with no charset.  There is a charset in the XML declaration <tt>&lt;?xml version="1.0" encoding="UTF-8"?&gt;</tt>, but that is ignored by Firefox because of the non-XML <tt>Content-Type</tt>.  Therefore, the wrong encoding is detected and the Unicode symbols get mangled.

Possible fixes include sending <tt>Content-Type: text/html; charset=UTF-8</tt>, or sending <tt>Content-Type: application/xhtml+xml</tt> so that the XML declaration is respected , or both (<tt>Content-Type: application/xhtml+xml; charset=utf-8</tt>), or adding equivalent <tt>&lt;meta http-equiv="Content-Type"&gt;</tt> tags.

**Comment by ttuegel** [comment]
This isn't a Cabal issue.
