### ISSUE TITLE
Cabal v2 install refuses to work

### ISSUE THREAD

**Issue by TakodaS** [haskell/cabal#7589]
**Describe the bug**
Cabal v2-install absolutely refuses to work for me, giving me the error 

**To Reproduce**
In a new directory I type
```
cabal init
cabal v2-install packagename
```
and it fails giving the error 
```
cabal.exe: Cannot build the executables in the package primes because it does
not contain any executables. Check the .cabal file for the package and make
sure that it properly declares the components that you expect.
```

Running 
`cabal v2-install --lib packagename`

gives me the error
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: ghc-8.10.4/installed-8.10.4 (user goal)
[__1] next goal: process (user goal)
[__1] rejecting: process-1.6.13.2, process-1.6.13.1, process-1.6.12.0
(constraint from user target requires ==1.6.11.0)
[__1] rejecting: process-1.6.11.0 (conflict: ghc =>
process==1.6.9.0/installed-1.6.9.0)
[__1] rejecting: process-1.6.10.0, process-1.6.9.0/installed-1.6.9.0,
process-1.6.9.0, process-1.6.8.2, process-1.6.8.1, process-1.6.8.0,
process-1.6.7.0, process-1.6.6.0, process-1.6.5.1, process-1.6.5.0,
process-1.6.4.0, process-1.6.3.0, process-1.6.2.0, process-1.6.1.0,
process-1.6.0.0, process-1.5.0.0, process-1.4.3.0, process-1.4.2.0,
process-1.4.1.0, process-1.4.0.0, process-1.3.0.0, process-1.2.3.0,
process-1.2.2.0, process-1.2.1.0, process-1.2.0.0, process-1.1.0.2,
process-1.1.0.1, process-1.1.0.0, process-1.0.1.5, process-1.0.1.4,
process-1.0.1.3, process-1.0.1.2, process-1.0.1.1, process-1.0.0.0,
process-1.6.13.0 (constraint from user target requires ==1.6.11.0)
[__1] fail (backjumping, conflict set: ghc, process)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: process, ghc
```

The only things that work are manually editing the `haskellproject.cabal` file and then running `cabal install`, or using v1-install

**System information**
 - Operating system: windows 10
 - `cabal`, `ghc` versions: 3.4.0.0, 8.10.4

**Comment by Mikolaj** [comment]
Could you try `cabal build`?

**Comment by Mikolaj** [comment]
Or `cabal run` so that we see if the way suggest in https://www.haskell.org/cabal/ makes sense?

**Comment by Mikolaj** [comment]
BTW, where did you get your workflow from? Perhaps there's some other outdated documentation out there that we need to fix?

**Comment by TakodaS** [comment]
`cabal build` gives me
```Resolving dependencies...                                                                     Build profile: -w ghc-8.10.4 -O1                                                              In order, the following will be built (use -v for more details):                               - haskelltest2-0.1.0.0 (exe:haskelltest2) (first run)                                        Configuring executable 'haskelltest2' for haskelltest2-0.1.0.0..                              Preprocessing executable 'haskelltest2' for haskelltest2-0.1.0.0..                            Building executable 'haskelltest2' for haskelltest2-0.1.0.0..                                 [1 of 1] Compiling Main             ( app\Main.hs, D:\path\to\haskelltest2-0.1.0.0\x\haskelltest2\build\haskelltest2\haskelltest2-tmp\Main.o )                                                                                  Linking D:\\path\to\haskelltest2\dist-newstyle\build\x86_64-windows\ghc-8.10.4\haskelltest2-0.1.0.0\x\haskelltest2\build\haskelltest2\haskelltest2.exe 
```
and resolves successfully.

`cabal run` also works fine, giving me the Hello Haskell! message. However, the install does not work since when I put in an `import Packagename` into `app/Main.hs` it gives me a could not load module error. 

Workflow is just from https://cabal.readthedocs.io/en/latest/getting-started.html. It does instructs the newbie to add a package to the .cabal file manually, but I can't believe you have to do this for every new package.

**Comment by Mikolaj** [comment]
Indeed, that does not "install" the package in any way. However, that should not be required most of the time.

I'd like to ask where the `app/Main.hs` file comes from, but I'm afraid github is not the best medium for assisting in cabal experiments and for general advice. Would you like to ask for help on some beginner friendly forum? E.g., IRC, Matrix, many others. After that, if you could come back and suggest improvements in documentation or the tooling itself, I'd be personally very grateful.
