### ISSUE TITLE
HackageDB messes up {-# OPTIONS_HADDOCK hide #-}

### ISSUE THREAD

**Issue by bos** [haskell/cabal#759]
(Imported from [Trac #769](http://hackage.haskell.org/trac/hackage/ticket/769), reported by @blamario on 2010-11-26)

Have a look at the SCC 0.6 package page ([http://hackage.haskell.org/package/scc](http://hackage.haskell.org/package/scc)) and then try to see, say, its XML module API ([http://hackage.haskell.org/packages/archive/scc/0.6/doc/html/Control-Concurrent-SCC-XML.html](http://hackage.haskell.org/packages/archive/scc/0.6/doc/html/Control-Concurrent-SCC-XML.html)).

The reason for the 404 message that this module has a {-# OPTIONS_HADDOCK hide #-} pragma. When I tried Haddock locally, the effect was that the  module became invisible, which was my intention. Making the module name visible but its documentation missing was not.

**Comment by ttuegel** [comment]
This isn't a Cabal issue.
