### ISSUE TITLE
Paths module fails -Wprepositive-qualified-module

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/cabal#7599]
**Describe the bug**
The autogenerated `Paths_*.hs` module fails when GHC is passed `-Werror -Wprepositive-qualified-module`.

**To Reproduce**
1. Specify Paths module in cabal file
2. Add `ghc-options: -Werror -Weverything` to cabal file
3. Use GHC 8.10
4. Build

**Expected behavior**
It should work

**System information**
- GHC 8.10

**Additional context**

**Comment by phadej** [comment]
That is already fixed https://github.com/haskell/cabal/pull/7352, most likely will be in the next `cabal-install` release.

**Comment by brandon-leapyear** [comment]
Apologies; I searched for `prepositive-qualified-module` in issues, but forgot to check PRs.
