### ISSUE TITLE
cabal is not reading or respecting ~/.cabal/config

### ISSUE THREAD

**Issue by bos** [haskell/cabal#760]
(Imported from [Trac #770](http://hackage.haskell.org/trac/hackage/ticket/770), reported by guest on 2010-11-27)

I changed my ~/.cabal/config file to keep global packages under /usr/local/lib/haskell and /usr/local/share/haskell to avoid cluttering the main /usr/local/lib and /usr/local/share/doc directories.  ghc-pkg finds them just fine, and ghc-pkg recache works as expected.  However, when I do 'cabal install whatever --global' it still throws everything into the old default directories, and more distressingly it isn't updating the access timestamp on ~/.cabal/config (as revealed by ls -u.)

cabal --version reports 0.8.2 using library 1.8.0.6, nothing else unusual about my setup.

**Comment by ttuegel** [comment]
Closing this issue, which appears to be user error.
