### ISSUE TITLE
Cabal init gives "Error: no package name provided."

### ISSUE THREAD

**Issue by rgkirch** [haskell/cabal#7640]
```
mkdir foo
cd foo
cabal init --non-interactive

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Error: no package name provided.
```
Running `cabal init` creates a changelog.md file and an app/Main.hs file. Sholudn't it also create a foo.cabal file?
I tested this on Windows 10 with cabal version 3.4.0.0 and ghc version 9.0.1 as well as macos with cabal version 3.4.0.0 and ghc version 8.10.7 and got identical results.

**Comment by Mikolaj** [comment]
Hi! I guess it should. Could you try with the just release cabal 3.6.1? I hope it's fixed there.

**Comment by emilypi** [comment]
Upgrade to 3.6 please - this is fixed.

**Comment by emilypi** [comment]
```shell
λ athena foo → cabal init --non-interactive 
cabal: The name foo is already in use by another package on Hackage.
```

**Comment by rgkirch** [comment]
Thanks for the help!
