### ISSUE TITLE
cabal list-bin cabal-tests (and others) fails with "No or multiple targets given"

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#7679]
**Describe the bug**

`cabal list-bin cabal-tests` complains about zero or multiple targets, even when a qualified target is used. I'm not sure why the error happens only with cabal-tests

**To Reproduce**

```
> cabal list-bin cabal-testsuite:exe:cabal-tests
cabal: No or multiple targets given
```

**Expected behavior**

* getting the path to cabal-tests
* a better error

**System information**

- cabal: current master, even with #7408 applied

**Additional context**

https://github.com/haskell/cabal/pull/7648#issuecomment-924111500 

**Workaround**

use [cabal-plan](https://hackage.haskell.org/package/cabal-plan) list-bin

**Comment by fgaz** [comment]
It looks like this happened in the wild https://github.com/agda/agda/issues/4216#issuecomment-930142519

**Comment by fgaz** [comment]
@mouse07410 in #7739 you explicitly mentioned cabal 3.6. Is this a regression from 3.4?

**Comment by mouse07410** [comment]
I mentioned 3.6.0.0 because that's what I'm using, and thought you need to know.

Unfortunately, I don't even have `cabal-3.4.0.0` anymore. Are you saying that fur debugging you'd like me to install 3.4.0.0 again and try `cabal list-bins`? 

Since I never tried this command (list-bins) in the past, and only trying it now to avoid the rebuild caused by `install`, there's a good reason to assume this but was present in older versions as well.

**Comment by fgaz** [comment]
> Are you saying that fur debugging you'd like me to install 3.4.0.0 again and try cabal list-bins?

No need. I just wanted to confirm you weren't implying this is a regression (from what I remember it isn't, it's always been like this).

> Also, you mentioned a workaround - using cabal-plan. Unfortunately, one cannot build it with current GHC-9.0.1

relevant cabal-plan ticket: https://github.com/haskell-hvr/cabal-plan/issues/72

**Comment by mouse07410** [comment]
> relevant cabal-plan ticket: haskell-hvr/cabal-plan#72

Actually, situation seems worse than that:
```
$ cabal install cabal-plan -w ghc-8.10.7
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - base-compat-0.12.0 (lib) (requires build)
 - hashable-1.3.4.1 (lib) (requires build)
 - base-compat-batteries-0.12.0 (lib) (requires build)
 - time-compat-1.9.6.1 (lib) (requires build)
 - these-1.1.1.1 (lib) (requires build)
 - scientific-0.3.7.0 (lib) (requires build)
 - unordered-containers-0.2.14.0 (lib) (requires build)
 - data-fix-0.3.2 (lib) (requires build)
 - uuid-types-1.0.5 (lib) (requires build)
 - strict-0.4.0.1 (lib) (requires build)
 - attoparsec-0.14.1 (lib) (requires build)
 - aeson-1.5.6.0 (lib) (requires build)
 - cabal-plan-0.7.2.0 (lib) (requires build)
Starting     hashable-1.3.4.1 (lib)
Starting     base-compat-0.12.0 (lib)
Building     base-compat-0.12.0 (lib)
Building     hashable-1.3.4.1 (lib)
Installing   hashable-1.3.4.1 (lib)
.  .  .  .  .
Completed    aeson-1.5.6.0 (lib)
Starting     cabal-plan-0.7.2.0 (lib)
Building     cabal-plan-0.7.2.0 (lib)
Installing   cabal-plan-0.7.2.0 (lib)
Completed    cabal-plan-0.7.2.0 (lib)
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
* You might have wanted to add them as dependencies to your package. In this
case add "cabal-plan" to the build-depends field(s) of your package's .cabal
file.
* You might have wanted to add them to a GHC environment. In this case use
"cabal install --lib cabal-plan". The "--lib" flag is provisional: see
https://github.com/haskell/cabal/issues/6481 for more information.
$ 
```

So, how can one use that `cabal-plan` workaround, while this problem is being sorted out?

**Comment by mouse07410** [comment]
> strange, I was able to install cabal-plan executable in the past, maybe some project config is interfering with? could you try to execute the command outside of any project (so out of any subdir of a project too)? will try to reproduce asap

No need to. A couple-of-days-old cabal installed `cabal-plan` 0.7.2.0   as a library **only**. After `cabal update`, it installed 0.7.2.1 with the necessary executable. So, `cabal-plan` utility is installed and running. 

Problem - it's of limited usefulness fur dynamic executables.

**Comment by larskuhtz** [comment]
Not sure if it is related: After adding a test suite to a package, `cabal list-bin` stopped working with `cabal: No or multiple targets given`. The test suite is called tests, which is different from the name of the executable.

I tried all kinds of syntax for qualifying the target (as described in the latest docs), but none worked and some resulted in confusing failure messages, that indicate that more might be wrong with `list-bin`.

**Comment by larskuhtz** [comment]
I made the failure message a bit more verbose and it turns out that the problem is that `cabal list-bin PROGRAM_NAME` fails be finding two targets: the executable (`PROGRAM_NAME`) and the test suite which is called `tests`. The same result is returns with `cabal list-bin executable:PROGRAM_NAME`.

So, problem (at least in my case) seems to be that cabal includes the test suite in the result, even though it is clearly not specified as a target.

**Comment by larskuhtz** [comment]
Some more details. Here is an example run that logs the `targetSelector` as well as the final (reject) list of targets. 

Note how the qualified target selector explicitly selects: the package (`chainweb-mining-client`), the kind (`CEceName`), and the component name (`chainweb-mining-client`), yet list of selected targets include the test-suite (`build/tests/tests`).

```
$ cabal list-bin chainweb-mining-client:executable:chainweb-mining-client
"targetSelectors: [TargetComponent (PackageIdentifier {pkgName = PackageName \"chainweb-mining-client\", pkgVersion = mkVersion [0,2]}) (CExeName (UnqualComponentName \"chainweb-mining-client\")) WholeComponent]"
Error: cabal: Multiple targets found:
["/Users/lars/Code/chainweb/chainweb-mining-client/dist-newstyle/build/x86_64-osx/ghc-9.0.1/chainweb-mining-client-0.2/build/chainweb-mining-client/chainweb-mining-client","/Users/lars/Code/chainweb/chainweb-mining-client/dist-newstyle/build/x86_64-osx/ghc-9.0.1/chainweb-mining-client-0.2/build/tests/tests"]
```

**Comment by larskuhtz** [comment]
cf. https://github.com/haskell/cabal/pull/7791 for a proposed fix

**Comment by larskuhtz** [comment]
#7791 resolves the original issue that is described above:

```sh
> cabal list-bin cabal-testsuite:exe:cabal-tests
cabal: No or multiple targets given

> $(cabal list-bin cabal-install:cabal) list-bin cabal-testsuite:exe:cabal-tests
/Users/lars/Code/github/cabal/dist-newstyle/build/x86_64-osx/ghc-9.0.1/cabal-testsuite-3/build/cabal-tests/cabal-tests
```
