### ISSUE TITLE
cabal init does not put cabal-version on the first line

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#7680]
**Describe the bug**

cabal init does not put cabal-version on the first line. it puts a comment instead. according to the spec, though, starting from 2.2, the version should be on the first line

**To Reproduce**

```
$ cabal init --non-interactive --lib

Guessing dependencies...

Using cabal specification: 3.0

Warning: unknown license type, you must put a copy in LICENSE yourself.
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Creating directory ./src...
Creating file src/MyLib.hs...
Creating file tmp-Ztm69mNz3W.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field

$ cabal build
Errors encountered when parsing cabal file ./tmp-Ztm69mNz3W.cabal:

tmp-Ztm69mNz3W.cabal:5:1: error:
cabal-version should be at the beginning of the file starting with spec version 2.2. See https://github.com/haskell/cabal/issues/4899

    5 | cabal-version:      3.0
      | ^


```

The generated cabal file starts with:

```
-- The cabal-version field refers to the version of the .cabal specification,
-- and can be different from the cabal-install (the tool) version and the
-- Cabal (the library) version you are using. As such, the Cabal (the library)
-- version used must be equal or greater than the version stated in this field.
cabal-version:      3.0

```

**Expected behavior**

cabal-version and the comment should be swapped

**System information**

 - cabal: current master

/cc @emilypi @ptkato

**Comment by emilypi** [comment]
@fgaz is this with master or `3.6`?

**Comment by fgaz** [comment]
> cabal: current master

**Comment by emilypi** [comment]
Great! thanks - missed that line :)

**Comment by ptkato** [comment]
That's a consequence of #7553. Now, should we move that comment below the `cabal-version` field or what?

**Comment by ptkato** [comment]
If we are to move that comment below the field, I can think of two options, the first is to hack it somehow and place a dummy field below it with just the comment, or go the "right" way and un-hardcode the comments from being at the top of the fields, here:

https://github.com/haskell/cabal/blob/cb980245455092ef44cd4bede694b7c18bd5246e/Cabal/src/Distribution/Fields/Pretty.hs#L116-L118

**Comment by emilypi** [comment]
@ptkato i'm thinking #2 is probably the best way to go here, and I have an idea in my head of how we can mock this. I think it would just come down to adding the following datatype to `Fields/Pretty.hs` which tags the order of rendering for comments: 

  ```haskell
    data CommentLines = CommentBefore [String] | CommentAfter [String]
  ```

Changing the `PrettyField` definition to be `PrettyField ann name CommentLines`. Then, where we output comments, we can case on whether to flip the output. E.g.: 

```haskell
renderField :: Opts ann -> Int -> PrettyField ann -> Block
renderField (Opts rann indent post) fw (PrettyField ann name doc) =
    Block before after content
  where
    content = case comments of
     CommentBefore cs -> cs ++ post ann lines'
     CommentAfter cs -> post ann lines' ++ cs
    comments = rann ann
...
```

**Comment by ptkato** [comment]
I don't think I follow; wouldn't it be better if we snuck `CommentLines` inside whatever comes in `ann`? Something like so

```haskell
data FieldAnnotation = FieldAnnotation
  { annCommentedOut :: Bool
  , annCommentLines :: CommentLines
  }
```

**Comment by emilypi** [comment]
Ah i forgot to describe that step. yes - you would have to so that when you run `rann ann` you'd produce a FieldAnnotation and then you could case on `annCommentLines` yes.
