### ISSUE TITLE
`cabal init` tests should check for buildable output

### ISSUE THREAD

**Issue by ptkato** [haskell/cabal#7689]
As of now the tests pertaining `cabal init` only check if the command generates the rightful stanzas and .cabal file, however none of them check if the generated file can actually build a package proper. Such tests would go a long way to prevent bugs like #7680.

**Comment by ptkato** [comment]
@fgaz you mentioned in https://github.com/haskell/cabal/pull/7681#pullrequestreview-763606814 that testing could be possible through the cabal-testsuite, and to look into the hermetic tests, but do we actually need to test this through using hermetic tests? We wouldn't be modifying any cabal source code, am I missing something?

**Comment by fgaz** [comment]
> By default, we run tests directly on the source code that is checked into the
> source code repository. However, some tests require programatically
modifying source files, or interact with Cabal commands which are
not hermetic (e.g., cabal freeze).

"source code" means "test source code" here: for example freeze creates a freeze file which must be removed before rerunning the test, and init creates a package which again must be removed and recreated each time
