### ISSUE TITLE
Simpler support for isolated/sandboxed builds

### ISSUE THREAD

**Issue by bos** [haskell/cabal#770]
(Imported from [Trac #780](http://hackage.haskell.org/trac/hackage/ticket/780), reported by @dcoutts on 2010-12-21)

Cabal/cabal-install allows setting the install prefix and the package database. Together these allow creating isolated builds. This is clearly not sufficiently easy to use as there are now two projects that provide wrappers over cabal-install to provide more direct support for this use case:

<ul><li>[http://github.com/creswick/cabal-dev/blob/master/README.md](http://github.com/creswick/cabal-dev/blob/master/README.md)
</li><li>[http://www.haskell.org/haskellwiki/Capri](http://www.haskell.org/haskellwiki/Capri)
</li></ul>The task is to investigate what user behaviour is desired and to integrate this in the best way with Cabal/cabal-install.

This is probably related to:

<ul><li>ticket #556 about local config files (e.g. persistently setting some sandbox flag)
</li><li>ticket #734 about supporting multiple local .cabal files
</li><li>ticket #524 about supporting file, directory and url targets for packages and .cabal files
</li></ul>

**Comment by BardurArantsson** [comment]
@dcoutts This doesn't seem to be very relevant any longer. I suggest it be closed.
