### ISSUE TITLE
Our CI needs to stop using cabal 3.4, because it fails with new autoconf and prevents the actual branches being tested

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#7708]
See #7707.

We should probably switch to 3.6.2 as soon as it's released.

**Comment by Mikolaj** [comment]
That's a nice hack. But @hasufell managed to devise and test and emergency measure making network compilable again without alienating any users, so let's hope this can be pushed through ASAP and we can punt with CI update until 3.6.2 is out.

**Comment by jneira** [comment]
@Mikolaj maybe we close this as it does not reproduce in master and we will not release more 3.6series?

**Comment by Mikolaj** [comment]
Yes, you are right, it's been fixed in many ways now. Closing.
