### ISSUE TITLE
"Controlling flag assignments" section of users guide appears not to exist

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7712]
**Describe the bug**
In the ["Resolution of Conditions and Flags"](https://cabal.readthedocs.io/en/latest/cabal-package.html#resolution-of-conditions-and-flags) section of the users guide there is a link with the text "control these in several ways". The target of this link is a page which makes no mention of flags.

**To Reproduce**
Follow the indicated link.

EDIT (@andreasabel): Here is the link:
https://github.com/haskell/cabal/blob/2e64e238b76942be4b9331f2b09d3d8394c06c6d/doc/cabal-package.rst#L2511

**Comment by Mikolaj** [comment]
It seems the dangling link is there at least since a commit ""This is the result of using pandoc with default settings to convert the existing .markdown files to .rst files". Presumably markdown auto-generated such anchors from section names and pandoc does not (or did not). 

@andreasabel: why does our CI script that validates the docs not error out at such dangling links?

**Comment by Mikolaj** [comment]
To clarify, the link is really dangling, not just off-topic, because no such anchor exists and readthedocs just falls back to the start of the chapter.

**Comment by andreasabel** [comment]
> @andreasabel: why does our CI script that validates the docs not error out at such dangling links?

Good question, I need to investigate this.  Currently we run `sphinx-build` with these options, which _should_ do the right thing:

- `-n`
    Run in nit-picky mode. Currently, this generates warnings for all missing references. See the config value nitpick_ignore for a way to exclude some references as “known missing”.

- `-W`
    Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.

- `--keep-going`

    With -W option, keep going processing when getting warnings to the end of build, and sphinx-build exits with exit status 1.

**Comment by andreasabel** [comment]
The link in question is to a `html` file generated by sphinx.  It seems that such links are not checked by sphinx.  
This is anyway not the recommended way to link, as it breaks e.g. for the PDF version.  Here is the docs on how to link: https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html
We should replace all such `html` links by proper cross-references.

**Comment by andreasabel** [comment]
Cabal developer discussion 2022-01-13 (jitsi): Gershom suggest to link to the latest hackage publication of Cabal using redirects like:  https://hackage.haskell.org/package/Cabal/docs/Distribution-Backpack-DescribeUnitId.html
