### ISSUE TITLE
`cabal man` does not work on macOS

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7714]
Re #6548:

`cabal man` does not work on macOS
```
$ cabal man 
man: invalid option -- l
man, version 1.6c

usage: man [-adfhktwW] [section] [-M path] [-P pager] [-S list]
	[-m system] [-p string] name ...

  a : find all matching entries
...
fd:13: commitBuffer: resource vanished (Broken pipe)
```

Also, there is a typo in an error message:
```
$ cabal man happy
Error: cabal: 'manpage' doesn't take any extra arguments: happy
```

**Comment by andreasabel** [comment]
Something that might be more portable is piping into `groff`:
```
$ cabal man --raw | groff -Tutf8 -i | less
```
(That looks horrible.  But even the HTML rendering is horrible.)

However, the output of `cabal man` is not well-formatted, it seems:
```
$ cabal man --raw | groff -Tutf8 -i > /dev/null 2> man-errors.txt
$ cat man-errors.txt 
<standard input>:3825: warning: macro `new-repl'' not defined (probably missing space after `ne')
<standard input>:20376: warning: macro `new-build',' not defined (probably missing space after `ne')
<standard input>:20381: warning: macro `new-build' not defined (probably missing space after `ne')
```

Quick fix is to drop the piping into `man` part and make `--raw` the default.

Then folks can choose their OS-specific rendering of their taste.

**Comment by andreasabel** [comment]
Here is man's man page for BSD: https://www.freebsd.org/cgi/man.cgi?query=man

@fgaz wrote:
> does `cabal man --raw | man /dev/stdin` work?

Thanks indeed, this works, yet without formatting.

However, this is of limited use because:
```
$ cabal man --raw | wc
   54621  126439  871117
```
`cabal man` produces a 50kloc text!  Not sure that this meets the intuitive expectations of a man page.

It seems like every option is repeated for each command.  The text is highly redundant:
```
$ cabal man --raw | sort | uniq | wc
    1385    7760   56194
```
So, it is inflated by a factor of >30.

What is actually the purpose of `cabal man`?  Dump the whole help text rather than exploring it via the `--help` flag?

Is it used to automatically produce man-pages for some distro?


@gbaz wrote:
> What about using nroff instead of groff as in [unix.stackexchange.com/a/313110](https://unix.stackexchange.com/a/313110) ?

Thanks, this actually produces nice formatting.
```
$ cabal man --raw | nroff -man /dev/stdin | less
```

It still suffers from the redundancy problem, though.

**Comment by gbaz** [comment]
I think this is a lot of hoops to jump through for a rarely used command that doesn't seem particularly important for most purposes? I'm in favor of doing a basic fix to it, but unless we already have infrastructure in place to lookup a pager etc, probably overkill.

**Comment by fgaz** [comment]
Oh for sure, I just meant that the fix shouldn't be at the expense of other users, like in linux, where `man` is ubiquitous and respects `$PAGER`, but `groff` isn't.

I wasn't actually proposing to check for `$PAGER`, just to case on the platform, which would be strictly an improvement for all users.

**Comment by hasufell** [comment]
apparently, this also happens on BSD

**Comment by fgaz** [comment]
@hasufell feel free to review #7726 ;)
