### ISSUE TITLE
Extend new dogfooding ci job to linux and macos

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#7742]
* The motivation is clear: cabal HEAD should be able to install istself including its dependencies. It wuld cover the build of important libs for the ecosystem like network
* The job was initially added for windows by @Mikolaj 

https://github.com/haskell/cabal/blob/69f62284bb46af37d860c82eb0d55506b80ea281/.github/workflows/windows.yml#L72
https://github.com/haskell/cabal/blob/69f62284bb46af37d860c82eb0d55506b80ea281/.github/workflows/windows.yml#L168

* Ideally those jobs should reuse the cabal excutable buils in the previous step. The usual way is upload and download it as a workflow artifact

**Comment by Mikolaj** [comment]
Actually, as @hasufell rightly points out, we'd benefit from extending this to all architectures suppported by cabal, either on GHA or gitlab CI or whenever else we can set it up.

**Comment by andreabedini** [comment]
After #7952 we are now testing dogfooding on linux, macos and windows. I belive this can be closed.
