### ISSUE TITLE
`cabal install` does not accept relative dirs in `--store-dir` (but `cabal build` does)

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#7760]
**Describe the bug**
You can use relative dirs in `--store-dir` for `cabal build` but no for `cabal install`

**To Reproduce**

```
$ cabal --store-dir=./relative v2-install 
```

actual log

```
D:\ws\haskell\cabal-test>cabal --store-dir .\sr install --builddir dist2
Wrote tarball sdist to
D:\ws\haskell\cabal-test\dist2\sdist\cabal-test-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - say-0.1.0.1 (lib) (requires build)
 - cabal-test-0.1.0.0 (lib) (requires build)
 - cabal-test-0.1.0.0 (exe:cabal-test) (requires build)
Configuring library for say-0.1.0.1..
cabal-3.6.2.0.exe: expected an absolute directory name for --prefix:
.\sr\ghc-8.6.5\say-0.1.0.1-f56dd8dcb828e676e2fe979752cedce7d5e3ea47
```

**Expected behavior**
`cabal install` should accept relative dirs in `--store-dir` like `cabal build`

**System information**
 - windows
 - `cabal-3.6.2.0`, `ghc` versions: any

**Additional context**

* bug found investigating https://github.com/haskell/cabal/issues/7745#issue-1024878468
* maybe related with #4097

**Comment by andreasabel** [comment]
Looks like I duplicated your issue in #7812.

**Comment by jneira** [comment]
Duplicate of #7812
