### ISSUE TITLE
Cabal incorrectly constructs libHSrts library path

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7763]
**Describe the bug**

A recent GHC bug ([#20520](https://gitlab.haskell.org/ghc/ghc/-/issues/20520)) brought to light the fact that Cabal includes knowledge of internal implementation details of GHC (specifically, the particular file name of `libHSrts`). This appears to have been introduced by 382143aa73 and 1c07f8354b8e3c9900a5a913334bc9831ed7f7a8.

This naming is unstable and has indeed changed in recent releases, hence the ghc#20520.

**Comment by Mikolaj** [comment]
@bgamari: any news? #7747 is nearing completion, so soon we should be able to test foreign libraries with master branch.

**Comment by Bodigrim** [comment]
@bgamari it would be nice to fix this in time for GHC 9.2.2, otherwise Windows users are likely to be stuck with GHC 8.10 indefinitely.

**Comment by Bodigrim** [comment]
@Mikolaj could Cabal maintainers please take the lead in resolving this?

**Comment by Mikolaj** [comment]
Easily said. Let me beg @bgamari some more... :)

**Comment by Bodigrim** [comment]
@Mikolaj see https://gitlab.haskell.org/ghc/ghc/-/issues/20520#note_411402, I believe Ben can use help from the core team.

**Comment by hasufell** [comment]
Which Cabal (library) version includes this fix?

**Comment by Kleidukos** [comment]
@hasufell according to GH the PR (https://github.com/haskell/cabal/pull/7764) is included in 3.8.1.0
