### ISSUE TITLE
list-bin is missing from user's manual

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#7774]
`list-bin` command, added in 3.4, is still missing from user's manual as of 3.6: https://cabal.readthedocs.io/en/3.6/cabal-commands.html.

**Comment by Mikolaj** [comment]
@ philderbeast: would you like to turn that summary into a PR? If so, don't worry about how it fits the existing docs too much --- create a new section at a likely place and dump the knowledge.

**Comment by philderbeast** [comment]
> @ philderbeast: would you like to turn that summary into a PR? If so, don't worry about how it fits the existing docs too much --- create a new section at a likely place and dump the knowledge.

Yes, happy to.

**Comment by Mikolaj** [comment]
Splendid. Thank you.
