### ISSUE TITLE
build-depends on packages that provide no library

### ISSUE THREAD

**Issue by bos** [haskell/cabal#779]
(Imported from [Trac #789](http://hackage.haskell.org/trac/hackage/ticket/789), reported by @dcoutts on 2011-01-13)

It is possible to list build-depends on packages that have just an executable and no library. Currently the behaviour of cabal-install does not consider this and it will allow such packages to be pulled in as dependencies. It leads to problems however because the non-lib package never gets registered with ghc-pkg and so it leads to re-install loops.

The solution is for cabal-install to not consider exe-only packages to be valid for satisfying a build-depends requirement. It should produce a suitable error message.

Note that it must take into account the posibility that a newer or older version of a package may switch from exe only to exe+lib or just lib, or indeed vica versa.

We should mark exe-only versions of the package as excluded with a reason. Then if the dep is not satisfiable then we can explain why all the excluded ones were excluded (ie due to not exposing a lib).

**Comment by mietek** [comment]
[Halcyon](https://halcyon.sh) supports declaring and automatically installing executable-only Cabal packages for use at build-time with the [`HALCYON_SANDBOX_EXTRA_APPS`](https://halcyon.sh/reference/#halcyon_sandbox_extra_apps) option.  Version constraints for these apps can be declared with the [`HALCYON_SANDBOX_EXTRA_APPS_CONSTRAINTS`](https://halcyon.sh/reference/#halcyon_sandbox_extra_apps_constraints) option.

Similarly, you can use [`HALCYON_EXTRA_APPS`](https://halcyon.sh/reference/#halcyon_extra_apps) and [`HALCYON_EXTRA_APPS_CONSTRAINTS`](https://halcyon.sh/reference/#halcyon_extra_apps_constraints) to declare additional apps to be installed for use at run-time.

See [Haskell Language](https://halcyon.sh/examples/#haskell-language) for an example of declaring _alex_ and _happy_ as sandbox extra apps.

**Comment by gbaz** [comment]
I'm not sure what to do with this issue. The immediate pain points are solved. On the one hand we have `build-tool-depends` so depending directly on an executable doesn't make sense. On the other, if you _do_ do so, you don't get an infinite loop, but instead a message like:

> cabal: The following package dependencies were requested
>  --dependency='cursedcsv=cursedcsv-0.1.2-7D1AGd1eXLEIeYIJLvLgpZ'
> however the given installed package instance does not exist.

So this  message could be slightly better, but other than that it seems a nonissue?

**Comment by 23Skidoo** [comment]
Leaving open as a reminder to fix the error message.

**Comment by grayjay** [comment]
I think this issue is part of per-component dependency solving (#4087).  It could be fixed by generalizing the fix for #4781 to check for required components rather than just required executables.  Implementing it in the solver would mean that cabal could try other versions of the package if the first one didn't contain a library.
