### ISSUE TITLE
cabal init crashes with `--source-dir=.`

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7806]
```
$ cabal init --lib --source-dir=.
```
After answering a long list of questions (like when you just want a Burger in an American restaurant), `cabal init` crashes when apparently trying to create the current directory:
```
Creating LICENSE...
Creating file LICENSE...
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: invalid argument (Invalid argument)
```

Related question: Does `cabal init` allow you to cabalize an existing code base?  (Does not seem so, from the error message.)

UPDATE: This seems to be a regression in 3.6.  `cabal-3.4 init` does not crash, but gives me a `.cabal` file.
CORRECTION: No, this is only a regression on `master`.  Version 3.6.2 still is correct.

**Comment by Mikolaj** [comment]
@ptkato: what do you think about this one?

**Comment by fgaz** [comment]
pinging @emilypi too

> Related question: Does cabal init allow you to cabalize an existing code base? (Does not seem so, from the error message.)

it does, or at least before the recent rewrite it did

**Comment by ptkato** [comment]
I'll look into it; @andreasabel could you please provide your project's file structure?

**Comment by andreasabel** [comment]
@ptkato: Well that was very simple.  A single module `MyLib.hs` with the following content:
```haskell
module MyLib where

greet :: IO ()
greet = putStrLn "Hello, you!"
```

**Comment by ptkato** [comment]
Huh, I don't seem to be able to reproduce that error, neither in 3.6 branch, nor master branch, nor 3.6.2.0 release.

**Comment by andreasabel** [comment]
Here is a self-contained reproducer:
```sh
#!/bin/sh

DIR=$(mktemp -d)
cd $DIR
cat > MyLib.hs <<< "module MyLib where"
cabal init -n --lib --sourcedir=.

# EOF
```
Run:
$ ./reproduce.sh 

Guessing dependencies...

Using cabal specification: 3.0

Warning: unknown license type, you must put a copy in LICENSE yourself.
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: invalid argument (Invalid argument)
```
My cabal version:
```
$ cabal --version
cabal-install version 3.7
compiled using version 3.7.0.0 of the Cabal library 
```
Recent enough `master`:
```
2021-11-08 10:56 dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/x/cabal/build/cabal/cabal
```

@ptkato : What do you get when you run the reproducer?

**Comment by ptkato** [comment]
I see, now I get the error, but it's slightly different:

```
$ ./reproduce.sh 

Guessing dependencies...

Using cabal specification: 3.6

Warning: unknown license type, you must put a copy in LICENSE yourself.
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: resource busy (Device or resource busy)

**Comment by andreasabel** [comment]
> I see, now I get the error, but it's slightly different:

Your error:
```
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: resource busy (Device or resource busy)
```
My error:
```
Warning: . already exists. Backing up old version in ..save0
.: renameDirectory:renamePath:rename: invalid argument (Invalid argument)
```
The difference seems to how the OS responds to the non-sensical request to rename `.`.

**Comment by ptkato** [comment]
Also, can this be considered a regression at all? `cabal init` was pretty much rewritten from scratch.

**Comment by andreasabel** [comment]
Well, the same command works with 3.6.2 but fails with master.  That is the classic regression.
See also #7810.  The rewritten `init` still supports the same interface, so it should behave the same.  If the rewritten `init` does something completely different, maybe it should not be called `init`, but something else, e.g. `wizard`.  Then users can choose whether they want the old `init` or the new `wizard`.
