### ISSUE TITLE
Large libraries not installable on OS X

### ISSUE THREAD

**Issue by bos** [haskell/cabal#781]
(Imported from [Trac #791](http://hackage.haskell.org/trac/hackage/ticket/791), reported by @batterseapower on 2011-01-18)

For example:

<pre class="wiki">cabal unpack highlighting-kate-0.2.8.1
cd highlighting-kate-0.2.8.1
ghc --make Setup.hs
./Setup configure
./Setup build
</pre>This fails:

<pre class="wiki">ld: scattered reloc r_address too large for inferred architecture i386
</pre>The underlying reason is that Cabal is trying to create an object file for use with GHCi, but that is not possible (see [http://hackage.haskell.org/trac/ghc/ticket/3260](http://hackage.haskell.org/trac/ghc/ticket/3260)).

Cabal's GHC.hs should not use combineObjectFiles on with GHC &gt;= 7 and OS X.

**Comment by jsl** [comment]
I just built this same package and version (`highlighting-kate-0.2.8.1`) on an OS X machine without a problem. I propose we close this ticket as something that has probably been fixed in Cabal or GHC sometime in the last few years since there is no other activity since May 2012, but please re-open if you're still having this problem. 

Below is my machine info and the build output:

```
justin ~/Code/cabal $ uname -a
Darwin uio-mbp-02.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

justin ~/Code/cabal $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

justin /tmp/testit $ cabal sandbox init
Writing a default package environment file to
/private/tmp/testit/cabal.sandbox.config
Creating a new sandbox at /private/tmp/testit/.cabal-sandbox
justin /tmp/testit $ cabal install highlighting-kate-0.2.8.1
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/testit/.cabal-sandbox
Configuring transformers-0.4.2.0...
Configuring text-1.2.0.4...
Building transformers-0.4.2.0...
Building text-1.2.0.4...
Installed transformers-0.4.2.0
Configuring mtl-2.2.1...
Building mtl-2.2.1...
Installed mtl-2.2.1
Configuring regex-base-0.93.2...
Building regex-base-0.93.2...
Installed regex-base-0.93.2
Configuring regex-pcre-builtin-0.94.4.8.8.35...
Building regex-pcre-builtin-0.94.4.8.8.35...
Installed regex-pcre-builtin-0.94.4.8.8.35
Installed text-1.2.0.4
Configuring parsec-3.1.8...
Building parsec-3.1.8...
Installed parsec-3.1.8
Downloading highlighting-kate-0.2.8.1...
Configuring highlighting-kate-0.2.8.1...
Building highlighting-kate-0.2.8.1...
Installed highlighting-kate-0.2.8.1
justin /tmp/testit $ echo $?
0

```
