### ISSUE TITLE
`cabal init` can no longer cabalize an existing project

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7810]
`cabal init` version 3.6.2 (and before) can be instructed to build a cabal file around an existing application `app/Main.hs`.
`cabal init` from master does not seem to be able to do this.

Reproducer script:
```sh
#!/bin/sh

DIR=$(mktemp -d)
cd $DIR
mkdir app
cat > app/Main.hs <<EOF
module Main where
main :: IO ()
main = putStrLn "I was there before cabal init ran!"
EOF
${CABAL:-cabal} init -v0 -n --package-name=hello-cabal --exe --application-dir=app --main-is=Main.hs
tree
cabal run -v0
```

Testing with `cabal-3.6.2`:
```
$ CABAL=cabal-3.6.2 ./reproduce.sh
...
.
├── CHANGELOG.md
├── app
│   └── Main.hs
└── hello-cabal.cabal

1 directory, 3 files
I was there before cabal init ran!
```
This is the expected behavior: a cabal package `hello-cabal.cabal` is built around `app/Main.hs`, and running via this cabal package runs this `Main.hs`.

Testing with current `master`:
```
$ ./reproduce.sh
.
├── CHANGELOG.md
├── app
│   └── Main.hs
├── app.save0
│   └── Main.hs
└── hello-cabal.cabal

2 directories, 4 files
Hello, Haskell!
```
This replaces the existing `app/Main.hs` with a standard template that prints `Hello, Haskell!` (and puts the user code into `app.save0`).

**Comment by gbaz** [comment]
We definitely should fix this -- cabalizing existing is a very important use case!

**Comment by emilypi** [comment]
@ptkato would you please look into this?
