### ISSUE TITLE
`cabal install` does not reinstall when user flags (`-f`) change 

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7814]
`cabal install` does not reinstall when user flags (`-f`) change.  In the wild:
```
$ cabal install -w ghc-9.0.1  cabal-plan
...((Success))...

$ cabal-plan license-report fix-whitespace 
ERROR: `cabal-plan license-report` sub-command not available! Please recompile/reinstall `cabal-plan` with the `license-report` Cabal flag activated.
```
Oh, forgot the `-f license-report` flag.  Ok, then:
```
$ cabal install -w ghc-9.0.1 -f license-report cabal-plan
Resolving dependencies...
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - cabal-plan-0.7.2.1 (lib) (requires build)
Configuring library for cabal-plan-0.7.2.1..
Preprocessing library for cabal-plan-0.7.2.1..
Building library for cabal-plan-0.7.2.1..
[1 of 1] Compiling Cabal.Plan       ( src/Cabal/Plan.hs, dist/build/Cabal/Plan.o, dist/build/Cabal/Plan.dyn_o )
Installing library in /Users/abel/.cabal/store/ghc-9.0.1/incoming/new-14995/Users/abel/.cabal/store/ghc-9.0.1/cbl-pln-0.7.2.1-9877695f/lib
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
* You might have wanted to add them as dependencies to your package. In this
case add "cabal-plan" to the build-depends field(s) of your package's .cabal
file.
* You might have wanted to add them to a GHC environment. In this case use
"cabal install --lib cabal-plan". The "--lib" flag is provisional: see
https://github.com/haskell/cabal/issues/6481 for more information.

$ cabal-plan license-report fix-whitespace 
ERROR: `cabal-plan license-report` sub-command not available! Please recompile/reinstall `cabal-plan` with the `license-report` Cabal flag activated.
```
_Vad fan!_ 

So, `cabal install` does not reinstall executables if the flags change.  Somehow in its subconscious mind, `cabal` notices that maybe it did not satisfy the customer fully, and issues a warning, but confuses it with a `--lib` installation request.

Atm, I do not know how to proceed, because `--reinstall` is anyway ignored:
```
$ cabal install -w ghc-9.0.1 -f license-report --reinstall cabal-plan
Resolving dependencies...
Up to date
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
...
```

**Comment by andreasabel** [comment]
Thank God for `v1-install`:
```
$ cabal v1-install -w ghc-9.0.1 -f license-report cabal-plan
```

**Comment by phadej** [comment]
> Vad fan!

Clear up your language.

---

Note there is an (automatic) `+exe` flag in `cabal-plan`. If it cannot be (easily) satisfied, it is turned off. Try with `-fexe` (or `--constraint='cabal-plan +exe`).

**Comment by andreasabel** [comment]
@phadej: I am sorry, but this is not easily discoverable:
<img width="539" alt="Screenshot 2021-11-13 at 14 10 51" src="https://user-images.githubusercontent.com/1155218/141645013-7354fa11-c896-430d-8960-2e007d092bb1.png">

There is an `exe` flag here but this is by default `Enabled`.  So why should I worry about it?  
I am not getting an alert that this flag was automatically disabled, and what the consequences of this automatic choice are.
I also did not have to supply `-fexe` when I installed without `-f license-report`.  
Flag `license-report` adds a functionality to the executable, so why should adding this flag _prevent_ installation of the executable?  This makes no sense to me.

`v1-install` does not suffer from this defective behavior (in this case).

> > Vad fan!
> 
> Clear up your language.

I already did, this is what remained.

**Comment by andreasabel** [comment]
Following the discussion, this is maybe a `cabal-plan` issue.

**Comment by phadej** [comment]
>  I am sorry, but this is not easily discoverable:

`hackage-server` developers hide automatic flags. i don't like the folding. https://github.com/haskell/hackage-server/pull/963

> Flag license-report adds a functionality to the executable, so why should adding this flag prevent installation of the executable? This makes no sense to me.

You answered it yourself: it adds functionality, and for that it adds dependencies (namely `Cabal`) which forces solver to work harder. It decides to turn automatic `-fexe` flag.

---

There are two solutions:
- fix cabal-install solver to not consider executable components when only library is asked for. This would remove the need for `-fexe` hack (preferable)
- split the executable `cabal-plan` into separate `cabal-plan-exe` package (not nice).

**Comment by phadej** [comment]
Another example is `yaml` package. Which has `no-exe` flag guarding `yaml2json` and `json2yaml` executables.

Maybe I should flip the `exe` flag in `cabal-plan` to by `False` by default.
