### ISSUE TITLE
cabal install --lib doesn't work any more with GHC 9.2

### ISSUE THREAD

**Issue by wz1000** [haskell/cabal#7819]
As mentioned by the [release notes](https://downloads.haskell.org/~ghc/9.2.1/docs/html/users_guide/9.2.1-notes.html#ghci) of GHC 9.2.1, GHC now respects the XDG specification for its user data directory (which includes package environments as well as GHCi configuration files). Howver, cabal hasn't been updated to reflect these changes yet, which means it still writes package environments to `~/.ghc`, instead of [`$XDG_DATA_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). 

This is the function in cabal that needs to be updated: https://github.com/haskell/cabal/blob/3bab1db253428e2ac7747893171e17e3e2d1e42a/Cabal/src/Distribution/Simple/GHC.hs#L373

The change to GHC was introduced in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4567

**Comment by Mikolaj** [comment]
We are working on it for a decade now: #680 (three digits!), but I guess it's time to speed it up.

**Comment by phadej** [comment]
This is not about #680, but about fixing

https://github.com/haskell/cabal/blob/5b4258cbfa536b6362c4e20578ced51676206ea8/Cabal/src/Distribution/Simple/GHC.hs#L370-L374

which would need to take the GHC version now.

**Comment by Mikolaj** [comment]
Right, so one option is to use XDG when working with GHC, but not use it when doing our own cabal things. And it seems we have good support for this distinction?

**Comment by phadej** [comment]
The release notes for 9.2.1 say:

> GHC now follows by default the XDG Base Directory Specification. If $HOME/.ghc is found it will fallback to the old paths to give you time to migrate. This fallback will be removed in three releases.

So why 9.2.1 doesn't work?

**Comment by phadej** [comment]
This is bug in GHC, I opened an upstream issue https://gitlab.haskell.org/ghc/ghc/-/issues/20684

**Comment by Mikolaj** [comment]
This seems to fix the problem, but I'm not 100% sure it's going to be backported to 9.2: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7010

**Comment by Mikolaj** [comment]
Good news, the GHC fix has just been backported and merged to GHC 9.2.2 (to be released).

**Comment by Mikolaj** [comment]
It seems we don't need to do anything, but let's keep this issue open until GHC 9.2.2 and possibly until somebody verifies it works.

**Comment by wz1000** [comment]
It would still be good to move towards respecting the XDG spec, but it is not a pressing concern as of now.

**Comment by Mikolaj** [comment]
> It would still be good to move towards respecting the XDG spec, but it is not a pressing concern as of now.

Yes, if anybody would like to help, that's be awesome. We track that work another ticket mentioned above.
