### ISSUE TITLE
cabal clean, cabal update, cabal install all return a weird list

### ISSUE THREAD

**Issue by raphipik** [haskell/cabal#7824]
**To Reproduce**
enter 'cabal clean' or 'cabal update' or any cabal command, and it returns this list (see pics attached) that seems to be related to ghc but I'm not sure. Either way, any advise or insight on how to resolve this issue would be greatly appreciated.

**Expected behavior**
that cabal would update and download latest package list from Haskell.

**System information**
 - Ubuntu 20.04.3 LTS
 - `caba 3.4.0.0`, `ghc 8.10` 

Pictures
![Screenshot1](https://user-images.githubusercontent.com/76642557/142362612-7f5b0b46-20fc-4681-bcb8-160bbca28921.png)
![Screenshot-2](https://user-images.githubusercontent.com/76642557/142362617-33208ce1-9b75-4b80-b948-3b19e40468b4.png)

**Comment by Mikolaj** [comment]
Thank you for the report. Indeed this is GHC output. How did you obtain your GHC and your cabal?

**Comment by raphipik** [comment]
Thank you for your reply.

I got my GHC and cabal from running a script from the Cardano Guild-Operators in the link below (specifically the cabal-build-all.sh script).
https://cardano-community.github.io/guild-operators/Build/node-cli/

This is the full shell script:
https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/cabal-build-all.sh

Please let me know if I can provide additional information to help.

**Comment by raphipik** [comment]
Actually I apologise, I think it was installed using this script:
https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/prereqs.sh

which is in this part of the guide:
https://cardano-community.github.io/guild-operators/basics/

**Comment by Mikolaj** [comment]
That's strange, because `--nonmoving-gc` is a legal options for ghc 8.10. What's the output of `ghc --version`? Of `ghc +RTS --nonmoving-gc`? Where is your ghc from Ubuntu and where's one downloaded by Cardano?

**Comment by raphipik** [comment]
Output for ghc --version is the following:
`The Glorious Glasgow Haskell Compilation System, version 8.10.4
`


Output for ghc +RTS --nonmoving-gc is the following:
```
ghc: no input files
Usage: For basic information, try the `--help' option.
```


For your last question I am not sure but the output of "whereis ghc" is :
`~/.ghcup/bin/ghc`

Within that same folder lies all these files (see picture attached)
![Screenshot from 2021-11-18 17-03-29](https://user-images.githubusercontent.com/76642557/142384667-8f0e7825-647c-4aac-b65f-ce5c8d9b42c2.png)

I apologise for my limited knowledge as I'm still learning,.

**Comment by phadej** [comment]
I suspect that you have [`GHCRTS`](https://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/runtime_control.html#setting-rts-options) environment variable set:

```
 % GHCRTS=--nonmoving-gc /opt/cabal/bin/cabal-3.4 --help 
cabal-3.4: unknown RTS option: --nonmoving-gc
cabal-3.4: 
cabal-3.4: Usage: <prog> <args> [+RTS <rtsopts> | -RTS <args>] ... --RTS <args>
cabal-3.4: 
```

**Comment by raphipik** [comment]
It looks like I have the following (when I use the env command):

GHCRTS=-N -T -I0 -A16m --disable-delayed-os-memory-return --nonmoving-gc

**Comment by Mikolaj** [comment]
Hmm, if cabal-3.4 doesn't accept it, probably the cabal was compiled using an older GHC. Which is fine.

How did you get that env variable into your system? If from cardano, please ask them how to reconcile the option with the old cabal (e.g., perhaps they want to bundle cabal 3.4.1 or 3.6.2). Generally, I think the best bet for you is now to ask the people from whom you got GHCRTS. Good luck!

**Comment by raphipik** [comment]
Understood! Thank you for your assistance!

**Comment by Mikolaj** [comment]
Closing the issue, but please come back and comment if the new information may be useful for future Cardano+cabal users.
