### ISSUE TITLE
First-class support for NO_COLOR in cabal-install

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#7845]
At the time of writing, end-users have a hard time toggling off the coloured output from `cabal-install`. 

I would like to implement first-class support for a CLI toggle, as well as support for the [NO_COLOR](https://no-color.org/) convention, and adhere to its semantics:

> User-level configuration files and per-instance command-line arguments should override $NO_COLOR. A user should be able to export $NO_COLOR in their shell configuration file as a default, but configure a specific program in its configuration file to specifically enable color.

Currently, users can pass `--ghc-options=-fdiagnostics-color=never`, but this is a GHC option, and when `Shake` calls `cabal-install`, the end-users can get "fd:7: hGetContents: invalid argument (invalid byte sequence)" as a result.

**Comment by Kleidukos** [comment]
cc @arafangion

**Comment by Mikolaj** [comment]
Any potential problems with this? 

How portable would that be?

Do we need ghc support? Any kind of intergration with ghc, with `fdiagnostics-color`?

**Comment by Kleidukos** [comment]
> Any potential problems with this?

None that I know of since the creation of this convention

> How portable would that be?

We would belong to an ecosystem of tools who have already adopted it. This includes in the Haskell ecosystem `stack`. Hedgehog has a [slightly different system](https://github.com/hedgehogqa/haskell-hedgehog/blob/3d4dde46e15ab25a10cac0deff03bae10ecacc4e/hedgehog/src/Hedgehog/Internal/Config.hs#L88-L108) but the intent is the same.

> Do we need ghc support? Any kind of intergration with ghc, with fdiagnostics-color?

* Do we need GHC support: Technically no, but for the full experience, `NO_COLOR` should be implemented in GHC as well. However I'd like to wait for the error message infrastructure PRs to be finished so that we're not trying to build this in a battlefield.

*  Any kind of intergration with ghc: At present time I don't think so. This may change if we determine that the user experience would benefit from this.

**Comment by Mikolaj** [comment]
So, would that work on Windows, on Mac?

Would cabal, in NO_COLOR mode, pass `-fdiagnostics-color=never` to ghc? Or the inverse, upon noticing `--ghc-options=-fdiagnostics-color=never` would cabal ingore NO_COLOR, not to collide with manual user handling of that?

**Comment by Kleidukos** [comment]
> So, would that work on Windows, on Mac?

* Windows: 
  * A linux shell in windows: yes
  * PowerShell: no idea, but since this uses stdlib.h's `getenv`, it should work
  * cmd.exe: Same remark as PowerShell
* macOS: Absolutely

**Comment by Kleidukos** [comment]
> Would cabal, in NO_COLOR mode, pass -fdiagnostics-color=never to ghc?

I don't know if we want to do such a thing before GHC supports NO_COLOR.  
That being said I could see this happening with the `allow-colors=(auto|always|never)` flag.

> Or the inverse, upon noticing --ghc-options=-fdiagnostics-color=never would cabal ingore NO_COLOR, not to collide with manual user handling of that?

Yes, the algorithm for NO_COLOR mandates that it is overridable by user-provided flags.

**Comment by phadej** [comment]
If there is `NO_COLOR` set, why GHC wouldn't adhere to it? Why should `cabal` care?

**Comment by phadej** [comment]
> and when Shake calls cabal-install, the end-users can get "fd:7: hGetContents: invalid argument (invalid byte sequence)" as a result.

Sounds like a bug (in Shake, or maybe GHC). The default `-fdiagnostics-color=auto` should output color markers only when the output file descriptor is a (pseudo)terminal. If `shake` captures the output of `cabal` and its child processes, there shouldn't be color.

That error sounds like locale issue, and arguably Shake shouldn't read cabal's nor GHCs output as text, there is no need to.

**Comment by Kleidukos** [comment]
> If there is NO_COLOR set, why GHC wouldn't adhere to it?

It's not a matter of principle, at the time of writing, GHC doesn't know about NO_COLOR.

> Why should cabal care what the tools do or don't?

I don't understand what you are talking about, `cabal-install` *is* a tool.

**Comment by phadej** [comment]
`cabal-install` could adhere to its *own* output. That I agree on. But IMO it shouldn't learn about every tool (e.g. `clang` and `ghc` could output colorful warnings too, it's IMO just too much to teach cabal about)

> It's not a matter of principle but a statement of fact: at the time of writing, GHC doesn't know about NO_COLOR.

So change GHC. The less `cabal` does stuff the better.

**Comment by fgaz** [comment]
I agree with @phadej. If cabal ever starts outputting colors on its own then it can support that variable (since it'd be already checking the terminal type), but this sounds like an upstream issue that should be addressed in ghc, hedgehog, etc

**Comment by Kleidukos** [comment]
Very well, I'll bump this ticket when cabal is able to output colours on its own. :)
