### ISSUE TITLE
Add Eq to DependencyMap (was: Please add `Ord` instance to `Dependency`)

### ISSUE THREAD

**Issue by bitc** [haskell/cabal#7849]
Cabal library has a type [Distribution.Types.Dependency.Dependency](https://hackage.haskell.org/package/Cabal-3.6.2.0/docs/Distribution-Types-Dependency.html#t:Dependency).

This type has `Eq` instance (and a bunch of other instances), but is missing `Ord` instance.

Please add `Ord` instance, so that we can use this in sets and as a key in maps.

I think this will be as simple as adding `deriving (Ord)` to `VersionRange` and to `Dependency`

Thank you

**Comment by fgaz** [comment]
Hmm, this would require adding an Ord instance to VersionRange too, which makes no sense. It's really unfortunate that "ordering for use in containers" is the same as "semantic ordering".

What is the use case for this, if I may? Could you get away with using `(PackageName, NonEmptySet LibraryName)` as key?

**Comment by bitc** [comment]
> "meaningful ordering"

Does the `Ord` type class really instruct that the the ordering must be meaningful?

**Comment by fgaz** [comment]
It does not, but I can see how adding `Ord` to `VersionRange` could lead to bugs. For example, one could compare two `VersionRange`s thinking they are `Version`s. On the other hand, I don't see how a `VersionRange`, which does not have a normal form, could ever be useful as a key, and that's why I asked for a use case.

**Comment by bitc** [comment]
My use case is that I am developing some build tooling on top of cabal. I want to check check if dependencies changed, so I parse the cabal file and save all the `Dependency`s, and then when the cabal file changes I want to see if any of the dependencies changed, so I figure a `Set` is the best way to compare

**Comment by gbaz** [comment]
I think fgaz's suggestion would be a clean way to do this -- a map keyed by packagename, or (packagename, nonemptyset libname).

**Comment by phadej** [comment]
https://hackage.haskell.org/package/Cabal-3.6.2.0/docs/Distribution-Types-DependencyMap.html#t:DependencyMap

```haskell
newtype DependencyMap = DependencyMap { unDependencyMap :: Map PackageName (VersionRange, NonEmptySet LibraryName) }
```

that type should be used more. (And it could/should have `Eq` / `Ord`).

**Comment by gbaz** [comment]
So it sounds like the action items are 1) adding Eq to that type, and 2) highlighting it in appropriate documentation of the Dependency type or similar so its easier to find.

**Comment by fgaz** [comment]
@bitc would that work for you?

**Comment by bitc** [comment]
> @bitc would that work for you?

Yes, this all looks very good. Thank you very much
