### ISSUE TITLE
Inconstent tagging of releases (Cabal/cabal-install)

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#7855]
For a long time both `Cabal` and `cabal-install` got separate release tags of the form:

```
Cabal-v3.2.0.0
```
or
```
cabal-install-v3.2.0.0
```

In the 3.4.0.0 release we got

```
Cabal-v3.4.0.0
```

but no `-v` prefix for the cabal-install release.

```
cabal-install-3.4.0.0
```

fast forward to 3.6 then there is the tag

```
Cabal-v3.6.0.0
```

but no corresponding tag for `cabal-install-v3.6.0.0`

Proposal: Create tags with a consistent naming policy for 3.4/3.6 and future releases.

**Comment by Mikolaj** [comment]
I see we also don't have any tag for Cabal or cabal-install 3.4.1.0. Perhaps these are just not pushed? It's quite unintuitive that you have to do `git push --tags`.

@emilypi, @hasufell: do you have any such unpushed tags? Would you like to me create them and push?

**Comment by hasufell** [comment]
> do you have any such unpushed tags?

Nope... the release was done in panic on a weekend. I have no memories whatsoever.

**Comment by Mikolaj** [comment]
OK, if you don't mind I will create the missing tags for 3.4 and 3.6 (in addition to the irregularly named tag, in case somebody links to it).

**Comment by jneira** [comment]
I think it is really necessary document the release process with a comprehensive check list of manual steps which have to be done. Then it could be used to find the pain points and opportunities for improve automation of the process or more general changes. With the goal of make the release process lightweight enough to being able to do releases more often.

One way to do it is change the person in charge of coordinate the release, in my experience it helps a lot to identify those pain points.

**Comment by Mikolaj** [comment]
@hasufell: has no memories whatsoever of the emergency patching release procedure, but @emilypi reported preparing her checklist before the normal release(s) and, I hope, amending the notes afterwards, so it would be a great source material to update release-checklist.md with.

**Comment by hasufell** [comment]
I believe the 3.4.1.0 binaries are from this pipeline: https://gitlab.haskell.org/haskell/cabal/-/pipelines/42060

So that commit to tag would be https://github.com/haskell/cabal/commit/12f6894cfb154b256342c57348cb754bb18d073d which indeed is the latest commit on the 3.4 branch https://github.com/haskell/cabal/tree/3.4

**Comment by Mikolaj** [comment]
@hasufell: thank you!

**Comment by Mikolaj** [comment]
I've got no more clues from anybody, so I've added the following tags:

Cabal-v3.4.1.0
cabal-install-v3.4.1.0
cabal-install-v3.4.0.0
cabal-install-v3.6.2.0 (approximate, which kind of defeats the purpose of tags, could have been a commit or two earlier, but not later; there is no corresponding complete pipeline job, so hard to guess)

I didn't even try to guess where cabal-install-v3.6.0.0 could be, so it will be missing forever. However, it was a short-lived release with bugs merged in by yours truly. There was no cabal-install-v3.6.1.0 release, so it's fine that it's not there.

**Comment by Mikolaj** [comment]
@jneira: do you think it would make sense to create a separate ticket out of your comment?

@mpickering: thank you for the report. Please keep them coming. 

Closing.

**Comment by hasufell** [comment]
I think the main action point here is to inflict more feeling of guilt for the ones doing releases.

So far, this has worked great, I can attest.

**Comment by Mikolaj** [comment]
@hasufell: I'm sorry you are taking it this way. This wasn't my intention, but perhaps my choice of words here and there was unfortunate. We are all grateful for the work of release managers and I think we expressed this many times explicitly and nobody needs to read it between the verses.

I do encourage you to treat me analogously if/when I make releases and in whatever else I'm doing. I want to be accountable, to improve in details, to reflect on the effects of my past greater decisions in order to make better ones in the future, etc.

**Comment by hasufell** [comment]
@Mikolaj i was taking this jokingly 😂

**Comment by Mikolaj** [comment]
*Phew*. I need to rest. I'm becoming a boring, serious, pointy-haired dude (the last bit is so true). Thank God that Christmas is near. :D
