### ISSUE TITLE
Feature request: granular v2-clean 

### ISSUE THREAD

**Issue by TeofilC** [haskell/cabal#7857]
**Motivation** 
As far as I know cabal currently only supports wiping out all build artefacts.
Yet, I'm often in a situation where I only want to do this to a package or component. 

This can be worked around by doing something like `rm -r dist-newstyle/$PACKAGE`, but it would be nice if `cabal-install` supported this directly.

**Proposal**
`cabal clean` when not given any further arguments stays as it is.

`cabal clean [targets]` wipes out only the build artefacts for `targets`.

If this sounds reasonable I'd be happy to give implementing it a go.

**Comment by gbaz** [comment]
Seems reasonable enough. My one question/concern would be the proper behavior if one is cleaning something lower in the build tree -- I'd think that "clean" would have to calculate that it needs to also clean the things dependent on it -- i.e. if one has a library, with a dependent executable, cleaning the lib would necessarily also mean cleaning the exe.

**Comment by jneira** [comment]
This could be aligned with some discussion around #7851 about implementing `cabal clean script.sh`

**Comment by bacchanalia** [comment]
This overlaps directly with the work I'm doing right now on scripts as is affects both how targets are calculated and the clean command.

**Comment by michaelpj** [comment]
Dupe? https://github.com/haskell/cabal/issues/7506

**Comment by TeofilC** [comment]
What's the procedure for duplicate tickets? Should this be closed in favour of the pre-existing one?

**Comment by Mikolaj** [comment]
Duplicate #7506

**Comment by Mikolaj** [comment]
Duplicate of #7506

**Comment by Mikolaj** [comment]
@TeofilC: if you are satisfied the other ticket covers your needs, please do close this one and keep the discussion/work alive on the other one. Thank you for your feedback!

**Comment by TeofilC** [comment]
Sounds good to me!
