### ISSUE TITLE
Feature Request: Ability to get the dependencies depending on a feature flag.

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#7860]
Currently, with the information Cabal gives us, we are able to get the dependencies of a particular library or executable in a Cabal package.

However, I don't think we are able to trace the origin of a dependency to a flag, as (for example) [Cargo does](https://doc.rust-lang.org/cargo/reference/features.html). 

## Current Situation

On Hackage, this translates to the following:

On the [`aeson`](https://hackage.haskell.org/package/aeson) package, the `bytestring-builder` flag enables an optional dependency on `bytestring-builder` for backward compatibility. It is expressed as such in the cabal file:

```cabal
  if flag(bytestring-builder)
    build-depends:
        bytestring          >=0.9    && <0.10.4
      , bytestring-builder  >=0.10.4 && <1
      …
```

However, `bytestring-builder` does not appear in the "Dependencies" section of the package page.  

## Problem

I think this is a problem because it does not offer a clear, automatically-generated overview of the potential dependencies of a package, nor a simple way to signal that such or such dependency is triggered by a flag. This role is left to the free-form documentation and I should not.

## Discussion axis

I don't know if it's realistically possible to extract build dependencies that are behind flags without incurring brain damage to the implementer.
The current conditional syntax in the cabal format seem to privilege flexibility and text insertion similar to CPP.

Maybe this warrants a more "condensed", dedicated syntax like Cargo's? In any case, this is definitely something I'd see happen in Cabal 4.
Something like this:

```cabal
flag bytestring-builder
  description:
    Depend on the bytestring-builder package for backwards compatibility.

  default:     False
  manual:      False
  component-depends: 
    aeson:lib: 
      bytestring-builder  >=0.10.4 && <1
```

I'm not wedded to this format, but here you can see that:

* `build-depends` is not used because that would be confusing to have the component name in the `build-depends` block, as opposed to the 
* components are explicitly named 
* optional dependencies are centralised

But this incurs complexity in the parser and the metadata unification.  
Maybe the current format just can't allow it and we'll have to design a new way to do in an alternative format.

**Comment by fendor** [comment]
> I don't know if it's realistically possible to extract build dependencies that are behind flags without incurring brain damage to the implementer.

LOL

> The current conditional syntax in the cabal format seem to privilege flexibility and text insertion similar to CPP.

I agree with this sentiment, allowing CPP level of flexibility makes pretty much everything harder.

>  Something like this:

How is this used in the different sections? If it is just a normal flag, then you still need to do something with it.
Maybe an entry such as `feature-flags: bytestring-builder` for each section?

--- 

I also like the idea of a proper syntax for feature-flags. However, in combination with other flags, I predict the outcome is going to be unreliable. I.e. what happens here:

```
flag new-bytestring
  ...

flag bytestring-builder
  description:
    Depend on the bytestring-builder package for backwards compatibility.

  default:     False
  manual:      False
  component-depends: 
    aeson:lib:
      if flag(new-bytestring):
         bytestring  >=0.10.4 && <1
      if not flag(new-bytestring):
         bytestring-builder  >=0.10.4 && <1
```

Now, the dependencies imposed by a feature flag might change based on the value of another flag.
You can probably achieve this by only conditionally allowing feature-flags. But maybe if people do that, they deserve the non-ideal documentation?

Another idea, a feature-flags usually require some sort of CPP to conditionally enable code-paths, maybe make it first-class to pass in some CPP constant that can be used in Haskell code?

**Comment by Kleidukos** [comment]
> How is this used in different sections? If it is just a normal flag, then you still need to do something with it.
Maybe an entry such as feature-flags: bytestring-builder for each section?

Yes I'm just extending the 'Flag' block. 
What we'd be doing would to remove the insertion of `build-depends` in the sections and centralise everything.

> However, in combination with other flags, I predict the outcome is going to be unreliable

So, that's the other problem. :grimacing: 

At some point I swear I'm going to prototype with an embedded Prolog interpreter just like [YarnJS](https://yarnpkg.com/features/constraints) does.

**Comment by fgaz** [comment]
Wouldn't this be solved by just traversing the GenericPackageDescription and collecting conditions along the way?

**Comment by Kleidukos** [comment]
@fgaz I'm far from certain, but this is my lack of familiarity with the data structure that speaks here.

**Comment by fgaz** [comment]
Really, it's simpler than it seems. A few pointers:

https://github.com/haskell/cabal/blob/cc598812da41e4ad6103d9f65eece558071c28be/Cabal/src/Distribution/Types/GenericPackageDescription.hs#L34-L62

https://github.com/haskell/cabal/blob/cc598812da41e4ad6103d9f65eece558071c28be/Cabal/src/Distribution/Types/CondTree.hs#L35-L80

**Comment by gbaz** [comment]
This is really for hackage, not cabal. I think the difficulty is not traversing the GPD to extract this information, but rather that displaying all this information in a usable way is a rather tricky UI question.

cf https://github.com/haskell/hackage-server/issues/809 and https://github.com/haskell/hackage-server/issues/843

**Comment by Kleidukos** [comment]
@gbaz I'm asking here because I'm looking into using `Cabal` outside of Hackage.

**Comment by phadej** [comment]
the latest `aeson` **library** doesn't depend on `bytestring-builder`. Thanks for point out, the test-suite shouldn't either.

However if you look at older  `aeson` release, e.g. `1.0.0.0`: https://hackage.haskell.org/package/aeson-1.0.0.0 it has `bytestring-builder` in the list, even the dependency is conditional.

**Comment by phadej** [comment]
... and by cleaning on `[details]` in the dependencies, you'll see the https://hackage.haskell.org/package/aeson-1.0.0.0/dependencies page, which shows the dependency origin:

![Screenshot from 2021-12-08 19-15-45](https://user-images.githubusercontent.com/51087/145253318-2eb2edb2-a7d7-4baf-936a-8a1d0be540b2.png)

**Comment by Kleidukos** [comment]
I see, thank you very much @phadej

**Comment by gbaz** [comment]
If that answers it, can we close?

**Comment by Kleidukos** [comment]
Yep'
