### ISSUE TITLE
Feature Request: Allow leading comma for first entry of `default-extensions`

### ISSUE THREAD

**Issue by TOTBWF** [haskell/cabal#7864]
Conveniently, `cabal` allows us to give a leading comma when specifying `build-depends`, like so:
```cabal
    build-depends:
            , base
            ...
```

This makes it easy to add new build dependencies, without having to muck with removing and adding commas.

One would expect we could do something similar for other stanzas. However, this is not the case. For instance, attempting to do so with `default-extensions` will cause an error:
```cabal
    default-extensions:
        , DerivingStrategies
```
```
test.cabal:48:9: error:
unexpected ','
expecting white space, "\"" or end of input

   47 |     default-extensions:
   48 |         , DerivingStrategies
      |         ^
```

For both the sake of consistency and convenience, it would be great if cabal supported leading commas here, as well as any other applicable stanzas.

**Comment by Mikolaj** [comment]
Could you try if this is already done in higher `cabal-version` standard numbers? (#5713)

**Comment by TOTBWF** [comment]
This does indeed work with higher version numbers.

However, it seems that the version generated by `cabal init` is too low to support this. Perhaps it's time to think about bumping that?

**Comment by Mikolaj** [comment]
I see in the past one could choose the version: https://github.com/haskell/cabal/issues/5713#issuecomment-441352380

Isn't there an option for that now?

**Comment by phadej** [comment]
My plan was to disallow commas in `default-extensions` and `other-extensions`, you don't need commas there.

**Comment by phadej** [comment]
that said... https://cabal.readthedocs.io/en/3.6/file-format-changelog.html#cabal-version-3-0 says

> Allow redundant leading or trailing commas in package fields with optional commas, such as `library:exposed-modules`

(that includes `default-extensions` and `other-extensions`).

**Comment by Mikolaj** [comment]
I was probably unclear: @TOTBWF: is there an option for `cabal init` that let's you choose which cabal format version gets used? And if there is, would that be enough for you, or do you propose a different default?

**Comment by TOTBWF** [comment]
I'm of the opinion that the default used by `cabal init` should be an up to date format, so whatever you all feel is best.

**Comment by Mikolaj** [comment]
I know the up to date formats require some features and then spam about them being experimental, because we are not able to finish them yet (that's true at least about specifying visibility of multiple libraries). @ptkato: is that why the default is a rather old format? 

However, I hope it's easy enough to bump the format manually. @TOTBWF: does it work for you fine? Does `cabal init` try to overwrite the format back to default on subsequent invocations?

**Comment by phadej** [comment]
@Mikolaj previously it was bumped to 2.4 cause that was the latest format Hackage supported.

Currently, https://github.com/haskell/hackage-server/blob/master/hackage-server.cabal#L116, the latest seems to be `Cabal-3.2`, i.e. ` cabal-version: 3.0` (as there isn't `cabal-version: 3.2`)

**Comment by Mikolaj** [comment]
@phadej: oh, thank you.

@TOTBWF: actually, which cabal version do you use? And which exactly `cabal-version` number `cabal init` produces for you? Could you try with dev version (master branch)?

**Comment by ptkato** [comment]
@Mikolaj, at least in master, the default cabal version for `cabal init` should be 3.0.

**Comment by Mikolaj** [comment]
> @Mikolaj, at least in master, the default cabal version for `cabal init` should be 3.0.

Oh, good to know. I guess that's fine. Newbies probably don't use multiple libraries.

**Comment by Mikolaj** [comment]
> @TOTBWF: actually, which cabal version do you use? And which exactly `cabal-version` number `cabal init` produces for you? Could you try with dev version (master branch)?

@TOTBWF: Is this issue solved for you? Can we close?

**Comment by Mikolaj** [comment]
Closing. Please re-open if needed.
