### ISSUE TITLE
super-exponential explosion of --repl-options

### ISSUE THREAD

**Issue by bacchanalia** [haskell/cabal#7867]
**Describe the bug**
When passing multiple --repl-options to cabal repl they get replicated super-exponentially

**To Reproduce**
```
$ cabal v2-repl --repl-options="A" --repl-options="B"
```
or if you want to see 2^15-1 errors
```
$ cabal v2-repl --repl-options="A" --repl-options="B" --repl-options="C" --repl-options="D" 2>&1 | grep error | wc -l
Prelude> :q
```

**Expected behavior**
Each option is passed once.

**System information**
 - nixos
 - `ghc-8.10.7`
 - `cabal` HEAD

**Additional context**
Introduced after 3.6.2.0

**Comment by bacchanalia** [comment]
This seems to fix it, but still not sure exactly why it was causing the exact bad behavior, so it might be masking a second issue.
```diff
--- a/Cabal/src/Distribution/Simple/Setup.hs
+++ b/Cabal/src/Distribution/Simple/Setup.hs
@@ -1700,7 +1700,7 @@ instance Monoid ReplOptions where
   mappend = (<>)
 
 instance Semigroup ReplOptions where
-  (<>) = gmappend
+  _ <> r = r
 
 data ReplFlags = ReplFlags {
     replProgramPaths :: [(String, FilePath)],
```
Even if we don't want to keep the left arg to (<>), why is (<>) getting called enough for us to see the 2^(2^n) behavior?

**Comment by bacchanalia** [comment]
The offending commit is 785ea62d2

**Comment by bacchanalia** [comment]
It was the option parser, which makes sense. Fix:
```diff
diff --git a/Cabal/src/Distribution/Simple/Setup.hs b/Cabal/src/Distribution/Simple/Setup.hs
index 6ed08e7ed..bfd020b62 100644
--- a/Cabal/src/Distribution/Simple/Setup.hs
+++ b/Cabal/src/Distribution/Simple/Setup.hs
@@ -1808,7 +1808,7 @@ replOptions _ =
     trueArg
   , option [] ["repl-options"]
     "use this option for the repl"
-    replOptionsFlags (\p flags -> flags { replOptionsFlags = p ++ replOptionsFlags flags })
+    replOptionsFlags (\p flags -> flags { replOptionsFlags = p })
     (reqArg "FLAG" (succeedReadE (:[])) id)
   ]
 ```

**Comment by jneira** [comment]
ugh, thanks for the fix, would you mind open a new pr with the fix? a regression test would be great but not mandatory imo (it could be add in another one)

**Comment by andreasabel** [comment]
@bacchanalia Thanks for the fix!  I ran into this today when trying `ghcid`, which would hang with my version of `cabal` from `master`.  After pulling your fix from `master`, the problem disappeared!
