### ISSUE TITLE
Allow `cabal init` to create a new project directory

### ISSUE THREAD

**Issue by konsumlamm** [haskell/cabal#7871]
Currently, `cabal init` initializes a new project in the current directory. It would be nice if it could also create a new directory where the project is located, so that one doesn't have to do that manually, similar to `stack new`. This could also be a new `cabal new` command.

**Comment by Mikolaj** [comment]
Or `cabal init new`? @ptkato: what do you think? Perhaps this is already possible somehow?

**Comment by ptkato** [comment]
I don't think it's possible as it is right now; however I also don't think it would be a hard feature to implement at all. I'll come up with a PR. About the command, I'm not sure about neither `cabal init new` or `cabal new`, I believe that it might fit better to define it as a flag.

**Comment by bacchanalia** [comment]
`cabal init` currently takes no arguments. Instead it could take one optional argument which is the name of the directory to create and init in, and the behavior with no arguments would stay the same (init in the current directory).

**Comment by ptkato** [comment]
There we go, yes, using the extra arguments is way more self-contained.
