### ISSUE TITLE
Allow `cabal build` in subdirectories

### ISSUE THREAD

**Issue by konsumlamm** [haskell/cabal#7875]
Currently, you can't use `cabal build` in a subdirectory (e.g. `app/` when generating a default project). It gives the following error message:
```
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```
I would expect cabal to search the parent directories for a `.cabal` file to use.

**Comment by Mikolaj** [comment]
How about `cabal.project` file to use, especially if there is one in the current directory? How about `dist-newstyle`?

Is the motivation to avoid one `cd ..` or this a special use case where changing the directory is problematic (e.g,. to use a different `cabal.project` or build dir)?

**Comment by fgaz** [comment]
Yeah, determining the correct builddir is not trivial and could even be ambiguous. If you create a `cabal.project` file at the root of your project though, then you'll be able to invoke cabal in any subdirectory. `cabal.project` is the source of truth for project root position

**Comment by konsumlamm** [comment]
> Is the motivation to avoid one `cd ..`

Yes, although often it's more like `cd ../../..`.

> If you create a `cabal.project` file at the root of your project though, then you'll be able to invoke cabal in any subdirectory.

With a `cabal.project` file, invoking `cabal build` still doesn't work, although `cabal build exe` does. Is this intended?

**Comment by Mikolaj** [comment]
Could you try with version from master branch?

**Comment by konsumlamm** [comment]
Ok, `cabal build <project name>` seems to work on the mater branch.

**Comment by Mikolaj** [comment]
@konsumlamm: is there anything else to do? If not, could you close the ticket? Thank you for verifying the functionality you need works as expected (though it won't very released tomorrow; I hope you can use the dev version till then).

**Comment by konsumlamm** [comment]
Just `cabal build` still doesn't work in subdirectories, would it be possible to automatically determine the project name (using `project.cabal`)? If that is not trivial or ambigiuous, feel free to close this issue.

This is not so critical that I need to use the dev version, I can just wait until it's released.

**Comment by Mikolaj** [comment]
No bite, so I guess people are busy with urgent stuff for now. Thank you again for the report. Closing.

**Comment by fgaz** [comment]
@konsumlamm you could also use generic targets like `all` and `exes`
