### ISSUE TITLE
cabal.exe: Could not resolve dependencies with --lib flag on Windows

### ISSUE THREAD

**Issue by Chaman-veteran** [haskell/cabal#7887]
Using PowerShell (Admin) to install the package parallel I tried to do : `cabal install parallel` which finished with

```
Resolving dependencies...
Up to date
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
* You might have wanted to add them as dependencies to your package. In this
case add "parallel" to the build-depends field(s) of your package's .cabal
file.
* You might have wanted to add them to a GHC environment. In this case use
"cabal install --lib parallel". The "--lib" flag is provisional: see
https://github.com/haskell/cabal/issues/6481 for more information.
```

Then I tried with the --lib flag and here's what I get :

```
cabal install --lib parallel
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: binary-0.8.9.0/installed-0.8.9.0 (user goal)
[__1] next goal: bytestring (user goal)
[__1] rejecting: bytestring-0.11.2.0 (constraint from user target requires
==0.11.1.0)
[__1] trying: bytestring-0.11.1.0/installed-0.11.1.0
[__2] next goal: deepseq (user goal)
[__2] rejecting: deepseq-1.4.6.1 (conflict: bytestring =>
deepseq==1.4.6.0/installed-1.4.6.0)
[__2] rejecting: deepseq-1.4.5.0, deepseq-1.4.4.0, deepseq-1.4.3.0,
deepseq-1.4.2.0, deepseq-1.4.1.2, deepseq-1.4.1.1, deepseq-1.4.1.0,
deepseq-1.4.0.0, deepseq-1.3.0.2, deepseq-1.3.0.1, deepseq-1.3.0.0,
deepseq-1.2.0.1, deepseq-1.2.0.0, deepseq-1.1.0.2, deepseq-1.1.0.1,
deepseq-1.1.0.0, deepseq-1.0.0.0, deepseq-1.4.6.0/installed-1.4.6.0,
deepseq-1.4.6.0 (constraint from user target requires ==1.4.6.1)
[__2] fail (backjumping, conflict set: bytestring, deepseq)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: binary, deepseq, bytestring, ghc,
unbuildable
Try running with --minimize-conflict-set to improve the error message.
```

The --minimize-conflict-set give me this :

```
cabal install --lib --minimize-conflict-set parallel
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: deepseq-1.4.6.1 (user goal)
[__1] next goal: ghc (user goal)
[__1] rejecting: ghc-9.2.1/installed-9.2.1 (conflict: deepseq==1.4.6.1, ghc =>
deepseq==1.4.6.0/installed-1.4.6.0)
[__1] trying: ghc-9.2.1
[__2] unknown package: unbuildable (dependency of ghc)
[__2] fail (backjumping, conflict set: ghc, unbuildable)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: deepseq, ghc, unbuildable
```

I precise that I've done cabal update already and I'm using The Glorious Glasgow Haskell Compilation System, version 9.2.1.

I talked about my issue on StackOverflow here : https://stackoverflow.com/questions/70473553/cabal-exe-could-not-resolve-dependencies-with-lib-flag-on-windows

A kind person told me to add the --allow-newer flag. Here's what I get with it : 
`cabal.exe: Could not resolve dependencies: [__0] trying: deepseq-1.4.6.1 (user goal) [__1] next goal: ghc (user goal) [__1] rejecting: ghc-9.2.1/installed-9.2.1 (conflict: deepseq==1.4.6.1, ghc => deepseq==1.4.6.0/installed-1.4.6.0) [__1] trying: ghc-9.2.1 [__2] unknown package: unbuildable (dependency of ghc) [__2] fail (backjumping, conflict set: ghc, unbuildable) After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: deepseq, ghc, unbuildable`

I hope I'm on the right channel to pull up my issue. Thanks for your attention and for your help 👍.

**Comment by fgaz** [comment]
First of all I advise you not to use an admin shell unless you have a specific reason to do that.

To answer your question, what are you actually trying to do? Quoting the warning, do you want to add `parallel` as dependency to your package, or do you want to add it to a GHC environment? If it's the former, you can just follow the advice given in the warning, while if it's the latter you may have an existing default environment that conflicts with the package you requested, in which case you could delete and recreate it with a single `install --lib` invocation.

**Comment by Chaman-veteran** [comment]
Thanks for your advice, I ran with an admin shell because I didn't know if it got any influence on what I want to do. My objective is to add it to a GHC environment. For deleting the GHC environment should I do it with cabal or reinstall cabal itself? The cabal --help doesn't seem to be of much help for this :/ If I do it with cabal can I re-download the latest version of my packages or should I do it manually?
Thanks a lot for your reply!

**Comment by Mikolaj** [comment]
HI @Chaman-veteran. I don't have experience working with GHC environment, so I can't help you, if the `cabal install --lib` suggested by @fgaz didn't reset it. I bet you could find the environment file and delete it manually. but I have no idea where it resides on Windows. But if I may ask, why are you working with GHC environments instead of using cabal in the usual way?

**Comment by Chaman-veteran** [comment]
Hi! Thanks for your reply!
Well, as I'm a beginner with GHC and cabal I naturally tried to install packages such as I can load my projects on ghci without any issue and the `cabal install` seemed insuffienct while `cabal install --lib` worked pretty well for others libs. I think I will search for the files to delete them. I didn't thought of the possibility of running cabal in the usual way as I didn't know that I wasn't using it the usual way.
I will look for this way then. Thanks a lot for your help!

**Comment by Mikolaj** [comment]
For `cabal repl`, please have a look at https://cabal.readthedocs.io/en/3.6/cabal-commands.html?highlight=repl#cabal-v2-repl and do `cabal repl --help`. You specify the packages you require and let repl take care of them. For most projects with repl that's the usual way (but if you really need to install libraries, which is very rare, look here: https://github.com/haskell/cabal/issues/648). Have fun!
