### ISSUE TITLE
'Could not find test program' with --enable-coverage

### ISSUE THREAD

**Issue by m1-s** [haskell/cabal#7893]
**Describe the bug**
I have a minimal cabal project with 2 packages called `a` and `b`. Each package consists of a library and test suite and the library of `b` depends on the library of `a`. When executing `cabal test all --enable-coverage`, I get the following error:
```
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - a-1 (lib:a) (first run)
 - b-1 (first run)
Configuring a-1...
Preprocessing library for a-1..
Building library for a-1..
[1 of 1] Compiling A
Running 1 test suites...
cabal: Error: Could not find test program
"/<pathToProject>/cabal-test/dist-newstyle/build/x86_64-linux/ghc-8.10.7/a-1/build/a-tests/a-tests".
Did you build the package first?
cabal: Tests failed for a-1 (which is required by b-1).
```

Cabal wants to run the test suite of `a` without having built it first.

**To Reproduce**
Checkout minimal reproducible example https://github.com/m1-s/cabal_coverage_test
Execute `cabal test all --enable-coverage`

**Expected behavior**
Cabal should create code coverage reports for both packages.

**System information**
 - Ubuntu 20.04.3 LTS
 - cabal-install version 3.6.2.0 compiled using version 3.6.2.0 of the Cabal library 
 - The Glorious Glasgow Haskell Compilation System, version 8.10.7

**Comment by Mikolaj** [comment]
Thank you for the report. Coverage is very brittle and I wouldn't be surprised if it didn't work with multi-package projects or required pre-building packages regardless. It would be useful to learn if you can make it work with some modest workarounds.

**Comment by m1-s** [comment]
The obvious workaround is manually building the individual test suite first. `cabal test a --enable-coverage`.
Then `cabal test all --enable-coverage` creates coverage reports for both packages as expected.

I have some time to look into this. Can you give me a pointer where to start? Are there any automated tests for this yet?

**Comment by Mikolaj** [comment]
Thank you for checking. So this indeed looks a well defined bug.

Regarding tests, I've added one

https://github.com/haskell/cabal/tree/master/cabal-testsuite/PackageTests/Regression/T5213ExeCoverage

because there were few or none. 

`git grep -i coverage` doesn't turn up too many hits, so any extra tests and points of interest may be found there.

Related tickets: https://github.com/haskell/cabal/labels/Cabal%3A%20code-coverage

Given how unmaintained coverage is, any progress would be priceless, perhaps most of all appraising the situation, picking any low hanging fruits, gathering in a single ticket all major things that need fixing. Based on that, adding a sentence of warning in a couple of places in cabal manual and in commandline help.

**Comment by m1-s** [comment]
Just a quick update from me: I started at `testAction` in `CmdTest.hs` and noticed that the `elaboratedPlan` was different when executing `cabal test all` (which works) and `cabal test all --enable-coverage` (which gives mentioned error). With the 1st command the `elaboratedPlan` contained `(a-1-inplace-a-tests)` so it correctly builds the test binary. When executing the 2nd command the `elaboratedPlan` only contains the library `(a-1-inplace)` but not the tests. From my understanding this is the bug that I am chasing, right? 

So I tried to find out what part of the cabal code removes the tests from the plan when `--enable-coverage` is added. I managed to trace this error to `elaboratedInstallPlan` in `ProjectPlanning.hs` with printf debugging. Unfortunately the IO monad ends there which makes it hard for me to debug further. Does anyone have a recommendation how to continue debugging or is familiar with the `InstallPlan` creation and can point me into the right direction?

**Comment by Mikolaj** [comment]
Debug.Trace.traceShow?

**Comment by m1-s** [comment]
Another update from me:
Traced the error down to `ProjectPlanning.elaborateSolverToComponents`. This function gives 2 different results depending on whether coverage is enabled or not.

[Diff 1](https://www.diffchecker.com/DkIjXVlT) shows the relevant excerpt of the result of calling `ProjectPlanning.elaborateSolverToComponents`. The left is the result when calling cabal without coverage, the right is with coverage enabled.

Both sides actually reference the missing a-tests. The left side contains an `ElaboratedConfiguredPackage` that describes `a-1-inplace-a-tests` in approx 1500 lines. On the right side `a-tests` is listed as part of `ComponentDeps` in the attribute `elabPkgOrComp` in only 50 lines.

I am not sure how to continue from here. Is the bug that `ElaboratedConfiguredPackage` for `a-1-inplace-a-tests` on the right side is missing or is it supposed to be only referenced in the `ComponentDeps`?
