### ISSUE TITLE
Cabal arogently assumes names shouldn't collide with those already on Hackage

### ISSUE THREAD

**Issue by TomMD** [haskell/cabal#7909]
**Describe the bug**

```
$ cabal init
cabal: The name ____ is already in use by another package on Hackage.
```

But lots of people use Haskell and cabal outside of the context of what is on Hackage or while building software never intended to be uploaded to hackage. There is no reason to use the entire haskell package set as a deny list.

**To Reproduce**

```
mkdir <some name on hackage>
cd $REALLY_COMMON_TERM
cabal init
```

**Expected behavior**
Cabal init happens
.

**Comment by gbaz** [comment]
dup of https://github.com/haskell/cabal/issues/7273 but despite that issue being closed it still doesn't seem resolved, sigh.

**Comment by gbaz** [comment]
(ah, i see, the fix there was to make the error more informative, this issue is whether the behavior is desired at all or not)

**Comment by TomMD** [comment]
How about a "force" flag?

**Comment by Mikolaj** [comment]
Hi! It works fine on master branch (to be released as 3.8; I haven't tried with 3.6.2). It asks you whether you want to name the package so anyway and then proceeds fine. Please confirm.

**Comment by Mikolaj** [comment]
@TomMD: were you able to confirm your problem is solved on master branch?

**Comment by TomMD** [comment]
Yes. I can verify 3.6.2  does not work but HEAD does for me. Thanks!

**Comment by Mikolaj** [comment]
@TomMD: thank you!

**Comment by damienstanton** [comment]
I'd second a `--force` option. This constraint feels like it is in the wrong place; It should be an error at package publish time, not package creation time.

**Comment by Mikolaj** [comment]
@damienstanton: hi! do you refer to the behaviour on master branch? If so, could you elaborate how you'd like to change it?

**Comment by damienstanton** [comment]
> @damienstanton: hi! do you refer to the behaviour on master branch? If so, could you elaborate how you'd like to change it?

No it appears that `master` does not have this issue, thanks!

**Comment by Mikolaj** [comment]
@damienstanton: thank you for confirming.
