### ISSUE TITLE
Scripts without an .hs or .lhs extension no longer work

### ISSUE THREAD

**Issue by ElderEphemera** [haskell/cabal#7910]
**Describe the bug**
In cabal version 3.6.2.0 and before, scripts could be named anything. But with a cabal-install built from HEAD attempting to run any script file without an ".hs" or ".lhs" suffix fails.

**To Reproduce**
Save the following as a file named "script":

```
{- cabal:
build-depends: base
-}

main = putStrLn "Hello"
```

Then,

```
$ cabal --version
cabal-install version 3.7
compiled using version 3.7.0.0 of the Cabal library 

$ cabal v2-run script
Resolving dependencies...
Build profile: -w ghc-9.2.1 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (first run)
Configuring executable 'script' for fake-package-0..
Error: cabal: The 'main-is' field must specify a '.hs' or '.lhs' file (even if
it is generated by a preprocessor), or it may specify a C/C++/obj-C source
file.
```

**Expected behavior**
Scripts should continue to work regardless of what they are named.

Although, it seems like this new behavior has fixed #5702 so error messages no longer confusingly mention "Main.hs". It would be nice to keep the new behavior but without this regression.

**System information**
 - cabal-install version 3.7 (built from commit 7775be851a4d661ab7e7d4e5efbc9268a8688975)
 - GHC version 9.2.1
 - NixOS 21.05

**Comment by fgaz** [comment]
I _think_ this is due to @bacchanalia's work in #7851

**Comment by bacchanalia** [comment]
Sorry about that! I'll look into it.
