### ISSUE TITLE
Cabal run leaves children running when killed

### ISSUE THREAD

**Issue by robx** [haskell/cabal#7914]
**Describe the bug**

When `cabal run` receives `SIGTERM`, it exits, but leaves its children running.

I'm not entirely sure whether this is buggy behaviour, but I was surprised by this,
in the context of running a Haskell tool via `cabal run` and [`withProcessTerm`](https://hackage.haskell.org/package/typed-process-0.2.8.0/docs/System-Process-Typed.html#v:withProcessTerm).

If I run `cabal run target` from the shell, and run
`kill <cabal-run-pid>`, I would have expected both `cabal` and `target`
to stop. Instead, `cabal` exits but `target` keeps running.

Note that when run interactively, `Ctrl-C` sends `SIGINT` to the whole
process group, which is how `cabal run` interrupts nicely on `Ctrl-C`.

**To Reproduce**

```
$ cat x.hs
{- cabal:
build-depends: base
-}

module Main where

import Control.Concurrent (threadDelay)
import Control.Exception
import Control.Monad (when)

main = loop `catch` logInterrupt
  where
    loop = do
      putStrLn "yo"
      threadDelay 1000000
      loop
    logInterrupt e = do
      when (e == UserInterrupt) $ putStrLn "ouch"
      throwIO e
```

Then call `cabal run x.hs`, in a different terminal:

```
$ ps | grep cabal
77565 ttys002    0:04.09 cabal run x.hs
77726 ttys002    0:00.01 /s/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/fake-package-0/x/script/build/script/script
$ kill 77565
```

Then the child keeps running although `cabal` exits:

```
yo
yo
yo
yo
Terminated: 15
$ yo
yo
yo
```

**Expected behavior**

I'd like the child process to be killed, too.

**System information**
- Operating system: macos
- cabal-install version 3.4.0.0, compiled using version 3.4.0.0 of the Cabal library 
- ghc 8.10.7

**Comment by Mikolaj** [comment]
I seem to remember an old ticket about that.

**Comment by robx** [comment]
I think in some sense the right/expected thing would be for `cabal run` to `exec()` instead of forking.

**Comment by Mikolaj** [comment]
Oh, yes, I know some of these words. The related issue might have been one of these: #7757 or #7309.

**Comment by robx** [comment]
Ah, yes, #7757 seems to address this issue explicitly. Thanks! I'd looked through issues but not PRs.

**Comment by robx** [comment]
I'm convinced this is a bug by now. cabal should stop and wait for all its children when killed.

As a work-around, I'm using this shell script to replace `cabal run`:

```bash
#!/usr/bin/env bash

#   cabal-run.sh target args
#
# is equivalent to
#
#   cabal run target --args
#
# except that killing it will also kill the target.
#
# https://github.com/haskell/cabal/issues/7914

set -euo pipefail

target="$1"
shift

echo "building target: ${target}"
cabal build "$target"

executable=$(cabal list-bin "$target")

exec "$executable" "$@"
```
