### ISSUE TITLE
copy command should not overwrite files

### ISSUE THREAD

**Issue by bos** [haskell/cabal#792]
(Imported from [Trac #802](http://hackage.haskell.org/trac/hackage/ticket/802), reported by @dcoutts on 2011-02-11)

see [http://hackage.haskell.org/trac/ghc/ticket/4955](http://hackage.haskell.org/trac/ghc/ticket/4955)

Cabal can inadvertently get users into situations where they have registered packages that do not match their package registration information.

Consider the package darcs and darcs-fastconvert which depends on the darcs library. If one installs darcs, then later in the darcs build tree do a <tt>cabal copy</tt> then it will overwrite the library .hi files but not update the library registration. This will mean that subsequent builds of darcs-fastconvert will fail with very confusing error messages (see the ghc ticket above).

A similar thing could happen with inplace registrations.

The suggestion to avoid this problem is for <tt>cabal copy</tt> to refuse to overwrite .hi files (executables are fine).

This is also partly related to #645 because some people are using <tt>cabal copy</tt> to avoid having to use <tt>cabal install</tt> which spends too long reconfiguring and checking nothing needs building before actually installing.

**Comment by BardurArantsson** [comment]
Is this still relevant at all?

**Comment by jneira** [comment]
thanks for noting it, closing

**Comment by fgaz** [comment]
Isn't this about the `Setup.hs` copy command?
