### ISSUE TITLE
Release notes for Cabal-3.4.1.0 are missing

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#7920]
https://hackage.haskell.org/package/Cabal-3.4.1.0/changelog points to https://github.com/haskell/cabal/blob/master/release-notes/Cabal-3.4.1.0.md, but there is no such file in https://github.com/haskell/cabal/tree/master/release-notes. Could it please be provided?

**Comment by Mikolaj** [comment]
Thank you for the heads up. I see there is https://github.com/haskell/cabal/blob/3.4.1.0-changelogs/release-notes/Cabal-3.4.1.0.md and https://github.com/haskell/cabal/blob/3.4/release-notes/Cabal-3.4.1.0.md, so it should just be copied. I guess that'd be enough?

**Comment by Bodigrim** [comment]
I guess so. Please also restore 3.4.1.0 entry in https://github.com/haskell/cabal/blob/master/Cabal/ChangeLog.md - it's missing now.
