### ISSUE TITLE
cabal-install broken at Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/cabal#7927]
Command `cabal install cabal-install` failed saying:

... 
Building th-compat-0.1.3 
Failed to install zlib-0.6.2.3 Build log
( /root/.cabal/logs/ghc-8.6.5/zlib-0.6.2.3-93Wbo8gIIzI9bg4p2MsNUF.log
): cabal: Entering directory '/tmp/cabal-tmp-9836/zlib-0.6.2.3'
Configuring zlib-0.6.2.3... cabal: Missing dependency on a foreign
library: * Missing (or bad) header file: zlib.h * Missing (or bad) C
library: z This problem can usually be solved by installing the system
package that 
... 
cabal: Leaving directory
'/tmp/cabal-tmp-9836/zlib-0.6.2.3' Downloading resolv-0.1.2.0 ...
Completed Cabal-3.6.2.0 cabal: Error: some packages failed to install:
cabal-install-3.6.2.0-5Y0kIBgGBHPLTQ8XdkgDxf depends on
cabal-install-3.6.2.0 which failed to install.
hackage-security-0.6.2.0-B0TjxsjMq5dADGx7XAtxpG depends on
hackage-security-0.6.2.0 which failed to install.
zlib-0.6.2.3-93Wbo8gIIzI9bg4p2MsNUF failed during the configure step.
The exception was: ExitFailure 1

But the claimed missing zlib.h resides at /usr/include/zlib.h

See also
https://stackoverflow.com/questions/66615901/cabal-install-cabal-cabal-install-fails-due-to-missing-zlib-library

Suggested workaround there installing "libghc-zlib-dev" seems successful.

**Comment by Mikolaj** [comment]
Hi! Thank you for the report. Could you make an experiment and remove "libghc-zlib-dev", but not anything else, and see if compilation still succeeds?

**Comment by andreas-roehler** [comment]
Seems to work fine after ‘ghclib-zlib-dev’ was removed.
Checked against dhall-yaml, the original package which missed zlib.h.
Called ‘ghc-pkg unregister dhall-yaml’, than ‘cabal install’ again.

However, did not call ‘apt autoremove’ as suggest from ‘apt remove libghc-zlib-dev’

Full message from ‘apt remove libghc-zlib-dev’ below: 

Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libfreetype6 zlib1g-dev
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  libghc-zlib-dev
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1838 kB disk space will be freed.
Do you want to continue? [Y/n] (Reading database ... 
(Reading database ... 5%
...
(Reading database ... 100%
(Reading database ... 39620 files and directories currently installed.)

Removing libghc-zlib-dev (0.6.2-2build1) ...

Processing triggers for ghc (8.8.1+dfsg1+is+8.6.5+dfsg1-3) ...

There are problems in package streaming-commons-0.2.2.3:

  dependency "zlib-0.6.2-BdOecmQ0rL1HOiGypdSgxY" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.

streaming-commons-0.2.2.3
dhall-yaml-1.2.9
dhall-json-1.7.9
dhall-1.40.2
http-client-tls-0.3.5.3
http-client-0.7.10

**Comment by Mikolaj** [comment]
Thank you for the experiment. If removing `ghclib-zlib-dev` broke stuff, I'd suspect a bug in the Haskell ecosystem. However, given your experimental results, I'm more inclined to suspect it's some OS fluke, like the original `/usr/include/zlib.h` corrupted or left over from another package or whatever it was that got fixed by (re)installing some packages. What do you think?

**Comment by Mikolaj** [comment]
BTW, you may find it convenient to remove all the Ubuntu GHC things and switch fully to ghcup.

**Comment by andreas-roehler** [comment]
Will try ghcup, thanks for the suggestion. Looks like there are several bugs. May try other system in some container.

**Comment by andreas-roehler** [comment]
‘ghcup’ seems not to make a difference. When starting from a fresh lxc, running ‘ghcup’,  ghci works.
At Linux ... 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

‘cabal install cabal-install’ errors: 
cabal: Failed to build zlib-0.6.2.3 (which is required by exe:cabal from
cabal-install-3.6.2.0).

**Comment by Mikolaj** [comment]
If that's a fresh install, it's completely expected. You need to do ‘apt install libghc-zlib-dev’.

**Comment by Mikolaj** [comment]
Pardon me, not `libghc-zlib-dev’, but `zlib1g-dev`.

**Comment by Mikolaj** [comment]
Haskell packages don't install the C libraries they need. They'd be running with sudo if they did and that's risky.

**Comment by Mikolaj** [comment]
Unless you install Haskell packages with `apt`, which is one of very few advantages of this method.

**Comment by hasufell** [comment]
Is this a new dependency? I can't remember this being a requirement.

**Comment by andreas-roehler** [comment]
Am 27.01.22 um 22:41 schrieb Mikolaj Konarski:
>
> Pardon me, not |libghc-zlib-dev|, but |zlib1g-dev|.
>
> —


Okay, with |zlib1g-dev everything |seems fine.

**Comment by Mikolaj** [comment]
Amazing. That satisfies my curiosity. As far as I'm concerned you can close the ticket.

**Comment by Mikolaj** [comment]
@andreas-roehler: thank you and take care!
