### ISSUE TITLE
Wrong "the 'synopsis' field is rather long" warning by 'cabal check'

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#7932]
When the synopsis field is exactly 80 characters long, `cabal check` warns:

    Warning: The 'synopsis' field is rather long (max 80 chars is recommended).

It should warn at over 80 characters (and so, starting at 81 characters).

Current master branch tested as well as 3.6.2.0.

**Comment by ptkato** [comment]
You mean it should warn if it's more than than 80 characters?

**Comment by Mikolaj** [comment]
Oops, you are right. I made the same mistake as the one I report: wrote "It should warn at 80 characters", but I meant "It should warn at 81 characters".
