### ISSUE TITLE
Interactive `cabal init` invoked a second time in the same directory silently discards changes

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7957]
Applies to current `master`:
1. In a new directory, I run `cabal init` and then interactively chose 
  * `4) Testsuite`
  * `cabal-version` 1.24
  * BSD3 licence
  * otherwise defaults
  This creates some scaffolding.

2. In the same directory, I again run `cabal init`, with the same choices, except
  * `cabal-version` 2.0

The response is:
```
Log: Using cabal specification: 2.0

Log: Creating LICENSE...

Log: Using existing file LICENSE...

Log: Creating CHANGELOG.md...

Log: Using existing file CHANGELOG.md...

Log: Using existing directory ./test...

Log: Using existing file test/Main.hs...

Log: Using existing file tests-calling-ghc.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.

Info: You may want to edit the .cabal file and add a Description field.
```

However, the directory is untouched, and the `.cabal` file has not been updated.

I would expect one of these:
1. Update happening, with a backup copy of the previous `.cabal` file, or:
2. Exit with status 1 and a appropriate error message.

ATTN: @ptkato

**Comment by ptkato** [comment]
Hello, thank you for your thoroughly testing; now to the problem: this behaviour is intended, due to #7876, if you want to update it, you need to use `--overwrite`. But I suppose an error message might be the proper solution for this case.

**Comment by andreasabel** [comment]
> Hello, thank you for your thoroughly testing; 

You're welcome.  I use `cabal init` to set up experiments, and when I notice something unexpected in `cabal init`, I report it.

> now to the problem: this behaviour is intended due to #7876. If you want to update it you need to use `--overwrite`, but I suppose an error message might be the proper solution for this case.

Since the user is in an interactive session, would it make sense to ask the user whether they wish to overwrite?  At least, asking a dozen questions and then erroring out seems not quite right.  If answering all these questions has no chance of having any effect (because of a missing `--overwrite` flag), the questions should not be asked in the first place.

**Comment by ptkato** [comment]
That is reasonable, I shall include it in the PR.
