### ISSUE TITLE
Detected by Windows Defender as PUP

### ISSUE THREAD

**Issue by BernardoGomesNegri** [haskell/cabal#7961]
**Describe the bug**
The binary Windows version of Cabal, downloaded at https://www.haskell.org/cabal/download.html or through Chocolatey is detected as a Potentially Unwanted Program by Windows Defender. Windows Defender calls it "Win32/Bearfoos.B!ml"

**To Reproduce**
Download the Windows x86-64 Cabal binary at https://www.haskell.org/cabal/download.html.
Extract the zip file.
Right click on Windows Explorer, click "Scan with Windows Defender...".
It will detect a Potentially Unwanted Program and automatically quarantine it.

**Expected behavior**
Cabal does not get detected as a Potentially Unwanted Program by Windows Defender

**System information**
 - Windows 10, version 21H2, build 19044.1466
 - Cabal 3.6.2.0

**Additional context**

**Comment by ptkato** [comment]
I am not familiar with Windows, does it happen automatically (like if it were watching for malicious activities or something), or only when you actively ask for a scan?

**Comment by BernardoGomesNegri** [comment]
Automatically when you run the program.

**Comment by fgaz** [comment]
Is there a way to mark it as safe/ignored or does windows defender make running cabal impossible on windows?

**Comment by gbaz** [comment]
you can mark it as ignored, and also you can follow the steps here to submit it for analysis and ask that they fix the false positive on their end. i don't think that cabal developers are in a position to do much here -- this is a problem that microsoft's team needs to address https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide

**Comment by BernardoGomesNegri** [comment]
Microsoft removed the detection. Thank you for all the help.
