### ISSUE TITLE
`cabal v2-run` suggests target `all` but then refuses to accept it.

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7968]
On current `master`:
```
$ cabal run -w ghc-9.0.2
Error: cabal: No targets given and there is no package in the current
directory. Use the target 'all' for all packages in the project or specify
packages or components by name or location. See 'cabal build --help' for more
details on target options.

$ cabal run all -w ghc-9.0.2
Error: cabal: The run command is for running a single executable at once. The
target 'all' refers to all the packages in the project which includes the
executable 'example-client', the executable 'hackage-repo-tool', the
executable 'hackage-root-tool' and the test suite 'TestSuite'.
```

**Comment by bacchanalia** [comment]
is this the same behavior as 3.6.2?

**Comment by fgaz** [comment]
There actually is _one_ case where `cabal run all` works: when the project contains a single executable. Maybe `Use the target 'all' for all packages in the project or specify
packages or components by name or location.` could be changed to `Specify
packages or components by name or location. If there is only one executable in the project, you can also use 'all'.` (or just omitting the 'all' part entirely)

**Comment by andreasabel** [comment]
> There actually is _one_ case where `cabal run all` works

Ok.  But `all` sounds like a plurality, not a singularity.  So maybe `cabal run` should not support `all`, or at least not advertise it.

> (or just omitting the 'all' part entirely)

I'd second that.

**Comment by ulysses4ever** [comment]
Maybe in the case of a single executable, `cabal run` should run that executable? Otherwise complain without mentioning `all` (which in the "otherwise" case won't help anyway).

**Comment by jneira** [comment]
> is this the same behavior as 3.6.2?

just tried `cabal-3.6.2.0` and it is same one
