### ISSUE TITLE
inplace is shadowed by package

### ISSUE THREAD

**Issue by bos** [haskell/cabal#797]
(Imported from [Trac #807](http://hackage.haskell.org/trac/hackage/ticket/807), reported by guest on 2011-03-05)

I have a library, persistent, that builds. When I try to build the test suite, I get:

<pre class="wiki">Preprocessing library persistent-0.4.0.1...
Preprocessing test suites for persistent-0.4.0.1...
Building persistent-0.4.0.1...
Registering persistent-0.4.0.1...
&lt;command line&gt;: cannot satisfy -package-id persistent-0.4.0.1-inplace:
    persistent-0.4.0.1-inplace is shadowed by package persistent-0.4.0.1-f5ffa1e952f5d8b58608c8d1f9f69825
    (use -v for more information)
</pre>The test-suite build-depends has:

<pre class="wiki">                   persistent &gt;= 0.4.0.1,
                   persistent-mongoDB,
                   persistent-postgresql,
                   persistent-sqlite,
</pre>persistent-mongoDB (and postgresql and sqlite) depends on persistent to build.
I have tried this twice now from a fairly clean install- immediately after upgrading to a new version of ghc.

**Comment by gbaz** [comment]
Here's a newer description of what seems to be the problem (regarding test-suites and cyclic dependencies) that helps clear up the key issues involved: http://stackissue.com/tibbe/hashable/higher-kinded-classes-124.html

So this seems to be an instance of https://github.com/haskell/cabal/issues/1575

which has an unmerged (stalled?) pr that gives a solution at https://github.com/haskell/cabal/pull/3422

**Comment by 23Skidoo** [comment]
Closing in favour of #1575.
