### ISSUE TITLE
Double take, which make for make users-guide?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#7977]
From the `doc` folder the instruction to build the docs is `make users-guide` but there are makefiles at the root and in the doc folder. The `make users-guide` only works for me if I'm in the root directory. That is confusing.

https://github.com/haskell/cabal/blame/master/doc/README.md#L15

**Comment by Mikolaj** [comment]
Is the version in root bit-rotten? Was it supposed to do the same thing? Shouldn't it just call the one in doc/?

**Comment by Mikolaj** [comment]
Oh, sorry, it's the other way around. The version in doc/ is broken? Or is called from root?

**Comment by philderbeast** [comment]
From the root the incantation is `make users-guide`. This calls across to the makefile in doc with ` && make -C doc build-and-check-requirements`.

From the doc folder we can do `make` to do an [skjold](https://github.com/twu/skjold) audit.

```
$ cd doc
$ make
. ../.python-sphinx-virtualenv/bin/activate \
  && pip install pip-tools \
  && pip-compile requirements.in
...
Successfully installed packaging-21.3 skjold-0.4.1 toml-0.10.2
Usage: skjold audit [OPTIONS] [FILE]
Try 'skjold audit --help' for help.

Error: It looks like you're trying to use the github source without providing an access
token.Skjold needs a token to access the Github GraphQL API.You can generate a
token at https://github.com/settings/tokens without giving it any permissions and
make it available to skjold by setting SKJOLD_GITHUB_API_TOKEN in your environment.
make: *** [Makefile:35: check-requirements] Error 2
```

**Comment by andreasabel** [comment]
> I ran into this too. It seems like the one in the doc folder is useless. I would support removing it and having the README unilaterally point to the one in root, unless anyone objects.

I object.
The `Makefile` in the `doc` folder isn't useless.  It generates the requirements file. It even says so in its first line:
https://github.com/haskell/cabal/blob/1b7162f5bbd3a5bc907706e60cc58fe04bb4e044/doc/Makefile#L1

The `make users-guide` from the root `Makefile` was there before I added the `doc/Makefile`, and I left it like that to not break developer routines.

If you think `make` in the `doc` folder should build the documentation (which isn't unreasonable to expect), the functionality from the root `Makefile`should be moved to the `doc/Makefile`, leaving only the `make users-guide` which will delegate as `make -C doc`.

**Comment by BinderDavid** [comment]
Since I just took a closer look at the Makefiles for building the docs, I will try to implement the suggestion of @andreasabel .
