### ISSUE TITLE
all cabal builds on MacOS monteray on M1 macs leave zombie processes

### ISSUE THREAD

**Issue by lavirlifiliol** [haskell/cabal#7981]
**Describe the bug**
cabal-build doesn't seem to reap it's zombies, so for builds with lots of modules, the process limit gets exceeded and the build fails. So far it's only been an issue for OpenGLRaw due to it's impressive 617 modules.

**To Reproduce**
open 3 terminals, and run these commands in each
```sh
$ cabal v2-install  --lib -v OpenGLRaw
```
```sh
$ tail -f <the build log from cabal-install>
```
```sh
$ ps -o stat,pid,ppid #repeat once build gets to ~400/617
```
and watch as the number of Z+ processes goes up as the build progresses. It can also be observed on `cabal install Cabal`, but that one does finish on my system. Eventually the build errors out with some error along the lines of "could not execute opt", "cannot determine llvm version", "fork: resource temporarily unavailable" at step 540-ish, the tail of the log looks something like this, the exact point of failure varies.
```
[541 of 617] Compiling Graphics.GL.ARB.DebugOutput ( src/Graphics/GL/ARB/DebugOutput.hs, dist/build/Graphics/GL/ARB/DebugOutput.o, dist/build/Graphics/GL/ARB/DebugOutput.dyn_o )
[542 of 617] Compiling Graphics.GL.ARB.CopyImage ( src/Graphics/GL/ARB/CopyImage.hs, dist/build/Graphics/GL/ARB/CopyImage.o, dist/build/Graphics/GL/ARB/CopyImage.dyn_o )
[543 of 617] Compiling Graphics.GL.ARB.CopyBuffer ( src/Graphics/GL/ARB/CopyBuffer.hs, dist/build/Graphics/GL/ARB/CopyBuffer.o, dist/build/Graphics/GL/ARB/CopyBuffer.dyn_o )
ghc: could not execute: opt

cabal: Failed to build OpnGLRw-3.3.4.1-c3de2a93.
```
**Expected behavior**
the build completes after some time without zombie processes.
**System information**
 - MacOS monteray 12.0.1
 - ghc 8.10.7
 - llvm 12
 - cabal 3.6.2.0

**Comment by angerman** [comment]
Due to the mention of llvm I assume this is native and not Rosetta?

**Comment by lavirlifiliol** [comment]
Yes, native. I can test x86 in ~12 hours as well if need be.

**Comment by gbaz** [comment]
I will note that if this all occurs in a single package being compiled, I suspect the culprit may be ghc and not cabal?

**Comment by lavirlifiliol** [comment]
Oh, that may be the case. I will try to replicate with just GHC and see if
the issue is still there.

**Comment by mpickering** [comment]
GHC issue - https://gitlab.haskell.org/ghc/ghc/-/issues/20305

**Comment by gbaz** [comment]
Closing as not our issue.
