### ISSUE TITLE
The changelog is mute about v2-cabal

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7985]
Grepping the https://hackage.haskell.org/package/Cabal-3.6.2.0/changelog for
- `nix-style`: No hit.
- `nix` (whole word): No hit.
- `v1-`: No hit.
- `v2-`: No hit.
- `new-`: One hit:
> 2.4.0.0 ... Deprecate preSDist, sDistHook, and postSDist in service of new-sdist, since they violate key invariants of the new-build ecosystem. Use autogen-modules and build-tool-depends instead. ([#5389](https://github.com/haskell/cabal/pull/5389)).

Yeah, can't see the forest because of all the trees here.

I just wanted to quickly find out when the `nix-style`/`new-style`/`v2-cabal` was introduced.  Does not seem worth mentioning in the changelog?

**Comment by fgaz** [comment]
> https://hackage.haskell.org/package/Cabal-3.6.2.0/changelog

that's the changelog for Cabal, while v2- is a cabal-install feature

**Comment by andreasabel** [comment]
Bugger, yeah.
This explains it.
