### ISSUE TITLE
Mention of support for scripts for list-bin.

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#7986]
> Since #7925, it'd be great to amend this PR with the mention of support for scripts.

I'd rather have that as a separate issue to work on later if that is alright with you @ulysses4ever.

_Originally posted by @philderbeast in https://github.com/haskell/cabal/pull/7964#issuecomment-1041895791_

**Comment by andreasabel** [comment]
@bacchanalia : Could you contribute the documentation for your feature now?
https://github.com/haskell/cabal/blob/bcfc79ce1e286b1df1fef31139044c0e0503d5c7/doc/cabal-commands.rst?plain=1#L743-L744
