### ISSUE TITLE
PackageTests/ForeignLibs/setup.test.hs fails on MacOS on GHC 8.0.2

### ISSUE THREAD

**Issue by andreabedini** [haskell/cabal#7989]
PackageTests/ForeignLibs/setup.test.hs fails on MacOS on GHC 8.0.2, discovered while working on #7952 

```
creating /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib
Installing executable setup.dist/work/dist/build/myforeignlib/libmyforeignlib.dylib to /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib/libmyforeignlib.dylib
+ /usr/bin/gcc '-std=c11' -Wall -o uselib UseLib.c -l myforeignlib -L /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib
+ /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/./uselib
dyld: REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB has segment 2 which is not a writable segment (__LINKEDIT) in /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib/x86_64-osx-ghc-8.0.2/libHSmy-foreign-lib-0.1.0.0-ghc8.0.2.dylib

stderr:
*** Exception: Command /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/./uselib failed.
Output:
dyld: REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB has segment 2 which is not a writable segment (__LINKEDIT) in /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/ForeignLibs/setup.dist/usr/lib/x86_64-osx-ghc-8.0.2/libHSmy-foreign-lib-0.1.0.0-ghc8.0.2.dylib



*** unexpected failure for PackageTests/ForeignLibs/setup.test.hs
```

See full log [here](https://github.com/haskell/cabal/runs/5178990918?check_suite_focus=true#step:11:907)

**Comment by Mikolaj** [comment]
That's most likely a GHC 8.0 bug and we will drop GHC 8.0 in a year or two. However, there is low probability that it's actually a cabal bug, so worth making sure that it isn't.

**Comment by jneira** [comment]
Hi, the test was marked as broken for ghc >= 9.0 and windows with #8045. I forgot to comment here the new case (but this issue was linked in several commits, including the merge in master).

Later the case was fixed by #7764 and the test was unmarked as broken for windows and those ghc versions by #8111.

So the issue state is the initial one: it is reproduced in macos and ghc 8.0.2

**Comment by ulysses4ever** [comment]
As of bd998, 8.0 is no longer used on CI. Should this be closed?

**Comment by Mikolaj** [comment]
Yes, let me close. Thank you.
