### ISSUE TITLE
Optimization: False in cabal.project does not disable optimization

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#7991]
**Describe the bug**

When my `cabal.project` is

```
packages: wordle.cabal

package wordle
  optimization: False
```

(as copied from https://cabal.readthedocs.io/en/3.6/cabal-project.html#cabal-project-reference)
I still see

```
rae:22:29:48 ~/work/tweag/wordle> cabal build
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
```

Note the `-O1`. This slows down my build too much.

**Expected behavior**
I expected no optimization.

**System information**
 - Operating system: macOS 12.2
 
```
rae:22:30:54 ~/work/tweag/wordle> cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
```

```
rae:23:01:16 ~/work/tweag/wordle> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

**Comment by jneira** [comment]
To check it you could measure the diff between setting the flag and use `-O0` in the cli invocation (which is known to disable it effectively)

**Comment by goldfirere** [comment]
OK. I think you're right -- I think my optimization *was* disabled, but compilation still took forever (which is not cabal's problem, of course). Thanks!
