### ISSUE TITLE
Cannot demonstrate QuickCheck in a video

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#7992]
I wanted to demonstrate QuickCheck in a video, by running `quickCheck` in GHCi and showing how QuickCheck generates test cases for property-based testing. But I cannot figure out how to do this (unless I use https://github.com/phadej/cabal-extras/tree/master/cabal-env). Whenever I `import Test.QuickCheck` in GHCi, I am told that QuickCheck is a hidden package.

I tried adding `QuickCheck` to the `build-depends` of my testsuite. But that didn't work. (I even tried `cabal repl --enable-tests`.)

Note that my library does not use QuickCheck (or any other testing facility), because it is a library, not a testsuite.

What is the recommended way to proceed here? Thanks!

**Comment by TikhonJelvis** [comment]
Have you tried doing `:set -package QuickCheck` in the Cabal REPL?

That's what I do when I want to have an interpreter session for my library target, but still load and run test modules.

**Comment by andreabedini** [comment]
@goldfirere AFAIK a repl is specific to a component, by default the component is the library.
If you have added a test-suite called `my-library-tests`, `cabal repl my-library-tests` will load a repl with the test-suite and its dependencies in scope.

E.g.

```
$ mkdir tmp && cd tmp
$ cabal init --minimal --non-interactive --lib --tests
$ # add QuickCheck to the dependencies of the tmp-test test-suite component
```

Now

```
$ cabal repl
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - tmp-0.1.0.0 (lib) (ephemeral targets)
Preprocessing library for tmp-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/andrea/.ghci
[1 of 1] Compiling MyLib            ( src/MyLib.hs, interpreted )
Ok, one module loaded.
λ> import Test.QuickCheck

<no location info>: error:
    Could not load module ‘Test.QuickCheck’
    It is a member of the hidden package ‘QuickCheck-2.14.2’.
    Perhaps you need to add ‘QuickCheck’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘QuickCheck-2.14.2’.
    Perhaps you need to add ‘QuickCheck’ to the build-depends in your .cabal file.
```

but

```
[~/tmp] cabal repl tmp-test
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - tmp-0.1.0.0 (test:tmp-test) (first run)
Preprocessing test suite 'tmp-test' for tmp-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/andrea/.ghci
[1 of 1] Compiling Main             ( MyLibTest.hs, interpreted )
Ok, one module loaded.
λ> import Test.QuickCheck
λ> putStrLn "It works!"
It works!
```

What @TikhonJelvis says also seems to work (although that _the package flags have changed, resetting and loading new packages..._ message scares me a little)

```
$ cabal repl
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - tmp-0.1.0.0 (lib) (ephemeral targets)
Preprocessing library for tmp-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/andrea/.ghci
[1 of 1] Compiling MyLib            ( src/MyLib.hs, interpreted )
Ok, one module loaded.
λ> :set -package QuickCheck
package flags have changed, resetting and loading new packages...
λ> putStrLn "It works!"
It works!
```

**Comment by tomjaguarpaw** [comment]
Could you please show your setup and what you've tried so far? It's hard to know what to suggest without knowing your setup. It *sounds like* you have a `test-suite` stanza, and that's what you're trying to load into `cabal repl`. If so, here's an example of how I do the same, that you should be able to adapt to your use case:

My package `opaleye` has [a `test-suite` stanza](https://github.com/tomjaguarpaw/haskell-opaleye/blob/2790866343814ad4ceb8b003c609c4d8482613fa/opaleye.cabal#L112), called `test`, that has a [`build-depends` upon `QuickCheck`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/2790866343814ad4ceb8b003c609c4d8482613fa/opaleye.cabal#L135). In order to load this up in `cabal repl` I issue

```
cabal repl test
```

N.B. "`test`" there refers to the name of the `test-suite` stanza, so if your stanza is named differently, e.g. `test-suite: raestest`, then instead you should issue

```
cabal repl raestest
```

Once I do that I am in `ghci` and I can use `QuickCheck` (courtesy of it build a `build-depends`) and my `test` modules (courtesy of me naming `test` on the command line):

```
*Main> import Test.QuickCheck
*Main Test.QuickCheck> import Opaleye.Test.Arbitrary 
*Main Test.QuickCheck Opaleye.Test.Arbitrary> Test.QuickCheck.generate Opaleye.Test.Arbitrary.arbitraryPGString 
"U\1022782\186927e\66770~2r"
```

**Comment by Mikolaj** [comment]
Is that solution different to what @andreabedini proposed?

**Comment by tomjaguarpaw** [comment]
No, the solution does not differ (both say to use `cabal repl <test-suite-name>`. Only the presentation differs.

**Comment by tomjaguarpaw** [comment]
> What @TikhonJelvis says also seems to work (although that the package flags have changed, resetting and loading new packages... message scares me a little)

Well, it allows you to load `Test.QuickCheck`, but can you confirm whether you can actually load your library modules too? I can't. If I use `:set -package QuickCheck` then I can no longer actually load my library (which I guess is the consequence that "package flags have changed, resetting and loading new packages" is trying to point out).

**Comment by danidiaz** [comment]
A supplement to @andreabedini and @tomjaguarpaw comments. Besides simply mentioning the component name as the target, cabal-install also supports a [target syntax](https://cabal.readthedocs.io/en/3.6/cabal-commands.html?#cabal-v2-build) that helps disambiguating components and, when we are in a multi-package cabal project, also allows choosing the target package.

For example, if I'm in a Cabal project where it exists a package **dep-t-advice** that has a test suite named **synthetic-callstack-tests**, I can invoke:

    cabal repl dep-t-advice:test:synthetic-callstack-tests

Alas, the user guide seems incorrect here about target syntax. It says that `tests` is a valid type of component, but it doesn't work for me (cabal-install 3.6.2.0) . I had to write `test`. 

Also, ongoing work on [multiple home units](https://well-typed.com/blog/2022/01/multiple-home-units/) should make it easier to work with multiple components at the same time in ghci.

> There is also very basic support for multiple home units in GHCi: at the moment you can start a GHCi session with multiple units but only the :reload command is supported. Most commands in GHCi assume a single home unit, and so it is additional work ([#20889](https://gitlab.haskell.org/ghc/ghc/-/issues/20889)) to modify the interface to support multiple loaded home units.

**Comment by Mikolaj** [comment]
> Alas, the user guide seems incorrect here about target syntax. It says that `tests` is a valid type of component, but it doesn't work for me (cabal-install 3.6.2.0) . I had to write `test`.

I think the full story is that you can do "packageName:test:testName" or "packageName:tests" and the latter means all tests. Whether it's useful, I don't know, but the semantics seems well defined and presumably the user guide refers that (whether in a useful way, again, is disputable).

**Comment by andreabedini** [comment]
> Well, it allows you to load `Test.QuickCheck`, but can you confirm whether you can actually load your library modules too? I can't. If I use `:set -package QuickCheck` then I can no longer actually load my library (which I guess is the consequence that "package flags have changed, resetting and loading new packages" is trying to point out).

I agree. I didn't test loading the library module.

**Comment by goldfirere** [comment]
Thanks, all, for the very helpful comments here. The solution was indeed `cabal repl test`, which I suppose I could have figured out on my own. (Indeed, I'm somewhat embarrassed I didn't! Ah, well.)

Thanks again for the quick, helpful responses, and sorry for the noise.
