### ISSUE TITLE
latest cabal-install binary for linux x86_64 missing

### ISSUE THREAD

**Issue by Roguelazer** [haskell/cabal#7994]
**Describe the bug**
The link for "Binary download for Linux (x86-64, requires glibc 2.12 or later)" is a 404 on https://www.haskell.org/cabal/download.html. The specific missing file is https://downloads.haskell.org/~cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux.tar.xz

**Expected behavior**
Binary should be present

Not sure that github issues is really the best place to report this but _shrug_.

**Comment by Roguelazer** [comment]
None of the other files appear to be what this promises to be (a statically-linked, glibc 2.12+ executable).

**Comment by hasufell** [comment]
> None of the other files appear to be what this promises to be (a statically-linked, glibc 2.12+ executable).

Where do you read the promise of a statically linked glibc executable?

https://downloads.haskell.org/~cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux.tar.xz should point to https://downloads.haskell.org/cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux-deb10.tar.xz indeed... but that's not a statically linked glibc executable and we don't provide one. Linking against glibc statically is not supported by glibc.

**Comment by Roguelazer** [comment]
Sorry, I meant the conventional "statically linked except glibc" definition. If the debian 10 binary is linked against glibc 2.12 that would work for me.

**Comment by Mikolaj** [comment]
Yes, I think it is linked against glibc 2.12. Could you try?

@emilypi, @hasufell: I will fix the webpage. Do you think it's a good idea to rename the entry from "Binary download for Linux (x86-64, requires glibc 2.12 or later)" to "Binary download for Debian 10 (x86-64, requires glibc 2.12 or later)" (and fix the link)?

**Comment by Roguelazer** [comment]
The debian10 one is linked against glibc 2.27. It's also dynamically linked against libgmp.so.10 (which is a rather quite new version).

```
ldd cabal
./cabal: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./cabal)
./cabal: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./cabal)
./cabal: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./cabal)
	linux-vdso.so.1 =>  (0x00007ffda8beb000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd658e73000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fd658c5d000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd658a55000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fd658852000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd65864e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd658431000)
	libgmp.so.10 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007fd65809d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd657e19000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd65908d000)
```

**Comment by hasufell** [comment]
What exactly is the issue here? You don't want to use the musl binaries?

**Comment by Mikolaj** [comment]
Huh, so probably all of those binaries are linked against a higher glibc version than advertised? In that case, I think I will just remove the glibc version from the webpage and let people deduce from the Debian version displayed (I hope it's correct?).

**Comment by Roguelazer** [comment]
I mean, the core of the issue is that the download link on the website doesn't work...

I'm attempting to install on a system that _isn't_ debian 10, but does use glibc. I can't use the musl binaries unless I want to install a second libc, since the alpine distribution is dynamically linked against libc.musl-x86_64.so.1. I'm working on building from source but that's obviously pretty time-intensive.

**Comment by Mikolaj** [comment]
Seriously? https://downloads.haskell.org/cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux-alpine-static.tar.xz is *dynamically* linked?

**Comment by hasufell** [comment]
> Seriously? https://downloads.haskell.org/cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux-alpine-static.tar.xz is _dynamically_ linked?

no

**Comment by hasufell** [comment]
> I'm attempting to install on a system that isn't debian 10

Use ghcup: https://www.haskell.org/ghcup/

**Comment by Mikolaj** [comment]
Indeed:

```
~$ file ~/cabal
/home/mikolaj/cabal: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
~$ ldd ~/cabal
	not a dynamic executable
```

**Comment by Roguelazer** [comment]
I was testing cabal-install-3.6.2.0-x86_64-linux-alpine.tar.xz, which is the only thing linked from the download page. I didn't even see the static tarball.

**Comment by Mikolaj** [comment]
Oh yes, it does need a lot of love. :)

Thank you again for reporting and do give ghcup a try.

**Comment by Mikolaj** [comment]
I guess I will add a link to the static binary as well.

**Comment by Mikolaj** [comment]
At least it seems we don't miss any essential binary and we don't need to go rummage on gitlab or wherever it might be.

BTW, @emilypi: would you find a moment to edit and publish those release-preparation notes? As you can see, it's hard to even guess what should have been done at release, not to mention accurately keeping track of all those steps.

**Comment by jneira** [comment]
Static binaries apart and as reported again in #8001 and noted here the link in the downlaods page https://downloads.haskell.org/~cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux.tar.xz is broken and iiuc it should be replaced with https://downloads.haskell.org/cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux-deb10.tar.xz

//cc @Mikolaj

**Comment by Mikolaj** [comment]
@jneira; thank you for fixing this. I upload and it seems to be up already: https://www.haskell.org/cabal/download.html

The "link to the static binary"  will need to wait until next time. Closing.

**Comment by Mikolaj** [comment]
And the update of "requires glibc 2.12 or later" to something closer to reality will need to wait.
