### ISSUE TITLE
cabal-install-3.6.2.0 link is not working

### ISSUE THREAD

**Issue by HT-Moh** [haskell/cabal#8001]
Not sure if the write place, but the link https://downloads.haskell.org/~cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0-x86_64-linux.tar.xz seems to be dead

**Comment by jneira** [comment]
Hi, thanks for reporting the issue, it was already noted in #7994 and i've linked it to this one.
So i am ognna close this one if you dont mind
