### ISSUE TITLE
Monitoring ticket for manual testing of Cabal library 3.6.3 (for GHC 9.2.2) candidate.

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8026]
Let's not down here what runs from CI have been manually performed (and on what OSes) on the 3.6 branch (CI is not backported to 3.6), which haven't been, what tests failed.

**Comment by jneira** [comment]
From https://github.com/haskell/cabal/pull/8025#issuecomment-1057856355

Just in case i am adding a 9.2.1 job against 3.6 here: https://github.com/jneira/cabal/pull/6
Not sure if it worths to add it upstream though

> I agree, local tests should be enough

I suppose local tests has been done only in linux so there is some risk of unexpected bugs in windows/macos. I hope the risk is low enough to go forward.
I will try to give a try to the Cabal specific test suites locally in windows but afaics ci is not (and neved did) running them for windows

**Comment by jneira** [comment]
Ok, the [ci job for 9.2.1 and 3.6](https://github.com/jneira/cabal/runs/5404862213?check_suite_focus=true):
* passed `sh validate.sh -j 2 -w ghc-9.2.1 -v --lib-only -s lib-tests` :100: 
* failed in `sh validate.sh -j 2 -w ghc-9.2.1 -v --lib-only -s lib-suite`:

```
UNEXPECTED FAIL: PackageTests/Backpack/Includes3/setup-external-ok.test.hs PackageTests/Backpack/Includes2/setup-per-component.test.hs PackageTests/Backpack/Includes2/setup-external.test.hs
```

**Comment by jneira** [comment]
> Not sure if it worths to add it upstream though

Opened a pr upstream: https://github.com/haskell/cabal/pull/8027

**Comment by Mikolaj** [comment]
Thank you. How do I interpret the 'passed' and then 'failed' for things that look the same?

**Comment by jneira** [comment]
> Thank you. How do I interpret the 'passed' and then 'failed' for things that look the same?

it is `lib-tests` vs `lib-suite` and the steps are defined in validate.hs

* `lib-tests` runs the Cabal package tests
* `lib-suite` runs the Cabal specific tests of `cabal-testsuite`

**Comment by Mikolaj** [comment]
Doh, I missed the last words. :)

So these are the same failures we see in 3.7 and we agreed to ignore, right?

**Comment by Mikolaj** [comment]
OK, agreed, Linux-only is sensible cost/benefit, especially relative to 3.7 (by which I mean master branch).

**Comment by Mikolaj** [comment]
Well, at least it seems it wasn't a problem for anybody in 9.2.1, so let's hope it won't be in 9.2.2 either.

Is there anything else left to test? If not, I guess we can bump version (in cabal-install as well, even though we probably don't intend to release it) to 3.6.3 and wait for @emilypi's decision whether/when to release or a release checklist from @emilypi or a volunteer hero that would attempt the release without a checklist (and then we'd all handle the fallout in the coming months).

**Comment by Mikolaj** [comment]
BTW, GHC devs don't need to wait for the release. Just bumping the version and, I guess, a tag, should be should for them.

**Comment by Mikolaj** [comment]
It seems we bumped version already, so I hope the answer to "Is there anything else left to test?" is negative. Closing. Thank you @jneira.
