### ISSUE TITLE
memory-usage-tests fail with GHC 9.2

### ISSUE THREAD

**Issue by robx** [haskell/cabal#8029]
With GHC 9.2, CI runs of the memory-usage-tests suite fail by exhausting the heap:
```
>>> **/memory-usage-tests -j1 --hide-successes 
memory-usage-tests: Heap exhausted;
memory-usage-tests: Current maximum heap size is 8388608 bytes (8 MB).
memory-usage-tests: Use `+RTS -M<size>' to increase it.
<<< **/memory-usage-tests -j1 --hide-successes  (33/212 sec, 251)
<<< /home/runner/work/cabal/cabal/dist-newstyle-validate-ghc-9.2.1/build/x86_64-linux/ghc-9.2.1/cabal-install-3.7.0.0/t/memory-usage-tests/build/memory-usage-tests/memory-usage-tests -j1 --hide-successes  (33/212 sec, 251)
```

Example: https://github.com/haskell/cabal/runs/5411331428?check_suite_focus=true
(master CI runs don't get to the `cli-tests`; that log is from https://github.com/haskell/cabal/pull/8022 which skips failing tests in lib-suite)

The test suite deliberately runs with a heap limited to 8MB:

```
-- Tests to run with a limited stack and heap size
--
Test-Suite memory-usage-tests
[...]
  ghc-options: -threaded -rtsopts "-with-rtsopts=-M8M -K1K"
```

Running locally on macOS with GHC 9.2.1:

```
Memory Usage
  UnitTests.Distribution.Solver.Modular.MemoryUsage
    basic space leak test:          OK (21.46s)
    package with many flags:        OK (6.28s)
    issue #2899:                    OK (4.31s)
    duplicate dependencies:         OK (0.02s)
    duplicate flagged dependencies: memory-usage-tests: Heap exhausted;
memory-usage-tests: Current maximum heap size is 8388608 bytes (8 MB).
memory-usage-tests: Use `+RTS -M<size>' to increase it.
```

**Comment by Mikolaj** [comment]
It seems that heap is artificially restricted to 8MB in the run from the log you provide so, yes, running out of heap would be the signal of test failure.

**Comment by robx** [comment]
Yeah. Would be nice if
- the 8MB limit was more explicit -- guess we could pass it in `validate.sh`? Seems the 8MB is just GHC default, so if that ever changes the tests might accidentally start failing or passing erroneously
- we could see if it's a particular test case that fails (should run this locally, but it'll take a while to build all the dependencies on a new GHC version)

**Comment by Mikolaj** [comment]
I've found this:

```
~/r/cabal$ git grep -7 "\-M8"
cabal-install/cabal-install.cabal-Test-Suite memory-usage-tests
cabal-install/cabal-install.cabal-  import: warnings, base-dep, cabal-dep, cabal-syntax-dep, cabal-install-solver-dep
cabal-install/cabal-install.cabal-  type: exitcode-stdio-1.0
cabal-install/cabal-install.cabal-  main-is: MemoryUsageTests.hs
cabal-install/cabal-install.cabal-  hs-source-dirs: tests
cabal-install/cabal-install.cabal-  default-language: Haskell2010
cabal-install/cabal-install.cabal-
cabal-install/cabal-install.cabal:  ghc-options: -threaded -rtsopts "-with-rtsopts=-M8M -K1K"
```

**Comment by robx** [comment]
Ah great, thanks!

**Comment by robx** [comment]
Judging by this, I'd say there's a modest increase of memory usage with 9.2, but it doesn't appear that things scale worse. I.e., the things the tests test against (exponential space usage) are still fine, and we can raise the limit a bit.

(Also ideally we'd be running the test cases independently, but that seems too complicated to be worth it.)

**Comment by Mikolaj** [comment]
Good call. Let's stick 16MB globally in the cabal file?
