### ISSUE TITLE
cabal init does not work on Ubuntu MATE 20.04.3 (Extremely Fragile!!!!)

### ISSUE THREAD

**Issue by robert-pearson** [haskell/cabal#8031]
robert@A88XM-A:/media/robert/900 GB Shared/Users/robert/VisualWorks Projects/greeter$ cabal init
Could not deserialize <repo>/root.json: Malformed: (line 1, column 1):
unexpected end of input
expecting white space or JSON value

ASUS A88XM-A computer, 32GB RAM, 4TB HDD. Ubuntu MATE 20.04.3 (Extremely Fragile!!!!).

Note. Cabal does not respect the separation of code and data. I use a separate partition for my data so I do not lose it when I have to reinstall Linux (a very frequent occurrence.)

**Comment by Mikolaj** [comment]
Hi @robert-pearson! Thank you for the report. Could you clarify what's your hypothesis why it fails? Is some partition mounted read-only? Which one? What do you expect `cabal init` to do contrary to what it does?

BTW, which cabal and GHC version is this?

**Comment by robert-pearson** [comment]
robert@A88XM-A:~$ cabal --version
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library 
robert@A88XM-A:~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

The most likely bug is that the the json file was corrupt when it was packaged for deployment. The next most likely directory is that your installer followed the philosophy and jammed the code and the data in the Ubuntu directories instead of under my $HOME directory. The only thing special about my installation is that my $HOME directory is in a different partition than the Ubuntu partition. (That allows me to reinstall Ubuntu when it breaks - a very frequent occurrence - without loosing all my apps and settings.) But then, cabal did not work even before I moved it.

Cabal is not the only defective program out there. EclipseFP and stack also do not work.

As a Software Engineer with 4 degrees and 35 years of experience, I find the current decline in the quality of code deplorable.

**Comment by Mikolaj** [comment]
> your installer followed the philosophy

What installer is that?

May I recommend to switch to using ghcup? That may solve all your problems.

**Comment by robert-pearson** [comment]
I installed ghcup. It would be nice if https://cabal.readthedocs.io/en/stable/getting-started.html was correct. The contents of the page do not match what my computer does.  I reminded me of a textbook on IBM assembly language. I took an example from the book and entered it into the computer. The computer detected 22 syntax errors in the example. This is one of the reasons learning a new language is so difficult.
I read an article about why Smalltalk failed. The article did NOT mention that when the companies bought C++ compilers, their coders continued writing in C. Plus the essence of Smalltalk is abstraction. Like perfect pitch, some have this ability, most don't.
I tried the EclipseFP and Atom IDEs. Neither worked. In addition, they are grossly inferior to the 1980 Smalltalk IDE. The System Browser lets you see every Smalltalk resource on your computer and the Package Browser lets you see everything in the online repositories as well. This is why Smalltalkers reuse code and Cites don't.
I wish there was a usable IDE for Haskell.

**Comment by Mikolaj** [comment]
I share your good wishes. Some people report that Visual Studio with HLS is usable, but I can't confirm.

Would you mind pointing out here whenever you find anything wrong at https://cabal.readthedocs.io/en/stable/getting-started.html ? It would be double-useful if you could also cross-check at https://cabal.readthedocs.io/en/latest/ which fixes some documentation things, but pertains to yet unreleased version (3.8).

Thank you for your colourful remarks. This is art (regardless if you mean it as a self-parody or not). I'm also from your punched cards and Z80 assembly age, so I can appreciate.

**Comment by ulysses4ever** [comment]
We haven't heard about it being reproducable with cabal 3 (not even latest, which is cabal 3.8.1 currently, and available from ghcup). Should we close? 

@robert-pearson do you still need any help? In any case, I suggest to upgrade your cabal.

**Comment by Mikolaj** [comment]
I don't hear any objections, so I'm closing. Thanks!
