### ISSUE TITLE
--help text seems wrong for --dis/enable-nix

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#8036]
```
cabal --help
...
 --enable-nix                   Enable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
 --disable-nix                  Disable Nix integration: run commands through
                                nix-shell if a 'shell.nix' file exists
```
in the second line, threre is a negation missing (don't run commands .. even if ..)?

```
cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library 
```

**Comment by Mikolaj** [comment]
Thank you. Indeed, the code just repeats the description of the functionality after the colon, with no negation. It should probably add after the colon "if not disabled, it would...". I wonder if this can be worded in a natural, but precise way.

**Comment by jwaldmann** [comment]
my suggestion above was: 

> never run commands trough nix-shell, even if a `shell.nix` file exists.

is that the correct semantics?

**Comment by Mikolaj** [comment]
I was being unclear. The code repeates *the same* description of the command for both the positive and negative case, only adding a different prefix. I think it's a good idea in general, but it sounds misleading at least in this case.
