### ISSUE TITLE
Option giving the project root directory

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8037]
I think it would be good if one could override the current working directory with a flag, similar to `make -C <root-dir>`.  I'd want this e.g. for executing an non-installed `agda` living in source tree `/agda-root/` from some wd `/bar/`.
```
/bar/$ cabal run --project-root=/agda-root agda -- someFile.agda
```
The name of this option could be bikeshed, e.g. `--project-root`, `--projectdir`, `--directory` (good old `make`).
We already have option `--project-file`, but there are projects that do not have such a file (just a `.cabal` file).

**Comment by cydparser** [comment]
I've implemented this in PR #8454

Please feel free to discuss/bikeshed in the PR.

**Comment by Mikolaj** [comment]
A new proposal dropped at https://github.com/haskell/cabal/pull/8454. Could you kindly voice your opinion?

**Comment by andreasabel** [comment]
Sorry, the option name is `--project-dir`, and that works (since 3.12).
Thanks!
