### ISSUE TITLE
Avoid orphan flexible instances in Cabal-TestSuite documentation

### ISSUE THREAD

**Issue by bos** [haskell/cabal#804]
(Imported from [Trac #814](http://hackage.haskell.org/trac/hackage/ticket/814), reported by guest on 2011-03-13)

The example code shown in
[http://www.haskell.org/cabal/release/cabal-1.10.1.0/doc/users-guide/#test-suites](http://www.haskell.org/cabal/release/cabal-1.10.1.0/doc/users-guide/#test-suites)
needs `FlexibleInstances?`, and the instance is orphan, too.
Although this code is not intended to be used in most packages,
it still looks like those instances are necessary or at least good style.
I suggest to replace the generic pair by a custom data type like

<pre class="wiki">data TestCase = TestCase String Bool
instance TestOptions TestCase where
   ...
</pre>in the documentation.
Since Cabal is a widely used library, it has automatically an educational aspect.

**Comment by ttuegel** [comment]
This hasn't been part of the User Guide in a long time.
