### ISSUE TITLE
cabal: Could not resolve dependencies:

### ISSUE THREAD

**Issue by peter-jerry-ye** [haskell/cabal#8060]
**Describe the bug**
I built a package successfully. After I tried to install it locally (which doesn't seem to work by the way), I can't rebuild it twice.

**To Reproduce**

```
$ git clone https://github.com/keera-studios/keera-hails.git
$ cd keera-hails/keera-hails-reactive-gtk3
$ cabal install --lib
$ cd ../demos/keera-hails-demos-gtk
$ cabal install # doesn't work here even though keera-hails-reactive-gtk3 is installed
$ cd -
$ cabal install # doesn't work here
```

**Expected behavior**
The keera-hails-demos-gtk gets built.
The keera-hails-reactive-gtk3 gets rebuilt on the second time.

**System information**
 - Operating system: Manjaro Linux
 - `cabal`, `ghc` versions: cabal 3.6.2.0, ghc 8.10.7

**Additional context**
Error message:
```
cabal: Could not resolve dependencies:
[__0] trying: keera-hails-reactive-gtk3-0.7.0 (user goal)
[__1] trying: gtk3-0.15.6 (dependency of keera-hails-reactive-gtk3)
[__2] trying: gtk3:setup.gtk2hs-buildtools-0.13.8.2 (dependency of gtk3)
[__3] trying: gtk3:setup.hashtables-1.2.3.2 (dependency of
gtk3:setup.gtk2hs-buildtools)
[__4] trying: gtk3:setup.primitive-0.6.4.0 (dependency of
gtk3:setup.hashtables)
[__5] next goal: gtk3:setup.Cabal (dependency of gtk3)
[__5] rejecting: gtk3:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13, gtk3:setup.Cabal =>
gtk3:setup.base==4.14.3.0/installed-4.14.3.0)
[__5] rejecting: gtk3:setup.Cabal-3.6.3.0 (conflict: gtk3 =>
gtk3:setup.Cabal>=1.24 && <3.3)
[__5] skipping: gtk3:setup.Cabal-3.6.2.0, gtk3:setup.Cabal-3.6.1.0,
gtk3:setup.Cabal-3.6.0.0, gtk3:setup.Cabal-3.4.1.0, gtk3:setup.Cabal-3.4.0.0
(has the same characteristics that caused the previous version to fail:
excluded by constraint '>=1.24 && <3.3' from 'gtk3')
[__5] trying: gtk3:setup.Cabal-3.2.1.0
[__6] next goal: gtk3:setup.base (dependency of gtk3)
[__6] rejecting: gtk3:setup.base-4.14.3.0/installed-4.14.3.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13)
[__6] rejecting: gtk3:setup.base-4.10.0.0, gtk3:setup.base-4.9.1.0,
gtk3:setup.base-4.9.0.0, gtk3:setup.base-4.8.2.0, gtk3:setup.base-4.8.1.0,
gtk3:setup.base-4.8.0.0, gtk3:setup.base-4.7.0.2, gtk3:setup.base-4.7.0.1,
gtk3:setup.base-4.7.0.0, gtk3:setup.base-4.6.0.1, gtk3:setup.base-4.6.0.0,
gtk3:setup.base-4.5.1.0, gtk3:setup.base-4.5.0.0, gtk3:setup.base-4.4.1.0,
gtk3:setup.base-4.4.0.0, gtk3:setup.base-4.3.1.0, gtk3:setup.base-4.3.0.0,
gtk3:setup.base-4.2.0.2, gtk3:setup.base-4.2.0.1, gtk3:setup.base-4.2.0.0,
gtk3:setup.base-4.1.0.0, gtk3:setup.base-4.0.0.0, gtk3:setup.base-3.0.3.2,
gtk3:setup.base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
[__6] fail (backjumping, conflict set: gtk3, gtk3:setup.base,
gtk3:setup.primitive)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: gtk3:setup.Cabal, gtk3:setup.base,
gtk3, gtk3:setup.primitive, gtk3:setup.hashtables,
gtk3:setup.gtk2hs-buildtools, keera-hails-reactive-gtk3
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by Mikolaj** [comment]
Hi @peter-jerry-ye,

It's `git clone` and `cabal install` and, ideally, you should not require `--lib`, but depend on the library source via a cabal project file or in some other way.

**Comment by peter-jerry-ye** [comment]
> It's `git clone` and `cabal install`

@Mikolaj Thank you for pointing out the typo.

> and, ideally, you should not require `--lib`, but depend on the library source via a cabal project file or in some other way.

I did that because in the [document](https://cabal.readthedocs.io/en/3.6/cabal-commands.html#cabal-v2-install) it said that:

> It is also possible to “install” libraries using the --lib flag.

which I thought it was used for installing a library locally. I had an impression that a few years ago it was done like this but I'm still learning how to do it properly. Thank you for your advice.

As of the issue itself. I've tried to uninstall/reinstall the cabal, remove the .cabal directory, but neither solved the problem. Could you point out where the problem is please? Thank you.

**Comment by Mikolaj** [comment]
This doesn't seem to be a cabal problem. Perhaps the gtk3 verison keera-hails-reactive requires is too old? I'd recommend to ask on a forum where keera-hails-reactive or gtk3 users could give you some hints. Or just any Haskell beginner forum. Try to apply what the last line in the log says. Paste the log and ask people. They may advise to try building gtk3 first or looking up the version fo gtk3 in the .cabal file of keera-hails-reactive. Etc.

**Comment by jneira** [comment]
From

```
[__6] rejecting: gtk3:setup.base-4.14.3.0/installed-4.14.3.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13)
```

i would suggest try to build it with ghc-8.6.5 which is the newer ghc version with base < 4.13

**Comment by peter-jerry-ye** [comment]
Hello @Mikolaj @jneira ,

Actually I succeeded in building it for the first time. But the rest of the builds all failed. I've also applied the last line in the log but that didn't really work.

I had another project that didn't rely on gtk3 but gtk(2) on the same computer, and it required a dependency of `keera-hails-reactivevalues` that is also used inside this project. It used to work well (build ok, run ok), but somehow it also got corrupted after this event with the same error message. So I suppose that the `install --lib` might have corrupted some information about the dependency tree.

Thank you.

**Comment by Mikolaj** [comment]
@peter-jerry-ye: I'm not able to follow. Could you illustrate all you say with copies of logs? Saying "it" doesn't really help. :)

**Comment by peter-jerry-ye** [comment]
@Mikolaj 
Sorry for not explaining clearly enough.

So here is the log for `keera-hails-reactive-gtk3`:
```
$ cabal build --minimize-conflict-set
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: keera-hails-reactive-gtk3-0.7.0 (user goal)
[__1] trying: gtk3-0.15.6 (dependency of keera-hails-reactive-gtk3)
[__2] trying: gtk3:setup.gtk2hs-buildtools-0.13.8.2 (dependency of gtk3)
[__3] trying: gtk3:setup.hashtables-1.2.3.2 (dependency of
gtk3:setup.gtk2hs-buildtools)
[__4] trying: gtk3:setup.primitive-0.6.4.0 (dependency of
gtk3:setup.hashtables)
[__5] next goal: gtk3:setup.Cabal (dependency of gtk3)
[__5] rejecting: gtk3:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13, gtk3:setup.Cabal =>
gtk3:setup.base==4.14.3.0/installed-4.14.3.0)
[__5] rejecting: gtk3:setup.Cabal-3.6.3.0 (conflict: gtk3 =>
gtk3:setup.Cabal>=1.24 && <3.3)
[__5] skipping: gtk3:setup.Cabal-3.6.2.0, gtk3:setup.Cabal-3.6.1.0,
gtk3:setup.Cabal-3.6.0.0, gtk3:setup.Cabal-3.4.1.0, gtk3:setup.Cabal-3.4.0.0
(has the same characteristics that caused the previous version to fail:
excluded by constraint '>=1.24 && <3.3' from 'gtk3')
[__5] trying: gtk3:setup.Cabal-3.2.1.0
[__6] next goal: gtk3:setup.base (dependency of gtk3)
[__6] rejecting: gtk3:setup.base-4.14.3.0/installed-4.14.3.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13)
[__6] rejecting: gtk3:setup.base-4.10.0.0, gtk3:setup.base-4.9.1.0,
gtk3:setup.base-4.9.0.0, gtk3:setup.base-4.8.2.0, gtk3:setup.base-4.8.1.0,
gtk3:setup.base-4.8.0.0, gtk3:setup.base-4.7.0.2, gtk3:setup.base-4.7.0.1,
gtk3:setup.base-4.7.0.0, gtk3:setup.base-4.6.0.1, gtk3:setup.base-4.6.0.0,
gtk3:setup.base-4.5.1.0, gtk3:setup.base-4.5.0.0, gtk3:setup.base-4.4.1.0,
gtk3:setup.base-4.4.0.0, gtk3:setup.base-4.3.1.0, gtk3:setup.base-4.3.0.0,
gtk3:setup.base-4.2.0.2, gtk3:setup.base-4.2.0.1, gtk3:setup.base-4.2.0.0,
gtk3:setup.base-4.1.0.0, gtk3:setup.base-4.0.0.0, gtk3:setup.base-3.0.3.2,
gtk3:setup.base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
[__6] fail (backjumping, conflict set: gtk3, gtk3:setup.base,
gtk3:setup.primitive)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: gtk3:setup.Cabal, gtk3,
gtk3:setup.base, gtk3:setup.primitive, gtk3:setup.hashtables,
gtk3:setup.gtk2hs-buildtools, keera-hails-reactive-gtk3
```

And another project that I wrote myself using also `gtk` and `keera-hails-reactivevalues` that are also the dependencies of `keera-hails-reactive-gtk3`, here is the log:
```
$ cabal run --minimize-conflict-set
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: my-gtk-0.1.0.0 (user goal)
[__1] trying: keera-hails-reactive-cbmvar-0.7.0 (dependency of my-gtk)
[__2] trying: lens-5.1 (dependency of keera-hails-reactive-cbmvar)
[__3] trying: vector-0.12.3.1 (dependency of lens)
[__4] trying: primitive-0.6.4.0 (dependency of vector)
[__5] next goal: transformers (dependency of lens)
[__5] rejecting: transformers-0.5.6.2/installed-0.5.6.2 (conflict: primitive
=> base>=4.5 && <4.13, transformers => base==4.14.3.0/installed-4.14.3.0)
[__5] rejecting: transformers-0.6.0.4 (conflict: lens => transformers>=0.5.0.0
&& <0.6)
[__5] skipping: transformers-0.6.0.3, transformers-0.6.0.2 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=0.5.0.0 && <0.6' from 'lens')
[__5] trying: transformers-0.5.6.2
[__6] next goal: base (dependency of my-gtk)
[__6] rejecting: base-4.14.3.0/installed-4.14.3.0 (conflict: primitive =>
base>=4.5 && <4.13)
[__6] rejecting: base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__6] fail (backjumping, conflict set: base, my-gtk, primitive)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, primitive, vector, lens,
transformers, my-gtk, keera-hails-reactive-cbmvar
```

**Comment by peter-jerry-ye** [comment]
@Mikolaj 
Sorry for not explaining clearly enough.

So here is the log for `keera-hails-reactive-gtk3`:
```
$ cabal build --minimize-conflict-set
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: keera-hails-reactive-gtk3-0.7.0 (user goal)
[__1] trying: gtk3-0.15.6 (dependency of keera-hails-reactive-gtk3)
[__2] trying: gtk3:setup.gtk2hs-buildtools-0.13.8.2 (dependency of gtk3)
[__3] trying: gtk3:setup.hashtables-1.2.3.2 (dependency of
gtk3:setup.gtk2hs-buildtools)
[__4] trying: gtk3:setup.primitive-0.6.4.0 (dependency of
gtk3:setup.hashtables)
[__5] next goal: gtk3:setup.Cabal (dependency of gtk3)
[__5] rejecting: gtk3:setup.Cabal-3.2.1.0/installed-3.2.1.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13, gtk3:setup.Cabal =>
gtk3:setup.base==4.14.3.0/installed-4.14.3.0)
[__5] rejecting: gtk3:setup.Cabal-3.6.3.0 (conflict: gtk3 =>
gtk3:setup.Cabal>=1.24 && <3.3)
[__5] skipping: gtk3:setup.Cabal-3.6.2.0, gtk3:setup.Cabal-3.6.1.0,
gtk3:setup.Cabal-3.6.0.0, gtk3:setup.Cabal-3.4.1.0, gtk3:setup.Cabal-3.4.0.0
(has the same characteristics that caused the previous version to fail:
excluded by constraint '>=1.24 && <3.3' from 'gtk3')
[__5] trying: gtk3:setup.Cabal-3.2.1.0
[__6] next goal: gtk3:setup.base (dependency of gtk3)
[__6] rejecting: gtk3:setup.base-4.14.3.0/installed-4.14.3.0 (conflict:
gtk3:setup.primitive => gtk3:setup.base>=4.5 && <4.13)
[__6] rejecting: gtk3:setup.base-4.10.0.0, gtk3:setup.base-4.9.1.0,
gtk3:setup.base-4.9.0.0, gtk3:setup.base-4.8.2.0, gtk3:setup.base-4.8.1.0,
gtk3:setup.base-4.8.0.0, gtk3:setup.base-4.7.0.2, gtk3:setup.base-4.7.0.1,
gtk3:setup.base-4.7.0.0, gtk3:setup.base-4.6.0.1, gtk3:setup.base-4.6.0.0,
gtk3:setup.base-4.5.1.0, gtk3:setup.base-4.5.0.0, gtk3:setup.base-4.4.1.0,
gtk3:setup.base-4.4.0.0, gtk3:setup.base-4.3.1.0, gtk3:setup.base-4.3.0.0,
gtk3:setup.base-4.2.0.2, gtk3:setup.base-4.2.0.1, gtk3:setup.base-4.2.0.0,
gtk3:setup.base-4.1.0.0, gtk3:setup.base-4.0.0.0, gtk3:setup.base-3.0.3.2,
gtk3:setup.base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
[__6] fail (backjumping, conflict set: gtk3, gtk3:setup.base,
gtk3:setup.primitive)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: gtk3:setup.Cabal, gtk3,
gtk3:setup.base, gtk3:setup.primitive, gtk3:setup.hashtables,
gtk3:setup.gtk2hs-buildtools, keera-hails-reactive-gtk3
```

And another project that I wrote myself using also `gtk` and `keera-hails-reactivevalues` that are also the dependencies of `keera-hails-reactive-gtk3`, here is the log:
```
$ cabal run --minimize-conflict-set
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: my-gtk-0.1.0.0 (user goal)
[__1] trying: keera-hails-reactive-cbmvar-0.7.0 (dependency of my-gtk)
[__2] trying: lens-5.1 (dependency of keera-hails-reactive-cbmvar)
[__3] trying: vector-0.12.3.1 (dependency of lens)
[__4] trying: primitive-0.6.4.0 (dependency of vector)
[__5] next goal: transformers (dependency of lens)
[__5] rejecting: transformers-0.5.6.2/installed-0.5.6.2 (conflict: primitive
=> base>=4.5 && <4.13, transformers => base==4.14.3.0/installed-4.14.3.0)
[__5] rejecting: transformers-0.6.0.4 (conflict: lens => transformers>=0.5.0.0
&& <0.6)
[__5] skipping: transformers-0.6.0.3, transformers-0.6.0.2 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=0.5.0.0 && <0.6' from 'lens')
[__5] trying: transformers-0.5.6.2
[__6] next goal: base (dependency of my-gtk)
[__6] rejecting: base-4.14.3.0/installed-4.14.3.0 (conflict: primitive =>
base>=4.5 && <4.13)
[__6] rejecting: base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__6] fail (backjumping, conflict set: base, my-gtk, primitive)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, primitive, vector, lens,
transformers, my-gtk, keera-hails-reactive-cbmvar
```

**Comment by peter-jerry-ye** [comment]
And for comparison, the `keera-hails-reactive-gtk3` has following dependencies:
```
  build-depends:
      base >= 4
    , mtl
    , gtk3
    , gtk3-helpers
    , pango
    , keera-hails-reactivevalues
```

and my project has following dependencies:
```
    build-depends:    
    	base ^>=4.14.3.0
      , keera-hails-reactivevalues
      , keera-hails-reactive-gtk
      , gtk
      , keera-hails-reactive-cbmvar
      , keera-callbacks
```

Sorry for sending the previous message twice. Bad network.

**Comment by Mikolaj** [comment]
Thank you for the details.  `--minimize-conflict-set` seems to work fine --- the "After searching the rest of the dependency tree exhaustively" line is minimized. As you can see in the first log, it's building gtk3 that fails, so @jneira's advice applies. In the second case, looking at the .cabal file, you are probably shooting yourself in the foot by preventing new base version to be used (the `^>=` operator; did you look it up in the manual?).

I think with the amount and precisions of details you are now posting, you could really get good guidance on IRC or Matrix of Discord or any other Haskell beginner forum. Good luck and let us know if you come across any cabal bugs. I'm closing the ticket.

**Comment by jneira** [comment]
> Actually I succeeded in building it for the first time. But the rest of the builds all failed. I've also applied the last line in the log but that didn't really work.

That is the weird bit, that build should have failed too. I would delete any `~/.ghc/` just in case environment files created by the first `cabal install --lib` is interfering the builds

After that, if it still doesnt work i would try with ghc-8.6.5

> And for comparison, the keera-hails-reactive-gtk3 has following dependencies:

Note than the error mentions `gtk3:setup` so it is about the dependencies set in the `setup-depends` field of the gtk3 [package](https://hackage.haskell.org/package/gtk3-0.15.6/gtk3.cabal):

```
custom-setup
  setup-depends: base >= 4.6,
                 Cabal >= 1.24 && < 3.3,
                 gtk2hs-buildtools >= 0.13.2.0 && < 0.14
```

**Comment by peter-jerry-ye** [comment]
@jneira That's the exact problem that bothers me. Especially there's another project that used to work and it doesn't work any more. I don't understand where the conflict come from and if possible, I don't mind to reinstall the whole ghc-related system etc. But it just doesn't work and I don't know how to reset it to the past state.

**Comment by jneira** [comment]
> But it just doesn't work and I don't know how to reset it to the past state.

had you the chance to try deleting `~/.ghc`? It should contain environment files from your `cabal install --lib` which could interfere the rest of builds, as they are globally used.
That is the main reason `cabal install --lib` should be used very very carefully (and be avoided as much as possible)

**Comment by peter-jerry-ye** [comment]
> had you the chance to try deleting `~/.ghc`? 

Yes. I even tried to delete the `~/.cabal` directory and reinstalled cabal with ghcup but it just doesn't work.

**Comment by Mikolaj** [comment]
But did you delete `~/.ghc`? It's not *inside* `~/.cabal`.

**Comment by jneira** [comment]
hmm have you tried a second `cabal install --lib`? maybe the `--lib` bit does not take in account the setup-depends and that makes the build succeed

**Comment by peter-jerry-ye** [comment]
> hmm have you tried a second `cabal install --lib`? 

It's not working due to the error appeared in the log above despite I've deleted ~/.ghc and cleaned up ~/.cabal.

By the way, I reviewed my bash history and I found that I may have run the command with `cabal install --lib -package-env somedir` once. Does that mess things up?

**Comment by peter-jerry-ye** [comment]
@Mikolaj @jneira

The problem is solved. Sorry for your time.

The actual problem was that the mirror I was using (because I'm in China) changed their policy. It seems that they changed from `Secure: False` to `Secure: True`, so my cabal may not have fetched the latest information.

**Comment by Mikolaj** [comment]
@peter-jerry-ye: good for you! Take care.
