### ISSUE TITLE
Must `import` really be the first field in a section?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#8067]
Is there a good reason why import must be the first field in a section?

```rst
-  ``import`` must be the first field in a section. Since Cabal 3.0 imports
   are also allowed inside conditionals.
```

SOURCE : [`doc/cabal-package.rst`](https://github.com/haskell/cabal/blame/9f584153bf3886eaace65e9ab87d18c5d77d7b45/doc/cabal-package.rst#L2763-L2764)

I'm trying to generate a `.cabal` file using hpack. With hpack's [verbatim mechanism](https://github.com/sol/hpack#passing-things-to-cabal-verbatim) I can generate `common name` and `import name` but these are appended after all other fields known to hpack are processed. The generated `.cabal` file is good except for `import name` not being the first field in its enclosing section. With this disorder, `cabal build` gives a warning (shouldn't it give an error if it recognises the field name but it is in the wrong order?):

```
> cabal build
Warning: some-package.cabal: Unknown field: import. Common stanza imports
should be at the top of the enclosing section
```

For a human reading a section it makes a lot of sense to require import to be first.

**Comment by Mikolaj** [comment]
When you look at cabal code, would another location of import require backtracking when parsing or when interpreting the file? E.g., would you need to look ahead, find the import and only then re-read the section? Given that some programs, e.g., hackage tools and solver in cabal-install, parse many .cabal files at once, this may be costly. Just a hypothesis.

**Comment by typedrat** [comment]
The issue is that successive repetitions of the same field tend to combine monoidally, and these monoids are not commutative, so `import` always comes first to ensure that they're at the head of the monoidal concatenation.

**Comment by philderbeast** [comment]
Thanks for the explanation @typedrat. With the latest release hpack is [putting import first](https://hackage.haskell.org/package/hpack-0.34.7/changelog).
