### ISSUE TITLE
cabal-install clobbers itself on multi-arch platforms

### ISSUE THREAD

**Issue by bos** [haskell/cabal#810]
(Imported from [Trac #820](http://hackage.haskell.org/trac/hackage/ticket/820), reported by @bos on 2011-03-23)

On my Mac, I have 32-bit and 64-bit versions of GHC 7.0.2 installed, and cabal installs the object and interface files into the same directory.

The <tt>$arch</tt> variable looks like it should do the right thing, but in fact it's expanded to whatever architecture cabal-install was built for, not the architecture that's supported by GHC itself.

**Comment by gbaz** [comment]
I think all the various tech in place means this issue is well-resolved and can be closed?

**Comment by hvr** [comment]
I think `new-build` does a much better job here thanks to nix-style hashing, but we need to check whether all clashing has been addressed... and document which isn't or cannot

**Comment by gbaz** [comment]
Even without `new-build` individual ghcs keep their packagedb distinguished by arch, which is enough to resolve this afaik.

This ticket is only about arch stuff, so I suggest it be closed. Other tickets can track other sorts of clashing.

**Comment by hvr** [comment]
yeah, the package-db, but there was quite some stuff that still got clashed in `~/.cabal/` overwriting each other... and that part got better w/ new-build :-)
