### ISSUE TITLE
about command "cabal update"

### ISSUE THREAD

**Issue by MathildaStacy** [haskell/cabal#8100]
**Describe the bug**
When I use command "cabal update", it can't add files like "01-*" in directory ".cabal/package/"website"/

**To Reproduce**
cabal update

and then check the file

$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
A clear and concise description of what you expected to happen.

**System information**
 version 3.6.2.0

**Additional context**
Add any other context about the problem here.
No.

**Comment by MathildaStacy** [comment]
I am a fucking idiot.....

**Comment by jneira** [comment]
Dont think so, behind every human and apparently silly error there is a opportunity to improve tools ux, so feel free to expose how cabal could have helped you to avoid it

**Comment by MathildaStacy** [comment]
> Dont think so, behind every human and apparently silly error there is a opportunity to improve tools ux, so feel free to expose how cabal could have helped you to avoid it

thank you for you encouragement!
