### ISSUE TITLE
`cabal haddock --enable-documentation --haddock-for-hackage` produces internal error

### ISSUE THREAD

**Issue by konsumlamm** [haskell/cabal#8110]
**Describe the bug**
Running `cabal haddock --enable-documentation --haddock-for-hackage` in my project produces an internal error:
```
haddock: internal error: ~/.cabal/store/ghc-9.0.2/indexed-traversable-0.1.2-044727e134ac2304803377aafa5a283b3f96400095892cd194503f9961bbc9cf/share/doc/html/doc-index.json: openBinaryFile: does not exist (No such file or directory)
```

**To Reproduce**

Unfortunately I was not able to reproduce this in a small example project.
```
$ git clone https://github.com/konsumlamm/rrb-vector.git
$ cd rrb-vector/
$ git checkout e43212bccfbbff4b0e1ced53558fe9e26d426ff0
$ cabal haddock --enable-documentation --haddock-for-hackage
```

**Expected behavior**
No internal error.

**System information**
 - `cabal` version: 3.6.2.0
 - `ghc` version: 9.0.2

**Comment by jneira** [comment]
thanks for the bug report, have you tried to wipe out the cabal store (or using a fresh one with `--store-dir`) to check if it reproduces consistently?

**Comment by jneira** [comment]
maybe related #8104

**Comment by konsumlamm** [comment]
> have you tried to wipe out the cabal store (or using a fresh one with `--store-dir`) to check if it reproduces consistently?

I get the same error after deleting `~/.cabal/store/ghc-9.0.2/`.

> maybe related #8104

This might actually be a duplicate, at least the error message looks the same.

**Comment by jneira** [comment]
yeah, moreover the initial failing command was the same:

> The original command that was failing me for was cabal haddock --haddock-for-hackage --enable-documentation, which I have CI run to generate Haddock artifacts remotely

so if you can reproduce it with the final command, we could confirm is the same thing

**Comment by konsumlamm** [comment]
> so if you can reproduce it with the final command and the same workaround works for you, we could confirm is the same thing

Yep, I can reproduce it and the workaround works.

Closing as duplicate of #8104.
