### ISSUE TITLE
`build` and `run` does not respect `-fforce-recomp`

### ISSUE THREAD

**Issue by zliu41** [haskell/cabal#8132]
I have a minimal test-suite where Main.hs has the `-fforce-recomp` flag:

```haskell
{-# OPTIONS_GHC -fforce-recomp #-}

module Main where

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

When I run `cabal v2-test`, Main.hs is re-compiled every time. But when running `cabal v2-build` or `cabal v2-run`, Cabal simply says "Up to date".

Cabal version: 3.6.2.0
GHC version: 8.10.7

**Comment by Mikolaj** [comment]
Hi! Thanks for the report. There is some explanation of the current status at https://github.com/haskell/cabal/issues/7496 and a discussion of an alternative tool (targetted `cabal clean`) at https://github.com/haskell/cabal/issues/7496.

Does that cover your situation? If so, you may want to close this tickets and comment on the others (e.g., how `cabal clean` is not sufficient for your use case).

**Comment by ulysses4ever** [comment]
@Mikolaj since we didn’t get a reply from the author, I suggest we close it as a dump for #7496.

**Comment by Mikolaj** [comment]
Yes indeed, thank you everyone, closing.
