### ISSUE TITLE
cabal install --enable-tests does not install test dependencies.

### ISSUE THREAD

**Issue by bos** [haskell/cabal#814]
(Imported from [Trac #824](http://hackage.haskell.org/trac/hackage/ticket/824), reported by @creswick on 2011-03-28)

Cabal install normally installs all the necessary project dependencies; however, this is not happening for the dependencies specified in the Test-suite stanzas.  Here's an example cabal file:

<pre class="wiki">Name:           foo
Version:        1.0
License:        BSD3
Cabal-Version:  &gt;= 1.9.2
Build-Type:     Simple
executable foo
    main-is: foo.hs
    build-depends: base
                 , xml == 1.3.7
Test-Suite test-foo
    type:       exitcode-stdio-1.0
    main-is:    test-foo.hs
    build-depends: base
                  , QuickCheck &gt;= 2.0
</pre><tt>cabal install</tt> will install xml if necessary, then build foo, but <tt>cabal install --enable-tests</tt> complains that `QuickCheck?` is not available:

<pre class="wiki"> $ cabal install --enable-tests
Resolving dependencies...
Configuring foo-1.0...
cabal: At least the following dependencies are missing:
QuickCheck &gt;=2.0
cabal: Error: some packages failed to install:
foo-1.0 failed during the configure step. The exception was:
ExitFailure 1
</pre>This causes some problems when building tests with <tt>cabal-dev</tt>:

[https://github.com/creswick/cabal-dev/issues#issue/10](https://github.com/creswick/cabal-dev/issues#issue/10)

(Using cabal-install 0.10.2 built with Cabal 1.10.1.0)

**Comment by JacquesCarette** [comment]
I am encountering this now with cabal 1.22.6.0.  Regression?

**Comment by ttuegel** [comment]
@JacquesCarette What package is causing the problem for you?

**Comment by JacquesCarette** [comment]
@ttuegel In this case, it was quickcheck.  Unsurprisingly, it is only used by our test suite, and not the main executable of Hakaru (https://github.com/hakaru-dev/hakaru).  I believe that Hakaru is still in the state that if you do
cabal configure --enable-tests
cabal install --dependencies-only
and you don't have the right quickcheck installed, it will fail.

**Comment by ttuegel** [comment]
@JacquesCarette The `cabal install` command does not recognize any options given to `cabal configure`; they are part of completely separate workflows. You need to run `cabal install --dependencies-only --enable-tests` to get test dependencies installed.

**Comment by JacquesCarette** [comment]
Ah, that was REALLY not obvious, from any of the cabal documentation that I've read.  I'll try that (can't do it, my system's not properly configured)

**Comment by gallais** [comment]
Seems like we have gotten the regression after all: https://github.com/actions/starter-workflows/issues/228

I am trying to get tests running using github actions and I cannot find a way
to get the test-suite's dependencies installed. Ideally I would like to use the
same command for all the cabals from version 2.0 to 3.0 that are being tested.

My unsuccessful attempts: https://github.com/msp-strath/Mary/pull/9

**Comment by jwatte** [comment]
Yes, this again fails, with `cabal install --dependencies-only --enable-tests`
The error is: `cabal: --enable-tests was specified, but tests can't be enabled in a remote package`
