### ISSUE TITLE
custom-setup documentation says optional, but it is actually mandatory

### ISSUE THREAD

**Issue by noughtmare** [haskell/cabal#8141]
The documentation here says the `custom-setup` stanza is optional:

https://github.com/haskell/cabal/blob/c901542c1d658ae949e6a8c922ab87a56e26b223/doc/cabal-package.rst?plain=1#L2893-L2894

But leaving that stanza out produces this error for me:

```
Since cabal-version: 1.24 specifying custom-setup section is mandatory
```

There also seems to be insconsistent use of "stanza" and "section" terminology.

**Comment by fgaz** [comment]
I think whoever wrote that meant that it's optional in the sense that you only need it if build-type = Custom
