### ISSUE TITLE
Does the build plan include dependencies of sub-libraries that aren't built?

### ISSUE THREAD

**Issue by danidiaz** [haskell/cabal#8143]
Hi, I have a question about how the [public sublibraries](https://github.com/haskell/cabal/issues/5660) feature of Cabal works.

Take [this repo](https://github.com/danidiaz/sublibrary-experiment) as an example.

In the repo, the [tests](https://github.com/danidiaz/sublibrary-experiment/blob/aaf25bbe616a012e73bcaf6a946674c48496965e/wumpus-json/wumpus-json.cabal#L41) in package [wumpus-json](https://github.com/danidiaz/sublibrary-experiment/tree/main/wumpus-json) depend on a [public sublibrary](https://github.com/danidiaz/sublibrary-experiment/blob/aaf25bbe616a012e73bcaf6a946674c48496965e/wumpus/wumpus.cabal#L29) ("wumpus-test-support") of [wumpus](https://github.com/danidiaz/sublibrary-experiment/tree/main/wumpus). But the [main library](https://github.com/danidiaz/sublibrary-experiment/blob/aaf25bbe616a012e73bcaf6a946674c48496965e/wumpus-json/wumpus-json.cabal#L23) of  [wumpus-json](https://github.com/danidiaz/sublibrary-experiment/tree/main/wumpus-json)  doesn't depend on the sublibrary.

```mermaid
graph TD
    wumpus-json --> wumpus
    wumpus-json-test --> wumpus
    wumpus-json-test --> wumpus-test-support
```

If I put an [unsatisfiable dependency](https://github.com/danidiaz/sublibrary-experiment/blob/aaf25bbe616a012e73bcaf6a946674c48496965e/wumpus/wumpus.cabal#L36) on the `build-depends:` of the "wumpus-test-support" sublibrary, and then  try to build the main library of "wumpus-json" with `cabal build wumpus-json:lib:wumpus-json`, I get a build plan error. I thought that perhaps it could still compile, given that the "wumpus-test-support" sublibrary is not required in this case—only for the tests.

Is this the expected behavior?

(I'm using cabal-install 3.6.2.0)

**Comment by Mikolaj** [comment]
OOI, if you have a single main library and an executable that does not use it, does cabal build the main library when you ask it specifically to run the executable?

**Comment by danidiaz** [comment]
> if you have a single main library and an executable that does not use it, does cabal build the main library when you ask it specifically to run the executable?

No, it doesn't build the library. 

However, if I put an unsatisfiable dependency on the `build-depends:` of the library and try to build the executable, the build fails.

**Comment by fgaz** [comment]
> Perhaps related to per-component dependency solving? https://github.com/haskell/cabal/issues/4087?

Yes, that's exactly it. Closing in favor of #4087.

I wonder what's the state of that ticket
