### ISSUE TITLE
Allow passing test options using `---`

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#8148]
At the moment, you have to pass options to test suite executables with `--test-options`. This is a bit inconvenience since you often have to quote the options, and then escape quotes inside them.

We could instead allow providing options to the test suite after `---`. This is a fairly standard CLI idiom, and already works for `cabal run`.

An argument against is that `cabal test` can take multiple components to test and it would have to give them all the same arguments, which might not be appropriate, but the same is true today of `--test-options`.

**Comment by fendor** [comment]
I think this looks a lot like https://github.com/haskell/cabal/issues/6198

**Comment by michaelpj** [comment]
Yep, it's a dupe.
