### ISSUE TITLE
Bootstrap CI job fails with new versions of packages

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8166]
so I temporarily switched it to 8.6.5. This fails both on master branch and 3.8 branch.

Last failing log: https://github.com/haskell/cabal/runs/6594921625?check_suite_focus=true

Edit: to clarity, CI fails after I *regenerate* the boostrap JSON files with `make bootstrap-jsons`. And the old boostrap JSON files were failing due to bumped versions in cabal .cabal files.

**Comment by Mikolaj** [comment]
Actually, it fails with GHC 8.6.5, so I reverted the boostrap refresh from 3.8 branch, but this remains a problem on master branch (once #8163 lands; or perhaps it should block #8163).

**Comment by robx** [comment]
I made a change to bootstrap.py to generate missing Setup.hs here: https://github.com/haskell/cabal/pull/8194

**Comment by Mikolaj** [comment]
> I made a change to bootstrap.py to generate missing Setup.hs here: #8194

Amazing. Thank you. That's quite critical for some users, given the pending major release.

**Comment by fgaz** [comment]
Is this resolved?

**Comment by Mikolaj** [comment]
Yes, it is, you are right. Closing.
