### ISSUE TITLE
Update the list of GHC extension for GHC 9.2 and 9.4

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8168]
This should not be to hard, based on GHC release notes or user guide, and should go in file Cabal-syntax/src/Language/Haskell/Extension.hs. I don't know if any extensions from 9.2 are missing, or perhaps even 9.0, so worth checking all.

**Comment by ffaf1** [comment]
A note for future updates, [Overview of all language extensions](https://downloads.haskell.org/ghc/9.4.1-alpha2/docs/users_guide/exts/table.html) is sadly *not* exhaustive (e.g. see [DoAndIfThenElse is undocumented](https://gitlab.haskell.org/ghc/ghc/-/issues/18631)).

**Comment by ffaf1** [comment]
I did not include undocumented language extensions `AlternativeLayoutRule`, `AlternativeLayoutRuleTransitional`, `RelaxedLayout`.

**Comment by Mikolaj** [comment]
Thank you! 

Is there a chance somebody is using the undocumented extensions and cabal would yell at that person? If it yells, should it yell "unknown or undocumented in GHC user manual" instead of the current (I assume) "uknown"?

**Comment by ffaf1** [comment]
There is very little information on the GHC repo, especially for `AlternativeLayoutRule` and `AlternativeLayoutRuleTransitional`. Despite the lack of documentation or advertising, some users [managed to stumble on those](https://gitlab.haskell.org/ghc/ghc/-/issues/13087).

 `ghc --supported-languages` lists them and they are not experimental, so I made a pull request including them.
