### ISSUE TITLE
Language extensions links are broken

### ISSUE THREAD

**Issue by ffaf1** [haskell/cabal#8172]
**Describe the bug**
Language extensions links to GHC documentation are broken.

**To Reproduce**
Go [there](https://hackage.haskell.org/package/Cabal-3.6.3.0/docs/Language-Haskell-Extension.html#t:KnownExtension), click on a few links.
Issue is not new (#4582).

Instead of providing a link for each extension, why don’t we leave the brief description and just place a link to GHC manual, Language Extension section on top of `data KnownExtension`? It would reduce breakage being only slightly less convenient.

**Comment by ulysses4ever** [comment]
Good idea. The only issue is that the link to language extensions list tends to change over time too. I'd suggest linking not the `latest` version of the docs but some specific version, and update the link every Cabal release (add it to the release checklist).
