### ISSUE TITLE
RFC: Ditch Section 3 (Configuration and Installing Packages) of the manual

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8177]
Currently, [the section called "Configuration and Installing Packages"][doc] consists of two subsections: 
 - 3.1. Configuration
 - 3.2. Building and installing packages

3.1 describes various configuration parameters of cabal CLI in a rather reference-like style, and, as such, I argue, belongs to section 6 (cabal-install Commands).

3.2 is basically empty: it holds "To be written" and than drops a rather problematic statement that you should use `cabal install` to install a package: without specifying whether you talk about local or external package this statement may or may not be fair. I think this text can be removed altogether.

[doc]: https://cabal.readthedocs.io/en/3.6/config-and-install.html

**Comment by ulysses4ever** [comment]
Based on a mildly positive feedback (in the form of emoji reactions), I went ahead and opened a pull request.

**Comment by Kleidukos** [comment]
@ivanperez-keera I invite you to review the associated PR if you have any remarks

**Comment by Mikolaj** [comment]
>     * Can we not make decisions about cabal based on two thumbs up on a comment?

@ivanperez-keera: thank you for caring, but please rest assured we are not making decisions based on an existence of a PR and PRs are sometimes a better way to brainstorm than vague musings in an issue.

Could you share your feedback?

**Comment by ulysses4ever** [comment]
@ivanperez-keera good point about the link! I added it to the the top post, and here it is again: ["Configuration and Installing Packages"][doc].

[doc]: https://cabal.readthedocs.io/en/3.6/config-and-install.html
