### ISSUE TITLE
Meta issue: why do we have labels `Cabal: cmd/check` and `cabal-install: cmd/check` ? 

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8185]
Why do we have labels `Cabal: cmd/check` (21 open, 14 closed issues) and `cabal-install: cmd/check` (3 open, 4 closed issues)? 
Isn't check just a `cabal-install` command?
```
$ runhaskell Setup.hs check
unrecognised command: check
```
Maybe these labels refer to the different source modules?
- `Cabal: cmd/check`: https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/PackageDescription/Check.hs
- `cabal-install: cmd/check`: https://github.com/haskell/cabal/blob/master/cabal-install/src/Distribution/Client/Check.hs

However, when I look at the issue lists, I don't see a system...
- https://github.com/haskell/cabal/labels/Cabal%3A%20cmd%2Fcheck
- https://github.com/haskell/cabal/labels/cabal-install%3A%20cmd%2Fcheck

**Comment by jneira** [comment]
> Good call. I support merging everything into the latter (cabal-install) tag.

done

**Comment by andreasabel** [comment]
@jneira : If you want to let me in to a secret, how did you do it?  Like, is there a tool, did you use the API, or just manually on the GUI?  I mean, "add label X to all issues that are labeled Y" sounds like a task that I would hope is mechanised...

**Comment by jneira** [comment]
in the GitHub UI, you can check boxes for several issues and do all kind of bulk changes, like remove and add labels
