### ISSUE TITLE
FreeBSD binaries are missing in gitlab CI pipline

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8192]
The error is `mkdir: /var/lib: Permission denied`, e.g., in https://gitlab.haskell.org/haskell/cabal/-/jobs/1070375

**Comment by Mikolaj** [comment]
Here's the companion gitlab ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/21480

**Comment by Mikolaj** [comment]
This is probably a planned part of the #8044 effort.

**Comment by Mikolaj** [comment]
This is now also subsumed by the recent gitlab CI work and the discussion of the future of release CI. The companion gitlab ticket is close. Closing.

**Comment by arrowd** [comment]
What was the resolution, for those who don't follow the discussion?
