### ISSUE TITLE
`cabal.project` CLI option

### ISSUE THREAD

**Issue by parsonsmatt** [haskell/cabal#8203]
Is it possible to select a `cabal.project` file with a CLI option?

Motivation: I'm used to having a bunch of different `stack.yaml` files for different configurations (eg testing new libraries easily, etc), and it's easy to do `stack --stack-yaml stack-ghc-9.2.yaml test` to quickly switch between packages like this.

If it is possible, then the `--help` output should be improved to indicate how

If not, it would be a *really* nice feature to have!

**Comment by fgaz** [comment]
Yes, there is `--project-file`

**Comment by philderbeast** [comment]
Yes you can. 

```
> cabal build all --project=cabal.blobs.project
> cabal build thoralf-plugin-uom --project=cabal.project
```

From https://github.com/BlockScope/plugins-for-blobs/tree/add/sublibraries.

**Comment by philderbeast** [comment]
The option in `cabal build --help` is indeed listed as `--project-file` but is `--project` a synonym command?

**Comment by parsonsmatt** [comment]
Great, thanks! Is that new in 3.8? It is not visible on my 3.6.2.0

**Comment by fgaz** [comment]
> is --project a synonym for that option?

The canonical name for the option is `--project-fille`, but all options can be shortened arbitrarily as long as they are unambiguous. For example `--proj` works too, but `--pro` doesn't (there are other options that begin with `--pro`). This is useful for interactive use, but canonical names should be preferred in scripts, for robustness against introduction of new flags.

**Comment by philderbeast** [comment]
> all options can be shortened arbitrarily as long as they are unambiguous

Great to know, thanks.

**Comment by jneira** [comment]
> Great, thanks! Is that new in 3.8? It is not visible on my 3.6.2.0
> 
> EDIT: Oh, it's in `cabal build --help`, not `cabal --help`. Maybe promoting it to the top level is a good idea, since it applies to `build` and `test` ?

imo it is better to no promote flags which don't work for all (or most) commands. They would need a note like ”only applicable to foo and bar”

in any case i would propose it in another issue (or change this one title)

**Comment by jneira** [comment]
I am gonna close it as the first question has been answered, feel free to reopen for the cli help thing (but please rename it in that case)
