### ISSUE TITLE
Unable to install cabal-install-3.8.0.20220526 on Windows

### ISSUE THREAD

**Issue by cydparser** [haskell/cabal#8210]
**Describe the bug**

_ghcup_ fails to install the prerelease version of _cabal-install_. The error indicates that a file named _cabal.exe_ was not found. The zip file contains a file named _cabal_ (without an extension).

**To Reproduce**

```sh
ghcup config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml
ghcup install cabal 3.8.0.20220526 
```

Resulted in:
```sh
Error: (Unable to copy a file. Reason was: C:\Users\cyd\AppData\Local\Temp\ghcup-c840ea7fe45060fc\cabal.exe: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:openBinaryFile: does not exist (No such file or directory),
 The version 3.8.0.20220526 of the tool cabal is not installed.)
```

**System information**
 - Windows 11
 - GHCup  v0.1.17.8-p1

**Comment by ulysses4ever** [comment]
This an unfortunate but known oversight, see #8191. Should be fixed in the future (pre)releases. I'm not sure though why this pre-release hasn't been fixed.

**Comment by Mikolaj** [comment]
> This an unfortunate but known oversight, see #8191. Should be fixed in the future (pre)releases.

Correct.

> I'm not sure though why this pre-release hasn't been fixed.

I'm guessing, we didn't want to break the checksums? Not sure.

**Comment by Mikolaj** [comment]
@hasufell: is there a non-dirty way of working around that problem in ghcup (by the user or by us)?

**Comment by hasufell** [comment]
> @hasufell: is there a non-dirty way of working around that problem in ghcup (by the user or by us)?

~~We~~ you fix the bindist manually and upload it as `-p1` as a new tarball.

**Comment by Mikolaj** [comment]
I do that (with a new signed file containing the new single checksum?) and what happens next? How does that help?

**Comment by Mikolaj** [comment]
OK, I fix, name with suffix `-p1`, checksum, sign, upload to the same directory as the previous 3.8.0.20220526 archives. Correct? Then what? I'd like to understand, so that I don't make wrong assumptions and silly mistakes.

**Comment by hasufell** [comment]
> OK, I fix, name with suffix `-p1`, checksum, sign, upload to the same directory as the previous 3.8.0.20220526 archives. Correct? Then what? I'd like to understand, so that I don't make wrong assumptions and silly mistakes.

Then you wait for me to get sober and update ghcup metadata.

**Comment by Mikolaj** [comment]
> > OK, I fix, name with suffix `-p1`, checksum, sign, upload to the same directory as the previous 3.8.0.20220526 archives. Correct? Then what? I'd like to understand, so that I don't make wrong assumptions and silly mistakes.

Done. (CDN may take some hours.)

> Then you wait for me to get sober and update ghcup metadata.

How do we catch that short window of opportunity?

**Comment by Mikolaj** [comment]
@hasufell: respectful ping?

**Comment by Mikolaj** [comment]
Good times! :D

**Comment by hasufell** [comment]
Done: https://github.com/haskell/ghcup-metadata/commit/437a84e8d987d7017d1181757dc2bc6b9c7fad3a

**Comment by Mikolaj** [comment]
Julian, thank you so much. @cydparser. please let us know if this works for you.

**Comment by cydparser** [comment]
It works, thanks!

**Comment by Mikolaj** [comment]
Success! Thank you all.
