### ISSUE TITLE
Inconsistent Paths_ modules generated

### ISSUE THREAD

**Issue by GuillaumeGen** [haskell/cabal#8219]
It can happen that the `Paths_` modules generated by cabal are inconsistent by containing call to the functions `minusFileName` and `splitFileName` without the definition of those functions

I am really sorry that it is not a minimal example, but this behaviour stroke me when doing:
```
git clone git@github.com:tweag/gazelle_haskell_modules.git
cd gazelle_haskell_modules
git checkout gg/#35-support-ghc92
nix-shell
git clean -fxd
echo "build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host" > .bazelrc.local 
bazel test //himportscan:tasty
```

When inspecting the code, I realized that the issue is in the file https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
The condition required to have calls to those functions is `if (zRelocatable z_root)` (https://github.com/haskell/cabal/blob/1037a1cdb3c3b15f4ba0d5dea6c751c3ccbf4ca5/Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs#L108) whereas the condition for those function to be declared is `  if (zNot z_root (zAbsolute z_root))` (https://github.com/haskell/cabal/blob/1037a1cdb3c3b15f4ba0d5dea6c751c3ccbf4ca5/Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs#L269).

I think both the use of those functions and their declaration should come together to avoid such an inconsistent state.

**Comment by jneira** [comment]
thanks for the detailed report describing the root cause
it seems to me the solution would be not  too complex so a pr would very welcome
the unique caveat is I am not sure if setup a test would be doable
