### ISSUE TITLE
Unrecognized field at the top-level

### ISSUE THREAD

**Issue by cblp** [haskell/cabal#8221]
**Describe the bug**

I want to specify ghc-options for all local packages

According to the documentation,
> They can be specified at the top-level, in which case they apply only to local package
https://cabal.readthedocs.io/en/3.6/cabal-project.html#package-configuration-options

(Why singular, by the way?)

And I get

```
Warning: .../cabal.project: Unrecognized
field 'ghc-options' on line 13
```

**To Reproduce**

```cabal
-- cabal.project
ghc-options: -Werror
```

**Expected behavior**
`-Werror` applied to all local packages and not applied to dependencies.

**System information**
 - Operating system: macOS 12.4
 - cabal-install version 3.6.2.0, compiled using version 3.6.2.0 of the Cabal library
 - The Glorious Glasgow Haskell Compilation System, version 8.10.7

**Comment by cblp** [comment]
oh, it's a known bug #3579

**Comment by cblp** [comment]
fixed in master; not fixed in production

**Comment by Mikolaj** [comment]
Yes, it looks so. Please install cabal 3.8 pre-release (https://discourse.haskell.org/t/cabal-3-8-pre-released/4631/1) and kindly confirm it's fixed for you. If so, let's close as fixed (we don't wait until fixes are released).

**Comment by Mikolaj** [comment]
Optimistically closing as fixed. @cblp: pretty please, make sure to alert us if that's not the case.

**Comment by jneira** [comment]
only want to stress you can't use ghc-options directly at top-level but under program-options section
