### ISSUE TITLE
Evil mode for cabal solver?

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#8229]
When writing a new package, it is difficult to establish lower bounds of dependencies. Cabal solver is keen to use the latest packages available, so I need to pass multiple constraints, forcing Cabal to pick up an older release. I would like to have an `--evil` mode, which reverses preferences and chooses the oldest dependency, which matches constraints. Then I'd able to set lower bounds quickly and with confidence. How does it sound?

Here is a relevant code snippet:
https://github.com/haskell/cabal/blob/a715d0473b0bca458a625ab308cef2f65d854799/cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs#L103-L109

So the proposal is to extend 
https://github.com/haskell/cabal/blob/a715d0473b0bca458a625ab308cef2f65d854799/cabal-install-solver/src/Distribution/Solver/Types/InstalledPreference.hs#L7-L11
with `PreferEarliest`, and expose the choice to users via a command-line flag.

**Comment by ulysses4ever** [comment]
SGTM modulo bikeshedding of the name (arguably, it should be more descriptive).

**Comment by Mikolaj** [comment]
Given that our APIs are now more modular, wouldn't that be a good candidate for an idenendent tool? Actually, perhaps there is a tool already? In any case, that's a sensible route: idea, ticket, tool, experiments, revisions adoption, optionally inclusion into cabal proper or at least advertising in the cabal manual, profit.

**Comment by gbaz** [comment]
I certainly think that I'd like an overhaul of the solver options handling, especially if we're going to have things like this. IMHO the solver package (which is now split out) should define its own options object. Then cabal-install should have flags all prefixed like `--solver-use-earliest` `--solver-allow-reinstalls` `--solver-prefer-installed` etc and take all `--solver` flags to just prepare a custom flagset for the solver itself.

As is, we'll just make the existing flag-creep and confusion somewhat worse.

**Comment by grayjay** [comment]
This issue looks like a duplicate of #2876. #2876 discusses some of the challenges of implementing this feature and links to a previous attempt.

**Comment by ulysses4ever** [comment]
Good catch! Should we close this @Mikolaj?

**Comment by Bodigrim** [comment]
Closed in favor of #2876.
