### ISSUE TITLE
`cabal --help` does not sufficiently describe what `cabal init` does

### ISSUE THREAD

**Issue by NiekPas** [haskell/cabal#8251]
**Describe the bug**
According to the documentation provided in `cabal --help`, `cabal init` "Create[s] a new .cabal package file." Running `cabal init` in an empty directory, however, does more than that: it creates (non-empty) `CHANGELOG.md` and `app/Main.hs` file as well.

I'm not trying to be pedantic here: reading through the output provided by `cabal --help` genuinely had me confused as to how to initialise a new build configuration.

**To Reproduce**

Run `cabal --help`

**Expected behavior**
See description.

**System information**
 - macOS Monterey 12.2.1
 - cabal-install version 3.6.2.0
- compiled using version 3.6.2.0 of the Cabal library

**Comment by NiekPas** [comment]
Something like "Initialise a new cabal project" would arguably be better, although I'm not sure if "cabal project" is the proper terminology here?

**Comment by NiekPas** [comment]
Great! Works for me. I probably should have tried updating Cabal first; apologies!

**Comment by ffaf1** [comment]
No worries, suggestions on how to improve `cabal` UX are always welcome!
