### ISSUE TITLE
cabal init: suggest GHC2021?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8265]
`cabal init -i` could suggest `GHC2021` along with `Haskell*` perhaps? I'm thinking that in the interactive menu we could write `"GHC2021 (requires at least GHC 9.2)"`. The language is already supported by Cabal
https://github.com/haskell/cabal/blob/f1395303feba296c58ba7eea3ecafdc10df7468b/Cabal-syntax/src/Language/Haskell/Extension.hs#L60
and it's just a matter of giving the extension more visibility. 

The non-interactive mode already has a flag that can be set to whatever (unfortunately, there's no check that the value makes sense), so it doesn't need any change.

Thoughts?

**Comment by Kleidukos** [comment]
Sounds good to me.

**Comment by Mikolaj** [comment]
Oh yes, would be great. Do we have any tests for `GHC2021` already? Or any tests for other features that have `GHC2021` in their sample cabal files?
