### ISSUE TITLE
`-Wtype-equality-requires-operators` warning building Cabal-syntax with ghc-9.4 

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#8268]
After adding lot of `allow-newer` building Cabal-syntax with ghc-9.4 throws this warning:

```
Preprocessing library for Cabal-syntax-3.9.0.0..
Building library for Cabal-syntax-3.9.0.0..
....
src\Distribution\Compat\Graph.hs:180:37: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
180 | instance (IsNode a, IsNode b, Key a ~ Key b) => IsNode (Either a b) where
    |
```

**Comment by andreasabel** [comment]
`TypeOperators` should be added to the `default-extensions` of the `.cabal` files (`Cabal-syntax.cabal`, ..).  This is harmless because the language flag exists since ages (before GHC 7).

**Comment by jneira** [comment]
hmm just i've hecked the module has the language eclared explicitly:

https://github.com/haskell/cabal/blob/5159ffbc8ab42e242ccd404cef594787bb08d65e/Cabal-syntax/src/Distribution/Compat/Graph.hs#L7

so a ghc bug?

**Comment by jneira** [comment]
> so a ghc bug?

No, the error is building Cabal-3.6.3.0 ant it did not have the language:

https://github.com/haskell/cabal/blob/60466878c23057f08063a49ef807d8b8313bb6cc/Cabal/src/Distribution/Compat/Graph.hs#L1-L7
