### ISSUE TITLE
`cabal init` UX improvement, do we need “alphanumeric” check?

### ISSUE THREAD

**Issue by ffaf1** [haskell/cabal#8278]
**Describe the bug**

Check this bit of cabal init interface

https://github.com/haskell/cabal/blob/1b8bf8ccb58c131efcbb3925bcbb5bd4c14adc03/cabal-install/src/Distribution/Client/Init/Interactive/Command.hs#L422-L429
Why are we doing an alphanumeric check? Is that helpful to the user (instead of a more standard “unrecognised xyz, valid choices are α, β, γ”?

**To Reproduce**

See above.

**Expected behavior**

See above.

**System information**
 - cabal install head

**Additional context**
If there is no need for that check, I could provide a small patch to improve the UI as I suggested (“Invalid xyz, valid choices α, β, y”).

**Comment by ulysses4ever** [comment]
For the reference, this check seems to have been added in [the last year's rewrite](https://github.com/haskell/cabal/commit/10687555d3c8524d5f5f373128ee80ccd56322bb#diff-2da5d0d682c7700ee592d9293190aeffa27ac50b39f1851812883ca0fa824cd1R405), and [wasn't there before](https://github.com/haskell/cabal/blame/4f8aeb2c8a0a3638e1af887dc869a17e291c8329/cabal-install/src/Distribution/Client/Init/Command.hs#L465-L468). I'm curious if @emilypi have any context for this restriction.

Generally, I don't believe this restriction actively hurts anyone in practice, so I don't mind having it. But I can also see a value in making code simpler. As I mentioned elsewhere, I think the bigger UI issue is with non-interactive mode that doesn't check the flag at all (if it's supplied by the user). So, you can `cabal init -n --language=abc` and it will happily generate a cabal file with that "language".
