### ISSUE TITLE
hackage: produce haddock documentation for executable only projects as well

### ISSUE THREAD

**Issue by bos** [haskell/cabal#829]
(Imported from [Trac #839](http://hackage.haskell.org/trac/hackage/ticket/839), reported by guest on 2011-04-28)

Hackage currently only contains haddock documentation for "libraries".

However, it'd be really cool to be able to see the source code of "executable" only projects as well. If the project is not haddock'ized, then a simple hscolor'ed html source base would be fine as well (like in `GitHub?`).

One of the more common use cases of Hackage is to look at other people's code, even for projects that you wouldn't download. This can go along way in making that much more pleasurable.

Alternatively, the user can specify a cabal flag to indicate if he wants browsable source code to be produced in case of executable only projects.

**Comment by ttuegel** [comment]
This isn't a Cabal issue.
