### ISSUE TITLE
How to get path to test log file in cabal-testsuite/PackageTests in the `TestM` monad?

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/cabal#8294]
I'm trying to add a test where I need to read test's log file. But I can't find out how to get the path to it inside the test.

An example of such a log file path is the following: `/Users/kristian/Documents/Kristian/haskell/cabal/cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.dist/work/dist/build/x86_64-osx/ghc-8.10.7/my-0.1/t/test-Foo/test/my-0.1-test-Foo.log`

How to get that path programatically since I want to check the contents of the file?
@Mikolaj maybe?

**Comment by ulysses4ever** [comment]
`assertOutputContains` should be enough for this purpose? See https://github.com/haskell/cabal/blob/2f871db2276af601be1d031c0d022bdde335b7ca/cabal-testsuite/README.md for details. I don't think getting an actual path is necessary...
