### ISSUE TITLE
getDataDir returns invalid path, at least when installing to ~/.cabal

### ISSUE THREAD

**Issue by alpha-bit** [haskell/cabal#8317]
**Describe the bug**

After the command:

    cabal install --overwrite-policy=always

When i run the installed binary getDataDir returns: ~/.cabal/share/x86_64-linux-ghc-9.0.2/abint-0.1.0

O.o ... yet that directory does not exists... :(

The data files were well installed and are located at: ~/.cabal/store/ghc-9.0.2/abint-0.1.0-e-abint-08c183433f44e5f446d03dc807bda62e0183d647b5dc8fafe20d9479bc87cc1b/share

**To Reproduce**

The above should be enough.

**Expected behavior**

I suppose, the path returned by getDataDir should be a symbolic link to where the files actually are.
The symbolic link is missing, should be created.

**System information**

 - nix-shell of nix installed in debian
 - `cabal`, `ghc` versions ::: 3.6.2.0, 11.3.0

**Additional context**

N/A

**Comment by Mikolaj** [comment]
I'm afraid this is a known bug with other tickets already open. Did you find any?

**Comment by alpha-bit** [comment]
no, i did search issues for "getDataDir", none seamed to be this.

I'm also noticing that getBinDir returns: ~/.cabal/lib/x86_64-linux-ghc-9.0.2/abint-0.1.0-inplace-abint

That also does not exist... :( ... seams that just default installing to ~/.cabal is messy

But I need access the data directory now...
How do i get this to install well in ~/.cabal, or otherwise any suggestion on how to work this around?

( O.o ... is not this the basic way of installing a cabal package? ... how everyone else overcomes this? )

**Comment by Mikolaj** [comment]
I overcome it by embedding the data files I need into the binary. I think there are other workarounds in the other tickets. Couple are marked with https://github.com/haskell/cabal/labels/data-files, but there is probably more.

**Comment by alpha-bit** [comment]
Also noticing that when running with `cabal run abint`, the getDataDir works fine ::: ..../src/./share/directory.sh

> ... by embedding the data files I need into the binary.

( O.o ... is that a thing?... lolz ::: googling for it... )

Though i need the files in the file system... to be sourced from a shell process that i run from haskell, the plan is to pass $dataDir for the user editable scripts to source packaged .sh files... I could otherwise pass a $scriptToEval, but that would not be right ::: the dataDir scripts are not part of the program, they are just optional predefined scripts for the user to source and to easily consult.

... & checking this ::: https://github.com/valderman/data-embed

( O.o ... Is this it?... i don't like it... less for this case, maybe useful for an application icon or so. )

**Comment by alpha-bit** [comment]
Closing ::: my bad... :( ... sorry.

Everything is working just fine... :)

I was running the wrong binary, by misstake... :(

... namely the built: `src/dist-newstyle/build/x86_64-linux/ghc-9.0.2/abint-0.1.0/x/abint/build/abint/abint`

  ( because is faster to `cabal run` than `cabal install, and runs fine apart from getDataDir )

Instead of the actually installed: `~/.cabal/bin/abint`

O.o ... hoops -> closing issue... :D

**Comment by Mikolaj** [comment]
I'm glad it fixed itself. :) Happy hacking!
