### ISSUE TITLE
cabal appears to complain about relative paths

### ISSUE THREAD

**Issue by bos** [haskell/cabal#832]
(Imported from [Trac #842](http://hackage.haskell.org/trac/hackage/ticket/842), reported by jeffz on 2011-05-16)

With <tt>cabal configure --extra-lib-dirs=foo</tt>

$ cabal build
Preprocessing library HENet-0.0.1...
Building HENet-0.0.1...
Registering HENet-0.0.1...
cabal.exe: HENet-0.0.1: library-dirs: .libs is a relative path (use --force to
override)

Originally reported on irc:

&lt;dcoutts&gt; jeffz: the right solution here would be for cabal to make the paths absolute before passing them on to ghc-pkg

**Comment by jneira** [comment]
>([Imported comment](http://hackage.haskell.org/trac/hackage/ticket/842#comment:2) by MikolajKonarski on 2011-05-16)

wow, @Mikolaj 😄

**Comment by jneira** [comment]
Closing in favour of #2641, which summarizes the problems with relative paths and the interaction with ghc-pkg

**Comment by Mikolaj** [comment]
> > ([Imported comment](http://hackage.haskell.org/trac/hackage/ticket/842#comment:2) by MikolajKonarski on 2011-05-16)
> 
> wow, @Mikolaj smile

Yes, I'm *that* old.
