### ISSUE TITLE
cabal run sends bluid info and "Up to date" to stdout, should send to stderr

### ISSUE THREAD

**Issue by alpha-bit** [haskell/cabal#8329]
**Describe the bug**

On `cabal run ... 2> /dev/null` the build processed is sent to stdout, even when has already built it sends  `"Up to date"` to stdout.

I use this to test a command line program, i need to be able to use the output of the program.

**To Reproduce**
try `cabal run ... 2> /dev/null`

**Expected behavior**
Expected to all output from `cabal run` to go to stderr. 

**System information**
 - nix-shell @ Debian
 - `cabal-install version 3.6.2.0`, `ghc version 9.0.2`

**Comment by ffaf1** [comment]
Would `cabal run --verbose=0 my-program` suit your workflow?

I am not sure sending stuff to `stderr` is the correct choice.

**Comment by ulysses4ever** [comment]
Thanks for the report! It's a dup of #7790, so I suggest we close.

**Comment by alpha-bit** [comment]
@ffaf1 ::: Option `--verbose 0` just works great, as needed... :)

( O.o ... i should have checked that. )

> I am not sure sending stuff to stderr is the correct choice.

I do think everything not-data (for natural piping) should go to stderr.

[ty], Closing as suggested
