### ISSUE TITLE
Clearer documentation for Cabal build hooks

### ISSUE THREAD

**Issue by kozross** [haskell/cabal#8334]
**Describe the bug**

The context of this problem is [`cabal-autoheaven`](https://github.com/kozross/cabal-autoheaven), which is an attempt to make bundling and integration of Autotools-based projects easier for Haskell projects. The way it works is to essentially create a custom hook which:

1. Generates a 'clean prefix' inside of the build directory.
2. Detects a C compiler (by borrowing the one with GHC), as well as some basic tools like `sh`, blowing up if not found.
3. Runs `configure` with the 'clean prefix' as the target and forcing the detected C compiler and tools.
4. Builds and installs into the 'clean prefix'.

There is also some minor build caching going on: you can view the [whole implementation](https://github.com/kozross/cabal-autoheaven/blob/main/src/Distribution/Autotools.hs#L69) for details.

Currently, this is only a post-conf hook, which is definitely necessary, but not sufficient to the task. In particular, I also need:

* A build hook to inform Cabal of where to find both the static library and headers (for bindings, for example).
* A packaging hook to bundle the source into the sdist.
* A 'cleanup hook' for `cabal clean`.
* Probably more I'm forgetting.

This brings me to my problem: the Cabal-the-library docs make it _very_ difficult for me to figure out how to do this. The only reason I got this far is due to having a (very similar) example to follow, and a lot of trial and error. I'm not even sure how to continue and do all the above things, because the docs don't really explain much to me. In fact, I don't even know if what I want is possible at all!

**To Reproduce**

1. Look at the Haddocs for `Cabal`.
2. Cry tears of blood at the lack of sense it all makes.
3. Give up whatever you were trying to do.

**Expected behavior**

More clarity on the steps, the different hooks, and what they can and can't do. Some examples would be great as well.

**System information**
 - Linux (but it doesn't matter)
 - `Cabal` ranges from 3.2 (inclusive) to 3.8 (exclusive) [as per here](https://github.com/kozross/cabal-autoheaven/blob/main/cabal-autoheaven.cabal#L38)

**Additional context**

This is more of a 'documentation and lack of understanding' problem, which may not be specifically related to the use of Cabal-the-build-system, but it definitely feels like an issue.

**Comment by Mikolaj** [comment]
I suppose there is no additional documentation at https://cabal.readthedocs.io/en/latest/setup-commands.html or anywhere else, only in haddocks? I fully sympathise, as I'm supposed to maintain these systems and I have much less clue than you do. May I ask that you record your findings in said haddocks? The hooks and the related code are rather stable, so there is little risk of writing docs for throwaway code. If you ask questions here, there is a chance somebody may know an answer and then it would get recorded at least in the ticket. Good luck with your tool!

**Comment by kozross** [comment]
@Mikolaj _Nothing_ on cabal.readthedocs.io is of _any_ use if you want to use Cabal as a library, which is what I'm trying to do here.

I'd love to record my findings, but right now, I don't have any! I have hunches and suspicions that need clear confirmation, ideally by someone who's familiar with these systems. This is what I hoped to gain by opening this issue, to be honest.

**Comment by gbaz** [comment]
The ask is too large and vague to be an actionable issue for us, I think. There's a lot of implicit questions that need some teasing out. Also the current maintainer team for cabal are not those with a lot of historic connection to the build hooks system, so I don't know if we have anyone especially qualified here -- so again, more specific questions might help.

That said, let me take a stab at what the questions appear to be:

"A build hook to inform Cabal of where to find both the static library and headers (for bindings, for example)."

You can almost certainly do this with a preBuild hook, but note the very funny and exasperated comment here: https://hackage.haskell.org/package/Cabal-3.6.3.0/docs/Distribution-Types-HookedBuildInfo.html

"A packaging hook to bundle the source into the sdist."

Absolutely does not exist, sadly. But I don't believe it should be necessary with our wildcards and extra files stuff...

"A 'cleanup hook' for cabal clean.""

Yep, there's a preClean and postClean that should work just like the other hooks.

One thing you might have gathered from the haddocks that do exist is that the people that were working on implementing and improving hooks got Very Mad at them and hit a point where they decided that the whole mechanism should be scrapped and replaced and of course we have no real idea how to do that, but also we discourage hooks (and custom setup in general) in favor of other mechanisms whenever possible, and it might also be useful to try to enumerate what features that are less invasive than hooks might suffice to get a lot of what you want accomplished, in conjunction with the Configure or Make build types (as opposed to Custom).

**Comment by kozross** [comment]
@gbaz Thanks for clarifying. It seems like what I want to do is not possible. Closing.
