### ISSUE TITLE
Support extension DeepSubsumption from GHC 9.2.4

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8341]
See https://gitlab.haskell.org/ghc/ghc/-/issues/21931#note_445804

This was last time done in https://github.com/haskell/cabal/pull/8170. but at that time DeepSubsumption has not yet been in 9.4.alpha nor 9.2.*, I think.

It would be good to have this in cabal 3.8.2.0, if we make the point release before 3.10. We can also double-check all 9.4 extensions are covered.

**Comment by Mikolaj** [comment]
This is already done in changelog.d/pr-8493. Closing.

**Comment by ulysses4ever** [comment]
Let's properly reference #8493 then.

**Comment by Mikolaj** [comment]
Correct.
