### ISSUE TITLE
Publish Cabal-3.8.1.0 as included in GHC 9.4.1

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#8347]
GHC 9.4.1 has been released with Cabal-3.8.1.0 included (e. g., https://downloads.haskell.org/ghc/9.4.1/docs/libraries/index.html). The source code (https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.4/libraries) points to 5d18b763. Could it please be uploaded to Hackage?

**Comment by Mikolaj** [comment]
Hi @Bodigrim; thank you for the confirmation. That's our plan. OOI, why do you think it's important? What's the use case?

**Comment by Bodigrim** [comment]
What's the use case of releasing packages? ;)

**Comment by Mikolaj** [comment]
Well, in that case, what makes you think we need to be reminded that releasing occasionally is a good idea? :)

I don't mean in general, but in whatever context you had in mind writing this ticket. E.g., you contributed feature X and want to have it available to users that use Hackage (which feature) or, e.g., packaging GHC would somehow be broken without the package on Hackage (how?) or whatever it is that made you specifically ask via a ticket.

**Comment by Bodigrim** [comment]
> Well, in that case, what makes you think we need to be reminded that releasing occasionally is a good idea? :)

Because releases of GHC submodules should happen before GHC release, not vice versa. Otherwise things tend to drift away (e. g., https://github.com/haskell/cabal/commits/3.8 has __already__ accumulated patches atop of 5d18b763356dca719f5286a52328cb41b9fa4192), leading to two different, but indistinguishable by version codebases.

Practically speaking, I often build things with exotic constraints, but non-reinstallable Cabal prevents most of them.

**Comment by Mikolaj** [comment]
> Because releases of GHC submodules should happen before GHC release, not vice versa.

And that's exactly what I asked for. A sensible rule and a good motivation for a request that helps us understand not only what users want, but why they want it. Thank you.

> e. g., https://github.com/haskell/cabal/commits/3.8 has already accumulated patches atop of https://github.com/haskell/cabal/commit/5d18b763356dca719f5286a52328cb41b9fa4192

That's a dubious example, given that GHC incorporated the v3.8.1.0 tag, not a random commit. And we announced the intention to release the very tag in https://gitlab.haskell.org/ghc/ghc/-/issues/21931 (to which issue you kindly responded).

> Practically speaking, I often build things with exotic constraints, but non-reinstallable Cabal prevents most of them.

That's a valuable hint, too. Let me say this in my own words: you may want to compile the same Cabal that is in GHC, but changing versions of some of its dependencies and for this you need the Cabal in Hackage. Is that right?

**Comment by Bodigrim** [comment]
> Let me say this in my own words: you may want to compile the same Cabal that is in GHC, but changing versions of some of its dependencies and for this you need the Cabal in Hackage. Is that right?

Precisely.

**Comment by Mikolaj** [comment]
Done. Haddocks of re-exported modules are still missing, but this should be re-installable all right now: https://hackage.haskell.org/package/Cabal-3.8.1.0 https://hackage.haskell.org/package/Cabal-syntax-3.8.1.0

**Comment by Bodigrim** [comment]
Thanks!
