### ISSUE TITLE
CI ignores all "validate lib-suite" tests with "SKIP no cabal-install"

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8372]
I happens for a long time already, e.g., 2 weeks ago: https://github.com/haskell/cabal/runs/7587547562?check_suite_focus=true

There are 2 problems here: 
* cabal-install is not found (but it seems it builds fine) and so tests don't run
* CI hides the fact, which probably makes sense for some old GHCs, etc., but not in general

**Comment by Mikolaj** [comment]
@jneira says "that is expected, the test suite is the same but validate-lib-suite skips all cabal-install tests by design". But I can't see where else CI runs these tests.

**Comment by jneira** [comment]
I think that is the expected behaviour, cabal-testsuite contains tests for cabal the lib and for cabal-install
Workflows validating only the lib runs some of the tests (100 or so)

**Comment by jneira** [comment]
> @jneira says "that is expected, the test suite is the same but validate-lib-suite skips all cabal-install tests by design". But I can't see where else CI runs these tests.

in the `Validate cli-suite` step below lib suite one`

**Comment by Mikolaj** [comment]
Oh, so it only shows the skipped failed tests there? Right, I missed `--hide-successes`. Thank you very much for the explanation. Panic called off, we can continue the party. :)

```
>>> **/cabal-tests --builddir=**/cabal-testsuite-3 --with-cabal=**/cabal -j2 --with-ghc=ghc --hide-successes 
threads: 2
tests to run: 316
PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs                                                SKIP no hackage-repo-tool (0.35s)
PackageTests/NewBuild/T3827/cabal.test.hs                                                                         SKIP 8032 heisenbug profiling (0.37s)
PackageTests/NewBuild/T4375/cabal.test.hs                                                                         SKIP needs ghc < 8.1 (0.36s)
PackageTests/NewSdist/ManyDataFiles/many-data-files.test.hs                                                       SKIP no open file limit (0.36s)
PackageTests/CustomDep/cabal.test.hs                                                                              SKIP needs ghc < 8.2 (0.34s)
PackageTests/Backpack/Includes3/setup-external-ok.test.hs                                                         OK (known failure) (6.04s)
PackageTests/Backpack/Includes2/setup-external.test.hs                                                            OK (known failure) (8.67s)
PackageTests/Backpack/Includes2/setup-per-component.test.hs                                                       OK (known failure) (8.08s)
PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs                                                     OK (known failure) (1.21s)
PackageTests/InternalVersions/BuildToolDependsExtra/setup.test.hs                                                 OK (known failure) (1.18s)
PackageTests/InternalVersions/BuildToolsExtra/setup.test.hs                                                       OK (known failure) (1.19s)
PackageTests/CustomPlain/cabal.test.hs                                                                            SKIP needs ghc < 8.2 (0.34s)
SKIPPED 6 tests
OK
```

**Comment by jneira** [comment]
in fact it seems we are running those 100 only lib tests twice, we should run only one of both, lib-suite or cli-suite

**Comment by ulysses4ever** [comment]
> in fact it seems we are running those 100 only lib tests twice, we should run only one of both, lib-suite or cli-suite

Should we open another ticket for this?

**Comment by jneira** [comment]
yeah, moreover I think it would help to avoid confusions

**Comment by ulysses4ever** [comment]
I’m trying to wrap my head around it (the structure of CI has been a black box to me for some time). If I succeed, I’ll create a ticket, otherwise, feel free to do it.

**Comment by ulysses4ever** [comment]
Unrelated, Reading up on CI a bit, I noticed:

>      # The tool is not essential to the rest of the test suite. If
>      # hackage-repo-tool is not present, any test that requires it will
>      # be skipped.
>      # We want to keep this in the loop but we don't want to fail if
>      # hackage-repo-tool breaks or fails to support a newer GHC version.
>      - name: Install hackage-repo-tool
>        continue-on-error: true

I wonder if it’s a good idea, or maybe it’d be better to actually keep track of failures due to hackage-repo-tool…
