### ISSUE TITLE
[PATCH] Store licenses in text files instead of code.

### ISSUE THREAD

**Issue by bos** [haskell/cabal#839]
(Imported from [Trac #849](http://hackage.haskell.org/trac/hackage/ticket/849), reported by refold on 2011-05-26)

This shaves 300 KiB off the final executable size and makes it slightly easier to add new license types (just drop the text file under %SRCDIR%/licenses and modify the 'licenseFile' function in Distribution.Client.Init.hs).

**Comment by 23Skidoo** [comment]
This patch was never applied, so closing. There's already #142.
