### ISSUE TITLE
cabal init -i does not sanitize the name of the package

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#8404]
**Describe the bug**
`cabal init -i` does not sanitize the name of the package

**To Reproduce**

```
$ mkdir foo.bar
$ cd foo.bar
$ cabal init -i
[...]
Package name? [default: foo.bar]
[...]
$ cabal build
Errors encountered when parsing cabal file ./foo.bar.cabal:

foo.bar.cabal:14:24: error:
unexpected '.'
expecting white space or end of input

    1 | cabal-version:      3.0
    2 | -- The cabal-version field refers to the version of the .cabal specification,
[...]
   13 | -- The name of the package.
   14 | name:               foo.bar
      |                        ^
```

`cabal init -n` correctly uses `foo-bar`

**Expected behavior**

3.6 succeeds:

```
$ cabal init -i
[...]
Package name? [default: foo-bar]
```

**System information**

cabal 3.8.1.0

cc @emilypi @ptkato

**Comment by emilypi** [comment]
The problem here is this block of code from `Init/Interactive/Command.hs`: 

```haskell
    defName <- case packageDir flags of
        Flag b -> return $ filePathToPkgName b
        NoFlag -> currentDirPkgName
```

Neither of `filePathToPkgName` or `currentDirPkgName` pass through parsec like the user input does via `prompt`. They construct a value of type `PackageName` directly: 

```haskell
filePathToPkgName :: FilePath -> P.PackageName
filePathToPkgName = PN.mkPackageName . Prelude.last . splitDirectories

currentDirPkgName :: Interactive m => m P.PackageName
currentDirPkgName = filePathToPkgName <$> getCurrentDirectory
```

The fix here would be to add an additional pass which parsed it, or, since those two functions are unsafe as currently defined, should be parsed and produce an `Either String PackageName` containing the parser error message. I'll have a PR up for it this week. FYI @ptkato.

**Comment by ulysses4ever** [comment]
@emilypi you wrote back in August that you're interested in fixing this. Do you have any news? We got another bug report for it today #8558…

Noninteractive mode does the right thing using `canonicalizePathNoThrow`:
https://github.com/haskell/cabal/blob/bd24cac2e290b8c2f56071f40250d79f433fa1b8/cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs#L85-L86

So, it may be a matter of just prepending `canonicalizePathNoThrow` inside `filePathToPkgName` and making its type impure.

**Comment by ulysses4ever** [comment]
Actually, it's not `canonicalizePathNoThrow`, it's the local function `repair` inside `guessPackageName` that does the sanitizing. It seems that `guessPackageName` can be pulled to `Utils.hs` whole-sale and reused in Interactive.

**Comment by ulysses4ever** [comment]
Okay, I was hasty and posted my idea as  #8561.

**Comment by emilypi** [comment]
Cheers thanks @ulysses4ever - I got bogged down with work and didn't have time to fix this. Thanks for investigating.
