### ISSUE TITLE
cabal man should support spaces in PAGER env var

### ISSUE THREAD

**Issue by sternenseemann** [haskell/cabal#8405]
**Describe the bug**

When running e. g. `env PAGER="less -R" cabal man`, it will fail with:

```
less -R: createProcess: posix_spawnp: does not exist (No such file or directory)
```

**Expected behavior**

It is relatively common for `PAGER` to contain spaces and the usual convention is to either support custom env vars that allow specifying options and pager independently (e.g. git) or split on spaces in the `PAGER` env var (possibly implementing shell quoting rules is also necessary).

E.g. GNU `man-db`'s `man(1)` does support it:

```
       MANPAGER, PAGER
              If $MANPAGER or $PAGER is set ($MANPAGER is used in preference),
              its value is used as the name of the program used to display the
              manual page.  By default, less is used, falling back to cat if
              less is not found or is not executable.

              The value may be a simple command name or a command with
              arguments, and may use shell quoting (backslashes, single
              quotes, or double quotes).  It may not use pipes to connect
              multiple commands; if you need that, use a wrapper script, which
              may take the file to display either as an argument or on
              standard input.
```

**System information**
 - NixOS
 - cabal-install 3.8.1.0, GHC 8.8.4, 8.10.7, 9.0.2, 9.2.4

**Comment by ulysses4ever** [comment]
Should be easy to fix:

https://github.com/haskell/cabal/blob/a97e1f13bdb28a3f761d55845f14a9072bee17ca/cabal-install/src/Distribution/Client/Manpage.hs#L81-L85

As a workaround: don't pass -R, it's the default (see the snippet above).
