### ISSUE TITLE
Add c-source-dirs: field analogous to hs-source-dirs: and include-dirs:

### ISSUE THREAD

**Issue by bos** [haskell/cabal#841]
(Imported from [Trac #851](http://hackage.haskell.org/trac/hackage/ticket/851), reported by @dankna on 2011-05-28)

I came across this need in the course of working with a hybrid Haskell-ObjC project; it just seems weird to set include-dirs but not set this, since it happens in my project to be the same directory.  Should be an easy feature; I'm going to implement it and keep track of my progress here.

**Comment by ttuegel** [comment]
Closing due to absence of activity in four years.
