### ISSUE TITLE
`cabal test --enable-optimization` sometimes runs the previously compiled unoptimized test

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8412]
**Describe the bug**

When I do

```
cabal build --disable-optimization
cabal test --enable-optimization
```

I see the proper test binaries linked in both cases (with `/noopt/` in the path in the first case), but sometimes the unoptimized binary gets run, which I can tell, because it's 10 times slower. This is non-deterministic and rather rare. I can't tell if this only happens when both the test binaries are up to date with the source code.

This is different from another scenario I occasionally see, when changes I made to the code do not cause recompilation when running `cabal test --enable-optimization`, or cause recompilation, but not re-linking. That one I've seen for years and it may be related to time drift, filesystem timestamps resolution and what not. It's likely to be in GHC or OS, while the bug above rather looks like a cabal bug.

I wonder in what bit of code cabal decides which test binary to run, out of the available binaries.

**System information**
A very old Ubuntu, GHC 9.2.4 and 9.0.2, cabal 3.8.1.0 (but I remember this from older cabals and GHCs)

**Comment by Mikolaj** [comment]
I'm sometimes seeing GHC compiling my code against a library archive (perhaps with a different optimization setting) from a previous compilation run, so perhaps it's not cabal running old test test exes, but GHC linking vs old library archives. BTW, my project has multiple (private) libraries, so compiling against various new and old library archives is common.

**Comment by ulysses4ever** [comment]
This stuff sounds a bit like #7711. (Maybe I'm wrong of course.)

**Comment by Mikolaj** [comment]
Let me close as a duplicate until #7711 is fixed and I can see and report what else is broken.
