### ISSUE TITLE
Regression (3.8.1.0): cabal sdist no longer works if GHC is not available

### ISSUE THREAD

**Issue by sternenseemann** [haskell/cabal#8413]
**Describe the bug**

Running `cabal sdist` will now fail with

```
Error: cabal: The program 'ghc' version >=7.0.1 is required but it could not
```

if GHC is not in `PATH`.

**Expected behavior**

My guess is that GHC is not necessary for this command and the check could be omitted.

**System information**
 - Operating NixOS
 - `cabal` 3.8.1.0

**Comment by ffaf1** [comment]
It seems a duplicate of #8352.
If it is ok with you @sternenseemann, I am closing it to focus the discussion on the original ticket.

**Comment by sternenseemann** [comment]
Sure.
