### ISSUE TITLE
Not possible to #include "*_stub.h" from C code

### ISSUE THREAD

**Issue by bos** [haskell/cabal#842]
(Imported from [Trac #852](http://hackage.haskell.org/trac/hackage/ticket/852), reported by @dankna on 2011-05-29)

Cabal doesn't make it possible to #include "*_stub.h" files from C code, because those files have not yet been generated at the time that it wants to check for their existence, which is during "cabal configure".

At first I was going to ask for advice because I didn't really see a solution, but now that I think about it, I think correct behavior is to omit the check for whether stub files exist and compile, but to check for the existence of files which /could/ generate them, which is to say, are Haskell files and match the module portion of the name.  So I'll implement that.

**Comment by ezyang** [comment]
Yes this was merged as 02f8eef1c0592ab90238de29c2fe88ec89c85c2f

But it turns out that this introduce a recompilation bug in old versions of GHC. I'll file a new ticket for it.
