### ISSUE TITLE
Duplicate modules in library error only in 3.8.1.0

### ISSUE THREAD

**Issue by Jasagredo** [haskell/cabal#8422]
**Describe the bug**
`cabal build` fails with "Duplicate modules" error on 3.8.1.0 and not on 3.6.2.0. 

```
Failed to build moo-1.2. The failure occurred during the configure step.
Build log (
/home/javier/.cabal/logs/ghc-8.10.7/moo-1.2-6c72b1ec57cdfd93c8ee847bd6ff6030f0e61f1f9da5e35fff72711d30fcfc62.log
):
Configuring library for moo-1.2..
Error: cabal-3.8.1.0: Duplicate modules in library:
Moo.GeneticAlgorithm.Crossover

Error: cabal: Failed to build moo-1.2 (which is required by test:test from
ouroboros-consensus-byron-test-0.1.0.0, test:test from
ouroboros-consensus-shelley-test-0.1.0.0 and others). See the build log above
for details.
```

**To Reproduce**
Works for me with a clean cabal store and dist-newstyle, on this commit on this project
```
❯ git clone git@github.com:input-output-hk/ouroboros-network.git ouroboros-network
❯ git checkout 8ddd9bef006fecfd5d34c1ce2085d24c0c800c00
❯ cabal build all
```
Here is a full log:
[out.txt](https://github.com/haskell/cabal/files/9401583/out.txt)
In the log, I run the compilation with cabal 3.8.1.0 which fails, then change to cabal 3.6.2.0 which succeeds (I `^C`'ed it when it was way past the installation of the `moo` library).

**Expected behavior**
I expected the compilation to not fail

**System information**
 - Ubuntu 22.04, Linux 5.15.0-46-generic
 - cabal 3.8.1.0 and ghc 8.10.7. Works with cabal 3.6.2.0.

**Comment by Jasagredo** [comment]
Ah indeed there are duplicated modules in the cabal specification! https://hackage.haskell.org/package/moo-1.2/src/moo.cabal

```
    other-modules:      Moo.GeneticAlgorithm.Crossover
...
                      , Moo.GeneticAlgorithm.Crossover
```

So the only question that remains is, was this not disallowed, and it is disallowed now?

**Comment by Mikolaj** [comment]
HI! Thank you for checking. This is indeed illegal. I don't remember the particular PR that did it, but it's quite likely we detect such cases better in cabal 3.8. Is there anything else we can help you with?

**Comment by Jasagredo** [comment]
Right! confirming that it is now illegal is enough. Thanks!

**Comment by aleeusgr** [comment]
I get this  error from `nix-build`
ghc 8.10.7 is specified in `default.nix`

I should try 8.10.(4?)

**Comment by Mikolaj** [comment]
@aleeusgr: apologies; apparently @ mentions added in a comment edit don't results in notifications (or at least I didn't get one).

Any progress since your report? Any workaround, tutorial fix, anything?

**Comment by aleeusgr** [comment]
@Mikolaj no worries.
We found a workaround, but I am not happy with it. 
Normally we build our exe with a manual workflow: cabal update, then cabal build inside nix shell.
This works for a VM, but I wanted to create a deployment container.
So the issue priority is non-critical, but I still would love to do it the right way (i.e. use nix to build docker container).

I got a suggestion to use new cli (flake.nix), it uses different solver for dependencie.

**Comment by Mikolaj** [comment]
OK, I've found it:

```
Duplicate modules in library: Moo.GeneticAlgorithm.Crossover
...
goblins-lib-goblins-0.2.0.0
```

Where is the the cabal file in question? Does it have, in fact, duplicate modules? Or is it auto-generated? If so, does it auto-generate with duplicates?

I can't find which version of cabal is used in the transcripts. Newer cabal understands conditionals, while old one considers modules in branches duplicates IIRC.

**Comment by aleeusgr** [comment]
Thank you for guidance.
Apologies for not being able to provide more details: the project structure changed significantly and it was released for beta testing. We are coming back to this package in December, I  will report here once I replicate the error.

Cabal file was manually generated by cabal, and edited by the author of the project.
Cabal version was 2.4 by default, and I tested with 3.6 and 3.8 after reading this issue.
There are details [here](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/18)

**Comment by Fourzin** [comment]
Hello, I am having the same error discussed in this issue

Configuring library for moo-1.2..
Error: cabal-3.8.1.0: Duplicate modules in library:
Moo.GeneticAlgorithm.Crossover

Error: cabal: Failed to build moo-1.2 (which is required by
test:amm-executor-test from amm-executor-0.1.0.0, exe:amm-executor-app from
amm-executor-0.1.0.0 and others). See the build log above for details.

Is there a fix for it?

**Comment by jonathanfishbein1** [comment]
you have to resolve this package with git.  The head of repo is fixed

https://github.com/astanin/moo/commit/dbda5e76ac3b4c72c805ec0cdb9bcdff7bb6247d
