### ISSUE TITLE
import stackage in cabal.project seems not to work in cabal 3.8.1

### ISSUE THREAD

**Issue by andrewufrank** [haskell/cabal#8423]
**Describe the bug**
I tried to add 
```
packages: .
import https://www.stackage.org/lts-19.2/cabal.config
```
to my cabal. profile file - per doc 3.8.  point 4.2.2
I copied the command and pasted. 
get error message: 

```
Error: cabal: Error parsing project file
/home/frank/Workspace11/u2giscore/uniform-field/cabal.project:2:
Parse of field '
unexpected ":"
expecting section parameter, "{", field or section name or end of file'
failed.
```

if I put `"` around the address, it runs past this point. 

1. please update the manual to include the quotes if they are necessary!

Now a second error occurs with the next line: 

```
packages: .
import https://www.stackage.org/lts-19.2/cabal.config

    ../../uBase/uniformBase

```

which builds fine without the `import ...`. 
The error is 
```
```
cabal v2-build
Error: cabal: Error parsing project file
/xxx/cabal.project:3:
Parse of field '
unexpected operator "../../"
expecting field or section name' failed.

frank@santafe:~/xxx$ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 
```

```
 
**System information**
 - Operating system : debian bullseye updated today
 - `cabal`, `ghc` versions 3.8.1.0 - ghc 9.0.2

**Additional context**

**Comment by philderbeast** [comment]
Could you try adding a colon? I saw that in the [conditionals and imports](https://cabal.readthedocs.io/en/3.8/cabal-project.html#conditionals-and-imports) section.

```
import: https://www.stackage.org/lts-19.2/cabal.config
```

**Comment by Mikolaj** [comment]
So it seem to be a documentation bug? the manual has an incorrect example? When we fix this, could we also cross-link and/or unify https://cabal.readthedocs.io/en/3.8/nix-local-build.html#cookbook and https://cabal.readthedocs.io/en/3.8/cabal-project.html#conditionals-and-imports?

**Comment by andreabedini** [comment]
Apparently there's typo in the example in https://cabal.readthedocs.io/en/3.8/nix-local-build.html#how-can-i-have-a-reproducible-set-of-versions-for-my-dependencies

```
packages: .
import https://www.stackage.org/lts-19.2/cabal.config
```

according to grep it seems to be the only one.

**Comment by andrewufrank** [comment]
I tried with adding a colon - which did the trick! Thank you!
However, I found that the order of stanzas is tricky and the documentation may be misleading. I recommend putting the `import:` separately and before the local packages (or at the end of them); the documentation gave me the impression that the `import:` should come 
after the `packages` and before the rest of them. For exmplae: 

```
import: https://www.stackage.org/lts-19.2/cabal.config

packages: *.cabal
... more 

```

**Comment by Mikolaj** [comment]
> I recommend putting the import: separately and before the local packages (or at the end of them)

This sounds important. What's the difference? Is the semantics documented well enough to deduce it? How should we refine it?

**Comment by andrewufrank** [comment]
Using the exact same file on a different computer, I get the error 

    Unrecognized field 'import' on line 2

I was calling `cabal build` and not `cabal v2-build` assuming that `v2` is now the default. Could you have the manual point out that there are cases, where `v2` is required and not default? 

Thank you!

**Comment by Mikolaj** [comment]
In cabal 3.8.1.0 (and some earlier version) v2- is intended to always be the default. Perhaps you had an even earlier version at the other computer? Could you list the versions you are using?

**Comment by Mikolaj** [comment]
This is kind-of regression, because it was just added, but was advertised and was supposed to work. Sadly, it's blocked on finding a volunteer that would reproduce and diagnose carefully.

**Comment by ulysses4ever** [comment]
@andrewufrank 

> Using the exact same file on a different computer, I get the error
>
> Unrecognized field 'import' on line 2

Are you sure you have cabal version 3.8 on that computer?

---

Overall, looks like a documentation bug only?

**Comment by andreabedini** [comment]
I am pretty sure it's a documentation bug only
