### ISSUE TITLE
`test-suite` options don't work in common stanzas

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/cabal#8429]
**Describe the bug**
`test-suite` options used in common stanzas fail with an unknown field error. In the `test-suite` stanza the required fields are missing, even if they are provided by `import`.

**To Reproduce**
clone https://github.com/oberblastmeister/cabal-testing.

```bash
$ cabal v2-build
```

<details open>
<summary>cabal output</summary>

```
Errors encountered when parsing cabal file ./cabal-testing.cabal:

cabal-testing.cabal:14:1: error:
Test suite "tests" is missing required field "main-is" or the field is not present in all conditional branches.

   12 |   main-is: Test.hs
   13 |
   14 | test-suite tests
      | ^

cabal-testing.cabal:11:3: warning:
Unknown field: "type"

   10 | common common-test
   11 |   type: exitcode-stdio-1.0
      |   ^

cabal-testing.cabal:12:3: warning:
Unknown field: "main-is"

   11 |   type: exitcode-stdio-1.0
   12 |   main-is: Test.hs
      |   ^
```

</details>

**Expected behavior**
Cabal should not error when using `test-suite` options in common stanzas. Cabal should recognize that the required options are provided by through `import`.

**System information**
 - NixOS 22.05
 - Cabal 3.8.1.0
 - GHC 9.2.4

**Comment by ulysses4ever** [comment]
Dup of #6117

**Comment by fgaz** [comment]
fyi `type` is optional from `cabal-version: 3.8`, so if you set that you can just leave it out

**Comment by oberblastmeister** [comment]
Closing as this is a duplicate
