### ISSUE TITLE
Warning "ghc-options: -threaded has no effect for libraries" is not true

### ISSUE THREAD

**Issue by lyokha** [haskell/cabal#8431]
**Describe the bug**
When I build a library with options `-flink-rts -threaded` put inside *ghc-options*, I get warning:

```
Configuring ngx-distribution-test-0.1.0.0...
Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
be used for executables.
```

This claim is *not* essentially true as soon as `-threaded` accompanied by `-flink-rts` (this option appeared in ghc *8.10.6* and *9.x*) defines which flavour of ghc RTS library the built library will be linked against. I need to specify this explicitly in some scenarios.

**To Reproduce**

Add options `-flink-rts -threaded` into *ghc-options* of a Cabal file, then run `cabal v1-configure` or `cabal v2-build`.

**Expected behavior**
I expect no warning when  `-threaded` is specified in *ghc-options* (even without *-flink-rts* option) independently of the type of the target.

**System information**
 - Linux, Fedora 36
 - `cabal 3.8.1.0`, `ghc 9.4.1` versions

**Additional context**
I use this in custom setup scripts with package [ngx-export-distribution](https://hackage.haskell.org/package/ngx-export-distribution-0.3.2.0/docs/NgxExport-Distribution.html).

**Comment by Mikolaj** [comment]
Thank you for the report. Is `-flink-rts` the only exception to the rule from the warning?

**Comment by lyokha** [comment]
> Is `-flink-rts` the only exception to the rule from the warning?

I would completely remove this warning for `-threaded` option. Notice that bare ghc won't warn with `-threaded` for libraries while it warns on options `-rtsopts` and `-with-rtsopts`.

```ShellSession
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.4.1
$ ghc -Wall -O2 -dynamic -shared -fPIC -threaded ngx_distribution_test.hs -o ngx_distribution_test.so -fforce-recomp
[1 of 2] Compiling NgxDistributionTest ( ngx_distribution_test.hs, ngx_distribution_test.o )
[2 of 2] Linking ngx_distribution_test.so [Objects changed]
$ ghc -Wall -O2 -dynamic -shared -fPIC -rtsopts ngx_distribution_test.hs -o ngx_distribution_test.so -fforce-recomp
[1 of 2] Compiling NgxDistributionTest ( ngx_distribution_test.hs, ngx_distribution_test.o )
[2 of 2] Linking ngx_distribution_test.so [Objects changed]
Warning: -rtsopts and -with-rtsopts have no effect with -shared.
    Call hs_init_ghc() from your main() function to set these options.
$ ghc -Wall -O2 -dynamic -shared -fPIC -with-rtsopts=-H128m ngx_distribution_test.hs -o ngx_distribution_test.so -fforce-recomp
[1 of 2] Compiling NgxDistributionTest ( ngx_distribution_test.hs, ngx_distribution_test.o )
[2 of 2] Linking ngx_distribution_test.so [Objects changed]
Warning: -rtsopts and -with-rtsopts have no effect with -shared.
    Call hs_init_ghc() from your main() function to set these options.
```

Btw Cabal also warns on `-rtsopts` and `-with-rtsopts` while building libraries, and this is ok.

**Comment by Mikolaj** [comment]
Fine. We are happy to follow GHC.

**Comment by lyokha** [comment]
Patch to remove the warning on option `-threaded` might look like

```diff
diff --git a/Cabal/src/Distribution/PackageDescription/Check.hs b/Cabal/src/Distribution/PackageDescription/Check.hs
index 198ee8365..0767c6366 100644
--- a/Cabal/src/Distribution/PackageDescription/Check.hs
+++ b/Cabal/src/Distribution/PackageDescription/Check.hs
@@ -186,7 +186,6 @@ data CheckExplanation =
         | OptSplitObjs String
         | OptWls String
         | OptExts String
-        | OptThreaded String
         | OptRts String
         | OptWithRts String
         | COptONumber String String
@@ -493,9 +492,6 @@ ppExplanation (OptWls fieldName) =
 ppExplanation (OptExts fieldName) =
     "Instead of '" ++ fieldName ++ ": -fglasgow-exts' it is preferable to use "
       ++ "the 'extensions' field."
-ppExplanation (OptThreaded fieldName) =
-    "'" ++ fieldName ++ ": -threaded' has no effect for libraries. It should "
-      ++ "only be used for executables."
 ppExplanation (OptRts fieldName) =
     "'" ++ fieldName ++ ": -rtsopts' has no effect for libraries. It should "
       ++ "only be used for executables."
@@ -1370,9 +1366,6 @@ checkGhcOptions fieldName getOptions pkg =
   , checkFlags ["-fglasgow-exts"] $
       PackageDistSuspicious (OptExts fieldName)
 
-  , check ("-threaded" `elem` lib_ghc_options) $
-      PackageBuildWarning (OptThreaded fieldName)
-
   , check ("-rtsopts" `elem` lib_ghc_options) $
       PackageBuildWarning (OptRts fieldName)
```

**Comment by Mikolaj** [comment]
@ffaf1: is that within you realm? We wouldn't want to intrude.

**Comment by ffaf1** [comment]
Thanks for the report and patch @lyokha . If prefer not to do a PR yourself, I will take care of it in some time.

**Comment by lyokha** [comment]
Btw now I'm thinking whether option `-flink-rts`  deserves a warning. The option was invented to build plain libraries (see description to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3511), while Cabal normally build packages which are supposed to be linked with Haskell executables: in this case the premature choice of the RTS flavour can be harmful. OTOH, the user should be conscious when putting the option into the list of *ghc-options*. Anyway, option `-threaded` with or without `-flink-rts` is still legit and harmless per se.

**Comment by Mikolaj** [comment]
I don't think a user is likely to type `-flink-rts` by mistake, as opposed to, say, misplacing `-threaded`. So I wouldn't worry. There's plenty of other options that don't make sense in a cabal file.
