### ISSUE TITLE
Validate CI should display the output of `cabal-plan`

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8440]
It would be good to see which dependencies are picked up to build `cabal-install`, so a step in the CI scripts to stream the output of `cabal-plan` after (ideally before) the build would be great.

Example of such a step: https://github.com/haskell/hackage-server/blob/f6c1e48f8da9293055ff9e86aabd8a33f6594893/.github/workflows/haskell-ci.yml#L192-L195

**Comment by jneira** [comment]
Maybe it couldbe added to validate.sh and make it ci agnostic. We are already using it there:

https://github.com/haskell/cabal/blob/1003ed665e2d1073b0ded10c2dcbe5bdd6bb18f9/validate.sh#L350
