### ISSUE TITLE
HACS Installation String wget command

### ISSUE THREAD

**Issue by terry389** [haskell/cabal#8443]
I'm trying to install HACS into Home Assistant using terminal with the string provided by HACS.
It will not install.
-bash   command not found
wget    unrecognized option

Refer to the attachment from the terminal.
Does anyone know why HACS will not install.

![Screenshot 2022-08-31 142838](https://user-images.githubusercontent.com/112446216/187594085-afceed2b-fe42-4e09-aead-0fb711f76f10.png)

**Comment by jneira** [comment]
@terry389 It seems you opened the issue in the wrong repo (maybe https://github.com/hacs/get?)
