### ISSUE TITLE
Build log for local packages not stored in file?

### ISSUE THREAD

**Issue by mouse07410** [haskell/cabal#8456]
**Describe the bug**
Regardless of what arguments I give in cabal command line or `~/.cabal/config` file, verbose build log of my project does not get written to a file.

**To Reproduce**

Edited `~/.cabal/config` to set `build-log: $pkgid.log` (no effect)

```
$ cabal v2-build --verbose
```

Expected verbose output shows on the console - but *not* in a file.

Note: (local) project files do not specify anything regarding logs. My goal is to have a global default that controls it, allowing individual projects/packages to bother specifying logging explicitly only when default is not acceptable.

**Expected behavior**
File `stepic-tests.log` (as the project is named `stepic-tests` and builds only one package) stored somewhere, either in `~/.cabal/logs/` or in `./dist-newbuild/`.

**System information**
 - Operating system: macOS Monterey 12.5.1
 - `cabal`, `ghc` versions: Cabal-3.8.1.0, GHC-9.2.4

**Comment by ulysses4ever** [comment]
Related: #5901 #6811

**Comment by ulysses4ever** [comment]
Closing as a dup.
