### ISSUE TITLE
Mergify impersonates random user — do we want a determinate?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8462]
I described the problem on the Mergify bug tracker https://github.com/Mergifyio/mergify/issues/5038

They say it's inevitable, but there's an option: instead of a random account use a fixed one (added to config as [the `update_bot_account` option](https://docs.mergify.com/actions/queue/)). Do we want a determinate one? I think it'd be less surprising to everyone if we put someone in high rank there. E.g. @Mikolaj would be my choice. 

Thoughts?

**Comment by Mikolaj** [comment]
You nominate me for a bot?

**Comment by ffaf1** [comment]
Mergify impersonating random users is an excellent setup for a game of [Werewolf](https://en.wikipedia.org/wiki/Mafia_(party_game)), but not good for a busy repo as ours.

I too second a fixed account, I too think Mikolaj is a good choice.

**Comment by ulysses4ever** [comment]
I'm fed up with the messages the bot sends, so I submitted #8830.

**Comment by ulysses4ever** [comment]
The upstream issue is https://github.com/Mergifyio/mergify/issues/5069 it seems impossible to work around it because stetting account that Mergify will impersonate seems to be a premium feature now.

**Comment by Mikolaj** [comment]
That's not so bad (for a free service). Shall we close?

**Comment by ulysses4ever** [comment]
> Shall we close?

I'm not sure. These messages (although, not per se the focus of this issue) are so annoying and polluting that I'm short of writing a GitHub bot that would shoot down them! If only I could program…

**Comment by ulysses4ever** [comment]
The rebasing issue as reported on the Mergify bug tracker became really pressing recently:

- https://github.com/Mergifyio/mergify/issues/5075

Quick summary here:

- GitHub API doesn't allow a bot to do certain things including rebasing. So, it has to impersonate real people to work because rebasing is pretty usual:
  - we use rebase to update a PR branch  when `master` went ahead (see Mergify config);
  - we use Mergify queues, and those require rebases in general: the bot tries to create a "merge train" rebasing several PRs one on top of each other (Ibid.).
 
- Before February 2023 Mergify would impersonate random "authorized users" (users with elevated permissions on the repo), which was annoying but working.

- [Since February 2023 they impersonate the PR author](https://changelog.mergify.com/changelog/rebasing-pull-requests-with-a-random-user-is-deprecated) by default. The issue is, not every PR author have enough permissions for the whole thing to work. As a result we see errors like the ones reported upstream, which I referenced at the start ("Unable to update: user X is unknown").
 
- Their description of the change seem to suggest that setting `update_bot_account` to a user that is logged into Mergify Dashboard (like Mikolaj or myself) should solve the issue.

- [People quickly noticed](https://github.com/Mergifyio/mergify/issues/5074) that setting `update_bot_account` was a premium feature. [My experiment here](#8830) to set that option also seemed to have failed because we don't have premium of course.

- Interestingly, I don't see a mention about this feature being premium in the docs right now. I repeat the experiment here: #9120
