### ISSUE TITLE
Decide what to do about licenses

### ISSUE THREAD

**Issue by bos** [haskell/cabal#847]
(Imported from [Trac #857](http://hackage.haskell.org/trac/hackage/ticket/857), reported by @dcoutts on 2011-06-18)

Currently you can specify some partial info about a license in the .cabal file. It's not exhaustive and does not cover all licenses. It seems originally intended so that common licenses will be given the same name (so no confusion over "bsd" =? "BSD").

There are a number of outstanding requests for new licenses to be listed (#844 BSD2 &amp; ISC, #811 Apache). This is based on users expecting that most licenses they might want should be listed. The current alternative of course is that they just list it as <tt>OtherLicense</tt>.

So this all comes down to what do we want the license field for, what is it's purpose, does it have any semantics?

Currently we can't really say that it has any reliable semantics (even if the info were accurate), it's really just a way to stop people spelling "GPL" wrong. It also serves a purpose to indicate what are recommended licenses, to work against license proliferation.

So, should we move to a more accurate license system where you can express more precisely the licensing terms? Apart from listing more licenses this would mean we have to tackle:

<ul><li>multiple licenses (conjunctive): the distributor has to comply with multiple licenses, e.g. because different parts of the code have different licenses.
</li><li>dual licensing (disjunctive): the distributor gets to pick which license to use
</li><li>GPL open ended versions: The GPL recommends that authors license under terms like "Version X or any later version". This is a special kind of dual licensing, it's the infinite disjunction of all later versions of the license and of course those later versions are mostly unknown so it'd have to be handled specially.
</li></ul>Then there's the issue in the BSD licenses that there's hardly any standard BSD3 license, people make up all kinds of variations. The 2-clause license is not actually (properly) listed by the FSF or the OSI (bizarrely the OSI has it listed but with the wrong text).

**Comment by jmatsushita** [comment]
Hi there. I hope this is the right issue thread. There are some free Creative Commons licenses which might be considered for addition to the list?

I am generating a website with Hakyll and this involves creating a custom cabal package to generate the site. While I guess the content is somewhat separated from the custom site generator, there can be very much seen as much as "code" than "content". In fact, when asked about the license the first thing that came to my mind was Creative Commons, after all, I'm building a website, I thought. Then I realised that that wasn't a Cabal license. 

**CC0** and an number of other **Creative Commons** licenses are in the [GNU license list](https://www.gnu.org/licenses/license-list.html). Don't know if that fits the "popularity" criteria.

**Comment by phadej** [comment]
https://github.com/haskell/cabal/issues/2547 is related

**Comment by dirrelito** [comment]
I would be more than happy if the creative commons licenses would be available. CC0 or CC-BY-NC-SA-4.0 or similar would be nifty.

Doing it the npm way and [recommending SPDX tags](https://docs.npmjs.com/files/package.json#license) migth be a way to standardize the set of allowed licenses?

**Comment by hvr** [comment]
@dirrelito adopting SPDX is what #2547 is all about :-)

**Comment by fgaz** [comment]
We seem to have reached a conclusion in #2547. Can we close this?

**Comment by 23Skidoo** [comment]
Closing in favour of #2547.
