### ISSUE TITLE
How can environment file get into invalid state?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#8473]
A user was having trouble with cabal and posted [his environment file](https://mail.haskell.org/pipermail/haskell-cafe/2022-September/135536.html) to haskell-cafe. It contains entries for `ghc-8.4.4` and `directory-1.3.7.1`, which are mutually incompatible. Therefore [cabal stopped working](https://mail.haskell.org/pipermail/haskell-cafe/2022-September/135533.html). I assume the environment file got into this state just through running `cabal install` and/or `cabal install --lib` rather than manually editing the environment file or using any other tooling. That's what [the thread](https://mail.haskell.org/pipermail/haskell-cafe/2022-September/135533.html) suggests at least.

If it did get this way through `cabal`, how is that possible? Can `cabal` really create an environment file with mutually incompatible packages in it?

**Comment by Mikolaj** [comment]
The user clearly states "cabal install --lib" has been involved.

**Comment by tomjaguarpaw** [comment]
Yes, Can `cabal install --lib` get the environment file into an invalid state?

**Comment by volkerwysk** [comment]
Hi! That user, that's me. Yes, I've just run `cabal install` and `cabal install --lib`. I haven't touched that environment file, or done any other tooling.

**Comment by ulysses4ever** [comment]
@tomjaguarpaw yes, this is a known problem, unfortunately. See #5559 (and if you're still curious #7373).

**Comment by tomjaguarpaw** [comment]
Ah thank you! That resolves my question.
