### ISSUE TITLE
The program 'ghc-pkg' is required but it could not be found error on Windows

### ISSUE THREAD

**Issue by salimp2009** [haskell/cabal#8480]
**Describe the bug**
I am Windows 11, I have been using ghc, ghcup cabal and stack for 6 months.

recently I updated cabal to cabal-3.8.1.0 via ghcup (version v0.1.18.0)

After the update when i use cabal repl; it gives me error 

`C:\Users\User>cabal repl
Error: cabal-3.8.1.0.exe: The program 'ghc-pkg' is required but it could not
be found.`

I also get this if i use cabal init ;
```
C:\Users\User>cabal init
Error: cabal-3.8.1.0.exe: The program 'ghc-pkg' is required but it could not
be found.
```

I also have ghc version 9.2.4 . I tried almost every version ghc 9 series and it gives me the same error.
I also installed previous version of cabal now that one does not work either. 

I also use WSL2 and cabal works over there

On Windows ghci  works and stack works fine but the problem is the cabal which is not working after the update.
I tried all version of cabal and reinstall the working version but did not work.

**To Reproduce**
cabal init
or 
cabal repl

```
$ cabal v2-build ...
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 Windows 11 ; using command line 
here is the list from ghcup;

```
I  ghc   8.10.7   recommended,base-4.14.3.0 hls-powered
X  ghc   9.0.1    base-4.15.0.0
I  ghc   9.0.2    base-4.15.1.0             hls-powered
X  ghc   9.2.1    base-4.16.0.0
I  ghc   9.2.2    base-4.16.1.0
X  ghc   9.2.3    base-4.16.2.0             hls-powered
IS ghc   9.2.4    base-4.16.3.0             hls-powered
X  ghc   9.4.1    base-4.17.0.0             hls-powered
X  ghc   9.4.2    latest,base-4.17.0.0      hls-powered
X  cabal 2.4.1.0
X  cabal 3.0.0.0
X  cabal 3.2.0.0
X  cabal 3.4.0.0
X  cabal 3.4.1.0
X  cabal 3.6.0.0
X  cabal 3.6.2.0  recommended
IS cabal 3.8.1.0  latest
X  hls   1.1.0
X  hls   1.2.0
X  hls   1.3.0
X  hls   1.4.0
X  hls   1.5.0
X  hls   1.5.1
X  hls   1.6.0.0
I  hls   1.6.1.0
I  hls   1.7.0.0
IS hls   1.8.0.0  latest,recommended
X  stack 2.5.1
X  stack 2.7.1
IS stack 2.7.3
X  stack 2.7.5    latest,recommended
IS ghcup 0.1.18.0 latest,recommended
```
![cabalIssue](https://user-images.githubusercontent.com/46407603/190869889-2f3239e4-328b-4dd4-94dd-3b18a6728c99.jpg)

**Additional context**

**Comment by jneira** [comment]
Hi, thanks for the report, unfortunately i cant reproducein windows 10:

```
PS D:\dev\ws\haskell\unison> cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library
PS D:\dev\ws\haskell\unison> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
PS D:\dev\ws\haskell\unison> ghcup set ghc 9.2.1
[ Warn  ] New ghc version available. To upgrade, run 'ghcup install ghc 9.4.2'
[ Warn  ] New stack version available. To upgrade, run 'ghcup install stack 2.7.5'
[ Info  ] verifying digest of: gs.exe
[ Info  ] GHC 9.2.1 successfully set as default version
PS D:\dev\ws\haskell\unison> ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
PS D:\dev\ws\haskell\unison> cabal repl
Resolving dependencies...
Build profile: -w ghc-9.2.1 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Warning: No exposed modules
GHCi, version 9.2.1: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from C:\\TEMP\\cabal-repl.-8648\\setcwd.ghci
```

Could you share the output of: `where.exe ghc`, `where.exe ghc-pkg` and `cabal exec -- where.exe ghc-pkg`.
Last one needs to be executed in a dir with a .cabal file. `cabal repl -v2` log could be useful too

**Comment by salimp2009** [comment]
thanks for returning back .
here are info you asked
where should I look for the log file ? I can send that one too

```
C:\Users\User>where.exe ghc
C:\ghcup\bin\ghc.exe
```
```

C:\Users\User>where.exe ghc-pkg
INFO: Could not find files for the given pattern(s).
```

the last one has cabal file create by cabal init when it was working
somehow looks like it cant find ghc-pkg; (not sure where it has to be)
weird thing it was working before;

```
C:\developer\haskell\learn-cabal>ls -a
.  ..  app  CHANGELOG.md  dist-newstyle  learn-cabal.cabal  LICENSE  src  test

C:\developer\haskell\learn-cabal>cabal exec -- where.exe ghc-pkg
cabal-3.6.2.0.exe: The program 'ghc-pkg' is required but it could not be
found.
```

also tried to rebuild the existing  project and failed but i create it before with cabal

```
C:\developer\haskell\learn-cabal>cabal build lib:learn-cabal
cabal-3.6.2.0.exe: The program 'ghc-pkg' is required but it could not be
found.
```

**Comment by jneira** [comment]
Ok, ghc-pkg is an executable included in ghc bindist and it is required to build or evaluate haskell programs which uses dependencies. It usually is in the same directory that ghc itself:
```
PS D:\dev\ws\haskell\unison> where.exe ghc-pkg
D:\ghcup\bin\ghc-pkg.exe
```
It seems your ghcup installation is broken someway, you could try: `ghcup unset ghc && ghcup set ghc`. If that does not work you could try `ghcup rm ghc x.y.z && ghcup install ghc x.y.z`. The goal would be restore the ghc-pkg executable close to ghc one.

**Comment by salimp2009** [comment]
ghc-pck versions are all in ghcup\bin directory
```
c:\ghcup\bin>ghc-pkg-9.2.4
ghc-pkg-9.2.4.exe: missing command
For usage information see 'ghc-pkg-9.2.4.exe --help'.
```

**Comment by salimp2009** [comment]
it worked after i did 
`ghcup unset ghc && ghcup set ghc`

it is working now ..thank you ...awesome ..whoooo :)))

```
c:\ghcup\bin>cabal repl
Resolving dependencies...
Build profile: -w ghc-9.2.4 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Warning: No exposed modules
GHCi, version 9.2.4: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from C:\Users\User\AppData\Roaming\ghc\ghci.conf
Loaded GHCi configuration from C:\\Users\\User\\AppData\\Local\\Temp\\cabal-repl.-16509\\setcwd.ghci


```

**Comment by jneira** [comment]
Nice! That executable is a "shim", a poor's man hard link for windows, pointing to the real executable inside `D:\ghcup\ghc...` and sometimes it does not work properly. Glad to help and happy haskell hacking

**Comment by lattice0** [comment]
Got this error on this docker container:

```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y build-essential curl \
libffi-dev libffi7 libgmp-dev libgmp10 \
libncurses-dev libncurses5 libtinfo5 git

ENV BOOTSTRAP_HASKELL_NONINTERACTIVE=1

ENV PATH ~/.ghcup/bin:$PATH
RUN sh -c "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh"

```
