### ISSUE TITLE
"Build profile" message doesn't reflect optimization setting from ~/.cabal/config

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8487]
_Originally posted by @mouse07410 in https://github.com/haskell/cabal/issues/6221#issuecomment-1236860222_

The title says it all. I checked that the `optimization: 2` in the global config is not reflected, but the local packages respect it (unless it was overridden down the line -- in cabal.project(.local) or .cabal files). It's not hard to fix. I could take it if there's no objections.

**Comment by mouse07410** [comment]
Objections? I think a fix should be welcome!

**Comment by ulysses4ever** [comment]
PR is posted #8488

**Comment by Mikolaj** [comment]
@mouse07410: could you kindly review, given that this PR is based on your input?

**Comment by Mikolaj** [comment]
Edit: ideally, test locally and review.

**Comment by Mikolaj** [comment]
Edit: wrong window. :)
