### ISSUE TITLE
cabal check complains about -Werror in cabal.project

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#8490]
**Describe the bug**

`cabal check` complains about `-Werror` even if it is set in the `cabal.project` file

**Expected behavior**

Given that `-Werror` is only bad if it is part of the `.cabal` file uploaded to Hackage, setting it in the `cabal.project` file should not trigger the bug.

**System information**

This is `cabal-3.6.2.0 ` from ghcup via `haskell-ci`.

**Additional context**

In my case the `cabal.project` is created by `haskell-ci` when using

```
haskell-ci regenerate  --local-ghc-options -Werror
```
which I tought might be a good way to get `-Werror` active on CI without affecting the Hackage releases.

(This is a minor thing of course, but still worth noting down.)

**Comment by ulysses4ever** [comment]
Thanks for the report! We have a full-fledged rewrite of `cabal check` under way: #8427. It'd be nice if someone could try that branch and see if it's affected. /cc @ffaf1

**Comment by ffaf1** [comment]
I am trying to reproduce this on my machine but cannot, the way to trigget is is with:

```
package *
    ghc-options: -Wall -Werror
```

in `cabal.project`, right?

**Comment by nomeata** [comment]
See https://github.com/nomeata/haskell-rec-def/actions/runs/3105946791/jobs/5032197241#step:21:29 for a failing run. It uses
```
package rec-def
  ghc-options: -Werror
```
so yes, that should be it. (The -Wall is part of the cabal file, if that makes a difference)

**Comment by ffaf1** [comment]
[prova.zip](https://github.com/haskell/cabal/files/9627394/prova.zip)

Can you try to unpack and then `cd prova2/ && cabal check`? I get `No errors or warnings could be found in the package.` with `3.8.1.0`.

edit: wait, I see an “unguarded” (not under flag) `-Wall -Werror` in the cabal file:

https://github.com/nomeata/haskell-rec-def/blob/3365379b6c29aa32a5170b8d0336c73413ca7434/rec-def.cabal#L72

Did CI fail with that?

**Comment by nomeata** [comment]
🤦🏻 

Sorry! My brain was thinking “I should add -Werror wait I should only add it to CI” and my fingers must have added it to the .cabal file before I noticed.

**Comment by ffaf1** [comment]
No worries, this highlights `cabal check` could benefit for specific column:row indication for warnings.

Il 22 settembre 2022 alle 10:20 Joachim Breitner ha scritto:
