### ISSUE TITLE
Feature request: Hackage X-ApiKey authentication in `cabal upload`

### ISSUE THREAD

**Issue by lf-** [haskell/cabal#8497]
Hackage supports generating an API key, which stack supports: https://github.com/commercialhaskell/stack/issues/5513

However, I can't find anything in the Cabal code supporting this. It would be quite nice to have it.

**Comment by ulysses4ever** [comment]
Sounds like a reasonable enhancement for `cabal upload`, and a one that shouldn’t be hard to implement.

**Comment by ulysses4ever** [comment]
This is probably a dup of #6738 but with a better description.
