### ISSUE TITLE
cabal-install and cabal-install-solver have unnecessarily strict base <4.17 constraint on hackage

### ISSUE THREAD

**Issue by sternenseemann** [haskell/cabal#8509]
It would be great if some with the appropriate permissions could create a hackage revision for both packages and applies the constraints as they are present in the repository now – then it'd be possible to build cabal-install from hackage with GHC 9.4.2.

**Comment by jneira** [comment]
hi, thanks for the suggestion, in the meanwhile, if the problem is only about base you coukld install it with `cabal install cabal-install --allow-newer="cabal-install:base"`

if that command does not succes, it means such hackage revision will not be enough either.

**Comment by sternenseemann** [comment]
I am already lifting the bounds on `base` manually which is why I opened this issue.

**Comment by sternenseemann** [comment]
Yes, I think so. The two failures I encountered were:

```
Configuring cabal-install-solver-3.8.1.0...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
base >=4.10 && <4.17
```

and

```
Configuring cabal-install-3.8.1.0...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
base >=4.10 && <4.17
```

GHC 9.4.2 otherwise ships the library versions cabal-install 3.8.1.0 wants by default (process, Cabal, Cabal-syntax).

**Comment by Mikolaj** [comment]
Done, Please kindly verify and close, if it works fine.

**Comment by sternenseemann** [comment]
Took a while, but can confirm that this resolves the issue!

**Comment by Mikolaj** [comment]
Thank you. :)

**Comment by juhp** [comment]
Still not on cabal-3.8 branch...
