### ISSUE TITLE
doc/html/frames.html broken on many recent packages

### ISSUE THREAD

**Issue by bos** [haskell/cabal#851]
(Imported from [Trac #861](http://hackage.haskell.org/trac/hackage/ticket/861), reported by @liyang on 2011-07-08)

For example, this works: [http://hackage.haskell.org/packages/archive/containers/latest/doc/html/frames.html](http://hackage.haskell.org/packages/archive/containers/latest/doc/html/frames.html)

But this doesn't: [http://hackage.haskell.org/packages/archive/mtl/latest/doc/html/frames.html](http://hackage.haskell.org/packages/archive/mtl/latest/doc/html/frames.html)

The frames version is rather useful in lieu of Chrome having a sidebar.

I'm guessing the original index.html and index-frames.html have been moved (rather than copied) elsewhere.

Thanks,
/Liyang

**Comment by ttuegel** [comment]
This isn't a Cabal issue, it's not even a Hackage issue.
