### ISSUE TITLE
Update PR and issue templates

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8511]
- [x] refer to CONTRIBUTING.md 
- [x] add templates for things other than bugs (presumably, "enhancement", "documentation")
- [x] ditch mention of `v2-` commands: they've been long the default
- [ ] add simplified PR template (see below)
- [ ] refer to [master/CONTRIBUTING.md#github-pull-request-conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md?rgh-link-date=2023-07-09T18%3A55%3A13Z#github-pull-request-conventions) in every PR template

_Originally posted by @Mikolaj in https://github.com/haskell/cabal/issues/6370#issuecomment-1193628012_

### Simplified PR template

People keep complaining about our PR template in that it has a long set of checkboxes that are not necessarily relevant for small contributions, and those are usually made by newcomers, so they get especially confused. Maybe, we need another template: something like "Documentation" or "User-invisible change" without any checkboxes.

See also:

- stack's templates as a source of inspiration: https://github.com/commercialhaskell/stack/issues/new/choose

**Comment by ulysses4ever** [comment]
Actually, a reference to CONTRIBUTING.md is already made in the current PR template.

**Comment by ffaf1** [comment]
Do we (in general) want a “User questions” template? (edit: Ok, I am seeing what stack does and it correctly points first and foremost to Discourse).

**Comment by geekosaur** [comment]
I'd say that's either Discourse or possibly the Discussions area. (Might be worth considering that it's very easy to switch something between Discussion and Issue on GH.)

**Comment by ulysses4ever** [comment]
I don't have a strong feeling about questions. We don't receive many of those anyway. I just felt that it may seem more welcoming to have it. And I'd much rather answer Cabal questions here instead of anywhere else, but I realize that it may be undesirable for some reasons.

**Comment by ulysses4ever** [comment]
I updated the description with a "simplified PR template". Please, share your thoughts!

**Comment by ffaf1** [comment]
Where would I choose the simplified template? When I make a PR? Would it be default?

**Comment by ulysses4ever** [comment]
@ffaf1 when you push the green button, just like with issues, no? I did double-check that GitHub allows several PR templates.
