### ISSUE TITLE
--bindir is ignored without warning or suggestion that `--installdir` should be used

### ISSUE THREAD

**Issue by mgajda** [haskell/cabal#8520]
**Describe the bug**

Using `v1-install` option `--bindir` results in no warning, but is silently ignored.
The option is displayed in `cabal new-install --help`, but redundant with `--installdir`

**To Reproduce**

```
$ cabal v2-install --bindir ./output
```
The resulting binary will not be copied to `./output`, nor warning will be issued.

**Expected behavior**

Since `--bindir` is accepted, it should be duplicate of `--installdir` or removed.

**System information**
 - `cabal` version `3.4.1.0`
 - `ghc` version -- irrelevant

*** Related ***

Similar problem as with #7437.

**Comment by mouse07410** [comment]
I confirm this problem.

**Comment by gbaz** [comment]
This should be resolved by https://github.com/haskell/cabal/pull/8556 which removes all installdirs options from new-install (but leaves them for build, etc)

**Comment by Mikolaj** [comment]
@mgajda and @mouse07410, could you kindly verify with the cabal version on master branch?

**Comment by Mikolaj** [comment]
@mouse07410: hah, you've edited my comment.

Any artifact from a merged PR should do. E.g., at the very bottom of 

https://github.com/haskell/cabal/actions/runs/3716873166

Let me know if that's not enough.

**Comment by mouse07410** [comment]
> @mouse07410: hah, you've edited my comment.

Hmm, did not realize...

 
> Any artifact from a merged PR should do. E.g., at the very bottom of
> 
> https://github.com/haskell/cabal/actions/runs/3716873166

Perhaps I'm being dense, and fighting some weird respiratory virus doesn't make me any sharper :-( . But I saw no artifacts there.
 
> Let me know if that's not enough.

I'm afraid it isn't. If somewhere within those runs is a snippet that places linked cabal binary to somewhere where I can reach it with, e.g., `wget` or `curl` - I did not see it.

So, I'd love something like (URL is definitely incorrect, and crafted merely to show what I'm trying to request):
https://github.com/haskell/cabal/actions/runs/3716873166/jobs/123456678/bin/cabal
It would be nice if the job is for `macOS` and uses GHC-9.0.2, 9.2.5, or 9.4.3.

Otherwise, I'm viewing a ton of validation output, but no artifacts...

**Comment by ulysses4ever** [comment]
@mouse07410 unfortunately, you can't get a direct download link for GitHub artifacts (see https://github.com/actions/upload-artifact/issues/27), and you have to use a web browser to retrieve them. Try again that page, and just Cmd+F (search) for the word Artifact: second occurrence of it should lead you to the links.

Direct link would be possible if we organized nightly pre-releases, as it was suggested in  #8541. If you feel energy, feel free to work on it: it's a simple update of the CI with a huge dev experience improvement.

**Comment by mouse07410** [comment]
> unfortunately, you can't get a direct download link for GitHub artifacts (see https://github.com/actions/upload-artifact/issues/27), and you have to use a web browser to retrieve them

That is fine. My problem is - there doesn't seem to be any artifact on that page.

>  Try again that page, and just Cmd+F (search) for the word Artifact: second occurrence of it should lead you to the links.

Either we're talking about different pages, or I've no clue whatsoever. Search for "Artifact" found zero entries.

That page only contains logs of "Validate XXX" jobs, "Dogfooding XXX" jobs, and "Validate post job". Trying to dig into any of those logs gives me the standard CI log "Set up job, Run actions/checkput@v3, ..." etc. I don't see any artifact (nor Artifact) anywhere there.

Besides the above, I picked the "Validate for macOS GHC-9.0.2" job
https://github.com/haskell/cabal/actions/runs/3716873166/jobs/6303690863 and tried to "guess" where the artifacts might be: https://github.com/haskell/cabal/actions/runs/3716873166/jobs/6303690863/artifacts

No joy.

This https://github.com/haskell/cabal/actions/artifacts also returns HTTP 404.

And before you ask, this https://github.com/haskell/cabal/actions/artifacts/3716873166/zip also fails with 404.

My guess is - there _are_ no artifacts on that page. As the proverb goes - "it's hard to search for a black cat in a dark room. Especially if it isn't there".


_Would love to show screenshots, but ~~stupid~~ GitHub does not allow uploading them anymore either._

> Direct link would be possible if we organized nightly pre-releases, as it was suggested in https://github.com/haskell/cabal/issues/8541.

I don't have a lot of time on my hands, especially now - but I'll take a look. In fact, I'm very surprised it hasn't been done yet.

**Comment by Mikolaj** [comment]
I'm really surprised. Your browser must be broken somehow, particularly the C-f functionality (you did use it, right? not the "Search" input field of github?). But scrolling the whole page with a scrollbar on the right (*not* scrolling any sub-pane only) of the original link I posted

https://github.com/haskell/cabal/actions/runs/3716873166

should really show a short "Artifacts" section at the end. If it doesn't, perhaps fire a Linux VM and try again.

**Comment by mouse07410** [comment]
> Your browser must be broken somehow, particularly the C-f functionality (you did use it, right? not the "Search" input field of github?)

Considering that my browser works with everything else (so far), I rather doubt it's broken. Yes, I used Cmd-F (the only way to do a search on the page?).

> should really show a short "Artifacts" section at the end

Damn it! I found it in your newly-provided page by scrolling to the very end _the **right** column_.

So, this page https://github.com/haskell/cabal/actions/runs/3716873166/ has it.
That page (original URL given) https://github.com/haskell/cabal/actions/runs/3716873166/jobs/6303690863 does not (the wrong one has "jobs/6303690863" suffix).

Now, to business. Downloaded artifact is installed on my system as `cabal-dev`.

```
$ cabal-dev install --bindir /tmp/output
Warning: this is a debug build of cabal-install with assertions enabled.
Wrote tarball sdist to
/Users/ur20980/src/stepic-tests/dist-newstyle/sdist/stepic-tests-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-9.4.3 -O2
In order, the following will be built (use -v for more details):
 - stepic-tests-0.1.0.0 (lib) (requires build)
Assertion failed
CallStack (from HasCallStack):
  assert, called at src/Distribution/Client/ProjectPlanning.hs:248:5 in cabal-install-3.9.0.0-inplace:Distribution.Client.ProjectPlanning
$ 
```

With the released cabal 3.8.1.0:
```
$ cabal install --bindir /tmp/output
Wrote tarball sdist to
/Users/ur20980/src/stepic-tests/dist-newstyle/sdist/stepic-tests-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-9.4.3 -O1
In order, the following will be built (use -v for more details):
 - stepic-tests-0.1.0.0 (lib) (requires build)
 - stepic-tests-0.1.0.0 (exe:maybe-demo) (requires build)
 - stepic-tests-0.1.0.0 (exe:qroots) (requires build)
 - stepic-tests-0.1.0.0 (exe:stepic-tests-exe) (requires build)
Starting     stepic-tests-0.1.0.0 (lib)
Building     stepic-tests-0.1.0.0 (lib)
Haddock      stepic-tests-0.1.0.0 (lib)
Installing   stepic-tests-0.1.0.0 (lib)
Completed    stepic-tests-0.1.0.0 (lib)
Starting     stepic-tests-0.1.0.0 (exe:maybe-demo)
Starting     stepic-tests-0.1.0.0 (exe:qroots)
Starting     stepic-tests-0.1.0.0 (exe:stepic-tests-exe)
Building     stepic-tests-0.1.0.0 (exe:maybe-demo)
Building     stepic-tests-0.1.0.0 (exe:qroots)
Building     stepic-tests-0.1.0.0 (exe:stepic-tests-exe)
Installing   stepic-tests-0.1.0.0 (exe:maybe-demo)
Installing   stepic-tests-0.1.0.0 (exe:qroots)
Completed    stepic-tests-0.1.0.0 (exe:maybe-demo)
Completed    stepic-tests-0.1.0.0 (exe:qroots)
Installing   stepic-tests-0.1.0.0 (exe:stepic-tests-exe)
Completed    stepic-tests-0.1.0.0 (exe:stepic-tests-exe)
Symlinking 'stepic-tests-exe' to '/Users/ur20980/.cabal/bin/stepic-tests-exe'
Symlinking 'qroots' to '/Users/ur20980/.cabal/bin/qroots'
Symlinking 'maybe-demo' to '/Users/ur20980/.cabal/bin/maybe-demo'
$ ll /tmp/output
total 0
drwxr-xr-x   2 ur20980  wheel    64 Dec 20 10:01 ./
drwxrwxrwt  33 root     wheel  1056 Dec 20 10:01 ../
$
```

**Comment by Mikolaj** [comment]
@mouse07410: I've started a gitlab run for you with the latest master branch *and* without assertions (that's how gitlab is configured):

https://gitlab.haskell.org/haskell/cabal/-/pipelines

The ProjectPlanning assertion failure is a known old embarrassing bug with a ticket or a few. I hope it only manifests with assertions on.

I hope your respiratory virus gets evicted soon. :)

**Comment by Mikolaj** [comment]
I see https://github.com/haskell/cabal/pull/8556 is still not merged, so if the above doesn't work, I will try to build https://github.com/haskell/cabal/pull/8556 on gitlab so that it doesn't have assertions.

**Comment by mouse07410** [comment]
@Mikolaj thank you - downloaded a working artifact from GitLab.

It still fails in exactly the same way: silently installs into `$HOME/.cabal/bin/`.
```
$ cabal-dev install --bindir=/tmp/output/
Wrote tarball sdist to
/Users/ur20980/src/stepic-tests/dist-newstyle/sdist/stepic-tests-0.1.0.0.tar.gz
Resolving dependencies...
Symlinking 'stepic-tests-exe' to '/Users/ur20980/.cabal/bin/stepic-tests-exe'
Error: cabal-dev: Path '/Users/ur20980/.cabal/bin/stepic-tests-exe' already
exists. Use --overwrite-policy=always to overwrite.

$ 
```

**Comment by gbaz** [comment]
I tested on that branch and got the following?

> cabal install --bindir=/tmp/output
> Warning: this is a debug build of cabal-install with assertions enabled.
> Error: cabal: unrecognized 'install' option `--bindir=/tmp/output'

**Comment by Mikolaj** [comment]
Amazing. Thank you, @gbaz. In that case I think we can put it to rest until #8556 is merged.

Afterwards, volunteer to update https://cabal.readthedocs.io/en/latest would be welcome.
