### ISSUE TITLE
An actually missing package list for a repository should probably be an error

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#8524]
If your package list is not up-to-date, cabal says things like this:
```
Warning: The package list for 'hackage.haskell.org' is 138 days old.
Run 'cabal update' to get the latest list of available packages.
```
It makes sense for this to be a warning, you may indeed not want to update.

But if you _don't have the package list at all_, that's _also_ a warning:
```
Warning: The package list for 'cardano-haskell-packages' does not exist. Run
'cabal update' to download it.
```

This seems like it should probably be an error: the user has said they want to use a package repository, but they don't have any content for it. Maybe that's wrong and there's a circumstance where you want to continue?

**Comment by jneira** [comment]
there is no situation when not having the list is "normal"? for example the first time you set the repository?

**Comment by ffaf1** [comment]
Just Asking Questions™:
- are there `cabal.projects` in the wild which depends only on `base`?
- do they work without an `update` first?

If no such thing is there, erroring early seems good UX.

**Comment by gbaz** [comment]
I believe there are operations that still work even without repo info, so we may want to be a bit cautious at which points this errors so as not to break any existing odd workflows.

**Comment by AndreasPK** [comment]
> Just Asking Questions™:
> 
> * are there `cabal.projects` in the wild which depends only on `base`?
> * do they work without an `update` first?
> 
> If no such thing is there, erroring early seems good UX.

I have a package that only depends on base and containers and it still builds with cabal when I delete the package list.

**Comment by ffaf1** [comment]
Thanks @AndreasPK, then I suspect erroring may not be the best path (or rather, not in every case).

**Comment by michaelpj** [comment]
Okay, that's convincing. Maybe I just need to push more for the other issue about making warnings more obvious.
