### ISSUE TITLE
docs: mention GitHub CI build artifacts in README

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8541]
We often have to reference them, so maybe adding a reference to the README could save us some effort...

**Comment by Mikolaj** [comment]
Also, gitlab artifacts, citing @jneira:

https://discourse.haskell.org/t/request-for-testing-of-the-xdg-enabled-cabal-install/5200/3?u=jneira

and below in the same post is how to install from gitlab via ghcup (I wonder if one can install from github in this way and if there's any advantage).

**Comment by athas** [comment]
One way of doing this, which seems fairly common for other projects, is to have a GitHub "release" that is automatically updated on every commit.  GitHub releases are mutable, so you only need a single one that you keep changing.  This is pretty visible to users.

**Comment by athas** [comment]
Not sure about Settings, but it does require GHA additions.  As inspiration for someone who wants to embark on this, [here are the salient parts from another Haskell project](https://github.com/diku-dk/futhark/blob/2fbd0875c2652cd58b039572ac50978ba41a0cd0/.github/workflows/main.yml#L605-L615).

I don't remember any downsides or problems, although you'll have a GitHub-side tag `nightly` that keeps changing.  As long as the release is marked as a "prerelease", no automated tooling that checks for new Cabal versions should be confused by the constantly changing release.

**Comment by ulysses4ever** [comment]
I also think no need in settings is required. @athas could you submit a PR with that snippet you referenced? A point of bike shedding: I don't like the title/tag "nightly" because it feels like it updates once a day. I'd call it "latest".

**Comment by Mikolaj** [comment]
As a stop-gap before we have nightly pre-releases, would it make sense to extend building (no-assert) binaries on gitlab from all tags to all PR merges (if that's possible; alternatively, all pushes, that's almost the same)?

@bgamari: would that burden gitlab too much? We don't have a high traffic compared to GHC, I think.
