### ISSUE TITLE
Make it clearer when solver errors are due to GHC version mismatch

### ISSUE THREAD

**Issue by danieljharvey** [haskell/cabal#8542]
**Describe the bug**

When solver errors are caused by an incompatible version of base, it's not clear that the GHC version is the issue.

**To Reproduce**

When running `cabal v2-install ormolu-0.3.0.1` with GHC 9.2.4, I get a wall of text solver error ending like this:

`After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghc-lib-parser, base, ormolu`

**Expected behavior**

The underlying problem here is that the version of `base` in GHC 9.2.4 is not compatible with this version of `ormolu`. However, it would really great for onboarding if we told the user this, so if `base` in included in this list, then `cabal` also tells them something along the lines of:

"The target package is not compatible with the version of `base` with your GHC version. This may indicate that you need to use a different compiler version to install this."

**System information**

Tested on M1 Mac, but pretty sure this is a universal issue

**Additional context**

I would be happy to implement this, if
a) this is something that people would find helpful
b) there is not another reason that `base` could be in the list above, thus making the message potentially misleading etc.

**Comment by ffaf1** [comment]
Indeed that would be a very good UX improvement!

**Comment by grayjay** [comment]
This issue looks like a duplicate of #7993. #7993 is more general because it suggests improving the error message for all non-upgradable packages.

**Comment by danieljharvey** [comment]
Looks like that other issue is much more detailed, will close this to reduce the noise.
