### ISSUE TITLE
`cabal repl -b ...` generates `dist-newstyle` 

### ISSUE THREAD

**Issue by fendor** [haskell/cabal#8550]
**Describe the bug**

`cabal repl -b ...` populates the `dist-newstyle` directory, even though it shouldn't.

**To Reproduce**

```
$ mkdir some-dir && cd some-dir
$ ls
$ cabal v2-repl -b base
> :q
$ ls # should be empty, but isn't
$ tree
.
└── dist-newstyle
    └── cache
        └── compiler

```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
No `dist-newstyle` should be created 

**System information**
 - Arch Linux
 - `cabal` 3.8.1.0
 - `ghc` 8.10.7

**Comment by gbaz** [comment]
expect this may be fixed by https://github.com/haskell/cabal/pull/8358 ?

**Comment by fendor** [comment]
Just checked cabal for the latest master commit e714824c6e652bf894f914bc57feccc15759668a and it is **not** fixed.

**Comment by ulysses4ever** [comment]
Same, I pulled the version built in CI for #8358, and it does create `dist-newstyle` both for `cabal repl` and `cabal update`.
