### ISSUE TITLE
`gcc.exe' failed in phase `Linker'. (Exit code: 1)

### ISSUE THREAD

**Issue by gospacedev** [haskell/cabal#8560]
**Describe the bug**
I tried to do the Quick Start Guide in: https://www.haskell.org/cabal/ but I got an error when running it:
```cmd
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
```

**To Reproduce**

```
cabal install cabal-install
mkdir myproject && cd myproject
cabal init
cabal run
```
```
Build profile: -w ghc-9.2.4 -O1
In order, the following will be built (use -v for more details):
 - myproject-0.1.0.0 (exe:myproject) (first run)
Preprocessing executable 'myproject' for myproject-0.1.0.0..
Building executable 'myproject' for myproject-0.1.0.0..
Linking C:\\Users\\grant\\Projects\\myproject\\dist-newstyle\\build\\x86_64-windows\\ghc-9.2.4\\myproject-0.1.0.0\\x\\myproject\\build\\myproject\\myproject.exe ...
C://ghcup//ghc//9.2.4//mingw//bin/ld.exe: C://ghcup//ghc//9.2.4//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_app_type[.refptr.mingw_app_type]+0x0): undefined reference to `mingw_app_type'
C://ghcup//ghc//9.2.4//mingw//bin/ld.exe: C://ghcup//ghc//9.2.4//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initcharmax[.refptr.mingw_initcharmax]+0x0): undefined reference to `mingw_initcharmax'
C://ghcup//ghc//9.2.4//mingw//bin/ld.exe: C://ghcup//ghc//9.2.4//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltssuo_force[.refptr.mingw_initltssuo_force]+0x0): undefined reference to `mingw_initltssuo_force'
C://ghcup//ghc//9.2.4//mingw//bin/ld.exe: C://ghcup//ghc//9.2.4//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdyn_force[.refptr.mingw_initltsdyn_force]+0x0): undefined reference to `mingw_initltsdyn_force'
C://ghcup//ghc//9.2.4//mingw//bin/ld.exe: C://ghcup//ghc//9.2.4//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdrot_force[.refptr.mingw_initltsdrot_force]+0x0): undefined reference to `mingw_initltsdrot_force'
collect2.exe: error: ld returned 1 exit status
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
```

**Expected behavior**
I expected it to run.

**System information**
 - Windows 11
```
cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library
```
```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.4
```

**Comment by jneira** [comment]
hi, thanks for the report, although you have experienced it through cabal this is a bug in ghc, the Haskell compiler.
iirc ghcup replaced the bad version some time ago, if you have not downloaded recently it I would try to reinstall ghc (`ghcup rm ghc 9.2.4 && ghcup install ghc 9.2.4`). 
If the problem persists I would try other ghc version.

**Comment by gospacedev** [comment]
Thanks, I solved it by installing ghcup's recommended C toolchain.

**Comment by senmorta13** [comment]
Just for the record, I was trying to install Agda 2.6.3 using cabal 3.6.2 on Ubuntu 20.4, and I was receiving this error. Actually, I got this error when I was trying to install any package with cabal (jneira has suggested the reason). Finally, I checked all the required distro packages here (https://www.haskell.org/ghcup/install/), and I found out that I had not installed one of them (libgmp-dev I guess! However may not actually matter!).

**Comment by ulysses4ever** [comment]
@senmorta13 please, try the latest cabal: `ghcup install cabal latest` and check that `cabal --version` says cabal 3.10.*.

**Comment by Jackl-o-o-l** [comment]
> Thanks, I solved it by installing ghcup's recommended C toolchain.

Thanks, I have the same issue and I solved it by checking [System requirements of GHCup](https://www.haskell.org/ghcup/install/#system-requirements) and install all the missing distro packages. We might be talking about the same thing; I am just trying to be more specific as this might be helpful.
