### ISSUE TITLE
Cabal flag assignment unavailable to build-type: configure script

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#8564]
**Describe the bug**
Currently there is no way for the configure script of a `build-type: configure` package to inspect the flag assignment being built. This makes it essentially impossible for flags to be used to optionally enable library dependencies.

I would suggest that the flag assignment should be passed to the configure script via the environment in two ways:

 * the `CABAL_FLAGS` variable should be set to the flag assignment using the traditional Cabal flag syntax (e.g. `+flagA -flagB`)
 * for each flag, `CABAL_FLAG_<flag name>` should be set to either `0` or `1` depending upon the flag

**Comment by Mikolaj** [comment]
LGTM

**Comment by Ericson2314** [comment]
This looks good to me. It should work well both with and in lieu of #8563.

I'm of a mind that autoconf-style things basically work in two ways:

1. When flags are *not* explicitly set, environment probing is used to guess a result

2. What flag *are* explicitly set, environment probing is used to *test* and make sure the flags match reality.

So #8563 is for (1), and this (#8564) is for (2).

**Comment by bgamari** [comment]
Implemented in !8565.

**Comment by andreabedini** [comment]
Implemented in #8565.

**Comment by hasufell** [comment]
I just got hit by this design while working on GHC/RTS and it took me half a day to figure out that there's an implicit relationship between cabal flags and configure. 

I think this design needs a revision. 

I think what we need is simply being able to explicitly specify configure arguments in the cabal file.

Then you could have something like:

```
if flag(foo)
  conf-options: FOO=1
```

Then cabal runs `./configure FOO=1`.

That means you can also make conf options depend on architecture/compiler etc. It seems a much more **explicit** and **general** design.

**Comment by bgamari** [comment]
This seems like a fine design as well. However, it's not clear that we really want to deprecate the existing mechanism.

**Comment by hasufell** [comment]
> This seems like a fine design as well. However, it's not clear that we really want to deprecate the existing mechanism.

I think we should (~5 years deprecation), because it makes reading and understanding cabal files harder.

**Comment by Ericson2314** [comment]
If @hasufell wants to make a new one, I am not wedded to the old one. If we backport the new feature to older RTS and older Cabal, I don't even mind accelerating the deprecation cycle.
