### ISSUE TITLE
Try to combine lists of non-installable and non-upgradable packages

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#8581]
Issue #8489 showed that cabal contains two separate lists of packages that cannot be installed. This issue is for determining whether the lists have the same meaning and combining them if they are redundant.  #8501 synced the contents of the two lists.

One is in the solver and is described as non-installable:

https://github.com/haskell/cabal/blob/09c90de378273ae2f08fb605ea03e857ec2b8720/cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs#L158-L173

The other is in Distribution.Client.Dependency and is described as non-upgradable:

https://github.com/haskell/cabal/blob/09c90de378273ae2f08fb605ea03e857ec2b8720/cabal-install/src/Distribution/Client/Dependency.hs#L387-L414

If only one is needed, I think we should keep the one in Distribution.Client.Dependency, since it is better to make the solver more general and pass in constraints rather than hard code package names.

**Comment by wismill** [comment]
Does somebody has this info? 

Else now that the two lists are synced, we could give it a try with proper comments. It would be easy to revert and desync the two list again if there is some issue. I think this would help addressing #7993. In what module should this list go?

**Comment by Mikolaj** [comment]
@wismill: thank you for taking interest and the willingness to contribute. I hope at some point @grayjay or @gbaz find a moment to conspire with you. If not, please ping me and I will try to find help elsewhere.

**Comment by grayjay** [comment]
@wismill I think it would be fine to try out this change and see whether the tests pass. I think that we should keep the list in Distribution.Client.Dependency. A fix for #7993 could use the ConstraintSource ([ConstraintSourceNonUpgradeablePackage](https://github.com/haskell/cabal/blob/605a3c6a68cd6ff34247bc3db2bdd8e1995bc14f/cabal-install/src/Distribution/Client/Dependency.hs#L396)) to determine whether a package version is disallowed because it is not upgradable.

It may also help to add more unit tests to this test group: https://github.com/haskell/cabal/blob/605a3c6a68cd6ff34247bc3db2bdd8e1995bc14f/cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs#L151-L162

I think that the test "Refuse to install base without --allow-boot-library-installs" could at least be improved by testing for a larger part of the error message that rejects `base`. The error message may also change due to this refactoring.

**Comment by wismill** [comment]
@grayjay `Distribution.Client.Dependency` is in `cabal-install`, which depends on `cabal-install-solver`. Therefore the list should be in `cabal-install-solver`, should not it?

**Comment by grayjay** [comment]
@wismill I think that the list should stay in `Distribution.Client.Dependency`, because it is better to keep the solver more general and pass in constraints on specific packages. Handling "installed" constraints similarly to other constraints that are passed to the solver also simplifies the code.

**Comment by wismill** [comment]
@grayjay Then correct me if I am wrong, but given the package dependency we can close this issue as non-fixable.

**Comment by grayjay** [comment]
The list in `Distribution.Client.Dependency` is already passed into and used by the solver. The issue is that the solver uses two lists of packages (the other in `Distribution.Solver.Modular.Solver`), so they probably provide redundant functionality.

**Comment by grayjay** [comment]
Reopening, because the `requireInstalled` function can probably also be removed, because it is redundant with enforcing the installed constraints that are added in `Distribution.Client.Dependency`: https://github.com/haskell/cabal/blob/ab24689731e9fb45efa6277f290624622a6c214f/cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs#L321-L322

**Comment by grayjay** [comment]
@wismill Are you still interested in working on this issue?

**Comment by wismill** [comment]
@grayjay I am too busy for the moment. I cannot say when I will be available, sorry.
