### ISSUE TITLE
How to make an executable to share the app in windows

### ISSUE THREAD

**Issue by Jastxz** [haskell/cabal#8583]
I can not make an exe in windows of a cabal project. Simply.

I need a way to do it and/or the place where the proccess is described. And, if it could be, the method added in the docs, in chapter 3 in 'Package Concepts' for example, in order to anyone can find it in the future.

I repeat, I am using cabal and is the platform for that I am looking for the solution.

Thanks to you for read me. Regards.

**Comment by jneira** [comment]
Hi, thanks for opening the issue
Respect  the concrete part on how to make an executable i've just tried this:

```shell
PS D:\dev\ws\haskell\issues> mkdir make-exec-in-windows; cd make-exec-in-windows; cabal init -n; cabal install
.....

Wrote tarball sdist to
D:\dev\ws\haskell\issues\make-exec-in-windows\dist-newstyle\sdist\make-exec-in-windows-0.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - make-exec-in-windows-0.1.0.0 (exe:make-exec-in-windows) (requires build)
Configuring executable 'make-exec-in-windows' for make-exec-in-windows-0.1.0.0..
Preprocessing executable 'make-exec-in-windows' for make-exec-in-windows-0.1.0.0..
Building executable 'make-exec-in-windows' for make-exec-in-windows-0.1.0.0..
[1 of 1] Compiling Main             ( app\Main.hs, dist\build\make-exec-in-windows\make-exec-in-windows-tmp\Main.o )
Linking dist\build\make-exec-in-windows\make-exec-in-windows.exe ...
Installing executable make-exec-in-windows in D:\cabal\store\ghc-8.10.7\incoming\new-15896\cabal\store\ghc-8.10.7\make-exec-in-_-0.1.0.0-3b1449cd28e5310cfdf2f18efd03d440e484db5b\bin
Warning: The directory
Copying 'make-exec-in-windows.exe' to 'D:\bin\make-exec-in-windows.exe'

PS D:\dev\ws\haskell\issues\make-exec-in-windows> D:\bin\make-exec-in-windows.exe
Hello, Haskell!
```

I guess your issue is more about improving docs adding an specific section on how to make an executable.
I've found here: https://cabal.readthedocs.io/en/stable/developing-packages.html#building-the-package this paragraph:

```
If the package contains an executable, you can run it with:

cabal run

and the executable can also be installed for convenience:

cabal install

When installed, the executable program lands in a special directory for binaries that may or may not already be on your system’s PATH. If it is, the executable can be run by typing its filename on commandline.
```

That is the in the quickstart section, usually the first to be read. How do you think we could improve it?

**Comment by Jastxz** [comment]
Hello, thanks for ask my question.

I used the command and it works for me. Thanks again. My problem now is another but that's another story.

About the docs, yes, I think that the section about building the package, specifically the command 'cabal install', is not enough clear. The cause of my confusion is that usually I used the 'cabal install' command in order to install another support libraries for Haskell. Example: cabal install random. So, I think that if the line '_and the executable can also be installed for convenience:_' could be something like '_and you can create an executable of your package/project for convenience with the same command that is used for install other libraries/packages:_'. And maybe add another redundant message in order to clarify again that 'cabal install' can be used in both ways.

Thanks for read me and I hope this issue can help other people.

**Comment by Mikolaj** [comment]
Hi @Jastxz,

> I used the` 'cabal install' command in order to install another support libraries for Haskell. Example: cabal install random

You should normally not needs this (and it doesn't work). If a package needs `random`, it will build it itself (or take it from a cache). I hope this is documented.
