### ISSUE TITLE
Improve error message when the available version of GHC is too old

### ISSUE THREAD

**Issue by athas** [haskell/cabal#8606]
The (only?) way Cabal allows you to specify a minimum version of GHC is by putting a constraint on the `base` dependency.  There are also various ways to indicate compatibility with GHC versions, and these work quite well for Haskell programmers.  However, I have noticed that non-Haskell programmers have a hard time figuring out the meaning of these errors.  [Example](https://github.com/diku-dk/futhark/issues/1763)

I think Cabal should have some way of producing a better error message in that case.  I am aware that Cabal also supports non-GHC compilers - I have no opinion on those, or whether special support should also be included for them, but I don't think it should prevent a better error message for GHC.

As a strawman implementation suggestion, Cabal could simply print a customised message when the solver fails because the `base` constraint cannot be fulfilled.  The full message can still be printed, but perhaps suffixed with a "Hint: this program requires at least GHC x.y.z and you have GHC a.b.c installed".

**Comment by ulysses4ever** [comment]
This dups #7993 afaict

**Comment by athas** [comment]
Indeed!  I assumed it would already have been reported, but couldn't find anything by searching.

**Comment by ulysses4ever** [comment]
Indeed, find anything here is hard. It took me a moment to remember the right keywords (in this case it was template-haskell and stackoverflow.com)... 

Thank you anyway for reporting — it means that this issue is still important. Notice the pr-welcome label on the issue: we hope to get a hand with it!
