### ISSUE TITLE
Bootstrap file for GHC 9.4 on Linux

### ISSUE THREAD

**Issue by nmeum** [haskell/cabal#8613]
Apologizes if this is not the right place for this kind of discussion but looking at `bootstrap/` there doesn't seem to be a JSON configuration file for GHC 9.4 on Linux, is there any reason why GHC 9.4 isn't supported out-of-the-box by the bootstrap setup? I am aware that I can create my own bootstrap JSON file for 9.4 by following the instructions in `bootstrap/README.md` I was, however, wondering if there is any official "policy" regarding the addition of these bootstrap files to the Cabal repository.

**Comment by Mikolaj** [comment]
Hi @nmeum, this is a good place to discuss. We still don't have full CI coverage of GHC 9.4 (IIRC doctests are failing, but I don't remember the ticket), which makes 9.4 a bit of a second class citizen. Also, problems with github containers prevents us from using GHC > 9.4.2. However, now that 9.4 stabilised and our CI problems are more clearly not stemming from GHC defects, if anybody prepares a boostrap JSON file (for 9.4.2, I guess?) and adds it to CI, I think there is a high chance it would pass CI fine and it would be merged.
