### ISSUE TITLE
cabal init -n produces a cabal file with latest cabal-version

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal#8616]
**Describe the bug**

cabal init -n produces a cabal file with latest cabal-version. the default should be a slightly older version, same as the one suggested in `--interactive`

**To Reproduce**

```
$ mkdir mypkg
$ cd mypkg/
$ cabal init -n
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.8
[...]
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

Version 3.0 is used

**System information**

cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 

**Additional context**

cc @ptkato @emilypi

**Comment by emilypi** [comment]
I don't agree that this is a bug. It doesn't use the latest cabal version - it uses the version of cabal that's referenced in $PATH, which is a perfectly reasonable assumption to make about what spec we should be using when the cabal file isn't present. IMO the suggestion that we use a random stable cabal version is as arbitrary, and less maintainable; it requires more effort to bump consistently as cabal versions get released, and it does not mitigate the need for manually fixing up a cabal file once it's written. 

What we're *not* doing, which is a vital step that would be lovely to add, is to check the cabal version in the .cabal file (if present), and just use that. The heuristic doesn't capture that data.

**Comment by ulysses4ever** [comment]
I agree with Emily but I have a different reason (although, I also completely agree that the maintenance cost is real). I think anyone who uses `cabal init` to start something serious will be able to choose appropriate cabal-version. But 99% of the time (I feel) `cabal init` is used to quickly have something that can be build with cabal locally. In that case I don't see a reason to be cautious about `cabal-version`. Again, when and if that little something grow into something more ambitious, only then will be the time to consider what `cabal-version` makes more sense all things considered.

**Comment by emilypi** [comment]
Closing due to the previous 2 comments
