### ISSUE TITLE
Cabal 3.8 does not appear to track extra-source-file rebuilds correctly

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#8632]
**Describe the bug**

**To Reproduce**

It's large, but here's the reproducer: https://github.com/input-output-hk/plutus

```
cabal build plutus-core:plutus-core
# edit plutus-core/cost-model/data/builtinCostModel.json
cabal v2-build plutus-core:plutus-core
# observe no recompliation
```

**Expected behavior**

Since there is a file that depends on `plutus-core/cost-model/data/builtinCostModel.json` using `addDependentFile`, I would expect modifying it to trigger a rebuild.

**System information**
 - NixOS
 - cabal 3.8.1
 - ghc 9.2.4

**Additional context**

We've confirmed that this works on cabal 3.6.2, and not on 3.8.1. I've tried a few semi-random things to try and get cabal to notice the change:

- Move the file to the package root to avoid directory separators in the pattern.
- Remove all the other `extra-source-files`
- Explicitly add a call to `addDependentFile <path>` to the relevant module.
- Changing to use a wildcard match on the file extension
- Bumping the `cabal-version` of the cabal file
- Add the package directory to the `extra-source-file` path in case there was a CWD mixup and it was looking from the project root somehow.

None of these have worked.

**Comment by gbaz** [comment]
First I want to clear up a confusion. As far as I know, `addDependentFile` _never_ was tracked by cabal. What did happen was there was a patch (https://github.com/haskell/cabal/pull/6889) to add extra source files to cabal's rebuild tracking. I would very much like to figure out why that seems to no longer work. However, the reproducer is too hard for me to work with. In particular, I don't mind a huge package repository -- but I _do_ mind having to also enter a nix development shell that is rather huge on top of that, especially given that it seems to want to add a bunch of extra configurations to my existing nix config.

Is there any possibility for a reproducer that does not require also entering a nix shell? Perhaps @SamirTalwar can provide one from graphql?

**Comment by gbaz** [comment]
Additionally, can it be that this tracking works in a single cabal package, but it is the introduction of multiple packages in a joint cabal-project that breaks it?

**Comment by michaelpj** [comment]
Sorry not to have a smaller reproducer, I didn't have time to make one and I thought this was better than nothing :(

I could have tested your hypotheses out for you but it looks like you found it already, which is excellent, thank you!
