### ISSUE TITLE
Warning if a file glob doesn't match anything

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#8634]
As a user, if I've got a file glob that doesn't match anything, that almost certainly means I've made a mistake.

**Comment by ffaf1** [comment]
Mhhh this should already be there in `cabal check`:

https://github.com/haskell/cabal/blob/63b0f6fb449ed6573da8877015c2abfd39cb8486/Cabal/src/Distribution/PackageDescription/Check.hs#L2367-L2374

[This is the test](https://github.com/haskell/cabal/tree/master/cabal-testsuite/PackageTests/Check/NoGlobMatches) (added five years ago), added in #5403.

I am currently in the middle of a thorny rebase, an MRE would be quite welcome!
