### ISSUE TITLE
Failed to build Accelerate package with Cabal 3.8.1.0

### ISSUE THREAD

**Issue by npatsakula** [haskell/cabal#8635]
**Describe the bug**

Cabal silently stops building package after fetching git dependencies. Cabal 3.6.3.0 works well.

**To Reproduce**

```bash
# Clone accelerate repo:
git clone https://github.com/AccelerateHS/accelerate-llvm; cd accelerate-llvm
# Try build:
cabal v2-build -v -- all
```

**System information**

- Operating system: NixOS 22.11, OS X Ventura (Apple M1).
- Cabal version:
  ```
  cabal-install version 3.8.1.0
  compiled using version 3.8.1.0 of the Cabal library
  ```
- GHC version:
  ```
  The Glorious Glasgow Haskell Compilation System, version 8.10.7
  ```

**Comment by ulysses4ever** [comment]
Can you post the output of the build?

**Comment by npatsakula** [comment]
> Can you post the output of the build?

```text
[nix-shell:~/accelerate-llvm/accelerate-llvm-native]$ cabal build
HEAD is now at eda85a2 Use cxx-sources instead of c-sources in the Cabal file
Cleared directory 'cbits/tracy'
Submodule 'cbits/tracy' (https://github.com/wolfpld/tracy.git) unregistered for path 'cbits/tracy'
HEAD is now at a9cf26f4 cabal: -optcxx requires ghc-8.10
Submodule 'cbits/tracy' (https://github.com/wolfpld/tracy.git) registered for path 'cbits/tracy'
Cloning into '/home/pacakula/accelerate-llvm/dist-newstyle/src/accelerate-b2128c9b790cf0a6/cbits/tracy'...
Submodule path 'cbits/tracy': checked out '07778badcced109b8190805fbf2d7abfaef0d3b9'
Entering 'cbits/tracy'
```

**Comment by ulysses4ever** [comment]
@npatsakula thank you! This message doesn't indicate any error (please, correct me if I'm wrong). Are you sure it's all of it?

**Comment by npatsakula** [comment]
@ulysses4ever, yes, it doesn't.

Yes. I can provide verbose output as well.

```text
[nix-shell:~/accelerate-llvm/accelerate-llvm-native]$ cabal build -v 
Project settings changed, reconfiguring...
creating /home/pacakula/accelerate-llvm/dist-newstyle/cache
Compiler settings changed, reconfiguring...
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin/ghc --numeric-version
looking for tool ghc-pkg near compiler in
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin
found ghc-pkg in
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin/ghc-pkg-8.10.7
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin/ghc-pkg-8.10.7 --version
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin/ghc --supported-languages
/nix/store/aib25x608lph775p06qhzdpzkj7pl32h-ghc-8.10.7/bin/ghc --info
creating /home/pacakula/accelerate-llvm/dist-newstyle
creating /home/pacakula/accelerate-llvm/dist-newstyle/cache
/usr/bin/git --version
creating /home/pacakula/accelerate-llvm/dist-newstyle/src
/usr/bin/git fetch
/usr/bin/git submodule deinit --force --all
/usr/bin/git reset --hard eda85a2bbe362a0b89df5adce0cb65e4e755eac5 --
HEAD is now at eda85a2 Use cxx-sources instead of c-sources in the Cabal file
/usr/bin/git submodule sync --recursive
/usr/bin/git submodule update --force --init --recursive
/usr/bin/git submodule foreach --recursive 'git clean -ffxdq'
/usr/bin/git clean -ffxdq
creating /home/pacakula/accelerate-llvm/dist-newstyle/src
/usr/bin/git fetch
/usr/bin/git submodule deinit --force --all
Cleared directory 'cbits/tracy'
Submodule 'cbits/tracy' (https://github.com/wolfpld/tracy.git) unregistered for path 'cbits/tracy'
/usr/bin/git reset --hard a9cf26f40cea53042659cca7d509ae2acafd3857 --
HEAD is now at a9cf26f4 cabal: -optcxx requires ghc-8.10
/usr/bin/git submodule sync --recursive
/usr/bin/git submodule update --force --init --recursive
Submodule 'cbits/tracy' (https://github.com/wolfpld/tracy.git) registered for path 'cbits/tracy'
Cloning into '/home/pacakula/accelerate-llvm/dist-newstyle/src/accelerate-b2128c9b790cf0a6/cbits/tracy'...
Submodule path 'cbits/tracy': checked out '07778badcced109b8190805fbf2d7abfaef0d3b9'
/usr/bin/git submodule foreach --recursive 'git clean -ffxdq'
Entering 'cbits/tracy'
/usr/bin/git clean -ffxdq
bash -c '! git submodule update --init --recursive'

[nix-shell:~/accelerate-llvm/accelerate-llvm-native]$
```

**Comment by npatsakula** [comment]
Also I can provide NIX shell environment if that helps. Feel free to contact me here or by email at any time. I'll be glad to help:)

**Comment by ulysses4ever** [comment]
No need in Nix shell, thank you.

The reason it fails is [a strange hack applied in `accelerate-llvm`'s `cabal.project`][cp]:
```
source-repository-package
    type: git
    location: https://github.com/tmcdonell/accelerate.git
    tag: a9cf26f40cea53042659cca7d509ae2acafd3857
    -- Cabal builds from an sdist, and `accelerate.cabal` references files that
    -- don't exist on a fresh clone. Cabal 3.8.0.0 will do this automatically.
    --
    -- XXX: For some reason cabal just stops when the command returns 0? So
    --      negating this seems to 'work'
    post-checkout-command: bash -c "! git submodule update --init --recursive"
```

If you remove the `!` (or comment out the `post-checkout-command` altogether?), the build works fine.

My diagnosis of it is that it's not our bug. It seems to me that they had a workaround for an older cabal issue (that `post-checkout-command`). Cabal 3.8 seems to not have the issue anymore. But now their workaround makes the build fail. Remove workaround and that would be it. Potentially, create a separate `cabal.project` file to be used with cabal starting from 3.8.

Full disclosure, I'm no expert in `source-repository-package` feature, so I may be wrong.

[cp]: https://github.com/AccelerateHS/accelerate-llvm/blob/2cd65569c875477b5250d54f0d0738d8ee28e597/cabal.project#L5-L14

**Comment by robbert-vdh** [comment]
Yes, older Cabal versions had a bug where it would silently terminate the build if the `post-checkout-command` returned 0/success, but if it returned an error/1 it would treat that as a success. Perhaps Cabal just erroneously `toEnum`'d the integer return value to a boolean. And those same older versions didn't clone submodules. Which is why I had to add that workaround in the first place. So I guess this bug was fixed in 3.8 (the cabal.project file was initially written for Cabal 3.4), which now breaks backwards compatibility with older Cabal versions.

**Comment by Mikolaj** [comment]
If you don't depend on Cabal, there may not be an easy way. You could make the bash script check the version of cabal from PATH perhaps? Or something subtler (take the path of the running cabal process, etc.).

**Comment by ulysses4ever** [comment]
Should we close it as invalid due to the package in question relying on a Cabal bug that was fixed?

**Comment by npatsakula** [comment]
@ulysses4ever, I think so. Thanx!
