### ISSUE TITLE
Warning: "debug build with assertions" interferes with --numeric-version

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8645]
The warning printed by the `cabal` development version interferes with collecting output, e.g.
```sh
CABAL_VERSION=$(cabal --numeric-version)
```
will usually set `CABAL_VERSION` to something like `3.8.1.0`, but for the development version it is the warning-string followed by the version:
```console
$ echo $CABAL_VERSION
Warning: this is a debug build of cabal-install with assertions enabled. 3.9
```

The problem is that this warning is printed to `stdout` with `normal` verbosity:
https://github.com/haskell/cabal/blob/399cf6432df746b0b0d8e33a8b41736120552380/cabal-install/main/Main.hs#L192-L198

I think this warning should only be printed with increased verbosity, e.g. `-v2`.

What confuses me is that `-v0` does not seem to have any effect:
```
$ cabal -v0 --numeric-version
Warning: this is a debug build of cabal-install with assertions enabled.
3.9
```
I still see this well-meant but silly warning.

**Comment by Mikolaj** [comment]
I suppose normal verbosity is needed to help people avoid surprises. However, `-v0` should work, so it's worth investigating. Also, I think there is a ticket about printing warnings (and errors?) to stderr.

**Comment by andreasabel** [comment]
> Also, I think there is a ticket about printing warnings (and errors?) to stderr.

We have:
- https://github.com/haskell/cabal/issues/7790
- https://github.com/haskell/cabal/pull/4789
- https://github.com/haskell/cabal/pull/7838
- ...

This topic has a history...

> I suppose normal verbosity is needed to help people avoid surprises.

Why do we need this warning preemptively at all?  Couldn't we just add it as explanation if an actual assertion is thrown? In >99% of my invocations of `cabal`, this message is just spamming me.

I'd think the best path of action here (if we want to avoid the thickets of stdout vs stderr) is to remove the warning and only utter it when an assertion failed.

**Comment by Mikolaj** [comment]
Some history:

https://github.com/haskell/cabal/pull/8240
https://github.com/haskell/cabal/pull/8396

**Comment by andreasabel** [comment]
Ok, to not start a revolution, I submitted a modest PR that shifts the warning to `stderr` and restricts it to normal operation of `cabal`, i.e. not in special commands such as `help` and `version`:
- #8647

**Comment by ulysses4ever** [comment]
I like the idea of printing it only when an assertion actually fails.

**Comment by grayjay** [comment]
> I like the idea of printing it only when an assertion actually fails.

I think that the main purpose of the warning is to warn about decreased performance.

**Comment by andreasabel** [comment]
@grayjay wrote:
> I think that the main purpose of the warning is to warn about decreased performance.

Digging the history I saw that once this warning had some text about decreased performance.  Do you know why this part was dropped?

**Comment by gbaz** [comment]
Just as a historical note, there was certainly a case I found at some point where we were shipping binaries that accidentally had assertions on, leading to vastly decreased solver performance.

**Comment by grayjay** [comment]
> Digging the history I saw that once this warning had some text about decreased performance. Do you know why this part was dropped?

Which warning mentioned decreased performance? Are you referring to the expensive assertions mentioned in #8240? They were only enabled with a custom build flag, so they were not easy to enable unintentionally.

**Comment by andreasabel** [comment]
@grayjay:  Ah, it was in a PR that didn't get merged as such:
- #4552
