### ISSUE TITLE
'cabal check' warns that 'ghc-options: -main-is' is not portable

### ISSUE THREAD

**Issue by sergv** [haskell/cabal#8646]
## Summary

When a package has an executable, test suite, or benchmark where main module has a name distinct from `Main` the `-main-is` flag should be passed to GHC to tell it how the main module is called. However `cabal check` complains about this with following error message

```
Warning: These warnings may cause trouble when distributing the package:
Warning: 'ghc-options: -main-is' is not portable.
```

My question is why is it not portable? The flag is specific to GHC yet it's listed under `ghc-options` field which should theoretically make any alternative Haskell compilers ignore it. Practically there's, on the one hand, pretty few alternative Haskell compilers to go around and on the other hand even if one manages to find such a compiler there's whole lots of non-portable things a package could do (e.g. use `import GHC.Exts` or use extensions)  that said compiler will probably not support and are hence are not portable as well. It feels strange to issue non-portability warning specifically for a command-line flag which has been around for quite a while.

Perhaps the warning about `-main-is` flag should be removed?

Little investigation revealed that warning was added in commit `39c03860055116afa365cc5e6610f85b4e4116df` in 2008. No specific justification for checking `-main-is` was mentioned.

At the time the warning probably made sense but now, in my opinion, any realistic altervative Haskell will most likely have to strive to be compatible with GHC in terms of flags to have any chance of getting traction.

## Steps to reproduce

Sample inputs that make `cabal check` produce the warning above:
`test.cabal`
```
cabal-version: 3.0

name: test
version: 0.1
build-type: Simple
category: Test
maintainer: Joe
synopsis: Input to 'cabal check'
description: Input to 'cabal check'.
license: BSD-3-Clause

executable test
  main-is: ExeMain.hs
  build-depends: base > 4 && < 5
  default-language: Haskell2010
  ghc-options: -main-is ExeMain
```

`ExeMain.hs`
```haskell
module ExeMain (main) where

main :: IO ()
main = putStrLn "Hello, world"
```

**Comment by ffaf1** [comment]
GHC `-main-is` and cabal `main-is:` with similar but different semantics, really unfortunate.

Thanks for the thorough report, MRE and git sleuthing @sergv, really appreciated.
- [Relevant documentation](https://downloads.haskell.org/~ghc/9.4.4/docs/users_guide/phases.html?highlight=main#ghc-flag--main-is%20%E2%9F%A8thing%E2%9F%A9).
- Commit: 39c03860055116afa365cc5e6610f85b4e4116df. (“Check for lots of insane ghc-options that people have used in real packages.”)
- Related: #172.

I don’t know how feelings have changed regarding compiler portability, but regardless this seems suspicious, right?

> Strictly speaking, `-main-is` is not a link-phase flag at all; it has no effect on the link step. The flag must be specified when compiling the module containing the specified main function (e.g. module A in the latter two items above). It has no effect for other modules, and hence can safely be given to ghc --make. However, if all the modules are otherwise up to date, you may need to force recompilation both of the module where the new “main” is, and of the module where the “main” function used to be; ghc is not clever enough to figure out that they both need recompiling. You can force recompilation by removing the object file, or by using the [-fforce-recomp](https://downloads.haskell.org/~ghc/9.4.4/docs/users_guide/separate_compilation.html#ghc-flag--fforce-recomp) flag.

If `-main-is` breaks standard cabal workflow (i.e. the user needs to remove object files or pass `-fforce-recomp` now and then), `cabal check` should output something, am I wrong?

**Comment by sergv** [comment]
@ffaf1 thanks for quick turnaround.

> If -main-is breaks standard cabal workflow (i.e. the user needs to remove object files or pass -fforce-recomp now and then), cabal check should output something, am I wrong?

I'm reading the bit from GHC manual about interaction with recompilation as the scenario where modules were first compiled with e.g. `-main-is Foo.bar` and later a recompilation is attempted with `-main-is Quux.frob` without touching any modules so GHC is not be able to figure out which object files need to be updated. But since this scenario implies changing GHC command line, cabal can know about it and remove stale object files or something.

I'm not 100% clear on the intended purpose of `cabal check` but as far as I can judge from its behaviour it's, at least partly, aimed at ensuring that package will interact well with Hackage. E.g. it checks that `base` has upper bound, that various fields like `license` and `category` are specified, etc. From that perspective it's not clear whether cabal should care about `-main-is`.

**Comment by ffaf1** [comment]
> I'm not 100% clear on the intended purpose of cabal check but as far as I can judge from its behaviour it's, at least partly, aimed at ensuring that package will interact well with Hackage. […] From that perspective it's not clear whether cabal should care about -main-is.

The mission is to keep Hackage happy, yes; by doing that we are sure the package plays well with package *users*. A look at the documentation of the datatype might make things clearer:

https://github.com/haskell/cabal/blob/399cf6432df746b0b0d8e33a8b41736120552380/Cabal/src/Distribution/PackageDescription/Check.hs#L774-L808

Now, where does `-main-is` stand?

I disagree with the commit message, `ghc-options: -main-is` is *not* insane, it is quite reasonable actually. But I think it could well fall into `PackageDistSuspicious` or `PackageDistSuspiciousWarn` buckets (“annoying or detrimental”), given the option documentation.

> I'm reading the bit from GHC manual about interaction with recompilation as the scenario where modules were first compiled with e.g. -main-is Foo.bar and later a recompilation is attempted with -main-is Quux.frob without touching any modules so GHC is not be able to figure out which object files need to be updated. But since this scenario implies changing GHC command line, cabal can know about it and remove stale object files or something.

If this is something cabal does already, there is no problem and the warning should be removed. If not, let me investigate:
- what is the current consensus on “non portable” (i.e., non GHC) stuff is.
- in which ways `-main-is` could turn to be surprising or annoying to cabal users.

Input welcome by everyone on both points!

**Comment by ulysses4ever** [comment]
I agree with OP that's it's weird to single out that particular flag. If cabal-check doesn't warn about other ghc-options, this warning really should go too.

A middle-ground option would be to hide this warning behind a cabal-check flag (--warn-compiler-compat or something).

**Comment by sergv** [comment]
> in which ways -main-is could turn to be surprising or annoying to cabal users.

I'd add to this regarding how `-main-is` could be useful to cabal users, which is my case.

For executable-like things, like plain exeturables, tests and benchmarks, the package author designates haskell file out of which they're built. In the most simple case of package having one executable its main module can be named `Main` and put into `Main.hs` file.

But when there's several of such executable-like entities then I feel like naming them all as `Main.hs` is a bad idea so I give the files  different names like `TestMain.hs`, `RegressionTest.hs`, `AuxBenchmarks.hs`, etc. Next each of those files is a regular Haskell module, so I tend to put module declaration in them (`module Foo (...) where`). Typically Haskel modules are named the same as the files they reside in, but when I add module declaration like `module TestMain (main) where` for my tests the ghc is not able to find the executable entry point so `-main-is` becomes required in this case. With cabal complaining about said `-main-is` flag I'm left to either 1. ignore the warning or, 2. work around it by either not introducing module declarations in otherwise perfectly valid Haskell modules or 3. by making all module declarations state that module name is `Main` across all the executables.

**Comment by ffaf1** [comment]
I am convinced.

@sergv would you like to try to produce a patch yourself that removes the check?

**Comment by sergv** [comment]
@ffaf1 thanks, I've created a PR removing the check #8651.
