### ISSUE TITLE
Release Cabal-3.8.1.1 and revise cabal-install-3.8.1.0

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8653]
Background:
- #8554
- #8342 

`Cabal-3.8.1.0` has an unfortunate dependency on `process >= 1.6.14`(released 2022) which belongs to `cabal-install`, actually.  This is already fixed on `3.8` in #8342, and I suggest a patch release to fix #8554.  The plan is:
1. Release `Cabal-3.8.1.1` from `3.8` branch.
2. Release `cabal-install-3.8.1.1` from `3.8` branch, with dependency on `Cabal >= 3.8.1.1`.
3. Revise `cabal-install-3.8.1.0` on Hackage, fixing the dependency to `Cabal==3.8.1.0` (otherwise, it might get built with `Cabal-3.8.1.1` which does not have said `process` dependency needed for `cabal-install`).

The idea is that of a very light-weight release, _only_ fixing the `.cabal` files of these two packages.

Tasks:
- [ ] Changes to `Cabal.cabal` and `cabal-install.cabal` on `3.8`
- [ ] Changelog entries for the 3.8.1.1 packages on branch `3.8`
- [ ] Upload hackage candidates
- [ ] Wait for feedback
- [ ] Publish to hackage
- [ ] Tag `3.8` branch with `Cabal-v3.8.1.0` and `cabal-install-v3.8.1.0`

**Comment by mouse07410** [comment]
Yes!

**Comment by ulysses4ever** [comment]
These two points:

> Release cabal-install-3.8.1.1 from 3.8 branch

> The idea is that of a very light-weight release, only fixing the .cabal files of these two packages.

contradict, I think, because the 3.8 branch probably has a good deal more. That said, it should have only benign stuff, so I'd say go for it…

**Comment by andreasabel** [comment]
@ulysses4ever wrote:
> contradict, I think, because the 3.8 branch probably has a good deal more.

Oops, thanks for the alert!
I'd think that in this case `cabal-install-3.8.1.1` would maybe not be the correct version?
Anyway, this is a shoe size bigger than I anticipated.

Maybe we can scale this down and still get a meaningful result. Just do now:
a. Release `Cabal-3.8.1.1` as just `Cabal-3.8.1.0` with accepted dependency bumps and the `process-1.6.14` dependency lifted.
b. Revise `cabal-install-3.8.1.0` to depend on `Cabal == 3.8.1.0`.

**Comment by andreabedini** [comment]
Looping myself in as we just run into this with [input-output-hk/cardano-wallet](https://github.com/input-output-hk/cardano-wallet). `doctest` and `PyF` bring in the ghc dependency and cabal blissfully puts a recompiled GHC-8.10.7 in the plan. Pinning process to `1.6.13.2` when using GHC-8.10.7 at the project level seems solve the problem for us.

**Comment by andreasabel** [comment]
Cabal developer meeting discussion 2023-02-23 came up with the following plan:
- branch off the `v3.8.1.0` tag and make a PR with the following changes:
- relax the tight `process` constraint in `Cabal-3.8.1.0` to render it non-limiting
- tighten the `process` constraint in `cabal-install-3.8.1.0` to achieve the limiting effect directly
- both can be published in revisions
- the PR is to leave a "paper trail" and enable discussion

**Comment by andreasabel** [comment]
Branch: https://github.com/haskell/cabal/compare/cabal-install-v3.8.1.0...move-process-constraint?expand=1

**Comment by andreasabel** [comment]
Revisions done.  This should be fixed (fingers crossed).
