### ISSUE TITLE
Documentation inaccurately claims that `--prefer-oldest` is supported since v3.8

### ISSUE THREAD

**Issue by sjakobi** [haskell/cabal#8656]
See https://cabal.readthedocs.io/en/latest/cabal-project.html#cfg-field-prefer-oldest.

`cabal-install-3.8.1.0` does not support this flag.

**Comment by ffaf1** [comment]
#8261 

@sjakobi If you feel like it, submit a PR, otherwise I will do it.

**Comment by ysangkok** [comment]
@ffaf1 What is the proposed fix? Just to say "Cabal 3.10" instead of "Cabal 3.8"?

**Comment by ffaf1** [comment]
Yes, no intention to backport or anything. Since nobody did, let me submit a quick PR myself.
