### ISSUE TITLE
Install rsync on hackage.haskell.org

### ISSUE THREAD

**Issue by bos** [haskell/cabal#868]
(Imported from [Trac #878](http://hackage.haskell.org/trac/hackage/ticket/878), reported by guest on 2011-08-26)

I keep a local copy of the HackageDB, which I construct by downloading archive.tar and 00-index.tar.gz on occasion.  This is kind of wasteful of bandwidth for me and the hackage.haskell.org server.

My proposed solution is to install rsync on hackage.haskell.org in daemon mode, and configure it to serve the HaskellDB archive (or archive.tar and 00-index.tar.gz).  This would allow users to download only the differences between their local copy and the official repository's copy.

[http://everythinglinux.org/rsync/](http://everythinglinux.org/rsync/) contains a sample rsync daemon configuration.  It looks relatively straight forward to set up.

Also, I would suggest that the front page's "Getting the Raw Data" section should contain a sample rsync command line invocation users can use to differentially mirror the archive.

**Comment by ttuegel** [comment]
This is not a Cabal issue, and also seems to have been resolved.
