### ISSUE TITLE
cabal init should not suggest Cabal < 2.0

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#8680]
https://github.com/haskell/cabal/blob/e714824c6e652bf894f914bc57feccc15759668a/cabal-install/src/Distribution/Client/Init/Interactive/Command.hs#L287-L295

With the latest update to Hackage any Cabal release prior to 2.0 stopped working, so there is probably no point to suggest users to set `cabal-version` of their packages to anything less than 2.0: it no longer provides any tangible better compatibility / support window. I suggest to offer less choices to users (especially new) and rewrite this as

```haskell
 displayCabalVersion :: CabalSpecVersion -> String 
 displayCabalVersion v = case v of 
   CabalSpecV2_0  -> "2.0   (best backward compatibility)" 
   CabalSpecV2_2  -> "2.2   (+ support for 'common', 'elif', redundant commas, SPDX)" 
   CabalSpecV2_4  -> "2.4   (+ support for '**' globbing)" 
   CabalSpecV3_0  -> "3.0   (+ set notation for ==, common stanzas in ifs, more redundant commas, better pkgconfig-depends)" 
   CabalSpecV3_4  -> "3.4   (+ sublibraries in 'mixins', optional 'default-language')" 
   _ -> showCabalSpecVersion v 
```

**Comment by BasLaa** [comment]
Hi,
This seems like a very quick fix, and I'd like to get a feel for contributing to cabal, so I'll get on this tomorrow.

**Comment by Mikolaj** [comment]
@BasLaa: go for it and make sure to ask questions here and/or on `#hackage` whenever stuck.

**Comment by Mikolaj** [comment]
@BasLaa: well done! Thank you.
