### ISSUE TITLE
cabal 3.8.1.0 build fails with sphinx 6.1.3

### ISSUE THREAD

**Issue by essandess** [haskell/cabal#8681]
**Describe the bug**

`cabal` 3.8.1.0 build fails with `sphinx` 6.1.3

References:
* https://trac.macports.org/ticket/66680#comment:13
* https://github.com/sphinx-doc/sphinx/issues/11094

This issue is fixed with this [patch](https://trac.macports.org/attachment/ticket/66680/patch-doc_conf_py.diff).

Error:
```
:debug:build system -W /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_cabal/cabal/work/cabal-install-3.8.1.0: sphinx-build-3.10 -n --keep-going -E doc /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_cabal/cabal/work/dist/doc/users-guide
:info:build Running Sphinx v6.1.3
:info:build making output directory... done
:info:build building [mo]: targets for 0 po files that are out of date
:info:build writing output... 
:info:build building [html]: targets for 18 source files that are out of date
:info:build updating environment: [new config] 18 added, 0 changed, 0 removed
:info:build reading sources... [  5%] bugs-and-stability
:info:build reading sources... [ 11%] buildinfo-fields-reference
:info:build reading sources... [ 16%] cabal-commands
:info:build reading sources... [ 22%] cabal-config-and-commands
:info:build reading sources... [ 27%] cabal-package
:info:build Exception occurred:
:info:build   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinx/ext/extlinks.py", line 103, in role
:info:build     title = caption % part
:info:build TypeError: not all arguments converted during string formatting
```

**To Reproduce**

```
$ cabal v2-build ...
sphinx-build-3.10 -n --keep-going -E doc
…
```

**Expected behavior**

Successful build.

* Cabal 3.8.1.0
* GHC version used: 9.4.4
* Sphinx 6.1.3
* Operating System: macOS 12.5 21G72; Xcode 13.4.1 13F100
* System Architecture: x86_64

**Comment by Mikolaj** [comment]
Thank you for that. So what's the root cause? Bad python code in our script or changed Python version or changed sphinx API?

**Comment by andreasabel** [comment]
Currently the doc building is pinned to `Sphinx-5.0.1`: https://github.com/haskell/cabal/blob/55d6f3213344d4572f32a0eb7367d282c68fa743/doc/requirements.txt#L50-L58

We could of course migrate to `Sphinx-6`, this just has not happened yet.

**Comment by andreasabel** [comment]
I experimented with bumping the dependencies, but it seems like the latest `sphinx-rtd-theme` (1.1.1) does not support Sphinx-6 yet.  So, it looks like we are up-to-date.

@essandess: The linked patch would not apply to `master`, since I already fixed this issue there.

I am not familiar with how external distributors package `cabal`, e.g. where they get the sources from, and where they would expect his problem to be fixed.  Must be more than our Hackage-published artefacts, because AFAIK we do not include the docs there; we publish them to `readthedocs.org`.  But as I said, I am not very knowledgeable here...

**Comment by essandess** [comment]
We build and install specific version-controlled releases. For cabal 3.8.1.0, these are from the release at https://downloads.haskell.org/~cabal/cabal-install-3.8.1.0/.

If this issue has already been fixed, then thank you, and I suggest that the issue be closed.

**Comment by andreasabel** [comment]
Ok, thanks, Steve @essandess.
