### ISSUE TITLE
source link broken for some Prelude types in online documentation

### ISSUE THREAD

**Issue by bos** [haskell/cabal#869]
(Imported from [Trac #879](http://hackage.haskell.org/trac/hackage/ticket/879), reported by mlinksva on 2011-08-28)

[http://hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html) links to [http://hackage.haskell.org/packages/archive/base/latest/doc/ghc-prim-0.2.0.0/src/GHC-Types.html](http://hackage.haskell.org/packages/archive/base/latest/doc/ghc-prim-0.2.0.0/src/GHC-Types.html) and [http://hackage.haskell.org/packages/archive/base/latest/doc/integer-gmp-0.2.0.3/src/GHC-Integer-Type.html](http://hackage.haskell.org/packages/archive/base/latest/doc/integer-gmp-0.2.0.3/src/GHC-Integer-Type.html) and [http://hackage.haskell.org/packages/archive/base/latest/doc/ghc-prim-0.2.0.0/src/GHC-Bool.html](http://hackage.haskell.org/packages/archive/base/latest/doc/ghc-prim-0.2.0.0/src/GHC-Bool.html) which obtain 404s.

Apologies if reporting bug in wrong place.

**Comment by ttuegel** [comment]
This is not a Cabal issue.
