### ISSUE TITLE
Don't generate C-comments: /* ... */ in cabal_macros.h

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#8711]
These relies on C preprocessor stripping them. However, if people use `cpphs`, it won't by default. And there is a good reason,

`//`, `/*` and `*/` are valid Haskell operators!

AFAICT we don't get much benefit from these comments as humans barely ever look at `cabal_macros.h`.

**Comment by phadej** [comment]
I'm not aware of any instance in the wild. But by default `cpphs` doesn't strip C-style comments, so that's one reason no-one uses `cpphs` as C preprocessor. (There are other incompatibilities as well). Of course one can tell `cpphs` to strip C comments, but that removes one benefit of using `cpphs`.

One reason to use `cpphs` (or some C-like preprocessor tailored for Haskell needs), is that we won't need to do stuff like:

```haskell
infix 2 -*-
infix 3 /\ -- backslashes at EOL interact badly with CPP...
```

Try to [guess which packages that is in](https://hackage-search.serokell.io/?q=%5C%5C+--.*%24)

**Comment by andreasabel** [comment]
Just from a high-level perspective, if my tooling cannot handle C-style comments in C-files, then maybe the best solution isn't to forbid writing comments, but to fix the tooling.

At least this initial warning is valuable and should be kept:
```c
/* DO NOT EDIT: This file is automatically generated by Cabal */
```

**Comment by phadej** [comment]
Whatever.
