### ISSUE TITLE
Single command to figure out ghc[i] options needed to compile a single file

### ISSUE THREAD

**Issue by bos** [haskell/cabal#873]
(Imported from [Trac #883](http://hackage.haskell.org/trac/hackage/ticket/883), reported by barsoap on 2011-09-15)

I'm thinking of a <tt>cabal options &lt;file.hs&gt;</tt> command that
1. locates the proper .cabal file for &lt;file.hs&gt;
2. parses that .cabal
3. outputs all options necessary to compile that file as cabal build would do it, that is, <tt>-isrc -idist/build/autogen (-Xwhatever)\* -hide-all-packages (-package-id whatever)*</tt>

There's already cabal-ghci on hackage which has one half of the equation, but packages are missing. (which happen to be available via grep and sed from cabal_macros.h...)

Needing those options comes up when e.g. working with vim's haskellmode on a cabal project: Most if not all cabal projects' files just fail to compile with default options. Having such a command would give a bullet-proof, non-hackish and low-tech way to integrate cabal with any such IDE tool.

(Do note that just building with cabal isn't enough, while haskellmode can parse the resulting warnings and errors, it doesn't stand a chance to figure out types, among other things, that way)

**Comment by fgaz** [comment]
We now have `cabal repl`, and `--write-environment-file` for direct ghc(i) invocations
