### ISSUE TITLE
`cabal build --offline` tries to access the network anyway

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#8752]
## Context

The [Haskell Playground](https://play-haskell.tomsmeding.com/) is in the process of being officially endorsed by haskell.org, and as such some changes are being made to it. In this case, it's the ability to offer packages other than the GHC boot libraries.

## Problem

The sandboxed environment in which the playground runners are is isolated from the network, and it has been discovered by @tomsmeding that `cabal build --offline` tries to perform network access despite the flag.

## Expected behaviour

cabal-install should fail with an informative message if it cannot locate the required packages *and* cannot use the network to fetch them. 

---

Reproducer:

network.cabal
```cabal
cabal-version:       >=1.10
name:                test
version:             0.0.1.0
build-type:          Simple

executable test
  main-is:
    Main.hs
  build-depends:
    base, acme-dont           -- this needs to contain packages that you need to download, substitute others if you have acme-dont already (madlad)
  hs-source-dirs:      .
  default-language:    Haskell2010
  ghc-options:         -Wall -O1
```

Main.hs
```haskell
module Main where
main = return ()
```

Commands
```bash
# This uses bwrap: https://github.com/containers/bubblewrap
# to cut cabal off the network.

$ bwrap --unshare-net --bind / / /bin/bash
[tom@arrow network]$ cabal build --offline
Resolving dependencies...
Build profile: -w ghc-9.2.4 -O1
In order, the following will be built (use -v for more details):
 - acme-dont-1.2 (lib) (requires download & build)
 - test-0.0.1.0 (exe:test) (first run)
Downloading  acme-dont-1.2
Error: cabal: Failed to download acme-dont-1.2 (which is required by exe:test
from test-0.0.1.0). The exception was:
dieVerbatim: user error (Error: cabal: '/usr/bin/curl' exited with an error:
curl: (7) Couldn't connect to server
)
```

**Comment by michaelpj** [comment]
dupe? https://github.com/haskell/cabal/issues/5346

**Comment by Kleidukos** [comment]
And I had completely forgotten about #8676
