### ISSUE TITLE
Document that `extra-source-files` trigger a rebuild

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8756]
I seem to have experienced that modifying a file listed in `extra-source-files` triggers a rebuild.  If this is the case, this should be documented here:
https://github.com/haskell/cabal/blob/78be2d51faf70f84d30e660af367c25ac23ed1c8/doc/cabal-package.rst?plain=1#L775-L787
Note that `extra-doc-files` documents that `cabal haddock` will consider and process them.

One question I have in this context: what about files that should neither affect the cabal build (`extra-source-files`) nor the documentation (`extra-doc-files`), nor are they needed at runtime (`data-files`), but I still want them in the sdist tarball (so that they are available after `cabal get`)?  I am thinking about `stack*.yaml` files or `Makefile`s that present alternative ways of building the package. https://github.com/agda/agda/blob/ede697e9a0bf12acd5c8e871581d77aba99bdb58/Agda.cabal#L87-L93

**Comment by Mikolaj** [comment]
I put them in `extra-doc-files`, but that's probably an abuse. However, yet another field seems a burden on the user. What's the downside of using  `extra-doc-files`? With `documentation: True` does it rebuild haddocks each time I run `cabal build` and modify such a file?

**Comment by andreasabel** [comment]
So the context is this issue:
- https://github.com/agda/agda/issues/6502

I managed to break the github "pages build and deploy" workflow by moving `release-notes/*.md` files from `extra-source-files` to `extra-doc-files`.  These were now suddenly part of the `html` directory created by `cabal haddock`, and Jekyll choked because they contain example of Agda's beautiful instance arguments `{{ ... }}` which Jekyll tried interpret as templates of some sort.

Yeah, the world is deeply connected!  

This is why I am asking for a "neutral" location like `extra-files` (or `extra-dist-files`) which cabal will include in the sdist tarball but that's it---no further influence on cabal's behavior.
