### ISSUE TITLE
`cabal init` should suggest a default license

### ISSUE THREAD

**Issue by ffaf1** [haskell/cabal#8757]
**Describe the bug**

`cabal init` does not have a default license in its interactive menu. 

**To Reproduce**

Type `cabal init`, select options until you arrive at the license part, press Enter.

```
Please choose a license:
   1) BSD-2-Clause
   2) BSD-3-Clause
   3) Apache-2.0
   4) MIT
  ⁝
  14) LGPL-2.1-or-later
  15) LGPL-3.0-or-later
  16) AGPL-3.0-or-later
  17) Other (specify)
Your choice? ⏎
Empty input is not a valid choice.
```

**Expected behavior**
`cabal` to pick a license for me. I am partial to copyleft ones, but even MIT (permissive) would be better than “no default”.

`cabal` 3.9

**Comment by Mikolaj** [comment]
I'm prefer GNU GPL as well, but I think the majority of Haskell packages, including most of major tools, is under BSD-3-Clause, so we should follow that even only out of the "least surprise" principle.
