### ISSUE TITLE
when installing globally, cabal shouldn't use umask, should set mods to 755 or 644

### ISSUE THREAD

**Issue by bos** [haskell/cabal#876]
(Imported from [Trac #886](http://hackage.haskell.org/trac/hackage/ticket/886), reported by alistra on 2011-09-18)

I have an umask 077 on my root user, but when i type:
cabal install --global pkg
or I have a global setting in my configuration file, cabal installs the package globally, but with root's umask.

cabal is a package manager and if I install a package globally, I expect it to be accessible globally.

**Comment by jsl** [comment]
I just tested this and it seems this problem has been resolved, so I propose closing this ticket. If you are still having problems with this issue, please re-open or create a new issue.

My console output is long so I won't paste the whole thing, but basically sudo'ing to root, setting umask 077, installing a package and then loading ghci works fine with Ubuntu 14.04, ghc 7.6.3, cabal 1.16.0.
