### ISSUE TITLE
Elaboration on duplicate module support

### ISSUE THREAD

**Issue by BurningWitness** [haskell/cabal#8771]
Over the past two months I've been figuring out how to write bindings to the Vulkan API and I've ended up with the following monstrocity of a Cabal file: [vulkan-raw.cabal](https://github.com/BurningWitness/vulkan/blob/9de1d293e00326417e25a9ea8cace56a62214128/vulkan-raw/vulkan-raw.cabal). Roughly 350 flags for every extension, all pulling bits and pieces from a shared pool of definitions; any combination of flags enabled should be valid and leaving some modules hanging when removing extensions won't lead to an error.

Structuring the library this way means the compilation times are way lower (down to ~45 seconds on my machine from the original 5 minutes) and it can be run on a much wider set of API versions (Vulkan does not guarantee API compatibility neither forwards, nor backwards, [described here](https://github.com/KhronosGroup/Vulkan-Docs/issues/580#issuecomment-334950292)).

This works fine under Cabal 3.6.2.0, but 3.8.1.0 denies it with `Duplicate modules in library`, I assume this was introduced with [#7966](https://github.com/haskell/cabal/pull/7966).

From the point of view of Cabal (and Hackage) design, is what I'm trying to do here actually incorrect or is this simply an insanely rare sidecase not accounted for? In the former case I need to restructure the library; in the latter the library is fine, but is incompatible with a few Cabal versions and probably Hackage.

**Comment by gbaz** [comment]
I think the chronology is off here. The offending PR was likely https://github.com/haskell/cabal/pull/7616, and the bug you're running into was https://github.com/haskell/cabal/issues/7776. The PR you link, https://github.com/haskell/cabal/pull/7966, should _resolve_ that bug, but I think it did not make it into Cabal 3.8.1.0. I _think_ this will be resolved in current head, or the pre-release of cabal 3.10 that is available for testing from ghcup.

**Comment by BurningWitness** [comment]
@gbaz You are indeed correct. I will proceed with my current design then and I'll check it under Cabal 3.10 as soon as it lands.

**Comment by ffaf1** [comment]
Mind that you do have duplicated modules in your `.cabal` file. E.g. `Vulkan.Types.Enum.VkAttachmentDescriptionFlags` is present in a top-level section (not under any user flags) and inside an `if` branch. That is an error and Hackage would refuse upload.

**Comment by BurningWitness** [comment]
@ffaf1 I've changed my code to remove any such module mentions and now 3.8.1.0 only complains about duplicates within if sections (which I assume is valid for Hackage and will be fixed in a later Cabal version), thanks.
