### ISSUE TITLE
runTests deprecated message should be more helpful

### ISSUE THREAD

**Issue by bos** [haskell/cabal#878]
(Imported from [Trac #888](http://hackage.haskell.org/trac/hackage/ticket/888), reported by dsfox on 2011-09-27)

It would be great if this message explained what the new testing interface was, where to find it, and optimally how to quickly create something more or less equivalent to the runTests function so we can get on with our lives.  :)

Warning: In the use of `runTests'

<blockquote>
(imported from Distribution.Simple, but defined in Distribution.Simple.`UserHooks?`):
Deprecated: "Please use the new testing interface instead!"

</blockquote>

**Comment by jsl** [comment]
Based on the comments in this issue it seems to be resolved, so I propose closing. Please open a new issue if this is still something that needs to be addressed.
