### ISSUE TITLE
Docs say config (same format as cabal.project) but is it?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#8782]
**Describe the bug**
The docs say that `dist-newstyle/cache/config` is in the same format as `cabal.project` but it doesn't read like that.

> ## config (same format as cabal.project)
> The full project configuration, merged from cabal.project (and friends) as well as the command line arguments.
SOURCE: [Quickstart | Caching](https://github.com/haskell/cabal/blob/master/doc/nix-local-build.rst#caching)

**To Reproduce**
Clone this repo, run the command below and then open `dist-newstyle/cache/config`. The docs suggest this file is a project that is the result of merging the project and friends and command line args[^1] but it doesn't read like plain text.

[^1]: Aren't there some args that cannot be supplied as project options such as [--builddir](https://cabal.readthedocs.io/en/stable/cabal-project.html#cmdoption-builddir)? How do they get merged into config?

```
$ cabal build all --ghc-options="-Werror" --keep-going --dry-run
```

![image](https://user-images.githubusercontent.com/633283/219947238-2f0d89bd-caa0-4c76-89d8-78799079f7a8.png)

**Expected behavior**
I would really like if this config file was human-readable plain-text in the `cabal.project` format as it would help track how the combination of inputs are merged.

**System information**
 - Ubuntu 22.04.1 LTS

```
$ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.5
```

**Comment by ffaf1** [comment]
commit: 0c541a3aa98c3f056c2baf8206f23e58147f5f0f pr: #3727

2016, maybe at the time it was true, for sure not now.

**Comment by ulysses4ever** [comment]
Only it does not say “same format” anywhere. “Merged” doesn’t necessarily mean it’s a mere concatenation.

That said, adding a word or two clarifying that it’s an internal binary format would probably make sense.

**Comment by ffaf1** [comment]
![image](https://user-images.githubusercontent.com/87714215/219952378-a54fd902-0d6a-4763-a391-1c83b7fb2f40.png)

It does in the header. If it is an internal binary format, user-facing documentation should just say “binary”, am I wrong?

**Comment by ulysses4ever** [comment]
Oh, I stand corrected, thank you @ffaf1! I'd say "internal binary format" perhaps, but that's up for bikeshedding.
