### ISSUE TITLE
Add option to list recursive dependencies of a package along with their licenses

### ISSUE THREAD

**Issue by bos** [haskell/cabal#879]
(Imported from [Trac #889](http://hackage.haskell.org/trac/hackage/ticket/889), reported by joeyadams on 2011-09-27)

It should be possible to list all of the dependencies of a package, including their licenses.  This would be useful for:

<ul><li>Developers writing proprietary applications.
</li></ul><ul><li>Developers who don't want their liberally-licensed libraries to be "upgraded" to the GPL or similar by subtle dependencies.
</li></ul>Attached is a simple patch that makes cabal-install list this information when the verbosity level is 2 or higher.  Sample usage:

<pre class="wiki">$ cabal install --verbose=2 --dry-run gnutls
Reading available packages...
Resolving dependencies...
base         BSD3
bytestring   BSD3
ffi          BSD3
ghc-prim     BSD3
gnutls       GPL (Just (Version {versionBranch = [3], versionTags = []}))
integer-gmp  BSD3
monads-tf    BSD3
rts          BSD3
transformers BSD3
In order, the following would be installed:
monads-tf-0.1.0.0 (new package)
gnutls-0.1 (new package)
</pre>This is a quick hack, as I am not familiar with the Cabal codebase.  This should probably be wrapped as a <tt>--list-licenses</tt> command line switch.  Pretty-printing licenses would be a plus.

I am already finding this feature useful, and hope others will too.

**Comment by libeako** [comment]
I was about to request this feature.

Many common licenses require a reproduction of the license when the software is distributed in binary form. For example : BSD3 : 
"Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution."

It is too tedious and error-prone to manually traverse the dependency graph and the individual licenses.

I imagine a command line tool that collects the license info into a folder dedicated for this purpose, which would be distributed together with the executable.

**Comment by hvr** [comment]
fwiw, @ekmett mentioned on `#hackage` he hacked up a script which generates
output like  https://gist.github.com/ekmett/34024e26479763d77bc3e1ecaa24b819

**Comment by Profpatsch** [comment]
A command line feature like this would be awesome, to see which package introduced which dependencies. For reference, here’s how `nix-store 1.11` implements it (though I’m not a fan of the naming at all).

```
OPERATION --QUERY
   Synopsis
       nix-store {--query | -q} {--outputs | --requisites | -R | --references |
                 --referrers | --referrers-closure | --deriver | --deriver | --graph
                 | --tree | --binding name | --hash | --size | --roots}
                 [--use-output] [-u] [--force-realise] [-f] paths...

   Description
       The operation --query displays various bits of information about the store
       paths . The queries are described below. At most one query can be specified.
       The default query is --outputs.

       The paths paths may also be symlinks from outside of the Nix store, to the Nix
       store. In that case, the query is applied to the target of the symlink.

   Common query options
       --use-output, -u
           For each argument to the query that is a store derivation, apply the query
           to the output path of the derivation instead.

       --force-realise, -f
           Realise each argument to the query first (see nix-store --realise).

   Queries
       --outputs
           Prints out the output paths of the store derivations paths. These are the
           paths that will be produced when the derivation is built.

       --requisites, -R
           Prints out the closure of the store path paths.

           This query has one option:

           --include-outputs
               Also include the output path of store derivations, and their closures.
           This query can be used to implement various kinds of deployment. A source
           deployment is obtained by distributing the closure of a store derivation.
           A binary deployment is obtained by distributing the closure of an output
           path. A cache deployment (combined source/binary deployment, including
           binaries of build-time-only dependencies) is obtained by distributing the
           closure of a store derivation and specifying the option --include-outputs.

       --references
           Prints the set of references of the store paths paths, that is, their
           immediate dependencies. (For all dependencies, use --requisites.)

       --referrers
           Prints the set of referrers of the store paths paths, that is, the store
           paths currently existing in the Nix store that refer to one of paths. Note
           that contrary to the references, the set of referrers is not constant; it
           can change as store paths are added or removed.

       --referrers-closure
           Prints the closure of the set of store paths paths under the referrers
           relation; that is, all store paths that directly or indirectly refer to
           one of paths. These are all the path currently in the Nix store that are
           dependent on paths.

       --graph
           Prints the references graph of the store paths paths in the format of the
           dot tool of AT&T's Graphviz package[1]. This can be used to visualise
           dependency graphs. To obtain a build-time dependency graph, apply this to
           a store derivation. To obtain a runtime dependency graph, apply it to an
           output path.

       --tree
           Prints the references graph of the store paths paths as a nested ASCII
           tree. References are ordered by descending closure size; this tends to
           flatten the tree, making it more readable. The query only recurses into a
           store path when it is first encountered; this prevents a blowup of the
           tree representation of the graph.
       
        … a few more
```

Interesting is the distinction between run-time and build-time dependencies, though I’m not sure if that’s relevant for cabal.

**Comment by neosimsim** [comment]
> Interesting is the distinction between run-time and build-time dependencies, though I’m not sure if that’s relevant for cabal.

Might be relevant/interesting for custom setups.

**Comment by andreasabel** [comment]
`cabal-plan` seems to solve the OP, see https://hackage.haskell.org/package/cabal-plan

Here is how we use it in Agda:
https://github.com/agda/agda/blob/2bab72d99ae3330cbf3a94450a647158838a1d1b/doc/license-report/Makefile#L9-L20

**Comment by ethercrow** [comment]
Posting just in case someone would have the same problem.

`cabal install -f license-report cabal-plan` was failing for me, claiming that it's not buildable.

However, `cabal install -f exe -f license-report cabal-plan` seems to work.

**Comment by andreasabel** [comment]
@ethercrow :
> `cabal install -f license-report cabal-plan` was failing for me, claiming that it's not buildable.
> 
> However, `cabal install -f exe -f license-report cabal-plan` seems to work.

I stumbled over this myself:  Here is some justification for the current flag setup by the author: https://github.com/haskell/cabal/issues/7814#issuecomment-968068735
