### ISSUE TITLE
Allow unknown fields in .cabal with X- at front

### ISSUE THREAD

**Issue by bos** [haskell/cabal#881]
(Imported from [Trac #891](http://hackage.haskell.org/trac/hackage/ticket/891), reported by zzo38 on 2011-09-29)

I have suggestion allowing unknown fields in a .cabal file, and if they are named with X- at front, they will not have warning message, and will be ignored if they are not understand.

It should also do similar thing with sections named with X- at front, where, it if it doesn't understand that section, it ignore entire section with no warning/error (regardless of field names), but if it can use that section, it is still warnings for unknown fields in that section without X- at front.

**Comment by jsl** [comment]
Since this doesn't have any activity since 2011, I propose closing. Please re-open or file a new ticket if this is something that is still desired.
