### ISSUE TITLE
Unknown Behavior regarding Cabal Install

### ISSUE THREAD

**Issue by liamzee** [haskell/cabal#8815]
I've been getting conflicting reports of what cabal install <alib> should do, but I've been able to reproduce my behavior.

On Windows 10, with a GHCup install of 9.4.4 and 3.8.1.0, at least, cabal install <alib> won't update a package database, and the files are inaccessible without using cabal repl -b, etc...

However, if you --lib something, you now create a package database to which ghci and ghc can see, and further cabal install <alib> will result in libraries being added, hidden, to this database.

Is this intended behavior, or a bug?

**Comment by ulysses4ever** [comment]
Welcome to the cabal bug tracker! Indeed, everything you describe is the intended behavior of `cabal install`. 
The behavior changed over years, that is why you may get conflicting informations. Please refer to the documentation when in doubt — it is the definitive source:

- [Cabal User Guide: cabal install](https://cabal.readthedocs.io/en/stable/cabal-commands.html#cabal-install)

If you find anything unclear in the guide, please, feel free to report a bug here.

**Comment by liamzee** [comment]
Thanks for your assistance!
