### ISSUE TITLE
cabal build: assertion failure at `Distribution/Client/InstallPlan:361` 

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8822]
(UPDATE: Could be that this assertion can be triggered by having manually delete build products in the `~/.cabal/store`.  I deleted files older then 400 days if I remember correctly to reclaim some disk space.)

I can reproduce this on my macOS Monterey with current `master`:
```shell-session
$ cabal get shelly-1.12.0
$ cd shelly-1.12.0
$ cabal build -w ghc-8.2.2
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Assertion failed
CallStack (from HasCallStack):
  assert, called at src/Distribution/Client/InstallPlan.hs:361:7 in cabal-install-3.9.0.0-inplace:Distribution.Client.InstallPlan
```
It is this assertion: https://github.com/haskell/cabal/blob/ab24689731e9fb45efa6277f290624622a6c214f/cabal-install/src/Distribution/Client/InstallPlan.hs#L361

It can be further reproduced with `ghc-8.10.7`.
However, it works with my other compilers: 8.4.4 8.6.5 8.8.4 9.0.2 9.2.7 9.4.4

If I try building with `cabal-3.8.1.0` instead, I get the following different result with `ghc-8.0.2`:
```
$ cabal-3.8.1.0 build -w ghc-8.2.2
Resolving dependencies...
Build profile: -w ghc-8.2.2 -O1
In order, the following will be built (use -v for more details):
 - mtl-2.2.2 (lib) (requires build)
 - unix-compat-0.6 (lib) (requires build)
 - transformers-compat-0.7.2 (lib) (requires build)
 - text-2.0.2 (lib) (requires build)
 - type-equality-1 (lib) (requires build)
internal error in InstallPlan.completed: not in configured state: Installed xcptns-0.10.7-033c1607
CallStack (from HasCallStack):
  error, called at src/Distribution/Client/InstallPlan.hs:259:25 in cbl-nstll-3.8.1.0-55ab9d4d:Distribution.Client.InstallPlan
  internalError, called at src/Distribution/Client/InstallPlan.hs:655:26 in cbl-nstll-3.8.1.0-55ab9d4d:Distribution.Client.InstallPlan
```
With `ghc-8.10.7` it works then.

Crude workaround: `rm -rf .cabal/store/ghc-8.2.2` and try again.  However, better not have stuff (e.g. installed exes) pointing there  ... (Works also for `ghc-8.10.7`).

**Comment by Mikolaj** [comment]
We've had some fixes recently that sounded vaguely families. Do you thing this is still reproducible? That was a regression on master in Feb. Does it mean it's a regression in 3.10 at this point? Did it really not affect cabal 3.8 or we have no way of reproducing with 3.8, but the problem may be older?

**Comment by andreasabel** [comment]
This issue does not really have a reproducer, so it is hard to further investigate it.  I'll close it, let's see if it resurfaces...
