### ISSUE TITLE
`cabal install EXE --program-suffix=SUF` fails in copy step

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8823]
Trying to install an executable (in this case, `cabal` itself) with `cabal` built from `master`:
```shell-session
$ cabal install cabal-install --program-suffix=-new-check
...
Building executable 'cabal' for cabal-install-3.9.0.0..
[1 of 1] Compiling Main             ( main/Main.hs, dist/build/cabal/cabal-tmp/Main.o )
[2 of 2] Linking dist/build/cabal/cabal
Installing executable cabal in /Users/abel/.cabal/store/ghc-9.4.4/incoming/new-90296/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin
Warning: The directory
/Users/abel/.cabal/store/ghc-9.4.4/incoming/new-90296/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin
is not in the system search path.
Copying 'cabal' to '/Users/abel/.cabal/bin/cabal-new-check'
/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/cabal: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:withBinaryFile: does not exist (No such file or directory)
```
I have this in my `.cabal/config`:
```
install-method: copy
overwrite-policy: always
```
I am on macOS, as you can see from the garbled package names.
(I am having a dejavu, haven't I reported this already?)

The problem is that in `~/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/` there is no executable `cabal`, but there is `cabal-new-check`.

Workaround:  Take matters in your own hand and do the copy step yourself:
```shell-session
$ cp ~/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/cabal-new-check ~/.cabal/bin/
```

Label `newcomer`: I _suppose_ the bug is a simple oversight and can be easily fixed.  However, there should also be a test case...

**Comment by ulysses4ever** [comment]
> I am on macOS, as you can see from the garbled package names.
> (I am having a dejavu, haven't I reported this already?)

Thanks to the apt title, I can easily find the issue and confirm that you did: 

- #7209

**Comment by fendor** [comment]
An open question remains, whether we want the store to contain the canonical name, e.g. `cabal` or whether the binary should be `cabal-new-check`. I think the former is the better behaviour. Otherwise, installing the same binary with multiple suffixes or prefixes, would produce multiple binaries (even in symlink mode).
