### ISSUE TITLE
Don't print 'Up to date' in 'cabal run'

### ISSUE THREAD

**Issue by chshersh** [haskell/cabal#8828]
When running executables with `cabal run`, it prints an annoying line `Up to date` line, messing with the output and making it look less pretty.

The `cabal exec` command, however, doesn't print this line, make the output nicer. The `cabal run` command, is more preferred, as it guarantees to run the latest version of the executable and compiles it if needed.

Comparison from one of the executables:

**cabal run**

```
❯ cabal run simple-grep -- -f iris.cabal -s iris
Up to date
2: name:                iris
7:     See [README.md](https://github.com/chshersh/iris#iris) for more details.
8: homepage:            https://github.com/chshersh/iris
9: bug-reports:         https://github.com/chshersh/iris/issues
27:   location:            https://github.com/chshersh/iris.git
107: test-suite iris-test
114:     Paths_iris
117:     Paths_iris
126:     , iris
```

**cabal exec*

```
❯ cabal exec simple-grep -- -f iris.cabal -s iris
2: name:                iris
7:     See [README.md](https://github.com/chshersh/iris#iris) for more details.
8: homepage:            https://github.com/chshersh/iris
9: bug-reports:         https://github.com/chshersh/iris/issues
27:   location:            https://github.com/chshersh/iris.git
107: test-suite iris-test
114:     Paths_iris
117:     Paths_iris
126:     , iris
```

I tried to check the code to see if it's possible to fix this log quickly. However, it seems like it's buried deep inside, and I'm not sure what is the best way to fix it.

https://github.com/haskell/cabal/blob/0bedc4ac3b2fd6c01183076c22f15a0e8338e3fc/cabal-install/src/Distribution/Client/ProjectOrchestration.hs#L882-L883

**Details**

cabal version: 3.8.1.0
OS: Ubuntu 20.04
GHC version: 9.2.5

**Comment by ffaf1** [comment]
Related: #7790

**Comment by ulysses4ever** [comment]
Thanks for the report! It's a dup of https://github.com/haskell/cabal/issues/4994, which was fixed, and the fix should be released as a part of cabal-install 3.10. I suggest we close.

**Comment by chshersh** [comment]
Nice to hear, it's closed! Wasn't aware there is a duplicate. I'm happy to close 🙌🏻

**Comment by ulysses4ever** [comment]
@chshersh sure, no worries. If you have GHCup at hand, you can add the prerelease channel (see their guide) and check out cabal-install 3.9, a prerelease that should have this patch. That way we can double check that everything is going as planned.
