### ISSUE TITLE
Add `cabal init --no-comments` option to config file

### ISSUE THREAD

**Issue by Lysxia** [haskell/cabal#8835]
I'd like to use `cabal init` non-interactively. How can I configure its default behavior? In particular I'd like to set the `--no-comments` option in the `config` file.

**Comment by ffaf1** [comment]
Alas in `~/.cabal/config`, in the `init` section, I see an `interactive:` option but not a `comments:` one.

**Comment by ulysses4ever** [comment]
It's a valid feature request. Shouldn't be hard to implement.

I fail to find another ticket where someone wanted a config field for author and stuff like that, but we suggested they use arguments and maybe wrap a cabal init call with those arguments in a script…

**Comment by ulysses4ever** [comment]
I did a quick experiment here: https://github.com/ulysses4ever/cabal/commit/1d3c7430d75997f85f9647933bcff074dd95a576

It's easy but it needs couple more pushes that I don't know when I can get to, so please take over if you feel like it:

- it needs a test
- it's not clear which `init` flags we want to allow: besides `no-comments` it seemed reasonable to allow `quiet`, `simple` and `minimal` (the last one implies `no-comments` btw). But maybe `author` and `email` too? Something else?

**Comment by Lysxia** [comment]
When I use `cabal init` it already knows my name (`author` and `email`). I can't find out where that's stored though.

**Comment by ulysses4ever** [comment]
@Lysxia it fetches it from your git config. One can imagine a setup without git available. It would be a very rare setup of course.
