### ISSUE TITLE
cabal run fails on windows due to the long path issue

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8841]
**Describe the bug**
 Copied from IRC:

> **maerwald:**
> windows cabal test consistently fails: https://github.com/haskell/ghcup-metadata/actions/runs/4396989936/jobs/7699817403#step:3:14665
>
> the same test works with 3.6.2.0: https://github.com/haskell/ghcup-metadata/actions/runs/4397003656/jobs/7699838528
> 
> D:\a\_temp\foobarbaz\ghcup\ghc\9.4.4\lib\../mingw/bin/llvm-ar.exe: error: C:\\cabal\\script-builds\\ff17c4bce8853274ef8c5beb95175084fb96425f714475e54f50bdf49f3b33c6\\dist-newstyle\\build\\x86_64-windows\\ghc-9.4.4\\fake-package-0\\x\\cabal-script-main.hs\\build\\cabal-script-main.hs\\cabal-script-main.hs-tmp\Main.p_o.tmp: No such file or directory
> 
> yes, there's a regression with long paths on windows

> **Artem:**
> any way to check if it works with 3.8.1.0? or how to repro it in general? 'Cause it seems like it `cabal run`s `print $ 1+1`, which 3.10 is definitely capable of (even on Windows!). Do I just put the script in a folder with a long path (like above)?

> **maerwald:**
> just make sure you don't have CABAL_DIR set and it should reproduce

**To Reproduce**

No idea.

**System information**
 - Operating system: Windows
 - `cabal`, `ghc` versions: 3.10.1.0, 9.4.4

**Comment by gbaz** [comment]
Note that @hasufell considers this a blocker to making cabal-install 3.10.1.0 a recommended release

**Comment by jneira** [comment]
Thanks for the report, to delimite the scope of the bug:
* it seems to affect only `cabal run`, at least not `cabal build` in my tests
* as commented setting CABAL_DIR to a short path workarounds the issue. Another one could be the usual one: enable long paths on windows (i've not tested it hough)
* it likely was introduced by the cabal run/script support in cabal-3.8 so it is not a regression only for 3.10:

```
PS D:\dev\ws\haskell\cabal-test> cabal-3.8.1.0.exe .\script.hs
realgcc.exe: error: C:\Users\atrey\AppData\Roaming\cabal\script-builds\8451f75c9bb9fd520bd934aea714d2e240d258f1e884c03cde6784c44c03d9ce\dist-newstyle\build\x86_64-windows\ghc-8.10.7\fake-package-0\x\cabal-script-script.hs\build\cabal-script-script.hs\cabal-script-script.hs-tmp\Main.o: No such file or directory
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
PS D:\dev\ws\haskell\cabal-test>
```

**Comment by ulysses4ever** [comment]
Very interesting and useful, thank you, @jneira ! 

For the future: am I understanding correctly that it's impossible to test in our test suite because we have CABAL_DIR set.

**Comment by jneira** [comment]
> Very interesting and useful, thank you, @jneira !
> 
> For the future: am I understanding correctly that it's impossible to test in our test suite because we have CABAL_DIR set.

To be precise the fact which causes the bug is to set CABAL_DIR to a enough long path. It turns out that the default one is long enough to do it.

So setting CABAL_DIR to a long enough path should reproduce the bug.

**Comment by ulysses4ever** [comment]
> it likely was introduced by the cabal run/script improvements in cabal-3.8 

Maybe page in @bacchanalia in that case

**Comment by Mikolaj** [comment]
Could somebody please verify if this affects only GHC 9.4.4 or any other GHC as well? 

@bgamari: I wonder if there's a possibility that GHC 9.4.5 fixes the long path issue on Windows (see the previous comment)?.

@bacchanalia: give your recollection of the code of this feature, is there any way to work around the problem? Make a temporary short link just before executing the script? Shorten or eliminate the hash? Remove all the "cabal-script" prefixes to fake package names?

**Comment by Mikolaj** [comment]
Good news: the GHC fix is on the horizon: https://gitlab.haskell.org/ghc/ghc/-/issues/21293

Still, long paths have been plaguing the ecosystem for long, for various reasons, so if we can make cabal less fragile with respect to this issue, that would be worthwhile IMHO.

**Comment by Mikolaj** [comment]
@bacchanalia: I'm not sure if the notifications are reaching you, so I may try the email. I'd prefer to avoid mucking around with somebody's design and code without as much as informing the author.

**Comment by Mikolaj** [comment]
@bacchanalia: I think you started working on this recently, but I can't find the PR. Could you point me to it? Thank you.

**Comment by bacchanalia** [comment]
I'm sorry, my life has been really hectic the past week. I didn't realize this was a blocker, sorry. Looking into this now.

**Comment by bacchanalia** [comment]
@Mikolaj I put a quick fix up which saves 21 chars, by using a more compact encoding for the hash. If this isn't enough, I can investigate other methods, like you were discussing in your previous comment. I don't have a Windows development environment set up to test it right now, but should be able to set one up in the next few days.

**Comment by Mikolaj** [comment]
Well done! Apologies for badgering --- this is not a clear blocker, but still every saved character is one less potential fresh user struggling, before GHC fixes this upstream.

Could a kind Windows user test if this suffices in any standard Windows install? Alternatively, could somebody tweak our CI not to shorten the path by setting CABAL_DIR to something unnaturally short?

**Comment by ulysses4ever** [comment]
This is fixed on `master` now (https://github.com/haskell/cabal/issues/8898) but automatic backport to 3.10 didn't land because of merge conflicts, unfortunately (#8970).

**Comment by jneira** [comment]
hi, only want to note that to be precise the issue is not totally fixed, still is possible to hit the limit with enough long script file names as it is noted in the QA notes of the original pr

**Comment by hasufell** [comment]
> hi, only want to note that to be precise the issue is not totally fixed, still is possible to hit the limit with enough long script file names as it is noted in the QA notes of the original pr

Right, but that's not a regression to 3.6, so to speak. Right?

**Comment by ulysses4ever** [comment]
@jneira cabal can't fix this issue for real, can it? It's limitation of Windows, and we can only try to not hit it too often.

**Comment by hasufell** [comment]
> @jneira cabal can't fix this issue for real, can it? It's limitation of Windows, and we can only try to not hit it too often.

It could, by using `\\?\` style paths everywhere, but that's kinda difficult: https://learn.microsoft.com/en-us/archive/blogs/bclteam/long-paths-in-net-part-1-of-3-kim-hamilton

**Comment by jneira** [comment]
or fixing the script file name (losing the complete file name in exchange)

**Comment by ulysses4ever** [comment]
I backported this change to 3.10 and as original reported I feel confident that we can close the ticket because it was specifically describing the regression in 3.8 w.r.t 3.6 that is fixed now (on master and on 3.10 branch).

**Comment by ulysses4ever** [comment]
Ideas on how to improve our UX on Windows are welcome as separate tickets.

**Comment by jneira** [comment]
well the maximum long script file name (it does not depend on full path only the name) is around 30 chars so I I think it will be not reached frequently
