### ISSUE TITLE
i can't make cabal install build and install the pandoc executable 

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#8874]
```
carterschonwald@CarterHydra ~/D/cabal-install-3.10.1.0-aarch64-darwin [1]> ./cabal install pandoc -fembed_data_files
Resolving dependencies...
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
* You might have wanted to add them as dependencies to your package. In this
case add "pandoc, pandoc" to the build-depends field(s) of your package's
.cabal file.
* You might have wanted to add them to a GHC environment. In this case use
"cabal install --lib pandoc pandoc". The "--lib" flag is provisional: see
https://github.com/haskell/cabal/issues/6481 for more information.
```
in previous versions of cabal-install, i'd maybe get a message about needing to set `--overwrite=always` but I see no hinting about how to install `pandoc`.

so i need to reference exe:pandoc or some other naming mechanism to say "give me the executable"?

in case this isn't clear, i'm seeing this with both prebuilt and nonprebuilt cabal install.

its worth mentioning that in a previous step ran the command `cabal install pandoc --only-dep` to just build all the libraries it would need. could that have interacted poorly?

**Comment by cartazio** [comment]
... maybe the most recent release of pandoc doesn't have an executable ... in which case this is perhaps an example of a cabal error message where it'd be useful to list that theres no executables in that package ..

**Comment by cartazio** [comment]
yup, its now `cabal install pandoc-cli` derp :)

**Comment by ulysses4ever** [comment]
Oh wow, this change will break a lot of users.

That said I wonder if we could be smarter with the error message. Well, being smart is hard, and I don't see an easy fix here.

**Comment by cartazio** [comment]
Yeah it’s a very confusing error message.  It would help if it explicitly said there were no executables in that package. But sleuthing that out was certainly confusing.
