### ISSUE TITLE
`cabal check` fails (exitcode 1), but produces warnings only, no error

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8880]
I am getting a failure from `cabal check` (3.10.1.0) with the following warnings:
https://github.com/diagrams/active/actions/runs/4546584124/jobs/8015396504?pr=41#step:21:21
```
Warning: These warnings may cause trouble when distributing the package:
Warning: Please consider moving the file 'CHANGES' from the
'extra-source-files' section of the .cabal file to the section
'extra-doc-files'.
Warning: These packages miss upper bounds:
- doctest
Please add them, using `cabal gen-bounds` for suggestions. For more
information see: https://pvp.haskell.org/
Warning: The following errors will cause portability problems on other
environments:
Warning: The dependency 'setup-depends: 'Cabal' does not specify an upper
bound on the version number. Each major release of the 'Cabal' package changes
the API in various ways and most packages will need some changes to compile
with it. If you are not sure what upper bound to use then use the next major
version.
Warning: Hackage would reject this package.
Error: Process completed with exit code 1.
```
I wish for a clearer communication of the problems:
- Which of these is just a recommendation (warning), and which leads to the exit code 1 (error)?
- Which of these prompts Hackage to reject the package?

**Comment by ffaf1** [comment]
Having a different prompt for warnings and errors is indeed reasonable request. The information *is* there, but as now it gets drowned in the output. Specifically:

```
Warning: These warnings may cause trouble when distributing the package:
Warning: The following errors will cause portability problems on other
environments:
```

are the "headers" for different error severities, fixing `setup-depends:` would get the exit code back to 0. Relevant code:

https://github.com/haskell/cabal/blob/d53b4d46c51f5162e84765fd69d9c8806eea15b1/cabal-install/src/Distribution/Client/Check.hs#L81-L108

I will sketch (and welcome suggestions on) some ideas for a better UX. I see the file was modified in #8427, so — like Sisyphus — that would have to be rebased.

**Comment by ffaf1** [comment]
Notes to my future self. This is where `exitFailure` is called:

https://github.com/haskell/cabal/blob/d53b4d46c51f5162e84765fd69d9c8806eea15b1/cabal-install/src/Distribution/Client/Main.hs#L877-L883

and this is where the warning message is formed:

https://github.com/haskell/cabal/blob/d53b4d46c51f5162e84765fd69d9c8806eea15b1/Cabal/src/Distribution/Simple/Utils.hs#L450-L461

`Warning:` is baked in. I wonder how sensible it would be to add a `waringPrompt :: String -> String -> IO ()` where we control what is prepended (Maybe some IDE use that to color-code output?). Sample output:

```
Warning: These warnings may cause trouble when distributing the package:
Warning: Please consider moving the file 'CHANGES' from the
'extra-source-files' section of the .cabal file to the section
'extra-doc-files'.
Warning: These packages miss upper bounds:
- doctest
Please add them, using `cabal gen-bounds` for suggestions. For more
information see: https://pvp.haskell.org/
Error: The following errors will cause portability problems on other
environments:
Error: The dependency 'setup-depends: 'Cabal' does not specify an upper
bound on the version number. Each major release of the 'Cabal' package changes
the API in various ways and most packages will need some changes to compile
with it. If you are not sure what upper bound to use then use the next major
version.
Error: Hackage would reject this package.
Error: Process completed with exit code 1.
```

A less invasive option is to just style header messages differently (add `***` or similar? `☞☞☞` `✝✝✝` `✚✚✚` `⭍⭍⭍`?) and word them in a stronger manner. Care needed not to annoy blind users who rely on TTS or braille displays. Sample output:

```
Warning: *** These warnings may cause trouble when distributing the package:
Warning: Please consider moving the file 'CHANGES' from the
'extra-source-files' section of the .cabal file to the section
'extra-doc-files'.
Warning: These packages miss upper bounds:
- doctest
Please add them, using `cabal gen-bounds` for suggestions. For more
information see: https://pvp.haskell.org/
Warning: *** The following errors will cause portability problems on other
environments and will be REFUSED by Hackage:
Warning: The dependency 'setup-depends: 'Cabal' does not specify an upper
bound on the version number. Each major release of the 'Cabal' package changes
the API in various ways and most packages will need some changes to compile
with it. If you are not sure what upper bound to use then use the next major
version.
Warning: Hackage would reject this package.
Error: Process completed with exit code 1.
```

**Comment by ulysses4ever** [comment]
@ffaf1 for the record, i think Cabal's messaging is severely under-developed in terms of decorations. Please, give me more emojis and alike! One of the ways to figure how to do it is to steal from someone, i think. E.g. `cargo` would be my first choice to look for an example. I guess, I could look into what Julia and its package manager do in such cases. I just need to figure out what would be the closest scenario…

**Comment by ulysses4ever** [comment]
Also, I think, the presentation here would benefit greatly from simply having blank lines after every message... Sorry I didn't mention it before the merge.
