### ISSUE TITLE
CI: cabal-testsuite tests fail with "double directory"

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8883]
It was observed earlier on Windows:

- #8739

but since GHC 9.6.1 it plagues the other platforms too. [Here's one recent CI run](https://github.com/haskell/cabal/actions/runs/4443872939/jobs/7801547699?pr=8840#step:19:36).

```
PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs:4:1: error:
Error:     Ambiguous module name ‘System.Directory’:
      it was found in multiple packages:
      directory-1.3.8.1 directory-1.3.8.1
  |
4 | import System.Directory (removeFile)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Due to this error I had to disable `cabal-testsuite` altogether for 9.6.1 in #8840.

**Comment by jgotoh** [comment]
I have this bug on my machine running with ghc 9.2.8 and cabal 3.10.1.0. Can I help you debug this somehow?

**Comment by Mikolaj** [comment]
@jgotoh: thank you very much. At some point @grayjay wanted to have a look at a log of a failed run (now provided in https://github.com/haskell/cabal/issues/8356), so I guess having a local reproducing checkout or hints about how to set up one could be valuable as well.

**Comment by ulysses4ever** [comment]
@Mikolaj should we close this on favor of #8356? I thought the title and description here is a little more clear, but you seem to be posting updates there. So, currently it's a bit confusing.

**Comment by Mikolaj** [comment]
I've now stolen your ticket title and description, so we can safely close this now. :)

**Comment by ulysses4ever** [comment]
Only good things get stolen, so I'm happy!
