### ISSUE TITLE
`code-generators` documentation missing

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8887]
See https://github.com/haskell/cabal/commit/67d26c6023efb9129145af24fe9ee5fd3307a563#r107039311

**Comment by gbaz** [comment]
Someone just needs to put this back -- it was lost in a merge conflict. Please!

**Comment by gbaz** [comment]
@jneira mentioned they would do this?

**Comment by jneira** [comment]
yeah I would like to do it but I need to find a time window, please do not wait for me if it is urgent

**Comment by ulysses4ever** [comment]
all right, I learned myself some more Magit magic by doing that partial reversion... #8969
