### ISSUE TITLE
CI RFC: remove dependency on cabal-plan

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8891]
Currently, our CI `cabal install`s `cabal-plan` on every validate job. Here're timings of every step in a [Validate ubuntu-20.04 ghc-9.4.2](https://github.com/haskell/cabal/actions/runs/4579043840/jobs/8086372305#logs) run (only longer-than-minute steps are shown):

| Step                         | Time |
| ---------------------------- | ---- |
| Run haskell/actions/setup@v2 | 2m 19s |
| Install cabal-plan           | 5m 42s |
| Validate build               | 15m 5s |
| Validate lib-test            | 1m 9s |
| Validate lib-suite           | 4m 33s |
| Validate cli-test            | 4m 31s |
| Validate cli-suite           | 11m 29s |   

My rough calculation is that the cabal-plan step takes more than 10% of time (~13% perhaps). I think it's a non-negligable price. Why do we pay it?

If you look into `validate.sh` -- the actual validation script, it uses `cabal-plan` for two use cases:

1. `cabal-plan list-bin` to find executables built by `cabal`
2. `cabal-plan top` to list all packages planned for the build topologically sorted.

The first use case is obsolete since we have `cabal list-bin`. It should be easy to swap one for another.

The second use case doesn't feel useful to me. Does anyone have a different feeling? Does it make sense to pay 13% of time for it?

If the answer for the latter question is No, I think we should consider removing dependency on cabal-plan.

---

There's one more reason I'd like to remove this dependency: `cabal-plan` does not update for newer GHCs particularly fast. E.g. GHC 9.6.1 has been released more than one month ago, and `cabal-plan` still does not build without `allow-newer`.

---

If people think that we should have `cabal-plan` in CI, I think we could do it and solve the two problems I mention here via prebuilt binaries: downloading those will both save most of the time and relieve us of compatibility considerations.

**Comment by andreabedini** [comment]
I’m ok with this. I remember that when I tried replacing `cabal plan list-bin` with `cabal list-bin` something wasn’t working as expected but perhaps things have changed now.

**Comment by andreabedini** [comment]
I have forgotten all the details but in #7952 i have a commit that removes cabal plan https://github.com/haskell/cabal/pull/7952/commits/3c8dd207c39d0a056192ee4c744ff5fa653290c3 and another one that puts in back because `cabal list-bin` didn’t quite work the same https://github.com/haskell/cabal/pull/7952/commits/77ae21aeb44d695f47b21117e9601b32dccea988

IMHO it’s worth trying again though.

**Comment by fgaz** [comment]
I think it was because of #7679 (and also it started building stuff according to https://github.com/haskell/cabal/pull/7648#issuecomment-924111500 ?!?)

If cabal list-bin works now, i agree on removing cabal-plan

**Comment by Mikolaj** [comment]
Me too. Mostly for simplicity. One less moving part.

**Comment by ulysses4ever** [comment]
I just saw that HaskellWeekly uses `cabal freeze` to get the whole plan. Maybe I should have done it in #8893. But oh well, we have something, and CI doesn't spend time on building `cabal-plan` anymore (#8893). Closing…
