### ISSUE TITLE
cabal install --lib <something> creates environment file that does not mention base

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#8894]
With cabal-install-3.10.1.0, after `cabal install --lib <something>`, `ghci` no longer loads `Prelude`:

Fine, note: no environment file:
```
$ ghci
GHCi, version 9.6.1: https://www.haskell.org/ghc/  :? for help
ghci> False
False
```

Install package:
```
$ cabal install --lib leancheck
Resolving dependencies...
Build profile: -w ghc-9.6.1 -O1
In order, the following will be built (use -v for more details):
 - leancheck-1.0.0 (lib) (requires build)
Starting     leancheck-1.0.0 (lib)
Building     leancheck-1.0.0 (lib)
Installing   leancheck-1.0.0 (lib)
Completed    leancheck-1.0.0 (lib)
```

Start `ghci` again, note: with environment file
```
$ ghci
Loaded package environment from /home/waldmann/.ghc/x86_64-linux-9.6.1/environments/default
GHCi, version 9.6.1: https://www.haskell.org/ghc/  :? for help
ghci> False

<interactive>:1:1: error: [GHC-88464]
    Data constructor not in scope: False
```

Work-Around:
```
$ ghci -package base
Loaded package environment from /home/waldmann/.ghc/x86_64-linux-9.6.1/environments/default
GHCi, version 9.6.1: https://www.haskell.org/ghc/  :? for help
ghci> False
False
```

Indeed, the environment file (created by the install) does not mention `base`, while they previously did.
This is with
```
$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 
```
and ghc-9.6.1, also ghc-9.4.4. This is a change in behaviour from cabal-install-3.8.1.0

**Comment by ulysses4ever** [comment]
Thanks for the report! That's due to #8607 most likely. Cc @gbaz

**Comment by Mikolaj** [comment]
Yes, `--lib` is evil and `cabal env` only slightly less so. I think the idea is that you add manually whatever global packages you need, but @gbaz would need to confirm if `base` was intended to be covered by this rule.

**Comment by gbaz** [comment]
I would say that neither is evil, both are fine, when used right imho. But we're still figuring out the best UI for using them right. And generally I think the right way is not a global env file, but a local one per "project unit."

This is indeed a consequence of the prior PR, and maybe there can be some inbetween.

One can also just "install" base after installing another package as well:

```
% cabal install --package-env=foo.env --lib leancheck
Resolving dependencies...
% cabal install --package-env=foo.env --lib base     
Resolving dependencies...
% ghci ghci -package-env foo.env 
GHCi, version 9.4.1: https://www.haskell.org/ghc/  :? for help
ghci> False
False
```

One thing to improve the UX might be to always add base, and never warn about it, as a special case?

**Comment by ulysses4ever** [comment]
I think `base` should be added automatically. (Maybe any non-reinstallable package, but that's less clear.) Not sure if it defeats the whole purpose of #8607 or will it be "mostly there". My hunch is that it should be okay. But it requires experiment, I guess. 

Anyways, if anything, this shows that we should have some integration tests for this business.

**Comment by gbaz** [comment]
If we auto-add base with no other changes, then that's not enough. We also need to add it in such a way that it only gets added if it is not already there, and arguably if the env file is fresh. Otherwise we will have the same situation that PR fixed, where amending an existing env file inevitably generated an error.

**Comment by ulysses4ever** [comment]
> So therefore, cabal install --lib always failed when an environment file already existed, full stop.

This is not true. I just checked that 3.8 worked fine at least for **some combinations of packages** (that is, non mutually exclusive ones)  E.g.

```
❯ cabal install --lib --package-env=. aeson
...
❯ cabal install --lib --package-env=. clock
...
❯ cat .ghc.environment.x86_64-linux-9.4.4
clear-package-db
global-package-db
package-db /home/artem/.cabal/store/ghc-9.4.4/package.db
package-id ghc-9.4.4
package-id bytestring-0.11.3.1
package-id unix-2.7.3
package-id base-4.17.0.0
package-id time-1.12.2
package-id hpc-0.6.1.0
package-id filepath-1.4.2.2
package-id process-1.6.16.0
package-id array-0.5.4.0
package-id integer-gmp-1.1
package-id containers-0.6.6
package-id ghc-boot-9.4.4
package-id binary-0.8.9.1
package-id ghc-prim-0.9.0
package-id ghci-9.4.4
package-id rts-1.0.2
package-id terminfo-0.4.1.5
package-id transformers-0.5.6.2
package-id deepseq-1.4.8.0
package-id ghc-boot-th-9.4.4
package-id pretty-1.1.3.6
package-id template-haskell-2.19.0.0
package-id directory-1.3.7.1
package-id text-2.0.1
package-id aeson-2.1.2.1-b4e99e6d85eb68b552d3bc6448013ed3c346f3f90bd1b87671bf5157dba380f7
package-id clock-0.8.3-e1cb5c09c08b802543e1c283427ef69d76d97cf2dec49fcef18840c2a8f690bf

❯ ghci                                                                                                            0 (0.002s) < 16:54:33
Loaded package environment from /home/artem/Temp/cabal-dup-env/.ghc.environment.x86_64-linux-9.4.4
GHCi, version 9.4.4: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/artem/.ghci
λ> import Data.Aeson
λ> import System.Clock
λ> 
Leaving GHCi.
```

---

> cabal install --lib works pretty ok

Well, it's a judgement call and so is hard to argue with. For me, it's barely usable because of two things: 

- at some point it was relatively easy to get mutually exclusive packages in one environment but I fail to repro it now (it needs some creativity in which packages you sequentially `cabal install --lib`);
- there's no support for profiling libs: #7832.

**Comment by gbaz** [comment]
Oops, one correction. The issue with adding _all_ the global packages was that e.g. `time` is such a package but it is reinstallable -- so one should be able to install a lib built against a different version of `time` and that was prevented by this. That's why adding base is ok, because of course base is not (as of now) reinstallable.
