### ISSUE TITLE
./Setup repl is not documented

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#8906]
`./Setup repl` should be documented in `doc/setup-commands.rst`

**Comment by ulysses4ever** [comment]
Simply copying (well, and formatting in RST) of the `--help` would go a long way:

```shell
❯ echo -e "import Distribution.Simple\nmain=defaultMain" >Setup.hs

❯ runhaskell Setup.hs repl --help
Open an interpreter session for the given component.
...
```

**Comment by andreabedini** [comment]
TIL about `./Setup.hs repl` 😂

**Comment by Sdywolf** [comment]
I'm a newcomer to Haskell community and I'll spend some days on this issue.
