### ISSUE TITLE
-v0 should hide haddock output

### ISSUE THREAD

**Issue by dmwit** [haskell/cabal#8915]
**Describe the bug**
There should be a verbosity level -- presumably 0 -- where haddock output is suppressed, but it seems like there currently isn't. This is especially relevant for `cabal run`, since that can appear as part of a pipeline. 

**To Reproduce**
```
$ cabal init --lib
$ cabal v2-build --enable-documentation -v0
Haddock coverage:
   0% (  0 /  2) in 'MyLib'
  Missing documentation for:
    Module header
    someFunc (src/MyLib.hs:3)
```

**Expected behavior**
I expect no output.

**System information**

```
$ uname -a
Linux barley 5.17.5-76051705-generic #202204271406~1651504840~22.04~63e51bd SMP PREEMPT Mon May 2 15: x86_64 x86_64 x86_64 GNU/Linux
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

**Comment by ulysses4ever** [comment]
Thank you for the report! It appears to be a duplicate of #5991. There's some interesting discussion over there.

**Comment by dmwit** [comment]
Definitely a dupe, thanks, I'll transfer my attention there. Apologies for the noise; that one didn't turn up in my search.

**Comment by ulysses4ever** [comment]
No worries!
