### ISSUE TITLE
No cabal file found - Cabal 3.6.2.0

### ISSUE THREAD

**Issue by vanceism7** [haskell/cabal#8926]
**Describe the bug**
While trying to build my codebase from scratch (i.e: inside of a fresh docker container), A few times I ran into the following error during compilation

```
Failed to build typed-process-0.2.11.0. The failure occurred during the
configure step.
Build log (
/home/vscode/.cabal/logs/ghc-9.2.7/typed-process-0.2.11.0-c9598a9a688d48802c1f83cee8b0bb830a88b682c49620f313c81ce4f0841f5a.log
):
cabal-3.6.2.0: No cabal file found.
Please create a package description file <pkgname>.cabal
```

Initially I thought maybe I had misconfigured the cabal file (since I copied the code from another repo of mine), but then realized there wasn't actually anything wrong with it. If I simply rerun `cabal build`, it eventually finishes, albeit sometimes with the above error occurring a few more times on random packages.

**To Reproduce**
Take any haskell project with a decent number of dependencies and build it. Make sure to clear out `~/.cabal/store/ghc-*/` (or start up a fresh docker container) before building
Here's my current build depends:
```
base ^>=4.16.1.0,
        text,
        bytestring,
        mtl,
        containers,
        time,
        http-types,
        wai,
        wai-cors,
        conduit,
        conduit-extra,
        http-conduit,
        warp,
        blaze-builder,
        blaze-html,
        yesod,
        yesod-core,
        yesod-auth,
        jose-jwt,
        safe,
        persistent,
        persistent-sqlite,
        yesod-persistent,
        esqueleto,
        monad-logger,
        resourcet,
        aeson
```

Run the build
```
$ cabal build
```

**Expected behavior**
The project builds without errors

**System information**
 - Ubuntu Jammy (Im just using vscode in a devcontainer)
 - Cabal 3.6.2.0
 - GHC 9.2.7

**Comment by ulysses4ever** [comment]
This looks more like an HLS problem, and maybe asking on their bug tracker is more appropriate. But first, let's do some sanity check.

1. Can you upgrade you cabal to `latest`? (3.10)
2. What version of HLS do you run? (check with `haskell-language-server-wrapper --version`)
3. Can you show us your directory structure?
4. Can you try to manually create a `hie.yml` file in your project root? In general it depends on your directory structure (hence question 3) but the default one is something like:

```
cradle:
  cabal:
```

**Comment by vanceism7** [comment]
I'm not sure how this relates to HLS since I'm simply running cabal from the command line. I did upgrade cabal to 3.10.1.0 using ghcup but the issue persists. In order to re-test, I also had to clear out all the packages in `~/.cabal/store/ghc-9.2.7/`

My project root contains the following
```
app  cabal.project  client_session_key.aes  dist-newstyle  env.example  Makefile  README.md  tt-network.cabal
```

HLS version:
haskell-language-server version: 1.10.0.0 (GHC: 8.10.7) (PATH: /home/vscode/.local/share/ghcup/hls/1.10.0.0/lib/haskell-language-server-1.10.0.0/bin/haskell-language-server-wrapper)

**Comment by vanceism7** [comment]
Actually I'm thinking back a little bit and I have a hunch this might actually be a problem related to running docker containers in windows...

**Comment by gbaz** [comment]
If this at all involves windows filesystems, that would be my first guess as to blame.

**Comment by vanceism7** [comment]
Yea, I just tried this outside of a docker container using cabal 3.10.1.0 and it worked fine. For some reason, docker containers seem to have some weird sync issue with windows which causes files to not be created sometimes. Gonna chalk this up a "docker on windows" problem. 

Thanks for the help!
