### ISSUE TITLE
".." added by `Distribution.Backpack.DescribeUnitId.setupMessage'`, not full stop or ellipsis?

### ISSUE THREAD

**Issue by mpilgrem** [haskell/cabal#8928]
A very minor UI point: the `".."` added to the end of setup messages by `setupMessage'` is neither a full stop (`"."`) nor an ellipsis (`"..."`) - see the `where` statement in the code extract further below. Is that intentional, or a bug? If a bug, I'll raise a pull request to change it to an ellipsis. It results in output like:
~~~text
Preprocessing library for foo-0.1.0.0..
Building library for foo-0.1.0.0..
~~~

~~~haskell
-- | Print a Setup message stating (1) what operation we are doing,
-- for (2) which component (with enough details to uniquely identify
-- the build in question.)
--
...
setupMessage' verbosity msg pkgid cname mb_insts = withFrozenCallStack $ do
    noticeDoc verbosity $
      case mb_insts of
...
        _ ->
          msg_doc <+> for_doc

  where
    msg_doc = text msg <+> text (showComponentName cname)
    for_doc = text "for" <+> pretty pkgid <<>> text ".."
~~~

**Comment by ulysses4ever** [comment]
Changed from ellipsis to `..` here: https://github.com/haskell/cabal/commit/bc9d5adaa7e04dd5ca51830c55bc701bcd4fe60a

I think it's pretty safe to assume that it's a typo, and a PR fixing it would be very welcome.

**Comment by mpilgrem** [comment]
@ulysses4ever, thanks - pull request raised.
