### ISSUE TITLE
Document why `base` is uncondtionnally included in the global packages

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#8938]
Follow-up of https://github.com/haskell/cabal/pull/8903, some prose is needed to justify why `base` is an unconditional member of `globalPackages`.

**Comment by gbaz** [comment]
Thanks for the courtesy of not blocking on this, but it was a small enough thing that I added a comment to the existing pr. Optimistically closing in the expectation you would find it sufficient.

**Comment by Kleidukos** [comment]
Yes all good on my side. :)
