### ISSUE TITLE
Project conditionals can be used where?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#8945]
Can we update the docs to say where project conditionals can be used or, alternately, can we allow conditionals at nested locations?

In the `cabal.project` [Conditionals and imports](https://cabal.readthedocs.io/en/stable/cabal-project.html#conditionals-and-imports) sections it says we can use conditionals but doesn't say where within `cabal.project`. I'm using a `cabal.project.local` with [kim/opentracing](https://github.com/kim/opentracing).

I can use a compiler conditional at the top level.

```
program-options
  ghc-options: -Werror

if impl(ghc >=8.10)
  program-options
    ghc-options: -Wunused-packages
```

I can't nest the conditonal like I can do say for a package library in its `.cabal` file.

```
program-options
  ghc-options: -Werror

  if impl(ghc >=8.10)
    ghc-options: -Wunused-packages
```

The error (same for different GHC versions):

```
$ cabal build all --enable-tests --enable-benchmarks
Warning:
/.../opentracing/cabal.project.local:
Unrecognized section 'if' on line 4
Build profile: -w ghc-8.10.7 -O1

$ cabal build all --enable-tests --enable-benchmarks
Warning:
/.../opentracing/cabal.project.local:
Unrecognized section 'if' on line 4
Resolving dependencies...
Build profile: -w ghc-9.4.5 -O1
```

I also tried nesting within a package and that is not understood either. An outer conditional works:

```
program-options
  ghc-options: -Werror

if impl(ghc >=8.10)
  package opentracing
    ghc-options: -Wunused-packages
```

A nested one doesn't:

```
program-options
  ghc-options: -Werror

package opentracing
  if impl(ghc >=8.10)
    ghc-options: -Wunused-packages
```

The error:

```
$ cabal build all --enable-tests --enable-benchmarks
Warning:
/.../opentracing/cabal.project.local:
Unrecognized section 'if' on line 5
Resolving dependencies...
Build profile: -w ghc-9.4.5 -O1
```

This is with the latest version of cabal on `ubuntu-22.04`.

```
$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 
```

**Comment by gbaz** [comment]
we should update the docs to note that conditionals can be only at the top level, i agree.
