### ISSUE TITLE
User-config `builddir` option is ignored

### ISSUE THREAD

**Issue by mixphix** [haskell/cabal#8947]
**Describe the bug**
The `cabal user-config` setting `builddir` has no effect on the location of the output files. The command line option `--builddir=` works as expected.

**To Reproduce**

```
$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library

$ cabal user-config diff
+ builddir: /Users/mbrown/.cabal/dist/build

$ cabal build
...

$ ls
...
dist-newstyle/
...
```

**Expected behavior**
The artifacts should not have shown up in the project directory, but rather in the directory specified in the config file.

**System information**
 - Operating system: macOS Ventura
 - `ghc-9.2.7`

**Additional context**
Persists after removing the build folder, with quotes around the file path, with environment variables...

**Comment by mixphix** [comment]
I was trying to find a way to (globally) prevent Cabal's build artifacts from syncing to iCloud, by appending `.nosync` to its output folder. The workaround is to make a shell function that passes this option in every time — yikes!

**Comment by ulysses4ever** [comment]
Thank you for the report! This is not supported, and it's not easy to support as discussed in #5271. There should be a warning, of course, and that's reported (although for project files) in #7941.
