### ISSUE TITLE
CI fails with newly released QuickCheck-2.14.3

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#8988]
Please fix asap, as it blocks any other development

**Comment by ulysses4ever** [comment]
@phadej thanks for reporting! What do you think would be the right way to fix it? Options:

1. Avoid importing `shrinkBoundedEnum` from `QuickCheck` via `hinding`.
2. Import `shrinkBoundedEnum`  from `QuickCheck` and add upper bound to 2.14.3.
3. Anything else?

**Comment by phadej** [comment]
If second option works, it's probably the easiest.

**Comment by gbaz** [comment]
The function `shrinkBoundedEnum` is only defined and used once within the same module. I think the simplest thing to do is rename it -- or even inline it to its single use site.

**Comment by phadej** [comment]
@gbaz I would advice against that. `shrinkBoundedEnum` as in `QuickCheck` is better, just use it.

**Comment by Mikolaj** [comment]
CI looks fine (so far). And the contents of the commit that cannot be named LGTM. Artem saves the day again.

Could anyone else have a look at https://github.com/haskell/cabal/commit/c345a0372e202ee5ddfe4e7df6004699707ab357 ?

**Comment by ulysses4ever** [comment]
Yes, please, do have a look at the commit. I tried to follow Oleg's suggestions: bump lower bound for Quick Check, import the shrinking function from there, and add import lists in that module.

**Comment by jneira** [comment]
hmmm máster branch is not protected against direct commits? wow, I would protect it asap (and also branches used to release minor versions!)

**Comment by jneira** [comment]
yeah, I guessed that was the case, I always check that box, as admin you can uncheck it temporary if it is really needed

**Comment by Mikolaj** [comment]
I sense a disturbance in the force.
