### ISSUE TITLE
Multi-component REPL doesn't quite work with executable components

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8995]
**Describe the bug**

Executable's `main` is not visible if I load the exe together with the lib component.

**To Reproduce**

```console
> pwd
repl-multi-comp
> ./cabal --version
cabal-install version 3.11
compiled using version 3.11.0.0 of the Cabal library 
> ./cabal init -nm --libandexe
...
> ./cabal repl exe:repl-multi-comp
ghci> main
Hello, Haskell!
someFunc
λ> 
Leaving GHCi.
> ./cabal repl exe:repl-multi-comp lib:repl-multi-comp --enable-multi-repl
...
ghci> main

<interactive>:1:1: error: [GHC-88464]
    Variable not in scope: main
    Suggested fix: Perhaps use ‘min’ (imported from Prelude)
```

**Expected behavior**
The last call to `main` should succeed just as the first one.

**System information**
 - Operating system: NixOS
 - `cabal` `HEAD`, `ghc` 9.6.1

**Additional context**
@mpickering, do you think you could look into it as the author of the feature?

**Comment by mpickering** [comment]
Only one component is "active" and visible in the repl at once, and in this case it's the library component not the executable component. GHCi chooses the last unit passes to it to set as the "active" unit.

So this isn't a bug in cabal but a limitation of GHCi's support for multiple components.

**Comment by ulysses4ever** [comment]
Thanks! After I read your reply I was able to google [the blog post](https://well-typed.com/blog/2023/03/cabal-multi-unit/), and it does mention this shortcoming around "active" unit (not explaining what "active" unit is, though). So, the current state of things is good for tooling (ghcid, hls), mostly? Do I get any benefit in the actual REPL? Ease of recompilation (as in `:r`) when any of the components changed?
