### ISSUE TITLE
per-package configuration

### ISSUE THREAD

**Issue by bos** [haskell/cabal#900]
(Imported from [Trac #910](http://hackage.haskell.org/trac/hackage/ticket/910), reported by @kowey on 2012-01-02)

This may be related to #223 but I don't particularly want it in my global config.  I'm sick of running "cabal build" and not noticing until much later that my test had a compile error because I'd neglected to reconfigure with "--enable-test".

A similar issue happens with packages with custom flags, say sometimes I lose the "-f-library" flag I sometimes use for faster compilation.

I wish I had a mechanism to remember the command line flags passed in for a particular package.  Editing my global config doesn't seem quite like what I'm looking for; it has to be something that works, eg. with different branches of the same package.  What might be better for me is something like the Darcs prefs system, where I could edit a file in the current working directory like ".cabal" that says something like

<pre class="wiki">configure --enable-test -f-library
install -fgui
</pre>

**Comment by gbaz** [comment]
i believe this is obsoleted by the project stuff with new-configure.
