### ISSUE TITLE
support resolv-0.2

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#9054]
**Describe the bug**
It would be nice to support resolv-0.2 (released this year)

**To Reproduce**

When trying to build for Stackage Nightly I ran into:

resolv-0.2.0.2 ([changelog](http://hackage.haskell.org/package/resolv-0.2.0.2/changelog)) (Grandfathered dependencies) is out of bounds for:
- [ ] cabal-install-3.10.1.0 (>=0.1.1 && < 0.2). Mikhail Glushenkov <mikhail.glushenkov@gmail.com> @23Skidoo. Used by: library

**Comment by jessicah** [comment]
Haiku support is also introduced in 0.2.0.2 for resolv, so will also be good for that.
