### ISSUE TITLE
Quickstart guide refers to `v2-` commands

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#9086]
**Describe the bug**

The Quickstart guide refers to `v2-` commands. `v2-` can be omitted (since at least `cabal-install` version 3) and I understand it's common practice to do so. Therefore I think the Quickstart guide should do so.

* https://cabal.readthedocs.io/en/stable/nix-local-build.html
* https://github.com/haskell/cabal/blob/94c86abdf1ea4d9e79a28b14ca003f381eadf974/doc/nix-local-build.rst

**To Reproduce**

Read [The Quickstart guide](https://cabal.readthedocs.io/en/stable/nix-local-build.html). For example, it says `$ cabal v2-build`

**Expected behavior**

The Quickstart guide should say `$ cabal build`.

**System information**

A web browser.

**Additional context**

This issue [confused a (potential) user in the real world](https://discourse.haskell.org/t/coming-back-after-a-few-years-away-from-haskell-whats-changed/6849/6).

I am willing to make the necessary edits if the cabal maintainers agree that this is indeed a bug.

**Comment by ulysses4ever** [comment]
@tomjaguarpaw my view is: absolutely, please go ahead with the PR. Unless someone more experienced raises a substantial concern, we'll merge it.

Previews stub at fixing docs w.r.t. `v1-vs-v2` in the reference section of the manual:

- #8020
  - rebased version of https://github.com/haskell/cabal/issues/6703 

The page you're reporting has been reported before:

- #6213

A more generic discussion on the topic:

- #6104

**Comment by tomjaguarpaw** [comment]
Thanks, I submitted https://github.com/haskell/cabal/pull/9087

**Comment by geekosaur** [comment]
While people are thinking about this, when I recently submitted a cabal bug the reporting template told me to explicitly use `v2-` commands for clarity. This should probably change as well.

**Comment by ulysses4ever** [comment]
@geekosaur by all means. I added a checkbox in https://github.com/haskell/cabal/issues/8511 Contributions are welcome!

**Comment by seanhess** [comment]
I'm the "user in the wild" mentioned in the bug report. I just ran into the same thing that @geekosaur said: 

```
➜ cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2023-07-06T14:48:07Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2022-11-02T09:30:00Z'
```

I assume that I can drop the v2 prefix?

**Comment by ulysses4ever** [comment]
@seanhess yes, you can. Perhaps, you'd like to submit a patch removing `v2` from there? It's one `grep` and one change away, I'm sure.
