### ISSUE TITLE
Make readFields report if brace syntax is used.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#9098]
We can use brace syntax  to delimit sections and fields in `.cabal` files. This is e.g. used in changelogs.

However it's somewhat of an obscure feature, I cannot find any examples in documentation using it for example.

It would be useful if `readFields` reported if braces are used or not. E.g. `cabal check` (-like tools) could say "don't do that".

**Comment by geekosaur** [comment]
Are you proposing to remove it? I'm pretty sure I've seen it in the wild, so while obscure it's not completely unknown. (It initially surprised me whne I saw it, but in more of a "oh, they thought of that" fashion.)

**Comment by phadej** [comment]
> Are you proposing to remove it?

No. Just make a way to detect if it's used. See #9099

**Comment by phadej** [comment]
For curious:

```
161638 Total files on Hackage at the moment of writing
    18 LexWarningNBSP
     5 LexWarningBOM
  3985 LexWarningTab
  1962 LexInconsistentIndentation
  4223 LexBraces
```

Braces are slightly more popular than tabs. (And inconsistent indentation was surprisingly common, in 1% of all content).

**Comment by ulysses4ever** [comment]
I don't see a reason to introduce such a warning. Also, if someone starts seeing the warning it's just some unnecessary churn for them.

**Comment by geekosaur** [comment]
Same, I'm confused by it being a warning if it's not on the chopping block or at least disrecommended.

**Comment by phadej** [comment]
> I don't see a reason to introduce such a warning. Also, if someone starts seeing the warning it's just some unnecessary churn for them.

The warning is not seen as users of `cabal-install`.

I want `Cabal-syntax` parser to tell me whether brace syntax was used. The warning is one way to do that. It would be possible to amend `Fields` to include that too, but that change would be more intrusive.

**Comment by ffaf1** [comment]
> The warning is not seen by users of cabal-install.

It is in your proposal, isn't it?

>  E.g. cabal check (-like tools) could say "don't do that".

Not knowing much about the parser, I have no opinion.

**Comment by phadej** [comment]
@ffaf1 

> It is in your proposal, isn't it?

It isn't.

See https://github.com/phadej/cabal/blob/e3721a22466bd3ad8a30b7ca1ca00d0a08948075/Cabal-syntax/src/Distribution/Fields/LexerMonad.hs#L97-LL99

**Comment by phadej** [comment]
Ping.

**Comment by fendor** [comment]
Change and motivation looks good as is, imo.

> It would be possible to amend Fields to include that too, but that change would be more intrusive

I would like to see that change for #4965 and other consumers, too.
