### ISSUE TITLE
testsuite failure for MultiRepl on Windows & GHC 9.4.4

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#9103]
**Describe the bug**

We have a Heisenbug in [`PackageTests\MultiRepl\EnabledSucc\cabal.test.hs` ](https://github.com/haskell/cabal/blob/master/cabal-testsuite/PackageTests/MultiRepl/EnabledSucc/cabal.test.hs). It appears on Windows & GHC 9.4.4 and always goes away after a restart.

Here's [an example workflow where it fails on `master`](https://github.com/haskell/cabal/actions/runs/5500706388/jobs/10023795292). The last line reads (I split it in several lines for ease of reading):

```
D:\a\cabal\cabal\cabal-testsuite\PackageTests\MultiRepl\EnabledSucc\cabal.dist\work\.\dist\multi-out-2236\paths\pkg-a-0-inplace:
removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:DeleteFile 
"\\\\?\\D:\\a\\cabal\\cabal\\cabal-testsuite\\PackageTests\\MultiRepl\\EnabledSucc\\cabal.dist\\work\\dist\\multi-out-2236\\paths\\pkg-a-0-inplace": 
permission denied (The process cannot access the file because it is being used by another process.)
```

We thought that https://github.com/haskell/cabal/pull/9055 would fix issues like this one, alas…

**To Reproduce**

No known way to reproduce it reliably.

**System information**
 - Operating system: Windows
 - GHC 9.4.4
 - cabal-install `master`

**Additional context**

I propose to disable the test on Windows for the time being.

@mpickering as a contributor of this feature and the test: do you have any guesses as to what this may be? Could an upgrade to GHC 9.4.5 help?

/cc @gbaz

**Comment by jasagredo** [comment]
This is fixed in latest versions, at least after #10186
