### ISSUE TITLE
Package in cabal.project not found among others

### ISSUE THREAD

**Issue by danse** [haskell/cabal#9133]
**Describe the bug**
This https://github.com/danse/exmargination/blob/main/cabal.project file allowed me to build its package from other local dependencies, but now it fails finding them. What is strange is that only the `margin` package is not found, where its sdist is in the same state as the others:
```
../collection/dist-newstyle/sdist:
collection-graph-0.1.2.0.tar.gz  noindex.cache

../dam/dist-newstyle/sdist:
dam-0.1.0.0.tar.gz

../hypergraph/dist-newstyle/sdist:
hypergraph-0.1.0.0.tar.gz  noindex.cache

../margin/dist-newstyle/sdist:
margin-0.4.0.0.tar.gz  noindex.cache

../retornado/dist-newstyle/sdist:
noindex.cache  retornado-0.1.1.0.tar.gz

../streamgraph/dist-newstyle/sdist:
noindex.cache  streamgraph-0.5.0.0.tar.gz

../visie/dist-newstyle/sdist:
noindex.cache  visie-0.5.0.1.tar.gz

../web-output/dist-newstyle/sdist:
noindex.cache  web-output-0.4.0.1.tar.gz
```
This is the cabal output
```
[_63] trying: prettyprinter-ansi-terminal:!bench
[_64] trying: prettyprinter-ansi-terminal:!test
[_65] trying: ansi-terminal-1.0 (dependency of prettyprinter-ansi-terminal)
[_66] trying: colour-2.3.6 (dependency of ansi-terminal)
[_67] trying: colour:!test
[_68] trying: ansi-terminal-types-0.11.5 (dependency of ansi-terminal)
[_69] trying: prettyprinter-1.7.1 (dependency of optparse-applicative)
[_70] trying: prettyprinter:!bench
[_71] trying: prettyprinter:!test
[_72] trying: time-1.11.1.1/installed-1.11.1.1 (dependency of exmargination)
[_73] unknown package: margin (dependency of exmargination)
[_73] fail (backjumping, conflict set: exmargination, margin)
[__0] fail (backjumping, conflict set: exmargination, margin)
CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:410:12 in Cabal-3.11.0.0-inplace:Distribution.Simple.Utils
Error: cabal: Could not resolve dependencies:
[__0] trying: exmargination-1.7.0.0 (user goal)
[__1] unknown package: margin (dependency of exmargination)
[__1] fail (backjumping, conflict set: exmargination, margin)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: exmargination (2), margin (1)
```

**To Reproduce**

Unfortunately one should try to install these packages which could be a bit tedious (they depend on other local packages).

**Expected behavior**

Expect all the packages to be found the same way.

**System information**
 - Operating system: Ubuntu 20.4
 - `cabal`, `ghc` versions: Cabal built with master/2564b547e9eb4f823c07310eee2459a4ddd476f2 (just pulled before writing this)

**Comment by danse** [comment]
ghc 9.2.8

**Comment by ulysses4ever** [comment]
Did it use to work with some cabal release? Which one?

**Comment by andreabedini** [comment]
TIL you can do
```
repository retornado
        url: file+noindex:///home/marea/hub/retornado/dist-newstyle/sdist/
```

because the single sdist is enough for local+noindex repositories :exploding_head:

I would have used

```
packages: /home/marea/hub/retornado/dist-newstyle/sdist//retornado-0.1.1.0.tar.gz
```

Anyway, it works for me. Try removing the `noindex.cache` files, they don't really get updated.

**Comment by danse** [comment]
> Did it use to work with some cabal release? Which one?

It actually worked with this same release, but only for some packages

> Anyway, it works for me. Try removing the `noindex.cache` files, they don't really get updated.

That worked! Not sure what could have gone wrong with that one cache. Thanks!

**Comment by andreabedini** [comment]
@danse I ran into this multiple times myself. TBH it's [documented](https://cabal.readthedocs.io/en/stable/config.html#local-no-index-repositories)
> cabal-install creates a .cache file, and will aggressively use its contents if it exists. Therefore if you change the contents of the directory, remember to wipe the cache too.

but I admit it is clearly a sub-optimal experience. I have opened #9136 about this.

**Comment by danse** [comment]
Interesting, i do not think i changed that package after build. Anyway, i will follow up on the other issue
