### ISSUE TITLE
Consider implementing a "remote cache" in the style of Bazel

### ISSUE THREAD

**Issue by andreabedini** [haskell/cabal#9137]
**Describe the feature request**

Bazel implements a [remote caching](https://bazel.build/remote/caching) through
a HTTP protocol that is simple enough to be used with many different
backends.

The [protocol](https://bazel.build/remote/caching#http-caching) is basically a
content-addressed blob store, accessed with GET/PUT requests.

cabal-install could use the same protocol to support a remotely-cached cabal
store. This could be very useful in CI setups.

I am perfectly aware that there are impurities in the hash key used in the
store, especially with respect to external dependencies. I don't think this
invalidates the utility of this feature.

After a first look, the most invasive change would be to generalise
[`StoreDirLayout`](https://hackage.haskell.org/package/cabal-install-3.10.1.0/docs/Distribution-Client-DistDirLayout.html#t:StoreDirLayout)
to be able to perform network IO, perhaps separating it from
[`CabalDirLayout`](https://hackage.haskell.org/package/cabal-install-3.10.1.0/docs/Distribution-Client-DistDirLayout.html#t:CabalDirLayout).
The store logic itself seems to require minor changes, the most notable one
being replacing
[getStoreEntries](https://hackage.haskell.org/package/cabal-install-3.10.1.0/docs/Distribution-Client-Store.html#v:getStoreEntries)
because we will not be able to traverse the remote cache.

**Comment by michaelpj** [comment]
It sounds like this would obsolete https://github.com/haskell-works/cabal-cache ?

**Comment by andreabedini** [comment]
> It sounds like this would obsolete https://github.com/haskell-works/cabal-cache ?

I would say that the existence of cabal-cache proves that this is desierable feature.

The README of cabal-cache mentions https://github.com/haskell/cabal/issues/4097, which is worthy of note here too.

**Comment by TeofilC** [comment]
This looks like a duplicate of https://github.com/haskell/cabal/issues/5582, which also suggests the bazel protocol

**Comment by andreabedini** [comment]
Thanks @TeofilC :facepalm:
Closing as duplicate.
