### ISSUE TITLE
error in error-message

### ISSUE THREAD

**Issue by andrewufrank** [haskell/cabal#9142]
**What is wrong with the docs?**
I got the following error message when `cabal build`

Error: cabal: Cannot test the package xx because none of
the components are available to build: the test suite 'pandoctest' is not
available because the solver picked a plan that does not include the test
suites, perhaps because no such plan exists. To see the error message
explaining the problems with such plans, force the solver to include the test
suites for all packages, by adding the line 'tests: True' to the
'cabal.project.local' file.

The docs say
    The command line variant of this flag is --enable-tests and --disable-tests.

therefore the instructions in the error message are outdated and should be --enable-tests.

unfortunately, these instruction in the docs are probably also not correct and I get: 

Parse of field 'tests' failed (<viewAsFieldDescr>enable-tests ): enable-tests

cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library  
The Glorious Glasgow Haskell Compilation System, version 9.4.5
on a linux debian bookworm

**Comment by gbaz** [comment]
I believe it is the case that `tests: True` is indeed what goes in a project file, and it is set on the command line by running `cabal configure --enable-tests` or `--disable-tests`.

I.e. I believe the error message and the docs are both correct, and if you have not tried them, I would recommend you do.

**Comment by andrewufrank** [comment]
I do not understand my error messages when I try. What is wrong?

my project file starts with:
```
packages: 
    ./*.cabal
tests: True
```
and when I run: 
```
frank@lajatico:~/Workspace11/u4blog/uniform-pandoc$ cabal build
Error: cabal: Error parsing project file
/home/frank/Workspace11/u4blog/uniform-pandoc/cabal.project:3:
Parse of field 'tests' failed (<viewAsFieldDescr>True
...
frank@lajatico:~/Workspace11/u4blog/uniform-pandoc$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.4.5

frank@lajatico:~/Workspace11/u4blog/uniform-pandoc$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 
 
```

**Comment by gbaz** [comment]
I just tested with that precise project file and it works (same version of cabal-install), so I'm not sue what to tell you.

**Comment by andrewufrank** [comment]
Please close. The problem was the place I inserted the `tests: True` statement. it was in the middle of the `packages` stanza. I had after the `./*.cabal` a list of other files needed. If the `tests: True` is at end (or before `packages`) it works. My bad. Thank you for help.
