### ISSUE TITLE
cabal build is looking for a certain happy in the store but it doesn't exist

### ISSUE THREAD

**Issue by tchoutri** [haskell/cabal#9147]
While trying to build https://github.com/flora-pm/flora-server I am encountering the following phenomenon:

```
Failed to build pretty-show-1.10.
Build log (
/home/tchoutri/.cabal/logs/ghc-9.4.5/pretty-show-1.10-1c6c9e4586fd5ea6aee6f8a235bb1719115e54d9ccee645da1118ee28a14893c.log
):
Configuring library for pretty-show-1.10..
Preprocessing library for pretty-show-1.10..
happy: /home/tchoutri/.cabal/store/ghc-9.4.5/happy-1.20.1.1-e-happy-0e8fdc6f91e50c68c174a769e66bf1c3400fe5dd91f7ac6f7a885474e693d6c2/share/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
Error: cabal: Failed to build pretty-show-1.10 (which is required by
test:flora-test from flora-1.0.12). See the build log above for details.
```

And indeed I do not have happy-0e8fd… but I have `happy-1.20.1.1-e-happy-72fb74f9fa836b39a89b766ec5550c7f6a649aa4bd771a592a45c40383a2d058`. And indeed the `72fb…` string appears in the plan.json file, not the `0e8fd…`.

What can I do to solve this?

**Comment by fgaz** [comment]
From the log looks like happy is found and executed, but then fails to find a template file. So we either pass the wrong arguments to happy, or that particular happy is broken. What happens if you try to execute `/home/tchoutri/.cabal/store/ghc-9.4.5/happy-1.20.1.1-e-happy-72fb74f9fa836b39a89b766ec5550c7f6a649aa4bd771a592a45c40383a2d058/bin/happy` manually?

**Comment by gbaz** [comment]
Recall the issue in latest cabal (fixed in next release) that cabal will use happy in the path over happy in the build-tool-depends. Perhaps the one on the path is busted and if you try with no happy in path, things will work correctly?

**Comment by tchoutri** [comment]
Yes that was exactly it! Removing the `happy` I had in ~/.cabal/bin worked. Thanks a lot you two!
