### ISSUE TITLE
cabal init regression: blank project asks to overwrite files

### ISSUE THREAD

**Issue by emilypi** [haskell/cabal#9150]
In a completely new directory, this made my heart jump a bit for Cabal 3.10: 

```
λ П arithmetic → cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2023-07-26T18:33:40Z.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2023-06-22T20:21:41Z'
λ П arithmetic → cabal init
What does the package build:
   1) Library
 * 2) Executable
   3) Library and Executable
   4) Test suite
Your choice? [default: Executable] 1
Do you wish to overwrite existing files (backups will be created) (y/n)? [default: n]
```

Why is it asking to overwrite existing files in a new directory? Why is it doing this *at all* in the interactive case? This is a UI/UX regression.

**Comment by ffaf1** [comment]
5e204b4763c83a1d98d0d6f706ea3ac2cca319db #7959

https://github.com/haskell/cabal/blob/4aa5f88618a29cb53b988a8ae859caa2c70a6e62/cabal-install/src/Distribution/Client/Init/Interactive/Command.hs#L277-L282

Indeed UX could be better.
