### ISSUE TITLE
indented cabal-version

### ISSUE THREAD

**Issue by tonyday567** [haskell/cabal#9156]
With

```
cabal-version:
  3.0
```

at the start of my cabal file I get the following error:

```
Errors encountered when parsing cabal file ./foo.cabal:

foo.cabal:1:1: error:
cabal-version should be at the beginning of the file starting with spec version 2.2. See https://github.com/haskell/cabal/issues/4899

    1 | cabal-version:
      | ^
```

All other fields seem to be able to be on a new line and indented.

Should I consider this an invariant, a feature or a bug?

**Comment by gbaz** [comment]
The cabal-version field is special and documented here: https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-cabal-version

The reason it is special is it is not necessarily parsed by the "standard" parser, as its parse can actually influence the correct way to parse the remainder of the file. Further, it is specified particularly rigidly to allow tools to parse it rapidly on its own.

**Comment by tonyday567** [comment]
OK, that's clear. Thanks!
