### ISSUE TITLE
have some way to express AllRightsReserved in the license field

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#9161]
while we dont want these to end up on hackage, its a recurrent point of confusion for writing proprietary code, at least for me. afaict SPDX explicitly doesn't have such an option

**Comment by ffaf1** [comment]
You might want to use the user defined [`LicenseRef-[idString]`](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/).

```
f@mkiii:/tmp/prova$ cat prova.cabal
cabal-version:   3.0
name:            prova
version:         0.1.0.0
license:         LicenseRef-ProprietaryFoo
author:          Francesco Ariis
maintainer:      fa-ml@ariis.it
build-type:      Simple
extra-doc-files: CHANGELOG.md
category:        Bar
synopsis:        a syn
description:     this is a longer desc

executable prova
    main-is:          Main.hs
    build-depends:    base == 4.*
    hs-source-dirs:   app
    default-language: Haskell2010
f@mkiii:/tmp/prova$ cabal check
Warning: this is a debug build of cabal-install with assertions enabled.
No errors or warnings could be found in the package.
f@mkiii:/tmp/prova$ cabal --version
cabal-install version 3.11
compiled using version 3.11.0.0 of the Cabal library
```

**Comment by ffaf1** [comment]
See also #5697

**Comment by fgaz** [comment]
"All right reserved" is the default state of a work, a license can relax this state. So you want to use `NONE` or omit the field entirely. There's also `LicenseRef`, as @ffaf1 wrote. See #5697 for more. The init menu and documentation about this could be improved, see the last comments of #5697
