### ISSUE TITLE
Is Nix integration broken?

### ISSUE THREAD

**Issue by yvan-sraka** [haskell/cabal#9165]
**Describe the bug**
I can't manage, following [the Nix Integration official tutorial](https://cabal.readthedocs.io/en/3.10/nix-integration.html), to make it works. Since I use Nix as my daily driver for years, I wonder, it is the documentation that is really misleading? Or is the feature broken, and [no one reported it before](https://github.com/haskell/cabal/labels/cabal-install%3A%20nix%20integration) because there is no user of it?

**To Reproduce**
I wanted to give Cabal Nix integration a try, so [I created a dummy project](https://github.com/yvan-sraka/is-cabal-nix-integration-broken) with a `shell.nix` that set an environment variable that a `Setup.hs` will try to read.

- `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    shellHook = "touch NIX_SHELL_HOOK_CALLED";
    VARIABLE_SET_BY_NIX_SHELL = "Hello from Nix shell!";
}
```
- `Setup.hs`:
```haskell
import Distribution.Simple
import System.Environment

main :: IO ()
main = do
    x <- getEnv "VARIABLE_SET_BY_NIX_SHELL"
    putStrLn x
    defaultMain
```

So, on a machine with Cabal and GHC installed (or in a developer shell spawned with `nix-shell -p cabal-install ghc`), you can build the project with `nix-shell --run "cabal build"` or the new experimental command `nix develop -c cabal build`. It works, and the `shell.nix` does 2 others side effect for debugging: it prints `Hello from Nix shell!` (it's `Setup.hs` that reads and displays the ENV variable `VARIABLE_SET_BY_NIX_SHELL`) on standard output and touch the file `NIX_SHELL_HOOK_CALLED`.

So, then if I understand well the Nix integration documentation, I could replace the previous commands by just `cabal --enable-nix build` or `cabal --nix=True build`, right? Both of that commands will not trigger any of the side effects defined in the `shell.nix` and so the build will fail:

```
$ cabal --enable-nix build
Resolving dependencies...
Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - test-0.1.0.0 (exe:test) (first run)
[1 of 1] Compiling Main             ( /home/yvan/is-cabal-nix-integration-broken/dist-newstyle/build/x86_64-linux/ghc-9.2.8/test-0.1.0.0/setup/setup.hs, /home/yvan/is-cabal-nix-integration-broken/dist-newstyle/build/x86_64-linux/ghc-9.2.8/test-0.1.0.0/setup/Main.o )
Linking /home/yvan/is-cabal-nix-integration-broken/dist-newstyle/build/x86_64-linux/ghc-9.2.8/test-0.1.0.0/setup/setup ...
setup: VARIABLE_SET_BY_NIX_SHELL: getEnv: does not exist (no environment variable)
Error: cabal: Failed to build test-0.1.0.0. The failure occurred during the
configure step.
```

**Expected behavior**
`cabal --enable-nix build` and `cabal --nix=True build` should have the same behavior as `nix-shell --run "cabal build"` or `nix develop -c cabal build`.

**System information**
```
$ uname -a
Linux X230 6.1.42 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 27 06:50:53 UTC 2023 x86_64 GNU/Linux
$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.8
```

**Additional context**
This issue was mentioned in the last _“cabal devs fortnightly chat”_, and the consensus was to depreciated progressively the feature. I will open a PR with a plan for that! :)

**Comment by ulysses4ever** [comment]
Hey! It had never work with v2 commands (which is what you you get when you say `cabal build` these days). Probably a dup of  #6444.
