### ISSUE TITLE
Modular solver needs support for ghc-6.12's base-wrapping

### ISSUE THREAD

**Issue by bos** [haskell/cabal#918]
(Imported from [Trac #928](http://hackage.haskell.org/trac/hackage/ticket/928), reported by @kosmikus on 2012-03-11)

In ghc-6.12, we had the situation that base-3 was a wrapper around base-4. The modular solver can currently not handle that situation, thereby making it mostly useless when used with ghc-6.12. For later ghc versions, this no longer occurs, thus isn't an issue. This is one reason why the modular solver currently is not the default.

Options:

<ul><li>Add a hack to the modular solver to deal with it, much like it is done in the topdown solver.
</li><li>Make the default solver being used dependent on the version of ghc (but that might be confusing).
</li></ul>

**Comment by kosmikus** [comment]
This should be fixed by Edsko's recent changes to the modular solver.
