### ISSUE TITLE
Cabal-syntax/src/Distribution/Fields/Lexer.x and .hs exist

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9196]
Since 0ab5571e81be89eb9f2ff0e6f51570f2b93ccd08 there is both a .x file and .hs file for the Distribution.Fields.Lexer module.

I think there should only be one file committed as otherwise they seem likely to get out of sync. 

Now there is a build-tool-depends listed on Alex, I imagine the correct fix is to delete Distribution/Fields/Lexer.hs

cc @andreabedini

**Comment by andreabedini** [comment]
Absolutely right. I had just noticed it a couple of days ago. I'll push a pr to remove the old file.
