### ISSUE TITLE
--semaphore is not compatible with build-type: Custom

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#9197]
**Describe the bug**
Cabal HEAD fails to build any package with `build-type: Custom` when `-j --semaphore` is passed.

**To Reproduce**

```
$ cabal unpack ghc-paths-0.1.0.12 && cd ghc-paths-0.1.0.12 && cabal build -w ghc-9.8.0.20230809 -j --semaphore --allow-newer
Resolving dependencies...
Build profile: -w ghc-9.8.0.20230809 -O1
In order, the following will be built (use -v for more details):
 - ghc-paths-0.1.0.12 (lib:ghc-paths) (first run)
Created semaphore called cabal_semaphore_3 with 8 slots.
[1 of 2] Compiling Main             ( /private/tmp/ghc-paths-0.1.0.12/dist-newstyle/build/aarch64-osx/ghc-9.8.0.20230809/ghc-paths-0.1.0.12/setup/setup.hs, /private/tmp/ghc-paths-0.1.0.12/dist-newstyle/build/aarch64-osx/ghc-9.8.0.20230809/ghc-paths-0.1.0.12/setup/Main.o )
[2 of 2] Linking /private/tmp/ghc-paths-0.1.0.12/dist-newstyle/build/aarch64-osx/ghc-9.8.0.20230809/ghc-paths-0.1.0.12/setup/setup
Configuring ghc-paths-0.1.0.12...
unrecognized 'build' option `--semaphore=cabal_semaphore_3'
Error: cabal: Failed to build ghc-paths-0.1.0.12.
```

**Expected behavior**
The build should complete successfully. If I remove `-j --semaphore`, all works well.

**System information**
 - Operating system: macOS
 - `cabal`: HEAD (41225bb43)
 - `ghc`: 9.8.0.20230809

**Comment by Bodigrim** [comment]
If the full support is challenging in the run down towards Cabal 3.12 release, IMHO it would be fine for `defaultMainWithHooks` ignore any `--semaphore=...` arguments for now. Just do not fail please :) 

CC @sheaf @mpickering @fgaz.

**Comment by mpickering** [comment]
I think the problem is just the version number on the guard in `setupHsBuildFlags`. 

Perhaps that should be `3,11,0,0` rather than `3,9,0,0`. Could a Cabal developer please comment about what the first version which `--semaphore` is supported is going to be?

**Comment by Bodigrim** [comment]
@Mikolaj @Kleidukos @ulysses4ever could someone please chime in?

**Comment by ulysses4ever** [comment]
3.12

**Comment by Mikolaj** [comment]
> 3.12

Which means that `3,11,0,0` (the version of master until we release 3.12) should be fine if @mpickering's diagnosis is correct. Any volunteers for a PR?

**Comment by mpickering** [comment]
https://github.com/haskell/cabal/pull/9221
