### ISSUE TITLE
cabal test is dropping --test-option flags

### ISSUE THREAD

**Issue by bos** [haskell/cabal#920]
(Imported from [Trac #930](http://hackage.haskell.org/trac/hackage/ticket/930), reported by @tibbe on 2012-03-12)

Adding two <tt>--test-option</tt> flags doesn't work correctly. For example, this

<pre class="wiki">cabal test --test-option=--plain
</pre>causes cabal to (correctly) pass the <tt>--plain</tt> flag to the underlying test-framework binary. However, this

<pre class="wiki">cabal test --test-option=--plain --test-option=--jxml=dist/unit-tests.xml
</pre>drops it on the ground. Some debug output

<pre class="wiki">cabal test --test-option=--plain --test-option=--jxml=dist/unit-tests.xml -v3
Using external setup method with build-type Custom
Creating ./dist/setup (and its parents)
Using Cabal library version 1.14.0
Using ./Setup.hs as setup script.
./dist/setup/setup test --verbose=3 --test-options=--jxml=dist/unit-tests.xml
--test-option=--jxml=dist/unit-tests.xml
</pre>There looks like there's an extra newline in the <tt>./dist/setup/setup</tt> invocation, perhaps that's the issue?

The problem can be reproduced on Cabal's own test suite.

**Comment by harpocrates** [comment]
I can fix this as part of https://github.com/haskell/cabal/pull/5455. What is the behaviour we'd want here? Should `--test-options` and `--test-option` always just add new arguments to the existing ones?

So should

     cabal test --test-option=--opt1 \
                --test-options="--opt2 --opt3" \
                --test-option=--opt4 \
                --test-options=--opt5

be equivalent to

     cabal test --test-options="--opt1 --opt2 --opt3 --opt4 --opt5"

Also, `benchmark-option` and `benchmark-options` suffer from the same problem. Even more generally, `programDbOption` suffers from this too (ex: `cabal new-haddock --haddock-option "--help" --haddock-option "--html"` discards `--help`).

**Comment by harpocrates** [comment]
On closer inspection, it looks like this is already fixed. In fact, the one thing I tried  (`cabal new-haddock --haddock-option "--help" --haddock-option "--html"`) is the only thing that is broken. The fix is pretty easy too: https://github.com/haskell/cabal/pull/5512.

Shall we close this?
