### ISSUE TITLE
`cabal init` seems set `--non-interactive` as default above cabal 3.6.2.0,not set `--interactive` as default

### ISSUE THREAD

**Issue by WendaoLee** [haskell/cabal#9208]
**What is wrong with the docs?**
 In the [developing-packages](https://github.com/haskell/cabal/blob/6c95f3fee3cdee859704b6476646cefd4628a850/doc/developing-packages.rst),chapter  `Using cabal init`,it said:

```markdown
The cabal init command creates the necessary files for a Cabal package, it has both an --interactive (default) and --non-interactive mode. 
```

But in my cabal (version 3.6.2.0),it seems like `cabal init` works like `--non-interactive` as default,not set `--interactive` as default .

**Additional context**
My test:
```pwh
C:\Users\LeeWe\Documents\GitHub\alchemy-starts-wechat\cli\test-default>cabal init

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Generating test-default.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
```
The `--non-interactive`:
```pwh
C:\Users\LeeWe\Documents\GitHub\alchemy-starts-wechat\cli\test-non-interactive>cabal init --non-interactive

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Generating test-non-interactive.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
```

The `--interactive`:
```pwh
C:\Users\LeeWe\Documents\GitHub\alchemy-starts-wechat\cli\test>cabal init --interactive
Should I generate a simple project with sensible defaults? [default: y] n
What does the package build:
   1) Executable
   2) Library
   3) Library and Executable
Your choice? 3
What is the main module of the executable:
 * 1) Main.hs (does not yet exist, but will be created)
   2) Main.lhs (does not yet exist, but will be created)
   3) Other (specify)
...
```

It seems like a bug in documents.👀Well,if it is,would you like to fix that?Or I can submit pr for it if maintainer not has time to fix this little piece.

**Comment by ffaf1** [comment]
`cabal init` is interactive by default since #7551:

```
f@mkiii:/tmp/prova$ cabal init
Warning: this is a debug build of cabal-install with assertions enabled.
What does the package build:
   1) Library
 * 2) Executable
   3) Library and Executable
   4) Test suite
Your choice? [default: Executable] ^C
```

Cabal 3.6.2.0 was released before that, I think you are checking the new documentation instead of the old one.
[Revelant section in 3.6.0.0](https://cabal.readthedocs.io/en/3.6/developing-packages.html#using-cabal-init) does not state anything about defaults.

Does this answer your question? If so, feel free to close the report.

**Comment by WendaoLee** [comment]
> `cabal init` is interactive by default since #7551:
> 
> ```
> f@mkiii:/tmp/prova$ cabal init
> Warning: this is a debug build of cabal-install with assertions enabled.
> What does the package build:
>    1) Library
>  * 2) Executable
>    3) Library and Executable
>    4) Test suite
> Your choice? [default: Executable] ^C
> ```
> 
> Cabal 3.6.2.0 was released before that, I think you are checking the new documentation instead of the old one. [Revelant section in 3.6.0.0](https://cabal.readthedocs.io/en/3.6/developing-packages.html#using-cabal-init) does not state anything about defaults.
> 
> Does this answer your question? If so, feel free to close the report.

Thank you for your reply!😽I get it.
