### ISSUE TITLE
Support building source trees with many packages

### ISSUE THREAD

**Issue by bos** [haskell/cabal#921]
(Imported from [Trac #931](http://hackage.haskell.org/trac/hackage/ticket/931), reported by @tibbe on 2012-03-12)

A not uncommon use case is building a package against a set of dependencies that exist in (unreleased) source form. For example, given two packages:

<pre class="wiki">$ ls
hashable
unordered-containers
</pre>I'd like to be able to

<pre class="wiki">$ cd unordered-containers
cabal build --root=..
</pre>Cabal should then recursively traverse directories from <tt>--root</tt>, looking for .cabal files to use when fulfilling dependencies (i.e. in this case it'd find <tt>hashable</tt>.) Those dependencies should also be marked as preferred to any Hackage versions of the package with the same version number.

It'd also be convenient to add several <tt>--root</tt> flags, so one can specify specific packages to use in source form (without using e.g. the user's complete <tt>~/src</tt> directory.)

<pre class="wiki">$ cd unordered-containers
cabal build --root=../hashable --root=../text
</pre>

**Comment by quasicomputational** [comment]
This is fixed! `cabal.project` files are a thing.
