### ISSUE TITLE
Absence of `--ignore-expiry` option in `cabal v2-update` incorrectly ignores signature expiry

### ISSUE THREAD

**Issue by gksato** [haskell/cabal#9211]
I've examined the source code (though I haven't tested this behavior) and it appears that the `--ignore-expiry` option for `cabal v2-update` works in the opposite way than one would expect. Specifically, it seems that `cabal-install` checks for the expiry of a package repository's signature only when the `--ignore-expiry` option is *present*. Conversely, it ignores the expiry check if the option is *absent*.

Here is the relevant code from the current master branch:

https://github.com/haskell/cabal/blob/fbd964202c134bedc13ac7832722c75e68c1ca4f/cabal-install/src/Distribution/Client/CmdUpdate.hs#L268-L272

In this section, it appears that the current time for verification (`ce`) is passed only if the flag for the `--ignore-expiry` option is set to **TRUE**. The [`Hackage.Security.Client.checkForUpdates`](https://hackage.haskell.org/package/hackage-security-0.6.2.3/docs/Hackage-Security-Client.html#v:checkForUpdates) documentation states that:

> You should pass `Nothing` for the `UTCTime` _only_ under exceptional circumstances (such as when the main server is down for longer than the expiry dates used in the timestamp files on mirrors).

I've touched upon this in issue #8918, but I believe this warrants its own separate issue, hence this post. I must note that I'm not entirely certain that my interpretation is correct. This is primarily because I wasn't able to think of a way to test this behavior without an actual example— I have not encountered any repositories with an expired signature. Confirmation that this is an actual bug in the implementation would be appreciated. The fix would likely be as simple as swapping the `then` and `else` clauses in the code.

**Comment by gbaz** [comment]
Thanks for continuing to raise this! Since the discussion in 8918 we've been looking into this and will address it in the next release. For now I'll close it this ticket and leave that issue as the place for it. I was going to drop you a line about this but couldn't find an email.

**Comment by gksato** [comment]
Oh I see. Thanks for your work!
