### ISSUE TITLE
cabal configure doesn't suggest cabal install --only-dependencies

### ISSUE THREAD

**Issue by bos** [haskell/cabal#923]
(Imported from [Trac #933](http://hackage.haskell.org/trac/hackage/ticket/933), reported by guest on 2012-03-14)

When running 'cabal configure' on a package that has missing dependencies, cabal fails to point out that the dependencies can be installed by running

cabal install --only-dependencies

When cabal is used by millions of programmers, this will cause $1bn in lost productivity.

**Comment by BardurArantsson** [comment]
This is completely obsolete, given sandboxes. Suggest closing.
