### ISSUE TITLE
implementation of Distribution.Version.invertVersionRange

### ISSUE THREAD

**Issue by bos** [haskell/cabal#925]
(Imported from [Trac #935](http://hackage.haskell.org/trac/hackage/ticket/935), reported by dsf on 2012-03-23)

Attached is an implementation of a function to return the complement of a `VersionRange?`.

**Comment by ddssff** [comment]
Does this test suite still exist?  I'm having trouble locating it in the current source tree.

**Comment by 23Skidoo** [comment]
@ddssff Looks like @tibbe removed it in 1e2ea93c3d509347fd990bdb3f947e72bc2b69de and 4eb213343b347042889bd215d422d5c506ed53b5.

**Comment by 23Skidoo** [comment]
Fixed by #2505.
