### ISSUE TITLE
Solver error message: suggest cabal update

### ISSUE THREAD

**Issue by michaelpj** [haskell/cabal#9255]
**Describe the feature request**

When the solver fails because a constraint requires a version that is strictly newer than all the available versions, suggest that the user might need to run `cabal update`.

**Additional context**

It's obviously hard for cabal to ever know that we're missing a package version, but this situation is pretty suggestive. 

Example of a confused user: https://github.com/haskell/haskell-language-server/pull/3771#issuecomment-1717183850

**Comment by grayjay** [comment]
This looks like a duplicate of #8922.

**Comment by michaelpj** [comment]
Yep, thanks.
