### ISSUE TITLE
Cannot install packages from tarball

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [haskell/cabal#9261]
**Description**
Cabal failed to install packages from local tarbal

**To Reproduce**

```
$ cabal install <package>.tar.gz
```

**System information**
 - Linux
 - Cabal 3.10.1.0

**Error log**
```
Error: cabal: Invalid package ID: <package>.tar.gz
"<eitherParsec>" (line 1, column 21):
unexpected all digits or a dot in a portion of package name
expecting "-"
```

**Comment by ffaf1** [comment]
From `cabal install --help`

```
Examples:
  cabal install
    Install the package in the current directory
  cabal install pkgname
    Install the package named pkgname (fetching it from hackage if necessary)
  cabal install ./pkgfoo
    Install the package in the ./pkgfoo directory
```

You are not supposed to pass a `.tar.gz` to `cabal install`. If any part of the documentation gave you the impression you could, please point it to us so we can fix it.

**Comment by k355l3r-5yndr0m3** [comment]
https://cabal.readthedocs.io/en/stable/intro.html#a-tool-for-working-with-packages
Here the incorrect segment, and it looks like the url example is also incorrect.

**Comment by ffaf1** [comment]
Thanks, I admit I am quite surprised. I will open a PR soon.

**Comment by fgaz** [comment]
Probably a duplicate of #7360

**Comment by k355l3r-5yndr0m3** [comment]
Yeah, the proper way is to prepend `file://` to the path although it still err identically to #7360. Somebody should also edit the doc to reflect this.

**Comment by dcoutts** [comment]
I think the explanation here is that the old v1 commands did indeed work with local tarballs and remote tarbal URLs.

For the v2 project style, it is possible (IIRC) to list local and remote tarballs in the project definition file, but then one refers to them thereafter by their package name for building with `build` etc.

The root issue here is that with the v2 project style, it becomes unclear in the UI what "immediate mode"  "cabal install this" commands should mean, especially if the thing referred to is not currently defined within the project.
