### ISSUE TITLE
warnOnTwoConfigs is overzealous on Windows

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#9277]
https://github.com/haskell/cabal/blob/c4e1268b8800175657a991cdf56cc8e0b96d3378/cabal-install/src/Distribution/Client/Config.hs#L729-L744

This is wrong on Windows: 

* [`getAppUserDataDirectory`](https://hackage.haskell.org/package/directory-1.3.7.1/docs/System-Directory.html#v:getAppUserDataDirectory) `"cabal"` returns `C:/Users/<user>/AppData/Roaming/cabal`.
* [`getXdgDirectory`](https://hackage.haskell.org/package/directory-1.3.7.1/docs/System-Directory-Internal.html#v:getXdgDirectoryFallback) `XdgConfig ("cabal" </> "config")`, unless XDG environment variables are set (and they are not by default), returns `C:/Users/<user>/AppData/Roaming/cabal/config`, in the very same folder.

Thus both paths exist and everyone is shown a very confusing warning:
```
Both C:/Users/<user>/AppData/Roaming/cabal 
and C:/Users/<user>/AppData/Roaming/cabal/config exist - ignoring the former.
It is advisable to remove one of them. 
In that case, we will use the remaining one by default (unless '$CABAL_DIR' is explicitly set)."
```

I cannot remove one of them, they are the same location. 

This is easy to fix, but I'm unpleasantly surprised that I'm the first person to test Cabal HEAD on Windows. If I may suggest, it would be nice to review that XDG business works outside of Linux paradise.

**Comment by fgaz** [comment]
Looks like this also affects 3.10 :-/ #8971

**Comment by Mikolaj** [comment]
> This is easy to fix, but I'm unpleasantly surprised that I'm the first person to test Cabal HEAD on Windows. If I may suggest, it would be nice to review that XDG business works outside of Linux paradise.

Yes, we are short on the precious resource of Windows developers and testers. We'll ask especially for WIndows testing once we announce unofficial 3.10.2.0 alpha binaries.
