### ISSUE TITLE
Add a ghcup metadata-generating script to help releasing cabal

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#9298]
**Describe the feature request**

We badly need a script that helps the release manager generate ghcup metadata (hashes, etc.). See a similar GHC script mentioned at https://github.com/haskell/ghcup-metadata/pull/127#issuecomment-1741778005

Related: https://github.com/haskell/cabal/issues/8932

**Comment by arjunkathuria** [comment]
Hi @Mikolaj, i can look into this one.

i've worked on GHCup with Julian (@hasufell) and am vaguely familiar with the metadata structure.

What are the general requirements here?

**Comment by hasufell** [comment]
https://github.com/haskell/haskell-language-server/blob/master/scripts/release/create-yaml-snippet.sh

This is a simplified version and still needs manual adjustments.

**Comment by arjunkathuria** [comment]
That's a great reference, thanks Julian!

**Comment by Mikolaj** [comment]
Wonderful. Thank you so much! Wiring in @Kleidukos, who struggled through the last cabal release manual metadata generation.

**Comment by arjunkathuria** [comment]
Added a draft PR with the initial working version of the script referenced from the script linked above by Julian with it's current output.

cc: @hasufell @Mikolaj
