### ISSUE TITLE
Release CI on GitLab: Darwin is broken

### ISSUE THREAD

**Issue by chreekat** [haskell/cabal#9299]
Due (I presume) to recent updates to the Darwin runners operated by @angerman, the poor neglected release CI on GitLab is broken.

Jobs fail like

```Error: 'git' must be installed and in your PATH!```
https://gitlab.haskell.org/haskell/cabal/-/jobs/1680702

The problem may be that `/usr/bin/git` is not functional.

```
-sh-3.2# /usr/bin/git
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
```
(The above reported by Moritz).

I tried working around this by putting the Nix-installed tools on the PATH, but it didn't help. (The job linked above has the attempted fix already.)

So, this is still unresolved.

I don't have access to the Darwin runners right now. Due to timezones, we may need to wait a while for this to get fixed.

**Comment by chreekat** [comment]
This has been fixed. :)

**Comment by chreekat** [comment]
The cause was a reprovisioning of the runners that went slightly awry.

**Comment by Mikolaj** [comment]
Thank you!
