### ISSUE TITLE
GitLab CI: i386-deb9 job is failing

### ISSUE THREAD

**Issue by chreekat** [haskell/cabal#9304]
Example job: https://gitlab.haskell.org/haskell/cabal/-/jobs/1681282

Failure message:

```
[ Error ] [ttps://errors.haskell.org/messages/GHCup-07140HCup-07140] Both installation and setting the tool failed. Install error was: Unable to find a download for the requested version/distro. 
[ ...   ] Set error was: The version 2.11.1 of the tool stack is not installed.
[ Error ] Also check the logs in /builds/haskell/cabal/toolchain/.ghcup/logs
"ghcup --metadata-fetching-mode=Strict --cache install stack" failed!
Stack installation failed
```

@hasufell what could cause this? This seemed to work fine a week ago.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/blob/374a68e0746d65077d5e41bc8fe362b9b1a7a6d5/ghcup-0.0.7.yaml#L5757

There never have been i386 stack binaries. 

Set `BOOTSTRAP_HASKELL_INSTALL_NO_STACK=yes` to skip stack installation.

**Comment by chreekat** [comment]
Ok, interesting. I'll double check my assumptions.

**Comment by chreekat** [comment]
https://gitlab.haskell.org/haskell/cabal/-/jobs/1677635 seems to think there *were* i386 stack binaries.

They were the unofficial ones. I guess they're gone now?

```
[ Info  ] downloading: https://downloads.haskell.org/ghcup/unofficial-bindists/stack/2.9.3/stack-2.9.3-linux-i386.tar.gz as file /builds/haskell/cabal/toolchain/.ghcup/cache/stack-2.9.3-linux-i386.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.1M  100 10.1M    0     0  63.0M      0 --:--:-- --:--:-- --:--:-- 63.4M
[ Info  ] verifying digest of: stack-2.9.3-linux-i386.tar.gz
[ Info  ] Unpacking: stack-2.9.3-linux-i386.tar.gz to /builds/haskell/cabal/toolchain/.ghcup/tmp/ghcup-95c80961
[ Info  ] Installing stack
[ Info  ] Stack installation successful
[ Info  ] Stack manages GHC versions internally by default. To improve integration, please visit:
[ ...   ]   https://www.haskell.org/ghcup/guide/#stack-integration
[ ...   ] 
[ ...   ] Also check out:
[ ...   ]   https://docs.haskellstack.org/en/stable/yaml_configuration
[ ...   ] 
```

**Comment by chreekat** [comment]
At any rate, the toolchain to build Cabal doesn't need Stack, so I can add `BOOTSTRAP_HASKELL_INSTALL_NO_STACK=yes` everywhere.

**Comment by hasufell** [comment]
> They were the unofficial ones. I guess they're gone now?

Yes, I don't do those anymore. Upstream business.

**Comment by andreabedini** [comment]
I don't want to sound rude but why are GHC CI issues reported here? :)

The OP in particular shows that GHCup could not install stack. How is this related to cabal?

**Comment by hasufell** [comment]
> I don't want to sound rude but why are GHC CI issues reported here? :)

That is the cabal release CI. I think that is fairly relevant, unless cabal devs don't want to cut bindists anymore.

**Comment by Mikolaj** [comment]
@andreabedini: please catch me on #hackage for the explanation of our test vs release CI infrastructures. Re-opening.

**Comment by andreabedini** [comment]
@hasufell I am sorry. This was a big blunder on my part.
@Mikolaj I will make sure I do early next week. Thank you.

**Comment by chreekat** [comment]
@andreabedini no hard feelings on my part! It's a funny situation that I myself have only recently been inducted into. :D 

Really doesn't help when I sometimes typo GitHub as GitLab or vice versa...

**Comment by chreekat** [comment]
Fixed in https://github.com/haskell/cabal/pull/9328
