### ISSUE TITLE
cabal.project: allow-newer per package

### ISSUE THREAD

**Issue by amigalemming** [haskell/cabal#9313]
I like to have an `allow-newer` field for specific packages.
Currently I can specify `allow-newer` only globally.
This leads to the following problem:
Say, I have package `A` with constraint `base < 4.18` and package `B` with constraint `base < 4.19`, but there is an older version of `B` with constraint `base < 4.18`.
I want to build newest versions of both `A` and `B` with `base-4.18`. I set `allow-newer: base` globally in `cabal.project`. However, now the Cabal resolver sometimes chooses the old version of `B` because that becomes feasible now.

To prevent this I like to write to `cabal.project`:
~~~~
package A
  allow-newer: base
~~~~

**Comment by amigalemming** [comment]
I see in another ticket that we already have this feature but with different syntax:
https://github.com/haskell/cabal/issues/8426

I think the syntax `--allow-newer pkg0:dep0,pkg1:dep1` was chosen for consistency with the command line, but it is unexpected that the per-package syntax is not available.

**Comment by andreabedini** [comment]
It's already possible, see https://cabal.readthedocs.io/en/stable/cabal-project.html#cfg-flag---allow-newer

> 
> For example, to relax pkgs [build-depends](https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-build-depends) upper bound on dep-pkg, write a scoped package name of the form:
> 
> allow-newer: pkg:dep-pkg
> 
> If the scope shall be limited to specific releases of pkg, the extended form as in
> 
> allow-newer: pkg-1.2.3:dep-pkg, pkg-1.1.2:dep-pkg
> 
> can be used to limit the relaxation of dependencies on dep-pkg by the pkg-1.2.3 and pkg-1.1.2 releases only.
