### ISSUE TITLE
Cabal-3.10.2.0 is bundled with GHC-9.8.1 but not uploaded to Hackage

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#9333]
is there an ETA when the `Cabal(-syntax)` will be uploaded to Hackage?

**Comment by Bodigrim** [comment]
Looking at `ghcup` issue tracker, there might be a reason to delay `cabal-install-3.10.2.0`. But there is no point not to release `Cabal-3.10.2.0` - it must be identical to one bundled with GHC 9.8.1 anyway, even if there are issues with.

**Comment by phadej** [comment]
>  it must be identical to one bundled with GHC 9.8.1 anyway, even if there are issues with.

Exactly.

**Comment by Bodigrim** [comment]
@Kleidukos @ulysses4ever @andreabedini @Mikolaj what's blocking this?

Also, what's the status of https://downloads.haskell.org/cabal/Cabal-3.10.2.0/ ? The modification date is Sep 6, so it could not be 15a0010461c3d181f30fbbf5980bf75945d6df2a (which is the commit [GHC 9.8 was built against](https://gitlab.haskell.org/ghc/ghc/-/commit/c83b768856426d500d480ad665ee55958aec7ebe)).

**Comment by Bodigrim** [comment]
And there is also https://hackage.haskell.org/package/Cabal-3.10.2.0/candidate, uploaded Aug 26, which, judging from dates, is different both from https://downloads.haskell.org/cabal/Cabal-3.10.2.0/ and Cabal-3.10.2.0 bundled with GHC 9.8.1.

For the reference, git history of `Cabal-3.10`: https://github.com/haskell/cabal/commits/3.10/Cabal

**Comment by ulysses4ever** [comment]
@Bodigrim i don’t have a power over this, unfortunately. Sorry. I did what I could, which is I raised this issue on Matrix, where Gershom agreed that this should have been done already. The ball is in the release managers’ quarters (Mikolaj and Hecaté). If they need any help, I have cycles to spare on this.

**Comment by andreabedini** [comment]
Same as @ulysses4ever.

**Comment by Mikolaj** [comment]
@Kleidukos: can @ulysses4ever and @andreabedini help? Is this down to the Windows breakage and the need to repeat most of the release checklist steps? I think we dogfooded enough (and haven't discovered the Windows bug, unsurprisingly) that we could release Cabal already and cabal-install as soon we toss a coin about whether to ignore the Windows issue and have no "recommended" 3.8.* release in ghcup ever.

**Comment by phadej** [comment]
This issue is about `Cabal` the library.

As @Bodigrim mentions in https://github.com/haskell/cabal/issues/9333#issuecomment-1765419378

GHC is released and bundles `Cabal-3.10.2.0` the release uploaded to Hackage should be at the exact same commit. (Or then you don't upload that version at all, and rather upload it under some other version. `3.10.2.1` or `3.10.3.0`).

**Comment by Kleidukos** [comment]
> The modification date is Sep 6, so it could not be https://github.com/haskell/cabal/commit/15a0010461c3d181f30fbbf5980bf75945d6df2a (which is the commit [GHC 9.8 was built against](https://gitlab.haskell.org/ghc/ghc/-/commit/c83b768856426d500d480ad665ee55958aec7ebe)).

@Bodigrim It's another problem with the way the CDN accepts PURGE HTTP requests (sometimes it doesn't).

**Comment by phadej** [comment]
What worse, it seems that GHC bundles a commit three commits further from **existing** `Cabal-v3.10.2.0` tag (as GHC de-facto distributes that version).

That drift commit is due `text-2.1` and `bytestring-0.12`, so https://gitlab.haskell.org/ghc/ghc/-/issues/23926 alone cannot be blamed.

**Comment by andreabedini** [comment]
As @ulysses4ever says our 3.10.2.0 tag is:
```
commit 15a0010461c3d181f30fbbf5980bf75945d6df2a (tag: cabal-install-v3.10.2.0, tag: cabal-install-solver-v3.10.2.0, tag: Cabal-v3.10.2.0, tag: Cabal-syntax-v3.10.2.0)
```
Which corresponds to what was shipped with GHC. AFAIU the source distributions can be published even if the binary distributions are not quite ready. Bug can be fixed in a follow up release.

Just as a note: solver failures you might run into are due to conservative bounds of v3.10.1.0 that exclude ghc-9.8.1 boot packages. You can go around them with `--allow-newer=Cabal{,-syntax}:{bytestring,deepseq,text}` but of course we should make a revision ASAP.

**Comment by Kleidukos** [comment]
okay, https://hackage.haskell.org/package/Cabal-3.10.2.0 has been published on the `15a0010461c3d181f30fbbf5980bf75945d6df2a` commit.

**Comment by nomeata** [comment]
Thanks a lot! Don’t forget Cabal-syntax.

**Comment by Kleidukos** [comment]
Yep it's published too: https://hackage.haskell.org/package/Cabal-syntax-3.10.2.0

**Comment by ulysses4ever** [comment]
Thank you, @Kleidukos!

The ticket can be closed, I assume?

**Comment by Kleidukos** [comment]
I'll let @phadej close the ticket if he is statisfied.

**Comment by andreabedini** [comment]
Oleg had the chance, I'll close :relaxed: :heart:
