### ISSUE TITLE
cabal: Add v2 implementation of outdated command

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#9345]
Currently the `cabal outdated` command only works in a directory which contains `<pkg>.cabal` file.

When this issue is complete:
- `v1-outdated` which sound work as the current version of that command.
- `v2-outdated` which would work where the directory it is run in has a `cabal.project` file.

**Comment by andreabedini** [comment]
We already have https://github.com/haskell/cabal/issues/8283

**Comment by andreabedini** [comment]
and before that we had https://github.com/haskell/cabal/issues/4831 :joy:

**Comment by erikd** [comment]
Closing in favor of https://github.com/haskell/cabal/issues/8283 .

**Comment by gbaz** [comment]
did you mean to reopen?

**Comment by Mikolaj** [comment]
Let's assume that was a typo. Closing.
