### ISSUE TITLE
`register` fails if `-fplugin=Foo` is used in `ghc-options:`

### ISSUE THREAD

**Issue by hamishmack** [haskell/cabal#9375]
With `ghc >=9.6` `--abi-hash` initialises plugins and will fail if a module in `-fplugin=Foo`.

```
$ ghc-9.4.7 --abi-hash -fplugin=Foo
921dcb31e865da25523dc30d4957f9c4
$ ghc-9.6.3 --abi-hash -fplugin=Foo
<command line>: Could not find module ‘Foo’
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

This causes problems because the fix for #3633 removes the package DB from the arguments passed when calling `ghc --abi-hash`.

The code is [here](https://github.com/haskell/cabal/blob/ac017649d8e56854898a5aea005dfd6a1e9a82df/Cabal/src/Distribution/Simple/GHC.hs#L2061-L2068):
```
    vanillaArgs =
      -- Package DBs unnecessary, and break ghc-cabal. See #3633
      -- BUT, put at least the global database so that 7.4 doesn't
      -- break.
      vanillaArgs0
        { ghcOptPackageDBs = [GlobalPackageDB]
        , ghcOptPackages = mempty
        }
```

To reproduce this issue with `cabal-install` and `ghc` `9.6.3` in the path:
```
$ cat test.cabal
cabal-version:      3.4
name:               test
version:            0.1.0.0
build-type:         Simple

library
    exposed-modules:  MyLib
    build-depends:    base, polysemy, polysemy-plugin
    ghc-options:      -Wall -fplugin=Polysemy.Plugin
    hs-source-dirs:   src
    default-language: Haskell2010
```
```
$ cat src/MyLib.hs
module MyLib (someFunc) where

someFunc :: IO ()
someFunc = putStrLn "someFunc"
```
```
$ cabal v1-install .
Resolving dependencies...
Starting     test-0.1.0.0
Building     test-0.1.0.0
Failed to install test-0.1.0.0
Build log ( /Users/hamish/.cabal-devx/logs/ghc-9.6.3/test-0.1.0.0-2vHb5qpV3rnA1Gux1WyweH.log ):
cabal: Entering directory '.'
Configuring test-0.1.0.0...
Preprocessing library for test-0.1.0.0..
Building library for test-0.1.0.0..
Installing library in /Users/hamish/.cabal-devx/lib/x86_64-osx-ghc-9.6.3/test-0.1.0.0-2vHb5qpV3rnA1Gux1WyweH
Error: cabal: '/nix/store/9drimq6n088xzlpk56hc9k6zb7a46qch-ghc-9.6.3/bin/ghc'
exited with an error:
<command line>: Could not find module ‘Polysemy.Plugin’
Use -v (or `:set -v` in ghci) to see a list of the files searched for.

cabal: Leaving directory '.'
Error: cabal: Some packages failed to install:
test-0.1.0.0-2vHb5qpV3rnA1Gux1WyweH failed during the final install step. The
exception was:
ExitFailure 1
```

This problem does not seem to affect `cabal v2-build`, but it does break haskell.nix (https://github.com/input-output-hk/haskell.nix/issues/2096).

**Comment by Mikolaj** [comment]
Thanks for the report.So is it `Setup register` that is broken, which is more or less the same as `cabal v1-register`? How come a fix done in 2018 affected haskell.nix now? Is it because only now you use the GHC version with a (I imagine) companion patch created in 2018? Still sounds unlikely. Or was haskell.nix never used with plugins before?

Is it possible to fix this without touching GHC?

BTW, I did not understand the first sentence in the issue description above.

**Comment by hamishmack** [comment]
> BTW, I did not understand the first sentence in the issue description above.

Oops, should have read:

With `ghc >=9.6` `--abi-hash` initialises plugins and will fail if a plugin module requested using `-fplugin=Foo` is not found.

> So is it `Setup register` that is broken, which is more or less the same as cabal `v1-register`?

I think so.

> Or was haskell.nix never used with plugins before?

I think everyone so far has probably used `{-# OPTIONS_GHC -fplugin=Foo #-}` pragma in the `.hs` file (which works fine), but `ghc-options: -fplugin=Foo` in the `.cabal` file should work too.

> Is it possible to fix this without touching GHC?

I think if we can just remove the `ghc-cabal` work around (#3639) it might fix this, however I'm not sure if that work around is still needed.

**Comment by andreabedini** [comment]
If I managed to reproduce this correctly ...

```
❯ runhaskell Setup.hs register -v
/home/andrea/.ghcup/bin/ghc-9.6.3 --abi-hash -fbuilding-cabal-package -O -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -idist/build/global-autogen -Idist/build/autogen -Idist/build/global-autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-unit-id test-0.1.0.0-AsDlKZOHW8q3ag8f7Au9wG -hide-all-packages -Wmissing-home-modules -no-user-package-db -XHaskell2010 MyLib -Wall '-fplugin=Polysemy.Plugin'
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup.hs: '/home/andrea/.ghcup/bin/ghc-9.6.3' exited with an error:
<command line>: Could not find module ‘Polysemy.Plugin’
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

This is the same issue above. Adding the same `-packagedb` and `-package` flags as during compilation seem to work.

```
❯ /home/andrea/.ghcup/bin/ghc-9.6.3 --abi-hash -fbuilding-cabal-package -O -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -idist/build/global-autogen -Idist/build/autogen -Idist/build/global-autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-unit-id test-0.1.0.0-AsDlKZOHW8q3ag8f7Au9wG -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db package-db -package-db dist/package.conf.inplace -package-id base-4.18.1.0 -package-id polysemy-1.9.1.3-2237d77f9db3f801a77859b2354a982f59993d35e3f6856fc3f94b9e556fa00b -package-id polysemy-plugin-0.4.5.1-d8eaf340541ad3cccef44415f28986ef92008e9a2c15ff833aef4df91839b857 -XHaskell2010 MyLib -Wall '-fplugin=Polysemy.Plugin'
7bd51309a86a53f874ad543e3b96edca
```

I'll make a PR to revert that work around.

**Comment by Mikolaj** [comment]
> I think if we can just remove the ghc-cabal work around (https://github.com/haskell/cabal/pull/3639) it might fix this, however I'm not sure if that work around is still needed.

@bgamari, @mpickering, do you think that workaround is still needed? See also the new https://github.com/haskell/cabal/pull/9384 that reverts it. CI passes for it, but these are cabal tests, not GHC tests.

**Comment by mpickering** [comment]
GHC built fine with this change, so I think it's good to go ahead.

**Comment by mpickering** [comment]
It turns out the commit I tested was a bad revert, testing again with the updated commit.

**Comment by mpickering** [comment]
I tested against the MR and GHC builds fine.
