### ISSUE TITLE
some way to specify common build-depends for library, executables and test-suites

### ISSUE THREAD

**Issue by bos** [haskell/cabal#938]
(Imported from [Trac #948](http://hackage.haskell.org/trac/hackage/ticket/948), reported by Oblosys on 2012-04-27)

Not sure whether this is a feature request or a bug report. I sometimes have a number of dependencies that are the same for library, executable, and test-suite. The global property 'build-depends' looks like an ideal place to put these, but any dependencies I list there seem to be ignored by cabal.

**Comment by grayjay** [comment]
#3404 and #2832 are related.

**Comment by quasicomputational** [comment]
Common stanzas are a thing now, hurrah!
