### ISSUE TITLE
cabal should fail if compilation depends on a file not existing in the cabal file

### ISSUE THREAD

**Issue by bos** [haskell/cabal#939]
(Imported from [Trac #949](http://hackage.haskell.org/trac/hackage/ticket/949), reported by LeventErkok on 2012-05-11)

Cabal doesn't complain if the build depends on a Haskell module that exists in the filesystem properly, but is not mentioned in the cabal file itself as part of "exposed-modules" or "other-modules". The build succeeds because ghc can find the relevant file just fine.

I've got bitten by this several times, especially after pushing a package to hackage, only to get it fail to build on the server because I've failed to put the name of a file in the appropriate section of the cabal file, thus it didn't make it to the .tar.gz bundle that got uploaded to the server.

I realize this might be hard to ensure, as it would require a deeper look into the dependencies between modules, but I trust the GHC API should have all the information necessary for cabal to complain appropriately.

**Comment by ttuegel** [comment]
Duplicate of #1746.
