### ISSUE TITLE
Hackage releases for Cabal-QuickCheck, Cabal-described and Cabal-treediff

### ISSUE THREAD

**Issue by locallycompact** [haskell/cabal#9396]
Hi, would it be OK to request hackage releases for Cabal-QuickCheck, Cabal-described and Cabal-treediff. These are needed for evaluation in horizon when providing a build environment for cabal-install, but because they are only test dependencies they are not being released to hackage.

This means I have to reverse lookup the git hash to provide versions and is very fragile, and difficult for me to automate.

https://gitlab.horizon-haskell.net/package-sets/horizon-core/-/blob/bab01dc12f9e1f6a3da269ee1eeaacf36147f2e2/horizon.dhall#L5-19

**Comment by gbaz** [comment]
I don't understand why horizon needs these? They're only needed by the cabal.project file for building additional testsuites that are also not released? It seems to me either horizon should be building the cabal-install package from hackage, or it should make available the full checkout of the project repo..

**Comment by locallycompact** [comment]
You're not wrong actually. Horizon does build cabal-install from hackage, but cabal2nix by default parses the test dependencies and expects them as derivation inputs. In one sense it's satisfying to be able to provide the complete shell environment for a haskell package so that someone can work on future proofing that package in particular, but given that all of these things are in the same repo that doesn't actually matter. That's sort of happenstance though, it's not knowledge cabal2nix has, but - probably something that it's fair to expect horizon to track.

**Comment by ulysses4ever** [comment]
@locallycompact thanks for your interest! Unfortunately, our team is vastly under-staffed, and maintaining releases for three more packages with our current release infrastructure (very much manual operation) sounds like a lot of work for very little benefit. I hope some solution on your end could be found. But keep us posted! Maybe we could come up with something if your end doesn't work.
