### ISSUE TITLE
External commands: `cabal help <cmd>` does not work

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9404]
`cargo` interprets `cabal help <cmd>` as `cabal-cmd --help`, this makes external commands integrate nicely into the existing `help` interface.

(cf https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands)

**Comment by Mikolaj** [comment]
@yvan-sraka: any comments? Feel free to remove the "needs triage" label once you think this does not need any further discussion.
