### ISSUE TITLE
cabal-install 3.10.2.0 returns wrong version

### ISSUE THREAD

**Issue by benz0li** [haskell/cabal#9415]
**Describe the bug**

Executing `cabal --version` with cabal-install 3.10.2.0 returns `cabal-install version 3.10.1.0`.

**To Reproduce**

On a host (`x86_64`) with docker installed:

```bash
docker run --rm -ti glcr.b-data.ch/ghc/ghc-musl:9.8.1 bash
```

Inside the container:

```bash
cabal update \
  && cabal install --allow-newer --constraint 'Cabal-syntax<3.11' cabal-install-3.10.2.0
```

```bash
/root/.local/bin/cabal --version
```

**Expected behavior**

Executing `cabal --version` with cabal-install 3.10.2.0 returning `cabal-install version 3.10.2.0`.

**System information**

 - Alpine Linux 3.18.4
 - ghc version: 9.8.1
 - cabal version: 3.10.1.0

**Additional context**

[execution-log.txt](https://github.com/haskell/cabal/files/13275702/execution-log.txt)

Cross reference: https://discourse.haskell.org/t/cabal-install-3-10-2-0-released/8009/3

**Comment by Kleidukos** [comment]
I can reproduce

**Comment by ulysses4ever** [comment]
Maybe, there should be a 3.10.3.0 (or 3.10.2.1?) that doesn't suffer this?

**Comment by Kleidukos** [comment]
@benz0li Alright, with [cabal-install-3.10.2.1](https://hackage.haskell.org/package/cabal-install-3.10.2.1) this should be solved. Would you mind trying on your side to confirm? 

```
cabal update \
  && cabal install --allow-newer --constraint 'Cabal-syntax<3.11' cabal-install-3.10.2.1
```

**Comment by benz0li** [comment]
> @benz0li [...] Would you mind trying on your side to confirm?

Confirmed: [execution-log.txt](https://github.com/haskell/cabal/files/13289566/execution-log.txt)

**Comment by benz0li** [comment]
> What is the analysis for why this has happened?

I would appreciate if you (@Kleidukos) answered @mpickering's question.

Thank you.

**Comment by Kleidukos** [comment]
Fantastic, I'll report on the Discourse thread

**Comment by Kleidukos** [comment]
Regarding the cause, I suspect a stale candidate that had been published. Indeed, the version number read by `cabal --version` is a constant defined in the code, not read from the cabal file, and as such it's very probable that the PR to bump the version to 3.10.2.0 missed it.

I think this mechanism should be dropped in favour of something more automatic, like the _Paths module
