### ISSUE TITLE
cabal haddock --open doesn't work on windows

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9417]
On windows `findOpenProgramLocation` tries to use `start` in order to open a browser to show the documentation.

However, this doesn't work because `start` isn't an executable but a built-in command.

See: https://web.archive.org/web/20101030061633/http://frank.neatstep.com/node/84

```
The trick is that "start" isn't an executable. It is a built-in command of the Windows command line interpreter "cmd.exe". In Java (and other languages) if you try to create a process using the "start" command this will fail -- since there is no "start.exe" executable in the system.

Instead you have to invoke "start" through the "cmd.exe" interpreter. This can be done using the /C flag:

cmd /c "start readme.txt"
```

It seems this would have been caught if there had been a test added for the `haddock --open` option.

**Comment by ulysses4ever** [comment]
This sounds like a newcomer friendly ticket doesn't it?
