### ISSUE TITLE
cabal update fails for hackage.head with `<repo>/timestamp.json is expired`

### ISSUE THREAD

**Issue by AndreasPK** [haskell/cabal#9430]
**Describe the bug**
After adding the head.hackage stanza to a cabal project cabal fails on cabal update.

**To Reproduce**

```
git clone git@github.com:haskell/cabal.git cabal_repro
cd cabal_repro
<add hackage.head stanza to cabal.project>
cabal update
```

And I get:
```
andi@arm-board:/mnt/repos/cabal_repro$ cabal update
Downloading the latest package lists from:
- hackage.haskell.org
- head.hackage.ghc.haskell.org
Verification loop. Errors in order:
  <repo>/timestamp.json is expired
  <repo>/timestamp.json is expired
  <repo>/timestamp.json is expired
  <repo>/timestamp.json is expired
  <repo>/timestamp.json is expired

```

**System information**
 - arm64/debian

```
andi@arm-board:/mnt/repos/cabal_repro$ cabal --version
cabal-install version 3.10.2.0
compiled using version 3.10.2.1 of the Cabal library
```

**Additional context**
I'm not quite sure if this is a cabal issue, a head.hackage issue, or something else. But this seemed like the best place to report this.

**Comment by andreabedini** [comment]
cabal-install has no specific support for head.hackage and treats it like any other repository that follows hackage format/protocol.

timestamp.json has its expiry time and date in clear so you can check yourself the signature has indeed expired.

This is the file I just got:
```
{"signatures":[{"keyid":"6ccc353695841b6deb473ed88ecfc1dc9ee9455d838109562d87383d0f38dbb9","method":"ed25519","sig":"ZCcUyNwFF80Ike5mxEdOqrazdzWACkpCaIX4hQkd/jlIFAkrUQ4Y+CPS3zXZJdcjHIoOGvJEYObpjNBASlYxCA=="}],"signed":{"_type":"Timestamp","expires":"2023-11-05T20:23:14Z","meta":{"<repo>/snapshot.json":{"hashes":{"sha256":"747d38c455f7de78f151fee16179426aedc42162c48aef9ff426e04ce17ed43a"},"length":796}},"version":2}}
```

**Comment by Mikolaj** [comment]
BTW, the head.hackage hackers are right now trying to come up with a way to keep the timestamp current. Until they do, you can use any older version of cabal.

**Comment by Mikolaj** [comment]
> Why an older version? I don't think anything has changed in cabal or hackage-security.

@gbaz: has the time for the Disclosure come at last? ;)

**Comment by gbaz** [comment]
the latest version of cabal-install fixes a security issue where the timestamp.json expiry was not properly checked: https://github.com/haskell/security-advisories/blob/main/advisories/hackage/cabal-install/HSEC-2023-0015.md

this is resolved by https://github.com/haskell/cabal/issues/9211

in particular, note that to get the old behavior back you can always use the `--ignore-expiry` flag, which works properly now.
