### ISSUE TITLE
`cabal sdist`, file name too long, unhelpful error message

### ISSUE THREAD

**Issue by augustss** [haskell/cabal#9438]
**Describe the bug**
cabal complains about a file name being too long without any mention of the file name.

**To Reproduce**
I'm not sure what causes the problem, I have no overly long file names.

```
$ cabal sdist
```
produces

Error: cabal: Error packing sdist: File name too long (cannot split)

**Expected behavior**
No error message.

**System information**
 - Ubuntu running in WSL
 
cabal-install version 3.10.2.0
compiled using version 3.10.2.1 of the Cabal library

**Comment by ffaf1** [comment]
Is the repo publicly available?

**Comment by ffaf1** [comment]
Relevant cabal code:

https://github.com/haskell/cabal/blob/2dad49aae0d691896df3ad3c79c57ae55637a54e/cabal-install/src/Distribution/Client/SrcDist.hs#L69-L86

Relevant `tar` code:

https://github.com/haskell/tar/blob/665c1ebc369b3c8734b43b5d092a26dc36de25a6/Codec/Archive/Tar/Types.hs#L349-L369

**Comment by augustss** [comment]
Yes
https://github.com/augustss/MicroHs

**Comment by ffaf1** [comment]
Cabal HEAD

```
~/download/MicroHs (master)$ cabal sdist
Warning: this is a debug build of cabal-install with assertions enabled.
Wrote tarball sdist to
/home/f/download/MicroHs/dist-newstyle/sdist/MicroHs-0.5.tar.gz
```

Same with cabal 3.10.1.0. This has to be Windows shenanigans. @jneira @Kleidukos, could you test on your machines?

```
git clone  https://github.com/augustss/MicroHs
cd MicroHs
cabal sdist
```

**Comment by augustss** [comment]
The WSL runs regular Ubuntu binaries in a VM, so it's more complex than
being a Windows problem.
But even so, the error message is not good.

**Comment by ffaf1** [comment]
I have opened a PR at haskell/tar#76.

**Comment by Kleidukos** [comment]
Yeah it all works well on my Windows by default. haskell/tar#76 will be helpful in debugging this.

**Comment by ffaf1** [comment]
The patch was accepted, so strictly speaking this bug report should be closed — when `tar` maintainers decide to upload a new release to Hackage, that is.

Meanwhile, would you mind using this executable to run `cabal sdist` in your folder? It should give us the name of the offending filepath.

[cabal-lennart.tar.gz](https://github.com/haskell/cabal/files/13357057/cabal-lennart.tar.gz)

**Comment by gbaz** [comment]
sadly an almost ten year old issue in `tar` on supporting long file names. (which really means supporting an extension to the tar format in a clean way, which causes a lot of architectural questions) https://github.com/haskell/tar/issues/1 sigh...

**Comment by Bodigrim** [comment]
@ffaf1 @gbaz could you test whether https://github.com/haskell/tar/pull/77 works for long file names?

**Comment by augustss** [comment]
That cabal was much more useful. :)
It gave me the bad file name, and I could quickly identify that I had an
accidental symbolic link that created a cycle.
Thanks!  Problems solved.

**Comment by ffaf1** [comment]
Another happy user.

@Bodigrim I tried it with a somewhat long path (558 characters) and it worked. (It should really be a Quickcheck test in the testsuite tho)

**Comment by Bodigrim** [comment]
> @Bodigrim I tried it with a somewhat long path (558 characters) and it worked. 

Thanks!

> (It should really be a Quickcheck test in the testsuite tho)

Contributing tests would be most welcome. The branch indeed is likely to get stalled again unless someone writes tests; I don't have any personaly interest or expertise in the area.
