### ISSUE TITLE
"add support for multiple packages" when the same package is listed twice

### ISSUE THREAD

**Issue by alt-romes** [haskell/cabal#9448]
**Describe the bug**

If a `cabal.project` file has `packages: .` listed twice, building results in. 
```
TODO: add support for multiple packages in a directory.  Got
reprto-0.1.0.0
reprto-0.1.0.0

CallStack (from HasCallStack):
  error, called at src/Distribution/Client/ProjectOrchestration.hs:654:9 in cabal-install-3.11.0.0-inplace:Distribution.Client.ProjectOrchestration
```

**To Reproduce**

1. `cabal init`
2. Create `cabal.project` with:
```
packages: .
packages: .
```

**Expected behavior**

I'm not entirely sure what means "support for multiple packages in a directory", or what is a situation in which this error is the right thing to give the user.

However, here, it seems we can be slightly smarter just by deduplicating the list of packages in `ProjectOrchestration.checkTarget` before checking whether it is really just one.

It is not that common for users to list `package: .` twice in `cabal.project`, however, it might happen accidentally e.g. if you are doing things programatically.

(FWIW as I was getting started with Haskell I remember coming across this and being stuck for a while, couldn't get the package to build)

Since we fail when we have more than one package in `checkTarget`, we might as well deduplicate -- it is almost free as we expect there to only ever be one package. Meanwhile, it protects users from slight configuration mistakes

A possible fix then (`patch.diff`):
```diff
       -- We can ask to build any whole package, project-local or a dependency
-      checkTarget bt@(TargetPackage _ [pkgid] mkfilter)
+      checkTarget bt@(TargetPackage _ (ordNub -> [pkgid]) mkfilter)
         | Just ats <-
             fmap (maybe id filterTargetsKind mkfilter) $
               Map.lookup pkgid availableTargetsByPackageId =
```

**System information**
 - Operating system: macOS
 - `cabal` HEAD, `ghc` 9.4

**Comment by Mikolaj** [comment]
Actually, it's quite common to have `package: .` both in `cabal.project` and in `cabal.project.local`. Users regularly (though rarely) report problems stemming from that. I think there was an issue to assume  `package: .` if no ` package:` is present, which would at least remove the question about convention: whether it should go to `cabal.project` or `cabal.project.local` and what to do if one of them is absent.

**Comment by chreekat** [comment]
@Mikolaj sounds like you're describing a different use case than the one @alt-romes has mentioned! Listing `package: .` in two separate places is different than listing it twice in the same place.

To me, it would make sense to just change the warning because it's not very understandable. 

    Warning: package listed twice in <project file>: "."

(It doesn't help that the message translates "." to "some-real-package-0.1.0.0")

**Comment by alt-romes** [comment]
The thing is it could be more general than that. Hence the question: what would it mean to have multiple packages/for the error to be applicable in its full generality?

**Comment by Mikolaj** [comment]
I have no idea what `TODO: add support for multiple packages in a directory` originally meant. Perhaps two versions of the same package? Or just many packages in a single project as opposed to one package, as it was initially? I guess whatever it was, it does not apply any more, so deduplicating (ideally across all sources of info) and warning seems fine.
