### ISSUE TITLE
build dependencies for custom Setup.hs

### ISSUE THREAD

**Issue by kowey** [haskell/cabal#948]
Projects often require custom Setup.hs files which in turn may rely on Haskell packages.  Those packages may in turn depend on Cabal, perhaps without being too fussy about which version of Cabal they want.

It might be useful to be able to express the idea that the Setup script itself has dependencies.  Rogan Creswick suggested maybe something that looks like

       CustomBuild
            Setup-is: Setup.hs
            Build-Depends:  ...
            Build-tools:    ...
            ...

Here was my musing about it:  https://plus.google.com/114991347543804898741/posts/2Wpy3WWvGyH (not sure if I understood correctly, and my user claims that upping the cabal-version constraint [which should be unnecessary in that case] fixes it for them)

This appears to have come up for several projects:

* GUI programmers on Mac might use a cabal-macosx package to help create application bundles for their executables
* Pandoc's Setup.hs at one point needed something from a new version of the process package
* Rogan Creswick filed this GSoC suggestion http://hackage.haskell.org/trac/summer-of-code/ticket/1602
* Rogan also commented something about cabal-dev (which I didn't fully process, sorry, Rogan!)

To ensure that these packages are present, I sometimes abuse the build-depends for my executable, which appears to be insufficient because when a Haskell-naive user upgrades from one version of Cabal to another, you get into a kind of messy situation where the Setup.hs file wants to use one version of Cabal but it relies on the package which assumes another version of Cabal.  It's the kind of thing that a Haskeller can just sort of muddle/bulldoze through, but for somebody who knows enough to type `cabal install` type commands but isn't otherwise a Haskeller, it can be seriously confusing.

**Comment by cies** [comment]
Does this mean we can also require, for instance, `alex` and `happy` binaries to be available?

And how about requiring other binaries and or libraries, for instance, postgres development headers; could we find a way to test for them as well "a la the traditional `configure` script"?

Please excuse my ignorance, I'm rather new to Haskell, but I was just wondering about these things and did not find the answers for them by reading this thread and google'ing.

**Comment by bennofs** [comment]
@cies You can already specify library dependencies for your package in the `project.cabal` file (there are pkgconfig-depends and extra-libraries fields). Build tools are currently not possible afaik.

This issue, however, is about dependencies for a special file, Setup.hs, which can be used to configure the build process in haskell (for example, to add additional checks to the configure phase). It's not about dependencies for the rest of your haskell code, only about dependencies of `Setup.hs`.

**Comment by 23Skidoo** [comment]
See #2515.

**Comment by enolan** [comment]
So, since #2515 is merged, can we close this?

**Comment by 23Skidoo** [comment]
I guess we can.
