### ISSUE TITLE
Mixins should not trigger the `-Wunused-packages` warning

### ISSUE THREAD

**Issue by MangoIV** [haskell/cabal#9536]
**Describe the bug**

If one wants to use a `mixin` as such: 

```cabal
  mixins: 
    base hiding (Prelude), 
    imports (Imports as Prelude), 
    imports
```

but `base` is not used anywhere else but there, then adding `base` as a `build-depends` in the stanza, triggers the `-Wunused-packages` warning. I think this should not be the case.

**To Reproduce**

See above 

**Expected behavior**

The `mixins` stanza should count as a use of the `base` package. 

**System information**
 - Operating system: 
   - system: `"x86_64-linux"`
   - host os: `Linux 6.6.4-zen1, NixOS, 24.05 (Uakari), 24.05.20231209.666fc80`
 - `cabal`, `ghc` versions
   - `cabal-install` / `Cabal`: 3.10.2.1
   - `ghc`: 9.4.8

**Additional context**
n/a

**Comment by jasagredo** [comment]
I think this is an upstream bug in GHC reported [here](https://gitlab.haskell.org/ghc/ghc/-/issues/24173) and [here](https://gitlab.haskell.org/ghc/ghc/-/issues/18563). Shall we close this one?

**Comment by MangoIV** [comment]
If it’s a GHC bug, sure
