### ISSUE TITLE
Support tar-0.6

### ISSUE THREAD

**Issue by Bodigrim** [haskell/cabal#9556]
`cabal-install` demands `tar < 0.6`, prohibiting a recently released https://hackage.haskell.org/package/tar-0.6.0.0. 
Cf. https://github.com/commercialhaskell/stackage/issues/7202

**Comment by ulysses4ever** [comment]
@Bodigrim thanks for the ping! I'm sure we'd welcome a PR...

**Comment by ffaf1** [comment]
We should modify stack @ to ping someone who is active in cabal dev, or even better — if possible — ping `cabal` as an organisation.

**Comment by Bodigrim** [comment]
> We should modify stack @ to ping someone who is active in cabal dev, or even better — if possible — ping cabal as an organisation.

AFAIR pinging organisations does not work. I encourage Cabal team 
* To move https://github.com/commercialhaskell/stackage/blob/f3c225fc62994076de3795211b990762c3113b3d/build-constraints.yaml#L3376-L3378 under a more active maintainer.
* Mention as many additional maintainers as desired here: https://github.com/commercialhaskell/stackage/blob/f3c225fc62994076de3795211b990762c3113b3d/build-constraints.yaml#L9298-L9301

**Comment by ffaf1** [comment]
@Bodigrim Is [this bit of `tar` documentation](https://hackage.haskell.org/package/tar-0.6.0.0/docs/Codec-Archive-Tar.html#g:5) still valid?
```
Tar.unpack dir . Tar.checkTarbomb expectedDir
               . Tar.read =<< BS.readFile tar
```

https://github.com/haskell/cabal/blob/8070ab14773484549c50a3df5568698cd33cbc4c/cabal-install/src/Distribution/Client/Tar.hs#L71-L76

**Comment by Bodigrim** [comment]
Good catch! No, you probably need to use something like https://hackage.haskell.org/package/tar-0.6.0.0/docs/Codec-Archive-Tar.html#v:unpackAndCheck

**Comment by ulysses4ever** [comment]
Not sure why Stackage would ping us if there's a newer version of our dependency: do they do it, normally? (Sorry, I'm veryI thought it's a new Hackage feature, which we probably haven't put to good use. But it will only notify Hackage maintainers (or the mailing list?)? Also, nomeata created a bot for such things I think: would be great to explore that.

@Mikolaj @Kleidukos how about enabling those magic hassle notifications for events like "a newer version of our dependency war published"? If the notification goes to your personal emails, could one of you set up an email filter to forward the notifications to the mailing list?

**Comment by Bodigrim** [comment]
> Not sure why Stackage would ping us if there's a newer version of our dependency: do they do it, normally? 

Yes. At the moment (see https://github.com/commercialhaskell/stackage/issues/7202) they ping @23Skidoo, because he was the most active maintainer when `cabal-install` was added to Stackage. It would be nice to update Stackage config as suggested in https://github.com/haskell/cabal/issues/9556#issuecomment-1868313119.

Hackage notifications are also useful of course, the more the merrier.

**Comment by ulysses4ever** [comment]
@Mikolaj are you fine with being added as the cabal-install owner on Stackage? They will ping you occasionally if something about cabal-install dependencies bounds needs attention.

Does anyone else want to be on the list of people Stackage pings when something is up with cabal-install dependencies?  @Kleidukos @ffaf1 @andreabedini @geekosaur and anyone I forget? You can simply thumb-up and I can ship one PR adding everybody.

**Comment by geekosaur** [comment]
I feel like I'm still a bit new to this.

**Comment by ulysses4ever** [comment]
@geekosaur totally understood, thank you for being honest!

**Comment by Mikolaj** [comment]
Yes, absolutely, let's add a lot of people everywhere and set up the Hackage notifications, ideally pointing to https://mail.haskell.org/mailman/listinfo/cabal-devel. I think I'm not getting any Hackage notifications relevant to cabal ATM, though I get some. I will pay attention.

**Comment by Bodigrim** [comment]
Back to the topic, `cabal-install` is the last blocker for `tar-0.6` in Stackage Nightly snapshot. What's the expected timeline for `cabal-install-3.10.3.0`? It would be great if support for `tar-0.6` was backported. 

(The grand design is to update `hackage-server` as well and test `tar-0.6` before releasing more exciting improvements)

**Comment by Mikolaj** [comment]
@Bodigrim: I'm sure @Kleidukos has the details.

**Comment by Kleidukos** [comment]
We'll be discussing the timeline during this Thursday's cabal meeting. :)

**Comment by Bodigrim** [comment]
@Kleidukos @Mikolaj whatever the exact timeline, I'd appreciate if you merge https://github.com/haskell/cabal/pull/9557 (seems good to go to me) and backport it to Cabal 3.10.3.0.

**Comment by ffaf1** [comment]
@Bodigrim we talked about this in today cabal dev meet.

#9557 will be merged (once @gbaz reviews it) and will be backported for 3.10 point release.

**Comment by Bodigrim** [comment]
Reopening until it's backported to 3.10.

**Comment by ffaf1** [comment]
Done.

**Comment by Bodigrim** [comment]
Thanks a ton, @ffaf1, for working on this!

**Comment by Bodigrim** [comment]
> @Mikolaj are you fine with being added as the cabal-install owner on Stackage? They will ping you occasionally if something about cabal-install dependencies bounds needs attention.
> 
> Does anyone else want to be on the list of people Stackage pings when something is up with cabal-install dependencies? @Kleidukos @ffaf1 @andreabedini @geekosaur and anyone I forget? You can simply thumb-up and I can ship one PR adding everybody.

@ulysses4ever just a reminder that it would be great to act on this: https://github.com/commercialhaskell/stackage/issues/7309 still pings @23Skidoo instead of anyone relevant to Cabal development nowadays.

**Comment by ulysses4ever** [comment]
Thank you for the ping. I secretly hoped that someone else would pick it up :-) https://github.com/commercialhaskell/stackage/pull/7311
