### ISSUE TITLE
master branch seems to pass -XLanguage flags to old GHCs

### ISSUE THREAD

**Issue by kosmikus** [haskell/cabal#956]
I think this has been introduced relatively recently, but I have to investigate further.

**Comment by phadej** [comment]
The problem is in `1.16` or `1.18`, but not in `cabal-1.22 `.  with `ghc-6.12.3` on travis.

For example https://travis-ci.org/snoyberg/file-embed/builds/75568345 builds ok with cabal-1.22 and ghc-6.12.3
