### ISSUE TITLE
Getting Started section of User Manual is inaccurate

### ISSUE THREAD

**Issue by rutenkolk** [haskell/cabal#9567]
**What is wrong with the docs?**
The very first command in the User Manual does not succeed. The [Getting Started section](https://github.com/haskell/cabal/blob/6c95f3fee3cdee859704b6476646cefd4628a850/doc/getting-started.rst) recommends to use `cabal init myapp --non-interactive`to initialize a new Haskell application. This command fails with a fresh install of cabal via GHCup (cabal-install version 3.6.2.1).

```ShellSession
% cabal init myapp --non-interactive
cabal: 'init' doesn't take any extra arguments: myapp
```

I'm not sure what the correct substitute for this command would be. I created the directory myself and ran `cabal init -n` in the new directory as a best guess.

**Comment by ulysses4ever** [comment]
Thanks for the report! Could you try the latest cabal? The init subcommands was rewritten at some point. The fact that ghcup installs obsolete cabal is an issue that we tried to drive with its author but failed. We recommend to always install the latest version of the cabal. Maybe, actually, we should add it to the docs.

**Comment by ffaf1** [comment]
```
f@x270:/tmp/prova$ cabal init myapp --non-interactive
Warning: this is a debug build of cabal-install with assertions enabled.
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.0
[Warning] unknown license type, you must put a copy in LICENSE yourself.
[Log] Creating fresh file CHANGELOG.md...
[Log] Creating fresh directory ./app...
[Log] Creating fresh file app/Main.hs...
[Log] Creating fresh file myapp.cabal...
[Warning] No synopsis given. You should edit the .cabal file and add one.
[Info] You may want to edit the .cabal file and add a Description field.

⁝
cabal-install version 3.11.0.0
compiled using version 3.11.0.0 of the Cabal library
```

see bc7e8fc53d

Given that most people will get cabal via `ghcup`, I wonder what would be the best way to funnel them to the relevant docs instead of HEAD.

**Comment by ulysses4ever** [comment]
Instead of funneling them to other docs, I think we should funnel them the the latest cabal. The effort will be similar, but the result is much better (they will get the up-to-date cabal experience). As easy as putting `ghcup install cabal latest` in README and in the manual.

**Comment by ffaf1** [comment]
Ah my bad, I misread the message and thought we were talking about `cabal head`, instead it is `3.10`.

Well, with the Soon to Be™ point release everything should align again. I am closing this, if you have further comments/suggestions please reopen @rutenkolk.
