### ISSUE TITLE
cabal-3.8 update creates dist-newstyle/

### ISSUE THREAD

**Issue by juhp** [haskell/cabal#9588]
**Describe the bug**
I realised today that `cabal update` at least for cabal-install-3.8.1.0 seems always to create a `dist-newstyle/` directory.
This seems like a regression relative to 3.6 - even wonder why it needs to know the compiler.

**To Reproduce**

```
$ cd
$ cabal update
$ tree dist-newstyle
dist-newstyle
└── cache
    └── compiler
```

**Expected behavior**
No dist-newstyle/ to be created

**System information**
 - Operating system: Linux
 - `cabal-3.8`, `ghc-9.4`

Doesn't seem to happen with cabal-3.10

**Comment by ulysses4ever** [comment]
Dup of #8589.
