### ISSUE TITLE
Add a CI check of cabal.project.release?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#9601]
I suspect that `cabal.project.release` is seldom touched. We might ensure that it is kept up-to-date by adding its build to CI with:

```
$ cabal build all \
  --enable-tests --enable-benchmarks --dry-run \
  --project-file=cabal.project.release \
  --index-state="hackage.haskell.org HEAD"
```

https://github.com/haskell/cabal/blob/49e3d183c0a9ac16da8d4afacc6b8a274ee67608/cabal.project.release#L1-L8

On the master branch at 49e3d183c0a9ac16da8d4afacc6b8a274ee67608:

```
$ cabal build all \
  --enable-tests --enable-benchmarks --dry-run \
  --project-file=cabal.project.release \
  --index-state="hackage.haskell.org HEAD"
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: cabal-install-3.11.0.0 (user goal)
[__1] trying: cabal-install:*test
[__2] unknown package: Cabal-described (dependency of cabal-install *test)
[__2] fail (backjumping, conflict set: Cabal-described, cabal-install, cabal-install:test)
After searching the rest of the dependency tree exhaustively,
these were the goals I've had most trouble fulfilling: cabal-install, cabal-install:test, Cabal-described
```

_Originally posted by @philderbeast in https://github.com/haskell/cabal/issues/9565#issuecomment-1881711036_

**Comment by philderbeast** [comment]
@ffaf1 sorry about the half-formed issue with wacky title. I fumbled, missed a key and hit enter.

**Comment by Mikolaj** [comment]
Yes, we definitely should. And if it builds with the same flags as the other CI builds, it should take almost no time (I hope the `--project-file` does not cause recompilation unless anything in the new project file does).

**Comment by ulysses4ever** [comment]
The failure in build is a more or less known one. There's a ticket to factor out tests out of the main packages so that they don't confuse people anymore.

**Comment by philderbeast** [comment]
I don't know what to do with this project. Should it be buildable if I `--enable-tests` and `--enable-benchmarks` from the command line even though it has these settings in the off position in the project?

https://github.com/haskell/cabal/blob/381441f7a062e4d0fb1b66dc103abcea6d9c08cb/cabal.project.release#L5-L6

It does build without `--enable-tests` and without `--enable-benchmarks`:

```
$ cabal build all --dry-run --project-file=cabal.project.release --index-state="hackage.haskell.org HEAD"
Resolving dependencies...
Build profile: -w ghc-9.8.1 -O1
In order, the following would be built (use -v for more details):
 - Cabal-3.11.0.0 (lib) (file src/Distribution/PackageDescription/Check/Warning.hs changed)
 - hackage-security-0.6.2.4 (lib) (configuration changed)
 - cabal-install-solver-3.11.0.0 (lib) (configuration changed)
 - cabal-install-3.11.0.0 (lib) (configuration changed)
 - cabal-install-3.11.0.0 (exe:cabal) (configuration changed)
```

**Comment by philderbeast** [comment]
Thanks @ulysses4ever, I went hunting for that ticket but couldn't find it.

**Comment by ulysses4ever** [comment]
Yeah, my bad I should have looked it up before posting but it did prove to be tricky to look up. 

- #8439
