### ISSUE TITLE
Warn on missing default-language 

### ISSUE THREAD

**Issue by adamgundry** [haskell/cabal#9620]
`default-language` has been optional for some time (see #6288). However, now that GHC has started introducing language editions like `GHC2021` and `GHC2024`, packages that do not specify a `default-language` ~~may be broken when GHC's default changes~~ will fall back to `Haskell98`, potentially unexpectedly. Thus it would be better if `cabal check` issued a warning about such packages.

See discussion from https://github.com/ghc-proposals/ghc-proposals/pull/613#issuecomment-1879188259 onwards. As @gbaz notes:
> We have a pretty clear plan of action that we can all agree on -- a pr to the cabal repo that creates a warning for missing language of at least "suspicious" severity -- which will lead to it being classified by `isHackageDistError` as something hackage would reject, and will lead to hackage, when it moves to using the new version of the cabal library, indeed rejecting the package.

**Comment by ffaf1** [comment]
@adamgundry after checking the relevant code, a cabal dev (I forgot who specifically, sorry) discovered that cabal defaults to `Haskell98` when `default-language` is missing (see #9668).

Would this solve your issue?

**Comment by adamgundry** [comment]
That's good news from a stability perspective. I think this feature request still makes sense, because it's very non-obvious that this default exists, so having `cabal check` encourage users to be explicit about `default-language` seems like a good idea. But it's less urgent in the light of #9668.
