### ISSUE TITLE
Provide statically linked linux pre-releases 

### ISSUE THREAD

**Issue by TeofilC** [haskell/cabal#9631]
### Summary

Currently a pre-release tarball contains a `cabal` executable that has dynamic library dependencies on zlib and gmp (along with glibc).

This means that folks on statically linked (eg, alpine), or oddly linked platforms (looking at you Nix/NixOS), can't directly use them.

### Suggestion

Let's additionally make available a statically linked binary.

I'm not sure if this would require a lot of work to get working on CI but I'd be happy to take a look.

**Comment by ulysses4ever** [comment]
I'd be happy to review and approve such PR if it's submitted.
