### ISSUE TITLE
Weird store path dir

### ISSUE THREAD

**Issue by alt-romes** [haskell/cabal#9654]
**Describe the bug**
Non-local build packages are built in a temporary location within the cabal store.
Weirdly, this temporary location duplicates the cabal-store-path-prefix within the temporary directory, something like
```
/home/tchoutri/.cabal/store/ghc-9.4.7/incoming/new-3485596/home/tchoutri/.cabal/store/ghc-9.4.7/openapi3-3.2.4-10ab5f1c59bbb45dbd67f02e0bbc49fff86fce693481f1e870150b3d6fa049d1/bin
```
This was also noted in #9640.

**To Reproduce**
Steps to reproduce the behavior

```
cd $(mktemp -d)
cabal init --lib -m --simple -d hegg
cabal --store-dir=$(mktemp -d) build -v2 | grep incoming/new-
```

Prints out something like
```
/var/folders/tv/35hlch6s3y15hfvndc71l6d40000gn/T/tmp.BWFEH5jATm/ghc-9.8.1/incoming/new-45541/var/folders/tv/35hlch6s3y15hfvndc71l6d40000gn/T/tmp.BWFEH5jATm/ghc-9.8.1/hgg-0.5.0.0-db29a4ad
```

**Expected behavior**
The incoming package build path should not duplicate the cabal store prefix within it.

**System information**
 - `cabal` HEAD

**Comment by Mikolaj** [comment]
I wonder if that's a silly mistake or if it (awkwardly) has some useful role, e.g., to make sure something is distinct from something else even in degenerate circumstances, e.g., with empty path prefixes somewhere. Whatever the case, I'm sure the extra path segment can be made shorter.

**Comment by alt-romes** [comment]
In my short investigation I think this was introduced by 5add3c973ccf4e68e95017e3ee035778382ee5cc (cc @angerman).

**Comment by alt-romes** [comment]
In fact, this is a bit harder to pin point. I no longer think the root cause is 5add3c9, sorry for the ping Moritz.
I'm working on it.

**Comment by alt-romes** [comment]
There is some prior discussion about this interaction of `--prefix` and `--store-dir` e.g. in https://github.com/haskell/cabal/issues/3473#issuecomment-234405146.

**Comment by ulidtko** [comment]
At the very least, it does look buggy to double the path length, `/home/user/.cabal/store/ghc-.../incoming/new-.../home/user/.cabal/store/ghc-.../actual-pkg-dir/bin`. @alt-romes are you saying this is as expected?

**Comment by alt-romes** [comment]
@ulidtko it's unfortunate but there is no easy solution here (changing this would imply changing many other things and break backwards compatibility). It would be cleaner not to duplicate the path in the tmp installation dir, but this is not cause for problems -- not a bug.
