### ISSUE TITLE
cabal-install 3.10.2.1 changelog is missing

### ISSUE THREAD

**Issue by mauke** [haskell/cabal#9664]
https://hackage.haskell.org/package/cabal-install-3.10.2.1/changelog says:

> 3.10.2.1 Hécate <hecate+github@glitchbra.in> November 2023
	* See https://github.com/haskell/cabal/blob/master/release-notes/cabal-install-3.10.2.1.md

https://github.com/haskell/cabal/blob/master/release-notes/cabal-install-3.10.2.1.md says:

> 404 - page not found

**Comment by fgaz** [comment]
Looks like we need to forward-port it to `master`. In the meantime you can find it here: https://github.com/haskell/cabal/blob/3.10/release-notes/Cabal-3.10.2.1.md
