### ISSUE TITLE
"the following two should never happen" span happens

### ISSUE THREAD

**Issue by DanBurton** [haskell/cabal#968]
According to this file http://hackage.haskell.org/packages/archive/Cabal/1.14.0/doc/html/src/Distribution-ParseUtils.html

    -- the following two should never happen:
    Span n     l  :_ -> syntaxError n $ "unexpected span: " ++ show l
    Line n _ _ l  :_ -> syntaxError n $ "unexpected line: " ++ show l

However if you attempt to use Haskell record update syntax as example code in the "description" field, you can make it happen. For example, if you use the following as the contents of a .cabal file:

    description: > quux (foo { bar = baz })

You will get the error message

    cabal: foo.cabal:1:  unexpected span: ")"

This may be connected to a deeper defect: curly braces do not display at all on Hackage package description pages.

**Comment by ttuegel** [comment]
Closing duplicate.
