### ISSUE TITLE
testsuite: Allow testing Cabal library via cabal-install tests

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9681]
At the moment the testsuite has two kinds of tests.

* `Setup.hs` tests, which are built against the in-tree Cabal library
* `cabal-install` tests, which use the in-tree `cabal-install` library but the boot compiler `Cabal` library.

This has caused much confusion with people writing `cabal-install` tests to attempt to test things they have changed in Cabal and wondering why the test never runs (see #9425)

We should be able to have more control in the testsuite about which version of the Cabal library is used for cabal-install tests.

* Use the boot compiler Cabal library (like we do now)
* Use the intree library, for testing changes in master.
* Use a specific Cabal library.

**Comment by Mikolaj** [comment]
We've chatted during the devs meeting and nobody knows of any false positives we could be getting by using other Cabal versions and that sounds like a great idea (frankly, quite a shocker we don't do this already in CI). The hope is versioning should prevent any problems and if it doesn't, good to learn it early.

The only drawback of testing more Cabal versions is that CI would take longer. So we'd definitely love to have one extra CI test run using in-tree Cabal (perhaps with the newest GHC) and if there are any other ideas, we are open. I guess, no big problems if `Setup.hs` tests are repeated in this extra single CI run. Perhaps we can vary some other minor parameter a big to make this run distinct enough (e..g, use one minor version older GHC than the newest one?).
