### ISSUE TITLE
cabal-install tries to build dynamic profiling libraries - conflict with C sources

### ISSUE THREAD

**Issue by thielema** [haskell/cabal#969]
Consider a package with C-sources. I have installed GHC with dynamic and profiling libraries, but no dynamic profiling libraries. The result is this:

$ cabal-0.15.0 install --enable-shared --enable-library-profiling cpuid-0.2.3
Resolving dependencies...
Downloading cpuid-0.2.3...
Configuring cpuid-0.2.3...
Building cpuid-0.2.3...
Preprocessing library cpuid-0.2.3...
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.o )
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.p_o )
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.dyn_o )
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.dyn_o )
gcc: Fehler: dist/build/cbits/cpuid.dyn_o: Datei oder Verzeichnis nicht gefunden
cabal-0.15.0: Error: some packages failed to install:
cpuid-0.2.3 failed during the building phase. The exception was:
ExitFailure 1

Compare with cabal-install-0.14:
$ cabal-0.14.0 install --enable-shared --enable-library-profiling cpuid-0.2.3
Resolving dependencies...
Configuring cpuid-0.2.3...
Building cpuid-0.2.3...
Preprocessing library cpuid-0.2.3...
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.o )
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.p_o )
[1 of 1] Compiling System.Cpuid     ( System/Cpuid.hs, dist/build/System/Cpuid.dyn_o )
Registering cpuid-0.2.3...
Running Haddock for cpuid-0.2.3...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0
Preprocessing library cpuid-0.2.3...
Haddock coverage:
  25% ( 21 / 84) in 'System.Cpuid'
Documentation created: dist/doc/html/cpuid/index.html
Installing library in ~/.cabal/lib/cpuid-0.2.3/ghc-7.4.1.20120516
Registering cpuid-0.2.3...
Updating documentation index ~/.cabal/share/doc/index.html

**Comment by jsl** [comment]
This works just fine on cabal 1.22.0.0, so it seems like this has been fixed. I propose closing, but please re-open or create a new ticket if this issue still exists. My build output and system information:

```
justin /tmp/testit $ cabal sandbox init
Writing a default package environment file to
/private/tmp/testit/cabal.sandbox.config
Creating a new sandbox at /private/tmp/testit/.cabal-sandbox
justin /tmp/testit $ cabal install --enable-shared --enable-library-profiling cpuid-0.2.3
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/testit/.cabal-sandbox
Configuring data-accessor-0.2.2.6...
Configuring utility-ht-0.0.10...
Building data-accessor-0.2.2.6...
Building utility-ht-0.0.10...
Installed data-accessor-0.2.2.6
Installed utility-ht-0.0.10
Downloading storable-record-0.0.3...
Configuring storable-record-0.0.3...
Building storable-record-0.0.3...
Installed storable-record-0.0.3
Downloading enumset-0.0.4...
Configuring enumset-0.0.4...
Building enumset-0.0.4...
Installed enumset-0.0.4
Downloading cpuid-0.2.3...
Configuring cpuid-0.2.3...
Building cpuid-0.2.3...
Installed cpuid-0.2.3
justin /tmp/testit $ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 

justin /tmp/testit $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

```
