### ISSUE TITLE
cabal v2-repl broken with head

### ISSUE THREAD

**Issue by TeofilC** [haskell/cabal#9710]
**Describe the bug**

`cabal v2-repl <component>` with cabal-head seems to just exit with exitcode 0 and not launch ghci.
This also breaks HLS.

**To Reproduce**
````
> cabal v2-repl foo
Resolving dependencies...
> echo $?
0
````

**Expected behavior**
This should open a repl

**Comment by ulysses4ever** [comment]
I can't reproduce it. What timestamp do you have on that binary? (We really should start embedding commit SHA into the `--version` info.) Also, what is `foo`, any chance for a self-contained reproducer?

**Comment by Benjamin-McRae-Tracsis** [comment]
`/home/username/.ghcup/bin/cabal-head repl aeson` seems to clone a bunch of neccessary stuff and then just exits as described.

**Comment by Benjamin-McRae-Tracsis** [comment]
running `/home/username/.ghcup/bin/cabal-head repl` in a non-package environement (just `~`) lets me enter the repl:

```
$ /home/username/.ghcup/bin/cabal-head repl
Warning: this is a debug build of cabal-install with assertions enabled.
Warning: Parsing the index cache failed (Data.Binary.Get.runGet at position
16: Non-matching structured hashes: f46da61e7afa58a5e8fd1d2b6fb79899;
expected: d81bdd513f41b5d7ee4cd28455adadbe). Trying to regenerate the index
cache...
Resolving dependencies...
Build profile: -w ghc-9.4.7 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (interactive) (lib) (first run)
Warning: this is a debug build of cabal-install with assertions enabled.
Configuring library for fake-package-0...
Warning: this is a debug build of cabal-install with assertions enabled.
Warning: No exposed modules
GHCi, version 9.4.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /tmp/cabal-repl.-239669/setcwd.ghci
ghci> :i head
head :: GHC.Stack.Types.HasCallStack => [a] -> a
        -- Defined in ‘GHC.List’
ghci>
```

**Comment by TeofilC** [comment]
@ulysses4ever Here's a standalone reproducer:
Checkout https://github.com/TeofilC/cabal-repl-repro
Then 
```
cabal build foo
cabal repl foo`
```

I think the key detail is having a custom setup somewhere in the project. It seems to be necessary to build first too.

**Comment by mpickering** [comment]
I am looking into this.

**Comment by mpickering** [comment]
With `9.6.2` I get: 

```
/home/matt/cabal-bisect/dist-newstyle/build/x86_64-linux/ghc-9.6.2/cabal-install-3.11.0.0/x/cabal/build/cabal/cabal repl foo
```

with 9.4.8 I get

```
[matt@nixos:~/cabal-bisect/cabal-repl-repro]$ /home/matt/cabal-bisect/dist-newstyle/build/x86_64-linux/ghc-9.6.2/cabal-install-3.11.0.0/x/cabal/build/cabal/cabal repl foo
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
```

**Comment by mpickering** [comment]
Seems that this was broken by the multi-repl patch.

**Comment by mpickering** [comment]
Patch here: https://github.com/haskell/cabal/pull/9720
