### ISSUE TITLE
Does LIBRARY_PATH and C_INCLUDE_PATH still work?

### ISSUE THREAD

**Issue by chansey97** [haskell/cabal#9712]
**What is your question?**

I hope cabal has the ability to specify `extra-include-dirs` and `extra-lib-dirs` via env variables. I found a old issue from https://github.com/haskell/cabal/issues/6716.

I tried setting LIBRARY_PATH and C_INCLUDE_PATH, but it doesn't work in cabal-install 3.10.2.1. Does LIBRARY_PATH and C_INCLUDE_PATH still work?

P.S. Setting `extra-include-dirs` and `extra-lib-dirs` in cabal/config is OK, but not very convenient.

**System information**
 - msys64
 - cabal-install version 3.10.2.1

**Comment by gbaz** [comment]
These paths are not used by cabal directly -- they are used by the underlying C compiler, so you need to see what paths your C compiler expects depending on your environment. It appears on windows, from what I've googled up, it does not use any special path env variables, but instead you append everything to the system path directly. So you may want to try that?

**Comment by chansey97** [comment]
@gbaz I used MINGW to build (i.e. setting these two env variables inside MINGW, not external), so in theory, underlying C compiler in MINGW should read both variables, but doesn't work.

Anyway even if LIBRARY_PATH and C_INCLUDE_PATH can work, it's still a temporary solution. The better way is [specify extra-include-dirs and extra-lib-dirs via env variables](https://github.com/haskell/cabal/issues/6716) .

**Comment by gbaz** [comment]
Different underlying C compilers will use different env variables regardless -- so you should consult the documentation for the current version of the C compiler used by mingw to see what it does. At the end of the day you need to determine which variables are appropriate for your system -- the main part of the answer is simply that cabal never directly worked with such variables, and it has always been the underlying toolchain that needs to be configured with regards to them.
