### ISSUE TITLE
[Windows] Document use and integration of MSYS2

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#9713]
There's zero documentation for windows users on how to utilize msys2 and link to system C libraries.

* https://cabal.readthedocs.io/en/stable/search.html?q=msys2&check_keywords=yes&area=default
* https://cabal.readthedocs.io/en/stable/search.html?q=mingw&check_keywords=yes&area=default

So far, GHCup is doing silent work here by setting `extra-lib-dirs`, `extra-include-dirs` and `extra-prog-path` to the correct locations: https://github.com/haskell/ghcup-hs/blob/2fdf896fbdd338ba6b4244c47b10dcd4067552e0/scripts/bootstrap/bootstrap-haskell#L598

The semantics and implications of these settings on windows should be documented, especially in light of [MSYS2 environments](https://www.msys2.org/docs/environments/).

Also see:

* https://github.com/haskell/ghcup-hs/issues/982
* https://github.com/haskell/ghcup-hs/pull/992

GHCup should not be where this is documented. Cabal needs to step up its game on windows.

**Comment by bradrn** [comment]
I’ve wished for proper documentation for this area for a long time. Happy to help write some if I can, though it’s been a while since I’ve done really large amounts of work on Windows.

**Comment by jasagredo** [comment]
Feel free to review/propose changes on #9723 where I summarized what I know of using Windows + Cabal + GHC. One thing I think that document is missing is a "Common problems on Windows and how to solve them" section, but yet I think what I wrote can serve as a first version.
