### ISSUE TITLE
master: cabal install from hackage broken?

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#9715]
Just built `cabal` from master  3d3622fc3207932eb21950baac434996165191aa and tried in my home directory:
```
$ cabal v2-install cabal-install-3.10.2.1 --program-suffix=-3.10.2.1
Warning: this is a debug build of cabal-install with assertions enabled.
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.
```
Looks like installation from hackage is broken in general, e.g. `cabal install hangman` also fails.

The docs say it should work: https://cabal.readthedocs.io/en/latest/cabal-commands.html#cabal-install

**Comment by geekosaur** [comment]
This is https://github.com/haskell/cabal/pull/9697#issuecomment-1938036790.
