### ISSUE TITLE
Support for pkgconfig alternatives

### ISSUE THREAD

**Issue by CasperVector** [haskell/cabal#974]
There are now several [pkgconfig] [1] alternatives, for example [pkgconf] [2], [pkg-config-lite] [3] and [pkgconfig-openbsd] [4]. The reason for choosing different implementations include avoiding unnecessary dependencies (for example [pkgconfig] [1] requires the glib, a library designed for GTK+) and so on.

Cabal does not support these alternatives since it only recognises the `/usr/bin/pkg-config --version` output in the `pkg-config a.b[.c]` form, while other alternatives output in other manners, for example pkgconf outputs `pkgconf a.b`. So on my machine with pkgconf installed instead of pkgconfig, Cabal yells
```
Warning: cannot determine version of /usr/bin/pkg-config :
"pkgconf 0.8\n"
setup: The program pkg-config version >=0.9.0 is required but the version of
/usr/bin/pkg-config could not be determined.
```
and aborts when trying to install `x11-xft`.

Therefore it would be nice to modify the Cabal source code and let Cabal recognise the `/usr/bin/pkg-config --version` outputs of these pkgconfig alternatives, thanks :)

P.S.
1. Since different pkgconfig alternatives have different versioning schemes, the modified source code might need to set different version conditions for different alternatives.
2. Cabal requires `>=0.9.0` version of pkgconfig, but interestingly I cannot find related settings in the Cabal source code (at least in the `Distribution.Simple.Program` module).

[1]: http://pkgconfig.freedesktop.org/wiki/
[2]: https://github.com/nenolod/pkgconf
[3]: http://sourceforge.net/projects/pkgconfiglite/
[4]: http://www.openbsd.org/cgi-bin/man.cgi?query=pkg-config&sektion=1

**Comment by jsl** [comment]
It looks from the comment history that this ticket is resolved, so I propose closing.

@CasperVector if there is something that you'd still like to see addressed here please re-open or create a new ticket. Thank you!

**Comment by CasperVector** [comment]
It works now.  Thanks :)
