### ISSUE TITLE
Regression on master: `main-is` not picked up from conditional

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#9742]
On today's master ( 9025af597b905f2027a878c0aa0f34b885e42a6e ).
Example:
```cabal
executable twee
  if flag(parallel)
    main-is: ParallelMain.hs
    build-depends: async, unix
    c-sources: executable/link.c
  else
    main-is: Main.hs
```
(Source: https://github.com/nick8325/twee/blob/eb4b83b4df6dd16fbff091b3fd90b5a55c88d41a/twee.cabal#L46-L52)
`cabal build` errors:
```
Configuring executable 'twee' for twee-2.4.2...
Error: [Cabal-5559]
[no-main-is] No 'main-is' field found for executable twee
```
This works fine on 3.10.2.1, so must be a regression on `master`.
Related:
- #9724 : reports that `cabal sdist` behaves differently on master than in 3.10.2 for flag-selected `main-is`.

**Comment by ffaf1** [comment]
Mhhh I suspect a misconfigured `CondTree` pattern match in `Check`.

I am on it.
