### ISSUE TITLE
`cabal path foo` errors with ` 'man' doesn't take any extra arguments: foo`

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#9755]
On current master:
```
$ cabal path foo
Error: [Cabal-7061]
'man' doesn't take any extra arguments: foo
```
This is a cut-and-paste coding error in PR
- #8879 

https://github.com/haskell/cabal/blob/9e5e815315794d4e5b8e69b36379ac04d0839c53/cabal-install/src/Distribution/Client/Main.hs#L1392-L1397
Copied from here:
https://github.com/haskell/cabal/blob/9e5e815315794d4e5b8e69b36379ac04d0839c53/cabal-install/src/Distribution/Client/Main.hs#L1379-L1384

ATTN: @athas

**Comment by fendor** [comment]
Perhaps interesting, #4661 refactors `cabal path`, and I think it fixes this particular error as well.

**Comment by athas** [comment]
Oh yeah, that's just a copy/paste error. Is it worth fixing if #4661 rewrites the command entirely?

**Comment by andreasabel** [comment]
> Is it worth fixing if #9583 rewrites the command entirely?

We can hold off any activity here until #9583 lands, I'd say.  I linked the latter as fixing this issue here.
