### ISSUE TITLE
`haddock-project`, missing `--local` option

### ISSUE THREAD

**Issue by ffaf1** [haskell/cabal#9760]
**What is wrong with the docs?**
The [manual](https://cabal.readthedocs.io/en/stable/cabal-commands.html#cabal-haddock-project) says.

> This command supports two primary modes: building a self contained directory (by specifying `--local` flag) or documentation that links to hackage (with `--hackage` flag).

But

```
$ cabal haddock-project --local
Error: cabal: unrecognized 'haddock-project' option `--local'
```

Which is correct?

**Comment by coot** [comment]
The flag was removed. It's not mentioned in the current version of the manual.
