### ISSUE TITLE
cabal install: "exit code 11"?

### ISSUE THREAD

**Issue by bjornkihlberg** [haskell/cabal#9769]
**Describe the bug**

Whenever I try to install something, eg `cabal install fourmolu` I get an exit code 11. ex:
```
> cabal install fourmolu
Resolving dependencies...
Build profile: -w ghc-9.8.1 -O1
In order, the following will be built (use -v for more details):
 - fourmolu-0.15.0.0 (lib) (requires build)
 - fourmolu-0.15.0.0 (exe:fourmolu) (requires build)
Starting     fourmolu-0.15.0.0 (lib)
Building     fourmolu-0.15.0.0 (lib)
Error: cabal-3.10.2.1.exe: Failed to build fourmolu-0.15.0.0 (which is
required by exe:fourmolu from fourmolu-0.15.0.0). The build process terminated
with exit code 11
```

I don't know what "exit code 11" means.

**To Reproduce**

1. Install cabal
2. Try to install any package

**Expected behavior**

**System information**
 - Windows 10
 - I'm using `ghcup-0.1.20.0`, `cabal-3.10.2.1` and `ghc-9.8.1` versions

**Comment by gbaz** [comment]
exit code 11 is a segfault. have you tested that ghc can compile and build code on its own, even without cabal?

from the error messages it appears that the version of ghc you have on that particular os is simply crashing in such a case.

**Comment by bjornkihlberg** [comment]
@gbaz Ok. thanks, I'll see what I can do about ghc.

**Comment by ulysses4ever** [comment]
Running with -v2 (or 3, 4) may help investigating?

**Comment by bjornkihlberg** [comment]
I think the problem is with a combination of GHC and Windows 10. I'm getting

```
Access violation in generated code when executing data at 0x7ff76fa96018

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x33c15fd560 0x7ff76fa96018
 * 0x33c15fd568 0x7ff765e2004b C:\ghcup\ghc\9.8.1\lib\x86_64-windows-ghc-9.8.1\base-4.19.0.0-1e7d\libHSbase-4.19.0.0-1e7d.a(#10:fs.o)+0x3b
                 (__hs_swopen+0x295)
 * 0x33c15fd570 0x100
 * 0x33c15fd578 0x80000000
 * 0x33c15fd580 0x7ef4ba0855d0
 * 0x33c15fd588 0x7ef4c060bb40
 * 0x33c15fd590 0x1
 * 0x33c15fd598 0x13c1751e480
```

which seems to be an old and recurring problem. I don't think I'm going to bother with development on Windows anymore.

Thanks for the help, guys.
