### ISSUE TITLE
Hope cabal can provide a command to print out all paths used by cabal.

### ISSUE THREAD

**Issue by chansey97** [haskell/cabal#9789]
Thanks for developing the excellent tool.

**Describe the feature request**

Stack has the [stack path](https://docs.haskellstack.org/en/stable/path_command/) command, which can provides all information about files and locations used by Stack. It's very convenient.

It would be nice if cabal also had a similar feature, e.g. `cabal path`.

**Additional context**

For novices, a frequently asked question is "where are the cabal related files placed?" 

For example, on Windows there are at least three important paths:

- cabal config path: `%AppData%/cabal`

- cabal install path: `%UserProfile%/.local/bin`

- cabal related path (store, logs):  `%LocalAppData%/cabal`

IMHO, it seems a bit messy. Also, we can set something like `extra-include-dirs`, `extra-lib-dirs`, etc in `%AppData%/cabal/config`, and sometimes we forget that we had set them before. This is why I hope a unified way to print them.

**Comment by ffaf1** [comment]
Hello @chansey97,  `cabal path` is in `master` and will be present in the next release. Example usage:

```
f@x270:~$ cabal path
Warning: this is a debug build of cabal-install with assertions enabled.
cache-dir: /home/f/.cache/cabal/packages
logs-dir: /home/f/.cache/cabal/logs
store-dir: /home/f/.local/state/cabal/store
config-file: /home/f/.config/cabal/config
installdir: /home/f/.local/bin
```

Would that cover your use case?

**Comment by chansey97** [comment]
@ffaf1 That is great.

Thanks!
