### ISSUE TITLE
Remove sandboxing from the release instructions

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#9794]
Could we please update the [making a release](https://github.com/haskell/cabal/wiki/Making-a-release#make-a-release-of-cabal-the-library) instructions to remove mention of `cabal sandbox`?

```
# Make sure that the library builds and that the tests pass.
cabal sandbox init
cabal clean
cabal install --enable-tests --only-dependencies
cabal configure --enable-tests
cabal build
cabal test
```

This command is no longer available is it?

```
$ cabal --version
cabal-install version 3.11.0.0
compiled using version 3.11.0.0 of the Cabal library 

$ cabal sandbox --help
Error: cabal: unrecognised command: sandbox (try --help)
```

**Comment by fgaz** [comment]
Isn't that just the historical section? I think it'll be removed when the new checklist is complete, cc @Kleidukos

**Comment by Kleidukos** [comment]
yeah it'll be removed. Follow these instructions instead: https://github.com/haskell/cabal/wiki/Making-a-release#release-checklist
