### ISSUE TITLE
`cabal init` generates non-standard licences

### ISSUE THREAD

**Issue by ffaf1** [haskell/cabal#9812]
**Describe the bug**
`cabal init` generates licences with some weird added wording, e.g. an additional “All rights reserved” in BSD-2. See [this Discourse thread](https://discourse.haskell.org/t/non-standard-license-generated-by-stack-new/9059).

**To Reproduce**

```
$ cabal init prova # then press ⏎ a number of times
$ cd prova
$ grep All LICENSE
```

viz. [SPDX text](https://spdx.org/licenses/BSD-2-Clause.html)

**Expected behavior**
Licence text should adhere to what is in SPDX.

**Comment by ulysses4ever** [comment]
Couple meta comments:

> $ grep All LICENSE

Would be good to see what grep shows :-)

> $ cabal init prova # then press ⏎ a number of times

it's always easier to use `cabal init -n` I find

**Comment by ffaf1** [comment]
>  Would be good to see what grep shows :-)

An “All Rights reserved” line:

https://github.com/haskell/cabal/blob/aaf16c42aa87bff9defb9fcb2acebdf1469dda3c/cabal-install/src/Distribution/Client/Init/Licenses.hs#L64-L66

which is not present in the current [text present at SPDX](https://spdx.org/licenses/BSD-3-Clause.html).
