### ISSUE TITLE
Is something wrong with the cache in quick jobs?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#9815]
Is there something wrong with the cache in [quick jobs](https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804#step:20:2);

> Post job cleanup.
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist,
> hence no cache is being saved.

_Originally posted by @philderbeast in https://github.com/haskell/cabal/issues/9804#issuecomment-1999384237_

**Comment by andreasabel** [comment]
Looks like this is part of the XDG fallout:

The path to be cached is non-XDG:
https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804#step:3:3
> path: ~/.cabal/store

Also the CI author intends to use non-XDG:
https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804#step:2:1
> echo "$HOME/.cabal/bin" >> $GITHUB_PATH

But cabal is working in XDG mode:
https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804#step:6:7
> Writing default configuration to /home/runner/.config/cabal/config

https://github.com/haskell/cabal/actions/runs/8294806206/job/22700513058?pr=9804#step:7:15
> Symlinking 'alex' to '/home/runner/.local/bin/alex'

A workaround might be to force non-XDG by creating `~/.cabal/bin` before adding it to the PATH in step 2.
Another fix would be to change the cached path to the XDG one.
