### ISSUE TITLE
cabal-install-solver-3.10.3.0 not compatible with Cabal-3.10.2.0

### ISSUE THREAD

**Issue by jkachmar** [haskell/cabal#9838]
## description

attempting to build `cabal-install-solver-3.10.3.0` against `Cabal-3.10.2.0` results in the following error:

```
           Module ‘Distribution.Simple.Program.Run’ does not export ‘getProgramInvocationLBSAndErrors’.
           Suggested fix: Perhaps use ‘getProgramInvocationOutputAndErrors’
          |
       43 |        (getProgramInvocationOutputAndErrors, programInvocation, getProgramInvocationLBSAndErrors)
          |                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

looks like it was added to both `Cabal` & `cabal-install-solver` in 0b34b4eaac65fb5a5ece8f7846077c4a3d627520.

right now Hackage bounds for `cabal-install-solver-3.10.3.0` are >=3.10 && <3.11; these should probably be changed.

**Comment by Kleidukos** [comment]
Thanks for the report, as new revision was published on Hackage.

**Comment by Kleidukos** [comment]
@jkachmar Can you confirm the fix?
