### ISSUE TITLE
CI validate-old-ghcs broken after haskell-actions/setup upgraded to node20

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#9858]
The container for the "old ghcs" workflow uses a container `phadej/ghc:8.8.4-xenial` that does not support `node20`.
https://github.com/haskell/cabal/blob/519f2f75125bee6464ca11de6c033ab1268d6cb1/.github/workflows/validate.yml#L223-L232
Since I bumped `haskell-actions/setup` to `node20` the workflow fails, missing a recent glibc:
https://github.com/haskell/cabal/actions/runs/8496523229/job/23275396876#step:5:16
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)

A short term solution would be to pin to `haskell-actions/setup@v2.6`, however, GH will axe `node16` in a couple of weeks, and then the problem will be back.

I'd rather axe GHC 7 validation.
E.g., for 7.0.4, less than 20% of the tests are actually run.  Not much of a point, if you ask me.
https://github.com/haskell/cabal/actions/runs/8392859676/job/22990941034#step:8:455
> 532 tests, 436 skipped, 0 unexpected passes, 0 unexpected fails.

Or someone has to make a new container.

**Comment by andreasabel** [comment]
There seem to be other issues with the `validate-old-ghcs` workflow:

It builds `cabal-install` but does not run the `cabal-install` tests.  Why?
- https://github.com/haskell/cabal/actions/runs/8392859676/job/22990941034#step:7:135
  > cabal-install-3.11.0.0 (exe:cabal) (first run)
- https://github.com/haskell/cabal/actions/runs/8392859676/job/22990941034#step:8:16
  > PackageTests/TestSuiteTests/ExeV10/cabal-with-hpc.multitest.hs      SKIP no cabal-install

The `validate.sh` script calls `jq` which is not installed: https://github.com/haskell/cabal/actions/runs/8392859676/job/22990941034#step:7:156
> validate.sh: 379: validate.sh: jq: not found

Also, something I don't understand:  Why is it essential to install the `-dyn` version of the old `ghc`?
https://github.com/haskell/cabal/blob/519f2f75125bee6464ca11de6c033ab1268d6cb1/.github/workflows/validate.yml#L256-L259
Is the `-dyn` version actually run?
https://github.com/haskell/cabal/blob/519f2f75125bee6464ca11de6c033ab1268d6cb1/.github/workflows/validate.yml#L282-L285

**Comment by Mikolaj** [comment]
Ouch. I'm afraid the answers to most of your questions, Andreas, are lost in time, like tears in rain.

The "old ghcs" workflow also tests against a few old GHC 8 versions. Are they affected as well?

Could we just use a newer phadej/* container or do all of them have the same problem?

Can we use ghcup or gihub default instead of the containers?

**Comment by Mikolaj** [comment]
Copied from https://hackmd.io/c1yOln1fR_K5WiEhhPsUlQ?both: 

> there seems to be a consensus to drop old ghc (old: not on ghcup) and there's hope the others can relatively easily be handled by switching from containers to ghcup (if they are not already set up like that). Volunteers welcome, but in the worst case, we'll react to the CI outage once it happens.
