### ISSUE TITLE
Release CI early warning is failing

### ISSUE THREAD

**Issue by chreekat** [haskell/cabal#9861]
E.g. https://gitlab.haskell.org/haskell/cabal/-/pipelines/92315

It looks like it's due to the use of `import` in the cabal.project files, requiring a bump of the bootstrap version.

I've resurrected the branch I was working on that introduced a bunch of new platforms. I'll PR it soon.

**Comment by philderbeast** [comment]
This is the change to [`cabal.project.release`](https://github.com/haskell/cabal/pull/9565/files#diff-5059488c1739c205cfcf33215ac5de038c4ced1f0f1c1413f6d0b7e73bb4801a) adding imports.

**Comment by philderbeast** [comment]
> As of cabal-install version 3.8, cabal supports conditional logic and imports in cabal.project files.
> [cabal project conditionals and imports](https://cabal.readthedocs.io/en/stable/cabal-project.html#conditionals-and-imports)
