### ISSUE TITLE
Odd windows-latest ghc-9.6.3 CI failures

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#9862]
Encountered a really odd [Validate windows-latest ghc-9.6.3 CI run](https://github.com/haskell/cabal/actions/runs/8522030936/job/23341377095?pr=9578) with various failures;

![Screen Shot 2024-04-02 at 4 13 29 PM](https://github.com/haskell/cabal/assets/633283/6933aef3-5bf6-4017-b0d0-4b799fb10052)

**Comment by andreasabel** [comment]
It timed out after 6h and was thus cancelled.
I usually do not attach relevance to such incidents, probably the machine running it just starved the process.  Maybe it started thrashing by using too much memory.

**Comment by philderbeast** [comment]
Thanks for the explanation, @andreasabel.
