### ISSUE TITLE
Improve Hackage server logging

### ISSUE THREAD

**Issue by igfoo** [haskell/cabal#990]
The hackage 2 server should be able to log request details, and the response code etc, to a log file.

Another log file should contain extra details of any error responses returned.

**Comment by ttuegel** [comment]
This is not a Cabal bug.

**Comment by ttuegel** [comment]
@igfoo The description of this issue is a little vague, so I'm not sure if the features you're looking for have been implemented yet. If they are still lacking, please report this on the [Hackage issue tracker](https://github.com/haskell/hackage-server).
