### ISSUE TITLE
Why release of support multi-repl takes so much time?

### ISSUE THREAD

**Issue by KovalevDima** [haskell/cabal#9903]
Releasing support of multi-repl, as I can understand, shouldn't affect functionality of other cabal commands. Me and my colleagues waiting this feature already about 3 month since a `support of multi-home-units` was released in [haskell-language-server-2.6.0.0](https://github.com/haskell/haskell-language-server/releases/tag/2.6.0.0).

Why it takes so much time? Is it possible to release this feature with 3.10.4.0? I think it would be quite unstable closest time anyway so the developers would give many reports about problems to you and to HLS team so we get much more progression in making development with HLS in many of Haskell monorepos possible

**Comment by geekosaur** [comment]
It takes time because we have a limited number of people involved with cabal development, and at the moment all of our time is taken up by releasing Cabal 3.12.0.0 for ghc 9.10. Finalizing cabal-install 3.12.1.0 with multi-repl support is planned for immediately after the ghc 9.10 release.

**Comment by geekosaur** [comment]
We're working our way through the release checklist and I don't think anything can speed that up. Probably the most helpful thing users can do is use the nightly build so it is well tested prior to official release.

**Comment by KovalevDima** [comment]
Okay. Sometimes I'm trying to build 3.12 branch in my packages via Nix. I haven't seen problems with cabal especially. I would make an issue if I see some
