### ISSUE TITLE
Reinstate the reverse dependencies feature

### ISSUE THREAD

**Issue by igfoo** [haskell/cabal#991]
The Hackage2 reverse dependencies feature is currently disabled due to space usage, and speed penalty when mirroring. We should fix any performance issues that can be fixed and reinstate it.

**Comment by ttuegel** [comment]
If this is still an issue, please file it at https://github.com/haskell/hackage-server.

**Comment by ttuegel** [comment]
Already reported in haskell/hackage-server#40.
