### ISSUE TITLE
`cabal list-bin` doesn't suppress stdout from other phases

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#9911]
**Describe the bug**

`cabal list-bin` doesn't suppress stdout from internal cabal phases, leading to broken behavior when you want to save the result in a variable.

**To Reproduce**

1. `git clone git@github.com:hasufell/list-bin.git`
2. `cd list-bin`
3. `cabal build`
4. `foo=$(cabal list-bin exe:list-bin)`
5. `${foo}`

Resulting in:

> bash: Downloading: command not found

**Expected behavior**

The only thing sent to stdout is the binary location.

**System information**
 - Operating system: Fedora 39
 - `cabal`: 3.10.3.0

**Comment by fendor** [comment]
Related issues: #8870, #7790, #4652

This seems like a long-standing issue in multiple cabal commands. Perhaps we should take inspiration from other project build tools and try to come up with a fix once and for all? E.g., `cargo` seems to printing everything to `stderr` (rustc errors, progress notifications, etc...).

A disadvantage of sending all output to `stderr` is that we probably break someone's scripts.

**Comment by ulysses4ever** [comment]
Duplicate, as mentioned above.
