### ISSUE TITLE
Add support to clean build cache of a specific local package

### ISSUE THREAD

**Issue by shivaraj-bh** [haskell/cabal#9918]
**Describe the feature request**
Add support to clean build cache of a specific local package with `cabal clean`. haskell-stack already does this, see: https://docs.haskellstack.org/en/stable/GUIDE/#the-stack-clean-command

**Additional context**
This would enable more fine-grained control over the build caches that the user can clean

**Comment by michaelpj** [comment]
Dupe of https://github.com/haskell/cabal/issues/7506 ?
