### ISSUE TITLE
`cabal install` program-suffix is applied to the binary name in the store

### ISSUE THREAD

**Issue by fendor** [haskell/cabal#9919]
**Describe the bug**

**To Reproduce**
With cabal HEAD (774ff0463f1797cac75c19e08727c076b4cb20d3), try installing any program, in my example `HLS` via:
```sh
$ cabal install exe:haskell-language-server -w ghc-9.6.4 --installdir /home/hugin/bin/ --program-suffix -9.6.4 --with-compiler=ghc-9.6.4 
```

After it finished compiling, the symlink looks good:
```sh
$ ls -al ~/bin/
haskell-language-server-9.6.4 -> ../.cabal/store/ghc-9.6.4/haskell-language-server-2.7.0.0-e-haskell-language-server-6719e6073284fd7edd180b3c8c9ea8c6482ea148b4407d215635b68fe07d055a/bin/haskell-language-server
```

but the path doesn't exist. The binary in the store has the `program-suffix` `-9.6.4` applied.

```sh
$ ls ~/.cabal/store/ghc-9.6.4/haskell-language-server-2.7.0.0-e-haskell-language-server-6719e6073284fd7edd180b3c8c9ea8c6482ea148b4407d215635b68fe07d055a/bin
haskell-language-server-9.6.4*
```

which is incorrect.

**Expected behavior**

This should create an executable `haskell-language-server` in the cabal store and a symlink to `haskell-language-server-9.6.4` in `~/.cabal/bin`.

**System information**
 - `cabal HEAD`, `ghc-9.6.4`
 
**Additional context**

The PR https://github.com/haskell/cabal/pull/6207 introduced the behaviour that `program-suffix` are applied to the symlink or copied binary only.

**Comment by andreasabel** [comment]
Is this the same as 
- #8823 ?

**Comment by fendor** [comment]
Yeah, looks like it could have a common root cause.
