### ISSUE TITLE
Switch to using a common `.project` file extension for projects?

### ISSUE THREAD

**Issue by philderbeast** [haskell/cabal#9925]
Can we please change the project names to have a common `.project` [file extension](https://en.wikipedia.org/wiki/Filename_extension) instead of a common `cabal.project` prefix?
```
$ tree -P 'cabal.project*' --prune -L 1
.
├── cabal.project
├── cabal.project.bootstrap
├── cabal.project.meta
├── cabal.project.release
├── cabal.project.validate
└── cabal.project.validate.libonly

1 directory, 6 files
```

I only use `.project` for full-blown projects. For imported project fragments I'll use `.config`.

If adopted, we'd have these project names;

```
$ tree -P '*.project' --prune -L 1
.
├── cabal.bootstrap.project
├── cabal.meta.project
├── cabal.project
├── cabal.release.project
├── cabal.validate-libonly.project
└── cabal.validate.project

1 directory, 6 files
```

**Comment by TeofilC** [comment]
Related issue: https://github.com/input-output-hk/haskell.nix/issues/2144

It's helpful to have a common suffix to enable filtering for just `cabal.project` and imported files.
I imagine this would also be helpful for .gitignores and file highlighting.
