### ISSUE TITLE
cabal-install 0.14: generated Paths_*.hs assumes extensible exceptions

### ISSUE THREAD

**Issue by geekosaur** [haskell/cabal#994]
This was just reported in `#xmonad`:  a user on Gentoo with the default Haskell mask (hence getting GHC 6.12.2) was unable to build xmonad because the Cabal-generated `Paths_xmonad.hs` was generated with what appears to be an assumption of extensible exceptions (or, maybe it's going back *too* far, given the "`Exception.`" qualifier, and using some ancient H98 exception code?).

    [ 8 of 10] Compiling Paths_xmonad     ( dist/build/autogen/Paths_xmonad.hs, dist/build/xmonad/xmonad-tmp/Paths_xmonad.o )
    
    dist/build/autogen/Paths_xmonad.hs:11:10:
        Couldn't match expected type `Exception.IOException'
               against inferred type `Exception.Exception'
          Expected type: Exception.IOException -> IO a
          Inferred type: Exception.Exception -> IO a
        In the expression: Exception.catch
        In the definition of `catchIO': catchIO = Exception.catch

**Comment by ttuegel** [comment]
Does this issue affect `GHC >= 7.2`?

**Comment by 23Skidoo** [comment]
I tried to reproduce this with GHC 6.12.1 and the module actually compiled. I guess it was picking `base-3` for some reason.

**Comment by 23Skidoo** [comment]
Heh, yes:

```
~/bin/ghc-6.12.1/bin/ghc -package base-3.0.3.2 -c Paths_Cabal.hs

Paths_Cabal.hs:13:10:
    Couldn't match expected type `Exception.IOException'
           against inferred type `Exception.Exception'
      Expected type: Exception.IOException -> IO a
      Inferred type: Exception.Exception -> IO a
    In the expression: Exception.catch
    In the definition of `catchIO': catchIO = Exception.catch
```

**Comment by 23Skidoo** [comment]
So it looks like we can use CPP in the `Paths_` file. The fix is therefore simple: #2552.

@ttuegel It doesn't, but it'd be nice if `cabal-install`s compiled with new GHC would continue to work with older GHCs.

**Comment by ttuegel** [comment]
@23Skidoo I agree, I would like us to maintain compatibility with older GHC versions. Because of concerns about breaking the `Paths_` module, do we want to consider (instead of using CPP), writing just different modules depending on the GHC version?

**Comment by 23Skidoo** [comment]
@ttuegel Well, the problem is that 6.12 comes with both `base-3` and `base-4`, so we're kinda forced to use CPP if we want to continue supporting it.

**Comment by 23Skidoo** [comment]
Re: breaking the `Paths_` file - I believe that my change should safe. It even supports the case when `cabal_macros.h` is not `#include`d for some reason:

```
#if defined(VERSION_base)

#if MIN_VERSION_base(4,0,0)
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#else
catchIO :: IO a -> (Exception.Exception -> IO a) -> IO a
#endif

#else
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#endif
```

**Comment by ttuegel** [comment]
I think that's fine, then!
