### ISSUE TITLE
Documentation for -fdeveloper

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/cabal#9962]
The text package uses the cabal flag `-fdeveloper` in 

https://github.com/haskell/text/blame/f4c2b7ebf3443c0e5ee23a15c6409ac8c83d8b49/.github/workflows/developer-flag.yml#L32

and @Lysxia recommended using it

https://github.com/haskell/text/pull/590#issuecomment-2084696589

It also seems to work as a flag when I run `cabal build -fdeveloper`.

I cannot find anything documenting this flag nor can I find it in the repo code. Is this an actual cabal flag? If so, where can I figure out how it works?

**Comment by Lysxia** [comment]
It's a flag defined in `text.cabal`.

**Comment by BebeSparkelSparkel** [comment]
@Lysxia thanks
