### ISSUE TITLE
Split off `cabal get` command

### ISSUE THREAD

**Issue by sheaf** [haskell/cabal#9994]
I suggest that the `cabal get` command should be split off into a separate library from `cabal-install`.

The main justification for this is bootstrapping. Currently, we rely on a `bootstrap.py` script to bootstrap `cabal-install`, but it doesn't handle a lot of the complexity that `cabal get` does when fetching packages, such as configuration of remote repositories, pinning index state, etc.

Ideally, when bootstrapping, we would:

  - compute bootstrap plans ahead of time using the solver built-in to `cabal-install` as we do now, or – even better – separately invoke the solver,
  - fetch the required packages using this separate `cabal get` command,
  - execute the build plan (much as we do now).

**Comment by ffaf1** [comment]
How would we bootstrap `cabal get` then?

**Comment by sheaf** [comment]
> How would we bootstrap `cabal get` then?

Good point. I suppose it depends on how self-contained it can be made to be, but I suppose this means the idea in this ticket wouldn't move things forward much.

**Comment by philderbeast** [comment]
I was considering using `cabal get` to [bootstrap Updo](https://github.com/cabalism/updo#getting-started) but went with curl from hackage instead, from `${HACKAGE}/updo-${UPDO_VERSION}/updo-${UPDO_VERSION}.tar.gz`.

**Comment by andreabedini** [comment]
> it doesn't handle a lot of the complexity that cabal get does when fetching packages, such as configuration of remote repositories, pinning index state, etc.

All the complexity you mention here is pre-planning. Once the planning is done, fetching the packages and their revisions is trivial.
